### ISSUE TITLE
Unable to create Admin user

### ISSUE THREAD

**Issue by Rouzax** [janeczku/calibre-web#1]
Just stumbled upon your fork of this project. 
What is the reason you decided to fork it, if I may ask?

When I start the cps.py I never get the option to create a admin user.

**Comment by janeczku** [comment]
@Rouzax The purpose of the fork is to make it play nicely in a Docker container. You may read more about the Docker image i created here: https://github.com/janeczku/docker-calibre-web 
The most important changes in the code:
* Admin user is created automatically with a default password which may be changed in the Web UI
* Mail server can now be configured in the Web UI (no need to edit config.ini manually)
* Some minor bug fixes of the original code

To answer your original question: Just log in with user admin and password "admin123".

**Comment by Rouzax** [comment]
Ok, will that be the only difference or are you also looking to extend the features?
For example:
* Enable user to register
* More send to email capabilities
* database backend

**Comment by janeczku** [comment]
@Rouzax 
Enable user to register: Not doing it (admin can already create as many users as he wishes)
More send to email capabilities: What exactly do you mean by that? Multiple Send-To email addresses per User?
Database backend: You mean something other than sqlite database? What database do you need?

**Comment by Rouzax** [comment]
It would be nice if I could give my friends the link and let them register, the admin would have the final approval.
I believe there is only an option to send to kindle for email. One other thing might be a weekly new books added newsletter.
Sorry I didn't see that there was a sqlite backend. I thought everything was created as needed from the calibre backend, like covers and description.

**Comment by janeczku** [comment]
Added public user registration in 0f7c1294956682c243b9d3113326b7b3c0841136
To enable, edit config.ini and set PUBLIC_REG to 1.
/cc @Rouzax

**Comment by Rouzax** [comment]
Thanks will give it a try.

**Comment by Rouzax** [comment]
Would it be very hard to have the admin approve the user after registration?

**Comment by janeczku** [comment]
Why not try to do it yourself: You need to add an additional field to the user DB schema (e.g. "approved" type bool) and then let the admin change that value. PR is welcome!

**Comment by Rouzax** [comment]
@janeczku, I really would if I could :cry: unfortunately I don't have the coding skill to pull that off.
