### ISSUE TITLE
Add opds support for kobo / koreader

### ISSUE THREAD

**Issue by vincowl** [janeczku/calibre-web#1000]
Kobo readers have removed access to opds. Therefore you need to install an alternative firmware. One of the most known is koreader who has an access to define customed opds catalogs. But calibre-web's one is simply not found.

It would be great to provide a way to access to calibre-web's opds catalog  on kobo readers !

**Comment by FrouxBY** [comment]
Hi,
maybe it's an issue with your setup,
I can perfectly access to my calibre-web opds from koreader on a kobo,
with the url https://domain.tld/opds and my local account credentials
i'm running calibre-web with docker and an nginx proxy

**Comment by vincowl** [comment]
I just totally forgot to close this issue since I solved it. It was a syntax error : I need to set it up to `https://www.mydomain.com/opds/`. The last `/` is mandatory here...
