### ISSUE TITLE
public shelves disappeared

### ISSUE THREAD

**Issue by izenn** [janeczku/calibre-web#1002]
After updating from 3eae2e9 to 4be5528 my public shelves disappeared from anonymous browsing

**Comment by izenn** [comment]
it doesn't look like the upgrade caused the problem.  I'm rolling back some python updates to see if that caused the issue.  i'll update once i know more

**Comment by OzzieIsaacs** [comment]
Okay

**Comment by izenn** [comment]
i rolled back all the python modules (basically i was just going through the requirements.txt and installing the missing ones)  the only other thing i did this morning was create a new public shelf.

Here is the server debug log
```
[2019-08-06 14:02:34,670] DEBUG {cps.comic:34} cannot import comicapi, extracting comic metadata will not work: No module named 'comicapi'
[2019-08-06 14:02:34,763] DEBUG {cps.cache_buster:43} Computing cache-busting values...
[2019-08-06 14:02:34,788] DEBUG {cps.cache_buster:56} Finished computing cache-busting values
[2019-08-06 14:02:34,788]  INFO {cps:89} Starting Calibre Web...
[2019-08-06 14:02:34,813]  INFO {cps.server:149} Starting Tornado server on :8083
```
What else can i look at/do to troubleshoot?

**Comment by izenn** [comment]
update: i started with a completely new git-pull in a new folder and i still don't have any public shelves showing up for the guest user

python versions:
```
python 3.7.4
python-babel 2.7.0-1
python-flask 1.0.3-1
python-flask-babel 0.12.2-1
python-flask-login 0.4.1-2
python-flask-principal 0.4.0-1
python-pypdf2 1.26.0-1
python-pytz 2019.2-1
python-requests 2.22.0-1
python-sqlalchemy 1.3.6-1
python-tornado 6.0.3-1
python-unidecode 1.1.1-1
python-wand 0.5.6-1
```

**Comment by izenn** [comment]
looks like commit 2a5f2ff7b344fdc6aec2e128fab2e93719cc49dd introduced the public shelf issue (i've been stepping through the commits one by one from an old known good version and this update broke it)

**Comment by OzzieIsaacs** [comment]
The problem should be fixed no, thanks to @W1ndst0rm

**Comment by wgibcus** [comment]
Looks like this issue has raised its head again in Beta 0.6.9 Beta - 843279bacb9ab40888d137dd69f8f688a1c920b2 - 2020-08-23T21:22:44+02:00

**Comment by OzzieIsaacs** [comment]
It's back for a longer time, one of the core maintainers fiddled around in the code because of issue #1448
