### ISSUE TITLE
Location of Calibre database

### ISSUE THREAD

**Issue by ashish-kerketta** [janeczku/calibre-web#1003]
How to setup Location of Calibre database in mac and ubuntu.

**Comment by OzzieIsaacs** [comment]
Like described here: https://github.com/janeczku/calibre-web/wiki/Configuration#basic-configuration

**Comment by MaximeStl** [comment]
In Settings/Basic configuration
![image](https://user-images.githubusercontent.com/40502885/63424018-d0e81380-c40d-11e9-92df-8d47e37b6e97.png)

**Comment by OzzieIsaacs** [comment]
I hope the answers helped, I'll close the issue.
