### ISSUE TITLE
 SSL_ERROR_RX_RECORD_TOO_LONG after latest commit

### ISSUE THREAD

**Issue by ajbergh** [janeczku/calibre-web#1004]
After upgrading from 7/30 commit to 8/7 commit, SSL no longer functions with  SSL_ERROR_RX_RECORD_TOO_LONG error in firefox. Internet Explorer has this error: "This might be because the site uses outdated or unsafe TLS security settings. If this keeps happening, try contacting the website’s owner.

Your TLS security settings aren’t set to the defaults, which could also be causing this error."

Any ideas on how to resolve? Using Technosoft2000 docker image.

**Comment by OzzieIsaacs** [comment]
I doublechecked it with a "normal" calibre-web installation.Everything is working fine:
![grafik](https://user-images.githubusercontent.com/6438895/63215594-28923080-c129-11e9-8a7f-9332f34ddf51.png)
The reason might be your certificate?

**Comment by OzzieIsaacs** [comment]
I'm using the following certificate files for testing purposes:
https://github.com/OzzieIsaacs/calibre-web-test/tree/master/test/SSL
I check it with tornado 5.1 on python2 tornado 6.02 on python3 and also with gevent as server

**Comment by OzzieIsaacs** [comment]
No response for long time
