### ISSUE TITLE
Mark as read not working

### ISSUE THREAD

**Issue by Supergamer1337** [janeczku/calibre-web#1009]
If I try to mark a book as read on CalibreWeb, it does not disappear from the "unread" section, and does not appear in the "read" section.

Have I done something wrong, or is this a bug?

**Comment by OzzieIsaacs** [comment]
Depending on the version you are using, you might suffer from this bug: #971

**Comment by Supergamer1337** [comment]
That's probably the case then, since I'm also running ver. 0.6.5

**Comment by pdf** [comment]
@OzzieIsaacs I also see this behaviour on latest master - no books under `Read`, all books show up under `Unread`, regardless of the status of the flag (viewing individual books shows the read status correctly).  No errors or other useful information in the logs (with DEBUG enabled), `app.db` contains `book_read_link` table, with data populated.

Linux, pulled from git, latest commit, `Link read/unread status to Calibre column` empty, `Regular expression for ignoring columns` empty.

**Comment by OzzieIsaacs** [comment]
Okay, but that's something different than the initial  issue claims (it was about not working read status with linked calibre column). To my shame I didn't try using it with not linked column and indeed isn't working anymore....

**Comment by OzzieIsaacs** [comment]
Please try the newest commit. It should now work again.

**Comment by pdf** [comment]
Working now, thank you! I posted against this issue rather than #971 as this one specifically doesn't mention using the custom column.

**Comment by Nosirus** [comment]
I created a "Read" column on Calibre

lookup name = read
column heading = Read
Column type = Yes/No

the modifications I make in calibre work well in calibre-web but not the other way around

did I miss something?
