### ISSUE TITLE
Can't successfully use 'Public Shelves'

### ISSUE THREAD

**Issue by udo1toni** [janeczku/calibre-web#101]
As far as I understand, if I want to use a bookshelf as a public one, the only thing to do would be to check 'should the shelf be pubic?', but no luck...
1. the bookshelf appears at "Your Shelves", not at "Public Shelves"
2. I can't put any bookt at the shelf, because it doesn't appear in the drop down list.

I did the installation through git at January, 29th.

Do I have to do something special?

**Comment by OzzieIsaacs** [comment]
please do a update to newest commit, should work now

**Comment by udo1toni** [comment]
:) Thanks, now works as expected.
