### ISSUE TITLE
Need help to configure a local PostFix server for the SMTP e-mail server

### ISSUE THREAD

**Issue by MaximeStl** [janeczku/calibre-web#1011]
Hello,
I'm trying to configure a local smtp server with PostFix but it doesn't work.
SMTP with Gmail work fine but I don't want to use it.
![image](https://user-images.githubusercontent.com/40502885/63158159-ed084100-c018-11e9-96ae-2eee9c19a7de.png)

For the SMTP hostname I try : 
-localhost
-my local ip
-mydomain.tld

It doesn't work.

Do you have an exemple of basic configuration ?

**Comment by OzzieIsaacs** [comment]
I'm doing testing of the project with a local smtp server. There I'm using the ip-adress 127.0.0.1, and this was working perfectly.
Could you please set the loglevel to debug, (restart calibre-web) and try to send a test email and check the output in the calibre-web.log afterwards? (pleas post it and remove any confidential part especially the password (even if it's hashed)

**Comment by MaximeStl** [comment]
Here the logs : 
[2019-08-16 11:39:28,877]  INFO {cps.server:179} Performing restart of Calibre-Web
[2019-08-16 11:39:30,420]  INFO {cps:89} Starting Calibre Web...
[2019-08-16 11:39:30,544]  INFO {cps.server:149} Starting Tornado server on :8083
[2019-08-16 11:39:53,911] ERROR {cps.worker:522} Error sending email: SMTP AUTH extension not supported by server.

With this conf : 
![image](https://user-images.githubusercontent.com/40502885/63159130-14600d80-c01b-11e9-82f1-2634e292a9f7.png)

**Comment by OzzieIsaacs** [comment]
Problem is not on calibre-web side (well almost not). Calibre-web doesn't support unauthenticated smtp transfer. It looks like from the screenshot that's also not what you want. But your server looks like it's not configured for using e-mail authentication (https://en.wikipedia.org/wiki/SMTP_Authentication). Therefore you get the message "SMTP AUTH extension not supported by server". Could you please check your postfix configuration if authentication is enabled, google suggests this one: https://www.digitalocean.com/community/questions/enable-authentication-on-postfix (I personally never used or configured postfix, so I can only deliver a limited support)

**Comment by OzzieIsaacs** [comment]
You could try to use telnet to debug the postfix connection, when it's working "localhost" should work also as hostname

**Comment by MaximeStl** [comment]
Finaly, i used this and configure postfix correctly : 
![image](https://user-images.githubusercontent.com/40502885/63419227-ac3b6e00-c404-11e9-83cf-04c26c547683.png)


Thanks for your help !!
