### ISSUE TITLE
[Raspi] Goodreads not installed

### ISSUE THREAD

**Issue by RPSouto** [janeczku/calibre-web#1016]
After installation of API Goodreads, Calibre-Web keeps showing as "Not Installed".

Any help?

**Comment by OzzieIsaacs** [comment]
It's working now again on python 2.

**Comment by RPSouto** [comment]
Thank you for your help. Meanwhile, after pulling all the changes:

 'goodreads': bool(services.goodreads_support)
AttributeError: 'module' object has no attribute 'goodreads_support'

**Comment by OzzieIsaacs** [comment]
For me it was working, I found another problem and renamed one variable, maybe it's now working on your pi.

**Comment by RPSouto** [comment]
Thank you for your help. With the new commit is working again.

**Comment by RPSouto** [comment]
Still persists: 

Goodreads | not installed

Google Drive ,Flask_SimpleLDAP etc works with no problem.

Any help?

Thank You

**Comment by RPSouto** [comment]
Workaround:
Had to remove goodreads.pyc from cps/services/
Changed:

from goodreads.client import GoodreadsClient 

to 

from goodreads import client

The option to enter the key and secret appears, goodreads is recognized and authors information appears

**Comment by OzzieIsaacs** [comment]
Can't reproduce this with the newwest commit on raspberry pi zero, debian buster, python 2.
![grafik](https://user-images.githubusercontent.com/6438895/70861926-23a58800-1f35-11ea-92b6-06cc7f38a23c.png)
![grafik](https://user-images.githubusercontent.com/6438895/70861930-315b0d80-1f35-11ea-9bde-a9c9c0bc6bd8.png)

**Comment by Oreolek** [comment]
had the same problem, removing goodreads.pyc from cps/services/ helped.
