### ISSUE TITLE
Audiobooks available on Docker yet?

### ISSUE THREAD

**Issue by jacobmix** [janeczku/calibre-web#1024]
Right now i'm on the latest version from "linuxserver/calibre-web" so 0.6.4
I saw that here https://github.com/janeczku/calibre-web/pull/634 that audiobook support should be on master, but is part of the progress towards v0.7.0?
Is there a beta version for Docker or something? I'd like to test my audiobooks.

**Comment by OzzieIsaacs** [comment]
You could use the technosoft2000 container, as far
as I know it pulls on every start the newest commit from the master branch.
From linuxserver there is no beta version as far as I know.
I‘m not the maintainer of both projects, and I‘m not using them for, so I don‘t have any insight knowledge

**Comment by jacobmix** [comment]
Thanks. Seem to be working. Doesn't save your spot if you leave, but still pretty cool.
