### ISSUE TITLE
How to change the Listen Port to 8085

### ISSUE THREAD

**Issue by petrukngantuk** [janeczku/calibre-web#1025]
Please Anyone guide me to change the Listen Port,

I Try to modified `cps/constants.py` to :
`DEFAULT_PORT = 8085`

not working

trying using export CALIBRE_PORT=8085
not working
![Screenshot_288](https://user-images.githubusercontent.com/4683704/63669534-7a5f4880-c804-11e9-8c62-17feb238ec11.png)

anyone can help

**Comment by petrukngantuk** [comment]
@janeczku please help sir

**Comment by OzzieIsaacs** [comment]
Both settings are only applicable for the first run, so either you delete your app.db, or easier version: start calibre-web, go to the admin section, basic setup and change the port.

**Comment by OzzieIsaacs** [comment]
If your problem is solved, please close this issue
