### ISSUE TITLE
Traefik as a reverse proxy doesn't redirect correctly with path

### ISSUE THREAD

**Issue by MephistoXoL** [janeczku/calibre-web#1031]
I have Docker containers with calibre-web (v0.6.4) and Traefik (v1.7.14), configured a traefik label to do the redirection to container calibre-web via path:
`traefik.frontend.rule=Host:domainexample.duckdns.org; PathPrefixStrip:/calibre/`
If I do the config to a subdomain without path works fine.
I've tried severals Traefik labels, but any works. for example:
```
traefik.frontend.passHostHeader=true
traefik.frontend.headers.hostsProxyHeaders=true
traefik.frontend.headers.customRequestHeaders=X-Script-Name:/calibre/
traefik.frontend.headers.STSIncludeSubdomains=true
```
Similar issue: 
https://stackoverflow.com/questions/54954958/traefik-not-routing-to-static-resources-within-a-docker-backend

Ideas¿?

Thanks

**Comment by OzzieIsaacs** [comment]
Not really an answer to your question, but in 2.0.0 I got it working with this:
traefik.toml:
```
[log]
  level = "DEBUG"
  filePath = "log-file.log"

[accessLog]
  filePath =  "log-access.log"
  bufferingSize =  100

[providers]
  [providers.file]
    filename = "traefik-dynamic.toml"

[api]
  dashboard = true
  debug = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
```
traefik-dynamic.toml:

```
[http]
    [http.middlewares]
      [http.middlewares.testHeader.headers]
        [http.middlewares.testHeader.headers.customRequestHeaders]
            X-Script-Name = "/cw"
      [http.middlewares.test-stripprefixregex.stripPrefixRegex]
            regex = ["/cw"]

    [http.routers]
       [http.routers.my-router]
          rule = "(Host(`127.0.0.1`) && PathPrefix(`/cw`))"
          service = "phx"
          entryPoints = ["web"]
          middlewares = ["test-stripprefixregex","testHeader"]
    [http.services]
          [http.services.phx.loadbalancer]
            [[http.services.phx.loadbalancer.servers]]
              url = "http://127.0.0.1:8083"
```
From my understanding this is working for 127.0.0.1 for localhost ip-adress and servername you have to extend the hosts rule (or generate additional routers?)

**Comment by OzzieIsaacs** [comment]
I did not use docker, so it's "plain" traefik with "plain" calibre-web (current master). Python3.7 and Linux Mint

**Comment by OzzieIsaacs** [comment]
If you use a script name with  a trailing slash, the resulting links in the calibre-web html files will look like "/calibre//books...".  (with double slash in it, apache can deal with it, but e.g. nginix has problems with it, the example in the wiki explicitly states NO slash at the end)

**Comment by OzzieIsaacs** [comment]
I added my example to the wiki. I hope you get it working. I also hope you understand that supporting calibre-web is my main goal and not reverse proxy configuration issues.
Thanks for your understanding.
