### ISSUE TITLE
New to the whole github deal and having problems installing

### ISSUE THREAD

**Issue by ahhmong** [janeczku/calibre-web#1032]
Hi, I have followed the instructions on how to install however, when I run the batch file it gives me this error:

> Can't read file cps/translations/iso639.pickle: the STRING opcode argument must be quoted

Sorry if this is a dumb question but I could not find a solution. I did however run into a dos2unix conversion(?) that I have no idea to use.

Thank you for reading.

**Comment by OzzieIsaacs** [comment]
https://github.com/janeczku/calibre-web/wiki/FAQ#error-on-startup-the-string-opcode-argument-must-be-quoted
