### ISSUE TITLE
Book covers not scaling after update - messy page

### ISSUE THREAD

**Issue by Flo-63** [janeczku/calibre-web#1033]
After updating on nightly channel, covers are not scaled anymore which renders the page unusable. 
![calibre-messypage](https://user-images.githubusercontent.com/6236477/64076439-4c2aae80-ccc5-11e9-8869-c667033105be.png)
Any idea what went wrong?

**Comment by OzzieIsaacs** [comment]
looks like you are missing a js or css file. could you please open a developer console (str+d on firefox) reload the page again and check for some 404 errors? if you post the output here I can help you where to look for the missing files on your harddrive

**Comment by Flo-63** [comment]
These are the errors I see in Chrome:
![image](https://user-images.githubusercontent.com/6236477/64077236-851b5100-ccce-11e9-8cb3-25c9ea3826ce.png)

**Comment by OzzieIsaacs** [comment]
You are have the same problem as #999. Could you please try to Update flask and flas login as sugested  there.

**Comment by Flo-63** [comment]
I updated to python3-flask to 0.12.1-1 and python3-flask-login 0.4.0-1 on Debian 4.9.144-3.1 - does not resolve the error.

**Comment by OzzieIsaacs** [comment]
I think the newest version of flask is 1.1.1. Please try updating to a newer version via pip

**Comment by Flo-63** [comment]
Yes, this worked-many thanks!!

For the files and the ones not familiar with pip:
To update flask and flask login:
1. Stop Calibre-Web Service 
2. Update packages: 
pip install --upgrade flask
pip install --upgrade flask-login
3. Start Calibre-Web Service
