### ISSUE TITLE
Calibre Companion /opds bug

### ISSUE THREAD

**Issue by balazshasprai** [janeczku/calibre-web#1034]
Calibre Companion can't get the metadata.  
It can't get the books on the 'home screen'.  
You can search for books and that does work, but download and metadata download doesn't.  
Directly connected to calibre-web, no SSL.

**Comment by OzzieIsaacs** [comment]
totally broken

**Comment by OzzieIsaacs** [comment]
Everything should now work again, please try the newest commit
