### ISSUE TITLE
No "Use Google Drive?" option on config page

### ISSUE THREAD

**Issue by philipatc** [janeczku/calibre-web#1035]
I've follow the instruction for using google drive intergation on wiki, and download and rename the client_secrets.json and put it to calibre-web folder, however, when I go to config page, there is no "Using Google Drive?" option there. is that any way to trigger this option?

and some more question : 
I'm using other PC to maintenance the calibre library and the metadata.db is stored on google drive. How can I config the calibre database location?

Thanks for help

**Comment by OzzieIsaacs** [comment]
You need to install the following depencies from the optional-dependecies.txt file:
```
# GDrive Integration
google-api-python-client==1.7.11
gevent==1.2.1
greenlet==0.4.12
httplib2==0.9.2
oauth2client==4.0.0
uritemplate==3.0.0
pyasn1-modules==0.0.8
pyasn1==0.1.9
PyDrive==1.3.1
PyYAML==3.12
rsa==3.4.2
six==1.10.0
```
Afterwards the option should appear.
If you've configured the google drive setting you get a single-select Combo-Box where you can select the folder where the metadata.db exisits (it displays all folders and you have to select the right one).

**Comment by vv47424** [comment]
i have a same problem

i use this code to install
"pip install --target vendor -r optional-requirements.txt"
cant install it has error
"ERROR: Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/OzzieIsaacs/comicapi.git 'C:\Users\WATCHA~1\AppData\Local\Temp\pip-install-p6lubccu\comicapi'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?"

but when i use this code to install
"pip install --target vendor -r requirements.txt"
can install and used but no option of google drive

thanks

**Comment by OzzieIsaacs** [comment]
Please delete all lines from the file optional-requirements.txt except the above mentioned and it will work, or please install "git" and put it to the path variable

**Comment by Valek626** [comment]
Hi there, I installed the same Python version that I saw in the help, Git 2.23.0 for windows and Microsoft Visual C++ Build Tools as requested, but I receive this error:

Running setup.py install for greenlet ... error
    Complete output from command "c:\program files\python37\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\valer\\AppData\\Local\\Temp\\pip-install-lamrv6f4\\greenlet\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\valer\AppData\Local\Temp\pip-record-am12n_2h\install-record.txt --single-version-externally-managed --compile --home=C:\Users\valer\AppData\Local\Temp\pip-target-v5ajrn69:
    running install
    running build
    running build_ext
    building 'greenlet' extension
    creating build
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.23.28105\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT "-Ic:\program files\python37\include" "-Ic:\program files\python37\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.23.28105\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcgreenlet.c /Fobuild\temp.win-amd64-3.7\Release\greenlet.obj
    greenlet.c
    greenlet.c(463): error C2039: 'exc_type': non Š un membro di '_ts'
    c:\program files\python37\include\pystate.h(212): note: vedere la dichiarazione di '_ts'
    greenlet.c(464): error C2039: 'exc_value': non Š un membro di '_ts'
    c:\program files\python37\include\pystate.h(212): note: vedere la dichiarazione di '_ts'
    greenlet.c(465): error C2039: 'exc_traceback': non Š un membro di '_ts'
    c:\program files\python37\include\pystate.h(212): note: vedere la dichiarazione di '_ts'
    greenlet.c(485): error C2039: 'exc_type': non Š un membro di '_ts'
    c:\program files\python37\include\pystate.h(212): note: vedere la dichiarazione di '_ts'
    greenlet.c(487): error C2039: 'exc_value': non Š un membro di '_ts'
    c:\program files\python37\include\pystate.h(212): note: vedere la dichiarazione di '_ts'
    greenlet.c(489): error C2039: 'exc_traceback': non Š un membro di '_ts'
    c:\program files\python37\include\pystate.h(212): note: vedere la dichiarazione di '_ts'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.23.28105\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
Command ""c:\program files\python37\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\valer\\AppData\\Local\\Temp\\pip-install-lamrv6f4\\greenlet\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\valer\AppData\Local\Temp\pip-record-am12n_2h\install-record.txt --single-version-externally-managed --compile --home=C:\Users\valer\AppData\Local\Temp\pip-target-v5ajrn69" failed with error code 1 in C:\Users\valer\AppData\Local\Temp\pip-install-lamrv6f4\greenlet\

what should I do? 
thank you! 
v.

**Comment by Valek626** [comment]
I installed the last version of greenlet without any problem, but I have a similar message with gevent. Someone can help me? :) pleeeeaaase :)

**Comment by OzzieIsaacs** [comment]
Installing gevent on windows was somehow tricky. Installing the whl should work (https://files.pythonhosted.org/packages/a8/5b/b3bdf4f166c70fa58f558b6e84874f377881973010dd9bea2b02138d4161/gevent-1.4.0-cp37-cp37m-win32.whl). With python -m pip install [path-to-whl-file]. 
If not, gevent is not really necessary, so please delete the gevent line in the optional-requirements file and rerun the install command.

**Comment by OzzieIsaacs** [comment]
No feedback on inital post, closing issue
