### ISSUE TITLE
Standard Postfix config doesnt allow mails sent by calibre-web

### ISSUE THREAD

**Issue by InsOpDe** [janeczku/calibre-web#1037]
I opened this issue here
https://github.com/tomav/docker-mailserver/issues/1265
because my mailserver didnt allow smtp-connections because of a faulty `helo`-command of calibre-web.
This is what my mailserver logs:
```
mail    | Sep 16 12:48:56 mail postfix/submission/smtpd[7565]: connect from 84.205.247.35.bc.googleusercontent.com[35.246.205.94]
mail    | Sep 16 12:48:56 mail postfix/submission/smtpd[7326]: lost connection after RSET from 84.205.247.35.bc.googleusercontent.com[35.246.205.94]
mail    | Sep 16 12:48:56 mail postfix/submission/smtpd[7326]: disconnect from 84.205.247.35.bc.googleusercontent.com[35.246.205.94] ehlo=2 starttls=1 auth=1 mail=1 rcpt=0/1 rset=1 commands=6/7
mail    | Sep 16 12:48:56 mail postfix/submission/smtpd[7565]: Anonymous TLS connection established from 84.205.247.35.bc.googleusercontent.com[35.246.205.94]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
mail    | Sep 16 12:48:56 mail postfix/submission/smtpd[7565]: NOQUEUE: reject: RCPT from 84.205.247.35.bc.googleusercontent.com[35.246.205.94]: 501 5.5.2 <600>: Helo command rejected: Invalid name; from=<from@example.com> to=<to@example.com> proto=ESMTP helo=<600>         
```

**Comment by OzzieIsaacs** [comment]
For sending the emails the python standard-lib smtplib is used. The hostname is automatically determined by smtplib. To figure out the problem it would be great to have more information about the invalid name. Was it an IP-adress, internal computer name, or an public accessible domain name?

**Comment by InsOpDe** [comment]
Unfortunately my mailserver didnt log the name. calibre-web didnt log anything of it either.
How could I provide you with the requested information?

**Comment by OzzieIsaacs** [comment]
Was indeed a bug in initializing the smtplib. Now a valid domainname should be send with the helo command (Before it was the timeout setting).
Before:
[2019-09-17 18:20:28,278] DEBUG {cps.worker:125} send: 'ehlo 600\r\n'
After:
`[2019-09-17 18:23:11,138] DEBUG {cps.worker:125} send: 'ehlo [127.0.1.1]\r\n'`

**Comment by euri10** [comment]
just discover this has been fixed, thanks a lot
when you think there will be a release, while i could bake my own docker image I'm lazy and still rely on linuxserver's one :) thanks in advance
