### ISSUE TITLE
Internal Server Error when trying to connect to google drive.

### ISSUE THREAD

**Issue by Hello-User** [janeczku/calibre-web#1038]
I'm using the latest linuxserver.io image. 

Logs:

https://pastebin.com/SeFD3d0u

**Comment by OzzieIsaacs** [comment]
Could you please look for the client_secrets.json file, open it and look for the string: "redirect_uris". I guess it's not in the file. If so, please go to the google developer console and  check step 14 of the configuration guideline in the wiki. Please make sure that something is entered in the field "Authorized redirect URIs"

**Comment by mogsub** [comment]
what if the server is for internal use and it's not facing the internet? What URI should I use?

**Comment by OzzieIsaacs** [comment]
If there is no public connection to the internet, this won't work. Google is requesting a public reconnect address, otherwise it's not possible to use the google drive API (as far as I know).
I'm sorry, I don't create the rules, I only apply them.
