### ISSUE TITLE
Bug: Can not find book file

### ISSUE THREAD

**Issue by febalci** [janeczku/calibre-web#1043]
Some of the added books have book name and author appear, but missing the cover page and when i try to download it says '404 Not Found'.
As i understood, If the author name has non standart character or have a resembling author name, it creates problems. Like:

Sample:
Book Name: Astronomy Book, Author: Dk
Book Name: Mythology Book, Author: Dk Publishing

As it appears on Linux 'Calibre Library' Folders (As Folder Names):
DK:
'The Astronomy Book (5895)'

'Dk Publishing':
'The Mythology Book (5526)'

When i try to download 'The Astronomy Book' it is 404. If i change the author of the book something other than 'Dk', it works...

**Comment by OzzieIsaacs** [comment]
I can't reproduce the problem, for me it works.
The only thing I could imagine is, a mismatch of the stored data in metadata.db and your folder structure. You could try to run a repair library from the calibre desktop program.
