### ISSUE TITLE
Series ID Counts Roll over after 9

### ISSUE THREAD

**Issue by adamsih300u** [janeczku/calibre-web#1044]
When setting series ID with years (useful for magazines), the counter will not go higher than 9.
For instance: 2018.9 will increment to 2019.1; this prevents setting a series ID for months October-December.

Also, it would be nice if a leading zero would be allowed - for example: 2018.08. In some cases this can make for easier sorting.

**Comment by OzzieIsaacs** [comment]
The ID is represented as a "normal" number with 1 decimal. I don't think that calibre can accomplish this the way you want to do it.I'd recommend to use a format like:
201901 to 201912 to represent the IDs(without the dot)

**Comment by OzzieIsaacs** [comment]
meanwhile, you can enter 2 decimals
