### ISSUE TITLE
request: Link to newest books ?

### ISSUE THREAD

**Issue by stfrbrntyu** [janeczku/calibre-web#1045]
Hi

Could you please add a link to newest released books in the left side menu?

Additionally it would be nice to be able to set a certain view as a standard view, now the view "recently added books" is the default, but I prefer to have "new released books" as default.

Strange difference between OPDS en website:
OPDS (/opds) does show "new books" but on the web site it is called recently added books,

Why is this different ?

**Comment by OzzieIsaacs** [comment]
The answer to the last question is very easy: It was that way, since I'm programming in this project. I chanegd it, so it's now in both locations "Recently added [books]"

**Comment by OzzieIsaacs** [comment]
The recently added books menu is renamed to books, you can now sort the books according to your wishes (more or less) and sort order is saved per user base
