### ISSUE TITLE
Googledrive redirect_uri_mismatch error

### ISSUE THREAD

**Issue by mariusst** [janeczku/calibre-web#1046]
Hi 
I'm traying to install my calibre gdrive library on a new ubuntu 18.04 vps. I followed all the steps to enable gdrive but I get an error about the redirect uri

> 400. That’s an error.
> 
> Error: redirect_uri_mismatch
> 
> The redirect URI in the request, http://localhost:8080/, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/[...]
> 
> Learn more
> Request Details
> 
>     scope=https://www.googleapis.com/auth/drive
>     redirect_uri=http://localhost:8080/
>     response_type=code
>     client_id=[...].apps.googleusercontent.com
>     access_type=offline
> 
> That’s all we know.

I have to mention that the error is opened on the server terminal using elinks, the client browser doesn't load anything

**Comment by OzzieIsaacs** [comment]
You need to use a public accessible redirect url.  You have to fulfill the setup with the public address you gave to the "Authorized redirect url" in step 14 in the setup. If you entered "localhost" there, this wont work

**Comment by mariusst** [comment]
I use public url with a domain I own that was verified by google

**Comment by mariusst** [comment]
Calibre-web is on a remote vps accessed through ssh. After I hit python cps.py and access the public adress in firefox  I get the error in links browser on the remote terminal session and firefox just keeps loading

**Comment by OzzieIsaacs** [comment]
I can't reproduce this. I did some changes for the gdrive integration yesterday. For me it works.
