### ISSUE TITLE
"Read in browser" shouldn't be a dropdown when there's a single readable format

### ISSUE THREAD

**Issue by inputsh** [janeczku/calibre-web#1051]
There's an integrated reader for a handful of formats. There are cases in which you'll only have one of those available for a book you want to read. Instead of there being a dropdown with only one available option:

![Screenshot from 2019-09-30 13-43-57@2x](https://user-images.githubusercontent.com/4890548/65875848-68833f00-e388-11e9-84cd-28f20b77f2f0.png)

..."Read in browser" button should just open the only readable format automatically, reducing friction from two clicks to one. The label could possibly be changed to "Read Epub in browser", though I personally consider it unnecessary to specify the format three times in a row (in a screenshot above: "Download Epub", "Convert Epub to Mobi", "Read Epub in browser").

Of course, the dropdown should still be there in case there's more than one readable format:

![Screenshot from 2019-09-30 13-48-55@2x](https://user-images.githubusercontent.com/4890548/65876249-1bec3380-e389-11e9-9c0e-61d2243642cc.png)

This is already in place for the "Send to Kindle" button, since it becomes a dropdown only when multiple formats are available.

I also find it weird that, in the first screenshot, "Download" and "Epub" are two separate buttons, out of which the first one does nothing on click as far as I can tell. They should probably be combined into one "Download (Epub)" button.

**Comment by OzzieIsaacs** [comment]
The feature is meanwhile implemented
