### ISSUE TITLE
Calibre 4.0 Compatibility

### ISSUE THREAD

**Issue by christophwolff** [janeczku/calibre-web#1056]
A new Major Version of Calibre was release today. What about the compatibility with calibre web?

https://calibre-ebook.com/new-in/thirteen

**Comment by OzzieIsaacs** [comment]
I‘m currently away from my pc. I checked the changelist, no Chargers affect the database, so from my Point of view it‘s safe to use Calibre 4.0.
Backup is as usual strongly recommended.

**Comment by blysik** [comment]
I went from calibre 3.x, using a docker with an older X11 gui.  It upgraded to 4.x and stopped working.  I found this project, and used the linuxserver/calibre-web docker with the optional calibre layer.  AFAICT, everything is working amazingly. Great project.

**Comment by magriiiii** [comment]
I updated from 3.x to 4.1 using Windows server. Calibre-Web installed as Windows services. Everything seems to be working fine.

**Comment by OzzieIsaacs** [comment]
I checked it by myself, Calibre-4 doesn't change anything on the database format, so it's safe to use.

**Comment by OzzieIsaacs** [comment]
Found a problem: With calibre 4.x the ebook convert function is no longer working. While converting a book, the converter crashes after the `Applying case-transforming CSS...` line and a "Segmentation fault (core dumped)" (not visible) is generated.
Looks difficult to fix. Currently it's recommended to use calibre 3.xx as highest version if you are using the ebook-converter function

**Comment by OzzieIsaacs** [comment]
New information: It's a problem with my debugger (pyCharm). If starting calibre right from the console calibre-web is able to use calibre 4.x as converter.
@technosoft2000: If calibre 4.x is causing a problem with the docker container, please give me feedback. I'm sorry for the inconvenience.
