### ISSUE TITLE
is IE 11 explorer can view the book? 

### ISSUE THREAD

**Issue by flashliao** [janeczku/calibre-web#1057]
I update the newest calibre-web web server!It can not read the book.It stay loading screen.
![image](https://user-images.githubusercontent.com/28710685/66381148-55f1b100-e9eb-11e9-9bd4-ed27f2fdf7cc.png)
I reamber old version can run IE 11!
I test on visit https://futurepress.github.io/epubjs-reader
it still IE11 Can not read!

**Comment by OzzieIsaacs** [comment]
IE is going to be end of life soon. I will not fix this issue
