### ISSUE TITLE
I can't see my CBR / CBZ

### ISSUE THREAD

**Issue by Gorglob** [janeczku/calibre-web#1062]
hello, 

I do not understand why I do not see the CBR and CBZ files in the web interface while they are present in my database Caliber. Does anyone have an explanation ?

The numbers of files are différent (as you can see on these screenshots ) 

![image](https://user-images.githubusercontent.com/35777839/66723337-30640d80-ee18-11e9-9263-ae7235ee0e8b.png)

![image](https://user-images.githubusercontent.com/35777839/66723344-3eb22980-ee18-11e9-8720-db84621c5cc0.png)

**Comment by OzzieIsaacs** [comment]
I'm guessing you see the covers (of CBR and CBZ files) listed in calibre-web on the "main" screen?
You can download CBR, CBZ, ZIP and RAR files?
But the button view in Browser is not visible for CBR and CBZ?
You doublechecked that the user is allowed to download and view ebooks? 
You tried pdf and epub files and they are working fine in the viewer?
You are running calibre-web on linux? with python 2 and using the version 0.6.4?
You are using the dark interface and also tried the standard theme?
