### ISSUE TITLE
Synology NAS: on upload getting permission denied error

### ISSUE THREAD

**Issue by alokc83** [janeczku/calibre-web#1069]
I am an admin. I have just finished the installation. I am trying to add books and I am getting permission denied error. any pointers for me? 

Thanks a lot for your time.
Alok C

**Comment by OzzieIsaacs** [comment]
You installed via docker or the normal version?
Permission denied normally points to insufficient access rights in the folder where the metadata.db is located.  
Can you rename authors and or book titles in calibre-web?

**Comment by OzzieIsaacs** [comment]
No feedback for long time
