### ISSUE TITLE
Synology and Docker - "DB location is not valid, please enter correct path"

### ISSUE THREAD

**Issue by pantone672** [janeczku/calibre-web#1076]
Hi, 
I'm having trouble having calibre-web run via Docker on my Synology.
I've uploaded all my ebooks and my metadata.db file in a folder volume1/calibre/ebooks.
But inserting this adress (and many expressions close to this one !) has proven unsucessful.
Any ideas how I should proceed ?
Thanks !
<img width="789" alt="screenshot_synology_docker_calibre" src="https://user-images.githubusercontent.com/57294789/68073707-2b4d0b00-fd93-11e9-995b-2e944790d0fb.png">

P.

**Comment by CHBMB** [comment]
Without knowing how you set this up nobody can help `/volume1/calibre/ebooks` sounds like a host location not the docker container mount.  In our readme we recommend using `/books` 

Going to close this as there isn't a bug with the container, rather a support issue.

**Comment by OzzieIsaacs** [comment]
Could you please open an issue at the corresponding docker you are using. Entering the folder only is correct for pointing to the location. So I think this problem is not related to calibre-web itself.
