### ISSUE TITLE
Logging to syslog

### ISSUE THREAD

**Issue by dfn-certling** [janeczku/calibre-web#1078]
We collect log messages in our installation in syslog. Since I didn't find a way to do this with the currently used `RotatingFileHandler` we patch our installation in the following way:

```patch
Index: cps/web.py
===================================================================
--- src/cps/web.py 2019-10-25 14:08:33.727215678 +0000
+++ src-patched/cps/web.py 2019-10-25 14:13:09.179222104 +0000
@@ -23,7 +23,7 @@
 
 import mimetypes
 import logging
-from logging.handlers import RotatingFileHandler
+from logging.handlers import RotatingFileHandler, SysLogHandler
 from flask import (Flask, render_template, request, Response, redirect,
                    url_for, send_from_directory, make_response, g, flash,
                    abort, Markup)
@@ -173,13 +173,19 @@
 app.wsgi_app = ReverseProxied(app.wsgi_app)
 cache_buster.init_cache_busting(app)
 
-formatter = logging.Formatter(
-    "[%(asctime)s] {%(pathname)s:%(lineno)d} %(levelname)s - %(message)s")
-try:
-    file_handler = RotatingFileHandler(config.get_config_logfile(), maxBytes=50000, backupCount=2)
-except IOError:
-    file_handler = RotatingFileHandler(os.path.join(config.get_main_dir, "calibre-web.log"),
-                                       maxBytes=50000, backupCount=2)
+if config.get_config_logfile() == '/dev/log':
+    formatter = logging.Formatter(
+        "<SYSLOGNAME>[%(process)s]: "
+        "{%(pathname)s:%(lineno)d} %(levelname)s - %(message)s")
+    file_handler = SysLogHandler(address='/dev/log', facility='<FACILITY>')
+else:
+    formatter = logging.Formatter(
+        "[%(asctime)s] {%(pathname)s:%(lineno)d} %(levelname)s - %(message)s")
+    try:
+        file_handler = RotatingFileHandler(config.get_config_logfile(), maxBytes=50000, backupCount=2)
+    except IOError:
+        file_handler = RotatingFileHandler(os.path.join(config.get_main_dir, "calibre-web.log"),
+                                           maxBytes=50000, backupCount=2)
     # ToDo: reset logfile value in config class
 file_handler.setFormatter(formatter)
 app.logger.addHandler(file_handler)
```

Would this be interesting for you and worth a pull request? I can clean it up if it's interesting.

`SYSLOGNAME` and `FACILITY` are values specific to our installation so these would have to go into the configuration. Alternatively, one might use a magic value for the logfile name (or something similar) to simply log to stdout and use a systemd service to forward log messages to syslog.

**Comment by OzzieIsaacs** [comment]
Thanks for the offer. 

I think on windows logging to syslog would not be an good idea, because on windows  the syslog equivalent is lesser known and used as on linux, furthermore I think if you log to syslog in the docker container it would be additional effort for the maintainer to extract the logs to make them available for the users.

But using a magic value (i think '/dev/stdout' would be a good one) to log to the stdout seems reasonable. This will obviously not work on windows, but I think that will be okay.

I think this could be available at the end of this weekend.
