### ISSUE TITLE
Use defusedxml for xml parsing

### ISSUE THREAD

**Issue by dfn-certling** [janeczku/calibre-web#1079]
The standard lxml parser is vulnerable to a number of attacks that might result from uploading books in XML-based formats. This can be mitigated by using [defusedxml](https://pypi.org/project/defusedxml/) instead:

```patch
--- src/cps/epub.py 2019-10-25 13:52:08.983127962 +0000
+++ src-patched/cps/epub.py 2019-10-25 14:49:22.115518294 +0000
@@ -18,7 +18,7 @@
 #  along with this program. If not, see <http://www.gnu.org/licenses/>.
 
 import zipfile
-from lxml import etree
+from defusedxml import lxml as etree
 import os
 import uploader
 import isoLanguages

--- src/cps/fb2.py 2019-10-25 13:52:08.983127962 +0000
+++ src-patched/cps/fb2.py 2019-10-25 14:49:22.115518294 +0000
@@ -17,7 +17,7 @@
 #  You should have received a copy of the GNU General Public License
 #  along with this program. If not, see <http://www.gnu.org/licenses/>.
 
-from lxml import etree
+from defusedxml import lxml as etree
 import uploader
```

I can make it into a pull request if you'd like one.

**Comment by OzzieIsaacs** [comment]
I'm aware of the problem, and I wanted to change it also, but the problem is it will break all existing installations (there is a in-program update, and nothing is more annoying than a program which is not running after an update and needs additional installation). The way I could think of would be 
A) 
```
try:
     new import
except import_error:
    old import
```
B) changing the optional_requirements.txt file to point to the changed lib.
C) Please also check if `defusedxml` exports a version info and add the information in the about/stats section.
With this 3 points taken into consideration a PR is very welcome.

**Comment by dfn-certling** [comment]
Starting on this, I just discovered https://github.com/tiran/defusedxml/issues/38. defusedxml.lxml is marked as deprecated and it seems like it will be removed with the next version. Unfortunately it's not quite clear from the issue yet whether lxml's problems have been addressed or whether one has to do that oneself. [defusedxml's README](https://github.com/tiran/defusedxml/blob/master/README.md) still lists lxml as vulnerable. So for the moment it doesn't seem too promising to change this.

**Comment by OzzieIsaacs** [comment]
I reread the defusedxml manual again, and I now think I got it, they are just deprecated the lxml part of it.
![grafik](https://user-images.githubusercontent.com/6438895/81323849-5728b080-9096-11ea-958c-4ca99f24aa77.png)
So migrating to defusedxml would need to migrate to one of the other parsers.  defusedxml.ElementTree looks like the right one. 
I'd be happy merging the change, if you are still interested in migrating and willing to spend more on the project than just changing 2 lines.

**Comment by dfn-certling** [comment]
Thanks for the pointer, I'll have a look at it. I have been using lxml itself in other places as it offers more options than the base ElementTree. Therefore I'm not sure how simple porting would be. But I have to investigate for other projects anyway. Might take a bit.

**Comment by dfn-certling** [comment]
I just put in some time to investigate the status of lxml and verified that it is still vulnerable as stated in defusedxml. defusedxml itself basically implements what the lxml FAQ states as necessary to secure it. From that perspective I don't see why the module is deprecated besides maybe the author not maintaining it.

Nevertheless, I'll have a look at ElementTree and whether it provides enough functionality here.

**Comment by dfn-certling** [comment]
The problem with rewriting to ElementTree is that that only supports a limited set of XPath expressions and namespace handling is a pain. It doesn't support `text()` and `local-name()`. `text()` itself would require to iterate over all children of the current node and collect all text nodes.

I'd suggest to stay with defusedxml for the time being. I will do that with our installation and am happy to prepare a PR along the lines of https://github.com/janeczku/calibre-web/issues/1079#issuecomment-554621148 if you'd like. That seems to be the smallest change that improves the situation. If that turns out to be abandoned, a rewrite is still possible.

**Comment by OzzieIsaacs** [comment]
I think it's fine as it's now. I will not change it
