### ISSUE TITLE
[GDrive] 500 Internal Server Error

### ISSUE THREAD

**Issue by BlutHanfling** [janeczku/calibre-web#1081]
Hi there !

I tried to add GDrive support to my newly installed calibre-web (love this tool btw) following the wiki tutorial. I'm able to generate the client_secrets.json file and pass it to the server. I also successfully go through the step of connecting with a google account, skipping the "not secure app" warning and giving access right to the app.
However, once I clicked "Authorize", I get instantly redirected to my web server on the following page :
URL : https://mydomain/calibre-web/gdrive/callback?code=somecode&scope=https://www.googleapis.com/auth/drive
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Any idea of what I could have done wrong ?
I ran into some issues in creating the json because Google APIs seems to have changed some of its menus since the last commit on your wiki, which makes it difficult to follow.

Thanks in advance !

**Comment by BlutHanfling** [comment]
Hi again,

I've been trying to start from scratch again in order to post a step by step guide on how to reproduce the issue but I'm unable to do so... Now putting the client_secrets.json file in my calibre-web folder produce the server to crash with as sole error `No credential to refresh.`
I think what would help here is an updated guide on what is required and how to create the json with the new Google interface. Not much has changed but enough to leave some dark zones here. 

Moreover, I haven't find yet if Google needs to approve the use of the application. I started to go through the validation process, but it seems a lot of work for something not even mentionned in the calibre-web wiki. 

Anyone who successfully activated Gdrive integration could help ?
Thanks

**Comment by billyprice1** [comment]
Same here 
[2019-11-25 18:38:18,546] ERROR in app: Exception on /admin/config [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/root/calibre-web/cps/web.py", line 461, in inner
    return f(*args, **kwargs)
  File "/root/calibre-web/cps/web.py", line 2821, in configuration
    return configuration_helper(0)
  File "/root/calibre-web/cps/web.py", line 2952, in configuration_helper
    if filedata['web']['redirect_uris'][0].endswith('/'):
KeyError: 'redirect_uris'
::ffff:45.146.6.7 - - [2019-11-25 18:38:18] "POST /admin/config HTTP/1.1" 500 425 0.009030
::ffff:45.146.6.7 - - [2019-11-25 18:38:18] "GET /favicon.ico HTTP/1.1" 200 61966 0.004126

**Comment by BlutHanfling** [comment]
Error looks different than mine though.

Since no response was provided by the contributors of the project, I would strongly recommend anyone going through some similar issue to consider using the command line program **rclone**. It works with drive but also most of the cloud storage providers. Essentially, you it alllows you to mount a drive folder on a server, the same way you would do on your pc.

It isn't perfect, some server (like AWS) seem to deduct the data stored on the remote from your quota but it might help some people until a proper updated tutorial is made.

**Comment by OzzieIsaacs** [comment]
Sorry, the gdrive integration was totally broken. It should with the newest commit work better (hopefully useable)

**Comment by OzzieIsaacs** [comment]
@billyprice1 : This error should now be catched.Your problem might be that the redirect URL isn't included in the client secrets.json file.Please check on google developer console that the redircect uri is entered there, and re download the file.
