### ISSUE TITLE
send to kindle

### ISSUE THREAD

**Issue by dr400** [janeczku/calibre-web#1082]
sorry to jump into that issue again but send to kindle does not work the way it should. Test email is working as expected but send to kindle sends back a negative response : "there was an error when sending the book : the requested book could not be read. Permissions problem ?". This is when sending azw3 book, pdf works as intended !

**Comment by dr400** [comment]
correction ... pdf does not work either ... it is just that it doesn't trigger a permission error. It seems to have sent it (green sentence), whereas nothing is received. Same with MOBI ebooks : green sentence but nothing. AZW3 triggers a red sentence (permission error). Within Calibre application it does work (with PDF and MOBI but not with AZW though)

**Comment by OzzieIsaacs** [comment]
Which version do you use? In the current master branch, send azw, azw3 to kindle is disabled, as amazon does not support it. 
The green sentence means it is queued for sending, the current send status can be viewed in the task section. 
There is currently a bug, if one send request causes an error, every task afterwards is not excecuted. A restart of the app should solve this. It's essential for fixing the bug to have the logfile of the relevant error, please provide it, and please tell me if you are using a docker container or not.

**Comment by OzzieIsaacs** [comment]
There is an issue while converting files with calibre version 4.xx, this could maybe your problem (or at least part of it)

**Comment by OzzieIsaacs** [comment]
Found out that the calibre 4.x problem was caused by my debugger.

**Comment by OzzieIsaacs** [comment]
No reply for long time

**Comment by Milchdealer** [comment]
I have the same problem. The file does exist though. I'm running in docker with technosoft2000's image.

I ssh'd onto the container:
```sh
$tail calibre-web.log -n 2                                             
[2021-02-25 17:36:03,743] ERROR {cps.tasks.mail:228} [Errno 2] No such file or d
irectory: '/books/Graeber, David/Bullshit Jobs (39)/Bullshit Jobs - Graeber, Dav
id/Bullshit Jobs - Graeber, David.mobi'                                         
[2021-02-25 17:36:03,744] ERROR {cps.tasks.mail:229} The requested file could no
t be read. Maybe wrong permissions?
$pwd                                                                   
/books/Graeber, David/Bullshit Jobs (39)
$ls                                                                    
'Bullshit Jobs - Graeber, David.azw3'  'Bullshit Jobs - Graeber, David.pdf'     
'Bullshit Jobs - Graeber, David.epub'   cover.jpg                               
'Bullshit Jobs - Graeber, David.mobi'   metadata.opf
```
