### ISSUE TITLE
Hi, please add search by extension. Thx

### ISSUE THREAD

**Issue by marcoryba** [janeczku/calibre-web#1083]

**Comment by BlutHanfling** [comment]
As a workaround, you could select and tag all your books for your different extensions directly from Calibre. Then use the advanced Search module in calibre web, with the extension tag as filter.

Of course, this will require you to do this operation again from time to time but seems a good way to achieve your goal until this is developed.

**Comment by marcoryba** [comment]
Yes, it is also an option. Thx

**Comment by OzzieIsaacs** [comment]
Filtering by extension is already present:

![grafik](https://user-images.githubusercontent.com/6438895/70860654-82163a80-1f24-11ea-97ce-cd348845a670.png)

**Comment by OzzieIsaacs** [comment]
Feature implemented
