### ISSUE TITLE
Ebook converter

### ISSUE THREAD

**Issue by Beryllium30** [janeczku/calibre-web#1090]
Dear all 

Since I switched to unraid I am having issues to get the ebook converter to run. 

I get the error **excecution permissions missing** 

Currently I tried to chmod 777 and chown nobody:users the folder. (I basically just copied the calibre docker folder into a folder Calibre web can access. 

I tried playing around with differen UID and PGUID, but to now avail. Am I missing something essential?

The log gives me following error:
errno 13 permission denied

I would be thankful about all help!

**Comment by OzzieIsaacs** [comment]
I'm sorry, I don't use unraid. 
From calibre-web the calibre-ebook converter is called by a simple " subprocess.Popen" command. If this command returns a permission error, this is reported. 
Maybe for security reasons the server doesn't allow to call other processes from within a web server?

**Comment by xxzj990** [comment]
same err

**Comment by xxzj990** [comment]
> Dear all
> 
> Since I switched to unraid I am having issues to get the ebook converter to run.
> 
> I get the error **excecution permissions missing**
> 
> Currently I tried to chmod 777 and chown nobody:users the folder. (I basically just copied the calibre docker folder into a folder Calibre web can access.
> 
> I tried playing around with differen UID and PGUID, but to now avail. Am I missing something essential?
> 
> The log gives me following error: errno 13 permission denied
> 
> I would be thankful about all help!

This docker image worked:

`https://hub.docker.com/r/technosoft2000/calibre-web`

You can try~
