### ISSUE TITLE
[Enhancement] Add Dropbox as Storageprovider

### ISSUE THREAD

**Issue by borouj-rashid-UOIT** [janeczku/calibre-web#1091]

**Comment by OzzieIsaacs** [comment]
? I don't understand what you want. 
Could you please try to describe your request a little bit?

**Comment by borouj-rashid-UOIT** [comment]
> ? I don't understand what you want.
> Could you please try to describe your request a little bit?

oh, i want to do the google drive integration, except without using google drive

**Comment by borouj-rashid-UOIT** [comment]
i want my library to be on my dropbox instead

**Comment by OzzieIsaacs** [comment]
I decided to not add any storageproviders anymore.
 I'd like to focus more on the core functionality of Calibre-Web.
