### ISSUE TITLE
read-in-browser not working for EPUB unless download-role is true

### ISSUE THREAD

**Issue by halfbeep** [janeczku/calibre-web#1095]
this bug occurs with ebub, pdf reads okay 
warning generated and read in browser hangs unless user is permitted to download to 
WARNING:tornado.access:403 GET /download/378/epub/file.epub  
I thinks it's either sockets or admin rights related
tried both themes std and blur

**Comment by halfbeep** [comment]
i am investigating and close to fixing this, it appears that the app.route function is not called correctly for EPUB reads

**Comment by halfbeep** [comment]
fixed by removing the following line numbers:-
l2234 2206
@download_required
the download required test should not be applied for the creation of the link - especially when it's for an internal web-socket connection

**Comment by OzzieIsaacs** [comment]
Yes you are right it was a bug. I fixed it in the newest commit. 
While separating download and viewer role I forgot to point the epub reader to the new endpoint
