### ISSUE TITLE
Hello I have some problem when i upload my books.

### ISSUE THREAD

**Issue by nanjolono** [janeczku/calibre-web#1102]
Hello, There is no display books on my site when i upload my books with admin.😥

**Comment by OzzieIsaacs** [comment]
which version, which OS?
You use the admin account and use the upload button? 
Which file format do you upload? 
Is there anything relevant in the logfile?

**Comment by OzzieIsaacs** [comment]
Is the uploadbar green at the end of upload, or is it red with an error? 
Are you uploading one file at a time, or multiple files?

**Comment by nanjolono** [comment]
No, It's blue. It's success to upload when i select another files(size : 2MB). May be the file is to large (size:100MB) when i first uploaded.
