### ISSUE TITLE
[Gdrive] Error 500 when uploading files

### ISSUE THREAD

**Issue by MerouaneBen** [janeczku/calibre-web#1108]
I have my calible-web connected to my gdrive, I followed the documentation in the wiki to configure the gdrive.
When i upload new files I get error 500 
<img width="651" alt="Screen Shot 2019-12-14 at 2 12 12 PM" src="https://user-images.githubusercontent.com/12593367/70853584-ca2e5200-1e7d-11ea-8bf4-e863a5784a42.png">

below the logs from the server: 

<img width="969" alt="Screen Shot 2019-12-14 at 2 27 49 PM" src="https://user-images.githubusercontent.com/12593367/70853598-019cfe80-1e7e-11ea-9ec3-aed04f6bc966.png">

thanks for you help

**Comment by OzzieIsaacs** [comment]
Looks like you are not using the newest version. I found some problems recently and fixed them. This evening I did some more testing and found more problems. Please try again with the newest commit version

**Comment by MerouaneBen** [comment]
hey @OzzieIsaacs , thanks for  your quick reply. 
I think i'm on the latest version, I'm using **linuxserver** docker image. 

<img width="874" alt="Screen Shot 2019-12-15 at 10 02 00 AM" src="https://user-images.githubusercontent.com/12593367/70864649-277bdf00-1f22-11ea-91fe-331a16354be0.png">

**Comment by OzzieIsaacs** [comment]
You are on the latest stable version. Meanwhile it turned out that gdrive is more or less broken in this release. 
The newest version is 0.6.5 beta.

**Comment by OzzieIsaacs** [comment]
Should be fixed now
