### ISSUE TITLE
Add Base URL support

### ISSUE THREAD

**Issue by brianbuquoi** [janeczku/calibre-web#111]
To better support reverse proxies, could 'base URL' be added to the GUI?

I am noticing when doing a nginx reverse proxy via the documented way, it works but none of the twitter bootstrap works and everything is text only.

If there's something I'm missing, please let me know.

**Comment by OzzieIsaacs** [comment]
I just doublechecked it, for me it works.
Could you please tell me, which commit version are you using? Are you using windows/which type of linux? Is the problem existing on every page (can you log in?)?
Could you please check the source of the transmitted web-page in your browser (firefox: menu extras -> web-developer -> source or something like that)
It should be something like:
```    
<link href="/calibre-web/static/css/libs/bootstrap.min.css" rel="stylesheet" media="screen">
```
(Calibre-web should be the folder your reverse proxy points at). If this is correct, could you please verify that the file is existing (installing folder/cps/static/css/libs/bootstrap.min.css) and accessible (access rights?) by the browser. 

All the issues relating to reverse proxys had there reasons in missprogramming, so a config option would not change this problem

**Comment by brianbuquoi** [comment]
This is what I see when the reverse proxy is configured to /calibre with nginx:

http://imgur.com/04APyYl

This is how it's added into my nginx.conf:

```location /calibre {
          proxy_pass         http://10.0.1.23:8788;
          proxy_redirect     off;
          proxy_set_header   Host $http_host;
          proxy_set_header   X-Real-IP $remote_addr;
          proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header   X-Forwarded-Host $server_name;
          proxy_set_header   X-Scheme $scheme;
          proxy_set_header   X-Script-Name /calibre;
      }```

I'm running it via the Docker image.

I was asking for a base URL setting as most other media applications have (sonarr, couchpotato, plexpy, etc.) to allow for easier reverse proxy (where all that is needed is the proxypass setting).

From directly at the IP, I am able to access the css:

http://10.0.1.23:8788/static/css/libs/bootstrap.min.css

However I am unable to access the css stylesheet when it is behind the reverse proxy (404 Not Found):

https://home.xxxxxxx.com/calibre/static/css/libs/bootstrap.min.css

Also, when viewing the source when behind the reverse proxy, I see the following:

```<link rel="shortcut icon" href="/calibre/static/favicon.ico">
    <link href="/calibre/static/css/libs/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="/calibre/static/css/style.css" rel="stylesheet" media="screen">```

But none of those links work... If I'm doing something incorrectly, I'm sorry. I have about 8 services all running behind this proxy and this is the only one giving me issues.

**Comment by OzzieIsaacs** [comment]
I checked your configuration, it works for me, except that redirects are not working, the reroute to port 80. (Which works for me in the configuration given in the readme). The links in the source are correct. The reverse proxy path is added correctly. 

Am I correct assuming that you run the reverse proxy on https (port 443)?

So summarizing the link:
`https://home.xxxxxxx.com/calibre` 
is working and showing the login page /root page of calibre-web (except that nothing else than the html is loaded) and
`https://home.xxxxxxx.com/calibre/static/css/libs/bootstrap.min.css` 
is not working and showing a 404 error?
If this is the case, than it's not calibre-webs fault. It seems that the proxy is not routing https://.../calibre/static/css/libs/bootstrap.min.css to http://...:8788/static/css/libs/bootstrap.min.css.

**Comment by brianbuquoi** [comment]
Yes, my reverse proxy is 443 and I have a blanket redirect from 80 to 443.

Is there something else necessary that I'm missing in the nginx config that would be needed for this application specifically?

This is not something I've needed to do with any other application.

**Comment by janeczku** [comment]
> I'm running it via the Docker image.

This is probably be the cause of your issue, since the Docker image itself runs a Nginx instance in front of the application.

**Comment by brianbuquoi** [comment]
Ah that explains some of it.... Is there anything I can do to resolve the redirection?

**Comment by janeczku** [comment]
The Nginx config in the Docker image just doesn't support being behind another proxy. It makes the static files available at /static. I would suggest you build a custom docker image without nginx for that purpose.
