### ISSUE TITLE
Low resolution on cover downloads

### ISSUE THREAD

**Issue by olskar** [janeczku/calibre-web#1111]
Hello!

I recently started using this software and liked it a lot!

When updating metadata from google books, the cover that gets downloaded is very low resolution (only a thumbnail)

Example-URL:
http://books.google.com/books/content?id=PotjAgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api

By adding `&fife=w800-h900` to the end, the image that gets downloaded is highres.

Furthermore, by removing `&edge=curl` you dont get the slightly odd-looking pagecurl on the bookcovers.

I am not sure where in the code this can be changed though :)

**Comment by OzzieIsaacs** [comment]
The request are created in cps/static/js/get_meta.js

**Comment by olskar** [comment]
Thanks @OzzieIsaacs  I had a look but not sure my js-skills are up to it

**Comment by olskar** [comment]
Do you know btw if this is happening for you as well or only me @OzzieIsaacs ? That it downloads only low res covers I mean

**Comment by OzzieIsaacs** [comment]
You are right from google the cover files are downloaded in low-res

**Comment by abdalazizrashid** [comment]
What's the status of this issue?

**Comment by OzzieIsaacs** [comment]
I currently working on it

**Comment by abdalazizrashid** [comment]
Thanks alot!

**Comment by AIndoria** [comment]
If you're using the old(er) version where requests are made separately in form of  `ggSearchBook(title){...}` for example, you could add this block

`for (var i = 0; i < data.items.length - 1; i++) {
                        data.items[i].volumeInfo.imageLinks.thumbnail =
                            data.items[i].volumeInfo.imageLinks.thumbnail +
                            "&fife=w800-h900";
                    }`

after the `if("items" in data)` line in the same form.

That should solve it temporarily while the author works to integrate it.

**Comment by OzzieIsaacs** [comment]
A fix is merged into the newest nightly version
