### ISSUE TITLE
Feature request: convert from same format to same format (to fix wrong cover being sent to Kindle via email after converting from epub to mobi 

### ISSUE THREAD

**Issue by Technosoft2000** [janeczku/calibre-web#1113]
The user @cferrey has posted this feature request https://github.com/Technosoft2000/docker-calibre-web/issues/68

**Here the request message:**

If I upload an epub file and then manually replace the cover, it adds the new cover file to the book's directory as the file cover.jpg. If I then convert the book from epub to mobi and email it to my Kindle Voyage, the wrong cover gets sent (it uses the embedded one in the file, rather than the cover.jpg file).

This can be fixed by using the desktop version of Calibre, where you can import the epub file, add the new cover, and then convert from epub to epub. This embeds the new cover image into the epub file. The epub file can then be uploaded to calibre-web, and converting it to mobi in calibre-web and sending to Kindle via email works with the correct cover showing up on the Kindle.

It would be great if this convert epub to epub functionality could be implemented in calibre-web, such that the cover.jpg file could be embedded into the epub file itself without needing to process it through the full version of the desktop app.

**Comment by OzzieIsaacs** [comment]
Dublicate of #1030
