### ISSUE TITLE
Unable to create tab in Organizr

### ISSUE THREAD

**Issue by OasisFounder** [janeczku/calibre-web#1116]
Possibly an IFrame compatibility issue, or root url issue; however not able to create a functional tab in Organizr+nginx and redirect for calibre-web.  Reverse proxy in wiki does not work in Organizr.

**Comment by richard-lee-863** [comment]
I'm having the same issue getting a 404 error when trying to use reverse proxy on Caddy. Does the calibre-web app need a setting to add a base path? similar to the likes of Sonarr etc?

**Comment by cbartondock** [comment]
Same issue, it works locally but not remotely because of the following error:
`Mixed Content: The page at 'https://hostname.org/#Calibre' was loaded over HTTPS, but requested an insecure frame 'http://hostname.org/calibre/login?next=%2Fcalibre%2F'. This request has been blocked; the content must be served over HTTPS.`

**Comment by henningBunk** [comment]
This looks like a regression for me. On `linuxserver/calibre-web:0.6.7-ls64` (last Linuxserver container for 0.6.7) I have no problems with nginx, organizr and calibre-web in an iFrame. Localy and remotely.

With `linuxserver/calibre-web:0.6.8-ls65` (first linuxserver container for 0.6.8 I am getting a security error when opening in an iFrame.

![Screenshot 2021-01-11 at 21 00 20](https://user-images.githubusercontent.com/14870695/104233026-78c20f00-5451-11eb-9ad8-3fd4241a97ad.png)

Translation: Firefoc is not allowed to open this embedded site. Open in new Tab.

**Comment by OzzieIsaacs** [comment]
It's not a regression, it's a feature! 

Calibre-Web meanwhile supports security features to prevent Cross Site-Scripting attacks.

So I'm sorry, but I don't revert this

**Comment by henningBunk** [comment]
Would there be any way to get this to work with newer versions than? Configuring headers, cookies etc.? I only have a really superficial knowledge of these topics so just want to check the options.

**Comment by OzzieIsaacs** [comment]
For firefox there is an addon ignore X-Frame Options, you could install it add the Calibre-Web Site to the "supported" sites and it should work

**Comment by AddAndy** [comment]
For anyone else who runs into this who doesn't want to change a setting in their browser, i found adding:
`proxy_hide_header X-Frame-Options;` to my nginx-conf works

**Comment by joe-eklund** [comment]
I fixed this on Traefik 1.7 by adding this label to my docker-compose file for calibre-web:

```
traefik.frontend.headers.customFrameOptionsValue: 'allow-from https:myserver.com'
```

I think you can do something similar with traefik 2 as well.

**Comment by justmytwospence** [comment]
Does anyone know the correct Traefik v2 header middleware to achieve this? HTTP headers are still a bit of a black art to me.

**Comment by justmytwospence** [comment]
Aha I figured it out minutes after asking for help of course. Here's a working Traefik v2 middleware to allow iframe embedding:

```
traefik.http.middlewares.allow-embedding.headers.contentSecurityPolicy: "frame-ancestors my-organizr-subdomain.my-domain.com"
```

Keep in mind that the Calibre-Web author(s?) disallowed this for a reason so this is less secure in specific ways.

**Comment by joe-eklund** [comment]
Hey @justmytwospence were you able to work passed the issue I asked about in #2054? I am still getting mixed content issues. Even though the original page loads, you can't login or search for things, even with the contentsecuritypoloicy header set in traefik 2.
