### ISSUE TITLE
how to add book that are already in the nas

### ISSUE THREAD

**Issue by WilliamPrvz** [janeczku/calibre-web#1118]
installed everyting through docker from my synology, i can only add books that are on my computer, not the one that are already on my nas, how can i add them ? thanks

**Comment by OzzieIsaacs** [comment]
How do you add the books?

**Comment by OzzieIsaacs** [comment]
After thinking a while in your request, I now think you try to ask me how to mount the nas to your computer. 
This depends on your operating system.
First you need to activate and configure Samba/SMB on your and. Afterwards on Windows you should be able to access the files via the Explorer, clicking on the name of your nas and open the share. This should also work from the Open file dialog on uploading a Book. On Linux you see the share normally also in the explorer equivalent, but the file Open dialog normally doesn‘t allow you to select the network share as source. You have to mount the share to your filesystem (google will help you to figure out how to do this for your distro).
