### ISSUE TITLE
Edit EXTENSIONS_UPLOAD in Settings

### ISSUE THREAD

**Issue by ghost** [janeczku/calibre-web#1119]
Hello!

We use your app in our small company as platform for company library. It has very nice interface, works smooth, but there is only one thing what we miss.

We not only read, but listen books, and calibre-web has a white list of extentions allowded to upload. Audiobooks usually storage in .zip with many .mp3 or mp4 in it.

I am not a developer myself, i requested our programmists/dev-ops add .zip to white list, but they refused because they need to re-compose docker container every update, it's would took many hours they said.

Please, can u add edit EXTENSIONS_UPLOAD in Settings in UI?
This can be helpfull to all other people, who somehow goes to use non-standart files in their libraries.

**Comment by OzzieIsaacs** [comment]
The feature is meanwhile implemented in the newest release (if you activate upload function an new option is shown)
