### ISSUE TITLE
Uploading a single ebook causes 500 Internal Server Error

### ISSUE THREAD

**Issue by SpencerDub** [janeczku/calibre-web#1122]
I'm running calibre-web as part of a YunoHost server. I've been slowly setting up my library, uploading books one at a time through the calibre-web interface. The location of my calibre-web library is not currently being used by any other Calibre installations; for instance, my Calibre desktop client has its own library on my local computer, not the server.

I have suddenly begun having issues uploading ebook files. When I try to upload a single book, the uploader gives me an error message and the file doesn't upload. I've tried this with several ebook files, around 70-80 KB each, and the problem is always the same.

The upload window attempts to display a full error webpage in the progress bar:

![Xanderwhart Calibre error](https://user-images.githubusercontent.com/4674927/71646913-039af600-2ca3-11ea-8f00-966f67f64598.png)

If I use my browser's DOM inspector to view the contents of this, I get a fully formed HTML document within that single `<div>`, which reports a 500 Internal Server Error:

> **500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.**
> Traceback (most recent call last):
> File "/var/www/calibreweb/vendor/flask/app.py", line 2446, in wsgi_app
> response = self.full_dispatch_request()
> File "/var/www/calibreweb/vendor/flask/app.py", line 1951, in full_dispatch_request
> rv = self.handle_user_exception(e)
> File "/var/www/calibreweb/vendor/flask/app.py", line 1820, in handle_user_exception
> reraise(exc_type, exc_value, tb)
> File "/var/www/calibreweb/vendor/flask/app.py", line 1949, in full_dispatch_request
> rv = self.dispatch_request()
> File "/var/www/calibreweb/vendor/flask/app.py", line 1935, in dispatch_request
> return self.view_functions[rule.endpoint](**req.view_args)
> File "/var/www/calibreweb/cps/web.py", line 145, in decorated_view
> return login_required(func)(*args, **kwargs)
> File "/var/www/calibreweb/vendor/flask_login/utils.py", line 261, in decorated_view
> return func(*args, **kwargs)
> File "/var/www/calibreweb/cps/web.py", line 216, in inner
> return f(*args, **kwargs)
> File "/var/www/calibreweb/cps/editbooks.py", line 696, in upload
> error = helper.update_dir_stucture(book.id, config.config_calibre_dir)
> AttributeError: 'NoneType' object has no attribute 'id'

I've switched to nightly builds and updated to the most recent build, v0.6.5 beta. I've also restarted calibre-web. Neither of those has helped; I still get the error when uploading files.

Any help would be appreciated. Thanks.

**Comment by OzzieIsaacs** [comment]
Calibre-Web tries to rename a non Existing  Book, and this fails. ( for me the Upload works). are there and other entries in the logbook (calibre-web.log in the Root folder). Which version of the libraries (visible in about section) are installed?

**Comment by OzzieIsaacs** [comment]
I know what happens: You have restrictions applied (like only certain language is visible, or exclude mature content. If the uploaded book has one of this metadata set, the book is stored to the database, then it's tried to read the content, but it's blocked, so None is returned in editbooks.yp:691 and the upload fails

**Comment by SpencerDub** [comment]
Ah, that must be it. I had recently changed it so that my account only showed books in English.

Unfortunately, I've encountered an additional error: when I try to go to my account settings (/calibre/me), I get another [internal server error](https://pastebin.com/gWZexZqt). I can't seem to get to my account settings in order to remove the restrictions.

**Comment by OzzieIsaacs** [comment]
I fixed the new problem 2 hours ago, so if you update to the newest commit, the 2nd error should be gone

**Comment by SpencerDub** [comment]
Thanks, @OzzieIsaacs. The newest commit resolved the second error, which allowed me to remove the language restriction from my account. That fixed the primary error for me.

**Comment by OzzieIsaacs** [comment]
Fine.
Please leave the issue open, I will close it upon solving the problem programmatically.

**Comment by Todtmann** [comment]
> I know what happens: You have restrictions applied (like only certain language is visible, or exclude mature content. If the uploaded book has one of this metadata set, the book is stored to the database, then it's tried to read the content, but it's blocked, so None is returned in editbooks.yp:691 and the upload fails

You made my day. I thought I have somewhere a big permission issue...
