### ISSUE TITLE
Hide Mature Content - Public Shelfs

### ISSUE THREAD

**Issue by ramsnerm** [janeczku/calibre-web#1123]
Hi!
First of all thanks for the great piece of software. I like the Book Version of PLEX :-)

Now the issue:
- create a public shelf
- add some books rated with a "Mature Content" tag
- login as user which is not allowed to see "Mature Content"

The User will not see the Books in the overview list (eg sorted A to Z) but if he is clicking on the public bookshelf all content can be seen.

Effect:
- Can see the cover of the books
- Cannot open the details
- By clicking on a book the user is re-routed back to the overview page again

**Comment by OzzieIsaacs** [comment]
It's indeed not working, also not for private shelfs (if you add the book before the mature_content rule was applied).
Looks complicate to fix

**Comment by OzzieIsaacs** [comment]
I found an easy workaround for the complication. There is still on issue, if you rearrange books in shelfs with invisible (=mature) content this will lead to unexpected results. I have to fix this, too.

**Comment by ramsnerm** [comment]
Thanks for the support.

**Comment by ramsnerm** [comment]
> ... if you add the book before the mature_content rule was applied).

I tested it and in my installation it is also shown in case the book has been added after the rule was applied.

**Comment by OzzieIsaacs** [comment]
Forgot to push my changes, now they are visible

**Comment by OzzieIsaacs** [comment]
> I tested it and in my installation it is also shown in case the book has been added after the rule was applied.

But how do you add a invisible book to a shelf?

**Comment by ramsnerm** [comment]
> > I tested it and in my installation it is also shown in case the book has been added after the rule was applied.
> 
> But how do you add a invisible book to a shelf?

When you are logged in as a different User with mature content and public shelf management rights.

**Comment by OzzieIsaacs** [comment]
Okay, I was referreing to private shelf, so now everything fits together.  
I think the final patch including sorting of invisible books will be available soon.

**Comment by ramsnerm** [comment]
Thanks

**Comment by OzzieIsaacs** [comment]
It's meanwhile fixed an improved, you now see "hidden" books if sorting shelfs with books you don't see.

**Comment by ramsnerm** [comment]
Thanks
