### ISSUE TITLE
Metadata scraping

### ISSUE THREAD

**Issue by Dinth** [janeczku/calibre-web#1126]
Is there a way of adding new metadata scrapers to calibre-web? 
I would love to contribute support for polish LubimyCzytac.pl, but i dont know where to start.

**Comment by OzzieIsaacs** [comment]
The loading and processing is done only in javascript.
The dialog you see for selecting the metadata is defined in: /cps/templates/book_edit.html (there are the 2 buttons for douban and google, you need to add another one for your provider)
The real processing and loading is done in cps/static/js/get_meta.js
I think you can take the current 2 provider as template for your one, the code is not so complicated and complex, so should be understandable.
Currently there is no defined API or detailed documentation for doing it. After restarting the server the new javascript and html files are loaded, AND: (big advantage compared to many other projects) every script is loaded with it's hash value as parameter, so the browser always detects changed scripts and you won't have to fiddle around with the browser cache.
