### ISSUE TITLE
caliBlur! publisher page says "Series"

### ISSUE THREAD

**Issue by SpencerDub** [janeczku/calibre-web#1128]
When you browse by Publisher when using the caliBlur! theme, the heading reads "Series" instead of "Publisher".

![CaliBlur publisher](https://user-images.githubusercontent.com/4674927/71789545-7b895900-2fe0-11ea-85e8-cbd1820a43e0.png)

This does not appear to be an issue with the default theme, only with caliBlur!.

I'd submit a PR for this minor fix myself, but I can't find the proper file to edit. Sorry!

**Comment by OzzieIsaacs** [comment]
I fixed it. The text is added in the caliblur.min.css file.But there are more bugs in this, the file formats and ratings section are missing the headers, and the texts are not translateable

**Comment by SpencerDub** [comment]
Great, thanks!
