### ISSUE TITLE
[Feature Request] Allow toggle for auto sign-up via Auth Reverse Proxy

### ISSUE THREAD

**Issue by rg9400** [janeczku/calibre-web#1130]
As a continuation of this excellent PR https://github.com/janeczku/calibre-web/pull/1107, I was wondering if it was possible to allow headers for email/name to also flow from auth proxy headers, and then to create a toggle to allow auto sign-up using those data points if the user did not exist in the Calibre-Web DB already. The default settings and visibilities for that user can be pulled from the same defaults for new users. It essentially removes the need for a registration flow if users are being registered somewhere else, such as in my case from Organizr. Changes to kindle email can continue to be done manually from the user, and password is irrelevant (random) since the user would essentially be using oAuth from the auth-proxy. Below, I have linked an implementation of the same in Grafana as an example.

https://grafana.com/docs/grafana/latest/auth/auth-proxy/

**Comment by OzzieIsaacs** [comment]
I'm not happy with the idea to open another new path of registering new users, this creates another level of complexity. I prefer not to implement it.

**Comment by xcffl** [comment]
@OzzieIsaacs I don't think it's that hard. I'm going to implement this in my project. And I'd love to contribute this to upstream.
