### ISSUE TITLE
[feature request] Integrate Kepubify script

### ISSUE THREAD

**Issue by Dinth** [janeczku/calibre-web#1132]
Would it be possible to add Epub <> Kepub converter to the docker container?
https://www.mobileread.com/forums/showthread.php?t=295287

**Comment by OzzieIsaacs** [comment]
I'm not the maintainer of the docker container, only of calibre-web.
Would it be enough for you to have it in the docker container, or do you also request to integrate kepubify in calibre-web?

**Comment by rcristi** [comment]
I would like to see kepubify integrated right in the calibre-web

**Comment by Carina235** [comment]
Me, too.

**Comment by Stvn21** [comment]
yes, great idea to integrate it in calibre-web.

**Comment by CHBMB** [comment]
@OzzieIsaacs I guess you can close this now, and I'll handle the linuxserver docker container side.

**Comment by OzzieIsaacs** [comment]
Thanks
