### ISSUE TITLE
metadata.opf is missing when sending from Calibre

### ISSUE THREAD

**Issue by rablador** [janeczku/calibre-web#1134]
Hi!

Just recently sending ebooks directly from Calibre to calibre-web (via copy function) stopped working. After upload (which in itself is working) the books are missing an opf file and calibre-web cannot parse file location or cover art (some other metadata is there though). When trying to delete the book from calibre-web I get the following error:

```
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
return func(*args, **kwargs)
File "/calibre-web/app/cps/editbooks.py", line 157, in delete_book
helper.delete_book(book, config.config_calibre_dir, book_format=book_format.upper())
File "/calibre-web/app/cps/helper.py", line 448, in delete_book
return delete_book_file(book, calibrepath, book_format)
File "/calibre-web/app/cps/helper.py", line 282, in delete_book_file
if len(next(os.walk(path))[1]):
StopIteration`
```

**Comment by OzzieIsaacs** [comment]
> directly from Calibre to calibre-web (via copy function)

means you have books in database1 in calibre and calibre-web is using database2 and you copy the books to the database of calibre-web, right?
> the books are missing an opf file

That can be right, as Calibre-web is not generating and using the opf files currently.
> calibre-web cannot parse file location
Means, what is not working?

For tracking down this issue it's necessary for me to have more information. Are you using docker,  which one, and on what system (raspberryPi, Synology, etc...) Where are the databases located, both on the same computer, or on different one's?

**Comment by rablador** [comment]
Ah, my bad!

- Technosoft2000 docker image, currently version 1.3.1
- Synology Diskstation, lastest version
- calibre-web, always try to keep up with latest

I have one db locally on my Mac and one (calibre-web) remotely on Diskstation. I ususally add books etc and fix metadata locally, then I copy from local db to remote through Calibre software. This has worked very well in the past, but suddenly stopped working. I can see that all successful past transfers have an opf file bundled with them in calibre-web, but not the new ones.

All metadata is transferred, but not the cover image or the actual book file.

Also, although possibly unrelated, I don't get the option to read any books directly from calibre-web anymore. I can only download.

**Comment by rablador** [comment]
Never mind the thing I wrote about not being able to read directly on the web. My bad, it works 👍
