### ISSUE TITLE
Russian translation update / Language settings for the guest user / Deleting books

### ISSUE THREAD

**Issue by XZVB12** [janeczku/calibre-web#1135]
Hello, I would like to offer you my update of the Russian translation, since the translation in this repository is outdated and partially missing. I did not find any mention of mail or feedback, so I write here. Thank you for the project anyway.
I decided not to create additional "issues" and add a few questions here, sorry if this is inconvenient.
1)In the guest user settings, you can configure the interface language, but when using the "guest" user, the English interface will always be displayed, can this be fixed?
2)In the user settings, you can enable the deletion of books, but I did not find a way to do this, after enabling this option ... can you help me with this?
[Russian translation update.zip](https://github.com/janeczku/calibre-web/files/4043541/Russian.translation.update.zip)

**Comment by OzzieIsaacs** [comment]
I merged the language file, thanks
1.) The guest language setting shouldn't be visible at all. (I will fix this). The guest user language is taken from the user accept header from the browser. Reason behind this: If you are having guest user, they could be from anywhere in the world, so everybody should see it's preferred language. If you see the UI always in english, there is something wrong with it. In Firefox you can view the accept header by opening the developer console, going to networkanalysis reloading the calibre-web webpage choosing a random request and then clicking on change and resend (bottom right corner), afterwards you should see all request headers. There should be on saying accept language. 
![grafik](https://user-images.githubusercontent.com/6438895/72288837-330a1500-364a-11ea-8aca-78c1bf50facb.png)
If you post the contents of this string I can check why it's not working (for me it's working):
![grafik](https://user-images.githubusercontent.com/6438895/72289079-a0b64100-364a-11ea-9614-ce6ce50a0892.png)
2) The delete book option is on the edit metadata page, so you can only see it if you are also tick "allow edit books". I will change this, so enabling delete book will also allow (and tick) edit book

**Comment by OzzieIsaacs** [comment]
The accept language header is no read out correctly, in the old version the weighting of the browser (which language is the preferred language) was not taken into account correctly, so a random language was the preferred one.
