### ISSUE TITLE
support passing initial admin/password from env to cli

### ISSUE THREAD

**Issue by rockonedege** [janeczku/calibre-web#1136]
with admin/admin123 being default,  I have to change it once the site is up the first thing.

Is there an option to specify a custom account/password through cli parameter or env existing?

**Comment by OzzieIsaacs** [comment]
There is indeed a undocumented Feature, I just rediscovered. Of you Start calibre Web with -h you der the available options, the Last Sets the password of a certain user

**Comment by OzzieIsaacs** [comment]
My last statement wasn't fully true. Looks like I started implementing the feature but I didn't finish it, so it's currently not working

**Comment by OzzieIsaacs** [comment]
The command line option is available
