### ISSUE TITLE
Send to Kindle - Large Book File Size Error Handling

### ISSUE THREAD

**Issue by joshobriencom** [janeczku/calibre-web#1141]
Hi, 
With email accounts having attachment size restrictions and Amazon's Send to Kindle having a maximum limit of 50MB per email, it would be great if Calibre-Web could have the option to set a maximum file size for the Send to functionality. This would allow an admin to set a maximum Send to limit of 50MB and if a user selects "Send to Kindle" and the file is above the size limit, Calibre-Web instead displays an error message advising the user that the book is too big to send and will need to be downloaded and transferred manually to their Kindle. 

This would be an amazing feature as all my users read only on Kindle devices and exclusively use the Send to Kindle function, however there are some of my books are above 100MB like cookbooks or travel books.

**Comment by rg9400** [comment]
I second this feature. Right now, the Send to Kindle fails silently, both for the user requesting the book and the server owner. The only way either of them would come to know would be to realize the book never arrived or check the task status and notice a failure (which actually blends in with successful task status on the Blur theme). 

Ideally, the option to Send to Kindle should not even be allowed, with an error message as the OP mentioned being useful info for the user to decide to download the book manually instead.

In the meantime, maybe failed tasks can somehow be more evident via some notification on the UI or an email alert?

**Comment by OzzieIsaacs** [comment]
There is a new setting in the newest master commit to limit the attachment size. If book has a size above limit it's not available for emailing

**Comment by rg9400** [comment]
Thanks a ton! Checked a few samples, and it is working as intended. Really appreciated
