### ISSUE TITLE
[Feature Request] Book shelves lock down

### ISSUE THREAD

**Issue by Alacard** [janeczku/calibre-web#1144]
what im hoping to be able to do is create a new public book shelve called "For Kids" and assign a user to that shelve, so that user is only able to see/read what in the book shelve. i think adding something like this will make it more "kid friendly" seeing how my wife have a few romance books on the server that i would not like my kid be able to see/read.

I do no that there's the "Show mature content" option but seeing as most (if not all) "mature" books dont by default have a meta tag for that. its becomes a pain in a half to have to go behind my wife every time she adds a new book. so being able to lock them in a book shelve would help a lot with something like that.

P.S. bonus point if it also works via OPDS

**Comment by OzzieIsaacs** [comment]
My solution/ proposal would be the following:
I‘m currently working on a feature change from a general restriction towards a restriction on per user base. additionally it will be possible to make all books invisible for a certain user and only books with a special tag name or special content in a custom column will be visible. So you have to activly make it visible to your kids (like deny all books with tag adult and allow only books with tag kidcontent)

**Comment by Alacard** [comment]
Something like that would work too, just got both of my kids kindles for x-mes, and for got all about my wife romance book. until one of my kinds came to me and said. "Daddy what that word mean?" so ya no kindle for them until i can get something like this working

**Comment by OzzieIsaacs** [comment]
The feature is implemented
