### ISSUE TITLE
Mobi download on kindle problem

### ISSUE THREAD

**Issue by b0tting** [janeczku/calibre-web#1149]
I recently updated my calibre-web instance to the most recent version. After the upgrade, my kindle paperwhite (also updated) could no longer download .mobi files from calibre-web pages. When clicking on the link the kindle browser complains about invalid file extensions and mentions that only .mobi and .text are supported.

I managed to isolate it to a change in the content-disposition header. This has changed from a simple filename= to filename*=UTF8 in get_download_link in cps/helper.py. 

When changing this line:
`headers["Content-Disposition"] = "attachment; filename*=UTF-8''%s.%s" % (quote(file_name.encode('utf-8')),book_format)` 

to a version similar to https://tools.ietf.org/html/rfc6266#section-5 it works fine again: 
`headers["Content-Disposition"] = "attachment; filename=%s.%s; filename*=UTF-8''%s.%s" % (quote(file_name), book_format,quote(file_name.encode('utf-8')), book_format)
`
..but I am not sure if this functions correctly in cases where the reason the UTF-8 change was made for.

**Comment by OzzieIsaacs** [comment]
I took your proposal and integrated in calibre-web. I digged into the code, it looks like I added it to give the downloads names on normal browser download. I checked it on marvin, chunky and firefox and it was still working, so I think it's safe (almost)

**Comment by b0tting** [comment]
@OzzieIsaacs Did a pull and retested with my kindle experimental browser - this works again. Thank you for the effort.
