### ISSUE TITLE
version update stay 0.6.5 Beta,but can not update 0.6.5 stable version.

### ISSUE THREAD

**Issue by flashliao** [janeczku/calibre-web#1152]
No mater how many times click update versions,version update stay 0.6.5 Beta,Not 0.6.5 stable.

0.6.5 Beta chrome internet not have chinese translation.

I use chrome internet.

**Comment by flashliao** [comment]
0.6.5 Beta version can not read the book!

**Comment by OzzieIsaacs** [comment]
Yes it was an error that the version number wasn't changed, this is fixed now.
