### ISSUE TITLE
last update version Guest account just can english languages,Can not change chinese translation.

### ISSUE THREAD

**Issue by flashliao** [janeczku/calibre-web#1153]
0.6  stable version Guest account just show chinese translation.
but Chromium explorer 69.0.3497.100 can not show chinese languages,IE、Edge explorer show chinese  languages.
If I update the versions,other accounts can login,and can changge the languages.But Guest account 
 how to changge the language? I'm in china.I'm useing the web application.

**Comment by OzzieIsaacs** [comment]
The language is detected automatically by the preferred browser language. You can change the setting as written below. This has the advantage that many other pages which detect the language will show in chinese afterwards.
From https://stackoverflow.com/questions/37221494/how-to-change-the-locale-in-chrome-browser
Open chrome, go to chrome://settings/languages

On the left, you should see a list of languages. Use mouse to drag the language you want to the top, that will change the order for the values in Accept-language of requests.

If you still don't see the language you prefer, it may be cookies. Go to cookies and clean it up you should be good.

**Comment by OzzieIsaacs** [comment]
The code now takes the ranking of the languages into account, please update, should work now
