### ISSUE TITLE
How to backup Public Shelf

### ISSUE THREAD

**Issue by abubaman** [janeczku/calibre-web#1157]
I know almost all data will be stored in calibre-library file.(metadata.db and xxx.opf)
But as I know, public shelf is only calibre-web function, so i don't think calibre-library file stores publick shelf.

So, In case I want to back up public shelf, the only thing I need to do is back-up app.db file?
And if I want to back up configuration of Calibre-web, do I need to back up app.db file also?

**Comment by OzzieIsaacs** [comment]
Yes, every setting from calibre-web is stored in the app.db, so if you backup this files you get everything (public/private shelfs, download statistics, usernames, passwords, user settings, email server settings, ...).
