### ISSUE TITLE
ebook-convert ERROR - Ebook-converter failed: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by 8bitgentleman** [janeczku/calibre-web#1159]
Calibre-Web is running from a Docker container (technosoft2000/calibre-web) on a Synology NAS and is set up to use calibre-convert which is located at /opt/calibre/ebook-convert. The calibre-web version is 0.6.4. 
When attempting to convert an epub file to mobi (to send to a kindle) calibre-web throws this error:

`ERROR - Ebook-converter failed: [Errno 2] No such file or directory`

The calibre desktop app is able to convert the file just fine. Both the file and ebook-convert have wide open permissions (777). Any clue what could be going on here?

**Comment by OzzieIsaacs** [comment]
Could you please check in the about/stats section if the calibre-converter is listed with a version number? If not, the file is somehow not found. Many people using docker complained here about container having problems with "not found calibre-databases" and so on. Could you please check the mapping from "outside" to the container filesystem? 
Could you please try to enable debug logging, and check if there are more outputs? 
Would it be possible for you to update calibre-web and/or the container? 
Furthermore I'd like to suggest to open this issue on the technosoft2000 container (I'm not the maintainer of the docker container, and I have never used any docker container, and therefore have no knowledge in this field.)

**Comment by 8bitgentleman** [comment]
hmm interesting, under About/stats it says the Calibre converter is not installed. I've copied the actual ebook-converter file into the docker container, not linked it. Maybe that's the issue...
Does calibre-web need anything other than the ebook-convert binary file?

I'll open this on the technosoft2000 repo as well

**Comment by OzzieIsaacs** [comment]
I really have no clue about this mapping file stuff from docker. Because of this type of problems, I'm planing for a longer time a "server-side" file browser, so you can see which folders the server sees and it's easier to point to the metadata file and the calibre-converter file. But currently I'm having other topics to fulfill.

**Comment by 8bitgentleman** [comment]
I started fresh with a new pull of the docker container and everything magically works now. Must have been using an old version. Thanks for the help
