### ISSUE TITLE
[Enhancement]: Prevent user from creating shelves

### ISSUE THREAD

**Issue by philipsd6** [janeczku/calibre-web#1171]
I would like to be able to create a shared user account that does not have the ability to create shelves. Otherwise, someone in that group could use shelf titles to send inappropriate messages to the group with no accountability. Currently, there is no option to enable/disable this feature, and the guest browsing access doesn't include reading books online.

(Obviously, creating individual user accounts is preferred, but we have several groups that only last several months, and don't want to incur the burden of additional user management.)

**Comment by OzzieIsaacs** [comment]
You can enable viewing books on the guest account by editing the guests user account:
![grafik](https://user-images.githubusercontent.com/6438895/73590237-6967e100-44e0-11ea-8ff9-9330c14e74f7.png)
But, yes there is no option to "disallow" creating and editing shelfs of certain users. I will think about this request

**Comment by Gentleman03** [comment]
+1 for this enhancement.
