### ISSUE TITLE
[Enhancement]: automatic username

### ISSUE THREAD

**Issue by philipsd6** [janeczku/calibre-web#1172]
I would like to enable public registration, but only for users belonging to my educational domain. Additionally, I would like to use their email address as their username, or the username portion as their username, as I do not want anyone to create their own username.

So, request is to have the option of whitelisting domains for registration, and optionally eliminating the username field and falling back on the email address as the username.

This is similar to #901, which was closed as implemented, but in fact there is still no option to whitelist domains.

**Comment by OzzieIsaacs** [comment]
In the setup email server section you can whitelist domainparts or as I called it "allow domains for registering"
![grafik](https://user-images.githubusercontent.com/6438895/73590181-cd3dda00-44df-11ea-9dca-ce530493b59e.png)

**Comment by OzzieIsaacs** [comment]
And I think about the other part of your request

**Comment by OzzieIsaacs** [comment]
I'm currently implementing the feature, I added a new option: if public registering is enabled, you can choose to use the user's email as username. 
The registering form would look like this:
![grafik](https://user-images.githubusercontent.com/6438895/81710432-02f54600-9473-11ea-93cd-f8f7e606fe2e.png)

After registering and login in the user would be able to change their e-mail address, but not their username:
![grafik](https://user-images.githubusercontent.com/6438895/81710130-cd505d00-9472-11ea-9fc6-2f3e0e4bb114.png)
Admins would still be allowed to change a users name:
![grafik](https://user-images.githubusercontent.com/6438895/81710617-2ae4a980-9473-11ea-8736-f3098ccdced3.png)

Would this fulfill your requirements?

**Comment by OzzieIsaacs** [comment]
In the newest master commit you have the option to use the email address as username
