### ISSUE TITLE
Reset Password Bug

### ISSUE THREAD

**Issue by skillpoint-dev** [janeczku/calibre-web#1177]
When having a freshly setup calibre-web docker container, without having the SMTP config touched at all, I encountered the problem that when I enter an existing username and press [Forgot Password] the password is changed although it shouldn't.

- ### Expected behavior: Password isn't changed, user is probably informed that reset is not possible.

- ### Current behavior: Reset of password happens and user is not informed and can therefore not login again with this user.

I dug through the code a bit and found the simple mistake:

In the **config.py** the default value for the mail_login is

`mail_login = Column(String, default='mail@example.com')`

whereas in the **constants.py** the constant for the default mail server is

`DEFAULT_MAIL_SERVER = "mail.example.org"`

Because of this simple mismatch **reset_password** in **helper.py** the non existing configuration will not be caught by the if-statment and therefore the reset will be executed.

I am sorry that I am not solving this with a pull-request myself but I have no idea how I would debug/test this on my own and I thought this is a quite fast and easy fix for someone who knows what he/she is doing. Thanks!

**Comment by OzzieIsaacs** [comment]
It is already fixed:
![grafik](https://user-images.githubusercontent.com/6438895/73867505-2a6ebe00-4847-11ea-93be-2aea792d0b4d.png)
Looks like you are using an outdated version.

**Comment by skillpoint-dev** [comment]
> It is already fixed:
> ![grafik](https://user-images.githubusercontent.com/6438895/73867505-2a6ebe00-4847-11ea-93be-2aea792d0b4d.png)
> Looks like you are using an outdated version.

Sorry, I wasn't looking at the develop branch and it isn't yet merged to master so I guess it isn't yet released or are there versions "released" from the develop branch?

**Comment by OzzieIsaacs** [comment]
It's part of the master branch and also included in the latest release 0.6.5
![grafik](https://user-images.githubusercontent.com/6438895/73869505-a4547680-484a-11ea-8750-9aec987986e8.png)

**Comment by skillpoint-dev** [comment]
Sorry, I somehow must really have had an old version. Anyway it is gone now and I love it. Thanks for the answers!
