### ISSUE TITLE
error excute python cps.py

### ISSUE THREAD

**Issue by hughdj** [janeczku/calibre-web#1180]
Error starting server: module 'asyncio' has no attribute 'WindowsSelectorEventLoopPolicy'

**Comment by OzzieIsaacs** [comment]
Python Version:
Operating System:
Docker [yes/no]:
Which docker:

**Comment by hughdj** [comment]
> Python Version: python 3.6
> Operating System: windows 10
> Docker [yes/no]: no
> Which docker: none

**Comment by OzzieIsaacs** [comment]
It's fixed, please update to the newest commit version
