### ISSUE TITLE
Book details not showing

### ISSUE THREAD

**Issue by tegobash** [janeczku/calibre-web#1181]
Hi! I think I followed the instructions thoroughly, yet I cannot access any book details. The pop-up window displays only three dots and when I click on the book through the author's page I get this error: 

> 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
> Traceback (most recent call last):
> File "C:\calibre-web-master\vendor\flask\app.py", line 2446, in wsgi_app
> response = self.full_dispatch_request()
> File "C:\calibre-web-master\vendor\flask\app.py", line 1951, in full_dispatch_request
> rv = self.handle_user_exception(e)
> File "C:\calibre-web-master\vendor\flask\app.py", line 1820, in handle_user_exception
> reraise(exc_type, exc_value, tb)
> File "C:\calibre-web-master\vendor\flask\_compat.py", line 39, in reraise
> raise value
> File "C:\calibre-web-master\vendor\flask\app.py", line 1949, in full_dispatch_request
> rv = self.dispatch_request()
> File "C:\calibre-web-master\vendor\flask\app.py", line 1935, in dispatch_request
> return self.view_functions[rule.endpoint](**req.view_args)
> File "C:\calibre-web-master\cps\web.py", line 166, in decorated_view
> return login_required(func)(*args, **kwargs)
> File "C:\calibre-web-master\vendor\flask_login\utils.py", line 261, in decorated_view
> return func(*args, **kwargs)
> File "C:\calibre-web-master\cps\web.py", line 1471, in show_book
> is_xhr=request.is_xhr, title=entries.title, books_shelfs=book_in_shelfs,
> File "C:\calibre-web-master\vendor\werkzeug\local.py", line 347, in __getattr__
> return getattr(self._get_current_object(), name)
> AttributeError: 'Request' object has no attribute 'is_xhr'

I've tried three different browsers, clearing browser cache & went through similar issues. 
Log attached.
[calibre-web.log](https://github.com/janeczku/calibre-web/files/4174088/calibre-web.log)

**Comment by OzzieIsaacs** [comment]
Problem is you are using a version of "werkzeug" which is to new.
As workaround till I find a fix 
please try: 
`pip3 install --target vendor -I werkzeug==0.15.4`

**Comment by tegobash** [comment]
Didn't help

**Comment by OzzieIsaacs** [comment]
Did you update, or change werkzeug installation?
Is the error message in the log the same?
Which version of werkzeug is listed in the about section?

**Comment by tegobash** [comment]
I used the command you posted 
`pip3 install --target vendor -I werkzeug==0.15.4`
The error message is the same and the werkzeug version is 1.0.0. 
I understand that I need to downgrade but I don't know what command should I use.

**Comment by tegobash** [comment]
I realized I haven't mounted calibre-web folder so I did that and used the command again. Now cps.py gives this:

> C:\calibre-web-master>python cps.py
Traceback (most recent call last):
  File "cps.py", line 34, in <module>
    from cps import create_app
  File "C:\calibre-web-master\cps\__init__.py", line 59, in <module>
    app = Flask(__name__)
  File "C:\calibre-web-master\vendor\flask\app.py", line 601, in __init__
    self.add_url_rule(
  File "C:\calibre-web-master\vendor\flask\app.py", line 98, in wrapper_func
    return f(self, *args, **kwargs)
  File "C:\calibre-web-master\vendor\flask\app.py", line 1277, in add_url_rule
    self.url_map.add(rule)
  File "C:\calibre-web-master\vendor\werkzeug\routing.py", line 1388, in add
    rule.bind(self)
  File "C:\calibre-web-master\vendor\werkzeug\routing.py", line 730, in bind
    self.compile()
  File "C:\calibre-web-master\vendor\werkzeug\routing.py", line 794, in compile
    self._build = self._compile_builder(False).__get__(self, None)
  File "C:\calibre-web-master\vendor\werkzeug\routing.py", line 951, in _compile_builder
    code = compile(module, "<werkzeug routing>", "exec")
TypeError: required field "type_ignores" missing from Module

**Comment by OzzieIsaacs** [comment]
Meanwhile I have fixed calibre-web. 
So if you download  the newest version of calibre-web it should work.  
Calibre-web should now work with the new version of werkzeug. (Maybe you should delete the vendor folder and start all over with the install procedure. For me 4 hours ago everything worked fine, without errors on windows)
And pip3 ... installs werkzeug for python3, pip would install werkzeug for python2, you didn't tell me which version you are using, so maybe I guessed the wrong one.

**Comment by tegobash** [comment]
It works! Thank you very much! :)
