### ISSUE TITLE
Disable downloading books for guest (pdf problem)

### ISSUE THREAD

**Issue by Gentleman03** [janeczku/calibre-web#1184]
Hello Janeczku!

There is an option to disable downloading books from library. But if you can view pdf file then you can easily "download" them by printing it to file. So is there any way to disable/avoid printing option?

**Comment by OzzieIsaacs** [comment]
I removed the print button in the pdf form, but you can still print the file from the browser menu. I had discussions like this before, as long as you can see the document, you can download it to your computer, it's just a matter of effort. The real way of preventing it would be disable the read functionallity (via admin -> user edit -> allow browse)

**Comment by Gentleman03** [comment]
I agree, if you can see the document it's just matter of effort to download it and that is the point. It's all about making it hard enough to make it not worth the effort. Thanks for removing the button, it's always something :)

**Comment by OzzieIsaacs** [comment]
Sorry, forgot the git push, the change should be visible now.
