### ISSUE TITLE
Can't open book details

### ISSUE THREAD

**Issue by Thatkookooguy** [janeczku/calibre-web#1188]
I can view my library no problem, seeing all the books I have.

But once I click a book, I get the following error:

![image](https://user-images.githubusercontent.com/10427304/74116281-be05fe80-4b67-11ea-8b8b-e068762c3120.png)

So I can't open any book.
I tried this with `pdf` files and `epub` books.
Also, since the error showed some `login` files, I tried logging out and logging back in of `calibre-web` to refresh my token but that didn't fix the problem.

## Some info
System: `Windows 10 Home`
Calibre-Web: `0.6.5`
Calibre: `4.10.1`
Running using python 3 (not inside a container)

**Comment by OzzieIsaacs** [comment]
Please refer to #1181.
