### ISSUE TITLE
upload button retrieves error message

### ISSUE THREAD

**Issue by waelguirguis** [janeczku/calibre-web#1189]
when uploading a PDF book using the upload button, i receives an error message and the book was not uploaded.

**Comment by OzzieIsaacs** [comment]
Python Version:
Operating System:
Docker [yes/no]:
Which docker:
Calibre-Web version:
Error message:
Relevant Content of calibre-web logfile:
Size of uploaded pdf file:
Installed dependencies (visible in about section):
