### ISSUE TITLE
search  v 0.6.5 

### ISSUE THREAD

**Issue by LouiseLo02** [janeczku/calibre-web#1190]
Search doesn't seem to work for me, always get "No Results", Searching for Author or Book Title or anything doesn't work. also it is way slower than before.

**Comment by OzzieIsaacs** [comment]
Python Version:
Operating System:
Docker [yes/no]:
Which docker:
Calibre-Web version: 0.6.5
Relevant Content of calibre-web logfile:
Installed dependencies (visible in about section):
Could you please also give an example of the term you are searching for and book names, titles in your library, so I have a chance to reproduce it. 
I doublechecked it, for me it's working

**Comment by LouiseLo02** [comment]
Python Version:  3.6.9
Operating System:  Linux Mint 19.2
Docker [yes/no]:  no
Calibre-Web version: 0.6.5


After the looking at the dependencies... I saw there were a few missing: 
python3-wand  
python3-pypdf2 
python3-unidecode 


After installing those, it started working.  Thank you so much!

**Comment by OzzieIsaacs** [comment]
The unidecode was the problematic one.
