### ISSUE TITLE
Enhancement: add license to calibre-web

### ISSUE THREAD

**Issue by cervinko** [janeczku/calibre-web#12]
as far as i can see calibre-web and the original calibreserver do not use any license. 
i think we should contact Raphael Mutschler and ask him to add a 'free' license

or do we already have a license and i didn't find it?

**Comment by janeczku** [comment]
I opened an issue on his bitbucket repo: https://bitbucket.org/raphaelmutschler/calibreserver/issues/19/add-license-file

**Comment by cervinko** [comment]
https://github.com/mutschler/calibreserver/issues/1
mutschler added gplv3

**Comment by mutschler** [comment]
ah... well didn't saw this one here. but as mentioned above i've added a GPL v3 License

**Comment by janeczku** [comment]
Closed in fe1ab44a58295889fce1495603d7a05cdfebe475
