### ISSUE TITLE
can't change cover

### ISSUE THREAD

**Issue by SkqLiao** [janeczku/calibre-web#1204]
I can't change cover neither by upload jpg nor enter url.
But there is no log info..
So I don't know what's wrong...

**Comment by SkqLiao** [comment]
sorry, it suddenly works after several tries.

**Comment by SkqLiao** [comment]
It's only succeeded once. I added six books and edit their covers. Now five of them are still "cover not available"

**Comment by OzzieIsaacs** [comment]
I know this problem from caching issues by the browser. Could you please try to open the calibre-web in a private-tab (if possible in your browser). Could you please also check if the cover file is present on the hard disk. If not it would be nessecary to know more about your system: docker yes/no, python version, calibre-web version, operating system, ...

**Comment by SkqLiao** [comment]
> I know this problem from caching issues by the browser. Could you please try to open the calibre-web in a private-tab (if possible in your browser). Could you please also check if the cover file is present on the hard disk. If not it would be nessecary to know more about your system: docker yes/no, python version, calibre-web version, operating system, ...

Thank you for your reply. I opened calibre-web in a private tab and all the covers appeared! It worked. I think I need to press "CTRL + F5" after changing the covers.
Thanks again!
