### ISSUE TITLE
[Feature Request] List view

### ISSUE THREAD

**Issue by rodalpho** [janeczku/calibre-web#1207]
The very large thumbnail view is attractive but wastes space and doesn't convey much information.

I would prefer a simple list view, with the cover thumbnail, title, author, series, and date added.

**Comment by Gentleman03** [comment]
+1

**Comment by gorgobacka** [comment]
Would this be difficult to implement?

For my use case, the title, the author and tags are much more important than the cover. And a list view would give them much more space.

**Comment by OzzieIsaacs** [comment]
The covers are now replaced with thumbnails to activate this feature please follow the steps below:
- Please update to the newest nightly version
- Install APScheduler via pip
- Restart Calibre-Web
- Go into admin section enter edit schedule task settings, enable "Generate Book Cover Thumbnails", change the regular update time if you want (only needed for sideloaded books via Calibre), save setting
- go to admin section Click on Refresh Cover Thumbnnail cache
- Check Tasks section and wait some minutes until all thumbnails are generated

Furthermore there is a list view (I decided to have it without covers) which can be activated from the normal users visibility configuration. For me the request is now done, I will close it with the next release
