### ISSUE TITLE
[Feature Request] Series Name & Number

### ISSUE THREAD

**Issue by RottenRonnie** [janeczku/calibre-web#1208]
Default display could show the Series Name & Book number in addition to current data:
Cover art
Book title
Author

**Change to:** 
Cover art
Book title
Series Name (hot linked)
Series Book Number
Author

Thanks for taking the time to consider this change. I'm very pleased with Calibre-Web.

**Comment by Knepherbird** [comment]
I've been thinking about this for a while and finally started digging into the code and created pull request #1443  
Comments and criticisms are welcomed.

**Comment by RottenRonnie** [comment]
Thank you so much! 

While Linuxserver.io has not included the update in the official docker image, I was able to copy your commit to the css and html files within my docker container and now I can see the series title and number. Fantastic! 

Thank you! 

![2020-06-26 14_21_42-Calibre-Web _ Discover (Random Books)](https://user-images.githubusercontent.com/10812745/85885673-1b1eeb80-b7bb-11ea-97f8-7292c4427fd7.png)
