### ISSUE TITLE
Live update possibility for the Library

### ISSUE THREAD

**Issue by Varabaiba** [janeczku/calibre-web#1209]
Hi, I did my best to find similar issue, but none of related to update (like #1130 or #0042) seems to relate to mine.
I have synced folders for Calibre app and calibre-web. When I add new books to the app and try to sync with another folder for web, I'm having trouble rewriting metadata.db as it seems to be locked by the calibre-web script. Thus, I have to stop/start calibre-web every time I add books. Not to mention that in my case cps.py doesn't respond to ctrl+c and I'm actually killing the process, IMO this is not a best possible behavior. Also I'm curious what do those ppl do, who have one folder for both, how do they use calibre app, if calibre-web locks metadata.db
This may be lame misunderstanding from my side or improper setup and I would be happy to get some guidance, but if calibre-web really locks metadata.db entire running period, is it possible to change this to read, cache, close behavior and for the sake of updates, add some "refresh/resync" button (as there would be no chance to see updated list anyways in case of blocking exists).
Thanks

**Comment by Gentleman03** [comment]
I'm using calibre while calibre-web is running and everything works fine. I can add new books to calibre and edit them and changes show instantly in calibre-web. But i use the same lib for calibre and calibre-web.

**Comment by Varabaiba** [comment]
@Gentleman03 thanks a lot. It seems something is wrong with how I have it set up. Would look into details.

**Comment by OzzieIsaacs** [comment]
If you need additional help, we need a much more details description about your environment, where you exactly have your files and what exactly you are doing.
Regarding crtl+c: This is possible depending on your operating system and your Calibre-Web version.
In the admin section there is a button "reconnect calibre database" for reconnecting the database. Up to now I could no reproduce any case where this button is needed (except using docker container), but you can try your luck with it.

**Comment by sbelongie** [comment]
I just started having an issue like this as well.  I never had an issue until today.  I added a book to Calibre Type MOBI and it does not show up on the web.  If I add an epub it works fine.  Not sure if something like that has an issue.  Let me know how I can help troubleshoot.
