### ISSUE TITLE
How to back up calibre settings and user data

### ISSUE THREAD

**Issue by Ju-ch** [janeczku/calibre-web#1212]
When I want to upgrade my VPS, what files do I need to back up to keep my settings data and user data. I tried copying the `app.db` file, because there seems to be basic information about the user, but when I overwrite the new ** app.db **, calibre-web fails to start.

**Comment by OzzieIsaacs** [comment]
English please. Otherwise I will close the issie. Thank you for your understanding

**Comment by OzzieIsaacs** [comment]
https://github.com/janeczku/calibre-web/wiki/FAQ#how-to-backup-calibre-web-settings

There are mechanisms to convert the settings from old installation to new installations. If your installation was to old (more than 1.5 year + I guess) it might fail. 
Please tell me the following as starting point
Python Version:
Operating System:
Docker [yes/no]:
Which docker:
Which Calibre-Web version: 
What is the exact error message: 
What does the logfile state:

**Comment by Ju-ch** [comment]
> Please tell me the following as starting point
> Python Version:
> Operating System:
> Docker [yes/no]:
> Which docker:
> Which Calibre-Web version:
> What is the exact error message:
> What does the logfile state:


Python Version : **3.6.9**;
Operating System : **Ubuntu18.04**;
Docker : **NO**;
Calibre-Web version : **V0.6.5 - Kira**.
That's all for the log: 
```
[2020-02-22 21:00:10,312] INFO {CPS :89} Starting Calibre Web...
[2020-02-22 21:00:10,415] INFO {cns.server :152} Starting Tornado server on :443
WARN {tornado. General :1407} SSL Error on 13 ('171.82.154.145', 51317): [SSL: HTTP_REQUEST] HTTP request (_ssl.c:852)
WARN {tortor.general :1407} SSL Error on 13 ('171.82.154.145', 51345): [SSL: HTTP_REQUEST] HTTP request (_ssl.c:852)
WARN {tornado. General :1407} SSL Error on 13 ('171.82.154.145', 51247): [SSL: HTTP_REQUEST] HTTP request (_ssl.c:852)
WARN {tortor.general :1407} SSL Error on 13 ('171.82.154.145', 51316): [SSL: HTTP_REQUEST] HTTP request (_ssl.c:852)
[2020-02-22 21:8:47,001] INFO {cps.server:194} webserver stop (restart=False)
[2020-02-22 21:8:54,662] INFO {cps.server:179} Performing shutdown of calibre-web
ERROR {asyncio:1285} Task was destroyed but it is pending!
Task:
< Task pending coro = < HTTP1ServerConnection. _server_request_loop () running at/home/juch/Calibre/cp - web/vendor/tornado/http1connection py: 809 > cb = [IOLoop. Add_future. < locals >. < lambda > the at ()
/ home/juch/Calibre/cp - web/vendor/tornado/ioloop py: 690] >
```
All I did was overwrite the current Ubuntu app.db file with an app.db file on another server.

**Comment by OzzieIsaacs** [comment]
This is what I get on accessing a calibre-web instance with activated ssl if I access it via http:
![grafik](https://user-images.githubusercontent.com/6438895/75093384-7331b100-5581-11ea-9e2b-c9acc56e94c1.png)
so I think you messed up http and https, you should access it via https://....

**Comment by OzzieIsaacs** [comment]
You could start Calibre-web via: `python3 cps.py -k "" -c ""`, this should deactivate ssl, afterwards you could access it via normal http, by using: http://[ip-address]:443. (Worked for me in Chromium, but not in firefox), and figure out what's wrong

**Comment by Ju-ch** [comment]
我正在尝试使用http而不是https，看来事情确实是您说的那样，不过既然**app.db**包含了所以的**calibre-web**设置，在我的另一台Ubuntu上使用`https://myDomain`是可以的，现在看起来在我的新的Ubuntu上它不能这样。

**Comment by Ju-ch** [comment]
I'm trying to use **HTTP** instead of **HTTPS**, so that's exactly what you said, but since app.db includes all your calibre-web Settings, it's ok to use `https://myDomain` on my other Ubuntu, and it doesn't look like it can on my new Ubuntu.

**Comment by OzzieIsaacs** [comment]
Have you also copied your ssl files to the new server? What is the error message if you access it via https? I'm doing several automated tests with ssl, it's definitively working.

**Comment by Ju-ch** [comment]
I almost copied the contents of the original Ubuntu to the new Ubuntu, as well as my SSL certificate and key, and kept them in the same location.

**Comment by OzzieIsaacs** [comment]
I don't know. The only thing I could offer you is you send me the ssl files and the app file via private email message (address on my profile page) and I take a look into it. (You need to trust me, I will not use it for anything else than checking whats wrong and delete the files afterwards.) I don't need you password, as I can change it to my on password within the app.db file. Otherwise I don't know how to help.You also could start all over again and configure Calibre-Web from beginning.
