### ISSUE TITLE
CalibreWeb will not start (module 'signal' has no attribute 'SIGQUIT')

### ISSUE THREAD

**Issue by rg9400** [janeczku/calibre-web#1217]
**Describe the bug/problem**
Calibre Web will not start with Python 3 anymore. Error below

```
c:\CalibreWeb>python cps.py
Traceback (most recent call last):
  File "cps.py", line 34, in <module>
    from cps import create_app
  File "c:\CalibreWeb\cps\__init__.py", line 71, in <module>
    web_server = WebServer()
  File "c:\CalibreWeb\cps\server.py", line 58, in __init__
    signal.signal(signal.SIGQUIT, self._killServer)
AttributeError: module 'signal' has no attribute 'SIGQUIT'
```

**To Reproduce**
1. Grab latest version. I believe I tried updating to this commit 32a6beae65248060dbbe5c59110288f3f866d026
2. Try to start CalibreWeb with python3

**Expected behavior**

**Screenshots**
CalibreWeb would start

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.8.1
 - Calibre-Web version [e.g. 0.6.5 or master@16.02.20, 19:55 ]: Not sure how to find the version, but it was the latest update prior to this post (32a6beae65248060dbbe5c59110288f3f866d026)

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy]

**Comment by OzzieIsaacs** [comment]
It's fixed again, did some mismerging this morning. Please update to release 0.6.6 or the newest master commit

**Comment by rg9400** [comment]
That fixed it, thanks!
