### ISSUE TITLE
UI configuration has no tags for mature content options

### ISSUE THREAD

**Issue by zaw007** [janeczku/calibre-web#1222]
UI configuration has no tags for mature content options。My calibre-web version is 0.6.7。Is this feature gone？

**Comment by OzzieIsaacs** [comment]
The feature isn'T gone, it's extended. Some users wanted to have per user based restrictions. So now you can allow and deny tags per user (admin -> user setup, last button above submit button):
![grafik](https://user-images.githubusercontent.com/6438895/75260000-336d0280-57e9-11ea-90ed-29e7f655f0f0.png)
And you can also allow and deny content based on Calibre-Custom Columns

**Comment by zaw007** [comment]
Thanks
