### ISSUE TITLE
Setting up fake worker failed: "Cannot read property 'WorkerMessageHandler'

### ISSUE THREAD

**Issue by atrezonator** [janeczku/calibre-web#1223]
Describe the bug/problem

when trying to open pdf - errors
PDF.js v2.2.228 (сборка: d7afb74a)
Сообщение: Setting up fake worker failed: "Cannot read property 'WorkerMessageHandler' of undefined".
It`s not working on chrome, edge, opera. But work on Firefox
p/s on ver 6.5 works fine.

Environment (please complete the following information):

Linux: centOS8, python3
Calibre-Web version 6.6
Browser Firefox,Chrome,edge,opera
Thanks

**Comment by GamerNoTitle** [comment]
The same

---The Following are the messages---
PDF.js v2.2.228 (build: d7afb74a)
信息：Setting up fake worker failed: "Cannot read property 'WorkerMessageHandler' of undefined".

--Environment---
Windows Server 2016 Datacenter, Python 3.6.6
Calibre-Web Version 0.6.7 Beta
Browser Google Chrome

**Comment by OzzieIsaacs** [comment]
You are allowed to guess one time which browser I tested it on....

**Comment by OzzieIsaacs** [comment]
The old code didn't work on Firefox anymore, so I changed it back to the original one (which is older than the old one). It's some sort of timing problem, but the pdf.js website is not very clear on how to start the reader best way.

**Comment by SerinitySW** [comment]
I'm also experiencing this.

`PDF.js v2.2.228 (build: d7afb74a) Message: Setting up fake worker failed: "Cannot read property 'WorkerMessageHandler' of undefined".`

Chrome web browser, Calibre-Web version 0.6.7 Beta (LinuxServer Docker) on unRaid.

**Comment by brooksvb** [comment]
Exact same error as above. I noticed that it works for some pdf files but not for most. Not sure what the difference is between the working and non-working ones.

**Comment by amuro9999** [comment]
我发现pdf.js与google翻译插件不兼容，删除goolge翻译插件就可以正常在线预览了

> Describe the bug/problem
> 
> when trying to open pdf - errors
> PDF.js v2.2.228 (сборка: d7afb74a)
> Сообщение: Setting up fake worker failed: "Cannot read property 'WorkerMessageHandler' of undefined".
> It`s not working on chrome, edge, opera. But work on Firefox
> p/s on ver 6.5 works fine.
> 
> Environment (please complete the following information):
> 
> Linux: centOS8, python3
> Calibre-Web version 6.6
> Browser Firefox,Chrome,edge,opera
> Thanks


I found that pdf.js is not compatible with the google translation plugin for chrome. Delete the goolge translation plugin for chrome and I can preview online normally.


edge chromium
win10 ltsc 2019

**Comment by GamerNoTitle** [comment]
> > Describe the bug/problem
> > when trying to open pdf - errors
> > PDF.js v2.2.228 (сборка: d7afb74a)
> > Сообщение: Setting up fake worker failed: "Cannot read property 'WorkerMessageHandler' of undefined".
> > It`s not working on chrome, edge, opera. But work on Firefox
> > p/s on ver 6.5 works fine.
> > Environment (please complete the following information):
> > Linux: centOS8, python3
> > Calibre-Web version 6.6
> > Browser Firefox,Chrome,edge,opera
> > Thanks
> 
> I found that pdf.js is not compatible with the google translation plugin for chrome. Delete the goolge translation plugin for chrome and I can preview online normally.
> 
> edge chromium
> win10 ltsc 2019

But i didn't install a Google Translation on my chrome......

**Comment by OzzieIsaacs** [comment]
I think I fiexed it, please try and give feedback if the problem is solved.
If you find new different problems, please open a new issue and do not discuss this in this issue, thanks.

**Comment by GamerNoTitle** [comment]
the pdf reader worked, thank you :-)

**Comment by iyakrivas** [comment]
any help for this version PDF.js v2.4.456 (build: 228a591c) for the same error
