### ISSUE TITLE
[CBR] Unable to get cover image from CBR files (CBZ ok)

### ISSUE THREAD

**Issue by wanoo** [janeczku/calibre-web#1225]
**Describe the bug/problem**
When upload a CBR (Rar comics book archive) calibre-web didn't get the cover. On calibre directly i don't have this issue. 

I use Docker image from linux server, witch got unrar is install (not found where i can set the unrar path like it said on README.md)

**To Reproduce**
1. Upload a CBR
2. No cover
3. Convert to CBZ
4. upload it
5. Got cover

**Expected behavior**
Normally i should have some cover, like with the CBZ

**Environment (please complete the following information):**
 - Docker : linuxserver/calibre-web:amd64-latest
 - Calibre-Web version 6.6
 - Browser FF & Chrome

Thanks

**Comment by OzzieIsaacs** [comment]
I was a bit concerned about adding the ability to calibre-web to execute random executables on the hard disk just be pointing on them in the Web-UI, so I removed the rar support, but being inconsistent I left the Calibre executable.
You are right, it should work as you suggested it.

**Comment by OzzieIsaacs** [comment]
And thanks for filling out the bug form, it helps a lot to figure out the problem, but up to now not everybody got the benefits...

**Comment by wanoo** [comment]
No problem at all,

i try to made calibre-web my comics collections, so i'll try to propose some pull request for the scrapping meta data.

regards
