### ISSUE TITLE
[Enhancement]: comment system

### ISSUE THREAD

**Issue by flashlab** [janeczku/calibre-web#1230]
**Is your feature request related to a problem? Please describe.**
Add comment system.
motivation: 1) Since the register module is very mature, a comment system will enhance the social attributes. 2) Users can regard it as a note board to collect extra info.
**Describe the solution you'd like**
I'd like to choose two pluggable system: [Valine](https://github.com/xCss/Valine) and [Gitalk](https://github.com/gitalk/gitalk).
And land the comment block under detail book page. Admin can control the permission of display/hide - the same logic as role_edit.
Because I'm not familiar with python, Maybe I can refer to f70c839014031541f6243747967d9d3b34a8bdfe while building the patch.

**Describe alternatives you've considered**

**Additional context**
I'm not sure if old users can update such patch smoothly cause it'll modify the structure of database.

**Comment by OzzieIsaacs** [comment]
I don't think this is within the scope of the project. 
Calibre-Web is a web Interface to manage/read/store your personal books and not to interact/exchange with other users on ebooks. 
You are free to add this functionality to your Calibre-Web instance, but I currently don't think I will merge this to the project.
