### ISSUE TITLE
[Feature] Add support for OpenID Connect as auth provider.

### ISSUE THREAD

**Issue by OrwillT** [janeczku/calibre-web#1232]
Add support for OIDC.

**Comment by OzzieIsaacs** [comment]
I decided to not add more login provider or storage provider, to focus on the main purpose of Calibre-Web

**Comment by krohrsb** [comment]
I would ask one to reconsider. Implementing the openid connect spec will offload the responsibility of login providers to an external application. Things like authentik and authelia. It would be quite helpful such that you could SSO in via a social login (for example) without also requiring a separate calibre web user account.

**Comment by ajn142** [comment]
Howdy @OzzieIsaacs I wanted to ask again to consider reopening this. It looks like it would be relatively straight-forward to implement this using this https://github.com/fedora-infra/flask-oidc/ library (meaning beyond my meager Python but I’d bet there’s someone both interested and capable). That would allow offloading requests for any future login providers to the OIDC provider’s federation/social login support, e.g, using Discord via Authentik https://goauthentik.io/integrations/sources/discord/ . Not saying you have to be the one to implement it or put it on any roadmap, but I think having an issue to focus efforts and PRs on would help any community efforts at implementation.

**Comment by ajn142** [comment]
Ack, I apologize for badgering here. On further digging I see there’s a PR #2211 for exactly this where you outlined an acceptable path forward for folks who want the feature to implement it in a way that doesn’t cause you undue support burden. Linking in the hopes that it focuses effort on us implementing the feature rather than bothering you.
