### ISSUE TITLE
Is it doable on a dedicated web server ? [BEGINNER]

### ISSUE THREAD

**Issue by WilfriedJ** [janeczku/calibre-web#1233]
Hi, so i'm new to code (only few experiences with setting a wordpress localhost).

So my question is this : 

i have an unlimited database + FTP offer, and i was wondering if there was any ways for me to install calibre web server on oen dedicated domain name i have.

Like when i want to read a book when i'm in my bed or traveling for example, i just have to go to https://calibre.thewebsite.fr

Because from everything i saw this is only for localhost if i'm right ?

**Comment by XiovV** [comment]
If you want to access it from calibre.thewebsite.fr then you need to: 
1) Set up calibre-web on your server
2) Set up a reverse proxy: [reverse proxy wiki post](https://github.com/janeczku/calibre-web/wiki/Setup-Reverse-Proxy)
3) Make sure the calibre subdomain is pointing to the right address (the server on which you are hosting calibre-web)

**Comment by OzzieIsaacs** [comment]
In general I agree to @XiovV. 
What you need would be a "dedicated host", I don't know if this what you mean with "dedicated domain". There is no need for a database (but normally included in this type of offers). The Calibre database Calibre-Web needs to function is "just" a file.
You need to transfer all your books to this dedicated server and you should have python (version 3.x at best) installed on this server.
I'm not sure if you really need a reverse proxy (access several services on one port like http://your.do.main/one,   http://your.do.main/two instead of  http://your.do.main:8000,  http://your.do.main:8001), but what I recommend would be using encryption (SSL) to access the server, but you could add this later, after you set up everything else.

**Comment by WilfriedJ** [comment]
Thanx for your spead of answer ! Yes i mean dedicated host :p

So all i need is to install Python on a file on my ftp and then extract the calibre-web-server zip and that's all ?

Because i tried to do that for the last night : Here is what i did : 
- Create a separate file
- upload calibre-web-server.zip
- Extract
- Follow the SSH guidelines on the readme.md file

And then i didn't knew where/how to acces my calibre web server

Like i don't know what URL to use...

I tried with the subdomain i allowed to the file, but when i charged it i was only displayed "Congrats, Python is installed and works succesfully)

This was a subdomain and not a domain, do you think that this could have been the main problem with this ?

**Comment by WilfriedJ** [comment]
> If you want to access it from calibre.thewebsite.fr then you need to:
> 
> 1. Set up calibre-web on your server
> 2. Set up a reverse proxy: [reverse proxy wiki post](https://github.com/janeczku/calibre-web/wiki/Setup-Reverse-Proxy)
> 3. Make sure the calibre subdomain is pointing to the right address (the server on which you are hosting calibre-web)

Didn't saw your answer

So what you basically mean is that in any way i can't just install calibre on the hosting i have to access it freely ? 

I'll always need to have my PC turned ON to acces it ?

**Comment by OzzieIsaacs** [comment]
Create a separate file -> created a seperate folder on the server?
Follow the SSH guidelines on the readme.md file?? setup guidelines?
Normally (often, maybe) your server should run under some sort of linux. You should be able to acces the server via ftp (you can upload and download files from your local drive) and via ssh (you get a shell with some sort of prompt like "user@server ~ $" and you can execute commands) If the pip command runs smoothly without any errors you afterwards should be able to start calibre web via the command in 2.) in the installation instructions. Calibre-web starts silently, so no output. if you start it with nohup line you should get your prompt back and can check that there is a logfile name calibre-web.log in the root folder, the content (nano calibre-web.log could work for viewing the file) should include a line starting calibre-web and there should be no errors. 
Afterwards you should be able to access calibre-web. You should have a domain name like yourawesomedomain.com or subdomain.hostingprovider.com, where you upload the files and connect to it. To access calibre-web it would be http://yourawesomedomain.com:8083 http://subdomain.hostingprovider.com:8083.
I tried with the subdomain i allowed to the file, but when i charged it i was only displayed "Congrats, Python is installed and works succesfully) No idea, screenshot please of the whole page, please erase domainname in the brwoser and ensure that no other private information is visible, any crazy long strings with letters and number are not good to show

**Comment by OzzieIsaacs** [comment]
So what you basically mean is that in any way i can't just install calibre on the hosting i have to access it freely ? Calibre is a different program, I'm talking about Calibre-Web, and yes if you install it on the server and ensure that the program is running you can access it from anywhere in the world as long as you have internet access.
I'll always need to have my PC turned ON to acces it ? No, as long as calibre-web is running on the server you can access it from any computer in the world with internet access.

**Comment by WilfriedJ** [comment]
> Create a separate file -> created a seperate folder on the server?
> Follow the SSH guidelines on the readme.md file?? setup guidelines?
> Normally (often, maybe) your server should run under some sort of linux. You should be able to acces the server via ftp (you can upload and download files from your local drive) and via ssh (you get a shell with some sort of prompt like "user@server ~ $" and you can execute commands) If the pip command runs smoothly without any errors you afterwards should be able to start calibre web via the command in 2.) in the installation instructions. Calibre-web starts silently, so no output. if you start it with nohup line you should get your prompt back and can check that there is a logfile name calibre-web.log in the root folder, the content (nano calibre-web.log could work for viewing the file) should include a line starting calibre-web and there should be no errors.
> Afterwards you should be able to access calibre-web. You should have a domain name like yourawesomedomain.com or subdomain.hostingprovider.com, where you upload the files and connect to it. To access calibre-web it would be http://yourawesomedomain.com:8083 http://subdomain.hostingprovider.com:8083.
> I tried with the subdomain i allowed to the file, but when i charged it i was only displayed "Congrats, Python is installed and works succesfully) No idea, screenshot please of the whole page, please erase domainname in the brwoser and ensure that no other private information is visible, any crazy long strings with letters and number are not good to show

1. Yes a separate Folder sry
2. I followed the Quick Setup : 
- pip3 install --target vendor -r requirements.txt
- python cps.py

Ok for everything, so i'll delete everything and re-start from scratch and then i'll post an update

Thank you very much for your time this is really kind !

**Comment by OzzieIsaacs** [comment]
If you came that far, I don‘t see any reason for deleting anything, python3 cps.py might be safer as last line, If you used pip3. Just check if you can access it

**Comment by OzzieIsaacs** [comment]
After you started it, if you disconnect your computer with python command from the server, the server will close the program upon disconnect (nohup python3 cps.py is the command of Choice in this state)

**Comment by WilfriedJ** [comment]
So i deleted everything as i saw your message too late :p

Reinstalled everything, Upload the zip file and extracted everything

Instaled Python 3 (trough cPanel)

Logged into the SSH terminal, did 1) and 2)

Went to the log file and saw this : https://prnt.sc/r95dd7

Unfortunately i have an error "Adress already in use"

I also have to configure somehting (i think) on the cpanel side for the basic settings of Python : https://prnt.sc/r95i4l

Do you think i've done everything right ?

**Comment by OzzieIsaacs** [comment]
Looks like to old instance is still running. Please press the restart button.
Afterwards you sould beable to press the open button on the page -> add :8083 to the address you got to and you should see the starting page.
The only thing left it to upload the calibre database (metadata.db) with your books (all subfolders to the metadata.db) and then point to this location on the calibre-web start page

**Comment by OzzieIsaacs** [comment]
Python 3.3.7 is rather old, if you encounter problems (traceback text in logfile) and there is the choice of a newer version please try installing it.

**Comment by WilfriedJ** [comment]
I installed Python 3.7.3 + Restarted the app

And now the error message changed and display that : https://prnt.sc/r95psb

**Comment by OzzieIsaacs** [comment]
Okay, the last output was better. This is something from your provider, I don't know. Did you also install everything with the new python version (the run pip command)? Normally the pip installation has to be done with every python version you want to use.
Could you please doublecheck that you are allowed to open a server port 8083 (to avoid that address already in use means access forbidden)

**Comment by OzzieIsaacs** [comment]
What looks a bit suspicous to me is the application entry point setting. Looks for me like you are using some sort of framework to run calibre-web in (which I don't know will work). I don't know what exactly is happening on the server by doing the config settings. A command line would give me much more confidence

**Comment by OzzieIsaacs** [comment]
You could try to remove the application entrypoint setting (as calibre-web brings it's own wsgi server with it and also routines to start and stop it and doing some starting routines before)

**Comment by WilfriedJ** [comment]
So i upgraded the pip version to the latest + Rerun 1) and 2)

The error code is still the same

OFr the framework i just have configured the "Web application" 

I tried to delete the application entry point but unfortunately i had an error message saying "--entry-point option is requires --startup-file option for interpreter python"

Bu i also have access to the ssh, so i can also add code lines through the SSH interface

**Comment by WilfriedJ** [comment]
> You could try to remove the application entrypoint setting (as calibre-web brings it's own wsgi server with it and also routines to start and stop it and doing some starting routines before)

Do you know the file ? I tried to put "passenger_wsgi.py" but nothing different seems to be hapening

i also have a question on when you asked me to ensure that i was allowed to create ports ? What do you mean by that ?

**Comment by OzzieIsaacs** [comment]
Webserver is not the right choice, it expects to run calibre-web as extension to a webserver. Do we have standaone program or something like that as option?

**Comment by WilfriedJ** [comment]
> Webserver is not the right choice, it expects to run calibre-web as extension to a webserver. Do we have standaone program or something like that as option?

I'm sorry but i didn't understood ..

**Comment by OzzieIsaacs** [comment]
Sorry I meant web application was not the right choice for starting calibre-web. Can you configure something different than web application? (The ports question is obsolete, if it works like I think)

**Comment by OzzieIsaacs** [comment]
If not, we should start all over again from ssh command line.

**Comment by WilfriedJ** [comment]
Thsi is the dashboard i have when i go on CPanel > Setup Python App : https://prnt.sc/r962d3

I'm completely in if we need to restart it's mainly you and you'r will, me i'm 100 % in

**Comment by OzzieIsaacs** [comment]
Maybe we continue this via e-mail and we can exchange more private information. My e-mail address is on my profile page. Please tell me in the email your provider and if there are different options which linux you are using. I can then try check if's basically possible to run a standalone application and if there is a firewall, or if you are caught to a webserver plugin (which doesn't work with calibre-web)

**Comment by Wilfried-1** [comment]
Hi,

Can we delete this thread please ?

**Comment by OzzieIsaacs** [comment]
The thread is closed, issues can‘t be deleted, so this is the final state

**Comment by Wilfried-1** [comment]
Ok, and i can't delete the Screenshots's URL neither ? :(

**Comment by OzzieIsaacs** [comment]
I removed the screenshots. (You should be able also to edit your posts, but you can't delete the whole thread)
