### ISSUE TITLE
Domain limit for registration stopped working

### ISSUE THREAD

**Issue by elfcan** [janeczku/calibre-web#1239]
Hello,

Domain limitation for registration had been working without a problem until recently. Now it's not working. SMTP is configured and domain limit is configures as seen on the screenshot:
![Selection_616](https://user-images.githubusercontent.com/2270993/75658694-d0acb880-5c79-11ea-9447-fd3f7f8644c7.png)

When we try to register with kodgemisi.com mail account we see this error:
![Selection_617](https://user-images.githubusercontent.com/2270993/75658789-f0dc7780-5c79-11ea-9d8a-df755a3d7018.png)

On the logs there is only this info:
[2020-03-02 11:29:57,231]  INFO {cps.web:1121} Registering failed for user "tttesssttt" e-mail adress: tttesssttt@kodgemisi.com

Am I missing something? Could you kindly help please?
Thanks.
Elifcan

**Comment by OzzieIsaacs** [comment]
Yes, I  indeed changed the behavior recently. It's no possible to also limit parts of the email adress itself (like only familyname@domain.com). 
The "new" allowed domain for your usecase would be "*@kodgemisi.com"

**Comment by elfcan** [comment]
Thanks, it works now. 

Best,
Elifcan
