### ISSUE TITLE
[Enhancement] Textual input for tags and/or an option to collapse tags on advanced search

### ISSUE THREAD

**Issue by utkuozdemir** [janeczku/calibre-web#1240]
I have a Calibre library where everything is organized with tags. In total, I have more than a hundred of tags, with potential of reaching a thousand.

When I go to advanced search, they are listed twice, once for including them in the search and one for excluding them from it.

This makes advanced search screen counter intuitive.

I suggest a feature that handles a big number of tags in a nice way. For example, it can be a textual input for auto-completion - something like the one in this UX StackExchange post: https://ux.stackexchange.com/q/63285

To give an idea on how it looks currently
![image](https://user-images.githubusercontent.com/1465819/75762113-76276100-5d3a-11ea-94f4-a31c247d7153.png)

**Comment by OzzieIsaacs** [comment]
I see the problem

**Comment by OzzieIsaacs** [comment]
I almost got it.
We will have drop down lists with the posibility to search for tags and so on:
![grafik](https://user-images.githubusercontent.com/6438895/103215014-69e84200-4912-11eb-97cf-22a2ce587700.png)

**Comment by utkuozdemir** [comment]
Looks good, thank you for the work 🙏
