### ISSUE TITLE
Cannot edit allowed/denied tags/custom values on CaliBlur

### ISSUE THREAD

**Issue by rg9400** [janeczku/calibre-web#1247]
**Describe the bug/problem**
When using the caliblur theme, these settings do not trigger the proper popup. It works on the default theme. These settings do work on CaliBlur when setting for new users, but not for existing users.

**To Reproduce**
1. Switch to CaliBlur
2. Go to an existing user
3. Try to click the respective buttons

**Expected behavior**
A popup should appear, similar to the default theme

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.8.2
 - Calibre-Web version: 0.6.7 Beta - 5ba4801a79286ae23cd8fe7114351951faa876f6 - 2020-03-08T08:02:15+01:00
 - Browser: Edge 81.0.416.20

**Additional context**
Problem exists behind Reverse Proxy and local access
Also, what is the meaning of the setting `View Restrictions based on Calibre column`? This just has a dropdown with the option of `None` in the View Configuration setting. Not sure what it does and how to set it.

**Comment by OzzieIsaacs** [comment]
It's possible that the Caliblur! Theme isn't working. I didn't check it, the development of the Theme was done by @hexeth and @leram84. There are some more issues with this Theme.
Regarding the bonus question: 

> what is the meaning of the setting View Restrictions based on Calibre column? 

You can add restrictions based on tags (what you are try to use currently) and based on custom columns. This setting is made for selecting the custom column where the restrictions are taken from. If you see None as only option, you have no text content custom columns.
The restrictions are now on per user base, to change the restrictions of exisitng users you have to go to edit user and than you can edit the restrictions of this specific user.

**Comment by OzzieIsaacs** [comment]
It's indeed a problem with the Caliblur! Theme, my problem is, the original programmer seems to have currently other priorities, so work on the theme is stalled. The code is very complex, and hard to debug.
Currently I tent to deactivate it, as I can't support it.

**Comment by BeckyDTP** [comment]
Please leave the option to choose a dark theme or at least another (custom) than the standard one.

This issue is easy to fix.

Change line [366](https://github.com/janeczku/calibre-web/blob/24d755b12374bb3342e4b45ff3068ca78155e154/cps/static/js/caliBlur.js#L366):

`modalWanted = ['admin', 'editbook', 'config', 'uiconfig', 'me', 'edituser'];`

**Comment by hexeth** [comment]
Thanks @BeckyDTP , I've made a PR. 

Sorry @OzzieIsaacs , I've been slammed with a merger and now COVID-19. If there's any more fixes that are needed hit me direct and I'll do my best

**Comment by OzzieIsaacs** [comment]
@hexeth There are some more issues tagged with Caliblur! Theme, if you could have a look at it, this would be great.

Stay healthy
