### ISSUE TITLE
Hide custom columns?

### ISSUE THREAD

**Issue by deadman36g** [janeczku/calibre-web#1251]
Hello, I know this isn't technically a bug, but is it possible to hide the custom columns that I created with calibre?

**Comment by OzzieIsaacs** [comment]
Calibre-web can hide certain Columns like described in the wiki: 

Regular expression for ignoring columns and Link read/unread status to Calibre column:
If you having a bool custom column in Calibre you can use it as a "global" read/unread status (only usefull in single user environments) In this case you can select this column in the Link read status. After saving the Read/Unread selection on each book is read from this column and also saved to thi field in the calibre-database. Furthermore you should Enter this column name to the "Regular expression for ignoring columns", so the column isn't showing up twice in Calibre-Web.
Example: ".*" would exclude all custom columns, "Read" only the column with the name column, "^My\scol.*" all Columns starting with "My col".
There was a bug in this function which was fixed on January 27th

**Comment by deadman36g** [comment]
I am sorry If I am misunderstanding,

But I have put the following under "Regular expression for ignoring columns"
<img width="306" alt="Screen Shot 2020-03-12 at 11 36 51 PM" src="https://user-images.githubusercontent.com/3932793/76590319-a8635c00-64ba-11ea-8557-634e38da1c6f.png">

But yet the custom columns are still appearing for me.

**Comment by OzzieIsaacs** [comment]
The " in the manual should not be part of the text you are entering in the filed, so it should be .* for hiding everything

**Comment by deadman36g** [comment]
Ah, silly error on my part.

Thank you, the interface is now hiding the entries.
