### ISSUE TITLE
Don't convert the book format and send an email

### ISSUE THREAD

**Issue by RyanRaw** [janeczku/calibre-web#1252]
Now all books have to be converted to mobi to send emails, which is annoying. 
Can I send the email without converting the format of the book?.
Can I configure the email address when sending emails? I need to send the book to non-kindle users.

Above is google translation, sorry

**Comment by RafalHo** [comment]
Duplicate of #1054

**Comment by RafalHo** [comment]
I am also in favor of this solution.
Of course, I can use the "Send to Kindle" option, but then mobi files are sent by email, but epub files would be better.

Is there a chance to add such an option?
Alternatively, if you could add a choice, what format is to be sent?
