### ISSUE TITLE
When I read the .pdf books,I can't read!

### ISSUE THREAD

**Issue by flashliao** [janeczku/calibre-web#1254]
**Describe the bug/problem**
When I read the .pdf books,I can't read ,it shows!
PDF.js v2.2.228 (build: d7afb74a) ：Setting up fake worker failed: "Cannot read property 'WorkerMessageHandler' of undefined".

**Comment by OzzieIsaacs** [comment]
Duplicate of #1223. Please update to the newest commit version

**Comment by reavessm** [comment]
Similar issue on Vivaldi (chrome engine), works on FireFox.  Changed the update train from stable to nightly, updated, problem fixed.

Thanks for all the hardwork!
