### ISSUE TITLE
Comic viewer with webp support

### ISSUE THREAD

**Issue by gabmak** [janeczku/calibre-web#1255]
**Is your feature request related to a problem? Please describe.**
Webp images in CBZ unable to open/render in the Comic Reader
When I try to read a CBZ in the browser, seems like the webp files are not picking up after the unzip. I've tried both Chrome and IE but the same result.

**Describe the solution you'd like**
Comic Reader can display webp images in cbz 

**Additional context**

I'm using the latest docker from linuxserver/calibre-web
calibre-web is updated to the latest version (0.6.6)
Chrome version 80.0.3987.132

![image](https://user-images.githubusercontent.com/22220745/76411195-40cee300-63cc-11ea-9fd5-591ca83fa2b6.png)

**Comment by OzzieIsaacs** [comment]
It‘s correct, this is currently not implemented

**Comment by gabmak** [comment]
So is the currently supported image be jpg, png, gif, jpeg only?

**Comment by OzzieIsaacs** [comment]
I created an entry in the wiki for answering the question:
https://github.com/janeczku/calibre-web/wiki/FAQ#which-picture-formats-are-supported-in-the-comic-reader
(You've been missing svg, and the other formats are correct)
