### ISSUE TITLE
Forgot password function

### ISSUE THREAD

**Issue by stfrbrntyu** [janeczku/calibre-web#1257]
The forgot password function as it is now, is sure to give issues.
Any user can now just type in the user "admin" and reset the admin password.
If you don't have an smtp server setup the admin is locked out of the system.

I rather would see a function where the system sends you an e-mail first asking if you actually requested a password reset and by pressing a confimation link that a new password is sent to you.
Or even better a form where you can set your own password.

For now I will remove the forgot password button from the start page.

**Comment by OzzieIsaacs** [comment]
If your email server is set to mail.example.org the button will disappear on it's own (was a bug in earlier installations that the default value was wrong).
It's recommended to change the default admin user name, so everybody has to guess two things, or at least know more. 
Besides this, you are right, everybody can trigger  a reset password

**Comment by stfrbrntyu** [comment]
mail.example.org idd removes the button, didn't know that, thanks

.
