### ISSUE TITLE
[Enhancement] Change the max buffer size from 200MB to 512MB so that larger files can be uploaded

### ISSUE THREAD

**Issue by zapdap** [janeczku/calibre-web#1260]
This is my first time doing anything on github so if I am doing this incorrectly or if there is a better way to go about presenting this request please let me know.

I work with .cbz files that are often times 300+ MBs in size and when I tried to upload one through calibre web it gave me an error. I poked around in the logs and saw this.

`[2020-03-13 17:48:04,776]  INFO {tornado.general:289} Malformed HTTP message from (My Devices IP Address): Content-Length too long`

I googled around and found that tornado's file upload size limit is controlled by the max_buffer_size variable so I started poking around in the code.

I changed line 156 in the server.py file from 

`max_buffer_size=209700000`

to

`max_buffer_size=512000000`

and so far everything has been working perfectly.

I would like for this to be changed on master as well so that it hopefully won't inconvenience anyone else in the future.

I don't think that this will have any unintended consequences but then again I am pretty new to programming. If this change hurts more than it helps please let me know.

**Comment by OzzieIsaacs** [comment]
You found the right line in the code. 
My concern about increasing the upload limit to much higher values was about running into timeouts if uploading on very slow connections. But up to now, nobody complained about the limit and I had no time and idea how to test if it works properly.
Option without changing the code would be using gevent instead of tornado. Install it via: `pip3 install gevent`. After a restart you should see a line in the about section saying gevent version blabla. And  there should be no upload limit anymore (as far as I remember)

**Comment by zapdap** [comment]
You're right about this issue not being a common one. It's possible I am the only one who is hindered by it. I suggested the change so that anyone who is in my situation wouldn't be bothered by it in the future.

I didn't think about the possibility of it timing out on slow connections. I think I may be able to simulate a slow connection and see what tornado does whenever I try to upload a large file and pass my results onto here. Also thank you for the advice about using gevent instead of tornado! If I ever run into any issues I will give it a shot.

**Comment by klausmcm** [comment]
> You're right about this issue not being a common one. It's possible I am the only one who is hindered by it. I suggested the change so that anyone who is in my situation wouldn't be bothered by it in the future.
> 
> I didn't think about the possibility of it timing out on slow connections. I think I may be able to simulate a slow connection and see what tornado does whenever I try to upload a large file and pass my results onto here. Also thank you for the advice about using gevent instead of tornado! If I ever run into any issues I will give it a shot.

You're definitely not the only one. I also ran into this issue and made the change in the `server.py` file. Ideally, this should be something that can be configured externally such as in a config file. I couldn't find an open ticket for this issue.

**Comment by zanhecht** [comment]
I'll add my vote to making this configuable. I like to store m4b audiobook files in Calibre, many of which are hundreds of megabytes.

**Comment by crispybegs** [comment]
did this ever get looked at? i have a whole bunch of epubs that are like 2.1mb and they won't upload
