### ISSUE TITLE
Nohup doesn't work on Raspberry pi

### ISSUE THREAD

**Issue by orhanarifoglu** [janeczku/calibre-web#1262]
So when I run nohup cps.py & it doesn't run the CPS.py script. It only run it successfully when I run it as normal. However that means when I close the terminal script is gone. I tried various nohup combinations to redirect output and all but nothing works. Nohup works on other programs so I suspect it might be issue with calibre-web. Message I am getting is 

nohup: ignoring input and appending output to 'nohup.out'

And nothing happens in browser.

**Comment by OzzieIsaacs** [comment]
Doublechecked it. For me it's working. Using Raspian Buster. The output is correct. If you open the nohup.out file which is generated, you should see what you are doing wrong (the readme recommends `nohup python cps.py &` and not `nohup cps.py &`)
