### ISSUE TITLE
accessing book 10000 and higher returns empty response

### ISSUE THREAD

**Issue by anonuser12345** [janeczku/calibre-web#1268]
**Describe the bug/problem**
When attempting to access the url `/ajax/book/10000` the server returns an empty response

**To Reproduce**
1. add 10,000 books or more
2. access url `/ajax/book/10000`
3. observe empty response

**Expected behavior**
a valid json response

**Additional context**
is this a limitation of flask or calibre?

**Comment by anonuser12345** [comment]
calibre-web book id is not the same as the ajax book id

**Comment by anonuser12345** [comment]
ajax endpoint doesn't escape html. where you have html in the book comments, the request will return text content type. this code will get book tags and assign a class, so you could show an icon for books that are of a specific tag.

1. adding route to match book by book id:
```python
@app.route("/ajax/book/bookid/<string:book_id>")
@requires_basic_auth_if_no_ano
def get_metadata_calibre_companion2(book_id):
    entry = db.session.query(db.Books).filter(db.Books.id.like("%" + book_id + "%")).first()
    if entry is not None:
        js = render_template('json.txt', entry=entry)
        response = make_response(js)
        response.headers["Content-Type"] = "application/json; charset=utf-8"
        return response
    else:
        return {}
```

2. remove comments field from templates/json.txt 

3. adding js to get book ids on page, make ajax request to get book tags, and adding a class 
```js
var bookidarr = []
var bookarr = []
var bookids = $('.discover.load-more > .row .meta > a').each((i, a) => {
  bookidarr.push(a.getAttribute('href').replace(/\/book\//,''))
})


$('.discover.load-more > .row .meta > a').each(function(i, a) {
  var id = a.getAttribute('href').replace(/\/book\//,'')
  a.setAttribute('data-bookid', id)
})

async function genBookArr () {
  for (let id of bookidarr) {  
    var req = await fetch('/ajax/book/bookid/'+id)
    var res = await req.json()
    if (res && res.tags.includes('sometag')) bookarr.push(res.application_id)  
  }
  return bookarr
}

var assignId = async () => {
  const bookIds = await genBookArr()
  for (let bookId of bookIds) {
    $('.discover.load-more > .row .meta > a').map((i, anchor) => {
      if (anchor.dataset.bookid == bookId) $(anchor).parent().prev().addClass('someclass')
    })
  }
}

assignId()
```

**Comment by OzzieIsaacs** [comment]
?
What are you doing? I don't get it.

The json output is for a android program called calibre-companion. I can doublechek if the comments are need to be escaped, or calibre-companion is fine with this.

What is the purpose of the js code? I see no need for it, what's it for?

**Comment by OzzieIsaacs** [comment]
?
The opds feed doesn't use any javascript?

**Comment by anonuser12345** [comment]
needed to get book tags, and this was available in the ajax endpoint. didn't see a book endpoint in the opds routes. also opds returns xml. so to get a books tags by it's book id, this endpoint was needed. the current endpoint returns the calibre book id, not the flask book id. then the js above is to assign a class to the html container, where a book has the given tags. 

this is useful if you want to assign an icon to books that have a specified tag, for example.
