### ISSUE TITLE
find meta info error

### ISSUE THREAD

**Issue by VentionZong** [janeczku/calibre-web#1272]
![image](https://user-images.githubusercontent.com/24422173/77539286-160c8080-6edc-11ea-992b-871cb1b8ae79.png)

**Comment by VentionZong** [comment]
@OzzieIsaacs

**Comment by OzzieIsaacs** [comment]
There is already a fix on the way:  #1267

Do you have an (non-)working example for me?

I'm currently testing the autoupdater, so takes some time to merge the PR.

**Comment by VentionZong** [comment]
> There is already a fix on the way: #1267
> 
> Do you have an (non-)working example for me?
> 
> I'm currently testing the autoupdater, so takes some time to merge the PR.

This bug affects the experience，Hope to merge as soon as possible

**Comment by VentionZong** [comment]
@OzzieIsaacs When are you going to merge the PR?

**Comment by xcffl** [comment]
You may just use my branch for the time being

**Comment by VentionZong** [comment]
> You may just use my branch for the time being

I've already used the master branch
