### ISSUE TITLE
No sorting options in mobile browsers

### ISSUE THREAD

**Issue by himdo** [janeczku/calibre-web#1274]
**Is your feature request related to a problem? Please describe.**
When visiting the website on mobile you are allowed to search for books, but on mobile there is no way to sort you books in any sense. Currently I have some books that are numbered (eg. book 1, book2. ...) but when on mobile you can only see random books, and recently added books.

This issue is mitigated when you know the exact url (eg. root/abc/) but there isn't an easy way to get to this.

**Describe the solution you'd like**
I would like there to be the same interface as with desktop where you can choose which way to sort. This would preferably be on the top bar 

**Describe alternatives you've considered**
An alternate would be adding this to the search bar in some way.

**Additional context**
An easy way to test this is by going into your web dev settings on desktop and changing the browser settings to mimic a phone.

**Comment by OzzieIsaacs** [comment]
Currently the buttons are not visible on small screen (intentionally), because I thought they would consume to much space. 
As intermediate solution you could change the folowing files in cps/templates: list.html (line 5), index.html (line 56) and author.html (line 25)
`<div class="filterheader hidden-xs hidden-sm">`
to
` <div class="filterheader">`

**Comment by himdo** [comment]
It almost seems like dynamically setting the icon size would be a good solution. 
Form a quick google search it seems like the size of the icons is directly related to the font-size CSS variable. I'm not familiar with this web framework but you might be able to do this using `font-size: var(variable_name);` in the CSS. 
The only issue I see with this approach would be making the icons to small for very small screens to interact with this.
To fix this it might be best to use the normal size but hide it by default behind some sort of drop down bar which when clicked would toggle the visibility for the buttons.

**Comment by ComputerWolf** [comment]
I agree that having a way to sort on mobile would be extremely helpful as the default sort is usually not ideal. I would modify the theme files, but running it within docker makes that more of a challenge.

**Comment by ferboiar** [comment]
After two years since this was commented for the first time there is still no way to sorting the views in mobile browsing?

**Comment by OzzieIsaacs** [comment]
Thanks for pointing this out. It should be available since a view releases

**Comment by nraeth** [comment]
But where and how do I sort on a mobile device? I don't see any options for that?

And on the basic interface there aren't even categories.
