### ISSUE TITLE
Hide Send to Kindle for mobi files over 25mb

### ISSUE THREAD

**Issue by rg9400** [janeczku/calibre-web#1275]
**Is your feature request related to a problem? Please describe.**
Whenever a book has a mobi file over 25mb, users will often see and click the Send to Kindle button. This button tries to send an email to the user, but as far as I know, there's no real email client that will allow attachments over 25mb. These emails fail, and while they show up as failed under tasks, it is silent since I don't get an email or know that the task failed. Users also will not know that the email failed since it never got past my email client.

**Describe the solution you'd like**
Ideally, the Send to Kindle button should be hidden so users know that option is not available. As I understand it, 25mb would be a limit for specifically the files used to sent to Kindle (mobi only, right?). Unless there's some other method to send these larger files to users that I am unaware of. 

**Describe alternatives you've considered**
Maybe a notification email or some way to alert me that the task failed? I currently monitor the tasks, but that's not ideal.

**Comment by OzzieIsaacs** [comment]
duplicate #1141
