### ISSUE TITLE
Incomplete redaction of sensitive data

### ISSUE THREAD

**Issue by nate2014jatc** [janeczku/calibre-web#1278]
**Describe the bug/problem**
In your Wiki, on the Google Drive page, you have gone through the effort of redacting your domain name in almost every instance where it would be shown.
In the file `images/gdrive/google_allow.png` there is one instance that was not redacted. 
I thought I would alert you to this, in case you wanted to correct it.

**Comment by OzzieIsaacs** [comment]
Thanks, I think it's fixed
