### ISSUE TITLE
Kobo Readers don't download books through internal browser

### ISSUE THREAD

**Issue by guardiande** [janeczku/calibre-web#1279]
**Describe the bug/problem**
We have two Kobo devices (one Forma and one Aura). Both devices do not download books over the web GUI in the internal browser anymore. They did before and I'm not aware of changes.

Note:
* It worked before.
* It works with normal websites.
* It works on other devices (browser on MacBook, iPhones).
* The web server actually logs the download
```
93.218.x.x - - [30/Mar/2020:12:46:28 +0200] "GET /books/fiction/download/61/epub?anyname=61.epub HTTP/1.1" 200 872321 "-" "Mozilla/5.0 (Linux; U; Android 2.0; en-us;) AppleWebKit/538.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/538.1 (Kobo Touch 0377/4.20.14622)"
```

**To Reproduce**
1. Open the internal browser (settings > beta features)
2. Log on to the web GUI
3. Search for a book
4. In the details view click on the button with the available formats and choose epub
5. The button flashes but the download does not start.

**Expected behavior**
The typical download dialog should appear asking you for confirmation.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu 18.10
 - Python version 2.7.15 (default, Jan 24 2019, 16:32:39) [GCC 8.2.0]
 - Calibre-Web version 0.6.6, 0.6.7-beta, nightly
 - Docker container Technosoft2000 
 - Special Hardware [e.g. Rasperry Pi Zero]

**Additional context**
Accessed through reverse proxy

**Comment by OzzieIsaacs** [comment]
Under the hood some changes have been conducted 
The url for the download changed and the content header was changed, because of kindle problems. A downgrade to 0.6.6 could help
Another option would be using the brand new (and yet less documented feature) to sync the Kobo devices via Wifi.
I'll take a look at it, but have currently some other issues to work on and I'm busy on testing and improving the auto updater.

**Comment by guardiande** [comment]
I downgraded to 0.6.5 but that did not help.

Kobo sync sounds interesting but I would loose the ability to use the Kobo shop.

**Comment by guardiande** [comment]
Downgrading to 0.6.4 helps.

Besides the URL I don't see any differences between the headers.

**0.6.5**

```
GET /download/1207/epub?anyname=1207.epub HTTP/1.1
Host: ...
X-Forwarded-For: 93.x.x.x
X-Scheme: https
X-Script-Name: /books/fiction
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Linux; U; Android 2.0; en-us;) AppleWebKit/538.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/538.1 (Kobo Touch 0377/4.20.14622)
Accept-Language: de-DE, de;q=0.9, en;q=0.8, *;q=0.7
Cookie: remember_token=7|abaf4ed925e2bb36e678bb8d6ac60fae5593424384d052ab3d6892922b43df3db4e35cb15c2a34988ec8fd2dd4d0d61468cb634122b29bc1d; session=.eJxNjsFuwjAQRH-l8pkDmJwicQAZKkdaW4mWWt4LUklax8aXUJRoEf-Oj72O5s2bp7j8TMM9iPpvegwrcRl7UT_Fx7eoBUiTrNpLz4nN5ykANjeDXSYMmXLLVl0rgxSAmxFUl7xsRkJYA56Cz3pr8CottouPeuNZVxD1uvSikbC1roue-7JlErjzYnjPFPVCsY8QTfEcK8hfwTON3p1n6wqjjhty7QL8K8nRzeIhe4SZVNqJ10o87sP0_7-ZdyV_vQFSrErq.XoGeSg.beFvMwAMztjHdubi6WrSPzWWZM0
Accept-Encoding: gzip, deflate

HTTP/1.1 200 OK
Content-Type: application/epub+zip
Content-Disposition: attachment; filename*=UTF-8''My%20Book%201.epub
Vary: Cookie
Date: Mon, 30 Mar 2020 13:54:49 GMT
Transfer-Encoding: chunked
```

**0.6.4**

```
GET /download/1207/epub/1207.epub HTTP/1.1
Host: ...
X-Forwarded-For: 93.x.x.x
X-Scheme: https
X-Script-Name: /books/fiction
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Linux; U; Android 2.0; en-us;) AppleWebKit/538.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/538.1 (Kobo Touch 0377/4.20.14622)
Accept-Language: de-DE, de;q=0.9, en;q=0.8, *;q=0.7
Cookie: remember_token=7|abaf4ed925e2bb36e678bb23898b5f8d6ac6b4320fae5593424384d052ab3d6892922b43df3db4e35cb15c2a34988ec8fd2dd4d0d61468cb634122b29bc1d; session=.eJxNjsFuwjAQRH-l8pkDmJwicQAZKkdaW4mWWt4LUklax8aXUJRoEf-Oj5s2bp7j8TMM9iPpvegwrcRl7UT_Fx7eoBUiTrNpLz4nN5ykANjeDXSYMmXLLVl0rgxSAmxFUl7xsRkJYA56Cz3pr8CottouPeuNZVxD1uvSikbC1roue-7JlErjzYnjPFPVCsY8QTfEcK8hfwTON3p1n6wqjjhty7QL8K8nRzeIhe4SZVNqJ10o87sP0_7-ZdyV_vQFSrErq.XoGeSg.beFvMwAMztjHdubi6WrSPzWWZM0
Accept-Encoding: gzip, deflate

HTTP/1.1 200 OK
Content-Type: application/epub+zip
Content-Disposition: attachment; filename*=UTF-8''My%20Book%201.epub
Vary: Cookie
Date: Mon, 30 Mar 2020 13:58:08 GMT
Transfer-Encoding: chunked
```

**Comment by OzzieIsaacs** [comment]
Okay, the header was changed recently for 0.6.6 or 0.6.7 Beta, it's now:
`Content-Disposition: attachment; filename=My%20Book%201.epub; filename*=UTF-8''My%20Book%201.epub"`
But looks like the problem is what I was guessing, the filename is now a parameter and the kobo is not detecting this as a proper filedownload. I'lldoublecheck why I changed it and will revert it.

**Comment by guardiande** [comment]
Thank you!

**Comment by OzzieIsaacs** [comment]
I reverted my change, regarding the download route, it should now work again

**Comment by guardiande** [comment]
@OzzieIsaacs I can confirm that the nightly build version fixes the problem. Thank you!
