### ISSUE TITLE
Auto send book to kindle 

### ISSUE THREAD

**Issue by rajil** [janeczku/calibre-web#1280]
Hello,

I would like to auto-send book to kindle as soon it is added to calibre. Is it possible?

Thanks

**Comment by OzzieIsaacs** [comment]
No currently it's not possible and the usecases seems to me to small/less. You could send it to kindle via your email program and add it to calibre-web later, or add it and press the send button afterwards. Normally you don't add books every minute, so it should not consume so much time.
I'm thinking for a long time on a plugin system, so users could program their own stuff and realize features like this.
