### ISSUE TITLE
[REQ] Rename output MOBI files when send to Kindle (Metadata Plugboards)

### ISSUE THREAD

**Issue by javogiraldez** [janeczku/calibre-web#1285]
Any chance to add something like this "Calibre feature"? It's the best way to sort series in Kindle.

Thanks!!

![2020-04-01 01 14 10](https://user-images.githubusercontent.com/6696140/78085787-3648ad80-73bc-11ea-9769-830f44b895f4.png)

**Comment by OzzieIsaacs** [comment]
Could you please describe a little bit more what this "plugin" does and what you expect Calibre-Web to do? (What should be configurable). 
If it's a small project I can think of it. If it would be the screen like shown with corresponding big backend, it's a No.

**Comment by javogiraldez** [comment]
Hi Ozzie, thanks for the reply!

No, it doesn't need a new backend (I guess...).
Kindle it's the worst eReader when yo want sort book series (it doesn't have this option), so this option in calibre rename "on the fly" the ebook before sending by email, save to disk, download from server, etc. It takes the metadata info and generate a new file to send to mail, save or download but changing the name.

Here it's explained: [https://www.howtogeek.com/114063/how-to-use-calibre-to-correctly-order-your-ebook-series/](url)

Thank you!
Best regards.

# stayhome

**Comment by Villhellm** [comment]
Plugboards allow you to change the metadata of a file before sending to a device/emailing. This would allow you to actually change the display title/author on a Kindle when you send via email from the calibre-web frontend. Without plugboards it's kinda pointless to update the metadata before emailing to a Kindle as the changes are not reflected in the file that is sent.

**Comment by OzzieIsaacs** [comment]
There is a PR for changing the metadata of ebooks: #2497
