### ISSUE TITLE
internal server error while config 

### ISSUE THREAD

**Issue by linuxaman2020** [janeczku/calibre-web#1288]
```
Internal Server Error
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
cursor, statement, parameters, context
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 588, in do_execute
cursor.execute(statement, parameters)
sqlite3.DatabaseError: file is not a database
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2446, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1951, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1820, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1949, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1935, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/app/calibre-web/cps/web.py", line 206, in inner
return f(*args, **kwargs)
File "/app/calibre-web/cps/admin.py", line 255, in basic_configuration
return _configuration_update_helper()
File "/app/calibre-web/cps/admin.py", line 407, in _configuration_update_helper
if not db.setup_db(config):
File "/app/calibre-web/cps/db.py", line 357, in setup_db
cc = conn.execute("SELECT id, datatype FROM custom_columns")
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 976, in execute
return self._execute_text(object_, multiparams, params)
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1151, in _execute_text
parameters,
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
e, statement, parameters, cursor, context
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
sqlalchemy_exception, with_traceback=exc_info[2], from_=e
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 178, in raise_
raise exception
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
cursor, statement, parameters, context
File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 588, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) file is not a database
[SQL: SELECT id, datatype FROM custom_columns]
(Background on this error at: http://sqlalche.me/e/4xp6)
Please report this issue with all related information: C
```

**Comment by OzzieIsaacs** [comment]
> file is not a database -> it's talking about app.db.

Would be great if you could paste more than just the traceback if you need further help. What did you do, what is your environment, and so on

**Comment by linuxaman2020** [comment]
[cloud_user@lab1~]$ docker inspect -f '{{ .Mounts }}' b84e8074fa80
[{volume 55664a0a565b0f04875c7c7eb9716100d0743cdb9e538edbb571a6fb396dbc8e /var/lib/docker/volumes/55664a0a565b0f04875c7c7eb9716100d0743cdb9e538edbb571a6fb396dbc8e/_data /config local  true } {volume 5f4193d978195490f923464681fb76b95a072c0ee08fffec478b769da3a9df17 /var/lib/docker/volumes/5f4193d978195490f923464681fb76b95a072c0ee08fffec478b769da3a9df17/_data /books local  true }]

[root@lab1 docker]# find /var/lib/docker/ -name metadata.db
/var/lib/docker/volumes/metadata.db
/var/lib/docker/buildkit/metadata.db

when try access http://localhost:8083 its asking for db path and i tried with /books directory it failed. do i need to copied or create new metadata.db file ?

**Comment by linuxaman2020** [comment]
[root@lab1 docker]# docker inspect b84e8074fa80
[
    {
        "Id": "b84e8074fa80234e751f8f05170aadf2a2ca091a6b18b2b771a3a4c20389db73",
        "Created": "2020-04-04T03:09:05.403224821Z",
        "Path": "/init",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 2110,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2020-04-05T03:46:28.63563082Z",
            "FinishedAt": "2020-04-04T04:40:30.639275088Z"        },        "Image": "sha256:73ec46fc0d9727f2b39260594b0164ecb626dc51469cf6fb9798bc469671b196",
        "ResolvConfPath": "/var/lib/docker/containers/b84e8074fa80234e751f8f05170aadf2a2ca091a6b18b2b771a3a4c20389db73/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/b84e8074fa80234e751f8f05170aadf2a2ca091a6b18b2b771a3a4c20389db73/hostname",
        "HostsPath": "/var/lib/docker/containers/b84e8074fa80234e751f8f05170aadf2a2ca091a6b18b2b771a3a4c20389db73/hosts",
        "LogPath": "/var/lib/docker/containers/b84e8074fa80234e751f8f05170aadf2a2ca091a6b18b2b771a3a4c20389db73/b84e8074fa80234e751f8f05170aadf2a2ca091a6b18b2b771a3a4c20389db73-json.log",
        "Name": "/calibre-web",
        "RestartCount": 0,
        "Driver": "devicemapper",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "8083/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8083"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/asound",
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "DeviceId": "9",
                "DeviceName": "docker-259:1-33561120-8181c90911d9a921a53a89570c5edb12c671f451f034915dc2f5522c945e29da",
                "DeviceSize": "10737418240"
            },
            "Name": "devicemapper"
        },
        "Mounts": [
            {
                "Type": "volume",
                "Name": "55664a0a565b0f04875c7c7eb9716100d0743cdb9e538edbb571a6fb396dbc8e",
                "Source": "/var/lib/docker/volumes/55664a0a565b0f04875c7c7eb9716100d0743cdb9e538edbb571a6fb396dbc8e/_data",
                "Destination": "/config",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "5f4193d978195490f923464681fb76b95a072c0ee08fffec478b769da3a9df17",
                "Source": "/var/lib/docker/volumes/5f4193d978195490f923464681fb76b95a072c0ee08fffec478b769da3a9df17/_data",
                "Destination": "/books",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "b84e8074fa80",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "8083/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PUID=1000",
                "PGID=1000",
                "TZ=Asia/Kolkata",
                "DOCKER_MODS=linuxserver/calibre",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "HOME=/root",
                "LANGUAGE=en_US.UTF-8",
                "LANG=en_US.UTF-8",
                "TERM=xterm"
            ],
            "Cmd": null,
            "Image": "linuxserver/calibre-web",
            "Volumes": {
                "/books": {},
                "/config": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/init"
            ],
            "OnBuild": null,
            "Labels": {
                "build_version": "Linuxserver.io version:- 0.6.6-ls56 Build-date:- 2020-03-30T09:37:26-04:00",
                "maintainer": "chbmb"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "6c93d0b11089fe644af94d0729f76dd236823921a709fa41f822fd51dfa4d075",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "8083/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8083"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/6c93d0b11089",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "72a53f2d373eada90fb3ed6e9975fc1dc6a2ac5e621ed79f7a6656161ed1a5d8",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "ce57fdc5a05cd647d3b4a9ff5f0a93d676e5589f143c91d794a322a40f09e6a1",
                    "EndpointID": "72a53f2d373eada90fb3ed6e9975fc1dc6a2ac5e621ed79f7a6656161ed1a5d8",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by OzzieIsaacs** [comment]
You need an existing valid metadata.db file. The other stuff, if relevant afterwards looks like it has nothing to do with calibre-web. As I‘m not the owner of the docker container, please open an issue at the container repro.

**Comment by linuxaman2020** [comment]
thanks will check with repo
