### ISSUE TITLE
PDFs in a specific shelf

### ISSUE THREAD

**Issue by smashkins** [janeczku/calibre-web#1289]
I would like to upload pdfs to a shelf without making them appear among the recently added ePub books. How to do it?

**Comment by OzzieIsaacs** [comment]
This is not possible, and also not a planned feature. 
Calibre organizes it's books in a normal sqlite database. The "recently added" just displays all books sorted according to the books added to database timestamp. 
I don't see any usecase for excluding some sort of books from this view and displaying the books in a different view (the shelf view)

**Comment by smashkins** [comment]
I would have liked to collect my pdf magazines on a separate shelf and don’t show it on the home.
Ok. I understand your reasons. Thank you
