### ISSUE TITLE
New installation failing during installation of dependencies

### ISSUE THREAD

**Issue by UKLibrarian** [janeczku/calibre-web#1291]
I'm building a new calibre bbookserver in a VPS and I'm following the installation process described in the readme and have hit a blocker that I can't puzzle out.

When I issue the "pip3 install --target vendor -r requirements.txt" command the first four steps seem to run OK (Collecting Babel, Flask_Babel, Flask-Login and Flask Principal) but then I get an error:
 Complete output from command python setup.py egg_info:
 Traceback (most recent call last):
 File "<string>", line 1, in <module>
 ModuleNotFoundError: No module named 'setuptools'

Which results in an error message:
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-r8dss3s5/Flask-Principal/

It's a brand new build - Debian 10, Python 3.7.3.

Any suggestions?

**Comment by OzzieIsaacs** [comment]
https://stackoverflow.com/a/14426553

**Comment by UKLibrarian** [comment]
Wow - amazingly fast response, thank you. Installing python3-setuptools moves it along several stages but I then an error on "Invalid command bdist_wheel" which then causes a string of "Failed building wheel" messages for Flask-Principal, iso-639, PyPDF2, tornado and blinker.

Am I missing another pre-req somewhere?

**Comment by OzzieIsaacs** [comment]
`pip3 install wheel`

Could help, never had this problem before

**Comment by UKLibrarian** [comment]
That helps a lot. The pip3 command now installs cleanly :)

Unfortunately running python cps.py  generates:

Traceback (most recent call last):
  File "cps.py", line 34, in <module>
    from cps import create_app
  File "/home/admin/calibre-web/cps/__init__.py", line 38, in <module>
    from .server import WebServer
  File "/home/admin/calibre-web/cps/server.py", line 33, in <module>
    from tornado.wsgi import WSGIContainer
  File "/home/admin/calibre-web/vendor/tornado/wsgi.py", line 51
    def to_wsgi_str(s: bytes) -> str:
                     ^
SyntaxError: invalid syntax

Am I just missing something obvious - is there a step somewhere in the installation which I've forgotten to do, or a package I have not installed?

**Comment by OzzieIsaacs** [comment]
You installed it for python3 (via pip3), so please start it with python3 and not python (= python2), the newest tornado is not compatible with python2

**Comment by UKLibrarian** [comment]
That was dumb of me - I should have spotted that. Yes, that seems to work perfectly now.

Thank you so much for your help. *sends you a virtual beer*
