### ISSUE TITLE
Adding IPFS as a storage backend

### ISSUE THREAD

**Issue by xcffl** [janeczku/calibre-web#1292]
**Is your feature request related to a problem? Please describe.**
Book storage in IPFS will be more resillient even when the origin server (that runs calibre-web) goes down or has data curruption. It also makes downloading faster. Moreover, if you agree, it keeps human's knowledge longer.

**Describe the solution you'd like**
Given that there is also a GDrive backend and IPFS has a Python library, it will be relatively easy to implement.

**Additional context**
If it is a welcomed feature, I'll be pleased to help.

**Comment by OzzieIsaacs** [comment]
I decided to not add any more storage backends, so I will not implement it
