### ISSUE TITLE
500 error on search action

### ISSUE THREAD

**Issue by Oreolek** [janeczku/calibre-web#1293]
`[calibre path]/search` returns error 500.

 File `cps/web.py`, line 814, in search: `term = request.args.get("query").strip().lower()`

AttributeError: 'NoneType' object has no attribute 'strip'

If there's no `query` parameter, then there's no string to strip. I assume the page should just redirect to the library.

**Comment by OzzieIsaacs** [comment]
You are right. I'm currently in a big merge. I will fix it this weekend. It will display an empty search result.

**Comment by OzzieIsaacs** [comment]
Remark: There are many more routes with get parameters which require proper input check

**Comment by OzzieIsaacs** [comment]
The newest commit fixes the problem
