### ISSUE TITLE
Show all books sorted by author

### ISSUE THREAD

**Issue by UKLibrarian** [janeczku/calibre-web#1294]
This seems so basic that I feel I must be missing something really obvious, but I've been looking for it all afternoon and can't figure it out. I have my currently imported books tagged as 'fiction' (non-fiction will come later) and it seems there ought to be a way to browse all books, sorted by author, just like you would on a normal real-world library.

Even if I go into my "Fiction" category, the blue alpha sort button at the top then sorts alphabetically by title not author. What have I missed?

**Comment by OzzieIsaacs** [comment]
There is no such option, you can only filter by author in the left authors section

**Comment by UKLibrarian** [comment]
I'll not carry on looking for it then :)
