### ISSUE TITLE
enable deploying calibre-web instances to  /path intead of being tied to the root / 

### ISSUE THREAD

**Issue by rockonedege** [janeczku/calibre-web#1295]
**Is your feature request related to a problem? Please describe.**

>A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
I'd like to deploy multi-instance of  calibre-web  under one domain name differentiated for each other with path. e.g. `books.example.com/lib1`, `books.example.com/lib2`. which is not possible as I test it, the redirects always go back to the site root `books.example.com/login` instead of `books.example.com/lib1/login`, `books.example.com/lib2/login`

**Describe the solution you'd like**

>I'd like to arrange my calibre libraries as `books.example.com/lib1`, `books.example.com/lib2`, etc.

**Describe alternatives you've considered**

>I could achieve it with subdomains  `lib1.books.example.com`, but it's not the best choice in my case for other considerations.

**Additional context**

**Comment by OzzieIsaacs** [comment]
Can't reproduce the problem, for me it's working for years with apache reverse proxy.
I'm using the procedure described here https://github.com/janeczku/calibre-web/wiki/FAQ#how-to-handle-multiple-calibre-libs (well I'm actucally using a init script, but this doesn't matter) and I've using twice the setup from here: https://github.com/janeczku/calibre-web/wiki/Setup-Reverse-Proxy#apache-24
I'm using a linux server with ubuntu.

What are you doing? (To help you I need details about your setup)

**Comment by rockonedege** [comment]
I am using dockerized traefik and calibre-web. something like this I was trying to access it from bookshelf.mysite.me/ebooks/bookshelf
linuxserver-web-calibre-bookshelf:
image: linuxserver/calibre-web
container_name: linuxserver-calibre-web-bookshelf
environment:
- PUID=1026
- PGID=100
- TZ=Asia/Shanghai
- DOCKER_MODS=linuxserver/calibre-web:calibre
volumes:
- /volume1/ebook/bookshelf:/books
- /volume1/docker/web-calibre/linuxserverio/config/bookshelf:/config
ports:
- 11000:8083
restart: always
networks:
- traefik-network
labels:
# Note: all dollar signs need to be doubled for escaping.
- "traefik.enable=true"
- "traefik.http.routers.web-calibre-bookshelf.rule=Host(`bookshelf.mysite.me`) && PathPrefix(`/ebooks/bookshelf`)"
- "traefik.http.services.web-calibre-bookshelf.loadbalancer.server.port=8083"

- "traefik.http.middlewares.web-calibre-bookshelf.stripprefix.prefixes=/ebooks/bookshelf"
- "traefik.http.routers.web-calibre-bookshelf.entrypoints=web"
this following script proves my traefik setting was working.

whoami2:
image: "containous/whoami"
container_name: "whoami-path"
labels:
- "traefik.enable=true"
- "traefik.http.routers.whoami2.rule=Host(`whoami2.yiyi.synology.me`) && PathPrefix(`/web`)"
- "traefik.http.routers.whoami2.entrypoints=web"
- "traefik.http.services.whoami2.loadbalancer.server.port=80"

# Strip prefix /foobar and /fiibar
- "traefik.http.middlewares.whoami2.stripprefix.prefixes=/web"

networks:
- traefik-network

In case it helps, here's my traefik setting:

traefik-proxy:
image: "traefik"
container_name: "traefik"
command:
- "--log.level=DEBUG"
- "--api.insecure=true"
- "--providers.docker=true"
- "--providers.docker.exposedbydefault=false"
- "--entrypoints.web.address=:80"
- "--entrypoints.websecure.address=:443"
- "--providers.file.watch=true"
- "--providers.file.directory=/etc/traefik"

ports:
- "88:80"
- "8800:8080"
volumes:

- "./config:/etc/traefik"
- "/var/run/docker.sock:/var/run/docker.sock:ro"
networks:
- traefik-network

**Comment by OzzieIsaacs** [comment]
I'm sorry I can't help you,this repro is the wrong to ask for help in this case. Calibre-Web is a standalone server and requires listening on an unique/exclusive port. 
If you want to have multiple libraries, you need multiple instances of Calibre-Web (in your case of the docker container). Each one has to be individual configured to listen on an unique and exclusive port. To access those 2 instances later on via a common IP-address or host name you use a proxy (like traefik).

> The above link was using multiple ports...

From my point of view, if you want to run mulitple instances, you always need multiple ports to run it one and afterwards tie it together by mapping it to different paths.
 
What I'm missing in the above configuration (if I'm reading it right, my docker knowledge is very limited, and I have absolutely no clue on traefik) is a second docker configuration and the configuration for the second Calibre-Web docker instance in traefik.

My apache is configured as follows (if I want to add an 3rd instance just run calibre-web a 3rd time on a different port and add a third location block to the configuration). From outside the ports 8082 and 8083 are not reachable, so everybody who wants to access my calibre-web instances has to use domain-name.com/cw or domain-name.com/cw-newspaper and gets to the corresponding pages.

```
<Location /cw>
    RequestHeader set X-SCRIPT-NAME /cw
    RequestHeader set X-SCHEME https
    ProxyPass http://localhost:8083/
    ProxyPassReverse http://localhost:8083/
</Location>

<Location /cw-newspaper>
    RequestHeader set X-SCRIPT-NAME /cw-newspaper
    RequestHeader set X-SCHEME https
    ProxyPass http://localhost:8082/
    ProxyPassReverse http://localhost:8082/
</Location>
```

**Comment by OzzieIsaacs** [comment]
Please ask for further assistance on the linuxserver repro or at traefiks repro. If you can reach each page individual it's more a traefik questions, if ths doesn't work it's more a question on the docker container.
