### ISSUE TITLE
Cannot upload more than one pdf to same book

### ISSUE THREAD

**Issue by ikwyl6** [janeczku/calibre-web#1299]
**Describe the bug/problem**
When the ```Upload``` feature is enabled and a book is created with a PDF, a user cannot upload another pdf so the user cannot view both under the ```Read in Browser``` drop down.

**To Reproduce**
1. Enable 'UPload' in Admin settings
2. Click on a book that already has been added to calibre-web that has a pdf as it's source
3. Click 'Edit MetaData' for that book
4. Click 'Upload Format'
5. Choose another PDF for that book 
6. Click Save and have the 'View book on Save' checkbox ticked.
7. Click the dropdown 'Read in Browser' downdown there is only one pdf listed (not two).

**Logfile**
[2020-04-09 19:59:56,038]  WARN {cps.editbooks:351} Book format PDF already existing
[2020-04-09 19:59:56,722]  WARN {cps.uploader:159} Pdf extraction forbidden by Imagemagick policy: attempt to perform an operation not allowed by the security policy `gs' @ error/delegate.c/ExternalDelegateCommand/378

**Expected behavior**
Should be able to add same file format of books as the PDFs may have different features compared to the other. Even though Imagemagick complains about security policy, I have tried this with other random PDFs and it still does not upload and gives the same warning.

**Environment (please complete the following information):**
 - OS: Arch Linux, headless server
 - Python version: Python 3.8.2 running in a venv environment.
 - Calibre-Web version: git clone, commit ```25ab3cabfef7b4b443116c91a0b6a5b2b6ce333c```
 - Docker container: None
 - Special Hardware: PogoPlug 
 - Browser: Brave

**Additional context**
none at this time.

**Comment by OzzieIsaacs** [comment]
Checked it in Calibre, it's also not possible there (or how do you do it). The only way of generating exactly 2 pdf's is by converting it from same format to same format. Afterwards you are having 2 pdfs, but you can't convert from the first one to another format, looks to me more like a bug than a feature.
But to answer your question calibre-web is an "alternative" UI to Calibre, so I want to becompatible to the calibre database whereever it's possible. This feature looks to me not like compatible with calibre.
