### ISSUE TITLE
[Req] Add native Audiobook support

### ISSUE THREAD

**Issue by darkcloud784** [janeczku/calibre-web#1300]
Would really really really like to have a singular place to have my books, be it audio book or ebook. Adding native support so I can tie my audiobooks to my ebooks without having to zip them and download them as an alternative format would be ideal.

**Comment by OzzieIsaacs** [comment]
Currently audio support is missing in the readme, you can upload mp3, m4a, m4b files, which file format do you need?

**Comment by darkcloud784** [comment]
I'm looking for a way to automate adding the audiobooks.

**Comment by OzzieIsaacs** [comment]
I personally don't use audiobooks, so what is missing from your point of view?

**Comment by darkcloud784** [comment]
> I personally don't use audiobooks, so what is missing from your point of view?

A way to automate adding the files to calibre-web.

**Comment by OzzieIsaacs** [comment]
I recommend something like this:
https://github.com/janeczku/calibre-web/wiki/FAQ#mass-add-books
I will not integrate it in Calibre-Web
