### ISSUE TITLE
Sorting alphabetically by author

### ISSUE THREAD

**Issue by UKLibrarian** [janeczku/calibre-web#1301]
I think this is probably two separate enhancement requests (in terms of implementation) but they are closely linked user functionality. Let me know if you would like me to split them.

Within the various browse views (the single-level ones like Recently Added, Hot Books, Read/Unread and the multi-level ones like Categories, Series. Authors etc) the blue sort-buttons along the top allow for sorting by date added and publication dates and alphabetically by title. Normal library usage is to sort alphabetically by author - this is the paradigm which will be familiar to most users.

As an addition to the above sort buttons, could there also be another one which allowed the selected books to be sorted by alphabetically by author a-z (and possibly one for z-a as well?)

The second, allied request was for there to be sort buttons within shelves. Obviously at present it is possible to re-order books into author order on shelves manually , but it is a laborious and time-consuming task to do initially and then to maintain when new books are added.

**Comment by OzzieIsaacs** [comment]
The sort buttons in shelves are available meanwhile

**Comment by OzzieIsaacs** [comment]
It's also possible to sort according to author name:
![image](https://github.com/janeczku/calibre-web/assets/6438895/b835da93-d703-448f-8603-e10a40232b6e)
