### ISSUE TITLE
Ordering Custom Columns

### ISSUE THREAD

**Issue by EolianPipes** [janeczku/calibre-web#1304]
Is there a way to order custom columns in the Book Details view?

How are they ordered currently?

**Comment by OzzieIsaacs** [comment]
Currently(and is not planned) to order custom columns view. 
In calibre all custom columns having  a unique number (starting from 1 upwards). Calibre-Web outputs the columns sorted in ascending order.
Unfortunately, this number is not the order visible in Calibre. I tried to visualize this in the following screenshot
![grafik](https://user-images.githubusercontent.com/6438895/79256133-c93b1a80-7e87-11ea-9455-e26f9189b65c.png)

**Comment by EolianPipes** [comment]
That makes sense. I wondered if this was where they were coming from. I was hoping there might be a way to re-org or re-number in Calibre directly, but I'm pretty sure they are just incremented when a new custom column is created.

I can ask this in a different thread, but what field should I be looking at to do the "hide columns" regex? Is it the column name or the column lookup?

**Comment by OzzieIsaacs** [comment]
It's the column name, I will add this in the wiki
