### ISSUE TITLE
Use first page of PDF as cover

### ISSUE THREAD

**Issue by blizarazu** [janeczku/calibre-web#1305]
Hi,

I think it would be great to have the choice to use the first page of a PDF book as cover image. I guess it could be done using imagemagick's convert tool as described here:
https://www.imagemagick.org/discourse-server/viewtopic.php?t=14927

Thanks.

**Comment by OzzieIsaacs** [comment]
Upon uploading the first page of a pdf is converted to a jpg and added as cover file to the book.
Is this not working for you? 
Are you suffering from: https://github.com/janeczku/calibre-web/wiki/FAQ#what-to-do-if-cover-pictures-are-not-extracted-from-pdf-files ?
Or what is exactly your request?

**Comment by blizarazu** [comment]
It was the problem with the policy.xml file. I made the change and now it works fine. Thank you!
