### ISSUE TITLE
github oauth login not visible

### ISSUE THREAD

**Issue by flashlab** [janeczku/calibre-web#1307]
**Describe the bug/problem**
I use the nightly version, and have installed optional-requirements related oauth, but in the setup page I can't find the input option.
Also int the login page, there is no login with github button.

**Environment (please complete the following information):**
 - OS: Debian 9
 - Python version python 3.5.3
 - Calibre-Web version latest
 - Browser chrome

**Comment by OzzieIsaacs** [comment]
Looks like 
flask-dance>=0.13.0
was to optimistic.
If you install version 0.13 it works. I've to check what the problem is.

**Comment by OzzieIsaacs** [comment]
Should be visible back with the newest commit

**Comment by flashlab** [comment]
@OzzieIsaacs Thanks for your patch, the github login button come back, and I can setup the app id and secret.
Now the problem is callback url.
I notice the redirect_uri field `http://127.0.0.1:8083/login/github/authorized` I can only set the same value in github's `Authorization callback URL` field before correctly jump to github authorization page.
but I host calibre-web with domain, not locally, so how can I make the redirect_uri use the real domain? Thak you very much.

**Comment by OzzieIsaacs** [comment]
You need a public accessible instance of Calibre-Web. So if your computer is accessible from internet via "example.org:8083", please access Calibre-Web via this address, afterwards the callback address will magically change to `http://example.org:8083/login/github/authorized`. This is how it should work. Once authorized and logged in you can access your Calibre-Web instance again via 127.0.0.1...

**Comment by flashlab** [comment]
@OzzieIsaacs Sorry for not making my situation clear. I host Calibre-Web on VPS and use Nginx to proxy 8083 port to my domain https://calibre.redbux.cn 
For now, I can use `ip:port format` (like this: `http://xxx.xxx.xxx.xxx:8083/login/github/authorized`) in the `Authorization callback URL` field to jump to github authorization page, but after click the button and redirect back, I receive `500 Internal Server Error`:
```
Traceback (most recent call last):
File "/home/zjf/calibre-web/vendor/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/home/zjf/calibre-web/vendor/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/zjf/calibre-web/vendor/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/home/zjf/calibre-web/vendor/flask/_compat.py", line 39, in reraise
raise value
File "/home/zjf/calibre-web/vendor/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/home/zjf/calibre-web/vendor/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/home/zjf/calibre-web/vendor/flask_dance/consumer/oauth2.py", line 260, in authorized
**self.token_url_params
File "/home/zjf/calibre-web/vendor/requests_oauthlib/oauth2_session.py", line 240, in fetch_token
authorization_response, state=self._state
File "/home/zjf/calibre-web/vendor/oauthlib/oauth2/rfc6749/clients/web_application.py", line 203, in parse_request_uri_response
response = parse_authorization_code_response(uri, state=state)
File "/home/zjf/calibre-web/vendor/oauthlib/oauth2/rfc6749/parameters.py", line 262, in parse_authorization_code_response
raise InsecureTransportError()
oauthlib.oauth2.rfc6749.errors.InsecureTransportError: (insecure_transport) OAuth 2 MUST utilize https.
```
If I use the `domain` (like https://calibre.redbux.cn/login/github/authorized) format, I will be traped by redirection dead loop.
========
I also try the latest commit, seems not work ;(

**Comment by OzzieIsaacs** [comment]
The lasted commit did indeed nothing change here. I just renabled google oauth, which wasn't working before. And also enabled deleting the key, which wasn't possible before.
The error message is somehow related to encrypted, unencrypted connection. I personally don't use oauth (and as there are many problems, not many people seem to do so), I try to check it.

**Comment by OzzieIsaacs** [comment]
From reading the code setting an environment variable:
OAUTHLIB_INSECURE_TRANSPORT
disables the check for a encrypted callback routine and would solve the problem for the error 500 (I will check if I can catch the error)

**Comment by OzzieIsaacs** [comment]
There is no need to try around, it's simply not working

**Comment by OzzieIsaacs** [comment]
Okay, I think I got it now. 
It should work again with all version of flask-dance >0.13. It's recommended to use version >1.3, the interface changed at that point, and causes additional code, so I will remove it in future. The statement regarding the "OAUTHLIB_INSECURE_TRANSPORT" environment variable is still valid and necessary.
