### ISSUE TITLE
Duplicate shelf name

### ISSUE THREAD

**Issue by hallamjeff** [janeczku/calibre-web#1309]
I created a new shelf call "Programming" as a non-admin user. When I then attempted to add a book to the shelf (from a search results page) it appears twice in the drop down list of choices (see screenshot).

**To Reproduce**
1. Create a regular user and login.
2. Create a new shelf
3. Attempt to add a book to the shelf.

**Logfile**
N/A

**Expected behavior**
Expecting the shelf name to appear just once.

**Screenshots**
![shelf_name_double](https://user-images.githubusercontent.com/17209731/79285298-8bdc8a00-7e93-11ea-9590-5cf2ce5991d2.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.4 server
 - Python version 3.6.9
 - Calibre-Web version 0.6.7 Beta
 - Docker container: None
 - Special Hardware: N/A
 - Browser Firefox

**Additional context**
N/A

**Comment by OzzieIsaacs** [comment]
Thanks for reporting, it's fixed in the newest master commit
