### ISSUE TITLE
Enhancement LDAP : Enable simple authentication

### ISSUE THREAD

**Issue by Krakinou** [janeczku/calibre-web#1311]
To use simple authentication in LDAP, we need to send empty LDAP_USERNAME and LDAP_PASSWORD ( = '' to be more specific)
It is achievable by setting '' (2 simple quotes) in corresponding field in LDAP settings to bypass the "enter LDAP service username and password" error message but I think a tick that would allow to choose between those 2 options (simple authentication without username nor password or bind with username and password) would be easier to use.

**Comment by OzzieIsaacs** [comment]
According to: https://ldapwiki.com/wiki/Simple%20Authentication there are 3 authentication methods, the one you are referring to is called anonymous authentication there.

I agree with you to add an setting, to not confuse the user.

- [ ] Add Select "Anonymous Authentication", "Unauthenticated Authentication" and "Name/Password Authentication Mechanism, default the third one
- [ ] Enable visibility of username and password according to the setting, check content of username and password field based on this setting upon saving
- [ ] Create new config setting admin_authentication_method
- [ ] Based on this setting config SimpleLDAP class upon start to the corresponding mode (so stored passwords and usernames can be kept in the database for further useage
- [ ] Add section in wiki to explain the setting and it's impact
- [ ] modify and add automatic  tests with the new config options

(The last one will take the longest time)
