### ISSUE TITLE
[Auto update] Stuck at auto-restart

### ISSUE THREAD

**Issue by simkin** [janeczku/calibre-web#132]
After updating calibre-web via the admin view, the application become unresponsive (stuck at loading after page refresh)

When looking at the service status it seems to be stuck processing the reboot command?:
root@nas:/opt/calibre-web# systemctl status calibre-web
```
● calibre-web.service - Calibre Web
   Loaded: loaded (/lib/systemd/system/calibre-web.service; enabled)
   Active: active (running) since Tue 2017-02-28 11:51:07 CET; 1 day 21h ago
 Main PID: 16641 (python)
   CGroup: /system.slice/calibre-web.service
           └─16641 /usr/bin/python /opt/calibre-web/cps.py

Feb 28 11:51:07 nas systemd[1]: Started Calibre Web.
Feb 28 11:51:08 nas python[16641]: WARNING:tornado.access:404 GET /favicon.ico (::1) 6.42ms
Feb 28 11:51:08 nas python[16641]: WARNING:tornado.access:404 GET /favicon.ico (::1) 1.43ms
Mar 01 06:59:31 nas python[16641]: WARNING:tornado.access:404 GET /robots.txt (::1) 1.29ms
Mar 02 08:47:38 nas python[16641]: INFO:cps.web:Performing restart of Calibre-web
```
When I manually restart calibre via "systemctl restart calibre-web" I can access the application again

**Comment by OzzieIsaacs** [comment]
Could you please tell me, which Linux you are using, I can take a look at that

**Comment by simkin** [comment]
Debian Jessie (latest version)

how do you initiate service restart?

**Comment by OzzieIsaacs** [comment]
I'm using it on ubuntu, so I start the service by upstart (and I tested this). In the calibre-web code the restart is done via stopping tornado, and than starting a new instance of calibre web via:

`os.execl(sys.executable, sys.executable, *sys.argv)`

**Comment by OzzieIsaacs** [comment]
I could reproduce the error. 
Please try newest commit. After update you could check it by trying the restart function in the admin section, this caused the same error before.

**Comment by simkin** [comment]
Will do. I noticed pressing restart worked. Was pending update to continue
investigating.

Op 17 mrt. 2017 20:01 schreef "Ozzie Isaacs" <notifications@github.com>:
