### ISSUE TITLE
Deprecated werkzeug function ImmutableDict

### ISSUE THREAD

**Issue by bobberb** [janeczku/calibre-web#1323]
**Describe the bug/problem**
Using werkzeug latest (`1.0.1` on Arch), calibre-web will not boot

> The import 'werkzeug.ImmutableDict' is deprecated and will be removed in Werkzeug 1.0. Use 'from werkzeug.datastructures import ImmutableDict' instead.
>     from werkzeug import ImmutableDict

**To Reproduce**
1. Have latest werkzeug installed
2. Attempt to start calibre-web
3.  ` ImportError: cannot import name 'ImmutableDict' from '
werkzeug' (/usr/lib/python3.8/site-packages/werkzeug/__init__.py)
4. Crash
`

**Expected behavior**
A boot

**Environment**
 - OS: Arch Linux, full system up-to-date as of 2020-04-23
 - Python version 3.8
 - Calibre-Web version git-pull `master`:

**Fix**
Werkzeug can be downgraded via pip/other manager (in my case, overriding OS pacman)
`sudo pip install --upgrade werkzeug==0.16.1`

**Comment by OzzieIsaacs** [comment]
I don't have an Arch accessible, but I checked it with Manjaro. There is no problem. The following screenshot shows the direct imports of the testing enviroment:
![grafik](https://user-images.githubusercontent.com/6438895/80094198-2315a180-8566-11ea-8498-b4577647125a.png)
Additionally Werkzeug      1.01 was used.

Werkzeug isn't used directly by calibre-web it's a dependency of flask, so I can't fix it.

Beside this I searched for the "deprecated warning" text, I didn't find it in the code of Werkzeug, and also not in Flask. I also checked newest version of flask for the "deprecated import" statement. I didn't find it. I also checked back to flask version 0.12, the import statement isn't there also.
Maybe I'm searching on the wrong imports, but to check for the right one, I need the import line and file in Calibre-Web, which is calling the deprecated import (complete traceback). I guess you are having something beside a new Werkzeug, which is very old. With newest versions it's working for me.
