### ISSUE TITLE
Add to Shelf Button Missing in CaliBlur! Theme

### ISSUE THREAD

**Issue by Boh1** [janeczku/calibre-web#1324]
After performing a search / advanced search, the "Add to shelf" button is not visible when using the CaliBlur! (dark) theme. This makes it difficult to add multiple books to a shelf.

This seems specific to this theme since switching back to the default 'light' theme the button is once again visible.

This was mentioned late last year in another bug report. I'm just opening this up to identify / track this specific issue.

Version 0.6.6

**Comment by OzzieIsaacs** [comment]
@hexeth and  @leram84 this issue looks also related to the Caliblur! Theme

**Comment by cbartondock** [comment]
This was fixed in my PR

**Comment by OzzieIsaacs** [comment]
Thanks @cbartondock
