### ISSUE TITLE
Enhancement: Support Calibre Custom Column generated from other Columns

### ISSUE THREAD

**Issue by Vctrsnts** [janeczku/calibre-web#1331]
Hello,

It is possible that in the next version the "**#revision**" column will be available in the same way that this column "**#revision**" is in "**calibre**".

It is so that when we have the same book 2 times, the oldest revision can be deleted.

Thank you if is possible...

**Comment by OzzieIsaacs** [comment]
I only have a German Calibre, the translations seem to differ a lot, is it the column lookup "last_modified"?

**Comment by Vctrsnts** [comment]
Hello,

In my case (Spanish caliber) this column is **#revision** and I see this column in the [metadata.opf](https://github.com/janeczku/calibre-web/files/4542001/metadata.txt) file, it is created when loading the book automatically in caliber-non-web:

`<meta name = "caliber: user_metadata: #revision"`

It is very possible that this column is added by the book editor, but **caliber-web** does not see it (because the opf file is not created) and **caliber-non-web** does (because it does create the opf file).

With this, it can be added to the list of visible columns (title, author, category, etc.) for later display.

I comment it, because the **last_modified** field can always be the same (date) if you copy the files from one directory to another.

Thanks for everything and sorry for the inconvenience

**Comment by OzzieIsaacs** [comment]
Sorry, I was a bit tiered yesterday, now I got it. 
The text you showed me, tells me that the revision you are using is a Custom Column. Calibre is not creating this entry on it's own, you created it in the Calibre database file. I gues you are using a new Calibre-Web database file and did not copy your original Calibre File, or 2nd posibility: Calibre Web isn't supporting all types of Custom Columns, this is why ou don't see it.
Could you please post a screenshot of the Calibre Columns:
![grafik](https://user-images.githubusercontent.com/6438895/80450917-e14c7880-8922-11ea-995e-658177ac56f9.png)

Via right click on headline and the something like "Add Custom Columns"

**Comment by Vctrsnts** [comment]
Hello,
Don't worry, nothing happens.

Regarding whether my **calibre-web database** was created **new** or **not**, say that I am using the **DDBB** of the calibre-non-web version that I have used so far (copy the DDBB from one side to the other).

And here I put the image of how I have configured the columns as you ask me:
![img001](https://user-images.githubusercontent.com/59069334/80485700-2dff7600-895a-11ea-9de8-268ab7772806.png)
The column is the last, with name **Version** --> **#revision**

Thanks for all

**Comment by OzzieIsaacs** [comment]
The Column is from type: Column generated from other Columns (or so) , this column type is currently not supported by Calibre-Web

**Comment by Vctrsnts** [comment]
Okay,
Nothing happens, I'll wait until it's compatible.

Thank you so much for everything.

**Comment by OzzieIsaacs** [comment]
If you close it, I will not implement it, as I forget it

**Comment by Vctrsnts** [comment]
Ok, sorry...

**Comment by OzzieIsaacs** [comment]
I thought I got it, searched a bit in the internet and now I'm sure I didn't get it:
If I had to organize the revision of a book with calibre, I would generate a custom column with text content and fill the revision in it (already possible).
I searched a bit on what you might do, but I didn't find any results. Could you please explain more detailed what are you doing, and what you expect Calibre-Web to do and how you configure this in Calibre?

**Comment by Vctrsnts** [comment]
No problem, I'll explain it to you within my means.

If possible, the column I added could be seen in caliber-web, in this case "revision".

In the case of caliber-non-web, I have done it as follows (I attach an image)

![img001](https://user-images.githubusercontent.com/59069334/80872569-ffafcc80-8cb2-11ea-8a29-7854bdf5e25c.png)


But of course, I know I could be a bit difficult, if you have to add all the custom columns that people can create.

In my case, it is to know what "revision" of the book is. If it is revision 1,1.1, 1.2, etc ... (which means that they are correcting the errors that are found).

Thank you so much for everything.
