### ISSUE TITLE
Captcha implementation

### ISSUE THREAD

**Issue by nomorehey** [janeczku/calibre-web#1332]
When the web-calibre instance is exposed to the internet it receives visits from many bots and crawlers that saturate the server, I want to keep keeping the server open, but it would be nice if the registered and invited users could impose a limit when browsing or uploading / download books using captchas, equal to the time of registering or logging in.

**Comment by nomorehey** [comment]
Okay...

**Comment by OzzieIsaacs** [comment]
I'd like to focus more on the books part of the project and not implement any more login routines, storage providers, registering improvements and so on. I decided not to implement it.

**Comment by nomorehey** [comment]
I would also like to see this functionality being implemented!
