### ISSUE TITLE
Need to whitelist email in Amazon in order for "send to kindle" to work

### ISSUE THREAD

**Issue by funnelcloudservices** [janeczku/calibre-web#1336]
This took me a while to figure out and might be beneficial to have as a tooltip inside the app.

If you wish to send books to your kindle, not only do you have to add your "send to kindle" email address in Calibre-web, but you also have to whitelist the email address that your server is sending emails under.

_On Amazon, Go to Manage Your Content and Devices.
From Preferences scroll down to Personal Document Settings.
Under Approved Personal Document Email List, check if your email address is listed. If your email address is not listed, select Add a new approved e-mail address.  (the one you have set in outgoing email name in Calibre-web)
Enter the desired email address and select Add Address._

**Comment by OzzieIsaacs** [comment]
Thank you very much, I transfered this useful information to the wiki: https://github.com/janeczku/calibre-web/wiki/Additional-Configuration-for-Kindle-E-Mail
