### ISSUE TITLE
Search metadata from Calibre custom columns

### ISSUE THREAD

**Issue by ameel** [janeczku/calibre-web#1338]
First, this work looks fantastic. I can't wait to use it.

**Is your feature request related to a problem? Please describe.**
I use predominantly CBZ files.
For metadata, ComicInfo.xml files are embedded inside the CBZ file.
Calibre reads the CBZ file but cannot process all the types of metadata.
One example of the problem:
I have setup a custom column in Calibre called 'Genre' (type: Comma separate text, like tags, shown in the Tag browser) to retain 'Genre' metadata.

**Describe the solution you'd like**
Ability to search by other metadata from Calibre custom columns based on their type

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Knepherbird** [comment]
@ameel Not sure what plans there might be to support other metadata formats in calibre-web, but have you tried the Embed Comic Metadata plugin for Calibre? I use it to pull in all the comicvine metadata in my comic book files. It hasn't been updated in a year or two, but it's still working for me on the latest version of calibre:
https://www.mobileread.com/forums/showthread.php?t=264710

**Comment by OzzieIsaacs** [comment]
It's meanwhile possible to search for most of the custom column types with the advanced serach function
