### ISSUE TITLE
no module named middleware.proxy_fix

### ISSUE THREAD

**Issue by bartart3d** [janeczku/calibre-web#1339]
**Describe the bug/problem**
Trying to run 'python cps.py' after installing the dependencies on a raspberry 4, raspbian, I get this error:
Traceback (most recent call last):
  File "cps.py", line 34, in <module>
    from cps import create_app
  File "/home/pi/Documents/calibre-web-master/cps/__init__.py", line 39, in <module>
    from werkzeug.middleware.proxy_fix import ProxyFix
ImportError: No module named middleware.proxy_fix

**To Reproduce**
- follow the quick start
- step 2 produces the error

**Expected behavior**
installation, or running of calibre-web

**Screenshots**

**Environment (please complete the following information):**
 - OS: raspbian
 - Python version: python2.7 and python 3
 - Calibre-Web version: master on 30/04/2020

 - Special Hardware: Rasperry Pi 4
 - Browser : chromium, chrome

**Comment by OzzieIsaacs** [comment]
If possible try to update "Werkzeug" to a newer version via:
`pip install Werkzeug -U` or `pip3 install Werkzeug>=1.0.0 -U`, depending on your python version. 
I try to fix it in parallel

**Comment by bartart3d** [comment]
Thank you! That did the trick :-) .
It seems to be working now!
