### ISSUE TITLE
SMTP e-mail server not sending emails

### ISSUE THREAD

**Issue by AllowPing** [janeczku/calibre-web#1341]
Calibre-Web isn't sending the test email as admin or password resets for other user accounts. I am using the linuxserver/calibre-web docker container behind the linuxserver/letsecrypt docker container. Emailing works without issue on a linuxserver/calibre-web docker image that's not behind letsencrypt, though I'm not seeing enough in calibre-web logs to rule out this app being the issue.

Log Level | DEBUG | returns:
ERROR {cps.worker:531} Error sending email: Cannot assign requested address

As always, the pop-up is provided when sending the test email:
Test e-mail successfully send to example@gmail.com

I've tried STARTTLS 587 and SSL/TLS 465.

I've checked some logs, but didn't see anything jump out at me:
/docker/letsencrypt/log/letsencrypt/letsencrypt.log
/docker/letsencrypt/log//nginx/access.log
/docker/letsencrypt/log//nginx/error.log

Linux and docker are pretty new to me, so any help narrowing this down would be great.

edit: words

**Comment by OzzieIsaacs** [comment]
The error message is somehow related to docker and name resolution. Calibre-Web isn't able to get the right ip-address to connect to the mail server (a quick google search for "docker Cannot assign requested address" delivered out many results, the first one looks promising to me: https://medium.com/it-dead-inside/docker-containers-and-localhost-cannot-assign-requested-address-6ac7bc0d042b). 
I'm not familiar with docker, and as you mentioned a pure Calibre-Web is working. Could you please open an issue at linuxserver. Sorry, I can't help you.
(Regarding the missleading message, there is already an open issue for it: #657)

**Comment by AllowPing** [comment]
Thank you for the speedy reply!

Looking towards the search and link you suggested seems promising. Unless this is marked as closed before I find resolution, I'll report back on my findings and I agree that it does seem to be an issue outside of Calibre-Web.

Thanks for linking to the misleading message issue. At least, the Tasks list page details things a bit more specifically.

Cheers

**Comment by OzzieIsaacs** [comment]
Thank you.
I Hope you get it running according to your requirements

**Comment by AllowPing** [comment]
Turns out, the issue wasn't Calibre-Web or docker images - it was the VPS provider, Linode, blocking outbound email by default to combat spam.

The helpful folks here and the LinuxServer.io Discord Server pointed me towards it being a VPS issue and suggested running a packet capture. A pcap showed DNS replies from Linode for smtp.office365.com, then multiple outbound re-transmission packets for TCP 587 with no reply. A quick support ticket with Linode and they confirmed and lifted these restrictions from the account.

Thank you again for the help.
