### ISSUE TITLE
404 error when trying to change user's password

### ISSUE THREAD

**Issue by johnvick** [janeczku/calibre-web#1342]
Using Technosoft2000 docker version on Ubuntu server 20.04 recently upgraded from 18.04. The problem I have run into is if I try to change user or admin password I get a 404 error. Other than this it works fine. I am not a developed just a user looking for assistance thanks.

**Comment by OzzieIsaacs** [comment]
How do you change password, by just typing in a new one in?
Could you please provide the calibre-web logbook? 
Could you please also activate the access log and also paste the content of this one?

**Comment by johnvick** [comment]
I try to change password by using the Reset User Password button on the admin menus.
How do I get the logbook and activate access log?

**Comment by OzzieIsaacs** [comment]
Okay,
found it, it's a bug.

**Comment by johnvick** [comment]
Great thanks for the quick fix.

**Comment by OzzieIsaacs** [comment]
It's not yet merged to the master branch, it will take some time till you receive the fix (hopefully this weekend)
