### ISSUE TITLE
"Cover is not a jpg file, can't save"

### ISSUE THREAD

**Issue by databoy2k** [janeczku/calibre-web#1343]
**Describe the bug/problem**
A clear and concise description of what the bug is. If you are asking for support, please check our [Wiki](https://github.com/janeczku/calibre-web/wiki) if your question is already answered there.

I cannot save a cover to any of my e-books in Calibre-Web. I receive the error, "Cover is not a jpg file, can't save." The rest of the metadata saves, but the book is left with a white "Cover not available" box for a cover.

**To Reproduce**
1. Go to a given ebook.
2. Click on "Edit Metadata" (the pen).
3. Scroll down to "Fetch Metadata" and click on it.
4. Click on a cover (tested with Google Books as a source) and note that the metadata and the cover appears filled in.
5. Click "Save"

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

I cannot locate any relevant logs.

**Expected behavior**

I expected a cover to appear on the book.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10/raspian] Ubuntu Server 18.03
 - Python version [e.g. python2.7] Python3
 - Calibre-Web version [e.g. 0.6.5 or master@16.02.20, 19:55 ]: 0.6.7
 - Docker container [ None/Technosoft2000/Linuxuser]: N/A
 - Special Hardware [e.g. Rasperry Pi Zero] N/A
 - Browser [e.g. chrome, safari] Chrome

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy]

Happy to answer questions.

**Comment by OzzieIsaacs** [comment]
Yes, this was indeed a bug, I fixed it recently. If you switch to nightly updates (admin section, basic configuration, server configuration) and update to the newest commit version, it should work.

**Comment by databoy2k** [comment]
Thanks; I hope I didn't just duplicate a bug report. I did search, though.

Nightly works great. All the fun of bleeding edge software, mind you, but looking forward to this hitting stable.
