### ISSUE TITLE
Handle more than one author during Kobo sync

### ISSUE THREAD

**Issue by OzzieIsaacs** [janeczku/calibre-web#1344]
**Describe the bug/problem**
During sync of to Kobo reader only the first author is synced. All author names should be transmitted

```
"BookMetadata" : {
  "ContributorRoles": [
    {
      "Name": "Garth Nix"
    },
    {
      "Name": "Leo and Diane Dillon"
    }],
  "Contributors": [ "Garth Nix", "Leo and Diane Dillon"],
```

**Logfile**
N/A

**Expected behavior**
Show all authors during sync

**Screenshots**
N/A

**Environment (please complete the following information):**
All

**Additional context**
N/A

**Comment by OzzieIsaacs** [comment]
@shavitmichael I have to come back to you with this issue. I implemented the response based on the example you gave me. I also found some examples on the web (https://github.com/TnS-hun/kobo-book-downloader/issues/7) suggesting it's right, but there is only one author showing up:
![IMG_0504](https://user-images.githubusercontent.com/6438895/86540050-292ee380-bf02-11ea-84ba-4c4bab6c7a82.JPG)
![grafik](https://user-images.githubusercontent.com/6438895/86540092-9773a600-bf02-11ea-99b8-4f09be76fd8c.png)
![grafik](https://user-images.githubusercontent.com/6438895/86540104-aa867600-bf02-11ea-954f-c47ed2ec7a87.png)
![grafik](https://user-images.githubusercontent.com/6438895/86540115-b8d49200-bf02-11ea-935a-ff6b282fed51.png)
Do you have a complete working sync example?

**Comment by shavitmichael** [comment]
Thanks for reaching out, I'm glad to see this is being kept alive :) .

This is a little puzzling however. I just tried out your commit (450411a), and it does show multiple authors on my device.

![IMG_20200707_020430](https://user-images.githubusercontent.com/4763500/86724066-755b5000-bff6-11ea-8cc5-a6e779fdb387.jpg)

For what it's worth though, here's a (partially redacted) response from the actual Kobo store:

> {
  "BookMetadata": {
    "CrossRevisionId": "0c72dbc2-97a8-4b0f-8808-870a6405231b",
    "RevisionId": "0b2bd2ee-d5bd-48aa-93ca-51baefcab5c6",
    "Publisher": {
      "Name": "HarperTeen",
      "Imprint": "HarperTeen"
    },
    "PublicationDate": "2009-10-06T04:00:00.0000000",
    "Language": "en",
    "Isbn": "9780061975134",
    "Genre": "87ddc38f-1048-45b4-9cc4-c66dd657d61d",
    "Slug": "sabriel-1",
    "CoverImageId": "e52427fd-3106-48d8-9613-0abe0617ca09",
    "IsSocialEnabled": true,
    "WorkId": "93e3dc1a-a877-3097-b769-519199b8fdea",
    "ExternalIds": [
      "od_8322"
    ],
    "IsPreOrder": false,
    "ContributorRoles": [
      {
        "Name": "Garth Nix"
      },
      {
        "Name": "Leo and Diane Dillon"
      }
    ],
    "IsInternetArchive": false,
    "Title": "Sabriel",
    "Description": "<p><em>Game of Thrones</em> fans will love the <em>New York Times</em> bestselling Abhorsen series. <em>Sabriel</em>, the first installment in the trilogy, launched critically acclaimed author Garth Nix onto the fantasy scene as a rising star.</p><p>Since childhood, Sabriel has lived outside the walls of the Old Kingdom, away from the power of Free Magic, and away from the Dead who refuse to stay dead. But now her father, the Abhorson, is missing, and Sabriel must cross into that world to fi...",
    "Categories": [
      "00000000-0000-0000-0000-000000000001",
      "87ddc38f-1048-45b4-9cc4-c66dd657d61d",
      "9adbbf41-5dbb-4d44-aff9-df784b3d4727",
      "fbe2f615-1c34-472f-87cc-46ced6b16bf7",
      "49103b40-0945-4d13-be5e-0ada45f2bcf3",
      "7dce010e-0e51-45ce-8a90-99e3ff2ef2a1",
      "7516907e-0cd5-4ffe-8bd2-2b7db1a6846e",
      "fbb06e66-7661-4b22-838c-4834e95bf42f",
      "1561e6f7-742f-4c1b-a804-187728814574",
      "5958de6e-7b94-4911-8af8-79e98e35ff33",
      "f9ef14d3-705d-4ae6-a169-15130fd6c60a"
    ],
    "Contributors": [
      "Garth Nix",
      "Leo and Diane Dillon"
    ],
    "Series": {
      "Id": "0aba6c0c-88e1-5dfd-acd7-c327c6ff4f01",
      "Name": "Old Kingdom",
      "Number": "1",
      "NumberFloat": 1
    },
    "CurrentDisplayPrice": {
      "TotalAmount": 8.99,
      "CurrencyCode": "USD"
    },
    "CurrentLoveDisplayPrice": {
      "TotalAmount": 0
    },
    "IsEligibleForKoboLove": false,
    "PhoneticPronunciations": {},
    "RelatedGroupId": "34d74a2f-1ce6-35a9-0000-000000000000"
  }
}

The only notable difference with 450411a is that the Kobo store doesn't ever seem to assign a "Role" field in the ContributorRoles   structure (at least not among the responses I've seen).

**Comment by OzzieIsaacs** [comment]
? For me it's not working for others it seems to do the job?
