### ISSUE TITLE
Remote calibre db

### ISSUE THREAD

**Issue by tiamilani** [janeczku/calibre-web#1348]
Hello, I'm writing this message because I was planning to use this application on a personal project and I have a question.

I was wondering, is possible to have the calibre db on another machine in the same network and retrieve/update the file? I was looking for this information in the wiki but I didn't find anything about it.

Thanks,
Mattia

**Comment by OzzieIsaacs** [comment]
If you are having the metadata.db file and the book files mounted on a samba share this should normally work (even if it is not recommended by the programmer of Calibre). There is one small entry in the Wiki regarding parallel access of Calibre and Calibre-Web (https://github.com/janeczku/calibre-web/wiki/FAQ#concurrent-access-calibre-and-calibre-web)
But if you start accessing the metadata.db file by other programs or start coping and syncing the metadata.db around with other locations, this will usually cause trouble (and I don't fix those sort of problems) as long as Calibre-Web is running in parallel.
