### ISSUE TITLE
Error after last update

### ISSUE THREAD

**Issue by ElQuimm** [janeczku/calibre-web#1355]
**Describe the bug/problem**
After the last update, server stop and not restart

**To Reproduce**
1. Simply update Calibre-web via update button

**Logfile**
[INFO] Launching Calibre-Web ...                                                                                                                                   
Traceback (most recent call last):                                                                                                                                 
  File "/calibre-web/app/cps.py", line 43, in <module>                                                                                                             
    from cps.editbooks import editbook                                                                                                                             
  File "/calibre-web/app/cps/editbooks.py", line 456                                                                                                               
    saved_filename, *os.path.splitext(requested_file.filename), config.config_rarfile_location)                                                                    
SyntaxError: only named arguments may follow *expression 

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: QNAP NAS with technosoft2000 docker container
 - last version

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy]

**Comment by ElQuimm** [comment]
Thank you.

**Comment by johnvick** [comment]
Same here on Technosoft Docker install upgrading from within the app to v 3.9-1

**Comment by flashliao** [comment]
find in cps/editbooks.py. 
Note line 456
saved_filename, *os.path.splitext(requested_file.filename), config.config_rarfile_location)
Change 
saved_filename, os.path.splitext(requested_file.filename), config.config_rarfile_location)

can open the website!

**Comment by OzzieIsaacs** [comment]
Sorry my fault: It's not your fault, that the docker container is running on python2

**Comment by ElQuimm** [comment]
Thank you. I have modified the two lines, and the server start again. Performed the update script with the application button and now all work perfectly.
Concerning pyton 2/3, I can write two lines to technosoft2000 with the suggestion of an update of the container version of pyton.
Thank you again.

**Comment by OzzieIsaacs** [comment]
No, please don't do it.

**Comment by OzzieIsaacs** [comment]
I didn't read the issue right, and I was writing the text for another issue. I meanwhile checked on the technosoft2000 web page that he tried to migrate to python3, but has some strange problem. So I don't want to encourage you to tease him for something he is already working on:
![grafik](https://user-images.githubusercontent.com/6438895/81207950-aa373080-8fce-11ea-97fa-a08896b2ccc1.png)

**Comment by ElQuimm** [comment]
Ok, thank you for the information. And for the job :-)

**Comment by theslash** [comment]
Worked for me too, thank you very much!!
