### ISSUE TITLE
Kepub books not renamed to kepub.epub when downloading

### ISSUE THREAD

**Issue by gpulido** [janeczku/calibre-web#1357]
When I try to download an already converted kepub book on calibre onto my Kobo device using the experimental browser the kobo doesn't download it as the kepub's are stored in calibre as .kepub and kobo needs them to be .kepub.epub (it is just a rename of the file adding the epub)
Several solutions:
1) add a flag to calibre web to "download kepub as kepub.epub" so all downloads are renamed. 
2) whenever a kepub format is found add another option to the download button to download the kepub.epub

I known there is some work done / being done onto the kobo sync functionality but this is "unrelated" as is just a way to download the kepub with the right extension.
Please forgive me if this has already asked or if there is any kind of workaround to solve this. I haven't found it yet.

**Comment by OzzieIsaacs** [comment]
I understood the problem, and I agree with you, this is not related to the kobo sync stuff

**Comment by gpulido** [comment]
Hello,
I'm reviewing the code and I will try to make a pr for this.
It seems very easy just to attach the .epub to the filename tag on the response headers if the fileformat is a Kepub. But that would mean that any download from the web of a kepub format it will include the kepub.epub.
At the end kepub is only used by kobo and it needs such extension, so maybe it make sense (is the same that is doing calibre when you send a kepub file to a kobo device), but it seems a bit patch to just do something like this (look to the real_book_format)
```python

def get_download_link(book_id, book_format):
    book_format = book_format.split(".")[0]
    book = db.session.query(db.Books).filter(db.Books.id == book_id).filter(common_filters()).first()
    if book:
        data1 = db.session.query(db.Data).filter(db.Data.book == book.id)\
            .filter(db.Data.format == book_format.upper()).first()
    else:
        abort(404)
    if data1:
        # collect downloaded books only for registered user and not for anonymous user
        if current_user.is_authenticated:
            ub.update_download(book_id, int(current_user.id))
        file_name = book.title
        if len(book.authors) > 0:
            file_name = book.authors[0].name + '_' + file_name
        file_name = get_valid_filename(file_name)
        real_book_format = book_format + '.epub' if book_format == 'kepub' else book_format
        headers = Headers()
        headers["Content-Type"] = mimetypes.types_map.get('.' + book_format, "application/octet-stream")
        headers["Content-Disposition"] = "attachment; filename=%s.%s; filename*=UTF-8''%s.%s" % (
            quote(file_name.encode('utf-8')), real_book_format, quote(file_name.encode('utf-8')), real_book_format)
        return do_download_file(book, book_format, data1, headers)
    else:
        abort(404)
```
However I don't know if that change should be done elsewhere, and also it means to put an specialized "business logic" inside such method.
One way to generalize is to add a new param to the method
```python
def get_download_link(book_id, book_format, real_book_format):
````
And let the callers hierarchy manage it, son at some point someone will need to add the .epub if it is a kepub. It could be also done with a defined map somehere in the code, but as this such special case I don't know if it is needed.
What do you think?

**Comment by OzzieIsaacs** [comment]
I changed the handling (well actually not I programmed it, special thanks to @vi-n ) , so via autodetection of the browser the file is renamed to kepub.epub, otherwise it stayes .kepub
