### ISSUE TITLE
Error after last update

### ISSUE THREAD

**Issue by flashliao** [janeczku/calibre-web#1358]
Error after last update

Error after last update,when I type sudo python cps.py,I can't open the website.

Traceback (most recent call last):
  File "cps.py", line 43, in <module>
    from cps.editbooks import editbook
  File "/home/liao/calibre-web-master/cps/editbooks.py", line 456
    saved_filename, *os.path.splitext(requested_file.filename), config.config_rarfile_location)
SyntaxError: only named arguments may follow *expression

**Environment (please complete the following information):**
 - OS: centos 7
 - Python v2

**Comment by OzzieIsaacs** [comment]
I fixed it, please try newest commit version.
Python2 is end of life since end of december 2020, you should consider to switch to python3. Calibre-Web is regulary tested with Python3 (and only with python2)
