### ISSUE TITLE
Can I batch-fill shelves?

### ISSUE THREAD

**Issue by TalmarGrosskotz** [janeczku/calibre-web#136]
Hi I installed your program and pointed it to my rather large calibre-database. Since I own a series with 100+ episodes, I find it exhauting to add them individually to a shelf. Is there a way to "mass-add" books to a shelf?

**Comment by OzzieIsaacs** [comment]
Currently there is no such function, and its not planned either. 
Possible way of doing it: 
Generate a csv catalog of all books in calibre (menu convert books)
Manually sort out, the books to add to shelf
write a short python script: open catalog file, login via requests, and then post each book id to add shelf path in calibre-web "http://ip-adress:8083/shelf/add/[shelf-id]/[book-id]

**Comment by OzzieIsaacs** [comment]
Please try this one:
https://github.com/OzzieIsaacs/cps-shelf-adder

**Comment by TalmarGrosskotz** [comment]
Tried it,

works great! Thanks a lot!


Am 15.03.2017 um 20:23 schrieb Ozzie Isaacs:

**Comment by Riccardomirto** [comment]
Hi, I am so happy I have found this post, but I have tried to run the script and can never login to calibre-web. it is running on 8083, user are correct. how can I troubleshoot it? I have many books to add to shelf, manual work will be madness :) Thanks!

**Comment by OzzieIsaacs** [comment]
I changed the script to make it work with current version of calibre-web. Please download latest commit.

**Comment by Riccardomirto** [comment]
It  connect now, thanks!

I still get an error, and working on it :)

> root@CalibreServer:~# python mass_add_books.py
> Traceback (most recent call last):
>   File "mass_add_books.py", line 19, in <module>
>     add=requests.get(serveradress+'/shelf/add/'+shelf_id+'/'+current_row['id'],cookies=r.cookies,headers=headers)
> KeyError: 'id'


The csv file content is like this:

auths;title;id
Agatha Christie;Alla deriva;69
...

**Comment by OzzieIsaacs** [comment]
Hello,

the items have to be comma seperated, then it should work.

**Comment by Riccardomirto** [comment]
Hi. Script works fine but books are not listed in the shelf when I login to calibre-web. I tried different users and shelf id but same result. I am using tags for now, but you might want to investigate it. Cheers

root@CalibreServer:~# python mass_add_books.py
Book with id 71 was sucessfully add to shelf
Book with id 72 was sucessfully add to shelf
Book with id 73 was sucessfully add to shelf
Book with id 74 was sucessfully add to shelf
root@CalibreServer:~#

**Comment by OzzieIsaacs** [comment]
Tried it, for me its working.
Just to make it sure: The shelf_id is not the name of the shelf to add, but the number of the shelf in the adress line of your browser, if you look at the shelf. 
I improved the adding srcipt to display more information in case anything is wrong

**Comment by Gronda74** [comment]
Hi, I was looking for a way to organize the 500+ comics in a library and this looked like the solution to my needs. But having created a csv of just the relevant id's and tweaked the script to my config, when I run it I get: 

```
Traceback (most recent call last):
File "c:\Users\Guy\Desktop\mass_add_books.py", line 1, in <module> 
    import requests
ImportError: No module named 'requests'
```

What am I missing?

**Comment by OzzieIsaacs** [comment]
you need to install ‚requests‘ via ‚pip install requests‘
if you are gettimg import errors afterwards you have to install the named modules the same way like above mentioned

**Comment by Gronda74** [comment]
Thanks. That seems to have moved me on and I've ended up putting the csv file in the Python directory as otherwise it couldn't find it (apologies, I'm not great with command line stuff anymore). Now I'm getting:

```
C:\Python34>python.exe c:\temp\mass_add_books.py
Traceback (most recent call last):
  File "c:\temp\mass_add_books.py", line 20, in <module>
    for current_row in reader:
  File "C:\Python34\lib\csv.py", line 109, in __next__
    self.fieldnames
  File "C:\Python34\lib\csv.py", line 96, in fieldnames
    self._fieldnames = next(self.reader)
_csv.Error: line contains NULL byte
```

**Comment by OzzieIsaacs** [comment]
looks like there are empty lines in the csv file (maybe the last line?)

**Comment by Gronda74** [comment]
There was a blank last line which I've just deleted but I get the same error message. The csv file only has the one column with id in the first line and then the id numbers one per line after that.

**Comment by Gronda74** [comment]
Hmm, still not working here but I'm on Python 3.4. I'll see about installing 3.6 or 2.7 tomorrow and also try some variants of the source csv file. Thanks for your help!

**Comment by OzzieIsaacs** [comment]
Meanwhile it‘s also possible to add the result of a Advanced search to a shelf inside Calibre-Web

**Comment by Gronda74** [comment]
Still no joy and the same error message using a newly installed Python 2.7.

My .csv file is in the format:

> id
> 123
> 456
> 789

I've tried editing it to read

> id123,456,789

And

> id,123,456,789

Neither worked. And with the advanced search I haven't found a way to have the comics listed in publish date order - is there a search term I can include for this?

**Comment by OzzieIsaacs** [comment]
The First one is suppost to work, the other two can‘t work. Have you tried my uploaded file? Do you get always the same error message?

The Advanced search doesn‘t offer an option to sort the results. But afterwards you can arrange the books in the shelf (for 500 books maybe not practical)

**Comment by Gronda74** [comment]
Your test file worked so I played around with my file a bit more. It's now working by me copying the text out of my file and pasting it into yours via Notepad++. Not sure what's going on here - I used Calibre to export the data and Excel 2013 to sort it and then remove all data but the ID's. I'd opened the file in Notepad and Notepad++ a few times to edit it as just the ID numbers and then saved it. But the script is working wonderfully! Thank you so much for the script and the help.

**Comment by OzzieIsaacs** [comment]
maybe it‘s encoding or line ending problem (both are somewhere options in notepad++) I‘m happy that’s working now

**Comment by OzzieIsaacs** [comment]
freaky

**Comment by j-moran** [comment]
I had the best luck by importing it into a google sheet and then exporting it again as a csv. However you get it to work I suppose.

**Comment by dirtymurt** [comment]
I had to open it in Excel, save it as "csv (MS Dos)" then it ran fine.
