### ISSUE TITLE
Archive book -> missing cover

### ISSUE THREAD

**Issue by stfrbrntyu** [janeczku/calibre-web#1361]
After archiving a book, the cover in the Archived books section shows the default placeholder "Cover not available".

**To Reproduce**
1. Archive a random book
2. goto Archived books section
3. Press ctrl F5 (or any other shortcut to reload the images in the browser)
4. Cover has changed to "Cover not available".

**Comment by OzzieIsaacs** [comment]
It's fixed in the newest commit
