### ISSUE TITLE
info archived flag

### ISSUE THREAD

**Issue by armandoss** [janeczku/calibre-web#1362]
hi guys
today I reinstalled caliber web.
I noticed the Archived item to be selected in under the read item.
it is possible to remove it ... I don't remember ever having seen it before ... maybe I'm wrong but with the dark weather it's a bit annoying.
thank you very much

**Comment by OzzieIsaacs** [comment]
Every user can adjust the viewable items in the sidebar in the users config section

**Comment by armandoss** [comment]
yes I looked everywhere but I can't find anything to cut that flag. having never noticed it, I ask you even if it appears to you.
thanks

**Comment by OzzieIsaacs** [comment]
Okay, I‘m not sure if we are talking about the same thing. There are many issues in the past where people posted unspecific problems and it took me hours to figure out what we are talking about. I‘m pretty sure upon creating this request you saw a form and one of the requested information was screenshot, I this this would help me to understand your problem

**Comment by armandoss** [comment]
![Immagine](https://user-images.githubusercontent.com/65025113/81411366-901e5f00-9142-11ea-9140-1f49a1476941.jpg)

at the top right that option appears to me.
I don't think I've ever seen her before.

**Comment by yeraycito** [comment]
I updated the software yesterday and I have the same problem.

**Comment by armandoss** [comment]
ok then I remembered never having seen him.
it's quite annoying ... I put the original theme back where it is at least done so as not to bother in the metadata window. if there is no way to eliminate it, the only way is to system the ui with the calibur theme

**Comment by OzzieIsaacs** [comment]
I changed the behavior, if you have the archived book section not visible, the new option is not visible anymore.
