### ISSUE TITLE
Add 2fa authentication

### ISSUE THREAD

**Issue by yeraycito** [janeczku/calibre-web#1363]
I would like to ask to include access authorization in 2 factors ( Authy - Google Authenticator ).
LDAP Login - OAuth Login with Github and Google are really complicated to use. I use their fantastic software in my nas via docker ( linuxserver/calibre-web ).

**Comment by OzzieIsaacs** [comment]
https://github.com/janeczku/calibre-web/blob/master/CONTRIBUTING.md#feature-request
I decided to add no more login abilities
