### ISSUE TITLE
Spanish language error: Nickname/Usuario

### ISSUE THREAD

**Issue by yeraycito** [janeczku/calibre-web#1365]
![Screenshot_20200508_220425](https://user-images.githubusercontent.com/65027248/81445080-8c0d3400-9178-11ea-8806-89041757b246.png)

**Comment by OzzieIsaacs** [comment]
https://github.com/janeczku/calibre-web/blob/master/CONTRIBUTING.md

**Comment by OzzieIsaacs** [comment]
Pleas change the wrong translations in the translation file and provide the info as described in the contribution rules. 
Thank you
