### ISSUE TITLE
Get rid of underscorejs

### ISSUE THREAD

**Issue by jvoisin** [janeczku/calibre-web#1374]
Currently calibre-web is using underscorejs to render templates.
Unfortunately, it [doesn't]( https://github.com/jashkenas/underscore/issues/906 ) play nice with CSP.

If this is a welcomed change, and if someone can suggest an other way of doing templates, I'll be happy to do the leg work and send a pull-request.

**Comment by OzzieIsaacs** [comment]
The only thing I see where underscore.js intention.js and context.js are used is the add and remove book to shelf function in books detail view.
I'm not sure if there is really some javascript libraries needed, maybe if you don't try to replace one lib with another, but just try to solve the task it's needed for in a different way this would do the job.
