### ISSUE TITLE
import errors in 0.6.7

### ISSUE THREAD

**Issue by b-t-k** [janeczku/calibre-web#1376]
**When trying to run new version**
`Mini-Media-Server:~ admin$ python3 /pythonweb/calibre-web-master/cps.py
Traceback (most recent call last):`
`File "/pythonweb/calibre-web-master/cps.py", line 34, in <module> from cps import create_app`
`File "/pythonweb/calibre-web-master/cps/__init__.py", line 28, in <module>  from babel import Locale as LC`
`ModuleNotFoundError: No module named 'babel'`

If I go back to the old version it works fine. (I can't find where the old version number  is, but iirc it is the previously released version.) Any idea what has gone wrong?

Mac OS 10.13.6
Python 3.7.7 (and 2.7.16)

**Comment by OzzieIsaacs** [comment]
The version number is displayed in admin section and then scroll down to the bottom. Would be helpful to know it. It's possible to be something like 0.6.6 but also a simple date.
Did you change your python version in between, or was it always 3.7? You also checked 2.7?
In the running version could you please paste the content of the about section? (I'm after the dependencies and version numbers?)
How did you install the dependencies? Systemwide, or did you use the procedure described in the readme?

**Comment by OzzieIsaacs** [comment]
Did you update it by deleting the whole files and then coping the new version into the then empty path? Did you perform the pip command afterwards? For making your old copy run, did you copy the whole path content back (including the vendor folder)?

**Comment by OzzieIsaacs** [comment]
For easiest update, just press search for update, then update, wait for the update to finish and I‘m sure it will work afterwards

**Comment by b-t-k** [comment]
I simply replaced the files (which worked last time) because I modify the templates by hand to add series info. But the Update button did it—didn't even know it existed. I can go back and edit the templates after the fact. Sorry for such a amateurish mistake :-)
