### ISSUE TITLE
Prevent Users from Deleting Public Shelves

### ISSUE THREAD

**Issue by galacticat** [janeczku/calibre-web#138]
It would be nice to have a little control over users ability to delete things like a Public Shelf. If you spend an hour putting books together in a Shelf group, only to have a user accidentally delete it, then it really sucks.

**Comment by OzzieIsaacs** [comment]
There is now a new user role "editing public shelfs". 
Before deleting the shelf a dialog pops up with a security questions.
By default all exisiting useres are no longer allowed to create/delete/rename and reorder public shelfs (its not possible to migrate the current setting)

**Comment by galacticat** [comment]
This is awesome!
