### ISSUE TITLE
Rework Integration: Calibredb - Enable new option to use Calibre Content Server - Solves Metadata/Uploading not updating in Calibre

### ISSUE THREAD

**Issue by MollyBe** [janeczku/calibre-web#1380]
When editing metadata or uploading in Calibre-Web it will not be reflected in your Calibre library until you restart Calibre. 

By enabled the option to use the Calibre Content Server with a specified URL, username and password in Calibre-Web changes will be reflected in Calibre instantly.

The alternative is to use an older version of Calibre.

Here is a better description, https://lazylibrarian.gitlab.io/config_processing/#calibre

**Comment by OzzieIsaacs** [comment]
This sounds like a docker problem if you use the normal installation the database is updated instantly
