### ISSUE TITLE
Visibility restrictions containing '&' cannot be deleted

### ISSUE THREAD

**Issue by philipsd6** [janeczku/calibre-web#1382]
**Describe the bug/problem**
When setting tag visibility for a user, if a tag is selected that contains an ampersand, it cannot then be deleted. One has to edit the tag to remove the ampersand and then it can be removed.

**To Reproduce**
1. Go to UI Configuration -> Default Visibilities for New Users
2. Click on Add Allowed/Denied Tags
3. Add View Restriction for "Science & Technology" either Allow/Deny (doesn't matter)
4. Then click on the trashcan to delete that restriction -- Nothing happens!

**Logfile**
Nothing shows up in the log file for this issue.

**Expected behavior**
The view restriction should be deleted

**Screenshots**

**Environment (please complete the following information):**
 - OS: Linux 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64
 - Python version: 3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0]
 - Calibre-Web version: 0.6.7 - 0735fb1e929fd673397acdd7e2c1c8be0d510d3f - 2020-05-05T20:28:10+02:00
 - Docker container: linuxserver/calibre-web:latest
 - Special Hardware:
 - Browser: Firefox

**Additional context**
Accessing via reverse proxy, but not relevant to this issue.

**Comment by OzzieIsaacs** [comment]
Thank you for the detailed report. 
As workaround you could rename the Tag, remove the "&" and than you can delete it

**Comment by philipsd6** [comment]
Yes, that's what I noted in the summary -- glad I figured that out before I went crazy.

**Comment by OzzieIsaacs** [comment]
Sorry, didn't realize that sentence. 
I fixed it in the master branch (was an unescaped string), I hope you can work with it till I create a new release (hopefully end of May)

**Comment by OzzieIsaacs** [comment]
The new Release with the fix is out
