### ISSUE TITLE
Kobo sync handling of kepub/epub

### ISSUE THREAD

**Issue by davidelias** [janeczku/calibre-web#1383]
I've being using the new kobo sync for a few days and is awesome, thanks :)

I've converted all my epubs to kepubs with kepubify and added them to calibre. When I download a book from my kobo, checking calibre-web's access log, I've noticed that it downloads the epub format and works just fine, at least it seems to have all the kepubs features but I could be missing something.
I've changed calibre-web to only list kepubs in the kobo sync api and it works just the same.

So my questions are, does nickel do the conversion itself or should calibre-web only list the kepub format in `DownloadUrls: []`?

**Comment by OzzieIsaacs** [comment]
I think the kobo reader doesn't do the conversion (but I'm not sure, I only use epub up to now). 
Maybe this is releated to #1357
I need some time to check it

**Comment by davidelias** [comment]
> I think the kobo reader doesn't do the conversion (but I'm not sure, I only use epub up to now).

Yeah, what probably happens is that nickel assumes everything coming through the sync api is an epub and opens it with the access reader.

> Maybe this is releated to #1357

I don't think so, I think that one is related with downloading directly from calibre-web's ui.

I think it's more related to this one #1219 

Thanks :)

**Comment by OzzieIsaacs** [comment]
#1219 is fixed, so should be solved
