### ISSUE TITLE
Private shelves are listed twice in the "Add to shelf" dropdown menu

### ISSUE THREAD

**Issue by philipsd6** [janeczku/calibre-web#1385]
**Describe the bug/problem**
When adding books to a shelf from search results, using the "Add to shelf" dropdown menu, my private bookshelves are displayed twice: one at the top, then the public shelves, and then my private shelves again at the bottom.

**To Reproduce**
1. Create some public and private bookshelves
2. Do a search
3. Click on "Add to shelf..."
4. See the duplicate shelf names

**Logfile**
Nothing in logs.

**Expected behavior**
The shelves listed should be a unique set

**Screenshots**
![m1kfBXsrud](https://user-images.githubusercontent.com/908201/81610083-e986c800-93a6-11ea-875f-5d4ad07cea64.png)

**Environment (please complete the following information):**
    - OS: Linux 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64
    - Python version: 3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0]
    - Calibre-Web version: 0.6.7 - 0735fb1 - 2020-05-05T20:28:10+02:00
    - Docker container: linuxserver/calibre-web:latest
    - Special Hardware:
    - Browser: Firefox

**Additional context**
 Accessing via reverse proxy, but not relevant to this issue.

**Comment by OzzieIsaacs** [comment]
I found it and fixed it in the master branch
