### ISSUE TITLE
Google Drive - Shared Drives

### ISSUE THREAD

**Issue by delize** [janeczku/calibre-web#1388]
**Is your feature request related to a problem? Please describe.**
Provide support for Google Drive's shared / team drives. 

**Describe the solution you'd like**
The ability to use Shared Drives / Team Drives to host the database file and it's contents.

**Describe alternatives you've considered**
I have tried using rclone as a host mount, and then volume bind it to the docker container, but this fails.

**Additional context**
I noticed from a crash that you have SharedDrives set to false, enabling this and modifying the code to support should be the solution.

**Comment by OzzieIsaacs** [comment]
I decided not to add any more storage providers (https://github.com/janeczku/calibre-web/blob/master/CONTRIBUTING.md)
