### ISSUE TITLE
Unable to send email, instant error out.

### ISSUE THREAD

**Issue by nickisagod** [janeczku/calibre-web#1394]
I am no longer able to send emails, the task fails instantly. I have tried switching to a different email account but that is the same.

**Logfile**
[2020-05-14 14:40:58,446] ERROR {cps.worker:520} Error sending email: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1076)

**Environment (please complete the following information):**
 - OS: Windows 7
 - Python version 3.7
 - Calibre-Web version 0.6.7
 - Docker container None
 - Browser Chrome

**Comment by nickisagod** [comment]
Good news I have it working, I had tested SSL/TLS and none but this time I tested with STARTTLS and it worked. This is with the smtp.live.com for anyone using outlook, hotmail etc

**Comment by samisme0818** [comment]
thank you.

> Good news I have it working, I had tested SSL/TLS and none but this time I tested with STARTTLS and it worked. This is with the smtp.live.com for anyone using outlook, hotmail etc
