### ISSUE TITLE
SSL Certificate

### ISSUE THREAD

**Issue by yeraycito** [janeczku/calibre-web#1396]
I have a certificate created with letsencrypt. I have installed it and when doing so, access to linuxserver-calibreweb is blocked with the following error message:
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:852)                                                                 
2020-05-15T13:31:46Z <Greenlet at 0x7fd8e68cab48: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound met
hod StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x7fd8e684254)> failed with SSLError  
Linuxserver-calibreweb running on port 8083

**Comment by OzzieIsaacs** [comment]
Not reproducible with the info you gave me. 
Could be a docker problem, maybe?
This wrong version number error is throw if you try to access an encrypted server with an not encrypted request
