### ISSUE TITLE
Audiobook M4B, M4A Support not working

### ISSUE THREAD

**Issue by jvimedia** [janeczku/calibre-web#1397]
**Description: 

when trying to either download or open file types of M4B or M4A calibre web doesn’t show any progress or ay feedback and does not start the download in safari or chrome and doesn’t start play back either.

**Expected behavior**
I expected it to at least download the audio file.

**Environment (please complete the following information):**
 - OS: macOS Safari, Chrome, iOS Safari

**Comment by OzzieIsaacs** [comment]
Looks like the used script for playing m4a and m4b sound isn't capable of doing so. So the solution would be changing the documentation and removing the "support" for m4a, m4b files. 
Good news: We can add ogg files to the playable formats

**Comment by OzzieIsaacs** [comment]
I added a fix which removes m4a and m4b from the playable formats. 
I hope you understand that I'm not providing a fix for enabling the feature, as this is more than one year broken and nobody realized it. I'd like to focus more on the common requested features.

**Comment by jvimedia** [comment]
Okay, I understand this. Sad, but you are right.

Just to clarify. Maybe I'll open a secondary Bug for that:
In case of having already unsupported file types e.g. m4a files in the library from a local calibre installation. 

I just want to download it, not play it or anything alike. I run into this issue.

[2020-05-20 00:01:06,519] ERROR {tornado.application:67} Uncaught exception
Traceback (most recent call last):
  File "/root/calibre-web/vendor/tornado/http1connection.py", line 273, in _read_message
    delegate.finish()
  File "/root/calibre-web/vendor/tornado/httpserver.py", line 280, in finish
    self.request_callback(self.request)
  File "/root/calibre-web/vendor/tornado/wsgi.py", line 118, in __call__
    body = b"".join(response)
MemoryError
[2020-05-20 00:01:18,366] ERROR {tornado.application:67} Uncaught exception
Traceback (most recent call last):
  File "/root/calibre-web/vendor/tornado/http1connection.py", line 273, in _read_message
    delegate.finish()
  File "/root/calibre-web/vendor/tornado/httpserver.py", line 280, in finish
    self.request_callback(self.request)
  File "/root/calibre-web/vendor/tornado/wsgi.py", line 118, in __call__
    body = b"".join(response)
MemoryError

<img width="716" alt="Bildschirmfoto 2020-05-20 um 00 59 15" src="https://user-images.githubusercontent.com/4837419/82386805-a4613680-9a35-11ea-8b14-3e37154d70cd.png">

**Comment by OzzieIsaacs** [comment]
How big is the file? Sounds like out of memory. One thing you could try is installing gevent via pip, this might help

**Comment by jvimedia** [comment]
About 350mb

**Comment by dhernan3** [comment]
Sorry, but I don't understand. I usually used Plex to play audiobooks, until I discovered Calibre-Web also supported m4b, mp3.
I've updated today to latest version, 0.6.8 from 0.6.6, and found my m4b are not playing. After a bit of searching, I discovered this bug.
I've not had any problems with my m4b files. Also, I've modified the constants.py from this version and added again support to m4b, and it plays nicely, both on my macOS (Catalina 10.15.5 and Safari 13.1.1) and my iPhone 7 with latest iOS 13.5.1 and Safari. Chrome on Android (Huawei Smart 2019) also works.

**Comment by OzzieIsaacs** [comment]
Was my fault, I didn't read the documentation right. I missed the part about m4a and m4b. I didn't check it really for the initial problem.

**Comment by adocampo** [comment]
I hate to be that guy, but m4b files doesn't play again. Progress bar gets stalled and doesn't show the total duration either
![image](https://user-images.githubusercontent.com/2266612/94730181-1ee67f00-0363-11eb-88a1-f3521f1351a6.png)
File plays nicely with any audio player, file specs are:
```
$ file Sidi\ -\ Arturo\ Pérez\ Reverte.m4b 
Sidi - Arturo Pérez Reverte.m4b: ISO Media, Apple iTunes ALAC/AAC-LC (.M4A) Audio
$ ls -lah Sidi\ -\ Arturo\ Pérez\ Reverte.m4b 
-rw-r--r-- 1 malevolent wheel 607M Sep 30 17:32 'Sidi - Arturo P'$'\303\251''rez Reverte.m4b'
```
Any ideas?

**Comment by adocampo** [comment]
Never mind... I've created a new m4b file from mp3 files, and this one works. So I guess the problem is with the file I uploaded before.

Anyway, it seems this player can't jump to chapters and doesn't save the position, isn't it?
