### ISSUE TITLE
Make app.db path configurable

### ISSUE THREAD

**Issue by aserrallerios** [janeczku/calibre-web#1401]
Title says it all. Motivation:

I want to backup the app.db file in a different location (so I can install calibre-web anywhere with no risks) and then "mount" it so it's available to the running calibre-web app. Mounting a single file can be problematic in some environments.

**Comment by OzzieIsaacs** [comment]
You can choose the path to the app.db via command line argument: https://github.com/janeczku/calibre-web/wiki/Command-Line-Interface#command-line-options

**Comment by aserrallerios** [comment]
Missed that! Thanks!
