### ISSUE TITLE
sqlite3.OperationalError: too many SQL variables With more than 1000 read books

### ISSUE THREAD

**Issue by Jedi5000** [janeczku/calibre-web#1407]
After a long Time my Books finally exceeded the Number of 1000.

Now when clicking on "unread" or "read" above  Error occurs
(Can provide a Log if required but I think the issue is clear here, see below).
Calibre-Web Version is 0.6.8. (but also tried with 0.6.7.)
Occurs with any Browser in a Win2019-Server Environment (no Docking Container)

As I understand this is because I have to increase the  SQLITE_MAX_VARIABLE_NUMBER (default 999).
As I'm surley not the only one who has 1000 Books, is there a Solution for this?

Is there really a need for recompiling with a higher number? (If so is there a File to be provided to just change to avoid this message?).

Or can I edit app.db with a Sql-DB-Editor and increase this Number by my own?

Or is there any other solution to this (couldn't find any though)?

Any help on this issue would be appreciated :)

Thank you.

**Comment by OzzieIsaacs** [comment]
You many not the only one with more than 1000 books, but the only one having the problem (smily):
![grafik](https://user-images.githubusercontent.com/6438895/82346789-3138cf80-99f7-11ea-9e37-3a2d314df506.png)
(Tested under linux)

**Comment by OzzieIsaacs** [comment]
Checked it under windows 10 (this is as near as I come to the win2019 server):
![grafik](https://user-images.githubusercontent.com/6438895/82349492-701c5480-99fa-11ea-81ce-1a4c299ac66e.png)
No problem. 
So logbooks is not clear, please paste complete error message, so I can check where it fails. To many sql variables would mean that there are more than 1000 parameters in one query, where I currently not aware of where this could be. 
Please also paste all dependencies (the about section)
I opened app.db with a sql editor, and didn't find the setting. So currently I have no idea.

**Comment by OzzieIsaacs** [comment]
And please describe any specialitys you use (like remote storage or so)

**Comment by OzzieIsaacs** [comment]
I used a new app.db and the read status isn't linked to any custom calibre-column and no tags or custom columns are hidden

**Comment by OzzieIsaacs** [comment]
![grafik](https://user-images.githubusercontent.com/6438895/82350124-3bf56380-99fb-11ea-9a40-3ffbdea1cca3.png)

**Comment by Jedi5000** [comment]
Hi

here's the complete Log:
[2020-05-19 17:16:10,373] ERROR {cps:1892} Exception on /read/new/ [GET]
Traceback (most recent call last):
  File "D:\BooksServer\calibre-web-master\vendor\sqlalchemy\engine\base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "D:\BooksServer\calibre-web-master\vendor\sqlalchemy\engine\default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: too many SQL variables

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\BooksServer\calibre-web-master\vendor\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\BooksServer\calibre-web-master\vendor\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\BooksServer\calibre-web-master\vendor\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\BooksServer\calibre-web-master\vendor\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\BooksServer\calibre-web-master\vendor\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\BooksServer\calibre-web-master\vendor\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\BooksServer\calibre-web-master\cps\web.py", line 185, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "D:\BooksServer\calibre-web-master\vendor\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\BooksServer\calibre-web-master\cps\web.py", line 629, in books_list
    return render_read_books(page, True, order=order)
  File "D:\BooksServer\calibre-web-master\cps\web.py", line 1119, in render_read_books
    entries, random, pagination = fill_indexpage(page, db.Books, db_filter, order)
  File "D:\BooksServer\calibre-web-master\cps\helper.py", line 817, in fill_indexpage
    return fill_indexpage_with_archived_books(page, database, db_filter, order, False, *join)
  File "D:\BooksServer\calibre-web-master\cps\helper.py", line 829, in fill_indexpage_with_archived_books
    .filter(common_filters(allow_show_archived)).all()))
  File "D:\BooksServer\calibre-web-master\vendor\sqlalchemy\orm\query.py", line 3246, in all
    return list(self)
  File "D:\BooksServer\calibre-web-master\vendor\sqlalchemy\orm\query.py", line 3405, in __iter__
    return self._execute_and_instances(context)
  File "D:\BooksServer\calibre-web-master\vendor\sqlalchemy\orm\query.py", line 3430, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "D:\BooksServer\calibre-web-master\vendor\sqlalchemy\engine\base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "D:\BooksServer\calibre-web-master\vendor\sqlalchemy\sql\elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "D:\BooksServer\calibre-web-master\vendor\sqlalchemy\engine\base.py", line 1103, in _execute_clauseelement
    distilled_params,
  File "D:\BooksServer\calibre-web-master\vendor\sqlalchemy\engine\base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "D:\BooksServer\calibre-web-master\vendor\sqlalchemy\engine\base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "D:\BooksServer\calibre-web-master\vendor\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "D:\BooksServer\calibre-web-master\vendor\sqlalchemy\engine\base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "D:\BooksServer\calibre-web-master\vendor\sqlalchemy\engine\default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) too many SQL variables
[SQL: SELECT books.id AS books_id, books.title AS books_title, books.sort AS books_sort, books.author_sort AS books_author_sort, books.timestamp AS books_timestamp, books.pubdate AS books_pubdate, books.series_index AS books_series_index, books.last_modified AS books_last_modified, books.path AS books_path, books.has_cover AS books_has_cover, books.uuid AS books_uuid 
FROM books 
WHERE books.id IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) AND 1 = 1]
[parameters: (1568, 1567, 1557, 1556, 1554, 1555, 1552, 1553, 1551, 1548, 1550, 1549, 1540, 1537, 1536, 1539, 1526, 1535, 1521, 1516, 1515, 1514, 1511, 1510, 1509, 1500, 1519, 1518, 1523, 1498, 1499, 1497, 1496, 1495, 1489, 1493, 1494, 1488, 1475, 1478, 1476, 1469, 1468, 1452, 1471, 1473, 1443, 1522, 1448, 1450, 1440, 1436, 1298, 1437, 1560, 1566, 1559, 1525, 1524, 1558, 1520, 1547, 1517, 1508, 1507, 1506, 1505, 1504, 1503, 1502, 1501, 1492, 1490, 1491, 1487, 1486, 1485, 1484, 1483, 1482, 1481, 1480, 1479, 1477, 1474, 1472, 1470, 1467, 1466, 1465, 1464, 1463, 1462, 1461, 1460, 1458, 1457, 1456, 1455, 1454, 1451, 1453, 1449, 1447, 1445, 1577, 1578, 1446, 1442, 1441, 1444, 1438, 1434, 1459, 1435, 1426, 1433, 1439, 1432, 1431, 1429, 1430, 1428, 1427, 1425, 1424, 1423, 1422, 1421, 1420, 1419, 1418, 1417, 1416, 1403, 1406, 1404, 1405, 1401, 1402, 1399, 1400, 1398, 1396, 1395, 1394, 1393, 1397, 1407, 1392, 1391, 1389, 1387, 1386, 1388, 1384, 1390, 1313, 1415, 1414, 1413, 1411, 1409, 1408, 1412, 1385, 1410, 1383, 1382, 1381, 1379, 1378, 1377, 1376, 1375, 1374, 1373, 1372, 1380, 1371, 1370, 1368, 1367, 1366, 1365, 1369, 1363, 1364, 1361, 1360, 1362, 1359, 1357, 1356, 1355, 1358, 1354, 1352, 1351, 1350, 1353, 1348, 1347, 1346, 1345, 1349, 1344, 1342, 1343, 1340, 1341, 1339, 1337, 1336, 1338, 1334, 1335, 1333, 1331, 1330, 1332, 1329, 1328, 1327, 1325, 1324, 1323, 1322, 1318, 1321, 1320, 1326, 1316, 1317, 1319, 1315, 1312, 1310, 1311, 1314, 1308, 1309, 1307, 1305, 1306, 1303, 1301, 1304, 1302, 1297, 1300, 1295, 1296, 1299, 1293, 1294, 1292, 1290, 1288, 1291, 1285, 1287, 1289, 1284, 1283, 1282, 1281, 1286, 1278, 1280, 1279, 1276, 1275, 1277, 1274, 1273, 1272, 1271, 1270, 1269, 1267, 1268, 1266, 1265, 1264, 1263, 1262, 1259, 1260, 1261, 1257, 1255, 1258, 1256, 1253, 1251, 1254, 1252, 1249, 1247, 1250, 1246, 1248, 1245, 1244, 1243, 1242, 1240, 1239, 1235, 1241, 1237, 1236, 1233, 1232, 1234, 1238, 1231, 1230, 1224, 1226, 1228, 1227, 1223, 1225, 1221, 1213, 1220, 1229, 1219, 1217, 1222, 1218, 1216, 1212, 1215, 1211, 1214, 1210, 1209, 1208, 1207, 1205, 1201, 1204, 1206, 1203, 1200, 1199, 1198, 1197, 1195, 1202, 1196, 1193, 1192, 1191, 1190, 1194, 1188, 1189, 1187, 1186, 1184, 1185, 1182, 1183, 1172, 1180, 1178, 1179, 1181, 1175, 1171, 1173, 1169, 1176, 1174, 1177, 1170, 1168, 1167, 1165, 1164, 1163, 1162, 1160, 1161, 1166, 1158, 1159, 1156, 1157, 1154, 1155, 1152, 1153, 1150, 1151, 1148, 1147, 1149, 1145, 1143, 1146, 1142, 1144, 1141, 1136, 1140, 1139, 1135, 1137, 1138, 1134, 1132, 1130, 1133, 1131, 1129, 1128, 1127, 1126, 1125, 1124, 1122, 1123, 1120, 1121, 1119, 1117, 1116, 1118, 1112, 1110, 1115, 1114, 1113, 1111, 1109, 1107, 1108, 1106, 1105, 1104, 1103, 1102, 1101, 1100, 1099, 1098, 1095, 1097, 1096, 1094, 1092, 1090, 1091, 1093, 1089, 1088, 1087, 1085, 1086, 1082, 1083, 1080, 1084, 1081, 1077, 1078, 1079, 1076, 1075, 1074, 1071, 1070, 1073, 1072, 1069, 1068, 1067, 1066, 1065, 1064, 1061, 1062, 1059, 1060, 1063, 1058, 1056, 1055, 1054, 1052, 1053, 1050, 1049, 1051, 1048, 1057, 1047, 1046, 1045, 1044, 1042, 1043, 1041, 1039, 1040, 1038, 1035, 1032, 1036, 1037, 1034, 1033, 1029, 1027, 1030, 1026, 1031, 1024, 1025, 1021, 1022, 1019, 1017, 1023, 1016, 1028, 1020, 1018, 1013, 1015, 1012, 1014, 1011, 1010, 1008, 1009, 1006, 1007, 1005, 1002, 1003, 1004, 1000, 1001, 999, 994, 998, 997, 996, 995, 992, 993, 990, 989, 991, 988, 986, 987, 985, 984, 983, 982, 981, 980, 978, 979, 977, 976, 975, 974, 973, 971, 972, 969, 970, 968, 967, 965, 966, 964, 963, 962, 961, 960, 959, 958, 956, 957, 946, 955, 954, 953, 952, 950, 951, 949, 947, 945, 948, 944, 943, 942, 939, 941, 938, 936, 937, 935, 933, 934, 931, 932, 930, 929, 928, 925, 926, 927, 924, 923, 922, 920, 921, 919, 918, 917, 916, 915, 913, 912, 914, 908, 907, 905, 903, 904, 901, 902, 900, 899, 898, 897, 891, 889, 888, 890, 896, 883, 886, 882, 884, 881, 885, 880, 878, 879, 893, 874, 876, 875, 872, 877, 892, 866, 895, 887, 894, 871, 873, 864, 863, 862, 865, 860, 870, 869, 857, 868, 854, 855, 856, 867, 861, 850, 849, 859, 858, 852, 853, 851, 848, 847, 846, 840, 841, 837, 845, 844, 843, 842, 833, 834, 830, 839, 831, 838, 835, 836, 829, 832, 828, 827, 820, 819, 818, 817, 815, 826, 816, 825, 824, 822, 823, 810, 821, 809, 814, 813, 812, 811, 808, 807, 804, 800, 799, 798, 796, 797, 794, 795, 793, 791, 806, 789, 788, 787, 805, 784, 803, 802, 801, 781, 782, 779, 792, 790, 786, 773, 765, 785, 772, 770, 771, 775, 769, 768, 774, 766, 911, 909, 910, 906, 780, 777, 776, 757, 755, 759, 763, 752, 753, 751, 783, 767, 762, 761, 778, 760, 758, 764, 754, 750, 749, 756, 745, 744, 738, 748, 743, 746, 740, 741, 742, 739, 730, 737, 747, 725, 734, 733, 736, 735, 732, 731, 728, 726, 727, 729, 724, 722, 723, 713, 719, 720, 709, 721, 717, 718, 715, 714, 716, 712, 702, 711, 700, 708, 707, 710, 706, 705, 704, 703, 699, 701, 698, 695, 697, 696, 694, 693, 691, 690, 689, 692, 687, 688, 685, 686, 683, 682, 684, 672, 681, 678, 679, 680, 676, 675, 674, 673, 671, 668, 677, 669, 670, 667, 666, 664, 663, 665, 662, 661, 656, 660, 659, 657, 658, 654, 655, 652, 653, 650, 651, 649, 648, 647, 646, 644, 645, 643, 642, 641, 640, 638, 639, 637, 635, 636, 633, 634, 632, 631, 630, 628, 629, 627, 625, 626, 624, 623, 622, 621, 619, 620, 618, 617, 616, 614, 615, 613, 603, 611, 612, 609, 608, 607, 605, 606, 610, 602, 604, 601, 600, 599, 1580, 1581, 1582, 1583, 1584, 1585, 1586, 1587, 1588, 1589, 1590, 1591, 1592, 1593, 1594, 1595, 1596, 1597, 1598, 1599, 1600, 1603, 1605, 1601, 1602, 1604, 1606, 1607, 1608, 1609, 1610, 1579, 1611, 1612, 1613, 1615, 1616, 1617, 1618, 1619, 1622, 1621, 1620, 1623, 1624, 1625, 1626, 1627, 1630, 1629, 1631, 1628, 1633, 1634, 1635, 1636, 1638)]
(Background on this error at: http://sqlalche.me/e/e3q8)

Dependencies follow in one Moment.

**Comment by Jedi5000** [comment]
![Part1](https://user-images.githubusercontent.com/65608434/82353115-4580ca80-99ff-11ea-8c24-241497cff6c4.JPG)
![Part 2](https://user-images.githubusercontent.com/65608434/82353127-49ace800-99ff-11ea-9846-9b36e8600fb1.JPG)

**Comment by Jedi5000** [comment]
Nothing special. It's just on a Microserver, that is also used as Picture storage, but no other Sql Database or any SQL alikes installed.

Also noithing Special in Installation.
Installed Python. 
executed pip install --target vendor -r requirements.txt
Server was up and Running, Calibre DB connected.

Worked for Months withoutr any issue...Problem occured after I hit 1000 Books :)

Thanks in Advance :)

**Comment by OzzieIsaacs** [comment]
Okay I think I got it.The problem occurs not with 1000books in database, but with more than 1000 books in database, this really creates a query the more than 1000 parameters

**Comment by OzzieIsaacs** [comment]
might be ugly to fix, I try my best

**Comment by Jedi5000** [comment]
Wow found a bug :-)

Anyways thanks for your quick answer! 
Hope you're able to fix it :-)

**Comment by Jedi5000** [comment]
Thanks for your effort.
Changed the 2 files.
But now it throws 

Traceback (most recent call last):
File "cps.py", line 36, in <module>
from cps.opds import opds
File "D:\BooksServer\calibre-web-master\cps\opds.py", line 34, in <module>
from .helper import fill_indexpage, get_download_link, get_book_cover, speaking_language
File "D:\BooksServer\calibre-web-master\cps\helper.py", line 6
<!DOCTYPE html>
^
SyntaxError: invalid syntax


upon Starting, so its not even starting up.

**Comment by OzzieIsaacs** [comment]
Yes definitely. 
I pushed it to the development branch, there are dozens of changes pending, so just replacing the 2 files and having the programm running again would be like a miracle.
Before I'm pushing it to the master branch I need to do some tests and also fix the other (bigger) half of the problem to get it working without linked custom-calibre column. This is a bigger change because there I have to do a sql query across 2 databases, which is currently not possible in the code.

**Comment by Jedi5000** [comment]
Ah ok my Error, sorry. 
Thought that'll do the Trick ;)

**Comment by OzzieIsaacs** [comment]
Now I'm ready. It's fixed in current master. Please try.

**Comment by Jedi5000** [comment]
Wuhuu!

yOu're the best! It works!
Thank you!
