### ISSUE TITLE
How to convert ebooks

### ISSUE THREAD

**Issue by Dinth** [janeczku/calibre-web#1408]
**Describe the bug/problem**
Im struggling to find an option to convert ebooks. Its not being shown the book page (i cannot download any other format than the one in the library.
![Screenshot from 2020-05-19 16-19-49](https://user-images.githubusercontent.com/313674/82344973-9affac00-99ec-11ea-89a4-1f556398dc80.png)
But according to About page, ebook converter is installed correctly:
![Screenshot from 2020-05-19 16-21-02](https://user-images.githubusercontent.com/313674/82345264-f92c8f00-99ec-11ea-81ae-c8f673f1bb36.png)

**Environment (please complete the following information):**
 - Calibre-Web version [e.g. 0.6.5 or master@16.02.20, 19:55 ]: 0.6.7 - 0735fb1e929fd673397acdd7e2c1c8be0d510d3f - 2020-05-05T20:28:10+02:00
 - Docker container [ None/Technosoft2000/Linuxuser]:Linuxserver

**Comment by Braincoke** [comment]
If you click on `Edit Metadata` you should see the form to convert the book under the book cover.
I never tested it myself though...

![image](https://user-images.githubusercontent.com/8492812/82350649-ed949480-99fb-11ea-91d9-2808571e8922.png)

**Comment by Dinth** [comment]
ah great, thank you!
