### ISSUE TITLE
Search bar grabbing focus is problem on mobile/tablet devices

### ISSUE THREAD

**Issue by Knepherbird** [janeczku/calibre-web#1413]
When a page loads, it appears that the search bar grabs input focus. On desktop browsers, this doesn't seem to be an issue, but on my phone and tablet (using both Chrome and Firefox for Android), this can cause things like password managers or autosuggest menus to activate, and makes using the app painful.

Would it be possible to bypass this function on mobile/tablet devices?

**Comment by OzzieIsaacs** [comment]
I'm going to revert it

**Comment by OzzieIsaacs** [comment]
In the master branch the change should be done
