### ISSUE TITLE
Config: Regular expression for title sorting

### ISSUE THREAD

**Issue by sciurius** [janeczku/calibre-web#1415]
0.6.8beta, From the docs:

> Regular expression for title sorting: Calibre stores internally the title and a "sorted title". Title often starting with articles like "A" in english, or "Die/Der/Das" in german, which make no sense to sort after, therfore all of the listed words in these field are ignored for sorting the title. 

Why not use Calibre "sorted title" instead?

**Comment by OzzieIsaacs** [comment]
What do you exactly mean?

The current string is from a calibre version one or 2 years before. 
I saw, they meanwhile changed the sorting so it's language depended (https://manual.calibre-ebook.com/customize.html#tweaks)

**Comment by sciurius** [comment]
Since Calibre maintains a title and a sorttitle I would use the sorttitle for sorting. This eliminates the need for nifty regexes to ignore articles.

**Comment by OzzieIsaacs** [comment]
Beside the fact that there was indeed a bug in the sorting routine I don't understand what you want me to do:
![grafik](https://user-images.githubusercontent.com/6438895/82587883-3c783080-9b9a-11ea-9f1f-31e7a7402abe.png)
If you select ascending sorted books "The Audiobook" is displayed before "A Book". A from Audiobook is sorted before B from Book.

**Comment by sciurius** [comment]
I'm just thinking out loud...

Calibre has a field _title_ that contains values like (using your example) "The Audiobook" and "A Book".
To get the desired ordering, you use a regex to ignore articles like The and A. Fine.
Calibre also has a field _sorttitle_ that contains values like "Audiobook, The" and "Book, A". Calibre uses a complex regex to derive sorttitle from title.
So why not use _sorttitle_ to determine the ordering, instead of using _title_ and derive sort order yourself?

**Comment by OzzieIsaacs** [comment]
What do you think does this button in calibre:
![grafik](https://user-images.githubusercontent.com/6438895/82747483-68153980-9d99-11ea-9fdb-700f267afdbc.png)
And why do you think you can configure such regexes in Calibre?
![grafik](https://user-images.githubusercontent.com/6438895/82747508-c04c3b80-9d99-11ea-89f1-108bf19a2528.png)
As Calibre-Web uses the database format of calibre there is of course a column sorted title, where the sorted titles are stored. Calibre-Web hasn't visible this column and also not the sorted author column. But I still don't know what this has to do with the automatic title sorting algorithm, so I'm closing the issue.
