### ISSUE TITLE
Total books sum

### ISSUE THREAD

**Issue by rafarq** [janeczku/calibre-web#1426]
**Is your feature request related to a problem? Please describe.**
I add many books each time and i have to login to my raspberry pi and open calibre to know how many books are there in the library.
**Describe the solution you'd like**
A text in any place with the numbers of books, even in the sidebar section a number displaying how many books are there in each section.

**Describe alternatives you've considered**

**Additional context**

**Comment by OzzieIsaacs** [comment]
You can view this in the about section
![grafik](https://user-images.githubusercontent.com/6438895/82754656-a9740c00-9dce-11ea-9b12-25a355540062.png)

**Comment by rafarq** [comment]
Oh, sorry I didn’t see it.

**Comment by OzzieIsaacs** [comment]
No problem
