### ISSUE TITLE
CLI tool/API to configure application settings

### ISSUE THREAD

**Issue by flying-sausages** [janeczku/calibre-web#1427]
**Is your feature request related to a problem? Please describe.**
I would like to add calibre-web to a seedbox installer toolset and I would like to be able to change some of the application configuration values as part of the configuration.

**Describe the solution you'd like**
It would be nice if there were some sort of CLI tool or an API which would allow me to change these without having to go through the `app.db` directly through the sqlite

**Describe alternatives you've considered**
I was thinking of making the SQL calls, however that is not exactly reliable as this could go out of sync with the schemas etc. over time.

**Additional context**
I essentially need to change the user's password, and configure the application's web port and base url. Additionally, changing the settings for converting tool path would be sweet too

**Comment by philipsd6** [comment]
I think it's even more important for user management -- We need to have a way to mass edit/import/delete users, instead of having to do it one by one.
