### ISSUE TITLE
CBZ files do not have a convert option available

### ISSUE THREAD

**Issue by flying-sausages** [janeczku/calibre-web#1428]
**Describe the bug/problem**
When editing metadata for CBZ files, the converting function is not available

**To Reproduce**
1. Add CBZ file to library
2. Go to file's metadata field
3. Find a lack of converting options

**Logfile**
N/A

**Expected behavior**
Being able to use the Calibre converter to create ePub/PDF etc. versions of the file

**Screenshots**
![image](https://user-images.githubusercontent.com/23618693/82755778-c9570000-9dcd-11ea-8a31-75571345b621.png)

![image](https://user-images.githubusercontent.com/23618693/82755794-df64c080-9dcd-11ea-92f6-3304ceb70184.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python version: Python 3.8.2
 - Calibre-Web version 0.6.8:
 - Docker container [ None/Technosoft2000/Linuxuser]: None
 - Browser [e.g. chrome, safari] : Firefox ESR 68

**Additional context**
While the "ebook converter" is shown as "not installed", the option is available for epub and mobi and probably most other formats
![image](https://user-images.githubusercontent.com/23618693/82755833-2357c580-9dce-11ea-9865-570ede057bb5.png)

**Comment by flying-sausages** [comment]
Fixed the path of "ebook converter" to the calibre one and tested succesful conversion, but the issue still persists

**Comment by OzzieIsaacs** [comment]
From my knowledge the calibre-converter only supports a limited subset of converting files to another format. 
I think all the comic file formats (like .cbz, .cbr, .cbt) are not supported formats as source or destination format

**Comment by flying-sausages** [comment]
I got succesful, nice and quite optimal converts with `ebook-convert` just now. Just need to pass a couple flags to the converter

**Comment by flying-sausages** [comment]
i.e. https://gist.github.com/flying-sausages/867021e2ee1ee5aa31d8356a3dbc90f9

**Comment by OzzieIsaacs** [comment]
You are right, the algorithm for showing the conversion options has to be more sophisticated. Currently it is "one" list for all source and destination format. But Calibre can convert ''from'' more formats than **to** formats.

**Comment by flying-sausages** [comment]
I would think the easiest way would be to have the database store settings like these
```
Rule NR | FROM format   | TO format     | Flags to add               |            
------------------------------------------------------------------
1       | CBZ,CBR,CB7   | ePub          | --landscape --no-default-epub-cover --no-process --output-profile=tablet
------------------------------------------------------------------
2       | CBZ           | ePub          | --something else
```
And give the user some UI to fill this in.

Maybe make two checklists for FROM and TO, and if there are multiple rows which would match, only use the last one. You can also show in the tasks the number/ID of the rule that was applied to make troubleshooting easier.

**Comment by OzzieIsaacs** [comment]
Is meanwhile fixed
