### ISSUE TITLE
Stars difficult to see

### ISSUE THREAD

**Issue by rafarq** [janeczku/calibre-web#1430]
**Is your feature request related to a problem? Please describe.**
I don’t know if it is because I have daltonism but in the default light theme I cannot differentiate which stars are on and which are off so I cannot know the book rating. 
**Describe the solution you'd like**
Could you please change the on stars color to one that could be differentiated better?

**Describe alternatives you've considered**
Maybe adding a text like 3,5/5 next to the starts would be nice too.

**Comment by OzzieIsaacs** [comment]
On which screen are you referring?
Edit books:
![grafik](https://user-images.githubusercontent.com/6438895/82833251-cb988780-9ebd-11ea-8369-6257b737ed8f.png)
Ratings list:
![grafik](https://user-images.githubusercontent.com/6438895/82833279-de12c100-9ebd-11ea-8720-74ee58e71862.png)
Advanced search:
![grafik](https://user-images.githubusercontent.com/6438895/82833322-f84c9f00-9ebd-11ea-8bb5-0f55b4f17ed2.png)

**Comment by rafarq** [comment]
On rating lists and best rated books. ![image](https://user-images.githubusercontent.com/3762929/82910757-4bc8f680-9f6b-11ea-9c41-06f78c791b93.jpeg)

**Comment by OzzieIsaacs** [comment]
On best rated books, only books with 5 stars are displayed, so it's right to see all stars "full".
In the ratings section, the no. of stars per book is clearly visible:
![grafik](https://user-images.githubusercontent.com/6438895/83056899-72179080-a056-11ea-8811-e815673f4492.png)
![grafik](https://user-images.githubusercontent.com/6438895/83056922-7c398f00-a056-11ea-9e9e-109e9c477def.png)

**Comment by rafarq** [comment]
If it were clearly to see I wouldn’t write this message. I cannot see which one are on and off. If you don’t want to change that I will dig into the css to see the way of changing it for me. But I thing that there should be a middle way for this.

**Comment by OzzieIsaacs** [comment]
Sorry now I got it. 
I didn't read your first post right, and missed the part about your disease

**Comment by OzzieIsaacs** [comment]
Would this be better:
Option 1:
![image](https://user-images.githubusercontent.com/6438895/83164815-f3c9f580-a10c-11ea-9597-f3daae80c91b.png)
Option 2:
![image](https://user-images.githubusercontent.com/6438895/83165019-3f7c9f00-a10d-11ea-96d5-ee6a0a89cf5e.png)

**Comment by rafarq** [comment]
Don’t worry. I thought something was missing in our conversation. 😉 

All two options al good. So you can choose the best for the theme design. 

Thanks a lot.

**Comment by OzzieIsaacs** [comment]
I changed it in the newest commit version
