### ISSUE TITLE
Calibre Database location not working

### ISSUE THREAD

**Issue by closerp** [janeczku/calibre-web#1431]
**Describe the bug/problem**
A clear and concise description of what the bug is. If you are asking for support, please check our [Wiki](https://github.com/janeczku/calibre-web/wiki) if your question is already answered there.

**To Reproduce**

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10/raspian]
 - Python version [e.g. python2.7]
 - Calibre-Web version [e.g. 0.6.5 or master@16.02.20, 19:55 ]:
 - Docker container [ None/Technosoft2000/Linuxuser]:
 - Special Hardware [e.g. Rasperry Pi Zero]

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy]

# COMMENT
what I use for creat one stack in portainer in docker on openmediavault
##
---
version: "2.1"
services:
  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=998
      - PGID=100
      - TZ=Europe/Lisbon
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - /srv/dev-disk-by-label-Files/Config/Calibre:/config
      - /srv/dev-disk-by-label-Files/Calibre:/books
    ports:
      - 8083:8083
    restart: unless-stopped
##
then i create a "metadata.db" file in file explorer in the calibre:books directory
I enter in calibre-web \books and select next and the service give error

**Comment by closerp** [comment]
-I'm runing the openmediavault in a raspberry pi 4 with latest raspbian lite 
-browser: google chrome in windows 10 for acessing everything
-in portainer i encounter this info inside the image "linuxserver/calibre-web:latest" : Linuxserver.io version:- 0.6.7-ls63

**Comment by OzzieIsaacs** [comment]
> then i create a "metadata.db" file in file explorer in the calibre:books directory
This is not what is needed, you need a calibre database file, even with only one book (the default one, which is created from the calibre program). You could try this file:
https://github.com/kovidgoyal/calibre/blob/master/src/calibre/db/tests/metadata.db
If this solves not your problem, please fill out the form, not just copy it. I can not help you anymore with the information you provided
Thanks
