### ISSUE TITLE
Troubleshooting Help: Why might a book cover be missing on Calibre-Web but present in the desktop version of Calibre?

### ISSUE THREAD

**Issue by SquareBottle** [janeczku/calibre-web#1442]
I imported several EPUB books into Calibre and individually updated the metadata. For some reason, one of the books appears in the gallery with a big "Cover not available" image instead of the cover. It's especially perplexing because this book happened to be part one of a three part series, and the others parts display just fine.

I've already tried switching to a different cover, manually reconnecting to the DB, and restarting the server. I'm just baffled now. Any ideas?

**Comment by OzzieIsaacs** [comment]
Good question.
Please check if the cover file is really present in the folder, where it is supposed to be
There is an issue regarding the browser cache. Please reload the calibre-web page to refresh the cache (opening calibre-web in an private tab would be also a good idea to overcome this issue)
For more help I need the information from the form you deleted (maybe)

**Comment by SquareBottle** [comment]
I didn't delete anything, actually. There were two options for pre-made forms, and one option to use when the other two didn't fit.

I didn't pick the bug option because I don't know the steps to recreate the issue, which is what that form seemed to be all about. I don't know how to recreate the issue because I don't know what caused the issue. Since I have no idea what the issue is, I don't feel like I can confidently say that it's a bug at all. It might be a bug, it might be me. 

I didn't pick the feature request option because, well, it's _especially_ clear that this isn't a feature request. 

So, I picked the "Neither of these sound right?" option, which was blank.

After restarting everything a few more times and even setting everything back up from scratch again with a new docker image, I eventually just gave up and stepped away. Want to know what the cherry on top is? _The missing cover is now there!_ I'm even more baffled than before, somehow.

The cover image was/is definitely in the folder. Keep in mind, it was showing up fine on the Calibre desktop app the whole time. I even tried replacing the cover.

Since I have absolutely no idea how to reproduce the problem, all I can do is wait and see if it happens again. If it doesn't, then great! Thanks for reading.

If it does happen again, then I'll come back with system info, logs, and whatever else you want. Until then, take care.

**Comment by palmfighter** [comment]
Just fyi.. I had similar issue, found out that by changing the calibre library name, the folder also changes... so the folder that Calibre-Web is using needs to be updated.. 

Anyhow that was my problem on cover not found ;) fixed it..

**Comment by mimavox** [comment]
I had the same problem. A simple restart fixed it for me (Calibre-Web Settings -> Restart)

**Comment by ewok2** [comment]
Hello
Same problem... some works other with "Cover not available"

I try "Calibre-Web Settings -> Restart" and does not works
In the folder containing the cbr file there is a cover.jpg...

And the cover is displayed in the calibre app launch from a MacBook
=> The calibre-web is run on a Ubuntu VM aside the calibre server

Any idea to corect the wrong book ?

**Comment by OzzieIsaacs** [comment]
Permission problem?

**Comment by ewok2** [comment]
Bingo !
It was that.
Thanks

**Comment by ewok2** [comment]
Strange behavior (not of calibre web but on calibre app or on calivre server)
Whan I add a book from the Calibre application it creat the book on the server but with user/group not set to calibre:calibre but to myuser:mygroup ....
So of course all new books are not readable by calibre server...
=> A chown on server side seem's to be needed after adding newbook

**Comment by dkupl** [comment]
Hi,

On Mac (docker compose) in "Database Configuration"  set the same path in the fields: 
* Location of Calibre Database
* (checked) Separate Book Files from Library

**Comment by gabahulk** [comment]
> Hi,
> 
> On Mac (docker compose) in "Database Configuration" set the same path in the fields:
> 
> * Location of Calibre Database
> * (checked) Separate Book Files from Library

This was also the problem for Windows
