### ISSUE TITLE
Rewrite error behind cascaded reverse proxy

### ISSUE THREAD

**Issue by Arkhee** [janeczku/calibre-web#1444]
Hi,
I have (I think) an URL rewrite problem when using apache reverse proxy.
When I access my web it is rewritten to : 
_http://books.mydomain.com%2C%20books.mydomain.com/login?next=%2F_

My Calibre-web UI is working fine with : http://localhost:8083
Standard calibre web ui is also ok on http://localhost:8080
I'm trying to set a reverse proxy with apache on : 
http://book.mydomain.com/

When I go manually to this url :
http://book.mydomain.com/login?next=%2F_
Then login works, I can browse database, but not read a book.
I tried both stable and nightly version of calibre-web
Same issue on all browsers

Virtualhost is quite basic and works fine with the standard calibre web UI : 
```
<VirtualHost  192.168.0.1:80>
    ServerName book.mydomain.com
    ProxyPreserveHost On
    ProxyPass / http://192.168.0.1:8083/
    ProxyPassReverse / http://192.168.0.1:8083/
</VirtualHost>
```

Thanks for your help

**Comment by OzzieIsaacs** [comment]
I double checked it with the config you gave me, it's working without any problem. I checke localhost, my local IP address and I edited the hosts file to point to the "book.mydomain.com" url. I check with another computer in my private network, also without any problem. The url you are redirected to is:
`books.mydomain.com, books.mydomain.com`
which looks very suspicious to me. Comma and following space looks like something some human entered in some list, are your really sure you are not having any config error?
I'm not sure if I know, what you do exactly:
You open your browser and enter : http://books.mydomain.com, this redirects you to http://books.mydomain.com%2C%20books.mydomain.com/login?next=%2F?
If you enter http://book.mydomain.com/login?next=%2F_, then there is no redirection?

**Comment by Arkhee** [comment]
Hi, your answer gave me a hint. Actually le calibre server is behind two reverse proxies : one located on a dedicated server on the internet, the other is my local server on LAN. 
First server dispatches requests on several servers according to the requested URL, and local reverse proxy does the job for the port (proxying 8083 behind 80/443)
Looking at a phpinfo() page I noticed the server variable : 
$_SERVER['HTTP_X_FORWARDED_HOST'] is "books.mydomain.com, books.mydomain.com"
This is exactly the url (though not urlencoded)

You're right about the reverse proxy working though, when I set manually the ip of the domain (via hosts file) to point on the LAN server, it works.

I'll try to fix this by overriding the HTTP_X_FORWARDED_HOST value in the virtualhost, although I think you might want to use another variable (ex. in PHP the $_SERVER['HTTP_HOST']), which does not contain a list of concatenated domains.

**Comment by OzzieIsaacs** [comment]
You are the first having this problem. 
I change the title to "Rewrite error behind cascaded reverse proxy"
The reverse proxy code is from the example pages from flask (the framework Calibre-Web is using), so I trusted it.
I take a look  at it, but with low priority

**Comment by Arkhee** [comment]
I bet calibre servers behind a double reverse proxy can be counted with one hand :->
Well I fixed my problem by unsetting the value : 
`RequestHeader unset X-FORWARDED-HOST`
There should be an equivalent command for nginx/iis I suppose
Thanks for the hint ! And the time
