### ISSUE TITLE
Allow the possibility to specify and access multiple databases / libraries

### ISSUE THREAD

**Issue by Arkhee** [janeczku/calibre-web#1445]
Hi,
I have not found any info in the wiki about this subject, but it seems to me it's not covered
When starting calibre-server in command line/service, it is possible to provide several path to different databases.
For instance :
`/usr/bin/calibre-server "/home/calibre/publicdatabase1"  "/home/calibre/privatedatabase2" --enable-local-write --enable-auth  --userdb /home/calibre/userdb.sqlite`
The standard calibre web ui allows us to chose which one to browse, and also access rights can be granted to one library or the other on a per user basis.

On the other hand, calibre-web seems to allow only one database.
Is it exact ? If so would it be possible to allow several databases + access rights, in the same way that calibre-server does ?

By extension, using the calibre-server user database in calibre-web would be quite convenient too.
Thanks in advance

**Comment by jerrac** [comment]
I have about 13 different libraries to help keep things organized. So being able to add more libraries to calibre-web would be extremely helpful. I really really like what I've seen of the interface so far. 

What would it take to support multiple libraries?

**Comment by OzzieIsaacs** [comment]
Short answer: Much work.
The UI had to be changed completly, as soon as I start offering it (I guess you can imagine what has to be configured).
Several use cases will pop up, like:
I'd like to search in only one database at a time
I'd like to search in all databases at a time
Some of my databases are on remote storages, which aren't available all the time.

Calibre-Web has some settings which are depending on the calibre database, but not stored in it itself, like reading status, read progress for kobo devices, shelfs and downloaded books. 

Supporting more than one database at a time would mean every routine for displaying and handling the books has to be extended and rewritten.

**Comment by OzzieIsaacs** [comment]
My solution is documented here:
https://github.com/janeczku/calibre-web/wiki/FAQ#how-to-handle-multiple-calibre-libs

**Comment by Arkhee** [comment]
I ended up doing this as well, creating an instance for each calibre database, which is not so troublesome since I have only two of them.

However if I want to go through with the idea, in that case being able to as a custom "library" link somewhere on the left column would be logical and convenient to navigate through instances.

Also since one of the main reason one would need separate libraries is for user right managements, maybe adding access rights, or more simply a private/public property attribute (like for the shelves) to these links would probable enough.
