### ISSUE TITLE
Error work with SSL

### ISSUE THREAD

**Issue by atrezonator** [janeczku/calibre-web#1446]
**To Reproduce**
1. Generated an SSL file through Apache
1. Go to setting
2. added a key and certificate
3. when saving and loading the server see error

**Environment (please complete the following information):**
 - OS: CentOS 8
 - Python version [e.g. python3.6]
 - Calibre-Web version [e.g. 0.6.8 beta ]:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib64/python3.6/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/lib64/python3.6/site-packages/gevent/server.py", line 174, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "/usr/lib64/python3.6/site-packages/gevent/_ssl3.py", line 642, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib64/python3.6/site-packages/gevent/_ssl3.py", line 161, in __init__
    self._context.load_cert_chain(certfile, keyfile)
ssl.SSLError: [SSL] PEM lib (_ssl.c:3542)
Thu May 28 16:44:52 2020 <Greenlet at 0x7f25921125a0: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed]  object, fd=-1, )> failed with SSLError
```

**Comment by OzzieIsaacs** [comment]
Assuming python3.6(?), the code fails on a line saying something about password (https://github.com/python/cpython/blob/3.6/Modules/_ssl.c )
Is your private key password protected? Calibre-Web isn't supporting it.

**Comment by atrezonator** [comment]
here is my certificate.
created with this command:
`sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/apache2/ssl/apache.key -out /etc/apache2/ssl/apache.crt`
[ssl.zip](https://github.com/janeczku/calibre-web/files/4699828/ssl.zip)

**Comment by OzzieIsaacs** [comment]
Thanks, I'll check it

**Comment by OzzieIsaacs** [comment]
From the first impression it looks good

**Comment by OzzieIsaacs** [comment]
One question: Are you using some sort of docker container?

**Comment by atrezonator** [comment]
I am start python cps.py on system, not on docker

**Comment by atrezonator** [comment]
> I am start python cps.py on system, not on docker/ 
virtual machine with one this server

**Comment by OzzieIsaacs** [comment]
I tried the files you gave me, no problem:
![grafik](https://user-images.githubusercontent.com/6438895/83332919-340cad80-a29e-11ea-99a8-f0b80a52f2fb.png)
![grafik](https://user-images.githubusercontent.com/6438895/83332932-4edf2200-a29e-11ea-8edc-db59c0a8cfed.png)
