### ISSUE TITLE
Additional description for a shelf

### ISSUE THREAD

**Issue by gorgobacka** [janeczku/calibre-web#1451]
**Is your feature request related to a problem? Please describe.**
I would like to see the functionality to add some description to a shelf to describe the purpose of a specific shelf. At the moment, there is only to shelf item. But often, I would like to add more information to it.

**Describe the solution you'd like**
An editable text between the title of the shelf and it's content.

**Comment by decentral1se** [comment]
Yes, this would be incredibly useful :heart:
