### ISSUE TITLE
How to completely remove calibre web?

### ISSUE THREAD

**Issue by Seruschl** [janeczku/calibre-web#1452]
hi i was trying to use calibre web but i am not able to get into the interface. After the installation i've set up the location of the database and from there it is asking for an login an password. I haven't configured one and i couldn't find an standard credential so i want to completely remove everything and start from the beginning again.

hope someone can help

**Comment by OzzieIsaacs** [comment]
The readme states the initial login Information: https://github.com/janeczku/calibre-web#quick-start

**Comment by Seruschl** [comment]
omg. . . .how was i not able to see this -.-' 

thanks for that
