### ISSUE TITLE
Disallow search engines

### ISSUE THREAD

**Issue by aleksandar-todorovic** [janeczku/calibre-web#1456]
**Is your feature request related to a problem? Please describe.**

My Calibre instance is indexed by search engines, which goes beyond the "share with a group of friends" philosophy.

**Describe the solution you'd like**

Basic `robots.txt` support with `Disallow: /`, perhaps as an admin preference that can be toggled on or off.

**Describe alternatives you've considered**

Maybe it would work if I simply add the `robots.txt` in `cps/static`, maybe I'd need to create another directory and tell my web server to look into that directory when bots look into `robots.txt`. I'd say both of these cases are somewhat non-optimal.

**Additional context**

The only issue in which I've seen this being referenced is #831, but that one covers way more than `robots.txt`. @OzzieIsaacs closed it while addressing only the analytics feature request, so I found no comments made by the team about `robots.txt` support.

**Comment by OzzieIsaacs** [comment]
In general the robots.txt would be okay for me, I'm against some sort of indexing and stuff, as I think this is the starting point for calibre-web getting used for some illegal book sharing platforms, which I try to avoid.
Placing the file in the static folder would not work, as it would be delivered with the route .../static/robots.txt. 
I can create a route in calibre-web which points to "/robots.txt" and if it's called I can deliver a file robots.txt from the static folder. 
During update I can exclude the file, so once created it will be there for all the time and can be used, or not. 
If somebody calls the route and the file isn't there, an error "404 not found" will be shown.

Would this be fine for you?

**Comment by aleksandar-todorovic** [comment]
Yup, that sounds perfect! Especially this part, since it will make it persistent even across updates:

> I can create a route in calibre-web which points to "/robots.txt" and if it's called I can deliver a file robots.txt from the static folder.
