### ISSUE TITLE
Error after update to 0.70

### ISSUE THREAD

**Issue by Andei** [janeczku/calibre-web#1457]
**Describe the bug/problem**
After the last update, server stops and no restart

**To Reproduce**
Update via Calibre-web update button

**Logfile**
File "/calibre-web/app/cps.py", line 43, in from cps.editbooks import editbook
File "/calibre-web/app/cps/editbooks.py", line 456 saved_filename, *os.path.splitext(requested_file.filename), config.config_rarfile_location)
SyntaxError: only named arguments may follow *expression

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: Synology NAS with Docker and technosoft2000
 - Calibre-Web version: 0.68 (I think)

**Additional context**
Same issue as in [#1355](https://github.com/janeczku/calibre-web/issues/1355)
Any instructions for a noob to fix it like the guys in post
[#624609486](https://github.com/janeczku/calibre-web/issues/1355#issuecomment-624609486)
[#624778145](https://github.com/janeczku/calibre-web/issues/1355#issuecomment-624778145)

I would like to have v0.70 ;)

Thx in advance

**Comment by OzzieIsaacs** [comment]
I created a new release, 0.6.8 the problem should be fixed there. (After technosoft2000 has updated the container and you updated it)
