### ISSUE TITLE
Kobo Issue - Downloading books

### ISSUE THREAD

**Issue by JackED42** [janeczku/calibre-web#146]
Hi, 

If you try and download books with the built in browser on Kobo, you can only download books, if the extension is .epub/.mob etc. It cannot be a link that doesn't end in a file, e.g. book/1/download.

If you want to support kobo, there are 2 ways of fixing this: -

1. Make the download links end in the file name
2. Have a separate download for Kobo, that ends in the file name. 

I don't mind doing a pull request and making the change, but would just like your opinion on which option you think would be best.

**Comment by OzzieIsaacs** [comment]
My prefered solution would be no.1

**Comment by Kennyl** [comment]
The name will be as simple as book_id.file_format
