### ISSUE TITLE
Links to Amazon.de do not work

### ISSUE THREAD

**Issue by Schmidtze2** [janeczku/calibre-web#1461]
Hi,

the Links to Amazon.de do not work, the always point to the same location where calibre-web is installed on. I'm using calibre-web for maybe 1 year now, and it didn't ever work. Is it maybe because of the German link address? In metadata.opf I see something like this:

  `<dc:identifier opf:scheme="AMAZON_DE">3864904692</dc:identifier>`

I'm using the current version (29.05.20, 07:11) on a synology NAS.

Best regards
Friedemann

**Comment by OzzieIsaacs** [comment]
Calibre-web isn't using the metadata.opf file. 
The recognized identifiers are:
"amazon", "asin", "isbn", "doi", "goodreads", "google", "kobo", "lubimyczytac", "douban", "url"

Extending it by the different amazon country sides, looks like a reasonable request

**Comment by Schmidtze2** [comment]
Ah, I understand! Doing this

  `select type, count(id) from identifiers group by type order by type`

results in

```
amazon        81
amazon.de      1
amazon_de   2267
barnesnoble   16
bol_de         1
edelweiss      5
ff            13
goodreads     41
google      1322
guid           1
isbn        2287
isbn (print)   1
isbn e-book    1
mobi-asin    206
sonybookid     3
url            1

```

So for me and generally "amazon_*" seems to be the candidate to look at...

Many thanks and best regards
Friedemann

**Comment by Schmidtze2** [comment]
Oops, replacing "amazon_de" with "amazon" in the table "identifiers" does the job already! :-)

**Comment by OzzieIsaacs** [comment]
Yes that's right, but then it's indeed pointing to amazon.com instead of amazon.de, what it was before.

**Comment by Schmidtze2** [comment]
> Yes that's right, but then it's indeed pointing to amazon.com instead of amazon.de, what it was before.

Yes, that's right, but all information about the book seems to be there. Of course I didn't try all books now. Maybe it's available for books only which can be ordered from amazon.com... But maybe a solution is not so difficult, I guess that the extension ".com" has to be replaced simply by the extension after "_"...

**Comment by OzzieIsaacs** [comment]
Yes, that's what I thought on how to implement it

**Comment by Schmidtze2** [comment]
Unfortunately it doesn't work for me. For example the link https://www.amazon.de/dp/B0765ZYP13 will be substituded to https://www.amazon.de/B0765ZYP13, without the "dp", which leads to a not-found page...

Best regads
Friedemann

**Comment by OzzieIsaacs** [comment]
You've been right, I changed the link. It was not correct before
