### ISSUE TITLE
Auto index of manually uploaded PDF files in /books folder

### ISSUE THREAD

**Issue by dvlpmt** [janeczku/calibre-web#1464]
Hello,

Just wondering if Calibre Web supports auto index of files that was manually uploaded in data folder or files has to be uploaded trough interface directly?

Thanks

**Comment by OzzieIsaacs** [comment]
The files have to be uploaded via the interface. There is no automatic to scan folders for new files. To add books from a folder, you could take a look at the script using calibre itself, as described her: https://github.com/janeczku/calibre-web/wiki/FAQ#mass-add-books
