### ISSUE TITLE
Question: what is unrar used for?

### ISSUE THREAD

**Issue by aserrallerios** [janeczku/calibre-web#1468]
The updated README mentions unrar, but I cannot find any specific setting (like ebook-convert) in calibre-web UI nor any documentation about features requiring unrar.

**Comment by CHBMB** [comment]
I might be wrong as I'm not a comic book reader, but I believe it's used by `.cbr` files

https://github.com/janeczku/calibre-web/issues/1333

**Comment by OzzieIsaacs** [comment]
Unrar is needed for extracting metadata (e.g. coverfiles) from .cbr files. The options regarding unrar are only visible if you install some of the optional-requirements (rarfile). Otherwise you can just ignore it.

**Comment by OzzieIsaacs** [comment]
@CHBMB you are right, but the comic reader itself is working without unrar (the problem why rar5 files are not working in the reader)

**Comment by aserrallerios** [comment]
How can we successfully use the optional-requirements.txt? (and thus rarfile) Differences between installing it and not doing it?

Context: I've created a Freenas community Plugin for Calibre-Web and I want to configure it so it has all possible runtime dependencies available (ebook-convert, unrar?, ...).

**Comment by OzzieIsaacs** [comment]
If you open optional-requirements.txt each headline of a block explains what the dependencies are for. Furthermore a view to the wiki can give some impressions on what the software can do and what is needed to use it (https://github.com/janeczku/calibre-web/wiki)
