### ISSUE TITLE
Commercial Services ?

### ISSUE THREAD

**Issue by berserkwarwolf** [janeczku/calibre-web#1469]
Hi, I am in the process of researching software that would help my company launch a book shop + library for our users. And I wanted to ask you if calibre-web would be a suitable library for this purpose.

If it's possible, I would like to talk in private about the possibility of hiring you to install and maintain an instance, or train someone to do it.

**Comment by OzzieIsaacs** [comment]
Calibre-Web has not really shop functions (like book price tags, billing and so on) and I don' want to extend Calibre-Web in this direction (https://github.com/janeczku/calibre-web/blob/master/CONTRIBUTING.md#feature-request).
Thank you for offering the "job". Calibre-Web is my hobby and I'd like to leave it this way. Maybe someone else is interested here, it would be no problem for me.

**Comment by berserkwarwolf** [comment]
@OzzieIsaacs I'm sorry if I wasn't clear. I don't want to extend any functionality. I want people to buy ebooks on my ecommerce site, and then give them access to those ebooks in a calibre-web server.

So, my users would buy on one site, and consume them on another site.

My original question was aimed at things like:
How many users can a calibre-web server handle at the same time reading an ebook ?
Is there an API to create, modify, delete users ?
Is there an API to assign or revoke access to ebooks ?

**Comment by OzzieIsaacs** [comment]
Regarding the performace I haven‘t done any benchmarking tests. My personal instance is only used by very little no. Of users. The reader only downloads the book once, and than everything is happening on the reading device itself.
There is no api for user handling, and also no api for ‚one-time‘ access of books. Limiting access to books can be done by tagging books, but I think it‘s not made for a usecase like you describe it (yours sounds more like deny all, allow is exception. Currently it‘s more like allow all, deny is exception)

**Comment by berserkwarwolf** [comment]
I understand, thanks for clarifying that. Is there a any public demo site that I can test ? If it could suit our needs, would you be interested in developing the required functionality to work as deny all, allow is exception, sponsored by us ?

**Comment by OzzieIsaacs** [comment]
I'm sorry, there is no public demo page I know of.
Thank you for offering the "job". Calibre-Web is my hobby and I'd like to leave it this way.

**Comment by berserkwarwolf** [comment]
I understand, thank you very much for your response anyways.
