### ISSUE TITLE
SMTP and GMAIL Error

### ISSUE THREAD

**Issue by ryryonline** [janeczku/calibre-web#147]
When I enter in GMAIL settings for SMTP, I get this error:
Failed to send mail: {u'': (555, '5.5.2 Syntax error

The rest of the string is a random error that changes each time. It looks like the header of the email isn't set correctly when doing a test.

**Comment by Kennyl** [comment]
Need set send_to_kindle email first

**Comment by OzzieIsaacs** [comment]
Thanks @ryryonline .It'S fixed now
