### ISSUE TITLE
Separate config folder from log folder

### ISSUE THREAD

**Issue by aserrallerios** [janeczku/calibre-web#1471]
Context: I want to set a custom folder for `app.db`, `gdrive.db` and `client_secrets.json`, so this files can be easily customized by the end user.

Looking at the code, it looks like the only way to achieve this is using the `CALIBRE_DBPATH` env variable.

Problem? I want the .log file to be in a different folder (I don't want to mix config with runtime outputs).

Are my assumptions right? Is there any workaround for this?

**Comment by OzzieIsaacs** [comment]
https://github.com/janeczku/calibre-web/wiki/Command-Line-Interface#command-line-options, 
The logfile location can be set from the ui. A app.db with preset configuration could be a solution for you

**Comment by aserrallerios** [comment]
If the folder can be changed at runtime, I can just setup the `CALIBRE_DBPATH` and tell the user to change the logfile settings...

Just to explore all possibilities, is there any available guide to create a preset app.db?

**Comment by OzzieIsaacs** [comment]
You could start caliber-web, do the needed settings and then use/copy the created app.db file during installation
