### ISSUE TITLE
google oauth 

### ISSUE THREAD

**Issue by mijairaf** [janeczku/calibre-web#1472]
After a LOT of failures I finally have oauth working with google. The one important missing piece  is to set this environment variable
OAUTHLIB_RELAX_TOKEN_SCOPE=1

Great documentation is provided here  [https://flask-dance.readthedocs.io/en/v0.8.0/quickstarts/google.html](https://flask-dance.readthedocs.io/en/v0.8.0/quickstarts/google.html)

**Comment by OzzieIsaacs** [comment]
I never personally used it before, my guess is you are the first one to try it.

**Comment by acomick** [comment]
Hey mijairaf,

Thanks for detailing some of your findings. I am also trying to get this to work, but am hitting a 500 after I pass my Google credentials. Can you share which file you added your export statement to? Thanks!

**Comment by mijairaf** [comment]
The export needs to be set for the environment that cps.py will run in. It
depends where and how you are starting calibreWeb. If you are running with
docker you will need to add it using  to your docker run or docker compose
file. In linux just enter the export command at the shell prompt or add it
to your startup script.

$ export OAUTHLIB_RELAX_TOKEN_SCOPE=1$ python cps.py


When you setup your oauth credentials at google the uri should be as
follows:
Authorized redirect URI
 should be https://www.yourdomain.com/l*ogin/google/authorized *

If you are using  https://www.yourdomain.com/*login/github/authorized *you
will get a 500 error.

I found both the uri information and the export information here
https://flask-dance.readthedocs.io/en/v0.8.0/quickstarts/google.html.

Good Luck

**Comment by acomick** [comment]
Awesome. Thank you, this really helped, and I am now able to use google oauth after linking an account in my user settings.

I am running on (I know, I know, its where I had compute capacity at the moment) Windows server 2019 running calibreweb as a service using a dedicated service account. If anyone else needs to get this working in a Windows enviroment, heres what I did to make it work

Open up a powershell window (if you use a service account, make sure it is running as the user who executes your CalibeWeb Server process, as this is a user level defined setting)
Enter the following command:
`[Environment]::SetEnvironmentVariable("OAUTHLIB_RELAX_TOKEN_SCOPE","1","User")`
to check that the value was set, run the following:
`Get-ChildItem Env: | select name,value | findstr 'OAUTH'`
You should see something like:
`Get-ChildItem Env: | select name,value | findstr 'OAUTH'`

After this, I restarted my windows service:
```
stop-service calibreweb
start-service calibreweb
```

And tried to log into my account with oauth. I got an error saying no linked oauth accounts. I logged in via username and password, when to my profile, ensured that my configured email and google account email where the same, and clicked link my account to an oauth account. Finally, I logged back out and was able to log in again.

Thanks again for the help, I'll try to document the process under the wiki page when I get a a chance.

**Comment by MeanderingCode** [comment]
Thank you for finding this workaround!

The real issue, however, is that calibre-web is requiring an OAuth scope that has been deprecated by Google and is no longer supported (namely `https://www.googleapis.com/auth/plus.me`).

This scope should be removed from the project.
