### ISSUE TITLE
calibre-web not redirecting to login screen

### ISSUE THREAD

**Issue by stfrbrntyu** [janeczku/calibre-web#1475]
**Describe the bug/problem**
Every time I open Calibre-Web, it looks like this:
![Naamloos](https://user-images.githubusercontent.com/4924023/83997071-dcd1a180-a95d-11ea-80a4-7425323b9e76.png)

To continue I click on any link, which will forward me to the login screen, press login button, and then I can proceed as normal.
It started happening after a hardcoded seed was changed to a random seed. I can't find the pull request.
I am using SSL

**To Reproduce**
Close all browsers and open Calibre-Web in google chrome or Firefox.

**Expected behavior**
When opening either redirect immediately to the login screen -or-
login immediately when the "Remember me" checkbox is enabled on the login screen.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.7.4
 - Calibre-Web version: 0.6.9 Beta - 2020-06-07T15:41:53+02:00
 - Docker container: None
 - Special Hardware [e.g. Rasperry Pi Zero]
 - Browser: Chrome, Firefox, Microsoft Edge (new),

**Comment by OzzieIsaacs** [comment]
I‘m aware of it

**Comment by OzzieIsaacs** [comment]
It's fixed in the newest commit

**Comment by stfrbrntyu** [comment]
thank you!
