### ISSUE TITLE
Need custom subdirectory(base URL) setting function 

### ISSUE THREAD

**Issue by coolwlm** [janeczku/calibre-web#1476]
**Is your feature request related to a problem? Please describe.**
I want to use http(s)://xxx.xxx.xxx/calibre instead of http(s)://xxx.xxx.xxx:port to access the calibre-web server

**Describe the solution you'd like**
base URL setting function like jellyfin

**Describe alternatives you've considered**

**Additional context**

**Comment by OzzieIsaacs** [comment]
Please refer to the Wiki on how to set up a Reverse Proxy configuration for calibre-Web:
https://github.com/janeczku/calibre-web/wiki/Setup-Reverse-Proxy#reverse-proxy

**Comment by coolwlm** [comment]
Thanks for your quick response. Above reference only works on root location / ,  calibre server doesn't support virtual path setting.

**Comment by coolwlm** [comment]
It works fine now.  thanks
