### ISSUE TITLE
[Bug]urllib.quote without encode('utf-8') may cause KeyError

### ISSUE THREAD

**Issue by idalin** [janeczku/calibre-web#148]
`[2017-03-07 03:21:56,239] {/opt/app/vendor/flask/app.py:1587} ERROR - Exception on /read/12345/pdf [GET]
Traceback (most recent call last):
  File "/opt/app/vendor/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/app/vendor/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/app/vendor/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/app/vendor/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/app/vendor/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/app/cps/web.py", line 1240, in read_book
    tmp_file = os.path.join(book_dir, urllib.quote(book.data[0].name)) + ".pdf"
  File "/usr/lib64/python2.7/urllib.py", line 1282, in quote
    return ''.join(map(quoter, s))
KeyError: u'\u53a8'`

https://github.com/janeczku/calibre-web/blob/master/cps/web.py#L1239  and others.

append .encode('utf-8') to book.data[0].name can fix this
`        elif format.lower() == "pdf":
            all_name = str(book_id) + "/" + urllib.quote(book.data[0].name.encode('utf-8')) + ".pdf"
            tmp_file = os.path.join(book_dir, urllib.quote(book.data[0].name.encode('utf-8'))) + ".pdf"
            if not os.path.exists(tmp_file):
                pdf_file = os.path.join(config.config_calibre_dir, book.path, book.data[0].name) + ".pdf"
                copyfile(pdf_file, tmp_file)
            return render_title_template('readpdf.html', pdffile=all_name, title=_(u"Read a Book"))
        elif format.lower() == "txt":
            all_name = str(book_id) + "/" + urllib.quote(book.data[0].name.encode('utf-8')) + ".txt"
            tmp_file = os.path.join(book_dir, urllib.quote(book.data[0].name.encode('utf-8'))) + ".txt"
            if not os.path.exists(all_name):
                txt_file = os.path.join(config.config_calibre_dir, book.path, book.data[0].name) + ".txt"
                copyfile(txt_file, tmp_file)
            return render_title_template('readtxt.html', txtfile=all_name, title=_(u"Read a Book"))
        elif format.lower() == "cbr":
            all_name = str(book_id) + "/" + urllib.quote(book.data[0].name.encode('utf-8')) + ".cbr"
            tmp_file = os.path.join(book_dir, urllib.quote(book.data[0].name.encode('utf-8'))) + ".cbr"`

**Comment by Kennyl** [comment]
need a little bit further change

Change all book.data[0].name to book_id  then no need quote and encode

book.data[0].name and book_id is no different for internal static cache
ie.
static/101/①②③.pdf  (using book.data[0].name) or static/101/123.pdf (using book_id)
