### ISSUE TITLE
Book titles are truncated in details view

### ISSUE THREAD

**Issue by Donatzsky** [janeczku/calibre-web#1482]
When going into Book Details, the title is truncated to ~60 characters. This means that a title such as "Imperial Twilight - The Opium War and the End of China’s Last Golden Age" becomes "Imperial Twilight - The Opium War and the End of China’s Last ...". 

It really should show the full title, though. Unlike the list/cover view, there's no reason to restrict the length.

**Comment by OzzieIsaacs** [comment]
I think at the time I implemented it there was an issue on my IPad with very long titles
