### ISSUE TITLE
Allow Send To Kindle, but not Download

### ISSUE THREAD

**Issue by rodskogj** [janeczku/calibre-web#1485]
**Describe the bug/problem**
'Send to Kindle' function does not work unless a user has 'Allow Downloads' rights

**To Reproduce**

Go to UI Configuration -> Edit User
Uncheck the 'Allow Downloads' option
Save changes
Open a book and press 'Send Mobi to Kindle'
"Error 403 Forbidden" error is shown on screen

**Expected behavior**
Copy of the book should be sent by email to the kindle address

**Screenshots**

**Environment (please complete the following information):**

OS: Windows 10
Python version: 3.8
Calibre-Web version: 0.6.8
Docker container: 
Special Hardware:
Browser: Chrome

**Additional context**
This 'Allow Download' option button should only affect downloading of books, not the email to kindle option. A separate option button could be added to restrict the kindle email, but this seems serplurferous as each user has a separate 'send to kindle' email address that could be blanked out to achieve the same effect

**Comment by flying-sausages** [comment]
What's the use case of someone having send to kindle but no download privileges

**Comment by OzzieIsaacs** [comment]
I will not split up the download/read right into another one. As a user having the right only read bookscan easily download the book and if you are only allowed to send the book to kindle you can send it to any email address and download it from there so this option makes no sense to me
