### ISSUE TITLE
calibre-web as https://example.com/calibre-web not working

### ISSUE THREAD

**Issue by quarz12** [janeczku/calibre-web#1489]
**Describe the bug/problem**
I want to run my calibre-web on the address https://example.com/calibre-web. I understand that I need to use a reverse proxy for that. I am using apache on Raspbian. I already have a nextcloud instance running on example.com/nextcloud using SSL. 
This is my calibre-web.conf for apache:

<VirtualHost *:443>
    SSLEngine on
    SSLProxyEngine on
    SSLCipherSuite ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv2:+EXP:+eNULL
    SSLCertificateFile /etc/letsencrypt/live/example.com/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/example.com/privkey.pem

    <Location /calibre-web >
        RequestHeader set X-SCRIPT-NAME /calibre-web
        RequestHeader set X-SCHEME https
        ProxyPass http://localhost:8083/
        ProxyPassReverse http://localhost:8083/
        ProxyPassReverseCookiePath  /  /calibre-web/
    </Location>
</VirtualHost>

I changed the path of the cert files to the ones certbot already gave me for nextcloud.
now when I reload apache, https://example.com/calibre-web does not exist. 
When I go to http://example.com:8083 I get directed to this:
![image](https://user-images.githubusercontent.com/64491670/84449160-d8063980-ac4c-11ea-83ef-7b444a22ba75.png)
clicking on the link just directs me to the same site.
on localhost:8083 everything works fine.

the log output for this connection is:
INFO {tornado.general:253} Malformed HTTP message from (ipv6 address) no colon in header line

At this point I am clueless where to search for solutions since there isn't a lot about this project on the internet.

**Comment by OzzieIsaacs** [comment]
The 404 error means that you try to access a route which isn't available. The error message gives a hint about  "ipv6 address".
Let's first fix the direct access via 8083 from a different computer and then see what's going on with apache.
Could you please open the developer console (str+shift+k) on German-Firefox, reload the page. In the network analysis page we should see something like:
![grafik](https://user-images.githubusercontent.com/6438895/84522515-0c263c80-acd7-11ea-8836-b32eaf77d69a.png)
On inital config you should see something like /config on the first request (if already configured, it should be same as me).
Could you also please try to access calibre-web via ip-address (http://999.999.999.999:8083) (replace the 9's with your address. IP-V6 should be something like: [fff:fff:fff:fff:fff:fff]:8083.
Could you please also check if calibre-web listens on the right addresses. -> Should be in logfile during startup: 
[2020-06-12 xxxxxx]  INFO {cps.server:156} Starting Tornado server on :8083

**Comment by OzzieIsaacs** [comment]
And I need this information sooner or later:

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10/raspian]
 - Python version [e.g. python2.7]
 - Calibre-Web version: [e.g. 0.6.5 or master@16.02.20, 19:55 ]
 - Docker container: [ None/Technosoft2000/Linuxuser]
 - Special Hardware: [e.g. Rasperry Pi Zero]
 - Browser: [e.g. chrome, safari]

**Comment by quarz12** [comment]
This is the console output for mydomain:8083 
![image](https://user-images.githubusercontent.com/64491670/84533184-e5bccd00-ace7-11ea-8a1c-cee98d52a26a.png)
This is for myip:8083 here everything works as it should
![image](https://user-images.githubusercontent.com/64491670/84533302-27e60e80-ace8-11ea-8525-93a76754b84f.png)
tornado does listen on 8083
In my opinion the mistake lies somewhere in the apache configs. 
also something that is probably the least priority: 
when I try to add the cert files in the web UI, I get 
>Certfile Location is not Valid, Please Enter Correct Path

OS: raspian
python2.7
Calibre-Web version: 0.6.9 beta
Docker container: None
Special Hardware:  Rasperry Pi 4
Browser: Brave, Firefox

**Comment by OzzieIsaacs** [comment]
Okay, if you enter mydomain:8083 you are getting redirected to index.php which is not right. This tells me you are not directly accessing calibre-web in this case, there is something in between (proxy?).
Regarding the certificate: If you are using apache as the proxy for accessing than apache can do the encryption ssl stuff and calibre-web doesn't need to use the encrpytion files, so do not enter them. If you got calibre-web running with https, then you need to also proxy https requests and not http requests.

**Comment by OzzieIsaacs** [comment]
Your configuration:
The server running calibre-web is the raspberry Pi with raspian. It is connected to your router (wifi or cable, doesn't matter). You are accessing it from your computer with firefox. The computer is connected to the same router (wifi or cable, doesn't matter). So all experiments we are doing are from within your home network, right?
What do we get if you type:`sudo netststat-pnlt`
?

![grafik](https://user-images.githubusercontent.com/6438895/84536216-a5604d80-aced-11ea-967c-19d684a858fa.png)
My guess is, there is somebody else listening on 8083 than python2 in your case?

**Comment by OzzieIsaacs** [comment]
Hope the commands are the same between raspian and ubuntu.
You can get the name of the command executed by: py PID (so `ps 868` for calibre-web in my case)
![grafik](https://user-images.githubusercontent.com/6438895/84536395-10118900-acee-11ea-8072-f232eb67ff7f.png)

**Comment by OzzieIsaacs** [comment]
Just to clarify: apache is not supposed to listen on port 8083, so there shall be no line:
`listen 8083` 
anywhere in the apache config

**Comment by quarz12** [comment]
this is my netstat
![image](https://user-images.githubusercontent.com/64491670/84537850-d4c48980-acf0-11ea-9149-7bbd11e63031.png)
as you see nothing else is on 8083.
this is my ports.conf:
![image](https://user-images.githubusercontent.com/64491670/84538091-51576800-acf1-11ea-91f7-579cc6c03f75.png)
and again calibre-web.conf:
![image](https://user-images.githubusercontent.com/64491670/84538388-d9d60880-acf1-11ea-939c-905c23df4ac2.png)

Is it possible that apache doesn't like nextcloud and the reverse proxy on the same port?

**Comment by OzzieIsaacs** [comment]
Nextcloud and reverse proxy is also my usecase. But in your config I don't see the nextcloud config?
I'd like to suggest the following:
In the site file your nextcloud config (with whatever your options are), listening on 443 (-> https://myexample.com):
![grafik](https://user-images.githubusercontent.com/6438895/84539248-60d7b080-acf3-11ea-9676-29f31d251425.png)

And in the standard apache.conf: (-> https://myexample.com/calibre-web):
![grafik](https://user-images.githubusercontent.com/6438895/84539014-fa529280-acf2-11ea-8c92-5e22c3a92ef2.png)

**Comment by OzzieIsaacs** [comment]
If you are having 2 virtual hosts for exactly *443 this could cause trouble I think

**Comment by quarz12** [comment]
right now this is my sites available folder
![image](https://user-images.githubusercontent.com/64491670/84539824-74374b80-acf4-11ea-984c-a45b8e2915f3.png)
000-default.conf:
![image](https://user-images.githubusercontent.com/64491670/84540751-579c1300-acf6-11ea-8f6e-95fd638c2adf.png)
000-default-le-ssl.conf:
![image](https://user-images.githubusercontent.com/64491670/84542582-0ee65900-acfa-11ea-98b2-11e5017caba2.png)
default-ssl.conf:
https://pastebin.com/DkMBykXa
nextcloud.conf:
![image](https://user-images.githubusercontent.com/64491670/84542768-684e8800-acfa-11ea-8304-4267403d5626.png)

Sadly I only understand about half of what these files are saying

**Comment by OzzieIsaacs** [comment]
The first one is redirecting all requests from http to https
The 2nd one is serving all files in /var/www/html via https
The default-ssl.conf is doing the same as the 2nd one (you should deactivate one of them)
The nextcloud.conf is serving nextcloud under https://server/nextcloud
Deactivate the calibre-web.conf file. 
Copy the location block from the calibre-web.conf file to 000-default-le-ssl.conf and you should be done.

**Comment by quarz12** [comment]
my new 000-default-le-ssl.conf:
![image](https://user-images.githubusercontent.com/64491670/84547993-f29be980-ad04-11ea-83c0-d359b897d673.png)

Now I get error 500 for mydomain.com/calibre-web:
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@localhost to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
this log looks like this
![image](https://user-images.githubusercontent.com/64491670/84550709-a1432880-ad0b-11ea-8de5-e8e74c718d8f.png)

that means something is wrong with my ssl certificate?

**Comment by OzzieIsaacs** [comment]
I don't think so, as nextcloud is working with https. 
In my opinion this is a pure apache config problem and has nothing to do with calibre-web. Please try to use your favorite search engine to find a solution.

**Comment by quarz12** [comment]
I managed to get it to work at least for http for now by simply adding quotation marks here:
ProxyPass "http://localhost:8083/"
ProxyPassReverse "http://localhost:8083/"
