### ISSUE TITLE
Calibre and rclone/google drive 

### ISSUE THREAD

**Issue by gwenvador** [janeczku/calibre-web#1490]
**Describe the bug/problem**
I have my ebook library in google drive which I access via rclone on a locally mounted disk. (/books in docker). In the config when I configure the db location to the rclone disk it does not work.
Inside the container the file correctly exists: 
root@bdb200e45b62:/# file /books/metadata.db
/books/metadata.db: SQLite 3.x database, user version 23, last written using SQLite version 3031001

**Logfile**
[2020-06-12 05:01:01,820] ERROR {cps.config_sql:323} (sqlite3.OperationalError) unable to open database: /books/metadata.db
[SQL: attach database '/books/metadata.db' as calibre;]
(Background on this error at: http://sqlalche.me/e/e3q8)
[2020-06-12 05:01:01,821]  WARN {cps.config_sql:324} invalidating configuration

**Environment (please complete the following information):**
 - OS: raspian
 - Docker container : linuxserver/calibre-web

**Comment by OzzieIsaacs** [comment]
The only thing I can say is: "unable to open database: /books/metadata.db" (maybe access rights are missing or wrong)?
I don't use this type of configuration, so I don't know whats going on.

**Comment by hackmonker** [comment]
wanted to add to this. I also have my library mounted via rclone and it cant find the database. What permissions or rights are needed to access the files?

**Comment by OzzieIsaacs** [comment]
for folder where metadata.db lives you need rwx, and if the owner of metadata.db runs calibre-web than the rights you showed in your post are alright.

**Comment by hackmonker** [comment]
drwxrwxr-x is for the folder where metadata.db lives

**Comment by OzzieIsaacs** [comment]
Calibre-Web tries to open the file, the error message in the logfile is from the operating system, it say I can't open the file. 
Is the file maybe opened and locked by somebody else?

**Comment by hackmonker** [comment]
my books library is in /mnt/books if it is helpful

**Comment by OzzieIsaacs** [comment]
I'm sorry, you are on your own. 
It's perfectly working with a local mounted library and also (maybe with some tricks) with a library on a samba share, the google drive integration seems also to run properly. 
I can't support every sync tool in the world.

**Comment by hackmonker** [comment]
even I am confused. I run other web apps like plex and sonarr but they can read the mounted files. but calibre-web cant open the database. it feels like a permission error. anyway does gdrive intagration work for teamdrives?

**Comment by hackmonker** [comment]
ok wow. after a lot of testing. I finnaly was able to do it. For future if any one wants to know.

You need --vfs-cache-mode writes flag enabled while mounting otherwise it wont detect the metadata.db.

Anyway thanks for such a great software. appreciate it.

**Comment by gwenvador** [comment]
> ok wow. after a lot of testing. I finnaly was able to do it. For future if any one wants to know.
> 
> You need --vfs-cache-mode writes flag enabled while mounting otherwise it wont detect the metadata.db.
> 
> Anyway thanks for such a great software. appreciate it.

Yeaahh. Well found hackmonker. I confirm this work. I also use the sonarr/radarr suite with rclone and don't have issue with it. I guess this is pretty standard and optimal way to use google drive. I appreciate the work of calibre-web but I feel like the current google integration is pretty complex. Rclone is easier.

For reference (https://rclone.org/commands/rclone_mount/#limitations) it looks like calibre needs to read and write the db at the same time so without this flag it fails.

**Comment by dominus-imperium** [comment]
> ok wow. after a lot of testing. I finnaly was able to do it. For future if any one wants to know.
> 
> You need --vfs-cache-mode writes flag enabled while mounting otherwise it wont detect the metadata.db.
> 
> Anyway thanks for such a great software. appreciate it.

Hi, sorry to bother you but i cannot seem to get rclone working with calibre-web. it keeps saying invalid db select valid path. any help will be appreciated. I have also used the --vfs...=full or writes flag and it seem still not to work.

**Comment by dominus-imperium** [comment]
Found how to use rclone with calibre-web:

The command `rclone mount --vfs-cache-mode=full --file-perms=0777 cloud:Calibre_folder local:mountpoint`
is how you use calibre web with rclone. all the flags are necessary for the calibre-web to see and use the metadata.db file.
