### ISSUE TITLE
Caliblur poster shows empty square behind

### ISSUE THREAD

**Issue by hackmonker** [janeczku/calibre-web#1492]
**Describe the bug/problem**
Dont know if that is a bug but there is an empty square behind the book poster when using caliblur!

**To Reproduce**
1. Have the default skin
2. go to settings
3. change to caliblur theme.
4. open book details
5. see the empty box

**Logfile**

[2020-06-13 01:18:06,787]  WARN {cps.config_sql:324} invalidating configuration
[2020-06-13 01:18:06,874]  INFO {cps.server:156} Starting Tornado server on :8083
[2020-06-13 01:22:55,602]  INFO {cps.server:207} webserver stop (restart=False)
[2020-06-13 01:23:01,718]  INFO {cps.server:207} webserver stop (restart=False)
[2020-06-13 01:23:03,658]  INFO {cps.server:184} Performing shutdown of Calibre-Web
[2020-06-13 10:31:44,357]  INFO {cps:98} Starting Calibre Web...
[2020-06-13 10:31:52,295]  INFO {cps.server:156} Starting Tornado server on :8083

**Expected behavior**
no empty sqaure behind the cover

**Screenshots**

![FV7Dc6XuZw](https://user-images.githubusercontent.com/46002790/84560677-d5e2ce80-ad63-11ea-9838-1f4996e4c098.png)

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Python version python 3.8.2
 - Calibre-Web version 0.6.9 Beta
 - Docker container none
 - Special Hardware none
 - Browser firefox

**Additional context**

**Comment by joshumax** [comment]
I too have this strange border around my book covers. I had to modify the Caliblur CSS a bit in order to make it look less hideous. The problem seems to have existed since 0.6.8 - I can send a PR with my fixes unless someone is already working on this.

**Comment by SpencerDub** [comment]
I'm also encountering this issue. @joshumax, did you ever submit a PR on this? :slightly_smiling_face:

**Comment by joshumax** [comment]
@SpencerDub No, but I can send a PR out later this evening with the fixes.

**Comment by lightmaster** [comment]
@joshumax Did you create a PR for this? I don't see any PRs from you relating to it.

**Comment by cbartondock** [comment]
I fixed this in a previous PR.

**Comment by OzzieIsaacs** [comment]
I‘ll close it. Thanks @cbartondock
