### ISSUE TITLE
Calibre web does not redirect to main page after login

### ISSUE THREAD

**Issue by hackmonker** [janeczku/calibre-web#1493]
**Describe the bug/problem**
I login via login page. If I leave it, it will load till it times out. However before I timeout if I remove the login term from the url and refresh then it logs into my account.

**To Reproduce**
1. Go to books.domain.com/login
2. Enter my account and login
3. wait and it will time out
4. if I login and before timeout, remove /login and refresh the base url, it will open my account normally.

**Logfile**
[2020-06-13 14:39:51,966]  INFO {cps.server:189} Performing restart of Calibre-Web
[2020-06-13 14:39:52,712] DEBUG {cps.services:29} Cannot import goodreads, showing authors-metadata will not work: No module named 'betterreads'
[2020-06-13 14:39:52,712] DEBUG {cps.services:37} Cannot import simpleldap, logging in with ldap will not work: No module named 'flask_simpleldap'
[2020-06-13 14:39:52,953] DEBUG {cps.comic:44} Cannot import comicapi, extracting comic metadata will not work: No module named 'comicapi'
[2020-06-13 14:39:52,955] DEBUG {cps.comic:51} Cannot import rarfile, extracting cover files from rar files will not work: No module named 'rarfile'
[2020-06-13 14:39:53,365] DEBUG {cps.uploader:43} Cannot import Image, generating pdf covers for pdf uploads will not work: MagickWand shared library not found.
You probably had not installed ImageMagick library.
Try to install:
  http://docs.wand-py.org/en/latest/guide/install.html
[2020-06-13 14:39:53,372] DEBUG {cps.uploader:58} Cannot import epub, extracting epub metadata will not work: No module named 'lxml'
[2020-06-13 14:39:53,373] DEBUG {cps.uploader:65} Cannot import fb2, extracting fb2 metadata will not work: No module named 'lxml'
[2020-06-13 14:39:53,373] DEBUG {cps.uploader:73} Cannot import Pillow, using png and webp images as cover will not work: No module named 'PIL'
[2020-06-13 14:39:53,383] DEBUG {cps.admin:64} Cannot import Flask-Dance, login with Oauth will not work: No module named 'flask_dance'
[2020-06-13 14:39:53,399] DEBUG {cps.cache_buster:45} Computing cache-busting values...
[2020-06-13 14:39:53,446] DEBUG {cps.cache_buster:58} Finished computing cache-busting values
[2020-06-13 14:39:53,446]  INFO {cps:98} Starting Calibre Web...
[2020-06-13 14:39:58,833]  INFO {cps.server:156} Starting Tornado server on :8083
[2020-06-13 14:43:16,627] DEBUG {cps.web:1432} You are now logged in as: 'admin'

**Expected behavior**
I go to book.domain.com and login, it automatically redirects into my account

**Screenshots**

**Environment (please complete the following information):**
 - OS: ubuntu
 - Python version python 3.8.2
 - Calibre-Web version 0.6.9 beta
 - Docker container none
 - Special Hardware none
 - Browser firefox

**Additional context**
accessing via reverse proxy using caddy
This problem is the same with this guy
https://www.reddit.com/r/Calibre/comments/f9cf3r/calibrecalibreweb_behind_traefik_reverse_proxy/
https://www.reddit.com/r/Traefik/comments/ev7ont/timeouts_to_some_services_being_reverse_proxied/

Like he said it works fine in my PC. But other devices not so.

**Comment by hackmonker** [comment]
So this is a problem faced nly in caddy and traefik. For some reason nginx doe not have this. Hope someone can shed light on it.

**Comment by OzzieIsaacs** [comment]
Sorry, wrong issue closed

**Comment by OzzieIsaacs** [comment]
I installed caddy version 2.0.0 from the Github page (I used the deb installer). I'm using a linux mint 19.3. I granted access rights to open a port 80 for caddy. 
I started caddy with `caddy start`
I started my Calibre-web instance (current master from evening 20th June 2020)
I created the reverse proxy by typing: `caddy reverse-proxy --from :80 --to 127.0.0.1:8083`
I tried to access the calibre-web from the localhost (firefox) by accessing `http://127.0.0.1`. It's redirecting me to the login page `http://127.0.0.1/login`, I can enter my credentials, get logged in and get redirect to `http://127.0.0.1`. 
I tried to access it from another computer (linux mint 19.3) by using http//server-name, same behaviour, login page, get logged in 
I used my IPad using http//server-name, same behaviour, login page, get logged in.

Both links you posted are referring to traefik reverse proxy installations and sounds like they are running docker container and having the problem by accessing it from outside their home networks. Sounds different to me.
In the last sentence you write:

> Like he said it works fine in my PC. But other devices not so.

Does this mean it's working in general and only one device isn't working? The whole post doesn't sound like this

**Comment by OzzieIsaacs** [comment]
I also checked it with traefik (I added my configuration in the wiki) I can not see any problems, but I don't use docker, just the "plain" reverse proxy's. If the problem is related to docker, please ask for help at the docker, traefik or caddy repros. My primary focus is calibre-web and not reverse proxy configurations of different softwares and use cases.
Thanks for your understanding.

**Comment by samcro1967** [comment]
I am able to reproduce this consitently.  I am running Calibre-Web and Caddy  V2 both in Docker containers on the same host.  When I login to https://calibre-web.mydomain.net, it redirects me to  http://calibre-web.mydomain.net/ (http instead of https).  If I manually update the URL in the browser address bar from http to https, everything works fine.  I get the same result from Safari and Chrome on iOS.

I also get the same behavior when I logoff as well as the next time I launch the browser and go to https://calibre-web.mydomain.net.  I again automatically redirected back to to http://calibre-web.mydomain.net/.  I just update the URL to https and it works again,  I have tried numerous changes to the Caddy config and nothing seems to work.

**CaddyFile Confg**
```
##############################################################################################
calibre-web.mydomain.net http://local.calibre-web {
	encode gzip
	log {
		output file /logs/calibre-web.log
		format single_field common_log
	}
	reverse_proxy 192.168.1.103:8083
}
```

**Comment by dima-ser** [comment]
I also have this issue. After logging in (or logging out), it's hardcoded to redirect to http, not https. So if you have your calibre-web behind reverse proxy with only 443 port, it fails when it tries to access it on port 80.

Can we have a configuration option to let calibre-web know either whether or not to use HTTPS or provide a full app URL so that it knows where to redirect?

**Comment by raskitoma** [comment]
> I also have this issue. After logging in (or logging out), it's hardcoded to redirect to http, not https. So if you have your calibre-web behind reverse proxy with only 443 port, it fails when it tries to access it on port 80. I'm using Synology NAS reverse proxy.
> 
> Steps to reproduce:
> 
> * Go to https://calibre-web.domain.com
> * Enter login credentials on the login page
> * Get redirected to http://calibre-web.domain.com which fails to connect because I don't have my proxy listening on port 80
> * I have to manually change http to https in the URL in the address bar and then it lets me in as I'm already authenticated
> 
> I think this should be a calibre-web issue as even if someone doesn't use a reverse proxy, they may want to run calibre-web on SSL port only. As it is right now, calibre-web is forcing the HTTP.
> 
> Can we have a configuration option to let calibre-web know either whether or not to use HTTPS or provide a full app URL so that it knows where to redirect?

Have the same error using caddy for proxy_reverse. Thing is when I'm trying to enable oauth with google, for some reason caddy sends http instead of https for the redirect_uri, provoking "Error 400: redirect_uri_mismatch"

I can only setup the redirect_uri as https (developer account), but as caddy manages all the tls it should works with no problem.

**Comment by dima-ser** [comment]
> 
> 
> > I also have this issue. After logging in (or logging out), it's hardcoded to redirect to http, not https. So if you have your calibre-web behind reverse proxy with only 443 port, it fails when it tries to access it on port 80. I'm using Synology NAS reverse proxy.
> > Steps to reproduce:
> > 
> > * Go to https://calibre-web.domain.com
> > * Enter login credentials on the login page
> > * Get redirected to http://calibre-web.domain.com which fails to connect because I don't have my proxy listening on port 80
> > * I have to manually change http to https in the URL in the address bar and then it lets me in as I'm already authenticated
> > 
> > I think this should be a calibre-web issue as even if someone doesn't use a reverse proxy, they may want to run calibre-web on SSL port only. As it is right now, calibre-web is forcing the HTTP.
> > Can we have a configuration option to let calibre-web know either whether or not to use HTTPS or provide a full app URL so that it knows where to redirect?
> 
> Have the same error using caddy for proxy_reverse. Thing is when I'm trying to enable oauth with google, for some reason caddy sends http instead of https for the redirect_uri, provoking "Error 400: redirect_uri_mismatch"
> 
> I can only setup the redirect_uri as https (developer account), but as caddy manages all the tls it should works with no problem.

FYI, I fixed this by adding **X-Scheme** header with the value **$scheme** in my reverse proxy config

**Comment by raskitoma** [comment]
> > > I also have this issue. After logging in (or logging out), it's hardcoded to redirect to http, not https. So if you have your calibre-web behind reverse proxy with only 443 port, it fails when it tries to access it on port 80. I'm using Synology NAS reverse proxy.
> > > Steps to reproduce:
> > > 
> > > * Go to https://calibre-web.domain.com
> > > * Enter login credentials on the login page
> > > * Get redirected to http://calibre-web.domain.com which fails to connect because I don't have my proxy listening on port 80
> > > * I have to manually change http to https in the URL in the address bar and then it lets me in as I'm already authenticated
> > > 
> > > I think this should be a calibre-web issue as even if someone doesn't use a reverse proxy, they may want to run calibre-web on SSL port only. As it is right now, calibre-web is forcing the HTTP.
> > > Can we have a configuration option to let calibre-web know either whether or not to use HTTPS or provide a full app URL so that it knows where to redirect?
> > 
> > 
> > Have the same error using caddy for proxy_reverse. Thing is when I'm trying to enable oauth with google, for some reason caddy sends http instead of https for the redirect_uri, provoking "Error 400: redirect_uri_mismatch"
> > I can only setup the redirect_uri as https (developer account), but as caddy manages all the tls it should works with no problem.
> 
> FYI, I fixed this by adding **X-Scheme** header with the value **$scheme** in my reverse proxy config

Can you guide me on how to write this into my Caddyfile... this is the excerpt for calibre-web:

```
books.mydomain.com {
	reverse_proxy calibre-web_ip:8083 {
		header_up Host {http.request.host}
		header_up X-Real-IP {http.request.remote.host}
		header_up X-Forwarded-Proto https
	}
}
```

**Comment by dima-ser** [comment]
> 
> 
> > > > I also have this issue. After logging in (or logging out), it's hardcoded to redirect to http, not https. So if you have your calibre-web behind reverse proxy with only 443 port, it fails when it tries to access it on port 80. I'm using Synology NAS reverse proxy.
> > > > Steps to reproduce:
> > > > 
> > > > * Go to https://calibre-web.domain.com
> > > > * Enter login credentials on the login page
> > > > * Get redirected to http://calibre-web.domain.com which fails to connect because I don't have my proxy listening on port 80
> > > > * I have to manually change http to https in the URL in the address bar and then it lets me in as I'm already authenticated
> > > > 
> > > > I think this should be a calibre-web issue as even if someone doesn't use a reverse proxy, they may want to run calibre-web on SSL port only. As it is right now, calibre-web is forcing the HTTP.
> > > > Can we have a configuration option to let calibre-web know either whether or not to use HTTPS or provide a full app URL so that it knows where to redirect?
> > > 
> > > 
> > > Have the same error using caddy for proxy_reverse. Thing is when I'm trying to enable oauth with google, for some reason caddy sends http instead of https for the redirect_uri, provoking "Error 400: redirect_uri_mismatch"
> > > I can only setup the redirect_uri as https (developer account), but as caddy manages all the tls it should works with no problem.
> > 
> > 
> > FYI, I fixed this by adding **X-Scheme** header with the value **$scheme** in my reverse proxy config
> 
> Can you guide me on how to write this into my Caddyfile... this is the excerpt for calibre-web:
> 
> ```
> books.mydomain.com {
> 	reverse_proxy calibre-web_ip:8083 {
> 		header_up Host {http.request.host}
> 		header_up X-Real-IP {http.request.remote.host}
> 		header_up X-Forwarded-Proto https
> 	}
> }
> ```

Not sure as I use Synology for my reverse proxy. But just looking at the syntax in your post, you already have some headers added, so if we use those as example it would probably be like this:

```books.mydomain.com {
	reverse_proxy calibre-web_ip:8083 {
		header_up Host {http.request.host}
		header_up X-Real-IP {http.request.remote.host}
		header_up X-Forwarded-Proto https
                header_up X-Scheme $scheme
	}
}
```
No guarantee it will work as I'm flying blind here.

**Comment by raskitoma** [comment]
> > > > > I also have this issue. After logging in (or logging out), it's hardcoded to redirect to http, not https. So if you have your calibre-web behind reverse proxy with only 443 port, it fails when it tries to access it on port 80. I'm using Synology NAS reverse proxy.
> > > > > Steps to reproduce:
> > > > > 
> > > > > * Go to https://calibre-web.domain.com
> > > > > * Enter login credentials on the login page
> > > > > * Get redirected to http://calibre-web.domain.com which fails to connect because I don't have my proxy listening on port 80
> > > > > * I have to manually change http to https in the URL in the address bar and then it lets me in as I'm already authenticated
> > > > > 
> > > > > I think this should be a calibre-web issue as even if someone doesn't use a reverse proxy, they may want to run calibre-web on SSL port only. As it is right now, calibre-web is forcing the HTTP.
> > > > > Can we have a configuration option to let calibre-web know either whether or not to use HTTPS or provide a full app URL so that it knows where to redirect?
> > > > 
> > > > 
> > > > Have the same error using caddy for proxy_reverse. Thing is when I'm trying to enable oauth with google, for some reason caddy sends http instead of https for the redirect_uri, provoking "Error 400: redirect_uri_mismatch"
> > > > I can only setup the redirect_uri as https (developer account), but as caddy manages all the tls it should works with no problem.
> > > 
> > > 
> > > FYI, I fixed this by adding **X-Scheme** header with the value **$scheme** in my reverse proxy config
> > 
> > 
> > Can you guide me on how to write this into my Caddyfile... this is the excerpt for calibre-web:
> > ```
> > books.mydomain.com {
> > 	reverse_proxy calibre-web_ip:8083 {
> > 		header_up Host {http.request.host}
> > 		header_up X-Real-IP {http.request.remote.host}
> > 		header_up X-Forwarded-Proto https
> > 	}
> > }
> > ```
> 
> Not sure as I use Synology for my reverse proxy. But just looking at the syntax in your post, you already have some headers added, so if we use those as example it would probably be like this:
> 
> ```
> 	reverse_proxy calibre-web_ip:8083 {
> 		header_up Host {http.request.host}
> 		header_up X-Real-IP {http.request.remote.host}
> 		header_up X-Forwarded-Proto https
>                 header_up X-Scheme $scheme
> 	}
> }
> ```
> 
> No guarantee it will work as I'm flying blind here.

Thanks man, it didn't worked. I'm using an std debian machine with docker/docker-compose/portainer mix.

Thing is, it should be possible to add the correct "expected" redirect_uri. There are many other apps that allows you to do that. (by apps I mean containers and so...)

Thanks anyway.
