### ISSUE TITLE
Change Calibre-web font in caliblur

### ISSUE THREAD

**Issue by hackmonker** [janeczku/calibre-web#1495]
**Is your feature request related to a problem? Please describe.**
Just a maybe help I guess. Anyway to get the default calibre web font in caliblur. thats all. just asking if it is possible.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by OzzieIsaacs** [comment]
I could change it of course. I guess the Caliblur! font is the same as Plex uses, which it is tring to fit the design into. 
I cannot distinguish between the two fonts. So may I kindly ask what's the reason behind your request?

**Comment by hackmonker** [comment]
Oh sorry for not clearing it properly. I meant the font of the calibre-web logo in the default one. Really like that cursive font. Is it possible to use the same font in the logo for caliblur?

**Comment by OzzieIsaacs** [comment]
The idea of the caliblur theme is to have a "plex for books" and the design of the plex ui looks absolutly similar to the caliblur theme (https://images.techhive.com/images/article/2016/08/plexrecordinginfo-100680017-large.jpg). So I think it would break the design and I will not change it, sorry
