### ISSUE TITLE
I can't read my e-books on Calibre-Web.

### ISSUE THREAD

**Issue by Yngda** [janeczku/calibre-web#1496]
I can't find the _"read"_ button in management panel. E-books can't be read online, but they could be downloaded.
And I found an issue like mine: [url](https://github.com/Technosoft2000/docker-calibre-web/issues/65) , but it can't work my problem out.

Calibre-Web version: 0.6.8; 
OS: Debain 9.6;
Browser: Google Chrome, version 83.0.4103.97.

**Comment by OzzieIsaacs** [comment]
The access right is granted?:
![grafik](https://user-images.githubusercontent.com/6438895/84807049-eebede80-b006-11ea-9649-787a3642fac9.png)
You are aware that only certain formats are supported?
![grafik](https://user-images.githubusercontent.com/6438895/84807327-5d03a100-b007-11ea-8fe8-ebc67b173c3f.png)

**Comment by Yngda** [comment]
Thanks for your replyment! 
I have grated "allow e-book viewer" right, and all of my books are "epub" format. 
But there is no "read" button, the books just can be downloaded.

**Comment by AlexKalopsia** [comment]
Hi, I am having the same issue. Some EPUBS have the Read button, others (converted from aw3 to eepub wiith calibre) don't. Any idea what could be causing this? Is there a way to refresh the db somehow?

**Comment by vasujain** [comment]
same for me. Was it ever resolved?

**Comment by vasujain** [comment]
Actually got resolved. You need to do the above for the current user (admin) - `Allow eBook Viewer`
