### ISSUE TITLE
upload button not there even though uploads are allowed

### ISSUE THREAD

**Issue by XiovV** [janeczku/calibre-web#1497]
The uploads are allowed in the admin section, but the Upload button is not showing on the top bar next to Tasks. I'm running Calibre Web 0.6.8.

**Comment by OzzieIsaacs** [comment]
You may have to reload the page after saving. 
I can't reproduce this. I need more details (this is why I created the issue reporting template)

**Comment by XiovV** [comment]
@OzzieIsaacs I did reload and switched from linuxserver.io to Technosoft2000's docker container, same issue

**Comment by beltet** [comment]
Same problem. I created a new user aswell beside the admin account. No upload button....

**Comment by shermansmith** [comment]
was confused after install by this. solution is to go to the admin menu, Edit Basic Configuration, Feature Configuration, and check the box for "enable uploads". This worked for me on the Technosoft2000 docker image. YMMV.

**Comment by XiovV** [comment]
@shermansmith Yup, that was it. Thanks a lot.
