### ISSUE TITLE
Cannot read property 'length' of undefined on http://127.0.0.1:8083/config

### ISSUE THREAD

**Issue by stormeyes** [janeczku/calibre-web#1503]
**Describe the bug/problem**
once I clone the repo and pip install requirements, then I python cps.py, then visit http://127.0.0.1:8083/config , and try to click the folder icon button, nothing happen, then
I press F12 to get the console error info and I got this
![image](https://user-images.githubusercontent.com/5072174/85391422-baa26b00-b57c-11ea-958c-b7001d46f2da.png)

**To Reproduce**
1. after everything ready, first time to visit http://127.0.0.1:8083/config
2. See error

**Logfile**
Uncaught TypeError: Cannot read property 'length' of undefined
    at HTMLDocument.<anonymous> (config:159)
    at e (jquery.min.js?q=dc5e7f1:2)
    at t (jquery.min.js?q=dc5e7f1:2)

**Expected behavior**
the button should open file select dialog

**Screenshots**

**Environment (please complete the following information):**
 - OS: mac
 - Python version python3.8
 - Calibre-Web version: master
 - Docker container: None
 - Special Hardware MacBook 2020/ Mac Mini
 - Browser: chrome and safari

**Additional context**

**Comment by OzzieIsaacs** [comment]
You are right, the button is supposed to open a file select dialog. But I'm not ready yet. So currently it's a marker that the field is a file dialog. This one is a special one, as it has to be a server file browser. I'm currently working on different issues. I'll close this one. (Regarding the js error, I will provide a fix)
