### ISSUE TITLE
Unable to connect to Zimbra's LDAP Service 

### ISSUE THREAD

**Issue by Kuroburn** [janeczku/calibre-web#1504]
**Description**
Hello again, I'm trying to connect the app to the Zimbra's LDAP Service of my work but so far I have not achieved what was proposed. I reccently got the credentials to access the LDAP server but after configure the values on the app's Basic Configuration there is no sign of sucess.

**Reproduction**
1. Register my works LDAP info into app:

> LDAP Base DN: dc=utm,dc=edu,dc=ec
LDAP SERVER: Server IP
LDAP Admin DN: uid=zimbra,cn=admins,cn=zimbra
PASSWORD LDAP: *******

2. Click on Save
3. App shows the update config message on top
4. Restart App service.
5. Logout and relogin
6. After no sucess, login with the fallback.

**Logfile**

```
[2020-06-23 22:20:44,560]  INFO {cps.server:200} webserver stop (restart=True)
[2020-06-23 22:20:44,568]  INFO {cps.server:185} Performing restart of Calibre-Web
[2020-06-23 22:20:45,119] DEBUG {cps.services:29} Cannot import goodreads, showing authors-metadata will not work: No module named 'goodreads'
[2020-06-23 22:20:45,160] DEBUG {cps.services:45} Cannot import SyncToken, syncing books with Kobo Devices will not work: No module named 'jsonschema'
[2020-06-23 22:20:45,270] DEBUG {cps.comic:33} cannot import comicapi, extracting comic metadata will not work: No module named 'comicapi'
[2020-06-23 22:20:45,271] DEBUG {cps.comic:40} cannot import rarfile, extracting cover files from rar files will not work: No module named 'rarfile'
[2020-06-23 22:20:45,655] DEBUG {cps.uploader:58} cannot import epub, extracting epub metadata will not work: No module named 'lxml'
[2020-06-23 22:20:45,655] DEBUG {cps.uploader:65} cannot import fb2, extracting fb2 metadata will not work: No module named 'lxml'
[2020-06-23 22:20:45,655] DEBUG {cps.uploader:73} cannot import Pillow, using png and webp images as cover will not work: No module named 'PIL'
[2020-06-23 22:20:45,665] DEBUG {cps.admin:63} Cannot import Flask-Dance, login with Oauth will not work: No module named 'flask_dance'
[2020-06-23 22:20:45,681] DEBUG {cps.cache_buster:45} Computing cache-busting values...
[2020-06-23 22:20:45,713] DEBUG {cps.cache_buster:58} Finished computing cache-busting values
[2020-06-23 22:20:45,713]  INFO {cps:95} Starting Calibre Web...
[2020-06-23 22:20:45,807]  INFO {cps.server:152} Starting Tornado server on :443
[2020-06-23 22:21:52,989] DEBUG {cps.config_sql:288} _ConfigSQL updating storage
[2020-06-23 22:21:52,998] DEBUG {cps.config_sql:288} _ConfigSQL updating storage
[2020-06-23 22:21:53,001]  INFO {cps.server:200} webserver stop (restart=True)
[2020-06-23 22:21:53,009]  INFO {cps.server:185} Performing restart of Calibre-Web
[2020-06-23 22:21:53,550] DEBUG {cps.services:29} Cannot import goodreads, showing authors-metadata will not work: No module named 'goodreads'
[2020-06-23 22:21:53,591] DEBUG {cps.services:45} Cannot import SyncToken, syncing books with Kobo Devices will not work: No module named 'jsonschema'
[2020-06-23 22:21:53,700] DEBUG {cps.comic:33} cannot import comicapi, extracting comic metadata will not work: No module named 'comicapi'
[2020-06-23 22:21:53,701] DEBUG {cps.comic:40} cannot import rarfile, extracting cover files from rar files will not work: No module named 'rarfile'
[2020-06-23 22:21:54,050] DEBUG {cps.uploader:58} cannot import epub, extracting epub metadata will not work: No module named 'lxml'
[2020-06-23 22:21:54,050] DEBUG {cps.uploader:65} cannot import fb2, extracting fb2 metadata will not work: No module named 'lxml'
[2020-06-23 22:21:54,051] DEBUG {cps.uploader:73} cannot import Pillow, using png and webp images as cover will not work: No module named 'PIL'
[2020-06-23 22:21:54,060] DEBUG {cps.admin:63} Cannot import Flask-Dance, login with Oauth will not work: No module named 'flask_dance'
[2020-06-23 22:21:54,076] DEBUG {cps.cache_buster:45} Computing cache-busting values...
[2020-06-23 22:21:54,108] DEBUG {cps.cache_buster:58} Finished computing cache-busting values
[2020-06-23 22:21:54,108]  INFO {cps:95} Starting Calibre Web...
[2020-06-23 22:21:54,198]  INFO {cps.server:152} Starting Tornado server on :443
[2020-06-23 22:21:56,213] DEBUG {cps.web:309} LDAP empty response
[2020-06-23 22:22:05,554]  INFO {cps.server:200} webserver stop (restart=True)
[2020-06-23 22:22:05,556]  INFO {cps.server:185} Performing restart of Calibre-Web
[2020-06-23 22:22:06,152] DEBUG {cps.services:29} Cannot import goodreads, showing authors-metadata will not work: No module named 'goodreads'
[2020-06-23 22:22:06,194] DEBUG {cps.services:45} Cannot import SyncToken, syncing books with Kobo Devices will not work: No module named 'jsonschema'
[2020-06-23 22:22:06,316] DEBUG {cps.comic:33} cannot import comicapi, extracting comic metadata will not work: No module named 'comicapi'
[2020-06-23 22:22:06,317] DEBUG {cps.comic:40} cannot import rarfile, extracting cover files from rar files will not work: No module named 'rarfile'
[2020-06-23 22:22:06,675] DEBUG {cps.uploader:58} cannot import epub, extracting epub metadata will not work: No module named 'lxml'
[2020-06-23 22:22:06,676] DEBUG {cps.uploader:65} cannot import fb2, extracting fb2 metadata will not work: No module named 'lxml'
[2020-06-23 22:22:06,676] DEBUG {cps.uploader:73} cannot import Pillow, using png and webp images as cover will not work: No module named 'PIL'
[2020-06-23 22:22:06,686] DEBUG {cps.admin:63} Cannot import Flask-Dance, login with Oauth will not work: No module named 'flask_dance'
[2020-06-23 22:22:06,703] DEBUG {cps.cache_buster:45} Computing cache-busting values...
[2020-06-23 22:22:06,736] DEBUG {cps.cache_buster:58} Finished computing cache-busting values
[2020-06-23 22:22:06,737]  INFO {cps:95} Starting Calibre Web...
[2020-06-23 22:22:06,833]  INFO {cps.server:152} Starting Tornado server on :443
[2020-06-23 22:22:13,960] DEBUG {cps.web:1350} User logged out
[2020-06-23 22:22:16,651]  INFO {cps.web:1331} Login failed for user "bluzardo@utm.edu.ec" IP-adress: 181.198.206.23
[2020-06-23 22:22:18,997]  INFO {cps.web:1297} Local Fallback Login as: 'cdemera'
```

**Expected behavior**
Login into the App with my work's zimbra credentials. The use of LDAP is for academic purpose since my students are struggling with the credentials of multiple accounts in the University, this is a solution to use an already created account.

**Screenshots**
[Screenshot 1](https://i.imgur.com/UuGrEsz.png)
[Screenshot 2](https://i.imgur.com/0UKBrIn.png)
[Screenshot 3](https://i.imgur.com/a5cTkGD.png)
[Screenshot 4](https://i.imgur.com/gs31bXC.png)

**Environment (VM):**
 - OS: CentOS 8
 - Python version: python3.6
 - Calibre-Web version: 0.6.7 (updated through app)
 - Docker container: None
 - Special Hardware: None
 - Browser: Brave

**Additional context**
I access the server through SSH.

Thanks for the read time and the help.

**Comment by OzzieIsaacs** [comment]
Looks like a longer project (inital problem was 1month ago).
What's a bit sucpious to me is the `LDAP Base DN: dc="",dc="",dc=""`, the screenshot shows someting else. Which one do you use?
In 0.6.7 there was one bug in the LDAP import users, username with whitespaces weren't imported correct. Could this (partly) be your problem? Another problem was regarding opds, this seems not your problem.

I'd like to suggest to cut the elephant in pieces. 
Part one: Logging on 
Part two: Importing the users

Did you see the example in the wiki? https://github.com/janeczku/calibre-web/wiki/LDAP-Login#example (Especially the commands to check if the parameters are correct in the lower area)

For part one: Did you create a user with the name you are trying to log in? Is it possible for you to execute the lpadsearch programm from the wiki? (`yum -y install openldap-clients` should install it) 

If we don't find a solution there it might be necessary to install wireshark (to display the network traffic) (https://linuxtechlab.com/install-wireshark-linux-centosubuntu/)

In the wiki there are some schema files listed. I don't know if Zimbra has something similar. If yes, would be great if you could post it (you can replace real names with fake entries, I just want to get impression on the structure). I can then try to reproduce it with my setup. 

Did you try to get it work with openldap server? In the screenshot the tick for openldap compatibility is ticked. Google didn't give a clear statement regarding this topic. Did you try it without this setting?

One Remark:
Restart App service. -> this should not be neccessary, as calibre-web is restarting in the background, right after presenting the success message

**Comment by Kuroburn** [comment]
> Looks like a longer project (inital problem was 1month ago).
> What's a bit sucpious to me is the `LDAP Base DN: dc="",dc="",dc=""`, the screenshot shows someting else. Which one do you use?

The screenshot values, sorry my mistake.

> In 0.6.7 there was one bug in the LDAP import users, username with whitespaces weren't imported correct. Could this (partly) be your problem? Another problem was regarding opds, this seems not your problem.

Don't know anything of this becauase I cannot connect.

> I'd like to suggest to cut the elephant in pieces.
> Part one: Logging on
> Part two: Importing the users

Already tried this, fill only the connection values without success. Don't care if I cannot import the users, I just want to be able to login with the University credentials.

> Did you see the example in the wiki? https://github.com/janeczku/calibre-web/wiki/LDAP-Login#example (Especially the commands to check if the parameters are correct in the lower area)

Yes, I have exactly 25 hours trying to figure the error.

> For part one: Did you create a user with the name you are trying to log in? Is it possible for you to execute the lpadsearch programm from the wiki? (`yum -y install openldap-clients` should install it)

I wasn't able to do this yesterday but today I just get the privilegies from the IT guy to install openldap-clients and run the ldapsearch, and yes... I got answer there, but no in the App, I mean... I have connection from the console with the same parameters of the App but no vice versa.

> If we don't find a solution there it might be necessary to install wireshark (to display the network traffic) (https://linuxtechlab.com/install-wireshark-linux-centosubuntu/)

My enviorement won't allow me to do this ... I connect to the VM through an encrypted VPN and I feel the IT guy won't help me in this one (he already gives me privileges to use the LDAP server and that is a lot of responsability).

> In the wiki there are some schema files listed. I don't know if Zimbra has something similar. If yes, would be great if you could post it (you can replace real names with fake entries, I just want to get impression on the structure). I can then try to reproduce it with my setup.

Well... from the response of ldapsearch command I can tell you that when looking for a uid the answer looks like this:
_**dn: uid=username_without_domain_,ou=people,dc=utm,dc=edu,dc=ec**_

> Did you try to get it work with openldap server? In the screenshot the tick for openldap compatibility is ticked. Google didn't give a clear statement regarding this topic. Did you try it without this setting?

[Zimbra documentation](https://wiki.zimbra.com/wiki/Zimbra_Directory_Service_(LDAP)#:~:text=The%20Zimbra%20LDAP%20service%20is,the%20Zimbra%20schema%20already%20installed.&text=The%20LDAP%20server%20is%20identified,includes%20attributes%20specifying%20operating%20parameters.) says they use OpenLDAP  

> One Remark:
> Restart App service. -> this should not be neccessary, as calibre-web is restarting in the background, right after presenting the success message

Thanks for the tip bro.

**Comment by OzzieIsaacs** [comment]
To figure out where the problem is, we could try to activate debug outputs for the python ldap login code. Could you please search for the flask-simpleldap folder (if you used the vendor folder, it should be in there, otherwise, python3/site-packages would be a good idea to look for it). Please edit the file \_\_init\_\_.py. Line 92 to line 95 should look like this:
            conn = ldap.initialize('{0}://{1}:{2}'.format(
                current_app.config['LDAP_SCHEMA'],
                current_app.config['LDAP_HOST'],
                current_app.config['LDAP_PORT'])**, trace_level=2**)
Please add the , trace_level=2 part. After a restart of calibre web we should get outputs on the console on login attempts
[...]
*** <ldap.ldapobject.SimpleLDAPObject object at 0x7fb2224af9b0> ldap://127.0.0.1:3268 - SimpleLDAPObject.simple_bind
(('cn=root,dc=utm,dc=edu,dc=ec', b'secret', None, None), {})
=> result:
1
*** <ldap.ldapobject.SimpleLDAPObject object at 0x7fb2224af9b0> ldap://127.0.0.1:3268 - SimpleLDAPObject.result4
((1, 1, -1, 0, 0, 0), {})
=> result:
(97, [], 1, [])
*** <ldap.ldapobject.SimpleLDAPObject object at 0x7fb2224af9b0> ldap://127.0.0.1:3268 - SimpleLDAPObject.search_ext
(('ou=people,dc=utm,dc=edu,dc=ec', 2, '(uid=user0)', [], 0, None, None, -1, 0),
 {})
=> result:
2
*** <ldap.ldapobject.SimpleLDAPObject object at 0x7fb2224af9b0> ldap://127.0.0.1:3268 - SimpleLDAPObject.result4
((2, 1, -1, 0, 0, 0), {})
=> result:
(101,
 [('uid=user0,ou=people,dc=utm,dc=edu,dc=ec',
   {'cn': [b'user0'],
    'gn': [b'John'],
    'objectClass': [b'organizationalPerson', b'person', b'zimbraAccount'],
    'sn': [b'Doe'],
    'uid': [b'user0'],
    'userPassword': [b'terces'],
    'zimbraAccountStatus': [b'active'],
    'zimbraId': [b'112']})],
 2,
 [])
*** <ldap.ldapobject.SimpleLDAPObject object at 0x7fb2224af9b0> ldap://127.0.0.1:3268 - SimpleLDAPObject.unbind_ext
((None, None), {})
=> result:
None
[...]
*** <ldap.ldapobject.SimpleLDAPObject object at 0x7fb2224af9b0> ldap://127.0.0.1:3268 - SimpleLDAPObject.simple_bind
(('cn=root,dc=utm,dc=edu,dc=ec', b'secret', None, None), {})
=> result:
1
*** <ldap.ldapobject.SimpleLDAPObject object at 0x7fb2224af9b0> ldap://127.0.0.1:3268 - SimpleLDAPObject.result4
((1, 1, -1, 0, 0, 0), {})
=> result:
(97, [], 1, [])
*** <ldap.ldapobject.SimpleLDAPObject object at 0x7fb2224af9b0> ldap://127.0.0.1:3268 - SimpleLDAPObject.search_ext
(('ou=people,dc=utm,dc=edu,dc=ec',
  2,
  '(uid=user0)',
  None,
  0,
  None,
  None,
  -1,
  0),
 {})
=> result:
2
*** <ldap.ldapobject.SimpleLDAPObject object at 0x7fb2224af9b0> ldap://127.0.0.1:3268 - SimpleLDAPObject.result4
((2, 1, -1, 0, 0, 0), {})
=> result:
(101,
 [('uid=user0,ou=people,dc=utm,dc=edu,dc=ec',
   {'cn': [b'user0'],
    'gn': [b'John'],
    'objectClass': [b'organizationalPerson', b'person', b'zimbraAccount'],
    'sn': [b'Doe'],
    'uid': [b'user0'],
    'userPassword': [b'terces'],
    'zimbraAccountStatus': [b'active'],
    'zimbraId': [b'112']})],

so we can see what fails, the admin login, the user details query, or the user password check

I tried to set up a schema like ( I think it could be) yours. It worked for me.
dn: dc=edu,dc=ec
dc: ec
objectClass: dcObject

dn: dc=utm,dc=edu,dc=ec
dc: zimbra
objectClass: dcObject
objectClass: organization

dn: ou=people,dc=utm,dc=edu,dc=ec
objectClass: organizationalUnit
ou: people

dn: cn=root,dc=utm,dc=edu,dc=ec
cn: root
gn: root
mail: admin@calibreweb.com
objectclass: top
objectclass: person
objectClass: zimbraAccount
zimbraAccountStatus: active
zimbraId: 111
sn: admin
userPassword: secret

dn: uid=user0@we.de,ou=people,dc=utm,dc=edu,dc=ec
objectClass: person
objectClass: organizationalPerson
objectClass: zimbraAccount
uid: user0@we.de
cn: user0
gn: John
sn: Doe
zimbraAccountStatus: active
zimbraId: 112
userPassword: terces

**Comment by Kuroburn** [comment]
> To figure out where the problem is, we could try to activate debug outputs for the python ldap login code. Could you please search for the flask-simpleldap folder (if you used the vendor folder, it should be in there, otherwise, python3/site-packages would be a good idea to look for it). Please edit the file __init__.py. Line 92 to line 95 should look like this (please keep the spaces/tabs in the original file:
> conn = ldap.initialize('{0}://{1}:{2}'.format(
> current_app.config['LDAP_SCHEMA'],
> current_app.config['LDAP_HOST'],
> current_app.config['LDAP_PORT'])**, trace_level=2**)
> Please add the , trace_level=2 part. After a restart of calibre web we should get outputs on the console on login attempts
> [...]
> *** <ldap.ldapobject.SimpleLDAPObject object at 0x7fb2224af9b0> ldap://127.0.0.1:3268 - SimpleLDAPObject.simple_bind
> (('cn=root,dc=utm,dc=edu,dc=ec', b'secret', None, None), {})
> => result:
> 1
> *** <ldap.ldapobject.SimpleLDAPObject object at 0x7fb2224af9b0> ldap://127.0.0.1:3268 - SimpleLDAPObject.result4
> ((1, 1, -1, 0, 0, 0), {})
> => result:
> (97, [], 1, [])
> *** <ldap.ldapobject.SimpleLDAPObject object at 0x7fb2224af9b0> ldap://127.0.0.1:3268 - SimpleLDAPObject.search_ext
> (('ou=people,dc=utm,dc=edu,dc=ec', 2, '(uid=user0)', [], 0, None, None, -1, 0),
> {})
> => result:
> 2
> *** <ldap.ldapobject.SimpleLDAPObject object at 0x7fb2224af9b0> ldap://127.0.0.1:3268 - SimpleLDAPObject.result4
> ((2, 1, -1, 0, 0, 0), {})
> => result:
> (101,
> [('uid=user0,ou=people,dc=utm,dc=edu,dc=ec',
> {'cn': [b'user0'],
> 'gn': [b'John'],
> 'objectClass': [b'organizationalPerson', b'person', b'zimbraAccount'],
> 'sn': [b'Doe'],
> 'uid': [b'user0'],
> 'userPassword': [b'terces'],
> 'zimbraAccountStatus': [b'active'],
> 'zimbraId': [b'112']})],
> 2,
> [])
> *** <ldap.ldapobject.SimpleLDAPObject object at 0x7fb2224af9b0> ldap://127.0.0.1:3268 - SimpleLDAPObject.unbind_ext
> ((None, None), {})
> => result:
> None
> [...]
> *** <ldap.ldapobject.SimpleLDAPObject object at 0x7fb2224af9b0> ldap://127.0.0.1:3268 - SimpleLDAPObject.simple_bind
> (('cn=root,dc=utm,dc=edu,dc=ec', b'secret', None, None), {})
> => result:
> 1
> *** <ldap.ldapobject.SimpleLDAPObject object at 0x7fb2224af9b0> ldap://127.0.0.1:3268 - SimpleLDAPObject.result4
> ((1, 1, -1, 0, 0, 0), {})
> => result:
> (97, [], 1, [])
> *** <ldap.ldapobject.SimpleLDAPObject object at 0x7fb2224af9b0> ldap://127.0.0.1:3268 - SimpleLDAPObject.search_ext
> (('ou=people,dc=utm,dc=edu,dc=ec',
> 2,
> '(uid=user0)',
> None,
> 0,
> None,
> None,
> -1,
> 0),
> {})
> => result:
> 2
> *** <ldap.ldapobject.SimpleLDAPObject object at 0x7fb2224af9b0> ldap://127.0.0.1:3268 - SimpleLDAPObject.result4
> ((2, 1, -1, 0, 0, 0), {})
> => result:
> (101,
> [('uid=user0,ou=people,dc=utm,dc=edu,dc=ec',
> {'cn': [b'user0'],
> 'gn': [b'John'],
> 'objectClass': [b'organizationalPerson', b'person', b'zimbraAccount'],
> 'sn': [b'Doe'],
> 'uid': [b'user0'],
> 'userPassword': [b'terces'],
> 'zimbraAccountStatus': [b'active'],
> 'zimbraId': [b'112']})],
> 
> so we can see what fails, the admin login, the user details query, or the user password check

Done, where is supposed to show the outputs, because everything remains the same.

> I tried to set up a schema like ( I think it could be) yours. It worked for me.
> dn: dc=edu,dc=ec
> dc: ec
> objectClass: dcObject
> 
> dn: dc=utm,dc=edu,dc=ec
> dc: zimbra
> objectClass: dcObject
> objectClass: organization
> 
> dn: ou=people,dc=utm,dc=edu,dc=ec
> objectClass: organizationalUnit
> ou: people
> 
> dn: cn=root,dc=utm,dc=edu,dc=ec
> cn: root
> gn: root
> mail: [admin@calibreweb.com](mailto:admin@calibreweb.com)
> objectclass: top
> objectclass: person
> objectClass: zimbraAccount
> zimbraAccountStatus: active
> zimbraId: 111
> sn: admin
> userPassword: secret
> 
> dn: uid=[user0@we.de](mailto:user0@we.de),ou=people,dc=utm,dc=edu,dc=ec
> objectClass: person
> objectClass: organizationalPerson
> objectClass: zimbraAccount
> uid: [user0@we.de](mailto:user0@we.de)
> cn: user0
> gn: John
> sn: Doe
> zimbraAccountStatus: active
> zimbraId: 112
> userPassword: terces

With this example the values on app configuration should be?

**Comment by OzzieIsaacs** [comment]
Done, where is supposed to show the outputs, because everything remains the same.
-> then you got the wrong file. It's possible that flask-simpleldap is installed multiple times (python site-packages, users site-packages, venv folder).
How did you install flask-simpleldap?

Values:
LDAP Base DN: dc=utm,dc=edu,dc=ec
LDAP SERVER: Server IP
LDAP Admin DN: cn=root,dc=utm,dc=edu,dc=ec
PASSWORD LDAP:secret
config_ldap_user_object: (uid=%s)
Username is user0@we.de

Remark: I'm not using OpenLDAP, or zimbra, I'm using ldaptor a python, it's a multipurpose server, and I'm using it to run my tests with it, I can easily exchange all configuration data, it's nothing for productive use.

If you share this schema stuff with me, I can try to reproduce the problem.

**Comment by Kuroburn** [comment]
> Done, where is supposed to show the outputs, because everything remains the same.
> -> then you got the wrong file. It's possible that flask-simpleldap is installed multiple times (python site-packages, users site-packages, venv folder).
> How did you install flask-simpleldap?

Already checked all the possible folders and nothing appears, I installed flask-simpleldap from optional-requierements.txt
 
> Values:
> LDAP Base DN: dc=utm,dc=edu,dc=ec
> LDAP SERVER: Server IP
> LDAP Admin DN: cn=root,dc=utm,dc=edu,dc=ec
> PASSWORD LDAP:secret
> config_ldap_user_object: (uid=%s)
> Username is [user0@we.de](mailto:user0@we.de) and password is terces
> 
> Remark: I'm not using OpenLDAP, or zimbra, I'm using ldaptor a python, it's a multipurpose server, and I'm using it to run my tests with it, I can easily exchange all configuration data, it's nothing for productive use.
> 
> If you share this schema stuff with me, I can try to reproduce the problem.

Get the schema is the big problem, I can't get it...

**Comment by OzzieIsaacs** [comment]
Please start python (the same python command you use to start calibre-web, with the same user) from a console, without any parameter. (like `python3`, in my case it's ./venv/bin/python3)
You should get something like this:
![grafik](https://user-images.githubusercontent.com/6438895/85917053-190a6a80-b857-11ea-86e0-50dc88ca1c30.png)
then please type (like in the screenshot):
`import flask_simpleldap`
`flask_simpleldap.__file__`
It should output the folder with the file imported as flask_simpleldap. Please apply the patch I mentioned above to this file. (You can quit python by typing `quit()`)
Just to be sure (as this is one reason for not getting any output). The user you try to log in from calibre-web is present in calibre-web? You created a user with the same login name as you try to log in via LDAP in calibre-web, right? (I know I already asked it, I just want to make it sure, please check it again)

**Comment by Kuroburn** [comment]
> Please start python (the same python command you use to start calibre-web, with the same user) from a console, without any parameter. (like `python3`, in my case it's ./venv/bin/python3)
> You should get something like this:
> ![grafik](https://user-images.githubusercontent.com/6438895/85917053-190a6a80-b857-11ea-86e0-50dc88ca1c30.png)
> then please type (like in the screenshot):
> `import flask_simpleldap`
> `flask_simpleldap.__file__`
> It should output the folder with the file imported as flask_simpleldap. Please apply the patch I mentioned above to this file. (You can quit python by typing `quit()`)

After type import flask_simpleldap returns _ModuleNotFoundError: No module named 'flask_simpleldap'_

> Just to be sure (as this is one reason for not getting any output). The user you try to log in from calibre-web is present in calibre-web? You created a user with the same login name as you try to log in via LDAP in calibre-web, right? (I know I already asked it, I just want to make it sure, please check it again)

No, I'm using de fallback login with my admin user that doesn't exists in my work's LDAP.

**Comment by OzzieIsaacs** [comment]
Okay: 
Please type the command python on the machine running calibre-web. 
What do you type to start calibre-web?

**Comment by Kuroburn** [comment]
> Okay:
> Please type the command python on the machine running calibre-web.
> What do you type to start calibre-web?

I'm in the machine running calibre-web... I use this [method](https://github.com/janeczku/calibre-web/wiki/Setup-Service-on-Linux) from wiki.

**Comment by OzzieIsaacs** [comment]
Please stop the service (best would be logging in to calibre-web and press the shutdown button in the admin section). Please check afterwards that calibre-web isn't running anymore (by tring to reload the page in the webbrowser). If it's still running get it to stop (sudo systemctl servicename stop would work in ubuntu, centos I don't know)
I have the feeling you never got it to reload

**Comment by OzzieIsaacs** [comment]
After it's stopped please run the python command you entered in the unit file (the files you linked in your post)

**Comment by OzzieIsaacs** [comment]
please use the user you used in the file to start python

**Comment by Kuroburn** [comment]
> After it's stopped please run the python command you entered in the unit file (the files you linked in your post)

which files?

**Comment by OzzieIsaacs** [comment]
You linked the wiki entry for starting a service. To do this you created a file with the content like in the wiki. In the wiki the file has some variables in it:
User={Username}
ExecStart={path to python}
I'd like you to use exact the same user and python path as in this file. 
(I have one idea what's happening)

**Comment by OzzieIsaacs** [comment]
If you now still get the import error, please go to the root folder of calibre-web (the folder with the cps file in it and the vendor folder as sub folder) and start the python program again without any parameter. type:
`from vendor import flask_simpleldap`
`flask_simpleldap.__file__`
th result should now be the file name `.../vendor/flask_simpleldap/__init__.py'`

**Comment by OzzieIsaacs** [comment]
Now please start calibre-web from the console you are now in, and try to login with the user from the ldap server. You should now see the output on the console

**Comment by Kuroburn** [comment]
> from vendor import flask_simpleldap



> If you now still get the import error, please go to the root folder of calibre-web (the folder with the cps file in it and the vendor folder as sub folder) and start the python program again without any parameter. type:
> `from vendor import flask_simpleldap`
> `flask_simpleldap.__file__`
> the result should now be the file name `.../vendor/flask_simpleldap/__init__.py'`

I get this error now _ModuleNotFoundError: No module named 'ldap'_

**Comment by OzzieIsaacs** [comment]
Please start calibre-web from the console python3 cps.py, log in to calibre-web with your admin account and go to the about/stats section and search for these entries:
![grafik](https://user-images.githubusercontent.com/6438895/85917656-59201c00-b85c-11ea-938e-6ebf762df2f3.png)

**Comment by Kuroburn** [comment]
> Please start calibre-web from the console python3 cps.py, log in to calibre-web with your admin account and go to the about/stats section and search for these entries:
> ![grafik](https://user-images.githubusercontent.com/6438895/85917656-59201c00-b85c-11ea-938e-6ebf762df2f3.png)

got both, but python_LDAP es 3.2.0

**Comment by OzzieIsaacs** [comment]
okay should be fine

**Comment by OzzieIsaacs** [comment]
You said you changed the \_\_init\_\-.py file in ./vendor/flask_simpleldap. I'm almost convinced that it was the right one. If you now try to log in with the ldap user, do you see some output?

**Comment by Kuroburn** [comment]
> You said you changed the __init_-.py file in ./vendor/flask_simpleldap. I'm almost convinced that it was the right one. If you now try to log in with the ldap user, do you see some output?

Yes... but this is weird... when I log in with my fallback login I got the output in console... but when I try to log in with my LDAP credentials nothing happens on console.

**Comment by OzzieIsaacs** [comment]
Calibre-web is checking if the user is existing in it's database, if yes and ldap is activated it tries to login via ldap. If the user is not in database no login attempt with ldap is tried. 
(I'm still not convinced you are having the ldap user in your calibre-web database).
I'd like to see the console output of the login attempt (you can delete the passwords and also parts of the username). I also like to see a screenshot of the admin section with the user you are trying to log in.
I fidles a bit with the ldapsearch command:
ldapsearch -H ldap://my-computer.com -D "cn=root,dc=calibreweb,dc=com" -w <root-passwort> -b 'dc=calibreweb,dc=com' '(objectclass=*)'
or
ldapsearch -H ldap://my-computer.com -D "cn=root,dc=calibreweb,dc=com" -w <root-passwort> -b 'dc=calibreweb,dc=com' '(cn=*)'
Should output the ldap structure. Could you please send it to me ( the short version with only one user and the admin, without passwords would be enough) (via e-mail on my profile page)

**Comment by Kuroburn** [comment]
> Calibre-web is checking if the user is existing in it's database, if yes and ldap is activated it tries to login via ldap. If the user is not in database no login attempt with ldap is tried.
> (I'm still not convinced you are having the ldap user in your calibre-web database).

Wait a minute... I need to register the user from the LDAP on the app? confirm this because if true obviusly I only had the admin user registered on the app, and no other users.

**Comment by OzzieIsaacs** [comment]
Arrrrr
Yes, (this is the purpose of the import users button)
Every user which shall be allowed to log in to calibre-web needs to have an account in calibre.web (for saving the visibility, access rights and so on)

**Comment by Kuroburn** [comment]
> Arrrrr
> Yes, (this is the purpose of the import users button)
> Every user which shall be allowed to log in to calibre-web needs to have an account in calibre.web (for saving the visibility, access rights and so on)

Since I cannot login with ldap I never try to import users because a got the error posted on the first screenshots... let me see if I can import now the users.

**Comment by Kuroburn** [comment]
UPDATE; LDAP is already working, apparently the problem was always that it had never applied the configurations since it always assumed that when saving the configurations the respective restart of the service was carried out.

The problem I have now is that in my work they don't have groups defined inside the LDAP server and talking to the IT guy he told me that it is problematic to create groups inside the zimbra's ldap server.

Is there a way to import users without defining groups?

**Comment by OzzieIsaacs** [comment]
Sorry, I forgot to answer. I#m sorry, this is not possible, as Calibre-Web requests a group record, this record has a link to all users. So if the group "record" is not present, it's not possible to import the users. How many users are we talking about? (Maybe a bash/python script would do the job?)

**Comment by Kuroburn** [comment]
> Sorry, I forgot to answer. I'm sorry, this is not possible, as Calibre-Web requests a group record, this record has a link to all users. So if the group "record" is not present, it's not possible to import the users. How many users are we talking about? (Maybe a bash/python script would do the job?)

Don't worry, I know this things takes time. Around ~1.1k users... 
I assumed that the groups on the ldap server would have to be that way, so just enable registration in the application.
If there's a way through a script I would appreciate trying.
After your next answer I proceed to close the report.

**Comment by OzzieIsaacs** [comment]
Here we go:
Unzip zip file in this comment, to a random folder
Please make sure that "requests" is installed (e.g. via `pip3 install requests`)
Open the import.py file with the text editor of you choice
Please change the parameters on top of the file with your data for calibre-web:
ADMIN = Administrator username of calibre-web
ADMIN_PASSWORD = admin password
ADDRESS = Address and port to connect to calibre-web instance
USER_LANGUAGE = default language of newly created users (es = spanish, en=english). Valid language codes can be found in the foldernames of calibre-web in the following folder `calibre-web/cps/translations` 
USER_FILE = filename of a file containing all usernames with a email address (username and email address have to be unique). Username and emailadress have to be seperated by ";" and no additional whitespace in between. 
Save your changes.
Start calibre-web
Run the script by excecuting e.g. `python3 import.py`
Wait for the magic to happen
For each user created a text line is output, In case something is wrong with a text line this is also output.
The script has almost no error handling. It waits after each request 1second, to not run into some timing issues. The wait time could be reduced in line 38, by changing the number 1 to something smaller (e.g. 0.1) or bigger (e.g. 3). 
Afterwards, or during the import the progress could be watched in a browser (by refreshing the admin page)

[import.zip](https://github.com/janeczku/calibre-web/files/4892565/import.zip)

**Comment by Kuroburn** [comment]
Thanks for the help, I going to try the script and let you know how it goes... I will keep the report open to report the process.

**Comment by Kuroburn** [comment]
> Here we go:
> Unzip zip file in this comment, to a random folder
> Please make sure that "requests" is installed (e.g. via `pip3 install requests`)
> Open the import.py file with the text editor of you choice
> Please change the parameters on top of the file with your data for calibre-web:
> ADMIN = Administrator username of calibre-web
> ADMIN_PASSWORD = admin password
> ADDRESS = Address and port to connect to calibre-web instance
> USER_LANGUAGE = default language of newly created users (es = spanish, en=english). Valid language codes can be found in the foldernames of calibre-web in the following folder `calibre-web/cps/translations`
> USER_FILE = filename of a file containing all usernames with a email address (username and email address have to be unique). Username and emailadress have to be seperated by ";" and no additional whitespace in between.
> Save your changes.
> Start calibre-web
> Run the script by excecuting e.g. `python3 import.py`
> Wait for the magic to happen
> For each user created a text line is output, In case something is wrong with a text line this is also output.
> The script has almost no error handling. It waits after each request 1second, to not run into some timing issues. The wait time could be reduced in line 38, by changing the number 1 to something smaller (e.g. 0.1) or bigger (e.g. 3).
> Afterwards, or during the import the progress could be watched in a browser (by refreshing the admin page)
> 
> [import.zip](https://github.com/janeczku/calibre-web/files/4892565/import.zip)

Thanks for the help, I going to try the script and let you know how it goes ... I will keep the report open to report the process.

**Comment by OzzieIsaacs** [comment]
No feedback for long time
