### ISSUE TITLE
ability to set listen address in configuration

### ISSUE THREAD

**Issue by ch604** [janeczku/calibre-web#1505]
calibre-web is currently set up to listen to 0.0.0.0 by default (in cps/server.py), unless the config_ipaddress variable is set in the sqlite3 database. however, the default schema for this settings table does not include such a configuration option, nor are you able to set this up through the gui.

I would like to set my calibre-web install to only listen on 127.0.0.1 instead, as I intend to proxy it, for security's sake. i know that closing the port in the firewall is probably sufficient, but its still not useful to reference a configuration variable that can never be set.

**Comment by OzzieIsaacs** [comment]
There is a command line option to restrict the access: https://github.com/janeczku/calibre-web/wiki/Command-Line-Interface#command-line-options (-i)

**Comment by ch604** [comment]
oop; thanks! that should provide what i need without code changes.
