### ISSUE TITLE
[Bug] No graceful shutdown of server

### ISSUE THREAD

**Issue by epsilon-0** [janeczku/calibre-web#1506]
**Describe the bug/problem**
Process does not die even when pressing `Ctrl + C`

**To Reproduce**
1. Start calibre-web: `python3.7 cps.py`
2. Wait a few seconds
3. Press `Ctrl + C`
4. Nothing happens
5. Have to kill using `pkill -9` (which is ugly and prone to misuse)

**Logfile**
```
[2020-06-25 20:10:55,633]  INFO {cps:98} Starting Calibre Web...
[2020-06-25 20:10:55,711]  INFO {cps.server:156} Starting Tornado server on :8083
```

**Expected behavior**
The tornado server should shut down gracefully.

**Environment (please complete the following information):**
 - OS: OpenBSD 6.7
 - Python version: Python 3.7
 - Calibre-Web version: 0.6.8 (release tarball)
 - Docker container: None
 - Special Hardware: None
 - Browser: Firefox 77.0.1

**Additional context**
I think this might be happening due to the tornado server being in a separate thread(!?). 
Am not even sure if that is the issue...

**Comment by OzzieIsaacs** [comment]
I just checked it. On Linux Mint it's working (and I think also on Windows last time I checked it).
Tornado isn't running in a separate thread it's the updater, the database and the converter/emailer running in threads. 
Before the shutdown commando to tornado is send, those threads are stopped and the message `webserver stop (restart=false)` is logged. I don't see this message in your log. So I think the Ctrl+c signal (SIGINT) isn't received by calibre-web. 
To prove this theory, could you please try to stop calibre-web from the webinterface (admin section stop button in the lower half of the page). This should at least outputting the message in the logfile.
One additional questions: Which version of tornado did you install (visible in the about/stats section)

**Comment by epsilon-0** [comment]
Tornado version - 5.1.1

Even after shutting down from the admin interface, it does not do anything. There is no output to the file and the server is still running.

**Comment by OzzieIsaacs** [comment]
Oka! This means the shutdown Stucks in stopping the threads. I‘m downloading a openbsd and try to reproduce it in a virtual machine

**Comment by epsilon-0** [comment]
thank you so much !

**Comment by OzzieIsaacs** [comment]
1 hour later, I have one experience more: OpenBSD is harder to install than "modern linux", but runs calibre-web without any problem.
So what I did: I installed the iso image from openbsd 6.7 from the openbsd website. Installed it in Oracle VirtualBox. After inital startup I installed xfce desktop environment (editied .xsession file and added startxfce command), restarted, logged in as user. Opened a terminal. Installed py3-pip as root (python 3.7. was installed during installation of desktop environment). Installed virtualenv as root via pip. Installed all required dependencies in virtual environment. started it in the terminal as root, started it as normal user (after changing the folder and file ownership), 
pressed ctrl+c -> stopped (using german keyboard layout) 
pressed restart in UI -> restarted
pressed stop in UI -> stopped
![grafik](https://user-images.githubusercontent.com/6438895/85860371-fd538580-b7be-11ea-8e59-90c382a0a01c.png)

The only difference I see is, I used tornado 6.04. 
Further Question: If you change the database location/log level is calibre-web restarting in the background?
![grafik](https://user-images.githubusercontent.com/6438895/85860664-6e933880-b7bf-11ea-8d62-45b83f090c01.png)

**Comment by epsilon-0** [comment]
OK, let me try in a `virtualenv`
I'm currently packaging this for OpenBSD so I was using the packages provided by the system manager, which are very outdated.

**Comment by epsilon-0** [comment]
OK, so in a `virtualenv` I can get the proper UI for calibre-web and is working well. 
But when I press `Ctrl + C` it takes really long to stop.
Furthermore, I got this error: 
```
^C^C^C^C^C^C^C^C^C^C^C^C^Csys:1: RuntimeWarning: coroutine 'HTTP1ServerConnection._server_request_loop' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by epsilon-0** [comment]
Ah, this was on `0.6.7` instead of the one you are testing `0.6.9-Beta`.
On `0.6.7` I was able to shutdown and restart properly from the UI, though the command line still had that bug.

I have come to the conclusion its due to the old broken dependencies in the OS package manager.
WIll fix those as well, when making this port!!

Thanks a lot for your work!
