### ISSUE TITLE
Deleting book fails

### ISSUE THREAD

**Issue by julzKB** [janeczku/calibre-web#1512]
Deleting books fails complaining about subfolders, it used to work fine, because updating my docker image .

for example :

`Deleting book 8026 failed, path has subfolders: Charles Dickens/Barnabe Rudge - Tome II (8026)`

Is there somewhere I should be looking into, deleting books with that tree structure never caused any issue in the past , this is using version : 

0.6.8
--

**Comment by OzzieIsaacs** [comment]
I changed the behaviour, to not accidentally delete files/folder which are belonging to something else. Please check the folder, there should be an additional subfolder in it.

**Comment by julzKB** [comment]
I checked the folder, but there are no subfolders in it, it's just the default way Calibre has imported my books, here is what the directory structure looks like :

<img width="372" alt="Screen Shot 2020-07-03 at 8 47 18 AM" src="https://user-images.githubusercontent.com/831656/86407843-eaced400-bd09-11ea-8e36-aadf28d1c1e4.png">

Same goes for every other book I'm trying to delete, they all share the same directory structure with no subfolders at the book file level .

Could I suggest that we have a switch in the options to revert back to the previous behaviour ? Right now i'm unable to delete any book :)

Thanks !

**Comment by OzzieIsaacs** [comment]
Can't reproduce it. I changed the bahavior, the book files are deleted, a warning message is shown on the gui, beside the delete success message and also an additional error message is logged, showing which path are causing the trouble

**Comment by julzKB** [comment]
nice, one, I'll test it as soon as there is a new docker build . Thanks !
