### ISSUE TITLE
[Enhancement] Order shelf by x, y, z

### ISSUE THREAD

**Issue by cbartondock** [janeczku/calibre-web#1518]
Problem: Manually re-ordering shelves should not be the only way to do so. It is difficult and time consuming.

Ideal solution: Buttons to order shelf by author name, title, last opened. Similar to what is available in "Recently added" but for individual shelves.

Thanks for the great software!

**Comment by UKLibrarian** [comment]
Agreed - for the way I use it, this is the only significant feature missing from the software. Apart from this, it makes my life very easy.

**Comment by cbartondock** [comment]
It seems this has been added! Closing
