### ISSUE TITLE
issue with create service under Linux with systemd

### ISSUE THREAD

**Issue by skyforce97809** [janeczku/calibre-web#1519]
My /etc/systemd/system/cps.service 

> [Unit]
> Description=Calibre-Web
> 
> [Service]
> Type=simple
> User=skyforce
> ExecStart=/usr/bin/python3 /home/skyforce/calibre-web-0.6.8/cps.py
> WorkingDirectory=/home/skyforce/calibre-web-0.6.8
> 
> [Install]
> WantedBy=multi-user.target
> 

![cps service](https://user-images.githubusercontent.com/32296261/86586972-dd2f7d80-bf99-11ea-9820-1254afeff993.jpg)

-----------
The Logs
root@mamrafoelab01:/etc/systemd/system# systemctl enable cps.service
root@mamrafoelab01:/etc/systemd/system# systemctl start cps.service
root@mamrafoelab01:/etc/systemd/system# systemctl status cps.service

>  ● cps.service - Calibre-Web
> 
>      Loaded: loaded (/etc/systemd/system/cps.service; enabled; vendor preset: enabled)
>      Active: failed (Result: exit-code) since Mon 2020-07-06 10:34:29 UTC; 6s ago
>     Process: 3671 ExecStart=/usr/bin/python3 /home/skyforce/calibre-web-0.6.8/cps.py (code=exited, status=1/FAILURE)
>   
> 
> Main PID: 3671 (code=exited, status=1/FAILURE)
> 
> Jul 06 10:34:29 mamrafoelab01 systemd[1]: Started Calibre-Web.
> 
> Jul 06 10:34:29 mamrafoelab01 python3[3671]: Traceback (most recent call last):
> Jul 06 10:34:29 mamrafoelab01 python3[3671]:   File "/home/skyforce/calibre-web-0.6.8/cps.py", line 34, in <module>
> Jul 06 10:34:29 mamrafoelab01 python3[3671]:     from cps import create_app
> Jul 06 10:34:29 mamrafoelab01 python3[3671]:   File "/home/skyforce/calibre-web-0.6.8/cps.py", line 34, in <module>
> Jul 06 10:34:29 mamrafoelab01 python3[3671]:     from cps import create_app
> Jul 06 10:34:29 mamrafoelab01 python3[3671]: ImportError: cannot import name 'create_app' from partially initialized module 'cps' (m>
> Jul 06 10:34:29 mamrafoelab01 systemd[1]: cps.service: Main process exited, code=exited, status=1/FAILURE
> Jul 06 10:34:29 mamrafoelab01 systemd[1]: cps.service: Failed with result 'exit-code'.
> lines 1-15/15 (END)

**Comment by skyforce97809** [comment]
![cps service](https://user-images.githubusercontent.com/32296261/86585321-5b3e5500-bf97-11ea-8c9a-fb1cf02b0fb6.jpg)
cps.service file

**Comment by OzzieIsaacs** [comment]
For me it‘s working. I created an issue template for providing essential information. With the information you provided I can‘t do anything for you
