### ISSUE TITLE
Calibre ebook-convert.exe yields [WinError 193] %1 is not a valid Win32 application on Windows 10 64-bit

### ISSUE THREAD

**Issue by cbartondock** [janeczku/calibre-web#1520]
Just attempted to send something to kindle and discovered this bug. In my "About" page I see the error "Executable permissions missing" for "ebook converter." I spent a while chasing this error until I read the log and discovered it was highly misleading. The log gives the error:
`ERROR {cps.worker:564} Ebook-converter failed: [WinError 193] %1 is not a valid Win32 application`

My path for the ebook converter is `C:\Program Files\Calibre2\ebook_convert.exe`. The file exists and works when used independently. I tried switching to the 32 bit version of Calibre, and the 32 bit version of python, and both. No luck.

Any help would be welcome! I suspect it is a 32bit/64bit issue but I could be off.

**Comment by cbartondock** [comment]
I found the bug. It's in `subproc_wrapper.py`. In the version of python I am using (python 3.7), the `subproces.Popen` command expects a list of arguments rather than a string. Setting `exc_command=[x for x in command]` solves the problem. Please implement fix.

**Comment by cbartondock** [comment]
After trying this fix I know have the correct version, etc showing up in the About section but am seeing the following in the log
```
[2020-07-06 16:51:43,845]  INFO {cps.worker:346} ebook converter failed with error while converting book
[2020-07-06 16:51:43,846] ERROR {cps.worker:565} Ebook converter failed with unknown error
```

**Comment by cbartondock** [comment]
Annnnnd fixed. The quotation stuff where you add in extra quotes appeared to be the problem. My subprocess_wrapper.py process_open method now looks like

```
def process_open(command, quotes=(), env=None, sout=subprocess.PIPE, serr=subprocess.PIPE, newlines=True):
    if os.name == 'nt':
        exc_command = [x for x in command]
    ... Linux handling
```

And this works fine. Not sure where in windows/python versions the old way got borked, so I hesitate to submit a PR, but this was the fix for me.

**Comment by OzzieIsaacs** [comment]
For me it's working, as I don't know which python version you are using and which calibre version, I don't want to change it.
 If you don't mind sharing this information at least, I can try to reproduce it:
![grafik](https://user-images.githubusercontent.com/6438895/86817813-d847f800-c085-11ea-85a9-b17a60e333b6.png)

**Comment by cbartondock** [comment]
Sure thing:

![Capture](https://user-images.githubusercontent.com/4482454/86942057-b2b50000-c112-11ea-99be-83d6d123351e.PNG)

**Comment by cbartondock** [comment]
But actually I have tried several different python versions, I was having the same issue on 3.72
