### ISSUE TITLE
[Windows] Fails to send to kindle when running docker

### ISSUE THREAD

**Issue by andysom25** [janeczku/calibre-web#1522]
**Describe the bug/problem**
I currently just run calibre-web via powershell by calling the cps.py file to run. 
I have noticed if I have Docker running on that machine, my send to kindle emails will fail. 

**To Reproduce**
1. run calibre web
2. run docker desktop
3. attempt to send to kindle 

**Logfile**
[2020-07-09 14:16:26,746]  INFO {cps:98} Starting Calibre Web...
[2020-07-09 14:16:27,280]  INFO {cps.server:156} Starting Tornado server on :8083
[2020-07-09 14:17:15,013] ERROR {cps.worker:564} Socket Error sending email: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python version: Python 3.8.3
 - Calibre-Web version: 0.6.8
 - Docker container: None
 - Special Hardware: None
 - Browser: Chrome

**Comment by OzzieIsaacs** [comment]
I checked for me it's working. In my opion the reason is very obvios: Docker or a docker container is blocking the port you are using to send the email. There is nothing I can do from my side.

**Comment by andysom25** [comment]
> I checked for me it's working. In my opion the reason is very obvios: Docker or a docker container is blocking the port you are using to send the email. There is nothing I can do from my side.

I'll have to confirm this as I had no containers running, and by default docker usually only uses port 80.. and the emails from calibre web are going out on 8083

**Comment by OzzieIsaacs** [comment]
Calibre-Web's email will go out on the port you configure in the email settings.

**Comment by OzzieIsaacs** [comment]
I have to correct myself, it's not the port which is blocked, it's the ip-address, or socket, where calibre-web can't connect to (according to the error message)

**Comment by andysom25** [comment]
> I have to correct myself, it's not the port which is blocked, it's the ip-address, or socket, where calibre-web can't connect to (according to the error message)

Right, I was thinking port 465 in my case for sending via Gmail would not need to change ? 
Wonder what docker is doing by default that would cause it not the be able to connect

**Comment by OzzieIsaacs** [comment]
I don't know. I did a fresh docker desktop installation rebooted. Waited after windows startup till this docker messages pop up and started calibre-web. Worked without any trouble
