### ISSUE TITLE
Option to open books in a new page instead of loading a java script pop-up

### ISSUE THREAD

**Issue by ghost** [janeczku/calibre-web#1524]
**Is your feature request related to a problem? Please describe.**
It is not possible to download books from Kindle's built-in browser because it is unable to render the pop-up when you tap a book's cover.

**Describe the solution you'd like**
This project says "This software is a fork of library and licensed under the GPL v3 License" in the main page so I went ahead and installed Library to see if Kindle's browser can handle it. Yes, it can, because Library loads book information and download links in a new page instead of relying on JavaScript. This could be an optional feature available in the settings to maintain the original design for those who prefer it.

Like the screenshot below, Kindle's experimental browser can download from that page:
![2020-07-12 (1)](https://user-images.githubusercontent.com/29753260/87250938-a5638280-c43e-11ea-86c8-090789ec002c.png)

But this, as it Calibre-Web currently does, won't load on Kindle's browser:
![2020-07-12 (2)](https://user-images.githubusercontent.com/29753260/87251094-8a454280-c43f-11ea-8215-c85a09eb1eb5.png)

**Comment by contributor** [comment]
Open a book in new page instead of popup is must-have feature. This will make a book page bookmark-able in a browser, you can't do this in a popup which doesn't have distinct URL

**Comment by florianjacob** [comment]
Those individual book pages already exist, try `://<calibre-web>/book/1` - where 1 is the calibre book identifier. Those pages are however are only used in the "simple" theme, which is enabled when the user agent of the browser is one of a known ebook reader device. Kindle is already present, so there *should* be no modal popup on kindle.

* issue: https://github.com/janeczku/calibre-web/issues/1569
* user agent detection code: https://github.com/janeczku/calibre-web/blob/e7464f26948bc6695b99de5420fc035e5ba6b12b/cps/render_template.py#L32

**Comment by OzzieIsaacs** [comment]
@florianjacob : thanks for pointing to this issue, it is indeed fixed since one or 2 month, please update to the newest version
