### ISSUE TITLE
Error opening eBook. File does not exist or file is not accessible

### ISSUE THREAD

**Issue by nieroivan** [janeczku/calibre-web#1525]
Hi.

 I've try everything but it seems impossible to upload a book on my calibre-web in my synology NAS (without docker). I installed all the items on requirements.txt with no errors and the issue persists. I also try to install the optional requirements, but I still got the same issue.

The progress bar goes until the end and then I get the error: _Error opening eBook. File does not exist or file is not accessible_

The permissions on my book folder where the metadata is also stored and where the calibre-web is storead are set R/W for all types of users and groups.

**To Reproduce**
1. Log in in the app
2. click on upload
3. select a book
4. upload

**Logfile**
[2020-07-12 23:17:23,564]  INFO {cps:98} Starting Calibre Web...
[2020-07-12 23:17:24,828]  INFO {cps.server:156} Starting Tornado server on :8091
[2020-07-12 23:17:34,491] DEBUG {cps.web:1432} You are now logged in as: 'nieroivan'
[2020-07-12 23:17:48,676] DEBUG {cps.uploader:203} Temporary file: /tmp/calibre_web/0dbd3889bf9716b993c7e41a9a878782

**Environment (please complete the following information):**
 - OS: DSM 6.2.3-25426
 - Python version: python 2.7 and python 3 (I tested on both versions)
 - Calibre-Web version: 0.6.8
 - Docker container: None
 - Special Hardware: Synology ds218j
 - Browser: Chrome

**Comment by OzzieIsaacs** [comment]
I can't reproduce it (I don't have a Syncology NAS and for me it's working)

**Comment by OzzieIsaacs** [comment]
Could you please check if the file is still there after the upload: /tmp/calibre_web/0dbd3889bf9716b993c7e41a9a878782
Is the book listed in the database (means you see at least an empty cover and some maybe random author and title)?

**Comment by nieroivan** [comment]
For some reason, the folder calibre_web didn't exist. I created it, gave
all the permissions, repeated the upload process, and got the same error.


Em ter., 21 de jul. de 2020 às 13:19, Ozzie Isaacs <notifications@github.com>
escreveu:

**Comment by OzzieIsaacs** [comment]
The folder is supposed to get deleted after upload, so this is a valid result.
Is the book visible in calibre-web?

**Comment by nieroivan** [comment]
No. After the error, I cannot find it.

---
Ivan Niero Miranda


Em ter., 21 de jul. de 2020 às 15:19, Ozzie Isaacs <notifications@github.com>
escreveu:

**Comment by OzzieIsaacs** [comment]
Is it happening with every book, or only with a certain one. Do other bookformats, like ePub, pdf, txt also create the error?

**Comment by nieroivan** [comment]
I think it's with every book. I try to upload an epub, mobi and a pdf and
got the same error.

It's really strange that the log doesn't show the error that I got on
screen.

---
Ivan Niero Miranda


Em ter., 21 de jul. de 2020 às 15:37, Ozzie Isaacs <notifications@github.com>
escreveu:

**Comment by OzzieIsaacs** [comment]
Do you have visibility restrictions applied? The user can only see books with tag "A"? Are the books visible in the folder structure of your hard drive?

**Comment by nieroivan** [comment]
All the tests were made with an admin user.

 I changed all the permissions of all folders that is related to it to full
access (read, modify and write).

Regarding the last question, you're referring to the book that I just
uploaded or the other books on my library? If it's the book that I just
uploaded the answer is no.. it didn't show anywhere. For all other books,
everything is visible.

---
Ivan Niero Miranda


Em qua., 22 de jul. de 2020 às 14:15, Ozzie Isaacs <notifications@github.com>
escreveu:

**Comment by hrxfab** [comment]
I have the same issue. 
I was able to upload books 2 weeks ago, and now its not working.
Permissions are correct on the /tmp/calibreweb folder.

**Comment by nieroivan** [comment]
Hi. Any news on it?
@hrxfab did you manage a way to solve this issue?

**Comment by hrxfab** [comment]
Hi @nieroivan 

I did, by switching from the master chanel to the nightly.
I believe this was patched someway.

**Comment by nieroivan** [comment]
Do you mind to explain to me how did you do that? I'm a bit newbie on it. :|

---
Ivan Niero Miranda

**Comment by hrxfab** [comment]
Sure, you simpy have to change in the parameter page -> main config -> server config -> the update channel from master to nightly. (not sure that the names are exact as I don't have the interface configured in english)

However, since yestededay it does not work anymore. Problem is not solved then.

**Comment by nieroivan** [comment]
Hi. I'm using python 3 now to run the cps.py and the error is showing as follow:

Failed to Move Cover File /volume2/livros_new/Unknown/Historia da Menina Perdida - Elena Ferrante/cover.jpg: [Errno 2] No such file or directory: '/volume2/livros_new/Unknown/Historia da Menina Perdida - Elena Ferrante/cover.jpg'
Rename title from: '/tmp/calibre_web/0dbd3889bf9716b993c7e41a9a878782' to '/volume2/livros_new/Unknown/Historia da Menina Perdida - Elena Ferrante (7814)' failed with error: [Errno 18] Invalid cross-device link: '/tmp/calibre_web/0dbd3889bf9716b993c7e41a9a878782' -> '/volume2/livros_new/Unknown/Historia da Menina Perdida - Elena Ferrante (7814)/Historia da Menina Perdida - Elena Ferrante.mobi

Any idea?

**Comment by nieroivan** [comment]
Hi. I just did a clean install (even reinstalled Python) and now works flawless. 👍 

Probably it was something that I mess during the first installation.
