### ISSUE TITLE
500 Internal Server Error after update

### ISSUE THREAD

**Issue by kaipee** [janeczku/calibre-web#1530]
**Describe the bug/problem**
Last night I updated calibre-web from 0.6.6 to 0.6.8 and it seemed to run fine. Today I logged in and am presented with an '500 Internal server erro' - login screen does show OK.

**To Reproduce**
1. Login

**Logfile**

> Traceback (most recent call last):
> File "/opt/calibre-web/vendor/flask/app.py", line 2446, in wsgi_app
> response = self.full_dispatch_request()
> File "/opt/calibre-web/vendor/flask/app.py", line 1951, in full_dispatch_request
> rv = self.handle_user_exception(e)
> File "/opt/calibre-web/vendor/flask/app.py", line 1820, in handle_user_exception
> reraise(exc_type, exc_value, tb)
> File "/opt/calibre-web/vendor/flask/_compat.py", line 39, in reraise
> raise value
> File "/opt/calibre-web/vendor/flask/app.py", line 1949, in full_dispatch_request
> rv = self.dispatch_request()
> File "/opt/calibre-web/vendor/flask/app.py", line 1935, in dispatch_request
> return self.view_functions[rule.endpoint](**req.view_args)
> File "/opt/calibre-web/cps/web.py", line 201, in decorated_view
> return login_required(func)(*args, **kwargs)
> File "/opt/calibre-web/vendor/flask_login/utils.py", line 272, in decorated_view
> return func(*args, **kwargs)
> File "/opt/calibre-web/cps/web.py", line 623, in index
> entries, random, pagination = calibre_db.fill_indexpage(page, db.Books, True, [db.Books.timestamp.desc()])
> File "/opt/calibre-web/cps/db.py", line 511, in fill_indexpage
> return self.fill_indexpage_with_archived_books(page, database, db_filter, order, False, *join)
> File "/opt/calibre-web/cps/db.py", line 525, in fill_indexpage_with_archived_books
> .filter(self.common_filters(allow_show_archived))
> File "/opt/calibre-web/cps/db.py", line 490, in common_filters
> negtags_list = current_user.list_denied_tags()
> File "/opt/calibre-web/cps/ub.py", line 178, in list_denied_tags
> mct = self.denied_tags.split(",")
> AttributeError: 'NoneType' object has no attribute 'split'

**Expected behavior**
Ability to login.

**Environment (please complete the following information):**
 - OS: 4.4.0-185-generic Ubuntu
 - Python version: Python 2.7.12 & Python 3.5.2
 - Calibre-Web version: dcba720
 - Docker container: [None/Technosoft2000/Linuxuser]: None
 - Special Hardware: Dell R710 VM (Proxmox)
 - Browser: Firefox latest

**Comment by kaipee** [comment]
Here is some info from the update last night, followed by testing reading an ebook in the browser, then the errors today:

> [2020-07-17 18:10:14,559]  INFO {cps.web:1184} Login failed for user "kaipee" IP-adress: 192.168.0.51
> [2020-07-17 18:10:52,181]  INFO {cps.admin:700} Update status requested
> [2020-07-17 18:10:52,200]  INFO {requests.packages.urllib3.connectionpool:761} Starting new HTTPS connection (1): api.github.com
> [2020-07-17 18:11:25,569]  INFO {requests.packages.urllib3.connectionpool:761} Starting new HTTPS connection (1): api.github.com
> [2020-07-17 18:11:25,869]  INFO {requests.packages.urllib3.connectionpool:761} Starting new HTTPS connection (1): codeload.github.com
> [2020-07-17 18:35:56,857]  INFO {cps.admin:700} Update status requested
> [2020-07-17 18:35:56,859]  INFO {requests.packages.urllib3.connectionpool:761} Starting new HTTPS connection (1): api.github.com
> [2020-07-17 18:36:16,502] ERROR {cps:1891} Exception on /get_updater_status [POST]
> Traceback (most recent call last):
>   File "/opt/calibre-web/vendor/flask/app.py", line 2446, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/opt/calibre-web/vendor/flask/app.py", line 1951, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/opt/calibre-web/vendor/flask/app.py", line 1820, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/opt/calibre-web/vendor/flask/_compat.py", line 39, in reraise
>     raise value
>   File "/opt/calibre-web/vendor/flask/app.py", line 1949, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/opt/calibre-web/vendor/flask/app.py", line 1935, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/opt/calibre-web/vendor/flask_login/utils.py", line 272, in decorated_view
>     return func(*args, **kwargs)
>   File "/opt/calibre-web/cps/web.py", line 192, in inner
>     return user
>   File "/opt/calibre-web/cps/admin.py", line 727, in get_updater_status
>     if error_flash:
>   File "/usr/lib/python3.5/threading.py", line 840, in start
>     raise RuntimeError("threads can only be started once")
> RuntimeError: threads can only be started once
> [2020-07-17 18:39:52,514]  INFO {cps.server:196} webserver stop (restart=True)
> [2020-07-17 18:39:52,517]  INFO {cps.server:184} Performing restart of Calibre-Web
> [2020-07-17 18:39:54,615]  INFO {cps:98} Starting Calibre Web...
> [2020-07-17 18:39:54,790]  INFO {cps.server:156} Starting Tornado server on :8083
> [2020-07-17 18:40:17,280]  INFO {cps.admin:1022} Update status requested
> [2020-07-17 18:40:17,291]  INFO {requests.packages.urllib3.connectionpool:761} Starting new HTTPS connection (1): api.github.com
> [2020-07-17 18:53:23,327]  INFO {cps.server:207} webserver stop (restart=False)
> [2020-07-17 18:53:23,441]  INFO {cps.server:184} Performing shutdown of Calibre-Web
> [2020-07-17 18:53:46,810]  INFO {cps:98} Starting Calibre Web...
> [2020-07-17 18:53:46,987]  INFO {cps.server:156} Starting Tornado server on :8083
> [2020-07-17 18:56:16,049]  INFO {cps.admin:1022} Update status requested
> [2020-07-17 18:56:16,057]  INFO {requests.packages.urllib3.connectionpool:761} Starting new HTTPS connection (1): api.github.com
> [2020-07-17 18:56:20,491]  INFO {cps.server:207} webserver stop (restart=True)
> [2020-07-17 18:56:20,495]  INFO {cps.server:189} Performing restart of Calibre-Web
> [2020-07-17 18:56:21,931]  INFO {cps:98} Starting Calibre Web...
> [2020-07-17 18:56:22,085]  INFO {cps.server:156} Starting Tornado server on :8083
> [2020-07-17 18:56:52,503]  INFO {cps.web:1271} Serving book: Python Crash Course, 2nd Edition - Eric Matthes
> [2020-07-18 22:04:17,525]  INFO {cps.server:207} webserver stop (restart=False)
> [2020-07-18 22:04:17,858]  INFO {cps.server:184} Performing shutdown of Calibre-Web
> [2020-07-18 22:12:15,898]  INFO {cps:98} Starting Calibre Web...
> [2020-07-18 22:12:46,357]  INFO {cps.server:156} Starting Tornado server on :8083
> [2020-07-18 22:20:14,286]  INFO {cps.server:207} webserver stop (restart=False)
> [2020-07-18 22:20:14,388]  INFO {cps.server:184} Performing shutdown of Calibre-Web
> [2020-07-18 22:50:55,645]  INFO {cps:98} Starting Calibre Web...
> [2020-07-18 22:50:56,010]  INFO {cps.server:156} Starting Tornado server on :8083
> [2020-07-18 22:53:54,210] ERROR {cps:1891} Exception on / [GET]
> Traceback (most recent call last):
>   File "/opt/calibre-web/vendor/flask/app.py", line 2446, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/opt/calibre-web/vendor/flask/app.py", line 1951, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/opt/calibre-web/vendor/flask/app.py", line 1820, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/opt/calibre-web/vendor/flask/_compat.py", line 39, in reraise
>     raise value
>   File "/opt/calibre-web/vendor/flask/app.py", line 1949, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/opt/calibre-web/vendor/flask/app.py", line 1935, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/opt/calibre-web/cps/web.py", line 201, in decorated_view
>     return login_required(func)(*args, **kwargs)
>   File "/opt/calibre-web/vendor/flask_login/utils.py", line 272, in decorated_view
>     return func(*args, **kwargs)
>   File "/opt/calibre-web/cps/web.py", line 623, in index
>     entries, random, pagination = calibre_db.fill_indexpage(page, db.Books, True, [db.Books.timestamp.desc()])
>   File "/opt/calibre-web/cps/db.py", line 511, in fill_indexpage
>     return self.fill_indexpage_with_archived_books(page, database, db_filter, order, False, *join)
>   File "/opt/calibre-web/cps/db.py", line 525, in fill_indexpage_with_archived_books
>     .filter(self.common_filters(allow_show_archived))
>   File "/opt/calibre-web/cps/db.py", line 490, in common_filters
>     negtags_list = current_user.list_denied_tags()
>   File "/opt/calibre-web/cps/ub.py", line 178, in list_denied_tags
>     mct = self.denied_tags.split(",")
> AttributeError: 'NoneType' object has no attribute 'split'

**Comment by kaipee** [comment]
I've restored the VM from backup.

Here is a list of the Linked Libraries info


Program library | Installed Version
-- | --
2.6.0
1.3.13
not installed
not installed
0.5.0
3.11.0
1.0.0
Linux calibre 4.4.0-140-generic #166-Ubuntu SMP Wed Nov 14 20:09:47 UTC 2018 x86_64 x86_64
2.9.1
0.4.5
2.8.0
installed
0.4.0
2019.3
1.1.1
2.11.1
3.5.2 (default, Oct  8 2019, 13:06:37)  [GCC 5.4.0 20160609]
Tornado 6.0.3
ImageMagick 6.8.9-9 Q16 x86_64 2018-09-28 http://www.imagemagick.org
v1.26.0
0.5.9
not installed
not installed
not installed
ebook-convert (calibre 3.34.0)

**Comment by OzzieIsaacs** [comment]
I can't reproduce it, but I think I know what happend, please try the newest commit

**Comment by kaipee** [comment]
Sure thing, what's the easiest way to do that? Will the self-updater in the WebUI pull the latest commit?

**Comment by kaipee** [comment]
I've changed the Admin config to nightly updates and applied the latest

Version | Details
-- | --
7/20/20, 7:28 PM | Current version

Server has been restarted, I'll wait until tomorrow to confirm any issues.

**Comment by kaipee** [comment]
I'm still getting (what looks to be) the same error.

I have confirmed, however, that I can login successfully using my admin account and navigate the system.

> 
> 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
> Traceback (most recent call last):
> File "/opt/calibre-web/vendor/flask/app.py", line 2446, in wsgi_app
> response = self.full_dispatch_request()
> File "/opt/calibre-web/vendor/flask/app.py", line 1951, in full_dispatch_request
> rv = self.handle_user_exception(e)
> File "/opt/calibre-web/vendor/flask/app.py", line 1820, in handle_user_exception
> reraise(exc_type, exc_value, tb)
> File "/opt/calibre-web/vendor/flask/_compat.py", line 39, in reraise
> raise value
> File "/opt/calibre-web/vendor/flask/app.py", line 1949, in full_dispatch_request
> rv = self.dispatch_request()
> File "/opt/calibre-web/vendor/flask/app.py", line 1935, in dispatch_request
> return self.view_functions[rule.endpoint](**req.view_args)
> File "/opt/calibre-web/cps/web.py", line 196, in decorated_view
> return login_required(func)(*args, **kwargs)
> File "/opt/calibre-web/vendor/flask_login/utils.py", line 272, in decorated_view
> return func(*args, **kwargs)
> File "/opt/calibre-web/cps/web.py", line 620, in index
> entries, random, pagination = calibre_db.fill_indexpage(page, db.Books, True, [db.Books.timestamp.desc()])
> File "/opt/calibre-web/cps/db.py", line 511, in fill_indexpage
> return self.fill_indexpage_with_archived_books(page, database, db_filter, order, False, *join)
> File "/opt/calibre-web/cps/db.py", line 525, in fill_indexpage_with_archived_books
> .filter(self.common_filters(allow_show_archived))
> File "/opt/calibre-web/cps/db.py", line 491, in common_filters
> postags_list = current_user.list_allowed_tags()
> File "/opt/calibre-web/cps/ub.py", line 189, in list_allowed_tags
> mct = self.allowed_tags.split(",")
> AttributeError: 'NoneType' object has no attribute 'split'

**Comment by OzzieIsaacs** [comment]
This error message is a slightly different one. Would it be possible for you to send me the app.db file via private email? I‘d like to avoid we are playing this game several times. I don‘t need passwords, I like to check some entries. Or are you able to open the app.db file with Something like sqlitebrowser and change/check some database entries? ( I tell you which one to check?)

**Comment by kaipee** [comment]
I should be able to open the database and check for any irregularities.

**Comment by OzzieIsaacs** [comment]
Could you please check in the table "user", that denied_tags, allowed_tags, denied_column_value and allowe_column value are all contain an empty string (or any other sting, if you restrict the visibility) and not NULL
![grafik](https://user-images.githubusercontent.com/6438895/88083032-d6505f80-cb82-11ea-86b9-1f169f77b7ab.png)

**Comment by OzzieIsaacs** [comment]
Please also check the table settings for the column "config_mature_content_tags", and enter there also an non NULL value

**Comment by kaipee** [comment]
Using **dbeaver** to check, those columns do indeed seem to have some NULL values in them.

![image](https://user-images.githubusercontent.com/5189160/88104143-ea538b80-cb99-11ea-98cd-5f56dd1bc423.png)

User 1 and User 2 are 'admin' and 'guest', respectively, so I'm assuming that's why I can login as admin.

No custom tags have been configured for any user (including 'admin') - so I'm not sure how they got random NULL values.

![image](https://user-images.githubusercontent.com/5189160/88104507-6ea60e80-cb9a-11ea-8cc2-d03b9946c719.png)

**Comment by kaipee** [comment]
The 'config_mature_content_tags' does not seem to have a NULL value inserted.

![image](https://user-images.githubusercontent.com/5189160/88104676-ad3bc900-cb9a-11ea-9e6f-d961aa345182.png)

**Comment by OzzieIsaacs** [comment]
I still don't now how this happend to your database, but with the newest commit it should work now.

**Comment by OzzieIsaacs** [comment]
Could you please also check in table settings for config_denied_tags, config_allowed_tags, config_denied_column_value, config_allowed_column_value. If they are all NULL, this could be the reason (but I don't know why). To remove the NULL values thers, please go as admin in admin section -> UI confguration -> default visiblitys of new users, add a random colum visibility restriction and delete it right afterwards (with the trashcan) and check the values in the app.db later on, they should be emty strrings and not NULL anymore and you should be "ready for future".
Just to be save: Could you please try to add another user and check for the entries.
If everything works out as expected, please close the issue.

**Comment by kaipee** [comment]
I've just tried to perform the update from the WebUI and got the following error : "Update failed: Update File Could Not be Saved in Temp Dir"

![image](https://user-images.githubusercontent.com/5189160/88338537-667fd780-cd30-11ea-9b24-f9d05994d36b.png)

A second attempt was successful at updating.
I can confirm logging in with all other users works again.

Thanks for your work.

Looking at the app.db (fater update) the NULL values are still present - I assume it's safe to go ahead and empty those?

With regards to the 'settings' table - all config columns as mentioned are empty (no NULL values).

**Comment by kaipee** [comment]
I noticed some other NULL values for columns in 'settings' table, such as the google_drive options and goodreads options - not sure if these are fine or also a potential issue.

**Comment by kaipee** [comment]
I've removed all NULL entries from both the 'users' table and the 'settings' table. Everything seem to run fine (so far).
