### ISSUE TITLE
Support for multiple libraries

### ISSUE THREAD

**Issue by kriss6557** [janeczku/calibre-web#1535]
Hello,
I would like to see the possibility to switch easily between different libraries like it is possible in calibre and calibre content server.
Is it something in the pipes ? 
Any estimated date ?
Thank you for your good work.
Best

**Comment by Lynxai** [comment]
Yes, please! Or at least the possibility of running multiple instances of calibre docker.

**Comment by flying-sausages** [comment]
This has been shut down multiple times, just do a quick search

**Comment by kriss6557** [comment]
Hi @flying-sausages  , I didn't notice that earlier.
I didn't think this was so much work especially if it's just a simple switch with no advanced features like search in all DBs for instance (pretty much a bit of GUI changes).
Anyway I have 3 collections and will run 3 containers for the purpose.
Thanks

**Comment by OzzieIsaacs** [comment]
The problems start with the features Calibre-Web adds: 
The downloads have to be counted then for each DB, the visibility restriction have to be made for each database, how to integrate Kobo sync without access to the GUI, how to change OPDS feed, handling of shelfs, ...
For your usecase this might work, but I start enabling it, users will come and ask for every single feature and we will end with a very complex piece of software.
This is the background of this decision
