### ISSUE TITLE
Add option to disable Metadata Sources

### ISSUE THREAD

**Issue by pattems** [janeczku/calibre-web#1536]
**Is your feature request related to a problem? Please describe.**
The ComicVine metadata source seems to take precedence over other searches, even when providing less relevant results. I have to manually uncheck the ComicVine search every time I do a metadata search to find relevant results. Case in point: A search for "The Dark Design - Philip Jose Farmer" hits 10 comic book results before anything else. Unchecking the ComicVine search brings the appropriate result immediately

**Describe the solution you'd like**
A setting in options to manage metadata sources, to be able to disable sources not relevant to an individual

**Describe alternatives you've considered**
Better sorting of results - Currently it appears that the search grabs the top 10 hits from ComicVine, then the top 10 from Google, and finally the top 10 from Douban. Instead of sorting results by provider, sorting the relevant matches from all sources by relevance would resolve this issue. Not having the ComicVine results being first on the list would probably provide more relevant results to more people as well.

**Comment by bedr0** [comment]
I would also like to see this functionality being implemented!

**Comment by nomorehey** [comment]
I would also like to see this functionality being implemented! x2

**Comment by fizzyade** [comment]
This needs to be implemented, every time  fetch metadata I have to disable douban and comic vine because they're no relevant to anything I'd download.

At the very least, make google results priority.

**Comment by fizzyade** [comment]
The easiest way to fix this is:

edit the file calibre-web/cps/static/js/get_meta.js

`    function doSearch (keyword) {
        showFlag = 0;
        dbDone = ggDone = cvDone = 0;
        dbResults = [];
        ggResults = [];
        cvResults = [];
        $("#meta-info").text(msg.loading);
        if (keyword) {
            dbSearchBook(keyword);
            ggSearchBook(keyword);
            cvSearchBook(keyword);
        }
    }`

either comment out dbSearchBook and cvSearchBook or change the order so ggSearchBook is first.

I went for the former as I'm not interested in the other types of metadata.

**Comment by kbruegge** [comment]
This seems to have been fixed in the latest version if I understood this correctly.

**Comment by OzzieIsaacs** [comment]
It's possible to deactivate metadata source meanwhile:
Option 1 - In program: 
Just deactivate the provider you don't want to query, this setting is saved on a per user base.

Option 2 - Out of program:
Delete the file with the provider name you don't like from the cps/metadata_provider folder
