### ISSUE TITLE
Getting documents into Calibre Web

### ISSUE THREAD

**Issue by rr2121** [janeczku/calibre-web#1541]
I've got this installed on my server and it's working.

Am I to understand this system only allows putting documents into it by uploading them one by one (or a few at a time) from my local computer.  There is no way to add documents from the server itself other than by running command line commands?  

This system has no way of scanning a folder for documents and adding them automatically such as the way Plex does media?

I like the system, but without a way of getting documents into it from the server, it's useless to me.

**Comment by OzzieIsaacs** [comment]
> I like the system, but without a way of getting documents into it from the server, it's useless to me.
Sorry to hear this, but currently there are no other ways than via Upload Button, or a script like the one given in the wiki

**Comment by rr2121** [comment]
Thank you for the reply.  Uninstalling now.
