### ISSUE TITLE
Cant use opds with reader apps

### ISSUE THREAD

**Issue by hackmonker** [janeczku/calibre-web#1548]
**Describe the bug/problem**
I tried to put the opds link - my.domain.com/opds in the opds apps like moon reader. it gives the catalogue but I cant read or download from the apps as  it says not authorized. I get it as it is because it is login protected but where do I login while using the opds? can we only browse and not read directly from the apps?

**Comment by OzzieIsaacs** [comment]
The Wiki gives some hints for working opds reader: https://github.com/janeczku/calibre-web/wiki/FAQ#which-opds-readers-work-with-calibre-web
The Reader automatically detects if it needs to log in. You should have got a request for authorisation for Browsing the Books. Some of the readers are a bit buggy and do not send authorisation information on requesting covers or Download.

**Comment by OzzieIsaacs** [comment]
And it would be cool of you didn‘t just delete the Form, but instead would fill it out. And please try to be a bit more precise: Readers as moon reader means you also tried ...? You are using which version, is there any entry in the logbook? Did you enable the accesslog, what does ist State After trying to download a Book? Do the covers getting Displays? Did you enable anonymous Browsing? Has the user download rights? If you can browse the catalog how did you enter your cedentials? Are you using a reverse proxy inbetween? What happens if you enter the Download url in a Normal Browser?

**Comment by OzzieIsaacs** [comment]
The path for downloading is: /opds/download/<book_id>/<book_format>/

**Comment by hackmonker** [comment]
Sry I thought this happened before. Ok so my instance is in https://site.com. I use nginx as a reverse proxy. I have anonymous browsing enabled. Now what happens when I tried to use apps

1, Moon reader - I went to opds catalogue add. There there is a space for site. I enter https://site.com/opds. then I gave a name for catalogue. and it then cinnects. I can see all my books. and covers too. I can search. but when I click on download it says 
HTTP/1.1 403 Forbidden

There is no place where I can put my login details so that it can be authenticated

2. Same for fbreader. In ebookdroid there is a username and password section during adding opds so that works. cool reader also has a username and password section but even then I  can browse but on clicking on the book it gives 403 error.

**Comment by hackmonker** [comment]
the problem is in most of the apps there is no authentication for opds.

**Comment by hackmonker** [comment]
ok so apparently login option only comes when anonymous browsing is turned off

**Comment by OzzieIsaacs** [comment]
The apps try to access the given address ( https://site.com/opds), if they get "access denied", they ask for credentials, if they get the data, they just continue.  If you have anonymous browsing enabled, the apps get access and just continue. If you get access denied while browsing anonymous, then I think you have disabled (which is the default) the download rights for guest user. 
There are 2 options: 
A) Disable anonymous browsing and force the apps to ask for credentials
B) Use anonymous browsing and have download rights enabled for guest user.
I haven't checked it recently, but I'm sure I'm testing this so it should work like described above.
The access rights specially for downloads and cover pictures is not always well implemented on the apps (I'm happy to hear ebookdroid is working meanwhile, asked for a fix 1 1/2 years ago), and there is nothing I can do from my side.

**Comment by hackmonker** [comment]
Yeah ebookdroid does work since there is a username and password section while we are adding the opds. others dont have this. Thanks for clarifying though. I turned off anonymous browsing so it is working now.
