### ISSUE TITLE
Please update messages.pot

### ISSUE THREAD

**Issue by radzio1993** [janeczku/calibre-web#155]
Please update file messages.pot. How to use Babel to update the file messages.pot? In case of detection of outdated version of the update would go along with the Polish translation.

**Comment by Kennyl** [comment]
Or maybe port the translation to transifex?

**Comment by radzio1993** [comment]
Transifex is not available in free version.

**Comment by OzzieIsaacs** [comment]
Done.

You can use: `pybabel extract --no-wrap -F babel.cfg -o messages.pot cps` to generate new .pot file. Detailed docs can be found here:  http://babel.pocoo.org/en/latest/cmdline.html#cmdline
