### ISSUE TITLE
Configure Favicon and login page

### ISSUE THREAD

**Issue by Blitzbirnep** [janeczku/calibre-web#1552]
Hey I am wondering if it is possible to change the login page layout e.g. add a picture and how to modify the favicon?

regards Blitz

**Comment by timholl** [comment]
The favicon can be changed by replacing `cps/static/favicon.ico`; there is currently no way to achieve this via the web frontend.

**Comment by OzzieIsaacs** [comment]
My preferred way of fulfilling your request would be indeed replacing the favicon file manually and also editing the login.html page (cps/templates) manually
