### ISSUE TITLE
Auto-download of Humble Bundle books

### ISSUE THREAD

**Issue by blitzmann** [janeczku/calibre-web#1555]
Hi there,

A group of friends and I like to purchase Humble Book Bundles (for example: https://www.humblebundle.com/books/raspberry-pi-raspberry-pi-press-books) and then share them since they are DRM-free. I've been looking at calibre-web as a centralized ebook management system that we can all use to manage this.

To that end, I have a couple of questions:
* Does calibre-web support some type of plugin system? That is, would I be able to write a plugin that folks can download and use without affecting the mainline repo?
* If not... what is the level of support such a project would receive for inclusion into this repo?

The idea that I have is that a user could have a way to give the web interface an auth token for Humble Bundle, then the application will fetch the various bundles that they've ordered. From there, they can choose which books would be downloaded and added to the library. It wouldn't be an automated system, but it would require the server to download (potentially many) files in the background in a sort of queue, and then process them into the library.

I'm just putting a couple feelers out for such a feature to get a better idea of what might be involved.

**Comment by OzzieIsaacs** [comment]
Calibre-Web does not support any plugins (I'm was planning it and also mentioned it for several years, but made no progress so far) and currently it doesn't look like it's going to hapen within the next years. 
In the past few years many people had ideas for adding supoort of special third party filestorages and similar stuff, I accepted pullrequests regarding gdrive support, metadata download and ldap login and now I spend much time supporting and fixing this non-ebook-library related program parts. I decided to not go further into this directions and also pointed this out in the contribution rules (https://github.com/janeczku/calibre-web/blob/master/CONTRIBUTING.md#feature-request). So I think I won't merge your proposal into to the mainline repro.  (My experience from the past: You might be satisfied with a certain level of functionallity, but if many user use this features unhandeled errorcases will come up frequently and then I would spend hours and days fixing this problems)
My suggestion would therefore be writing a different tool which uses the calibre-web upload function via an automated script to add the ebooks to the calibre-web database.

**Comment by blitzmann** [comment]
Thanks for your candid response. :)

> My suggestion would therefore be writing a different tool which uses the calibre-web upload function via an automated script to add the ebooks to the calibre-web database.

That may be a good alternative. Kind of like how calibre-web hooks into calibre without it having knowledge, I could potentially make a service to hook into calibre-web.

I'll have to dig into a few things to see how feasible it is, but thank you for the suggestion :)

**Comment by blitzmann** [comment]
I'm currently hacking at the codebase to get a better feel for how things are laid out and how they work. My plan currently is to just write a customization directly with calibre-web that would allow for such a feature and simply maintain an as-is port for now, as that seems like it would be the easiest path to get up and running. As I get more comfortable with the codebase, I may write it as an independent service in the future.

Closing this as it no longer concerns the main product here :)
