### ISSUE TITLE
Caliblur theme styling is broken in a few places

### ISSUE THREAD

**Issue by Efreak** [janeczku/calibre-web#1560]
**Describe the bug/problem**
1. When you view the 'Download Shelf' page, there's no dark styling.
2. When you go to Advanced Search, the header at the top is not at the top, it's mostly below and partly behind the title field.
3. The scrollbar isn't styled in firefox

**To Reproduce**
1. Click a shelf, then click `Download Shelf`
2. Click `Advanced Search`

**Logfile**
N/A

**Expected behavior**
1. The background in the Download Shelf styling should be dark
2. The header in advanced search should be at the top like every other header *or* it should at least have a margin set on it to move it up and the next element down:
    1. Replace `body.advsearch > div.container-fluid > div > div.col-sm-10::before` css rules with an element, `<h1 class="catload">Advanced Search</h1>` like the other pages have
    2. Add `margin-top:-50px` to `body.advsearch > div.container-fluid > div > div.col-sm-10::before` css rules, and add `.col-md-10.col-lg-6 {margin-top: 50px;}`. These styles work on the *advanced search* page, but I'm not sure if they break anything elsewhere.
3. Add `scrollbar-color: hsla(0, 0%, 100%, .2) transparent;` to the body element. you can also set `scrollbar-width:thin`, but I'm not sure where (it doesn't work on the body element, but it does work on * selector).

**Screenshots**

<details>
<summary>1. Download Shelf styling</summary>

[![Download Shelf](https://files.catbox.moe/xtm5zs.png)](https://files.catbox.moe/xtm5zs.png)
</details>
<details>
<summary>2. Advanced Search and scrollbar styling:</summary>

[![Screenshot](https://files.catbox.moe/jmvele.png)](https://files.catbox.moe/jmvele.png)
<sup>Yes, my firefox theme is horrible. It's the result of my giving up halfway through figuring it out.</sup>
</details>

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS
 - Python version: Python 3.6.9, Python 2.7.17
 - Calibre-Web version: 1a1d105f (latest as of this writing)
 - Docker container: None:
 - Special Hardware: Digital Ocean server
 - Browsers: Firefox 80.0b4, Chrome 86.0.4221.3

**Additional context**
Reverse proxy in use. Special database locations in use. Calibre-Web is otherwise fully functional, I'm pretty sure the environment/context is irrelevant here.

**Comment by OzzieIsaacs** [comment]
You are right, the dark theme has several issues (all tagged with Caliblur! Theme), it‘s missing a maintainer.

**Comment by ghighi3f** [comment]
I can tackle the other points too.
For the shelfdown template the caliBlur css was not loaded.
This change and a little bit of styling outputs this:
![Screenshot 2020-10-10 at 14 56 16](https://user-images.githubusercontent.com/21315004/95654484-ec7a1600-0b08-11eb-84a1-a8b0617f3c62.png)
Let me know if it's ok.

**Comment by OzzieIsaacs** [comment]
Looks good
