### ISSUE TITLE
Feature: Don't use modal popup book-detail-view when browser is kindle  

### ISSUE THREAD

**Issue by JHerseth** [janeczku/calibre-web#1569]
**Is your feature request related to a problem? Please describe.**
Kindles web browser doesn't support the modal book view in calibre

**Describe the solution you'd like**
Detect kindle browser, and redirect to book-details page instead of modal popup

**Describe alternatives you've considered**
Manually turning off js in browser - it is cumbersome.

**Comment by indigomirage** [comment]
I agree with this.  In my case, it's a kobo, but it's the same issue.

Another option, but not ideal - I use a guest account (limited to my LAN), and if the Book List view was available, it might be possible to get to the book download pages.

But, fundamentally, supporting very rudimentary browsers (like those on the Kindle or Kobo) is what's needed - it's actually my core use case for wanting Calibre-Web (ie - navigate to it on the eReader, and download the book I want).

**Comment by AnonTester** [comment]
Fixed in https://github.com/janeczku/calibre-web/issues/1861
