### ISSUE TITLE
[Question] User config location

### ISSUE THREAD

**Issue by CHBMB** [janeczku/calibre-web#158]
Just playing around with the docker container, application looks amazing, but it's non persistent if I remove the container.

Just wondering where the config information is stored?

**Comment by OzzieIsaacs** [comment]
The user config, database config is stored in a internal SQLite database. I don't really know how the docker stuff works, maybe @janeczku can explain better why this happens

**Comment by Kennyl** [comment]
you can commit once when you finish setup

**Comment by CHBMB** [comment]
@Kennyl Not sure what you mean by that.  I set the container up and it's working beautifully, but if I remove the container then reinstall I need to set it up again.  Generally with docker it's nice to be able to put config on a volume mount so a remove/reinstall of a container results in image persistence.

**Comment by Kennyl** [comment]
<img width="565" alt="screen shot 2017-03-13 at 4 56 52 pm" src="https://cloud.githubusercontent.com/assets/1933134/23847611/28c6423e-080e-11e7-9e34-a879c3042cfd.png">

**Comment by Kennyl** [comment]
Once Setup.
```docker ps 
```get which ContainerID running
```docker commit -m "finish setup"  <ContainerID>  calibre-web:latest
next time run  Container with calibre-web:latest  image

**Comment by CHBMB** [comment]
@Kennyl Thanks for the info, appreciate you looking at this.  I was more thinking along the lines of making the user database/config location definable, so it could be placed onto a volume mount on the docker host.  Then if the container is removed and then reinstalled, the setup is already done.  

Something along the lines of what we do with Couchpotato [here](https://github.com/linuxserver/docker-couchpotato/blob/master/root/etc/services.d/couchpotato/run) where it is placed in `/config` which is mapped to a folder on the host. 

Looks like chickenzord has something along the lines of what I'm thinking of in his [fork](https://github.com/chickenzord/calibre-web/blob/master/config.ini.example), admittedly he seems behind on dev.

**Comment by Kennyl** [comment]
Yeah, 
For docker,  exposing more config to environment variable is best option. (Including app.db location.)

Few steps add to Dockfile may fulfill your requirement/enhancement.
ie. link app.db to new volume.

I still think ```docker commit``` is OK,  because when you update calibre-web , you still need commit the program update.

BTW, this enhancement maybe dangling for awhile.

**Comment by issmirnov** [comment]
#166 might be of interest to you. It solves half the problem ; namely passing in a custom path for the DB.

With the proper docker bind, you could have the app.db live on the host and attach it to the container as you requested.

**Comment by Kennyl** [comment]
I have proposed to https://github.com/Technosoft2000/docker-calibre-web

**Comment by CHBMB** [comment]
I'm actually part of [linuxserver.io](http://tools.linuxserver.io/dockers) and we've been looking to create a docker container of this.  Sticking points being able to define where the user config files reside and still struggling to get it working with our reverse proxy nginx container.

**Comment by Kennyl** [comment]
At this moment you may try to using ln -s /opt/cps/app.db  /volume/a/app.db and changedb.sh instead.
