### ISSUE TITLE
Public shelf not available to guest

### ISSUE THREAD

**Issue by wgibcus** [janeczku/calibre-web#1581]
When accessing a public shelf when not logged in, the login prompt is displayed. 

Platform | Linux 5.4.0-1013-raspi #13-Ubuntu SMP Mon Jun 15 03:17:37 UTC 2020 aarch64 aarch64
PHP: 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]
Version: 0.6.9 Beta - 843279bacb9ab40888d137dd69f8f688a1c920b2 - 2020-08-23T21:22:44+02:00
Web server: Gevent 20.5.2

**Comment by oizo123** [comment]
thanks

**Comment by wgibcus** [comment]
Awesome. All fixed in the new update 👍
