### ISSUE TITLE
opds feed categories as calibre has

### ISSUE THREAD

**Issue by contramundi** [janeczku/calibre-web#1582]
Is it possible to get the opds feed a little more like the default calibre server has? Like for example authors not in a massive list but you get for example:

Authors > A/B/C/etc. > Authors with the selected letter. 

Also what i'm missing is something like books by title, there's a few categories but i'm unable to go straight to a list with all books in alphabetical order for example.

**Comment by OzzieIsaacs** [comment]
Meanwhile there is an additionl level with grouped by "starting character" access, like you requested
