### ISSUE TITLE
Is that possible to add a book via command line?

### ISSUE THREAD

**Issue by madpin** [janeczku/calibre-web#1583]
My context, is I think the recipes from Calibre really useful.
And I can run them with the `ebook-convert` binary, but I can't add this to my library.

And a further question, would that be possible to send this file to my kindle via command line?
Because if it's possible, I can schedule from Cron and have those books delivered to my kindle everyday morning.
=]

Thanks,

**Comment by flying-sausages** [comment]
`calibredb add`, check the Calibre docs.

**Comment by OzzieIsaacs** [comment]
I think this looks more like a job for ebook-convert, calibredb and another commandline tool for sending emails and not for calibre-web.
