### ISSUE TITLE
"Forgetting" library location on boot

### ISSUE THREAD

**Issue by atropos112** [janeczku/calibre-web#1584]
Hi, 

My apologise perhaps this is an obvious issue but couldn't figure out a way myself. 

I'm running calibre-web from Raspberry Pi with the library on external hard drive, ext4 with all privilages given to everyone , for diagnosing purposes. Every time i restart the Raspberry Pi, I added "@reboot \opt\calibre-web\cps.py" to run the calibre-web in the background on boot. However it asks me for location of the library ever time it reboots. Is there a way for it to know the library location and not "forget" everytime i reboot ?

**Comment by OzzieIsaacs** [comment]
Your Problem is calibre-Web is startinh while the external drive isn‘t available, so delaying the start with a little bash script would help

**Comment by atropos112** [comment]
That was it, thank you @OzzieIsaacs , you were right on point, i changed "@reboot \opt\calibre-web\cps.py" to "@reboot sleep 30 && \opt\calibre-web\cps.py" and it did the charm, thank you.
