### ISSUE TITLE
Feature Request: Welcome Message or Screen

### ISSUE THREAD

**Issue by dhatereki** [janeczku/calibre-web#1587]
It would be nice to have a welcome page or header on main page with custom text for users. For example, I am managing a library to share ebooks with my students. It would be good to have a welcome message which one could edit like what the library is, how to contact the library admin and maybe I could even through in a Google Forms link for book requests or issues etc.

**Comment by wgibcus** [comment]
Could you just put a standard HTML page with that info in your web root and make that the landing page for students? You could then link the Calibre-Web url from there

**Comment by brandonhowlett** [comment]
It would be helpful to be able to include more than one %s in LDAP User Object Filter to perform more advanced queries. For example, trying to match an email that is either cn, email, or title (don't ask me why that is-it just is).

**Comment by MinchinWeb** [comment]
Duplicate of #992 ?

**Comment by OzzieIsaacs** [comment]
@MinchinWeb thanks, for pointing out, this is indeed a duplicate
