### ISSUE TITLE
caliBlur! theme: Advanced search page header is incorrectly positioned

### ISSUE THREAD

**Issue by blitzmann** [janeczku/calibre-web#1594]
**Describe the bug/problem**

![image](https://user-images.githubusercontent.com/3904767/91677985-536fdc80-eb12-11ea-911d-95b5052aad46.png)

**To Reproduce**
Set theme to caliBlur! and go to Advanced Search

**Expected behavior**
I expect the header to go into the area above the page content, to the right of the Calibre-Web orange link

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10/Raspberry Pi OS] Windows 10
 - Python version: [e.g. python2.7] py3.6
 - Calibre-Web version: [e.g. 0.6.8 or 087c4c59 (git rev-parse --short HEAD)]: 4b14cc6a74ff44527759af92977e07c270da6c61 (current Develop HEAD)
 - Docker container: [None/Technosoft2000/Linuxuser]: None
 - Special Hardware: [e.g. Rasperry Pi Zero] None
 - Browser: [e.g. Chrome 83.0.4103.97, Safari 13.3.7, Firefox 68.0.1 ESR] Chrome 85

**Comment by OzzieIsaacs** [comment]
The Caliblur! Theme is a bit buggy on several spots, I'm aware of it. It was programmed by somebody else, 
It's to much for me to support it beside the normal enhancements of Calibre-Web

**Comment by ghighi3f** [comment]
Hello. I attach a screenshot of a possible fix for this issue.
If it's ok, I can take a stab at it, lemme know.
Thanks
![Screenshot 2020-10-10 at 12 13 36](https://user-images.githubusercontent.com/21315004/95651316-3acfea80-0af2-11eb-8f0b-f407668c4d79.png)

**Comment by OzzieIsaacs** [comment]
Looks better than before.
I don't want to complain, but..
all other headlines having a smaller title:
![grafik](https://user-images.githubusercontent.com/6438895/95651494-19b7cb80-0aeb-11eb-8823-3a71a8e3b3da.png)
![grafik](https://user-images.githubusercontent.com/6438895/95651500-24726080-0aeb-11eb-9dda-9d05b8f9de75.png)

So if you could also adjust this also, it would be perfect

**Comment by OzzieIsaacs** [comment]
Yeah there is only the minified version. We could unpack it via a online javascript beautifier to make it better accessible. (In the original repro I think there is also an earlier version of the unminified css)

**Comment by ghighi3f** [comment]
Yes, I think only the .min extension is still present, it doesn't look like a minified file anymore :)

About your feedback, do you mean something like this ?
![Screenshot 2020-10-10 at 12 29 54](https://user-images.githubusercontent.com/21315004/95651674-a6b35280-0af4-11eb-8a73-dfb4f6e3cd72.png)

**Comment by OzzieIsaacs** [comment]
Yes

**Comment by OzzieIsaacs** [comment]
I talked about this one: https://github.com/leram84/layer.Cake/blob/master/caliBlur/caliBlur.css
(But it's an old version, it has to be merged with the current one)

**Comment by ghighi3f** [comment]
> I talked about this one: https://github.com/leram84/layer.Cake/blob/master/caliBlur/caliBlur.css
> (But it's an old version, it has to be merged with the current one)

Yes, but because our caliBlur.min.css isn't minified anymore, wouldn't we get away with changing the .min extension and continuing with it like that?
And then it will not be confusing anymore.
I could be wrong, tho.

About my fix, I did it in the previous implementation way, by setting the css content rule on another pseudo element.
But after a second thought, best practice will be to include the title string in the html template, so it could be registered as a translatable string.
I'm willing to invest the time for this, just let me know. That why I didn't submit a pull request yet.
Thanks!

**Comment by OzzieIsaacs** [comment]
Looks good and is merged
