### ISSUE TITLE
Feature Request: Deactivate users

### ISSUE THREAD

**Issue by gorgobacka** [janeczku/calibre-web#1595]
Besides deleting users, it would be useful to have the feature to deactivate users. Then it's possible to temporarily disable users to use the Calibre Web instance and you don't need to add all data again (email, username, permissions) when activating the user again.

**Comment by OzzieIsaacs** [comment]
In the contribution rules I stated that I will try to focus on organizing books and not doing user management, so I will not implement it. You could change the username and password to something you only know to perform this task

**Comment by gorgobacka** [comment]
That's understandable. Thanks for the reply.
