### ISSUE TITLE
[Feature Request] List of downloaded books: Lazy loading on admin page for users

### ISSUE THREAD

**Issue by gorgobacka** [janeczku/calibre-web#1597]
**Is your feature request related to a problem? Please describe.**
When I want to change as an admin the settings for a user, I go to the user's page and I always need to wait till the complete list of books downloaded by the user and it's images are loaded. This is annoying when there are a lot.

**Describe the solution you'd like**
I would propose to also add a lazy loading here.

**Describe alternatives you've considered**
Display the list of books downloaded by the user and it's images on a subpage.

**Comment by OzzieIsaacs** [comment]
My solution is the following:
I moved the downloaded section from the user page to the left navbar. Now sorting and paged loading is supported
(Please check the newest commit version)
(See also #1625)

**Comment by gorgobacka** [comment]
Sounds great. Thanks. I will check it out.
