### ISSUE TITLE
Raspberry Pi OS (32-bit) - Errors when saving options

### ISSUE THREAD

**Issue by NeroLupo** [janeczku/calibre-web#1603]
**Describe the bug/problem**
Calibre-web stops working when I change and save a setting to the server or users. After that I get an error message in the browser (see screenshot below) and I can't access it anymore. Strangely enough, new users can be created and also configured in calibre-web. Only server and UI settings are affected by the error/crash.

Then the only thing that helps after the crash is `sudo systemctl stop cps.service` and `sudo systemctl start cps.service` and the previously changed settings are not applied. Also changing to "nightly" updates is not possible, because the error will appear as well.

Calibre-web runs on my Raspberry Pi 3b with the current system. I have already done `sudo apt-get update` and `sudo apt-get upgrade` (with `sudo reboot` afterwards) - unfortunately without success, the error occurs again when I'm changing settings in calibre-web. 

Since I am a beginner in this calibre-web topic, maybe you can help me what the problem is?

**Additional information:**
I have already performed a complete new installation of calibre-web. After that I can make some settings for a short time, but then the error described above occurs again and I cannot configure anything. So I have no idea where the problem could be.

I have installed as follows:
`sudo su`
`mkdir /var/www/calibre-web`
`git clone https://github.com/janeczku/calibre-web /var/www/calibre-web`
`cd /var/www/calibre-web`
`apt install python3-pip`
`python3 -m pip install --system --target vendor -r requirements.txt`

The service file contains the following:
`[Unit]`
`Description=Calibre Web`

`[Service]`
`type=simple`
`User=root`
`ExecStart=/usr/bin/python3 /var/www/calibre-web/cps.py`
`WorkingDirectory=/var/www/calibre-web`

`[Install]`
`WantedBy=multi-user.target`

Followed by `sudo systemctl enable cps.service`

After a restart the cps.service starts as it should and I can navigate normally, read books in browser or download them. Only when I want to change a setting the error occurs again.

**To Reproduce**
I don't know if there are steps to reproduce the behavior.

**Logfile**
latest logfile after the error occurred again and I stopped the cps.service:
[calibre-web.log](https://github.com/janeczku/calibre-web/files/5168049/calibre-web.log)

**Expected behavior**
Change server and user settings correctly.

**Screenshot**
![grafik](https://user-images.githubusercontent.com/68917950/92106722-1727cf00-ede5-11ea-912f-bda8b4268812.png)

**Environment (please complete the following information):**
 - OS: Raspberry Pi OS
 - Python version: python3.7
 - Calibre-Web version: 0.6.8
 - Docker container: [None/Technosoft2000/Linuxuser]: ?
 - Special Hardware: Rasperry Pi 3b
 - Browser: Chrome 85.0.4183.83, Firefox 80.0.1

**Comment by udo1toni** [comment]
At least I have a quite similar behavior.
But: all works as suggested, as long as I start calibre-web as user root. (e.g. sudo ./cps.py) I can change settings, create users and so on. But I don't want to start calibre-web as user root!
So, when starting calibre-web as a common user, calibre starts just fine, but stops working when changing settings. log complains about a read only database:
`OperationalError: (sqlite3.OperationalError) attempt to write a readonly database`
but all the files in calibre-web directory belong to the common user, so: how to get the database writable?

**Comment by wgibcus** [comment]
Where is your Calibre database located? Are permissions set correctly on this folder?

**Comment by OzzieIsaacs** [comment]
@udo1toni : Once you start calibre-web as root you create the settings database as user root, normal users can't write access the database later on for obvious reasons. Please delete app.db and start calibre-web as normal user (and not as root)

**Comment by OzzieIsaacs** [comment]
@NeroLupo : The error looks like it's trying to do a google drive configuration and enabling public registrating but this is not working. A restart is required after this type of error, this is correct. I have no Idea why this is not working
