### ISSUE TITLE
Allow anonymous downloads

### ISSUE THREAD

**Issue by damionx7** [janeczku/calibre-web#1611]
How should I allow anonymous downloads on OPDS ? I need this for moon reader. Currently I can browse the ebooks but not read or download.

**Comment by OzzieIsaacs** [comment]
As Admin with enabled anonymous browsing edit the rights of the First User and give the Guest User the Rights for downloading

**Comment by OzzieIsaacs** [comment]
If your questions is answered please close the issue

**Comment by bonnebulle** [comment]
In my case, I would like to allow download access for Guest ... but only for some type of files (images, jpg/png) 
I cant find this option, there is ?
Thanks
