### ISSUE TITLE
Feature request: Use more than one library

### ISSUE THREAD

**Issue by udo1toni** [janeczku/calibre-web#1615]
I'm using more than one library in calibre and would like to use them as well in calibre-web :) for now I have to change the library via administration.
One point of the separation of books to different libraries is to hide some books from under age readers. That could be covered with labels, but another point is how fast the library is loaded, and that's depending on the mass of books.

**Comment by wgibcus** [comment]
You can run multiple instances of Calibre-Web on different ports. For example, your fiction library could be on 8083 and your non-fiction on 8084. There is information on this in the wiki. I believe the different libraries feature is written in a specific language in Calibre and is not compatible with Calibre-Web.

**Comment by OzzieIsaacs** [comment]
This was discussed several times like in #1535, it's a: No, I'm not doing it
