### ISSUE TITLE
Is a Calibre-Web 0.6.9 perhaps possible this month, for Internet-in-a-Box 7.2's final release?

### ISSUE THREAD

**Issue by holta** [janeczku/calibre-web#1617]
Thanks @OzzieIsaacs if you can possibly consider a release in coming days &mdash; or when the situation allows?

Just fyi DRAFT Release Notes for Internet-in-a-Box (IIAB) 7.2 are converging quickly here:
https://github.com/iiab/iiab/wiki/IIAB-7.2-Release-Notes

Cheers & many thanks for considering what's possible, within the context of your release schedule!

**Comment by OzzieIsaacs** [comment]
Yes, the current master is quite stable, I have to fix one or 2 things. End of next week might be a possible release date

**Comment by OzzieIsaacs** [comment]
Mission accomplished: V0.6.9 is out

![grafik](https://user-images.githubusercontent.com/6438895/94360273-62fc2a00-00ac-11eb-8009-8720e57ebd15.png)
