### ISSUE TITLE
Partial load for recent download

### ISSUE THREAD

**Issue by Na0mir** [janeczku/calibre-web#1625]
Hello

First, thank you guys for all of your hard work! Calibre-web is awesome
I figured out that one of my user downloaded all my ~4000 books (I don't know how but that's not the point).
When I try to edit this user https://calibre.domain.tld/admin/user/4 the loading is incredibly slow because Calibre try to load the 4000 books. Is that possible to use the setting "Books per Page" here also ?

Thanks

**Comment by OzzieIsaacs** [comment]
My solution is the following:
I moved the downloaded section from the user page to the left navbar. Now sorting and  paged loading is supported 
(Please check the newest commit version)

**Comment by Na0mir** [comment]
Awesome thanks, I will try that when the next released is out!
