### ISSUE TITLE
Ability to enable auto-reconnect of Calibre Database

### ISSUE THREAD

**Issue by pratikpanchal22** [janeczku/calibre-web#1628]
### Current Implementation:
In version 0.6.8, each time the Calibre library is updated (add/remove/edit of books), an admin has to manually reconnect Calibre Database by clicking on the button named so under the 'Administration' section of admin tasks (screenshot).  

![image](https://user-images.githubusercontent.com/6437346/93891286-812aea00-fca8-11ea-8ad8-6a9b7300ec4a.png)
  
### Feature request:
This Issue is to request a feature to provide an option to admins to automate this process.  
  
### Possible solutions:
This can be done in 2 ways:
**1. Based on the change detection in Calibre Database:** One possible solution is to auto-reconnect the database when a change is detected.  
**2. Based on schedule:** This might be resource-intensive but simple: A configurable time field can be provided under admin tasks. A script runs on server that reconnects the Calibre database with a periodicity of that configured time.

**Comment by PeterJT** [comment]
See issue #1557

**Comment by pratikpanchal22** [comment]
Thank you!
