### ISSUE TITLE
Error Gevent SSL

### ISSUE THREAD

**Issue by yeraycito** [janeczku/calibre-web#1629]
**Describe the bug/problem**
Error Gevent ssl. Software: Linux Mint
I have a letsencrypt ssl certificate installed in calibre
![Captura de pantalla de 2020-09-22 19-14-16](https://user-images.githubusercontent.com/65027248/93915855-eadae080-fd08-11ea-916d-3b097a6de673.png)
-web to access it from outside via https. The funny thing about the case is that the access by https is done without problems but in the terminal it gives this error.
**To Reproduce**

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10/Raspberry Pi OS]
 - Python version: [e.g. python2.7]
 - Calibre-Web version: [e.g. 0.6.8 or 087c4c59 (git rev-parse --short HEAD)]:
 - Docker container: [None/Technosoft2000/Linuxuser]:
 - Special Hardware: [e.g. Rasperry Pi Zero]
 - Browser: [e.g. Chrome 83.0.4103.97, Safari 13.3.7, Firefox 68.0.1 ESR]

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

**Comment by OzzieIsaacs** [comment]
I'm aware of it. 
I also don't know the reason, as you mentioned it's working

**Comment by OzzieIsaacs** [comment]
I think I understood it (maybe). For me it's like the following: I open a tab in my browser, enter the address and the traceback error is shown several times, afterwards I can browser the page without any trouble, no further error message is shown. 
I tried to analyse the communication packages and it looks to my like the first comunication is started with TLS1.0, which is answered with change chipher spec, subsequently all communication is marked as TLS1.2. So the traceback could be related to old chipher spec which are rejected. (??? I have no really knowledge about the encryption stuff ???) 
I also tried to find a way to disable the output, but I failed (the errors are not logged via the normal logging function, I haven't found a method to redirect the output)

**Comment by yeraycito** [comment]
Thank you very much for trying to fix it. The good thing is that it works.

**Comment by OzzieIsaacs** [comment]
Issue is reported: https://github.com/gevent/gevent/issues/1681

My confidence in the open source community regarding fixing issues is not so high anymore (I'm no exception), so I can't promise anything

**Comment by OzzieIsaacs** [comment]
I got feedback and implemented a corresponding fix, please update to the newest commit version. You still get the error message, as they are valid, but no traceback output on stderr

**Comment by yeraycito** [comment]
Thank you very much
