### ISSUE TITLE
Ldap login installation issue

### ISSUE THREAD

**Issue by cjiwonder** [janeczku/calibre-web#1631]
Calibre-web latest version installed in Windows 2019 Server and installed python_ldap-3.3.1-cp38-cp38-win_amd64.whl for LDAP authentication but LDAP options are showing under "Admin" section "Basic Configuration", "Feature Configuration". 

Is there any other prerequisite tools / configurations required to enable LDAP authentication?

Thanks in advance.

**Comment by OzzieIsaacs** [comment]
You also need Flask-SimpleLDAP, as listed in optional-requirements.txt in the root folder

**Comment by OzzieIsaacs** [comment]
If you problem, could be solved, this this hint, it would be great if you could close the issue. 

Otherwise, please fill out the "bug-report form" and please also provide the list from the "about section" regarding the installed dependencies. The logfile in debug mode should also give a hint like: ldap login is not available: ...

**Comment by cjiwonder** [comment]
> Flask-SimpleLDA

Thanks for your prompt response.

While running Flask-SimpleLDAP, I am getting the following error could you pls help me to resolve this error. Already Microsoft Visual C++ 15.0 installed.

Installing collected packages: Werkzeug, MarkupSafe, Jinja2, itsdangerous, click, Flask, pyasn1, pyasn1-modules, python-ldap, Flask-SimpleLDAP
    Running setup.py install for python-ldap ... error
    ERROR: Command errored out with exit status 1:
     command: 'd:\python\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\2\\pip-install-wihm7p2i\\python-ldap\\setup.py'"'"'; __file__='"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\2\\pip-install-wihm7p2i\\python-ldap\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Administrator\AppData\Local\Temp\2\pip-record-4bbwcqjf\install-record.txt' --single-version-externally-managed --home 'C:\Users\Administrator\AppData\Local\Temp\2\pip-target-hkuo3b0z' --compile --install-headers 'C:\Users\Administrator\AppData\Local\Temp\2\pip-target-hkuo3b0z\include\python\python-ldap'
         cwd: C:\Users\Administrator\AppData\Local\Temp\2\pip-install-wihm7p2i\python-ldap\
    Complete output (73 lines):
    running install
    running build
    running build_py
    creating build\lib.win-amd64-3.8
    copying Lib\ldapurl.py -> build\lib.win-amd64-3.8
    copying Lib\ldif.py -> build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\ldap
    copying Lib\ldap\async.py -> build\lib.win-amd64-3.8\ldap
    copying Lib\ldap\asyncsearch.py -> build\lib.win-amd64-3.8\ldap
    copying Lib\ldap\cidict.py -> build\lib.win-amd64-3.8\ldap
    copying Lib\ldap\compat.py -> build\lib.win-amd64-3.8\ldap
    copying Lib\ldap\constants.py -> build\lib.win-amd64-3.8\ldap
    copying Lib\ldap\dn.py -> build\lib.win-amd64-3.8\ldap
    copying Lib\ldap\filter.py -> build\lib.win-amd64-3.8\ldap
    copying Lib\ldap\functions.py -> build\lib.win-amd64-3.8\ldap
    copying Lib\ldap\ldapobject.py -> build\lib.win-amd64-3.8\ldap
    copying Lib\ldap\logger.py -> build\lib.win-amd64-3.8\ldap
    copying Lib\ldap\modlist.py -> build\lib.win-amd64-3.8\ldap
    copying Lib\ldap\pkginfo.py -> build\lib.win-amd64-3.8\ldap
    copying Lib\ldap\resiter.py -> build\lib.win-amd64-3.8\ldap
    copying Lib\ldap\sasl.py -> build\lib.win-amd64-3.8\ldap
    copying Lib\ldap\syncrepl.py -> build\lib.win-amd64-3.8\ldap
    copying Lib\ldap\__init__.py -> build\lib.win-amd64-3.8\ldap
    creating build\lib.win-amd64-3.8\ldap\controls
    copying Lib\ldap\controls\deref.py -> build\lib.win-amd64-3.8\ldap\controls
    copying Lib\ldap\controls\libldap.py -> build\lib.win-amd64-3.8\ldap\controls
    copying Lib\ldap\controls\openldap.py -> build\lib.win-amd64-3.8\ldap\controls
    copying Lib\ldap\controls\pagedresults.py -> build\lib.win-amd64-3.8\ldap\controls
    copying Lib\ldap\controls\ppolicy.py -> build\lib.win-amd64-3.8\ldap\controls
    copying Lib\ldap\controls\psearch.py -> build\lib.win-amd64-3.8\ldap\controls
    copying Lib\ldap\controls\pwdpolicy.py -> build\lib.win-amd64-3.8\ldap\controls
    copying Lib\ldap\controls\readentry.py -> build\lib.win-amd64-3.8\ldap\controls
    copying Lib\ldap\controls\sessiontrack.py -> build\lib.win-amd64-3.8\ldap\controls
    copying Lib\ldap\controls\simple.py -> build\lib.win-amd64-3.8\ldap\controls
    copying Lib\ldap\controls\sss.py -> build\lib.win-amd64-3.8\ldap\controls
    copying Lib\ldap\controls\vlv.py -> build\lib.win-amd64-3.8\ldap\controls
    copying Lib\ldap\controls\__init__.py -> build\lib.win-amd64-3.8\ldap\controls
    creating build\lib.win-amd64-3.8\ldap\extop
    copying Lib\ldap\extop\dds.py -> build\lib.win-amd64-3.8\ldap\extop
    copying Lib\ldap\extop\passwd.py -> build\lib.win-amd64-3.8\ldap\extop
    copying Lib\ldap\extop\__init__.py -> build\lib.win-amd64-3.8\ldap\extop
    creating build\lib.win-amd64-3.8\ldap\schema
    copying Lib\ldap\schema\models.py -> build\lib.win-amd64-3.8\ldap\schema
    copying Lib\ldap\schema\subentry.py -> build\lib.win-amd64-3.8\ldap\schema
    copying Lib\ldap\schema\tokenizer.py -> build\lib.win-amd64-3.8\ldap\schema
    copying Lib\ldap\schema\__init__.py -> build\lib.win-amd64-3.8\ldap\schema
    creating build\lib.win-amd64-3.8\slapdtest
    copying Lib\slapdtest\_slapdtest.py -> build\lib.win-amd64-3.8\slapdtest
    copying Lib\slapdtest\__init__.py -> build\lib.win-amd64-3.8\slapdtest
    running egg_info
    writing Lib\python_ldap.egg-info\PKG-INFO
    writing dependency_links to Lib\python_ldap.egg-info\dependency_links.txt
    writing requirements to Lib\python_ldap.egg-info\requires.txt
    writing top-level names to Lib\python_ldap.egg-info\top_level.txt
    reading manifest file 'Lib\python_ldap.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'Doc\.build'
    writing manifest file 'Lib\python_ldap.egg-info\SOURCES.txt'
    creating build\lib.win-amd64-3.8\slapdtest\certs
    copying Lib\slapdtest\certs\README -> build\lib.win-amd64-3.8\slapdtest\certs
    copying Lib\slapdtest\certs\ca.conf -> build\lib.win-amd64-3.8\slapdtest\certs
    copying Lib\slapdtest\certs\ca.pem -> build\lib.win-amd64-3.8\slapdtest\certs
    copying Lib\slapdtest\certs\client.conf -> build\lib.win-amd64-3.8\slapdtest\certs
    copying Lib\slapdtest\certs\client.key -> build\lib.win-amd64-3.8\slapdtest\certs
    copying Lib\slapdtest\certs\client.pem -> build\lib.win-amd64-3.8\slapdtest\certs
    copying Lib\slapdtest\certs\gencerts.sh -> build\lib.win-amd64-3.8\slapdtest\certs
    copying Lib\slapdtest\certs\gennssdb.sh -> build\lib.win-amd64-3.8\slapdtest\certs
    copying Lib\slapdtest\certs\server.conf -> build\lib.win-amd64-3.8\slapdtest\certs
    copying Lib\slapdtest\certs\server.key -> build\lib.win-amd64-3.8\slapdtest\certs
    copying Lib\slapdtest\certs\server.pem -> build\lib.win-amd64-3.8\slapdtest\certs
    running build_ext
    building '_ldap' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'd:\python\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\2\\pip-install-wihm7p2i\\python-ldap\\setup.py'"'"'; __file__='"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\2\\pip-install-wihm7p2i\\python-ldap\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Administrator\AppData\Local\Temp\2\pip-record-4bbwcqjf\install-record.txt' --single-version-externally-managed --home 'C:\Users\Administrator\AppData\Local\Temp\2\pip-target-hkuo3b0z' --compile --install-headers 'C:\Users\Administrator\AppData\Local\Temp\2\pip-target-hkuo3b0z\include\python\python-ldap' Check the logs for full command output.

**Comment by cjiwonder** [comment]
Fresh installation : Result

Using legacy 'setup.py install' for Flask-Principal, since package 'wheel' is not installed.
Using legacy 'setup.py install' for iso-639, since package 'wheel' is not installed.
Using legacy 'setup.py install' for PyPDF2, since package 'wheel' is not installed.
Using legacy 'setup.py install' for blinker, since package 'wheel' is not installed.
Installing collected packages: pytz, Babel, MarkupSafe, Jinja2, click, itsdangerous, Werkzeug, Flask, Flask-Babel, Flask-Login, blinker, Flask-Principal, six, singledispatch, backports-abc, iso-639, PyPDF2, idna, chardet, urllib3, certifi, requests, SQLAlchemy, tornado, Wand, unidecode
    Running setup.py install for blinker ... done
    Running setup.py install for Flask-Principal ... done
    Running setup.py install for iso-639 ... done
    Running setup.py install for PyPDF2 ... done
Successfully installed Babel-2.8.0 Flask-1.1.2 Flask-Babel-1.0.0 Flask-Login-0.5.0 Flask-Principal-0.4.0 Jinja2-2.11.2 MarkupSafe-1.1.1 PyPDF2-1.26.0 SQLAlchemy-1.3.19 Wand-0.5.9 Werkzeug-1.0.1 backports-abc-0.5 blinker-1.4 certifi-2020.6.20 chardet-3.0.4 click-7.1.2 idna-2.10 iso-639-0.4.5 itsdangerous-1.1.0 pytz-2020.1 requests-2.23.0 singledispatch-3.4.0.3 six-1.15.0 tornado-6.0.4 unidecode-1.1.1 urllib3-1.25.10

While starting Service :

D:\Python>"D:\Python\python.exe" "D:\calibre\cps.py"
Traceback (most recent call last):
  File "D:\calibre\cps.py", line 34, in <module>
    from cps import create_app
  File "D:\calibre\cps\__init__.py", line 28, in <module>
    from babel import Locale as LC
ModuleNotFoundError: No module named 'babel'

**Comment by OzzieIsaacs** [comment]
I never build python-ldap on my own, so I can't help with that. Using the wheel from your first post is a good idea.

From the bug template I would know which OS, python version you are using, If you try the latest release or a git clone, if you where using docker, otherwise I would have to guess everything (I don't like this). Would be really great if you could find the time to fill it out (specially the environment section, I pasted it into this post)

From the errors I feel you might have installed more than one python version and also might get mixed up with x86 and x64. So it would be good to know the complete paths of the commands you've been running.

`ModuleNotFoundError: No module named 'babel'`
vs. 
`Successfully installed Babel-2.8.0`

-> seems to be different python environment, 
Did you use virtual-environment? 
or installed it with the recommendation from the readme? Is the vendor folder in parallel to the cps folder (absolutly mandatory)?

...

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10/Raspberry Pi OS]
 - Python version: [e.g. python2.7]
 - Calibre-Web version: [e.g. 0.6.8 or 087c4c59 (git rev-parse --short HEAD)]:
 - Docker container: [None/Technosoft2000/Linuxuser]:
 - Special Hardware: [e.g. Rasperry Pi Zero]
 - Browser: [e.g. Chrome 83.0.4103.97, Safari 13.3.7, Firefox 68.0.1 ESR]

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

...

**Comment by cjiwonder** [comment]
I just downloaded Flask_SimpleLDAP-1.4.0-py3-none-any.whl from https://pypi.org/project/Flask-SimpleLDAP/#files and got working.

Thank you so much support.

**Comment by cjiwonder** [comment]
I can't import LDAP users, it's throwing "operations error"

My configuration looks like this:
LDAP server: "ip-address"
Server Port:389
LDAP Encryption: None
LDAP Authentication: Simple
LDAP Administrator Username: cn="...",ou=...,ou=...,dc=...,dc=...,dc=...
LDAP Distinguished Name: ou=...,ou=...,dc=...,dc=...,dc=...
LDAP User filter: (&(objectclass=user)(samaccountname=%s))
LDAP Group Object Filter: (&(objectclass=group)(cn=%s))
LDAP Group Name: staff
LDAP Group Members Field: memberUid

Could you help me to resolve this please?

**Comment by OzzieIsaacs** [comment]
> Otherwise, please fill out the "bug-report form" and please also provide the list from the "about section" regarding the installed dependencies. The logfile in debug mode should also give a hint like: ldap login is not available: ...

No log -> I have no idea about error message, I can not help you if you don't give me all information you are having

For me it's working

**Comment by cjiwonder** [comment]
Sorry, where to get the logs? already I have enabled calibre-web log and access log but I cant find any logs in that with regard to ad login. Pls guide me to get ad logs.

**Comment by OzzieIsaacs** [comment]
The logfiles should be in the root folder of calibre-web (calibre-web.log). Or you can view them in admin section "view logfiles"

**Comment by cjiwonder** [comment]
Yes, I am checking calibre-web.log from admin section-> "view logs" but I cant see any logs in that with regard to ad login.

**Comment by OzzieIsaacs** [comment]
> I can't import LDAP users, it's throwing "operations error"
The text of the error message should be longer, and there should be a corresponding entry in the log file. You could paste the whole logfile from the relevant timeframe and I have a look. Important: Log-Level set to DEBUG before (admin section -> basic configuration -> log Configuration -> Loglevel)

**Comment by OzzieIsaacs** [comment]
>... I cant see any logs in that with regard to ad login.

vs.

>  in that with regard to ad login.

What is your Problem? Login or user import?
I'd like to encourage you once again to clearly describe what you did, what your problem is, also your expectation, the error message and so on. The issue form will guide you through this process. 
I can't help you otherwise

**Comment by cjiwonder** [comment]
I cant login with AD user login and I cant import users from AD too.

 Here is the logs:

[2020-09-24 18:09:01,726] DEBUG {cps.services:29} Cannot import goodreads, showing authors-metadata will not work: No module named 'betterreads'
[2020-09-24 18:09:02,465] DEBUG {cps.services:45} Cannot import SyncToken, syncing books with Kobo Devices will not work: No module named 'jsonschema'
[2020-09-24 18:09:03,398] DEBUG {cps.gdriveutils:58} Cannot import pydrive,httplib2, using gdrive will not work: No module named 'pydrive'
[2020-09-24 18:09:03,499] DEBUG {cps.comic:44} Cannot import comicapi, extracting comic metadata will not work: No module named 'comicapi'
[2020-09-24 18:09:03,499] DEBUG {cps.comic:51} Cannot import rarfile, extracting cover files from rar files will not work: No module named 'rarfile'
[2020-09-24 18:09:03,668] DEBUG {cps.uploader:44} Cannot import Image, generating pdf covers for pdf uploads will not work: MagickWand shared library not found.
You probably had not installed ImageMagick library.
Try to install:
  http://docs.wand-py.org/en/latest/guide/install.html#install-imagemagick-on-windows
[2020-09-24 18:09:03,900] DEBUG {cps.uploader:59} Cannot import epub, extracting epub metadata will not work: No module named 'lxml'
[2020-09-24 18:09:03,900] DEBUG {cps.uploader:66} Cannot import fb2, extracting fb2 metadata will not work: No module named 'lxml'
[2020-09-24 18:09:03,900] DEBUG {cps.uploader:74} Cannot import Pillow, using png and webp images as cover will not work: No module named 'PIL'
[2020-09-24 18:09:03,915] DEBUG {cps.admin:64} Cannot import Flask-Dance, login with Oauth will not work: No module named 'flask_dance'


[2020-09-24 18:09:03,915] DEBUG {cps.gdrive:46} Cannot import googleapiclient, using GDrive will not work: No module named 'googleapiclient'
[2020-09-24 18:09:03,931] DEBUG {cps.cache_buster:45} Computing cache-busting values...
[2020-09-24 18:09:30,126] DEBUG {cps.cache_buster:58} Finished computing cache-busting values

**Comment by OzzieIsaacs** [comment]
I give you a last chance: 
I asked you for providing complete data about your environment, the error message, a clear and consistent description of your problem, a description of what you are exactly doing and so on (more information is better) 
If you can't provide this it makes no sense to discuss this further and I will close the issue.
The logfile you provided shows no single login attempt, and therefore no errors.

**Comment by cjiwonder** [comment]
Sorry for the late reply, my primary issue is that I can't login with AD username and password and "import LDAP users" is also not working.

I can't see any logs related to AD authentication in the calibre-web.log. For testing purpose, I entered wrong password in the Login type -> LDAP authentication, it is throwing log "[2020-09-28 14:38:48,982] DEBUG {cps.web:319} Invalid credentials" but when I tried to login with AD username and password or "import LDAP users", it is not at all throwing any logs.

Could you please take my server remotely and check? My anydesk Id is 917 521 924
