### ISSUE TITLE
HTML code access for WYSIWYG editor

### ISSUE THREAD

**Issue by wgibcus** [janeczku/calibre-web#1634]
**Is your feature request related to a problem? Please describe.**
Is it possible to add a "code view" for the WYSIWYG editor for the description? I wish to add URLs in the description.

**Describe the solution you'd like**
A code view or "add a link" button for the editor or button customisation options. Alternatively, a different WYSIWYG editor.

**Describe alternatives you've considered**
It seems as if tinymce is used but that's all I know. I'm happy to try out any changes and have a working knowledge of editing code.

**Comment by OzzieIsaacs** [comment]
A plugin to tinymce is needed to do so:
https://www.tiny.cloud/docs/plugins/code/

**Comment by wgibcus** [comment]
Excellent! Issue resolved, thank you very much

**Comment by OzzieIsaacs** [comment]
Feel free to create a PR if you have coded it
