### ISSUE TITLE
Reverse proxy suddenly not working after update: 502 Error

### ISSUE THREAD

**Issue by vurtomatic** [janeczku/calibre-web#1635]
**Describe the bug/problem**
Used the sample reverse proxy from here, used to work and now the browser is giving me a 502 Error.

> #Config for Calibre Web
	location ^~ /calibre/ {
		auth_basic "Restricted";
 	    auth_basic_user_file /config/nginx/.htpasswd;
 	    include /config/nginx/proxy.conf;
		proxy_bind              $server_addr;
		proxy_pass              http://192.168.1.252:8083;
		proxy_set_header        Host            $http_host;
		proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header        X-Scheme        $scheme;
		proxy_set_header        X-Script-Name   /calibre;
	}

Did something change with Calibre-Web? I had a look at the sample config and it's still the same.

**Comment by OzzieIsaacs** [comment]
No, nothing changed
