### ISSUE TITLE
Metadata not correctly loaded from epub after uploading

### ISSUE THREAD

**Issue by amasolini** [janeczku/calibre-web#1637]
**Describe the bug/problem**
Uploading an epub file to calibre-web doesn't load all the metadata. The only information that is loaded from the metadata is the cover, the book title and the author.
I compared the metadata that Calibre was able to get. I'm attaching 2 screenshots for you to see.

**To Reproduce**
1. Upload an epub file to Calibre Web
2. Take note of the metadata that was loaded
3. Add the same book to Calibre and take note of the medatadata that was loaded
4. Compare the metadata from Calibre-web and Calibre.

**Logfile**
`[2020-09-27 08:06:52,607] DEBUG {cps.uploader:208} Temporary file: /tmp/calibre_web/5c94f6aae45965b4c3b3fcb27b115b10
[2020-09-27 08:06:53,627]  INFO {cps.worker:209} 1
[2020-09-27 08:06:53,627]  INFO {cps.worker:210} 2`

**Expected behavior**
I expect the following metadata to be loaded:
* Identifiers
* Publisher
* Published Date
* Language
* ...

**Screenshots**
Screenshot from Calibre metadata:
![image](https://user-images.githubusercontent.com/5497345/94364664-11ab6500-00c3-11eb-9f15-d81753a82169.png)

Screenshot from Calibre-Web metadata:
![image](https://user-images.githubusercontent.com/5497345/94364688-2daf0680-00c3-11eb-82f4-5b0d014d6bcb.png)

**Environment (please complete the following information):**
 - OS: CentOS 8.2.2004 (Linux 4.18.0 #1 SMP Mon Dec 9 19:36:21 MSK 2019 x86_64 x86_64)
 - Python version: 3.8.0 (default, May 7 2020, 02:49:39) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]]
 - Calibre-Web version: 0.6.9 - a9c0bcb4a2441b0171966cfc32c60b6cf677c590 - 2020-09-27T07:15:03+02:00
 - Docker container: None
 - Special Hardware: None
 - Browser: 85.0.4183.121 (Official Build) (64-bit)

**Additional context**
This was happening also with version 0.6.8 of calibre-web. I haven't tried with other versions.

**Comment by OzzieIsaacs** [comment]
The publisher, identifiers, publishing date are indeed not extracted by calibre-web, that's right.
Why: Nobody asked for it before. I'll have a look, I should find enough example books to gather test data

**Comment by OzzieIsaacs** [comment]
Remark: The Language is already extracted (and now working again for non english UIs), as shown on the screenshot

**Comment by amasolini** [comment]
Thank you very much @OzzieIsaacs for confirming this is actually how Calibre Web works.

**Comment by OzzieIsaacs** [comment]
No you are right, metadata extraction can be improved (i's a key feature of calibre web)
