### ISSUE TITLE
Performance: CPU, Memory?

### ISSUE THREAD

**Issue by blueteq** [janeczku/calibre-web#1640]
Hi, I have everything up and running, and works well. 
It's on a VPS with 1GB RAM and 1 CPU, so everything loads really slowly and Panel on iPad times out on download. 

What should I upgrade? Memory or go to Dedicated CPU?

PS: is there an IRC or other community where I can ask these questions instead of logging an issue?

**Comment by OzzieIsaacs** [comment]
> PS: is there an IRC or other community

Not as far as I know

> What should I upgrade? Memory or go to Dedicated CPU?

I can not guarantee it, but I think CPU power is more needed as RAM

**Comment by blueteq** [comment]
I have upgraded my server on Linode to dedicated CPU and 4GB Memory, there is a small improvement but nothing dramatic. 

Thanks
