### ISSUE TITLE
SQLAlchemy requirement needs to be >= 1.3.0.

### ISSUE THREAD

**Issue by dfn-certling** [janeczku/calibre-web#1641]
This is related to #1572 and #1609. requirements.txt states that SQLAlchemy needs to be >= 1.1.0. But JSON support for sqlite was added to SQLAlchemy only with 1.3, see https://github.com/sqlalchemy/sqlalchemy/issues/3850.

The minimum version requirement of SQLAlchemy should be 1.3.0.

**Comment by OzzieIsaacs** [comment]
You are right, thanks for pointing it out
