### ISSUE TITLE
Editing metadata in Chinese prompts "bootstrap-datepicker.zh_Hans_CN.min.js" does not exist

### ISSUE THREAD

**Issue by rainsuns** [janeczku/calibre-web#1642]
Platform:Windows 10 10.0.19041 
Python:3.8.5 
Calibre_Web:0.6.10 Beta
WebServer:Tornado 6.0.4

https://github.com/janeczku/calibre-web/tree/master/cps/static/js/libs/bootstrap-datepicker/locales

![151](https://user-images.githubusercontent.com/26184114/94639770-8d99ed00-030f-11eb-832c-216ca3867f5e.png)

**Comment by OzzieIsaacs** [comment]
Sorry, it's fixed in the newest commit
