### ISSUE TITLE
highlight on pdf and epub

### ISSUE THREAD

**Issue by BrunoTeixeira1996** [janeczku/calibre-web#1645]
Hey, i wanted to know if you guys will add anything to do highlights in pdf and epub folders
Thats realy important and its the only thing that i need and it does not have

Thanks

**Comment by almereyda** [comment]
You could try to leverage hypothes.is for that matter. They provide a Chromium plugin and a Firefox bookmarklet, which injects their client to the current webpage.

Else one could also integrate hypothes.is via a plugin, and always display its annotations in the calibre-web client, but keep them in that cloud service for referencing from the outside.

Another way could be to integrate the Open Annotator project. Or an independent implementation of the Web Annotation standard, ref.: https://www.w3.org/annotation/
