### ISSUE TITLE
Read in browser button

### ISSUE THREAD

**Issue by entryb** [janeczku/calibre-web#1648]
Updated my docker container to latest yesterday 0.6.9 and seems my view in browser button has disappeared , has it been removed or so? Logs at debug level show no errors

Expected behavior
read in browser button available

Environment
Docker container: my own
Firefox : 81.0.1 (64-bit) windows 10

![Capture](https://user-images.githubusercontent.com/44838864/94988943-46ab3200-0571-11eb-8fbd-db6e865196f4.PNG)

**Comment by OzzieIsaacs** [comment]
Please check if your account has the right to view books (admin section -> edit user), the access rights were split (before is was download+read now it's download and read separate)

**Comment by entryb** [comment]
> 
> 
> Please check if your account has the right to view books (admin section -> edit user), the access rights were split (before is was download+read now it's download and read separate)

That was it,cheers! Also thanks a lot for this awesome software!
