### ISSUE TITLE
Is it possible to hide books in private book collection ?

### ISSUE THREAD

**Issue by ferocknew** [janeczku/calibre-web#165]
as title

**Comment by OzzieIsaacs** [comment]
I don't know what you mean? Private Collection equals to a non public shelf? Why do you want to hide them? Do you want to delete them from shelfs?
If you want to delete the book from a shelf you have to go to the detailed book page and click on the little cross beside the shelf name.

**Comment by OzzieIsaacs** [comment]
No response for long time.
