### ISSUE TITLE
User list too long, pagination feature wanted

### ISSUE THREAD

**Issue by vagra** [janeczku/calibre-web#1651]
**Is your feature request related to a problem? Please describe.**
User list too long in the /admin/view page. I have nearly 300 users now.

**Describe the solution you'd like**
Add pagination feature to User list.

**Comment by vagra** [comment]
Simply moving the user list to the bottom of the admin page can also be solved.

**Comment by OzzieIsaacs** [comment]
Max 10 Users are listed meanwhile, everything else can be accessed via a filterable table
