### ISSUE TITLE
Question: Plex as OAuth provider?

### ISSUE THREAD

**Issue by PriamX** [janeczku/calibre-web#1652]
I've just installed calibre-web today. In the documentation I see instructions for setting up OAuth with Github and Google. I'm wondering, are these just examples of how to use OAuth and calibre-web, for instance, can calibre-web be set up to work with Plex OAuth (what I'd like to do)? Or would this feature require further development?

Thanks!
-Mike

**Comment by OzzieIsaacs** [comment]
Plex is not supported out of the box by flask-dance (the lib which is used by calibre-web to support oauth).
I decided to not extend calibre-web regarding login routines and so on anymore (https://github.com/janeczku/calibre-web/blob/master/CONTRIBUTING.md#feature-request). I'd like to focus more on the core feature of calibre-web: Manage books!

**Comment by OzzieIsaacs** [comment]
Google and Github are the only supported OAuth provider

**Comment by PriamX** [comment]
Thank you.
