### ISSUE TITLE
cli: init and migrate subcommands

### ISSUE THREAD

**Issue by gramakri** [janeczku/calibre-web#1656]
**Is your feature request related to a problem? Please describe.**
I am currently implementing a Docker based package for calibre-web (this is for Cloudron). calibre-web inits/migrates when run and continues to start the web server. The settings are loaded on start up. This means that if the package initializes settings after start up, those configs are not picked up. So, I have to start calibre-web, initialize settings in db, kill the server and start it up again.

**Describe the solution you'd like**
 It will be helpful to have "cps.py init" or "cps.py migrate" which initializes and runs the database migrations.

**Describe alternatives you've considered**
All I can think of is to start it up, initialize and restart the web app.

**Additional context**
https://git.cloudron.io/cloudron/calibre-web-app/-/blob/master/start.sh#L62 is how I do it currently.

**Comment by gramakri** [comment]
I am not a python programmer, so here's my basic analysis. We can implement subcommands in the cli.py like https://docs.python.org/dev/library/argparse.html#sub-commands . Two subcommands "start" and "migrate" should do it with "start" being the default for compatibility like right now.

A complete alternate solution is to reload the configuration when the server receives a signal or something. I don't know of many web servers that do this (many linux daemons do), so I am not sure if you like this idea. But something like this to nudge the web app to reload configuration is also OK.

**Comment by gramakri** [comment]
Depending on your answer here, I would also like to have a "import_ldap_users" subcommand which can be invoked on startup or with some cronjob.

**Comment by gramakri** [comment]
@OzzieIsaacs I don't know how easy/hard this is, but will you accept this change if I make a PR?

**Comment by OzzieIsaacs** [comment]
I need some time to think on it. I give you feedback this weekend

**Comment by gramakri** [comment]
@OzzieIsaacs Did you have any thoughts on this? The `import_ldap_users` subcommand is probably more important than the start up initialization sequence which I can work around. To be clear, what I am asking is if I am implement it, would you be open to merging it? Thanks!

**Comment by OzzieIsaacs** [comment]
Sorry, for not giving you feedback, I'm getting constantly new issues and sometimes one get's lost. 
So the commandline interface you suggest would be:
1) python cps.py [start] -> behavior as now, with all the parameters we are having currently (https://github.com/janeczku/calibre-web/wiki/Command-Line-Interface) having [start] optional for compatibility  
2) python cps.py config -m -> create/migrate settings database and quit
3) python cps.py config -l -> import ldap users and quit

The current parameter p and g have to be global (so you can still specify the location of the database together with the configs you suggest. The version parameter stays also global, where i, c, k are part of the start subcommand

Where it would be nice or even required that  3) could be run with a running cps instance, right? 
2) could only be run if the calibre-web server isn't running.

I think for the no of parameters we are having now, it would be sufficient to have an additional parameter -m  and -l without subcommands. I think subcommands make sense if we had to specify additional options based on the paramters like import users and have an option to limit the no of users, or migrate database  and optional delete users (example makes no sense).

My suggestion is: keep it easy, implement the 2 parameters, and I will merge it.

**Comment by Grienauer** [comment]
+1

**Comment by OzzieIsaacs** [comment]
Please create a PR if you are finished. I'll close the issue up to then
