### ISSUE TITLE
Add book to database via email

### ISSUE THREAD

**Issue by FPMilan** [janeczku/calibre-web#1658]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Send a mail to a configured address with the ebook attached and calibre-web will add it to it's database

**Describe alternatives you've considered**
Alternative is to use calibre Desktop Version what is sometimes a struggle

**Additional context**
-

**Comment by OzzieIsaacs** [comment]
From the user perspective this sounds feasible. From the programmers perspective not so much.
This would require to have calibrew-web running it own e-mail server with all the programming effort, or alternativly watch a imap email folder for changes. I'm not happy with both of the solutions, so I decided not to implement this feature.
