### ISSUE TITLE
Advanced Search Issues

### ISSUE THREAD

**Issue by celogeek** [janeczku/calibre-web#1660]
**Describe the bug/problem**
The advanced search has several problems.

- no filter failed with error 500
- next page return to advance search form instead of getting next page

**To Reproduce**
1. Go to advanced search
2. Click on search
3. you got a error 500

in the function render_adv_search_results, this end with:
```
    return render_title_template('search.html',
                                 adv_searchterm=searchterm,
                                 pagination=pagination,
                                 entries=q[offset:limit_all],
                                 result_count=result_count,
                                 title=_(u"Advanced Search"), page="advsearch")
```
But offset, limit_all and result_count are only defined if
```
if include_tag_inputs or exclude_tag_inputs or include_series_inputs or exclude_series_inputs or \
        include_languages_inputs or exclude_languages_inputs or author_name or book_title or \
        publisher or pub_start or pub_end or rating_low or rating_high or description or cc_present or \
        include_extension_inputs or exclude_extension_inputs:
```

Another problem, is pagination, next page go back to advance search form:
1. Go to advanced search
2. Select a filter that return more than 1 page
3. click on page 2

**Logfile**
None, if need I can but it is easy to reproduce

**Expected behavior**
We should be able to click on search without crash and go to page 2 or more on a long results.

**Screenshots**

**Environment (please complete the following information):**
 - OS: MacOS 10.15.6
 - Python version: 3.8.5
 - Calibre-Web version: d128b037
 - Browser: Opera

**Additional context**
I run python cps.py directly.

**Comment by OzzieIsaacs** [comment]
I'll try to have a look at it this weekend

**Comment by OzzieIsaacs** [comment]
It's almost fixed, one last issue is remaining, the selection of the buttons (include, exclude ..) is currently not working anymore

**Comment by OzzieIsaacs** [comment]
Everything should work again, thanks for reporting

**Comment by celogeek** [comment]
Yes it is ! thanks

One more thing: https://github.com/janeczku/calibre-web/pull/1659
This make search on read status works again.
