### ISSUE TITLE
Terrible UI location for 'Delete User' checkbox

### ISSUE THREAD

**Issue by JeremyMahieu** [janeczku/calibre-web#1664]
**Describe the bug/problem**
The location of the "Delete User" checkbox is terrible. It gives the impression (to me at least) that you are give the user the right to delete users. But in fact you are deleting this user. It doesn't make any sense to put it there. Better would be a red button, that gives a confirmation popup.

**To Reproduce**
1. http://.../admin/user/1

**Expected behavior**
Expected to give user rights to delete user.

**Screenshots**
![image](https://user-images.githubusercontent.com/23409814/96143864-d3f06e00-0f03-11eb-8279-9e2e440088b1.png)

**Environment (please complete the following information):**
 - Docker container: technosoft2000/calibre-web

**Comment by OzzieIsaacs** [comment]
For deleting users a user should have admin rights. 
I agree with you, doing delete with a checkbox is not consistent to the Userinterface in similar situations (merge books, delete books). I will change it to a (red) button

**Comment by OzzieIsaacs** [comment]
It's changed in the newest commit:
![grafik](https://user-images.githubusercontent.com/6438895/103478886-035b9c00-4dca-11eb-853a-b99e29c8efbf.png)
