### ISSUE TITLE
next page on result list does not work

### ISSUE THREAD

**Issue by kero242** [janeczku/calibre-web#1666]
**Describe the bug/problem**

in the result list of a search that goes over several pages, turning to the next page does not work

**To Reproduce**

Search result that is more than the number of books per page

**Logfile**

can provide if necessary

**Expected behavior**

next page should be displayed 

**Environment (please complete the following information):**

 - OS:debian 10.6
 - Python version: Python 3.7.3
 - Calibre-Web version: 0.6.10 Beta - 2020-10-14
 - Browser:chrome,firefox

**Comment by yeraycito** [comment]
Something similar happens to me. On the first page when I start the program ( 60 books per page ), I see the 60 books but there are gaps between them. On the second page everything is fine.
