### ISSUE TITLE
Add BOL.NL to add / edit metadata

### ISSUE THREAD

**Issue by Peteyismyname** [janeczku/calibre-web#1669]
**Is your feature request related to a problem? Please describe.**
Is it possible to add BOL.NL to add / edit metadata, the current options are
 
    var douban = "https://api.douban.com";
    var google = "https://www.googleapis.com";
    var comicvine = "https://comicvine.gamespot.com";

**Describe the solution you'd like**
Could perhaps this help in adding this ?  https://www.mobileread.com/forums/showthread.php?t=139472

thanks for this GREAT solution!

**Comment by naydichev** [comment]
I think you mean `bol.com` - `bol.nl` is something completely different...

**Comment by palmfighter** [comment]
yes, bol.com would be nice, I use it in my normal calibre through a plugin.

**Comment by OzzieIsaacs** [comment]
Meanwhile Calibre-Web supports adding customized metadata providers: https://github.com/janeczku/calibre-web/wiki/Developer#add-metadata-provider
I will not add anymore metadata providers, but anybody is free to add it's own provider.
Sorry but I can't support everything and have to focus on stuff which is doable for me.
