### ISSUE TITLE
Collapse does not work

### ISSUE THREAD

**Issue by skystormer-1** [janeczku/calibre-web#1672]
**Describe the bug/problem**
Sorry if I just am a bad reader, but tried setting up the server.
I can login to the server, but whenever I have have a collapse menu it menu does not collapase. URL just changes to #collapsethree.

**To Reproduce**
1. Go to 'your server'
2. Click on 'Edit basic configuration'
3. Try to open a collapse menu.

**Logfile**
No error, meaning no log.

**Expected behavior**
A menu should have opened.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.9.0
 - Calibre-Web version: 0.6.10 Beta
 - Docker container: None
 - Special Hardware: [e.g. Rasperry Pi Zero]
 - Browser: Internet Explorer (also tried Firefox and Chrome)

**Additional context**
Whatever I try: 
Wand version keeps on standing @ not installed.

**Comment by OzzieIsaacs** [comment]
It's working for me.
Looks like we are having some javascript error. Could you please open the developer console extras-> web developer -> web-console in firefox. PLease reload the page. I guess you will see some red lines, please provide information about it.

Regarding wand. You also need to install imagemagick:
https://github.com/janeczku/calibre-web/wiki/Extend-Features#extract-metadata-from-uploaded-files

**Comment by skystormer-1** [comment]
Correct:
Uncaught ReferenceError: $ is not defined
The recource from "http://localhost:8083/static/js/main.js?q=a1ebe1a" was blocked due to MIME type ("text/pain") mismatch (x-content-type-options: nosniff)

**Comment by OzzieIsaacs** [comment]
Could you please try the hint from this issue 
https://github.com/janeczku/calibre-web/issues/896#issuecomment-488831045

**Comment by skystormer-1** [comment]
Thx so much, that did the trick.
