### ISSUE TITLE
Books not displaying after adding metadata

### ISSUE THREAD

**Issue by timmehtimtims** [janeczku/calibre-web#1674]
Many books in my Calibre library are not displaying/available in Calibre-Web, as indicated by the screenshots below of Stephen King books (for example):

**Screenshots**
Records in Calibre = 79
![screencapture-calibre](https://user-images.githubusercontent.com/27214018/96590255-ae85aa80-12dd-11eb-84df-d759e5e551f4.png)

Records in Calibre-Web = 6
![screencapture-calibre-web](https://user-images.githubusercontent.com/27214018/96589920-4fc03100-12dd-11eb-9519-c8f67686a8f3.png)

When I strip out all metadata other than author and title that allows Calibre-Web to pick up all books, however when I bulk-add metadata in Calibre (tags etc...) then calibre-web no longer sees them.

**Logfile** - does not show any difference in library when starting calibre-web after removing and then adding metadata
[2020-10-19 12:26:49,061]  INFO {cps:99} Starting Calibre Web...
[2020-10-19 12:26:49,163]  INFO {cps.server:146} Starting Gevent server on [::]:8083
[2020-10-19 14:32:17,993]  INFO {cps:99} Starting Calibre Web...
[2020-10-19 14:32:18,093]  INFO {cps.server:146} Starting Gevent server on [::]:8083

**Expected behaviour**
I would not expect that adding metadata would prevent Calibre-Web from seeing these books. 

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python version: Python 2.7.16
 - Calibre-Web version: 0.6.10 Beta 
 - Docker container: [Technosoft2000]:

**Additional context**
Storage is local. Access is through a reverse proxy.

**Comment by OzzieIsaacs** [comment]
Did you add a visibility restriction like only certain tags are visible, or only books of a certain language are visible?

**Comment by timmehtimtims** [comment]
No, I wouldn't know how - I've had a brief look around the settings and cannot see any of those options within calibre-web. Would this be a calibre issue?

**Comment by OzzieIsaacs** [comment]
The settings are on the user page:
![grafik](https://user-images.githubusercontent.com/6438895/96606537-acc8e080-12f7-11eb-9d4b-669e4478534e.png)
Or on the user setup page:
![grafik](https://user-images.githubusercontent.com/6438895/96606638-c79b5500-12f7-11eb-8079-8f3724f96948.png)

How many books are shown on the authors page? 
![grafik](https://user-images.githubusercontent.com/6438895/96606750-e8fc4100-12f7-11eb-9395-6fc0a0168982.png)

Are authors and authors sort correct set?

**Comment by OzzieIsaacs** [comment]
Your search result showns not 6 authors stephen king, but 6 results for "stephen" or "king" in authors, Book title, tags, publisher or series
which is omething different than doing advanced_search for author "stephen king". 
Will not change the difference but the number of results (looks like 4 instead of 6 according to your screenshot)

**Comment by timmehtimtims** [comment]
You're a star - it had 'Vampires' 'War' 'Horror' etc... denied. 👍 
Had never seen that option before so thanks for that!
