### ISSUE TITLE
ValueError: year=101 is before 1900; the datetime strftime() methods require year >= 1900

### ISSUE THREAD

**Issue by leoepoot** [janeczku/calibre-web#1675]
When I browse OPDS, an error is reported. as follows.

" ValueError: year=101 is before 1900; the datetime strftime() methods require year >= 1900"

**Comment by OzzieIsaacs** [comment]
The datetime functions are very os dependent, this is the reason why this is asked in the issue template. 

There was a similar problem in earlier version, is the reason why this is asked in the issue template. 

When I browse OPDS -> OPDS feed consists of more then 10 pages.  is the reason why the issue template is asking for a clear and consitent description of what you did.  

With this vague information I can't help you
