### ISSUE TITLE
Has anyone themed CW?

### ISSUE THREAD

**Issue by leram84** [janeczku/calibre-web#168]
I'm looking for a good front end for my lib, and its currently between CW and ubooquity, I go back and forth every day. I plan on running this all inside [organizr](https://github.com/causefx/Organizr) but the ability to theme CW (i believe) will be enough to tip the scales definitively.

Just wondering if anyone has gone down this route, and how successful they were.

**Comment by OzzieIsaacs** [comment]
Hi,
I don't know anybody asking for a different theme nor do I know anybody working on any theme.
