### ISSUE TITLE
Failed to Move Cover File and [Errno 18] Invalid cross-device link

### ISSUE THREAD

**Issue by nieroivan** [janeczku/calibre-web#1687]
Hi.

 I'm using Calibre-Web with Synology NAS without docker and I'm having this problem every time I try to upload a new book (pdf, mobi, epub, etc):

Failed to Move Cover File /volume2/livros_new/Unknown/Historia da Menina Perdida - Elena Ferrante/cover.jpg: [Errno 2] No such file or directory: '/volume2/livros_new/Unknown/Historia da Menina Perdida - Elena Ferrante/cover.jpg'
Rename title from: '/tmp/calibre_web/0dbd3889bf9716b993c7e41a9a878782' to '/volume2/livros_new/Unknown/Historia da Menina Perdida - Elena Ferrante (7814)' failed with error: [Errno 18] Invalid cross-device link: '/tmp/calibre_web/0dbd3889bf9716b993c7e41a9a878782' -> '/volume2/livros_new/Unknown/Historia da Menina Perdida - Elena Ferrante (7814)/Historia da Menina Perdida - Elena Ferrante.mobi

All the permissions are R&W on the folder where the database and the books are stored.

Any idea on how to solve it?

**Comment by wgibcus** [comment]
Have you tried opening the database in the Calibre app and checking it for errors? Always make a backup before you do :)

**Comment by OzzieIsaacs** [comment]
> Any idea on how to solve it?

Please update to the newest version. Please fill out the issue-form next time.
If your problem is solved by this, please close the issue

**Comment by nieroivan** [comment]
Solved. Thanks!
