### ISSUE TITLE
Support for custom identifiers

### ISSUE THREAD

**Issue by Zaroz** [janeczku/calibre-web#1691]
On a similar vein to [issue #550](https://github.com/janeczku/calibre-web/pull/550), I would like to request that support for custom identifiers be added. As it is, only a select few identifiers are supported (isbn, goodreads, url,), which limits a user's ability to link to the book's various metadata sites.

Currently, if you try to add a custom identifier, the link just links back to the book page, even if you put in a full url.

I am not asking for the whole system to be immediately added with rules, parsing, etc, just the ability to add custom ids with urls and have them show up as properly working hyperlinks by using the info added to the forms like (if it were written in html):
`<a href="{Identifier Value}">{Identifier Type}</a>`

**Comment by Zaroz** [comment]
Since to apparent changes had been made, I decided to make a pull request myself. see: #1877 
Please approve it so I

**Comment by Zaroz** [comment]
added changes via #1877

**Comment by Zaroz** [comment]
awaiting approval of pull request of #1877

**Comment by gorgobacka** [comment]
It seems that #1877 is approved.
