### ISSUE TITLE
KoboSync Download Links

### ISSUE THREAD

**Issue by naydichev** [janeczku/calibre-web#1693]
**Describe the bug/problem**

- first of all, my Kobo sync isn't working at all, but there is an existing issue open about this (#1680).
- I tested the call locally (using `curl`) and I noticed that there are download links that do not go through the kobo routes. I have explicitly opened up `<calibre-web>/kobo` to be accessible by the outside world, all other paths require SSL MA. I'm not aware of a mechanism to setup SSL MA with the Kobo reader, but I do believe that all traffic from Kobo should be routed through a `/kobo/<auth_token>/` URL. It doesn't seem like it would be too difficult to make this change either.

**To Reproduce**
1. `curl $CALIBRE_URL/kobo/$KOBO_AUTH_TOKEN/v1/library/sync`
2. Notice the `URL`: `"Url":"$CALIBRE_URL/download/84/epub"`
3. It should be `"Url":"$CALIBRE_URL/kobo/$KOBO_AUTH_TOKEN/download/84/epub"`

**Expected behavior**
See `#3` from the list above.

**Screenshots**
N/A

**Environment (please complete the following information):**
N/A

**Comment by OzzieIsaacs** [comment]
I don't see the problem with the normal download link. The user using kobo sync should of course have download rights and for me the sync is working fine. If it's not working, this looks to me like it's a problem with yunohost.

**Comment by OzzieIsaacs** [comment]
Your PR is merged, I consider this as solved
