### ISSUE TITLE
I can't search metadata from douban

### ISSUE THREAD

**Issue by zhaohong21** [janeczku/calibre-web#1698]
**Describe the bug/problem**
I can't search metadata from douban in recent months. It seems that the API key was banned,since someone who has same problem fixed it by modified the apikey  from "0df993c66c0c636e29ecbb5344252a4a" to "054022eaeae0b00e0fc068c0c0a2102a".

**Comment by OzzieIsaacs** [comment]
I changed the apikey, thanks for reporting
