### ISSUE TITLE
[Enhancement] Dark Theme

### ISSUE THREAD

**Issue by leram84** [janeczku/calibre-web#170]
I opened an issue a few days ago asking about the theme-ability of CW, but since that's probably unlikely, I'm wondering if simply adding a dark theme might be more reasonable to add/desirable by users. 

ehh?

**Comment by OzzieIsaacs** [comment]
As I mentioned nobody was after this before. From the comments and issues in the past I know some people using calibre web directly on there reader, so the only theme I currently could think of, would be a high contrast one, to make it better readable on e-ink readers.
I currently do not plan to implement a theme (I'm not really a UI programmer)

Contribution is always welcome.

**Comment by leram84** [comment]
thanks for the reply! Yeah, i guess most people are downloading then, cause the single most requested feature for these kinds of things is always dark theme (night time mode). Its funny because i always thought people were being silly by acting like that was so important. But while i don't really care if my software has night modes, for an ereader it kinda does make a pretty big difference when you're staring at the screen for so long. 

Anyway, iI'll try and see if theres anything i can do, but im not a programmer, so dont hold your breath lol. Thanks again though! A friend just let me demo this app on their server, and the in browser reader is leagues ahead of ubooquity for ebooks, so i'm definitely using this regardless!

**Comment by OzzieIsaacs** [comment]
If you, or somebody else creates a dark theme, or something else, create a pull request and I'll merge it.
