### ISSUE TITLE
Generating apnx file during send to kindle process

### ISSUE THREAD

**Issue by norangebit** [janeczku/calibre-web#1711]
When I use the send to kindle feature the ebook on kindle have missing *real* page numbers.
Instead when i use sent to device with calibre desktop there isn't problem because the apnx file is generated during the process.
Is it possible to generate this file even with calibre web interface?

**Comment by christopher-dG** [comment]
I'd also really love this. Would be nice if it could be done solely via `ebook-convert` to avoid a bunch of code duplication here, in which case most of the work would need to be in the Calibre repo.
