### ISSUE TITLE
Books in PDF format are not syncing / downloaded on Kobo

### ISSUE THREAD

**Issue by fabiosirna** [janeczku/calibre-web#1712]
**Describe the bug/problem**

I'm using Calibre Web to sync my own book library. I mainly own books in PDF and pub format. My Kobo Libra H2O is synced with the library but I noticed that PDF books are not shown.

**Expected behavior**
I'm expecting to be able to sync / download the PDF files.

**Environment (please complete the following information):**
 - Calibre-Web version: 0.6.9
 - Docker container: DockerHub
 - Special Hardware: Odroid XU4, Kobo Libra H2O (firmware 4.25.15875)
 - Browser: Firefox 82.0.3

**Comment by OzzieIsaacs** [comment]
This behaviour is correct and can't be changed. 
No matter, which format you present to the kobo reader it will only download books marked as epub3 format, and no matter which format the book really has, it will treat it as kepub, leading to some strange problem, if the book is not in kepub format. 
So this problem can't be solved by calibre-web
