### ISSUE TITLE
Series Sort order

### ISSUE THREAD

**Issue by szemlicka** [janeczku/calibre-web#1715]
Hi,

is there a way to sort the order of a series? For a large series like Perry Rhodan it is not possible to order it. An additional button at the top can be helpful...:-)

**Comment by OzzieIsaacs** [comment]
Yes, I also realized it that the current sort options are "not ideal"

**Comment by szemlicka** [comment]
Thanks...:-)

**Comment by OzzieIsaacs** [comment]
The button is now present, please update to the newest commit
