### ISSUE TITLE
Unable to Upload Large Files

### ISSUE THREAD

**Issue by suineg** [janeczku/calibre-web#1716]
**Describe the bug/problem**
I am trying to upload a large epub that is 112 MB and it goes through the process and then fails, once I saw a screen that says the file was too large but I can't get that screen up again to take a screenshot.

**To Reproduce**
1. Go to 'Main Page'
2. Click on 'Upload'
3. Scroll down to 'Select large epub (for instance 110mb)
4. Receive just a screen that says error.

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

**Expected behavior**
I would assume that it has an option somewhere to set max upload size.

**Screenshots**

**Environment (please complete the following information):**
 - OS: docker alpine
 - Python version: 3.6.9 (default, Oct 8 2020, 12:12:24) [GCC 8.4.0]
 - Calibre-Web version: 0.6.9 - a9c0bcb4a2441b0171966cfc32c60b6cf677c590 - 2020-09-27T07:15:03+02:00 
 - Docker container: linuxserver
 - Special Hardware: none
 - Browser: chrome

**Additional context**
Running an nginx reverse proxy that is set to universally handle files over 4GB, not saying that can't be the case but it is functioning elsewhere. I have looked through the python files to see if this is limited via flask and can't see that it is but I'm not super familiar with flask.

**Comment by suineg** [comment]
<html> <head><title>413 Request Entity Too Large</title></head> <body> <center><h1>413 Request Entity Too Large</h1></center> <hr><center>cloudflare</center> </body> </html>      

This was the error message after attempting again.

**Comment by brunovianna** [comment]
did you fix it? i have the same issue with nginx in yunohost

**Comment by suineg** [comment]
> did you fix it? i have the same issue with nginx in yunohost

So for me it was an issue with CloudFlare not allowing POST of that size. I had to disable it and upload.
