### ISSUE TITLE
No LDAP configuration in the WebUI

### ISSUE THREAD

**Issue by hysci** [janeczku/calibre-web#1717]
It is claimed in the feature list that LDAP is supported, however, due to some known bugs, the feature was closed: https://github.com/janeczku/calibre-web/commit/d82289e3039f1b2477545ea7d622848f6f7ec592

Will the LDAP configuration be supported in the WebUI in the future?

**Comment by OzzieIsaacs** [comment]
It‘s supported:
https://github.com/janeczku/calibre-web/wiki/LDAP-Login#installation

**Comment by hysci** [comment]
@OzzieIsaacs Thanks, I've already installed python-ldap, but how can I enable LDAP in the WebUI? Shall I modify the python source code?

**Comment by OzzieIsaacs** [comment]
You also have to install flask-SimpleLDAP, as stated in the optional-requirements.txt
![grafik](https://user-images.githubusercontent.com/6438895/100060836-6e11d300-2e2d-11eb-9305-57704f2be1b8.png)

![grafik](https://user-images.githubusercontent.com/6438895/100060619-170bfe00-2e2d-11eb-9976-e37642affa22.png)

In the basic config section - feature configuration you should see the menu login type and should be able to select LDAP login
![grafik](https://user-images.githubusercontent.com/6438895/100060714-3acf4400-2e2d-11eb-908a-d8e97af37365.png)

**Comment by OzzieIsaacs** [comment]
Please feel free to change the entry in the wiki if it's not clear to you what to do (after you figured it out).

**Comment by OzzieIsaacs** [comment]
For a working LDAP login Calibre-Web version 0.6.7 at least is needed:
![grafik](https://user-images.githubusercontent.com/6438895/100061320-2ccdf300-2e2e-11eb-9ecd-ea8d7401acb0.png)
