### ISSUE TITLE
requests.exceptions.MissingSchema: Invalid URL '/static/generic_cover.jpg': No schema supplied. 

### ISSUE THREAD

**Issue by tmechen** [janeczku/calibre-web#1718]
**Describe the bug/problem**
When recieving no book cover via "load meta data" and trying to safe the metadata, this raises an exception

**To Reproduce**
1. Look up metadata for a book
2. book has no image
3. click save
4. See exception

**Logfile**
```
[2020-11-20 13:59:29,669] ERROR {cps.editbooks:716} Invalid URL '/static/generic_cover.jpg': No schema supplied. Perhaps you meant http:///static/generic_cover.jpg?
Traceback (most recent call last):
  File "/calibre-web/app/cps/editbooks.py", line 655, in edit_book
    result, error = helper.save_cover_from_url(to_save["cover_url"], book.path)
  File "/calibre-web/app/cps/helper.py", line 581, in save_cover_from_url
    img = requests.get(url, timeout=(10, 200))      # ToDo: Error Handling
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
    p.prepare(
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/static/generic_cover.jpg': No schema supplied. Perhaps you meant http:///static/generic_cover.jpg?

```

**Expected behavior**
Adding no cover or a generic image

**Environment (please complete the following information):**
 - Platform: Linux 4.15.0-123-generic #126-Ubuntu SMP Wed Oct 21 09:40:11 UTC 2020 x86_64 
 - Python version: 3.8.5 (default, Jul 20 2020, 23:11:29) [GCC 9.3.0]
 - Calibre-Web version: 0.6.10 Beta 
 - Docker container: : Technosoft2000

*edit*
just found your corresponding todo ;)

https://github.com/janeczku/calibre-web/blob/32b7b39223e494e338d87e40ccfe05b7277afbdd/cps/helper.py#L584

**Comment by OzzieIsaacs** [comment]
Thanks for the detailed report, I tried to reproduce it, but I didn't succeed. My search term was "book11", there is one book without cover from douban (named Fonolibros, Stage 1, Book11, El Aguila Vuela Alto, 6 Pack), but I don't get the problem you reported.

The steps would be 

1. Goto "Edit Metadata"
2. Click "Fetch Metadata"
3. Search for **"??"**
4. **Click on empty cover ??**
5. click save on metadata edit page
6. See exception

Could you please give me the search term

**Comment by OzzieIsaacs** [comment]
After looking into the code it turns out that this can only happen with google search results...

**Comment by tmechen** [comment]
Sorry, didnt include the search in question. 
* can reproduce it with the searchterm "3737353999"
* ISBN for "Zwischen dir und mir die Sterne"
* first result is a google books link (https://books.google.de/books?id=ionijwEACAAJ)
* (see image below)

![grafik](https://user-images.githubusercontent.com/9123876/99839998-f9f4d800-2b6b-11eb-8140-8c42603eb5c8.png)

* after clicking on the "Cover not available" to fetch the metadata, it updates the view 
![grafik](https://user-images.githubusercontent.com/9123876/99840228-74bdf300-2b6c-11eb-995a-b647ee092472.png)

**Comment by OzzieIsaacs** [comment]
Problem should be fixed now, another prerequisite was that uploading was enabled. 
Another problem was that the Generic cover wasn't displayed if accessed from behind a reverse proxy with "path_prefix".
Please update to newest version, and close the issue if it's solved 
Remark: The cover is only updated in the browser after a page reload, this is a known bug.

**Comment by tmechen** [comment]
can confirm.
thx for the quick fix :)
