### ISSUE TITLE
Crash on old Kindle

### ISSUE THREAD

**Issue by ofalvai** [janeczku/calibre-web#1721]
**Describe the bug/problem**
When I try to load Calibre Web on my old Kindle 4 (2011) the whole system restarts after a few seconds of loading. I started investigating the issue and my guess is the system is running out of memory because of the default book covers. The "Cover not available" image is a 2500x3500 JPEG (183KB), and my initial library contains lots of books without a proper cover image. My theory is when the Kindle loads the initial page (with random and recently added books) it runs out of memory because of these large images. When I load a subpage without any books (eg. `/login`) the device can load the page without any problem.

**To Reproduce**
1. Have some books in the library with no cover
2. Load initial page on some old device (Kindle 4)
3. Device crashes and reboots

**Expected behavior**
Calibre should serve a smaller cover or generate the default cover with CSS

**Environment (please complete the following information):**
 - OS: Raspberry Pi OS
 - Python version: 3.6.9
 - Calibre-Web version: 0.6.9 - a9c0bcb4a2441b0171966cfc32c60b6cf677c590 - 2020-09-27T07:15:03+02:00
 - Docker container: linuxserver
 - Special Hardware: Raspberry Pi 3B+
 - Browser: Kindle 4 (2011, non-touch)

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

**Comment by ofalvai** [comment]
This is probably related to https://github.com/janeczku/calibre-web/issues/1347, it's just a more severe version of the same issue.

**Comment by OzzieIsaacs** [comment]
I shrinked to cover picture to about 1/10 size

**Comment by ofalvai** [comment]
Thanks, it's no longer crashing my Kindle. I'm closing the issue.
