### ISSUE TITLE
how can I using gunicorn for calibre-web?

### ISSUE THREAD

**Issue by vagra** [janeczku/calibre-web#1725]
I want to use gunicorn for calibre web multi threading services. 

Refer to the configuration in [docker calibre web](https://github.com/janeczku/docker-calibre-web), but it seems to be old, so it always fails. 

How to set the current version of calibre-web gunicorn.conf.py  and wsgi.py  ?

**Comment by OzzieIsaacs** [comment]
The linked website states:

**This image has been deprecated. Please see here for links to alternative Docker images for Calibre Web.**

> How to set the current version of calibre-web gunicorn.conf.py and wsgi.py ?

It's not possible. On the project Readme there are 2 docker container listed.  Please try one of them, I don't know if gunicorn brings any benefit for this project or docker containers

**Comment by vagra** [comment]
now I don't require gunicorn anymore, I use gdrive to solve my problem very well. 

I was unable to install gdrive after upgrading to python3.7, which caused tonador to report errors frequently, so there was this problem.

later I compiled and installed gdrive and this problem has been solved.
