### ISSUE TITLE
Series overview gone away in 0.6.9 

### ISSUE THREAD

**Issue by szemlicka** [janeczku/calibre-web#1726]
Hi,

I updated today to the latest version 0.69 and the series are not showing in the overview.
If you go to for an example to Recently Added Books, you see an overview of your books. That overview includes
1. Cover
2. Titel
3. Author
Before I made the update I also saw series and in braked the number of the series. That is gone away. Before the update I open a ticket ( https://github.com/janeczku/calibre-web/issues/1715) because the sort order was not given. But he, its better to have an unsorted list before I have nothing...:-) 
Please bring it back.....:-)
![image](https://user-images.githubusercontent.com/15927779/100079198-a7097200-2e44-11eb-9f39-8fd8f2919c92.png)

Platform 	Linux 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64
Python 	3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
Calibre_Web 	0.6.9 - a9c0bcb4a2441b0171966cfc32c60b6cf677c590 - 2020-09-27T07:15:03+02:00
WebServer 	Tornado 6.0.4
Flask 	1.1.2
Flask_Login 	0.5.0
Flask_Principal 	0.4.0
Werkzeug 	1.0.1
Babel 	2.8.0
Jinja2 	2.11.2
Requests 	2.21.0
SqlAlchemy 	1.3.20
pySqlite 	2.6.0
SQLite 	3.27.2
iso639 	0.4.5
pytz 	2020.4
Unidecode 	installed
Image Magick 	ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
PyPdf 	v1.26.0
lxml 	not installed
Wand 	0.5.9
Pillow 	not installed
Comic_API 	not installed
ebook converter 	ebook-convert (calibre 3.39.1)
unrar 	not installed
kepubify 	not installed

**Comment by szemlicka** [comment]
I switch to nightly and have now the series back.
![image](https://user-images.githubusercontent.com/15927779/100083140-59433880-2e49-11eb-93ce-bb38f8caec41.png)

**Comment by OzzieIsaacs** [comment]
I hope I can start working on the sorting topic next week

**Comment by szemlicka** [comment]
No problem. Stay save.
