### ISSUE TITLE
installing the optional Component rarfile-4.0 breaks calibre-web

### ISSUE THREAD

**Issue by mesfinteshome** [janeczku/calibre-web#1727]
**Describe the bug/problem**
installing the optional Component rarfile-4.0 breaks calibre-web. After uninstalling the package the calibre-web works again on Debian 9.
**To Reproduce**
1.  Install optional requirements
2. Access the calibre-web application

**Environment (please complete the following information):**
 - OS: [e.g. No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.13 (stretch)
Release:        9.13
Codename:       stretch
 ]
 - Python version: [Python 3.5.3]
 - Calibre-Web version: [0.6.10 Beta - eed2f0a4304aba9b90c70b5bd88b4dd7d230bb31 - 2020-11-22T08:45:02+01:00t HEAD)]:
 - Docker container: [None]:
 - Special Hardware: [e.g. None]
 - Browser: [e.g. All Browsers]

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

**Comment by OzzieIsaacs** [comment]
No, can't reproduce it, for me it's working. (Checked it on Linux Mint 20)
If you installed comicapi, please check that you have installed the newest version. I remember a problem in conjunction with "rarfiles", on an older version.
git+https://github.com/OzzieIsaacs/comicapi.git@b323fab55e7daba97f90bf59a4bc8de9d9c0a86b#egg=comicapi
was before:
git+https://github.com/OzzieIsaacs/comicapi.git@15dff9ce4e1ffed29ba4a2feadfcdb6bed00bcad#egg=comicapi

What is the error message (logfile?) you get?
Did you start with a new calibre-web installation, or are you using an old app.db file?

**Comment by vityav** [comment]
Same issue on a fresh install when going from base requirements to optional requirements. Works great on base, won't start with optional.
Debian 9.6
Python 3.5.3
Calibre-Web version: 0.6.10 Beta commit eed2f0a4304aba9b90c70b5bd88b4dd7d230bb31

The output log just shows a series of
`INFO {cps.server:216} webserver stop (restart=False)`

whenever I restarted, where previously it showed the tornado server starting on a port (deleted old log already where it worked when attempting re-install). If I run it manually, I get:
```
Traceback (most recent call last):
  File "cps.py", line 39, in <module>
    from cps.about import about
  File "/home/victoir/calibre-web/cps/about.py", line 33, in <module>
    from . import db, calibre_db, converter, uploader, server, isoLanguages, constants
  File "/home/victoir/calibre-web/cps/uploader.py", line 25, in <module>
    from . import logger, comic
  File "/home/victoir/calibre-web/cps/comic.py", line 37, in <module>
    from comicapi.comicarchive import ComicArchive, MetaDataStyle
  File "/usr/local/lib/python3.5/dist-packages/comicapi/comicarchive.py", line 31, in <module>
    import rarfile
  File "/usr/local/lib/python3.5/dist-packages/rarfile.py", line 946
    warnings.warn(f"Windows junction not supported - {info.filename}", UnsupportedWarning)
```

And then it hangs. Uninstalling rarfile gets it back to functional.

**Comment by OzzieIsaacs** [comment]
@vityav thanks for the errormessage, but I think there is missing the important part, the last line with the syntax error.
Looks like it‘s this one: https://github.com/markokr/rarfile/issues/66

**Comment by mesfinteshome** [comment]
Thank you, OzzieIsaacs, upgraded Python to 3.7 and now even after install rarfile, calibre-web works fine.
