### ISSUE TITLE
cannot longer see what users have been downloading

### ISSUE THREAD

**Issue by stfrbrntyu** [janeczku/calibre-web#1730]
Since a couple of updates (beta channel) I can not longer see what users have been downloading.

Is this intentional or a bug?

**Comment by OzzieIsaacs** [comment]
Maybe, depends on what you are referring exactly: 
I indeed removed the recent Downloads section in the admin -> edit user and user's section, as it caused trouble on having many downloads (#1625).
![grafik](https://user-images.githubusercontent.com/6438895/100861985-dea29a80-3492-11eb-87b0-bb12c0c40a8c.png)
But what I indeed forgot is that you could see the downloaded books of a user before, in case you were an admin.
I'll have a look at it, if I can restore it.

**Comment by stfrbrntyu** [comment]
Yes that is what I meant.
I can understand why it is gone, it does get slow if the user downloaded a lot of books.
It's not that important to me, it's "nice to have", if you find a good solution i'll be happy, if not, i won't be unhappy :)

**Comment by rg9400** [comment]
I can see other user's books on the Downloaded Books shelf item now on `0.6.12 Beta - 1a0de3b3cf05388bce3471b4e08bbff3a8373306 - 2021-04-06T18:08:32+02:00`

Just curious that if a user has this permission, will they see other users' downloaded books as well, or just their own?

**Comment by OzzieIsaacs** [comment]
Non Admin user only see their own book downloads (so the choose user page is not visible to them, they get directly to the cover page)
