### ISSUE TITLE
Nginx Reverse Proxy delivers 404 on CSS/JS Files

### ISSUE THREAD

**Issue by simon-sysadmin** [janeczku/calibre-web#1735]
Hi, I've installed Calibre-Web on Arch Linux through AUR.

The service works great whenever I load it directly in the browser: 
> http://local-ip:8083

But when I try to load the site through Nginx, then the site loads without any CSS/JS. The static files fail to load due to a 404 error.

I've set the Nginx server block exactly as indicated over here: https://github.com/janeczku/calibre-web/wiki/Setup-Reverse-Proxy
> https://domain.com/calibre

The server in which I host Calibre-web has a good number of running websites under Nginx. Some of them are also served through a reverse proxy. And they aren't facing such issue with CSS/JS.

**Comment by vagra** [comment]
···
location ^~ /static/ {
                include  /etc/nginx/mime.types;
                root /***********/calibre-web/cps/;
        }

···

**Comment by simon-sysadmin** [comment]
Thanks for pointing that out!
Not sure if that's correct, but I included my cps directory root to the existing block, and it just loads fine.

This is how it looks from my end:

```
# Calibre
location /calibre {
  root /usr/lib/calibre-web/cps/;
  proxy_bind $server_addr;
  proxy_pass http://127.0.0.1:8083;
  proxy_set_header Host            $http_host;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Scheme        $scheme;
  proxy_set_header X-Script-Name   /calibre;  # IMPORTANT: path has NO trailing slash 
}
```

**Comment by OzzieIsaacs** [comment]
Looks like you solved your problem
