### ISSUE TITLE
Installer Executable

### ISSUE THREAD

**Issue by Encyclopedus** [janeczku/calibre-web#1738]
Hello. I am not particularly tech savvy. Would it be possible to create an installer executable with a GUI that runs all the necessary installation tasks so I don't have to mess around with command-line installs?

**Comment by OzzieIsaacs** [comment]
Which OS are we talking about? Windows?

**Comment by OzzieIsaacs** [comment]
The newest release has a windows installer to download

**Comment by Encyclopedus** [comment]
Awesome, thank you so much!
