### ISSUE TITLE
Add (or move) "download" button to the top of "description" page

### ISSUE THREAD

**Issue by smiserge** [janeczku/calibre-web#174]
Book Description page: For user convenience IMHO it would be better to move (or copy) the "download" button to the top area of the "Book Description" page. The reason is that in many cases "description" of the book is taller than browser working area, so one has to scroll down to the bottom of the page before book can be downloaded. It is confusing for new users because they need to know in advance that they need to scroll through the whole description in order to get to "download" button, and it is not even visible. For experienced users it is and extra "scroll", e.g., in my usage pattern I typically know enough about the book already and I do not need to read the description again, I just need to download (or read) the book.
Possibly the same argument is true for the "read in browser" button. 
Thanks for the great project!

**Comment by OzzieIsaacs** [comment]
Good idea. Done
