### ISSUE TITLE
Exclude book from Recently Added

### ISSUE THREAD

**Issue by Nando-debug** [janeczku/calibre-web#1740]
Hi everyone, I'm new here.
I have recently started using caliber-web and I am fine, but I wanted to find out if there is a way to exclude a category of books from the "recently added" view.
Basically what I would like to do is place the category of "thriller" books on a shelf, then excluding them from the "recently added" view. it's possible to do it?
Thanks

**Comment by OzzieIsaacs** [comment]
No, I'm sorry, this is not possible. 
You could exclude books based on categories from being visible at all, or you could exclude books based on languages from visible. 
But it's not possible (and also not planned) to exclude categories of books from certain views

**Comment by Nando-debug** [comment]
Thanks for the reply, you were very fast.
So I try to ask you something else: is it possible to make books with a specific word in the title (example: thriller) appear at the bottom of the "recently added" list? I would like to understand the criterion by which books are displayed in "recently added". Thank you again

**Comment by OzzieIsaacs** [comment]
All books are listed in recently added. In the calibre database there is a column called book-date (the date where the book was added to calibre). In recently section there are several sorting options (which are stored on a per user base, except for the guest user, there it is stored on a per session base). You could choose one of them , e.g sort according to title and give all the books you don't want to see a title starting with "Z", or you could sort according to author, giving the author a starting "Z" or publishing date (this would be a bit tricky, as "no date" is year 0101)

**Comment by Nando-debug** [comment]
Thanks for the information! I set an old date (1st Jan 1990) for the category I wanted to leave at the bottom of the list. In this way all other books are displayed first, and at the end the ones I wanted to exclude. This way with a large collection, these will hardly be immediately visible.

Thanks so much again.
