### ISSUE TITLE
Control Cache Behavior

### ISSUE THREAD

**Issue by aCID-sLAM** [janeczku/calibre-web#1742]
**Is your feature request related to a problem? Please describe.**
I have a huge ebook collection and i noticed, the web server of calibre handles it a bit better, it seems.
Calibre takes quite a while, after the first run and uses more memory, but when its loaded, it is much more responsive.

**Describe the solution you'd like**
A faster handling of huge librarys. Maybe a option for the user, where he can tweak the memory usage and cache behaivor
itself.

**Comment by OzzieIsaacs** [comment]
The only possibility is see is changing the amount of books loaded per time (admin -> UI config -> books per page or similar). There is a PR ongoing to shrink the cover pictures.  This might speed up it a little bit, but otherwise I don't see any chance for making big speed improvements except from reprogramming everything and removing a lot of features.

**Comment by aCID-sLAM** [comment]
Sorry for pushing this up again but maybe it would speed up, not flushing the database after a browsing is done, through the webinterface?
You may not even do it but my metadata.db is about 240 MB big and calibre-server uses about 1-2 GB memory, when loaded.
It takes a while, until its responds after first start but than, the handling is alot faster. But it also lacks of alot of features, compared to calibre-web

Calibre-web uses a max of about 500 mb, which lowers to 100 mb after using it. It always raises the memory use, when using Calibre-web, which makes me think, its loads stuff again and again into memory, when used. Why may cause a slowdown on a huge library. 
But to be honest, i dont know much about python and memory handling. Just though, there may be a (easy) way to adjust the handling for users, which bigger librarys.
