### ISSUE TITLE
For CJK languages ​​, when sorting books by name, use data.name instead of books.sort

### ISSUE THREAD

**Issue by vagra** [janeczku/calibre-web#1746]
**Is your feature request related to a problem? Please describe.**
If the language of the book title is CJK, now when sorting in alphabetical order, it is sorted by unicode instead of pinyin order.

**Describe the solution you'd like**
In fact, in the metadata.db database, the book name has been converted to pinyin and stored in the data.name field.

So, can modify calibre-web to use data.name for alphabetical sorting for CJK languages?

**Describe alternatives you've considered**
or teach me how to modify the relevant code.

**Comment by vagra** [comment]
This is unicode sorting, not alphabetical sorting:
![图片](https://user-images.githubusercontent.com/1576687/101274405-cd31f900-37d8-11eb-91e1-48e7d3ec01b7.png)

This is the alphabetical order:
![图片](https://user-images.githubusercontent.com/1576687/101274443-12eec180-37d9-11eb-8c8e-92a258f6c6af.png)
Code in web.py:
```
def render_books_list(data, sort, book_id, page):
    ...
    if sort == 'abc':
        order = [db.Books.sort]
    if sort == 'zyx':
        order = [db.Books.sort.desc()]
    ...
```
How can I modify this code to use the data.name field to sort?

how

**Comment by OzzieIsaacs** [comment]
It's not possible by just changing this line of code, as the Data is in a different table with a 1:N relationship
