### ISSUE TITLE
ebook-convert settings problem

### ISSUE THREAD

**Issue by Nando-debug** [janeczku/calibre-web#1747]
Hello everyone, I already apologize for the question, but I could not find any information about it.
I entered some settings for the calibre converter, but they don't seem to work.
I doubt that I have done the wrong things.
I would like to have the first image removed from the file during the conversion and then inserted the one from the metadata.
These are the commands I entered (taken from the Calibre guide). Are they correct or did I write rubbish?

![screenshot-192 168 1 17_8083-2020 12 07-10_45_10](https://user-images.githubusercontent.com/75420138/101354018-c5378f00-3894-11eb-911e-39ef9e022e45.png)

Thanks to anyone who will help me

**Comment by OzzieIsaacs** [comment]
Please ensure that the command you are try to run is really doing what you expect it. 
Calibre-Web is just running the command:
`ebook-convert input_file output_file [options]`

Please run this with the desired options (--remove-first-image and --prefer-metadata-cover) on the comandline and check the output. If this works and within calibre-web it's not working we could start digging for the problem in calibre-web. 

One remark: Calibre-Web is not Calibre, bot programs don't share anything (programmers, code, ..) except the database format, so you can not get any support for the ebook-convert program at all here

**Comment by Nando-debug** [comment]
Thanks for the reply. In fact, it doesn't seem to work even as a terminal.
I will try to find another solution.
Thanks again
