### ISSUE TITLE
Disable shelf for user

### ISSUE THREAD

**Issue by LwsBtlr** [janeczku/calibre-web#1749]
I would like to be able to disable the appearance of the “add to shelf” button on a per-user basis. The primary user of my library iOS 85yo and finds that link (the only thing that looks like a link on search result page) to be very confusing.

Short of that, disabling shelves entirely would be acceptable.

**Comment by OzzieIsaacs** [comment]
I hope you understand that I can't have each and every feature configurable, as there are now already alot of people who can't get simple features to work, as they don't find the right button. 
So I'd like you to ask to delete the following lines (whole lines) in cps/templates/layout.html:
![grafik](https://user-images.githubusercontent.com/6438895/101739574-0368c480-3ac8-11eb-94e4-04c7ea54b19c.png)
This will remove the button to create a shelf and also disable the visibility of any shelf (for all users)
 Line numbers are from current master, so depending on your version the numbers might be different. You should do this on every update you are performing. The chance that the lines are changing totally and no longer recognizable are very low at the moment
