### ISSUE TITLE
Delete User

### ISSUE THREAD

**Issue by mesfinteshome** [janeczku/calibre-web#1756]
It would be nice to have a "Delete User" feature in the admin interface. I don't see anywhere to click to delete a user.

**Comment by OzzieIsaacs** [comment]
Duplicate of: #1664
Hope you can solve your problem with this post, otherwise please let me know. Please close this issue afterwards. Let's track the change in the first issue.

**Comment by mesfinteshome** [comment]
That was the last place I would have checked to delete a user. But it gets the job done. Thank you.
