### ISSUE TITLE
Kobo sync error on Docker using https reverse proxy

### ISSUE THREAD

**Issue by luke-70it** [janeczku/calibre-web#1758]
I configured Calibre Web as a Docker container. Inside my home network it uses default 8083 port in plain http, but I use swag Docker container to be able to access all my dockers using https (on standard 443 port) via duckdns and letsencrypt.
kobo glo can't sync

**To Reproduce**
1. I enabled "Enable Kobo sync" and "Proxy unknown requests to Kobo Store" in Feature Configuration
2. I changed "Server external port" to 443
3. I added to Kobo eReader.conf file the line: api_endpoint=https://<host>.<mydomain>.duckdns.org/kobo/<api_key>
4. I restarted both Calibre Web Docker and Kobo Glo

I checked my Kobo eReader.conf and I saw that a number of entries were added:
image_host=http://<host>.<mydomain>.duckdns.org
image_url_quality_template=http://<host>.<mydomain>.duckdns.org/kobo/<api_key>/{Quality}/isGreyscale/image.jpg
image_url_template=http://<host>.<mydomain>.duckdns.org/kobo/<api_key>/{ImageId}/{width}/{height}/false/image.jpg

These 3 parameters doesn't use https and the links result inaccessible. Probably this is the problem.

If I configure both Calibre Web and Kobo Glo to use plain http protocol and standard 8083 port kobo sync work flawless, but it would be nice if I can use ssl encryption

Environment:
 - OS: Openmediavault 5.5.17.3 and Docker 20.10.0-3

Platform	        Linux 5.9.0-0.bpo.2-amd64 #1 SMP Debian 5.9.6-1~bpo10+1 (2020-11-19) x86_64 x86_64
Python		3.6.9 (default, Oct 8 2020, 12:12:24) [GCC 8.4.0]
Calibre_Web	0.6.9 - a9c0bcb4a2441b0171966cfc32c60b6cf677c590 - 2020-09-27T07:15:03+02:00
WebServer	Gevent 20.5.2
Flask		1.1.2
Flask_Login	0.5.0
Flask_Principal	0.4.0
Werkzeug	1.0.1
Babel		2.8.1
Jinja2		2.11.2
Requests	        2.25.0
SqlAlchemy	1.3.20
pySqlite	        2.6.0
SQLite		3.22.0
iso639		0.4.5
pytz		        2020.4
Unidecode	installed
Flask_SimpleLDAP	installed
python_LDAP	3.2.0
Goodreads	installed
Jsonschema	3.2.0
flask_dance	3.0.0
Image Magick	ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
PyPdf		v1.26.0
lxml	        	v4.5.2.0
Wand		0.5.9
Pillow		v7.1.2
Comic_API	2.1.1
ebook converter	not installed
unrar		UNRAR 5.50 freeware Copyright (c) 1993-2017 Alexander Roshal
kepubify	kepubify v3.1.6

**Comment by OzzieIsaacs** [comment]
Please try to edit the eReader.conf file again and change the http to https then it should work. 
There is not much I can do from this side regarding this, the texts are added by the kobo reader itself. I dont know why it added http links instead of https.

**Comment by luke-70it** [comment]
Unfortunately after kobo reboot these urls are automatically changed to http :(
If these parameters are compiled automatically by the ereader itself there is nothing to do, and I don't think I can open a ticket to kobo... ;)

Thank you for your reply and for this great software!
