### ISSUE TITLE
Please help me!Why i can't  modify the metadata？

### ISSUE THREAD

**Issue by xu2006** [janeczku/calibre-web#176]
Please help me!Why i can't  modify the metadata？
By editing the metadata button, I can get the metadata that can‘t be automatically added to the page.
Please help me!
Thanks you!

**Comment by OzzieIsaacs** [comment]
I don't understand exactly the problem. Is there a error in the logfile (calibre-web.log)? Could you please try to explain the problem more detailed?

**Comment by idalin** [comment]
Same as #182 . I'll fix it in a few days.

**Comment by OzzieIsaacs** [comment]
Sorry guys. Should now work again

**Comment by simkin** [comment]
Meta text update works again, Thanks! Cover-art is not updated though ("Cover not available"). Any ideas?

**Comment by OzzieIsaacs** [comment]
During my checks some covers were displayed, some not. I thought that the corresponding entry's had no covers. I'll check it.

**Comment by OzzieIsaacs** [comment]
To me its working. If cover not available is displayed, than Google doesn't deliver a cover (on the original website there is only a generic cover visible). Maybe its some caching issue on your site?
![grafik](https://cloud.githubusercontent.com/assets/6438895/25305846/194485c0-2783-11e7-917f-836d1ee94fd1.png)

**Comment by simkin** [comment]
aaa, my bad. Some books I uploaded did not contain any cover art. I assumed/hoped the metadata update function would also grab the cover-art. Would be a nice addition :)
