### ISSUE TITLE
Is a new version of Calibre-Web possible for 2021?  (0.6.10 or 0.7.0 ?)

### ISSUE THREAD

**Issue by holta** [janeczku/calibre-web#1763]
Hi @OzzieIsaacs & All!

It's _very_ bad form to beg for Christmas presents (:

But is a new release of Calibre-Web perhaps possible for the New Year or similar, e.g. version 0.6.10 or maybe even 0.7.0 ?

Thanks for considering, so this might be distributed as part of [Internet-in-a-Box (IIAB) 7.2](https://github.com/iiab/iiab/wiki/IIAB-7.2-Release-Notes) ideally!

Ref: https://github.com/janeczku/calibre-web/releases/tag/0.6.9 (V0.6.9 - Priyā)

**Comment by OzzieIsaacs** [comment]
Currently my plans tend more towards a release in mid of January (I'd like to finish and include a feature regarding sorting of shelfs)

**Comment by OzzieIsaacs** [comment]
It's done, version 0.6.10 Florence is published
