### ISSUE TITLE
no button for smtp setting

### ISSUE THREAD

**Issue by zhjcreator** [janeczku/calibre-web#1766]
version: Nightly ,12/13/20, 5:33 PM
problem: there is no smtp configuration under the smtp info
![image](https://user-images.githubusercontent.com/55911606/102772359-53962f80-43c2-11eb-830d-e26d911d67a0.png)

**Comment by OzzieIsaacs** [comment]
Sorry, copy pasted it wrong while reorganizing the page

**Comment by OzzieIsaacs** [comment]
It's fixed in the newest commit
