### ISSUE TITLE
Users: Login screen to show users/names in system, allow no password.

### ISSUE THREAD

**Issue by CyanBC** [janeczku/calibre-web#1767]
I would like to see which users have access to the system from the login screen. Since I may setup various users as admin, I would like to tell those users to go to the internal site and they can click on their name to enter. Instead of needing to know and entering a username.

I would also like to be able to setup user accounts without passwords (this is on my internal network).

**Describe the solution you'd like**
User name icon/text at login screen
Allow no password entry

**Additional context**
Other media apps such as Jellyfin and Kodi have login pages that allow one to select the user. Something like:
https://i.pinimg.com/736x/c2/53/ae/c253aeff04b83da8e2fac892831c0800--ui-components-user-interface.jpg

**Comment by OzzieIsaacs** [comment]
I thought a bit about your request and I came to the conclusion, that I will not implement it (I'd like to focus more on the book library functions of calibre-web and not on the user management).
Many users expose their Calibre-Web instance to the internet, making the username visible reduces the complexity to guess the password, so weakens the security of the calibre-web instance. If you'd like to have your books visible without password, you could use the anonymous browsing function, even if you don't have all functions available that way.
Another option would be using an email address as username and use a very simple password like only one letter. The login status is normally stored in a browser, so you don't have to login on the same computer once logged it (tick remember me box on login page). 
Some modern browser also offer to store the credentials so your users don't have to remember it the browser is able to fill in the data based on the domain name.
