### ISSUE TITLE
invalidating configuration after server restart

### ISSUE THREAD

**Issue by suciocerdo** [janeczku/calibre-web#1770]
Hi,

After restarting my computer some settings are reset (the library path and the option to upload books). My guess is that this is an issue regarding the authorizations of app.db but I am still learning how to work with Ubuntu and my computer knowledge is limited in this area. Other than that calibre-web runs smoothly. This is my set up:

Python version: 3.8.6
OS: Ubuntu 20.10
Calibre-Web version: 0.6.10 Beta
Browser: Chrome Version 87.0.4280.88

Logfile:
[2020-12-22 15:15:24,767]  INFO {cps.server:216} webserver stop (restart=False)
[2020-12-22 15:15:25,834]  INFO {cps.server:196} Performing shutdown of Calibre-Web
[2020-12-22 15:16:10,774]  WARN {cps.config_sql:315} invalidating configuration
[2020-12-22 15:16:14,059]  INFO {cps:99} Starting Calibre Web...
[2020-12-22 15:16:14,314]  INFO {cps.server:168} Starting Tornado server on :8083
[2020-12-23 01:23:04,621]  WARN {cps.config_sql:315} invalidating configuration
[2020-12-23 01:23:08,200]  INFO {cps:99} Starting Calibre Web...
[2020-12-23 01:23:08,448]  INFO {cps.server:168} Starting Tornado server on :8083

**service file**

[Unit]
Description=Calibre-Web

[Service]
Type=simple
User=skynet2
EnvironmentFile=/home/skynet2/calibre-web/cps.conf
ExecStart=/usr/bin/python3 /home/skynet2/calibre-web/cps.py $ARG1 $ARG2
WorkingDirectory=/home/skynet2/calibre-web

[Install]
WantedBy=multi-user.target

**cps.conf**

ARG1 = -p
ARG2 = /home/skynet2/calibre-web/app.db

*** permisions calibre-web folder ***
-rw-rw-rw-  1 skynet2 skynet2 94208 Dez 23 14:04 app.db
-rw-rw-rw-  1 skynet2 skynet2    95 Dez  1 09:14 babel.cfg
-rw-rw-rw-  1 skynet2 skynet2  7725 Dez 24 08:25 calibre-web.log
-rw-rw-rw-  1 skynet2 skynet2  5051 Dez  1 09:14 CONTRIBUTING.md
drwxrwxrwx  8 skynet2 skynet2  4096 Dez  1 09:15 cps
-rw-r--r--  1 root    root       50 Dez  8 09:50 cps.conf
-rwxrwxrwx  1 skynet2 skynet2  2498 Dez  1 09:14 cps.py
-rw-rw-rw-  1 skynet2 skynet2 32768 Dez  1 09:15 gdrive.db
-rw-rw-rw-  1 skynet2 skynet2 35141 Dez  1 09:14 LICENSE
-rw-rw-rw-  1 skynet2 skynet2    21 Dez  1 09:14 MANIFEST.in
-rw-rw-rw-  1 skynet2 skynet2 55174 Dez  1 09:14 messages.pot
-rw-rw-rw-  1 skynet2 skynet2   770 Dez  1 09:14 optional-requirements.txt
-rw-rw-rw-  1 skynet2 skynet2  5428 Dez  1 09:14 README.md
-rw-rw-rw-  1 skynet2 skynet2   344 Dez  1 09:14 requirements.txt
-rw-rw-rw-  1 skynet2 skynet2  2365 Dez  1 09:14 setup.cfg
-rw-rw-rw-  1 skynet2 skynet2  1609 Dez  1 09:14 setup.py
drwxrwxrwx  4 skynet2 skynet2  4096 Dez  1 09:14 test
drwxrwxrwx 52 skynet2 skynet2  4096 Dez  1 09:15 vendor

Thanks,

**Comment by OzzieIsaacs** [comment]
`invalidating configuration` means the calibre database (metadata.db) is no longer reachable and therefore the configuration is invalidated. 
Please make sure to always have access to the metadata.db file while using Calibre-Web
