### ISSUE TITLE
Drop-down menus error.

### ISSUE THREAD

**Issue by yeraycito** [janeczku/calibre-web#1773]
**Describe the bug/problem**
When you access the calibre-web configuration and try to modify any option using the drop-down menus, they do not work ( the options appear but quickly disappear )
**To Reproduce**

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 Linux Mint 20
 Firefox last version
 Calibre-web download and install 24/12/2020
**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

**Comment by yeraycito** [comment]
I have noticed that the error only occurs when trying to make a change in the web-caliber configuration in the drop-down menus with the mouse. Doing so with the cursor keys on the keyboard works perfectly. I have tried to do this with different browsers (firefox - Chrome) and the same thing happens. I have tried to do different installations:

1 - requirements.txt by default without modification
2 - requirements.txt modified to the latest versions available
3 - requirements.txt by default changing tornado to gevent
4 - requirements.txt modified to the latest versions with gevent

In all installations the same error still occurs with the mouse.
Attached are some screenshots of the installation and post-installation.

![Captura de pantalla de 2020-12-27 15-13-51](https://user-images.githubusercontent.com/65027248/103174249-d99df480-4860-11eb-8c5b-50ecc8d38912.png)
![Captura de pantalla de 2020-12-27 15-54-57](https://user-images.githubusercontent.com/65027248/103174255-de62a880-4860-11eb-9c37-dad191e3ffda.png)

**Comment by OzzieIsaacs** [comment]
It seems to be a timing issue, some changes request a restart of calibre-web in the background, if the client needs to long to fetch all data from the server, it doesn't get all scripts loaded, so the javascript functions are not working. In this case, just press reload of the page and everything will work as expected. I will change this somewhere in the future
