### ISSUE TITLE
Cover not converted from epub to mobi

### ISSUE THREAD

**Issue by FPMilan** [janeczku/calibre-web#1774]
**Describe the bug/problem**
When converting a book out of calibre web from epub to mobi, the mobi file will have no cover.

**To Reproduce**
1. Go to a epub book with a cover
2. Click on Edit Metadata' 'convert from epub' to 'mobi'
3. Download mobi

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

**Expected behavior**
Mobi Version with Cover

**Screenshots**

**Environment (please complete the following information):**
 Tried lots of ebook-convert commands to twerk the output without success

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

**Comment by OzzieIsaacs** [comment]
I can't reproduce it. I tried a random epub book converted it via calibre ebook convert 5.7.2 on Linux Mint via the convert book function in Calibre-Web. Afterwards I opened the new generated mobi file with Calibre's ebook reader, the cover was there.

Calibre-Web is only using the converter from calibre, we are not programming it, so if you have trouble with the conversion, please ask for help at the calibre repository.
