### ISSUE TITLE
Reader problems

### ISSUE THREAD

**Issue by xiaozhangxia** [janeczku/calibre-web#1775]
I want the reader to unzip the ePub and read the HTML file directly。
I see a website online reading is like this, how can I do it
/books/mobile/e7/e7d9b88d34d2b1ebbc5c99bec0e8dfa2/text00001.html
/books/mobile/e7/e7d9b88d34d2b1ebbc5c99bec0e8dfa2/text00002.html
.....
I'm sorry, I can't speak English. This is my translation software

**Comment by OzzieIsaacs** [comment]
I'm sorry, this is not possible, I'm using a javascript library to display the epub's. It handles the books different with different links.
