### ISSUE TITLE
Comic reader can't not display cbz format book content in either Safari or Chrome browser

### ISSUE THREAD

**Issue by patricorgi** [janeczku/calibre-web#1776]
**Describe the bug/problem**
When open a cbz format comic book with "Read in Browser", it opens a webpage without any content. (see screenshot below)

![](https://tva1.sinaimg.cn/large/0081Kckwly1gm0xzs5kr2j31mb0u04qp.jpg)

**To Reproduce**

1. Create a new calibre library
2. Create an empty folder named `my_comic_book` and put a random jpg picture in it. 
3. Use Archive Utility in macOS to zip it and get `my_comic_book.zip` file
4. Import `my_comic_book.zip` file to the new library and calibre will automatically convert it to cbz format
5. Start calibre web server
6. Try to read this cbz book in Safari/Chrome browser.

**Environment (please complete the following information):**
 - OS: macOS 11.1
 - Python version: Python 3.7.9
 - Calibre-Web version: 2d3ae71
 - Docker container: None
 - Browser: Safari 14.0.2 (16610.3.7.1.9) / Chrome (87.0.4280.88 arm64)

**Comment by OzzieIsaacs** [comment]
Sorry, I accidentality merged an experiment to the master branch. 
Please update to the newest version, it should then work again

**Comment by patricorgi** [comment]
> Sorry, I accidentality merged an experiment to the master branch.
> Please update to the newest version, it should then work again

Now, it works like magic. Thank you so much for debugging!
