### ISSUE TITLE
Freenas jail only listening on TCP6

### ISSUE THREAD

**Issue by maxmangit** [janeczku/calibre-web#1778]
Installed a FreeNAS (TrueNAS) jail and it is not opening a web server. When I checked the listening ports it shows that the server is running on TCP6. Is there a way to change the listening port to TCP4? See output of netstat below:

          # netstat -an | grep LIST
          tcp6       0      0 *.8083                 *.*                    LISTEN

**Comment by OzzieIsaacs** [comment]
I guess you are having 2 possibility:
1) You might have installed gevent, if you remove this, calibre-web runs with tornado server, it's listening on ipv4 per default
2) You can start Calibre-web with the -i commandline option (https://github.com/janeczku/calibre-web/wiki/Command-Line-Interface#command-line-options), and then using "0.0.0.0" or "127.0.0.1" or your ip-address to make Calibre-Web listen on this address instead of all ipv6 addresses

**Comment by fahadshery** [comment]
@maxmangit could you share step by step how you set up the jail pls? I have been struggling with it and the community plugin is buggered. 
@OzzieIsaacs I managed to hack the community plugin and when I run:
```
which ebook-convert
```
It shows:
```
/usr/local/bin/ebook-convert
```
How do I enable the book conversion pls?

Many thanks

**Comment by OzzieIsaacs** [comment]
Go to adin-> basic configuration ->external binaries:

**Comment by OzzieIsaacs** [comment]
![grafik](https://user-images.githubusercontent.com/6438895/103301248-42bc6e00-4a01-11eb-9982-5c8dbb2078e8.png)
Enter `/usr/local/bin/ebook-convert` there and you should be able to convert books

**Comment by maxmangit** [comment]
When I try to run the Calibre-web via command-line, it gives me an error to mention the library. Do you know the directory?


> I guess you are having 2 possibility:
> 
> 1. You might have installed gevent, if you remove this, calibre-web runs with tornado server, it's listening on ipv4 per default
> 2. You can start Calibre-web with the -i commandline option (https://github.com/janeczku/calibre-web/wiki/Command-Line-Interface#command-line-options), and then using "0.0.0.0" or "127.0.0.1" or your ip-address to make Calibre-Web listen on this address instead of all ipv6 addresses

**Comment by maxmangit** [comment]
@fahadshery 

The installation was easy. Once you log in to the TrueNAS. Make sure you can resolve external DNS by going to the commandline and ping any public website. Go to Plugins > Select Community > Select Calibre-Web > Select DHCP for the IP Address.

Somewhere I read that sometimes TrueNAS (FreeNAS) plugins have issues with MAC Address. You can manually enter the MAC Address and it should put the libraries from Git.

**Comment by fahadshery** [comment]
@OzzieIsaacs perfect. that works perfect. 

@maxmangit I already had installed the community plugin but it wasn't starting under the `calibreweb` user.
I had to run it under `root` and it started working.
thanks

**Comment by OzzieIsaacs** [comment]
Problem solved?.
I'll close the issue.
