### ISSUE TITLE
Embedding broken (disabled?) after update 

### ISSUE THREAD

**Issue by cloo** [janeczku/calibre-web#1779]
I use Calibre-web as a part of my nextcloud-based ecosystem, as embedded "external site".
After update from 6.6 (or 6.7, not sure) to 6.9, I cannot open it embedded in nextcloud interface anymore.
I get a message: "To protect your security, knygos.ciri.institute will not allow Firefox to display the page if another site has embedded it. " in firefox and "knygos.ciri.institute refused to connect." in chrome. 
Without embedding, everything works fine.
Is there a way to enable embedding again?

**Comment by OzzieIsaacs** [comment]
From the nextcloud manual:
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/external_sites.html#configurations-preventing-embedding
The corresponding code in calibre-web, file cps/web.py, was done for security strengthening:
![grafik](https://user-images.githubusercontent.com/6438895/103166724-1cda7200-4825-11eb-9e64-7c5c797fdcdd.png)
You could delete the line 138, but I will not make this configurable or revert it.

**Comment by cloo** [comment]
Thanks @OzzieIsaacs, very detailed answer, even about nextcloud's policy. 
But I can't find this piece of code in cps/web.py. Is it from somewhere else?

**Comment by OzzieIsaacs** [comment]
Please go to the folder where Calibre-Web is installed, go to the cps folder, open the file web.py.
 Please go to line 133 (in version 0.6.9). It's there:https://github.com/janeczku/calibre-web/blob/a9c0bcb4a2441b0171966cfc32c60b6cf677c590/cps/web.py#L133

**Comment by cloo** [comment]
Thanks for your patience, but it is strangely not there..
![firefox_tgkGdBlk5Z](https://user-images.githubusercontent.com/651760/103167933-0853a500-4838-11eb-8cf0-b70ec2e9a93b.png)
web.py  in calibre-web/cps folder:
![firefox_oyv4k6w4l1](https://user-images.githubusercontent.com/651760/103167964-43ee6f00-4838-11eb-9ecf-c5a021f5ba48.png)

**Comment by OzzieIsaacs** [comment]
I don't know what you are having, but it's not 0.6.9, so there are 2 posibilities:
The file you opened is not the file you are using (most likely), or you are having a mess in the files.
Please check in the folder you think you are using the file constants.py, the version number should be there:
https://github.com/janeczku/calibre-web/blob/a9c0bcb4a2441b0171966cfc32c60b6cf677c590/cps/constants.py#L131
And please try to reinstall calibre-web, to get the right files

**Comment by cloo** [comment]
You were right! Silly me, moved to docker some day for some reason. and forgot to remove folder from webroot. 
We can close it now, I guess. I guess we should leave only the question and answer, to keep conversation useful for others?

**Comment by red4dj** [comment]
Shouldn't this be modernized to frame-ancestors within the CSP? It would allow embedding through the already configurable domains. Same security, allows embedding, and no new configuration changes. https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives#frame-ancestors

**Comment by EnduringGuerila** [comment]
I too would like to embed this into our nextcloud, is deleting 'sameorigin' still the best option?
