### ISSUE TITLE
Doesn't work when behind a TLS reverse proxy

### ISSUE THREAD

**Issue by gramster** [janeczku/calibre-web#1785]
**Describe the bug/problem**

I looked at the reverse proxy section on the wiki but that doesn't seem to be applicable here, as I want to use the calibre-web login form for authentication. This may be related top https://github.com/janeczku/calibre-web/issues/838 but there the suggestion is to use a reverse proxy which is exactly what I am doing. So this seems like a bug to me.

I am running calibre-web in a Docker container on a Synology. It works fine if I hit the port directly (I'm using 4001). However, for external access I want to use a reverse proxy, so that I can map https://books.mydomain.com to http://localhost:4001.

I have a similar proxy set up for a couple of other services in exactly the same way (e.g. comics.mydomain for Ubooquity), and they are all working fine. However, with Calibre-web, when I hit the URL, I get a redirect to http://books.mydomain/login?next=%2F, and that just spinds for a while before failing with an EMPTY-RESPONSE.

The problem is that the https:// is being changed to http://. If I manually change back to TLS, I get a login prompt. If I then enter credentials, I have a similar problem happen; I get redirected to http://books.mydomain instead of https://books.mydomain.

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

**Expected behavior**

Keep the protocol. I guess this would involve looking at the protocol in the request's headers, and preserving that in the response's Location header when doing the redirect.

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10/Raspberry Pi OS] - Linux (Synology)
 - Python version: [e.g. python2.7]
 - Calibre-Web version: [e.g. 0.6.8 or 087c4c59 (git rev-parse --short HEAD)]:
 - Docker container: [None/Technosoft2000/Linuxuser]: linuxserver/calibre-web
 - Special Hardware: [e.g. Rasperry Pi Zero]
 - Browser: [e.g. Chrome 83.0.4103.97, Safari 13.3.7, Firefox 68.0.1 ESR] Chrome

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

**Comment by OzzieIsaacs** [comment]
> Keep the protocol. I guess this would involve looking at the protocol in the request's headers, and preserving that in the response's Location header when doing the redirect.

For this the `proxy_set_header        X-Scheme        $scheme;` is responsible. Depending on your reverse proxy the syntax might be different. 
In this example the requesting protocol should be kept, to fix it to https replace `$scheme` with `https`, this is working for me since years (I'm using apache)

**Comment by gramster** [comment]
An odd thing happened - my SSL certificate was set up just for mydomain, but today I got a new one from LetsEncrypt that included *.mydomain, and now things are working for me. Closing this as it is no longer an issue.
