### ISSUE TITLE
Can't find the "Send to Kindle" option

### ISSUE THREAD

**Issue by Nevarro** [janeczku/calibre-web#1786]
**Describe the bug/problem**
I entered all the E-Mail credentials but I can't find the option to send eBooks to my kindle anywhere in Calibre web.

**To Reproduce**
1. Click on eBook cover.
2. No "send to Kindle"-option, only "Download" and "Read in Browser"

**Logfile**
-

**Expected behavior**
A button to send the eBook to Kindle should appear.

**Screenshots**
-

**Environment (please complete the following information):**
 - OS: [macOS Catalina 10.15.7; Safari 14.0.2 ]
 - Calibre-Web version: [0.6.9]:
 - Docker container: [linuxserver/Calibre-web]:
 - Browser: [Safari 14.0.2]

**Additional context**
Sorry if my question is stupid and for opening an issue here. I'm no tech-newbie but I really can't find the option.

**Comment by OzzieIsaacs** [comment]
You have to configure email sending first. Please go to the admin section and configure the email account you want to sent the emails from:
![grafik](https://user-images.githubusercontent.com/6438895/103348303-e2c5d600-4a99-11eb-8bd1-f3ef422d6ffb.png)

Afterwards please check in the users section if the user you try to send the email with has a valid kindle email address configured:
![grafik](https://user-images.githubusercontent.com/6438895/103348330-fc671d80-4a99-11eb-8954-fed922e64174.png)

**Comment by Nevarro** [comment]
I did both. Test-Mail is working too. However, there's no option to send it to Kindle.

**Comment by OzzieIsaacs** [comment]
The only formats allowed to send to kindle are mobi/azw and pdf (azw3 is blocked by amazon's server and therefore not offered).
The option to convert on the fly before sending is only offered if the calibre-converter is present.

**Comment by Nevarro** [comment]
> The only formats allowed to send to kindle are mobi/azw and pdf (azw3 is blocked by amazon's server and therefore not offered).
> The option to convert on the fly before sending is only offered if the calibre-converter is present.

I haven‘t thought about that. Thanks so much and sorry for bothering.

**Comment by OzzieIsaacs** [comment]
Your welcome
