### ISSUE TITLE
after google drive authentication - nothing happen 

### ISSUE THREAD

**Issue by C4T4** [janeczku/calibre-web#1792]
**Describe the bug/problem**
Hi, after the google drive authentication I'm redirected to 
`https://***.com/gdrive/redirect/?code=******Qgfu**cOx0Kj6*****Y8lmw&scope=https://www.googleapis.com/auth/drive`
(it's the start page of calibre-web) and nothing happens.

If I go back to the config settings, I can repeat but with the same result.

**To Reproduce**
1. Go to /admin/config
2. Click on "Authenticate Google Drive"
3. follow the google auth 

**Logfile**
logfile is on debug mode buth there is nothing relevant

[2021-01-01 19:19:04,183]  WARN {cps.admin:101} reconnecting to calibre database
[2021-01-01 19:19:22,860] DEBUG {cps.helper:682} unrar version 5.50
[2021-01-01 19:19:22,862] DEBUG {cps.config_sql:308} _ConfigSQL updating storage
[2021-01-01 19:19:25,074] DEBUG {cps.helper:682} unrar version 5.50
[2021-01-01 19:19:25,080] DEBUG {cps.config_sql:308} _ConfigSQL updating storage

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Python version: 3.6.9
 - Calibre-Web version: 0.6.9 
 - Docker container: ghcr.io/linuxserver/calibre-web:

**Additional context**

    upstream calibre {
        server 127.0.0.1:8083;
    }

	server {
			client_max_body_size 20M;
			listen [::]:443 ssl ipv6only=on; # managed by Certbot
			listen 443 ssl; # managed by Certbot
			ssl_certificate /etc/letsencrypt/live/****/fullchain.pem; # managed by Certbot
			ssl_certificate_key /etc/letsencrypt/live/****/privkey.pem; # managed by Certbot
			include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
			ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
		location / {
			proxy_bind              $server_addr;
			proxy_pass              http://calibre;
			proxy_set_header        Upgrade $http_upgrade;
			proxy_set_header        Connection 'upgrade';
			proxy_set_header        Host $host;
			proxy_cache_bypass      $http_upgrade;

		}
	}

  docker-compose.yml

  version: "2.1"
  services:
    calibre-web:
      image: ghcr.io/linuxserver/calibre-web
      container_name: calibre-web
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Berlin
        - DOCKER_MODS=linuxserver/calibre-web:calibre
      volumes:
        - /volume1/config/calibre:/config
        - /volume1/books/calibre:/books
        - /etc/letsencrypt/live/waack.info:/certs
      ports:
        - 8083:8083
      restart: unless-stopped

**Comment by OzzieIsaacs** [comment]
I can't reproduce this, for me it's working. I don't know how to help you
