### ISSUE TITLE
Redirect to login page behind traefik

### ISSUE THREAD

**Issue by Marketos-Damigos** [janeczku/calibre-web#1793]
**Describe the bug/problem**
Calibre-web (ls.io docker image) behind traefik v2 logins but after some time (or clicks) redirects to login page.

**To Reproduce**
1. Login
2. Browse (doesn't matter where)
3. Back to login page

**Logfile**
Nothing interesting

**Expected behavior**
It should stay logged in

**Environment (please complete the following information):**
 - OS: Latest Docker image from linuxserver.io

**Additional context**
Connection directly to the IP doesn't reproduce the problem (so it has to do with traefik)

**Comment by OzzieIsaacs** [comment]
Sorry, I'm only supporting the Calibre-Web repro. I can't support each and every reverse proxy configuration in combination with some other tools (here Docker). Please ask for help at a traefik forum, or the docker provider.
The only hint I can give you: The login is stored in a session cookie, which expires in the far future. So if you get logged out, I guess this cookie is lost, or not passed to Calibre-Web. (You can see the cookie in chrome or Firefox, and I guess also in Edge and Safari in the developer tools section:
![grafik](https://user-images.githubusercontent.com/6438895/103458891-37708780-4d0c-11eb-95be-3f59929546c4.png)
If "path" in the cookie is not matching this could be another reason

**Comment by kjboa** [comment]
I have exactly the same issue. Have you by any chance found a solution?

**Comment by Marketos-Damigos** [comment]
> I have exactly the same issue. Have you by any chance found a solution?

No, unfortunately not. I still face the issue and i am not that good with HTTP stuff to fix it.
