### ISSUE TITLE
Cannot set cover image for a CBR file

### ISSUE THREAD

**Issue by jbcpollak** [janeczku/calibre-web#1795]
**Describe the bug/problem**

I am not able to use a remote url to update the cover of a CBR file.

**To Reproduce**
Upload CBR
Edit Metadata
Fetch Metadata
Select match
New cover appears as URL
Click save
First page of CBR appears as the cover image

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

**Expected behavior**
I was expecting the remote url cover image to be set in the catalog.

**Screenshots**

**Environment (please complete the following information):**
- Docker image on Synology NAS
- Version:  0.6.9 - a9c0bcb4a2441b0171966cfc32c60b6cf677c590 - 2020-09-27T07:15:03+02:00

**Comment by OzzieIsaacs** [comment]
This sounds like a known problem. It‘s abrowser caching problem, reloading the page should solve the problem, it will be fixed in the next release

**Comment by jbcpollak** [comment]
confirmed, a forced cache-bust reload shows the new cover. Thanks.

>
