### ISSUE TITLE
Is it possible to see shelves created from calibre-web in Calibre Desktop

### ISSUE THREAD

**Issue by cerbaire** [janeczku/calibre-web#1799]
**Describe the bug/problem**
I would like to associate my books to shelves from Calibre Desktop, as it is not possible to do it easily from calibre-web.

**Expected behavior**
1. I create a shelf from calibre-web
2. I open Calibre Deskop and can see the shelf from the My Shelves entry (#myshelves:true)
3. Then I can associate my books to a shelf and check in calibre-web that my book appears under the previously created shelf

**Comment by OzzieIsaacs** [comment]
I thought about this in the past, and decided not to implement it. 
Reason:
The Calibre database itself is made for a single user system and only stores book related stuff and is not capable of (= not having a table to store this information) storing this sort of information. As I want to be compatible to Calibre I'm not willing to extend the calibre database (and I don't know if Calibre would accept this extended databases). A limited solution would be to use a custom column as this can be done for the read status, but I think a single user could also handle shelfs via categories/series. 
In a multi user environment I would have to store user, shelf name, position for each shelf (as the original purpose of a shelf was having a reading list). I had to find a custom column type to handle this data, each book must be capable of storing this dataset for several users and for several shelfs, it would be definitely very ugly and not intuitive to read in Calibre.

**Comment by OzzieIsaacs** [comment]
Ah and: The shelf information is not stored in Calibre database, but in Calibre-web's own settings database.

**Comment by Floppy** [comment]
Could this not work in the same way as the optional "Read" column, which is surely per-user but stored in calibre DB? 

So a user could specify a column in calibre to use for their shelf names. Storage of position, which user is which, etc, still stays in calibre-web, and it wouldn't replicate *all* the information back, but it would solve a simple use case of "I have a custom field in calibre, and would like it to be used as my shelves in calibre-web".

**Comment by Floppy** [comment]
It's a slight tweak in the original use case here, where shelves created in calibre-web wouldn't go *back*, but you as long as you create the custom column in Desktop, then it would work from there TO calibre-web.

**Comment by Floppy** [comment]
User journey:

1.  I create a custom column in Calibre Desktop and set it to (for example) "Scifi" for a number of my books.
2. I tell calibre-web to use my custom column as Shelf names in the settings, near the option for the custom "Read" column.
3. A shelf called Scifi appears in calibre-web (along with any other values I've set) for my user. Any existing shelves created within calibre-web are discarded or hidden.
3. My books tagged with Scifi in that custom column appears under the appropriate shelf.

Another user could choose a different custom column, or none.

**Comment by cerbaire** [comment]
Hi,
@OzzieIsaacs Thanks for your response, I understand your point of view.
@Floppy Thanks for you suggestion. I tried it but I cannot get it to work.
1. I successfully created a new column in Calibre desktop and I can see it in Calibre Web
2. I added this new column in the 'View Restrictions based on Calibre column' setting of UI Configuration
- All my shelves created in Calibre Web still appears and I do not see values put on books for that new column in Calibre Desktop.
- I do not have the option to change this setting for other user than admin. 
Any advice on what I may have done wrong?
Many thanks for your support

**Comment by SingingDwarf** [comment]
> User journey:
> 
> 1. I create a custom column in Calibre Desktop and set it to (for example) "Scifi" for a number of my books.
> 2. I tell calibre-web to use my custom column as Shelf names in the settings, near the option for the custom "Read" column.
> 3. A shelf called Scifi appears in calibre-web (along with any other values I've set) for my user. Any existing shelves created within calibre-web are discarded or hidden.
> 4. My books tagged with Scifi in that custom column appears under the appropriate shelf.
> 
> Another user could choose a different custom column, or none.

Where do you see the option to use custom column as Shelf names in the settings? In the Edit UI Configuration > View Configuration option I see Link Read/Unread Status to Calibre Column, but nothing about Shelf names.

I am running v0.6.16

**Comment by cerbaire** [comment]
> > User journey:
> > 
> > 1. I create a custom column in Calibre Desktop and set it to (for example) "Scifi" for a number of my books.
> > 2. I tell calibre-web to use my custom column as Shelf names in the settings, near the option for the custom "Read" column.
> > 3. A shelf called Scifi appears in calibre-web (along with any other values I've set) for my user. Any existing shelves created within calibre-web are discarded or hidden.
> > 4. My books tagged with Scifi in that custom column appears under the appropriate shelf.
> > 
> > Another user could choose a different custom column, or none.
> 
> @Floppy Where do you see the option to use custom column as Shelf names in the settings? In the Edit UI Configuration > View Configuration option I see Link Read/Unread Status to Calibre Column, but nothing about Shelf names.
> 
> I am running v0.6.16

@SingingDwarf @Floppy I used the 'View Restrictions based on Calibre column' setting to set my custom column. When set, all my shelves in Calibre-web disappears.
Reading the comment of @Floppy a second times let me think that it was just a suggestion on how my need could be implemented in Calibre-web, but it is currently not.

**Comment by Floppy** [comment]
Yes, sorry, it was a suggestion for a potential solution, not a thing that works right now :)

**Comment by pmdci** [comment]
@OzzieIsaacs Your reasons for not wanting to extend the Calibre DB make sense. I'm very keen to start using Calibre-web, and I will, but the drawback is that I have multiple libraries, and I guess I'll have to only support my main one.

My libraries:
- Fiction
- Non-fiction (my main one!)
- User guides and manuals
- Role Playing Games

I don't think I'm alone in having such set-up, so I think that support for switching libraries would be great.

Either way this is a great project and I thank the devs for all their efforts.
