### ISSUE TITLE
Setup on macOS environment

### ISSUE THREAD

**Issue by sramauge** [janeczku/calibre-web#1802]
**Describe the bug/problem**
My calibre database is on my machos Catalina
I ll setup a lamp system with http://ampps.com/downloads
Is it possible to setup calibre-web on it ?

Thanks

**Expected behavior**
Work on macOS system

**Comment by OzzieIsaacs** [comment]
Yes, sure

**Comment by OzzieIsaacs** [comment]
Calibre-web provides it's own server components. It's a standalone program. 
You can just install python and run it. 
The computer running calibre-web can of course run some other programs. 
You don't need any other programs.
Python can run on MacOS, so calibre-web can also (last time I tried it).

(? I'm not sure, what you are expecting exactly from me ?)

**Comment by sramauge** [comment]
Hello

It was just a question because  I didn't see in the description (or I miss it)  if it works on macOS
So I've installed python and it's working fine

so thanks

**Comment by OzzieIsaacs** [comment]
The readme is not saying anything about platforms, that's right. Calibre-Web is running on every platform which is capable of executing python scripts (Windows, Linux, MacOS, BSD, Rasperry Pi, NAS, ...)
