### ISSUE TITLE
Working fine, then stopped.

### ISSUE THREAD

**Issue by itchygrub** [janeczku/calibre-web#1805]
Ubuntu 20.4 server
AMD PC
Python 3.8
ca212c87
Firefox 84.0.2

systemctl start cps
system status cps

Get following error
cps.service - Calibre-Web
     Loaded: loaded (/etc/systemd/system/cps.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2021-01-10 02:26:06 UTC; 21min ago
   Main PID: 18636 (python3)
      Tasks: 2 (limit: 19014)
     Memory: 47.3M
     CGroup: /system.slice/cps.service
             └─18636 /usr/bin/python3 /opt/calibre-web/cps.py

Jan 10 02:26:06 homeserver systemd[1]: Started Calibre-Web.
Jan 10 02:26:07 homeserver python3[18636]: Traceback (most recent call last):
Jan 10 02:26:07 homeserver python3[18636]:   File "/opt/calibre-web/cps.py", line 36, in <module>
Jan 10 02:26:07 homeserver python3[18636]:     from cps.opds import opds
Jan 10 02:26:07 homeserver python3[18636]:   File "/opt/calibre-web/cps/opds.py", line 34, in <module>
Jan 10 02:26:07 homeserver python3[18636]:     from .helper import get_download_link, get_book_cover
Jan 10 02:26:07 homeserver python3[18636]:   File "/opt/calibre-web/cps/helper.py", line 54, in <module>
Jan 10 02:26:07 homeserver python3[18636]:     from .tasks.convert import TaskConvert
Jan 10 02:26:07 homeserver python3[18636]: ModuleNotFoundError: No module named 'cps.tasks.convert'

Had the site working fine.
Was trying to get the registration working and changing admin default password(still having problem).
Was able to email book to kindle
Was able to reach from internet
Did a reinstall of software
Same error message  

Mitch

**Comment by OzzieIsaacs** [comment]
The error message `ModuleNotFoundError: No module named 'cps.tasks.convert'` points to a missing file , or a not accessible file.

Could you please check if the file `/opt/calibre-web/cps/tasks/convert.py` is existent and also accessible by the user running calibre-web?

**Comment by itchygrub** [comment]
Ozzie

Thanks for the reply.
I trashed the whole system.
I did a full rebuild of server.
Reinstall of calibre-web.
Have it up an running.
books.honeyset.net:8083
I have mutliple Calibre libraries to make.

Please close. As it was my mistake. Am retired just getting back into a learning curve.

Mitch

On 10/01/2021 18:02:54, Ozzie Isaacs <notifications@github.com> wrote:
The error message ModuleNotFoundError: No module named 'cps.tasks.convert' points to a missing file , or a not accessible file.
Could you please check if the file /opt/calibre-web/cps/tasks/convert.py is existent and also accessible by the user running calibre-web?
