### ISSUE TITLE
Search query loads every possible result in 1 page

### ISSUE THREAD

**Issue by dedostorpes** [janeczku/calibre-web#1807]
I have Calibre-Web configured to show only 10 books per page.

When I perform a search, the program loads every result and won't "divide" the results in pages. 

For example, if I search the term "Yoga", the app loads the 50 ebooks in 1 single page instead of 5 pages.

I don't know if this is normal behaviour. There are some queries that take some time to load, depending on the number of books related.

Am I missing some config? Couldn't find anything. The pagination works fine in the home page, but not when I perform a search.

Thanks

**Comment by OzzieIsaacs** [comment]
For me it's working:
![grafik](https://user-images.githubusercontent.com/6438895/104365533-67900580-5518-11eb-82f6-7ef97ffc81dd.png)

Which version are you using?

**Comment by dedostorpes** [comment]
I'm using the latest version.

It's a clean install. The pagination only works when I filter by publisher, genre or Home page. 

I noticed that infinite scrolling is enabled. Is there any way to change that? I cannot change pages manually. Maybe the issue is associated it with infinite scrolling. 

Thanks for your help.

**Comment by OzzieIsaacs** [comment]
If the result isn't fitting on page infinity scrolling is enabled per default. If the no of results fit on one page you will see the pagination. This behaviour is the same for all pages (search, authors, series,...):
Showing 5 books per page:
![grafik](https://user-images.githubusercontent.com/6438895/104956198-eaf3a000-59cb-11eb-8265-0f2da477e3d5.png)
Showing 6 books on a slightly smaller screen:
![grafik](https://user-images.githubusercontent.com/6438895/104956266-14143080-59cc-11eb-99b3-e94738b28e1d.png)
By scrolling down now infinite scrolling starts to work

This can't be disabled.
