### ISSUE TITLE
Incorrect type for azw3 in opds

### ISSUE THREAD

**Issue by erys** [janeczku/calibre-web#1811]
**Describe the bug/problem**
azw3 books are listed as "application/octet-stream" in opds when they should be  "application/x-mobi8-ebook"
This causes some opds readers to not recognize the books as being in a supported format. 

**To Reproduce**
1. Have an ebook in azw3 format
2. View the book in the opds feed.
3. The type of the book in the acquisition specification will be listed as "application/octet-stream"

**Expected behavior**
The type should be "application/x-mobi8-ebook" as it is in the built in calibre server. 

**Environment (please complete the following information):**
 - OS: LibreElec
 - Python version: python 2.7
 - Calibre-Web version: 0.6.9
 - Docker container: linuxserver
 - Special Hardware: Raspberry pi 4
 - Browser: N/A

**Comment by RandomDennisLee** [comment]
@OzzieIsaacs was this issue fixed? Because I'm still seeing it on the latest version.
