### ISSUE TITLE
Support for CB7 format, maybe switching to libarchive

### ISSUE THREAD

**Issue by frspackager** [janeczku/calibre-web#1816]
**Is your feature request related to a problem? Please describe.**
There seem to be no support of CB7 Comic Book Archive format

**Describe the solution you'd like**
Maybe use a similar approach than for CBR, CBZ and CBT with [py7zr](https://pypi.org/project/py7zr/) module or (maybe a larger change but that can offer a lot more flexibility) use [libarchive](http://libarchive.org) and [python libarchive module](https://pypi.org/project/libarchive/) as an abstraction layer to all types of archives. Libarchive comes packaged on a lot of recent linux distributions, works on macOS via brew or macports, not sure for windows.

**Comment by OzzieIsaacs** [comment]
I think py7zr will do the job. 
There a 2 places where it has to be changed, in python code to extract covers and in the comic reader (javascript code, "kthoom" lib).
I personally have never seen a comic book using this format, is this a very widely spread format according to your experience?

**Comment by frspackager** [comment]
> I think py7zr will do the job. 
> 
> There a 2 places where it has to be changed, in python code to extract covers and in the comic reader (javascript code, "kthoom" lib).

Understood. Any thought on using libarchive? That would remove the dependency on external unrar binary and cover all formats but will prevent the use of ComicsArchive but not ComicsAPI. I just can't appreciate the magnitude of the potential change throughout the whole code.

> I personally have never seen a comic book using this format, is this a very widely spread format according to your experience?

I would say CB7 is less common than CBR or CBZ but more than CBT according to my experience. It's also a great way to keep images archives compact when you work with large image source like drone pictures, etc... 7Zip is LZMA and widely available.

My two cents...

**Comment by OzzieIsaacs** [comment]
The change to libarchive looks to me bigger than just adding py7zr. And currently I'm having other priorities than refactoring the comic extraction. Even using libarchive would not remove the need to add 7z support to the comic reader to make it a complete package

**Comment by frspackager** [comment]
You are correct. I am also working on other projects at this time but I will give a go at the libarchive approach (it can benefit my another project) and why not send a PR if I succeed.

Do you want me to close the issue?

**Comment by OzzieIsaacs** [comment]
Please leave it open for the cb7 support

**Comment by frspackager** [comment]
No problem.

Just looking at the code, I saw you carry pure javascript libraries to deal with zip, rar, tar (static/js/archive) and wanted to let you know I found one pure js for 7zip: https://github.com/stil/sevenzip.js. I have not used it yet.

**Comment by OzzieIsaacs** [comment]
The repository you linked is no longer accessible

**Comment by frspackager** [comment]
That's crazy, the GitHub repository is still open in my browser and I downloaded the released code yesterday. The author must have deleted it right after I connected. I can share the released code with you but regarding its maintainability it now seem compromised at best.
