### ISSUE TITLE
Language selector shows chinese characters when editing book metadata in english UI

### ISSUE THREAD

**Issue by Ashtronaughte** [janeczku/calibre-web#1819]
**Describe the bug/problem**
The language selector when editing book metadata is not in English when the site is set to English. Problem arose after updating to latest web version. Languages display correctly when selecting languages from sidebar.

**To Reproduce**
1. Upload book/ edit book metadata
2. Under "language", the text is not english

![image](https://user-images.githubusercontent.com/16417586/104947401-b828b800-5989-11eb-8ffc-5f6483d1797d.png)
![image](https://user-images.githubusercontent.com/16417586/104947451-c7a80100-5989-11eb-9004-c00d3e081317.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Python version: 3.8.5
 - Calibre-Web version: 0.6.10 - 9418045a2cbd8646524d1b8181057084a41e1a99 - 2021-01-17T16:28:28+01:00
 - Docker container: None
 - Special Hardware: AWS Lightsail instance
 - Browser: Chrome 87.0.4280.141

**Comment by OzzieIsaacs** [comment]
Funny, but reality.
Language selection is displayed in chinese

**Comment by OzzieIsaacs** [comment]
Please update to the newest nightly version and the problem should be gone

**Comment by amasolini** [comment]
@OzzieIsaacs thanks for the fix. 

Do you have any plans on creating a hotfix on the stable version? I'm not running nigthly as I prefer to run the stable one.

**Comment by OzzieIsaacs** [comment]
I will do a new release soon (<2days)
