### ISSUE TITLE
Get Metadata no longer working?

### ISSUE THREAD

**Issue by simkin** [janeczku/calibre-web#182]
Did not test it for a while but when a click the book cover in the search window, no metadata text/cover is grabbed/copied.

The log is empty, which make sit hard to debug. Please advise

Steps: Click Book --> Select "Edit metadata" --> Select "get metadata" --> Click Book cover

> Program library	Installed Version
> Python	2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
> Kindlegen	Amazon kindlegen(Linux) V2.9 build 1028-0897292
> ImageMagick	ImageMagick 6.8.9-9 Q16 x86_64 2016-11-26 http://www.imagemagick.org
> PyPDF2	v1.26.0
> Babel	v1.3
> SqlAlchemy	v0.8.3
> Flask	v0.12
> Flask Login	v0.4.0
> Flask Principal	v0.4.0
> Tornado web server	v4.1
> ISO639 Languages	v0.4.5
> Requests	v2.13.0
> SQlite	v3.16.2
> Pysqlite	v2.8.3

**Comment by idalin** [comment]
Code cosmetics introduced this. I'll fix it in a few days.

**Comment by OzzieIsaacs** [comment]
Sorry guys. Should work now again
