### ISSUE TITLE
Bulk Edit user permissions

### ISSUE THREAD

**Issue by rg9400** [janeczku/calibre-web#1821]
**Is your feature request related to a problem? Please describe.**
Whenever a new permission is added, I need to go in to modify all my existing users. Since I have over 30 of them, that process can be fairly painful. For example, recently, the permission to see Downloaded Books was added, and I wanted to enable it for everyone, but I saw no quick way to do it, only setting it for new users.

**Describe the solution you'd like**
Maybe give an option to multi-select and edit users, giving a similar UI like shown when accessing Default Visibilities for new users.

**Describe alternatives you've considered**
Just manually edit each user each time the permissions need to be changed en masse.

**Additional context**
Side note: I notice that as an admin, I can no longer see downloaded books by user by clicking on their profile. Is there another way to see those books? I now see the tab on the left side menu, but it seems to be my downloaded books only.

**Comment by OzzieIsaacs** [comment]
Related to #1651
Reasonable request

**Comment by OzzieIsaacs** [comment]
The feature is implemented in the newest version of calibre-web
