### ISSUE TITLE
Admin user does not exist after install in some edge case

### ISSUE THREAD

**Issue by flying-sausages** [janeczku/calibre-web#1824]
**Describe the bug/problem**
So I'm really not sure what the hell is happening here, but my install script is failing to change the admin password after a reinstall due to "admin" not existing on one of the machines I tested it on.

**To Reproduce**
1. Remove previous installation of calibre-web and the entire folder it resides in, code and `app.db` included
2. Re-install calibre-web through swizzin (https://github.com/swizzin/swizzin/pull/401)
2. Installer attempts to change the admin's password thorugh `cps.py -s admin:password` (https://github.com/swizzin/swizzin/pull/401/files#diff-909d99a14d7f626912e0522d1a2a6158a13a7629233062b271c8c1db54f66b76R146)
3. Admin apparently doesn't exist

The problem is I'm unable to reproduce this on my personal ARM environment, and so I wouldn't know what is at play that would 

**Logfile**
This is the entire log from the swizzin install. The notable line here is the last non-log one from the bottom, where `cps.py` says `admin` does not exist.
https://privatebin.net/?d0e129401bb36c1a#YKpbhTrPGXBCLP3Bvd6aB6P6WNUpK2AHbGaA2v34tCF

**Expected behavior**
The username `admin` exists and the password can be changed for it

**Screenshots**
this is the output of `cps.py -s admin:password`
<img width="856" alt="Untitled" src="https://user-images.githubusercontent.com/23618693/105090740-15faf400-5a9f-11eb-9c29-c38cf472623e.png">

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 (intel)
 - Python version: Python3
 - Calibre-Web version: 0.6.10
 - Docker container: None
 - Special Hardware: Intel and ARM64
 - Browser: N/A

**Additional context**
I don't know exactly how to reproduce this 100% so any tips on that would be super helpful. Thanks in advance!

**Comment by OzzieIsaacs** [comment]
I can' access the logfile on privatebin. 
I'd like to avoid installing and running this scripts and the environment might be needed. 

After the first start Calibre-Web is generating the app.db database and "manually" inserting the admin and guest user. If your call to change the password is to early (app.db is not written finally to the the drive, or even admin user isn't inserted yet), it might be possible that the change password request fails -> timing issue

**Comment by flying-sausages** [comment]
Aha, That's good to know! That would explain why it would be specific to slow intel architectures; the machine i'm testing on did not need any sleep between the library setup and the admin password change.

I'm going to see if I can create some sort of a loop that would check the SQL and add a timeout then, and see if that would work. I'll post the code here when I've got it too.
