### ISSUE TITLE
Calibre / Calibre web: importing book in Calibre library results in double entry in metadata.db

### ISSUE THREAD

**Issue by MarGer1962** [janeczku/calibre-web#1827]
OS: Windows 10
Python version: [e.g. python2.7]
Docker container: LinuxServer:
Browser: Firefox 84.02

NAS Synology D716+
DSM 6.2.3-25426 Update 3 (Version is up to date)
janeczku / calibre-web version 0.6.10 (version is up to date)
I installed janeczku / calibre-web  with Docker

The file metadata.db is located in my NAS (Docker \Calibre\Books)
Calibre (PC) points to that file

I use Calibre, version 5.10.0 on my PC

I have created read/write rights in my Synology directories Docker\Calibre for (username)
I stopped Calibre-web on my NAS (Reason: so there could be no interference by other user) 

I have logged in on my PC and started Calibre as (username)
I started Calibre on my PC

I wanted to import the epub Winter Raven - Baker Adam
Because i want to sort the author by Lastname > I changed Adam Baker into Baker, Adam
Then i searched for another bookcover (bigger)
I imported that bookcover

Then i clicked op OK 
Then i got Messages (see hereafter)

Expected behavior
I expected that i could change the information,(author) and bookcover and then adjust the book to my books
I expected to adjust this one book to my books. 

But ... i got these messages that o.a. the database was could not be opened.
AND (see attached files)

The strangest thuing is that in de database it look likes there are twee entries for the book in Calibre Web!
Strange because: according to the messages the database file could not be opend : so how is it possible that there is even one entry?

Furthermore
Although i clicked Cancel (in Calibre program on PC) it seems that there are (also) two entries for the book!
I expected that ther would not be any entry in Calibre on my PC (because i clicked Cancel)

==== Messages

FOUT: Niet afgehandelde fout: <b>CantOpenError</b>:CantOpenError: unable to open database file

calibre 5.10 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: nl
Successfully initialized third party plugins: BOL_NL (4, 5, 0)
Traceback (most recent call last):
  File "calibre\gui2\metadata\single.py", line 640, in accept
  File "calibre\gui2\metadata\single.py", line 615, in apply_changes
  File "calibre\gui2\metadata\basic_widgets.py", line 416, in commit
  File "calibre\db\legacy.py", line 915, in func
  File "calibre\db\cache.py", line 72, in call_func_with_lock
  File "calibre\db\cache.py", line 1206, in set_field
  File "calibre\db\cache.py", line 1220, in update_path
  File "calibre\db\backend.py", line 1664, in update_path
  File "calibre\db\tables.py", line 613, in set_fname
  File "calibre\db\backend.py", line 920, in execute
apsw.CantOpenError: CantOpenError: unable to open database file

**Then when clicking OK, i got this message**

calibre, version 5.10.0
FOUT: Toegang geweigerd: Kan van dit boek de locatie op de harde schijf niet wijzigen. Is dit boek geopend in een ander programma?
_TRANSLATION: ERROR: Access Denied: Unable to change the location of this book on the hard drive. Has this book been opened in another program?_

Locked file: \\NasQiMatou\docker\calibre\books\Adam Baker/Winter Raven (9505)\Winter Raven - Adam Baker.epub

Traceback (most recent call last):
  File "calibre\gui2\metadata\single.py", line 615, in apply_changes
  File "calibre\gui2\metadata\basic_widgets.py", line 230, in commit
  File "calibre\db\legacy.py", line 929, in func
  File "calibre\db\cache.py", line 72, in call_func_with_lock
  File "calibre\db\cache.py", line 1206, in set_field
  File "calibre\db\cache.py", line 1220, in update_path
  File "calibre\db\backend.py", line 1660, in update_path
  File "calibre\db\backend.py", line 1522, in copy_format_to
  File "calibre\db\backend.py", line 1342, in format_abspath
  File "shutil.py", line 261, in copyfile
PermissionError: [Errno 13] Permission denied: '\\\\NasQiMatou\\docker\\calibre\\books\\Adam Baker/Winter Raven (9505)\\Winter Raven - Adam Baker.epub'

Then i clicked Cancel

======== Questions:
1. is it good practice to shut Calibre-web down BEFORE i make an entry in Calibre on PC? Or is it better to keep it running?
 
2.is there a manual or best practice on how to use Calibre / Calibre-Web server for importing books?

**ATTACHED PICS**
=====the entry in Calibre
![Calibre WinterRaven](https://user-images.githubusercontent.com/77753615/105610977-03d8c880-5db3-11eb-9032-5f7cb8fef126.PNG)

====== how it shows in Calibre web: 2 result if searched for Winter Raven: 2 entries!! 
![CalibreWeb WinterRaven](https://user-images.githubusercontent.com/77753615/105610981-0e935d80-5db3-11eb-936e-431b53d097fa.PNG)

====== how it shows in Calibre web: 1 entrie, coverimage and epub
![CalibreWeb WinterRaven 02](https://user-images.githubusercontent.com/77753615/105610979-0d623080-5db3-11eb-8a27-a0b0c2f08386.PNG)

====== how it shows in Calibre web: 1 entrie, no coverimage / no epub
![CalibreWeb WinterRaven 01](https://user-images.githubusercontent.com/77753615/105610980-0dfac700-5db3-11eb-9f2c-3ba82dae838f.PNG)

**Comment by OzzieIsaacs** [comment]
If I get it right you are having problems with calibre (Calibre is not Calibre-Web) then you are here wrong. Please ask for help at the calibre repo. From the errormessages I can tell you the permssions arn't right, Calibre can't write to the database or the folders


1.) is it good practice to shut Calibre-web down BEFORE i make an entry in Calibre on PC? Or is it better to keep it running?
If you leave Calibre-Web running and the start Calibre this is normally fine. Except for the Docker users many of them complain about changes not visible in the Calibre-Web UI (There is a button to reconnect to the database in the admin section to work around this problem)

2.) is there a manual or best practice on how to use Calibre / Calibre-Web server for importing books?
You could have a look at the wiki, but if your file permissions are right everything will work, without manual
