### ISSUE TITLE
some hacker attack me, registerd many illegal username.

### ISSUE THREAD

**Issue by vagra** [janeczku/calibre-web#1831]
`user` table in app.db:

![图片](https://user-images.githubusercontent.com/1576687/105875224-81f9d100-6038-11eb-9bc9-065eb221a0a1.png)

Need to improve the security of registration and login.

**Comment by OzzieIsaacs** [comment]
That's correct: You should improve the security of your installation. 

You could limit the allowed registration domains to domains you know, like: friends.\*@baidu.cn, or block all users named abc*. Or deactivate the registration if anybody can access the website and you are not sure who is registering
![grafik](https://user-images.githubusercontent.com/6438895/105882334-d20b7000-6005-11eb-8779-8e9e35c59994.png).

I'm not sure what I'm seeing there, but it looks not like valid email addresses. To get logged in you need to receive the email send out by calibre-web and enter the password given there. In my instance I can't register a user without using an email address, so `/etc/./passwd `isn't working.

I currently see nothing I can do with the information I have (e.g. which version are you using, what am I seeing there, which settings do apply, what is the content of the logbook -> means please fill out the form you deleted, before pasting your text in)

**Comment by vagra** [comment]
This happened in the previous v0.6.9 version. I don’t know what methods hackers used to register these illegal accounts. I haven’t looked after the website for a while, so I didn’t leave the log at that time. I upgraded to the latest v0.6.10 last night. if this problem occurs again, I will report it to you.
