### ISSUE TITLE
User will be logged out after clicking on a link in Calibre-web 

### ISSUE THREAD

**Issue by jebr** [janeczku/calibre-web#1834]
**Describe the bug/problem**
After logging into calibre-web the profile page will be displayed. When a link is then clicked (for example recently added), the user is logged out and must be logged in again. 

**To Reproduce**
1. Go to calibre-web
2. Click on Guest
3. Login with credentials
3. Click on Recently addad (or any other link)
4. User is logged out 

**Logfile**
Nothing is added to the log file.

**Expected behavior**
Navigation to all elements 

**Environment (please complete the following information):**
 - OS: Linux Ubuntu Server 20.04
 - Python version: 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
 - Calibre-Web version: V0.6.10 - Florence:
 - Docker container: linuxserver/calibre-web:latest:
 - Special Hardware: None (Server)
 - Browser: Firefox Versie 84.0.2, Chomre Versie 88.0.4324.104

**Additional context**
The setup is Nginx reverse proxy with calibre-web behind it. Everything related to calibre-web is default.

**Comment by OzzieIsaacs** [comment]
I guess you are having trouble with the reverse proxy setup forwarding the "login cookie" to your browser, please try to access it without proxy (if possible)

**Comment by jebr** [comment]
Indeed, the problem was caused by the reverse proxy. Without the proxy, everything works fine. I have set up the reverse proxy again, after this everything works fine. Unfortunately I have not been able to find what is causing this problem. Thanks for the quick response.

**Comment by jebr** [comment]
Unfortunately the problem has not been solved yet. After a few clicks back and forth, I am logged out again. Do you happen to have some additional info for setting the login cookie with Nginx proxy?

**Comment by jebr** [comment]
I had contact with the maker of [npm ](https://nginxproxymanager.com/ )to check if this problem has something to do with [npm](https://nginxproxymanager.com/). After logging in, the following message is displayed in the browser console:

Cookie “remember_token” has been rejected because it is already expired.

Through some testing I found out that when I set the proxy status from Cloudflare to DNS only the problem is solved. I have no idea if calibre web can change that or if I can leave it like that in Cloudflare. Do you have an idea? 

![cloudflare_settings](https://user-images.githubusercontent.com/7726815/106604422-eb5d7080-655f-11eb-9080-acef0ce4e3a7.png)
![console_output](https://user-images.githubusercontent.com/7726815/106604498-03cd8b00-6560-11eb-91bb-2e1e84d78fe9.png)

**Comment by OzzieIsaacs** [comment]
I program calibre-web and I'm using it with a Apache reverse proxy without any problems, I also created configs for some other proxies, which I could use without any issue. 
I don't know what all tools outside the control of Calibre-Web are doing. The only thing I know is: If the browser presents the cookies which Calibre-Web handed out to the "outside tool" it will accept it

**Comment by OzzieIsaacs** [comment]
I'm sorry I can't help you any further an I'm happy you found a workaround for your problem
