### ISSUE TITLE
Book's covers editing options missing

### ISSUE THREAD

**Issue by Kuroburn** [janeczku/calibre-web#1836]
**Describe the bug/problem**
I just updated the application to its latest version and when editing the book's metadata there is no option to change the cover. Is it no longer available or something? 

**Screenshots**

[Screenshot](https://imgur.com/a/GX8KImx)

**Environment (please complete the following information):**
 - OS: CentOS 8
 - Python version: Pyhton 3
 - Calibre-Web version: 0.6.10
 - Browser: Mozilla Firefox 85.0

**Comment by OzzieIsaacs** [comment]
I tied this menu to the upload function, as uploading covers from hdd or url is nothing else than uploading books

**Comment by Kuroburn** [comment]
I have about 1600 books added through the calibre's cli, of which about 1400 do not have the cover correctly placed. When I added the books, the cover could be edited after that process, now I see that this option is part of the upload process from the application interface. I think I'll have to erase everything and upload the books again then hahahaha,

I assume that nothing can be done in this case right?

**Comment by OzzieIsaacs** [comment]
I‘m not sure if I got it right.
If you want to replace the covers, please enable the upload function in calibre-Web, afterwards the cover buttons are visible and you can continue as before

**Comment by Kuroburn** [comment]
> I‘m not sure if I got it right.
> If you want to replace the covers, please enable the upload function in calibre-Web, afterwards the cover buttons are visible and you can continue as before

Oh I see, that's how it was.
Thanks, this fixed my "problem".
