### ISSUE TITLE
Log authentication failures for OPDS as well

### ISSUE THREAD

**Issue by rg9400** [janeczku/calibre-web#1838]
**Is your feature request related to a problem? Please describe.**
Right now, CW logs authentication failures when trying to access the main interface. However, no failures are logged when trying to access the OPDS endpoint. This makes it hard to run Fail2Ban on that endpoint.

**Describe the solution you'd like**
Log failures on OPDS just like it is logged for the main login interface

**Describe alternatives you've considered**
Do not run F2B on OPDS, which is less secure

**Comment by OzzieIsaacs** [comment]
I'll include it this weekend

**Comment by OzzieIsaacs** [comment]
It's included in newest master commit. 
Successful logins aren't logged, as every request with valid Basic Authentication will log you in, and therefore would create a log entry, spamming the log file.
