### ISSUE TITLE
Quick access to "Read in browser" and "Delete Book".

### ISSUE THREAD

**Issue by patricorgi** [janeczku/calibre-web#1840]
**Is your feature request related to a problem? Please describe.**
All my books have the same format. It's a bit frustrating each time I have to press "Read in browser" and then choose the only format. It also requires two steps to delete a book: you have to go into the Edit metadata page then press "Delete Book".

**Describe the solution you'd like**
Quickly open a book: I'm wondering if it's possible to open the book directly with "Read in browser" when there's only one format. 
Quickly delete a book: could you put the "Delete Book" button on the book details floating sheet instead of inside metadata editing page?

**Comment by OzzieIsaacs** [comment]
Read in browser button -> Done
Delete Book -> This was discussion long time ago, I denied changing it and I'm still convinced that having the delete button in the edit section is the right place for it

**Comment by patricorgi** [comment]
Hi, thanks a lot for adding this feature! We can keep the Delete Book button in the edit section by default but it will be nice to have an option to place it on the book details...
