### ISSUE TITLE
Question: File locking between calibre and calibre-web

### ISSUE THREAD

**Issue by UKLibrarian** [janeczku/calibre-web#1841]
(Can I just start by saying a huge "thank you" for the recent changes. The ability to re-order shelves in various ways, especially by author, has made my life SO much simpler for my use case and has lead me to think how I am going to move my project forward, hence my question below.)

If I understand the documentation correctly, calibre-web doesn't need calibre itself to run - it just needs the calibre directory structure and the metadata.db file. Because I hadn't researched this properly when I first built my existing project, I have both calibre and calibre-web on my server, and so have to go through the hoops of maintaining a GUI on my server (eek!) so that I can run calibre remotely.

If I'm right about only needing the calibre files, could I run the calibre program itself on my local PC but with just the files stored on my VPS and shared with the PC using something like NFS or SSHFS? My concern about doing that would be that while I had the files open in calibre presumably they would be locked in some manner which could well cause problems in calibre-web?

My server is very low traffic and with small numbers of fairly infrequent updates, so this may not be a huge issue, but I just wondered what the end-user experience would be if someone tried to access calibre-web while I was updating books in calibre.

Regards, Andy.

**Comment by OzzieIsaacs** [comment]
> it just needs the calibre directory structure and the metadata.db file.

Yes, only converting ebooks relies on calibre itself, but this is optional. So no real need to install calibre on your server.

> My concern about doing that would be that while I had the files open in calibre presumably they would be locked in some manner which could well cause problems in calibre-web?

Yeah, there are quit a few rumours out there regarding problems, which I personally never could reproduce (using cifs myself). If you start Calibre first and afterwards Calibre-Web, Calibre indeed locks the database and doesn't allow Calibre-Web to access the database (metadata.db) file. Starting Calibre-Web and afterwards Calibre should work.

> I just wondered what the end-user experience would be if someone tried to access calibre-web while I was updating books in calibre.

After a page reload, Calibre-Web shows the updated information (my experience, but especially docker users having trouble with this). 
If you view the book covers in Calibre-web, delete one of the books visible in Calibre in parallel and the user clicks on the cover of the deleted book in Calibre-Web he will, of course, get an error. If you edit something in Calibre like categories and Calibre-Web changes the same entry right after it the new value of Calibre-Web will show up.

I can't guarantee that there will be no unhandled errors, but issues reported regard this are normally so vague and unspecific that they are impossible to reproduce and to fix.

**Comment by UKLibrarian** [comment]
Thank you.
I'm not using Docker (another thing for me to learn one of these days in my copious spare time) but it sounds like this is definitely worth a try. I must admit I've never even heard of cifs - did you have a specific reason for choosing it over other network filestore solutions ? I'm not wedded to any specific approach (as long as it's not Samba).

**Comment by OzzieIsaacs** [comment]
cifs = smb = samba = windows network

**Comment by UKLibrarian** [comment]
Oh, ok. I have had issues with securing SMB before, and found myself getting told off by my hosting provider for allowing NETBIOS reflection attacks via my server. Maybe I need to go around that loop again. Thanks a lot. A.

**Comment by OzzieIsaacs** [comment]
If NFS is working for you leave it. I don‘t think samba will make it better, just different with a lot of work

**Comment by dsm1212** [comment]
I'm using calibre, calibre-web and lazylibrarian. Frequently I find lazylibrarian cannot write to the database and it fails to postprocess. When this happens if I go to calibre-web and "reconnect to database" it corrects the problem. Totally repeatable, this always corrects it. I find the system this way very frequently. All local files, no cifs or nfs. Any suggestion why this happens?
