### ISSUE TITLE
Trying to import LDAP users results on a forever-looping spin

### ISSUE THREAD

**Issue by flixman** [janeczku/calibre-web#1843]
**Describe the bug/problem**
I have set up LDAP authentication on my calibre web, rooted on a subfolder of the document root. If I run the commands
ldapsearch -H ldap://<server> -D <binding username> -w <password> -b <base search> '(&(objectclass=groupofnames)(cn=ebooks))' member
from a terminal, I get a list of the users. However, if I go to admin page and click on 'Import LDAP users' I get a forever looping spin. I have debugged it with Firefox, and the problem seems to be that when clicking on that button the following request is made:

    https://my.server.org/import_ldap_users

instead of

    https://my.server.org/subfolder/import_ldap_users

When running it with the firefox debugger, I get to see that in main.js, line 305, there is this statement:

    var pathname = document.getElementsByTagName("script"), src = pathname[pathname.length - 1].src;

I understand this is the workaround to make the pathname subfolder agnostic. In my case, for some reason, src is an empty string, whereas baseURI contains https://my.server.org/subfolder/admin/view.  Because the URL https://my.server.org/subfolder/import_ldap_users does not exist (error 404), this results in a forever spinning wheel.

**However** if I modify that line to look like (note the **2** in the access to pathname)

     var pathname = document.getElementsByTagName("script"), src = pathname[pathname.length - 2].src;

The call succeeds.

**To Reproduce**
1. Go to Admin
2. Click on Import LDAP users

**Expected behavior**
The LDAP directory is queried and users get imported

**Environment (please complete the following information):**
 - OS: Debian 10
 - Python version: python 3.7.3
 - Calibre-Web version: 0.6.9
 - Docker container: None
 - Special Hardware: No
 - Browser: Firefox 85.0b9

**Comment by OzzieIsaacs** [comment]
There are 3 different routine to detect the right pathname, and thisone seems not to work perfectly. It relies on the order the scripts are loaded, this seems to be different depending on OS, browser, ??. I exchanged it with another one, I do some tests and it should be fixed tomorrow (if the fix works)
