### ISSUE TITLE
Using other LDAP attributes than uid for user creation does not work as expected.

### ISSUE THREAD

**Issue by flixman** [janeczku/calibre-web#1844]
**Describe the bug/problem**
I have the following user filter in my LDAP search:

    (&(objectclass=inetOrgPerson)(mail=%s))

When importing users this filter does not work, because the response from openldap has the following form:

    uid=user1,ou=Users,dc=mydomain,dc=org
    uid=user2,ou=Users,dc=mydomain,dc=org

In the line 331 of web.py, the "mail" attribute is obtained from the filter, but as the "mail" attribute is not present on the answer this results in the following search (line 334) failing and not grabbing the user.

**To Reproduce**
1. Go to LDAP properties
2. Set (&(objectclass=inetOrgPerson)(mail=%s)) as user object filter
3. Save the changes
4. In the main admin pannel, click on "Import LDAP users".

**Expected behavior**
The users belonging to the provided group are created based on the attribute given in the user object filter.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Debian 10
 - Python version: python 3.7.3
 - Calibre-Web version: 0.6.9
 - Docker container: None
 - Special Hardware: No
 - Browser: Firefox 85.0b9

**Comment by OzzieIsaacs** [comment]
Please update to 0.6.10. 
Depending on your configuration (I can't guess it from your description)  please change LDAP Member User Filter Detection to custom filter, or maybe autodetect will work(?) 
![grafik](https://user-images.githubusercontent.com/6438895/106393394-2001e880-63f7-11eb-9c40-bf2b8893e149.png)
and set LDAP Member User Filter to (I don't know maybe mail or uid???)=%s

**Comment by flixman** [comment]
Hi,
I just updated it, to 0.6.11, and the import still does not work. The problem is that, in cps/admin.py (line 1313), the group is queried and a number of users are returned with this format:

    uid=user1,ou=Users,dc=mydomain,dc=org
    uid=user2,ou=Users,dc=mydomain,dc=org

in line 1324-1389, there is a loop on each one of those lines to detect the user_identifier. Specifically, in lines 1326-1336 the case that the string returned by the ldap contains a = is handled, and in that case checks the string for the identifier. In that case, if other attribute than uid is used (e.g., mail) that will produce an Exception and the remaining of that iteration will be skipped. I do not have enough experience with ldap (otherwise I would fork and try to patch it), but... once the list of users has been returned, maybe an additional loop to check each one's attributes is required? I have observed this happens a few lines later in the code, but by then the "Continue" of that exception has already been hit.

**Comment by OzzieIsaacs** [comment]
You gave me 50% of your LDAP configuration and 50% of your Calibre-Web settings. 
I need a complete (100% of both) example to help you, a device tree like the following would be helpful and a FULL set of settings ( I'll hope the names are understandable, if not please ask, and don't just leave it open):

```
dn: cn=John1 Doe1,ou=people,dc=calibreweb,dc=com
objectClass: person
objectClass: organizationalPerson
objectClass: inetOrgPerson
mail: user12@gamma.org
mail: user12@beta.com
sAMAccountName: user12
cn: John1 Doe1
gn: John1
sn: Doe1
userPassword: terces

#Generic groups
dn: ou=groups,dc=calibreweb,dc=com
objectclass:organizationalunit
ou: groups

# create the cps entry
dn: cn=cps,ou=groups,dc=calibreweb,dc=com
objectclass: groupofnames
cn: cps
member: cn=John1 Doe1,ou=People,dc=calibreb,dc=com
```

'config_ldap_provider_url': '127.0.0.1',
'config_ldap_port': '3268',
'config_ldap_authentication': 'Simple',
'config_ldap_dn': 'dc=calibreweb,dc=com',
'config_ldap_serv_username': 'cn=root,dc=calibreweb,dc=com',
'config_ldap_serv_password': 'secret',
'config_ldap_user_object': '(sAMAccountName=%s)',
'config_ldap_group_object_filter': '(& (objectclass=groupofnames)(cn=%s))',
'config_ldap_openldap': 1,
'config_ldap_encryption': 'None',
'config_ldap_group_members_field': 'member',
'config_ldap_group_name': 'cps'
'ldap_import_user_filter': 'Custom Filter'
'config_ldap_member_user_object': 'cn=%s'

This configuration results (if LDAP server runs as openldap server on localhost and the correct port with the right admin and passwort) in one imported user with the name user12

**Comment by flixman** [comment]
I have just understood what you meant with the config_ldap_member_user_object. Setting it to uid=%s, while keeping config_ldap_user_object to mail=%s. Did the trick! Thank you!!!
