### ISSUE TITLE
OPDS search not available using readers like Librera/MoonReader

### ISSUE THREAD

**Issue by rg9400** [janeczku/calibre-web#1845]
**Describe the bug/problem**
I am trying to get Calibre-Web's OPDS feed added into an ebook reader on Android. I tried some of the very popular options like Librera and MoonReader. MoonReader doesn't seem to pick up covers, series, tags, etc. when navigating through the OPDS feed at all, so I prefer Librera, but seems like neither allow you to search the OPDS feed. When adding a direct OPDS from calibre, search becomes available in both apps.

**To Reproduce**
1. Install MoonReader+/Librera
2. Add the calibre-web OPDS feed as a network catalog
3. Notice how search is not available
4. Add a calibre OPDS feed as a network catalog
5. Notice how search is now available

**Expected behavior**
Ideally, search should work on the OPDS feed.

**Environment (please complete the following information):**
 - OS: Docker
 - Python version: 3.8.5 
 - Calibre-Web version: 0.6.11 Beta - a866dbaa809beff6c378798d97895ac61ed89db2 
 - Docker container: LinuxServer
 - Special Hardware: Windows 10 running Docker via WSL2 Backend
 - Browser: Librera PRO 8.3.100

**Comment by rg9400** [comment]
I got a response from the Librera dev. Attaching it here, could you see if these can be added?

```
Librera search tag {searchTerms} inside the xml response (https://specs.opds.io/opds-1.2.html)
But the Gutenberg response does not have it. for example (http://flibusta.is/opds)

<link href="/opds-opensearch.xml" rel="search" type="application/opensearchdescription+xml" />
 <link href="/opds/search?searchTerm={searchTerms}" rel="search" type="application/atom+xml" />
 <link href="/opds" rel="start" type="application/atom+xml;profile=opds-catalog" />
 <link href="/opds" rel="self" type="application/atom+xml;profile=opds-catalog" />
```

**Comment by OzzieIsaacs** [comment]
Please try the newest commit version, there was indeed something missing. For me it was now working in an android simulator.

> MoonReader doesn't seem to pick up covers ...

Covers are indeed a problem of MoonReader, as it forgets to send the credentials together with the cover request. The only way to avoid this is to enable anonymous browsing

**Comment by rg9400** [comment]
Yes, this seems to have fixed it. Really appreciate it!

**Comment by silviuvulcan** [comment]
I know it's closed (and you're probably tired of all those readers missbehaving :) ) but if somebody finds this as I did, currently:

Fbreader for Android search doesn't work unless anonymous browsing is enabled
Moon+ for Android search icon only appears (and works) if anonymous browsing is enabled.

**Comment by Metrasher** [comment]
I don't know if this should belong here, but it's clearly related, so I'll take the risk.
I'm connected to my calibre-web OPDS feed from koreader. Everytime I try searching anything, server answers that catalog cannot be accessed, with the status from server: wantread.
I tried the above from filviu user, enabling  anonymous browsing, but nothing changed.
Is there something I am missing or is it really a bug there?

**Comment by filviu** [comment]
I no longer use fbreader and moon+ since I discovered koreader. I run it on my kindle 4nt, android phone & tablet and boox android ereader. On all of them it works just fine including search, downloading, etc. with `Anonymous Browsing` disabled.

Don't forget to add `/opds` to your url i.e. https://calibre-web.example.com/opds.

**Comment by Metrasher** [comment]
That didn't solve the issue, but it pointed me in the right direction. 
The thing is that Calibre web took too much time to resolve the search for differen circumstances and the client capped the wait to a certain amount of time (issue discussed on https://www.mobileread.com/forums/showthread.php?t=364890).
So after modifying the values in the client the search is working as intended. 

The confusing bit was the status message on the error: when accesing from a reverse proxy URL like 'https://calibre-web.example.com/opds' it throws the status "wantread", and when accessing from LAN, i.e. 'http://192.168.1.xxx:9999/opds' the status thrown is "timeout", which makes more sense and drove me to the solution.
