### ISSUE TITLE
DB location is not Valid, Please enter Correct Path

### ISSUE THREAD

**Issue by prash85** [janeczku/calibre-web#1848]
**Describe the bug/problem**
I'm hosting calibre-web server on my openmediavault5 NAS. I created /config and /books folder path using omv5 UI and assigned them proper permissions. The container is initialised and I can access the Basic Configuration page however under Library configuration when I enter "/books" (as per calibre-web wiki), I get an error "DB location is not Valid, Please enter Correct Path" and stays on basic configuration page.

**To Reproduce**
1. Run Docker Stack
2. When container is up and running, go to web page and wait for 2 minute for the service to finish configuration
3. On basic configuration page, enter /books path
4. You will see error on top banner 

**Logfile**
[_calibre-web_calibre-web.1.y48rc2hhc7ikmnrto6vqm4e5r_logs.txt](https://github.com/janeczku/calibre-web/files/5909001/_calibre-web_calibre-web.1.y48rc2hhc7ikmnrto6vqm4e5r_logs.txt)

**Expected behavior**
It should've redirected to calibre-web main page

**Screenshots**
Attached

![calibreweberror](https://user-images.githubusercontent.com/28559257/106558324-a9d8bf80-6577-11eb-94d2-4a1be26fb558.PNG)

**Environment (please complete the following information):**
 - OS: Debian 10 running openmediavault5
 - Python version: 3
 - Calibre-Web version: latest
 - Docker container: ghcr.io/linuxserver/calibre-web
 - Special Hardware: ATX Computer
 - Browser: Chrome 88.0.4324

** Docker Stack**
version: "3"
services:
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=xxx
      - PGID=xxx
      - TZ=Australia/Sydney
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - /srv/dev-disk-by-label-disk1/calibreweb:/config
      - /srv/dev-disk-by-label-disk2/ebooks:/books
    ports:
      - 8083:8083
    restart: unless-stopped

**Comment by PipeItToDevNull** [comment]
Calibre-web needs an existing calibre library, it cannot create one. One of the other issues (this is a duplicate) has a blank db uploaded by a user. (I used that)
