### ISSUE TITLE
How do I use Tags or "custom column values" to allow or deny content correctly?

### ISSUE THREAD

**Issue by Fribb** [janeczku/calibre-web#1849]
I can't really wrap my head around the whole "allow/deny" for tags or custom values and I also can't find any documentation that would answer this question. I did found and could get a Tag to allow or deny access to content but even that isn't working as expected.

For example, I have two comics in my Calibre library and they are also displayed in my Calibre-Web instance. I create a Tag because one of them is "Mature Content" and I assign that Tag to one of the Comics.

The Tag is now updated in Calibre-Web and Comics can be filtered through this. When I now edit a user and "Select Allowed/Denied Tags of User" for the Tag "Mature Content" and select deny then that Comic with the Tag will be hidden from that user while the other comic is still there. But when I now change it to allow that tag the display is switched. I get only the Comic with the "Mature Content" Tag while the other, who doesn't have this Tag (in fact doesn't have ANY tag at all), is now hidden.

While writing this it seems that those lists are strict positive lists, a user has **only** the "Mature content" Tag allowed so they can **only** view everything that is also tagged "Mature Content" but nothing else.

Is that intended because I would have thought that setting allow or deny by a tag would increase or decrease what the user can see instead of one or the other?

The next thing I could find nothing about how to use it is the "Add allowed/denied custom column values". What custom column and what values?

I think what I am looking for is that I could create a custom column in calibre and use the content of that column to allow or deny the view restriction for those comics. Which might be the "Add allowed/denied custom column values" but there is nothing I can find on how to use it. Is there any documentation for this?

**Comment by hikanwoi** [comment]
> The next thing I could find nothing about how to use it is the "Add allowed/denied custom column values". What custom column and what values?
>I think what I am looking for is that I could create a custom column in calibre and use the content of that column to allow or deny the view restriction for those comics. Which might be the "Add allowed/denied custom column values" but there is nothing I can find on how to use it. Is there any documentation for this?

I think what you're looking for is "View Restrictions based on Calibre column" under "UI configuration" --> "View Configuration".
The value of "View Restrictions based on Calibre column" determines which column is used for "Add allowed/denied custom column values".

**Comment by Fribb** [comment]
> I think what you're looking for is "View Restrictions based on Calibre column" under "UI configuration" --> "View Configuration".
> The value of "View Restrictions based on Calibre column" determines which column is used for "Add allowed/denied custom column values".

That is correct, after trying it out it behaves pretty much as how you would set it up with a "Tag" just that you have your own Column for that. I think my problem was that I wanted it to be a "boolean" value (so yes or no) which you apparently can't use in that context, which also makes sense in that regard.

**Comment by OzzieIsaacs** [comment]
Problem solved?

**Comment by abdessalaam** [comment]
A bit late to the party: 
My "View Restrictions based on Calibre column" has only one option available: 'none'. How to modify this?
I have created a custom column: Public:yes|no and I would like to use it so that not logged guests can only see books marked as public:yes in that column

**Comment by AsherMaximum** [comment]
> A bit late to the party: My "View Restrictions based on Calibre column" has only one option available: 'none'. How to modify this? I have created a custom column: Public:yes|no and I would like to use it so that not logged guests can only see books marked as public:yes in that column

Not sure why, but custom column selection is limited to only text columns. The column you have is an "enumeration".

I wanted to do the same thing, so I edited the admin.py page to allow both "text" and "enumeration" datatypes:
````
@admi.route("/admin/viewconfig")
@user_login_required
@admin_required
def view_configuration():
    read_column = calibre_db.session.query(db.CustomColumns) \
        .filter(and_(db.CustomColumns.datatype == 'bool', db.CustomColumns.mark_for_delete == 0)).all()
    restrict_columns = calibre_db.session.query(db.CustomColumns) \
        .filter(and_(or_(db.CustomColumns.datatype == 'text', db.CustomColumns.datatype == 'enumeration'), db.CustomColumns.mark_for_delete == 0)).all()
```
```
def check_valid_restricted_column(column):
    if column != "0":
        if not calibre_db.session.query(db.CustomColumns).filter(db.CustomColumns.id == column) \
          .filter(and_(or_(db.CustomColumns.datatype == 'text', db.CustomColumns.datatype == 'enumeration'), db.CustomColumns.mark_for_delete == 0)).all():
            return False
    return True
```

If there was a reason that enumeration columns weren't already part of the allowed restricted columns, this may cause me issues, but we'll see. Initial tests show it working.

**Comment by DianaNites** [comment]
Did that change ever cause issues?

**Comment by AsherMaximum** [comment]
> Did that change ever cause issues?

Nope, it's still working fine
