### ISSUE TITLE
Google Drive Integration error

### ISSUE THREAD

**Issue by bluebird11** [janeczku/calibre-web#185]
Hi, sorry to bother you again, but I can't get the Google Drive integration running. Here is the error log:

`
[2017-04-23 09:59:58,211] {/usr/local/lib/python2.7/dist-packages/flask/app.py:1560} ERROR - Exception on /gdrive/authenticate [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/home/pi/calibre-web/cps/web.py", line 422, in inner
    return f(*args, **kwargs)
  File "/home/pi/calibre-web/cps/web.py", line 1336, in authenticate_google_drive
    authUrl = Gauth.Instance().auth.GetAuthUrl()
  File "/usr/local/lib/python2.7/dist-packages/pydrive/auth.py", line 485, in GetAuthUrl
    self.GetFlow()
  File "/usr/local/lib/python2.7/dist-packages/pydrive/auth.py", line 443, in GetFlow
    self.LoadClientConfig()
  File "/usr/local/lib/python2.7/dist-packages/pydrive/auth.py", line 366, in LoadClientConfig
    self.LoadClientConfigFile()
  File "/usr/local/lib/python2.7/dist-packages/pydrive/auth.py", line 388, in LoadClientConfigFile
    raise InvalidConfigError('Invalid client secrets file %s' % error)
InvalidConfigError: Invalid client secrets file ('Error opening file', 'client_secrets.json', 'No such file or directory', 2)
`

Thanks a lot in advance for your help!

**Comment by OzzieIsaacs** [comment]
@Kennyl could you please give some advice in this case, I'm not very familiar with the google drive API

**Comment by Kennyl** [comment]
I don't use Google Drive, I think it is the cause of __where is working directory__

Maybe fix it by adding  ```
WorkingDirectory=[/PATH/TO/]
ExecStart=[path to python] cps.py
```
https://github.com/janeczku/calibre-web/blob/master/readme.md#start-calibre-web-as-service-under-linux

Or
Fix the ambiguous path location.
https://github.com/janeczku/calibre-web/blob/master/cps/web.py#L1344

**Comment by bluebird11** [comment]
Thanks for the reply! I tried adding the WorkingDirectory (and reloaded and restarted the service afterwards), but it doesn't help. I still get the same error. Any other ideas?

**Comment by Kennyl** [comment]
Run without service once again ( on console,  python cps.py), does it repeat the same error?

**Comment by bluebird11** [comment]
Ok, running without service didn't really change anything.

What I did: I manually copied the file client_secrets.json (which I downloaded from Google Console) to the main directory of calibre-web. Looks like Calibre web then finds it and I was successfully redirected to the Google confirmation page. But then nothing happens. I get redirected back to the admin page and "use google drive" is unchecked again. And there are no further errors in the log.

Any further ideas?

**Comment by Kennyl** [comment]
I don't use google drive, but I have some suggestion
- place json file to calibre-web/cps/client_secerts.json
- check file permission 
- at last if you are SELinux Enabled, try to disable temporary and start the cps again.

**Comment by bluebird11** [comment]
Ok, thanks so much for your help, I'm slowly making progress.

I figured out that I have to click "Submit" at the very bottom of the admin page for the changes to get saved... This could have been the problem the entire time so far. I tried deleting the json file, calibre-web doesn't seem to recreate it, but it still seems to be google-authenticated...

The "authenticate with google" button is now called "enable watched of metadata.db".

So, I guess, it should be working now. But how do I use it?? I expected it to make a copy of my books library on my google drive?

**Comment by Kennyl** [comment]
Just copy to googledrive.
or use some tools mount your googledrive and use calibre move the library .

**Comment by bluebird11** [comment]
Hmm, ok, I uploaded my entire library to my Google Drive to a folder "docs/calibrelib". Then I entered this path in the field "Google drive Calibre folder" in Admin.

However, I don't see any changes in calibre web even if I add a new book to the database in Google Drive.

How do I know if I'm still doing something wrong. I can't find any relevant info in the log.

**Comment by OzzieIsaacs** [comment]
@JackED42 could you please give some hints regarding the problem. Thanks.
@Kennyl sorry for pulling you into this issue, I got confused about the contributions you made. And thanks for your help, it got us far ahead.

**Comment by JackED42** [comment]
Hi. 

Could you screen shot the settings page? Make sure you black out any sensitive info though. I will take a look

Cheers

**Comment by bluebird11** [comment]
Here's a screenshot. Thanks!

![calibreweb](https://cloud.githubusercontent.com/assets/1311350/25556619/f671350c-2cff-11e7-9152-35208b94910c.jpg)

**Comment by JackED42** [comment]
Hmm. I wonder if there is a bug with the Google drive folder. 2 things to
try. 1. Remove leading forward slash. 2. Make the Google drive folder a
single level.

When I get chance I will double check the code and see if this could cause
an issue

Cheers

Jack

**Comment by bluebird11** [comment]
Ok, I changed the Google Drive folder to only "patupilib". I noticed that I after enabling "google drive" I got no covers in Calibre Web anymore and following errors in the log (they kind of appeared after a while...):

`
[2017-04-29 18:27:04,883] {/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py:1143} INFO - (3, 1, 0)
[2017-04-29 18:27:04,885] {/usr/local/lib/python2.7/dist-packages/flask/app.py:1560} ERROR - Exception on /cover/Osho/One Seed Makes The Whole Earth Gree (126) [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/home/pi/calibre-web/cps/web.py", line 1574, in get_cover
    return redirect(get_cover_via_gdrive(cover_path))
  File "/home/pi/calibre-web/cps/web.py", line 1555, in get_cover_via_gdrive
    df = gdriveutils.getFileFromEbooksFolder(Gdrive.Instance().drive, cover_path, 'cover.jpg')
  File "/home/pi/calibre-web/cps/gdriveutils.py", line 174, in getFileFromEbooksFolder
    drive.auth.Refresh()
  File "/usr/local/lib/python2.7/dist-packages/pydrive/auth.py", line 470, in Refresh
    raise RefreshError('No refresh_token found.'
RefreshError: No refresh_token found.Please set access_type of OAuth to offline.
`

So it looks like it can't really connect to drive. Where is it supposed to get the refresh_token from?

**Comment by JackED42** [comment]
A yaml file should be generated from your details.  Maybe double check this file in your root from the gdrive template. I can't be of much help currently, as I am away from my laptop. I will investigate this properly when I get chance

**Comment by bluebird11** [comment]
Ok, it seems to be kind of working now, but I guess not the way it's supposed to.

There was a 0 KB "settings.yaml" file in the root folder of calibre web. As it was 0 KB I simple deleted it, hoping it will be recreated when I click on "Authenticate Google Drive". However, it didn't work :( It started complaining in the log about not being able to find  client_secrets.json. So I copied it to the "cps" directory. Then the button "Authenticate Google Drive" simply stopped working, but the book covers take forever to load, so I assume that they are loaded from gdrive.

However, a book in my calibre web library, which was deleted from my gdrive library still showed up, but without a cover. Another book, which exists in my gdrive library doesn't show up in calibre web.

Is calibre web supposed to keep both libraries in sync?

**Comment by JackED42** [comment]
Interesting.

Is the local folder synced with gdrive?

The local folder should be empty. And is just used as a temporary folder to upload books / update etc. I am wondering whether the folder has existing books.and is trying to sync them with your Google drive.

The images will take some time to load. I use cloudflare to cache them for me.

**Comment by bluebird11** [comment]
Ok, I think I'm understanding now. If I start Calibre Web with an empty folder and Google Drive integration it's crashing, because it's missing its metadata.db. If I manually copy metadata.db it loads the books and covers from Google Drive. This seems to work nicely.

However, metadata.db is not synced in either way. If I understand correctly, this can be done using "Enable watch of metadata.db", which however works only if my server supports HTTPS. Am I right?

**Comment by JackED42** [comment]
Metadata.db should sync up to gdrive. Just not the other way, if you don't watch metadata.db then it won't sync from gdrive.


You are correct about HTTPS, annoying Google drive API requirement. Again, cloudflare can be used for free https

**Comment by JackED42** [comment]
I think because there were issues on the initial setup of gdrive. Something got messed up and it didn't download metadata.db. 

May need to add some stricter checks

**Comment by varunpatro** [comment]
Hi @JackED42, are there better docs on how to get Gdrive Integration working?

I followed the useful discussion that took place here, and it was quite helpful. 

However, I still ran into some problems. Namely, I still have the

`RefreshError: No refresh_token found.Please set access_type of OAuth to offline.`

I get these errors when I click `Enable watch of metadata.db` or when I try to download an epub from the collection. I believe this is when it tries to use the gdrive api but fails.

Cheers,
Varun

![screen shot 2018-03-21 at 11 19 28 pm](https://user-images.githubusercontent.com/6943308/37718993-f40a70de-2d5e-11e8-9322-3904756099e8.png)

**Comment by ZhangYanTJU** [comment]
Hi,
I got the same error:
`('Error opening file', 'client_secrets.json', 'No such file or directory', 2)`
Anyone can help me?
My client_secrets.json is placed in both the dictionary calibre-web and calibre-web/cps, but it still didn't work.
