### ISSUE TITLE
HTTP 308 Redirection on accessing author id 1 or series id 1 cause problem

### ISSUE THREAD

**Issue by StudioEtrange** [janeczku/calibre-web#1854]
**Describe the bug/problem**
When accessing first created author book list there is a weird 308 redirection involved which is not the case for other authors id
```
https://mydomain/author/new/1 => HTTP Response 308, redirect to HTTP://mydomain/author/new
https://mydomain/author/new/ =>  HTTP Response 307, redirect to HTTPS://mydomain/author/new/ (by reverse proxy)
https://mydomain/author/new/ => HTTP Response 200 print author book list
```
While any other ID directly print book list
```
https://mydomain/author/new/3 => HTTP Response 200 print author book list
```

The problem is 
* that there is a redirection in first place only for ids "1" for author or series book list. 
* that the redirection using 308 and remove id in URL and change scheme (HTTP instead of HTTPS)

This behavior is weird, occurs on author books list but on series books list also
and make it hard to integrate into other system, and manipulate through reverse proxy like traefik
and have other side effect not already known

**To Reproduce**
1. Go to Series or Author Menu
2. Click on Series or Author Menu
3. Look at network console and see that

**Logfile**

**Expected behavior**
When printing author book list, or series book list, do not get involve in HTTP redirection

**Screenshots**

Normal behavior (id 5)
![series_5](https://user-images.githubusercontent.com/4258690/107216946-c3618780-6a0d-11eb-8397-19911819f735.JPG)

Strange behavior (id 1)
![series_1a](https://user-images.githubusercontent.com/4258690/107216981-d1170d00-6a0d-11eb-970b-9ddeb0034fe0.JPG)
![series_1b](https://user-images.githubusercontent.com/4258690/107217000-d8d6b180-6a0d-11eb-90f5-70be5cd6519e.JPG)
![series_1c](https://user-images.githubusercontent.com/4258690/107217010-db390b80-6a0d-11eb-867b-47dd84146693.JPG)

**Environment (please complete the following information):**
 - OS: linux docker linux
 - Python version:
 - Calibre-Web version:0.6.10
 - Docker container:  linuxserver/calibre-web:version-0.6.10
 - Special Hardware: 
 - Browser: chrome Version 88.0.4324.146

**Additional context**
Reverse proxy used : traefik 2.3

**Comment by OzzieIsaacs** [comment]
This is a problem of the reverse proxy configuration, I can‘t help you with this. I‘m sorry.
Please ask for help at the docker container provider, or from the reverse proxy programmer.

**Comment by StudioEtrange** [comment]
Ok, so there is no code in calibre web that generate this : 

https://mydomain/author/new/1 => HTTP Response 308, redirect to HTTP://mydomain/author/new

**Comment by OzzieIsaacs** [comment]
I doublechecked it, there is indeed this strange redirect for "id" = 1. Calibre-Web internally has a routing table where some parameters are having default values to ensure valid pages are shown. Id =1 is one of this and also page = 1. It looks now like the routing mechanism is redirecting https://mydomain/author/new/1  to HTTP://mydomain/author/new (with default id = 1). I never realized this before.  
I will let run a complete set of tests this evening and publish the change tomorrow (if everything is fine)

**Comment by OzzieIsaacs** [comment]
I changed it, please update to the newest beta of 0.6.12 (available via nightly updates)
