### ISSUE TITLE
Viewing users' downloaded books from admin view missing after v0.6.9

### ISSUE THREAD

**Issue by shayaknyc** [janeczku/calibre-web#1855]
Hey there! I recently upgraded to v0.6.11 and I was previously on v0.6.9
When logged in to the Admin view, and then clicking on a user, there used to be displayed at the bottom of their profile a thumbnail view of all that user's downloads. While I have "view downloaded books" toggled ON for all users, I can no longer, as the admin, see the specific books that were downloaded, only a download count. Is there a way to restore this functionality? 

Now, if I click on the "Downloaded Books" in the left sidebar, it only displays the logged-in user's book list. I'd like, as the admin user, to be able to see all my users' downloaded books.

**Comment by johnvick** [comment]
Noticed this also and would be keen to have this feature back. Thanks to all involved in making this excellent app.

**Comment by OzzieIsaacs** [comment]
Duplicate of #1730
