### ISSUE TITLE
"Cover Format Error" on all metadata cover downloads from URL

### ISSUE THREAD

**Issue by aserrallerios** [janeczku/calibre-web#1859]
**Describe the bug/problem**
Calibre-web cannot download cover URLs (like the ones got from "metadata fetch".

**To Reproduce**
1. Upload a new book
2. Edit metadata
3. Fetch metadata with cover (example: https://img9.doubanio.com/view/subject/m/public/s31889541.jpg)
4. Save

**Logfile**
```
[2021-02-13 13:56:22,452]  INFO {cps.helper:590} File Format Error 'Response' object has no attribute 'save'
```

**Expected behavior**
I expect to see no error and the cover successfully applied to the book.

**Environment (please complete the following information):**
 - OS: FreeBSD
 - Python version: python3.7
 - Calibre-Web version: 0.6.12

**Comment by OzzieIsaacs** [comment]
It's fixed in the newest nightly version. Please consider installing imagemagick library, so you can save the time of changing the cover on several formats after upload, because they are detected and inserted already

**Comment by aserrallerios** [comment]
Thanks, there's any documentation abut that feature? Should I just install the `imagemagick` binary?

**Comment by OzzieIsaacs** [comment]
https://github.com/janeczku/calibre-web/wiki/Extend-Features#extract-metadata-from-uploaded-files
