### ISSUE TITLE
Auto Login

### ISSUE THREAD

**Issue by bkanuka** [janeczku/calibre-web#186]
I'd like to auto login as Guest and jump right to showing books and browsing. Currently the only page I can access without logging in is the login screen.

**Comment by OzzieIsaacs** [comment]
If you want to use it as guest you only have to activate anonymous browsing (admin section, configuration). Than a user guest should appear in the admin section, you can give this user the rights you want (editing metadata, showing/hiding certain nav elements, ...) After logging out you should be able to access all the configured sections. (I had sometimes the problem that it's not working as expected, in this case a restart of the script and/or the browser helped).

**Comment by bkanuka** [comment]
hmm, I thought that's how it should work! I'll try restarting everything...

**Comment by bkanuka** [comment]
Still not working. On first start, I'm presented with the config screen. I set the database location, as well as enabling upload and anonymous browsing (and everything else!). However, going to the main page just brings me to the login page - as does clicking "Guest" at the top.

In order to see books, I need to create a new account and log in.

**Comment by bkanuka** [comment]
The real problem is that I need to restart the app before these settings take. But, I was using the docker image and the settings are erased on startup! Ultimately I think this is bug in the docker image because the db/settings should be consistent across restarts.

**Comment by Kennyl** [comment]
Please refer #158 
IT iS NOT docker bug, docker's nature, commit docker once you finish setup.
Or change another image contribution.

**Comment by bkanuka** [comment]
I don't think its a bug in docker - I think it's a bug with the docker image I'm using [janeczku/docker-calibre-web](https://github.com/janeczku/docker-calibre-web). I will try your suggestions in janeczku/docker-calibre-web#4
