### ISSUE TITLE
Reverse Cache

### ISSUE THREAD

**Issue by mycanaletto** [janeczku/calibre-web#1860]
Latest linuxserver Docker.

Hi,

When I activate the cache on the Nignx reverse I always fall on the /basicconfig page. Cannot get the login page.

The only solution is to disable the cache at the Nignx level.

I deleted the reverse configuration without success.

Idea welcome ;-)

Merci

**Comment by OzzieIsaacs** [comment]
I read some documentation and I don't think is going to work together with the way Calibre-Web works:
route e.g. "basicconfig" is generated by calibre-web server and the content is changing based on the configuration step you are in:
1. request -> Display field for entering database location, "enter" button visible
2. request -> Display filled field for database location, "goto login" button visible
Nginx would now cache the content of the first request (especially if you enter a wrong database several times) -> your problem.
This behavior is the same for many other pages. Only very view pages load the data via javascript calls (e.g. books list view), where caching the base html page would make sense (but then the time consuming part is loading and rendering the data afterwards, so I don't think caching would save much time)

Calibre-Web now doesn't support any caching functions (from my understanding this ones: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) to tell the proxy to not cache this pages to prevent the issues you describe.

**And no I will not implement this feature**. 

There is an ongoing PR to reduce the size of the cover pictures to speed up loading of the pages (#1771)

From personal view the only cachable routes would be the "cover" routes and the routes starting with "static" for javascript, css, favicon, graphics and so on. But be aware for the "covers", in case you change a cover the cache will still send out the old cover (we had earlier a problem with the browser internal cache regarding this issue)
