### ISSUE TITLE
No download on Tolino Vision 4 HD

### ISSUE THREAD

**Issue by tobivan** [janeczku/calibre-web#1861]
Hi there,

I am running docker-container technosoft2000/calibre-web on Synology DS920 and all's fine, yeah, except......
On Tolino Vision 4 HD there is no button showing up for downloading an .epub.
In fact, everything is working fine except there isn't showing up anything if I click on a book. It says "Buchdetails" and that's it, no description of the book, nothing.

Thanks for help!
![tolino_calibre](https://user-images.githubusercontent.com/25041087/107921913-877b7480-6f6f-11eb-88cc-b130602cbffa.jpg)

**Comment by oulifspeedy** [comment]
I have the same problem von my Kobo Glo HD and Tolino Shine.

**Comment by fxsth** [comment]
Same problem on Tolino Shine 2 HD. Is it still the `lm.session_protection = 'strong'` issue mentioned in #1466 ?

**Comment by OzzieIsaacs** [comment]
Possible

**Comment by kbruegge** [comment]
Same here. Bin that way at least since version 6.09. One way to work around the problem is to click the books author. Then from the author page click the selected books title (not the cover) to got the books page. At this point you can download the file.

**Comment by fxsth** [comment]
> Same problem on Tolino Shine 2 HD. Is it still the `lm.session_protection = 'strong'` issue mentioned in #1466 ?

Can confirm, it is the session protection. In (default) basic mode it works. Basic mode can enable the login by username:password@calibre-web-url either. 
@OzzieIsaacs Is there any solution for fixing that in an easier way? I run calibre-web in docker (linuxserver) and editing files in a docker container seems to be an ugly way. What about setting the session protection as environmental variable, default 'strong' and optional 'basic' for every Tolino-owner?

**Comment by kaoz3000** [comment]
I fixed it for my tolino by setting `lm.session_protection = 'basic'`
and delete all `data-target="#bookDetailsModal"`  from the template html files 
then the book details will not open in a popup (that tolino can't render) but open on a new page where i can download the ebup and read all the details.

**Comment by tobivan** [comment]
Where can I find these paths and files cps/templates/ and cps/_init_.py ?

**Comment by kaoz3000** [comment]
> Where can I find these paths and files cps/templates/ and cps/_init_.py ?

I think this depends on how and where you installed calibre-web. `/cps/` is a subdirectory of the calibre-web App.
I used the linuxserver docker: I had to log in the docker (`docker exec -it calibre-web /bin/bash`) and then it's in this directory: `/app/calibre-web/cps`

**Comment by Gymnae** [comment]
I helped myself with loading two shells into my shotgun, I mean, by adding these three lines of code to my shell script spinning up the calibre-web container:
```sh
docker exec calibre-web find /app/calibre-web/cps/ -mindepth 1 -type f -exec sed -i 's/data-target="#bookDetailsModal"//g' {} \;
docker exec calibre-web find /app/calibre-web/cps -mindepth 1 -type f -exec sed -i "s/lm.session_protection = 'strong'/lm.session_protection = 'basic'/g" {} \;
docker restart calibre-web
```

**Comment by Gymnae** [comment]
My workaround has stopped working with the latest release, now the downloads are all corrupted.

**Comment by Gymnae** [comment]
That them unfortunately hinders logging in - the login form does not render correctly

**Comment by AnonTester** [comment]
Same problem on my Bookeen ereader. 
User agent string:
Mozilla/5.0 (mobile; CPU ARM Linux 2.6.21;en-us) AppleWebKit/525.1 (bookeen/cybook) Orizon/1.0 (screen 600x800)"

This commit probably fixed the issue for Kindle,kobo,Tolino, but needs Bookeen cybook exception as well:
https://github.com/janeczku/calibre-web/commit/14a6e7c42c6d27369467a05986a82f16d73290f8

**Comment by OzzieIsaacs** [comment]
I added "bookeen" reader to the list of "simple theme" reader, preventing the use of dialogboxes to show book details.

**Comment by OzzieIsaacs** [comment]
Due to some donations I'm now owning a tolino reader and I tried to solve the issue with it. Till now I didn't succeed, so the only solution is up to now:
remove: `lm.session_protection = 'strong'` line in \_\_init\_\_.py file
remove:     
```
if not ub.check_user_session(current_user.id, flask_session.get('_id')) and 'opds' not in request.path:
        logout_user()
```
in admin.py

The side effect is that it's easier to steal the login cookie and use it even after you logged out the user. If you use Calibre-Web in your home without access to the internet this might be okay for you. 

Currently there is not more I can do. 

I will not put this into the code as configuration option

**Comment by AnonTester** [comment]
> I added "bookeen" reader to the list of "simple theme" reader, preventing the use of dialogboxes to show book details.

Working fine, thanks.

**Comment by IFireflyl** [comment]
> Due to some donations I'm now owning a tolino reader and I tried to solve the issue with it. Till now I didn't succeed, so the only solution is up to now: remove: `lm.session_protection = 'strong'` line in __init__.py file remove:
> 
> ```
> if not ub.check_user_session(current_user.id, flask_session.get('_id')) and 'opds' not in request.path:
>         logout_user()
> ```
> 
> in admin.py
> 
> The side effect is that it's easier to steal the login cookie and use it even after you logged out the user. If you use Calibre-Web in your home without access to the internet this might be okay for you.
> 
> Currently there is not more I can do.
> 
> I will not put this into the code as configuration option

Can you provide a quick tutorial on how to complete these two steps? Calibre-web is completely unusable with Cloudflare as it logs you out every few seconds, and everything I have tried to correct this isn't working. I can no longer downgrade to the old version as it doesn't have the fix for the mobi to epub format when sending to Kindle, and if I can't stop this stupid thing from logging me out every couple of mouse clicks then I'm going to throw in the towel.

**Comment by Ilpredatore** [comment]
Hi,
is this fix still working with version: [0.6.21-ls243]?

In my Tolino Vision 4 i can't select a book because web UI log me out.

Thank you.

Federico

**Comment by NiiWiiCamo** [comment]
> Due to some donations I'm now owning a tolino reader and I tried to solve the issue with it. Till now I didn't succeed, so the only solution is up to now: remove: `lm.session_protection = 'strong'` line in __init__.py file

This is still the current fix for Tolino owners (Vision 5 here). The admin.py file seems to have been modified at some point already to comment out the other lines.

**Comment by gymnae** [comment]
My workaround is to turn the tolino into a kobo device. This only possible for newer tolinos which share the same Hardware with kobo devices.

Then calibre-web can be connected via the kobo sync feature.

**Comment by TwlyY29** [comment]
@gymnae this sounds intriguing. would you mind sharing your approach?
So far, I set the `SideloadedMode=true` in `Kobo/Kobo eReader.conf`, and tried setting the `api_endpoint` in a newly added config section `[OneStoreServices]`. Syncing, however, didn't work. I'd appreciate a pointer what to try next... :-)
