### ISSUE TITLE
SyntaxError: invalid syntax on startup

### ISSUE THREAD

**Issue by bin101** [janeczku/calibre-web#1862]
**Describe the bug/problem**
Commit e6fb46007186e152bb262b0eb979f60462abb552 seems to break something.

**To Reproduce**
1. Use a version with the mentioned commit
2. Try to start cps with python3 cps.py
3. SyntaxError: invalid syntax

**Logfile**
Feb 15 08:43:03 calibre-web python3[96]: Traceback (most recent call last):
Feb 15 08:43:03 calibre-web python3[96]:   File "/root/calibre-web/cps.py", line 34, in <module>
Feb 15 08:43:03 calibre-web python3[96]:     from cps import create_app
Feb 15 08:43:03 calibre-web python3[96]:   File "/root/calibre-web/cps/__init__.py", line 38, in <module>
Feb 15 08:43:03 calibre-web python3[96]:     from .server import WebServer
Feb 15 08:43:03 calibre-web python3[96]:   File "/root/calibre-web/cps/server.py", line 159
Feb 15 08:43:03 calibre-web python3[96]:     and os.path.exists(f"{py_script}.exe")
Feb 15 08:43:03 calibre-web python3[96]:                                         ^
Feb 15 08:43:03 calibre-web python3[96]: SyntaxError: invalid syntax

**Expected behavior**
CPS should start properly

**Environment (please complete the following information):**
 - OS: debian 10
 - Python version: 3.5.3
 - Calibre-Web version: see above
 - Docker container: None

**Comment by OzzieIsaacs** [comment]
Please try the newest nightly version, could have been related to spaces vs. comma, or a line ending problem

**Comment by OzzieIsaacs** [comment]
If your problem is solved, please close the issue

**Comment by bin101** [comment]
@OzzieIsaacs still the same:

```
Traceback (most recent call last):
  File "cps.py", line 34, in <module>
    from cps import create_app
  File "/root/calibre-web/cps/__init__.py", line 38, in <module>
    from .server import WebServer
  File "/root/calibre-web/cps/server.py", line 159
    and os.path.exists(f"{py_script}.exe")
```

**Comment by bin101** [comment]
It seems the pyload code needs at least python 3.6. I will test this and give you my result here.

**Comment by bin101** [comment]
@OzzieIsaacs python 3.5 was the issue. With python 3.6 it works. Could you change the dependency in the README file?

**Comment by OzzieIsaacs** [comment]
Okay next try, I removed the f-strings, so it should work again with python3.5

**Comment by bin101** [comment]
@OzzieIsaacs that worked but I will keep now my Debian 10 LXC Container with Python 3.7 :)
