### ISSUE TITLE
Mass add-to-shelf button not working in dark theme

### ISSUE THREAD

**Issue by hikanwoi** [janeczku/calibre-web#1863]
**Describe the bug/problem**
When using the dark theme, in the advanced search result page, clicking the "add-to-shelf" button does not bring up the "add-to-shelves" dropdown menu. It works in the standard theme.

**To Reproduce**
0. Use dark theme
1. Go to advanced search
2. Do any search
3. Click the "add-to-shelf"
4. The dropdown menu does not show up as expected.

**Expected behavior**
The "add-to-shelves" dropdown menu should show up, allowing mass add to shelf.

**Screenshots**
http://prntscr.com/zl8txe

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.7.3
 - Calibre-Web version: 0.6.11
 - Docker container: None
 - Special Hardware: n/a
 - Browser: Firefox 85.0.2, Chrome 88

**Comment by OzzieIsaacs** [comment]
The dark theme has indeed some issues. I'm not the programmer of it, so it's always a little bit behind the standard theme

**Comment by cbartondock** [comment]
It actually does work in that if you go in to inspect the page and click the link it works fine. The problem is that the dropdown is getting hit with a "display: none" style for some reason.

**Comment by jamestomasino** [comment]
I'm still experiencing this issue, even on nightly builds.
