### ISSUE TITLE
fetch metadata error

### ISSUE THREAD

**Issue by winnerqin** [janeczku/calibre-web#1864]
hi, when fetch metadata , Show search results is normal, but its display "search error", click  the cover to the form ,no  response. 
What is the reason for this?

**Comment by OzzieIsaacs** [comment]
Fetching metadata from Douban is currently broken, due to a API change of Douban 
#1882

**Comment by OzzieIsaacs** [comment]
It's fixed and working again, and should not happen anymore in the future
