### ISSUE TITLE
No conversion option given on raspberry pi?

### ISSUE THREAD

**Issue by orhanar** [janeczku/calibre-web#1867]
Hi so i installed calibre on pi, also installed calibre web. I set it up normally but despite picking /usr/bin/ebook-convert from the admin menu no conversion option is shown for the books. Also some books dont have send to kindle button despite setting up email in settings. Thanks

**Comment by Hermit-coder** [comment]
Hi. I've been about to post a similar issue about e-book conversion on PRI. Calibre-web doesn't seem to be compatible with Calibre3 ebook-convert with is the latest version that can be installed on RPI.
It returns this error:
`INFO {cps.tasks.convert:104} Book id 238 - target format of .mobi does not exist. Moving forward with convert.
INFO {cps.tasks.convert:140} ebook converter failed with error while converting book
WARN {cps.converter:46} /opt/calibre/ebook-convert: [Errno 8] Exec format error: '/opt/calibre/ebook-convert'`

Is there a way to get around this, or is it something you can fix in a later version?

**Comment by OzzieIsaacs** [comment]
I tried to install calibre on my raspberry pi nano. Installation almost succeded, except for an illegal instruction on shared-mime-info package. I could make calibre to show up in calibre-web by pointing to the correct path. 
![grafik](https://user-images.githubusercontent.com/6438895/108749474-2429ad80-7540-11eb-9c16-8a51d23d9fd7.png)
Converting an epub to mobi failes with empty error message.

Trying to start ebook-convert from command line results in "invalid machine command" (german error message freely translated). 
The Raspberry Pi Nano seems to have a ARM command set which isn't supported by Calibre

Only thing to try would be excecute the ebook-convert command from command line and check what it's saying:
e.g. ` /usr/bin/ebook-convert inputfile.epub outputfile.mobi`

I'm sorry I can't help any further as I don't have a "normal" Raspberry Pi.

**Comment by OzzieIsaacs** [comment]
I bought a raspy 4, installed calibre on newest raspian-lite version (via sudo apt install calibre). Installed everything from requirements.txt and optional-requirements.txt with normal user pi. Cloned calibre web to the raspi (also as user pi), I'm using the calibre database from here: https://github.com/OzzieIsaacs/calibre-web-test/tree/master/test/Calibre_db. I could successfully convert "book7" from epub to mobi and "book8" from epub to azw3.
So I'm sorry, finally I can say I can not reproduce it. The convert option shows up (maybe permission problem?) and I can convert the books.
It might be a problem with your book, which can not be converted by the old version of calibre.

**Comment by OzzieIsaacs** [comment]
![grafik](https://user-images.githubusercontent.com/6438895/109535035-56955680-7abc-11eb-9a2b-60257562cb75.png)
