### ISSUE TITLE
Sending mobi with calibre-web makes Amazon requesting a validation

### ISSUE THREAD

**Issue by pedrom34** [janeczku/calibre-web#1868]
**Describe the bug/problem**
With latest version, when sending mobi book to the kindle address I immediately receive an email asking for verification, just like on this reddit post: https://www.reddit.com/r/kindle/comments/dl58gz/amazon_emailing_me_to_verify_every_book_i_sent_to/

I am not sure AT ALL this issue came with latest version, since I don't use this feature every day, and maybe it worked mid-February, but I'm quite confident it worked with Florence in January.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a book
2. Click on send mobi to kindle
3. The address received an email asking to click on a link to actually receive the book.

**Logfile**
There's no error on the log file, and that's great, because the file is sent! :smile: 

**Expected behaviour**
Book sent without confirmation needed.

**Environment (please complete the following information):**
 - OS: dietpi (Armbian 21.02.2 Buster) 
 - Python version: 2.7
 - Calibre-Web version: 0.6.11 
 - Docker container: None. Calibre-web is on my self-hosted server, behind a nginx reverse proxy.
 - Special Hardware: Rock64
 - Browser: Firefox 85.0.1

**Additional context**
I think it's somehow related to calibre-web, because:
- I made a factory reset on my kindle ;
- I changed the email address "xx@kindle.com" to something else ;
- I changed the sender address to something else ;
- I contacted Amazon support and they told me to delete approved sender address and add it again. I did it.
All of the above without any success, and:
- I tested to send a mobi file with thunderbird => no validation needed at any attempt ;
- I tested with calibre desktop (v. 5.11) => no validation needed at any attempt, whereas when using calibre-web amazon ask for validation every single time.

The settings on calibre-web, calibre and thunderbird are exactly the same:
- SMTP server: ssl0.ovh.net
- Port: 587
- Connection security: TLS

Can you help me with that issue?

**Comment by pulitux** [comment]
try using two completely different accounts, for example thing@kindle.com for your teaser and someotherstuff@hotmail.com for calibre. The point is to avoid any possible similarity of the names. Avoid Gmail, or you must deal with the 'non secure apps' setting

**Comment by pedrom34** [comment]
Yes, that's already the case... And it's working fine with calibre and by sending email directly. It's just with calibre-Web that there's an issue...

**Comment by pedrom34** [comment]
And I'm not using Gmail.

**Comment by tfer6** [comment]
I just stumbled upon the same issue last night.  Hadn't used the send feature in awhile.   My email and kindle email names are incredibly different and am currently using gmx.com to handle the smtp functions.   As pedrom34 mentioned it spits out no error as the file does sent out correct.  Something is just triggering Amazon to flag the email.  I've tried changing my kindle email as well as removing and re-adding my email address to the approved sender, but no luck.

**Comment by rg9400** [comment]
I've been having this issue as well. It is recent, and it may be related to using SMTP to send kindle docs (https://www.fivefilters.org/2021/amazon-send-to-kindle-changes). I am not sure if there is a way to solve this. For what it is worth, I am not "spoofing" my SMTP From Address, which according to the linked article is the culprit.

**Comment by munkymack** [comment]
I'm running into the same issue as well. I'm using Gmail's SMTP as my SMTP server (custom URL, not a gmail.com address). 
 
My send-to-kindle address is thing_123aBc@kindle.com

**SMTP settings are:**
Hostname: smtp.gmail.com
Port: 465
Encryption: Yes
SMTP Login: mybooks@personalURL.com
From Email: mybooks@personalURL.com

I'm getting the verify email from Amazon if I use the **send Mobi to Kindle** button, but also if I download to my computer, and then manually send as an attachment from mybooks@personalURL.com to thing_123aBc@kindle.com

**Comment by pedrom34** [comment]
> **Worth noting:**
> Using the same SMTP settings as above, books sent from Calibre (not Calibre-Web) also are getting a verify email.

Damn. I just tested again, I am not experiencing that at all...
What version of Calibre are you using? 5.12.0 for me.

**Comment by munkymack** [comment]
I'm running both Calibre and Calibre-Web on Docker, both the linuxserver.io image.

Calibre-Web: 0.6.9
Calibre: 5.7.2

So that could be why I'm having an issue. I wouldn't have chimed in above had I previously realized I was so far behind.

_If you are asking yourself why I'm running outdated versions, it's because I can't figure out how to get the latest versions running on Docker. I've got images of the latest versions of both (0.6.11 and 5.12.0), but for some reason, the latest versions are marked in Portainer as Unused._

**Comment by tfer6** [comment]
I was finally able to resolve this issue (fingers crossed). 

I ended up changing both my Kindle email and the smtp email.   

For the Kindle email I used a combination of generic words and numbers.   Like "HouseTreeDog15" or so.  I've ready reports of people having issues with this email matching parts their amazon account and causing issues.

For the smtp email I changed from using GMX.com to Outlook.com.  I also used a very generic but different email address following the same scheme as above.  

Finally, I removed all approved email addresses from my amazon account and then added only the newly create outlook.com email.

Hopefully this will help if anyone else has the issue.  Consider my part of this issue closed.

**Comment by pedrom34** [comment]
Well it doesn't explain why my current setup works with calibre and not with calibre-web.
I still think this issue is relevant. But I'm glad you figured a solution out 👍

**Comment by rg9400** [comment]
I can confirm that I am getting this issue even when sending with Calibre. It seems to be related to a change on Amazon's end, maybe with how gmail and smtp work. Not sure if anyone has figured out a workaround as I can't easily shift smtp servers

**Comment by telecomguyML** [comment]
> I can confirm that I am getting this issue even when sending with Calibre. It seems to be related to a change on Amazon's end, maybe with how gmail and smtp work. Not sure if anyone has figured out a workaround as I can't easily shift smtp servers

I'm not sure this is 100% related to using GMail as your SMTP server.  I have my own domain, email server hosted elsewhere and I am still experiencing this issue.  However, when it first started I noticed I was getting an email back to the sender's (Calibre's) account to click the link to confirm the file being sent and then when I tested last week I noticed I was getting an email to the Amazon account holder email address to confirm receipt of the mobi.

**Comment by rg9400** [comment]
I think I fixed it using GSuite. Please read the blog post at the bottom of this comment in detail as it explains exactly what has changed and may give hints as to how to solve it in your specific setups.

By default, GSuite is not authenticating the domain, which according to the link below, is the new key requirement. Amazon is making sure the sending email (from address) is actually authorized to send from the domain. I have no idea how it works if you are using abc@gmail.com, but if you are using abc@domain.com from GSuite, go to 
`Apps>Google Workspace>Settings for Gmail>Authenticate email` and generate a TXT record which you can add to your DNS provider to run DKIM authentication.

After setting up this type of authentication, sending via gmail SMTP worked. Again, no clue what happens if you don't use a domain, but I assume the from email would be authorized to send from the relevant smtp login, so it shouldn't have an issue in the first place? Keep in mind that if you still use a sending email address that is too similar to your receiving email address, it will still ask for verification. 

https://www.fivefilters.org/2021/amazon-send-to-kindle-changes

**Comment by telecomguyML** [comment]
> I have no idea how it works if you are using [abc@gmail.com](mailto:abc@gmail.com), but if you are using [abc@domain.com](mailto:abc@domain.com) from GSuite, go to
> `Apps>Google Workspace>Settings for Gmail>Authenticate email` and generate a TXT record which you can add to your DNS provider to run DKIM authentication.
> 
> After setting up this type of authentication, sending via gmail SMTP worked. Again, no clue what happens if you don't use a domain, but I assume the from email would be authorized to send from the relevant smtp login, so it shouldn't have an issue in the first place? Keep in mind that if you still use a sending email address that is too similar to your receiving email address, it will still ask for verification.
> 

Alright, so this helped me.  I have my mailserver through Dreamhost but my DNS through Cloudflare.  I found this article:

https://help.dreamhost.com/hc/en-us/articles/215029758-What-are-DKIM-records-

I logged into my Dreamhost console and found the TXT DKIM record and added it to Cloudflare.  I'm guessing this was created after I moved my DNS to Cloudflare.  Once I added that, I tested again and the book now shows up under Personal Documents on Amazon.

**Comment by pedrom34** [comment]
I don't get it.

Why calibre-web requires DKIM records and Calibre doesn't?

**Comment by OzzieIsaacs** [comment]
> I can confirm that I am getting this issue even when sending with Calibre.

Maybe we are discussing two different problems...

**Comment by pedrom34** [comment]
Amazon has changed something.
When sending an ebook to Kindle, an email was sent to the sending address asking to click a confirmation link.
Now it sends an email asking to click a link to the Amazon account address.

For my personal situation, this is much more acceptable. And I think it's a confirmation that calibre-web is not the culprit here.

I don't know if @janeczku wants to close this ticket?
