### ISSUE TITLE
Feature request: Preferred download format

### ISSUE THREAD

**Issue by Kakunas** [janeczku/calibre-web#1869]
If a book have multiple formats like pdf, epub, azw3 you must chosse the right format in the download dropdown menue.
Maybe it is possible to define a preferred format which one i mostly want to download.
Like the look if only one format is available, but with the option to dropdown the download menue.

**Comment by pollitor** [comment]
Better than that, it would be great to allow the user to choose a preferred format and perform an automatic conversion _on the fly_ on download **if the book is not available** in the calibre library **in the chosen format**.

- The preferred format would be **configurable for each user** of calibre-web.
- In the current web interface, conversion is only possible with the permission to edit the book's metadata in the library, which makes it cumbersome to download a book in another format than the one available in the library, and impossible if the user does not has permissions to change the book's metadata. **This feature would not require permission to edit the metadata**, unless you want to save the new format to the library.
- This feature would also be **applicable to the OPDS** catalog and would greatly facilitate the simple download of books in a suitable format for each user.
- It does not need to replace the existing download of formats available in the caliber library in the web interface, **it can be added as a "preferred format"** if the library does not have the book in that format.
- The behavior could also be configured to do a conversion that would **save the new format to the library or do the conversion _on the fly_** without saving it to the library.
- As in the case of the format conversion that is already available, **access to calibre software's _ebook-convert_ tool needs to be configured correctly**.
