### ISSUE TITLE
CBZ/CBR/CBT files with PNG images no longer work in comic viewer

### ISSUE THREAD

**Issue by armouredking** [janeczku/calibre-web#1870]
**Describe the bug/problem**
CBZ files with WEBP or JPG work. CBZ files with PNG do not work.

**To Reproduce**
1. Attempt to read online a CBZ with PNG images

This happens with all of mine with PNG, around 96 mangas. Converting the images in the CBZ to JPG or WEBP allows it to work.

**Logfile**
There are no log files relevant. As far as calibre-web is concerned, nothing is wrong and nothing shows up outside of the open entry (even in DEBUG mode). There is also nothing printed in Chrome's debug console (until you try to go left or right, when you'll get undefineds). Interestingly enough, it appears like it is trying to do something when you open it (and the loader bar at top knows how many images are supposed to be in the CBZ file, it'll say like 1/17 etc) but nothing happens, and in the code window the image ids do not show up

**Expected behavior**
CBZ files with PNG images should work in online reader

**Screenshots**

**Environment (please complete the following information):**
 - OS: Debian 10
 - Python version: 3.7.3
 - Calibre-Web version: 0.6.11
 - Docker container: LinuxServer (tested both install regularly and with Docker, same results)
 - Browser: Brave V1.20.110

**Additional context**
None

**Comment by OzzieIsaacs** [comment]
During addind up of webp format png was accidentally removed. Please update to the newest nightly version and it should work again

**Comment by armouredking** [comment]
Going to close unless something besides commit needs to happen. I took the time to convert stuff to WEBP so don't have any PNGs left over.
