### ISSUE TITLE
Clicking on any author causes an unrecoverable crash

### ISSUE THREAD

**Issue by wobblycogs** [janeczku/calibre-web#1871]
**Describe the bug/problem**
Clicking any author on the authors page causes the stack trace shown below. Calibre-web is unable to recover from this and the only way to get it working again is to restart the container.

Browsing by categories, series, publishers and languages works as expected.

**To Reproduce**
1. Load the site
2. Click authors, list of authors presented
3. Click an author

**Logfile**

500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/app/calibre-web/cps/usermanagement.py", line 38, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 728, in books_list
return render_books_list(data, sort_param, book_id, page)
File "/app/calibre-web/cps/web.py", line 397, in render_books_list
return render_author_books(page, book_id, order)
File "/app/calibre-web/cps/web.py", line 491, in render_author_books
entries, __, pagination = calibre_db.fill_indexpage(page, 0,
File "/app/calibre-web/cps/db.py", line 610, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, pagesize, database, db_filter, order, False, *join)
File "/app/calibre-web/cps/db.py", line 635, in fill_indexpage_with_archived_books
return entries, randm, pagination
UnboundLocalError: local variable 'entries' referenced before assignment

There seems to be very little in the log file even with log level set to debug.

[mod-init] Attempting to run Docker Modification Logic
[mod-init] Applying linuxserver/calibre-web:calibre files to container
[mod-init] linuxserver/calibre-web:calibre at sha256:12236bee76ab71407b72a02f412ad7972854b58e97084078d1d5bd1ad9c401e1 has been previously applied skipping
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 60-calibre-config: executing... 
[cont-init.d] 60-calibre-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Expected behavior**
Display a list of books by the selected author

**Environment (please complete the following information):**
 - OS: Linux Mint
 - Python version: [e.g. python2.7]
 - Calibre-Web version: 0.6.11
 - Docker container: linuxserver/calibre-web:latest
 - Special Hardware: [e.g. Rasperry Pi Zero]
 - Browser: Chrome 88.0.4324.190 (Official Build) (64-bit)

**Additional context**

**Comment by OzzieIsaacs** [comment]
This is already fixed in the newest nightly version

**Comment by OzzieIsaacs** [comment]
#1865

**Comment by OzzieIsaacs** [comment]
It's fixed in the latest release
