### ISSUE TITLE
Send to kindle failed with permission error

### ISSUE THREAD

**Issue by blackver** [janeczku/calibre-web#1872]
I deploy calibre-web on my docker swarm cluster. I tested the SMTP send email feature with registering new user, and can run correctly. But trying to use send to kindle return this error : Oops! There was an error sending this book: The requested file could not be read. Maybe wrong permissions?

**Comment by OzzieIsaacs** [comment]
Yes, wrong permissions. Calibre-Web can't open the ebook file to attach it to the email. This should also happen during ebook download and maybe if you are try to use the internal viewer

**Comment by Milchdealer** [comment]
I have the same problem. The file does exist though. I'm running in docker with technosoft2000's image.

I ssh'd onto the container:
```sh
$tail calibre-web.log -n 2                                             
[2021-02-25 17:36:03,743] ERROR {cps.tasks.mail:228} [Errno 2] No such file or d
irectory: '/books/Graeber, David/Bullshit Jobs (39)/Bullshit Jobs - Graeber, Dav
id/Bullshit Jobs - Graeber, David.mobi'                                         
[2021-02-25 17:36:03,744] ERROR {cps.tasks.mail:229} The requested file could no
t be read. Maybe wrong permissions?
$pwd                                                                   
/books/Graeber, David/Bullshit Jobs (39)
$ls -la                                                                
total 23384                                                                     
drwxr-xr-x 1 calibre calibre     320 Feb 27 13:21  .                            
drwxr-xr-x 1 calibre calibre      36 Feb 25 17:31  ..                           
-rwxr-xr-x 1 calibre calibre 6726031 Feb 25 18:07 'Bullshit Jobs - Graeber, Davi
d.azw3'                                                                         
-rwxr-xr-x 1 calibre calibre 5601871 Feb 25 17:42 'Bullshit Jobs - Graeber, Davi
d.epub'                                                                         
-rwxr-xr-x 1 calibre calibre 6725981 Feb 25 17:28 'Bullshit Jobs - Graeber, Davi
d.mobi'                                                                         
-rwxr-xr-x 1 calibre calibre 4721921 Feb 25 17:57 'Bullshit Jobs - Graeber, Davi
d.pdf'                                                                          
-rwxr-xr-x 1 calibre calibre  123527 Feb 25 17:25  cover.jpg                    
-rwxr-xr-x 1 calibre calibre   28886 Feb 25 17:25  metadata.opf
```

Sidenote: the files were all generated by calibre-web

**Comment by Milchdealer** [comment]
I can download the files just fine. It also works to send files which were not converted by calibre-web. So I'm unsure why it fails with converted ones...

**Comment by adocampo** [comment]
Yes, sending to kindle stopped working here on `technosoft2000/calibre-web` docker image. It was working last time I've uploaded a book, a few weeks ago, IIRC.
I've configured manually calibre desktop to see if there were some problems with my kindle or account, but from calibre desktop I can send books as usual, so there must be something wrong with calibre-web.
I've double-checked the smtp parameter, and send a test email succesfully.
Task view shows no error
![image](https://user-images.githubusercontent.com/2266612/109888308-9195b680-7c83-11eb-9ff8-844f18c724bb.png)
Server logs says mobi format does not exist
```
[2021-03-04 00:49:29,807]  INFO {cps.tasks.convert:104} Book id 70872 - target format of .mobi does not exist. Moving forward with convert.
```
but that isn't really true, as I can download the MOBI from the web
![image](https://user-images.githubusercontent.com/2266612/109888439-cc97ea00-7c83-11eb-8cc9-f1fc2c41d0bb.png)

And the file is indeed there
```
[root@samael Varios autores]# ls -la Dangerous\ Women\ \(70872\)/
total 2513
drwxr-xr-x   2 root users       5 mar  4 00:49  .
drwxr-xr-x 846 root users     846 feb 25 11:36  ..
-rw-r--r--   1 root users  180899 nov 15 17:48  cover.jpg
-rw-r--r--   1 root users  850755 nov 15 17:48 'Dangerous Women - Varios autores.epub'
-rw-r--r--   1 root users 1290548 mar  4 00:49 'Dangerous Women - Varios autores.mobi'
```

I'm running container with the parameters `-e PUID=0 -e PGID=985 ` so permissions are ok

**Comment by adocampo** [comment]
Any progress on this issue? 
I can do some tests if any developer wants to.

**Comment by blackver** [comment]
i solved it already, i made my own image for raspberry pi. Here my image blackver/calibre-web:latest. That include ebook-convert too.

**Comment by adocampo** [comment]
Just last night I've tried linuxserver docker image and there is working too... so I've switched from technosoft to linuxserver docker.

**Comment by Milchdealer** [comment]
So this is an issue with technosoft's image?

**Comment by adocampo** [comment]
That's my guess, don't know the differences between technosoft and linuxserver but on the later it works.

**Comment by blackver** [comment]
For my problem, i found it because i don't have ebook-convert tool installed. When i have AZW3 files without ebook-convert the button on the "send to kindle" is detecting the files as AZW. So i make calibre-web docker image for armf with calibre installed.

**Comment by adocampo** [comment]
Both technosoft and linuxserver has ebook-convert, linuxserver out of the box and, if I'm not wrong, technosoft by adding the environment parameter `-e APP_REPO=https://github.com/janeczku/calibre-web.git`
Technosoft just stopped working suddenly on my scenario
