### ISSUE TITLE
[0.6.11] CBZ files no longer open on browser

### ISSUE THREAD

**Issue by GarckaMan** [janeczku/calibre-web#1874]
**Describe the bug/problem**
After updating to 0.6.11, Calibre-web can't open CBZ files

**To Reproduce**
1. Update to 0.6.11
2. On the main page, click any cbz file
3. Click **Read in the browser** > **cbz**
4. The reader will appear with the loading bar but the file will not open

**Logfile**
```
[2021-03-01 02:48:12,148] DEBUG {cps.web:1548} Start comic reader for 5834
[2021-03-01 02:48:12,321]  INFO {cps.web:1203} Serving book: Shelter - Cuvie
```

**Expected behavior**
The reader should be able to open the CBZ file

**Screenshots**
![image](https://user-images.githubusercontent.com/68790233/109446271-1f716780-7a20-11eb-9244-a98fc1cf0ad7.png)

**Environment (please complete the following information):**
- OS: Debian 10 (on a Proxmox LXC)
- Python version: 3.7.3
- Calibre-Web version: 0.6.11
- Docker container: None - Installed using pip
- Special Hardware: AMD
- Browser: Chrome latest

**Comment by OzzieIsaacs** [comment]
Are you maybe having this one: #1870?

**Comment by GarckaMan** [comment]
@OzzieIsaacs Indeed it is the same issue.
I saw that it was fixed on the nightly version. I download the fix and it is working fine for me now.
