### ISSUE TITLE
Safari: drag and drop file upload fails due to missing constructor

### ISSUE THREAD

**Issue by njjonet** [janeczku/calibre-web#1881]
Steps to reproduce:
1. Use Safari 14.0.3 on Big Sur
2. Drag and drop EPUB file onto CalibreWeb top bar or 'Upload' button.
3. Expected: file upload dialog box appears with progress of adding EPUB to Calibre library
4. Result: nothing happens.

Safari JS console highlights this is where the issue is:
https://github.com/janeczku/calibre-web/blob/87d6008dfc3d06326de183243192c9357b835d4d/cps/static/js/main.js#L90

At most, it seems to just be missing a semi-colon at the end of the statement. Very likely, Safari doesn't tolerate this, while Chrome and other browsers handle it more liberaly.

**Comment by njjonet** [comment]
Did some local testing trying to fix this issue. Turns out it's not just a simple semi-colon missing in the code (duh!).
Something in Safari doesn't like how the jQuery DataTransfer object is created. According to https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/DataTransfer, this object constructor is not compatible with Safari. Does anyone know a workaround?

**Comment by OzzieIsaacs** [comment]
According to the linked website safari is compatible meanwhile
