### ISSUE TITLE
send to kindle not option

### ISSUE THREAD

**Issue by jocefello** [janeczku/calibre-web#1887]
I don't see the button / option to send the books to kindle 

![imagen](https://user-images.githubusercontent.com/39740830/110258182-8a331d80-7fa1-11eb-960d-f9de94d3ddd5.png)

how to activate this option? 

Thx

**Comment by name-is-ooo** [comment]
You need to set up your Kindle E-mail Address in persenal center.

**Comment by jocefello** [comment]
In the new user created I have added the Kindle email address. 
But the button still does not appear. 

Version 0.6.11 with Docker

**Comment by name-is-ooo** [comment]
Maybe you need to upload books in other formats, such as .mobi/.azw3/.pdf

**Comment by name-is-ooo** [comment]
It looks like you only uploaded the book in EPUB format, which is not supported by Kindle, so there is no button / option to send the books to kindle

**Comment by jocefello** [comment]
> 
> 
> It looks like you only uploaded the book in EPUB format, which is not supported by Kindle, so there is no button / option to send the books to kindle

the file type was the problem.
solved!

thanks very much man

**Comment by ArtisanByteCrafter** [comment]
If your installation of calibre-web has the calibre binary built in to it, you can put the path to the converter binary under `Admin > Basic Configuration > External Binaries ` and it will auto convert to .mobi then send the book to kindle. IIRC, Linuxserver.io images have the calibre app built in.

![image](https://user-images.githubusercontent.com/2523522/110705503-1caf0900-81bc-11eb-86ad-76979a645e9e.png)
