### ISSUE TITLE
Question: Using some form of calibre metadata to auto-shelve items into calibre-web shelves

### ISSUE THREAD

**Issue by UKLibrarian** [janeczku/calibre-web#1888]
Issue #809 (which you also cross-ref to #760) both relate to some mechanism by which Calibre metadata (the original issues don't seem to specify whether they mean the default calibre fields such as tags, or custom columns) can be used to automatically assign books to Calibre-web public shelves.

My question was whether or not this was still on a development plan (or has it already been implemented and I just can't find it).

Regards

Andy

**Comment by OzzieIsaacs** [comment]
You can now perform a advanced search, search for a specific series. Afterwards click on the add to shelf button in the search results, all books are added to the shelf (books already in the shelf are skipped)

**Comment by RARESwan** [comment]
Hi, OzzieIsaacs. I'm running Calibre-Web on my QNAP NAS and it's been working like a dream!

When I do an advanced search I don't see an "add to shelf" button anywhere in the search results page. 

![image](https://github.com/janeczku/calibre-web/assets/15021071/9b36d1f1-386d-4bb9-97bb-e40c2290020a)

**Comment by Mela** [comment]
> You can now perform a advanced search, search for a specific series. Afterwards click on the add to shelf button in the search results, all books are added to the shelf (books already in the shelf are skipped)

This has to be repeated every time there are a number of new books in the library for every shelf. This is nowhere near any definition of the term 'auto-shelve'.
