### ISSUE TITLE
Fetch Metadata is extremely finicky

### ISSUE THREAD

**Issue by Kazz3r24** [janeczku/calibre-web#1889]
**Describe the bug/problem**
When attempting to fetch metadata for a book, after clicking the cover image to select the appropriate metadata, nothing happens. I can do this 5 times in a row and it still doesn't catch. The ONLY way I've been able to successfully get the fetch metadata to stick is by clicking in the absolute bottom right corner of the cover image, then and only then does the data populate properly.

**To Reproduce**
1. Go to 'any book in your library'
2. Click on 'click on Fetch Metadata button'
3. Scroll down to 'the correct match for your book and click the cover image'
4. See error - nothing happened.

**Logfile**
I'll add logs if requested.

**Expected behavior**
For metadata from the selected source to populate correctly.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu server 18.05
 - Python version: Python 3.6.9
 - Calibre-Web version: 0.6.12 Beta 
 - Docker container: N/A
 - Special Hardware: N/A
 - Browser: Chrome 89.0.4389.82

**Additional context**
I haven't tried any other browsers as I assume the same result will occur.

**Comment by OzzieIsaacs** [comment]
It‘s at least not working for comic vine covers, google covers seem to work fine

**Comment by Kazz3r24** [comment]
I'm still finding I have to try clicking on the cover art for a book at least twice before it sticks. I haven't tried a different browser yet but that's my next step.

**Comment by OzzieIsaacs** [comment]
I tried it on my iPad with the above result, I’ll have a look at it

**Comment by OzzieIsaacs** [comment]
Is there any message on the JavaScript console

**Comment by Kazz3r24** [comment]
I haven't investigated this much at all and I'm not at my pc, if I find the answer before you do I'll post another comment.

**Comment by Kazz3r24** [comment]
So far this is the only error I've seen come up in the console. When I tried to match the book, I had the same issue come up where the new metadata didn't stick but no error came up. This error shows when you initially click on Fetch Metadata (probably the search error that comes up).

`jquery.min.js:2 GET https://api.douban.com/v2/book/search?apikey=054022eaeae0b00e0fc068c0c0a2102a&q=The%20Husband%20List&fields=all&count=10&callback=jQuery35109348876288806307_1615664261299&_=1615664261300 net::ERR_ABORTED 403 (Forbidden)`

**Comment by OzzieIsaacs** [comment]
The error is this one #1892

**Comment by cbartondock** [comment]
For the record usually if it doesn't work the first time you click a cover, it will work the second time. No idea why.

**Comment by blumarten** [comment]
Was there ever a fix for this? Im having real problems trying to get some books' metadata to stick. Some just refuse outright, no matter where i click on the metadata thumbnail to add it

**Comment by OzzieIsaacs** [comment]
I can’t reproduce this, I click on the thumbnail and data is changed

**Comment by blumarten** [comment]
hey ozzie, in case it's helpful to you, i screen-recorded an example here - https://www.youtube.com/watch?v=wgK8DM7AGcU

It's not all books this happens with, just here and there.

**Comment by FantoDev-1** [comment]
I had this issue, but found that if i enabled uploads for the user in question, it worked flawlessly every time.

**Comment by blumarten** [comment]
> I had this issue, but found that if i enabled uploads for the user in question, it worked flawlessly every time.

hmm, i'm the admin and it did work a few times, but now it doesn't work at all.
where would i find the setting you mention? there's nothing leaping out at me right now

**Comment by LantrixUK** [comment]
Got to Admin (top right) > Edit Users and select the user and tick the Allow Upload.

URL is: http://yourip:8083/admin/usertable

**Comment by OzzieIsaacs** [comment]
To make the setting visible you might need to activate uploads in general via admin -> basic configuration -> feature configuration -> enable uploads

**Comment by blumarten** [comment]
hmm i tried turning that on, but no success. still won't 'stick' any metadata.
tbh i t would be useful to be able to swap book covers without having to choose an entire set of other metadata to go with it. That's actually all i use the metadata option for

**Comment by blumarten** [comment]
> Got to Admin (top right) > Edit Users and select the user and tick the Allow Upload.
> 
> URL is: http://yourip:8083/admin/usertable

ahhh this setting worked, thank you!

**Comment by LantrixUK** [comment]
You can just upload a cover image, if you have one locally. Often, i'll just download a cover image and then upload locally.

**Comment by blumarten** [comment]
> You can just upload a cover image, if you have one locally. Often, i'll just download a cover image and then upload locally.

duh, i see i now have that option having turned on the upload for the user account. that's perfect, what a great piece of software this is!

**Comment by LantrixUK** [comment]
It's fantastic isn't it!

**Comment by blumarten** [comment]
> It's fantastic isn't it!

just brilliant. i did also try kavita, which is ok, but the lack of communication between the UI and the calibre db just made things much more difficult than they need to be. Also, now i have a domain & cloudflare tunnel set up so my elderly parents can access my library it's just excellent. a huge thank you to the team who made this.
