### ISSUE TITLE
douban link seems broken.

### ISSUE THREAD

**Issue by free521521521** [janeczku/calibre-web#1892]
Seems information from douban is invalid.

**Comment by litianyu0707** [comment]
yes, it can't work.

**Comment by OzzieIsaacs** [comment]
PR #1882 fixes this

**Comment by OzzieIsaacs** [comment]
Meanwhile douban isn't working anymore, as the api is changed. It will not be supported in the fututre. I'm sorry, but there is nothing I can do about it.

**Comment by free521521521** [comment]
pity

**Comment by free521521521** [comment]
> Meanwhile douban isn't working anymore, as the api is changed. It will not be supported in the fututre. I'm sorry, but there is nothing I can do about it.

pity

**Comment by ybnedsi** [comment]
https://registry.hub.docker.com/r/fugary/simple-boot-douban-api/

**Comment by OzzieIsaacs** [comment]
Douban is back in the newest nightly
