### ISSUE TITLE
Cannot enter author's name Lina Galán

### ISSUE THREAD

**Issue by adocampo** [janeczku/calibre-web#1895]
**Describe the bug/problem**
A weird bug is annoying me. My wife added a few books from Lina Galán, she added previosuly other books from that author before, and she had no trouble at all, but now, when she enters that name, the field author simply doesn't save.
At first, I thought perhaps the name had an `á`, so I'd tried to add another name with an accent (José), and that worked, then I've tried to modify slightly the name Lina Galán, and Linda Galán, Lina Galánd worked, but as soon as I type Lina Galán, the author's name disappear.

**To Reproduce**
1. Edit a boot metadata
2. Change the author's name to Lina Galán
3. Save
4. See how author's name is empty

**Logfile**
no error logged on calibre-web.log

**Expected behavior**
Name should be saved.

**Screenshots**

**Environment (please complete the following information):**
 - OS: docker version
 - Python version:  python2.7
 - Calibre-Web version: 0.6.11 and 0.6.2beta
 - Docker container: Technosoft2000, Linuxservers
 - Special Hardware:
 - Browser: Firefox 86, Latest Chrome and even Edge

**Additional context**
Access via reverse proxy

**Comment by adocampo** [comment]
Just tried with linuxservers docker image, the problem is still there. I opted to put the name as `Galán, Lina` instead.

**Comment by OzzieIsaacs** [comment]
I'm pretty sure this has to do with your calibre database. Could you please check in calibre if there are different authors named Lina Galán?
![grafik](https://user-images.githubusercontent.com/6438895/111128250-f7801900-8574-11eb-964e-d008c3a67a85.png)
Could you please send me a screenshot of the situation, this would help to solve the problem.
Could you also try to unify the names in calibre, afterwards it should work as expected.

**Comment by OzzieIsaacs** [comment]
Could be related to #1789

**Comment by adocampo** [comment]
hummm, there are 3 Lina Galán on my database: author 6684, 6685 and 11747
![image](https://user-images.githubusercontent.com/2266612/111130047-0e276f80-8577-11eb-8ec8-6594a27e28d9.png)
![image](https://user-images.githubusercontent.com/2266612/111130106-1da6b880-8577-11eb-984e-0f230b4881e4.png)

My bet is I need to leave just one of those, deleting dups and incorrect ones, like Linda Galan (without accent)

Let me check

**Comment by OzzieIsaacs** [comment]
Yep, this is the problem

**Comment by adocampo** [comment]
Thank you I'm going to clear duplicates then.

There is a thing I don't understand, for example if I take and earlier uploaded book for that author, metadata shows the "author order" correctly
![image](https://user-images.githubusercontent.com/2266612/111133783-30bb8780-857b-11eb-8179-9b4e83bd18fe.png)

But on newer, it complains about this
![image](https://user-images.githubusercontent.com/2266612/111133604-fd78f880-857a-11eb-85f8-3c5739c8db67.png)
but even correcting the order
![image](https://user-images.githubusercontent.com/2266612/111134017-78daaa00-857b-11eb-848d-1750c3bb7735.png)
appears the author
![image](https://user-images.githubusercontent.com/2266612/111134053-82fca880-857b-11eb-8562-012ce7600693.png)

so, definitively, I need to clear all those duplicates.

Thank you a lot @OzzieIsaacs, and sorry for bother you with those non-unrelated calibre-web issues...
