### ISSUE TITLE
Cannot view Book Details in default kobo browser

### ISSUE THREAD

**Issue by csbenz** [janeczku/calibre-web#1899]
**Describe the bug/problem**
In the default Kobo browser, whenI click on a book, a window appears but it is empty. I cannot see the book details and cannot download the book. On my computer, everything works fine. A Javascript issue?

**To Reproduce**
1. Go to https://calibre.domain.com/calibre-web in the default Kobo browser
2. Click on any book
3. The book details window appears
4. The window is empty and no action is possible (no download button)

**Expected behavior**
Be able to see the book details, like on the computer

**Environment (please complete the following information):**
 - OS: Kobo Libra H20
 - Python version: [e.g. python2.7]
 - Calibre-Web version: 0.6.11

**Comment by kaoz3000** [comment]
Maybe you can try my solution:
https://github.com/janeczku/calibre-web/issues/1861?_pjax=%23js-repo-pjax-container#issuecomment-802337087

**Comment by nadres** [comment]
Hello,

Same is happening to me. The workaround is fine and I can download books from my Kobo. However it will be annoying having to manually apply these changes after each update. Is this an issue with the browser in the Kobo or can something else be done to have a consistent behaviour?

Kobo Libra H20.
Python | 2.7.17 (default, Feb 27 2021, 15:10:58) [GCC 7.5.0]
Calibre-Web: 0.6.10 Beta

Thanks much.

**Comment by OzzieIsaacs** [comment]
This is a problem with the used browsers in the reader, they can't open the modal dialog which was used to display the books detail page. Meanwhile calibre-web (or it should) detects the reader and opens the details page in a new browser tab/window
