### ISSUE TITLE
Cannot send mobi to Kindle

### ISSUE THREAD

**Issue by ptoulouse** [janeczku/calibre-web#1900]
**Describe the bug/problem**
I can't send books to kindle using Linuxserver docker container. The conversion to mobi is successful but that emailing the kindle failed. Looking in the folder I can see a mobi file where I expect it. Looking at the log, it seems calibre-web seems to try to send the book with a wrong path: `/books/Rick Riordan/L'epee de l'ete (1341)/L'epee de l'ete - Rick Riordan/L'epee de l'ete - Rick Riordan.mobi`. The correct path is: `/books/Rick Riordan/L'epee de l'ete (1341)/L'epee de l'ete - Rick Riordan.mobi`

Sending from calibre works.

**To Reproduce**
1. Select a book.
2. Press send to Kindle (either epub or AZW3 as source fails).
3. Go to Tasks view.
4. Message says conversion is successful, but emailing failed.
5. Repeat the send step. This time no conversion occurs but emailing fails.

**Logfile**
```
[2021-03-16 20:31:23,012]  INFO {cps.tasks.convert:94} Book id 1341 already converted to .mobi
[2021-03-16 20:31:23,018] ERROR {cps.tasks.mail:228} [Errno 2] No such file or directory: "/books/Rick Riordan/L'epee de l'ete (1341)/L'epee de l'ete - Rick Riordan/L'epee de l'ete - Rick Riordan.mobi"
[2021-03-16 20:31:23,018] ERROR {cps.tasks.mail:229} The requested file could not be read. Maybe wrong permissions?
```
**Expected behavior**
I expect that sending book works at it used to.

**Environment (please complete the following information):**
 - OS: Linux
 - Calibre-Web version: 0.6.11
 - Docker container: LinuxServer

**Comment by jslan420** [comment]
Hi, here's a quick hack. This is not well tested, maybe there is some nasty side effects... but it works for me anyway.

1. change line 96 in `/app/calibre-web/cps/tasks/convert.py`
```
    #self.results['path'] = file_path
    self.results['path'] = file_path + format_new_ext
```

2. change line 224 in `/app/calibre-web/cps/tasks/mail.py`
```
   #file_ = open(os.path.join(calibrepath, bookpath, filename), 'rb')
   file_ = open(os.path.join(bookpath), 'rb')
```
restart calibre-web and it should be ok.

**Comment by swf5002** [comment]
Just a note to confirm this same problem exists with the container version that the linuxserver.io team packages.

**Comment by OzzieIsaacs** [comment]
Remark: Amazon doesn't allow azw files to be send via email to kindle readers, only mobi files work. 
I can reproduce the problem with mobi files which are not part of the library and "get found" by calibre-web via the convert process. So I recommend (until I fix it) to run a library maintenance from calibre desktop app and add all missing book formats.
