### ISSUE TITLE
How to set base url for calibre-web?/or is it possible to add the function for it, thanks!

### ISSUE THREAD

**Issue by wswv** [janeczku/calibre-web#1911]
Due to I used self-defined port as web server port, it looks like: www.dd.dd.net:5321/calibre-web, when I use reverse proxy to access calibre-web, the web address link will jump and removed the self-defined port, it looks like www.dd.dd.net/calibre-web/login, it can not access the web except manually add the port to www.dd.dd.net:5321/calibre-web/login.
I know some software like dukuwiki, it could define a base url, which you can defined the base url to www.dd.dd.net:5321, then when link changed, but original link www.dd.dd.net:5321 will not change all the time, and it will not meet the issue too.

Could it is possible to define the base url in calibre-web?

I used SWAG(from linuxserver) as reverse proxy, and docker calibre-web from them too. they indicated in reverse proxy  config that calibre-web didn't support the base url.

So is it possible to add the function for it?

Thanks!

**Comment by OzzieIsaacs** [comment]
Calibre-web will autodetect the config based on proxy header values. I will not add a baseurl.
Please have a look at the wiki:
https://github.com/janeczku/calibre-web/wiki/Setup-Reverse-Proxy

Please understand that I can't support all reverse proxy programs in the world, I never heard about SWAG. I'm sorry you are on your own to find out how to add the header variables
