### ISSUE TITLE
Move multi ebook in shelf

### ISSUE THREAD

**Issue by fra-pel** [janeczku/calibre-web#1914]
It would be nice and useful to be able to select multiple ebooks and move them to the shelves, maybe from "Book list".

**Comment by OzzieIsaacs** [comment]
You can do a search to get the Books you want to add to the shelf and then there is a Button to Add all of them

**Comment by fra-pel** [comment]
> You can do a search to get the Books you want to add to the shelf and then there is a Button to Add all of them

Thanks, i have found! The button "move tho shelves" show when i do "Advanced search". Thanks.

**Comment by fra-pel** [comment]
But when i click on "add to shelf" don't work. Don't click...

**Comment by OzzieIsaacs** [comment]
For me it's working I testsd standard theme and also Caliblur Theme. Without more information (the form!!) I can't help you anymore
