### ISSUE TITLE
Recommended way to take into account Calibre db update?

### ISSUE THREAD

**Issue by nodje** [janeczku/calibre-web#1920]
I just started to use Calibre-web and so far so good.

But as I added books to the library, which I do with a "traditional" Calibre and then sync the db with calibre-web instance, I realised Calibre-web would not display newly added books.

I got it to work restarting the docker instance running it. Which works.

I couldn't find any documented way for this scenario.
I'd be super handy to have a way to cope with Calibre library changes, as this is a very obvious need.

Maybe a croned refresh/restart?
Though that should be handled within the docker instance.

**Comment by konart** [comment]
I've just started using calibre-web myself and have no problems with sync. Though I'm not entirely sure If you are using the same db for calibre and calibre-web or not.

The way I use it is:

1. Sync local folder to `/upload` folder on my server
2. Crontab adds new books to calibre
3. That's it. You can see them in calibre-web (calibre-web is using the same books\db folder as calibre)

**Comment by nodje** [comment]
Actually I wasn't aware of any upload capacity of calibre-web. Now that you mention it, I can see
- Upload new books in many formats, including audio formats (.mp3, .m4a, .m4b)
in the feature list of the Readme.

Still, I can't find the `/upload` folder you are talking about.

The way I do it now, it to sync my laptop's calibre folder with CalibreWeb server's db folder. 
But then I have to restart the docker service to have CalibreWeb take the changes into account

**Comment by OzzieIsaacs** [comment]
The update problem seems to be mostly related to the docker installation (I can't reproduce it). There is a button in the admin section to do a reconnect to the database (the content is then refreshed). A possible solution is described in https://github.com/janeczku/calibre-web/issues/1510#issuecomment-664803786.

> The way I do it now, it to sync my laptop's calibre folder with CalibreWeb server's db folder.

I can promise you, you will get trouble at some point. Calibre-Web is not made for having replaced the metadata.db file while using it. So you will get a `corrupt database` error at a time you can't remember this post anymore.

**Comment by konart** [comment]
> Still, I can't find the `/upload` folder you are talking about.

This folder has nothing to do with calibre itself. It is something that I’ve created in my home folder on server. 

I upload my books into this folder and crontab executes the `calibredb add` command every 5 minutes to add newly uploaded books to calibre database. 

> The way I do it now, it to sync my laptop's calibre folder with CalibreWeb server's db folder.

I don’t think that replacing calibredb file created by a different calibre instance every time is a good practice.

**Comment by nodje** [comment]
OK, I wasn't aware I had to activate the Upload feature in Feature Configuration. My bad.

This is a bit confusing though. Why would calibre-web need to be able to "reconnect" to the DB?
That seems to indicate that it basically is made to act as a "Reader" of the db only.

And then the Upload feature feels like a work-around this basic predicate.

With this in mind, using a Desktop Calibre instance to add books, with all the metadata editing possibilities, and syncing to a  read-only database dedicated for a Calibre-web server instance seems to be a pretty good setup to me.

**Comment by OzzieIsaacs** [comment]
> The update problem seems to be mostly related to the docker installation (I can't reproduce it)

**Comment by perler** [comment]
ok, I understand your reservations about replacing the metadata.db while running calibre-web but for a lot of people this is the way they work. so, I can live with the limitations but wonder why in my case here even "reconnect database" doesn't pick up the new metadata.db.

this is a docker image (ghcr.io/linuxserver/calibre-web) and worked, what I did was a) replacing the sync method (from resilio to google drive with https://www.insynchq.com/) and updated from 6.09 to 6.12. I see that the metadata.db is updated in the filesystem (outside and inside the container) and the test book added is in a directory on the calibre-web server. 

any way to debug this?
