### ISSUE TITLE
Caliblur - add to shelves button in search broken

### ISSUE THREAD

**Issue by ashtonx** [janeczku/calibre-web#1930]
**Describe the bug/problem**
When searching for novels there's no add to shelve button which can be used to add books to shelf
When using advance search the button is there but it doesn't work.

**To Reproduce**
1. Use search
2. Look for button on results page (none)
4. Use advanced search
5. Click on add to shelf icon on results page (button sometimes clicks, no menu shows up)

**Expected behavior**
- In search results there should be Add to shelf button.
- In advanced search results, add to shelf button on click should popup shelves to which add results.

**Screenshots**
Search - normal theme:
![calibreweb-search-normal](https://user-images.githubusercontent.com/17355743/113449818-ef422d80-93fe-11eb-9a72-666381d3b25e.png)
Search - caliblur theme:
![calibreweb-search-normal-caliblur](https://user-images.githubusercontent.com/17355743/113449820-ef422d80-93fe-11eb-8957-cc39d83cece8.png)
(no add to shelf button)

Advanced search - normal theme:
![calibreweb-search-advanced](https://user-images.githubusercontent.com/17355743/113449811-ed786a00-93fe-11eb-835b-b7b697df709f.png)
Advanced search - caliblur theme:
![calibreweb-search-advanced-caliblur](https://user-images.githubusercontent.com/17355743/113449816-eea99700-93fe-11eb-82f6-363f41583855.png)
(clicking on button does nothing)

**Environment (please complete the following information):**
 - OS: ArchLinux (Desktop)
 - Calibre-Web version:  0.6.11
 - Docker container: LinuxServer
 - Special Hardware: qnap ts251D (8GB RAM) (nas server)
 - Browser: Firefox 87.0 (Desktop)

**Comment by cbartondock** [comment]
This is fixed as of a PR I made and that got merged. You can either switch to master or wait for a new version.
