### ISSUE TITLE
optional-requirements.txt has an incompatible dependency

### ISSUE THREAD

**Issue by Caligatio** [janeczku/calibre-web#1936]
**Describe the bug/problem**
It appears that `optional-requirements.txt` has an indirectly incompatible requirement on `google-api-python-client` resulting in the following error when trying to install the optional dependencies:

```console
ERROR: pydrive2 1.7.3 has requirement google-api-python-client>=1.12.5, but you'll have google-api-python-client 1.7.12 which is incompatible.
```

**To Reproduce**
1. `pip3 install -r optional-requirements.txt`
2. See error

**Logfile**
N/A

**Expected behavior**
Things to install without error

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.2
 - Python version: Python 3.8.5 (stock Ubuntu 20.04.2)
 - Calibre-Web version: V0.6.11
 - Docker container: None
 - Special Hardware: N/A
 - Browser: N/A

**Additional context**
`optional-requirements.txt` has `google-api-python-client` directly pinned to `>=1.7.11,<1.8.` whereas pydrive2 1.7.3 wants google-api-python-client>=1.12.5.

**Comment by OzzieIsaacs** [comment]
This is already fixed in the newest nightly version (And it should be safe to just upgrade `google-api-python-client` to the newer version)

**Comment by Caligatio** [comment]
Ahh drat, this is what I get for deciding to use a stable tag instead of HEAD.  Sorry for not checking!

**Comment by OzzieIsaacs** [comment]
No problem, but on head there might be other things not working ...
