### ISSUE TITLE
Finish work on editing user list 

### ISSUE THREAD

**Issue by OzzieIsaacs** [janeczku/calibre-web#1938]
- [x] Sort in checkbox column in user list and book list not working
- [x] no error message in case it's tried to delete last admin account
- [x] delete book from book list leads to main page
- [x] Click on "Edit user" and than cancel leads to admin page
- [x] Implement delete user in user list view
- [ ] Implement mass delete user in user list view
- [ ] Implement mass edit of allow/deny tags/columns
- [x] Guest user can be deleted in list view
- [x] Implement Backend to deny editing Guest rights restriction
- [x] Read visibility missing in user list view
- [x] Enable sort in Book list for non Books table columns, as series, tags, language, publisher, author
- [ ] add tests https://github.com/OzzieIsaacs/calibre-web-test/issues/54

**Comment by rg9400** [comment]
Few comments on just my initial look into this feature

1. It seems the table might be mislabelling upload/download permissions. The table says all my users have upload permission and no download permission when it is the other way around.
2. Clicking Edit User while behind a subfolder reverse proxy leads to a 404 error. The url that seems to be loading is `domain.com/admin/user/3` when it should be loading `https://domain.com/calibre/admin/user/3` instead. All other pages load properly when I use `proxy_set_header 	X-Script-Name 		/calibre;` in NGINX, so it might just be the link
