### ISSUE TITLE
Cannot download the books with any format.

### ISSUE THREAD

**Issue by coyawa** [janeczku/calibre-web#194]
I can access the server very well. I can choose a book and read it online, but can not download it.
What should I do?
read/xxx/pdf works well.
download/xxx/pdf doesn't work.

**Comment by OzzieIsaacs** [comment]
Could you please provide the calibre-web.log file for the problem. I assume you see the buttons and use them for downloading?
Do you try to download it on a PC or a reader? Which browser do you use?

**Comment by coyawa** [comment]
Sorry, the calibre in running in a docker container in may NAS, I don't know how to get the log file.
I click the download button, it linked this page:
![image](https://cloud.githubusercontent.com/assets/4596255/26244463/ba3bc77e-3c5d-11e7-8b97-4f02b411dd40.png)
"Internal Server Error"

If I click the read online button with the same book, everything goes well.
![image](https://cloud.githubusercontent.com/assets/4596255/26244704/d78d3c58-3c5e-11e7-8d69-1584df6612eb.png)

I tried different devices and browser, they all meet the same issue. But not all books have this issued, I randomly tried one book, and it can download successfully.

**Comment by OzzieIsaacs** [comment]
If you can download some books, it looks like a user rights problem. Please check if the access rights of the working and not working books differ.

**Comment by coyawa** [comment]
No, they all used the admin account
