### ISSUE TITLE
Is it possible to customise the name in top left from Calibre Web to something else?

### ISSUE THREAD

**Issue by jdaviescoates** [janeczku/calibre-web#1940]
**Describe the bug/problem**
I want to change the name in top left from Calibre Library to something else.  I couldn't sworn this used to be possible but I've looked around in the admin options and I'm not seeing anything.

**To Reproduce**
1. Go to my install of Calibre Web
2. Note it says Calibre Web top left instead of eBook Library
3. Look in Admin to see if I can change the title somewhere
4. Fail to find such settings.

**Expected behavior**
I *think* I managed to do this before, but now I don't seem able to manage it. It's possible I'm misremembering.

**Screenshots**

I'd like to be able to customise the Calibre Web shown top left here

![Screenshot from 2021-04-08 21-57-21](https://user-images.githubusercontent.com/2113743/114095516-6b33ee00-98b5-11eb-9165-205d8342a29b.png)

**Comment by itchygrub** [comment]
Please go UI configuration, you be able to change name

**Comment by jdaviescoates** [comment]
Thanks, not sure how I missed that! (I'd obviously found it before)
