### ISSUE TITLE
Unable to config OAuth Login

### ISSUE THREAD

**Issue by CGarces** [janeczku/calibre-web#1942]
**Describe the bug/problem**
I have installed the dependencies an created the OAuth config on Google Cloud but I can't find how set the information on calibre-web.

As described in the documentation for OAuth Login

"Copy this information in the corresponding fields in Calibre-Web. should see the Application in the OAuth 2.0 Client IDs table section"

But the combo option not populate any new field (like LDAP)

**To Reproduce**
1. Click on Login type combo  select OAuth
2. Aditional field are not populated

**Logfile**

I see this error in the log, but I can't raise it again....

```
[2021-04-11 19:56:06,065]  INFO {cps.server:205} Starting Gevent server on [::]:8083
[2021-04-11 19:57:35,068] ERROR {cps:1891} Exception on /me [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/calibre-web/vendor/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ubuntu/calibre-web/cps/web.py", line 1565, in profile
    oauth_status = get_oauth_status()
  File "/home/ubuntu/calibre-web/cps/oauth_bb.py", line 169, in get_oauth_status
    query = ub.session.query(ub.OAuth).filter_by(
AttributeError: module 'cps.ub' has no attribute 'OAuth'
[2021-04-11 19:57:47,803]  INFO {cps.server:273} webserver stop (restart=True)
[2021-04-11 19:57:48,814]  INFO {cps.server:261} Performing restart of Calibre-Web
[2021-04-11 19:57:54,461]  INFO {cps:101} Starting Calibre Web...
[2021-04-11 19:57:54,685]  INFO {cps.server:205} Starting Gevent server on [::]:8083

```

**Expected behavior**
Show OAuth options

**Screenshots**

![image](https://user-images.githubusercontent.com/6617155/114319504-222ca580-9b12-11eb-8bf8-6a8037421286.png)

**Environment (please complete the following information):**
 - OS: Ubuntu Minimal 20.04
 - Python version: Python 3.8.5
 - Calibre-Web version:  2d73f541
 - Browser: Chomium Version 89.0.4389.114

**Comment by CGarces** [comment]
div data-related="login-settings-2" is populated
https://github.com/janeczku/calibre-web/blob/4a11dd1e1631b40c0260df1faeda10144592edd4/cps/templates/config_edit.html#L358

But  `provider` at `{% for prov in provider %}` is empty.

**Comment by OzzieIsaacs** [comment]
> AttributeError: module 'cps.ub' has no attribute 'OAuth'

> oauthProvider provider table not exist on my BBDD

Yes this is the problem

**Comment by CGarces** [comment]
> I'll have a look at it.
> 
> Could you please download the debug package from admin page and send it to me.
> 
> Preferable via email on my profile page.
> 
> I'm having the feeling that you are missing "flask dance" python library

```json
{
    "Platform": "Linux 5.4.0-1041-oracle #44-Ubuntu SMP Fri Mar 19 18:12:09 UTC 2021 x86_64 x86_64",
    "Python": "3.8.5 (default, Jan 27 2021, 15:41:15) \n[GCC 9.3.0]",
    "Calibre_Web": "0.6.12 Beta - $Format:%%H$ - $Format:%%cI$",
    "WebServer": "Gevent 21.1.2",
    "Flask": "1.1.2",
    "Flask_Login": "0.5.0",
    "Flask_Principal": "0.4.0",
    "Werkzeug": "1.0.1",
    "Babel": "2.8.1",
    "Jinja2": "2.10.1",
    "Requests": "2.22.0",
    "SqlAlchemy": "1.4.7",
    "pySqlite": "2.6.0",
    "SQLite": "3.31.1",
    "iso639": "0.4.5",
    "pytz": "2021.1",
    "Unidecode": "installed",
    "Flask_SimpleLDAP": "installed",
    "python_LDAP": "3.3.1",
    "Goodreads": "installed",
    "jsonschema": "3.2.0",
    "flask_dance": "3.0.0",
    "greenlet": "1.0.0",
    "Image Magick": "not installed",
    "PyPdf": "v1.0.3",
    "lxml": "v4.6.3.0",
    "Wand": "not installed",
    "Comic_API": "2.2.0",
    "ebook converter": "not installed",
    "unrar": "not installed",
    "kepubify": "not installed"
}
```

**Comment by OzzieIsaacs** [comment]
> "SqlAlchemy": "1.4.7",

Please downgrade to a supported version of SqlAlchemy:
from requirements.txt:

`SQLAlchemy>=1.3.0,<1.4.0    # oauth fails on 1.4+ due to import problems in flask_dance`

**Comment by OzzieIsaacs** [comment]
https://github.com/janeczku/calibre-web/issues/1902#issuecomment-812361209

**Comment by OzzieIsaacs** [comment]
`flask-dance 4.0` would work instead of `flask-dance 3.0`

**Comment by OzzieIsaacs** [comment]
Dependencies are working as follows:

| Sqlalchemy  | sqlalchemy-utils  | Flask-dance |
| ---------- |:---------:|---------:|
| <1.4 | any | <=3.0.0 |
| any | >=0.37.0 | <=3.0.0 |
| any | / | >=4.0.0 |

Complicated stuff

**Comment by CGarces** [comment]
I'm newby on python
If requeriments.txt has
SQLAlchemy>=1.3.0,<1.4.0    # oauth fails on 1.4+ due to import problems in flask_dance

Why I have 1.4.7? I have review my bash history and the commands exucuted was:

```
pip3 install --target vendor -r requirements.txt
pip3 install optional-requirements.txt
sudo apt-get install libldap2-dev libsasl2-dev <- To install mising dev dependencies
pip3 install optional-requirements.txt

```

In any case `pip3 install Flask-dance -U` solve the issue on my environment,

**Comment by OzzieIsaacs** [comment]
One of the dependencies is requiring sqlalchemy without limiting it‘s max version. Now you should have flask-dance 4.0 which works
