### ISSUE TITLE
"Read in Browser" is missing

### ISSUE THREAD

**Issue by zais** [janeczku/calibre-web#1943]
Running calibre-web: 0.6.11 - 4a4d02ea6a91ba3e77337cfce65e756e2e806599 - 2021-02-02T19:04:55+01:00
In docker from linuxserver: ghcr.io/linuxserver/calibre-web ("build_version": "Linuxserver.io version:- 0.6.11-ls113 Build-date:- 2021-04-06T10:21:00+00:00")
Everything appears to be ok, but there is no reader/viewer button visible:
![img](https://i.imgur.com/ULBy43X.png)

**Comment by OzzieIsaacs** [comment]
Your user is missing the read role.
Add it by editing the user as admin from the admin page and add `Allow Edit` to the access rights
![grafik](https://user-images.githubusercontent.com/6438895/114595351-9429f980-9c8e-11eb-8535-cc5d68a42e3d.png)

**Comment by zais** [comment]
Well, that's embarrassing.
Thank you for quick turn around, it works now.
Not sure why admin user doesn't have 'Allow eBook Viewer' by default.

**Comment by OzzieIsaacs** [comment]
For new created instances the admin account should have all rights. This was a "bug" long time ago, I think. Another posibility is you created your app.db before the roles have been switched and I didn't extend roles for already created users
