### ISSUE TITLE
TokenExpiredError for Google OAuth 

### ISSUE THREAD

**Issue by abhilesh** [janeczku/calibre-web#1944]
**Describe the bug/problem**
I had successfully setup Google OAuth authentication by setting the appropriate environmental flags in my docker compose

**To Reproduce**
1. Sign-in using google
2. See error

Same issue encountered while trying to link Google Account for individual users

**Logfile**
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/app/calibre-web/cps/oauth_bb.py", line 50, in inner
return f(*args, **kwargs)
File "/app/calibre-web/cps/oauth_bb.py", line 321, in google_login
resp = google.get("/oauth2/v2/userinfo")
File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 543, in get
return self.request('GET', url, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/flask_dance/consumer/requests.py", line 194, in request
return super(OAuth2Session, self).request(
File "/usr/local/lib/python3.8/dist-packages/requests_oauthlib/oauth2_session.py", line 477, in request
url, headers, data = self._client.add_token(
File "/usr/local/lib/python3.8/dist-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 198, in add_token
raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired)
**Expected behavior**

**Environment (please complete the following information):**
 - OS: [Raspberry Pi OS Buster]
 - Python version: python3.8
 - Calibre-Web version: 0.6.11
 - Docker container: ghcr.io/linuxserver/calibre-web
 - Special Hardware: Raspberry Pi 4
 - Browser: Chrome Version 89.0.4389.114 (Official Build) (x86_64)

**Additional context**
I'm accessing the server via nginx reverse proxy

**Comment by OzzieIsaacs** [comment]
If you update to the newest commit version from now you should get an error message. 
Googling the error messages lead me to the conclusion that the token you are using is revoked/deleted/invalid

**Comment by abhilesh** [comment]
Thanks a lot for adding the error. How would I force a refresh of the token for a given user?

**Comment by abhilesh** [comment]
I have been able to get both github and google OAuth login working for http but not https. I'm using a self-signed certificate from Let's Encrypt that's managed by Nginx Reverse Proxy manager.

Are there additional settings that I need to configure to get the https callback url worklng?

**Comment by OzzieIsaacs** [comment]
While testing this I also used Let's encrypt certificate. Using `Https` normally was easier than getting `http` to work, as google is denying `http` requests per default.
Github was easier than google. 
Create Oauth App inDeveloper settings on Github page. Enter Homepage URL and authorisation callback url in the corresponding pages on github page.
My Reverse proxy maps calibre-web to a folder like: https:\\example.com\calibre-web. I'm using Apache and a config very similar to the config in the wiki. Access of calibre-web instance via reverse proxy to make the callback working later on.
My callbackrotine is therefor:  `https:\\example.com\calibre-web\login\github\authorized`
Enable debug logging in Calibre-web Basic config. Enter Github client id and client secret in basic config in calibre-web. 
Click on "link" on the user side gives me the following output:
![grafik](https://user-images.githubusercontent.com/6438895/114695025-6f2f9800-9d1b-11eb-92d9-9ece82cd00f8.png)

The certificate is also from let's encrypt (all browser texts are in german, I'm sorry):
![grafik](https://user-images.githubusercontent.com/6438895/114695713-3217d580-9d1c-11eb-94b8-cfaa4817a598.png)


This is working like a charm. What are you doing? What's exactly not working, which step isn't working? What is the exact error message?

**Comment by abhilesh** [comment]
For the github OAuth, say if my reverse proxy is pointed at `https://ebooks.example.com`, the http callback routine - `http://ebooks.example.com/login/github/authorized` works fine but the https callback - `https://ebooks.example.com/login/github/authorized` throws a redirect_url_mismatch error. I've attached a screenshot for the log for this.

For the google OAuth, I keep running into the TokenExpiredError. The last time I could fix it by clearing cookies but I haven't been able to force refresh the token since then. I run into this error even when trying to unlink google account.

**Comment by OzzieIsaacs** [comment]
I spend the time to set everything up. 
Worked as expected on the first try using the example from the wiki adding up the 3 line for the ssl stuff. 
![grafik](https://user-images.githubusercontent.com/6438895/116781579-07e84680-aa84-11eb-8668-a53a497036e3.png)

Setup on github site:
![grafik](https://user-images.githubusercontent.com/6438895/116781586-19c9e980-aa84-11eb-9239-8cb477c16482.png)

Just follow the example and don't forget the x-scheme header parameter
