### ISSUE TITLE
Home button in reader

### ISSUE THREAD

**Issue by Jakgab617** [janeczku/calibre-web#1945]
I just wanted to ask if there's a way to add a home button while using the built-in reader.

Any help or nudge in the right direction is appreciated. Thank you.

**Comment by Northguy** [comment]
What do you mean with 'home' button? The reader opens in a new tabsheet, so you can always return to calibre-web by switching tabs?
Navigating within the book can be done through the book index which is hidden under the hamburger menu on the top left of the reader?

**Comment by Jakgab617** [comment]
Hi, I sorted it out. I didn't know that this thread is still open. I was trying to make an app out of it. And on the reader window there's no navigation if it's viewed within an app. The quick fix I did for the app is to create a navigation menu on top of the reader tab.
