### ISSUE TITLE
[Question] How to store eBooks and BooksOnTape

### ISSUE THREAD

**Issue by iamdoubz** [janeczku/calibre-web#1947]
# Idea
Simply put, I want to have my eBooks and the .ogg/.mp3/etc files under the same category and not separate. In addition, if the files for the audio come in multiple parts, how do I store that using calibre-web?

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10/Raspberry Pi OS] Ubuntu 20.04
 - Python version: [e.g. python2.7] 3.8.5
 - Calibre-Web version: [e.g. 0.6.8 or 087c4c59 (git rev-parse --short HEAD)]: 0.6.11 - 4a4d02ea6a91ba3e77337cfce65e756e2e806599
 - Docker container: [None/Technosoft2000/LinuxServer]: LinuxServer
 - Special Hardware: [e.g. Rasperry Pi Zero] ?
 - Browser: [e.g. Chrome 83.0.4103.97, Safari 13.3.7, Firefox 68.0.1 ESR] Chrome 89 / Firefox 87

**Additional context**
Just how to do it. If it doesn't exist, I can re-write into a [FEATURE REQUEST]

**Comment by OzzieIsaacs** [comment]
> I want to have my eBooks and the .ogg/.mp3/etc files under the same category and not separate.
? I'm not sure if I get this question right. You want to you ebooks and your audio books in one database? This is of course possible, with the restriction from part 2 of your question, see below

> In addition, if the files for the audio come in multiple parts, how do I store that using calibre-web?

Calibre-web uses the calibre database to store the ebook data. According to my knowledge calibre isn't capable of dosing so, so calibre-web can't do it. One book can only have one book of each format
