### ISSUE TITLE
Cover image rendering

### ISSUE THREAD

**Issue by MontyJ** [janeczku/calibre-web#195]
Unable to see cover images (outline box only) when accessing from the web. Images show properly when accessing locally via 192.168.x.xxx:port.

Have tried Firefox, Chrome, and Brave browsers, none will render covers.

**Comment by OzzieIsaacs** [comment]
Are you using the docker image, or Reverse proxy?

**Comment by MontyJ** [comment]
Thanks Ozzie,

No docker image.

I am using the Pagekite DNS server service, similar to noIP. No port forwarding needed. I run Ubooquity through this service on the same Calibre db with no problems. Have also run the Calibre Server through this service.

**Comment by MontyJ** [comment]
I tried again, and now have success with Chrome. Cleared all caches and history and now chrome shows images properly.

However, doing the same with Firefox and Brave browsers, and restarting them, still does not render the cover images. Sometimes the first image will show, but none of the others will. Sometimes only a partial image will show...it seems random on how they display. But never more than one or two show completely...if any at all.

I disabled as many plugins in Firefox as I could, no luck. I do not have any in Brave, but set the 'shields' to all off.

**Comment by OzzieIsaacs** [comment]
Hint from a former similar problem:
Calibre is made for case insensitive file systems like Windows, hence sometimes you get the situation where the file names in the database and the actual file names on disk do not match with regards to character case. (But this doesn't match to working with some browsers)

Are the covers loading if you are clicking on one of them? 
If you take a look on the source of the website (firefox -> Extras -> web developer -> page source or similar) The links to the covers are showing up as:
`<img src="[image Link]"/>`
Do the links work there? Clicking them one by one loads them?

You could create an account on your calibre-web for me (very restricted access would be enough) and send me the login data via e-mail. I try to take a look on my own.

**Comment by MontyJ** [comment]
Ozzie,

Ok, good idea, I will set up a login for you.

No, the images still do not load. The results seem random, ie they may load partially, from the top down, not at all, or rarely, the full image will load!

Does the image size have anything to do with it? The "cover.jpg" files are only about 184KB, but in Calibre I set them all to 900x1200. If you think that may make a diff, I could set a few back and test them.

Monty

**Comment by OzzieIsaacs** [comment]
It's just loading the files independently from size. The bigger the files the longer it takes, but there is no limitation from the server side.

**Comment by MontyJ** [comment]
Ozzie,

I'm new to this system...don't see how to email you privately?

**Comment by OzzieIsaacs** [comment]
Please send an email to ozzie.fernandez.isaac [at] gmail.com

**Comment by MontyJ** [comment]
Ok, email with login info sent.

**Comment by OzzieIsaacs** [comment]
Sorry I pasted email address wrong:
ozzie.fernandez.isaacs [at] gmail.com
(Missing s at the end)
Could you please send email to this address.

Thanks

**Comment by MontyJ** [comment]
Thanks Ozzie for the assist!

One last question that may be of general interest: How to delete a user? I don't see any control in the admin setup for users to "delete" a user. I do get users coming and going and assuming this image problem gets squared away, will be making use of it.

Again, many thanks for taking a look at this!

Monty

**Comment by OzzieIsaacs** [comment]
In the admin section click on the user you want to delete. On bottom of the page tick the last option on right side "delete user" and than submit
