### ISSUE TITLE
Support for full-text search in TXT file format of e-books

### ISSUE THREAD

**Issue by GruberMarkus** [janeczku/calibre-web#1950]
The Calibre plugin Multi-Column Search (https://www.mobileread.com/forums/showthread.php?t=261712) creates a custom column in the Calibre database, basically containing the whole ebook as plain text.

The plugin uses the text in this column for an integrated full-text search feature.

It would be great if calibre-web could add this column to it's search feature, as this would make it possible to search the content of an ebook and not only the metadata.

**Comment by GruberMarkus** [comment]
My wish for a full-text search in Calibre-Web is still there, but my initial proposal to use a table created by the Multi-Column search plugin will not work.

After rethinking my wish and investigation technical possibilities, I see three options for a full-text search:

1. Perform a full-text search in every e-book that is also available in TXT format (pure plain text). This is what the full-text search of the Multi-Column Search plugin for calibre does.
This might be implementable in Calibre-Web with the least effort compared to the other options and does not bloat metadata.db, but requires more storage space for each book (appr. 500 MB for 1,000 books) and an additional conversion step for the librarian.

2. Perform a full-text search in every ebook, no matter which format is available.
This seems hard to implement, as Calibre-Web would need to have a reading component for every e-book format. I would not bloat metadata.db and be convenient for the librarian, but would probably be slower than searching through TXT files.

3. Use the word index Multi-Column Search
In the table "_mcs_word_book_index", the column "book" is the book number as integer and "word" is a single word string contained in this book.
The search would probably be faster than searching in TXT files, but table bloats metadata.db (appr. 500 MB for 1,000 books), requires multiple extra steps for the librarian (create TXT files, manually start indexing), and can not be used to search for phrases as the table only contains single words without a hint which words occure before or after.


I think that only options 1 and 2 are feasable.

@OzzieIsaacs, it would be great if there was an option in Calibre-Web to extend the search so that it includes the already search Calibre columns as well as e-books which are available in TXT format.

**Comment by OzzieIsaacs** [comment]
I decided to not move on in this direction.

**Comment by jorbig** [comment]
Calibre 6 supports full text search within all books. Will Calibre Web jump in on that?
