### ISSUE TITLE
Send to Kindle stopped working. Task fails immediately.

### ISSUE THREAD

**Issue by Cloudhidden** [janeczku/calibre-web#1953]
**Describe the bug/problem**
Send to kindle feature does not work. When I click send PDF or MOBI to kindle from any book, the task fails immediately and it hangs in the tasks preventing me from initiating any other tasks. I have to go into settings and restart to clear the task.

**To Reproduce**
1. Click on book
2. Click the Send to Kindle button
3. Click tasks
4. Task fails in less than 5 seconds and it hangs indefinitely until calibre-web is restarted

**Logfile**
No errors are logged to calibre-web.log 

> [2021-04-15 12:59:03,301]  INFO {cps.server:216} webserver stop (restart=True)
> [2021-04-15 12:59:03,318]  INFO {cps.server:201} Performing restart of Calibre-Web
> [2021-04-15 12:59:06,712] DEBUG {cps.services:29} Cannot import goodreads, showing authors-metadata will not work: No module named 'betterreads'
> [2021-04-15 12:59:06,716] DEBUG {cps.services:37} Cannot import simpleldap, logging in with ldap will not work: No module named 'flask_simpleldap'
> [2021-04-15 12:59:06,718] DEBUG {cps.services:45} Cannot import SyncToken, syncing books with Kobo Devices will not work: No module named 'jsonschema'
> [2021-04-15 12:59:07,228] DEBUG {cps.gdriveutils:69} Cannot import pydrive,httplib2, using gdrive will not work: No module named 'pydrive'
> [2021-04-15 12:59:09,135] DEBUG {cps.comic:44} Cannot import comicapi, extracting comic metadata will not work: No module named 'comicapi'
> [2021-04-15 12:59:09,147] DEBUG {cps.comic:51} Cannot import rarfile, extracting cover files from rar files will not work: No module named 'rarfile'
> [2021-04-15 12:59:09,374] DEBUG {cps.admin:72} Cannot import Flask-Dance, login with Oauth will not work: No module named 'flask_dance'
> [2021-04-15 12:59:09,402] DEBUG {cps.gdrive:46} Cannot import googleapiclient, using GDrive will not work: No module named 'googleapiclient'
> [2021-04-15 12:59:09,553]  INFO {cps:101} Starting Calibre Web...
> [2021-04-15 12:59:10,186]  INFO {cps.server:168} Starting Tornado server on :8083

**Expected behavior**
When I click Send to Kindle it should email the book to my kindle. If it errors out, it should at the very least throw an error message in the log.

**Screenshots**
![image](https://user-images.githubusercontent.com/82607052/114932484-6a86e480-9dec-11eb-9ad7-43d1acbedd1f.png)

**Environment (please complete the following information):**
 - OS: Raspberry Pi OS 
 - Python version:  3.7.3
 - Calibre-Web version: 0.6.11
 - Special Hardware: Raspberry Pi 3B w/ SSD 
 - Vivaldi 3.5.2115.87

**Additional context**

I've been using calibre-web for over a year now and it's been working great. This issue just started happening.
Though I recently migrated my installation from a Pi2 to a Pi3 and am running the OS from an SSD and not from the SD card, I don't see how any of that relates to this one particular feature not working anymore.

I have installed it using the steps on this project page.  I did not use docker.

I tested my SMTP config in desktop Calibre and it works fine. I receive the book in my kindle.

![image](https://user-images.githubusercontent.com/82607052/114933884-11b84b80-9dee-11eb-944e-dd53bb613df8.png)

Converting tasks are not affected. Only Send to kindle tasks.

My issue sounds similar to #892 but my SMTP config is valid because it works from Calibre Desktop. 

I don't know what else to try or look for. The fact no errors appear in the logs is making me reach out for help.

Thank you.

**Comment by OzzieIsaacs** [comment]
Sounds a bit like:  #1906 (also outlook account). 
In the screenshot it states it failed after 13min and not 5sec?
You could try to update to the newest nightly version, I added some more outputs during sending emails

**Comment by Cloudhidden** [comment]
> In the screenshot it states it failed after 13min and not 5sec?

No, the task fails immediately but the Run Time keeps running indefinitely, even after the failure and it goes on until I click Settings > Restart. 


I checked for updates this morning in the Nightly branch and I saw that there were quite a few changes. I went ahead and updated my install to the latest version (4/18) but that did not resolve the issue.

I will try deleting the app.db per #1906 and will update this thread later.

**Comment by Cloudhidden** [comment]
Renaming the app.db to something else and re-generating it did not fix the issue.

I recreated the app.db and tested sending out to kindle with the admin account and it worked at first. However when I added other user accounts and tested them they failed the same way as before. I tried testing the admin account again and it fails too.

**Comment by vassallos** [comment]
I am also having the same problem.. using sendgrid to send emails (credentials are correct). It immediately fails the task.

**Comment by OzzieIsaacs** [comment]
Please update to the newest nightly version, I added some debug output and probably fixed a problem on sending emails with python versions <3.8

**Comment by Cloudhidden** [comment]
It's working! I don't know what changes you made but I can send e-books to kindle again.

I'm closing this issue as resolved. Thank you.
