### ISSUE TITLE
Kobo sync with deny tags doesn't work

### ISSUE THREAD

**Issue by JVT038** [janeczku/calibre-web#1962]
**Describe the bug/problem**
I wanted to sync only certain books to my kobo E-Reader, so I created another user, and added an allow tag called 'sync' to it. 
I added the tag 'sync' to all books I wanted to sync to my E-Reader and when I logged in with the user, it showed the books I allowed.
I added the kobo sync endpoint of that user to `Kobo eReader.conf`, but when I synchronized the books, I got 50 books who didn't have the `sync` tag, nor were they accessible via the calibre-web UI in the browser.
When I went to `calibreip:8083/kobo/kobo_secret/v1/library/sync` in the browser, I saw a lot of books, which didn't have the `sync` tag.

**To Reproduce**
1. Go to calibre-web
2. Create a new user and add an allowed tag
3. Generate an endpoint and add it to `kobo eReader.conf`

**Expected behavior**
I expected only the books with the `sync` tag to appear in the kobo sync 

**Environment (please complete the following information):**
 - OS: Docker
 - Python version: 3.8.5
 - Calibre-Web version: 0.6.12 beta, nightly branch
 - Docker container: Linuxserver/calibre-web
 - Special Hardware: Synology NAS DS918+
 - Browser: Firefox 87.0

**Additional context**
I access calibre-web via an NGINX reverse proxy with Authelia as authentication.

**Comment by OzzieIsaacs** [comment]
It‘s fixed in the newest master commit
