### ISSUE TITLE
ebook-convert fails

### ISSUE THREAD

**Issue by dr400** [janeczku/calibre-web#1965]
When invoking conversion tool, "tasks" reports that the book has been converted to the requested format (EPUB 2 MOBI) in 0s (strange indeed) but it appears that no conversion has been made ... mobi format does not exist under the metadata of the book. Therefore send to kindle failed to send the mobi format as it has not been created ...

![image](https://user-images.githubusercontent.com/48514024/115822783-67e84880-a405-11eb-9b99-10f5e090b760.png)

**Comment by Cloudhidden** [comment]
Go to Settings > view logs and see what calibre-web.log says.

When I get conversion errors like that it usually it has to do with some invalid character derailing the conversion.

**Comment by dr400** [comment]
> Go to Settings > view logs and see what calibre-web.log says.
> 
> When I get conversion errors like that it usually it has to do with some invalid character derailing the conversion.

When I want to convert from .epub to .mobi, logs say : 

[2021-04-24 20:11:57,281]  INFO {cps.tasks.convert:102} Book id 86265 - target format of .mobi does not exist. Moving forward with convert.

**Comment by dr400** [comment]
Alright, solution is that there was a problem with permissions ... I've fixed permissions and all is back to normal ...

**Comment by zachatttack** [comment]
@dr400 What permissions did you have to change?

**Comment by mike-lloyd03** [comment]
Yes. I'm having the same problem. A more thorough explanation of the solution would have been helpful :(
