### ISSUE TITLE
Batch Conversion from GUI

### ISSUE THREAD

**Issue by iamdoubz** [janeczku/calibre-web#1966]
**Is your feature request related to a problem? Please describe.**
I like to add my books in MOBI format, but like using the web interface to read EPUB formats. It is trivial to click into each and every book and convert from MOBI to EPUB.

**Describe the solution you'd like**
It would be really neat if maybe from the "Books List" be able to select a bunch of books and select "Batch Convert".

**Describe alternatives you've considered**
Using the command: `find . -name \*.mobi -exec /usr/bin/ebook-convert {} {}.epub;` converts all my books, but calibre-web doesn't know about them.

**Additional context**
It would be desirable that if I select a book that already (in this example) has the EPUB format existing, that it would add maybe an "INFO" or a "WARNING" into the Task logged that XYZ book skipped conversion. Reason: already exists.

Thank you and I appreciate all the hard work!

**Comment by Zaroz** [comment]
A workaround would be just to have a docker instance of calibre running and have it automatically add books from a folder and autoconvert those added books to epub

**Comment by OzzieIsaacs** [comment]
I think this is a task for a batch script and using calibre itself (it has a powerful command line interface). I will not implement this in calibre-web.
