### ISSUE TITLE
Very slow loading times

### ISSUE THREAD

**Issue by orhanar** [janeczku/calibre-web#1969]
I am running calibre web docker container on pi4 4gb. Issue is calibre web works very slowly like pages take 25 sec or so to load. Can anyone try it on their machine to see if this is hardware bottleneck or some other sort of issue?

1. Using docker container 
2. Click on next pages
3. You wait very long here

 
**Additional context**

Minimising no of books displayed doesnt really make the performance better.

**Comment by OzzieIsaacs** [comment]
Using a raspberry 4 with raspiban lite (no desktop) **without** docker. Having a library of 700 books located on a usb stick where the raspbian is also excecuted from, I get a loading time of approx 2.5sec. I'm accessing Calibre-Web via Firefox webbrowser executed from my linux PC in the same network (both are connected to my Router via WIFI. My router reports the Raspy having a connection speed of 72MBit/s up and download). The page size (book per page) was set to 20 books. I'm running ne3west commit version of Calibre-Web with python3 and Gevent as Webserver, having installed all optional dependencies. 
![grafik](https://user-images.githubusercontent.com/6438895/116779525-ec2a7380-aa76-11eb-98e9-84ea7c529c56.png)
This is divided into approx. 300ms for the sever response and the other time loading the covers. The cover loading speed is dominated by one cover having a size of 2.4MB.
Doing the same with a library with 40000 books in it leads to the following result (most of the books having no cover):
![grafik](https://user-images.githubusercontent.com/6438895/116779665-eb461180-aa77-11eb-9a6e-a62c88ddfd34.png)
The loading times can be viewed in the developer consoles of the used browsers.

**Comment by OzzieIsaacs** [comment]
issue turns out to be related to where data is stored. SD card was best but had limited space it was in external hdd so moved it to internal and performance is “ok” now
