### ISSUE TITLE
"Settings DB is not Writeable" when adding book to shelf

### ISSUE THREAD

**Issue by gitterspec** [janeczku/calibre-web#1973]
**Describe the bug/problem**
After about 5-10 min of starting the app, when adding a book to a bookshelf, either

1) I get the error "Settings DB is not Writeable" or
2) it appears to be successful but is not actually added on refresh.

The issue goes away after I restart or "Reconnect Calibre Database" but inevitably appears again after ~5-10min.
The issue occurs whether or not Calibre is running.
Changing Settings through Admin panel still works fine.

**Logfile**
Log file shows no output on these actions.

**Environment (please complete the following information):**
 - OS: unRAID 6.9.2
 - Python version: from latest LinuxServer docker
 - Calibre-Web version: 0.6.11
 - Docker container: LinuxServer
 - Special Hardware: N/A
 - Browser: appears on both Windows Chrome and Android Chrome versions

**Comment by OzzieIsaacs** [comment]
I can't reproduce it, for me it's working fine. Many problems with this type of error occur, because people think it's a good idea to sync the metadata.db/app.db file in the background while Calibre-Web is running. 
Every 5-10min sound like a cron job or something running constantly (?)

**Comment by jat255** [comment]
I am having this same issue. Here is the log file when trying (repeatedly) to add a book to a shelf. As far as I'm aware, I don't have any regular cron job or anything running on the Calibre-web database. I'm using the `linuxserver/calibre-web` image, and have updated through the web interface to 0.6.17. Anything else I can provide to help debug?

```
[2022-04-01 15:03:25,556]  INFO {cps.shelf:271} Shelf test created
[2022-04-01 15:03:28,841]  INFO {cps.ub:853} successfully deleted Shelf test
[2022-04-01 15:03:39,508] ERROR {cps.shelf:99} Settings DB is not Writeable
[2022-04-01 15:03:47,563] ERROR {cps.shelf:99} Settings DB is not Writeable
[2022-04-01 15:04:00,838] ERROR {cps.shelf:99} Settings DB is not Writeable
[2022-04-01 15:04:07,644] ERROR {cps.shelf:99} Settings DB is not Writeable
[2022-04-01 15:04:17,825] ERROR {cps.shelf:99} Settings DB is not Writeable
[2022-04-01 15:04:26,892] ERROR {cps.shelf:99} Settings DB is not Writeable
[2022-04-01 15:04:36,704] ERROR {cps.shelf:99} Settings DB is not Writeable
[2022-04-01 15:04:45,412] ERROR {cps.shelf:99} Settings DB is not Writeable
[2022-04-01 15:04:50,444] ERROR {cps.shelf:99} Settings DB is not Writeable
[2022-04-01 15:05:00,300] ERROR {cps.shelf:99} Settings DB is not Writeable
[2022-04-01 15:14:15,491] ERROR {cps.shelf:99} Settings DB is not Writeable
```

**Comment by gitterspec** [comment]
I never resolved this and still have the problem, so I frequently have to restart the docker. Are you volume mapping /books/metadata.db separately in the docker? (I am but don't know why this would be an issue).

I find that the error tends to happen randomly after I add books to shelves, which is usually successful but then inevitably leads to the error after a few books and a required docker restart.

I am starting to think it might be due to a corrupt metadata.db or other database but I haven't had time to troubleshoot troubleshooting the database.

**Comment by jat255** [comment]
Hmm, I do have things mounted through Docker, so perhaps that's the issue. It's on a ZFS volume, so maybe somehow snapshots are causing issues? I'll poke around that side of things to see if I can workaround it.

**Comment by gitterspec** [comment]
Mine is on BTRFS.  If it's a random problem with database access on the filesystem, it seems that calibre-web might be preventing retries after the initial failure.  Is there a way to override this behavior?

**Comment by jat255** [comment]
In my case, restarting the docker container does not help. I ran `docker-compose restart`, and after logging in tried first thing to add a book to a shelf and immediately got `ERROR {cps.shelf:99} Settings DB is not Writeable`

**Comment by jat255** [comment]
So I re-initialized my calibre-web, disconnecting the `/config` directory from any docker mount (so everything is internal to the container, currently) and shelves are working correctly as far as I can tell. It appears there's some sort of incompatibility with how Docker is accessing/locking things, perhaps?
