### ISSUE TITLE
database read-only

### ISSUE THREAD

**Issue by Dorifer** [janeczku/calibre-web#1974]
**Describe the bug/problem**
Calibre-web is not able to write to the metadata.db which is synced from my local machine via (webdav (nextcloud). 
(cant upload books or change metadata). Calibre on the local system is closed, all syncing is finished.

**logfiles:**
Error message in the web interface: 

Database error: (sqlite3.OperationalError) attempt to write a readonly database [SQL: INSERT INTO books (title, sort, author_sort, timestamp, pubdate, series_index, last_modified, path, has_cover, uuid, isbn, flags) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)] [parameters: ('Big Apple Sewer Samurai', '', 'Unknown', '2021-05-02 15:48:24.262395', '0101-01-01 00:00:00.000000', '1', '2021-05-02 15:48:24.262404', 'Unknown/Big Apple Sewer Samurai', True, None, '', 1)] (Background on this error at: http://sqlalche.me/e/13/e3q8).

output of docker exec -it calibre-web ls -la /books/metadata.db:

-rwxrwxrwx+ 1 995 995 464896 May  2 11:11 /books/metadata.db

**Expected behavior**
The database should be writeable

**Environment (please complete the following information):**
 - OS: linux, docker container on debian host system
 - Python version: [e.g. python2.7] 3.8.5 
 - Calibre-Web version: [e.g. 0.6.8 or 087c4c59 (git rev-parse --short HEAD)]: latest docker image (6.11)
 - Docker container: [None/Technosoft2000/LinuxServer]: LinuxServer
 - Special Hardware: [e.g. Rasperry Pi Zero]
 - Browser: [e.g. Chrome 83.0.4103.97, Safari 13.3.7, Firefox 68.0.1 ESR]: Firefox 87.0

**Comment by OzzieIsaacs** [comment]
> Calibre-web is not able to write to the metadata.db which is synced from my local machine via (webdav (nextcloud).

That's correct you can not exchange files Calibre-Web is using in the background and expect it to work. There is a reconnect button on the admin page, you could use this, there should be also some closed issues regarding an automated cron job for triggering a reconnect to the database.

I'm not gonna change it.

**Comment by Dorifer** [comment]
> That's correct you can not exchange files Calibre-Web is using in the background and expect it to work.

Well, it _does_ work kinda, when I add new books locally they show up in calibre-web in the same monent (after the sync has finished). So the reconnect to the database does not seem to be the problem.

> There is a reconnect button on the admin page, you could use this, there should be also some closed issues regarding an automated cron job for triggering a reconnect to the database.
> 
> I'm not gonna change it.

I'm not exptecting any changes in calibre-web, I'm just curious if I can make this setup work both ways that Iḿ able to add books on the calibre-web side as well. Thx in advance for any pointers.
