### ISSUE TITLE
How can I disable infinite scroll in calibur theme

### ISSUE THREAD

**Issue by gitksh** [janeczku/calibre-web#1975]
How can I disable infinite scroll in calibur theme? 
Personally, I don't like the infinite scroll feature, so I want to disable it

**Comment by OzzieIsaacs** [comment]
It's not made to be disabled. The only official thing you could do is reduce the no. of books shown on one page, so they fit to one page, then the normal pagination buttons will show up.

Inoffifical solution by editing the code: 
If you delete this whole block from main.js  
![image](https://user-images.githubusercontent.com/6438895/117053265-097e6c80-ad19-11eb-847d-795842a1750c.png)
This should deactivate it (without having it tested)
