### ISSUE TITLE
Error 404 and reading reading progress synchronization 

### ISSUE THREAD

**Issue by JVT038** [janeczku/calibre-web#1976]
**Describe the bug/problem**
I have 2 bugs I'd like to report.
1. Whenever I delete a book, make and save changes of a book, or search something, I get a 404 page.
The URL I get redirected to after saving changes to a book, is `https://calibre.domain.com/admin/book/https,https://calibre.domain.com/book/9`. 
For some reason, the 404 errors don't occur when using my internal IP instead of reverse proxy.

2. Second bug I'd like to report, is the synchronization of progress. 
I have never had this bug before, up till last week. I don't know why, but for some reason, every time I read a bit, close the book in the middle of a chapter and re-open the book, the book doesn't open where I left off, but in the beginning of the chapter.
Weird thing is, I have never had this issue before, despite having read a couple of synchronized books before.
With the first couple of books I synchronized from the server to my E-Reader, I could just close a book in the middle of a chapter and re-open it on the same location, without being sent back to the beginning of the chapter.
Then, for some reason, it suddenly started resuming books in the beginning of the chapter.
This doesn't happen when I move epub files from my computer to my E-Reader. Only when I synchronize the books.

**Environment (please complete the following information):**
 - Python version: Python3.8.5
 - Calibre-Web version: 0.6.12 beta
 - Docker container: Linuxserver
 - Special Hardware: Synology NAS DS918+
 - Browser: FireFox 88.0

**Additional context**
I usually access calibre-web via my NGINX reverse proxy with an SSL certificate from letsencrypt

**Comment by OzzieIsaacs** [comment]
You almost answered your question yourself:

> For some reason, the 404 errors don't occur when using my internal IP instead of reverse proxy.

Your problem is your reverse proxy configuration. Please check out our wiki, there are working examples. The ngnix one is working, I tried it last week by myself
