### ISSUE TITLE
Extend the Shelves in Calibre-web

### ISSUE THREAD

**Issue by szemlicka** [janeczku/calibre-web#1980]
Hi,

at first I love calibre-web. I use very often the function to create different shelves like 
"later read SF" or "must read SF"

Is it possible to put books automaticly inside this shelves related to the custom fields I use in Calibre?
Small example. I add a custom field in Calibre called "Must Read". with an option yes/no. If I choose yes for a book in calibre, it will showing under calibre-web inside the book Info under Published field.

The funtion with the read option and which field in Calibre is used for is similar the same.

A seperate option where you can select the field and the value (from calibre) and linked it to a dedicated Shelves in calibre-web is a missing option.

**Comment by silviuvulcan** [comment]
I think there already are issues for this: #1888 , #809 and the original #760 That being said it's something I'd like to use as well. I wish I could help but my coding skills are terrible 😆 I can help with devops/sysadmin tasks if you have any though...

**Comment by szemlicka** [comment]
I saw that I can search for that custom fields and than I can add it to a shelve. Its not direct this function but the result is the same.

**Comment by OzzieIsaacs** [comment]
Thanks
