### ISSUE TITLE
Custom Column Queries

### ISSUE THREAD

**Issue by jamieadamsuk** [janeczku/calibre-web#1984]
Hello,

I have read the Wiki and FAQ, but I'm struggling a bit with custom columns.

I've got two date columns in Calibre, which contain the date a book was started and the date that the book was completed. For some reason, these don't appear in calibre-web.

I have an additional custom column for my rating of the book, and that appears fine.

I also have a custom column for notes. This will appear if the column is set-up in a specific way, but not if the column format is set to 'long-text'.

Are there restrictions on the types / formatting of custom columns? Am I doing something wrong?

**Comment by OzzieIsaacs** [comment]
It's indeed nowhere documented. The following custom column types are excluded:

'datetime', 'comments', 'composite', 'series'

Some of them are excluded for a reason (I didn't get composite to work), for datetime I can't see the reason for now

**Comment by OzzieIsaacs** [comment]
I enabled custom datetime columns in the newest master commit (Advanced search for such a column isn't working yet)

**Comment by jamieadamsuk** [comment]
Wonderful. Thanks so much!
