### ISSUE TITLE
Kobo Clara HD and Calibre-Web Sync

### ISSUE THREAD

**Issue by serenewaffles** [janeczku/calibre-web#1986]
**Describe the bug/problem**
I am unable to get my Kobo to sync to Calibre web. I can get it to hit the server, but it almost immediately gives me the "Sync failed. Please try again." error.

**To Reproduce**
Attempt to sync with Calibre

**Logfile**
calibre-web.log
```
[2021-05-12 18:39:55,319] DEBUG {cps.kobo:878} Unimplemented User Request received: https://lib.[domain]/kobo/[api_key]/v1/user/profile
[2021-05-12 18:39:55,372] DEBUG {cps.kobo:878} Unimplemented User Request received: https://lib.[domain]/kobo/[api_key]/v1/user/loyalty/benefits
[2021-05-12 18:39:55,470] DEBUG {cps.kobo:878} Unimplemented User Request received: https://lib.[domain}/kobo/[api_key]/v1/analytics/gettests
[2021-05-12 18:39:56,438]  INFO {cps.kobo:138} Kobo library sync request received.
```
access.log
```
::ffff:172.18.0.1 - - [2021-05-12 18:37:39] "GET /ajax/log/1?_=1620858947720 HTTP/1.1" 200 18249 0.010934
::ffff:172.18.0.1 - - [2021-05-12 18:39:55] "GET /kobo/[api_key]/v1/initialization HTTP/1.1" 200 9027 0.016480
::ffff:172.18.0.1 - - [2021-05-12 18:39:55] "GET /kobo/[api_key]/v1/user/profile HTTP/1.1" 200 548 0.010939
::ffff:172.18.0.1 - - [2021-05-12 18:39:55] "GET /kobo/[api_key]/v1/user/loyalty/benefits HTTP/1.1" 200 548 0.010108
::ffff:172.18.0.1 - - [2021-05-12 18:39:55] "POST /kobo/[api_key]/v1/analytics/gettests HTTP/1.1" 200 548 0.010106
::ffff:172.18.0.1 - - [2021-05-12 18:39:57] "GET /kobo/[api_key]/v1/library/sync?Filter=ALL&DownloadUrlFilter=Generic,Android&PrioritizeRecentReads=true HTTP/1.1" 200 160030 0.734377
::ffff:172.18.0.1 - - [2021-05-12 18:39:57] "GET /502.html HTTP/1.1" 404 1726 0.005908
```
**Expected behavior**
The sync should sync.

**Screenshots**
![image](https://user-images.githubusercontent.com/775693/118053352-6057f780-b352-11eb-9891-553d3e7a1bfc.png)

**Environment (please complete the following information):**
 - Calibre-Web version: 0.6.11
 - Docker container: linuxserver
 - Special Hardware: x86_64, Clara HD
 - LSIO Swag reverse proxy

**Comment by serenewaffles** [comment]
I factory reset the Kobo and now everything is working great.

**Comment by YasserAntonio** [comment]
Hello i have the same issue, cloud you explain how you did it ? I reset the kobo Clara hd but I still get the sync failed message. Was your kobo up to date right after the  reset ?

**Comment by decisoft** [comment]
@YasserAntonio I had the same issue and the problem was AdGuard Home, that was blocking a Kobo's domain for updates. When I unblock that url, the sync was successful.
