### ISSUE TITLE
Set default "sort by series index" when viewing a series

### ISSUE THREAD

**Issue by haertig** [janeczku/calibre-web#1987]
**Describe the solution you'd like**
When navigating to a Series display, do a "sort by series index ascending" by default.

**Additional context**
This sort used to happen automatically with older versions of calibre-web (e.g., 0.6.8), but with version 0.6.11 books in the series are displayed in random order (this new behavior possibly started before version 0.6.11, but I didn't test other versions).  You can click one of the sort buttons at the top of the webpage to initiate a sort, but that's one click more than you had to do before when books were sorted by default.  Some kind of default sort makes sense when viewing a series, and sorting by series index makes the most sense.

**Comment by OzzieIsaacs** [comment]
The list is supposed to store the last ordering type like "sort by series index" but indeed doesn't do this

**Comment by OzzieIsaacs** [comment]
It's fixed in the newest master commit

**Comment by haertig** [comment]
Still fails to remember sort order in 0.6.17

**Comment by OzzieIsaacs** [comment]
For me it's working. Let's discuss this in the new issue
