### ISSUE TITLE
It appears book cover images are blurred

### ISSUE THREAD

**Issue by haertig** [janeczku/calibre-web#1988]
**Is your feature request related to a problem? Please describe.**
Problem: Blurred book covers are difficult to read.

**Describe the solution you'd like**
Do not blur book cover images.

**Additional context**
It appears that Calibre-Web intentionally blurs book cover images in views where multiple covers are displayed.  This blurring does not occur when looking at a single book, or if you right-click on a blurred image cover and choose "open image in a new tab".  So the cover images are not blurry in the source file, it appears that Calibre-Web is intentionally blurring them.

**Comment by OzzieIsaacs** [comment]
Calibre-web isn't doing this. My guess is that during loading of the page your browser renders the covers in a first step blurry

**Comment by haertig** [comment]
This does appear to be browser related.  Unfortunately, I broke the cardinal rule and updated two things at the same time on my computer.  I upgraded Calibre-Web from 0.6.8 to 0.6.11 and I upgraded Chromium-browser from 87 to 90.

It apparently is the browser upgrade - something in the rendering engine - that is the root of the problem.  I verified that the blurriness does not happen in Firefox browser.  And in the new version 90 of Chromium, the issue does not appear if you zoom the webpage out to 110% or higher, but at standard 100% zoom you see blurriness.

I did a little research and there have been reports over the years of Chrome browser (based on Chromium that I use) sometimes blurring images.  This seems to come and go as the browser versions change.

I apologize for falsely indicting Chromium-Web for this problem.  But maybe it's something you should be aware of if other users report blurry images.  The first question should be, "Are you using Chrome?"  Images were not blurry for me before upgrading Chromium.

**Comment by haertig** [comment]
I did find that when viewing a series in Calibre-Web (multiple book covers visible) that they are NOT blurry.  It is apparently only the main initial display "Books" where they are blurry at 100% zoom.  When looking at a series, book covers are sharp at 100%, and at 90%, and at 80% ...

So possibly there is some difference in the CSS that Calibre-Web uses for these two displays that triggers the flaw in Chromium's image rendering.  That's not Calibre-Web's fault, but it is possibly something to make note of.
