### ISSUE TITLE
Kobo api endpoint from localhost 

### ISSUE THREAD

**Issue by gwenvador** [janeczku/calibre-web#1990]
I am using a seedbox to host my calibre-web server so I don't have control over the calibre installation and server configuration. The app is a bundle (calibre and calibre-web) and access to the web server is done through a thin client (so I will appear as coming from localhost).
When I want to generate the Kobo Auth URL I have the error message:` PLease access calibre-web from non localhost to get valid api_endpoint for kobo device.` Is there a way to bypass this error or generate the API a different way? Any reason for restricting the API generation from localhost? 

**Environment (please complete the following information):**
 - OS: Linux / Seedbox 
 - Python version: python2.7
 - Calibre-Web version: 0.6.9

**Comment by OzzieIsaacs** [comment]
The problem with localhost is that you would normally get a string displayed to enter it in your kobo reader. If kobo tries to access it's localhost to sync the books this isn't working. For unexperienced users this is not obvious, therefore the string isn't shown.
So if I understand you right accessing the machine via it's hostname (e.g. desktop) isn't possible.
The only chance you have is to edit the app.db file with a sqlite browser and enter the apiendpoint data by yourself:
![grafik](https://user-images.githubusercontent.com/6438895/118862048-7ed36b00-b8dd-11eb-8f68-71c6c077a65c.png)
PLease replace id with the user id, you find in the user table, the auth_token should be a random string (normal alphanumeric characters). 
Another option would be to copy app.db file and start with this app.db another calibre-web instance which you could access via "non-localhost" so you will get the auth_token generated automatically

**Comment by gwenvador** [comment]
Thanks for your answer. I was able to setup the auth_token this way but unfortunately the kobo API is returning the book URL as 127.0.0.1 instead of the public address. So I guess the sync cannot work :(  
I will contact my seedbox host to see if there is a way to configure the web browser on a different way.

**Comment by gwenvador** [comment]
To follow up on this discussion would it be possible to configure the url_base as an option in the configuration (the same way as url_port) ?
