### ISSUE TITLE
Kybook3 sync support 

### ISSUE THREAD

**Issue by travelg** [janeczku/calibre-web#1997]
Hello please include sync books for kybook3 ios apps. 
http://kybook-reader.com/
Example project 
https://github.com/a-lagopus/KyBook3Sync

Thanks.

**Comment by OzzieIsaacs** [comment]
Looks to me like the sync option is a premium feature and only available after paying money. 
I did not find any interface description for it.
I'm sorry but I will not implement such a proprietary interface. Kybook also offers opds sync please use this feature to download books to your ios device
