### ISSUE TITLE
Google Oauth error

### ISSUE THREAD

**Issue by Kuroburn** [janeczku/calibre-web#1998]
**Describe the bug/problem**
I'm getting Internal Server Error 500 when trying to use the google icon in the login screen. I already did all the steps in the wiki and read all possible mistakes I could do but nothing seems to be my case.

**To Reproduce**
1. I installed #Gdrive and Gmail integration, #Gmail, #oauth and #Kobo integration from optional-requirements.txt 
2. I created the project in Google Cloud Platform and did the steps from wiki to setup the enviroment
3. I generated the credentials, downloaded the .json file and put everything inside  the calibre-web folder (client_secrets.json) and webapp (credentials).
4. I setup the environment variable in a **_.sh_** file inside _/etc/profile.d/_ since when rebooting the server the variable gets unseted (this is a point to emphasize on the wiki, at least from CentOS)
5. I restarted the app and rebooted the server and... when try to login... error 500.

**Logfile**
<details>
  <summary>Click here</summary>
[2021-05-26 01:22:47,766]  INFO {cps:101} Starting Calibre Web...
[2021-05-26 01:22:47,954]  INFO {cps.server:227} Starting Tornado server on :443
[2021-05-26 01:23:23,258] DEBUG {cps.web:1570} User logged out
[2021-05-26 01:23:30,825] ERROR {cps:1455} Exception on /login/google/authorized [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_dance/consumer/oauth2.py", line 267, in authorized
    **self.token_url_params,
  File "/usr/local/lib/python3.6/site-packages/requests_oauthlib/oauth2_session.py", line 360, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 421, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 431, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 461, in validate_token_parameters
    raise w
Warning: Scope has changed from "https://www.googleapis.com/auth/userinfo.email" to "https://www.googleapis.com/auth/userinfo.email openid".
</details>

**Expected behavior**
Use my work google account to login.

**Environment (please complete the following information):**
 - OS: CentOS 8
 - Python version: 3
 - Calibre-Web version: Pilar (latest)
 - Docker container: None
 - Special Hardware: None
 - Browser: Chrome & Firefox (latest)

**Additional context**
I'm trying to implement this since my work changed ISP and the new one has problems with Google's Secure LDAP Service (which was the login method I was using before)

**Comment by OzzieIsaacs** [comment]
Could you please provide the debug data (downloadable from admin section via button "Download Debug Package") You could send it to me via email, so not the whole world reads it.
2nd thing to try is change line 229 in cps/oauth_bb.py from:
`                scope=["https://www.googleapis.com/auth/userinfo.email"],`
to 
`                scope=["openid", "https://www.googleapis.com/auth/userinfo.email","https://www.googleapis.com/auth/userinfo.profile",],`

(in one line and maintain the number of spaces before the text). There is a certain chance it's working afterwards, and you may don't need to set the environment variable anymore. Would be great if you could try it out, because I need some time to set up an oauth environement with google. 

Regarding the wiki: It's what it's name states, if there is any information missing, feel free to add/change it.

**Comment by Kuroburn** [comment]
> Could you please provide the debug data (downloadable from admin section via button "Download Debug Package") You could send it to me via email, so not the whole world reads it.

Sorry, no problem I will send it to you.

> 2nd thing to try is change line 229 in cps/oauth_bb.py from:
> ` scope=["https://www.googleapis.com/auth/userinfo.email"],`
> to
> ` scope=["openid", "https://www.googleapis.com/auth/userinfo.email","https://www.googleapis.com/auth/userinfo.profile",],`
> 
> (in one line and maintain the number of spaces before the text). There is a certain chance it's working afterwards, and you may don't need to set the environment variable anymore. Would be great if you could try it out, because I need some time to set up an oauth environement with google.

**THIS!** I'm not getting the Internal Server Error 500 anymore but now, after selecting my work's account in the google's consent screen I got **Bad login, no user linked to OAuth account** (this was traslated from spanish hahahaha) in the login screen of the app.

> Regarding the wiki: It's what it's name states, if there is any information missing, feel free to add/change it.

Setting the environment variable is no needed anymore with the solution provided, but I'll keep it in mind next time.

**Comment by OzzieIsaacs** [comment]
Maybe just log in with your normal credentials and unlink/link account in the user section to make to work

**Comment by Kuroburn** [comment]
> Maybe just log in with your normal credentials and unlink/link account in the user section to make to work

Something is happening, or I don't get it... how an user can login the app? he/she must be previously registered?
I already linked my account but the rest of user should do the same?
Since LDAP was not working anymore I just did a fresh install and deleted all, so, there are no users in the application other than the administrator (me). 

By the way, from the admin panel when I click an username (e.g. mine) I get an internal server error 500 page with something like this at the end:

> {% if id not in oauth_status %}
jinja2.exceptions.UndefinedError: 'oauth_status' is undefined

I just sent you the debug package to your mail from this error.

**Comment by OzzieIsaacs** [comment]
Every user has to link the credentials to it's own account, this can't be done by an adminstrator, please link/unlink the google account in the user settings (2nd button from right with your user's name, the route with "/me"). 
I'll fix the error (this should have worked for more than 1 year)

**Comment by Kuroburn** [comment]
Thanks for the answer, already passed an email to the users to do they do the process. With this I guess the problem is solved. Thanks you very much.

**Comment by gritstub** [comment]
Hi @OzzieIsaacs 

I ran into the same 500 error when playing with OAuth.  The issue was closed, but will you commit this change to your repository?

> 2nd thing to try is change line 229 in cps/oauth_bb.py from:
> ` scope=["https://www.googleapis.com/auth/userinfo.email"],`
> to
> ` scope=["openid", "https://www.googleapis.com/auth/userinfo.email","https://www.googleapis.com/auth/userinfo.profile",],`
> 
> (in one line and maintain the number of spaces before the text). There is a certain chance it's working afterwards, and you may don't need to set the environment variable anymore. Would be great if you could try it out, because I need some time to set up an oauth environement with google.

**Comment by kkoshelev** [comment]
Users see - "No User Linked With OAuth Account" error.

I understand it's a "feature", but can you make users not to require to "LINK" their OAuth account? Me as an admin would require send a password and somewhat complicated instructions to a user just to make them login. I couldn't figure out for 30 min on how to fix that myself, TBO.

**Comment by maeries** [comment]
I'm running into the same issue with the "No User Linked With OAuth Account". I'm using google oauth btw. Can it be done in a way that a new account is created when there is no account linked? I mean creating an account for every user kinda defeats the purpose of sso
