### ISSUE TITLE
Book description html is broken

### ISSUE THREAD

**Issue by xor-gate** [janeczku/calibre-web#2]
Hi,

In the webview the html is stripped and all text is appended after each other. It looks like there
is something wrong with loading/displaying the description in the webui.

<img width="691" alt="screen shot 2015-10-11 at 12 49 47" src="https://cloud.githubusercontent.com/assets/1050166/10416410/9a846112-7016-11e5-8657-d7332e75ab38.png">
<img width="911" alt="screen shot 2015-10-11 at 12 49 37" src="https://cloud.githubusercontent.com/assets/1050166/10416413/9f940bee-7016-11e5-9a3e-5ee3ebd087a6.png">

**Comment by janeczku** [comment]
Thanks for reporting. HTML tags should now be rendered in the description. Please test.

**Comment by xor-gate** [comment]
Awesome, it works now as expected! Thanks for fixing.

<img width="856" alt="screen shot 2015-10-11 at 21 46 56" src="https://cloud.githubusercontent.com/assets/1050166/10418651/adb5be0c-7061-11e5-9787-d90c6eb71831.png">
