### ISSUE TITLE
Question on Author sort by series

### ISSUE THREAD

**Issue by Minstrel27** [janeczku/calibre-web#2001]
I've been using Calibre-web for a little while now and for the most part think it's quite good.   I have a question regarding how books are sorted for display.

I know that from the main page I can select from different sort parameters.    Choosing the Author sort does that but books seem to be displayed in a random order within that.  I would like to be able to sort by series / series index within the author but can't find a way to do that.   I can sort by series index if I view a series but would prefer if it was the possible to do it as the default author sort.

Is there a setting somewhere that controls this?  I've looked in the app and multiple online forums and can't find any reference to that.

Thanks.

**Comment by OzzieIsaacs** [comment]
I'm not sure if I get it. You 'd like to see on the books selection after selecting autors all books sorted according to authors and then as second ordering rule, getting authors books grouped by series and then sorted according to series_index?

![grafik](https://user-images.githubusercontent.com/6438895/125193012-b231d680-e24a-11eb-9818-0a850bdf1d2a.png)

**Comment by Minstrel27** [comment]
Yes, that's correct.

**Comment by OzzieIsaacs** [comment]
the feature is implemented in the newest nightly version.

**Comment by Minstrel27** [comment]
Thank you!
