### ISSUE TITLE
Safari download icon broken in Caliblur! theme

### ISSUE THREAD

**Issue by jimshea** [janeczku/calibre-web#2003]
**Describe the bug/problem**
Download dropdown icon no longer works for Safari desktop and IOS in CaliBlur! theme, 
User dropdown does not work correctly (must scroll with mouse to see about and logout) - inconvenience 

**Download works with light theme and chrome based browsers**
User dropdown broken all browesrs 

**To Reproduce**
1. Go to book with Safari browser
2. Click on download icon

**Expected behavior**
Able to download in Safari desktop and IOS 

**Screenshots**

**Environment (please complete the following information):**
 - Calibre-Web version: 0.6.12 - 54d06e580d73ba58274e7ed4efbd8fc94b7e1856
 - Docker container: Linuxserver.io version:- v5.19.0-ls114 Build-date:- 2021-05-28T04:16:43+01:00
 - Browser: Safari 14.1

**Additional context**
I have two instances of CW that used to work on 6.11/Caliblur! and now both can't download with Safari

**Comment by somel-web** [comment]
got this error in safari (not chrome/firefox desktop)
```
[Error] TypeError: undefined is not an object (evaluating '$("#add-to-shelf").offset().top')
	dropdownToggle (caliBlur.js:416)
	Code général (caliBlur.js:276)
```

**Comment by lukehankins** [comment]
Confirmed that switching back to the default theme fixed the issue.

**Comment by somel-web** [comment]
Adding a shelf remove the javascript error in safari. 
But still no dropdown for "download" or "view".

Viewing the rendered html code there is a difference  chrome vs safari
For example the 'download' dropdown render like this in **chrome**
`<ul class="dropdown-menu leramslist" aria-labelledby="btnGroupDrop1" style="right: auto; top: 60px; left: 1307px !important; display: block;">`
and like this in **safari**
`<ul class="dropdown-menu leramslist offscreen" aria-labelledby="btnGroupDrop1" style="display: block;">`
manualy editing the top attribute to the style bring back the menu.

**Comment by OzzieIsaacs** [comment]
The difference could be caused by the js error, the caliblur Theme rewrittes a lot of the html, this could be stopped because of the error

**Comment by OzzieIsaacs** [comment]
I try to have a look at it

**Comment by OzzieIsaacs** [comment]
I don't have a macOS to my hands, so I did some code reading, I think I found something related to the error message. Could you please try to update to the newest nightly version and try again (I give it a 30% change of working now).

If not please check the error message again if it's changed.

**Comment by somel-web** [comment]
It WORKS !!
(just replacing the caliblur.js file in the actual 0.6.12 released version)
- safari mac os desktop  -> ok 
- safari ios -> ok 
- chrome ios -> (chrome ios had the same bug)
Thanks :)

**Comment by OzzieIsaacs** [comment]
Cool
