### ISSUE TITLE
Broken icons in Safari PDF viewer

### ISSUE THREAD

**Issue by csdbz** [janeczku/calibre-web#2004]
Any ideas on why Chrome is rendering PDF viewer buttons but Safari isn't?

<img width="800" alt="Screen Shot 2021-05-30 at 7 04 03 PM" src="https://user-images.githubusercontent.com/85088085/120130087-338d4800-c17a-11eb-9171-8b1cebfbe6cd.png">

**Comment by OzzieIsaacs** [comment]
Have no idea, but it's also not working on iOS. Is there any error message in the developer/javascript console (don't know how it's called in safari).

**Comment by somel-web** [comment]
Here is the problem:
in chrome the url of svg are like this (-> ok)
`https://xyz.com/static/css/libs/images/toolbarButton-viewThumbnail.svg`
but in safari it's incorrect
`https://xyz.com/read/446/images/toolbarButton-viewThumbnail.svg`

`/static/css/libs/` is replaced by `/read/id_of_book`

**Comment by OzzieIsaacs** [comment]
I doublechecked it. The old version of the reader (with the black background by default) worked well, the new one (the white background creates the problem). I tried updating to the newest version of pdf.js, but the problem still persists. I currently haven't figured out, why safari is having the problem, from my understanding Chrome, Firefox behalf correct. 
There is one css file linking to the graphics. The standards say the root of the links shall be the location of the css file, safari takes the page where it's loaded from as it's root, this is the problem.
I did not find a solution to change the path to something which will work for Chrome, Firefox and Safari, and will also work for reverse proxy configurations.

**Comment by OzzieIsaacs** [comment]
Please update to the newest nightly version. For me it was working now

**Comment by somel-web** [comment]
Maybe this can help 
[](https://github.com/mozilla/pdf.js/issues/12942)
The problem seems related to webkit (used is safari mac desktop and ALL browsers in IOS (safari/chrome/firefox…)

**Comment by somel-web** [comment]
IT WORKS !!
Just tested on ios but should be ok on safari mac desktop

**Comment by OzzieIsaacs** [comment]
Awesome. Thanks for finding the issue on the pdf.js. No help to expect from their side. I‘ll make a note on how to change the sources for the next pdf reader update

**Comment by somel-web** [comment]
Annother issue about webkit and pdf.js viewer css problems
https://github.com/mozilla/pdf.js/issues/6685
One solution is to use a css filter like
```
@media all -webkit-device-pixel-ratio {….}
@media not -webkit-device-pixel-ratio {….}
```
https://stackoverflow.com/questions/15401375/css-media-check-if-not-webkit

**Comment by OzzieIsaacs** [comment]
The issue you are pointing to is claimed to be solved. Do you still have this problem?

**Comment by somel-web** [comment]
No it’s working, thanks a lot.
I didn’t want to reopen the issue but just leave a comment that could help for future debugging.

**Comment by OzzieIsaacs** [comment]
![17DC6FA4-88C8-4126-89A6-900332EB6194](https://user-images.githubusercontent.com/6438895/120887815-46c66a80-c5f5-11eb-86c6-00c57e25a383.jpeg)
To me the icons seem sharp
