### ISSUE TITLE
Define timings for thumbnail generation

### ISSUE THREAD

**Issue by CWempe** [janeczku/calibre-web#2006]
I just stumbled upon [this PR](https://github.com/janeczku/calibre-web/pull/1771).
Sounds like a great idea.

**Please let the user define the timings/intervals.**

I do not need it to look for missing images every 5 minutes. Once per day or week would be enough for me.
Maybe let the user define a specific time instead of an interval?
And the `expire time` could even be a couple of month, in my opinion.

My main concern is that my HDD would not go into standby when calibre-web is scanning for thumbnails all the time. 😄 

Just my 2 cents as a casual user.
I barely use calibre-web as you might have guessed. 😉

**Comment by mmonkey** [comment]
The latest update to the PR address this.

**Comment by OzzieIsaacs** [comment]
The PR is merged:
- Please update to the newest nightly version
- Install APScheduler via pip
- Restart Calibre-Web
- Go into admin section enter edit schedule task settings, enable "Generate Book Cover Thumbnails", change the regular update time if you want (only needed for sideloaded books via Calibre), save setting
- go to admin section Click on Refresh Cover Thumbnnail cache
- Check Tasks section and wait some minutes until all thumbnails are generated

Enjoy
