### ISSUE TITLE
Add md5 or sha256 of metadata.db books tables

### ISSUE THREAD

**Issue by jrespeto** [janeczku/calibre-web#2007]
**Is your feature request related to a problem? Please describe.**
Yes a person one. :) - I  sometimes I upload 2 or more copies of the same book and If the md5sum or sha256sum was calculated and check before saving the book it could help prevent duplicate books from being added. 

**Describe the solution you'd like**
When uploading new files. add the md5 or sha256 to the book table  
Add a page to show when there are duplicate entries.  

**Describe alternatives you've considered**
When uploading new files if the md5 or sha256 of the book exits in the book table. skip it and flash a message :) 

**Additional context**
On the update for this all book need the md5 add to the table. Need a command or run through all file in the book table to add the md5 or sha256.

**Comment by OzzieIsaacs** [comment]
I understand your request, but calibre-web is based on the calibre database itself, and this database has no such column, so I can't add this. 
Calibre itself somehow handles a duplicate check, I don't know how and haven't tried to find it out by now.
Calibre-Web has a basic dublicate check based on author name and title.

**Comment by lfmunoz** [comment]
@OzzieIsaacs duplicate check based on author and name and title is bad, doesn't work, how hard would it be to do add md5 check support?
