### ISSUE TITLE
Custom logout URL

### ISSUE THREAD

**Issue by Killerhaschen** [janeczku/calibre-web#2008]
**Does your feature request relate to a problem? Please describe it.
The problem is that when a user is authenticated through a reverse proxy, the logout button stops working.

**Describe the solution you would like to have**.
It would be nice to have a field where the admin can specify a URL that will be called when the logout button is clicked.

**Describe the alternatives you have considered**.
This would be better than the alternative of setting up a redirect on the proxy that redirects a user from calibre-web's logout page to the proxy's logout page.

**Comment by OzzieIsaacs** [comment]
... authenticated through a reverse proxy, the logout button stops working.
That's true. My expectation how it works would be the reverse proxy in this case handles the login/logout stuff. As long as the proxy sends valid credentials the user gets logged in, once logged in you have a valid session token and it's no longer necessary to provide the login header from the proxy.
My hobby is programming a ebook library and not an admin tool. I stated in the contribution tools that I'd like to focus more on the calibre-web core functions (https://github.com/janeczku/calibre-web/blob/master/CONTRIBUTING.md#feature-request). So I'm sorry I will not implement it, please help yourself by somehow handle it in the reverse proxy.

**Comment by Killerhaschen** [comment]
Thy. Just wanted to knew how to do it.
My working solution is now for authelia and nginx.

  location /logout {
    rewrite ^ https://authelia.domain.tld/logout permanent;
    include proxy.conf;
  }

Maybe this would be something for the Wiki:
https://github.com/janeczku/calibre-web/wiki/Setup-Reverse-Proxy
At the end of the Login via Header from Upstream Authentication Source block you could append:
```
If using a reverse proxy the logut button will not work. You have to redirect the logout request in your reverse proxy.
```
Maybe with a short example. Then other users will find the information at the expected place.

Thy for this aweseome project.
