### ISSUE TITLE
Can't save metadata when Calibre Web is running in a Docker container on a Nas whose books are mounted via CIFS share.

### ISSUE THREAD

**Issue by D1skanime** [janeczku/calibre-web#2010]
[2021-06-04 17:10:00,843]  INFO {cps.server:205} Starting Gevent server on [::]:8083
[2021-06-04 17:16:32,521] ERROR {cps.editbooks:56} (sqlite3.OperationalError) database is locked
(Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by Daniel15** [comment]
I don't think SQLite likes databases stored on SMB/CIFS shares. Could you try NFS instead?

**Comment by OzzieIsaacs** [comment]
Please follow the procedures described in #2062. If you still have problems, please contact the maintainer of the docker container, as this looks to me like docker problem.
