### ISSUE TITLE
bitjs.archive.Unzipper can not extra image file

### ISSUE THREAD

**Issue by hirorogithub** [janeczku/calibre-web#2012]
**Describe the bug/problem**
When I open my comic with cbz (which zipped by my golang script) format on web, the show api can return the cbz file. But the js seem`s can not really unzip then File.
However, when I re zip the comic with 7z, it seem`s every thing work well

**To Reproduce**
the core golang code I zip my comic:
```
func Zip(waitGroup *sync.WaitGroup, srcDir string, zipFileName string) {
	fmt.Println("start",zipFileName)
	// 创建：zip文件
	zipfile, _ := os.Create(zipFileName)
	defer zipfile.Close()

	// 打开：zip文件
	archive := zip.NewWriter(zipfile)
	defer archive.Close()

	// 遍历路径信息
	err := filepath.Walk(srcDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			panic(err)
		}
		// 如果是源路径，提前进行下一个遍历
		if path == srcDir {
			return nil
		}

		// 获取：文件头信息
		header, _ := zip.FileInfoHeader(info)
		header.Name = strings.TrimPrefix(path, srcDir+`\`)

		// 判断：文件是不是文件夹
		if info.IsDir() {
			header.Name += `/`
		} else {
			// 设置：zip的文件压缩算法
			header.Method = zip.Deflate
		}

		// 创建：压缩包头部信息
		writer, _ := archive.CreateHeader(header)
		if !info.IsDir() {
			file, _ := os.Open(path)
			defer file.Close()
			io.Copy(writer, file)
		}
		return nil
	})
	if err != nil {
		panic(err)
	}
	fmt.Println("done---", zipFileName)
	waitGroup.Done()
}
```
 When I open the comic on calibre-web , EXTRACT message not happen, I think this is the reason why I can not read the comit.
However, when I add error message handler, no error happened 
![image](https://user-images.githubusercontent.com/15611407/120877216-e0871b00-c5e7-11eb-84ca-377b780aded7.png)

**Environment (please complete the following information):**
I run my calibre-web on syncology Nas with docker [https://github.com/Technosoft2000/docker-calibre-web](https://github.com/Technosoft2000/docker-calibre-web)

**Comment by OzzieIsaacs** [comment]
As the comic viewer backend was constantly producing problems, e.g. no support for rar5 archives. I replaced it in the newest beta version with something else. I think the error should be gone away with this change (and it's much faster). I'm not sure if there is a beta channel available on the technosoft2000 docker, if yes, please try it.

**Comment by hirorogithub** [comment]
Oh, I can load image!!
thx a lot
(sorry for pool level of English
