### ISSUE TITLE
Shelf inaccessible after loosing all books

### ISSUE THREAD

**Issue by simkin** [janeczku/calibre-web#202]
Although I have rebuild parts of my library I see the following error when accessing one of the public shelfs (likely the books that the shelf used to contain are no longer available):

> [2017-06-07 20:26:29,435] {/usr/local/lib/python2.7/dist-packages/flask/app.py:1560} ERROR - Exception on /shelf/2 [GET]
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
>     return func(*args, **kwargs)
>   File "/opt/calibre-web1/cps/web.py", line 1986, in show_shelf
>     shelf=shelf)
>   File "/opt/calibre-web1/cps/web.py", line 559, in render_title_template
>     return render_template(instance=config.config_calibre_web_title, *args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
>     context, ctx.app)
>   File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
>     rv = template.render(context)
>   File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
>     return self.environment.handle_exception(exc_info, True)
>   File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/opt/calibre-web1/cps/templates/shelf.html", line 1, in top-level template code
>     {% extends "layout.html" %}
>   File "/opt/calibre-web1/cps/templates/layout.html", line 168, in top-level template code
>     {% block body %}{% endblock %}
>   File "/opt/calibre-web1/cps/templates/shelf.html", line 25, in block "body"
>     <p class="author"><a href="{{url_for('author', book_id=entry.authors[0].id) }}">{{entry.authors[0].name}}</a></p>
>   File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 411, in getitem
>     return obj[argument]
> UndefinedError: 'None' has no attribute 'authors'

Another shelf is working but contains different books. Guess the book IDs are not unique and driven by the order in the DB?

**Comment by OzzieIsaacs** [comment]
the order in the db depends on the order you add the books to the calibre-db. problem is sure related to non existinf books i'll check and fix

**Comment by OzzieIsaacs** [comment]
I don't know why this happes, but should be fixed now, please try

**Comment by perler** [comment]
yep, works again
