### ISSUE TITLE
Book Cover doesn't update after fetching metadata with default calibre-web settings

### ISSUE THREAD

**Issue by fivestones** [janeczku/calibre-web#2024]
**Describe the bug/problem**
After a clean install of calibre-web v. 0.6.12, if you attempt to fetch metadata for a book that has no cover, while the cover shows up in the edit metadata screen, after clicking save, there will be no cover, as before. The rest of the metadata updates properly.

I figured out how to make it work (based on the comments here: https://github.com/janeczku/calibre-web/issues/1836): I had to enable uploading in the admin area. Subsequently the cover updates after fetching metadata.

**To Reproduce**
1. Search for a book without a cover
2. Click on 'edit metadata'.
3. Click on 'fetch metadata'.
4. Perform metadata search and choose a result with a book cover image
5. The image will show up in the proper place in the edit book screen.
6. Click 'save'.
7. The book cover is missing.

**Expected behavior**
I would expect the book cover to update with the default settings to calibre-web. This is especially perplexing as a user given that the cover shows up in the edit book screen before you click save. At the very least, there should be some kind of notification (e.g. "Since uploading is turned off, no cover updates will be done. Change uploading settings in admin if you want the cover to update to this image you have picked.")

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10/Raspberry Pi OS] Raspberry Pi OS
 - Python version: [e.g. python2.7] ?
 - Calibre-Web version: [e.g. 0.6.8 or 087c4c59 (git rev-parse --short HEAD)]: 0.6.12 
 - Docker container: [None/Technosoft2000/LinuxServer]: Linuxserver
 - Special Hardware: [e.g. Rasperry Pi Zero] RPi 4
 - Browser: [e.g. Chrome 83.0.4103.97, Safari 13.3.7, Firefox 68.0.1 ESR] Firefox

**Additional context**
Thanks!

**Comment by tamet83** [comment]
I have similar problem. I can’t update book metadata. Each time the system gives me “Search Error!!”
This is my log:

`

[2021-06-19 11:27:36,670] ERROR {cps:1892} Exception on /scholarsearch/Vecchie+conoscenze [GET]
Traceback (most recent call last):
  File "/root/calibre-web/vendor/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/calibre-web/vendor/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/root/calibre-web/vendor/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/root/calibre-web/vendor/flask/app.py", line 2131, in make_response
    " {rv.__class__.__name__}.".format(rv=rv)
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a list.

`
I have latest version of calibre-we

**Comment by OzzieIsaacs** [comment]
The problem was related to each other. I fixed it in the newest master commit
