### ISSUE TITLE
LDAP import doesn't support users with dot

### ISSUE THREAD

**Issue by aleksandrmetik** [janeczku/calibre-web#2029]
When we tried to import users from LDAP, only users without a dot in UID were imported successfully.

1. Install FreeIPA (LDAP)
2. Create any users in IPA with dot, for example aleksandr.metik and test
3. Create service.calibre group in LDAP and add users (aleksandr.metik and test)
4. Configure LDAP on Calibra side
Login Type: Use LDAP Auth
LDAP server: <freeipa IP>
Ldap server port: 389 (for example)
LDAP Encyption: None
LDAP Auth: Simple
LDAP Administrator Username: uid=aleksandr.metik,cn=users,cn=accounts,dc=<domain>,dc=<domain1>
LDAP Administrator Password: <ipa/ldap password>
LDAP Distinguished Name (DN): dc=<domain>,dc=<domain1>
LDAP User Object Filter: (uid=%s)
LDAP Server is OpenLDAP? Yes
LDAP Group Object Filter: (&(objectclass=groupofnames)(cn=%s))
LDAP Group Name: service.calibre
LDAP Group Members Field: member
LDAP Member User Filter Detection: Custom Filter
LDAP Member User Filter: uid=%s
5. Click "Import LDAPs users"
6. See error  "At Least One LDAP User Not Found in Database"
In log file:  [2021-06-16 15:12:59,893]  WARN {cps.admin:1749} LDAP User: uid=aleksandr.metik,cn=users,cn=accounts,dc=<masked>,dc=<masked> Not Found
7. User "test" Succesful imported (But, without email #2030)

**Logfile**
[2021-06-16 15:12:59,893]  WARN {cps.admin:1749} LDAP User: uid=aleksandr.metik,cn=users,cn=accounts,dc=<masked>,dc=<masked> Not Found

**Expected behavior**
Users with dot in username should be imported too

**Screenshots**
![image](https://user-images.githubusercontent.com/23119755/122247321-ef1adf80-cecf-11eb-9935-8b842d777a38.png)
![image](https://user-images.githubusercontent.com/23119755/122247177-d8748880-cecf-11eb-8b3c-e03214c2a72f.png)

**Environment (please complete the following information):**
 - OS: Linux 5.4.0-74-generic \#83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64
 - Python version: 3.8.5 (default, May 27 2021, 13:30:53) [GCC 9.3.0]
 - Calibre-Web version: 0.6.13 Beta - e6e3032f02aac0d5ae02b9c015dd98d13df28dd3 - 2021-06-12T08:52:14+02:00
 and 
 - Calibre-Web version: 0.6.12 is reproduced too

**Comment by OzzieIsaacs** [comment]
This isn't supported yet.
https://github.com/janeczku/calibre-web/blob/e6e3032f02aac0d5ae02b9c015dd98d13df28dd3/cps/admin.py#L1792
Should contain a dot: ([\d\s\w-\\.]+)
