### ISSUE TITLE
[Enhancement] Create shelf from tags

### ISSUE THREAD

**Issue by gabriellluz** [janeczku/calibre-web#203]
Hi, I'd like to be able to also create a shelf using tags. That way we don't have to add books all the time.

**Comment by OzzieIsaacs** [comment]
As a 50% solution: Some time ago I wrote a script for mass adding books to shelfs: You could try it:
https://github.com/OzzieIsaacs/cps-shelf-adder

**Comment by OzzieIsaacs** [comment]
If you have at least one bookshelf you can now add all books of a search request (on the search result page) to a shelf at once.  (You can search for tags, categories or whatever you want in the advanced search section)
