### ISSUE TITLE
LDAP import - doesn't import mail attribute from FreeIPA LDAP

### ISSUE THREAD

**Issue by aleksandrmetik** [janeczku/calibre-web#2030]
When we tried to import users from LDAP, we can't change the mail attribute.
**In freeIPA: User Email Attribute is "mail"**

Install FreeIPA (LDAP)
Create any users in IPA for example "test" with mail test@example.com
Create service.calibre group in LDAP and add user "test"
Configure LDAP on Calibra side
Login Type: Use LDAP Auth
LDAP server:
Ldap server port: 389 (for example)
LDAP Encyption: None
LDAP Auth: Simple
LDAP Administrator Username: uid=<admin name>,cn=users,cn=accounts,dc=<domain>,dc=<domain>
LDAP Administrator Password: <ipa/ldap password>
LDAP Distinguished Name (DN): dc=<domain>,dc=<domain>
LDAP User Object Filter: (uid=%s)
LDAP Server is OpenLDAP? Yes
LDAP Group Object Filter: (&(objectclass=groupofnames)(cn=%s))
LDAP Group Name: service.calibre
LDAP Group Members Field: member
LDAP Member User Filter Detection: Custom Filter
LDAP Member User Filter: uid=%s
Click "Import LDAPs users"

![image](https://user-images.githubusercontent.com/23119755/122248728-f2fb3180-ced0-11eb-94c8-175ee4f330fe.png)
![image](https://user-images.githubusercontent.com/23119755/122248793-027a7a80-ced1-11eb-811f-88e265435d42.png)

User "test" Succesful imported (But, without email)

Logfile
[2021-06-16 15:29:32,822] DEBUG {cps.admin:1673} No Mail Field Found in LDAP Response

Expected behavior
I would like to see a way to change the expected email parameter from LDAP by GUI.

Workaround:
Change the requested attribute of the email field for LDAP sync in the code.

**Comment by OzzieIsaacs** [comment]
In my tests I'm using also **mail** as attribute for the email. 
You can have a look at the device trees I'm using for testing. 
https://github.com/OzzieIsaacs/calibre-web-test/blob/master/test/helper_ldap.py

It would be great if you could provide a similar example for your usecase. I'm not the LDAP guru and it costs me days to get this stuff working for a normal "OpenLDAP" installation. So I'd like to avoid creating a setup with your Server programm

**Comment by OzzieIsaacs** [comment]
No feedback
