### ISSUE TITLE
Bookdetails not shown on ereader

### ISSUE THREAD

**Issue by Gagalari** [janeczku/calibre-web#2034]
On Tolino ereader book details are not shown. On other deviceses like laptop, handy, pads there is no problem, just on all tolino ereaders (i dont have other ereaders). The version i have installed is 0.6.12. the book covers are sometimes not shown, maybe this gives a hint (also only on ereaders). The random books in the top never shown the covers (also only on ereaders)

**Comment by amigueldiez** [comment]
With the Kobo ebook browser I have also found the problem. I don't know if it's related to that calibre-web is expose on a different port than 80.

**Comment by OzzieIsaacs** [comment]
This is a known limitation on ebook readers

**Comment by Gagalari** [comment]
No this was running on version 0.6.9.

**Comment by Gymnae** [comment]
This bug also affects me

**Comment by OzzieIsaacs** [comment]
In the newest version (0.6.18) of Calibre-Web, e-readers are detected based on there request headers and the book details page is displayed as before as a normal page and therefore should work again
