### ISSUE TITLE
File with .CBR uppercase file extension is not uploaded

### ISSUE THREAD

**Issue by gritstub** [janeczku/calibre-web#2038]
**Describe the bug/problem**
File with .CBR uppercase file extension is not uploaded

**To Reproduce**
1. Click and drag a file with .CBR extension (uppercase) into the browser to upload it (eg: Test.CBR)

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

**Expected behavior**
File uploading dialog with progress bar is shown

**Actual behavior**
Nothing happens

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python version: python3.8
 - Calibre-Web version: 0.6.12
 - Docker container: LinuxServer
 - Special Hardware: None
 - Browser: Chrome/91.0.4472.101

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

**Comment by wgibcus** [comment]
I can confirm the error "test - Unknown' failed with error: [Errno 2] No such file or directory" It appears as if calibre-web does not handle upper case file extensions, even when added to the allowed upload list. 

My advice would be to use a batch file renamer to rename all the upper case extensions to lower case before uploading.

**Comment by OzzieIsaacs** [comment]
It's fixed in the newest master commit, please try to update to nightly version (if possible in the docker container)

**Comment by gritstub** [comment]
Thanks for the fix!
