### ISSUE TITLE
Download not working on Duokan / Alfa

### ISSUE THREAD

**Issue by gabriellluz** [janeczku/calibre-web#204]
Hi. I'm using an alternative firmware called Duokan. It's used for both kindle paperwhite devices and some chinese devices. When I click on Download, I don't have an option for a book format. Probably because it has an experimental browser. Maybe an option to display book formats instead of Download button. It also happens on Brazilian device Alfa, which was one of the most used e-ink book readers and also the first sold in Brazil.

**Comment by OzzieIsaacs** [comment]
Please try the newest version.

**Comment by OzzieIsaacs** [comment]
No response for long time

**Comment by gabriellluz** [comment]
Hi. The newest version didn't work, too. It turns out it's actually a problem with the FW, not Calibre-web. I forgot to mention it. Thx.
