### ISSUE TITLE
"fetch metadata" update could append to the existing tags instead or replacing them

### ISSUE THREAD

**Issue by wil70** [janeczku/calibre-web#2045]
Exiting Tags are being replaced when I use "fetch metadata" update

It takes some time to add "tags" in Calibre, then as we "fetch metadata" for books the tags are being wiped out and replaced by the new one. I would love to have the default option to "append" the tags so I can for instance add more precise tags or add words from another language etc..

Note: tags append by default on Calibre, it doesn't wipe them the previous one.
Note: most of the metadata (like identifier or series...) stays intact or even append already on calib-web but not for tags

For instance I might have add "Trading, bourse" (with foreign words) but when I fetch the meta data, I see "business and finance" which is not as precise, what I would like it  "Trading, bourse, business and finance"

I would like some user to be able to help and fetch the metadata but as of now I can' do it as by default it wipe out the existing one.

Thank you for your help!

**Comment by OzzieIsaacs** [comment]
I'm currently working on the feth metadata function to fetch the data from the backend, I will change it according to your suggestion (or make it selectable)

**Comment by wil70** [comment]
Super - thanks!
    On Thursday, July 8, 2021, 04:46:50 AM PDT, Ozzie Isaacs ***@***.***> wrote:  
 
 


I'm currently working on the feth metadata function to fetch the data from the backend, I will change it according to your suggestion (or make it selectable)
