### ISSUE TITLE
Show book title instead of "Read a book" in comic book reader

### ISSUE THREAD

**Issue by gritstub** [janeczku/calibre-web#2048]
**Is your feature request related to a problem? Please describe.**
When viewing a book in the comic book reader, the title shows "Read a book".  The HTML looks like
```
<div id="metainfo">
  <span id="book-title">Read a Book</span>
  <span id="title-seperator">&nbsp;&nbsp;–&nbsp;&nbsp;</span>
  <span id="chapter-title"></span>
</div>
```

**Describe the solution you'd like**
Show the Title of the book + Series + Series # instead of a generic string

**Additional context**
Is the code is looking for metadata inside the file?  Could this be passed on from the library metadata?

`calibre-web/cps/templates/readcbr.html`
```
<div id="metainfo">
  <span id="book-title">{{ title | shortentitle }}</span>
  <span id="title-seperator">&nbsp;&nbsp;–&nbsp;&nbsp;</span>
  <span id="chapter-title"></span>
</div>
```

**Comment by gritstub** [comment]
How about adding the title to the <title> tag as well, instead of generic "Comic Reader" ?

`calibre-web/cps/templates/readcbr.html`
```
<title>Comic Reader</title>
```

**Comment by OzzieIsaacs** [comment]
Is the code is looking for metadata inside the file?  No
Could this be passed on from the library metadata? Yes, I changed it that way. Please update to the newest nightly version to see the result

**Comment by gritstub** [comment]
Excellent, thank you!  I noticed a new bug since switching to nightly and reported it.
