### ISSUE TITLE
python cps.py fail on Windows 10 

### ISSUE THREAD

**Issue by candidodmv** [janeczku/calibre-web#205]
OSError: [WinError 10013] Foi feita uma tentativa de acesso a um soquete de uma maneira que é proibida pelas permissões de acesso

**Comment by OzzieIsaacs** [comment]
Could you please check the hints in #180? 
The port is blocked by another program (apache?, IIS?).

**Comment by gabriellluz** [comment]
Eu uso Windows 10 e funciona perfeitamente. Quais os passos que você executou? / I use Windows 10 and it works perfectly. Which steps you've taken?

**Comment by OzzieIsaacs** [comment]
Are there any news on this, otherwise I would close it.

**Comment by gabriellluz** [comment]
Works for me. I think a clean install of Windows 10 would solve the problem. But I can't reproduce the problem described by the op.

**Comment by gabriellluz** [comment]
You can close.
