### ISSUE TITLE
Kepub conversion fails with error "unknown shorthand flag: 'o' in -o"

### ISSUE THREAD

**Issue by aniqueta** [janeczku/calibre-web#2051]
**Describe the bug/problem**
Kepubify has been failing and looking at the debug log, it looks like v3.1.6 and v4.0.0 of the kepubify tool do not have an -o flag? See error in title and log below I tried to test kepubify-ing manually from the CLI using the comand construction in the Python script, and got the same error. 

**To Reproduce**
1. Setup kepubify binary
2. Add new book
3. Sync Kobo devince
4. See error in task list and logs

**Logfile**
Example log, same in every case:
````
INFO {cps.tasks.convert:102} Book id 113 - target format of .kepub does not exist. Moving forward with convert.
DEBUG {cps.tasks.convert:160} unknown shorthand flag: 'o' in -o
INFO {cps.tasks.convert:140} ebook converter failed with error while converting book
````

**Expected behavior**
Successful kepub conversion

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: macOS 
 - Python version: Python 3.9.6
 - Calibre-Web version: 0.6.12
 - Docker container: N/A
 - Special Hardware: Mac? But don't think that's the reason here.
 - Browser: N/A

**Additional context**
N/A

**Comment by OzzieIsaacs** [comment]
The manual still states the -o flag, maybe a „“ is missing around the folder and filename 
https://pgaskin.net/kepubify/docs/

**Comment by OzzieIsaacs** [comment]
Checked it on windows, linux and finally on macos:
![grafik](https://user-images.githubusercontent.com/6438895/125187338-73daee00-e22f-11eb-992e-ae380c4829b7.png)
![grafik](https://user-images.githubusercontent.com/6438895/125187347-7f2e1980-e22f-11eb-9e23-074a3bc4e2f9.png)

Worked without a problem.
Are you sure you downloaded the right program? Calibre-web can't check if the executable is really kepubify and nothing else? Could you please tell me which exact commandline with arguments you used which also lead to the error?

**Comment by aniqueta** [comment]
@OzzieIsaacs I was using the wrong executable from the linked kepubify releases page. Didn't see the other releases further down on my screen. What a dumb mistake and so sorry for the trouble.
