### ISSUE TITLE
Cover on opds catalog

### ISSUE THREAD

**Issue by burghy86** [janeczku/calibre-web#2059]
**Describe the bug/problem**
When use opds catalog on moon reader or aldiko app the cover of book are white. Is normal?  

In normal web app the cover work correct

**Screenshots**
![Screenshot_20210715-223248_Moon Reader](https://user-images.githubusercontent.com/17832100/125853981-8e0d72a7-7d74-41ec-9d0a-af734f1139d6.jpg)
![Screenshot_20210715-223335_Moon Reader](https://user-images.githubusercontent.com/17832100/125853988-2603bad7-a1cf-4617-8127-ab456fcfd7cd.jpg)

**Comment by Thovi98** [comment]
Did you enable the anonymous browsing ?

In the wiki, there is said :

> moon+ on Android (Cover pictures are only displayed with anonymous browsing enabled, tested with v4.5.7)

**Comment by burghy86** [comment]
Ops. I not see this wiki. Sorry. Close
