### ISSUE TITLE
metadata.db An error occurred while the file was too large

### ISSUE THREAD

**Issue by a1023456** [janeczku/calibre-web#206]
metadata.db An error occurred while the file was too large，I put about 1000 books。

**Comment by OzzieIsaacs** [comment]
Could you please describe what error occoured and what you exactly did? Could you please paste the contents of the calibre-web.log file (part where the error occoured). Thanks

**Comment by a1023456** [comment]
The problem has been resolved, and the database file calibre has been re restored through metadata.db.

Thank
