### ISSUE TITLE
Washed Out Text in Web Reader

### ISSUE THREAD

**Issue by UnPossible-Me** [janeczku/calibre-web#2060]
Initially this was just an extension to Issue [1983](https://github.com/janeczku/calibre-web/issues/1983). Until I realized what the actual web reader looked like:

This is how books look in the calibre app on my desktop:
![Screenshot from 2021-07-17 08-22-54](https://user-images.githubusercontent.com/71452014/126023431-812a9d08-c28b-4ce5-81b7-8c515960df34.png)

This is how they _should_ look in the calibre-web web reader right?:
![Screenshot from 2021-07-17 08-24-07](https://user-images.githubusercontent.com/71452014/126023454-39a8f30e-b26d-46a4-94ef-8e7e71744258.png)

Unfortunately this is how they actually look:
![Screenshot from 2021-07-17 08-24-37](https://user-images.githubusercontent.com/71452014/126023470-8692035b-e00e-47c2-a298-6fe9e7753f1e.png)

**To Reproduce**
1. Open any book
2. Flip though a couple pages, or zoom in and out, some sort of action.
3. Boom, text goes invisible.

**Logfile**
Nothing in the logs.

**Expected behavior:**
It should stay as shown in the second picture, not shift to the washed out text

**Environment:**
 - OS: Raspbian (Debian 10) for server, ZorinOS 15.3 on client
 - Python 3.7
 - Calibre-Web v0.6.12
 - Special Hardware: Pi 3B+
 - Browser: Firefox Candidate (From snap store), on client

**Additional context**
Nothing special here I suppose, I'm using a reverse proxy and custom library location, but everything regards to that seems to work fine.

**Comment by OzzieIsaacs** [comment]
I can't reproduce it on normal x64 hardware. Could you please check if there are any errors in the firefox developer console 
Shortcut: CRTL+SHIFT+K 
![grafik](https://user-images.githubusercontent.com/6438895/126945700-d1ae4719-4da1-4596-b5e6-a082405d5ad2.png)
The error you are seeing in my screenshot has nothing to do with calibre-web

**Comment by UnPossible-Me** [comment]
I messed around and figured out, it's not the text that's washing out. Rather it was one of my extensions. (Dark Reader) 

When attempting to read a book, it loads with a light theme, (white background, black text)
Once you start interacting, for whatever reason, the extension is supposed to make everything dark themed from the get go, but while the text becomes white, it's only after reloading the page does the background shift to black.

Disabling it made everything work as it's supposed to.
Thanks for pointing this out, and apologies beforehand, this should have occurred to be.

On an unrelated note, opening some of my books, I get this error message in the console, I hope it's not a cause for concern:
```
The stylesheet blob:https://[DOMAIN].org/6643f5d2-07d4-4741-bf14-b8e1abd48f77 was not loaded because its MIME type, “text/plain”, is not “text/css”.
```
