### ISSUE TITLE
500 Internal Server Error: Cannot read txt online

### ISSUE THREAD

**Issue by suisong** [janeczku/calibre-web#2061]
when i read a txt file online. Please check the screenshot for error information
![企业微信截图_20210720194257](https://user-images.githubusercontent.com/15356266/126318513-bacc4dc1-1031-4aa1-b7a2-6984a86f3688.png)

**Comment by OzzieIsaacs** [comment]
Could you send me the text file which is generating problems via private email (email address from my profile page). 
It's a decoding issue, 
I need a nonworking example to fix it.

**Comment by RBZhu5900** [comment]
same problem .Have it fixed?
