### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [janeczku/calibre-web#2063]
Hi there,

I couldn't find a `SECURITY.md` in your repository and am not sure how to best contact you privately to disclose a security issue.

Can you add a `SECURITY.md` file with an e-mail to your repository, so that our system can send you the vulnerability details? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, you should receive an e-mail within the next hour with more info.

Thanks! (cc @huntr-helper)

**Comment by ibarrionuevo** [comment]
@janeczku

**Comment by OzzieIsaacs** [comment]
Please write me an email as described in contribution rules: https://github.com/janeczku/calibre-web/blob/master/CONTRIBUTING.md#reporting-a-bug

**Comment by zidingz** [comment]
Thanks for the direction! Emails sent.

Also for your consideration: https://github.com/janeczku/calibre-web/pull/2070

**Comment by OzzieIsaacs** [comment]
The reported issues have been solved and fixes are released in 0.6.13
