### ISSUE TITLE
Unlimited let me log in

### ISSUE THREAD

**Issue by coverthesea** [janeczku/calibre-web#2065]
**Describe the bug/problem**
Unlimited let me log in .
Use admin login
If I Refresh，Let me login again
If I open a book ,let me login again
I click most of the pages . ,let me login again
![image](https://user-images.githubusercontent.com/48321555/126742331-efc066bf-6f3b-4fcf-ae35-36ff1eb3a9dd.png)
![image](https://user-images.githubusercontent.com/48321555/126742346-8ac2d654-937f-4ceb-9bdf-2c3a63e77a6c.png)

**To Reproduce**

**Logfile**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python version: python3.7.9
 - Calibre-Web version: 0.6.12
 - Docker container: None
 - Browser: Chrome 

**Additional context**

**Comment by OzzieIsaacs** [comment]
For me it's working. 
Are you are having a proxy or something in between? Does your browser accept cookies from the website?
If you get the login page over and over again, the "login cookie" gets lost for the next request, therefore you are getting redirected to the login page.

**Comment by coverthesea** [comment]
> For me it's working.
> Are you are having a proxy or something in between? Does your browser accept cookies from the website?
> If you get the login page over and over again, the "login cookie" gets lost for the next request, therefore you are getting redirected to the login page.

Sorry to bother you
The reason for the problem is that my computer keeps switching IP
