### ISSUE TITLE
 open book unlimited load

### ISSUE THREAD

**Issue by coverthesea** [janeczku/calibre-web#2066]
**Describe the bug/problem**
 open a epub book,,than unlimited load

![image](https://user-images.githubusercontent.com/48321555/126755825-1194ba4b-de4e-4129-b204-86143215a872.png)

**To Reproduce**

**Logfile**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS:Windows 10
 - Python version: python3.7.2
 - Calibre-Web version: 0.6.12
 - Browser: Chrome

**Additional context**

**Comment by OzzieIsaacs** [comment]
Please past output of the developer console in chrome: (CTRL+SHIFT+i)
![grafik](https://user-images.githubusercontent.com/6438895/126942910-3a2455f1-afd3-4712-ae73-9277ab8c1333.png)
Please check afterwards if you are having this problem: https://github.com/janeczku/calibre-web/issues/896#issuecomment-488831045

**Comment by coverthesea** [comment]
> 请在 chrome 中通过开发者控制台的输出：(CTRL+SHIFT+i) 请稍后检查您是否遇到此问题：[#896（评论）](https://github.com/janeczku/calibre-web/issues/896#issuecomment-488831045)
> ![涂鸦](https://user-images.githubusercontent.com/6438895/126942910-3a2455f1-afd3-4712-ae73-9277ab8c1333.png)
> [](https://github.com/janeczku/calibre-web/issues/896#issuecomment-488831045)

Sorry to bother you,It's normal.
The cause of the problem is network speed.
Please close this
