### ISSUE TITLE
[Kobo] Add sync support for PDF files stored in Calibre-web library

### ISSUE THREAD

**Issue by lpommerenke** [janeczku/calibre-web#2068]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Would be nice to also allow PDF files to be synced to Kobo eReaders and not just (k)ePub files. I have also many (unprotected) PDF files in my Calibre library and reading them with the Calibre-web web reader (PDF.js) is working just fine.

**Describe alternatives you've considered**
Currently I have to sync these PDF files manually with Calibre on a computer by attaching my Kobo to an USB port.

**Comment by OzzieIsaacs** [comment]
I‘m sorry this is a Limitation on kobo side. It just doesn‘t sync pdf. There is nothing I can do from my side
