### ISSUE TITLE
Hey, Dutch translation is here.

### ISSUE THREAD

**Issue by eddriesen** [janeczku/calibre-web#207]
Might not be the right way to communicate this. (what is the proper way to contibute a translation on github? I'm a noob and I'd like to start contributing translations to projects I use)

Anyhoo, attached the Dutch informal (je instead of U (du/sie) ) translations. They work perfectly on my server.
No wonky/robotic literal translation.
[nl.zip](https://github.com/janeczku/calibre-web/files/1092531/nl.zip)

Cheers!
Ed

**Comment by OzzieIsaacs** [comment]
I've included the translation. The "official way" would be forking the project and generating a pull request. This is fine also, too.
