### ISSUE TITLE
"Edit cover art" no longer available

### ISSUE THREAD

**Issue by kaipee** [janeczku/calibre-web#2071]
**Describe the bug/problem**
In previous releases there was an option to upload cover art or pull from the web. The option to edit cover art does not seem available in the latest Nightly release (just updated), or at least I cannot see if it has been moved.

**Comment by OzzieIsaacs** [comment]
It‘s still there but is now tied to the upload access right (makes in my eyes more sense to allow cover upload only if it‘s allowed to also upload whole books)

**Comment by kaipee** [comment]
Ah I see. To me (IMHO) that doesn't make much sense.

I would categorise the ability to modify cover artwork similar to simply editing metadata of a book, which would be a much lower privilege than uploading/overwriting a book in its entirety.

This also requires allowing "Enable Uploads" in the server configuration which I also see as a much high privilege than editing some metadata. (I also have this disabled server-wide).

The ability to "Edit" (metadata and artwork) should be decoupled from the ability to upload/overwrite or add new core content (books).

**Comment by OzzieIsaacs** [comment]
Uploading has to be enabled and the user needs the corresponding right to upload, then the button is visible:
![grafik](https://user-images.githubusercontent.com/6438895/137633173-fac2d389-ee9a-4f7b-867a-8737b9523f18.png)
