### ISSUE TITLE
Database disk image is malformed

### ISSUE THREAD

**Issue by zisco67** [janeczku/calibre-web#2074]
When I'm trying to edit the metadata of a newly uploaded book, it always tells me that the database is malformed:
`(sqlite3.DatabaseError) database disk image is malformed`

**Logfile**
[2021-07-31 19:04:12,362] ERROR {cps.editbooks:833} (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.DatabaseError) database disk image is malformed
[SQL: INSERT INTO comments (text, book) VALUES (?, ?)]
[parameters: ('<p>Josip Broz Tito war ein typisches Geschöpf des Zeitalters der Extreme, welches er persönlich erlebt, erlitten und gestaltet hat. Bei seinem Tod ga ... (1062 characters truncated) ... tausbruch, wie ihn Europa seit dem Zweiten Weltkrieg nicht mehr erlebt hatte. Über Titos Lebenswerk liegt somit der Schatten bitteren Scheiterns.</p>', 10069)]
(Background on this error at: http://sqlalche.me/e/13/4xp6)

**Expected behavior**
No error should occur.

**Environment (please complete the following information):**
 - OS: Linux 3.2.40 #25556 SMP Thu Mar 4 17:56:44 CST 2021 armv7l
 - Python version: 3.9.0
 - Calibre-Web version: 0.6.13 Beta - e245a147d949b96958075026c8aa09763637c3d9 - 2021-07-30T10:16:52+02:00
 - Docker container: None
 - Special Hardware: Synology DS215j
 - Browser: Edge

**Comment by OzzieIsaacs** [comment]
Please try to execute a library check from Calibre itself. (Bibilithekswartung -> Bibiliothek überprüfen). Looks like the calibre database got somehow damaged.
Stopping and restarting Calibre-web is also needed

**Comment by zisco67** [comment]
Finally I followed these steps, that resulted in a new, working database:
1. Create a new empty local Calibre-database
2. Import all books from remote Calibre-folder
3. Copy complete new calibre folder to remote
4. Restart Calibre-Web
