### ISSUE TITLE
How-to on backing up calibre-web settings

### ISSUE THREAD

**Issue by mikaelmoutakis** [janeczku/calibre-web#2077]
**Is your feature request related to a problem? Please describe.**
I would like to make a backup of the calibre-web settings. Ie not the settings for the calibre library. 

**Describe the solution you'd like**
A section on the wiki how you take a backup. Ie where are calibre-web's settings are located.

**Comment by OzzieIsaacs** [comment]
https://github.com/janeczku/calibre-web/wiki/FAQ#how-to-backup-calibre-web-settings

**Comment by mikaelmoutakis** [comment]
Ah! I went through the wiki, but missed that. Sorry for the trouble
