### ISSUE TITLE
Ability to set the amount of time before auto-logout

### ISSUE THREAD

**Issue by fivestones** [janeczku/calibre-web#2082]
Currently after some amount of time (not sure how long), when I go to the calibre-web page I have to log in before being able to use calibre-web. I have not logged out prior to this.

There should be a way in settings to set the time before an auto-logout occurs (e.g., 30 min, 1 week, 1 year), and to disable auto-logout completely (i.e., so that once I have logged in, I will be logged in indefinitely on that browser until I log out manually).

Thanks!

**Comment by OzzieIsaacs** [comment]
Which version you are using?

**Comment by fivestones** [comment]
Version 0.6.12

**Comment by fivestones** [comment]
Sorry, I should have mentioned that in my first post.

**Comment by OzzieIsaacs** [comment]
There should be not auto logout (or it should be at least >31days). 
If you close your browser without ticking "remember me" you get logged out instantly, yes.  You might also get logged out if you update your browser and the user agent string changes (e.g. User-Agent=Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0") Changing your ip-address might also log you out.

Calibre-web has caught the attention of a number of security researchers. So I improved the security of the login process
