### ISSUE TITLE
Use browser's native pdf viewer

### ISSUE THREAD

**Issue by sortedcord** [janeczku/calibre-web#2088]
Is there any way to view a pdf in the browser's native pdf reader instead (As ePUBs are not supported in many browsers as of now) without downloading the pdf file?

**Comment by OzzieIsaacs** [comment]
?
How should this work? You are having a file on your server and without downloading it to you browser it will show the file? 
Would be like browsing the internet without having connection (no need to download the html files?) 

If you want to use the build-in browser you can click on download, it then uses the build-in pdf reader

**Comment by sortedcord** [comment]
Actually I moved from another project called [docspell](https://github.com/eikek/docspell) to calibre-web recently. This project made use of some API to view the pdf in the browser itself. It might be possible that the browser is storing the pdf in some temporary location. I might not be able to explain the purpose of this but I just wanted to know if I was missing something or if such a thing was already implemented or not. The built-in pdf reader works as well. Thanks!
