### ISSUE TITLE
Upgrading From 0.6.12-ls124 to 0.6.12-ls128 Breaks Application

### ISSUE THREAD

**Issue by joe-eklund** [janeczku/calibre-web#2090]
**Describe the bug/problem**
Hello. I have been running Calibre Web in Docker for the past couple months, testing out things. Today when I upgraded from 0.6.12-ls124 to 0.6.12-ls128 I was greeted with a screen saying to choose where the database is. 

When I put in where it is, it did not work. 

Attempting to roll back to the previous image it still gave the same error. Luckily, I have duplicati backups and was able to restore all the config / database files for Calibre Web. That, combined with rolling back to 0.6.12-ls124, means my Calibre Web is functional again.

**To Reproduce**
1. Upgrade from 0.6.12-ls124 to 0.6.12-ls128 on Docker.
2. No longer can find database.
3. Try rolling back to previous image and it also doesn't work.
4. Only solution is to restore calibre web config directory from backup.

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

**Expected behavior**
Upgrading works correctly.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Docker on Ubuntu 18.04
 - Python version: Docker
 - Calibre-Web version: 0.6.12-ls128
 - Docker container:  LinuxServer
 - Special Hardware:  N/A
 - Browser: [e.g. Chrome 83.0.4103.97, Safari 13.3.7, Firefox 68.0.1 ESR] Chrome 92.0.4515.131 

**Additional context**
I am using an LDAP server for authentication if that matters at all. I did see you have recently changed authentication stuff, so maybe that was it? Please let me know if you require more info. Thanks!

**Comment by OzzieIsaacs** [comment]
Please open an issue at the corresponding docker repository, there are some people having trouble with the docker image in the last time. The standalone calibre-web version works fine.

**Comment by joe-eklund** [comment]
> Please open an issue at the corresponding docker repository, there are some people having trouble with the docker image in the last time. The standalone calibre-web version works fine.

Ok thank you. I will close this issue and open one over there. :)
