### ISSUE TITLE
PDF download: optionally disable `attachment` in response header `Content-Disposition`

### ISSUE THREAD

**Issue by tinywrkb** [janeczku/calibre-web#2091]
These days, browsers have pretty good PDF support, from built-in PDF viewers to extensions that can highlight and translate text.  
It would be nice if calibre-web will not force the browser to save PDF files in the download folder.  
I tested with the following change in Edge 92, and got the expected behavior. Also, when manually saving files, the filename from the `Content-Disposition` header is still being used by the browser.

```
diff --git a/cps/helper.py b/cps/helper.py
index b6ea6760..bd6b0114 100644
--- a/cps/helper.py
+++ b/cps/helper.py
@@ -842,7 +842,7 @@ def get_download_link(book_id, book_format, client):
         file_name = get_valid_filename(file_name)
         headers = Headers()
         headers["Content-Type"] = mimetypes.types_map.get('.' + book_format, "application/octet-stream")
-        headers["Content-Disposition"] = "attachment; filename=%s.%s; filename*=UTF-8''%s.%s" % (
+        headers["Content-Disposition"] = "filename=%s.%s; filename*=UTF-8''%s.%s" % (
             quote(file_name.encode('utf-8')), book_format, quote(file_name.encode('utf-8')), book_format)
         return do_download_file(book, book_format, client, data1, headers)
```

**Comment by tinywrkb** [comment]
This doesn't work with the `DjVu.js Viewer` extension, so format matter, and this should only be (optionally) enabled for PDFs.  

This works perfectly with PDF files and:
* Built-in viewers of Edge 93.0.961.18 (Linux).
* Chrome 94.0.4603.0 (Linux).
* With extensions like `Adobe Acrobat`, `PDF Viewer for Vimium C`.
* Safari and Edge 94 on iOS.

**Comment by OzzieIsaacs** [comment]
I don't want to make things more complicate then they are. Many people having problems to change all the settings now available. I you want to use your browser reader just click on download.
