### ISSUE TITLE
Instalación en Windows

### ISSUE THREAD

**Issue by lfers** [janeczku/calibre-web#2094]
**Describe the bug/problem**

Realicé una instalación manual de las siguientes versiones

- calibre-web-0.6.12
- calibre-web-0.6.11
- calibre-web-0.6.10 

Al probar las siguientes funcionalidades

1. Para crear un nuevo usuario 
2. Intentar cambiar el idioma con el usuario admin , ya que no me permite agregar uno nuevo.

Ambas funcionalidades el botón guardar parece no tener efecto y no realiza el guardado.

**Solo en la versión calibre-web-0.6.9_Priya la creación del usuario se realiza de forma satisfactoria.**

**To Reproduce**

1. Go to Al crear un nuevo usuario
2. Click on en el botón Guardar 
3. Scroll down to Hasta el final de la página

![image](https://user-images.githubusercontent.com/52684764/130289444-ff7593bc-c01d-4b70-b803-fe218bafa1cf.png)
![image](https://user-images.githubusercontent.com/52684764/130290432-76e7ba48-766a-4b3b-b305-31fc8a5ad548.png)

**Expected behavior**

- Crear y guardar un nuevo usuario.
- Actualizar el idioma del usuario admin.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.9
 - Calibre-Web version: calibre-web-0.6.10, calibre-web-0.6.11, calibre-web-0.6.12
 - Docker container: Instalación manual
 - Browser: Chrome last versión.

**Comment by yeraycito** [comment]
Hola, cómo vea el administrador que estas escribiendo en castellano se va a quejar, esto es válido para mi también....ji,ji.
Yo lo tengo instalado en un ordenador linux y con todas las versiones del programa que citas no he tenido ningún problema. Te aconsejaría que desactivaras en tu navegador todos los bloqueadores de anuncios que tengas. Es posible que sea eso lo que impida hacer lo que quieres. También probaría a intentarlo con otro navegador distinto.

**Comment by OzzieIsaacs** [comment]
https://github.com/janeczku/calibre-web/blob/master/CONTRIBUTING.md#general
Please post your text in english (I don't speak spanish, despite my name sounds spanish)
