### ISSUE TITLE
cps.py doesn't exist

### ISSUE THREAD

**Issue by Nakda** [janeczku/calibre-web#2096]
**Describe the bug/problem**
I wanted to run cps as a service, as instructed [here](https://github.com/janeczku/calibre-web/wiki/Setup-Service-on-Linux), but there is no `cps.py` on my system after installation so I'm not sure how to fill the service definition file.

**To Reproduce**
1. Install cps via pip, as instructed on readme: `pip3 install calibreweb`
2. Browse install folder to search for `cps.py`: `/home/<user>/.local/lib/python3.7/site-packages/calibreweb/cps`
3. Search for `cps.py`: `sudo find / -name cps.py`
4. No `cps.py` found

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

**Expected behavior**
Either cps.py should be there, or the wiki page to run a service should be updated to guide users on how to fill the service file definition (ExecStart and WorkingDirectory).

**Environment (please complete the following information):**
 - OS: Raspberry Pi OS (lite/headless)
 - Python version: python 3
 - Calibre-Web version: 0.6.12
 - Docker container: None
 - Special Hardware: Rpi 4

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

**Comment by OzzieIsaacs** [comment]
Yeah instructions are made for the source install and not for installation via pip.
‚/home/<user>/.local/bin/cps‘ or ‚python3 -m calibreweb‘ should do the trick

**Comment by Nakda** [comment]
> 
> 
> Yeah instructions are made for the source install and not for installation via pip.
> ‚/home//.local/bin/cps‘ or ‚python3 -m cps‘ should do the trick
> 
> Edited: cps instead of calibreweb

Thanks! Should I put this for both WorkingDirectory and ExecStart?

**Comment by OzzieIsaacs** [comment]
Not 100% sure and can‘t check it now. 
1) try to remove working dir
2) if Not working: /home/<user>/.local/lib/python3.7/site-packages/calibreweb could work

**Comment by OzzieIsaacs** [comment]
For my suggestion no.1 remove the complete line in the unit file

**Comment by Nakda** [comment]
I commented out WorkingDir and set `ExecStart=/usr/bin/python3 /home/<user>/.local/bin/cps`, seems to be working! Thank you very much
