### ISSUE TITLE
What is my OPDS catalogue URL?

### ISSUE THREAD

**Issue by jdaviescoates** [janeczku/calibre-web#2103]
I'm trying to connect my FBreader to my instance of CalibreWeb but when I enter my URL it just tells me https://books.uniteddiversity.coop is not an OPDS catalogue

Which URL should I be using? 

Thanks

**Comment by jdaviescoates** [comment]
OK, managed to work out that it's just https://books.united diversity.coop/opds so I can now browse my books. Great!

**Comment by jdaviescoates** [comment]
Does anyone know of any Android ebook apps that support authenticating to my Calibre Web OPDS so I can browse and download?

**Comment by oliverjhyde** [comment]
Moon+ Reader

**Comment by OzzieIsaacs** [comment]
https://github.com/janeczku/calibre-web/wiki/FAQ#which-opds-readers-work-with-calibre-web

**Comment by jdaviescoates** [comment]
> Moon+ Reader

Thanks, but I can't find any option to authenticate.  So I can browse my books, but I can't download them.  There don't appear to be any settings within Moon+ Reader to be able to add a username and password.

**Comment by jdaviescoates** [comment]
> https://github.com/janeczku/calibre-web/wiki/FAQ#which-opds-readers-work-with-calibre-web

Thanks, I'd seen that. I can browse my books fine, but can't download them because I need to be able to authenticate.  As far as I can tell, none of the existing apps will let me do that, which is a bit disappointing. But I'll keep looking/ experimenting...

**Comment by OzzieIsaacs** [comment]
Try harder and you will get it to work

**Comment by Forinil** [comment]
Since this seems to still be the top Google search result for Calibre-Web OPDS URL, allow me to add some more recent info.

_Moon+ Reader_ absolutely works - including authentication - if your instance is configured to be completely private. There's no place to provide credentials on the library adding screen, but it'll ask for a username and password while attempting to connect.

For _KyBook 3_ (iOS client) the workaround is to provide URL in format `http(s)://username:password@ip/hostname:port/opds`.
This may work for other clients (_Moon+ Reader_, unfortunately, ignores credentials passed this way).

**Comment by Akiamoto** [comment]
Working format with credentials on local Calibe-Web-server:

_http://username:password@localip:port/opds_

**Comment by jdaviescoates** [comment]
> Since this seems to still be the top Google search result for Calibre-Web OPDS URL, allow me to add some more recent info.
> 
> _Moon+ Reader_ absolutely works - including authentication - if your instance is configured to be completely private. There's no place to provide credentials on the library adding screen, but it'll ask for a username and password while attempting to connect.

Thank you! :pray: 

I just disabled Anonymous browsing here:

![image](https://github.com/janeczku/calibre-web/assets/2113743/a5da82c5-4c4f-45de-a4e4-1b0f5c235816)

And now it does indeed prompt for credentials and I'm able to download books from my Calibre Web library directly into my Moon+ Reader app. Wonderful!

**Comment by nicman23** [comment]
> Try harder and you will get it to work

try harder and maybe you would have better documentation.
