### ISSUE TITLE
KOBO Partial sync of my library (only 10%)

### ISSUE THREAD

**Issue by fdecourt** [janeczku/calibre-web#2110]
**Describe the bug/problem**
With  Calibre-WEB on a Docker LinuxServer, and a completely reset KOBO, the KOBO connects correctly to CalibreWeb. So far so good.
However, out of the 1070 books in the Calibre library, only 102 are synchronized, sometimes, without much reason, one is added.
Downloading epubs is not possible either (see log)

**To Reproduce**
1. Go to KOBO
2. Click on SYNC
4. Sync is marked as completed
5. But it will only sync 10% of the librairy, with information that will not allow the download of files

**Logfile**
![image](https://user-images.githubusercontent.com/4050977/132484363-7d101911-9e67-4b38-8a4f-5f0509f294a0.png)

**Expected behavior**
All the Library should be sync with the right informations.

**Environment (please complete the following information):**
- Latest version of Calibre-Web (0.6.12) from linuxserver docker image
- KOBO version : 4.28.18220 (07/08/2021)
- LIBRA H2O

**Additional context**

When I call the API http://[MY URL]:8083/kobo/[MY TOKEN]/v1/library/sync
I have all mys books returned : 
![image](https://user-images.githubusercontent.com/4050977/132488547-291f8b92-ee2c-4b2d-a3da-0995d7977cac.png)

Calibre-Web parameters :
![image](https://user-images.githubusercontent.com/4050977/132484857-e7389ac8-6d10-4736-960b-665c5911bc0a.png)

Number of book in my library :
![image](https://user-images.githubusercontent.com/4050977/132485799-5d3e98d5-d94f-4272-a793-566ca568e657.png)

Kobo Parameter :
![image](https://user-images.githubusercontent.com/4050977/132485237-bc9c8b9c-02e6-4364-8776-1d004c873b5c.png)

**Comment by fdecourt** [comment]
I restart from the begining : reset the KOBO and the calibre-web (so fresh database everywhere). I just didn't touche the Calibre database.
And still, only 102 book synchronized. Maybe a date problème ? But how to solve it ?

**Comment by OzzieIsaacs** [comment]
It‘s Not working properly, i‘m working on it

**Comment by fdecourt** [comment]
Great, thank you

**Comment by fdecourt** [comment]
Hi, thanks for your work, OzzieIsaacs, but with the Calibre-web version n°0.6.15 Beta - 9d9acb058dbada25678cb2f27940557772a0a1db - 2021-12-06T21:02:06+01:00, it is still not working
I reset everything (KOBO and calibre-web), do a fresh install of all.
- I have 1083 books in my librairy
- I used the force Full Kobo Sync button (and only 168 entries where deleted, but I had only 100 books in my Kobo)
- After that, when I restart the KOBO sync, nothing happen in my Kobo.
- Then, I clicked again on the Full Kobo Sync button, still 168 entries deleted.

So I tried the url of the API sync in my browser, and some stuff changed (http://[MY URL]:8083/kobo/[MY CODE]/v1/library/sync
It returns only 200 hundred entries (on 1083 books) : 
![image](https://user-images.githubusercontent.com/4050977/145265682-ca19f479-17d3-4399-840f-ca613361ed85.png)
From 0 to 99 > NewEntitlement
![image](https://user-images.githubusercontent.com/4050977/145265863-90ec9865-a697-4fbc-8180-1ef350751450.png)

from 100 to 199 > ChangedReadingState
![image](https://user-images.githubusercontent.com/4050977/145265936-09bbdaf8-5521-4665-a40a-15c92d8f9c89.png)

So I will never get the full list of books through the URL

If after that a try to resync my kobo, without deleting anything, on my browser, I will only avec 100 ChangedReadingState,  no more NewEntitlement

On the log file : 
![image](https://user-images.githubusercontent.com/4050977/145266338-6af47bdc-6f31-42ce-86f7-20d53fa65617.png)

**Comment by fdecourt** [comment]
I made an other test : I completely reinstall CalibreWeb (through Docker), deleted all config files and try to see what happen, not using my kobo.
First, when I used the Sync feature on my browser, It only show me 100 books (http://[URL]:8083/kobo/[TOKEN]/v1/library/sync)
(still 1082 books on my library)
When I just refresh the page, it shows me 200 entries (same as above, 100 NewEntitlement and 100 ChangedReadingState)

And, in the app.db, in the kobo_sync_book, there are 300 entries (I didn't sync my kobo), and the first book has book_id = 10
Then if I force the Full kobo sync, wit will delete 300 entries
Then, if I refresh  (http://[URL]:8083/kobo/[TOKEN]/v1/library/sync, there is still 200 entries (same as above, NewEntitlement and ChangedReadingState)
