### ISSUE TITLE
Question: where does the calibre-web store local data (those except from calibre db)

### ISSUE THREAD

**Issue by JeffersonQin** [janeczku/calibre-web#2113]
Ask as the title states. I noticed that in calibre-web, there are settings like "read", "archive", user settings, etc. But I can find them nowhere in the calibre database. As a result, I am wondering where are those data stored, and how to backup or restore them.

Thanks!

**Comment by OzzieIsaacs** [comment]
https://github.com/janeczku/calibre-web/wiki/FAQ#how-to-backup-calibre-web-settings

**Comment by JeffersonQin** [comment]
Thanks! Helped a lot.

**Comment by JeffersonQin** [comment]
@OzzieIsaacs Well, may be it is not proper to ask here, but would you please review the pull request I made a few days ago? I really think it's a useful feature. #2109

**Comment by OzzieIsaacs** [comment]
I currently only have limited Computer Access, please ne patient

**Comment by JeffersonQin** [comment]
@OzzieIsaacs Got that, thanks for your reply
