### ISSUE TITLE
💥 Potential security vulnerability

### ISSUE THREAD

**Issue by ranjit-git** [janeczku/calibre-web#2119]
Potential security vulnerability has been disclosed against this repo.
Plz visit report url https://huntr.dev/bounties/0dcddbb3-fdb3-4fb5-a2c4-be971b71714b/ to validate the bug

Thanks

**Comment by OzzieIsaacs** [comment]
The issue was fixed in 0.6.13. I forgot to close it in huntr.dev. I contacted the admin. 
I'll close the issue
