### ISSUE TITLE
Scrolling books list to second page stops loading covers (Safari)

### ISSUE THREAD

**Issue by jcollas** [janeczku/calibre-web#2126]
**Describe the bug/problem**

I see all the covers until I scroll to the second 'page' which then shows empty covers from that point on.  This appears to be a Safari-specific problem, doesn't happen in Chrome.

**To Reproduce**
1. Click on 'Books'
2. See book covers.
3. Scroll down to end of list of books, It'll refresh with the new book covers being empty (see screenshot)

**Logfile**
Nothing shows in log file

**Expected behavior**
I expect to see the covers when I scroll down the list of books.

**Screenshots**

![Screen Shot 2021-09-26 at 10 01 48 AM](https://user-images.githubusercontent.com/164569/134811109-730db166-553f-4044-bf33-ad8ac70d1820.jpg)

**Environment (please complete the following information):**
 - OS: linux 4.4.218.x86_64.1
 - Python version:  python 3.9
 - Calibre-Web version: 0.6.13
 - Docker container: docker 18.06.3-ce, build d7080c1
 - Special Hardware: 
 - Browser: Safari 15.0 (16612.1.29.41.4, 16612)

**Additional context**

In the Safari console, I see a 404 for static/js/libs/jquery.form.min.js.map, but this might not be related.

**Comment by Gagalari** [comment]
Same issue here.
Problem in Safari, Chrome ok.
On E-Reader i need to press refresh to get the books, also on first page.

Client: Tolino - E-Reader
Calibre-Web version 0.6.14 Beta
Docker container None
Special Hardware Raspberry Pi 3
Browser browser from tolino E-Reader

off topic:
if you fix this, can you have a look that the workaround from
https://github.com/janeczku/calibre-web/issues/1466
does work again?

**Comment by wgibcus** [comment]
> Please try the newest nightly version

So after updating my Macbook to the latest OS, bricking it (thanks T2 firmware!) and getting it back from repair, I can confirm that this issue is solved on Safari 15 and iOS 15. Well done and thank you :)

**Comment by pagocs** [comment]
I can confirm the issue is no more reproducible with calibre-web 0.6.14 and Safari (macos Monterey) version 15.1 (17612.2.9.1.20).
