### ISSUE TITLE
No user id in session - Error after updating to 0.6.13

### ISSUE THREAD

**Issue by ridoli** [janeczku/calibre-web#2127]
**Describe the bug/problem**

After upgrading to V  0.6.13 from  0.6.12 via UI, calibre web didn't start.
First I found that it was missing lxml module, so I installed it via pip and it started.

The problem now is that after login with an existing user the web loops again to the login page, even if at the top it appears a green message: "Now connected as 'Admin" (maybe not exact message but my web is in spanish, sorry, see screenshot below).

![image](https://user-images.githubusercontent.com/18705197/134824678-1868a3ff-535f-4590-897d-28f3539c82e1.png)

There is no error on Chrome console nor network tab:

![image](https://user-images.githubusercontent.com/18705197/134824696-286ec6e7-165f-4c93-b59f-d54ef2e8a3af.png)

In calibre.log fails, the following error appears every time I try to login:
`[2021-09-26 23:26:54,788] ERROR {cps.ub:83} No user id in session`

What could be the cause of this error?

Thank you very much in advance.

**To Reproduce**
1. Update from 0.6.12 to 0.6.13 via web UI
2. Try to start calibre web
3. Install lxml via pip
4. Start Calibre web
5. Login into calibre web
6. See the login pacge appears again

**Expected behavior**
calibre-web should go to main page after login in

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Python version: Python 3.6.9
 - Calibre-Web version: 0.6.13
 - Docker container: None
 - Browser:  Chrome 94.0

**Comment by OzzieIsaacs** [comment]
Somebody also reported this issue on discord:
![grafik](https://user-images.githubusercontent.com/6438895/134954219-d133c137-17df-41d8-9231-ddab7aaf5e7f.png)
Updating the dependencies to a newer version worked. It's still not clear which dependencies causes the problem. My new theory tends towards some of the flask-.. one's

**Comment by marcodamm** [comment]
Same error here after upgrading to 0.6.13. Running in a Docker container on my NAS though (see below)

OS: QNAP NAS OS (Host), Ubuntu 18.04.3 (Docker Container)
Python version: Python 2.7.17
Calibre-Web version: 0.6.13
Docker container: linuxserver/calibre-web
Browser: Chromium 93.0.4577.82

**Comment by ridoli** [comment]
Hi guys, 

I found the issue, completely on my side. Thank you for giving me light on this with the dependencies!

It was an old problem that it seems it wasn't afecting in previous versions.
The problem was the following:
- I have calibre-web installed on a virtualenv in my ubuntu server
- Then there is a systemctl service that runs calibre-web once system is started
- The problem was that the service was pointing to the "main" python installation insetad of pointing to the virtualenv.
- This main "python" didn't have the correct prrequisites installed.
- After changing it, it works fine.

Thank you for the help!

Best regards,
Carlos
