### ISSUE TITLE
Can’t login - calibre-web version 0.6.13

### ISSUE THREAD

**Issue by deadbone** [janeczku/calibre-web#2133]
**Describe the bug/problem**
Can’t log to calibre anymore since the last update 0.6.13.
Was working fine before.

**To Reproduce**
Try to login, put credentials : calibre indicates I’m connected but keeps staying on login page.

**Logfile**

Sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: user.nickname.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Synology DSM 6.2.4-25556-2
 - Calibre-Web version: 0.6.13
 - Docker container: mephistoxol/calibresrv_web latest
 - Browser: Safari

Regards

**Comment by OzzieIsaacs** [comment]
In the internal data structure the username was saved in older versions as nickname, in newer version this was changed to "name". The migration normally should happen automatically. For a reason I don't know this didn't work for you.
- I guess restarting calibre-web didn't work?
- Please try to update sqlalchemy and also flask and ideally all other dependencies
- manually try to change the database field. Open app.db file in a sqlite editor, such as sqlitebrowser (https://sqlitebrowser.org/). Change table user (nickname -> name), save and restart calibre-web
- delete app.db and restart config from the beginning (only if there are not many user and you haven't changed much) 
- send me the app.db file and I have a look at it (please in private email message. Together with calibre-web.log file. I'm not fully convinced that this is your problem)

**Comment by deadbone** [comment]
Hi,
I tested some solutions you gave me and no success. So I decided to test another docker image with the same db and it’s working like a charm. So the problem wasn’t your soft but the Docker image I used.
Sorry for the inconvenience
Regards
