### ISSUE TITLE
Calibre is duplicating math formulas automatically

### ISSUE THREAD

**Issue by Yunelsy** [janeczku/calibre-web#2136]
Hello,
I just started to work with Calibre. I am trying to convert an xhtml file to epub. This file has a lot of math formulas that are all duplicated automatically. Since there are many, I am trying to figure out what is happening in the conversion. An example is 
`<math xmlns="http://www.w3.org/1998/Math/MathML" id="S1.p1.m2" class="ltx_Math" alttext="n\geq 2" display="inline"><mrow><mi>n</mi><mo>≥</mo><mn>2</mn></mrow></math>`
which displays twice n≥2.
Does someone know how to fix this issue? Thanks in advance.

**Comment by OzzieIsaacs** [comment]
Calibre-web is not calibre and it only uses calibre for converting ebooks. So I think you are here wrong, please ask this question at the Calibre repository.
