### ISSUE TITLE
Epub Reader - Using arrow keys to navigate loads page twice

### ISSUE THREAD

**Issue by a1023456** [janeczku/calibre-web#214]
Win10 / chrome / PC
Read the epub time online Use the left and right arrows to page over a page.

**Comment by OzzieIsaacs** [comment]
what is the problem? For me the arrow buttons are working?

**Comment by a1023456** [comment]
Press the key twice to double the page

**Comment by a1023456** [comment]
Use the keyboard ⬅️ ➡️
