### ISSUE TITLE
have upload metadata.db file but still DB Location is not Valid, Please Enter Correct Path

### ISSUE THREAD

**Issue by luokai2000** [janeczku/calibre-web#2142]
![image](https://user-images.githubusercontent.com/56202705/138510518-ea2168ef-0bab-453d-9997-ec561d5d34cb.png)
![image](https://user-images.githubusercontent.com/56202705/138510595-20421ee7-4a33-4805-a1bf-4307118f6977.png)

**Comment by wgibcus** [comment]
What operating system are you using?

**Comment by luokai2000** [comment]
> 

centos 7.9
