### ISSUE TITLE
Cant execute cps.py

### ISSUE THREAD

**Issue by chrisvdgeld** [janeczku/calibre-web#215]
When I try to python cps.py I get this after ctrl + c on ubuntu 16.04:

```
exile:/opt/calibre# python cps.py
^CTraceback (most recent call last):
  File "cps.py", line 34, in <module>
    IOLoop.instance().start()
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 863, in start
    event_pairs = self._impl.poll(poll_timeout)
KeyboardInterrupt

```

**Comment by OzzieIsaacs** [comment]
the script is not starting any background job, so after entering the command the server is running and the console is blocked. To prevent this you can generate a service like descirbed in the readme. Other option is starting the script with "python cps.py &", this sends it to the background. The output only states that you aborted the script by pressing crtl-c.

**Comment by OzzieIsaacs** [comment]
No response for long time
