### ISSUE TITLE
Update README.md - End-of-Life of docker image from technosoft2000/docker-calibre-web 

### ISSUE THREAD

**Issue by Technosoft2000** [janeczku/calibre-web#2151]
Hello together, since I have almost no time to maintain [technosoft2000/docker-calibre-web](https://github.com/Technosoft2000/docker-calibre-web) anymore, I hereby discontinue it and recommend that only the well maintained image of [linuxserver/calibre-web](https://github.com/linuxserver/docker-calibre-web) should be mentioned in your `README.md`. Btw. thank you to @OzzieIsaacs and his team that they still work on Calibre Web to make it better and still adding additional features over such a long time 👍

**Comment by OzzieIsaacs** [comment]
I'm sorry to hear this. I fully understand your reasons. It was a pleasure to work with you on this wonderful project in the past few years.
I changed the readme according to your proposal.
