### ISSUE TITLE
Add OAuth support for custom provider

### ISSUE THREAD

**Issue by luclu** [janeczku/calibre-web#2153]
I would higly appreciate support for custom oauth providers like a self-hosted [goauthentik.io](https://goauthentik.io/) instance.

[Flask-Dance](https://github.com/singingwolfboy/flask-dance) the oauth library calibre-web uses does support **custom providers** ([docs](https://flask-dance.readthedocs.io/en/latest/providers.html#custom)).

As far as I understand this provider would only need three additional fields in the web-ui next to `client-id` and `-secret`:
- `base_url`
- `token_url`
- `authorization_url`

**Comment by OzzieIsaacs** [comment]
Please have a look here:
https://github.com/janeczku/calibre-web/blob/master/CONTRIBUTING.md#feature-request
