### ISSUE TITLE
No redirect after login

### ISSUE THREAD

**Issue by mariusst** [janeczku/calibre-web#2157]
Hi!
I updated to the most recent version with the autoupdater inside calibre web. After the update, when I try to login  there's no redirect to the main page or any other page, just the login page. 
Inside calibre web log there's this error: `ERROR {cps.ub:83} No user id in session`

 - OS: Debian Linux 10
 - Python version: 3.7.3
 - Calibre-Web version old: 0.6.9
 - Calibre-Web version updated: 0.6.13

**Comment by OzzieIsaacs** [comment]
Please try to update your dependencies. This helped in another case like this

**Comment by eddriesen** [comment]
> [2021-10-31 11:54:52,411] ERROR {cps.ub:83} No user id in session

Dang!

>Please try to update your dependencies. This helped in another case like this

`$ sudo pip3 install --target vendor --upgrade -r requirements.txt`
`$ sudo systemctl restart cps.service`

Fixed! thanks! Maybe a dependency check in the upgrade script for us noobs?

**Comment by mariusst** [comment]
Hi and thanks!
On my system it doesn't work because cryptography module can not be installed. It seems there's a bug with the Debian 10 rust package. It seems I have to find another workaround if I want to update calibre-web

**Comment by OzzieIsaacs** [comment]
@mariusst Installing the binary one via apt could do the job (python3-flaskext.wtf)

**Comment by OzzieIsaacs** [comment]
@eddriesen I added a dependency check at the start of calibre-web (easier to implement as during the update process)

**Comment by mariusst** [comment]
I managed to install the update but I have a new problem. Please check this new issue #2168
Thanks
