### ISSUE TITLE
Ability to view books that are in a combination of categories (with *and* logic)

### ISSUE THREAD

**Issue by fivestones** [janeczku/calibre-web#2159]
**Is your feature request related to a problem? Please describe.**
There is no way currently in Calibre-web to view all the books that are part of a certain category and also part of another category (e.g., show me just the books that have the category fiction and also have the category history. I can see all the books that are tagged as fiction, which will include a bunch that aren't historical in nature, or I can view all the books tagged as history, which will include some fiction books but mostly non-fiction. But if I want to see only those that are just fiction and history, I can't do it. Another example would be the categories 'Children's Books' and 'Science'. If I want a view for my kids that lets them see all the science books that are for kids, I can't do it. I'm stuck with either seeing all the kids books, or all the science books, but not the combination of the two. 

**Describe the solution you'd like**
In the advanced search, there should be a way to add on searches with 'and' logic (e.g., click a plus button and you can get a new set of search options that will be added to what you already have. This would allow for things like you can do in Calibre in the search bar including 'not' searches, e.g., `tags:"=Children's books" and not tags:"=Science"` to see all the kids books that aren't scientific.

Alternatively, these kinds of searches could just be typed into the search bar, the way you can in Calibre.

**Describe alternatives you've considered**
I don't really see any other way to do this.

**Additional context**
This is essentially the same request as https://github.com/janeczku/calibre-web/issues/1956, but with the title that is more descriptive so it doesn't get confused with issues like https://github.com/janeczku/calibre-web/issues/2019 as 1956 did. Also my idea of how to go about making this possible is a little different than in 1956, although I would be satisfied with either way to do it if it made this possible.

**Comment by OzzieIsaacs** [comment]
The advanced search is capable of doing what you want:
Search for "fiction" books which are not "kids"
![grafik](https://user-images.githubusercontent.com/6438895/140315721-2a4ff4d0-fdfb-4f1a-b0fa-a3300a11aec6.png)
or search for all "fiction" and "kids" books:
![grafik](https://user-images.githubusercontent.com/6438895/140315764-dca37f7b-a25f-4eeb-8b9f-3407c879e068.png)

(There is one issue requesting an "or" logic, this isn't possible, indeed)

? Or did I get something wrong?

**Comment by fivestones** [comment]
Can you reopen this?

You're right about being able to do this for the simple case of finding one tag which are also not one other tag. But the ability to to use *and* logic for any kind of search (Books that are children's books and also are science books [tags:"=Children's books" and tags:"=Science"]) is still not possible.
Or should I open a new issue?

**Comment by fivestones** [comment]
Sorry for my late reply. I'm still interested in this, and I expect many other users are as well.

**Comment by OzzieIsaacs** [comment]
?
![image](https://user-images.githubusercontent.com/6438895/145701990-87801c53-5457-427f-9a2e-705b8bb62afb.png)

If you refer to the fact that sometimes you can't tick two categories, this is because there are in this case no books with this combination of tags

**Comment by fivestones** [comment]
Thanks! I didn't understand from the UI at all that this was possible until you added it in your above comment...more than a year ago. Just wanted to tell you thanks again.
