### ISSUE TITLE
Upgrading from v0.6.13 to v0.6.14 requires a manual installation of flask-WTF package

### ISSUE THREAD

**Issue by amasolini** [janeczku/calibre-web#2161]
**Describe the bug/problem**
After running the upgrade process from the /admin/view page, calibre web is unable to start. 
Checking the logs I saw the package flask-WTF is required but it was not automatically installed

**To Reproduce**
1. Run version 0.6.13
2. Click on "CHECK FOR UPDATE" under the /admin/view page.
3. Upgrade to v0.6.14
4. Wait for the upgrade to finish and the popup requesting to refresh the page to appear.
5. Refresh the browser. Nothing will appear as calibre won't be working due to a missing requirement.

**Logfile**
[2021-10-31 18:38:13,295]  INFO {cps:125} *** "flask-WTF" is needed for calibre-web to run. Please install it using pip: "pip install flask-WTF" ***

**Expected behavior**
Calibre should be restarted and functioning after a version upgrade.

**Screenshots**
-

**Environment (please complete the following information):**
 - OS: CentOS Linux release 8.3.2011
 - Python version: python3.8
 - Calibre-Web version: 0.6.14
 - Docker container: -
 - Special Hardware: -
 - Browser: -

**Additional context**
-

**Comment by amasolini** [comment]
Running `pip install flask-WTF` and restarting calibre with `systemctl restart calibreweb` fixes the issue.

**Comment by OzzieIsaacs** [comment]
Yeah, I know. I‘ll avoid introducing new libraries. I will not program  a automatic installer, as it can be very troublesome, so the way you did it is the preferred way

**Comment by MarcoProcida** [comment]
On raspberry pi using Linux raspberrypi 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l GNU/Linux to install flask-WTF using the following command: "pip3 install flask-WTF"

**Comment by flutterkage2k** [comment]
using synology docker image same error message "pip install flack-WTF..."

completed as below.
access docker container console.

> apt-get -y install python3-pip
> pip install flask-WTF

restart container.

**Comment by marcolaeti** [comment]
bonjour, je suis sur nas synology,
j'ai installe calibre web avec le docker et fait la derniere mise a jour 0.6.14
et la messeage d'erreur : pip install flask-WTF

j'ai lu les commentaires mais rien a y faire, je n'y arrive pas
vous pouvez aider ?
