### ISSUE TITLE
Can not access database configuration in admin view after update

### ISSUE THREAD

**Issue by mariusst** [janeczku/calibre-web#2168]
After update to the latest version 0.6.14, accessing the database configuration gives this error message:

```
Traceback (most recent call last):
File "/home/marius/calibre-web/vendor/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/home/marius/calibre-web/vendor/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/marius/calibre-web/vendor/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/home/marius/calibre-web/vendor/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/home/marius/calibre-web/vendor/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/home/marius/calibre-web/cps/admin.py", line 94, in inner
return f(*args, **kwargs)
File "/home/marius/calibre-web/cps/admin.py", line 197, in db_configuration
return _db_configuration_result()
File "/home/marius/calibre-web/cps/admin.py", line 1308, in _db_configuration_result
gdrivefolders = gdriveutils.listRootFolders()
File "/home/marius/calibre-web/cps/gdriveutils.py", line 224, in listRootFolders
fileList = drive.ListFile({'q': folder}).GetList()
File "/home/marius/calibre-web/vendor/pydrive2/apiattr.py", line 166, in GetList
for x in self:
File "/home/marius/calibre-web/vendor/pydrive2/apiattr.py", line 150, in __next__
result = self._GetList()
File "/home/marius/calibre-web/vendor/pydrive2/auth.py", line 64, in _decorated
self.auth.Authorize()
File "/home/marius/calibre-web/vendor/pydrive2/auth.py", line 630, in Authorize
"drive", "v2", http=self.http, cache_discovery=False
File "/home/marius/calibre-web/vendor/googleapiclient/_helpers.py", line 134, in positional_wrapper
return wrapped(*args, **kwargs)
File "/home/marius/calibre-web/vendor/googleapiclient/discovery.py", line 294, in build
adc_key_path=adc_key_path,
File "/home/marius/calibre-web/vendor/googleapiclient/_helpers.py", line 134, in positional_wrapper
return wrapped(*args, **kwargs)
File "/home/marius/calibre-web/vendor/googleapiclient/discovery.py", line 493, in build_from_document
if isinstance(client_options, six.moves.collections_abc.Mapping):
AttributeError: module 'six.moves' has no attribute 'collections_abc'
```

**Environment:**
 - OS: Debian 10
 - Python version: 3.7.3
 - Calibre-Web version: 0.6.14

**Additional context**
Also, the book covers are not loaded, it look like calibre-web does not connect to gdrive.

**Comment by OzzieIsaacs** [comment]
Please check if the version of "six" (the one you installed in the vendor folder) is in the range of ">=1.10.0,<1.17.0"

**Comment by mariusst** [comment]
Package six is version 1.16.0

**Comment by OzzieIsaacs** [comment]
Then it could also be pydrive2, which version do you have there?

**Comment by OzzieIsaacs** [comment]
Or the google-api-client?

**Comment by mariusst** [comment]
There are 2 different packages for pydrive: PyDrive 1.3.1 and PyDrive2 1.8.3
For google-api-client please check the screenshot

![Screenshot (3)](https://user-images.githubusercontent.com/414526/140600064-875fae11-5fbb-4fb4-ad12-c3f1b11f27e0.png)

**Comment by OzzieIsaacs** [comment]
Okay. I'm not convinced that the versions you showed me are the ones which are used by the python interpreter you are using for calibre-web. Please go to admin section -> edit basic-configuration -> Server configuration -> Update channel -> change to Nightly. Go back to admin section search for update and update to the newest nightly version. After update is finished, you should hopefully see a full list of dependencies and could check if the versions used are really fitting to the requirements. 
(For me it's working with the given versions)

**Comment by mariusst** [comment]
I followed your steps but it didn't print the list of dependencies

this is what I have in the About page

> System Statistics
Program Library 	Installed Version
Platform 	Linux 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64
Python 	3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
Calibre_Web 	0.6.15 Beta - 60aa016734970ef31cce784306f5cbac53bbbe22 - 2021-11-06T21:17:48+04:00
Werkzeug 	2.0.2
Jinja2 	3.0.2
pySqlite 	2.6.0
SQLite 	3.27.2
Babel 	2.9.1
Flask-Babel 	2.0.0
Flask-Login 	0.4.1
Flask-Principal 	0.4.0
backports_abc 	0.5
Flask 	1.1.1
iso-639 	0.4.5
PyPDF3 	1.0.3
pytz 	2019.3
requests 	2.21.0
SQLAlchemy 	1.4.26
tornado 	6.0.3
Wand 	0.5.7
unidecode 	1.1.1
lxml 	4.6.4
flask-wtf 	0.15.1
gevent 	21.1.2
greenlet 	1.1.2
httplib2 	0.11.3
oauth2client 	4.1.3
uritemplate 	3.0.1
pyasn1-modules 	0.2.7
pyasn1 	0.4.7
PyDrive2 	1.8.3
PyYAML 	5.1.2
rsa 	3.4.2
six 	1.12.0
google-api-python-client 	1.7.11
google-auth-oauthlib 	0.4.6
goodreads 	0.3.2
python-Levenshtein 	0.12.2
python-ldap 	3.2.0
Flask-SimpleLDAP 	1.4.0
Flask-Dance 	5.0.0
SQLAlchemy-Utils 	0.37.9
rarfile 	4.0
scholarly 	1.2.2
natsort 	8.0.0
comicapi 	2.0
jsonschema 	3.2.0
Image Magick 	ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
ebook converter 	not installed
unrar 	not installed
kepubify 	not installed

I checked six, pydrive2, google-api-python-client package version and matches the version required by calibre-web

**Comment by OzzieIsaacs** [comment]
With the version numbers you gave me it's working for me. Please try to update the dependencies to the maximum allowed version, it should work then. (You claimed six is version 1.16.0, in the list I see the used version is 1.12.0!, so please make sure the dependencies used are getting updated. I know this is sometimes a mess with python)

**Comment by mariusst** [comment]
I update six package to version 1.16.0 and it works. Thanks a lot.
Is it possible to upgrade all packages to the latest version required, not one by one?

**Comment by OzzieIsaacs** [comment]
Something like `pip3 install --target vendor --upgrade -r requirements.txt`
