### ISSUE TITLE
CBR files are unreadable in browser

### ISSUE THREAD

**Issue by rinaldus** [janeczku/calibre-web#2169]
I installed dockerized version of calibre-web. I try to view comic files in browser and all of them are unreadable ([screenshot](https://i.postimg.cc/X4J5pRLy/Screenshot-20211106-192348.png)). I use Vivaldi browser 4.3 (Chromium 94 based). How to fix it?

**Comment by wgibcus** [comment]
> I installed dockerized version of calibre-web. I try to view comic files in browser and all of them are unreadable ([screenshot](https://i.postimg.cc/X4J5pRLy/Screenshot-20211106-192348.png)). I use Vivaldi browser 4.3 (Chromium 94 based). How to fix it?

Have you installed/updated unrar on your server? Scroll to the bottom of the Calibre-web homepage and locate "About" and copy and paste the system statistics in your reply.

**Comment by rinaldus** [comment]
[quote]Have you installed/updated unrar on your server?[/quote]
Yes, it was installed on my system.
[quote]Scroll to the bottom of the Calibre-web homepage and locate "About" and copy and paste the system statistics in your reply.[/quote]
I tried to copy&paste but table  content is breaking when I paste, I made screenshots instead.
[screenshot 1](https://i.postimg.cc/SxVMkc2v/screen1.png)
[screenshot 2](https://i.postimg.cc/N09fSX1T/screen2.png)

BTW, I used [this](https://github.com/linuxserver/docker-calibre-web) docker-compose configuration to install server.

**Comment by OzzieIsaacs** [comment]
For me it's working. Without any context (which would be provided by the information in the form you deleted), I can't help you.
Additional question: 
From what client OS and platform (ARM(iOS, Android), x86, ...) you are accessing the cbr files? 
Do cbz files work? 
Do all cbr files not work?

**Comment by g0tr00t** [comment]
Hi, in web browser console, I see the following error:

Refused to load the image 'blob:http://x.x.x.x/b38c7a0c-0edf-4f31-8c39-6c8d9d5f6033' because it violates the following Content Security Policy directive: "img-src 'self' data:".

The web page resembles same as other posting showing 'corrupt or not an image' error.

**Comment by Jerome2103** [comment]
i have the same problem

**Comment by wgibcus** [comment]
I can confirm this problem in 0.6.14 stable release. Issue is resolved in latest beta.

**Comment by rinaldus** [comment]
> I can confirm this problem in 0.6.14 stable release. Issue is resolved in latest beta.

How can I install it? The latest commit, you did, was 5 days ago.

**Comment by wgibcus** [comment]
> > I can confirm this problem in 0.6.14 stable release. Issue is resolved in latest beta.
> 
> How can I install it? The latest commit, you did, was 5 days ago.

Admin - Edit Basic Configuration - Update Channel. Change "Stable" to "Nightly" and save. Then update as usual. If you are unhappy with the nightly release, you can roll it back to stable by reversing the procedure.

**Comment by rinaldus** [comment]
> > > I can confirm this problem in 0.6.14 stable release. Issue is resolved in latest beta.
> > 
> > 
> > How can I install it? The latest commit, you did, was 5 days ago.
> 
> Admin - Edit Basic Configuration - Update Channel. Change "Stable" to "Nightly" and save. Then update as usual. If you are unhappy with the nightly release, you can roll it back to stable by reversing the procedure.

It works now! Thank you very much!
