### ISSUE TITLE
Having a trouble with searching which uses 2-bytes language(korean).

### ISSUE THREAD

**Issue by abubaman** [janeczku/calibre-web#217]
I am a user of calibre-web and it works fine.

but i have a trouble with searching functionality. when I have tried to search 'title in korean', sometimes they can find books, but sometimes they can not find books even though their titles have same word which i typed in search text area.

So how can I solve this problem?

**Comment by OzzieIsaacs** [comment]
could you give me a working and a non working title example (I can than generate book entries in my library with these and check it)

**Comment by OzzieIsaacs** [comment]
No response for long time
