### ISSUE TITLE
Default sort order changes for anonymous browsing

### ISSUE THREAD

**Issue by wgibcus** [janeczku/calibre-web#2174]
**Describe the bug/problem**
The default sort order for anonymous browsing changes from newest first to alphabetical order in 0.6.15 beta. In UI configuration,  "Allow Uploads", "Allow Edit" and "Allow Delete Books" are not available in " Default Settings for New Users". The bug is not present in 0.6.14 and rolling back to the stable release resolves any issues.

**To Reproduce**
- update to latest nightly release 

No action is required to fix as rolling back to stable release resolves the issue. This is purely informational.

**Comment by OzzieIsaacs** [comment]
I can only partly reproduce this:

> The default sort order for anonymous browsing changes from newest first to alphabetical order in 0.6.15 beta

Correct, I changed it. I didn't think of the guest user, I have to reconsider my change

> In UI configuration, "Allow Uploads", "Allow Edit" and "Allow Delete Books" are not available in " Default Settings for New Users". 

It's true, the upload checkbox is now invisible as long as you don't have upload enabled ( I got to may questions regarding I granted the right and it's not visible)
The delete button is also invisible as long as the edit right isn't granted. The delete role is a sub role of edit role, if you are not allowed to edit you are not allowed to delete, even if only delete is ticked


![grafik](https://user-images.githubusercontent.com/6438895/140957973-23df22da-5407-4407-b077-bd6842fef9c6.png)

**Comment by wgibcus** [comment]
Thanks for looking into those issues. I'd prefer to have the choice for the default sort order for guest users if that's possible. If this means changing the code, that's fine but a drop down choice list or similar would be great :)
