### ISSUE TITLE
LDAP user unable to send to kindle

### ISSUE THREAD

**Issue by maxleonca** [janeczku/calibre-web#2176]
**Describe the bug/problem**
When an LDAP user without admin privileges tries to send a book to their kindle, gets an 403.

**To Reproduce**
1. Configure LDAP
2. Import users
3. Configure kindle address
4. Log in as LDAP user with kindle address configured
5. Pick a book and click "Send to Kindle"

**Logfile**
Nothing on the log file, I think something on the front end prevents the request to be sent to the backend.

**Expected behavior**
Send the selected item to the users Kindle.

**Screenshots**
![403 on click](https://user-images.githubusercontent.com/952322/141005771-74467b07-170f-4b8f-9383-986360532a0b.png)

**Environment (please complete the following information):**
 - OS:  docker on Archlinux
 - Python version: 
 - Calibre-Web version: 
 - Docker container: [LinuxServer]:lscr.io/linuxserver/calibre-web:latest
 - Special Hardware: 
 - Browser: google-chrome 95.0.4638.69, opera 81.0.4196.31, firefox 94.0.1

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

**Comment by maxleonca** [comment]
I've been doing some testing and I found out 2 things.  All LDAP users admin or not are unable to send to kindle, but if I remove the user and re-imprt it from LDAP, then it Send to Kindle, works.

**Comment by OzzieIsaacs** [comment]
I can't reproduce this (seems like on the first import something went wrong on your side).
Are you sure the not working user have all right needed to send to kindle? Or if you compare a now working one with a non working one, what are the differences in permissions?
