### ISSUE TITLE
Canno't access "admin" nor add or edit users....

### ISSUE THREAD

**Issue by nomadelog** [janeczku/calibre-web#2187]
**Describe the bug/problem**
A clear and concise description of what the bug is. If you are asking for support, please check our [Wiki](https://github.com/janeczku/calibre-web/wiki) if your question is already answered there.

**To Reproduce**

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10/Raspberry Pi OS]
 - Python version: [e.g. python2.7]
 - Calibre-Web version: [e.g. 0.6.8 or 087c4c59 (git rev-parse --short HEAD)]:
 - Docker container: [None/LinuxServer]:
 - Special Hardware: [e.g. Rasperry Pi Zero]
 - Browser: [e.g. Chrome 83.0.4103.97, Safari 13.3.7, Firefox 68.0.1 ESR]

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

**Comment by nomadelog** [comment]
![calibre_error](https://user-images.githubusercontent.com/8586018/143048993-31ade7bc-23e7-467a-b243-04d9349eab8d.PNG)

**Comment by nomadelog** [comment]
That error comes up when clicking on "admin", or trying to edit or add users...

**Comment by OzzieIsaacs** [comment]
There is a missing language translation, I‘ll fix it

**Comment by OzzieIsaacs** [comment]
Please update to the newest nightly version, should work now

**Comment by nomadelog** [comment]
Hi, thank you for fixing it so fast....I would like to know the exact tag i
should be using, for both arm32 and arm64 ??

Have a nice day
;-)

Le mar. 23 nov. 2021 13 h 33, Ozzie Isaacs ***@***.***> a
écrit :

**Comment by OzzieIsaacs** [comment]
Hard to guess. You didn't fill out the form, so I don't know your hardware (and I don't know docker, which you might refer to), for Rasberry Pi it's most likely arm64(?), don't know
