### ISSUE TITLE
[Enhancement] Option to merge books of the same name and author

### ISSUE THREAD

**Issue by mercurycoolman** [janeczku/calibre-web#219]
If possible could an option be added to merge books of the same name and author for different filetypes. I have a .mobi of a book that shows no cover but i want to merge with a .pdf and have them all show on the same book page so i can select which file type i would like.

Thanks for any input in advance.

**Comment by Kyosfonica** [comment]
The functionality of handling differents formats of the same book is there. What should be implemented are the form and the backend responsible of uploading a new format of a book and put that info in the database

What I wouldn't do is to merge uploaded books into one single entry. The proper way to do this is to update an already uploaded book and add the new file to it. This way prevents unwanted duplicated book entries in the database.

I will give it a try in my spare time.

This is what you would like to see, isn't it?
![image](https://user-images.githubusercontent.com/5280026/28833104-b2421e5e-76de-11e7-97ca-56dd08f66477.png)

**Comment by OzzieIsaacs** [comment]
Finally...
There is a new option in the navbar, where you can (manually) select books and merge them

**Comment by dsm1212** [comment]
I'm a little confused on mulit-format, lets say I have a book with 2 formats. In Calibre I can group them and they show as one book. After this in calibre-web I see 2 of the book, only the first one has an image and a download link. The other is a ghost which has no image and no content. If I edit the ghost and add an image I then see 3 books - One with a download link and image, one with an image but no download link and the 3rd is a ghost again. I must be doing something wrong. This bug solution sounds like the feature in calibre but this is calibre-web issues, no?
