### ISSUE TITLE
use gevent.monkey to improve concurrency

### ISSUE THREAD

**Issue by Yxa2111** [janeczku/calibre-web#2193]
**Is your feature request related to a problem? Please describe.**

I found calibre-web can use gevent as web server, But there are many of sync python  standard library API in this project and some 3-rd party library. In some of case they may block the entire thread. If the call takes a long time, the server can't serve following request in this period until the sync call returned. gevent and coroutine can't work best in this case.

**Describe the solution you'd like**

gevent provide some API of asynchronous version like `gevent.os`, but replaceing all of them for gevent is impractical. So they provide `gevent.monkey` to replace the python std lib with their async version in the run-time, and It's also useful for 3rd party library.

Using `gevent.monkey` is easy, we just need two lines:
```
from gevent import monkey
monkey.patch_all()
```

 [See more in the link](http://www.gevent.org/api/gevent.monkey.html)

**Additional context**

In fact, I use rclone mount a cloud drive and put some books to it. calibre-web works well in the most case
 except when downloading or uploading books. If the book file is big, calibre-web will block and I can't even visit the homepage at the same time! So I try to solve it. After I use `gevent.monkey`, the problem improved much. So is it necessnary to use it?

**Comment by OzzieIsaacs** [comment]
Is implemented in 0.6.17

**Comment by OzzieIsaacs** [comment]
I'll have to revert this, a lot of people are having trouble with "database locked" after implementing this. 

So it's a won't implement
