### ISSUE TITLE
Filtering by extension in Advanced Search always returns no results

### ISSUE THREAD

**Issue by YMan84** [janeczku/calibre-web#2198]
*Describe the bug/problem**
When doing an advanced search, and selecting an extension, or checking "Select All" in the include dropdown, the search always returns "no results found". 

**To Reproduce**
1. Go to advanced Search
2. Select an extension or multiple extensions to be included  
3. Click the search button

**Expected behavior**
The results should display all my books that have the file extension that i selected from the dropdown. 

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Python version: Python 3.9.7
 - Calibre-Web version: 0.6.14
 - Browser: Firefox/Brave

**Comment by OzzieIsaacs** [comment]
I think I fixed this.
Please update to the newest nightly version (admin -> basic configuration -> server -> update channel -> nightly)
