### ISSUE TITLE
Support Keycloak as single-sign-on option

### ISSUE THREAD

**Issue by decentral1se** [janeczku/calibre-web#2199]
**Is your feature request related to a problem? Please describe.**

I have self-hosted oauth/single-sign-on where accounts are stored in a https://www.keycloak.org instance.

**Describe the solution you'd like**

Support https://www.keycloak.org as an oauth config option.

**Describe alternatives you've considered**

Tried to use the github/google auth with an ID/secret but it doesn't work.

**Additional context**

I can try to implement this if you like.

**Comment by decentral1se** [comment]
Looking at https://github.com/janeczku/calibre-web/pull/673 to see if I could base this work on that :eyes:

**Comment by OzzieIsaacs** [comment]
Sorry. 
I will not implement any more login routines (https://github.com/janeczku/calibre-web/blob/master/CONTRIBUTING.md#feature-request)

**Comment by decentral1se** [comment]
hey @OzzieIsaacs, that is fair enough. I know a few groups who would love to see this implemented tho and I am fully prepared to implement it myself. However, as a maintainer of other projects, I do understand that it is not just implementation that needs effort but also taking care of the code later on. So, is there some compromise we can find here together? Is there any way that this login routine code can be made pluggable? I can maintain a separate package and the installation can be done optionally? I would also note that keycloak supports many additonal integrations, see [here](https://www.keycloak.org/docs/latest/server_admin/index.html#social-identity-providers), so it can be become a way for people to integrate in other ways without further implementation in the code here. Thanks for your time!
