### ISSUE TITLE
Not being able to log in.

### ISSUE THREAD

**Issue by dominus-imperium** [janeczku/calibre-web#2215]
**Describe the bug/problem**
I have set up calibre web but when i try to log in through the website it say incorrect username or password. first i thought it was my fault and i thought i had changed the defalut by mistake. I reset the password various ways using the -s flag and even replacing the app.db entry for the password with another cipher. But nothing is working. currently i am getting this warning in the logs : [2021-12-10 09:27:50,354]  WARN {cps.web:1576} Login failed for user "admin" IP-address: . other than that i dont know where to look to solve this.

Another thing that may be related is that the set up was filled with errors and i had to reinstall it by deleting the calibre-web folder and reinstalling and i am on linux mint. Also, for some reason if i use the cps.py file outside of sudo or root i get a sqlalchemy error.

**Comment by OzzieIsaacs** [comment]
Looks like you have some confusion about the python dependencies. How did you install calibre-Web?

**Comment by OzzieIsaacs** [comment]
A duplicate of #2157

**Comment by dominus-imperium** [comment]
I installed it by cloning this repository and running pip 3 command against the requirements.txt with the system flag as the wiki for linux mint 20 says. I don't know if this is related but i run the `python3 cps.py `command with the flag `-p /directory/metadata.db`  This directory is actually a rclone mount. The first time i installed it it was working fine but i had some problems with rclone so as soon as i started using it again it says invalid password even if it is right. and the log i have already stated is the same.

**Comment by dominus-imperium** [comment]
Ok, thank you so much for you willingness to help. Luckily i found the solution to my problem:

1. -p command is not for the calibre db file - this was my mistake
2. The real problem was that in my rclone mount folder containing my metadata.db file was not being realised by calibre web was because of a flag missing when mounting : The command should have said `rclone mount --vfs-cache-mode=full --file-perms=0777 cloud:Calibre_Folder local:mount_point`  The file perms and vfs-cache flags are crucial.
3. The admin was not loggin in because of 1 - which again was me not reading the command flag description properly.
