### ISSUE TITLE
Improve chinese locale translations

### ISSUE THREAD

**Issue by dztsg** [janeczku/calibre-web#2218]
OzzieIsaacs：

I have a suggestion，I hope you can understand and agree：

calibre-web   user_edit.html   language:

中文（简体，中国）  change to： 中文（简体） or  简体中文

中文（繁體，台灣）  change to： 中文（繁體） or  繁體中文

Thank you very much!

**Comment by OzzieIsaacs** [comment]
Difficult.
I think this are the strings for choosing the 2 Chinese languages. The underlying library in python (the programming language) is generating this strings, so not so easy to remove the Hans/Hant part

**Comment by dztsg** [comment]
> 难的。 我认为这是选择2种中文语言的字符串。python（编程语言）中的底层库正在生成这些字符串，因此删除 Hans/Hant 部分并不容易

OzzieIsaacs：

I'm very glad that you replied to me quickly. Thank you very much!

I ask you to do your best to help solve this problem. Thank you again!

calibre-web   user_edit.html   language:

中文（简体，中国）  change to： 中文（简体） or  简体中文

中文（繁體，台灣）  change to： 中文（繁體） or  繁體中文

Thank you very much!

**Comment by dztsg** [comment]
OzzieIsaacs：

I'm very glad that you replied to me quickly. Thank you very much!

I ask you to do your best to help solve this problem. Thank you again!

calibre-web   user_edit.html   language:

中文（简体，中国）  change to： 中文（简体） or  简体中文

中文（繁體，台灣）  change to： 中文（繁體） or  繁體中文

Thank you very much!

**Comment by dztsg** [comment]
OzzieIsaacs：

I'm very glad that you replied to me quickly. Thank you very much!

I ask you to do your best to help solve this problem. Thank you again!

calibre-web user_edit.html language:

中文（简体，中国） change to： 中文（简体） or 简体中文

中文（繁體，台灣） change to： 中文（繁體） or 繁體中文

Thank you very much!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "janeczku/calibre-web"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月14日(星期二) 凌晨0:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [janeczku/calibre-web] Suggestion (Issue #2218)





 
Difficult.
 I think this are the strings for choosing the 2 Chinese languages. The underlying library in python (the programming language) is generating this strings, so not so easy to remove the Hans/Hant part
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by OzzieIsaacs** [comment]
I translated the chinese string to english. 
It's not what I expected in case of strange "Hans/Hant" words, it's only China and Taiwan, so I don't see the problem. This texts are not comming from calibre-web itself, but form the used library "Babel", so even I I would be willing to change it, I could not do so. 
I'll close the issue for this reason

**Comment by dztsg** [comment]
You have made great efforts in this matter. I thank you very much! I hope you can have a better solution in the future. Thank you again!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "janeczku/calibre-web"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月19日(星期天) 下午5:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [janeczku/calibre-web] Improve chinese locale translations (Issue #2218)





 
I translated the chinese string to english.
 It's not what I expected in case of strange "Hans/Hant" words, it's only China and Taiwan, so I don't see the problem. This texts are not comming from calibre-web itself, but form the used library "Babel", so even I I would be willing to change it, I could not do so.
 I'll close the issue for this reason
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
