### ISSUE TITLE
Upload button not being shown

### ISSUE THREAD

**Issue by adamtg** [janeczku/calibre-web#2224]
I am running 0.6.14.  I went to Admin->Edit Users and i selected "Allow Upload" for all my users.  But the upload button never appears.  I tried clearing out my cache, but it still is not showing up.

**Comment by OzzieIsaacs** [comment]
Please enable uploading feature in basic  settings first

**Comment by naclander** [comment]
@OzzieIsaacs  I just ran into this issue as well. It is not very clear that enabling uploads need to be done. Is it possible to either:

* Enable it by default 
* Add to README or wiki a statement saying how to enable this
