### ISSUE TITLE
Log4j Vulnerability Evaluation?

### ISSUE THREAD

**Issue by Torqu3Wr3nch** [janeczku/calibre-web#2225]
More of a question (and not really declaring a security vulnerability), but has calibre-web been evaluated for the log4j vulnerability?

**Comment by OzzieIsaacs** [comment]
Yes. Calibre-Web is a python program, therefore not using Java, and not using the Java logging feature log4j

**Comment by OzzieIsaacs** [comment]
I added a statement regarding this in the security.MD file
