### ISSUE TITLE
Error related to upgrade of python to 3.8 

### ISSUE THREAD

**Issue by McColdewey** [janeczku/calibre-web#2227]
**Describe the bug/problem**
A clear and concise description of what the bug is. If you are asking for support, please check our [Wiki](https://github.com/janeczku/calibre-web/wiki) if your question is already answered there.

On a fresh install of calibre-web after an upgrade of ubuntu's python (on ubuntu 20.04) to python version 3.8.10, cps fails to start.

**To Reproduce**
1. On a working ubuntu system with calibre-web running as a service, after upgrade of python to version 3.8 calibre-web fails to start.
2. cps also fails.
3. In both cases the error message is: "**Error starting server: an integer is required (got type bytes)**"
4. Previously calibre-web was working without issue on my system.
5. The issue appears to be a known issue also affecting other python based software packages.

**Expected behavior**
cps to start normally.

**Screenshots**
Not applicable.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python version: 3.8.10, GCC 9.3.0, on linux
 - Calibre-Web version: Latest as of today
 - Docker container: None.
 - Special Hardware: None, standard VPS.
 - Browser: Not relevant.

**Additional context**
See: 
- https://github.com/pyinstaller/pyinstaller/issues/4265 
- https://stackoverflow.com/questions/58700384/how-to-fix-typeerror-an-integer-is-required-got-type-bytes-error-when-tryin
- https://www.reddit.com/r/bigdata/comments/no448p/i_need_help_pyspark_typeerror_an_integer_is/
for related error messages in other packages

**Comment by OzzieIsaacs** [comment]
My guess is that tornado (the server component of calibre-web) is too old.
Could you please try to update it, something like `python -m pip install tornado -u`, should do it. (Exact command depends on how you installed calibre-web). Please also consider to update all dependencies, with something like `python -m pip --install --u --requirement requirements.txt`

**Comment by McColdewey** [comment]
I installed calibreweb using pip (pip install calibreweb). Initially I had it installed through root, but I have now installed as user. Other than the location of the cps script, this shouldn't make a difference though. 

I have run `python3 -m pip --install --u --requirement requirements.txt, and it goes through the list and says all dependencies are satisfied. `

`Running "python3 -m pip install tornado" results in "`Requirement already satisfied: tornado in /usr/local/lib/python3.8/dist-packages (6.1)"; I can't get it to run with the "-u" switch, it says: "no such option".

Jon

**Comment by OzzieIsaacs** [comment]
Sorry, should be capital ‚U‘. 
Do you also have installed gevent (from optional-requirements file)?

**Comment by OzzieIsaacs** [comment]
Google thinks yes you have (https://github.com/gevent/gevent/issues/1513). Could you please try to either remove gevent (if you don‘t need it for something else), or try to update as described above (with -U option)

**Comment by McColdewey** [comment]
Before I read your message below to uninstall geevent, I went ahead and installed the whole "optional-requirements.txt" list, and low and behold, the application now works. Sorry if that now means we don't know which component exactly was broken by the python upgrade, but something inside of optional requirements fixed it!

Many thanks, I'm happy again .. I'm a big fan of calibre and calibre-web. Fantastic work!

Best wishes, Jon

**Comment by OzzieIsaacs** [comment]
Only gevent could have generated it. in the next version there will be a depends check available to log this type of problems

**Comment by McColdewey** [comment]
I can confirm: I uninstalled the "optinal-requirements.txt" list and then installed only gevent, and cps works fine. 
Thanks again! Jon
