### ISSUE TITLE
Considering about OneDrive as storage?

### ISSUE THREAD

**Issue by orange2008** [janeczku/calibre-web#2229]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It seems like using OneDrive as library is a pretty good choice as they are usually cheaper than Google Workspace.
I have about 600 GB of e-books and I just get bored paying the server hard drive fee, but I've applied Microsoft E5 Developer, which includes 25 TB of storage. As far as I can tell, Microsoft Graph provides a lot of useful APIs that can access the files in OneDrive. That will be pretty sweet.
**It shouldn't be that hard, is it?**

**Describe alternatives you've considered**
Using rclone & fuse, mount them. But they are SLOOOOOOOW.

**Additional context**
Both Google Drive & OneDrive are using RESTful as their API, so I think it won't be that hard.
Please... I will be very happy if you can add OneDrive support.

**Comment by OzzieIsaacs** [comment]
No more storage backends, sorry.
https://github.com/janeczku/calibre-web/blob/master/CONTRIBUTING.md#feature-request
