### ISSUE TITLE
Syncing more than one kobo device with the library breaks syncing.

### ISSUE THREAD

**Issue by echto** [janeczku/calibre-web#2230]
**Describe the bug/problem**
Syncing more than one kobo device with the library breaks syncing.

**To Reproduce**
1. Create user1 and generate sync token.
2. Sync user1 kobo with library succeeds.
3. Create user2 and generate sync token.
4. Sync user2 kobo with library fails.  See log below.
5. Sync user1 kobo with library fails with same ` Kobo library sync request received` log entry.

**Logfile**

[2021-12-18 18:51:03,947]  INFO {cps.kobo:140} Kobo library sync request received.
[2021-12-18 18:51:04,270]  INFO {cps.kobo:140} Kobo library sync request received.
[2021-12-18 18:51:04,595]  INFO {cps.kobo:140} Kobo library sync request received.
[2021-12-18 18:51:04,914]  INFO {cps.kobo:140} Kobo library sync request received.
[2021-12-18 18:51:05,249]  INFO {cps.kobo:140} Kobo library sync request received.
[2021-12-18 18:51:05,575]  INFO {cps.kobo:140} Kobo library sync request received.
[2021-12-18 18:51:05,895]  INFO {cps.kobo:140} Kobo library sync request received.
[2021-12-18 18:51:06,212]  INFO {cps.kobo:140} Kobo library sync request received.
[2021-12-18 18:51:06,549]  INFO {cps.kobo:140} Kobo library sync request received.
[2021-12-18 18:51:06,870]  INFO {cps.kobo:140} Kobo library sync request received.
[2021-12-18 18:51:07,200]  INFO {cps.kobo:140} Kobo library sync request received.
[2021-12-18 18:51:07,518]  INFO {cps.kobo:140} Kobo library sync request received.
[2021-12-18 18:51:07,846]  INFO {cps.kobo:140} Kobo library sync request received.
[2021-12-18 18:51:08,215]  INFO {cps.kobo:140} Kobo library sync request received.
[2021-12-18 18:51:08,549]  INFO {cps.kobo:140} Kobo library sync request received.
[2021-12-18 18:51:08,885]  INFO {cps.kobo:140} Kobo library sync request received.
[2021-12-18 18:51:09,209]  INFO {cps.kobo:140} Kobo library sync request received.
[2021-12-18 18:51:09,525]  INFO {cps.kobo:140} Kobo library sync request received.
[2021-12-18 18:51:09,848]  INFO {cps.kobo:140} Kobo library sync request received.
[2021-12-18 18:51:10,268]  INFO {cps.kobo:140} Kobo library sync request received.
[2021-12-18 18:51:10,615]  INFO {cps.kobo:140} Kobo library sync request received.
[2021-12-18 18:51:10,955]  INFO {cps.kobo:140} Kobo library sync request received.
[2021-12-18 18:51:11,282]  INFO {cps.kobo:140} Kobo library sync request received.
[2021-12-18 18:51:11,598]  INFO {cps.kobo:140} Kobo library sync request received.
[2021-12-18 18:51:11,916]  INFO {cps.kobo:140} Kobo library sync request received.
[2021-12-18 18:51:12,242]  INFO {cps.kobo:140} Kobo library sync request received.
[2021-12-18 18:51:12,571]  INFO {cps.kobo:140} Kobo library sync request received.
[2021-12-18 18:51:12,904]  INFO {cps.kobo:140} Kobo library sync request received.

**Expected behavior**
A successful sync with the library.

**Environment**

Platform | Linux 5.15.7-gentoo-x86_64 #1 SMP PREEMPT Mon Dec 13 13:59:55 PST 2021 x86_64 
Python 3.9.9 (main, Dec  3 2021, 17:10:51)  [GCC 10.3.0]
Calibre_Web 0.6.14 - 4da64ceb23e69da3953f9c454ea261d9d0621e25 - 2021-10-31T11:31:53+01:00
WebServer 	Tornado 6.1
Flask 	2.0.2
Flask_Login 	0.5.0
Flask_Principal 	0.4.0
Flask_WTF 	1.0.0
Werkzeug 	2.0.2
Babel 	2.9.1
Jinja2 	3.0.3
Requests 	2.26.0
SqlAlchemy 	1.4.28
pySqlite 	2.6.0
SQLite 	3.35.5
iso639 	0.4.5
pytz 	2021.3
Unidecode 	installed
Scholarly 	not installed
jsonschema 	3.2.0
greenlet 	1.1.2
Image Magick 	ImageMagick 7.1.0-13 Q16 x86_64 2021-10-29 https://imagemagick.org
PyPdf 	v1.0.5
lxml 	v4.6.5.0
Wand 	0.6.7
Comic_API 	not installed
ebook converter 	not installed
unrar 	UNRAR 6.02 freeware Copyright (c) 1993-2021 Alexander Roshal
kepubify 	not installed

**Additional context**
Accessed via nginx reverse proxy.

**Comment by OzzieIsaacs** [comment]
Please update to the newest nightly version, it should work then

**Comment by echto** [comment]
Unfortunately the newest nightly version did not fix the problem.  Please see included pastebin links for logs.  Log entries for 'Kobo Sync Content' have been removed from the logs to make the logs easier to read.

Here is what I did.  I updated to the latest nightly and added a second user and generated a kobo sync token for the second kobo.  I initiated a sync on the second kobo device which eventually was aborted because the number of synced books shown on the kobo was greater than the number of books in the library.  Looking at the log it appears the sync to the second kobo device is stuck in a loop.  Here is the sync log for the second kobo device.

http://dpaste.com/HNN2M4P3F

Interesting note, there are only 980 books in the library but the sync sees 1960 books.


The first kobo device was able to sync successfully until now.  Here is the sync log for the first kobo device after the unsuccessful sync with the second kobo device. The device now also appears to be stuck in a sync loop.

http://dpaste.com/CKXURXTA3

**Comment by echto** [comment]
I initiated a full resync for the first kobo device and here is the log.

https://dpaste.com/8RK2BPJ36

Now the sync for the first device sees 1960 books as well.  There are only 980 books in the library.

**Comment by OzzieIsaacs** [comment]
I have no idea. 
For further investigation I would need the app.db file and the metadata.db file (if possible). Please send it to my personal email address listed on my profile.

**Comment by vvignaux** [comment]
I observe the exact same issue using the latest docker image. Looking at the logs, it seems this behavior started about two months ago.

>  I initiated a sync on the second kobo device which I eventually aborted because the number of synced books shown on the kobo was greater than the number of books in the library. Looking at the log it appears the sync to the second kobo device is stuck in a loop. 
> The first kobo device was able to sync successfully until now. Here is the sync log for the first kobo device after the unsuccessful sync with the second kobo device. The device now also appears to be stuck in a sync loop.

**Comment by frameset** [comment]
I am also having the same issue. @echto did you manage to get back to it working with just one Kobo for now?

**Comment by echto** [comment]
> I am also having the same issue. @echto did you manage to get back to it working with just one Kobo for now?

Yes.  The only solution I found was to delete app.db and limit to syncing one kobo device until the issue is resolved.

**Comment by frameset** [comment]
I've found switching to the nightly build and clearing the sync history has
helped me sync a bunch more, but not all of them. Hopefully this feature
gets some love, because it's by far the coolest thing I've seen in the
wireless sideloading space in a long time.

**Comment by frameset** [comment]
As a workaround to let my partner sync her Kobo as well, I used docker-compose to set up a second instance of calibre-web with it's own config directory. It's not the cleanest solution, but it works.

**Comment by echto** [comment]
> As a workaround to let my partner sync her Kobo as well, I used docker-compose to set up a second instance of calibre-web with it's own config directory. It's not the cleanest solution, but it works.

That is one option.  Do you share the same library directory or do you include the library in both instances which basically doubles the disk usage?  If you do share the same library between the instances have your encountered any issues when adding, deleting, or editing any books?

**Comment by frameset** [comment]
I share the library directory from the host computer, but her instance is
mounted as read only. Calibre-web detects this and notifies you in the UI.
Perhaps it also disables the features that require wrote access?

**Comment by echto** [comment]
> I share the library directory from the host computer, but her instance is mounted as read only. Calibre-web detects this and notifies you in the UI. Perhaps it also disables the features that require wrote access?
>

I do not think that is the issue, my library is inside my VM .  I see there is a new beta,

Calibre_Web | 0.6.15 Beta - 6d839d5cc71cbb8f839fb95365f838d8fd01f94c - 2022-01-04T21:12:59+01:00

I'm going to give that a try.

**Comment by OzzieIsaacs** [comment]
I now can reproduce the behavior, the problem is that the 2. user gets the same session id as the first one (there is nothing you can do with this information)

**Comment by echto** [comment]
It appears to be fixed in the latest build.  Thank you.

**Comment by OzzieIsaacs** [comment]
Cool

**Comment by 0dragosh** [comment]
I still experience the same behavior on 0.6.15.

Trying to sync two Kobo Sages with the same calibre-web instance(different accounts), they end up not being able to sync and stuck in a loop with the number of books on the Sage constantly growing (I canceled the sync at 100 000+ "books", there are only about 100 in the actual library)

**Comment by AtomicRPM** [comment]
Have to tried forcing a complete resync?

**Comment by echto** [comment]
This is confirmed. Something has happened.
Multi kobo user syncing is not working for me anymore.

I’m restoring a backup I made prior to updating to latest nightly to troubleshoot.

**Comment by echto** [comment]
ok I restored to

Calibre_Web 0.6.15 Beta - 0feb62c142bac7818ff4947218e6b3789098522f - 2022-01-09T17:43:20+01:00

and multi user sync was broken still when I know it worked before.

I factory reset the second Kobo device and syncing still would not happen. I deleted the existing kobo token and generated a new one. syncing still failed with 0 books to sync.

I deleted the second calibre-web user then recreated the second user. I generated the new token and updated the kobo.conf file. Success. The second kobo successfully synced. odd.

So as it is now with this version, 2022-01-09T17:43:20+01:00 , I have two separate calibre-web users each with their own kobo device successfully syncing.

**Comment by 0dragosh** [comment]
Whelp. I tried re-creating my user and sync token and it still doesn't sync properly.

**Comment by echto** [comment]
Something must have changed between the nightly builds. In the mean time I will stick with the nightly build that works. I have no idea if each nightly is available for downloading. I suggest creating a new bug issue.

**Comment by 0dragosh** [comment]
> > Edit: updating to `0.6.16` seems to have fixed _one device_ out of the two, for now. I'll have to test the second Kobo to see if that works.
> 
> The only thing I did not try with the latest was deleting and re creating the second user.

Yeah I tried that previously with no results.

**Comment by Thovi98** [comment]
FYI I've just tried to sync two users with their Kobo device (one for each user) and it works flawlessly 💯
I use latest stable Calibre-web version.
