### ISSUE TITLE
Google Scholar metadata provider is broken

### ISSUE THREAD

**Issue by cbartondock** [janeczku/calibre-web#2237]
I think it has something to do with the refactor that created the file `cps/metadata_provider/scholar.py`. 

The cover is replaced with the "Cover not available" image (I would actually call this not desirable behavior - previously it just got set to the first page of the paper which was much better), but no other meta is populated. Worse, the file will no longer open and it seems even gets *deleted* by attempting to set the metadata via google scholar.

Obviously this is a very serious bug as it could lead to data loss.

**Comment by cbartondock** [comment]
I believe  the issue occurred here https://github.com/janeczku/calibre-web/commit/1e1d3a7c81fbf12921303c3108feb6b673b8d474#diff-c53f5dabe25a508140e5d45c04c062dacc8fa9c2afca044bf6f78c8978093b77

when the scholarsearch route was removed from editbooks.

**Comment by cbartondock** [comment]
As an aside I am noticing that the system statistics (the versions of various python libraries) are not updating when the versions of those libraries change.

**Comment by OzzieIsaacs** [comment]
Thanks for the fix, it's merged
