### ISSUE TITLE
HTTPS Reverse Proxy Help

### ISSUE THREAD

**Issue by dabigc** [janeczku/calibre-web#224]
Hello, 

First let me say that I'm REALLY happy to have found this project. It breathes new life into Calibre management for those of us who want to do so on a headless machine and it's a beautiful interface.

I'm using [this method](https://www.htpcguides.com/secure-nginx-reverse-proxy-with-lets-encrypt-on-ubuntu-16-04-lts/) to secure my server and then using Docker images behind it for all of the applications I'm running from this server, including calibre-web. When I use the example nginx configuration I'm only getting the HTML and no CSS or javascript as far as I can tell ([example](http://coco.d.pr/8Kn6hz)). My nginx location config for calibre-web is listed below. My hope is that someone would be able to help me understand why it's not giving anything but the HTML and if there's some configuration adjustments I can make that should correct. Any help is greatly appreciated!

# Calibre-web
 location /calibre {
    proxy_bind $server_addr;
    proxy_pass http://127.0.0.1:8083;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Scheme $scheme;
    proxy_set_header X-Script-Name /calibre;
 }

**Comment by OzzieIsaacs** [comment]
Are you using the docker image?

**Comment by dabigc** [comment]
I am. I know it has its own nginx implementation and the ability to use your own SSL certificate but I'm not sure if that will work with the reverse proxy front-end I'm already using or not. If it will or you think it will and you have an idea of what I could try, please let me know. Thank you for your help!

**Comment by OzzieIsaacs** [comment]
The problem is that the docker container is not made for running behind another proxy. You could try the suggestions from #112

**Comment by OzzieIsaacs** [comment]
Maybe a different container like suggested in #196 could help, too

**Comment by CHBMB** [comment]
I've made a docker container that works behind a LetEncrypt reverse proxy.

https://hub.docker.com/r/chbmb/calibre-web/

Instructions are here.

https://github.com/linuxserver/docker-calibre-web/tree/alpine.python3.6
