### ISSUE TITLE
With SSL offloading this will define http as scheme instead of https

### ISSUE THREAD

**Issue by delcroip** [janeczku/calibre-web#2240]
Hi

Thank for the work, it really amazing to be able to hook my Kobo but I had to hard code the "https" because I am using Haproxy as reverse proxy for all my docker-compose

This line should be based on config as the port

https://github.com/janeczku/calibre-web/blob/1be7dfcdca7a3c9be08387dfa795f1d565ed266e/cps/kobo.py#L367

Same for the api_endpoint config but it is a details and can be fixed amanually when copying the config in Kobo reader config

I could have a look but I  have too many PR on opensource project so it will take time if I do it.

br

**Comment by OzzieIsaacs** [comment]
If your proxy sets "X-Scheme" in the header to "https" this should work out of the box without any config option. Or if you access calibre-web via https and http via your proxy there should be a variable to forward the current scheme.
Currently I'm not convinced that we need a config option to handle this in calibre-web.

**Comment by OzzieIsaacs** [comment]
Maybe like this (opinion of Google, untested):
` http-request add-header X-Scheme https if { ssl_fc }`

**Comment by delcroip** [comment]
Thx, I will give it a try
