### ISSUE TITLE
Suggestion: trim white space in search entry 

### ISSUE THREAD

**Issue by jeff47** [janeczku/calibre-web#2243]
**Describe the bug/problem**
Search for a book title, then try the same title with a space added after the name.  The search will not find a book named "Beloved" if you search for "Beloved ".  I realize that's not technically a bug, but may be confusing and unexpected to some users.  The convention in most word search features in software seems to be trim white space.

**To Reproduce**
1. Search for a book in your library 
2. Search for the same book title but with a space added at the end

Again, I don't think this qualifies as a bug but I'm curious if anyone else thinks this could be confusing.

**Comment by OzzieIsaacs** [comment]
This is indeed a bug, for the advanced search it was working as expected. I have some more changes in the pipeline which need to be tested, so I think I will have it fixed by beginning of January
