### ISSUE TITLE
Miscellaneous errors

### ISSUE THREAD

**Issue by yeraycito** [janeczku/calibre-web#2247]
1 - When updating Calibre-web via the night channel the requirements.txt file reverts to the default options.

2 - Error SSL Tornado

![Screenshot_20211230_191328](https://user-images.githubusercontent.com/65027248/147778579-1ba9052a-5e88-4530-97a3-1693465804d0.png)

**Comment by OzzieIsaacs** [comment]
1.) That correct. Please don't change the file content. I had many times problems with api's changing with newer versions, so I limit them to version, where I know they are working
2.) This looks to me like ssl errors caused by untrusted certificates (do you use self signed certificates?)

**Comment by yeraycito** [comment]
2.) This looks to me like ssl errors caused by untrusted certificates (do you use self signed certificates?):

Yes, The problem has been solved. The error occurred after updating Calibre-web and resetting the required components to default settings. Updating the components fixes the problem.
