### ISSUE TITLE
Problem with flask-WTF after upgrading from 0.6.12 to 0.6.14

### ISSUE THREAD

**Issue by StreetGuru** [janeczku/calibre-web#2248]
**Describe the bug/problem**
After running the upgrade from within calibre-web admin menu (from v. 0.6.12 to 0.6.14), I get a dependency error for flask-WTF. Although I have installed it with the command `pip3 install flask-WTF`, the error persists. I have also tried to downgrade flask-WTF version with `pip3 install 'flask-wtf ==0.14.2' --force-reinstall` (from #2137) but the error persists

**To Reproduce**
1. Update calibre-web from 0.6.12 to 0.6.14 from admin menu in calibre-web
2. calibre-web fails to start with 503 service unavailable
3. attempting to start calibre-web service from shell gives dependency error for flask-WTF
4. Install flask-WTF with `pip3 install flask-WTF` but the error persists

**Shell Commands**
```
# pip3 install flask-WTF
Requirement already satisfied: flask-WTF in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied: Flask in /usr/local/lib/python3.5/dist-packages (from flask-WTF)
Requirement already satisfied: WTForms in /usr/local/lib/python3.5/dist-packages (from flask-WTF)
Requirement already satisfied: Werkzeug<2.0,>=0.15 in /usr/local/lib/python3.5/dist-packages (from Flask->flask-WTF)
Requirement already satisfied: click<8.0,>=5.1 in /usr/local/lib/python3.5/dist-packages (from Flask->flask-WTF)
Requirement already satisfied: Jinja2<3.0,>=2.10.1 in /usr/local/lib/python3.5/dist-packages (from Flask->flask-WTF)
Requirement already satisfied: itsdangerous<2.0,>=0.24 in /usr/local/lib/python3.5/dist-packages (from Flask->flask-WTF)
Requirement already satisfied: MarkupSafe in /usr/local/lib/python3.5/dist-packages (from WTForms->flask-WTF)
# /usr/bin/python3 /opt/calibre-web/cps.py
*** "flask-WTF" is needed for calibre-web to run. Please install it using pip: "pip install flask-WTF" ***
```
**Logfile**
[2021-12-31 05:10:23,971]  INFO {cps.server:273} webserver stop (restart=False)
[2021-12-31 05:10:24,086]  INFO {cps.server:258} Performing shutdown of Calibre-Web
[2021-12-31 05:11:26,241]  INFO {cps:101} Starting Calibre Web...
[2021-12-31 05:11:26,830]  INFO {cps.server:227} Starting Tornado server on :8083
[2021-12-31 05:15:44,113]  INFO {cps.admin:1612} Update status requested
[2021-12-31 05:15:55,126]  INFO {cps.server:273} webserver stop (restart=True)
[2021-12-31 05:15:55,128]  INFO {cps.server:261} Performing restart of Calibre-Web
[2021-12-31 05:15:56,495] ERROR {cps.search_metadata:51} Import error for metadata source: scholar
[2021-12-31 05:15:56,531]  INFO {cps:120} *** "lxml" is needed for calibre-web to run. Please install it using pip: "pip install lxml" ***
[2021-12-31 05:15:56,531]  INFO {cps.server:272} webserver stop (restart=True)
[2021-12-31 05:19:17,979] ERROR {cps.search_metadata:51} Import error for metadata source: scholar
[2021-12-31 05:19:17,993]  INFO {cps:120} *** "lxml" is needed for calibre-web to run. Please install it using pip: "pip install lxml" ***
[2021-12-31 05:19:17,993]  INFO {cps.server:272} webserver stop (restart=True)
[2021-12-31 05:21:13,454] ERROR {cps.search_metadata:51} Import error for metadata source: scholar
[2021-12-31 05:21:13,472]  INFO {cps:125} *** "flask-WTF" is needed for calibre-web to run. Please install it using pip: "pip install flask-WTF" ***
[2021-12-31 05:21:13,473]  INFO {cps.server:272} webserver stop (restart=True)
[2021-12-31 05:25:30,269] ERROR {cps.search_metadata:51} Import error for metadata source: scholar
[2021-12-31 05:25:30,285]  INFO {cps:125} *** "flask-WTF" is needed for calibre-web to run. Please install it using pip: "pip install flask-WTF" ***
[2021-12-31 05:25:30,285]  INFO {cps.server:272} webserver stop (restart=True)

**Expected behavior**
calibre-web should start after update.

**Environment (please complete the following information):**
 - OS: Debian 9.13 (stretch)
 - Python version: Python 3.5.3
 - Calibre-Web version: 0.6.12
 - Docker container: None (installed manually)
 - Special Hardware: n/a
 - Browser: n/a

**Comment by yeraycito** [comment]
Solution: pip install flask-WTF

**Comment by yeraycito** [comment]
Requirement already satisfied: https://github.com/janeczku/calibre-web/issues/2247

**Comment by StreetGuru** [comment]
As per my original post, I have installed flask-WTF but the error remains.
I have also tried to deploy a new version of calibre-web manually from the current git but after starting the service successfully, the service is not listening on port 8083.

**Comment by OzzieIsaacs** [comment]
According to flask-wtf documentation https://flask-wtf.readthedocs.io/en/1.0.x/changes/#version-1-0-0, python3.5 is only supported up to version 0.15, so your version of `flask-wtf` is to new, please try to install an older version of it.

**Comment by StreetGuru** [comment]
If I install version 0.14.2 as the user, when starting the service it gives me again the same error of not recognizing flask-WTF:

```
calibre@host:/opt/calibre-web-books$ pip3 install 'flask-wtf ==0.14.2'
Collecting flask-wtf==0.14.2
  Downloading https://files.pythonhosted.org/packages/60/3a/58c629472d10539ae5167dc7c1fecfa95dd7d0b7864623931e3776438a24/Flask_WTF-0.14.2-py2.py3-none-any.whl
Collecting Flask (from flask-wtf==0.14.2)
  Using cached https://files.pythonhosted.org/packages/e8/6d/994208daa354f68fd89a34a8bafbeaab26fda84e7af1e35bdaed02b667e6/Flask-1.1.4-py2.py3-none-any.whl
Collecting WTForms (from flask-wtf==0.14.2)
  Using cached https://files.pythonhosted.org/packages/e0/31/614fc7dc7d76005b0acb8c0c8920d962b83d7422b4ba912886dfb63f86ff/WTForms-2.3.3-py2.py3-none-any.whl
Collecting Werkzeug<2.0,>=0.15 (from Flask->flask-wtf==0.14.2)
  Using cached https://files.pythonhosted.org/packages/cc/94/5f7079a0e00bd6863ef8f1da638721e9da21e5bacee597595b318f71d62e/Werkzeug-1.0.1-py2.py3-none-any.whl
Collecting itsdangerous<2.0,>=0.24 (from Flask->flask-wtf==0.14.2)
  Using cached https://files.pythonhosted.org/packages/76/ae/44b03b253d6fade317f32c24d100b3b35c2239807046a4c953c7b89fa49e/itsdangerous-1.1.0-py2.py3-none-any.whl
Collecting Jinja2<3.0,>=2.10.1 (from Flask->flask-wtf==0.14.2)
  Using cached https://files.pythonhosted.org/packages/7e/c2/1eece8c95ddbc9b1aeb64f5783a9e07a286de42191b7204d67b7496ddf35/Jinja2-2.11.3-py2.py3-none-any.whl
Collecting click<8.0,>=5.1 (from Flask->flask-wtf==0.14.2)
  Using cached https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl
Collecting MarkupSafe (from WTForms->flask-wtf==0.14.2)
  Using cached https://files.pythonhosted.org/packages/6e/57/d40124076756c19ff2269678de7ae25a14ebbb3f6314eb5ce9477f191350/MarkupSafe-1.1.1-cp35-cp35m-manylinux1_x86_64.whl
Installing collected packages: Werkzeug, itsdangerous, MarkupSafe, Jinja2, click, Flask, WTForms, flask-wtf
Successfully installed Flask-1.1.4 Jinja2-2.11.3 MarkupSafe-1.1.1 WTForms-2.3.3 Werkzeug-1.0.1 click-7.1.2 flask-wtf-0.14.2 itsdangerous-1.1.0
calibre@host:/opt/calibre-web-books$ exit
logout
root@host:~# systemctl start calibre-web-books
root@host:~# systemctl status calibre-web-books
● calibre-web-books.service - Calibre-Web-eBooks
   Loaded: loaded (/etc/systemd/system/calibre-web-books.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2022-01-02 12:00:48 GMT; 5s ago
  Process: 15131 ExecStart=/usr/bin/python3 /opt/calibre-web-books/cps.py (code=exited, status=7)
 Main PID: 15131 (code=exited, status=7)

Jan 02 12:00:47 host systemd[1]: Started Calibre-Web-eBooks.
Jan 02 12:00:48 host python3[15131]: *** "flask-WTF" is needed for calibre-web to run. Please install it using pip: "pip install flask-WTF" ***
Jan 02 12:00:48 host systemd[1]: calibre-web-books.service: Main process exited, code=exited, status=7/NOTRUNNING
Jan 02 12:00:48 host systemd[1]: calibre-web-books.service: Unit entered failed state.
Jan 02 12:00:48 host systemd[1]: calibre-web-books.service: Failed with result 'exit-code'.
```

**Comment by OzzieIsaacs** [comment]
looks like pip installs it somewhere else. Please run as the user running the service the command:
`/usr/bin/python3 -m pip install 'flask-wtf ==0.14.2'`

**Comment by StreetGuru** [comment]
yes, I'm installing it as the user calibre - same user running the service. Furthermore, I've confirmed that it created the .local folder in the home directory of the user.

**Comment by OzzieIsaacs** [comment]
Then there is maybe another version of `flask-wtf `interring. I recommend using a virtual environment for runing calibre-web in this case

**Comment by StreetGuru** [comment]
I've never used venv to install. Are there any easy to follow instructions on how to do it? Can i use venv as the unprivileged user to install all dependencies (they seem to require root normally). Thank you for all the assistance.

**Comment by OzzieIsaacs** [comment]
This one looks quite straightforward (https://realpython.com/python-virtual-environments-a-primer/), make sure not getting confused between python2 and python3. Instead of activate/deactivate you can just call the full path of python in the virtual environment in your service file. 
Normal/unpriveleged users should be able to create a virtual environment

**Comment by StreetGuru** [comment]
Brilliant, I'll try installing it using venv. Many thanks for your help.

**Comment by marcolaeti** [comment]
bonjour, 
je suis sur nas synology avec le docker calibre web installe.
en faisant la mise a jour a la version 0.6.14, j'ai eu effectivement le meme soucis avec une erreur flask-wtf ;
il me le propose de l'installer en pip.

Je l'ai installe mais toujours le meme message d'erreur ;

si vous avez la reponse et qu'on me detaille au mieux svp
merci a tous

**Comment by astlea** [comment]
Can you help me, I installed this project through python project manager in Pagoda Linux, but I can't access calibre-web through the public IP, the server is located in HUAWEI CLOUD, and port 8083 has been put on
