### ISSUE TITLE
No module named cps

### ISSUE THREAD

**Issue by Nilot352** [janeczku/calibre-web#2249]
After installing with pip3 I get a no module named cps when launching with Python3.

I am on a Raspberry Pi 3 with Python version 3.5.3

Here is the message:

usr/bin/python3: No module named cps

**Comment by OzzieIsaacs** [comment]
How do you start calibre-web, just by typing "cps"? 
Could you please check if you find the cps command (should be located in ~/.local/bin), maybe the filepath is not attached to the path variable, or you installed it as a different user, and now your user doesn't have access to the install location (installed as root user?). 
Alternatively you should be able to start calibre-web via `/usr/bin/python3 -m cps`

**Comment by rossywah** [comment]
I get the same issue on a Pi 4 with Python 3.7.3.  cps is in the correct place (and PATH variable is updated to include ~/.local/bin), and get the same error if I use /usr/bin/python3 -m cps

In addition, if I try and run cps directly without the python command, I get the following response:

$ cps
Traceback (most recent call last):
  File "/home/pi/.local/bin/cps", line 6, in <module>
    from calibreweb import main
  File "/home/pi/.local/lib/python2.7/site-packages/calibreweb/__init__.py", line 29, in <module>
    from cps import create_app
  File "/home/pi/.local/lib/python2.7/site-packages/calibreweb/cps/__init__.py", line 46, in <module>
    from flask_wtf.csrf import CSRFProtect
  File "/home/pi/.local/lib/python2.7/site-packages/flask_wtf/__init__.py", line 1, in <module>
    from .csrf import CSRFProtect, CsrfProtect
  File "/home/pi/.local/lib/python2.7/site-packages/flask_wtf/csrf.py", line 220
    dest = f'{view.__module__}.{view.__name__}'
                                              ^
SyntaxError: invalid syntax

**Comment by OzzieIsaacs** [comment]
It's hard for me to help you. If I get my pi and start calibre-web it will work. Your problem is that you got mixed up with different python instances. What you could do is create a virtual environment and install calibre-web there (did also help other people: https://github.com/janeczku/calibre-web/issues/2248#issuecomment-1003709348)
