### ISSUE TITLE
Book available on calibre is missing into calibre web

### ISSUE THREAD

**Issue by arnaudroubinet** [janeczku/calibre-web#2251]
I use the last version of calibre web provided by linux server (0.6.14), and the last 64 bits version of calibre (5.34.0).

I create a new database on a remote disk, and import all my books, reworking their metadata (Series, authors, etc).
Running a fresh install of calibre web with docker pointing on this new database.

I compare my calibre view with the calibre web one.

I have the same number of books on both sides. (both calibre and the about of calibre web show 424 books)
But when I go to "book", "serie" or "author" view, some of them are missing in calibre web.

Read books show 0 and unread 234.
Languages of book is on "show all".
I have no tag filter.

I try a new installation and still have the same problem.
I don't know how reproducing this error without sharing my library.

**Logfile**
Using debug mode I have no error in the view log page.

**Screenshots**
![image](https://user-images.githubusercontent.com/4160229/147983755-30387a69-3b49-479a-ba0d-4b8f936d81f6.png)
![image](https://user-images.githubusercontent.com/4160229/147983913-b283c920-5c69-4c87-a91d-30f68cc4cef3.png)

![image](https://user-images.githubusercontent.com/4160229/147984014-76ab93c0-ea63-4dee-afcd-034cd6f43d36.png)
![image](https://user-images.githubusercontent.com/4160229/147984066-ef3feff0-cebd-42b9-a229-bd0a727c0667.png)

**Environment :**
 - Calibre-Web version: 0.6.14 
 - Docker container: LinuxServer:
 - Special Hardware: Synology running on with an intel Celeron
 - Browser: Firefox 95.0.2

**Additional context**
I'm behind a linux server nginx (Swag) using authelia.

**Comment by OzzieIsaacs** [comment]
If you've synced books with kobo, please check if the book is not archived (show archived books on first screenshot, this enables another view on the left side). Unticking archive there will cause the book to show up again on your kobo reader
This is a calibre-web only feature (like read status) , therefore calibre itself is unaware of it.

**Comment by arnaudroubinet** [comment]
You are right !

Archived books seem a "random", but I guess what happens.
I renew the calibre DB from scratch and set it to calibre web without properly clean calibre web db and configuration.

I guess calibre web does join using technical id, which must explain why the books archived are not the ones I archived in my previous try to install it.

Thx a lot @OzzieIsaacs for your help and to all contributors for your amazing work.

**Comment by OzzieIsaacs** [comment]
The change database problem should be fixed now in the nightly version (since middle/end of december)
