### ISSUE TITLE
Use the nicer upload with progress bar when you upload new formats to a book

### ISSUE THREAD

**Issue by taxilian** [janeczku/calibre-web#2252]
**Describe the bug/problem**
This is partly a bug, partly a feature request -- somewhere in the middle. There are two parts:

1. When you upload additional formats to calibre-web it does not show any kind of progress bar for the upload like it does when you upload existing books, which is frustrating particularly if you are uploading large files, such as an audiobook or even just a formatted PDF

2. When you drop a file on the page when you are editing a book it should upload it to that book or else ask which one you want to do. Instead, it creates a new book, which is quite frustrating =[ it makes it hard for me to quickly upload multiple format books that I have to my calibre-web stuff.

**To Reproduce**

For part 1:

1. Open a book, then edit metadata
2. Click "Upload format" and choose a file
3. You will not see any indication of progress unless the browser provides something which most don't

For part 2:

1. Open a book, then edit metadata
2. Drag another book file onto the page
3. Calibre-web will create a new book or books instead of adding them as additional formats

Though these are somewhat different issues I am grouping them together because I expect that implementing them together may be faster than doing them separately.

**Logfile**

n/a

**Expected behavior**

I think that's clear from my above description; it's very counter-intuitive if dropping a file onto the "edit metadata" screen creates a new book, though I could see having a way to choose or formatting the "drop" indicator to make it clear what it is doing.

**Additional context**

I would be willing to implement this, but I am unfamiliar with the development environment; a starting place for where to look would be appreciated.

**Comment by OzzieIsaacs** [comment]
Number 2 also came to my mind while using calibre-web

**Comment by OzzieIsaacs** [comment]
Finally, we now have it. Progress bar, multiple formats at once and drag'n drop, all availabe in the newest nightly version behind this nice new button:
![grafik](https://github.com/user-attachments/assets/24e3bf73-547b-41d4-8213-b5214f2555ba)
