### ISSUE TITLE
Best iOS apps that work well with Calibre-web?

### ISSUE THREAD

**Issue by MReprogle1** [janeczku/calibre-web#2257]
Love calibre-web and using it with MoonReader on Android. However, I am starting to use iOS and am unable to find anything apps that allow the same functionality where you can download from an HTML catalog right into the app. Are there any suggestions for best iOS apps that work well with Calibre-web?

**Comment by MReprogle1** [comment]
Sorry, I saw that Marvin was tested to be working. I guess I am just having trouble getting to the ODPS side of things.

**Comment by OzzieIsaacs** [comment]
I'm using Marvin3 which seems to be unsupported for some years, but it was the easiest one to set up
