### ISSUE TITLE
Tornado vs Gevent

### ISSUE THREAD

**Issue by yeraycito** [janeczku/calibre-web#2258]
Which is the best and safest?

Tornado 6.1 ( Oct 30, 2020 ): https://pypi.org/project/tornado/

Gevent 21.12.0 ( Dec 11, 2021 ): https://pypi.org/project/gevent/

Tornado does not seem to be updated.

**Comment by OzzieIsaacs** [comment]
Tornado is still active, last commit on November 2021, maybe it's more stable than gevent and therefore receives less updates (I don't know)
![grafik](https://user-images.githubusercontent.com/6438895/148650623-0852614a-c055-49fe-ba9c-f3f22c661e8a.png)
I don't see any benefit of one over the other. In calibre-web I have equipped the tornado version with a 200MB upload limit. 
On the internet you find several benchmarks, from my point of view the results are ambiguous. I don't know if there is any difference regarding safety in both of them.

**Comment by yeraycito** [comment]
Thank you very much for your reply.
