### ISSUE TITLE
can't open epub file

### ISSUE THREAD

**Issue by ymmz** [janeczku/calibre-web#2264]
**Describe the bug/problem**
can't read epub file normally.

**To Reproduce**
1. Go to file to read
2. Click on "read in broswer-epub"
3. can't load file

**Logfile**
log file is normally

**Expected behavior**
can read epub file

**Screenshots**
![捕获](https://user-images.githubusercontent.com/26834233/149167262-3226ca70-d021-41a7-8036-6321ca611d76.PNG)

**Environment (please complete the following information):**
 - OS: win10
 - Python version: 3.10
 - Calibre-Web version: 0.6.14
 - Docker container: one
 - Special Hardware: no
 - Browser: edge97.0

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

**Comment by OzzieIsaacs** [comment]
Please update to the newest nightly version, should work then again

**Comment by ymmz** [comment]
> Please update to the newest nightly version, should work then again

I uninstall it by pip. and then install by calibre-web.exe-0.6.14. but it's the same problem

**Comment by OzzieIsaacs** [comment]
Please go to admin - basic configuration - server configuration -update channel - nightly
Afterwards go back to admin, click on search for update - update
Done

**Comment by ymmz** [comment]
> Please go to admin - basic configuration - server configuration -update channel - nightly Afterwards go back to admin, click on search for update - update Done
thanks. now it is ok.
