### ISSUE TITLE
Can't add books to shelve on nightly version

### ISSUE THREAD

**Issue by BrianTipton1** [janeczku/calibre-web#2265]
**Describe the bug/problem**
On the nightly version I am unable to add books to a shelf. Dev tools shows that it returns a 400 on the request. Switching to stable does not have this problem.

**To Reproduce**
1. Attempt to add book to shelf

**Logfile**
No info in log file that I can find when in debug mode

**Expected behavior**

**Screenshot**
Screen shot of request from devtools
![image](https://user-images.githubusercontent.com/61526625/149387060-1b42d098-0d7c-4718-b26b-1c07daa7fa9b.png)

**Environment (please complete the following information):**
 - Docker container: [LinuxServer]:

**Comment by OzzieIsaacs** [comment]
Newest nightly version from 3 days ago? Start of january it was indeed broken

**Comment by BrianTipton1** [comment]
Yes the version from 1/10

**Comment by OzzieIsaacs** [comment]
I‘ll check

**Comment by nwskier** [comment]
Nightly from 1/16 has this issue still as well.
Running on Pip install.

**Comment by OzzieIsaacs** [comment]
Should be fixed now. 

Over 300 tests but none of them is click on the add to shelf button on the popup page (if you click on edit and then cancel you will get to the site where the books details are visible on a fullpage, there it was working...)
I will do a new release next weekend, this will cause a lot of trouble
