### ISSUE TITLE
Access log

### ISSUE THREAD

**Issue by yeraycito** [janeczku/calibre-web#2274]
I think the access log is an excellent idea. The problem is that a lot of completely unnecessary data appears, which makes it difficult to use. It would be enough to be able to display the date and time of a user's login and logout along with their name.

![Screenshot_20220118_125652](https://user-images.githubusercontent.com/65027248/149933887-a59848b0-63df-4f27-8aa7-bd7ae25fd771.png)

**Comment by OzzieIsaacs** [comment]
The access log logs all accesses to calibre-web it's needed for debugging. If you are interested who logged in at what time, please check the calibre-web.log.
