### ISSUE TITLE
OPDS download failed because only guest login

### ISSUE THREAD

**Issue by 404gods** [janeczku/calibre-web#2275]
My calibre-web has enabled anonymous browsing, and the guest user does not intend to open the download permission. In this way, the connection through opds will not prompt other user names and passwords with permission to log in, and the download will fail. Is there a way to allow anonymous browsing without download permissions and opds downloads to coexist?

**Comment by OzzieIsaacs** [comment]
This sounds like a problem of the opds reader. Normally a not allowed answer by Calibre-Web should create a new request by the client with the proper credentials

**Comment by 404gods** [comment]
> 



> This sounds like a problem of the opds reader. Normally a not allowed answer by Calibre-Web should create a new request by the client with the proper credentials

i am using kybook 3 app

**Comment by OzzieIsaacs** [comment]
I doublechecked it. My memory was wrong, this is indeed not working. 
I will not change the the behavior as this will create another option. Which many user don't understand. 
So please change this line in opds.py by yourself (will be reverted on every update):  
https://github.com/janeczku/calibre-web/blob/81b85445d859b3eff4e4c2089f071a65c2a9e036/cps/opds.py#L47
to: `if true:` keep the trailing spaces/tabs from the original line. Afterwards opds access is only possible for users logged in (no anonymous browsing for opds catalog)
