### ISSUE TITLE
Add read status per user

### ISSUE THREAD

**Issue by xxsamxx1991** [janeczku/calibre-web#2276]
**Is your feature request related to a problem? Please describe.**
I would like to categorize each book reading status per user like:
If you login as mom: read status from calibre colum "[mom] read?"
If you login as dad: read status from calibre colum "[dad] read?"
If you login as son: read status from calibre colum "[son] read?"
If you login as friend: read status from calibre colum "[friend] read?"
...

I've already added fields to my calibre library and I would like to somehow connect them to calibre-web ones, but calibre web lacks the reading status to be set per user.

**Describe the solution you'd like**
I would like to have an additional reading status per user added to calibre-web

**Describe alternatives you've considered**
For now my own reading status is used for everyone.

**Comment by OzzieIsaacs** [comment]
Calibre-Web only supports one Calibre custom column for the read status. Your requests is supported by a calibre-web read-status. So if you don't configure a "Link Read/Unread Status to Calibre Column" column in calibre-web, the read status is saved on a per user base. Your suggesion doesn't scale very good with the number of columns in calibre (100 users need 100 columns), so I decided to have it limited to "1" custom column.

**Comment by xxsamxx1991** [comment]
Thank you. I havn't seen that it is possible without the calibre custom column.

The project is very good!
