### ISSUE TITLE
Feature Request: When searching consider also checking the custom fields.

### ISSUE THREAD

**Issue by ocgineer** [janeczku/calibre-web#2279]
**Is your feature request related to a problem? Please describe.**

In my Calibre library I have a few addition custom fields that help finding the series in occasion. For example translated Light Novels, I can search by their native title (both romaji and japanese script) or by a nickname given to some series to shorten their ridiculous long titles.

Some users of my calibre-web library know (part of) the Javanese title only or try using the know short/nickname e.g. bakarina for My Next Life as a Villainess: All Routes Lead to Doom! 

**Describe the solution you'd like**

Allow the search field to also check/find matching words in the custom fields that were created in Calibre, such as original/local name or nickname fields.

**Describe alternatives you've considered**

Non really, maybe an option to allow users to search in custom fields if it is too resource heavy and sys owners can decide if they want to allow this or not.

**Comment by OzzieIsaacs** [comment]
Searching for custom fields is possible in the advanced search.
You what to have this also available by default in the "normal" search? Did I get that right?

**Comment by ocgineer** [comment]
Ah yes, that would be correct. To be honest I never even considered the 'advanced search'.

I have quite a few custom fields so the list is pretty long now that I've seen the advanced search page. My Primary use was quickly searching for a book/series by its nickname or (part of) the Japanese name -which each have a custom field for- that I know better than the English title of the book (Japanese Light Novels).

**Comment by OzzieIsaacs** [comment]
Please check the newest nightly version if it's what you expected
