### ISSUE TITLE
cover undefined when uploading cbz with webp

### ISSUE THREAD

**Issue by dncpax** [janeczku/calibre-web#2280]
**Describe the bug/problem**
When you upload a cbz containing webp images, the cover is not defined and shows as "Cover not available".

**To Reproduce**
1. Click Upload button
2. Select cbz file containing webp images
3. Upload file
4. Check that the book has no cover after being uploaded

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 ARM64
 - Python version: 3.8.10
 - Calibre-Web version: 0.6.15 Beta - e3dbf7a88dd34b7c2a07ca8b538d1874c6a3c05f - 2022-01-07T12:40:03+01:00
 - Docker container: None
 - Special Hardware: Rasperry 4B 8GB
 - Browser: Brave 1.34.80

**Comment by OzzieIsaacs** [comment]
This is indeed not working if comicapi is installed without it, it's working. I'll have a look at it

**Comment by OzzieIsaacs** [comment]
Please update to the newest nightly version, the cover should show up afterwards (after uploading a new book)

**Comment by dncpax** [comment]
Hi there. Sorry to reopen this... it seems this a wider problem. Metadata also fails to be recognized or processed. Just tested it with a few images and a comicinfo.xml. It works with a cbz with jpegs, and doesn't with webp images.
What happens is there's no metadata when you upload the cbz with webps. But there is metadata when you upload the cbz with jpegs.

**Comment by OzzieIsaacs** [comment]
I can't reproduce this. 
The ComicInfo.xml is parsed and added in both cases (comicapi installed)
To fix it I need the nonworking file (or more details - content of ComicInfo.xml would be good starting point)

**Comment by dncpax** [comment]
Can I email you examples? I'd rather not put them here...

**Comment by OzzieIsaacs** [comment]
Yes please, use the email address on my profile page.
Thanks

**Comment by dncpax** [comment]
sent.

**Comment by dncpax** [comment]
it seems this was a goose chase. my fault. hadn't updated to latest nightly and thought this to be a different issue. it's solved.
