### ISSUE TITLE
Cannot assign books to public shelf after update

### ISSUE THREAD

**Issue by jonok2022** [janeczku/calibre-web#2282]
Hello,

After the most recent update I have found that when I try to assign a book to a shelf that it comes up with a page that just simply says books, and that it does not allow me to add a book to the shelf

![image](https://user-images.githubusercontent.com/98221994/150642588-664ce206-f1de-4c51-97a8-78001014c3de.png)

This is the result after selecting what bookshelf to assign it to, is there anything that I need to do to fix this issue or any setting I need to change?

**Comment by OzzieIsaacs** [comment]
It‘s broken on the last release, please update to the newest nightly version to fix this issue

**Comment by jonok2022** [comment]
Oh ok thank you for that info :)

**Comment by jonok2022** [comment]
Sorry I am a newb with Github, how would I go about updating to the nightly version on my linux system ? (I host it on a VPS server) and is it the file in the test folder I would have to update?

**Comment by jonok2022** [comment]
Sorry I did find the answer and changed to nightly build on the server, apologies! thanks for your time
