### ISSUE TITLE
Sync two kobo with the same account

### ISSUE THREAD

**Issue by SqueezedByte** [janeczku/calibre-web#2283]
Hi, I've a Sage and a Libra2. As now I'm using kobo sync and I adore it. The problem is that on the Libra 2 I must use a calibre-web account different that the one on the Sage. If I'm not doing it the books with only be synced on the first device and it will not appear on the "My books" on the second.
Is it possible to synchronize the same library with the same books (read or not) and the reading progress on both devices?

**Comment by OzzieIsaacs** [comment]
Short answer: No

Calibre-web stores the sync progress in several internal database tables, separately for each user. So a book is synced or not for one specific user under this account and there is no possibility to distinguish between two different devices for the same account.

**Comment by starkmapper** [comment]
I have two e-readers as well: one is waterproof, one isn't.
So when taking a bath, or reading by the pool we take the waterproof one, and the other takes the regular one.

Complete use-case:
1. We keep a ginormous library of books on the home server, setup specific shelves to sync
2. we go out on holiday
3. We complete a book and want to start a new one, so we go to calibre-web and add it to the specific shelf.
4. We sync the e-reader, and it downloads (YAY!)
5. I go to the pool and take the waterproof e-reader to find the books not there :'(

In this use-case, it's very nice to have the ability to sync your books to both e-readers.

My findings so far:
1. Clicking "Force full Kobo sync" actually causes the second e-reader to download the books (Workaround)
2. Syncing reading progress seems to work quite well (5 minutes of experimentation with the two side-by-side with kepubs)

**Comment by jaimetur** [comment]
This would be a great improvement. 

Very common use case.

**Comment by riplin** [comment]
I'm in the same boat. Libra Colour for on the road, Elipsa 2E for at home.

> So a book is synced or not for one specific user under this account and there is no possibility to distinguish between two different devices for the same account.

A device ID could be added to the API endpoint perhaps? Then you'd know which device is talking to the server.

**Comment by BWagener** [comment]
Some searching around leads me to believe that with the official kobo API syncing two kobo devices to one kobo account works.

From what I understand about the kobo sync functionality of calibre web, it mocks the official kobo API.

So from the devices' side, things look just like they do as if it was talking to the official API.

So the kobo API must have a way to identify which device it's talking to.

If all of these assumptions are correct, I don't see a reason why calibre-web couldn't support syncing multiple devices per user.

What do you think @OzzieIsaacs?

**Comment by BWagener** [comment]
To add to this, I've let an LLM loose on tcp dumps of two separate Kobo devices syncing through calibre-web. 

The devices are signed into the same Kobo account.

Here's the result:

## What uniquely differentiates the devices
* `SerialNumber` from `POST .../v1/analytics/gettests`
  * device 1: `N50633C2xyz`
  * device 2: `N50632C2abc`
  * This is the strongest hardware-level identifier.
* TestKey from the same request body
  * device 1: `1b88f4e9-1336-40c7-xyz`
  * device 2: `5f18e61b-1991-4090-abc`
  * Also device-distinguishing
* Opaque bearer token on /v1/initialization differs per device in these captures.

## What is NOT suitable as a device identifier
* JWT claims sub and kobo_user_id are the same in both captures (account-level).
* PlatformId is the same (...000000000386) on both captures.
* User-Agent mostly reflects model/firmware; useful context, weak as unique device key.

## Best approach for calibre per-device sync tracking

Use a two-stage identity strategy:
 
1. Canonical device ID: `SerialNumber` from `POST /v1/analytics/gettests`
2. Early-session provisional ID: opaque bearer from /v1/initialization
3. After analytics arrives, map provisional session -> `SerialNumber` and persist sync status by (calibre_user_id, serial_number).

This gives you:
* reliable per-device identity
* ability to attribute earlier requests in the same sync session
* stable long-term device tracking in calibre
