### ISSUE TITLE
add book to shelf

### ISSUE THREAD

**Issue by Thomas1005** [janeczku/calibre-web#2285]
Not possible anymore to add a ebook to a specific shelf...
Any help?

**Comment by OzzieIsaacs** [comment]
Please update to newest nightly version.

**Comment by Thomas1005** [comment]
to version V0.6.15 Lilith ?
Have it installed, not working....
<img width="452" alt="Bildschirmfoto 2022-01-23 um 11 22 43" src="https://user-images.githubusercontent.com/64309967/150674161-3be7ffc8-ca02-428e-a700-3ef1b799263e.png">

**Comment by OzzieIsaacs** [comment]
Basic configuration-> server configuration -> update channel nightly. Back to admin, search for update -> update

**Comment by Thomas1005** [comment]
directly inside calibre web ? 
thx already for great and quick response

**Comment by OzzieIsaacs** [comment]
Yes

**Comment by Thomas1005** [comment]
GREAT! its works again....you are a HERO! thanks a lot!

**Comment by JeffAlyanak** [comment]
I seem to have the same issue, but upgrading to latest nightly—and subsequently restarting the service and clearly browser cache—has not resolved it. After switching to `nightly` and running the upgrade, I'm currently on a version listed in the GUI as `1/22/22, 1:01 PM`.

Using the "Add to Shelf" option appears to drop me on an empty Books page.

**Comment by OzzieIsaacs** [comment]
There was one another bug on the search result page, this is now also fixed, please try to update again

**Comment by JeffAlyanak** [comment]
@OzzieIsaacs Same behaviour after the latest nightly update. I've found that it's isolated to the caliblur theme, though.

For others facing the same issue, try switching back to the default theme.

**Comment by OzzieIsaacs** [comment]
Please update to the newest nightly version

**Comment by JeffAlyanak** [comment]
@OzzieIsaacs Thanks, that's resolved it in the caliblur theme as well.
