### ISSUE TITLE
Can't select specific shelf to sync to Kobo

### ISSUE THREAD

**Issue by khppapaye** [janeczku/calibre-web#2286]
**Describe the bug/problem**
I've just installed Calibre-Web and activate the Sync to Kobo options (changed the api_endpoint option on my Kobo.conf). I added a new shelf on it and selected "only sync books on specified shelves.
Thing is : I can't find how to specify the shelves ?

**Expected behavior**
In the user profile, I'd expect to find a list of the created shelves so I can select which ones I will sync to my Kobo. I can also modify a config file if no GUI is available
**Environment (please complete the following information):**
 - OS: Last Docker version
 - Calibre-Web version: 0.6.15
 - Docker container: LinuxServer
 - Special Hardware: Qnap NAS
 - Browser: Edge 96.0.1054.57

**Comment by OzzieIsaacs** [comment]
Edit shelf after enabling the feature. There will be a new checkbox to select (sync or not)

**Comment by khppapaye** [comment]
It works ! My bad, that was an easy one :)
Thanks so much !
