### ISSUE TITLE
erreur czlibre web avec message flask-wtf

### ISSUE THREAD

**Issue by marcolaeti** [janeczku/calibre-web#2289]
bonjour, je suis sur nas synology,
j'ai installé calibre web avec le docker et fait la dernière mise à jour 0.6.14
et le message d'erreur : pip install flask-WTF

j'ai lu les commentaires mais rien n'y fait, je n'y arrive pas
vous pouvez aider ?

**Comment by OzzieIsaacs** [comment]
Please post your request in english. Please just install flask-wtf in the python version you are using to start calibre-web
