### ISSUE TITLE
Problem adding to shelves

### ISSUE THREAD

**Issue by Basemaly-pratt** [janeczku/calibre-web#2293]
**Describe the bug/problem**
I recently updated to version 0.6.16 but when trying to add a book to a shelf, the screen seems to partially load then freeze on a blank screen. 

**To Reproduce**
1. Go to any book 
2. Click on the "add to shelf" icon

**Logfile**
There aren't any entries relating to this error in the log file.

**Expected behavior**
Screen should load and a message appearing saying the book was added to the shelf.

**Screenshots**

**Environment (please complete the following information):**
 - OS: MacOS
 - Python version: 3
 - Calibre-Web version: 0.6.16 
 - Browser: Firefox

**Comment by OzzieIsaacs** [comment]
Are you using the caliblur theme?

**Comment by Basemaly-pratt** [comment]
Yes I'm using Caliblur Dark theme.

**Comment by OzzieIsaacs** [comment]
Please update to the newest nightly version

**Comment by Basemaly-pratt** [comment]
OK thank you!
