### ISSUE TITLE
How to run calibre-web at boot?

### ISSUE THREAD

**Issue by tenleftfingers** [janeczku/calibre-web#2296]
As my normal user, I use the command

`/home/pi/.local/bin/cps & `

to start the server. But when I add that to rc.local, it doesn't work on reboot. Even using su - <myuser> -c <command> doesn't work: `ps -A | grep cps` shows that the server isn't running.

Im running on a Debian buster headless setup.

**Comment by OzzieIsaacs** [comment]
Totally correct. 
If you start is a normal user you are in the home folder of your user like `/home/username`, you start the server also from this folder `/home/username.local/bin`, if you enter this in your start script it will try to start it from `/.local/bin/`. Please change the command in the start script to the complete path and it will work

**Comment by tenleftfingers** [comment]
Apologies, I've updated the post. The command was using the full path:

`/home/pi/.local/bin/cps &`

But it isn't running when I log in.

**Comment by OzzieIsaacs** [comment]
I hope we can agree this is not a problem of calibre-web itself, but a pure linux issue. 
I'm using systemd for the start of services. For systemd there is an example in the wiki. So I can't help any further (I have no idea in which log the errors are logged and so on). 

One final idea would be using `[path to the right! python installation]\python3 -m cps`.

**Comment by tenleftfingers** [comment]
Yes, I'm more asking for help than reporting an issue. Thanks, but an absolute path to python3 didn't work either.

```
...
/usr/bin/python3 /home/pi/.local/bin/cps &
exit 0
```

But as you say, it's a linux issue and I'll ask on the linux forums about it. Thanks again for a fantastic application. Hope to be in a position to support you at some stage.
