### ISSUE TITLE
[Docker] Unable to change port with ENV vars

### ISSUE THREAD

**Issue by jeanfrancoisgratton** [janeczku/calibre-web#2297]
I tried to automate building of the docker image by building my own container on top of the current container. This only because it is easier on my home tools to automate the launch without having to deal with extra params, etc (the same tools launches multiple containers).

This is my (simplified) Dockerfile, with some explanations below:
FROM lscr.io/linuxserver/calibre-web
ENV TZ="America/Montreal"
ENV PUID=9000
ENV GUID=1300
ENV DOCKER_MODS=linuxserver/calibre-web:calibre
ENV OAUTHLIB_RELAX_TOKEN_SCOPE=1
ENV CALIBRE_PORT=2699
ENV DEFAULT_PORT=2699
RUN sed -i -e "s/^lm.session_protection = 'strong'/#.session_protection = 'strong'/" /app/calibre-web/cps/__init__.py
RUN sed -i -e "s/^DEFAULT_PORT        = 8083/DEFAULT_PORT        = ${DEFAULT_PORT}/" /app/calibre-web/cps/constants.py
VOLUME [ "/config", "/books" ]
EXPOSE ${DEFAULT_PORT}

Two things:
- I am not sure that _both_ CALIBRE_PORT and DEFAULT_PORT are needed. Does one supercede the other ?
- The 2 RUN commands, the sed were added in a subsequent attempt as I could not see the changes being applied after a docker build.

Whatever I do these steps above, once in the container I still see this:
```
root@bookreader:/app# root@bookreader:/# netstat -pean|egrep "2699|8083" ;echo;echo;egrep -r "DEFAULT_PORT|CALIBRE_PORT|8083" /app
tcp6       0      0 :::8083                 :::*                    LISTEN      9000       30493054   -                   


/app/calibre-web/README.md:Point your browser to `http://localhost:8083` or `http://localhost:8083/opds` for the OPDS catalog
/app/calibre-web/cps/config_sql.py:    config_port = Column(Integer, default=constants.DEFAULT_PORT)
/app/calibre-web/cps/config_sql.py:    config_external_port = Column(Integer, default=constants.DEFAULT_PORT)
/app/calibre-web/cps/constants.py:DEFAULT_PORT        = 2699
/app/calibre-web/cps/constants.py:env_CALIBRE_PORT = os.environ.get("CALIBRE_PORT", DEFAULT_PORT)
/app/calibre-web/cps/constants.py:    DEFAULT_PORT = int(env_CALIBRE_PORT)
/app/calibre-web/cps/constants.py:    print('Environment variable CALIBRE_PORT has invalid value (%s), faling back to default (8083)' % env_CALIBRE_PORT)
/app/calibre-web/cps/constants.py:del env_CALIBRE_PORT
/app/calibre-web/cps/reverseproxy.py:        proxy_pass http://127.0.0.1:8083;
```

This is on version 0.6.16 ; for some reason I just cannot change the default port.
Any idea on what I might be missing ?

Thx

**Comment by OzzieIsaacs** [comment]
From the documentation:
`CALIBRE_PORT` allows to set the default listening port during creation of the settings database. Afterwards the port which is configured in the UI, is used.

For more help please ask the provider of the docker container. This feature is tested automatic and regular and I'm quite sure that it is working for non docker applications.

**Comment by jeanfrancoisgratton** [comment]
That was a quick reply :-)

I understand that Docker is an extra layer on top of the app, but .. why when I modify the python files with my value (that is: they get modify before the app starts), netstat still shows the app listening on tcp/8083 ?

It's not a docker issue per se, I think.

Btw, the only reason I wanted to run that in my own docker container is because I needed a way to automate disabling lm.session_protection. Doing it at build-time seemed sensible.

**Comment by OzzieIsaacs** [comment]
This number is only taken to create the initial value in the settings database of calibre-Web. So delete app.db, have this changes applied, start calibre-Web and the next app.db (calibre-Web settings database) is generated with this values. The port can be changed at any time in the ui

**Comment by jeanfrancoisgratton** [comment]
Alright. Thanks for the clarifications ! I will close this question.
