### ISSUE TITLE
Cannot add books to Shelves

### ISSUE THREAD

**Issue by dwilliamhouston** [janeczku/calibre-web#2300]
**Describe the bug/problem**
Having issues with both version 0.6.16 and 0.6.15 with adding books to shelves.  When I add a book it goes to a blank screen.  I have tried on both MS Edge and Apple Safari browsers with same results.  On Edge I have multiple extensions and on Safari I have no extensions.  Both are running latest version of browser.

**To Reproduce**
1. Go to Book you want to assign to Shelf
2. Click on Shelves and then select the Shelf you want to add to.
3. Goes bank to Books but no books listed.

**Logfile**
I tried to run debug logs but not getting any debug information.  Not sure if that is issue on my side.  
**Expected behavior**
Would expect book to be added to shelf.  If I check in shelf the book was not added.  This used to work as I have other books in existing shelves.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Linux/Docker (latest Linuxserver/calibre-web docker image)
 - Python version: What ever is installed with docker image.
 - Calibre-Web version: 0.6.16 but also broken in 0.6.15
 - Docker container: [None/LinuxServer]: LinuxServer/calibre-web
 - Special Hardware: [e.g. Rasperry Pi Zero] None
 - Browser: Edge 97.0.1072.76 and Safari 15.3 (17612.4.9.1.5)

**Additional context**
None

**Comment by OzzieIsaacs** [comment]
You are using caliblur! Theme? Please use the nightly dockervimafe, or switch to the default theme

**Comment by dwilliamhouston** [comment]
Switched to the default theme and that worked.  Are there plans to fix this so that we can use a dark theme?

**Comment by dwilliamhouston** [comment]
Just tested nightly build and its fixed also.  This bug can be closed.  Thanks.
