### ISSUE TITLE
500 on Book Upload [a bytes-like object is required, not 'str']

### ISSUE THREAD

**Issue by BoostWillis** [janeczku/calibre-web#2302]
**Describe the bug/problem**
Attempting to upload a 1.5mb PDF book results in an Internal Server Error

**To Reproduce**
1. Click upload button
2. Select Book
3. Wait for upload to complete
4. Receive error

**Logfile**
```
[2022-02-01 18:07:04,014] ERROR {cps:1458} Exception on /upload [POST]
Traceback (most recent call last):
  File "/var/www/calibreweb/vendor/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/calibreweb/vendor/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/calibreweb/vendor/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/calibreweb/vendor/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/var/www/calibreweb/cps/usermanagement.py", line 38, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/var/www/calibreweb/vendor/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/var/www/calibreweb/cps/editbooks.py", line 71, in inner
    return f(*args, **kwargs)
  File "/var/www/calibreweb/cps/editbooks.py", line 1028, in upload
    db_book, input_authors, title_dir = create_book_on_upload(modif_date, meta)
  File "/var/www/calibreweb/cps/editbooks.py", line 950, in create_book_on_upload
    modif_date |= edit_book_tags(meta.tags, db_book)
  File "/var/www/calibreweb/cps/editbooks.py", line 437, in edit_book_tags
    input_tags = tags.split(',')
TypeError: a bytes-like object is required, not 'str'
```
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

**Expected behavior**
Book to be uploaded without error.

**Screenshots**
n/a

**Environment (please complete the following information):**
 - OS: Debian running the latest YunoHost 4.3.6.2
 - Python version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
 - Calibre-Web version: 0.6.14 - 4da64ceb23e69da3953f9c454ea261d9d0621e25 - 2021-10-31T11:31:53+01:00
 - Docker container: None:
 - Special Hardware: Just a regular x86_64 linode VPS running Debian Yunohost.
 - Browser: Firefox 96

** Attempted Resolutions
Updated all packages.
Restarted the calibre-web service.
Restarted the server.

**Additional context**
Yunohost runs a reverse proxy
Special database location: /home/yunohost.multimedia/share/eBook
LDAP users

**Comment by OzzieIsaacs** [comment]
Meanwhile calibre-Web itself is on version 0.6.16.  Yunohost needs to update its calibre-Web version

**Comment by BoostWillis** [comment]
That seems to be in progress currently: https://github.com/YunoHost-Apps/calibreweb_ynh/pull/93

Was this a known issue in previous versions?

Update: This particular book uploads just fine after being converted to EPUB from PDF.

**Comment by OzzieIsaacs** [comment]
I can‘t remember. To check if it still happens with current version I would need the book (preferably per email, the one on my GitHub profile page)

**Comment by OzzieIsaacs** [comment]
Or you just wait a few days

**Comment by OzzieIsaacs** [comment]
It's causing the same bug in 0.6.16

**Comment by OzzieIsaacs** [comment]
It's fixed, but will

**Comment by OzzieIsaacs** [comment]
Updated the last comment

**Comment by BoostWillis** [comment]
Thanks so much!
