### ISSUE TITLE
Use Flask-User?

### ISSUE THREAD

**Issue by jkrehm** [janeczku/calibre-web#231]
I'd like to implement a feature to send emails inviting people (my family) to create accounts in calibre-web. That way I don't have to create accounts for them, then email their credentials. They would be able to create their own credentials.

While searching to see if that's already available in Flask (I'm new to Flask, and Python development in general) I came across https://github.com/lingthio/Flask-User. I know it would be a departure from what is currently done in calibre-web, and users would likely have to reset their passwords if/when the change were released, but it would add a bunch of user functionality, including email invitations.

I also noticed that there isn't currently "forgot password" functionality, so that would come baked-in, too.

What are your (the excellent maintainers) thoughts? Something worth looking into?

**Comment by OzzieIsaacs** [comment]
By enabling "public registration" it's possible that users can create their own account, but the feature to invite them is indeed not exisiting. I don't know if we need this? Having the option to have a "forgot password function on the other hand would be nice to have. 
So my answer is (the not very helpfull): "I don't have a real opinion"

**Comment by OzzieIsaacs** [comment]
I'm closing this, as we don't have any progress on it.
