### ISSUE TITLE
"Erlaubte/Verbotene Tags auswählen"

### ISSUE THREAD

**Issue by Jerome2103** [janeczku/calibre-web#2311]
**Describe the bug/problem**
![image](https://user-images.githubusercontent.com/27641713/153465366-ce8a1279-dda4-4a74-a6b0-f311fb5580e0.png)

The database say 3 to 4 tags.

**Environment (please complete the following information):**

- OS: Synology DSM
- Python version: python3.8
- Calibre-Web version: The lastet stable Version
- Docker container: LinuxServer
- Special Hardware: Synology
- Browser: Chrome 98

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

**Comment by Jerome2103** [comment]
Ich werde es morgen überprüfen und Bescheid sagen.

**Comment by Jerome2103** [comment]
Das komische ist, bei den Benutzern zeigt es richtig an, nur bei den Admin Settings für Standardberechtigungen nicht.

**Comment by OzzieIsaacs** [comment]
Bei mir gehts
