### ISSUE TITLE
Covers are not showing up on kobo reader

### ISSUE THREAD

**Issue by OzzieIsaacs** [janeczku/calibre-web#2312]
I've noticed that when using Kobo Sync, the artwork still does not render on the device. When side-loading the epub to the device, the artwork loads fine. I'm guessing something in the Kobo Sync function for Calibre-Web isn't sending the artwork? Should I make this a separate issue?

_Originally posted by @ryanmichaelmcclure in https://github.com/janeczku/calibre-web/issues/2294#issuecomment-1034419198_

**Comment by dotvhs** [comment]
I have the same issue, all covers are just text-based, while casual EPUBs have them without any problem. I was wondering if perhaps using different Kepubify would give better solutions? There's option to set up external library for it in Calibre-Web, but I haven't tested that yet.

**Comment by zixiangx** [comment]
Facing the same issue here. EPub covers show up proper in the Calibre-Web portal, but when sync is done, the covers don't show up in Kobo Reader and instead displays just text on white background as the cover picture.

**Comment by OzzieIsaacs** [comment]
I can't reproduce the issue anymore in the newest version
