### ISSUE TITLE
OPDS page not visible, returning 404

### ISSUE THREAD

**Issue by epsilon-0** [janeczku/calibre-web#2315]
**Describe the bug/problem**
I have a calibre-web server running at https://lib.epsilonknot.xyz and when I visit https://lib.epsilonknot.xyz/opds I get a 404 not found error.

**To Reproduce**
Visit https://lib.epsilonknot.xyz/opds 

**Logfile**
N/A

**Expected behavior**
OPDS catalog should be found.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: calibre-web in docker latest image
 - Python version: python3.8
 - Calibre-Web version: 0.6.16
 - Docker container: LinuxServer
 - Special Hardware: N/A
 - Browser: Firefox 97.0

**Additional context**
N/A

**Comment by OzzieIsaacs** [comment]
I can reproduce the error with the url given by you. 
But I can't reproduce it with my instance (no docker). To me it looks like it's a problem of the docker image and/or the reverse proxy configuration of the docker image
