### ISSUE TITLE
Problem to changing the book cover

### ISSUE THREAD

**Issue by 416e6e61** [janeczku/calibre-web#2319]
After importing ebooks with both MOBI and EPUB format I can edit metadata but I don't see any option to change the cover (Upload from computer/fetch from URL)
![Capture](https://user-images.githubusercontent.com/95119948/155284550-32bcbcf5-693d-4704-966f-d2151c5515b2.PNG)

**Comment by OzzieIsaacs** [comment]
To see this option you have to allow uploads and also give the user the right to upload.
People use denying upload to security harden there calibre-Web instance and with this background it makes sense the way it works now
