### ISSUE TITLE
cover.jpg become very dark!

### ISSUE THREAD

**Issue by flyxj** [janeczku/calibre-web#2321]
When I update the cover of a book, the color of the cover becomes very dark. What is the reason for this? How do I modify it? Help me.

Calibre-Web 0.6.16 with newest three files: cps/static/js/details.js，cps/templates/detail.html and cps/static/js/caliBlur.js for fix #2285 .

 - OS: Synology DSM 7.0.1
 - Python version: 3.8.8
 - Calibre-Web version: 0.6.16
 - Calibre version: 5.35.0
 - Docker container: Docker in Synology DSM 7.0.1（version: 20.10.3-1239）
 - Special Hardware: DS1621+
 - Browser: Chrome , Firefox and Edge

![图像 001](https://user-images.githubusercontent.com/1892385/155684975-a21d49e9-eb84-4f8a-b8c8-866411a6142e.png)

**Comment by sbstratos79** [comment]
I am also facing this problem. I can provide more info if needed. Please let me know if anybody is willing to look into this issue.

**Comment by garylavayou** [comment]
Same problem still exists for version 0.6.24. Here is an example of a cover image before and after saving metadata.

Before saving:
![origin-cover](https://img1.doubanio.com/view/subject/l/public/s27226968.jpg "Original")
After saving:
![saved-cover](https://github.com/user-attachments/assets/bb46d362-f6c9-4d45-ad24-e95b7e162055 "Saved")

**Comment by LordSushiPhoenix** [comment]
I'm also seeing this behaviour, although it only started recently. Calibre-web v0.6.24 using the linuxserver.io docker image. The cover is correct in the preview when editing metadata, then appears darkened after saving. I can provide multiple cover examples if needed.

**Comment by Borrower543** [comment]
I'm also seeing this behavior, also using v0.6.24 using the linuxserver.io docker image.

**Comment by OdinsAuge** [comment]
I can confirm this on Version 0.6.24.
The cover that is included in the ebook stays how it is, but if you use "load Metadata" or upload a cover file on your own, it gets very dark.
