### ISSUE TITLE
Multi-libraries management

### ISSUE THREAD

**Issue by Tos26** [janeczku/calibre-web#2324]
Hello,

I switched from [COPS](https://github.com/seblucas/cops) to Calbre-web during January 2022 and I really appreciate this webapp.

However, a feature of COPS could be interesting for people: The multi-libraries management.
Is it possible to think about the ability to manage several calibre folders, in order to have several libraries in the same web interface thru only one server?

Thank you in advance to consider that.

**Comment by OzzieIsaacs** [comment]
Calibre-Web extends the features of the Calibre library (read status per user, kobo sync status) and has it's own settings for this. So it's not so easy to just organize more than one library. The Calibre-Web solution is to install/run mulitple instances of Calibre-Web. 
Your proposal would create a lot of efford, so I will not implement it.

**Comment by Tos26** [comment]
Ok. I understand.
Thank you to take time to answer.
