### ISSUE TITLE
Audiobook new player

### ISSUE THREAD

**Issue by webysther** [janeczku/calibre-web#2328]
**Describe the solution you'd like**
The [sample player](https://w3c.github.io/wpub/experiments/audiobook/index.html) for ['audiobook' w3c](https://github.com/w3c/wpub/) spec

**Describe alternatives you've considered**
Join all mp3 files or create a zip file for all audiobooks

**Comment by OzzieIsaacs** [comment]
The code is meanwhile 5 years in draft, the last commit is 2018. I don't want to implement this in calibre-web
