### ISSUE TITLE
ERROR in helper: make_mobi: kindlegen failed, no excecution permissions

### ISSUE THREAD

**Issue by syhily** [janeczku/calibre-web#233]
OS: macOS 10.13 Beta 3
I have placed the kindlegen in vendor directory and `chmod 777 kindlegen` to make it executable.
But still suck with this annoying error when trying to push a book in epub format.

**Comment by OzzieIsaacs** [comment]
Please try the newest commit it should now work again

**Comment by CHBMB** [comment]
This error also appears if the Linux kernel has been compiled without IA32 emulation support.  Been experimenting with docker and this which is how I managed to get to this conclusion, not sure how that affects Mac users, but it's worth noting.

**Comment by syhily** [comment]
Tks, the latest commit fix my issue.
