### ISSUE TITLE
Moving Calibre-web to a new server

### ISSUE THREAD

**Issue by bdollerup** [janeczku/calibre-web#2331]
I need to move my Calibre-web Docker-based server to a new location. I would like to move users and other customizations along. Do I simply copy the content of the /config folder to the new location?

Thanks!
Bjarne

**Comment by OzzieIsaacs** [comment]
I guess yes. You need the app.db file

**Comment by bdollerup** [comment]
Dang. That was easy. I'll try that asap.

Thanks!
