### ISSUE TITLE
Cannot fetch book metadata from Amazon

### ISSUE THREAD

**Issue by gabryon99** [janeczku/calibre-web#2333]
Hello, I recently updated Calibre Web to version 0.6.17, and I see that now is possible to use Amazon as metadata provider, which is fantastic! I tried to fetch some metadata from the new provider, but it doesn't work, the modal shows '_Search error!!_' (see screenshots below).

**To Reproduce**
1. Go to 'Books'
2. Click on a book
3. Click on 'Edit Metadata'
4. Click on 'Fetch Metadata'
5. Select Amazon as metadata provider
6. Search for the book
7. See the error

**Logfile**
I leave here the log file generated by Calibre Web.
[calibre-web.log](https://github.com/janeczku/calibre-web/files/8233505/calibre-web.log)

**Expected behavior**
The Amazon provider should work as the Google does.

**Screenshots**
<img width="910" alt="Screenshot 2022-03-11 at 17 01 59" src="https://user-images.githubusercontent.com/14114916/157904740-614ebbae-c15d-4b6c-ad03-4ec8bd91bff2.png">

**Environment:**
 - OS: Raspbian GNU/Linux 10 (buster)
 - Python version: Python 3.7.3
 - Calibre-Web version: 0.6.17
 - Docker container: None
 - Special Hardware: Raspberry Pi 4
 - Browser: Safari Version 15.3 (17612.4.9.1.8)

**Additional context**
No additional context.

**Comment by OzzieIsaacs** [comment]
Sorry seems I didn't give you feedback: 
Looks like the amazon service wasn't available for whatever reason (maybe you started to many requests and as in the background there are many requests send to amazon this is detected as beginning of a denial of service attack and getting blocked?). I updated calibre-web to catch this sort of errors now.

**Comment by Irv007** [comment]
Hi all,

I had to reinstall Calibre Web on a new instance.

Now, I have the error described in this post: "Search error" on metadata search with amazon.

Log attached.

I don't understand, why.

Can somebody explain that to me?

Environment:

OS: 20.04.1-Ubuntu
Python version: 3.8
Calibre-Web version: 0.6.19
Docker container: -
Special Hardware: Google Cloud Platform
Browser: Google Chrome Version 106.0.5249.91 

[logs calibre container.txt.txt](https://github.com/janeczku/calibre-web/files/9693090/logs.calibre.container.txt.txt)

**Comment by OzzieIsaacs** [comment]
Looks like, for whatever reason Amazon.com can‘t be accessed by calibre-web additionally this case isn‘t handled properly by calibre-web

**Comment by OzzieIsaacs** [comment]
Looks also the log file can‘t be written

**Comment by Irv007** [comment]
>>Looks also the log file can‘t be written
I will investigate that.

**Comment by Irv007** [comment]
Thank you.
