### ISSUE TITLE
Calibre-web with TrueNAS Core

### ISSUE THREAD

**Issue by PonyLucky** [janeczku/calibre-web#2335]
**Description**
I had some issues when it came to making Calibre-web work on my TrueNAS server. So I ask if you could add to the readme (or another file) a guide.

**Here is my guide**
1. Install calibre-web from the `Community` collection in the `Plugins` panel. 
![image](https://user-images.githubusercontent.com/60187395/158035779-564bb302-0b5c-4f08-b994-a99e1dc0c471.png)
2. Keep the `POST INSTALL NOTES` for further use 
![image](https://user-images.githubusercontent.com/60187395/158035832-656f1715-14ec-47d2-bc54-bba1c348a2fa.png)
3. Click on MANAGE to open your Calibre-web (the credentials are written in the notes you just kept in the format `[username]:[password]`)
![image](https://user-images.githubusercontent.com/60187395/158035872-2fd164f1-1042-43d8-9b22-4ca6950dbe97.png)
4. Now we're going to add our database (library). Go to the `Storage / Pools` panel and on your pool **add a dataset** (with SMB share type)
![image](https://user-images.githubusercontent.com/60187395/158035996-1f1cc822-9603-4a7b-9068-35b631919771.png)
5. Go to `Sharing / SMB / Add` and **add** Calibre
![image](https://user-images.githubusercontent.com/60187395/158036026-f50e4d2b-5f9a-4f6f-b200-b375b5996ac4.png)
6. Make sure SMB is enabled on the `Services` panel 
![image](https://user-images.githubusercontent.com/60187395/158036237-d5538ca4-22e3-4a34-b6f6-68907d075cc7.png)
7. Go back to the `Storage / Pools`, click on the vertical '...' of the **Calibre dataset** and click on `Edit Permissions` :
  - DELETE all items on `Access Control List` section
  - Add an item with *who* at `User`, *Permissions* at `Full Control` and *User* at `(your ID on the notes, mine is 488)` (it shows you an error message on the *User* but it works for me)
  - Add an item for you with your personal user or group (*Permissions* at `Full Control`)
  - Turn on `Apply permissions recursively`
  - Save
![image](https://user-images.githubusercontent.com/60187395/158036440-32d92859-b1ee-4e49-87da-0b88d7ca3a57.png)
8. Now we will link this dataset with Calibre-web (every plugin is into a 'jail', like Docker so we can not go to the good path directly). Turn off the calibre by clicking on the STOP button
![image](https://user-images.githubusercontent.com/60187395/158036629-2aeefcf0-ce34-493b-a315-fe45cd4ebe85.png)
9. Go to the `Jails` panel, open `calibre` jail and click on MOUNT POINTS
![image](https://user-images.githubusercontent.com/60187395/158036675-dbfb6195-6e16-46cb-b421-57e915b692f5.png)
10. On the ACTIONS button, click on ADD. Then select `Calibre` as the source and a new folder as the destination (you just need to write with the keyboard the folder you want). My destination is `/mnt/test/iocage/jails/calibre/root/library`. SUBMIT
![image](https://user-images.githubusercontent.com/60187395/158036782-86b27524-79b2-436f-a92c-564774ebe2f7.png)
11. Go on the Calibre Desktop App (on your Windows or Linux) and click on `Library / Change/Create a library`
![image](https://user-images.githubusercontent.com/60187395/158037021-96dcccb2-c7f5-44a6-a671-7da42495694b.png)
12. Select `\\[servername or ip]\[calibre dataset]` and check `Create`
![image](https://user-images.githubusercontent.com/60187395/158037092-426df080-1666-4440-bdad-aceb087eb6b6.png)
13. Add every book you want
14. START calibre-web and click on MANAGE to go to the main page. After login, enter the `Location of Calibre database`. If you did like me it's `/library`
15. You should already see every book you have
![image](https://user-images.githubusercontent.com/60187395/158037208-ec6fa4e8-ba17-4c82-93db-4a05c7bbfff2.png)

**Environment:**
 - OS: TrueNAS Core 12
 - Calibre-Web version: N/A (not specified on TrueNAS Community Collection)
 - Browser: Chrome

**Comment by OzzieIsaacs** [comment]
Thanks a lot. I copied it over to the wiki.
https://github.com/janeczku/calibre-web/wiki/How-To:-Install-on-True-NAS
The wiki is open to everybody, so please check what I did and if everything is still valid.
