### ISSUE TITLE
Activate /reconnect from Environmental Variables?

### ISSUE THREAD

**Issue by minchinweb** [janeczku/calibre-web#2336]
Historically, I've been using the `<host>/reconnect` URL to tell calibre-web to that the database has been updated. This has worked well, but in v 0.6.17 it seems you have to pass a a command-line argument (`-r`) to enable it. However, I am using a pre-built docker container (LinuxServer's) and so don't directly have access to the command line invocation (short of building my own docker container).

So is there a way to (re-)enable the `/reconnect` URL with the use of an environmental variable? Or really any way that wouldn't require me to build and maintain a "private" docker image?

Thanks!

**Describe the bug/problem**
`/reconnect` returns a 404 error

**To Reproduce**
1. run `curl <host>/reconnect`
2. get 404 error

**Expected behavior**
Successfully hit endpoint, and calibre-web reloads the database

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10/Raspberry Pi OS] Ubuntu
 - Python version: [e.g. python2.7] ?
 - Calibre-Web version: [e.g. 0.6.8 or 087c4c59 (git rev-parse --short HEAD)]: nightly, post 0.6.17
 - Docker container: [None/LinuxServer]: LinuxServer
 - Special Hardware: [e.g. Rasperry Pi Zero] "regular" x64 server
 - Browser: [e.g. Chrome 83.0.4103.97, Safari 13.3.7, Firefox 68.0.1 ESR] curl or Firefox (on Windows)

**Additional context**
Database is mounted read-only to Docker.

**Comment by OzzieIsaacs** [comment]
Please set environment variable CALIBRE_RECONNECT in the newest nightly version to have the /reconnect endpoint reenabled

**Comment by ma3d1um** [comment]
Hi, how do you set this environment variable correctly?
I tried:
```
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - DOCKER_MODS=linuxserver/mods:universal-calibre
      - CALIBRE_RECONNECT
```
but I still get the 404. 
Thanks!
Randy

**Comment by ma3d1um** [comment]
Ah! It should be 
`    - CALIBRE_RECONNECT=1`
Can be closed!

**Comment by MinchinWeb** [comment]
I have
```
- CALIBRE_RECONNECT=true
```
and it works for me too.
