### ISSUE TITLE
Calibre-Web fails to remember sort order

### ISSUE THREAD

**Issue by haertig** [janeczku/calibre-web#2340]
Reopening previous bug that was reported to be fixed quite a while back.  Issue #1987.  Still fails in version 0.6.17.

Calibre-web does not remember the previous sort order.

Click on a book series to display.  Display appears to be in random order.  Click one of the sort buttons - I normally choose to sort by series index ascending.  Sort functions correctly.  Now move to some other area of Calibre-Web.  Then move back to display a series.  Display appears in random order again, previous sort was not remembered.

Per developer response in closed issue #1987, Calibre-Web is supposed to remember sort order.

**Comment by OzzieIsaacs** [comment]
To make absolutely sure what we are talking about. We are talking about this screen:
![grafik](https://user-images.githubusercontent.com/6438895/159112599-93bcc69d-783f-4ed2-9802-88d453845c86.png)
You click on the left pane on series, choose a series and want this view to be remembered?
To clarify the expectations:
After choosing a sort order in one series, the same sort order applies to all other series (this is how it is supposed to work):
![grafik](https://user-images.githubusercontent.com/6438895/159112734-3ae2abd0-4f23-4017-9e9d-66aa4ddb891a.png)

Are you viewing the series as logged in user? The view for guest users is only remembered until the browser is closed

Please check in your browser if there are any errors showing up.
Are there any relevant entries in the calibre-web.log file?

**Comment by haertig** [comment]
Thanks for the help.  I appreciate it.  Calibre-Web is fantastic.

Your example sequence is the exact one I am attempting.  "Pick a series. Sort it. Go elsewhere. Come back to same series (or a different one) ... and it is unsorted again."

I am using the Guest login, but this is all within the same browser session.  I just tried logging in with my Admin login.  Same behavior when logged in as Admin as when using Guest.  Sorting not remembered.

The Browser I am using is Chromium.  I popped up the developer console and there were no errors logged.  I have also tried Firefox ... same result.  All browser extensions were disabled during my testing (ScriptSafe, AdBlockPlus, Ghostery, etc.)

Both my server running Calibre-Web and my client desktop running the browser are Linux.

Calibre-Web is being run out of a Docker container.  Specifically, https://hub.docker.com/r/linuxserver/calibre-web  I have tried several versions of this Docker image based on different versions of Calibre-Web.  Currently I am running a container based on Calibre-Web 0.6.14 because I had some issues logging in as admin with a container based on 0.6.17.  _Those issues are not related to this sorting problem, but FWIW, with 0.6.17 when I login as admin the top of the screen tells me "you are logged in as admin", but the little icon in the top right of the screen says I am still Guest.  I will debug this later, for the time being I just reverted back to a container based on the older version of Calibre-Web._

I went looking for the calibre-web.log file.  I found a problem - on my end.  The logfile had not been updated for a while (as in "several months").  This is inconsistent, since the Docker container, and thus Calibre-Web, is automatically restarted nightly.  I have four different containers for four different libraries running Calibre-Web, and all of them have not been updating the logfile as expected.  Although each instance works as expected (except for the sorting issue).  Some container logfiles were last updated two weeks ago, and some were updated several months ago.  This makes no sense given that all four containers are restarted nightly and are used frequently.  But this is my problem to debug, not yours.  As soon as I manage to get my logfiles to update appropriately, I will post any entries relevant to this sorting problem.  There are entries in these logfiles from several years ago, but they have tapered off recently.  So at some time the files were being updated.  Hmmm.  An interesting problem for me to debug.

Could I ask, what mechanism do you use to remember sort settings?  Is there something specific I could look for to see if it is being updated appropriately?  Given that I seem to be having a problem with my calibre-web.log file being updated as expected, hmmm, could that relate to I am seeing in sorting forgetfulness?

Here is an example of one of my container's "config" directories.  Note the large difference in timestamps between calibre-web.log and app.db.  app.db was just updated a few minutes ago, the last time I messed with the web interface.  And the unexpected end of entries in calibre-web.log in August of last year.  I just restarted the Calibre-Web containers maybe 30 minutes ago.  No logfile entries.  Yesterday, I deleted and recreated the Calibre-Web containers.  I would certainly expect that to have resulted in a logfile entry when I restarted them.  File permissions are good.  As a test, I even opened them up to mode 666, but that didn't help.

```
docker@linux-server-1 /var/opt/docker/production/app_data/calibre-web/novels $ ls -l
total 260
-rw-r--r-- 1 calibre calibre 114688 Mar 19 11:09 app.db
-rw-r--r-- 1 calibre calibre  99996 Aug  9  2021 calibre-web.log
-rw-r--r-- 1 calibre calibre      3 Aug 30  2020 client_secrets.json
drwxr-xr-x 2 root    root      4096 Oct  6 14:18 custom-cont-init.d
drwxr-xr-x 2 root    root      4096 Oct  6 14:18 custom-services.d
-rw-r--r-- 1 calibre calibre  32768 Aug 30  2020 gdrive.db

docker@linux-server-1 /var/opt/docker/production/app_data/calibre-web/novels $ head calibre-web.log
[2020-08-31 00:49:38,381]  WARN {cps.config_sql:297} Log path None not valid, falling back to default
[2020-08-31 00:49:40,679]  INFO {cps:98} Starting Calibre Web...
[2020-08-31 00:49:40,820]  WARN {cps.config_sql:324} invalidating configuration
[2020-08-31 00:49:40,936]  INFO {cps.server:156} Starting Tornado server on :8083
[2020-09-01 20:25:34,495]  INFO {tornado.general:289} Malformed HTTP message from 10.192.0.2: no colon in header line
[2020-09-01 20:26:54,852]  INFO {cps.web:1437} Login failed for user "admin" IP-adress: 10.192.0.2
[2020-09-01 20:37:38,081]  INFO {cps.server:207} webserver stop (restart=True)
[2020-09-01 20:37:38,093]  INFO {cps.server:189} Performing restart of Calibre-Web
[2020-09-01 20:37:39,747]  INFO {cps:98} Starting Calibre Web...
[2020-09-01 20:37:39,860]  INFO {cps.server:156} Starting Tornado server on :8083

docker@linux-server-1 /var/opt/docker/production/app_data/calibre-web/novels $ tail calibre-web.log
[2021-08-07 17:11:13,457]  INFO {cps.server:258} Performing shutdown of Calibre-Web
[2021-08-07 17:15:18,598]  INFO {cps:101} Starting Calibre Web...
[2021-08-07 17:15:18,712]  INFO {cps.server:205} Starting Gevent server on [::]:8083
[2021-08-07 17:23:36,005]  INFO {cps.server:273} webserver stop (restart=False)
[2021-08-07 17:23:36,006]  INFO {cps.server:258} Performing shutdown of Calibre-Web
[2021-08-07 17:23:48,125]  INFO {cps:101} Starting Calibre Web...
[2021-08-07 17:23:48,239]  INFO {cps.server:205} Starting Gevent server on [::]:8083
[2021-08-08 05:16:30,372]  INFO {cps.helper:696} Downloading file: /books/Clifford D. Simak/Over the River & Through the Woods (2858)/Over the River & Through the Woods - Clifford D. Simak.epub
[2021-08-08 09:00:40,153]  INFO {cps:101} Starting Calibre Web...
[2021-08-09 09:00:47,961]  INFO {cps:101} Starting Calibre Web...

docker@linux-server-1 /var/opt/docker/production/app_data/calibre-web/novels $
```

**Comment by OzzieIsaacs** [comment]
Normal user:
If you open a series from the left navigation and click on the series name or series picture the route "series/stored/[number]" is called. The python backend then calls current_user.get_view_property this reads the field `view settings` in `user` table in the `app.db` database (sqlite). 
![grafik](https://user-images.githubusercontent.com/6438895/159157290-51e790d2-1faa-4033-bccc-fb23012d0e05.png)
There you see for series the stored value is authaz in my example.
If you change the order by clicking order according to series order the route "series/seriesasc/[number]" is called this leads to a write access the the same field in the database and the content will be "series": {"stored": "seriesasc"}

**Comment by OzzieIsaacs** [comment]
For guest user the data is stored in the session cookie (encypted with the flask secret key for your instance so can't be easily read from browsersite):
![grafik](https://user-images.githubusercontent.com/6438895/159157581-038d4fe6-f2a5-49b6-b0e8-de6b35c68b4e.png)
Anything else is working as desribed above (but not stored in database but in this cookie). So each time you navigate to a new section where the current guest session never was before the new value for this section is written to the cookie, so the cookie length should grow over time.

**Comment by haertig** [comment]
Thanks for telling me the method you use to store sort order memory.  That helped with my debugging.

For the logged in user case:

Since you store the sort preference in add.db, and I could see that my app.db was being updated, I figured I'd try debugging this case first.  I think I found the answer.  I did get Calibre-Web to remember sort preference in some cases, but not all.  Here's what happens: When you pick a series from the "Series" menu choice on the upper left of the screen, and you use this exact method to select a different series, Calibre-Web does indeed remember your sort preference.  But what I was doing and not thinking about, was intermixing this series choice method with the alternate choice method of clicking on the series indication that sits under the display of a specific book.  Once you use what I'm calling the "alternate choice method", that appears to reset any sort preference that was remembered.  I will try to attach a screenshot making it clear what I mean by these two choice methods.  If my image attaches successfully below, then the method highlighted in RED is the one that will successfully remember sort preference.  But if you ever use the method highlighted in YELLOW, then any previously remembered sort preference is forgotten.

![SeriesChoiceMethod](https://user-images.githubusercontent.com/41701764/159175050-80c306be-8701-4782-87c7-0096e431e706.jpg)

For the Guest user case:

Since you mentioned the use of cookies to remember sort preference, I immediately thought that this could be affected by setting on the client web browser.  I have been doing my testing with all my browser extensions disables and with all cookies, even third party ones, allowed.  However, I figured a clean break would be best.  So I booted a different computer of mine off of a Linux Live CD so that I was completely assured that no settings I had made or extensions I had installed were running interference.  Using this "clean" setup and after verifying in the browser (Firefox) settings that all cookies were allowed, JavaScript was enabled, blah, blah, blah (I did not change any of the default settings, I just verified that they were set correctly - which they were) - I proceeded to test again.

Sort preference was NOT remembered, no matter what I did.  I tried both "choice methods" as I described above, but neither of them ever resulted in sort preference memory.  Next, I looked at the current cookies that were set in the browser.  There was not a single one.  No cookies = no sort preference memory based on what you said Calibre-Web does in the Guest case.  I believe that booting from a "clean" Live CD pretty much rules out any client settings blocking required cookies.

So I looked at my Calibre-Web SERVER setup to see if somehow I might be blocking the ability to set cookies.  I wouldn't know how to do that if I tried, but I attempted to debug none-the-less.  If you recall, I pointed out that I am running Calibre-Web from a Docker container.  In addition to that, I am using NGINX web server in a different Docker container as a reverse proxy for the Calibre-Web container.  So I took the reverse proxy out of the picture.  I exposed the Calibre-Web port from it's Docker container and accessed it by connecting directly to that container, totally bypassing my NGINX reverse proxy in the process.  Unfortunately, that did not change anything.  Sort preference was forgotten again.  No cookies were set.

While playing around and testing some more, I went back to the logged in user case.  And I noticed that a cookie WAS set by Calibre-Web when I was logged in.  I could not see what this cookie said, but I could see it was present and from the domain where I have Calibre-Web running.  But this cookie had not appeared when I was running as Guest.  This appears to illustrate that Calibre-Web is indeed able to set cookies in my specific server setup.  Why it is in one case, but not in others, is a mystery to me.  I will continue to troubleshoot this.

Sorry for the length of this post.  But when I see one behavior and you are not able to duplicate it, even the smallest of details could be the culprit, so I was intentionally verbose.

Thanks for the help!

**Comment by OzzieIsaacs** [comment]
I‘ll have a look at the logged in case, this is something I can debug.

**Comment by OzzieIsaacs** [comment]
Total desaster: From many links the order was set to "new" for authors and series. It's fixed in the newest nightly version. This behavior applied for both guest and logged in users. So maybe your issue is now fixed (after updating your container to the newest nightly version)

**Comment by haertig** [comment]
I created a new Docker container based on the the NIGHTLY version of calibre-web pulled on Mar 23, 2022.

I can confirm that all of my "sort preference memory" issues have been resolved.  For both the logged in user case, and for the guest case.  As a bonus, I now see the sort indicator icon is highlighted when I move back into a series display, indicating that it was remembered from previous.  I did not expect this.  Nice touch!

As far as I am concerned, you may close this issue as "FIXED" at your convenience.  I will attempt to close it myself, since I see there is a "Close issue" button.  But I've never done that before and if I mess it up when I try now, please close it for me.

Thank you very much for addressing this and solving it so quickly!
