### ISSUE TITLE
Limit sharing a book with other users

### ISSUE THREAD

**Issue by arsinux** [janeczku/calibre-web#2343]
**Describe the bug/problem**
As far as I can see, currently, all users have access to all the books. What happens if a user wants to only upload a book just for itself and not share it with other users? Not sure if this is an intentional design or I am not able to find the feature I need. Basically what I need is for users to have the ability to keep their books for their own if they wanted and not share them with every other user. 
I tried to see if Shelves module can be a workaround, but still one can access all books via Books module.

**Expected behavior**
Having the ability to change access levels of a book (only me, everyone), either upon uploading the book or at any time after the book is uploaded.

**Comment by OzzieIsaacs** [comment]
You can use a custom column or a tag for this kind of feature.
A) So user1 restrict visible books to only books with category "user1" and so on for every user. 
B) Or each user has it's own exclusive tag, like category "exclusive_user1 and all other users are not allowed to view books with this category. 
https://github.com/janeczku/calibre-web/wiki/Configuration#default-settings-and-visibility-for-new-users

For new uploaded books to calibre-web books both little sideeffects:
If you use version A) the user would not see the book after uploading, as it doesn't have the category and for version B) all users can see the book until all tags are attached to the new book

**Comment by arsinux** [comment]
Seems like a good workaround. Thanks.
I am just not sure how to set it up in Calibre-web?
As my setup is content server I do not have access to the GUI of Calibre to set Custom Columns.
I wonder if I can set Custom Columns in Calibre-web?
I tried finding myself, Googled and also searched the user guide. Could not find. Would appreciate your help.
And if this could become a feature in future, that would be much appreciated.
Thanks for the great tool!

**Comment by OzzieIsaacs** [comment]
> I am just not sure how to set it up in Calibre-web?
> I wonder if I can set Custom Columns in Calibre-web?

Sorry for the late reply, the message got lost (in my emails). This is indeed not supported by Calibre-Web itself. You need to copy the metadata.db file from your library to a computer running Calibre (Operating system is not relevant) and add the Custom column there. Then copy the metadata.db (backup!) back to your "Server", restart Calibre-Web and it will show up.

Currently I'm way behind the issues, so I have to focus. The feature will not be implemented in the future, sorry
