### ISSUE TITLE
Edit Basic Configuration: Save Button does not work with ssl.

### ISSUE THREAD

**Issue by maarlo** [janeczku/calibre-web#2344]
Using version 0.6.17 and Calibre Web with SSL (Let's encrypt certs), Save button of Edit Basic Configuration doesn't work. If SSL is not used, it works.

**Comment by maarlo** [comment]
It also happens with send to Kindle

**Comment by maarlo** [comment]
It happens since version 0.6.13

**Comment by OzzieIsaacs** [comment]
What OS are you using, how do you start calibre-web? (Exefile, python direct, docker, ...)
If we are talking about SSL what do I have to imagine how you are using it? via Reverse proxy (which one, configuration according to wiki or different, using it with a subdomain, or access it wia a "path" ../calibre-web)? Or are you using the ssl configuration from within calibre-web?
What does save button isn't working mean? There is no reaction from calibre-web, or is itshowing a blank screen, you are directed to somewhere else, or is it showing a error message or something else?

**Comment by maarlo** [comment]
I'm using Debian 10. I start it using the command line and from the python environment (Python 3.7). I'm not using reverse proxy, I use the ssl configuration from calibre-web.

It means that when it is supposed to send a ajax request, it doesn't send anything, as a consequence, there is no reaction from calibre-web.

**Comment by OzzieIsaacs** [comment]
Is there any output on the developer console of the browser?

**Comment by maarlo** [comment]
``DevTools failed to load source map: Could not load content for https://webpage/static/js/libs/jquery.form.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE``, only this, but it is also at version 0.6.12 in which works.

**Comment by OzzieIsaacs** [comment]
Yes, this is okay and not relevant

**Comment by OzzieIsaacs** [comment]
I can't reproduce this: 
I started calibre-web server with standard configuration listening on port 8083
logging in with standard admin acount
Pointing to my calibre-database -> saving
Go to admin -> basic configuration -> server configuration -> entering ssl certificate and ssl private key, press save
Blue line with spinning "wheel" is showing up -> status isn't changing (server is no longer responding to http requests, so the browser never gets response from calibre-web)
Manually entering https in browser address line, pressing enter (wait proper time to give calibre-web time to restart)
Calibre-web is showing up again
Press on any button you want -> calibre-web works
Go to admin -> basic configuration -> server configuration -> change update channel to nightly, press save -> green success message shows up

**Comment by OzzieIsaacs** [comment]
To be complete, the Calibre-web configuration:
![image](https://user-images.githubusercontent.com/6438895/161379937-d81aea12-9b95-4c20-a67d-89641149f5e2.png)

**Comment by zanhecht** [comment]
I'm having the same issue, except I'm using an nginx reverse proxy for SSH. If I directly connect to my server at 127.0.0.1:8083 I can save the settings directly, but when I go to https://myserver.com/calibre clicking the "Save" button doesn't do anything. This started after an upgrade from 0.6.11 to 0.6.19. I'm using the following nginx configuration:

`    proxy_set_header X-Forwarded-For $remote_addr;
    location /calibre/ {
        allow 192.168.0.0/16;
        allow 172.16.0.0/12;
        allow 10.0.0.0/8;
        deny all;
        proxy_bind              $server_addr;
        proxy_pass              http://127.0.0.1:8083;
        proxy_set_header        Host            $http_host;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Scheme        $scheme;
        proxy_set_header        X-Script-Name   /calibre;  # IMPORTANT: path has NO trailing slash
        client_max_body_size    1024M;        
    }`
