### ISSUE TITLE
Reverse proxy for docker-calibre-web with Nginx on non-standard port

### ISSUE THREAD

**Issue by kingchl** [janeczku/calibre-web#2348]
**Describe the bug/problem**
Hi there.
When I login the Calibre-Web across my domain `https://calibre-web.mydomain.com:8888`, the web will redirect to `https://calibre-web.mydomain.com/login?next=%2F` rather than `https://calibre-web.mydomain.com:8888/login?next=%2F`.

I have to add this `non-standard port` (`8888`) manually to the address, then the login page gets back.
And after I inputted the correct account&password, the URL will also losing the non-standard-port (redirecting to `https://calibre-web.mydomain.com`).

For this case when I encountered in other server applications, there could be a URL settings in the configuration file like `.env`, or in the server settings page, to sett as `URL = https://calibre-web.mydomain.com:8888`. But I haven't found it in there.

Or it seems that this problem can also be sloved by configuring the Nginx reverse-proxy config-files, but I don't know how to handle with it.

can you help me? thanks anyway

**Environment (please complete the following information):**
 - router (port: 8888) -PortForwarding-> nginx (port: 443 https) -RverseProxy-> docker-calibre-web (port: 8083 http)
 - OS: [QTS5.0 on Qnap NAS]
 - Calibre-Web version: [0.6.17]:
 - Docker container: [LinuxServer]:
 - Special Hardware: [Qnap TS-264C]

**Comment by MartinJindra** [comment]
Which programm do you use as a reverse proxy?

**Comment by kingchl** [comment]
> Which programm do you use as a reverse proxy?

docker-swag, by LinuxServer

**Comment by OzzieIsaacs** [comment]
I left out the ssl part and I'm not using docker:
Setup my router to forward port 8888 to port 80 on my computer:
![grafik](https://user-images.githubusercontent.com/6438895/161392221-5395593e-7b82-4b92-b3bd-472fc6b5c87b.png)

Installed nginx on my Linux Mint computer:
![grafik](https://user-images.githubusercontent.com/6438895/161392267-02a5dfd6-8202-444f-87cb-562196b7aace.png)

Started calibre-web to serve on the standard port 8083
Opened a private browser window, entered my dyndns-subdomain:
![grafik](https://user-images.githubusercontent.com/6438895/161392360-7bc8e269-6873-4c26-a8a9-abeee3143ba2.png)
Generated links showing :8888 and act as expected:
![grafik](https://user-images.githubusercontent.com/6438895/161392412-09c85d00-3057-4f90-b9a7-d287906bbc74.png)

My nxnix.conf file unchanged from dist installation

My nginx config /sites-enabled/default:
```
server {
        listen 80 default_server;
        listen [::]:80 default_server;

            client_max_body_size 20M;
            location / {
                proxy_bind              $server_addr;
                proxy_pass              http://127.0.0.1:8083;
                proxy_set_header        Host            $http_host;
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header        X-Scheme        $scheme;
                # proxy_set_header        X-Script-Name   /;  # -> this is wrong in the wiki, I'll update it
            }

        server_name _;

}
```
I captured a packet with wireshark, the header looks like this:
![grafik](https://user-images.githubusercontent.com/6438895/161392573-ba237372-ffac-4cbc-864d-ce57f5add77a.png)

Scheme should for your usecase https (but of course encrpyted, so not so easy visible)

**Comment by OzzieIsaacs** [comment]
I finally changed the port to 81 to not have a standard port, where something could work because it's "default".
If you could provide config files for non-working (and maybe you can narrow it down, so I don't have to setup everything to reproduce it) we can continue to investigate the problem

**Comment by OzzieIsaacs** [comment]
I case you didn't had a look at the wiki: https://github.com/janeczku/calibre-web/wiki/Setup-Reverse-Proxy#nginx

**Comment by bigcat26** [comment]
I have encountered the same issue, even I have added the directives mentioned in https://github.com/janeczku/calibre-web/wiki/Setup-Reverse-Proxy#nginx

**Comment by hoopan007** [comment]
If using SSL in your reverse proxy on a non-standard port (e.g.12345), the following proxy_redirect line may be required:
`proxy_redirect http://$host/ https://$host:12345/;`
