### ISSUE TITLE
Missing module 'dataclasses' on python <3.7

### ISSUE THREAD

**Issue by teflontoni** [janeczku/calibre-web#2349]
```
Traceback (most recent call last):
  File "cps.py", line 45, in <module>
    from cps.search_metadata import meta
  File "/opt/weblibrary/cps/search_metadata.py", line 26, in <module>
    from dataclasses import asdict
ModuleNotFoundError: No module named 'dataclasses'
```
I tried updating calibre-web now this is the output, what I am missing?

**Comment by teflontoni** [comment]
Okay, so I installed dataclasses, but now the redirect following the login isn't working.

Calibre-Web says logged in as _Username_ but I am still on the login screen. I am behind a reverse proxy btw.

**Comment by teflontoni** [comment]
Okay, after some back and forth, it works as expected.

**Comment by OzzieIsaacs** [comment]
Import error shall be handled and logged on python versions <3.7
