### ISSUE TITLE
loop login

### ISSUE THREAD

**Issue by 404gods** [janeczku/calibre-web#2351]
I used the docker version of calibre-web and used the CDN service. I found that there would be a problem after about a day. After logging in, the user still returned to the login interface, and it was logged in circularly, unable to come to the console, there was no error in the logs, and it will return to normal after restarting the container, I don't know where the problem is.sorry for my bad English .

**Comment by AnonTester** [comment]
debug log of login-loop on my system may be related. It appears that sometimes the db is locked and thus cannot store login details.
[login-issue-locked-db-sesson-not-saved-calibre-web.log](https://github.com/janeczku/calibre-web/files/8358550/login-issue-locked-db-sesson-not-saved-calibre-web.log)

**Comment by 404gods** [comment]
> 我的系统上的登录循环的调试日志可能相关。有时数据库似乎被锁定，因此无法存储登录详细信息。 [login-issue-locked-db-sesson-not-saved-calibre-web.log](https://github.com/janeczku/calibre-web/files/8358550/login-issue-locked-db-sesson-not-saved-calibre-web.log)

Yes, I also found the same log content, it seems we have the same problem.

**Comment by LordZappZarapp** [comment]
Same here.
Running Calibre-web (0.6.17) in LXC-Container using Debian 11
[Calibre.txt](https://github.com/janeczku/calibre-web/files/8366138/Calibre.txt)

**Comment by LordZappZarapp** [comment]
Issue #2350 and #2351 seem to be the same Problem.
The Logs are very similar.

**Comment by OzzieIsaacs** [comment]
If possible for you please try to update to the newest nightly version or alternatively if possible try to uninstall gevent

**Comment by OzzieIsaacs** [comment]
Awesome, was a tricky issue
