### ISSUE TITLE
Transfer settings between installed instances

### ISSUE THREAD

**Issue by Basemaly-pratt** [janeczku/calibre-web#2352]
**Is your feature request related to a problem? Please describe.**
Is there a way to transfer settings, like user accounts and shelves between different instances of Calibre-Web? Are all the settings located within a few files that can be copied to a new instance?

**Describe the solution you'd like**
An easy way to transfer settings between different Calibre-Web instances. 

**Describe alternatives you've considered**
A migration tool

**Comment by Jerome2103** [comment]
The settings are in the "app.db" databases.

**Comment by OzzieIsaacs** [comment]
https://github.com/janeczku/calibre-web/wiki/FAQ#how-to-backup-calibre-web-settings
