### ISSUE TITLE
The div.cover container is way larger than the cover itself.

### ISSUE THREAD

**Issue by OrvilleQ** [janeczku/calibre-web#2354]
**Describe the bug/problem**

The `div.cover` container is way larger than the cover itself.

**Screenshots**
![image](https://user-images.githubusercontent.com/21377465/160829436-9e766eca-fefc-4b18-addb-1ba2bcc46652.png)

**Environment (please complete the following information):**
 - OS: Linux 5.3.18
 - Python version: 3.6.15
 - Calibre-Web version: 0.6.17
 - Docker container: None
 - Browser: Edge

**Comment by OzzieIsaacs** [comment]
Depends on the cover:

![grafik](https://user-images.githubusercontent.com/6438895/164729822-1afcb82d-2bff-4313-97a8-2055bff9c645.png)
