### ISSUE TITLE
Add option to cache cover images when using gdrive storage

### ISSUE THREAD

**Issue by belst** [janeczku/calibre-web#2355]
Since fetching cover images from gdrive requires 2 requests (one to calibre-web which returns 302 and then the actual request to gdrive) it often takes quite a while to display the images or even fails because of rate limiting.

A nice option would be to cache images locally on the server somewhere and serve those directly instead of hitting the gdrive api constantly.

**Comment by OzzieIsaacs** [comment]
There is an PR addressing this: #1771

**Comment by OzzieIsaacs** [comment]
The PR is merged:
- Please update to the newest nightly version
- Install APScheduler via pip
- Restart Calibre-Web
- Go into admin section enter edit schedule task settings, enable "Generate Book Cover Thumbnails", change the regular update time if you want (only needed for sideloaded books via Calibre), save setting
- go to admin section Click on Refresh Cover Thumbnnail cache
- Check Tasks section and wait some minutes until all thumbnails are generated

Enjoy
