### ISSUE TITLE
how to avoid being indexed by search engines?

### ISSUE THREAD

**Issue by 404gods** [janeczku/calibre-web#2358]
My calibre-web is indexed by Google, which is not the result I want, I found the robots.txt file in the following file directory, but it doesn't seem to work.

/usr/local/lib/python3.8/dist-packages/tornado/test/static/robots.txt

root@calibre-web:/# cat /usr/local/lib/python3.8/dist-packages/tornado/test/static/robots.txt
User-agent: *
Disallow: /

I tried adding a robots.txt file under /app/calibre-web/cps/static/ as well, but visiting https://mydomain.com/robots.txt or https://mydomain.com/static/robots. txt, the browser prompts a 500 error.
is this normal?

Please tell me how to avoid being indexed by search engines? Thank you so much!

**Comment by OzzieIsaacs** [comment]
https://github.com/janeczku/calibre-web/wiki/Extend-Features#use-your-own-robotstxt-file
this is the way to do it. It should be available under https://mydomain.com/robots.txt afterwards. In case of a 500 error something should logged in calibre-web.log. Beside this, the form you deleted also asks for the version you are using and if you are using Linux, windows or docker and if you are using a reverse proxy. This all would be helpful answers

**Comment by OzzieIsaacs** [comment]
The automatic text 2 days 4 days ago showed also that it's working:
![grafik](https://user-images.githubusercontent.com/6438895/161411975-c7e3ff35-519c-4a98-9c7f-6eca10d06c57.png)

**Comment by 404gods** [comment]
Thank you very much for your patient answer.
I am using Docker calibre-web.
1) After I added the robots file,
root@calibre-web:/# cat /app/calibre-web/cps/static/robots.txt
User-agent: *
Disallow: /

2) Visit https://mydomain.com/robots.txt , it will prompt an error:
Internal Server Error
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/app/calibre-web/cps/web.py", line 1371, in get_robots
return send_from_directory(constants.STATIC_DIR, "robots.txt")
File "/usr/local/lib/python3.8/dist-packages/flask/helpers.py", line 700, in send_from_directory
return werkzeug.utils.send_from_directory( # type: ignore
File "/usr/local/lib/python3.8/dist-packages/werkzeug/utils.py", line 852, in send_from_directory
return send_file(path, environ, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/werkzeug/utils.py", line 752, in send_file
file = open(path, "rb") # type: ignore
PermissionError: [Errno 13] Permission denied: '/app/calibre-web/cps/static/robots.txt'

3) calibre-web.log error content:

[2022-04-03 18:01:03,246] ERROR {cps:1457} Exception on /robots.txt [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/calibre-web/cps/web.py", line 1371, in get_robots
    return send_from_directory(constants.STATIC_DIR, "robots.txt")
  File "/usr/local/lib/python3.8/dist-packages/flask/helpers.py", line 700, in send_from_directory
    return werkzeug.utils.send_from_directory( # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/utils.py", line 852, in send_from_directory
    return send_file(path, environ, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/utils.py", line 752, in send_file
    file = open(path, "rb") # type: ignore
PermissionError: [Errno 13] Permission denied: '/app/calibre-web/cps/static/robots.txt'
[2022-04-03 18:02:07,710] ERROR {cps.db:791} Author (US) lawrence Cunningham not found to display name in right order

Thanks again for your hard work!

**Comment by OzzieIsaacs** [comment]
> PermissionError: [Errno 13] Permission denied: '/app/calibre-web/cps/static/robots.txt'

Calibre-Web can‘t open the robots file. I have no idea about this docker stuff, so I can‘t help more beside this

**Comment by 404gods** [comment]
Thank you very much, I updated to the night version, and now I visit mysite.com/robots.txt, the error message becomes 403 forbidden, and the calibre-web.log prompts: ERROR {cps.web:1374} No permission to access robots.txt file.
What does this mean?

Thank you

**Comment by OzzieIsaacs** [comment]
Calibre-Web can‘t open the robots.txt file (access permissions). I have no idea about this docker stuff, so I can‘t help more beside this

**Comment by mendhak** [comment]
@404gods are you using Docker Compose?  I've done it like so, in the volumes I've mapped a robots.txt:

```
volumes:
      - ${PWD}/data:/config
      - ${PWD}/books:/books
      - ${PWD}/robots.txt:/app/calibre-web/cps/static/robots.txt 
```

And /robots.txt works for me. 

If you have a webserver like nginx in front of Calibre-web,  you can also do it there instead of in calibre-web:

```
location = /robots.txt {
  add_header  Content-Type  text/plain;
  return 200 "User-agent: *\nDisallow: /\n";
}
```

You can also set an `X-Robots-Tag` against all URLs: 

```
add_header  X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";
```

**Comment by 404gods** [comment]
> @404gods are you using Docker Compose?  I've done it like so, in the volumes I've mapped a robots.txt:
> 
> 
> 
> ```
> 
> volumes:
> 
>       - ${PWD}/data:/config
> 
>       - ${PWD}/books:/books
> 
>       - ${PWD}/robots.txt:/app/calibre-web/cps/static/robots.txt 
> 
> ```
> 
> 
> 
> And /robots.txt works for me. 
> 
> 
> 
> If you have a webserver like nginx in front of Calibre-web,  you can also do it there instead of in calibre-web:
> 
> 
> 
> ```
> 
> location = /robots.txt {
> 
>   add_header  Content-Type  text/plain;
> 
>   return 200 "User-agent: *\nDisallow: /\n";
> 
> }
> 
> ```
> 
> 
> 
> You can also set an `X-Robots-Tag` against all URLs: 
> 
> 
> 
> ```
> 
> add_header  X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";
> 
> ```

marvelous!  thank you very much
