### ISSUE TITLE
import multi library

### ISSUE THREAD

**Issue by fangod123** [janeczku/calibre-web#2359]
I have many library in my calibre, and source file in different folder(like D:/comic and D:/newspaper), so i want this program can import not only one folder, like web serve of calibre which you can choose which library you want to going to. That is better if there are some mark show that which book is come from which library.

**Comment by OzzieIsaacs** [comment]
Please have a look here: https://github.com/janeczku/calibre-web/wiki/FAQ#how-to-handle-multiple-calibre-libraries
