### ISSUE TITLE
OPDS lists sometimes take a while to update after book is added

### ISSUE THREAD

**Issue by matejdro** [janeczku/calibre-web#2367]
**Describe the bug/problem**

After adding books to calibre-web, OPDS lists (such as "Recently added Books"  or "Alphabetical / All") seem to take a while to update. Books do appear in web interface (and I can see them at the top when sorting by added date) and they do appear in OPDS if I search for them, but they will not appear in actual lists for a while.

**To Reproduce**
1. Have calibre-web running in the background
2. Open Calibre (the desktop app) with the same database that calibre-web uses
3. Add a book to the database
4. Close Calibre
5. Open calibre-web in browser
6. Ensure that book you added is there
7. Open calibre-web's OPDS in koreader
8. Open "Recently added Books"
9. Note that book you just added is not there

**Logfile**

When I open DPMS, calibre-web will only generate bunch of `Author X not found to display name in right order` lines into the log, even in debug mode. Could those be relevant?

**Expected behavior**

Newly added book should be immediately available in the OPDS

**Environment (please complete the following information):**
 - OS: `Linux 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64 `
 - Calibre-Web version:: 0.6.19 Beta
 - Docker container: LinuxServer
-  E-Reader: Koreader 2022.03

**Comment by OzzieIsaacs** [comment]
> When I open DPMS, calibre-web will only generate bunch of Author X not found to display name in right order lines into the log, even in debug mode. Could those be relevant?

This messages are hinting towards inconsistencies in the calibre library (most likely with upper-lowercase names). To exclude this please execute a library check (library maintenance -> check library) in Calibre. 80% chance it's not the reason.

I can't reproduce this behavior with a normal installation. Many of the docker complains have to do with library updates with changes from outside. This is not a problem of Calibre-Web itself.

**Comment by matejdro** [comment]
Can I enable more logging somehow to help diagnose the issue?

**Comment by OzzieIsaacs** [comment]
In admin section basic configuration log configuration set the log level to debug

**Comment by matejdro** [comment]
Yes, I already set that to debug mode and OPDS made no more logs :/

**Comment by matejdro** [comment]
Sorry, my bad, it seems the problem is with koreader. Opening `/new` catalog in browser .works fine.
