### ISSUE TITLE
Issue with linux DB location

### ISSUE THREAD

**Issue by cwesterfield** [janeczku/calibre-web#237]
Trying to use `/Books/Calibre\ Library/` but I keep getting `DB location is not valid, please enter correct path`.

cwesterfield@calibre:~/calibre-web# ls -lah /Books/Calibre\ Library/metadata.db
-rw-rw-rw- 1 500 users 1.2M Jul 14 19:21 /Books/Calibre Library/metadata.db

I've tried as many variations as I could think of, but it refuses to be cool. The log file doesn't have any real helpful lines to get me where i need to go.

**Comment by OzzieIsaacs** [comment]
Try enter the path without "\" before space

**Comment by cwesterfield** [comment]
I got it!

/Books/Calibre Library/

Is what it wanted. Thank you very much!

**Comment by yochaigal** [comment]
Hello - I'm having this issue as well. It will not recognize '/home/yochai/Calibre Library/metadata.db' with or without single/double quotes, or escape characters.  It just keeps saying:  "DB location is not valid, please enter correct path."

**Comment by OzzieIsaacs** [comment]
/home/yochai/Calibre Library Should work

**Comment by yochaigal** [comment]
Ah, silly me! I thought I had tried that. Thanks!
