### ISSUE TITLE
Trusted Hosts? 

### ISSUE THREAD

**Issue by rickcecil** [janeczku/calibre-web#2372]
(Not sure if this is the right ticket type or not. It's a setup question and this seemed like the best match.)

I have a bookmarklet that loads a local annotation service in the browser. In theory, I should be able to use it to annotate books using either the PDF or ebook reader provided by Calibre Web. However, this doesn't work because my annotation service runs on a separate local domain and Calibre-Web's Content Security Policy is preventing the service from loading.

I am using Docker to run Calibre-Web, which means that I can't just edit web.py to include my hosts. Ideally, I would like to continue using Docker for Calibre-Web. I am hoping that you could give me guidance on the best approach to adding my internal domain to the Content Security Policy.

I've been doing quite a bit of research over the last few days and think there are several possible solutions. Though, if there is a better, faster path, please point me in that direction! :)

Here are there different approaches to solving this and the different problems that I've run into:

1.  Is there an environment variable that I can set to add new hosts to the Content Security Policy? I don't think that there is, but I thought it would be worth asking.
 

2. Taking a closer look at web.py I see this line:

>     csp += ''.join([' ' + host for host in config.config_trustedhosts.strip().split(',')])

Is there a config file that I can put in the mounted config directory to make this edit? Or some other way that I can add domains to trustedhosts?

3. I could edit the Dockerfile to copy over an edited file with my updates. This seems doable, but I need some help with this (specific to calibre-web not Docker). When docker runs, is web.py generating another file that specifies the CSP or is web.py specifying the the CSP and I just need to overwrite that file? Do you know the location on the Docker image where web.py would live? (That might be more of a Docker question, but I thought I would ask.)

4. I could build my docker image from a local version of the code with the appropriate edits made to web.py. This seems like a straight-forward idea. Though, probably last on my list of things to try.

5. Install Calibre-web manually and run it in a virtual environment such that I can edit the lines of code myself. I tried this and ran into some errors, so gave up. I am certain that I could sort all of that out. I just prefer to run things in Docker. 

I do appreciate any help or pointers that you can provide. Calibre Web is fantastic!

**Comment by rickcecil** [comment]
I ended up using option #3 and it is working ... mostly. I can annotate things in the PDF reader, but not in the epub reader. I need to investigate more.

**Comment by OzzieIsaacs** [comment]
Number 2:
Just enter the additional trusted hosts names in basic configuration in the UI:
![grafik](https://user-images.githubusercontent.com/6438895/163663508-7e26e907-c23f-497c-a7b9-e27a3975726d.png)

**Comment by OzzieIsaacs** [comment]
For number 5: The easiest way would be to just install calibre-web via pip in an virtual environment, as you mentioned.
For the next releases I will provide a .deb file as it seems many users having trouble installing calibre-web and the docker stuff is also generating a lot of trouble

**Comment by rickcecil** [comment]
> Number 2:
> Just enter the additional trusted hosts names in basic configuration in the UI:

I can't believe I missed that. I should have known you would have made it easy. Well, maybe others will see this post and it will help them. :)

Appreciate the response. I'll just focus on the fact that I learned quite a lot in troubleshooting this issue. 

-R

**Comment by rickcecil** [comment]
For anyone else coming across this in the future, here are the steps to get to the "Trusted Hosts" configuration in the admin:

1. Admin Dashboard (not profile)
2. Under Configuration section, click "Edit Basic Configuration"
3. Expand "Server configuration"
4. Add your domains to the "Trusted Hosts" field. Comma separated
