### ISSUE TITLE
Calibre-web docker problem

### ISSUE THREAD

**Issue by jra47** [janeczku/calibre-web#2373]
<!Calibre Web
Erreur Interne du Serveur
500 Erreur interne du serveur : le serveur a rencontré une erreur interne et n'a pas pu traiter votre demande. Soit le serveur est surchargé, soit il y a une erreur dans l'application.
Traceback (dernier appel le plus récent) :
Fichier "/usr/local/lib/python3.8/dist-packages/flask/app.py", ligne 2073, dans wsgi_app
réponse = self.full_dispatch_request()
Fichier "/usr/local/lib/python3.8/dist-packages/flask/app.py", ligne 1518, dans full_dispatch_request
rv = self.handle_user_exception(e)
Fichier "/usr/local/lib/python3.8/dist-packages/flask/app.py", ligne 1516, dans full_dispatch_request
rv = self.dispatch_request()
Fichier "/usr/local/lib/python3.8/dist-packages/flask/app.py", ligne 1502, dans dispatch_request
retourner self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
Fichier "/app/calibre-web/cps/usermanagement.py", ligne 39, en vue_décorée
return login_required(func)(*args, **kwargs)
Fichier "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", ligne 272, en vue_décorée
fonction de retour(*args, **kwargs)
Fichier "/app/calibre-web/cps/web.py", ligne 752, en index
return render_books_list("le plus récent", sort_param, 1, page)
Fichier "/app/calibre-web/cps/web.py", ligne 413, dans render_books_list
entrées, aléatoire, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, ordre,
Fichier "/app/calibre-web/cps/db.py", ligne 679, dans fill_indexpage
return self.fill_indexpage_with_archived_books(page, pagesize, database, db_filter, order, False, *join)
Fichier "/app/calibre-web/cps/db.py", ligne 685, dans fill_indexpage_with_archived_books
randomm = self.session.query(Livres) \
AttributeError : l'objet 'NoneType' n'a pas d'attribut 'query'-- Please have a look at our [Contributing Guidelines](https://github.com/janeczku/calibre-web/blob/master/CONTRIBUTING.md) -->

**Describe the bug/problem**
A clear and concise description of what the bug is. If you are asking for support, please check our [Wiki](https://github.com/janeczku/calibre-web/wiki) if your question is already answered there.

**To Reproduce**

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10/Raspberry Pi OS]
 - Python version: [e.g. python2.7]
 - Calibre-Web version: [e.g. 0.6.8 or 087c4c59 (git rev-parse --short HEAD)]:
 - Docker container: [None/LinuxServer]:
 - Special Hardware: [e.g. Rasperry Pi Zero]
 - Browser: [e.g. Chrome 83.0.4103.97, Safari 13.3.7, Firefox 68.0.1 ESR]

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

**Comment by OzzieIsaacs** [comment]
No content
