### ISSUE TITLE
Calibre-web won't start after commit c61e5d6

### ISSUE THREAD

**Issue by JVT038** [janeczku/calibre-web#2376]
Describe the bug/problem
The problem is that after commit [c61e5d6](https://github.com/janeczku/calibre-web/commit/c61e5d6ac03deaff00d1b4b85f2204ffb56c556b), the container starts, but shows an error.

To Reproduce

1. Update the container to latest version
2. Start the container
3. `docker logs -f calibre-web`

Logfile
```python
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 40, in <module>
    from cps.search_metadata import meta
  File "/app/calibre-web/cps/search_metadata.py", line 58, in <module>
    importlib.import_module("cps.metadata_provider." + a)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/app/calibre-web/cps/metadata_provider/amazon.py", line 116
    except Exception as e:
    ^
IndentationError: unexpected unindent
```

Expected behavior
I expected calibre-web to behave normally, but it showed an error related to Amazon metadata.

Environment (please complete the following information):

    OS: Diskstation Manager 7
    Python version: Python 3.8.10
    Calibre-Web version: Commit [c61e5d6](https://github.com/janeczku/calibre-web/commit/c61e5d6ac03deaff00d1b4b85f2204ffb56c556b)
    Docker container: LinuxServer
    Special Hardware: Synology DS918+
    Browser: Firefox 99.0.1

Additional context
I access the app from a reverse proxy, but I don't think that's relevant to this problem.

**Comment by OzzieIsaacs** [comment]
There is a newer version, please update to this one, it‘s fixed there

**Comment by JVT038** [comment]
That fixed it, thank you!
