### ISSUE TITLE
Add source IP to access.log requests

### ISSUE THREAD

**Issue by alexpearce92** [janeczku/calibre-web#2378]
Would it be possible to add the source IP address for requests in the access.log? I'm trying to add a filter for calibre-web in fail2ban to block repeated failed login attempts from the same IP address. Adding the attempted login ID could also be very useful, but not required for what I'm trying to do.

Something like:
`<host-IP>- - [<date time>] "<request>" <return code> <other code> <source-IP> <duration>`
or
`::ffff:172.27.0.1 - - [2022-04-19 02:26:46] "POST /login HTTP/1.1" 302 1239 100.1.1.1 0.116619`

**Comment by OzzieIsaacs** [comment]
Failed login attempts are logged in the other log (calibre-web.log) together with the source ip. Please parse this file.

**Comment by alexpearce92** [comment]
Looks like I had to allow calibre-web to recreate the calibre-web.log and/or reset the file permissions, as nothing was getting written to it, but I see the login attempts now with the username and IP. Thank you!
