### ISSUE TITLE
OAuth redirect uri is using http instead of https

### ISSUE THREAD

**Issue by AdrianKuta** [janeczku/calibre-web#2383]
## My environement

Hi everyone! 👋

Instance of Calibre-Web is running on my NAS server in docker container.
I have public domain, on which I can access my nas server, and services running on it.
Calibre Web is available in local network at `http://<nas-ip-address>:8083`.

I set reverse proxy:

**Source**:

| Protocol |     Host      | Port |
|:--------:|:-------------:|:----:|
|  https   | ebooks.my-domain.com | 443  |

**Target**:

| Protocol |       Host       | Port |
|:--------:|:----------------:|:----:|
|   http   | \<nas-ip-address\> | 8083 |

I have generated SSL certificate from Let's Encrypt. And I can access Calibre Web via secure Https protocol without problem.

## Describe the problem

I followed this [wiki page](https://github.com/janeczku/calibre-web/wiki/OAuth-Login-with-Github-and-Google) to configure OAuth.

### OAuth Login with Google

I added `https://ebooks.my-domain.com/login/google/authorized` as Authorized redirect URI in Google Cloud Console.
But when I try to login via Google OAuth, the redirect uri is using **http** instead of **https**, and I'm getting error:

> <h4>❗ 500 Internal Server Error:</h4>
>
> ```
> Traceback (most recent call last):
> File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
> response = self.full_dispatch_request()
> File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
> rv = self.handle_user_exception(e)
> File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
> rv = self.dispatch_request()
> File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
> return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
> File "/usr/local/lib/python3.8/dist-packages/flask_dance/consumer/oauth2.py", line 263, in authorized
> token = self.session.fetch_token(
> File "/usr/local/lib/python3.8/dist-packages/requests_oauthlib/oauth2_session.py", line 244, in fetch_token
> self._client.parse_request_uri_response(
> File "/usr/local/lib/python3.8/dist-packages/oauthlib/oauth2/rfc6749/clients/web_application.py", line 220, in parse_request_uri_response
> response = parse_authorization_code_response(uri, state=state)
> File "/usr/local/lib/python3.8/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 272, in parse_authorization_code_response
> raise InsecureTransportError()
> oauthlib.oauth2.rfc6749.errors.InsecureTransportError: (insecure_transport) OAuth 2 MUST utilize https.

 I think it is, because the instance of Calibre Web is running locally with `http` protocol and using same protocol for generating redirect uri.

### OAuth Login with Github

For Github I have similar problem. Generated uri is using `http` and opening this uri. But my NAS is configured to redirect `http` to `https`. Then I think OAuth login process is trying to open uri with `http` again -> NAS is redirecting it to `https` and so on. 
When I open Chrome DevTools I see requests:
- http://ebooks.my-domain.com/link/github
- https://ebooks.my-domain.com/link/github
- http://ebooks.my-domain.com/link/github
- https://ebooks.my-domain.com/link/github
- http://ebooks.my-domain.com/link/github
- https://ebooks.my-domain.com/link/github
- http://ebooks.my-domain.com/link/github
- https://ebooks.my-domain.com/link/github

Finally I'm getting error:

> <h4>❗ ERR_TOO_MANY_REDIRECTS</h4>

I was searching internet for a while, but wasn't able to find solution.
Do you have any suggestions, how to make calibre web using `https` for generating URIs?

**Comment by OzzieIsaacs** [comment]
Calibre-Web behind a proxy has to know that it should generate https links. This is done via proxy configuration (Calibre-Web detects the parameter from the proxy headers: X-Script-Name, X-Forwarded-For, X-Scheme). In this case the important one is `X-Scheme`, it should be set to `https` or some variable your proxy uses to detect the scheme (e.g. `$scheme` for nginx).
It's also necessary to start the workflow from the "public" address and not from the local address

**Comment by AdrianKuta** [comment]
> Calibre-Web behind a proxy has to know that it should generate https links. This is done via proxy configuration (Calibre-Web detects the parameter from the proxy headers: X-Script-Name, X-Forwarded-For, X-Scheme). In this case the important one is `X-Scheme`, it should be set to `https` or some variable your proxy uses to detect the scheme (e.g. `$scheme` for nginx). It's also necessary to start the workflow from the "public" address and not from the local address

@OzzieIsaacs 
Header: `X-Scheme: https` solved the issue 👍 

Thank you for help!

**Comment by eliaspcs** [comment]
@AdrianKuta I'm really a noob here, and have been looking for on how to do this. I'm using Nginx Proxy Manager. How can I accomplish this task?

Also I can override Nginx Proxy Manager and go full Nginx with this. How should it look the config?

I tried 

location / {
proxy_set_header X-Scheme 'https';
}

(quotes and no quotes) with no success.

Thanks in advance.

**Comment by eliaspcs** [comment]
Ok... I figured out how to do it.

This works perfect... until I choose my Google account:

This should go in the advanced settings in NPM

```
proxy_hide_header 'x-frame-options';
proxy_buffer_size 128k;
proxy_buffers 4 256k;
proxy_busy_buffers_size 256k;
real_ip_header X-Forwarded-For;

location / {
    proxy_pass              http://$server:$port;
    proxy_set_header        Host            $http_host;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header        X-Scheme        $scheme;
}
```

I tried to link my account, select link or login with google, then select my account and then I found the following message: 

```
Internal Server Error
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/usr/local/lib/python3.8/dist-packages/flask_dance/consumer/oauth2.py", line 263, in authorized
token = self.session.fetch_token(
File "/usr/local/lib/python3.8/dist-packages/requests_oauthlib/oauth2_session.py", line 366, in fetch_token
self._client.parse_request_body_response(r.text, scope=self.scope)
File "/usr/local/lib/python3.8/dist-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 448, in parse_request_body_response
self.token = parse_token_response(body, scope=scope)
File "/usr/local/lib/python3.8/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 441, in parse_token_response
validate_token_parameters(params)
File "/usr/local/lib/python3.8/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 471, in validate_token_parameters
raise w
Warning: Scope has changed from "https://www.googleapis.com/auth/userinfo.email" to "openid https://www.googleapis.com/auth/userinfo.email".
```
Any ideas?

**Comment by eliaspcs** [comment]
Well... I just figured out...

Into my docker-compose settings I set this variables as well:

      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
      - OAUTHLIB_INSECURE_TRANSPORT=1
      - HTTP_X_SCHEME=https

That fixed the problem for me

**Comment by Jafner** [comment]
Can anyone chime in with a working Traefik label for this?  
I'm working through this right now, but I'm not sure whether it should be a `customResponseHeaders`, `customRequestHeaders`, or `hostsProxyHeaders` middleware.

**Comment by Jafner** [comment]
I'll try each and see how it goes!
