### ISSUE TITLE
[Enhancement] Allow user votes not metadata score

### ISSUE THREAD

**Issue by Kyosfonica** [janeczku/calibre-web#239]
Right now each book rate is based on its own metadata and there is no way that each user can rate the book. It should be better to allow each user to rate a book and the engine show the average rate instead of just the metadata rate value.

**Comment by OzzieIsaacs** [comment]
As many people having ideas on how to expand the project, and I have limited time, I have to priorize and also to limit the features which can be included in calibre-web, I decided not to implement it.
