### ISSUE TITLE
Is it possible to configure a path prefix of URL ?

### ISSUE THREAD

**Issue by luochen1990** [janeczku/calibre-web#2391]
**Is your feature request related to a problem? Please describe.**

I want to deploy this behand nginx, and use a sub-path to distingwish with other services, like `xxx.com/calibre`, instead of a isolated sub domain like `calibre.xxx.com`

**Describe the solution you'd like**

Provide some configuration option like `url_base_prefix = "/calibre"`, So when visiting `xxx.com/calibre`, the page redirection will bring me to `xxx.com/calibre/login` instead of `xxx.com/login`.

**Describe alternatives you've considered**

Use isolate sub-domain name like `calibre.xxx.com`, but there is some situation when I prefer a sub-path instead of a sub-domain.

**Comment by OzzieIsaacs** [comment]
Please follow the procedure listed in the wiki (https://github.com/janeczku/calibre-web/wiki/Setup-Reverse-Proxy#nginx), the correct path is then detected automatically and in parallel you can directly access calibre-web without proxy

**Comment by luochen1990** [comment]
This is still needed since port 80 is banned, so it is impossible to redirect 80 to some other port :(
