### ISSUE TITLE
[BUG] Error in current commit timestamp

### ISSUE THREAD

**Issue by Kyosfonica** [janeczku/calibre-web#240]
The admin page shows the current commit timestamp as this:
Current commit timestamp: $Format:%cI$

Instead of the actual timestamp to compare commits.

![image](https://user-images.githubusercontent.com/5280026/28265026-03e733b8-6aee-11e7-997d-670a1a2a2532.png)

**Comment by OzzieIsaacs** [comment]
Replacing the Format string is done by git during a clone or download. After you press "Perform update", it updates itself to the newest commit and the string should be replaced with the correct one. If you download the whole repository via the clone or download button on the github website, the string is also set correctly. So from what I know up to now nothing to worry about.

**Comment by Kyosfonica** [comment]
Yes, the buttons work. It is just a display issue with the date.
