### ISSUE TITLE
Kobo sync: allow setting request scheme when behind TLS proxy

### ISSUE THREAD

**Issue by ludoo** [janeczku/calibre-web#2401]
I run calibre-web via Docker compose on port 8083, and expose it via Traefik on port 443 with a TLS certificate.

Everything works, except book syncing from Kobo where books are never actually downloaded.

I tried nailing down the issue and it seems to be due to the scheme set in metadata response for `DownloadUrls`, as the actual book download URLs have scheme set to `http` instead of `https`:

```json
"DownloadUrls": [
      {
        "Format": "EPUB3",
        "Size": 499610,
        "Url": "http://calibre-web.xxx.xx.xx/kobo/000000000000000000000000000/download/37/epub",
        "Platform": "Generic"
      },
```

My suspicion is that calibre-web [looks at the request coming from my reverse proxy](https://github.com/janeczku/calibre-web/blob/c1f1952b04cc8bb489dff94d88d451eebdcbc0e7/cps/kobo.py#L375) and sets the scheme based on that.

A simple fix would be inferring the scheme from the port, so if I set `443` as the external port, the scheme is set to `https` regardless.

**Comment by OzzieIsaacs** [comment]
Please use the X-Scheme header as described in the wiki (https://github.com/janeczku/calibre-web/wiki/Setup-Reverse-Proxy#nginx) to archive this:
`proxy_set_header        X-Scheme        $scheme;` 
(or a hardcoded https)
The request scheme in the line you are refering to is set to https here: https://github.com/janeczku/calibre-web/blob/c1f1952b04cc8bb489dff94d88d451eebdcbc0e7/cps/reverseproxy.py#L74

**Comment by OzzieIsaacs** [comment]
Sorry wrong example in the last post. But there is also one for traefik

**Comment by OzzieIsaacs** [comment]
https://github.com/janeczku/calibre-web/wiki/Setup-Reverse-Proxy#traefik-260-example-kobo-sync-fix-enabled

**Comment by ludoo** [comment]
@OzzieIsaacs that's beautiful, thanks a lot for the links! I would add a mention in the wiki page for Kobo, to avoid similar questions in the future.

Thanks a lot!!!
