### ISSUE TITLE
Creating calibre database via calibre-web

### ISSUE THREAD

**Issue by Dunrar** [janeczku/calibre-web#2403]
Calibre-Web is fantastic, and I even think for many users it has enough features to not need the main Calibre application anymore. That's why I think that for people with no pre-existing database, Calibre-Web should allow for the creatio of a new database via the UI. Having to install the main application to create a database feels like an artificial obstacle and might put off new users.

**Describe the solution you'd like**
Allow for the creation of a new database via the UI.

**Comment by OzzieIsaacs** [comment]
The problem is that the calibre database has a lot of features, which are currently not supported by Calibre-Web, so generating a database from scratch seems not feasible to me. 
I can imagine to download (or have a link to) an empty pre created database, but not to create one

**Comment by Dunrar** [comment]
I think that (or an empty database in the source code) would be enough.

**Comment by OzzieIsaacs** [comment]
I decided to ship an database together with calibre-web: 
https://github.com/janeczku/calibre-web/raw/master/library/metadata.db
