### ISSUE TITLE
PDF-only books don't appear

### ISSUE THREAD

**Issue by Gortus** [janeczku/calibre-web#2407]
Any book that I have only in PDF format doesn't show up at all in calibre-web.  Other formats are fine, and the PDF format is fine as long as the book has at least one other format. But anything that's PDF-only just doesn't seem to exist: it doesn't show in any of the Browse views or searches.

I have calibre-web using an up-to-date copy of the calibre database; all is well in Calibre.

1. Find a book in Calibre that has both EPUB and PDF formats.
2. Search for the book in calibre-web.
3. Note that the book appears and shows both formats on the download pulldown.
4. Find a book in Calibre that has only PDF format.
5. Search for the book in calibre-web.
6. Book is not found.

Expected behavior:
6. Book is found.

Environment:
Synology DSM 6.2.4
Docker container: Linuxserver
Calibre-Web version 0.6.18
Browser: Vivaldi 5.2.2623.46

**Comment by OzzieIsaacs** [comment]
I can't reproduce this. Please check that you don't have any visibility restrictions applied (language, based on tags or based on custom column)

**Comment by Gortus** [comment]
Aha! "Language of Books" was set to "English" instead of "Show All." Presumably PDF-only books don't set a language.

Thank you!

**Comment by bmelancon** [comment]
I just got bit by this myself, which is how I found this issue.

It seems to me this should still be considered undesirable behavior, if not an outright bug. If the book doesn't have a defined language the default should be to show the book, not hide it. 

At the very least there should be another checkbox to allow the end user to hide books with undefined languages if they make a conscience choice to do so. But it should be off by default.

**Comment by Trevo525** [comment]
I was also just burned by this. It took me days to even realize what was happening. I have been using Calibre for a while and just thought some of my books just weren't showing up. I took me a couple of weeks to recognize the pattern of "PDF-only" books.
