### ISSUE TITLE
Sudden redirect to Login Page

### ISSUE THREAD

**Issue by t0mcat1337** [janeczku/calibre-web#2422]
**Describe the bug/problem**
A user is normally logged in to Calibre-Web. During browsing the App suddenly the Login Screen appears and one has to authenticate again. Sometimes this happens after one or two arbitary clicks on whatever menu point, somtimes this happens after a longer time. 
It doesn't matter if the user has admin rights or not or if he is authenticated by calibre-web or LDAP.

**To Reproduce**
Hard to reproduce as this behaviour can't be forced but appears suddenly.

**Logfile**
```
[2022-05-24 17:23:07,879] DEBUG {cps.services.simpleldap:111} LDAP login '<username>': True
[2022-05-24 17:23:07,884] DEBUG {cps.ub:82} Found stored session: f8630ae0d90752019a641a39a18eddcaaf074c7a00069ae677c2b4bdfd667e87836d605d4537c62db62026ad8a73af066bd232df3ceb7834327233782f907732
[2022-05-24 17:23:07,888] DEBUG {cps.ub:82} Found stored session: f8630ae0d90752019a641a39a18eddcaaf074c7a00069ae677c2b4bdfd667e87836d605d4537c62db62026ad8a73af066bd232df3ceb7834327233782f907732
[2022-05-24 17:23:07,888] DEBUG {cps.web:1512} You are now logged in as: '<username>'
[2022-05-24 17:23:08,393] ERROR {cps.db:791} Author Arno, Strobel, not found to display name in right order
[2022-05-24 17:23:12,757] ERROR {cps.db:791} Author Arno, Strobel, not found to display name in right order
[2022-05-24 17:23:15,635] DEBUG {cps.updater:324} Stable version: {'version': '0.6.18'}
[2022-05-24 17:23:32,045] ERROR {cps.db:791} Author Arno, Strobel, not found to display name in right order
[2022-05-24 17:23:36,023] ERROR {cps.db:791} Author Arno, Strobel, not found to display name in right order
[2022-05-24 17:23:41,563] ERROR {cps.db:791} Author Christopher Paolini not found to display name in right order
[2022-05-24 17:23:41,818] ERROR {cps.db:791} Author Tracy, Hickman not found to display name in right order
[2022-05-24 17:24:00,400] ERROR {cps.db:791} Author Arno, Strobel, not found to display name in right order
[2022-05-24 17:24:14,315]  INFO {cps.ub:855} successfully deleted Shelf Meins
[2022-05-24 17:24:14,899] ERROR {cps.db:791} Author Arno, Strobel, not found to display name in right order
[2022-05-24 17:24:21,714] DEBUG {cps.updater:324} Stable version: {'version': '0.6.18'}
[2022-05-24 17:24:32,473] ERROR {cps.db:791} Author Arno, Strobel, not found to display name in right order
[2022-05-24 17:27:20,421] DEBUG {cps.services.simpleldap:111} LDAP login '<username>': True
[2022-05-24 17:27:20,425] DEBUG {cps.ub:82} Found stored session: 60f2081c55790c3ae854aa6981c627a25e229d4cebb197f0dcf49972c31694d99e0ea45448fd017fe15263b79504ce5967d09194d60988960c4d193757f08865
[2022-05-24 17:27:20,428] DEBUG {cps.ub:82} Found stored session: 60f2081c55790c3ae854aa6981c627a25e229d4cebb197f0dcf49972c31694d99e0ea45448fd017fe15263b79504ce5967d09194d60988960c4d193757f08865
[2022-05-24 17:27:20,428] DEBUG {cps.web:1512} You are now logged in as: '<username>'
[2022-05-24 17:27:26,623] DEBUG {cps.updater:324} Stable version: {'version': '0.6.18'}
```
As can be seen there is nothing special in the log:
--> Normal log in at 17:23:07
--> Clicked a bit here and there
--> Login Screen suddenly appears even in a Books detail view:

![grafik](https://user-images.githubusercontent.com/3826246/170074377-424c64a6-d507-4dfb-b4fd-934f16db29d0.png)

--> Logged in again at 17:27:20

**Expected behavior**
User shouldn't be redirected to Login Page but stay logged in.

**Environment (please complete the following information):**
 - OS: Linux Ubuntu 20.04.4 LTS
 - Calibre-Web version: 0.6.18
 - Docker container: Image from Docker Hub: linuxserver/calibre-web:latest
 - Browser: Firefox 100.0.2 

**Additional context**
Access via Traefik Reverse Proxy with SSL termination (LetsEncrypt). Traefik adds request headers "X-Forwarded-Scheme: https" and "X-Scheme: https"

**Comment by t0mcat1337** [comment]
In another occurance of this behaviour (this time after clicking on menu entry "Categories") this can be found in Browsers DevTools:

![grafik](https://user-images.githubusercontent.com/3826246/170083892-c0ff968f-ad21-4be7-b8af-1e51cbe282bb.png)

--> All former requests worked quit normal
--> Clicked on "Categories"
--> Request to "/category?data=category&sort_param=stored" was answered with "302 - Redirect" and Location to "/login?next=%2Fcategory%3Fdata%3Dcategory%26sort_param%3Dstored"

**Comment by OzzieIsaacs** [comment]
This usually can happen if your IP address changes between the different calls

**Comment by t0mcat1337** [comment]
As the container and client are running in the same LAN, at a first glance the Clients IP should not change during using the app.

BUT coming to the detailed architecture:
The container is running in a small self-hosted Kubernetes Cluster (1 Control Plane, 2 Worker Nodes) in the local LAN (the same, as the Client).
So in this case this is the commonly used data / request flow:

Client -> LoadBalancer (HAProxy in TCP mode in my case) -> Traefik entry point (SSL Port) on Kubernetes Nodes -> Kubernetes Service -> Kubernetes Pod

So the LoadBalancer round-robins the traffic to all Kubernetes Nodes as the Traefik Service (Type: NodePort) of course listens on every Node.
Could that be the cause Calibre-Web thinks, the Client IP changes between requests?

For further examination I replaced the calibre-web Image with "traefik/whoami". With it one can examine what request headers enter the Pod. This is the result of two consecutive requests:

```
user@client:~$ curl https://calibre.domain.dn
Hostname: calibre-79649695db-79gj5
IP: 127.0.0.1
IP: 10.42.15.217
RemoteAddr: 10.42.15.218:36664
GET / HTTP/1.1
Host: calibre.domain.dn
User-Agent: curl/7.81.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 192.168.42.221
X-Forwarded-Host: calibre.domain.dn
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Scheme: https
X-Forwarded-Server: traefik-c784489bf-fkqfp
X-Real-Ip: 192.168.42.221
X-Scheme: https

user@client:~$ curl https://calibre.domain.dn
Hostname: calibre-79649695db-79gj5
IP: 127.0.0.1
IP: 10.42.15.217
RemoteAddr: 10.42.15.218:36664
GET / HTTP/1.1
Host: calibre.domain.dn
User-Agent: curl/7.81.0
Accept: */*
Accept-Encoding: gzip
X-Forwarded-For: 10.42.177.64
X-Forwarded-Host: calibre.domain.dn
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Scheme: https
X-Forwarded-Server: traefik-c784489bf-fkqfp
X-Real-Ip: 10.42.177.64
X-Scheme: https
```
Conclusions:
--> The "RemoteAddr" is stable
--> So are the changing IPs in Headers "X-Forwarded-For" and/or "X-Real-IP" responsible for Calibre-Webs session behaviour?


BTW: 
I just noticed this closed issue: https://github.com/janeczku/calibre-web/issues/1466 ... could this be a similar search direction?
And are there any docs available, how to run the Calibre-Web Image in a Kubernetes Cluster correctly?

**Comment by t0mcat1337** [comment]
I indeed tackled down this issue to the same root cause, as described in https://github.com/janeczku/calibre-web/issues/1466 and https://github.com/janeczku/calibre-web/issues/1861.

So the meanwhile hardened session protection seems to completely break any sort of load-balanced / reverse proxyed setup.

All those sudden-logout behaviours have in common: Changing Client IPs during requests, no matter if caused by tolino web browser issues or changing IPs because of using some sort of load-balancer (HAProxy, Kubernetes, CloudFlare..)

With calibre-web version 0.6.18 the working workaround is still:

1) Comment out / remove `lm.session_protection = 'strong'` in `/app/calibre-web/cps/__init__.py`
2) Comment out / remove those lines in `/app/calibre-web/cps/admin.py`
```
if not ub.check_user_session(current_user.id, flask_session.get('_id')) and 'opds' not in request.path:
        logout_user()

```

In the end IMHO it could be worth overthinking this session protection thing a bit or make it more configurable as the hardening seems to break too much common use cases.

**Comment by musicderp** [comment]
> 

> With calibre-web version 0.6.18 the working workaround is still:
> 
> 1. Comment out / remove `lm.session_protection = 'strong'` in `/app/calibre-web/cps/__init__.py`
> 2. Comment out / remove those lines in `/app/calibre-web/cps/admin.py`
> 
> ```
> if not ub.check_user_session(current_user.id, flask_session.get('_id')) and 'opds' not in request.path:
>         logout_user()
> ```
> 
> In the end IMHO it could be worth overthinking this session protection thing a bit or make it more configurable as the hardening seems to break too much common use cases.

Building on this, I've adapted the original script for LSIO containers that will automatically apply this. In order to use it, ensure you are using the LSIO version of the container, then in your config folder, create a directory called custom-cont-init.d/

Create a file inside of it called patch-session-protection.sh

In the file, paste this:
```
#!/bin/bash

echo "**** patching calibre-web - removing session protection ****"

sed -i "/lm.session_protection = 'strong'/d" /app/calibre-web/cps/__init__.py
sed -i "/if not ub.check_user_session(current_user.id, flask_session.get('_id')) and 'opds' not in request.path:/d" /app/calibre-web/cps/admin.py
sed -i "/logout_user()/d" /app/calibre-web/cps/admin.py
```

Now, restart your calibre-web container and it should delete those lines and work with cloudflare now. Keep in mind that as the previous comments states, this removes some of the hardening that is in place.

**Comment by IFireflyl** [comment]
> > 
> 
> > With calibre-web version 0.6.18 the working workaround is still:
> > 
> > 1. Comment out / remove `lm.session_protection = 'strong'` in `/app/calibre-web/cps/__init__.py`
> > 2. Comment out / remove those lines in `/app/calibre-web/cps/admin.py`
> > 
> > ```
> > if not ub.check_user_session(current_user.id, flask_session.get('_id')) and 'opds' not in request.path:
> >         logout_user()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In the end IMHO it could be worth overthinking this session protection thing a bit or make it more configurable as the hardening seems to break too much common use cases.
> 
> Building on this, I've adapted the original script for LSIO containers that will automatically apply this. In order to use it, ensure you are using the LSIO version of the container, then in your config folder, create a directory called custom-cont-init.d/
> 
> Create a file inside of it called patch-session-protection.sh
> 
> In the file, paste this:
> 
> ```
> #!/bin/bash
> 
> echo "**** patching calibre-web - removing session protection ****"
> 
> sed -i "/lm.session_protection = 'strong'/d" /app/calibre-web/cps/__init__.py
> sed -i "/if not ub.check_user_session(current_user.id, flask_session.get('_id')) and 'opds' not in request.path:/d" /app/calibre-web/cps/admin.py
> sed -i "/logout_user()/d" /app/calibre-web/cps/admin.py
> ```
> 
> Now, restart your calibre-web container and it should delete those lines and work with cloudflare now. Keep in mind that as the previous comments states, this removes some of the hardening that is in place.

I spent the last hour not having the commands I needed to get this accomplished. Thank you so freaking much. I wasn't about to get rid of Cloudflare, and this has caused me no end of headaches.

**Comment by mph88** [comment]
To save someone setting this up as of [8/28/22](https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers), LSIO moved custom-cont-init.d out of the config folder, so you'll want to bind a new custom-cont-init.d and drop the batch script into there, otherwise if you reboot you'll get an error about a README file.

**Comment by jberlyn** [comment]
> To save someone setting this up as of [8/28/22](https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers), LSIO moved custom-cont-init.d out of the config folder, so you'll want to bind a new custom-cont-init.d and drop the batch script into there, otherwise if you reboot you'll get an error about a README file.

I couldn't get calibre-web to start since the latest update, so glad I saw your comment. Thanks!

**Comment by mph88** [comment]
> > To save someone setting this up as of [8/28/22](https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers), LSIO moved custom-cont-init.d out of the config folder, so you'll want to bind a new custom-cont-init.d and drop the batch script into there, otherwise if you reboot you'll get an error about a README file.
> 
> I love my Unraid, but I'm extremely unintelligent when it comes to using Linux. Could you be more specific on what steps I need to take? I don't know how to "bind a new custom-cont-init.d". Any help is appreciated. Also, thanks for posting this!

I'm not familiar with unraid's implementation of [docker](https://docs.docker.com/storage/bind-mounts/), but you'll need to create a new persistent folder and map it to the container. e.g. `-v /source:/custom-cont-init.d`, where `source` is your persistent folder.

**Comment by IFireflyl** [comment]
@mph88, I appreciate the attempt. Apparently Unraid works pretty differently, and it's actually way easier to make the change. It's just confusing to learn how. For anyone else using Unraid, to make this change you need to make a custom directory that exists outside of the /appdata/calibre-web/ directory (which is mapped to the /config directory). I made the following directory:

/appdata/custom-scripts/calibre-web/

Then I put my patch-session-protection.sh script into that directory. Finally, go into your docker containers and edit the template for calibre-web. To do this you can either just click where it says calibre-web, or you can click the icon to the left of that and click Edit. Once you're on the template page you need to scroll towards the bottom and click "Add another Path, Port, Variable, Label, or Device". Then make your settings look like this:

![image](https://user-images.githubusercontent.com/43413071/189944408-b9189242-b03a-4179-b516-1e261759c15b.png)

You will need to change the Host path to match the location that your script is located. If you named your directories the same as I did then you can just use what is in my screenshot.

**Comment by ShivamKumar2002** [comment]
I am able to fix the pdf download issue. To fix it, I simply edited cps/admin.py file and replace following lines:

```python
def before_request():
    # make remember me function work
    if current_user.is_authenticated:
        confirm_login()
    if not ub.check_user_session(current_user.id, flask_session.get('_id')) and 'opds' not in request.path:
        logout_user()
```

replaced with:

```python
def before_request():
    # make remember me function work
    if not ub.check_user_session(current_user.id, flask_session.get('_id')) and 'opds' not in request.path:
        logout_user()
    if current_user.is_authenticated:
        confirm_login()
```

Basically swapped the lines.

**Comment by mgrimace** [comment]
Thank you to everyone in this thread!

For anyone else finding their way here trying to fix the constant login for a docker version of calibre/calibre-web (0.6.20) on Ubuntu (technically on a ubuntu lxc in proxmox), here's how I resolved this:

in my docker-compose.yml file, I added following line to the `volumes:` for Calibre-Web:

```    
      - /opt/appdata/custom-scripts/calibre-web/custom-cont-init.d:/custom-cont-init.d
```

I tried a few variations and the keys for me were to use another folder rather than the config folder (hence the 'custom-scripts`), and to include the full pathway (hence the `.../custom-cont-inid.d`). Nothing else seemed to work.

Then,

I created a new directory `/opt/appdata/custom-scripts/calibre-web/custom-cont-init.d`, then created a file here using `nano patch-session-protection.sh` noting that `/opt/appdata/calibre` is where I put all my docker-compose file, you might want to put this wherever it makes sense to you.

Inside that file, I added: 

```
#!/bin/bash

echo "**** patching calibre-web - removing session protection ****"

sed -i "/lm.session_protection = 'strong'/d" /app/calibre-web/cps/__init__.py
sed -i "/if not ub.check_user_session(current_user.id, flask_session.get('_id')) and 'opds' not in request.path:/d" /app/calibre-web/cps/admin.py
sed -i "/logout_user()/d" /app/calibre-web/cps/admin.py
```

It seems that this is all working at least in my initial testing.

**Comment by mgrimace** [comment]
As a quick follow-up the above steps seem to break search (that being said, search would prompt a constant login anyways) with error 
```
Calibre-Web
Error 400
Bad Request
```
Otherwise moving through various screens no longer prompts a login, phew

**Comment by hoplahoi** [comment]
After more than one year the script is no longer working in the recent version published in Oktober 2023 gives error when the server starts. Anyone has update for the script? Stuck again with constant logout and covers not loading completely.

**Comment by OzzieIsaacs** [comment]
Meanwhile in the admin basic configuration page in the security section you can lower the session protection to simple. This should do the same as the procedure above

**Comment by mgrimace** [comment]
> After more than one year the script is no longer working in the recent version published in Oktober 2023 gives error when the server starts. Anyone has update for the script? Stuck again with constant logout and covers not loading completely.

I disabled the script by removing it from my compose file. A calibre-web update a awhile back fixed the issues for me. Using the script causes issues now on the recent version

**Comment by hoplahoi** [comment]
> Meanwhile in the admin basic configuration page in the security section you can lower the session protection to simple. This should do the same as the procedure above

I found the setting but the save button doesn't work. Can this option be set from the compose file?

**Comment by hoplahoi** [comment]
Ok, found solution. Performed local login and did the update. Thanks for the answer.

**Comment by seamuslowry** [comment]
Bless you @OzzieIsaacs and @hoplahoi. Changing the configurable setting for 'Session Protection' does solve this issue.

It can be found under 'Admin' > 'Edit Basic Configuration' > 'Security Settings' > 'Session Protection'

![image](https://github.com/janeczku/calibre-web/assets/6394062/1e3109a3-ccd0-43e0-99a6-3f68951324e7)

You'll have to do it over a network that you _don't_ see this issue in (like a local network). Otherwise the call to save the setting will attempt to redirect you to login and cannot succeed.

**Comment by Plaidstallion** [comment]
Had this exact symptom (sudden redirect to login mid-browsing, nothing unusual in Calibre-Web's own log around the time it happens) and found the cause in my case, which may be relevant given you're also on Traefik.

**Cause:** I'm behind Traefik with a CDN (Cloudflare) in front of it. My Traefik `websecure` entrypoint wasn't configured with `forwardedHeaders.trustedIPs`, so Traefik never resolved the real client IP from the upstream proxy's forwarded headers. Calibre-Web ended up seeing a different apparent "client IP" from request to request within the same session.

Flask-Login's session protection compares the current request's IP against the IP recorded when the session was created. A mismatch silently invalidates the session:

```
set-cookie: remember_token=; Expires=Thu, 01 Jan 1970 00:00:00 GMT; Max-Age=0
set-cookie: session=... (fresh)
```

No error gets logged by Calibre-Web itself, since as far as the app is concerned, it's just enforcing a legitimate security check on what looks like a hijacked session. That matches your log excerpt showing nothing unusual between the successful login and the sudden logout.

You mention Traefik adds `X-Forwarded-Scheme`/`X-Scheme` headers, worth checking whether your Traefik entrypoint is also configured to trust and forward the real client IP (`forwardedHeaders.trustedIPs`), not just the scheme. If there's any proxy/CDN layer in front of Traefik too, the trusted IP ranges need to cover that layer specifically.

Worth checking whether the client IP logged in Calibre-Web's `access.log` (or Traefik's own access log) stays consistent across a session. If it's changing between requests, that's the same root cause.
