### ISSUE TITLE
are there plans for a Calibre-Web ios/android clients?

### ISSUE THREAD

**Issue by moutasem1989** [janeczku/calibre-web#2426]
I have installed Calibre-Web on my server and I am very happy with it. but there is something missing: a client app.

I know it has an OPDS catalog front and a very well made web app, but sadly it is just not the same as a native app (ios or android).

are there any new apps one can use as ios/android clients for calibre-web ? will there ever be a real ios/android client/ebook reader to have a complete self-contained experience?

**Comment by OzzieIsaacs** [comment]
I don't have any plans for this, my free time is to short to extend the "calibre-web universe" in this direction

**Comment by driftywinds** [comment]
Might I suggest [Cantook by Aldiko](https://play.google.com/store/apps/details?id=com.aldiko.android)
