### ISSUE TITLE
One book in multiple series

### ISSUE THREAD

**Issue by webysther** [janeczku/calibre-web#2427]
![image](https://user-images.githubusercontent.com/750007/170812502-1414489d-24dc-4dd6-bd60-0a45e77bd7c8.png)
https://standardebooks.org/ebooks/david-garnett/lady-into-fox

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Support for multiple series to one book, in some case the book can be part of multiple series and have the unique serie ID

**Describe alternatives you've considered**
Create a shelf, but with no series id.

**Additional context**
The image if from Standard Ebooks and show one book that is part os multiple series with unique number.

More samples:
https://standardebooks.org/ebooks/arnold-bennett/the-old-wives-tale

**Comment by OzzieIsaacs** [comment]
I'm sorry the calibre database and therefore calibre itself only supports one series per book. I'd like to stay compatible with calibre so there is no solution for this topic from my side.
