### ISSUE TITLE
ERROR {cps.tasks.mail:178} 'ascii' codec can't encode character '\u200d' in position 13: ordinal not in range(128)

### ISSUE THREAD

**Issue by filwu8** [janeczku/calibre-web#2431]
https://hub.docker.com/r/linuxserver/calibre-web

ERROR {cps.tasks.mail:178} 'ascii' codec can't encode character '\u200d' in position 13: ordinal not in range(128)

how to fix？

**Comment by OzzieIsaacs** [comment]
First step is: you provide complete data as requested in the form you deleted as you created this issue, then we will see
