### ISSUE TITLE
changing metadata image does not update

### ISSUE THREAD

**Issue by quarz12** [janeczku/calibre-web#2440]
changing metadata via fetch metadata doesnt update the book image.
It does show up in the editing page but when saving and getting redirected back to the bookpage the old picture is not updated.
This is most obvious when trying to change from an image with a white border to one that is borderless

**Comment by simkin** [comment]
Did you try clearing your browsers cache afterwards? (to rule out caching issues)

**Comment by quarz12** [comment]
I just did. Nothing changed

**Comment by simkin** [comment]
Please enable debug logging and paste the parts where you reproduced the issue:
![image](https://user-images.githubusercontent.com/958263/173050568-2065be67-64f0-4f4e-a31d-b786bac51a3e.png)

**Comment by OzzieIsaacs** [comment]
Having a look at the developer console of the browser could also help to find the problem. (Beside the full filled form which was requested during intial creation of the issue)
![Uploading image.png…]()

**Comment by quarz12** [comment]
found the issue. I updated using the web UI and that didnt install the advocate package

**Comment by simkin** [comment]
Good work. Please close the issue :)
