### ISSUE TITLE
How could I enable image caching? Is it perhaps an idea to include in calibre-web?

### ISSUE THREAD

**Issue by simkin** [janeczku/calibre-web#2442]
Perhaps somebody could advise how to best implement image caching? It seems each book cover is reloaded at each page refresh? I tried to enable https://docs.nginx.com/nginx/admin-guide/content-cache/content-caching/ but failed to get that to work.

**Comment by wgibcus** [comment]
Could this be implemented via nginx? https://linuxhint.com/cache-static-resources-https-nginx/

**Comment by simkin** [comment]
https://github.com/janeczku/calibre-web/releases/tag/0.6.19

**Comment by webysther** [comment]
This works for this problem like a charm: https://www.digitalocean.com/community/tutorials/how-to-implement-browser-caching-with-nginx-s-header-module-on-centos-8
