### ISSUE TITLE
read status checkbox doesn't work for custom columns

### ISSUE THREAD

**Issue by comphru** [janeczku/calibre-web#2445]
**Describe the bug/problem**
The read status checkbox doesn't work for custom columns 

**To Reproduce**
1. Create a new readstatus column in calibre
2. Set this column in calibre-web as read status
3. Open a book detail form and try to change the read status from unread to read
4. See no changes after reloading the book

**Solution**
Changing the lines 325-330 in helper.py from 
```python
read_status = getattr(book, 'custom_column_' + str(config.config_read_column))
    if len(read_status):
        if read_status is None:
            read_status[0].value = not read_status[0].value
        else:
            read_status[0].value = read_status is True
```
to 
```python
book_read_status = getattr(book, 'custom_column_' + str(config.config_read_column))
    if len(book_read_status):
        if read_status is None:
            book_read_status[0].value = not book_read_status[0].value
        else:
            book_read_status[0].value = read_status is True
```
solves this problem.

**Comment by OzzieIsaacs** [comment]
Thanks, that's indeed a bug.

**Comment by comphru** [comment]
Thank you for the prompt fix!
