### ISSUE TITLE
Error while saving fetched metadata

### ISSUE THREAD

**Issue by ibigbug** [janeczku/calibre-web#2451]
**Describe the bug/problem**

Errors while saving metadata after fetching:

> Error in rename file in path: [Errno 2] No such file or directory: '/books/Brendan Gregg/Systems Performance (17)/Systems Performance_ Enterprise - Brendan Gregg.azw3'

**To Reproduce**
1. Go to 'Edit Metadata'
2. Click on 'Fetch'
3. Choose a result from Google, for example

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

[calibre-web.log](https://github.com/janeczku/calibre-web/files/8933207/calibre-web.log)

folder structure:

```
root@6df6bca3e4dd:/# ls '/books/Brendan Gregg/'
'Systems Performance (17)'  'Systems Performance_ Enterprise and (17)'
```

**Expected behavior**
It should be able to find the and rename the file

**Screenshots**

**Environment (please complete the following information):**
<html>
<body>

Platform | Linux 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 x86_64
-- | --
Python | 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
Calibre_Web | 0.6.18 - fee76741a02899d2dfdc2ce29cfc27901a06383c - 2022-04-03T20:17:34+02:00

</body>
</html>

 - Docker container: [None/LinuxServer]: LinuxServer
 - Special Hardware: [e.g. Rasperry Pi Zero]
 - Browser: FireFox

**Additional context**

I imported the book from Calibree on desktop

And I edit metadata in calibre-web 

Maybe there's a confusion on the old/new book title before/after renaming. not sure how to consolidate these ?

**Comment by OzzieIsaacs** [comment]
Please perform a library maintenance in calibre (should be in library menu), there is something wrong with names in the database and in file structure

**Comment by ibigbug** [comment]
thank you. after maintenance, library looking fine.
