### ISSUE TITLE
autostart in the background

### ISSUE THREAD

**Issue by thncode** [janeczku/calibre-web#2453]
how do I start calibre-web in the background? The cps command always keeps the shell active...

**Comment by OzzieIsaacs** [comment]
Number 6 https://github.com/janeczku/calibre-web/wiki/Manual-installation#manual-installation

**Comment by thncode** [comment]
I've read this, but it does not work. Probably because I did not do a manual installation and these folders / files do look different then. cps.py cannot be found...

**Comment by OzzieIsaacs** [comment]
You are using Linux?
How did you installed it?

**Comment by thncode** [comment]
I am using Linux on an RPI and have it installed like described on the front page:

1. Install Calibre-Web via pip with the command pip install calibreweb (Depending on your OS and or distro the command could also be pip3).
2. Calibre-Web can be started afterwards by typing cps

**Comment by OzzieIsaacs** [comment]
Then a normal `nohup cps` instead of `cps` should do the job

**Comment by AiOGajo** [comment]
> Then a normal `nohup cps` instead of `cps` should do the job

But then how do you start a service to run at startup? 
Thanks

**Comment by OzzieIsaacs** [comment]
Please take a look here: https://github.com/janeczku/calibre-web/wiki/Setup-Service-on-Linux

**Comment by jajaX** [comment]
hi,

for (k)ubuntu, like a service. read the doc !

I install calibre-web from source.

from at the end of this page
https://github.com/janeczku/calibre-web/wiki/Setup-Service-on-Linux

I just replace user ubuntu by root ans it works !
