### ISSUE TITLE
Amazon moving the goal posts

### ISSUE THREAD

**Issue by crazybadger** [janeczku/calibre-web#2454]
I've just sent a MOBI file from calibre-web to my Kindle and received the following e-mail from Amazon:

_Dear Kindle Customer,

Thank you for using the Send to Kindle service to send personal documents to your Kindle library. We noticed that the following document(s), sent by you at 09:24 PM on Tue, Jun 21, 2022 GMT are in MOBI (.mobi, .azw) formats:
* Title - Author.mobi

We wanted to let you know that starting August 2022, you’ll no longer be able to send MOBI (.mobi, .azw) files to your Kindle library. Any MOBI files that are already in your library will not be affected by this change. MOBI is an older file format and won’t support the newest Kindle features for documents. Any existing MOBI files that you want to read with our most up-to-date features for documents will need to be re-sent in a compatible format.

Compatible formats now include EPUB (.epub), which you can send to your library using your Send to Kindle email address. We’ll also be adding EPUB support to the free Kindle app for iOS and Android devices and the Send to Kindle desktop app for PC and Mac.      

 If you have any questions, please visit our help page or contact our Customer Service team.      

 Regards,
Amazon Kindle Support_

I love calibre-web and the work you've done to provide a really great electronic library and simple wireless mechanism for transferring books to my family's Kindles, so hopefully it will be a relatively simple change to send .epub files directly, rather than converting and sending .MOBI files?

Thanks again

**Comment by OzzieIsaacs** [comment]
Please crake a look here  #2393
