### ISSUE TITLE
data base location invalid

### ISSUE THREAD

**Issue by cchalifo999** [janeczku/calibre-web#2460]
**Describe the bug/problem**
 Fresh install on docker both nightly and latest
the data base location i put /books in the db path and here is the screen shot
![calibre-web](https://user-images.githubusercontent.com/2941510/176233542-7d1c96e8-7916-46e0-a6a0-379160d70128.png)

![path-calibre-web](https://user-images.githubusercontent.com/2941510/176233837-a8b53e18-5897-4539-ba0f-33496829dc37.png)

 - Calibre-Web version docker nightly and latest
 - Docker container: LinuxServer:
 - Special Hardware: docker
 - Browser:  Firefox none ESR]

**Additional context**

**Comment by Northguy** [comment]
@cchalifo999 you probably mapped your file location wrongly. Please share how you configured your Docker instance (i.e. docker-compose), otherwise no one can help you.
