### ISSUE TITLE
Can't Send eBooks to Kindle devices with the click of a button

### ISSUE THREAD

**Issue by Fabwiss** [janeczku/calibre-web#2461]
Hello,

I'm french but I try to explain my problem in french ;)
Sorry for my bad english.

I can't send my ebook to my Kindle because I don't have the email button.

I test on Mac (Safari and Chrome), iPhone (Safari and Brave) and PC (IE, Edge and Firefox).

My email config is OK and I received the test email.

Can you help me please ?

Thank you.

Fabwiss.

**Comment by Weediee** [comment]
1. Kindle e-mail added to user profile ? 
2. What version are You on ?
3. Anything at calibre-web.log ?

**Comment by Fabwiss** [comment]
> 1. Kindle e-mail added to user profile ?
Yes my e-mail addes in my user profile

> 2. What version are You on ?
My version is **0.6.18**

> 3. Anything at calibre-web.log ?
?

**Comment by ferboiar** [comment]
Amazon is sending emails to warn that soon they will no longer allow .mobi files to be sent to kindle. In fact it won't let me anymore. The solution is to send the file in epub format, supposedly amazon makes the conversion to a format compatible with your device (I have not tested it yet, we will see how the file ends up arriving to the kindle, if it misaligns it a lot or keeps the format.).

BUT there is an added problem. It does the conversion considering ISO-8859-1 instead of UTF-8, so you probably have to do a previous conversion from EPUB to EPUB to mark the file as UTF-8 before sending it to the kindle.

**Comment by mirisbowring** [comment]
@ferboiar got the mail today also.
As far as i remember, amazon did not fully support .epub at all. I had to rename the files to .png (no conversion) and sending them to my kindle address for conversion afterwards.

Is Epub supported now?

Also: Probably this should be addressed in a separate issue.

**Comment by therealactionadam** [comment]
> Only "mobi" files can be send to kindle. No calibre-ebook converter configured, no option to convert to mobi. No mobi file, no button.

Also PDF Files can be sent. I read somewhere when the file is larger than 50MB the button is not available, because amazon doesn't allow emails larger than 50MB.

**Comment by bulletprooffool** [comment]
The ability to send epubs directly was recently added in a nightly patch, but this is also seemingly not presenting the 'send to kindle' button

**Comment by OzzieIsaacs** [comment]
The user needs to have a kindle email address set and the book needs to have a mobi/ePub/pdf file (if a ebook converter is converted a azw3 can be converted to ePub)

**Comment by friki67** [comment]
Amazon is sending an email saying something like

> We wanted to inform you that as of August 2022 you will no longer be able to send MOBI (.mobi, .azw) files to your Kindle library. MOBI files already in your library will not be affected by this change. MOBI is an older file format that will not support the newer Kindle features for documents. Any existing MOBI files you wish to read with our most up-to-date document features will need to be resubmitted in a supported format.
> 
> Supported formats now include EPUB (.epub), which you can send to your library using your Send to Kindle email address. We will also be adding EPUB support to the free Kindle app for iOS and Android devices and the Send to Kindle desktop app for PC and Mac.

Translated from Spanish using DeepL.

**Comment by bulletprooffool** [comment]
Even some books that are already epubs don’t have the button

**Comment by GoGoSoSlow** [comment]
> Even some books that are already epubs don’t have the button

I had the same problem with the send-to button not showing.  For me it was because the book was over the 50Mb limit for send-to-kindle.

**Comment by tomdh76** [comment]
The nightly version works nice for sending epubs! Only the cover is not send, but this seems a problem with amazon: https://www.reddit.com/r/kindle/comments/ukb0rn/epub_to_kindle_via_calibre_with_cover_showing/
