### ISSUE TITLE
Not working: "Read" and "Shelves"

### ISSUE THREAD

**Issue by gavdgavd** [janeczku/calibre-web#2464]
**Describe the bug/problem**
- New installation of Calibre + Python + Calibre-Web (everything out-of-the-box)
- All Calibre and Calibre-Web functionality working properly, except:
- If I use the "Read" checkbox on one book and close the book-window, the check mark is not shown on the book picture and the book is also not shown in the "Read books" section. I can see that the entry is set correctly in the database, it is only not visible in the interface. If I open the book window again, the checkbox is not selected.
- I can make new Shelves, but if I set a book in one shelf, it is not visible in the shelf section. In this case, if I open the book window, I can see that the book is marked to be on the shelf. Again, I can see that the database is correctly updated, the problem is only in the interface
- If I use the "Archived" checkbox on one book, the book IS correctly moved to the "Archived Books" section, but the checkbox is not shown as selected.

**To Reproduce**
- I cannot reproduce the problem in other systems. Already installed everything in two other computers, and it works without problems. It is only in one computer, but, my issue is that this computer is the computer that is open to internet to serve the books, thus I need to solve the problem there.
- Already tried without results: Several computer resets + uninstalling/installing Calibre-Web.
- It is not a database or rights problem because I can see that the toggles are set in the database correctly. 

**Logfile**
Log-level set to "Debug", but the logs show no issues at all:
[2022-06-30 12:26:34,495] DEBUG {cps.updater:324} Stable version: {'version': '0.6.18'}
[2022-06-30 12:26:50,261]  INFO {cps.ub:855} Book 89 readbit toggled
[2022-06-30 12:27:04,310] DEBUG {cps.updater:324} Stable version: {'version': '0.6.18'}
[2022-06-30 12:28:26,528]  INFO {cps.ub:855} Book 88 readbit toggled
[2022-06-30 12:28:39,636] DEBUG {cps.updater:324} Stable version: {'version': '0.6.18'}

**Expected behavior**
Any help would be highly appreciated. Any idea what could be the problem? Any workaround? Calibre-Web is working perfectly for the rest, the issue is only in one computer.

**Screenshots**
Let me know if you want to see any picture.

**Environment (please complete the following information):**
 - OS: Windows Server 2022 (server with the problem). Tried also with Windows 10 and another computer with Windows Server 2022 without problems
 - Python version: 3.10.5
 - Calibre-Web: 0.6.18
 - Docker container: None
 - Special Hardware: None
 - Browser: Edge 102.0.1245.44, Firefox 102, Vivaldi 5.3.2679.55

**Additional context**
No reverse proxy, no database background sync, database location: "C:\Books"

**Comment by OzzieIsaacs** [comment]
Please update to the newest nightly version at least the read problem should be solved then

**Comment by gavdgavd** [comment]
Thank you for your message. Could you please indicate me where I can find the nightly version? I see in the releases only the 0.6.18 version. Once again, thanks in advance.

**Comment by OzzieIsaacs** [comment]
In admin section, basic configuration, server configuration, update channel, switch to nightly. Go back to admin section, search for update, update.

**Comment by gavdgavd** [comment]
Hi Ozzie. Thanks for your indications. But I found a workaround that solved all my problems:
	- Create a new folder for the library (The first one was called "C:\Books", the new one is "C:\Books_Full")
	- From Calibre (not Calibre-Web) go to the Books menu (use the arrow in the icon) -> "Switch/create library"
	- Select "Create an empty library at the new location", do not check "Copy estructure..." and select the new folder
	- A new Calibre database is created in the new folder. There are no books (yet) there in
	- From Calibre-Web (thus not Calibre) go to "Admin" - "Edit Calibre Database Configuration"
	- Select the new folder and save
	- From Calibre (thus not Calibre-Web) click on the arrow at the side of "Add books" -> "Add from folders and sub-folders"
	- In message "Multi-file books?" click on "Yes"
	- Select one of the author sub-folder under the old directory ("C:\Books")
	- All the books for this author will be imported, including different formats, pictures, etc.
	- Repeat the process for all the authors
After that, everything works as expected. I am pretty sure there is something in the configuration of the files (of main directory) that conflicts with Calibre-Web, but I cannot find what it is. I checked rights, configurations, everything, and I cannot find any difference between the old and the new files-structure. But with the workaround, everything is working correctly, and the old one is having big troubles.
In any case, many thanks for your help. And if you or somebody else have the described problem, I think this workaround will help.

**Comment by OzzieIsaacs** [comment]
In case of calibre database problems executing a library maintenance from within calibre helps often.
I‘m happy your problem is solved
