### ISSUE TITLE
Task status not updated after succesfull sending email to kindle

### ISSUE THREAD

**Issue by therealactionadam** [janeczku/calibre-web#2471]
**Describe the bug/problem**
After successfull sending Email to kindle task status not changed from started to finished.

**To Reproduce**
1. Choose Book (PDF)
2. Click "Send to Kindle"

**Screenshots**
![grafik](https://user-images.githubusercontent.com/21138161/177040442-57d517ab-3097-4c2e-8f30-d2a126d8677e.png)

**Environment (please complete the following information):**
 - docker 
 - gmail Oauth2 used

**Comment by IHSten** [comment]
Also seeing this for MOBI's (even though Amazon is removing support for them soon)

**Comment by ghighi3f** [comment]
I've noticed the problem myself and opened a PR with a fix.

**Comment by OzzieIsaacs** [comment]
Please update to the newest nightly version, the problem is solved there (Linuxserver should provide a docker version for "latest")
