### ISSUE TITLE
Modify Calibre Web to send epub directly to Kindle

### ISSUE THREAD

**Issue by friki67** [janeczku/calibre-web#2472]
**Is your feature request related to a problem? Please describe.**
Amazon is sending an email saying something like

> We wanted to inform you that as of August 2022 you will no longer be able to send MOBI (.mobi, .azw) files to your Kindle library. MOBI files already in your library will not be affected by this change. MOBI is an older file format that will not support the newer Kindle features for documents. Any existing MOBI files you wish to read with our most up-to-date document features will need to be resubmitted in a supported format.
> 
> Supported formats now include EPUB (.epub), which you can send to your library using your Send to Kindle email address. We will also be adding EPUB support to the free Kindle app for iOS and Android devices and the Send to Kindle desktop app for PC and Mac.

Translated from Spanish using DeepL.

**Describe the solution you'd like**
Give Calibre-Web the ability to send EPUB format directly to the Kindle, like is doing now with MOBI.

**Describe alternatives you've considered**
Use good-old desktop calibre or guacamole+calibre docker image to send EPUB  #books to the kindle. I prefer Calibre Web, of course

#2461

**Comment by OzzieIsaacs** [comment]
Please have a look here #2393
