### ISSUE TITLE
Books stop Scrolling on MS Edge but all books display in Safari

### ISSUE THREAD

**Issue by dwilliamhouston** [janeczku/calibre-web#2475]
**Describe the bug/problem**
I have a library of around 34,000 books and when I start scrolling through the books the scrolling stops at the first page when using MS Edge (103.0.1264.44).  If I go to the exact same URL the scrolling of library doesnt stop and allows me to continue.  At first I thought it was because of some issues with tags so I removed all the tags but the problem continues.  I am running version 0.6.18 of Calibre-Web and version 5.44 of Calibre.  Have cleared cache, etc from MS Edge and doesnt resolve issue.  I turned on Developer Tools in MS Edge and the problem goes away and I can continue to scroll through the books.

**To Reproduce**
1. Open up Calibre-Web using MS Edge on MacBook and scroll down to bottom of books.
2. Stops displaying any books when it gets to bottom of first page.
3.  Open up Calibre-Web using Safari on MacBook and scroll down to bottom of books.
4. Displays next books in library.

**Logfile**
N/A as far as I can see as no errors are showing up.  If needed let me know and I will provide.

**Expected behavior**
Should be able to display all books in library.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Running Docker version of Calibre-Web from linuxserver/calibre-web:latest.  Client is Mac OSX 12.5
 - Python version: [e.g. python2.7] What ever is installed in the docker image
 - Calibre-Web version: [e.g. 0.6.8 or 087c4c59 (git rev-parse --short HEAD)]: 0.6.18
 - Docker container: [None/LinuxServer]:  See above.
 - Special Hardware: [e.g. Rasperry Pi Zero] N/A
 - Browser: [e.g. Chrome 83.0.4103.97, Safari 13.3.7, Firefox 68.0.1 ESR] MS Edge 103.0.1264.44

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

**Comment by dwilliamhouston** [comment]
Still seeing this issue but I have noticed that if I hit the Next arrow that it continues working so not sure if the pagination is somehow getting messed up and manually hitting the Next arrow fixes it.

**Comment by OzzieIsaacs** [comment]
With the current version of Edge I can't reproduce the issue
