### ISSUE TITLE
amazon send to kindle feature now support epub but no longer mobi

### ISSUE THREAD

**Issue by aaronzgh** [janeczku/calibre-web#2476]
just simple problem because of amazon modification on send to kindle feature as the title said.
now Amazon send to kindle function no longer supports .mobi file, instead they started to support epub format, as notification email says.
But calibre-web "send to kindle" button just appears when the file format is .mobi, which complies with formal standards.

**Comment by OzzieIsaacs** [comment]
Please have a look here https://github.com/janeczku/calibre-web/issues/2393

**Comment by aaronzgh** [comment]
thanks very much and hope stable version rather than nightly will come up soon

**Comment by aaronzgh** [comment]
> Please have a look here #2393


thanks very much and hope stable version rather than nightly will come up soon
