### ISSUE TITLE
Downloaded ebooks in Moonreader are saved according to the calibre id, not the title

### ISSUE THREAD

**Issue by WorldTeacher** [janeczku/calibre-web#2480]
**Describe the bug/problem**
When accessing the calibre-web UI using the ebook-reader Moonreader on Android and downloading ebooks, they are saved according to the id associated with the ebook in the calibre database. When downloading from a browser, it downloads it with the full title.

**To Reproduce**
1. Install moonreader
2. access calibre-web UI using the net gallery
3. download any ebook
4. see the popup, wich displays the title the ebook will be saved to

**Expected behavior**
I think that the title should be saved there as well, as it would make navigating using shortcuts (eg: long press to go to next title) more effortless, as it usually would go to the next book with the same title, but in the case of the id's it goes to the next available id 

**Environment (please complete the following information):**
 - OS: [UnRaid 6.10]

 - Calibre-Web version: [e.g. 0.6.8 or 087c4c59 (git rev-parse --short HEAD)]: latest docker release
 - Docker container: [LinuxServer]: version: latest

 - Browser: [Firefox mobile], MoonReader

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]
I have a bunch of custom metadata, but that should not influence the filename in any way.

**Comment by OzzieIsaacs** [comment]
Are you refering to the opds feed ("/opds") or the "real" Web-UI ("/")
For the opds feed: 
The metadata of Calibre and Calibre-Web looking very similar, especially in the download link segment:

Calibre:
```
  <entry>
    <title>titerler</title>
    <author>
      <name>fdsfdsfdsf dsfsd f</name>
    </author>
    <id>urn:uuid:493bdca7-9e80-4215-afae-79a364b3d6fd</id>
    <updated>2022-08-07T10:17:26+00:00</updated>
    <published>2022-08-07T10:16:17+00:00</published>
    <dc:date>2015-12-24T00:00:00+00:00</dc:date>
    <link type="application/epub+zip" href="/get/epub/354/fdfdf" rel="http://opds-spec.org/acquisition" length="1377170" mtime="2022-08-07T10:16:17.627531+00:00"/>
    <link type="image/jpeg" href="/get/cover/354/fdfdf" rel="http://opds-spec.org/cover"/>
    <link type="image/jpeg" href="/get/thumb/354/fdfdf" rel="http://opds-spec.org/thumbnail"/>
    <link type="image/jpeg" href="/get/cover/354/fdfdfr" rel="http://opds-spec.org/image"/>
    <link type="image/jpeg" href="/get/thumb/354/fdfdf" rel="http://opds-spec.org/image/thumbnail"/>
  </entry>
```

Calibre-Web:   

```
<entry>
    <title>book7</title>
    <id>urn:uuid:da18a6c8-c1f2-4110-a4ad-344815961392</id>
    <updated>2017-01-20T20:10:54+00:00</updated>    
      <author>
        <name>Peter Parker</name>
      </author>       
      <dcterms:language>eng</dcterms:language>        
    <category scheme="http://www.bisg.org/standards/bisac_subject/index.html"
              term="Gênot"
              label="Gênot"/>            
    <link type="image/jpeg" href="/opds/cover/10" rel="http://opds-spec.org/image"/>
    <link type="image/jpeg" href="/opds/cover/10" rel="http://opds-spec.org/image/thumbnail"/>        
    <link rel="http://opds-spec.org/acquisition" href="/opds/download/10/epub/"
          length="5954" mtime="2017-01-20T20:10:54+00:00" type="application/epub+zip"/>    
</entry>
```

**If you download the file via Calibre is the name then the right one?** 

The Browser is working (in the opds feed), as the download link is using the same code (presented under a different route) as the normal download from the web interface.

If you are refering to the "real" web interface from "/", I think I can't help you this seems to be a "feature" of moonreader

**Comment by WorldTeacher** [comment]
I am using the "real" Web-UI, as I do not really like how the OPDS is displayed in MoonReader, as well as it not showing the data I have added to the titles.

Downloading from the opds however, returns the correct title.

**Comment by OzzieIsaacs** [comment]
Sounds like a general problem of moonreader. 
What are the file names if you are downloading files from somewhere else? (If you can give me a public available correct working example I can try if I can find differences)

**Comment by WorldTeacher** [comment]
I can only give an example for the files I personally own, as I use Calibre-Web to download ebooks to my phone when I'm reading.
I'll do some googling tomorrow, maybe I can find a public example that will give me the same result, but the available net library Project Gutenberg does not use calibre, so I can't test it with that.

The filenames are something like: `86--EIGHTY-SIX, Vol. 2 _ Run Through the Battlefront (Start) - Asato Asato.epub`

**Comment by WorldTeacher** [comment]
I didn't find any online source, but I could setup a calibre-web instance with some public available works and could send the link, if you want to do some tests.

**Comment by OzzieIsaacs** [comment]
That would not help me. I think it‘s moonreaders fault. If you find anything else which you can download with moonreader and does show a differentl behavior this would help
