### ISSUE TITLE
Update failed: Files could not be replaced during update

### ISSUE THREAD

**Issue by RichardMawdsley** [janeczku/calibre-web#2483]
**Describe the bug/problem**
After checking for an update in the web console, and selecting Perform Update, it does a short "Unzipping update package" before failing with "Update failed: Files could not be replaced during update".  I imagine this is permission related, I just don't know how to resolve.  Is it not possible to update via apt update?

**To Reproduce**
1. Go to Settings
2. Click on Check for Update, Perform Update
3. See error

**Logfile**
[2022-07-13 10:34:25,090]  INFO {cps.admin:1746} Update status requested
[2022-07-13 10:34:31,343]  INFO {cps.updater:414} Excluded file list for updater not found, or not accessible

**Expected behavior**
Update to Install

**Screenshots**
![image](https://user-images.githubusercontent.com/26411043/178689874-4f89dfee-3aa5-4844-87ce-f30b4e2735b6.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS
 - Python version: 3.8.10
 - Calibre-Web version: 0.6.18
 - Docker container: None
 - Special Hardware: None
 - Browser: Chrome 103.0.5060.114

**Comment by OzzieIsaacs** [comment]
> Is it not possible to update via apt update?

You can update it via pip, but, the 0.6.18 version is the latest one, so there is only a nightly update possible. This is only possible via the in program update. The alternative would be to do a git pull. 

> I imagine this is permission related,

The logfile sayes: "Excluded file list for updater not found, or not **accessible**". 
Please create an empty exclude.txt file in the root folder of calibre-web or download the empty file from here (https://github.com/janeczku/calibre-web/blob/master/exclude.txt)
