### ISSUE TITLE
Metadata comments section doesn't preserve <br>

### ISSUE THREAD

**Issue by teetui** [janeczku/calibre-web#2488]
Lines separated by < br > in Calibre metadata comments section become a single paragraph in Calibre-web book details description field.

**Comment by OzzieIsaacs** [comment]
I added the following in the calibre-web (using newest nightly build from today) edit book comment section using View -> Sourcecode editor:
`<div>text<br>test2<br><br>test3<br></div>`
After saving and re editing the ebook with the same function I find:
`<div>text<br />test2<br /><br />test3</div>`
Pasting the same content (line 2 of my post) into calibre's html sourcecode editor (version 6.3 of calibre on Linux Mint) for comments, results in:
```
<div>
<p>text<br />test2<br /><br />test3</p>
</div>
```

So can't reproduce it. Please provide a more detailed describtion on what you did and what the result is.
