### ISSUE TITLE
Calibre-web is not finding new books

### ISSUE THREAD

**Issue by LwsBtlr** [janeczku/calibre-web#2489]
**Describe the bug/problem**
After adding new books to calibre and starting calibre-web up, it is not seeing newly added books.

**To Reproduce**
Stop calibre-web (docker)
Open Calibre and add new books
Sync database and entire calibre folder to Calibre-web location
Restart calibre-web docker
Search for the newly added books(s) and no result.

**Logfile**
There's no error.

**Expected behavior**
Newly added books  should show up.

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10/Raspberry Pi OS]
 Calibre-web docker on Synology DSM7 with Calibre 6/1 back-end
 
 - Python version: [e.g. python2.7]
 python 3.10

 - Calibre-Web version: [e.g. 0.6.8 or 087c4c59 (git rev-parse --short HEAD)]:
 0.6.18

 - Docker container: [None/LinuxServer]:
 linuxserver/calibre-web:latest

 - Browser: [e.g. Chrome 83.0.4103.97, Safari 13.3.7, Firefox 68.0.1 ESR]
MS Edge, Safari

**Comment by OzzieIsaacs** [comment]
Sorry, I can‘t reproduce this. The book info is stored in the metadata.db file, if the file is updated the books are found. This could a problem with docker, but is not a calibre-web problem

**Comment by LwsBtlr** [comment]
Alright. It's been happening here for two days, but I will look into it some more and figure out where I went wrong.
