### ISSUE TITLE
Convert Mobi to Epub and send to E-Reader fails

### ISSUE THREAD

**Issue by adrianmihalko** [janeczku/calibre-web#2495]
**Describe the bug/problem**
"Convert Mobi to Epub and send to E-Reader" fails with 500 Internal server error

**To Reproduce**
1. Go to any book in mobi format
2. Click on Convert Mobi to Epub and send to E-Reader
3. ...

**Logfile**
```
Calibre-Web
500 Internal Server Error
The server encountered an internal error and was unable to complete your request. There is an error in the application.
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 303, in decorated_view
return current_app.ensure_sync(func)(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 113, in inner
return f(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 1199, in send_to_ereader
result = send_mail(book_id, book_format, convert, current_user.kindle_mail, config.config_calibre_dir,
File "/app/calibre-web/cps/helper.py", line 215, in send_mail
return convert_book_format(book_id, calibrepath, u'epub', book_format.lower(), user_id, ereader_mail)
File "/app/calibre-web/cps/helper.py", line 78, in convert_book_format
file_path = os.path.join(calibre_path, book.path, data.name)
AttributeError: 'NoneType' object has no attribute 'name'
```

**Expected behavior**
Convert & send Epub to Kindle

**Screenshots**
<img width="1137" alt="Screenshot 2022-07-21 at 21 32 06" src="https://user-images.githubusercontent.com/733361/180300243-f27afa01-1b13-4cfc-965a-6baef35fd7cf.png">

**Environment (please complete the following information):**
 - OS: Debian 
 - Calibre-Web version: nightly 2022. 07. 16. 19:27
 - Docker container: Docker image image: ghcr.io/linuxserver/calibre-web:nightly
 -

**Comment by olskar** [comment]
Same as https://github.com/janeczku/calibre-web/issues/2494 ?

**Comment by adrianmihalko** [comment]
It still doesn't work as expected. I click on convert and send to e-reader, but I get: Oops! There was an error sending this book: epub format not found for book id: xy.

**Comment by OzzieIsaacs** [comment]
Please run a library maintenance from calibre itself, looks like the book is not correct linked between database and harddisk

**Comment by Plaidstallion** [comment]
> It still doesn't work as expected. I click on convert and send to e-reader, but I get: Oops! There was an error sending this book: epub format not found for book id: xy.
> 
> Version: 7/31/22, 4:14 PM Current version

I am having the same issue. If I convert the book manually in calibre it will send but otherwise the function mobi to epub does not work in calibre-web
