### ISSUE TITLE
[BUG] Calibre-Web doesn't install on TrueNAS-13.0-U1

### ISSUE THREAD

**Issue by KorkyJohnson** [janeczku/calibre-web#2499]
**Describe the bug/problem**

Tried to install the plugin via the Trunas UI and get the following error

Error: <name>-Web had a failure Exception: RuntimeError Message: pkg error: - py38-pip :,py38-ldap : Refusing to fetch artifact and run post_install.sh! Partial plugin destroyed

**To Reproduce**
Just try to install the plug in

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

**Expected behavior**
Plugin installed

**Screenshots**

**Environment (please complete the following information):**
 - Trunas
 - Python version: Seems to be 3.9
 - Calibre-Web version: n/a
 - Docker container: n/a
 
**Additional context**
Thanks for the plugin and your time

**Comment by OzzieIsaacs** [comment]
Sorry for the late reply:
The Calibre-Web project does not provide any special scripts or a Truenas plugin for installing. Your error message `... run post_install.sh...` suggests that such a script is running. Please ask the provider of the script (Truenas?) for help

**Comment by AshwinParanjape** [comment]
FWIW, I got the same error with Truenas Core 12. But updating it to Truenas Core 13 (specifically 13.0-U2 is the one I tried), fixed the issue.

**Comment by FinlayDaG33k** [comment]
> FWIW, I got the same error with Truenas Core 12. But updating it to Truenas Core 13 (specifically 13.0-U2 is the one I tried), fixed the issue.

Same here, `13.0-U6.1`

**Comment by laaci** [comment]
Hello,
I inserted in line 22:
line21: },
line22:'' "pkgs": [],''
line23: "packagesite":..........
I then followed the github description.
[on Github](https://github.com/janeczku/calibre-web/issues/2335)
