### ISSUE TITLE
send to kindle without authentication?

### ISSUE THREAD

**Issue by perler** [janeczku/calibre-web#25]
It looks like I cannot send to kindle via SMTP without authentication. 

I have a smart host which authenticates via IP and brings me

`There was an error sending this book: Failed to send mail: (435, 'Unable to authenticate at present')`

unfortunately, I cannot look into the log of the relayserver (it's antispamcloud.com) but I think you send some bogus authentication when you just should connect to the server without authentication.

I wonder why you not simply use sendmail?

**Comment by janeczku** [comment]
Added in 82574d21. Just leave the password field empty.
