### ISSUE TITLE
A import advise,please read!

### ISSUE THREAD

**Issue by flashliao** [janeczku/calibre-web#250]
I suggest this calibre-web application compatibility is import than the application Features or Procedural beautification。
I share the books with friends use the calibre-web application,but my friends complain that not compatibility with IE9.Particularly  after update 2017-07-23T22:26:43+02:00,Ie9 explorer can't not open the books and not can read online.The picture shows blank when I open the books read to read.

![image](https://user-images.githubusercontent.com/28710685/28605119-1506a7c6-7202-11e7-9d19-984528213360.png)

There are other problems 
![image](https://user-images.githubusercontent.com/28710685/28605164-846f3dbc-7202-11e7-83d0-a0f755a0d456.png)

but the firefox explorer and chrome explorer have not these problem.If not ready compatibility  with IE9 or higher IE explorer.If there can show the messages "not compatibility  explorer" when everyone open the website?
everytimes I update,I found surprised.The Web application more and more better.

**Comment by jkrehm** [comment]
The current JavaScript linting expects ES6 syntax which is not compatible with any version of IE (not even IE 11). We should be able to support back to IE 9 without too much difficulty, but I'm personally of the opinion that if we do, IE 11 is as far back as we should support because IE 9 and IE 10 aren't supported by Microsoft anymore.

**Comment by jkrehm** [comment]
@flashliao Could you try the latest code? IE9 likely will not work, but IE11 should work without issue. #275 also took care of missing Chinese translations.

**Comment by flashliao** [comment]
@jkrehm there are IE11 prolem。
1、Some menu logo mising.
![image](https://user-images.githubusercontent.com/28710685/29348243-bb09d3cc-8284-11e7-9eca-2cd966633bf5.png)
2、Somebook（only a few）just only view frist page.But chrome can view all pages,I don't konw why and don't donw what's different between other books.
![image](https://user-images.githubusercontent.com/28710685/29348316-639d185a-8285-11e7-8bb9-d8126387e5a6.png)
![image](https://user-images.githubusercontent.com/28710685/29348338-8601cc7e-8285-11e7-89e4-e3eb4bb526fb.png)
3、Click fullscreen button shows blank.
![image](https://user-images.githubusercontent.com/28710685/29348402-ec023392-8285-11e7-8520-f9008e7c4d26.png)

**Comment by idalin** [comment]
![image](https://user-images.githubusercontent.com/3346204/29353091-9ea72b82-829b-11e7-8b34-57b85d089030.png)
menu icons ok here

**Comment by flashliao** [comment]
@idalin IE11 menu icons ok?

**Comment by OzzieIsaacs** [comment]
Missing bookmarks will be tracked in #285. All other issues are solved.
