### ISSUE TITLE
Explanation of gdrive integration?

### ISSUE THREAD

**Issue by seannymurrs** [janeczku/calibre-web#2504]
I read through the directions for using calibre-web with gdrive, but I’m still a bit confused as to how the integration actually works. Is my entire library (ebook files and metadata.db) stored on my Google Drive? If so, how does this get around the issue of Calibre not working correctly with Google Drive?

I’m trying to figure out if using calibre-web and its gdrive integration is a good fit for installing on my seedbox.

**Comment by OzzieIsaacs** [comment]
Yes, all files are stored on gdrive. The library file (metadata.db) is copied to a local folder, edited there and then synced to gdrive. 
My personal recommendation: don‘t do it. 
I still don‘t see the benefit of having a ebook library in the cloud instead of having it on the server itself

**Comment by seannymurrs** [comment]
Thanks for the reply and suggestion. If I did want to give the integration a try, how would I go about transitioning my current Calibre library (on my local computer) to the cloud? Unless I missed something, the gdrive integration instructions don’t go over that part.

Thanks again,

Sean Murray

**Comment by OzzieIsaacs** [comment]
Generate a folder on your gdrive, copy the whole library including the metadata.db into the folder. Generate a local folder on your server (it will act as transfer folder) and put a copy of the metadata.db into it. During config you will be asked for a library path, use the local folder with the metadata.db in it.
Don’t forget to do a backup
Don’t copy manually files to or from the library, don’t replace the metadata.db file while calibre-web is running

**Comment by seannymurrs** [comment]
Gotcha, thanks. Does calibre-web do anything special to avoid the incompatibility issue between Calibre and Google Drive (something to with how Google Drive names folders and files with numbers in them)? Thanks again!Sent from my iPadOn Aug 1, 2022, at 11:17 AM, Ozzie Isaacs ***@***.***> wrote:﻿
Generate a folder on your gdrive, copy the whole library including the metadata.db into the folder. Generate a local folder on your server (it will act as transfer folder) and put a copy of the metadata.db into it. During config you will be asked for a library path, use the local folder with the metadata.db in it.
Don’t forget to do a backup
Don’t copy manually files to or from the library, don’t replace the metadata.db file while calibre-web is running

**Comment by OzzieIsaacs** [comment]
I don’t know anything about calibre’s incompatibility with gdrive. To be sure tick “the replace non English charcaters…” in the basic config section. This should replace all strange characters while saving books to gdrive and the local drive

**Comment by weirdcrap** [comment]
For what it's worth I've ALWAYS stored my Calibre library in Google Drive and never had a single issue with it. ymmv but it's never once failed or corrupted on me.

**Comment by seannymurrs** [comment]
Thanks! I’ll backup my current library and give it a try. On Aug 3, 2022, at 3:58 PM, weirdcrap ***@***.***> wrote:﻿
For what it's worth I've ALWAYS stored my Calibre library in Google Drive and never had a single issue with it. ymmv but it's never once failed or corrupted on me.
