### ISSUE TITLE
Flask is missing in a fresh install of 0.6.19 version

### ISSUE THREAD

**Issue by Tos26** [janeczku/calibre-web#2506]
hello

I failed to upgrade my calibre-web to the version 0.6.19 from the Configuration menu. So I remove the full previous folder on my server in order to have  a fresh install.
I have python 3.9.
Here is the process used and the failure:

- `apt install sqlite3 python3-pip imagemagick`
- `apt install python3-setuptools` 
- `pip3 install wheel`
- Unzip the file calibre-web-0.6.19.tar.gz
- `pip3 install --system --target vendor -r requirements.txt`
- No error at this stage: 
`Installing collected packages: pycparser, cffi, tzdata, MarkupSafe, cryptography, werkzeug, urllib3, pytz-deprecation-shim, pytz, pyopenssl, pyasn1, Jinja2, itsdangerous, idna, click, charset-normalizer, certifi, WTForms, tzlocal, tqdm, six, setuptools, requests, netifaces, ndg-httpsclient, Flask, blinker, Babel, Wand, unidecode, tornado, SQLAlchemy, PyPDF3, lxml, iso-639, flask-wtf, Flask-Principal, Flask-Login, Flask-Babel, chardet, backports-abc, APScheduler, advocate
Successfully installed APScheduler-3.9.1 Babel-2.10.3 Flask-2.0.3 Flask-Babel-2.0.0 Flask-Login-0.6.1 Flask-Principal-0.4.0 Jinja2-3.1.2 MarkupSafe-2.1.1 PyPDF3-1.0.6 SQLAlchemy-1.4.39 WTForms-3.0.1 Wand-0.6.8 advocate-1.0.0 backports-abc-0.5 blinker-1.5 certifi-2022.6.15 cffi-1.15.1 chardet-4.0.0 charset-normalizer-2.0.12 click-8.1.3 cryptography-37.0.4 flask-wtf-1.0.1 idna-3.3 iso-639-0.4.5 itsdangerous-2.1.2 lxml-4.8.0 ndg-httpsclient-0.5.1 netifaces-0.11.0 pyasn1-0.4.8 pycparser-2.21 pyopenssl-22.0.0 pytz-2022.1 pytz-deprecation-shim-0.1.0.post0 requests-2.27.1 setuptools-63.3.0 six-1.16.0 tornado-6.1 tqdm-4.64.0 tzdata-2022.1 tzlocal-4.2 unidecode-1.3.4 urllib3-1.26.11 werkzeug-2.0.3`

- When I launch manually `python3.9 /opt/calibre-web/cps.py`
I got :
`Traceback (most recent call last):
  File "/opt/calibre-web/cps.py", line 28, in <module>
    from cps.main import main
  File "/opt/calibre-web/cps/__init__.py", line 28, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
root@MonServer:/opt/calibre-web# /usr/bin/python3 /opt/calibre-web/cps.py
Traceback (most recent call last):
  File "/opt/calibre-web/cps.py", line 28, in <module>
    from cps.main import main
  File "/opt/calibre-web/cps/__init__.py", line 28, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
` 

> But Flask seems to be installed properly.

What I missed ?

Thanks for your kelp.

**Comment by OzzieIsaacs** [comment]
> What I missed ?

The installation procedure in the readme. The target vendor folder installation isn‘t supported anymore.
https://github.com/janeczku/calibre-web#installation-via-pip-recommended

**Comment by Tos26** [comment]
Thank you for your fast answer.

I effectively missed this information... Apologize
