### ISSUE TITLE
New translation proposal: Galician

### ISSUE THREAD

**Issue by pollitor** [janeczku/calibre-web#2510]
Since I didn't see a translation of _Calibre-Web_ in my language (Galician), I decided to make a translation proposal for _Calibre-Web_ that I attached to the request.
It is made based on the latest version of the Spanish translation. I have tested it on my own installation and it works fine.
I hope it will be helpful to people who use your app in my country and I apologize in advance for any translation errors. I'm not a professional translator ;)

NOTE:
I've uploaded it as a feature request because I didn't see a better option. I hope you don't mind.

Greetings and thank you
[gl.zip](https://github.com/janeczku/calibre-web/files/9309647/gl.zip)
.

**Comment by OzzieIsaacs** [comment]
It's merged to the newest nightly version
