### ISSUE TITLE
Calibre-Web-Setup.exe after 6.16 fails to run.

### ISSUE THREAD

**Issue by MrMxyzptlk** [janeczku/calibre-web#2514]
I have several db's running on 6.16, when I noticed 6.19 is now out I did an upgrade.
I run with the -p option, and .17, .18. and .19 all crash and exit.

I reinstalled 6.16 and it's running perfect?

I'm on Windows Server 2022 standard with the latest patches.

No log files created when running the crashed versions.
I have validated that all of the requirements are on the right versions.
Here is what I get when starting in CLI mode.

C:\calibre-web>cps.py -p appbooks.db

C:\calibre-web>
[main 2022-08-12T17:21:02.307Z] update#setState idle
[main 2022-08-12T17:21:03.646Z] Starting extension host with pid 14660 (fork() took 23 ms).
[main 2022-08-12T17:21:04.986Z] Waiting for extension host with pid 14660 to exit.
[main 2022-08-12T17:21:05.171Z] Blocked vscode-file request vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/editor/common/services/editorSimpleWorker.nls.js
[main 2022-08-12T17:21:05.364Z] Extension host with pid 14660 exited with code: 0, signal: null.

**Comment by OzzieIsaacs** [comment]
The logfile is not from calibre-web itself. Please post the content of calibre-web .log itself.
Refering to the exe file and using the python script in the issue itself creates confusion on my site. What did you EXACTLY do

Remark: the installation procedure changed, the installation with the vendor folder is no longer supported.
Python2 is also no longer supported

**Comment by MrMxyzptlk** [comment]
OK
