### ISSUE TITLE
Port redirection error.

### ISSUE THREAD

**Issue by anyshpm** [janeczku/calibre-web#2527]
**Describe the bug/problem**
I run Calibre-web in docker behind a reverse proxy by a nonstandard port. Public URL is https://xxx.com:1024/. When I open the address, Calibre-web will redirect me to https://xxx.com/login?next=%2F. The port is missing.

**To Reproduce**
1. Go to website url with nonstandard port
2. Redirect me to url without port
3. See error

**Environment (please complete the following information):**
 - Calibre-Web version: [0.6.19]:
 - Docker container: [None/LinuxServer]:

**Comment by wgibcus** [comment]
This looks like a reverse proxy set-up issue. Please make sure you have configured it according to your set-up - https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/

Removing the port is what the reverse proxy does. it looks like your public and private addresses are around the wrong way :)

**Comment by anyshpm** [comment]
> This looks like a reverse proxy set-up issue. Please make sure you have configured it according to your set-up - https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/
> 
> Removing the port is what the reverse proxy does. it looks like your public and private addresses are around the wrong way :)

Thanks.
:)
