### ISSUE TITLE
Support calibre content server as backend

### ISSUE THREAD

**Issue by TheBinaryLoop** [janeczku/calibre-web#2528]
**Is your feature request related to a problem? Please describe.**
I want to use a calibre content server as my backend for calibre web. I have some self written applications that use the calibredb command to access the content server.

**Describe the solution you'd like**
Support the calibre content server as a possible backend.

**Describe alternatives you've considered**
I don't want to sync my library because of storage and consistency issues.

**Additional context**
N/A

**Comment by OzzieIsaacs** [comment]
Sorry, but this is out of the scope of this project. 
You are free to fork the project and implemented the needed changes by yourself.

**Comment by TheBinaryLoop** [comment]
Would a pull request be accepted?
________________________________
