### ISSUE TITLE
Haven't receive the email password reset

### ISSUE THREAD

**Issue by PetiteIno** [janeczku/calibre-web#2533]
Hi, i've forget my password and after entering my user i'd hit the forget password button. It says that the email has been sent but i haven't receive one

**Comment by OzzieIsaacs** [comment]
Please use the commandline interface to change the password. https://github.com/janeczku/calibre-web/wiki/Command-Line-Interface#command-line-options
if you haven‘t received the email, please check your spam folder and rethink which email address you used
