### ISSUE TITLE
page slice loading

### ISSUE THREAD

**Issue by fyhkimyon** [janeczku/calibre-web#2534]
**Is your feature request related to a problem? Please describe.**
When the book I upload is too large, my server will take a long time to load it, and I must wait for the whole file to load before I can display all the contents. I hope that every time I load a page of PDF, this page will be displayed.

**Describe the solution you'd like**
use [pdf.js](https://github.com/mozilla/pdf.js)

**Describe alternatives you've considered**
none.

**Additional context**
none.

**Comment by OzzieIsaacs** [comment]
The Mozilla reader is already used: https://github.com/janeczku/calibre-web/blob/master/cps/static/js/libs/pdf.js
The pdf in use, has to support this feature also

**Comment by OzzieIsaacs** [comment]
I updated pdf.js to a more recent version in the nightly version of calibre-web, please feel free to test it (I don't expect any change)

**Comment by fyhkimyon** [comment]
I used the latest docker image (7 hours ago) to test it.
pdf.js seems to work only after the backend loads all the resources. When I quickly switch the page at the browser, the page shows a short loading animation. 
I think it may be necessary to write the logic code of related page slice in the backend, and the frontend requests the backend page by page, otherwise, no content will be displayed on the page until the server completely transmits the entire resource to the browser.
