### ISSUE TITLE
How can I update port to environment variable, as this is required to deploy on heroku?

### ISSUE THREAD

**Issue by sopykt** [janeczku/calibre-web#2536]
**Describe the bug/problem**
I want to test to deploy the app to heroku. Heroku required to set port number as their environment varible which cannot be hardcoded and its random. So I want to know where to set this port to an environment variable.

**Comment by OzzieIsaacs** [comment]
It‘s currently not possible: https://github.com/janeczku/calibre-web/wiki/Command-Line-Interface#environmental-variables
