### ISSUE TITLE
Impossible to set Denied Column Value from user table

### ISSUE THREAD

**Issue by Tloz** [janeczku/calibre-web#2537]
**Describe the bug/problem**
Trying to set a Denied Column Value results in a toast asking if I want to delete the user.

**To Reproduce**
1. Go to Administration > Edit Users 
2. Scroll right until "Denied Column Values" column
3. Click on + sign

The form field appears, then the toast appears, taking the focus.
This doesn't appears when clicking on the + sign in "Allowed Column Values" column, the field appears properly.

**Expected behavior**
The toast should not appear and I should be able to fill the form field.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/2813581/189313790-1e6c79bb-db4a-436d-b49c-92f2aaba6308.png)

**Environment:**
 - OS: Raspberry Pi OS (`Linux 5.15.61-v8+ #1579 SMP PREEMPT Fri Aug 26 11:16:44 BST 2022 aarch64`)
 - Python version: 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
 - Calibre-Web version: 0.6.19 - pyPi
 - Docker container: None
 - Special Hardware: Rasperry Pi 3
 - Browser: Firefox 104.0.2

**Additional context**
locale set to FR

Thanks

**Comment by OzzieIsaacs** [comment]
I can reproduce it. I'll have a look at it.

**Comment by OzzieIsaacs** [comment]
Please update to the newest nightly build, it's working there.

**Comment by Tloz** [comment]
I installed calibreweb via pip, can you tell me how to switch to the nightly builds?

**Comment by OzzieIsaacs** [comment]
Admin section -> Basic configuration -> server configuration -> update channel -> switch to nightly
Back to admin section -> search for update -> update

**Comment by Tloz** [comment]
It's working properly. Thanks!
