### ISSUE TITLE
Error editing book: Proxies cannot be used with Advocate

### ISSUE THREAD

**Issue by xhpk** [janeczku/calibre-web#2538]
**Describe the bug/problem**
I m a user of china.When I import a book,and get metadata from google/douban with proxy.it always appear this erro.
So what should i do to solve it.

**To Reproduce**
1. import a book
2. get metadata from google/douban with proxy
3. save info 
4. fail and appear erro

**Logfile**
[2022-09-09 17:33:30,363] ERROR {cps.editbooks:231} Proxies cannot be used with Advocate

**Expected behavior**
none

**Screenshots**
![image](https://user-images.githubusercontent.com/40262993/189323621-de8fb0bf-b503-41ac-967e-c01b106122f5.png)

**Environment (please complete the following information):**
 - OS:  Windows 10
 - Python version: python3
 - Calibre-Web version:0.6.19
 - Docker container: LinuxServer
 - Special Hardware: 
 - Browser:Chrome 105.0.5195.102

**Comment by OzzieIsaacs** [comment]
You have to use the -l command line option (https://github.com/janeczku/calibre-web/wiki/Command-Line-Interface#command-line-options). I don‘t know how to do this with docker.

**Comment by xhpk** [comment]
> You have to use the -l command line option (https://github.com/janeczku/calibre-web/wiki/Command-Line-Interface#command-line-options). I don‘t know how to do this with docker.

thank you for your help , i have solved it。The docker user can add "CALIBRE_LOCALHOST=true"
