### ISSUE TITLE
Issue starting calibre web werkzeug.security

### ISSUE THREAD

**Issue by phairplay** [janeczku/calibre-web#2542]
**Describe the bug/problem**
having issues starting Calibre-web I'm getting the following error
```
C:\Windows\system32>C:\Python310\python310.exe C:\Calibre-web\cps.py
Traceback (most recent call last):
  File "C:\Calibre-web\cps.py", line 34, in <module>
    from cps import create_app
  File "C:\Calibre-web\cps\__init__.py", line 32, in <module>
    from .MyLoginManager import MyLoginManager
  File "C:\Calibre-web\cps\MyLoginManager.py", line 24, in <module>
    from flask_login import LoginManager
  File "C:\Python310\lib\site-packages\flask_login\__init__.py", line 16, in <module>
    from .login_manager import LoginManager
  File "C:\Python310\lib\site-packages\flask_login\login_manager.py", line 24, in <module>
    from .utils import (login_url as make_login_url, _create_identifier,
  File "C:\Python310\lib\site-packages\flask_login\utils.py", line 13, in <module>
    from werkzeug.security import safe_str_cmp
ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security' (C:\Python310\lib\site-packages\werkzeug\security.py)
```
I've installed all the required packages

**To Reproduce**
1. Go to 'start via C:\Python310\python310.exe C:\Calibre-web\cps.py'

**Logfile**
non available

**Expected behavior**
expected the program to start

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

**Comment by OzzieIsaacs** [comment]
Which version of werkzeug is installed. There was an issue with a version which was to new. This should be fixed in the newest version of calibre-web, so which version are you using there

**Comment by OzzieIsaacs** [comment]
No response
