### ISSUE TITLE
Calibre-Web Server Error - Object Books has no attribute custom_column_11

### ISSUE THREAD

**Issue by bmdempsey19** [janeczku/calibre-web#2543]
**Describe the bug/problem**
Somewhere along the latest update or two, I can no longer open any book details in calibre-web.   My library shows up fine, but when I click on any I get the 500 error below.  I've updated to the latest vesrion today and have the same issue.

Seems to be looking for a missing 'Read' column, which apparently at one point was custom_column_11.   I believe I deleted this custom column a long time ago, but it seems there are remnants now causing the web server to crash.

Calibre-Web
Internal Server Error
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
File "D:\CalibreWeb\vendor\flask\app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "D:\CalibreWeb\vendor\flask\app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "D:\CalibreWeb\vendor\flask\app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "D:\CalibreWeb\vendor\flask\_compat.py", line 39, in reraise
raise value
File "D:\CalibreWeb\vendor\flask\app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "D:\CalibreWeb\vendor\flask\app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "D:\CalibreWeb\cps\web.py", line 201, in decorated_view
return login_required(func)(*args, **kwargs)
File "D:\CalibreWeb\vendor\flask_login\utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "D:\CalibreWeb\cps\web.py", line 1715, in show_book
matching_have_read_book = getattr(entries, 'custom_column_' + str(config.config_read_column))
AttributeError: 'Books' object has no attribute 'custom_column_11'`

**Comment by OzzieIsaacs** [comment]
If possible try to go to admin section "Edit UI configuration" -> View Configuration, there should be a setting "Link Read/Unread Status to Calibre Column" and "View Restrictions based on Calibre column", please check both are pointing to a valid custom column. Upon entering the fields might seem to be set okay. In both cases, please save and try again, the setting should be valid afterwards. 
If not, please provide me the metadata.db file vie e-mail -> email from my profile page(please don't post it here) and I have a look at it.
If it's working please also give feedback, then I'll have a look at it.

**Comment by bmdempsey19** [comment]
Ozzie, thanks for the quick reply.  Tried checking those settings, but once I get to the UI Configuration page, the 'View Configuration' node along with the other two Default notes do not expand when I click them.   Tested on multiple browsers.

**Comment by OzzieIsaacs** [comment]
Could you please check if there is an entry generated in "calibre-web.log" after trying to save the settings

**Comment by bmdempsey19** [comment]
I was able to hit Save and got the green response 'Calibre-Web configuarion updated' at the top of the page, but no entry in the log file, and still can't expand the nodes.  Same is true for other pages like config.  On this page, each node click changes the url to include a bookmark (e.g. viewconfig#collapsefour) but nothing expands.  Almost like JS is disabled, but  tried in browsers with no blocking.

**Comment by OzzieIsaacs** [comment]
Please send me the metadata.db file and I'll have a look

**Comment by bmdempsey19** [comment]
OK, so good update!  The save must've fixed things even though I was unable to actually make any changes due ot the node issue.  I can now click on a book and get to its details page.  I see there is still a 'Read' checkbox on that details page (along with an 'Archived' checkbox), so that's a bit surprising since I no longer see that column in Calibre desktop.  So issue now is that the node won't expand.  I can create a new case if needed.   Thanks

**Comment by OzzieIsaacs** [comment]
Calibre-Web has to methods of storing a read flag, one is via a custom column in Calibre (single user), or if this is not configured, Calibre-Web has an own database to store the read progress. You can deactivate the archived flag by disabling the "Show archived books" in the users settings

**Comment by OzzieIsaacs** [comment]
> So issue now is that the node won't expand. I can create a new case if needed. 
If there are no Custom columns to use you can't see any in the Calibre-Web setting, so this is intended. From my point of view, we are done. (Beside the fact that you don't get an error message in this case)

**Comment by bmdempsey19** [comment]
Well, there's still an issue here with the +\- nodes.  *None* of them  expand or collapse - the 5 on the Edit Basic Configuration page or the 3 on the Edit UI Configuration page.

**Comment by OzzieIsaacs** [comment]
Okay, got it now. This is done via pure javascript, so please open the developer console on your browser and check for any javascript errors there. -> You are using Windows. There are several issues with the error message you will find. Please search for it in the issues section

**Comment by bmdempsey19** [comment]
Yup, it was a windows registry issue.  thanks for the help!

**Comment by OzzieIsaacs** [comment]
Has to be an old version, currently web.py only has approx. 1500 lines. The line throwing the exception is no longer in code
