### ISSUE TITLE
Calibre constant sign in issue

### ISSUE THREAD

**Issue by Surgical71** [janeczku/calibre-web#2544]
**Describe the bug/problem**
Calibre-Web constantly reverts me back to the login screen

**To Reproduce**
No specific steps

**Expected behavior**
To Only ask to login once and save the cookie

**Screenshots**
![image](https://user-images.githubusercontent.com/80483431/190978349-e4f1e04f-de6f-4476-8f7f-33e201ef851d.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python version: [e.g. python2.7]
 - Calibre-Web version: 0.6.19
 - Docker container: Yes/Linux
 - Special Hardware: None
 - Browser: Any Browser

**Additional context**
I am using NGINX Proxy Manager that causes the issue as when I connect directly there is no issues. I have followed the following thread ( https://github.com/janeczku/calibre-web/issues/1466#issuecomment-639050762) To change the config in the container as well as add the recommended changes to NGINX, but its still an issue. Any help would be great

**Comment by OzzieIsaacs** [comment]
The thread from #1466 is something different. Please try to use the reverse proxy config from the wiki:
https://github.com/janeczku/calibre-web/wiki/Setup-Reverse-Proxy#nginx-proxy-manager
This is working. If there is still an issue afterwards I recommend to ask for help at from the docker container provider. As I have no idea about the exact configuration of the docker container, sorry.

**Comment by Surgical71** [comment]
I am currently using the image (linuxserver/calibre-web) that is listed on this repo.
I tried the following:

proxy_buffer_size 128k;
proxy_buffers 4 256k;
proxy_busy_buffers_size 256k;

But this did not resolve the issue

**Comment by Surgical71** [comment]
I see the same issue was mentioned in #2521
