### ISSUE TITLE
Feature Request: Marvel API (Fetch Meta Data)

### ISSUE THREAD

**Issue by Surgical71** [janeczku/calibre-web#2546]
**Is your feature request related to a problem? Please describe.**
No Problem related

**Describe the solution you'd like**
There is currently a APi availible from Marvel to use to fetch Meta Data

**Additional context**
Link to Official Documentation (https://developer.marvel.com)

**Comment by OzzieIsaacs** [comment]
Sorry I will not provide any more Metadata providers:
https://github.com/janeczku/calibre-web/wiki/Developer's-corner-#add-metadata-provider
