### ISSUE TITLE
Fetch Metadata - TypeError: NoneType object is not iterable

### ISSUE THREAD

**Issue by dnovotny** [janeczku/calibre-web#2552]
**Describe the bug/problem**
A "Search Error" is the response when clicking "Fetch Metadta".

**To Reproduce**
1. Open a Book.
2. Click on the pencil to edit the book metadata.
3. Scroll down and click "Fetch Metadata"

**Logfile**
Console output:
 <div class="container-fluid">
  <div class="row">
    <div class="col">
        <h1  class="text-center">Calibre-Web</h1>
        <h1  class="text-center">500 Internal Server Error</h1>
        <h3>The server encountered an internal error and was unable to complete your request. There is an error in the application.</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-md-offset-4 text-left">
        
      
        <div>Traceback (most recent call last):</div>
      
        <div>  File &#34;/usr/local/lib/python3.8/dist-packages/flask/app.py&#34;, line 2073, in wsgi_app</div>
      
        <div>    response = self.full_dispatch_request()</div>
      
        <div>  File &#34;/usr/local/lib/python3.8/dist-packages/flask/app.py&#34;, line 1518, in full_dispatch_request</div>
      
        <div>    rv = self.handle_user_exception(e)</div>
      
        <div>  File &#34;/usr/local/lib/python3.8/dist-packages/flask/app.py&#34;, line 1516, in full_dispatch_request</div>
      
        <div>    rv = self.dispatch_request()</div>
      
        <div>  File &#34;/usr/local/lib/python3.8/dist-packages/flask/app.py&#34;, line 1502, in dispatch_request</div>
      
        <div>    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)</div>
      
        <div>  File &#34;/usr/local/lib/python3.8/dist-packages/flask_login/utils.py&#34;, line 303, in decorated_view</div>
      
        <div>    return current_app.ensure_sync(func)(*args, **kwargs)</div>
      
        <div>  File &#34;/app/calibre-web/cps/search_metadata.py&#34;, line 141, in metadata_search</div>
      
        <div>    data.extend([asdict(x) for x in future.result() if x])</div>
      
        <div>TypeError: &#39;NoneType&#39; object is not iterable</div>
      
        <div></div>
      
    </div>
   </div>
  
    <div class="row">
    <div class="col errorlink">Please report this issue with all related information:
        <a href="https://github.com/janeczku/calibre-web/issues/new?assignees=&labels=&template=bug_report.md&title=">Create Issue</a>
    </div>
      </div>

**Expected behavior**
A list of possible book metadata is fetched.

**Screenshots**
[calibre-web error](https://user-images.githubusercontent.com/4438568/192863292-294febcc-2099-406c-80f7-cadfd8d1b609.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python version: python3.8.10
 - Calibre-Web version: [e.g. 0.6.8 or 087c4c59 (git rev-parse --short HEAD)]: 0.6.19 - b5d5660d04acc98283b4ff4a798596d0d270441e - 2022-07-31T16:14:03+02:00
 - Docker container: [None/LinuxServer]: LinuxServer
 - Special Hardware: [e.g. Rasperry Pi Zero]: RaspberryPi4
 - Browser: [e.g. Chrome 83.0.4103.97, Safari 13.3.7, Firefox 68.0.1 ESR] Chrome 106.0.5249.61

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

**Comment by dnovotny** [comment]
This should be merged with https://github.com/janeczku/calibre-web/issues/2547 as they are the same error.

**Comment by OzzieIsaacs** [comment]
Pleas update to the newest nightly version, it should be fixed now
