### ISSUE TITLE
Scan books from a system folder

### ISSUE THREAD

**Issue by AmadeusGraves** [janeczku/calibre-web#2565]
**Is your feature request related to a problem? Please describe.**
The problem is that adding a book always has to be done from the interface. 

**Describe the solution you'd like**
When you have a lot of books and know how to download them automatically, for example with readarr or qbitorrent, they are stored in a system folder. Calibre Web should have the possibility to be able to add that folder as a media directory from where you can automatically import the books without having to do it manually. 

**Describe alternatives you've considered**
There is Kavita which has this functionality and provides most of its value. The problem with Kavita is that it is only translated into English and Calibre Web is in several languages, Calibre Web only lacks this functionality and it would be perfect to have it.

**Comment by bodybybuddha** [comment]
This has been requested a number of times before. The quickest solution is just to create a shell script to do it:  #412

**Comment by OzzieIsaacs** [comment]
Thanks @bodybybuddha

**Comment by scrapix** [comment]
The proposed solution was to create a cronjob, which would never add the books immediately to the lib.

I have found another solution (currently via shell script)

Therefore you need to first install inotify-tools. those allow to monitor a folder.
`nohup yes | apt install inotify-tools # installing inotify-tools and answering yes to any question during install

watchfolder=/books/autoAddFromHere #adjust to the folderpath you want to watch

nohup inotifywait -m $watchfolder -e create -e moved_to --exclude '\@.*' |
    while read directory action file; do
        echo "The file '$file' appeared in directory '$directory' via '$action'"
            echo "The file '$file' will be now added to the library"
            calibredb add -r $watchfolder --library-path="/books" $file
    done`

**Comment by timdonovanuk** [comment]
Sorry just ended up here, completely new to Calibre and Calibre-web...how on earth do I add a book? Do I always need to do everything via the Calibre desktop app first? 

"adding a book always has to be done from the interface."...?

**Comment by SirHazza** [comment]
For future reference, I've created a [full guide for this topic in the wiki](https://github.com/janeczku/calibre-web/wiki/Automatically-import-new-books-(Linux)), based on the approach provided by @scrapix. It was extremely helpful, thank you!
