### ISSUE TITLE
Transliteration of folders and filenames

### ISSUE THREAD

**Issue by akushsky** [janeczku/calibre-web#257]
When I use Calibre directly and add cyrillic book - it creates folder and filename transliteration way, but calibre-web uses cyrillic names from book metadata.

I think, that it's need to unify logic. 

Which library Calibre uses for it?

**Comment by OzzieIsaacs** [comment]
Please install "unidecode", afterwards the behavior should be same (I'll add it to the needed dependencys)

**Comment by akushsky** [comment]
Great, working, closing issue.

**Comment by paulhybryant** [comment]
Is it possible to make this an option? Not using unidecode gives a better name for the files saved on the filesystem and also the downloaded files.

**Comment by OzzieIsaacs** [comment]
I'm sorry. Calibre-web replicates calibre behaviour, and calibre does it the way it is implemented now, and I don't know of a option to change naming on the harddrive.

**Comment by paulhybryant** [comment]
Oh, what I meant is to make whether to use unidecode configurable through the web UI.
