### ISSUE TITLE
Add support for CALIBRE_OVERRIDE_DATABASE_PATH

### ISSUE THREAD

**Issue by cygmanu** [janeczku/calibre-web#2571]
**Is your feature request related to a problem? Please describe.**
According to https://manual.calibre-ebook.com/customize.html, CALIBRE_OVERRIDE_DATABASE_PATH "allows you to specify the full path to metadata.db. Using this variable you can have metadata.db be in a location other than the library folder. Useful if your library folder is on a networked drive that does not support file locking."

**Describe the solution you'd like**
The calibre way of solving this problem seems clunky to me. A better solution imho would be separating config_calibre_dir into config_calibre_dir (location of metadata.db - selectable from UI OR defaulted from ENV) and data_calibre_dir (location of library files - selectable from UI). 

**Describe alternatives you've considered**

**Additional context**
I am a developer by trade, though not fluent in python. I will attempt to implement a solution myself and submit a pull request, but am certainly open to thoughts/ideas from more seasoned experts.

**Comment by cygmanu** [comment]
Found a workaround. disregard.

**Comment by bronikowski** [comment]
@cygmanu it would be great if you'd tell us what workaround you've found
