### ISSUE TITLE
ImportError: cannot import name 'json' from 'itsdangerous' when trying to start up

### ISSUE THREAD

**Issue by phairplay** [janeczku/calibre-web#2574]
**Describe the bug/problem**
starting program and faced with the following error

**To Reproduce**
1. Go to 'starting cp.'
I re-ran the requirement file and have a different error 
```
C:\Calibre-Web>C:\Python37\python.exe C:\Calibre-web\cps.py
Traceback (most recent call last):
  File "C:\Calibre-web\cps.py", line 28, in <module>
    from cps.main import main
  File "C:\Calibre-web\cps\__init__.py", line 28, in <module>
    from flask import Flask
  File "C:\Python37\lib\site-packages\flask\__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "C:\Python37\lib\site-packages\flask\app.py", line 25, in <module>
    from . import cli, json
  File "C:\Python37\lib\site-packages\flask\json\__init__.py", line 21, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (C:\Python37\lib\site-packages\itsdangerous\__init__.py)

C:\Calibre-Web>pause
Press any key to continue . . .
```

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

**Expected behavior**
expected program to start up 

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python version: python3.7

**Additional context**
could you please help. I've installed all the requirement packages

here is everything I have installed 

- `advocate                  1.0.0
- altgraph                  0.17
- apprise                   1.0.0
- APScheduler               3.6.3
- Babel                     2.10.3
- backports-abc             0.4
- bcrypt                    4.0.0
- beautifulsoup4            4.9.3
- blinker                   1.5
- cachetools                5.2.0
- casttube                  0.2.1
- catt                      0.12.2
- certifi                   2020.12.5
- cffi                      1.15.1
- cfscrape                  2.1.1
- chardet                   3.0.0
- charset-normalizer        2.0.12
- cheroot                   8.2.1
- CherryPy                  18.6.0
- click                     7.1.2
- colorama                  0.4.5
- configparser              5.0.1
- cryptography              38.0.1
- feedparser                6.0.2
- Flask                     1.0.2
- Flask-Babel               0.11.1
- Flask-Login               0.3.2
- Flask-Principal           0.3.2
- Flask-WTF                 0.14.2
- FormEncode                2.0.1
- future                    0.18.2
- google-api-core           2.10.1
- google-api-python-client  2.62.0
- google-auth               2.11.1
- google-auth-httplib2      0.1.0
- google-auth-oauthlib      0.5.3
- googleapis-common-protos  1.56.4
- greenlet                  1.1.3
- httplib2                  0.20.4
- humanfriendly             10.0
- idna                      2.10
- ifaddr                    0.1.7
- importlib-metadata        4.12.0
- iso-639                   0.4.5
- itsdangerous              2.1.2
- jaraco.classes            3.2.0
- jaraco.collections        3.1.0
- jaraco.functools          3.1.0
- jaraco.text               3.4.0
- Jinja2                    2.10.1
- jsonrpclib-pelix          0.4.3.2
- lxml                      4.8.0
- Mako                      1.1.4
- Markdown                  3.4.1
- markup                    0.2
- Markups                   3.1.3
- MarkupSafe                2.0.1
- more-itertools            8.6.0
- natsort                   7.1.1
- ndg-httpsclient           0.5.1
- netifaces                 0.11.0
- oauthlib                  3.2.1
- paramiko                  2.11.0
- pefile                    2019.4.18
- Pillow                    9.2.0
- pip                       22.2.2
- portend                   2.7.0
- protobuf                  4.21.6
- psutil                    5.9.2
- pyasn1                    0.4.8
- pyasn1-modules            0.2.8
- PyChromecast              9.2.0
- pycountry                 22.3.5
- pycparser                 2.21
- PyDispatcher              2.0.6
- pyinstaller               4.2
- pyinstaller-hooks-contrib 2020.11
- PyNaCl                    1.5.0
- pynzbget                  0.6.4
- pyOpenSSL                 22.1.0
- pyparsing                 3.0.9
- PyPDF2                    1.20
- pypi-xmlrpc               2020.12.3
- pyreadline                2.1
- pySMART                   1.1.0
- pystun                    0.1.0
- python-markdown-math      0.8
- pytz                      2016.10
- pywin32                   300
- pywin32-ctypes            0.2.0
- PyYAML                    6.0
- rarfile                   4.0
- reload                    0.9
- requests                  2.27.1
- requests-futures          1.0.0
- requests-oauthlib         1.3.1
- rsa                       4.9
- setuptools                40.6.2
- sgmllib3k                 1.0.0
- simplejson                3.17.2
- six                       1.15.0
- soupsieve                 2.1
- SQLAlchemy                1.3.0
- SQLObject                 3.10.0
- ssdp                      1.1.0
- tempora                   4.0.1
- tornado                   4.1
- typing_extensions         4.4.0
- tzlocal                   2.1
- Unidecode                 0.4.19
- uritemplate               4.1.1
- urllib3                   1.26.3
- user-agent                0.1.10
- user-agent2               2021.12.11
- Wand                      0.4.4
- watchdog                  2.1.9
- Werkzeug                  2.0.3
- wheel                     0.37.1
- workerpool                0.9.4
- WTForms                   3.0.1
- xmltodict                 0.13.0
- youtube-dl                2021.12.17
- zc.lockfile               2.0
- zeroconf                  0.31.0
- zipp                      3.4.0`

**Comment by OzzieIsaacs** [comment]
Sorry for the late reply. Please try to reinstall flask, it looks like flask is incompatible to the itsdangerous version you have installed.
To avoid problems like this, please install calibre-web in it‘s own virtual environment (python venv command), or use the windows exe version.
