### ISSUE TITLE
CPS won't start Calibre-Web

### ISSUE THREAD

**Issue by blumarten** [janeczku/calibre-web#2586]
Hello. Firstly, apologies, I'm not very technical at all.

I installed Calibre-Web on a mac using the pip3 install and it worked perfectly (great job btw!)
This evening I tried to do the same on a raspberry pi using the pip install but after it finished i tried running with CPS without success.

Reading back through the terminal window I saw a series of warning just before the process ended, as below, and you can see my CPS / command not found attempt at the end:

```
Successfully built netifaces
Installing collected packages: tzdata, pytz-deprecation-shim, pytz, pyasn1, WTForms, tzlocal, tqdm, netifaces, ndg-httpsclient, greenlet, Babel, Wand, unidecode, tornado, SQLAlchemy, PyPDF3, iso-639, flask-wtf, Flask-Principal, Flask-Login, Flask-Babel, backports-abc, APScheduler, advocate, calibreweb
  WARNING: The script tqdm is installed in '/home/books/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script ndg_httpclient is installed in '/home/books/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pybabel is installed in '/home/books/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script unidecode is installed in '/home/books/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script cps is installed in '/home/books/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed APScheduler-3.9.1 Babel-2.10.3 Flask-Babel-2.0.0 Flask-Login-0.6.1 Flask-Principal-0.4.0 PyPDF3-1.0.6 SQLAlchemy-1.4.42 WTForms-3.0.1 Wand-0.6.10 advocate-1.0.0 backports-abc-0.5 calibreweb-0.6.19 flask-wtf-1.0.1 greenlet-1.1.3.post0 iso-639-0.4.5 ndg-httpsclient-0.5.1 netifaces-0.11.0 pyasn1-0.4.8 pytz-2022.5 pytz-deprecation-shim-0.1.0.post0 tornado-6.1 tqdm-4.64.1 tzdata-2022.6 tzlocal-4.2 unidecode-1.3.6
books@books:~ $ cps
bash: cps: command not found
```
 - OS: Raspberry Pi OS
 - Python version: [3.9.2
 - Calibre-Web version: not sure, whatever the latest version is
 - Docker container: [None]
 - Special Hardware: Raspberry pi 4

Any ideas? I'd love to get this working as it's so much better than other options.
Many thanks!

**Comment by OzzieIsaacs** [comment]
Looks like you (or your Mac) installed calibre-web in `/home/books/.local/bin` which is not on PATH.

So a `/home/books/.local/bin/cps` could do the trick. If this isn't working search for the file "cps" and start it with the full path name.I have no idea how to search for files on a Mac, so can't give you any more help

**Comment by blumarten** [comment]
hey ozzie, thank you for replying. 
sorry if i wasn't clear. I got it working fine on a mac, but my problem here is with a raspberry pi installation.
do you know where it should be installed on an RPi4?

**Comment by OzzieIsaacs** [comment]
If you installed it with the user books as the commands indicate, it should be the path I gave in my first reply

**Comment by blumarten** [comment]
thanks ozzie. i'm going to start again from scratch tonight and hopefully do it right this time. appreciate your help.

**Comment by OzzieIsaacs** [comment]
There is no need to reinstall, just search for the file

**Comment by blumarten** [comment]
hi ozzie, ok, i got back to a point where calibre-web is working again, and you were absolutely right, the cps was at the path you specified above.

So now I'm trying to get CW to auto-launch when my pi reboots. I've followed your instructions [here](https://github.com/janeczku/calibre-web/wiki/Setup-Service-on-Linux) but I think i've done something wrong.

My content in the cps.service I created is:

`[Unit]
Description=Calibre-Web

[Service]
Type=simple
User=books
ExecStart=/home/books/.local/bin/cps.py
WorkingDirectory=/home/books/.local/bin

[Install]
WantedBy=multi-user.target
`
(my username is 'books' on that pi btw)

Is that correct, or have I made a mistake? any idea how i can get this working?

**Comment by OzzieIsaacs** [comment]
I guess you enabled it (the last block in the instructions), maybe you need to start it also

sudo systemctl enable cps.service

with sudo systemctl status cps.service you should see if it’s running or what it is missing/wrong

**Comment by OzzieIsaacs** [comment]
I‘m away from my computer, and not 100% sure but the file name is cps and not cps.py in the folder you are pointing to

**Comment by blumarten** [comment]
hmm ok, the instructions seem to specify that i should type 'cps.py', in this line?

ExecStart={path to python} {/PATH/TO/**cps.py including cps.py**}

**Comment by blumarten** [comment]
oh it worked! i removed the .py from that line and it worked fine, thank you ozzie!

**Comment by OzzieIsaacs** [comment]
The instruction also states as first to have the path to a python, in this case you start python with cps.py as parameter, if you installed calibre-web via pip then it points to the starter file wilthout .py at the ende
