### ISSUE TITLE
Update the menu chinese translation.

### ISSUE THREAD

**Issue by flashliao** [janeczku/calibre-web#259]
![image](https://user-images.githubusercontent.com/28710685/28749916-ec24fcee-7509-11e7-818f-0f4a0e572797.png)
![image](https://user-images.githubusercontent.com/28710685/28749917-f8c14f8e-7509-11e7-917c-9d8b7d1dc950.png)

**Comment by jkrehm** [comment]
I imagine the authors would be happy to receive a pull request for those translations.

**Comment by idalin** [comment]
Done. #275

**Comment by OzzieIsaacs** [comment]
merged
