### ISSUE TITLE
How to import books?

### ISSUE THREAD

**Issue by Nabukodonosor** [janeczku/calibre-web#2592]
I've installed calibre-web in docker, and it works fine. I have my ebooks library on my disk. But I don't see the option to import that library. I only see the option to upload a book. And when I do, it creates a double copy of that book on my drive, with an author folder. How to avoid that and just import my existing library?

**Comment by GoGoSoSlow** [comment]
You need to pass the folder of the library to the docker instance.  There should be lines in your docker-compose that should look like:
volumes:
      - '/files/library:/books'  #replace /files/library with the location of the library on the host computer.
If you are using docker run use the /v command line option to do the same.

**Comment by Nabukodonosor** [comment]
I did pass the folder of the library. But it still doesn't load anything in Calibre-web. I have to go to the upload option. And when I do that it creates another folder in my ebook folder (it knows where it is, since I specified it in my docker-compose). Here's my docker-compose:

---
version: "2.1"
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Belgrade
      - DOCKER_MODS=linuxserver/calibre-web:calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - /MainPool/Documents/Containers/calibre:/config
      - /MainPool/Documents/Documents/e-books:/books
    ports:
      - 8083:8083
    restart: unless-stopped

**Comment by OzzieIsaacs** [comment]
This is a docker issue. I can‘t help you, please ask for help from the docker provider

**Comment by actuallymentor** [comment]
I'm pretty sure this is not a Docker issue. Adding new books to the `/book` folder for calibre-web` does not seem to import any books, even after restart.

**Comment by GoGoSoSlow** [comment]
Just adding files to the folder won't add them to the library, because the metadata won't be in the library database.  Calibre-web uses the Calibre library format.  The only way to import them using Calibre-web is to use the upload option.  

You could install the full Calibre app and use that to create your initial library, add all of your books, then pass that to calibre-web in the docker container.  There's a docker version of the full Calibre with a web-vnc front end if you need it, but it'll probably be easier to run the regular version: https://calibre-ebook.com/

**Comment by actuallymentor** [comment]
Ah that explains a lot. The online guides/docs imply that caliber web can also manage books.

If I understand correctly, a separate caliber instance is needed to actually manage file imports then?

I'll investigate that, thank you

**Comment by GoGoSoSlow** [comment]
Calibre-web is meant to be a webui to manage and give web access to calibre libraries.  It can completely run on it's own, but it's good to have a copy of the main calibre app for some things, like bulk conversions, fixing a corrupted library, etc.

I use calibre-web's upload feature to add my new books as I get them, and never need to use the main calibre app anymore.  I previously used Calibre to manage my library, so I didn't have to upload a huge number of books when I first switched to Calibre-web.
