### ISSUE TITLE
No Shelf via OPDS on my iPad

### ISSUE THREAD

**Issue by Nabukodonosor** [janeczku/calibre-web#2593]
I'm using calibre-web with opds in Chunky on my iPad. I have a server with calibre-web installed in docker. All those work fine. But when I access it with my iPad and Chunky, in Shelves there is no my created shelf. My book are there when I go to some of those categories like Authors or Alphabetical Books. Any ideas why my Shelf is not in Shelves?

**Comment by OzzieIsaacs** [comment]
I had the time to double check. For me it's working fine. You gave me no context (the information I asked in the form) so there is nothing more I can do for you

**Comment by Nabukodonosor** [comment]
For those having the same issue, you have to make your library public in the admin panel. Check the "Share with Everyone" option.

**Comment by OzzieIsaacs** [comment]
For me it was working without anonymous browsing enabled. Was you shelf a private one, or visible to everyone?

**Comment by Nabukodonosor** [comment]
Private by default.
