### ISSUE TITLE
Torrent download option for books

### ISSUE THREAD

**Issue by censoredviper** [janeczku/calibre-web#2598]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but it'd be efficient to spread the bandwidth.

**Describe the solution you'd like**
Adding a torrent download option for books, that opens a magnet link or downloads a torrent file that downloads the book. The server makes the torrent but anyone downloading it will also contribute to uploading it. Kind of like how peertube does it when you download a video. (They have a torrent option)

**Comment by OzzieIsaacs** [comment]
It‘s a bit out of scope of what I can support, so I will not implement it
