### ISSUE TITLE
read book - a lot of books are empty

### ISSUE THREAD

**Issue by perler** [janeczku/calibre-web#26]
a lot of books don't display anything at all. I think these are books without chapters. (see screenshots for comparison)

![2016-06-17_2052_001](https://cloud.githubusercontent.com/assets/623092/16161377/80026222-34cd-11e6-8b39-c98ed92b554b.png)
![2016-06-17_2052](https://cloud.githubusercontent.com/assets/623092/16161378/8017ea7a-34cd-11e6-9ec7-42c0240e84e4.png)

**Comment by janeczku** [comment]
Fixed in 91eb712

**Comment by perler** [comment]
not really, apparently my suspicion that it happens with books without a TOC was wrong. Can I send you a book that isn't displayed by mail?

**Comment by perler** [comment]
I just see, that there are warnings on the console:

WARNING:tornado.access:404 GET /static/2871/META-INF/container.xml (127.0.0.1) 3.82ms
