### ISSUE TITLE
Cannot install under Python 3.11 due to failure building LXML

### ISSUE THREAD

**Issue by Evolution0** [janeczku/calibre-web#2606]
**Describe the bug/problem**
Cannot install under Python 3.11 due to being unable to build LXML 4.8.0 with Python 3.11.

**To Reproduce**
1. Attempt to install under Python 3.11

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python version: Python 3.11
 - Calibre-Web version: 0.6.19
 - Docker container: None
 - Special Hardware: N/A
 - Browser: N/A

**Additional context**
This is an issue for a lot of projects under Python 3.11 that make use of LXML, its possible to get wheels of 4.9.0 for Python 3.11 even if I can't build it but not 4.8.0 (At least I could not) but calibre-web specifically is set to reject 4.9.0 as an option, is there a particular reason for that?

Switching to a 3.10 venv just as a sanity check and to confirm its not an issue with my system I can indeed install it without a problem, likely I will end up installing in a docker container in the meantime.

**Comment by OzzieIsaacs** [comment]
I limit the max versions of everything, because in the past some updates had breaking changes, so I‘d like to check it, before I allow it. In this case I don‘t expect any problems, so please try it

**Comment by dartie** [comment]
At moment, the workaround is using a virtual environment with python3.8 and install calibreweb.

**Comment by devicemxl** [comment]
I download the whl file (for my pc architecture), open a cdm in downloads folder and install: 
pip install lxml-4.9.0-cp311-cp311-win_amd64.whl
That's work for me.

- The recommendation of the repo: https://lxml.de/installation.html
- The instructions are here: https://www.delftstack.com/howto/python/how-to-install-a-python-package-.whl-file/
- The repo: https://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml

**Comment by Evolution0** [comment]
> I download the whl file (for my pc architecture), open a cdm in downloads folder and install: pip install lxml-4.9.0-cp311-cp311-win_amd64.whl That's work for me.
> 
> * The recommendation of the repo: https://lxml.de/installation.html
> * The instructions are here: https://www.delftstack.com/howto/python/how-to-install-a-python-package-.whl-file/
> * The repo: https://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml

Yeah at the time the cp311 wheel wasn't available, ~gohlke is what I usually use when I need a wheel of it.
