### ISSUE TITLE
Unable to Use pass phrase protected certs for SSL

### ISSUE THREAD

**Issue by Kalkn83** [janeczku/calibre-web#2609]
**Describe the bug/problem**
Unable to use pass phrase protected certs when configuring SSL. 

When I look at calibre-web.log, I'm seeing this error
{cps.server:215} Gevent SSL Error: [Errno 13] Permission denied

In the Terminal window where the cps.py is running, it gets stuck in a loop asking for the PEM pass phrase.

**To Reproduce**
1. Use a passphrase protected key and cert file in the in the Server Configuration
2. Look at calibre-web.log to see error seen above. 
3. Look at terminal window where the cps.py is running to see passphrase prompt. 
4. Enter pass phrase, prompt comes back immediately. 

**Logfile**
{cps.server:215} Gevent SSL Error: [Errno 13] Permission denied

**Expected behavior**
Able to use HTTPS/SSL

**Environment (please complete the following information):**
 - OS: MacOS
 - Python version: python3
 - Calibre-Web version: 0.6.19 Daria
 - Browser: Safari, Chrome, Firefox

**Comment by OzzieIsaacs** [comment]
I never checked this, so it's kind of expected that it's not working. I'll have a lok at it, but currently I'm busy with other topics

**Comment by wgibcus** [comment]
Not an expert in this area but I'm pretty sure you can merge the passphrase with your PEM file. (https://security.stackexchange.com/questions/59136/can-i-add-a-password-to-an-existing-private-key)
