### ISSUE TITLE
Question: is there a possibility to run calibre-web by Phusion Passenger

### ISSUE THREAD

**Issue by kryst3q** [janeczku/calibre-web#2611]
Hello and many thanks for such great piece of code!

I come with question. Is there any possibility to run calibre-web that was installed using pip by Phusion Passenger? I tried to do that by creating passenger_wsgi.py file that consist of below piece of code

```python
from calibreweb import main

def application(environ, start_response):
    return main
```

but got such error only

```
Traceback (most recent call last):
  File "/usr/local/lib/ruby/gems/2.7/gems/passenger-6.0.11/src/helper-scripts/wsgi-loader.py", line 203, in main_loop
    socket_hijacked = self.process_request(env, input_stream, client)
  File "/usr/local/lib/ruby/gems/2.7/gems/passenger-6.0.11/src/helper-scripts/wsgi-loader.py", line 347, in process_request
    for data in result:
TypeError: 'function' object is not iterable
```

I was looking on the codebase but I don't know nor python nor Flask. I only found [this](https://www.phusionpassenger.com/library/walkthroughs/start/python.html) example on PP website.

Thanks in advance!

**Comment by OzzieIsaacs** [comment]
This will not work, calibre-web has it‘s own builtin wsgi-server(tornado, or gevent). So it can’t be run by something else, sorry
