### ISSUE TITLE
A renewed request for 2FA or another solution for safe remote login 

### ISSUE THREAD

**Issue by joho500** [janeczku/calibre-web#2613]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Either a option to use 2FA with an OTP application or the ability to disable normal login and only use OAuth with GitHub or Google.

**Additional context**
I use Calibre-Web often outside my home when on holiday for instance. Therefore I have it accessible via the internet and in that situation I find 2FA a security necessity. 

I know you stated "We will not extend Calibre-Web with any more login abilities or add further files storages, or file syncing ability. Furthermore Calibre-Web is made for home usage for company in-house usage (...)". But I think that out-of-the-house usage for personal use is probably regular home usage for others too.
I hope you will consider this request.
Thanks.

**Comment by thirionlogan** [comment]
You can use the "reverse proxy authentication" setting that is already in calibre-web to use your own authentication setup. I use authelia which allows me to use TFA. If you want to use a second factor with no third party, you can set up a time-based one-time password method.

**Comment by joho500** [comment]
> You can use the "reverse proxy authentication" setting that is already in calibre-web to use your own authentication setup. I use authelia (Self hosted SSO) which allows me to use TFA. If you want to use a second factor with no third party, you can set up a time-based one-time password method. Also, there is already the option to use OAuth under the "reverse proxy authentication" setting.

Thanks. I will investigate that option
