### ISSUE TITLE
Two Factor Authentication

### ISSUE THREAD

**Issue by Jan-NiklasB** [janeczku/calibre-web#2616]
**Is your feature request related to a problem? Please describe.**
Without a second factor one needs a high entropy passwort (at least as admin) to be at least halfway safe against attacks.
High entropy passwords are hard to remember.

**Describe the solution you'd like**
Implementation of TOTP and FIDO, so one can use a password which is simple to remember without the risk of getting hacked by rainbow-table and bruteforce attacks.

**Describe alternatives you've considered**
OAUTH needs a third party which not everyone likes to have involved.

**Comment by thirionlogan** [comment]
You can use the reverse proxy authentication setting to use your own authentication setup. I use authelia which allows me to use TFA. If you want to use a second factor with no third party, you can set up a time-based one-time password method.

**Comment by OzzieIsaacs** [comment]
Sorry, I stated in the contribution guidelines that I will not extend calibre-web anymore with more login features.

https://github.com/janeczku/calibre-web/blob/master/CONTRIBUTING.md#feature-request
