### ISSUE TITLE
Get independent from calibre server instead build up metadata in own database

### ISSUE THREAD

**Issue by inject3d** [janeczku/calibre-web#2618]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i want to use calibre in a docker container. It does not work really nice as the ui is completly out of date. 

**Describe the solution you'd like**
It would be nice if the selected target folder would look for the epub files i've bought and create a database with its metadata on its own.

**Comment by OzzieIsaacs** [comment]
There is an example on how to mass-add books from a given folder using Calibre (no need to start the program itself).
https://github.com/janeczku/calibre-web/wiki/FAQ#mass-add-books

The purpose of Calibre-Web is to have a web server based on the calibre database, I don't want to start a totally independent library
