### ISSUE TITLE
Hide books from user

### ISSUE THREAD

**Issue by 8bitgentleman** [janeczku/calibre-web#262]
Is there a way to hide certain books from some user's?

**Comment by Kyosfonica** [comment]
AFAIK nope, there isn't such feature.

**Comment by 8bitgentleman** [comment]
I think that would be a useful feature to implement in the future. I share my library with many family members of different ages and there are some books that just aren't appropriate for younger readers. Just my 2 cents. Other than missing that one feature I'm loving calibre-web so far

**Comment by jkrehm** [comment]
Perhaps a custom column (either in Calibre's or Calibre-web's database) to track a rating system of some sort, like TV or movies have, e.g. B-Y, B, B-14, B-MA. And then configuration to denote what the maximum rating a user is allowed to see. If something like that were implemented, I think the default should be that a book is visible.

**Comment by 8bitgentleman** [comment]
I agree, the default should always be visible. Another solution could be to use calibre's category tags to filter hidden/visible. You could set books with certain category tags to alway be hidden (e.g books tagged with "Adult").

**Comment by jkrehm** [comment]
That's a much simpler idea to implement. A configurable list of tags (comma delimited), then a "show mature content" checkbox on the admin's version of the user's profile page to determine if books with those tags are shown.
