### ISSUE TITLE
User Profiles 

### ISSUE THREAD

**Issue by talamasc** [janeczku/calibre-web#2621]
Hi,

after migration of calibre-web to a new server, i'm not able to restore the user profiles from the old server.
After setup of the new server, the admin passwort was changed to the old one and i logged out.
Then I transfered the app.db to the new server to the correct directory _/home/[user]/calibre-web/app.db_
After logging in as admin there's no change. I can't see the old profiles.
Trying to create one of the old users show's up, that the user already exists.

Would be grateful for support.

Python Version :            3.9.2
Operating System :       Linux 5.10.0-19-amd64 , Debian 5.10.149-2 (2022-10-21) x86_64
Docker :                           NO;
Calibre-Web version :    0.6.19 - pyPi;

--

**Comment by OzzieIsaacs** [comment]
Before ypu copy the app.db file to the new location you need to stop calibre-web. Please start it afterwards, then the old data should be available. If not, calibre-web is using another app.db

**Comment by talamasc** [comment]
Thanks for your advice.

After a search I found  an other app.db which was used.
So it was obviously my fault.
