### ISSUE TITLE
Kindle (and others) ebook synchronization

### ISSUE THREAD

**Issue by evolucja** [janeczku/calibre-web#2625]
**Is your feature request related to a problem? Please describe.**
Currently there is no easy way of syncing our devices to Calibre-web.

**Describe the solution you'd like**
I'd like an option to connect device via USB cable, so the Calibre-web can fetch books from it and show the status "synced" or something like that. In addition, there would be a separate button "Send to device" or checkbox "Sync with device XYZ"

**Describe alternatives you've considered**
I can obviously use "Send to Kindle" but it doesn't give us back the status of the book and is not always very fast etc.

**Additional context**
None

**Comment by OzzieIsaacs** [comment]
The purpose of Calibre-Web is to act as a server, especially in use cases where you don't have physically access to the computer. For your use case, I recommend using Calibre itself.
