### ISSUE TITLE
Book Tracking read status - date last read

### ISSUE THREAD

**Issue by psyciknz** [janeczku/calibre-web#2629]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
The UI seems to support book read or not.....I was wondering how much structure, code would be required to add per book instead of just Read or not, when it was last completed.  So a book could actually show that it had been read a number of times.

Trying to consider a self hosted goodreads - which i only really use for tracking what I have read.

**Describe alternatives you've considered**
Goodreads - current functionality
ReadDB - seems to do the book tracking,

Ideally adding another service when it really is an extra piece of metadata I could hold about a book.

**Comment by OzzieIsaacs** [comment]
You could define a custom column in Calibre of format "date". In this column you could add the information on when the book was completed last time. 
Does this help you?

**Comment by psyciknz** [comment]
How would that work if it had been read multiple times?

i am making shelves,  one for each year as a work around
