### ISSUE TITLE
Please add LDAP and/or AD auth

### ISSUE THREAD

**Issue by ruben-herold** [janeczku/calibre-web#263]
hi,

it would be nice if I could use ldap or ActiveDirectory for user athentication

**Comment by ruben-herold** [comment]
https://code.tutsplus.com/tutorials/flask-authentication-with-ldap--cms-23101 example

**Comment by ThorstenS-linux** [comment]
this feature would be really helpfull for our school-servers.

**Comment by nocylah** [comment]
PAM auth would also be useful.

**Comment by nstephenh** [comment]
I'd also like to request LDAP, although I don't really use accounts with this program it would be nice to have the option.

**Comment by artiomn** [comment]
I need LDAP too.

**Comment by lucas-dclrcq** [comment]
Hi, I'm currently working on an external authentication scheme for Calibre web and I have a question : are people more interested in an implementation of LDAP authentication or OpenID ?

**Comment by bodybybuddha** [comment]
@lucas-dclrcq it looks like the biggest win is for LDAP, as it's mentioned more often then OpenID.  Of course it would be awesome to get them all!

@OzzieIsaacs also has mentioned in previous posts that he was hoping to do a plug in type system.  Maybe coordinate with him to ensure everyone is on the right path? Might have an easier time in getting the feature merged into the main fork.

**Comment by Krakinou** [comment]
Hi,
Any update on this subject?
I would be very interested by LDAP too

**Comment by Gorian** [comment]
Hello - I'd also like LDAP / Active Directory! I'm integrating everything on my network with Active Directory, and that would seel the deal for using this for hosting ebooks

**Comment by Krakinou** [comment]
Tired of waiting :)
#769

**Comment by centuryx476** [comment]
This would be an awesome feature.
Any update on it ?

**Comment by BinsonBuzz** [comment]
+1 from me for LDAP

**Comment by OzzieIsaacs** [comment]
LDAP is available in the newest master commit version
