### ISSUE TITLE
Own Column with Dates / Advanced Search not working

### ISSUE THREAD

**Issue by Dirk71** [janeczku/calibre-web#2631]
**Own Column**
I have created an Own Column in Calibre called "Read Date". For all my books I have read, I tag the books as READ and set the date I have finished the book in my Own Column "Read Date".

**Advanced Search**
In the Advanced Search I can set the "Read Date" From To Date. But it does not work. E.g. I have finished a book reading at 22.11.2022. When I search from 01.11.2022 to 31.12.2022 no books will be shown. It doesn't matter which dates I set, there will be no result at all.

**Updated explanation for Advanced Search**
There seems to be a link between OwnColumn #readdate (format:date) and #read (format:yes/no). When I set "Read Status" to "Yes" and set the readdates (from to), the books will be shown in the search result correctly.

**Comment by OzzieIsaacs** [comment]
I can't reproduce it, for me it's working. 
Maybe you set something in Calibre regarding the settings of the custom column:
![image](https://user-images.githubusercontent.com/6438895/209567603-e520c181-280c-4bd6-a700-13b948c0a48b.png)
During searching I leave everything empty except the custom date:
![image](https://user-images.githubusercontent.com/6438895/209567665-f356b664-cdd9-45dd-a632-9895497e965e.png)
I tried it with english and german language settings in the User interface.
The Link Read/Unread column was empty during my test:
![image](https://user-images.githubusercontent.com/6438895/209567757-860d8696-4da8-45a3-8ada-d1ffeb30b867.png)
