### ISSUE TITLE
Change the instance name so it doesn't say "Calibre-Web" in the title

### ISSUE THREAD

**Issue by rudolphh** [janeczku/calibre-web#2634]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

I notice 'instance' in layout.html.  Couldn't find anything suggesting this is currently possible.  Would also accept for now a hack (including going into the docker container) so that I could change my current setup.  Thanks for this great piece of software.  I will try to learn the codebase better to contribute.

**Comment by mohammed90** [comment]
You can already change it. Go to: admin -> Edit UI Configuration -> View Configuration. Change the value of the "Title" field.
