### ISSUE TITLE
Can't view book details

### ISSUE THREAD

**Issue by andyforceno** [janeczku/calibre-web#264]
I updated to Calibre-web 2017-07-30T06:59:12+02:00 and now when I click on the book cover to view the book details, there's nothing there. So, I can't read or download books, either.There are no errors in the log file. I tried restarting calibre-web, and I opened Calibre to confirm I can view the book metadata.

![book_details](https://user-images.githubusercontent.com/3803896/28991471-3efe094c-7956-11e7-8ab0-9c10f81fd799.png)

**Comment by jkrehm** [comment]
Are you getting JavaScript errors? Also, could you try clearing your browser cache and try again?

**Comment by andyforceno** [comment]
Oh, why didn't I think of that. I logged out and then cleared my cache, so I'm not sure which fixed it, but it's working again.

**Comment by jkrehm** [comment]
Sometime I want to figure out a good, reliable cache buster for the static assets, e.g. appending the MD5 hash of the file as a query string in the script `src`.

**Comment by csbenz** [comment]
I'm getting the same error inside the default Kobo browser, any way to solve the issue?
