### ISSUE TITLE
Cover images not showing in Search Metadata

### ISSUE THREAD

**Issue by ToontjeM** [janeczku/calibre-web#2640]
**Describe the bug/problem**
Cover images are not showing in Metadata search.
<img width="603" alt="image" src="https://user-images.githubusercontent.com/98271783/209666543-a7900d89-027a-4a37-98f3-062eee66f1ac.png">

**To Reproduce**
1. Go to any book
2. Click on Edit Metadata
3. Scroll down to any description that matches your book.
4. <img width="603" alt="image" src="https://user-images.githubusercontent.com/98271783/209666543-a7900d89-027a-4a37-98f3-062eee66f1ac.png">

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

**Expected behavior**
Cover images are shown.

**Environment (please complete the following information):**

Library Statistics
30	Books in this Library
22	Authors in this Library
27	Categories in this Library
0	Series in this Library

System Statistics
Program	Installed Version
Calibre Web	0.6.19
Python	3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
Platform	Linux 5.15.74-1-pve #1 SMP PVE 5.15.74-1 (Mon, 14 Nov 2022 20:17:15 +0100) x86_64 x86_64
Image Magick	ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25 https://imagemagick.org
Unrar	unrar 0.0.2
Ebook converter	ebook-convert (calibre 5.37.0)
Kepubify	kepubify v4.0.4
advocate	1.0.0
APScheduler	3.9.1.post1
Babel	2.11.0
backports_abc	0.5
beautifulsoup4	4.10.0
cchardet	2.1.7
chardet	4.0.0
comicapi	2.2.1
Flask	2.1.3
Flask-Babel	2.0.0
Flask-Dance	5.1.0
Flask-Login	0.6.2
Flask-Principal	0.4.0
Flask-SimpleLDAP	1.4.0
flask-wtf	1.0.1
gevent	21.12.0
goodreads	0.3.2
google-api-python-client	2.49.0
google-auth-oauthlib	0.5.3
greenlet	1.1.3.post0
html2text	2020.1.16
httplib2	0.20.4
iso-639	0.4.5
Jinja2	3.1.2
jsonschema	4.8.0
lxml	4.8.0
markdown2	2.4.6
natsort	8.1.0
oauth2client	4.1.3
pyasn1	0.4.8
pyasn1-modules	0.2.8
PyDrive2	1.10.2
PyPDF2	3.0.0
pySqlite	2.6.0
python-dateutil	2.8.1
python-ldap	3.4.3
python-Levenshtein	0.12.2
pytz	2022.1
PyYAML	5.4.1
rarfile	4.0
requests	2.25.1
rsa	4.8
scholarly	1.7.6
SQLAlchemy	1.4.45
SQLAlchemy-Utils	0.38.3
SQLite	3.37.2
tornado	6.1
unidecode	1.3.6
uritemplate	4.1.1
Wand	0.6.10
werkzeug	2.0.3

**Comment by OzzieIsaacs** [comment]
Please have a look at the developer console of your browser, if there are any relevant errors

**Comment by timdonovanuk** [comment]
I'm having the same thing. 

```
Refused to load the image '<URL>' because it violates the following Content Security Policy directive: "img-src 'self'  data:".

2:1 Refused to load the image 'https://books.google.com/books/content?id=MXj0THxYdkMC&printsec=frontcover&img=1&zoom=1&source=gbs_api&fife=w800-h900' because it violates the following Content Security Policy directive: "img-src 'self'  data:".

etc.

I wonder if this is because I'm accessing calibre-web via http and these resources are https? Either way, it can be avoided by fixing the tags. 
```

**Comment by OzzieIsaacs** [comment]
Please try to update to the newest nightly version, it hopefully should work again

**Comment by timdonovanuk** [comment]
> Please try to update to the newest nightly version

How does one do that? Thanks

**Comment by OzzieIsaacs** [comment]
Go to admin -> Basic configuration -> server configuration -> Update chanell, change no nightly. Go back to admin section, click on check for update and update
