### ISSUE TITLE
Thank You to the Calibre-Web Developer Community!

### ISSUE THREAD

**Issue by holta** [janeczku/calibre-web#2641]
Many https://internet-in-a-box.org schools & communities worldwide use your work, Thank You!

![haiti-school-kids](https://user-images.githubusercontent.com/2458907/209668509-36352a09-7f9c-456e-9dce-ccaed8c4a08f.jpg)

![image](https://user-images.githubusercontent.com/2458907/209668125-32801168-be58-4eef-bfdb-f3fe3426ec4d.png)

**Comment by OzzieIsaacs** [comment]
Thanks for the feedback
