### ISSUE TITLE
PDF Covers not extracted

### ISSUE THREAD

**Issue by scrapix** [janeczku/calibre-web#2647]
**Describe the bug/problem**
Covers are not being extracted from some PDFs when uploading via Web Upload.

**To Reproduce**
Regular Upload with certain PDFs

**Logfile**
`[2023-01-06 11:45:05,284]  WARN {cps.uploader:83} cannot parse metadata, using default: file has not been decrypted`

**Expected behavior**
Covers should be extracted from all PDFs. Calibre for desktop it works.

**Environment (please complete the following information):**
 - OS: linux
 - Python version: [e.g. python2.7]
 - Calibre-Web version: 0.6.19
 - Docker container: janeczku/calibre-web
 - Browser: any

**Additional context**
Works prefectly fine with other pdfs

**Comment by OzzieIsaacs** [comment]
Please install pypdf2 in the newest version and remove pypdf3. Then it should work

**Comment by scrapix** [comment]
hey @OzzieIsaacs thank you for your quick reply. 

I've tried your workaround suggestion.

1. exec'd into the container 
2. pip uninstall pypdf3
3. pip install pypdf2

Still not working. Metadata + Cover are not being read by calibre web on web upload. Same error.
`[2023-01-06 15:33:28,785]  WARN {cps.uploader:83} cannot parse metadata, using default: file has not been decrypted`

**Comment by OzzieIsaacs** [comment]
Please check that pypdf2 is really used by calibre-web (about section). If this is the case, the current encryption of the pdf isn‘t supported by the used library and as a consequence from this, also not supported by calibre-web
