### ISSUE TITLE
Create new public shelf

### ISSUE THREAD

**Issue by simper** [janeczku/calibre-web#265]
How to create a new public shelf, it seems I login as admin, but there is no way to make a shelf public and in creating a new shelf, there is no option to choose it to be public, the only input is the name of the shelf?

**Comment by fuchst** [comment]
On the page to edit users, click on the admin and in his settings there should be a toggle "Allow Editing Public Shelfs". Check if this is set. If so, a toggle should be visible during shelf creation.

**Comment by simper** [comment]
@fuchst it works, thanks for the detailed instructions!
