### ISSUE TITLE
Possibility to save bookmark and adjust font size in read in browser mode

### ISSUE THREAD

**Issue by simper** [janeczku/calibre-web#266]
Bookmark can be created in read in browser mode but once the page is closed or refreshed, the bookmark will be lost which makes this functionality useless; and the size of the font cannot be adjusted is also an annoying thing when some of the book's default font size is too small.

**Comment by fuchst** [comment]
Font size can be changed by zooming in the browser. Text reflows and it works really well. Regarding the bookmarks, this is also not working on my end. Sadly I currently don't have the time to investigate, but I assume that it just doesn't communicate with and store the state on the server. So it is only local.

**Comment by OzzieIsaacs** [comment]
Bookmarks are not saved (it's just not implemented)

**Comment by simper** [comment]
@OzzieIsaacs Is there near plan to implement bookmark in database for separate user?

**Comment by simper** [comment]
@fuchst Thanks for the tip, on computer browser it did work well, but on mobile, it is not very convenient to do such zoom in browser, it is still appreciated if the browser js reader provides the option to do several stops of font size adjustments.

**Comment by jkrehm** [comment]
@OzzieIsaacs does reader.min.js come from https://github.com/futurepress/epub.js/?

If so, it should be possible to hook into its event handler to listen for the `"reader:bookmarked"` event, e.g.

```javascript
window.reader.on("reader:bookmarked", function (location) {
  console.log(location); // e.g. epubcfi(/6/4[id7]!/4[307]/4/1:0)
});
```

We could save that to the database and append it to the URL when the user returns, e.g. http://calibre.dev.local/read/57/epub#epubcfi(/6/4[id7]!/4[307]/4/1:0).

**Comment by OzzieIsaacs** [comment]
I just checked the code on their website, it is the library which is used in calibre-web

**Comment by OzzieIsaacs** [comment]
I think it's a good idea to proceed as you suggested (creating a new table, holding the user_id, the books_id and the "bookmarkstring" )

**Comment by jkrehm** [comment]
FYI, I've begun work on this: https://github.com/jkrehm/calibre-web/tree/bookmarks

**Comment by OzzieIsaacs** [comment]
**1** bookmark per book is now saved. UI is not 100% perfect due to bugs in the underlying script used.

**Comment by abhisharm** [comment]
Is this supposed to work the other way around? I have many bookmarks saved in my calibre app but when viewing them through the browser they don't show up.
