### ISSUE TITLE
Some particular books not syncing with Kobo sync

### ISSUE THREAD

**Issue by g0r3** [janeczku/calibre-web#2664]
Hi,

yesterday I added a three PDFs to my Calibre-web instace. While (most) epub books sync just fine, I can't manage to get those three PDFs to show up in my library on my Kobo Sage. On the web interface they are perfectly visible. The logs don't contain any suspicious messages. The allowed language for my account is set to all languages. Does someone have a clue whats going on or how to debug this?

Thanks.

**Comment by Code-Slave** [comment]
Kobo sync does not support pdf

**Comment by g0r3** [comment]
Oh, sorry. I wasn't aware of that.
