### ISSUE TITLE
Kobo sync create token not working

### ISSUE THREAD

**Issue by Code-Slave** [janeczku/calibre-web#2665]
**Describe the bug/problem**
i just tried to enable kobo sync functionality. when i click create token in my profile is just show "..." then it starts coverting everything to kepub. Ive selected on specific shelves as an option. After running a while the kepub conversion now says db is locked.

**To Reproduce**
go to profile an create token

**Environment (please complete the following information):**
latest docker image from linuxserver
firefox and chrome

**Comment by flipside101** [comment]
i had similar , i found by accident that it took about 2 mins and then the token appeared

**Comment by Code-Slave** [comment]
i have 6000 books so the kepub creation i think is messing things up

**Comment by Code-Slave** [comment]
just tried on a completely fresh install and nothing. same issue

**Comment by Code-Slave** [comment]
I got it to work by logging in and opening a new tab then called /kobo_auth/generate_auth_token/3
in new tab. worked after 15 seconds. and shows up when i click the button under profile now. no idea why as debug log showed no errors. now going to test the kobo
