### ISSUE TITLE
Version Information shows date and time

### ISSUE THREAD

**Issue by rsauve** [janeczku/calibre-web#2667]
I just updated Calibre-web to:
Calibre Web      0.6.19 - e178efb58cadc53d30836ed92d5e6b869bc222c0 - 2023-01-15T13:49:16+01:00 - pyPi

Logging into the administrator account shows:
![Capture](https://user-images.githubusercontent.com/26235138/213831407-339dfa95-2162-4031-a337-a276010a21a4.PNG)

Shouldn't the version column show a version number instead of date and time?
<br/><br/>
**System information where Calibre-web is installed:**
System:    Host: fileserver Kernel: 5.4.0-137-generic x86_64 bits: 64 Console: tty 0
           Distro: Ubuntu 20.04.5 LTS (Focal Fossa)
Machine:   Type: Desktop Mobo: Intel model: D2500CC v: AAG81477-401 serial: <superuser/root required>
           BIOS: Intel v: CCCDT10N.86A.0040.2014.0520.1400 date: 05/20/2014
CPU:       Topology: Dual Core model: Intel Atom D2500 bits: 64 type: MCP L2 cache: 512 KiB
           Speed: 1867 MHz min/max: N/A Core speeds (MHz): 1: 1867 2: 1867
Graphics:  Device-1: Intel Atom Processor D2xxx/N2xxx Integrated Graphics driver: gma500 v: N/A
           Display: server: No display server data found. Headless machine? tty: 106x30
           Message: Advanced graphics data unavailable in console. Try -G --display
Audio:     Device-1: Intel NM10/ICH7 Family High Definition Audio driver: snd_hda_intel
           Sound Server: ALSA v: k5.4.0-137-generic
Network:   Device-1: Intel 82574L Gigabit Network driver: N/A
           Device-2: Intel 82574L Gigabit Network driver: e1000e
           IF: enp2s0 state: up speed: 1000 Mbps duplex: full mac: 00:22:4d:a6:3e:d2
           IF-ID-1: docker0 state: down mac: 02:42:a9:1b:f3:d7
Drives:    Local Storage: total: 5.57 TiB used: 1.91 TiB (34.3%)
           ID-1: /dev/sda vendor: Samsung model: SSD 750 EVO 120GB size: 111.79 GiB
           ID-2: /dev/sdb vendor: Western Digital model: WD6003FZBX-00K5WB0 size: 5.46 TiB
Partition: ID-1: / size: 108.74 GiB used: 58.94 GiB (54.2%) fs: ext4 dev: /dev/dm-0
           ID-2: /boot size: 973.4 MiB used: 223.7 MiB (23.0%) fs: ext4 dev: /dev/sda2
Sensors:   System Temperatures: cpu: 48.0 C mobo: 55.0 C
           Fan Speeds (RPM): fan-1: 128 fan-2: 0
Info:      Processes: 211 Uptime: 1d 17h 19m Memory: 3.82 GiB used: 849.5 MiB (21.7%) Init: systemd
           runlevel: 5 Shell: bash inxi: 3.0.38

**Comment by OzzieIsaacs** [comment]
If you are on the nightly update channel it shows a date (the commit date of the version you are using)
