### ISSUE TITLE
fake_pubdate overlap on pubdate on editing book page

### ISSUE THREAD

**Issue by cyrg38** [janeczku/calibre-web#2669]
**Describe the bug/problem**
The pubdate on editor page is superposed by 2 similar dates input, so becomes unreadable.
The calendar picker is not in good place.

**To Reproduce**
1. Go to book page
2. Click on edit button (pen)
3. Scroll down to pubdate
4. See overlapping dates

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/8496262/213860771-a9d45fde-d182-4111-991f-c7e68a2f5274.png)

Furthermore, when editing the date, the calendar object is not in good place : 
![image](https://user-images.githubusercontent.com/8496262/213860813-758682b0-15cd-468f-b0a8-e2945fee0a84.png)

I think The input with id="fake_pudate" must be removed, but I don't know how.

**Environment (please complete the following information):**
 - OS: Debian 10
 - Python version: 
 - Calibre-Web version: 0.6.19
 - Docker container: LinuxServer
 - Special Hardware: None
 - Browser: Firefox 109.0 Firefox Snap for Ubuntu, Google Chrome Version 109.0.5414.74

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

**Comment by OzzieIsaacs** [comment]
This is fixed with this PR https://github.com/janeczku/calibre-web/issues/2515 in the newestly nightly version. So if you switch to the nightly docker version (I don't know how they call it exactly) your issue should be solved

**Comment by cyrg38** [comment]
thanks
