### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by jvoisin** [janeczku/calibre-web#2673]
**Describe the bug/problem**

Calibre-web is crashing on startup.

**To Reproduce**
1. `python3 /opt/calibre/cps.py`
2. get a crash

**Logfile**
```
/opt/calibre $ python3 /opt/calibre/cps.py
Traceback (most recent call last):
  File "/opt/calibre/cps.py", line 31, in <module>
    main()
  File "/opt/calibre/cps/main.py", line 26, in main
    app = create_app()
          ^^^^^^^^^^^^
  File "/opt/calibre/cps/__init__.py", line 175, in create_app
    from .schedule import register_scheduled_tasks, register_startup_tasks
  File "/opt/calibre/cps/schedule.py", line 22, in <module>
    from .services.background_scheduler import BackgroundScheduler, CronTrigger, use_APScheduler
ImportError: cannot import name 'CronTrigger' from 'cps.services.background_scheduler' (/opt/calibre/cps/services/background_scheduler.py)
```

This is likely due to e178efb58cadc53d30836ed92d5e6b869bc222c0

**Expected behavior**
No crash.

**Environment (please complete the following information):**
 - OS: Alpine Linux
 - Python version: python 3.11.1
 - Calibre-Web version: 4913f06e
 - Docker container: None
 - Special Hardware: Nope

**Comment by OzzieIsaacs** [comment]
There is some problem with APScheduler, please try reinstalling it with pip

**Comment by jvoisin** [comment]
I'm using the [one packaged in Alpine Linux]( https://pkgs.alpinelinux.org/packages?name=py3-apscheduler&branch=edge&repo=&arch=&maintainer=), aka 3.9.1-r1.

**Comment by faspina** [comment]
is there a workaround for this.?

**Comment by OzzieIsaacs** [comment]
https://github.com/janeczku/calibre-web/issues/2653

This is some problem with APScheduler, please try reinstalling it with pip

**Comment by dqylyln** [comment]
after pip install apscheduler   is work
