### ISSUE TITLE
"Error: File size may be too big" on books of any size on Upload

### ISSUE THREAD

**Issue by Irv007** [janeczku/calibre-web#2678]
**Description of problem** 

1. Each uploaded book results in: "Error: File size may be too big".
2. I found this error message in calibre-web in uploadprogress.js.
3. I do have the problem with each book regardless of its size
4. Size of book: 600 KB (e. g.)
5. nginx.conf: client_max_body_size 30M;

The problem occurs since some days.

**Steps to reproduce the behavior**

1. Click Button "Upload" in Calibre-Web
2. Choose any book of any size
3. Press "ok"
4. Progress bar appears
5. See error

**Logfile calibre-web.log**

There is no info about the problem in the log file.

**Expected behavior**

- Books can be uploaded to Calibre-Web, no error message on books with size small enough

**Environment**

 - OS: 20.04.1-Ubuntu on Google Cloud Platform
 - Calibre-Web version: 0.6.19
 - Docker container: linuxserver/calibre-web, nginxproxy/nginx-proxy
 - Browser: Chrome, Edge

<img width="1213" alt="too big" src="https://user-images.githubusercontent.com/35102767/215256980-a1d2f937-5cf7-4caa-8099-dd2843a1596e.png">

**Comment by OzzieIsaacs** [comment]
It has to do with your proxy config (I can‘t catch the error to give a better error message in the code). Please have a look at the developer console of your browser and check if there are any errors

**Comment by Irv007** [comment]
Google Chrome
Dev Tools
Console

says:

```
POST https://xbuch.eu/upload
uploadprogress.js:99           
net::ERR_HTTP2_PING_FAILED

submit          @ uploadprogress.js:99
i               @ jquery.min.js:2
dispatch        @ jquery.min.js:2
v.handle        @ jquery.min.js:2
trigger         @ jquery.min.js:2
(anonymous)     @ jquery.min.js:2
each            @ jquery.min.js:2
each            @ jquery.min.js:2
trigger         @ jquery.min.js:2
S.fn.<computed> @ jquery.min.js:2
(anonymous)     @ main.js:142
dispatch        @ jquery.min.js:2
v.handle        @ jquery.min.js:2
```

**Comment by OzzieIsaacs** [comment]
I tried to Google the error message, but no real success. The error is referring to http version 2, calibre-web is still using http version 1.1. So the problem is the proxy inbetween. Please ask for help at the docker providers repository, this is not a problem of calibre-web

**Comment by Irv007** [comment]
ok. Thank you for your help.

**Comment by Irv007** [comment]
>>Please ask for help at the docker providers repository

Which docker providers repository could I ask for help?

linuxserver/calibre-web?
or
nginxproxy/nginx-proxy?

**Comment by OzzieIsaacs** [comment]
I think the proxy is the problem (nginx)

**Comment by Irv007** [comment]
https://github.com/nginx-proxy/nginx-proxy/discussions/2154

**Comment by Irv007** [comment]
- Long story short.
- I would not believe it, if somebody told me.
- The problem was the network card on my client (Windows PC).
- It did not figure out the real reason.
- Found via goole one description of a similar problem without a solution.
- I did not have any other problem with this network card.
- But since I don't use the network card any longer, everythings works again as expected.
- Now running on an external ethernet card usb-adapter.
