### ISSUE TITLE
No option to set number of columns in book view ?

### ISSUE THREAD

**Issue by matikken** [janeczku/calibre-web#2680]
There is no option to set number of column in book view, or at least wrap title option? When i/we ? maximize web browser on monitor (2K  resolution) there is a lot of wasted space between books covers, and titles are amost twice width of cover. This looks ugly. 
On FHD resolution books covers and their titles  looks much better arranged but also are not ideal. 

On main page here in description we can see screenshot of calibreweb with nice tightly arranged books, but i get such layout only for 1024x768. When you have larger monitor, title wraping dont works well and on 2k monitor i see only 6 covers in one row  and a lot of empty spaces with very wide titles (also left main menu is quite width, and feel empty - "create shelf" button is.. 9cm width).

Is any solution to this ?

**Comment by OzzieIsaacs** [comment]
There is no option to do this

**Comment by matikken** [comment]
> There is no option to do this

Maybe someone could point me to css code part to adjust it?

**Comment by OzzieIsaacs** [comment]
It‘s done via some ja code:   https://github.com/janeczku/calibre-web/blob/d2056ceb51b33cf3dfe079f024fcba905609f186/cps/static/js/main.js#L361
The ja library is from here: https://isotope.metafizzy.co/

**Comment by matikken** [comment]
Thanks, i will look into that. I noticed also second style : "caliBlur! Dark" which seems a way, way better than previous, default one (everything is properly compacted here even on larger screens, visually - colours, grained wallpaper also good).

So if someone cant stand big, empty areas at default light style - take look at dark. Hovewer it also has some flaws - looks at some places as if it wasnt finished yet (for example book list have glitched highlightning and dissappearing fonts on buttons after hovering).  Maybe this is reason why its not default style. One more drawback there, is that button to read book is not somewhere at proximity (for example under book cover) but far on right upper corner web browser.

**Comment by OzzieIsaacs** [comment]
In the newest nightly version, calibre-web displays again more books in a row, depending on the width of the screen

**Comment by matikken** [comment]
Great news, Cant wait to update to this in official version. Im impressed with calibreweb so far, and i recommend it to everyone who want to have his own library.
