### ISSUE TITLE
Feature request: create metadata.opf in book directories just like Calibre Desktop

### ISSUE THREAD

**Issue by sibbl** [janeczku/calibre-web#2683]
**Is your feature request related to a problem? Please describe.**

I regularly have the problem that when adding a book, a 500 internal server error happens. Once in a while, my metadata.db gets broken due to this... There are various options to restore the broken metadata.db:

1. Use a backup
2. Reimport all books from scratch
3. Let Calibre Desktop rebuild it from the metadata.opf files in the book directories

**Describe the solution you'd like**

Considering the 3 options from above...
1. needs additional effort as I need to create manual or automatic backups.
2. drops all metadata changes I manually did in Calibre Web.
3. is not possible, as no metadata.opf in the book directory is being created and maintained.

I'd appreciate it, if Calibre Web also creates metadata.opf files when a book is imported and updates it whenever metadata is changed - just like Calibre Desktop does it.

**Describe alternatives you've considered**

I'm right now regularly opening Calibre Desktop and using the maintenance option to recreate these metadata files.
This consumes quite some time, the more books there are.

Please let me know what you think and what might speak against this. Thanks! 🤗

**Comment by OzzieIsaacs** [comment]
I have programmed a function like this. Hopefully I can merge it in the next month

**Comment by OzzieIsaacs** [comment]
But of course we should find the underlying problem for the error 500

**Comment by sibbl** [comment]
@OzzieIsaacs mostly the 500 were related to specific pdfs+epubs or my NAS and its HDD were on high load. I suppose some file system issues just happen with a file based database. However, I'll keep in mind to create a bug report whenever I have a reproducable scenario.

**Comment by OzzieIsaacs** [comment]
In the newest nightly version (after installing all new dependencies) and restarting, there is a button in the scheduler section to generate metadata backup. This is done once per day. The file is compatible to calibre. It backups all "normal data" and **only** the custom columns supported by calibre-web

**Comment by OzzieIsaacs** [comment]
Additionally all upload,edit book activities in calibre-web mark this metadata for backup, so if you start calibre the data is automatically generated by calibre
