### ISSUE TITLE
Unable to load pdf books on Apple iPad

### ISSUE THREAD

**Issue by dztsg** [janeczku/calibre-web#2686]
**Describe the bug/problem**
A clear and concise description of what the bug is. If you are asking for support, please check our [Wiki](https://github.com/janeczku/calibre-web/wiki) if your question is already answered there.

**To Reproduce**
After updating to Calibre-Web0.6.19 stable version, pdf books can be loaded on Apple iPad using Apple Safari Browser, Microsoft Edge Browser, Firefox Browser and Google Chrome Browser.
However, after updating to Calibre-Web0.6.20 Beta, using Apple Safari Browser, Microsoft Edge Browser, Firefox Browser, and Google Chrome Browser on Apple iPad can't load pdf books, and the following pages are displayed.
Please help check the cause of the fault. Thank you very much!
![1](https://user-images.githubusercontent.com/96064333/217865725-e9c04610-4cfa-4a75-994e-4ef302441fd6.jpg)

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10/Raspberry Pi OS]
 - Python version: [e.g. python2.7]
 - Calibre-Web version: [e.g. 0.6.8 or 087c4c59 (git rev-parse --short HEAD)]:
 - Docker container: [None/LinuxServer]:
 - Special Hardware: [e.g. Rasperry Pi Zero]
 - Browser: [e.g. Chrome 83.0.4103.97, Safari 13.3.7, Firefox 68.0.1 ESR]

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

**Comment by OzzieIsaacs** [comment]
Using my iPadPro iOS 16.3 with Safari browser (all browser avilable on iOS have only a different user interface, but in the background are all the same) can't reproduce it:
<img width="1194" alt="2023-02-09 19-05-33-0" src="https://user-images.githubusercontent.com/6438895/217900130-b20c6d28-0db4-4d57-8d5c-8b5f5f4b4b4c.png">
I'm using the latest beta version from evening February 6th. Using the download pdf button or the read in browser button, both work

**Comment by dztsg** [comment]
Thank you very much for your quick reply!
My Apple iPad system seems to be iPad OS 15.7. Now, I update the system of Apple iPad to iPad OS 16.3.
Then, after Calibre-Web is updated to 0.6.20 Beta, using Apple Safari browser, Microsoft Edge browser, Firefox browser and Google Chrome browser on Apple iPad, pdf books can be loaded.
Thank you again!
