### ISSUE TITLE
[Kobo sync] Do NOT append port to [OneStoreServices] group entries

### ISSUE THREAD

**Issue by Stylback** [janeczku/calibre-web#2690]
**Is your feature request related to a problem? Please describe.**
Kobo Sync integration for Kobo Libra H2O only works on local network due to a default port behavior.

**Describe the solution you'd like**
Change the behaviour of Calibre web's Kobo Sync to NOT append the default port number (8083) to entries in the `[OneStoreServices]`  group if the API endpoint is an URL. This would allow sync to resolve for URL:s.

**Describe alternatives you've considered**
Using the Kobo Sync feature on local network only.

**Additional context**
For the `api_endpoint` in the `Kobo eReader.conf` file, you can either use `ip:port` or `domain.tld.`. If you use `domain.tld.`, upon disconnecting the eReader and trying to sync, you will be met with a sync error. If you then open  `Kobo eReader.conf`  you will notice that the default port number (8083) will have been appended to the URL for several entries in the `[OneStoreServices]`  group:

```
api_endpoint=http://sub.domain.tld/kobo/[sync token]
...
image_host=http://sub.domain.tld:8083
image_url_quality_template=http://sub.domain.tld:8083/kobo/[sync token]/{ImageId}/{width}/{height}/{Quality}/isGreyscale/image.jpg
image_url_template=http://sub.domain.tld:8083/kobo/[sync token]/{ImageId}/{width}/{height}/false/image.jpg
```

As `http://sub.domain.tld:8083` is unreachable, the sync will fail. Manually removing the port number will have no effect as they will be re-appended on the following sync attempt. Changing the file permission to read only will not work either as the eReader will trash and replace the file.

This behaviour might be not exclusive for Kobo Libra H2O, but I don't have an additional device to test on.

**Comment by IntBoat** [comment]
You should change post number in calibre-web config, If you use HTTP set it to 80, if you use HTTPS set it to 443.

Basic Configuration > Feature Configuration  > Server External Port (for port forwarded API calls)

**Comment by Stylback** [comment]
> You should change post number in calibre-web config, If you use HTTP set it to 80, if you use HTTPS set it to 443.
> 
> Basic Configuration > Feature Configuration > Server External Port (for port forwarded API calls)

Hi and thank you for the reply!  **Your suggestion worked for me**.

I did the following:

1.  In Calibre-Web, went to `Basic Configuration → Feature Configuration → Server External Port` and set it to `443`
2. Then reset my device at `More → Settings → Device information → Factory reset your eReader`
3. After connecting to WiFi and setting the device up, plug it in and edit `Kobo eReader.conf ` as outlined in the wiki.
4. Unplug device and ran repairs at `More → Settings → Device information → Repair your Kobo account`
5. In Calibre-Web, went to `Profile → Force full kobo sync`
6. On device, pressed `Sync`

Some fiddling, but sync works without issue now.

### Suggestion for future improvement

As far as I can tell, sync would have worked without the appended port number if an empty field was allowed in `Server External Port`. The entries in the `[OneStoreServices]` group would've still resolved correctly thanks to the Reverse proxy. Perhaps it's worth considering? Either way, consider this issue closed.
