### ISSUE TITLE
Database error: attempt to write a readonly database.

### ISSUE THREAD

**Issue by mikebgrep** [janeczku/calibre-web#2696]
Hello I just install the Calibre web docker image provided by linuxservers.io on my raspberry pi and I copy the methadata.db file into the container and set the path in the Calibre-web.

1. It doesn't make any difference I don't see book in the application and I can't search for books online
- _Not sure if this will actually need to happen since I need to have my library alone.But in my observation I need to have option to search for books online and buy (or I am wrong)_

2. I set up on install of the docker the Library folder to point external ssd where I upload pdf file.In the calibre-web I don't see the file
-  _Here I am pretty sure is need to be shown in the calibre-web_

3. I try to upload manual the pdf file and I got this error Database error: attempt to write a read-only database.
- _I check another issue its appear I have allowed all files and languages._

Any help and answers to the comment will be helpful.
Thank you

**Comment by OzzieIsaacs** [comment]
I‘m not providing the docker image, so I have only limited knowledge:

> I cp the methadata.db file into the container and set the bath in the Calibre-web

I don‘t think this is how it is supposed to work, you need to map the location of the metadata.db somehow to the docker container. Please ask for help at linuxserver repository

**Comment by mikebgrep** [comment]
Is the metadata.db empty database is connect and reconnect right

**Comment by mikebgrep** [comment]
I message again the problem is not in the docker container we test it with the providers the problem is in databse.
```
2023-02-17 20:36:33,477]  INFO {cps:152} Starting Calibre Web...
[2023-02-17 20:36:34,887]  INFO {apscheduler.scheduler:171} Scheduler started
[2023-02-17 20:36:34,968]  WARN {py.warnings:109} /usr/local/lib/python3.10/dist-packages/apscheduler/util.py:436: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tzinfo.localize(dt)
[2023-02-17 20:36:34,969]  INFO {apscheduler.scheduler:885} Added job "end scheduled task" to job store "default"
[2023-02-17 20:36:37,688]  INFO {cps.server:205} Starting Gevent server on [::]:8083
[2023-02-17 20:37:10,671] ERROR {cps.editbooks:301} Database error: (sqlite3.OperationalError) attempt to write a readonly database
[SQL: INSERT INTO authors (name, sort, link) VALUES (?, ?, ?)]
[parameters: ('Unknown', 'Unknown', '')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-02-17 20:40:36,462]  INFO {cps.ub:890} Changed allowed tags of user admin to ['*']
[2023-02-17 20:40:49,497] ERROR {cps.editbooks:301} Database error: (sqlite3.OperationalError) attempt to write a readonly database
[SQL: INSERT INTO authors (name, sort, link) VALUES (?, ?, ?)]
[parameters: ('Unknown', 'Unknown', '')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-02-17 20:41:04,671]  INFO {cps.ub:890} Deleted allowed tags of user admin: *
[2023-02-17 20:41:43,242]  WARN {cps.admin:154} reconnecting to calibre database
[2023-02-17 20:41:56,605] ERROR {cps.editbooks:301} Database error: (sqlite3.OperationalError) attempt to write a readonly database
[SQL: INSERT INTO authors (name, sort, link) VALUES (?, ?, ?)]
[parameters: ('Paco Hope', 'Hope, Paco', '')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-02-17 20:44:27,408] ERROR {cps.editbooks:301} Database error: (sqlite3.OperationalError) attempt to write a readonly database
[SQL: INSERT INTO authors (name, sort, link) VALUES (?, ?, ?)]
[parameters: ('Unknown', 'Unknown', '')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```
this is the sql error.Any help how to fix it

**Comment by OzzieIsaacs** [comment]
Calibre-web can‘t write to the database, so there is a permission problem

**Comment by mikebgrep** [comment]
I made chmod +x on the file just in case and still doesn't have permission.I think is a bug since the container work and can't be replicated or something in the settings.

**Comment by OzzieIsaacs** [comment]
It‘s definitely working, this are usual problems of docker users, I don‘t know the answer, but it nothing to do with calibre-web

**Comment by mikebgrep** [comment]
Ok I will see if its permission problem

**Comment by mikebgrep** [comment]
Ok is permission problem, I fix it. Thanks

**Comment by shunia** [comment]
> Ok is permission problem, I fix it. Thanks

Could you please share how you fixed it?

**Comment by mikebgrep** [comment]
You can try with this permission 
sudo chown -R 472:472 PATH
If this does not work if you give full permision to the folder where is the database must work.

**Comment by shunia** [comment]
@mikebgrep Thank you, but it's not working for root user after trying. I solved this problem by set PUID/PGID to the user who downloaded the db file.
Still thank a lot.

**Comment by fivehanz** [comment]
I added below environment variables

```
PUID=1000
PGID=1000
```

db file ```chmod 777```

**Comment by jaud7of8** [comment]
I see this is a closed issue, but non of the above fixed my issue.
Calibre-web is installed with docker-compose.
I had the metadata.db in the books folder, which is mapped to a storage drive, not the drive or location the docker-compose is running from.
I moved the metadata.db from to the host folder location of the config folder, then calibre-web was able to upload books.
snipit of the docker-compose

volumes:
      - /local-location/config:/config
    I moved the metadata.db to the  'local-location/config folder

**Comment by jackyu1996** [comment]
What seems to be working for me is this:

Check the owner of the library directory (where your metadata.db is placed) and change the owner to you. In my case, it was owned by root and after the change, I can upload just fine.

**Comment by marcusfey** [comment]
I had a similar problem and none of the advises here helped me.
Originally I mapped my metadata.db to /metadata.db, then to /app/calibre-web/metadata.db
Neither worked, always "readonly database".

What finally did the trick was to put the file into a directory which is accessible by user "abc". I used /tmp which may be weird but it works.

**Comment by MReschenberg** [comment]
I had this issue as well -- what fixed it for me was to `chmod 777 /path/to/folder/containing/database/` :) apparently chmoding the database isn't enough, the directory it is in needs to be correctly permissioned as well. I was using a directory I'd linked via container manager (with permissions there set to "read/write"). Ultimately I ended up spawning a bash instance from the container manager > open terminal view and running the chmod command above.

**Comment by mebaysan** [comment]
I moved metadata.db under /config and changed the ownership from root to abc. It worked!

**Comment by marcusfey** [comment]
@mebaysan That's a good idea! 

I tried it with a new installation and now my books ended up on `/config` as well. I did not find an option to change that.
So I moved the DB into `/library` and this works like a charm. I didn't even have to change any ownerships.

**Comment by 34292885** [comment]
I made the config and books chmod 777 and solved it.

**Comment by dansity** [comment]
I want to add that i had the same issue even after correct chmod until: 1) I had two calibre instances running, one on my PC and one on docker. 2) my books library was in a directory that had special character from my language. I renamed it to "Books" and started working

**Comment by ReeseArch64** [comment]
> I see this is a closed issue, but non of the above fixed my issue. Calibre-web is installed with docker-compose. I had the metadata.db in the books folder, which is mapped to a storage drive, not the drive or location the docker-compose is running from. I moved the metadata.db from to the host folder location of the config folder, then calibre-web was able to upload books. snipit of the docker-compose
> 
> volumes: - /local-location/config:/config I moved the metadata.db to the 'local-location/config folder

this solved my problem too

**Comment by raveBee** [comment]
For me the problem cloud be solved by setting the permission of the library folder.
Before fixing the issue all contents of the folder library belonged to the user root:
```
root@library:/var/lib/docker/volumes/calibre_web_library/_data# ls -la
total 412
drwxr-xr-x 2 root    root      4096 Jul 29 11:36 .
drwx-----x 3 root    root      4096 Jul 29 11:30 ..
-rw-rw-rw- 1 library library 413696 Jul 29 11:36 metadata.db
```

The fix was: `chown 1000:1000 /var/lib/docker/volumes/calibre_web_library/_data`

afterwards it looks like this and the upload is working

```
root@library:/var/lib/docker/volumes/calibre_web_library/_data# ls -la
total 412
drwxr-xr-x 2 library library   4096 Jul 29 11:36 .
drwx-----x 3 root    root      4096 Jul 29 11:30 ..
-rw-rw-rw- 1 library library 413696 Jul 29 11:36 metadata.db
```

**Comment by devkamiki** [comment]
This is ridiculous, because NONE of the above solutions actually worked for me.
Proof of I've done anything possible:

```
root@debian:~/docker/calibre# docker exec -it f4a223637d26 ls -la books  
total 356
drwxrwxrwx 2 abc abc   4096 Jul 29 12:56 .
drwxr-xr-x 1 abc abc   4096 Jul 29 10:33 ..
-rwxrwxrwx 1 abc abc 356352 Jul 29 12:56 metadata.db
root@debian:~/docker/calibre# docker exec -it f4a223637d26 ls -la config
total 524
drwxrwxrwx 2 abc abc   4096 Jul 29 13:15 .
drwxr-xr-x 1 abc abc   4096 Jul 29 10:33 ..
-rwxrwxrwx 1 abc abc 118784 Jul 29 13:09 app.db
-rw-r--r-- 1 abc abc  15010 Jul 29 13:39 calibre-web.log
-rw-r--r-- 1 abc abc      3 Jul 29 10:31 client_secrets.json
-rw-r--r-- 1 abc abc  24576 Jul 29 10:33 gdrive.db
-rw-r--r-- 1 abc abc     44 Jul 29 10:31 .key
-rwxrwxrwx 1 abc abc 356352 Jul 29 13:15 metadata.db
root@debian:~/docker/calibre# docker exec -it f4a223637d26 ls -la       
total 164
...
drwxrwxrwx   2 abc  abc   4096 Jul 29 12:56 books
...
drwxrwxrwx   2 abc  abc   4096 Jul 29 13:15 config

```

It's also chown 1000:1000 on the host machine and chmod 777 for metadata.db and the paths containing this file...

**Comment by ve6rah** [comment]
I'm stuck in the same boat. as far as I can tell all permissions are perfect, but I keep getting the readonly database errors.
That said, doesn't matter how many times I do chown 777 on things, the permissions don't actually change. but it shouldn't matter because the owner and group are correct.

**Comment by denislemire** [comment]
Don't put SQLite database files in the root of a filesystem.

Just had a fight with this issue and then remembered the problem as I ran into it before with other things that use an SQLite database. SQLite databases can be picky about the permissions on the directory containing the database.

When that directory is right on the filesystem boundary (right at the mount point)

eg) in /books/metadata.db when the mount point is /books

Put your library in a subdirectory of your volume, eg) /books/library if your volume is mounted at /books... This applies to Docker but also to Kubernetes or even if /books happened to be a seperate file system (partition) on a bare metal machine.

**Comment by tartley** [comment]
@denislemire THANK YOU! I would never have realized but you are absolutely right. THANK YOU!
