### ISSUE TITLE
Installation on ARM32 device fails, error while building wheel for cryptography

### ISSUE THREAD

**Issue by ed0mm** [janeczku/calibre-web#2697]
Hi all.

I'm trying to install the calibre-web app for yunohost on my server, which is on a Raspberry 4, but the installation fails due to errors while building the cryptography wheel.

[This](https://paste.yunohost.org/raw/exihusejoq) is the log I get with the errors about cryptography (and not finiding the rust compiler), and this is the error: `ERROR: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects`

I don't know if this concerns only the cryptography developers or you too, but I thought I'd let you know.

**Comment by OzzieIsaacs** [comment]
This is the line of interest:
`2023-02-14 18:06:57,048: WARNING -       error: can't find Rust compiler`

Google thinks this is caused by a pip version which is too old and recommends the following:
`https://stackoverflow.com/questions/67726349/stuck-at-could-not-build-wheels-for-cryptography-which-use-pep-517-and-cannot-be`

**Comment by OzzieIsaacs** [comment]
Thanks for reporting, I've updated the installation instructions accordingly

**Comment by ed0mm** [comment]
I must admit the problem is still there. I don't know if this is tied to updates yet to come from yunohost sincerely. My pip is up to date and on PATH (just as rust and cargo are) but the error is still the same (curiously saying pip and rust "n/a").
I'm no expert and absolutely don't know how dependencies and things run on the yunohost server though. I've opened [a post on ynh's forum](https://forum.yunohost.org/t/calibre-web-installation-fails-due-to-rust-and-cryptography-problems/23632/6) but to no help yet.

**Comment by OzzieIsaacs** [comment]
I could reproduce the error on raspberry and solve it with the procedure described above. So it’s maybe something else with yunohost

**Comment by ed0mm** [comment]
Just to confirm that with newer updates the problem solved itself for me. Thanks, best

**Comment by WindlePoonz** [comment]
Hi ! Sorry to annoy you but the bug still exist on raspberry pi 3. I tried for 3 days all i had found on google, but crytography failed with error : This package requires Rust >=1.56.0.
I installed latest rustup 1.71.1 without result..
Have you got an hint for this ?

**Comment by OzzieIsaacs** [comment]
I can't tell much more beside what I "researched" above. 

If you've installed rust and it's not found during installation, then maybe  "ensure it is on the PATH during installation" (https://community.brewpi.com/t/fresh-install-problem/5366) is helping.

**Comment by OzzieIsaacs** [comment]
Maybe installing the final deb package from calibre-web could avoid the problem: https://github.com/janeczku/calibre-web/releases/download/0.6.20/calibre-web_0.6.20_arm64.deb

**Comment by WindlePoonz** [comment]
Thank you ! But i just figured out that i use an ARM32. I'll see later with reinstalling ARM64.
