### ISSUE TITLE
Guest with only access to reader/viewer is still able to save e-books

### ISSUE THREAD

**Issue by nekoto-kun** [janeczku/calibre-web#2705]
**Describe the bug/problem**
Guest user with disabled download feature but enabled access to viewer is still able to save e-books with keyboard commands like <kbd>Ctrl + S</kbd> and <kbd>Ctrl + P</kbd>. In other words, everyone with enabled access to viewer is able to download. This issue happens on Chrome-based browsers. Is this issue intended?

**To Reproduce**
1. Find default Guest user, edit user, and enable **eBook Viewer**
2. Access web interface, find a book and read
3. Press <kbd>Ctrl + S</kbd> or <kbd>Ctrl + P</kbd>
4. See the PDF file actually downloaded to computer

**Logfile**
-

**Expected behavior**
Viewer is just a viewer with no save and printable feature.

**Screenshots**
-

**Environment (please complete the following information):**
 - OS: Windows 11
 - Python version: default from latest image
 - Calibre-Web version: V0.6.19 Daria
 - Docker container: LinuxServer
 - Special Hardware: -
 - Browser: [Brave Browser Version 1.48.171 Chromium: 110.0.5481.177 (Official Build) (64-bit)](https://brave.com/latest/)

**Additional context**
-

**Comment by OzzieIsaacs** [comment]
I can try to prevent this, but the reader downloads the file anyway. So you can grab the file from the developer console network traffic. It’s only cosmetics

**Comment by OzzieIsaacs** [comment]
The buttons are hidden meanwhile
