### ISSUE TITLE
Adding `djv` to allowed extensions in upload dialog

### ISSUE THREAD

**Issue by ekiim** [janeczku/calibre-web#2709]
Sorry for not following the template.

I notice that when uploading a file via the web UI, I am not able to upload `djv` but I can upload `djvu`, renaming the file does the trick, but I don't want to be doing that all the time.

Any possibility you and add `djvu` to the allowed files in the upload input?

I notice this issue in this version.

```
Calibre-Web version: 0.6.19 - unknown git-clone
Linux Raspbian 5.15.56-v8+ #1575 SMP PREEMPT Fri Jul 22 20:31:26 BST 2022 aarch64 GNU/Linux
```

**Comment by OzzieIsaacs** [comment]
Just go to admin-> basic configuration -> feature configuration and add the "djv" format to the allowed formats (separated by a ",")

**Comment by ekiim** [comment]
I think this could be a separated issue.
Could I integrate that extension to the DJVU viewer?

**Comment by OzzieIsaacs** [comment]
Please update to the newest nightly version, the reader should now allow djv files

**Comment by ekiim** [comment]
Thanks, I'll close this issue.

**Comment by OzzieIsaacs** [comment]
Please leave it open till the next release

**Comment by ekiim** [comment]
Another question I think related to this, the web ui, has support for a djvu web viewer, but when I have a djv file it doesn't allow it. 

Would that be something configurable on the webui?

**Comment by OzzieIsaacs** [comment]
Please update to the newest nightly version, the reader should now allow djv files
