### ISSUE TITLE
I added some unique tags    -- erb --       AND   ---ERB---    when i search for them i get them and lots of others????

### ISSUE THREAD

**Issue by xenduro** [janeczku/calibre-web#2710]
these showed up  100's more(464)????  last one good ??? whats with the others???

'spy thriller, international thriller, middle east thriller, thriller actiion, thriller adventure, thriller books, thriller espionage, thriller lebanon'

1789-1869, Johann Friedrich, Overbeck

-- erb, ---ERB---, www.freemegalink.com, www.gnivek.com

(i tried attaching a screen copy)
![caliber tag issue](https://user-images.githubusercontent.com/111011086/222870965-91582733-bf69-4ef2-aad4-d004465b7cd3.jpg)

**Comment by OzzieIsaacs** [comment]
What do you want to tell me?

**Comment by xenduro** [comment]
you can see the tag search in this clip. and a few of the results. Why are the NON --erb-- 's showing up???

does it look some place else? is it a know issue? is their a reason for it? how do i work around it. 

![caliber tag issue 1](https://user-images.githubusercontent.com/111011086/222874964-2e9aaac8-14bc-4347-8c53-08dac301ebd0.jpg)

**Comment by OzzieIsaacs** [comment]
The screenshot is from calibre. Calibre-Web is a different program, beside sharing the same database there is nothing in common, so please ask this question at calibre's bugtracker: https://bugs.launchpad.net/calibre
