### ISSUE TITLE
Help with OPDS and reverse proxy authentication?

### ISSUE THREAD

**Issue by PriamX** [janeczku/calibre-web#2711]
**Describe the bug/problem**
I am unable to authenticate any users other than 'admin' for the OPDS catalog. I'm using Nginx proxy in front of calibre-web for https, authentication is using the Organizr-auth API so users are known by Calibe-Web via X-WEBAUTH-USER, and this works well for the web interface; all users can access it using their Organizr creds. The URL is essentially https://myserv.mydomain.com/calibre-web, when using OPDS I configure the URL as "https://myserv.mydomain.com/calibre-web/opds/" and this works well using the 'admin' username and testing with an iOS app called MapleRead CX. However, using any other username, it does not work. I've also tested just using a browser from a PC to the URL. The error in the log is essentially:

`[2023-03-03 19:26:27,268]  WARN {cps.opds:492} OPDS Login failed for user "Username" IP-address: xxx.xxx.xxx.xxx`

**Environment:**
 - OS: Fedora Linux 37
 - Python version: 3.8.10
 - Calibre-Web version: 0.6.19
 - Docker container: LinuxServer.io
 - Special Hardware: None, Xeon-based server
 - Browser: MS Edge 110.0.1587.50

Thank you for any guidance!

**Comment by OzzieIsaacs** [comment]
Seems to be a duplicate of: https://github.com/janeczku/calibre-web/issues/2399, please update to the newest nightly version (there should be a docker version of it)

**Comment by PriamX** [comment]
Oh, sure is a duplicate. Thanks. I searched before posting, sorry I missed it.
