### ISSUE TITLE
Search Bug - Error 405

### ISSUE THREAD

**Issue by Jerome2103** [janeczku/calibre-web#2714]
**To Reproduce**
1. Go to 'main'
2. search something

(over advsearch no problem)

**Logfile**

> [2023-03-06 16:28:16,805] ERROR {cps.server:1226} <gevent._socket3.socket at 0x7fe6c48cc040 object, fd=12, family=10, type=1, proto=0>: Invalid HTTP method: '\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03\x80¤[âlÃ5ët\x02\x87öª±B3ÕÝ\x99¨ã6\x02^\x91\x14Êu·[O/ RÒ£\x05¦\x00äÝMm\x960\x9aUÇ\x90\x1fàGe¦&lh´¦(\x17ø®¯\x7f\x00 ÊÊ\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x01\x93ÊÊ\x00\x00\x003\x00+\x00)úú\x00\x01\x00\x00\x1d\x00 #ó¹0\x8b\x0eeZc\x8bR\x990n8B\x97>T\x89Ü\r.\x9aN§\x13¾ã\x8eJU\x00\x12\x00\x00\x00-\x00\x02\x01\x01\x00+\x00\x07\x06\n'
> [2023-03-06 16:28:16,902] ERROR {cps.server:1226} <gevent._socket3.socket at 0x7fe6c48cc040 object, fd=12, family=10, type=1, proto=0>: Invalid HTTP method: '\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03\x86\x80\x8dê\x8aà\x92¶|«õ××î\x1eòêQ\x16oðKw\x8e¸;µü_fø\x0e 0Ctæ_\x87\x91V\x9aM\xa0Ð°^º\x93c\x83ý\x1dÝ\x00\x85\x1e«ú¸\x8bm\xa0\x8aK\x00 zz\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x01\x93ZZ\x00\x00\x00\x10\x00\x0e\x00\x0c\x02h2\x08http/1.1\x00\x1b\x00\x03\x02\x00\x02\x00\x12\x00\x00\x00+\x00\x07\x06ZZ\x03\x04\x03\x03\x00\x0b\x00\x02\x01\x00\x00\x17\x00\x00\x00#\x00\x00Di\x00\x05\x00\x03\x02h2\x00-\x00\x02\x01\x01ÿ\x01\x00\x01\x00\x00\n'

**Expected behavior**
Show all books with "something"

**Screenshots**
![image](https://user-images.githubusercontent.com/27641713/223155800-5305fc0e-1c28-440f-a068-766723868e65.png)

**Environment (please complete the following information):**
 - OS: Synology
 - Python version: [e.g. python2.7] 3.10.6
 - Calibre-Web version: [e.g. 0.6.8 or 087c4c59 (git rev-parse --short HEAD)]: 0.6.19 - b5d5660d04acc98283b4ff4a798596d0d270441e - 2022-07-31T16:14:03+02:00
 - Docker container: [None/LinuxServer]: LinuxServer - Docker (image latest, not nightly!)
 - Browser: newest Chome

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]
no

**Comment by Jerome2103** [comment]
SOULUTION, by `layout.html`
change `<form class="navbar-form navbar-left" role="search" action="{{url_for('search.simple_search')}}" method="POST">` to `<form class="navbar-form navbar-left" role="search" action="{{url_for('search.simple_search')}}" method="GET">`

@OzzieIsaacs why is this changed?

**Comment by OzzieIsaacs** [comment]
? This should not happen, if you are using the version 0.6.19 from July 31st, the code is the get version. If you update your code to the newest nightly version (including the backend) the code expects the post requests and handles it properly.

It was changed because someone was claiming that everything worked, except for the search. Because the search was the only get request it I assumed that it had something to do with it. It turned out that it was something else, but I had implemented it already, so I merged it. 

Your problem is not caused by the change, but by mixing files from 2 commit versions (for whatever reason).

**Comment by Jerome2103** [comment]
the latest commit is:
https://github.com/linuxserver/docker-calibre-web/releases/tag/0.6.19-ls197

**Comment by Jerome2103** [comment]
thx ;)

**Comment by Jerome2103** [comment]
thx
