### ISSUE TITLE
Follow writers and books

### ISSUE THREAD

**Issue by 9acca9** [janeczku/calibre-web#2722]
Hi.
I will like to have that possibility. 
I have a big list where i add writers, and then i search for the books. It will be nice, instead of having this excel horrible list have a place in the calibre web to do that.
(i dont speak english).

Thanks!

p.s.i have a big big library, so... that is pretty relevant for me.

**Comment by OzzieIsaacs** [comment]
I think this is nearly the same request as this one: https://github.com/janeczku/calibre-web/issues/2192
So I consider this as a duplicate of it and I'll close this one
