### ISSUE TITLE
Crash using "default" database

### ISSUE THREAD

**Issue by GTP95** [janeczku/calibre-web#2728]
**Describe the bug/problem**
I'm using [this](https://hub.docker.com/r/linuxserver/calibre-web) Docker image to run Calibre web and I'm trying to use Nextcloud for storage. As I don't have a previous Calibre installation, I downloaded the database that you provide in the readme, and put it into a Nextcloud directory that already contains some ebooks (the container runs on the same machine running Nextcloud). I gave the container running Calibre web access to the directory using a Docker volume, and I made sure to make the database readable and writable by the container by setting its permissions to 666. After logging in and setting the DB location, I clicked on "books" on the left menu and the application crashed.

**To Reproduce**
1. Login with default admin credentials
2. Specify the location of the DB provided in the readme
3. Save the settings
4. Click on "books" in the menu on the left
5. Application crashes
6. Logging in again, I immediatly get an error after login

**Logfile**
See attached file.
[calibre-web.log](https://github.com/janeczku/calibre-web/files/11061504/calibre-web.log)

**Expected behavior**
An empty library shows up

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.6 LTS
 - Python version: I think Python 3.10
 - Calibre-Web version: v6.14.1
 - Docker container: LinuxServer
 - Special Hardware: not applicable
 - Browser: Firefox 111.0.1 (64 bit)

**Additional context**
access via Apache2 as a reverse proxy.

**Comment by OzzieIsaacs** [comment]
`AttributeError: 'NoneType' object has no attribute 'query'`
This is the usual docker database permission error. Please ask for help at the repository of the docker provider.

**Comment by GTP95** [comment]
Turned out that this wasn't a permissions issue, just that I wasn't downloading the database correctly (I had to use the "raw" link since I was using wget, that is https://github.com/janeczku/calibre-web/raw/master/library/metadata.db). Now it works.
