### ISSUE TITLE
Problem running 0.6.20 due to flask and werkzeug conflicts

### ISSUE THREAD

**Issue by Caligatio** [janeczku/calibre-web#2730]
**Describe the bug/problem**
I attempted a clean install of calibre-web using pip into a new virtualenv to upgrade to 0.6.20. I received the following error when I run CPS:

```bash
TypeError: __init__() got an unexpected keyword argument 'unbound_message'
```

It appears this is a problem with the version combination of flask and werkzeug: https://bobbyhadz.com/blog/python-typeerror-init-got-an-unexpected-keyword-argument-unbound-message

Downgrading flask to v2.1.3 fixes the issue.

**To Reproduce**
1. Create a new virtualenv
2. Do a `pip install calibreweb`
3. Do a `pip install -r optional-requirements.txt`

**Logfile**
```bash
$ /opt/calibre-web/venv/bin/cps
Traceback (most recent call last):
  File "/opt/calibre-web/venv/bin/cps", line 5, in <module>
    from calibreweb import main
  File "/opt/calibre-web/venv/lib/python3.8/site-packages/calibreweb/__init__.py", line 28, in <module>
    from cps.main import main
  File "/opt/calibre-web/venv/lib/python3.8/site-packages/calibreweb/cps/__init__.py", line 28, in <module>
    from flask import Flask
  File "/opt/calibre-web/venv/lib/python3.8/site-packages/flask/__init__.py", line 4, in <module>
    from . import json as json
  File "/opt/calibre-web/venv/lib/python3.8/site-packages/flask/json/__init__.py", line 8, in <module>
    from ..globals import current_app
  File "/opt/calibre-web/venv/lib/python3.8/site-packages/flask/globals.py", line 56, in <module>
    app_ctx: "AppContext" = LocalProxy(  # type: ignore[assignment]
TypeError: __init__() got an unexpected keyword argument 'unbound_message'
```

**Expected behavior**
CPS to run

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.6
 - Python version: 3.8.10 (stock Ubuntu)
 - Calibre-Web version: 0.6.20
 - Docker container: None
 - Special Hardware: None
 - Browser: N/A

**Additional context**
N/A

**Comment by m4hi2** [comment]
Run 
```
pip install --upgrade pip
pip install calibreweb
```

**Comment by Caligatio** [comment]
Dependency resolution is a hard problem and, per @m4hi2, it looks like newer versions of `pip` may handle it slightly better. That being said, `calibre-web`'s requirements.txt can be easily tweaked/fixed to make this a non-issue.

The problem:
`calibre-web` has the following two dependencies:
Flask>=1.0.2,<2.3.0
werkzeug<2.1.0

`Flask` >= v2.2 requires `werkzeug` >= 2.2 (I have no idea if the two projects link their version numbers?). The pinned version of `werkzeug` therefore defacto limits `Flask` to < 2.2. I suspect the newer version of `pip` figures this out but `calibre-web` can also easily fix this by tweaking the `Flask` dependency to < 2.2.

**Comment by OzzieIsaacs** [comment]
There was a time where Werkzeug was to new to handle the newest flask version, so Inimserted the Werkzeug line. Removing the Werkzeug requirement will also solve the problem

**Comment by Morglaf** [comment]
Hello, I am on swizzin and I can't get calibre-web to work... My error looks like yours... but even though I forced the installation of FLASK it doesn't change anything... I'm a beginner so I may have (probably) missed something...


Environment :

    OS: Ubuntu 20.04.6 LTS
    Python version:  3.8.10
    Calibre-Web version: 0.6.20
    Flask : 2.1.3
    Werkzeug : 2.0.3

```
admin@********:/opt/calibreweb$ sudo systemctl status calibreweb
● calibreweb.service - calibreweb
     Loaded: loaded (/etc/systemd/system/calibreweb.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2023-05-01 18:06:01 UTC; 4s ago
    Process: 26473 ExecStart=/opt/.venv/calibreweb/bin/python3 /opt/calibreweb/cps.py -i 127.0.0.1 (code=exited, status=1/FAILURE)
   Main PID: 26473 (code=exited, status=1/FAILURE)

May 01 18:06:01 ******** python3[26473]:     from flask import Flask
May 01 18:06:01 ******** python3[26473]:   File "/opt/.venv/calibreweb/lib/python3.8/site-packages/flask/__init__.py", line 4, in <module>
May 01 18:06:01 ******** python3[26473]:     from . import json as json
May 01 18:06:01 ******** python3[26473]:   File "/opt/.venv/calibreweb/lib/python3.8/site-packages/flask/json/__init__.py", line 8, in <module>
May 01 18:06:01 ******** python3[26473]:     from ..globals import current_app
May 01 18:06:01 ******** python3[26473]:   File "/opt/.venv/calibreweb/lib/python3.8/site-packages/flask/globals.py", line 56, in <module>
May 01 18:06:01 ******** python3[26473]:     app_ctx: "AppContext" = LocalProxy(  # type: ignore[assignment]
May 01 18:06:01 ******** python3[26473]: TypeError: __init__() got an unexpected keyword argument 'unbound_message'
May 01 18:06:01 ******** systemd[1]: calibreweb.service: Main process exited, code=exited, status=1/FAILURE
May 01 18:06:01 ******** systemd[1]: calibreweb.service: Failed with result 'exit-code'.
```

**Comment by OzzieIsaacs** [comment]
@Morglaf: Google thinks your flask version is to new for your interpreter: https://stackoverflow.com/questions/73337927/typeerror-init-got-an-unexpected-keyword-argument-unbound-message
Try: `/opt/.venv/calibreweb/bin/python3 -m pip install --upgrade --force-reinstall flask==2.1.3`

**Comment by Morglaf** [comment]
it is working ! Thx soo much !
