### ISSUE TITLE
'NoneType' object has no attribute 'author_sort'

### ISSUE THREAD

**Issue by kkoshelev** [janeczku/calibre-web#2733]
**Describe the bug/problem**
While trying to open djvu reader (https://books.example.com/read/9/djvu) server shows 500 internal error.

**To Reproduce**
1. Click on "Read in Browser - djvu" pointing to https://books.example.com/read/9/djvu
2. See error

**Logfile**
```
[2023-03-29 09:08:20,655] ERROR {cps:1449} Exception on /read/9/djvu [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/calibre-web/cps/usermanagement.py", line 34, in decorated_view
    return func(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 132, in inner
    return f(*args, **kwargs)
  File "/app/calibre-web/cps/web.py", line 1519, in read_book
    book.ordered_authors = calibre_db.order_authors([book], False)
  File "/app/calibre-web/cps/db.py", line 840, in order_authors
    sort_authors = entry.author_sort.split('&')
AttributeError: 'NoneType' object has no attribute 'author_sort'
[2023-03-29 09:08:28,894] DEBUG {cps.updater:329} Stable version: {'version': '0.6.20'}
```

**Expected behavior**
Expected to see the book reader

**Environment (please complete the following information):**
 - OS: unraid
 - Calibre-Web version: 0.6.20
 - Docker container: LinuxServer (lscr.io/linuxserver/calibre-web)
 - Browser: Chrome 111.0.5563.111

**Additional context**
Nginx reverse proxy

**Note**
Removing app.db (and reconnecting to calibre database again) makes the problem no longer reproducible, however it also removes all library setting, users, etc. It cannot be considered a workaround. I need some kind of instructions to clean up the corrupted database.

**Comment by OzzieIsaacs** [comment]
The error has nothing to do with the app.db file, but with metadata.db. A restart of calibre-web could have helped. A repair database executed in calibre itself also could have solved the problem.

**Comment by OzzieIsaacs** [comment]
The error occurs if you try to read a book with a not existing database entry. I'll fix it

**Comment by kkoshelev** [comment]
I have to respectfully disagree with your assessment. The book is there and calibre database is also valid.

I looked at the code, the problem seems to be with the language filter, [link](https://github.com/janeczku/calibre-web/blob/13c0d30a8fb734c544b8de77b36527118ada880d/cps/db.py#L711). This book is in Russian language and the default user setting is English and "Language of Books" has "Show All", the ap.db doesn't seem to have that set. So filter works incorrectly and get_filtered_book() returns nothing.

Neither the less, the error message should be more descriptive. "Selected book is unavailable. File does not exist or is not accessible" maybe should also include "language" to hit the user that filtering rules are set.
