### ISSUE TITLE
Search for book throws a 4xx error if page was opened a while ago.

### ISSUE THREAD

**Issue by mawise** [janeczku/calibre-web#2741]
**Describe the bug/problem**
I keep my Calibre-web tab open perpetually.  If I switch to the tab after it has been open for a while and search for a book with the search box, Calibre-web returns an error page.  If I then go home and search again it works fine.

**To Reproduce**
1. Open Calibre-web in a browser
2. Wait 24 hours (probably less is sufficient, I haven't narrowed down the timeout)
3. Search for a book
4. Observe error.

**Logfile**
I can get you a logfile if you really need.  I've noticed that my search query is not in the URL as a query parameter, so presumably search is implemented as a POST with a CSRF (or similar) token that is generated on page load but has expired.  I don't think we need CSRF protections against simple searches (and I think it would be a feature to be able to share with one of my users a URL for a search I've performed).

**Expected behavior**
The search returns results for the search instead of an error page.

**Screenshots**
Again, happy to provide a screenshot if you need it.

**Environment (please complete the following information):**

Calibre Web | 0.6.20 
Python 3.10.6 
Linux 5.14.0-283.el9.x86_64 #1 SMP PREEMPT_DYNAMIC 

 - OS: [e.g. Windows 10/Raspberry Pi OS]
 - Python version: [e.g. python2.7]
 - Calibre-Web version: [e.g. 0.6.8 or 087c4c59 (git rev-parse --short HEAD)]:
 - Docker container: [None/LinuxServer]:
 - Special Hardware: [e.g. Rasperry Pi Zero]
 - Browser: [e.g. Chrome 83.0.4103.97, Safari 13.3.7, Firefox 68.0.1 ESR]

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

**Comment by OzzieIsaacs** [comment]
I recently changed it to a post request as someone claimed it didn‘t work in a special application, I can revert the change
