### ISSUE TITLE
Advanced Search on Single Tag not returning all results

### ISSUE THREAD

**Issue by kgladfelder** [janeczku/calibre-web#2743]
**Describe the bug/problem**
When searching for a single tag (example: "Fantasy") using advanced search, about 2/3 of the actual books with the tag are returned.

**To Reproduce**
1. Go to 'Catagories'

![image](https://user-images.githubusercontent.com/39464447/230799581-bd2c3ba4-781e-4ffa-ba34-4b32a707bf79.png)

2. Click on 'Advanced Search'
3. Enter same tag in the Tags selection box 

![image](https://user-images.githubusercontent.com/39464447/230799611-4f69f653-619f-411b-991a-3c54cf08c17c.png)

4. Click on 'Search'
5. Number of books returned doesn't match counts for the Category tag.

![image](https://user-images.githubusercontent.com/39464447/230799653-2caf6ebb-fc91-4217-a1d5-f86846c47442.png)

**Expected behavior**
Same number of books are returned when searching from "Categories" or "Advanced Search"

**Environment (please complete the following information):**
 - OS: Debian
 - Python version: 3.10.6
 - Calibre-Web version: 0.6.20 - 1451a67912a41a4811dcd425abc49bc49becb711 - 2023-03-27T19:49:57+02:00
 - Docker container: lscr.io/linuxserver/calibre-web:latest [0.6.20-ls204](https://github.com/linuxserver/docker-calibre-web/releases/tag/0.6.20-ls204)
 - Special Hardware: n/a
 - Browser: Vivaldi 5.7.2921.65 (Stable channel) (64-bit)

**Comment by OzzieIsaacs** [comment]
I guess you have applied some visibility restrictions (language, limit by tags or custom column) this could explain the advanced search result, which would mean the number of books in the categories section isn't correct

**Comment by OzzieIsaacs** [comment]
Okay I can reproduce it. It has nothing to do with my idea in the last topic

**Comment by OzzieIsaacs** [comment]
It has to do with the read status. Read books are not returned by the advanced search in this case. (My config uses a linked calibre database)

**Comment by OzzieIsaacs** [comment]
I understood it. It's exactly doing what we told it. But it's indeed somewhat unexpected. All field are "and" combined, meaning it's searching for title and author and "read status". The read status is set to empty by default, meaning it's responding with all books having the read status not set! We are missing the choice "any" for the read status.

**Comment by OzzieIsaacs** [comment]
Please update to the newest nightly commit, you should then get all results as you (and I) expect it

**Comment by kgladfelder** [comment]
Thanks for looking into it. Everything appears to be working how I'd expect it as well.
