### ISSUE TITLE
Changed port (to 80); Won't restart

### ISSUE THREAD

**Issue by philnewman** [janeczku/calibre-web#2745]
I'm running on a Raspberry Pi 4B+. I (stupidly) attempted to change the port to port 80. Now when I attempt to start the server, I get the error message: `Error starting server: [Errno 13] Permission denied: ('',80)`

I ensured nothing was running on port 80 (I shutdown nginx). I attempted to manually change the item in constants.py file, without any success.  Any advice or next steps I can try?

**Comment by Harrenkyym** [comment]
I did the same (stupid) thing. More or less. From the settings tab, in Calibre Web, I changed the port 8083 to 80. 502 Bad Gateway.

How do I solve it?

I've tried to edit the app.db file, columns config_port and config_external_port to 8083, but I sitll have the 502 Bad Gateway problem... :(
