### ISSUE TITLE
Allow series id to reflect multiple books within single file

### ISSUE THREAD

**Issue by bstnwlf** [janeczku/calibre-web#2753]
Hello,
couldn't find a similar feature request. If this already has been requested I apologize:

**_Is your feature request related to a problem? Please describe._**
Some eBooks get sold as multi-volume-package (for example https://www.amazon.com/Lord-Rings-One-J-R-R-Tolkien-ebook/dp/B007978OY6).
Currently, series id is not able to properly reflect this.

**_Describe the solution you'd like / Describe alternatives you've considered_**
A solution could be implemented in several ways:
- the edit field could take comma/semicolon-separated values
- there could be a "multi-volume" checkbox switching between single number and multiple numbers (see above)
- multiple entries (same as with ids above)

This could make multi-volume-series split over several book-files easier to tag.

Kind regards,
bstnwlf

**Comment by OzzieIsaacs** [comment]
My target is to stay as close as possible to the Calibre Database format. The Calibre format does not allow to have more than one series id applied to a book. The solution I can imagine is to use a "multi-volume" custom column value
