### ISSUE TITLE
Home button in caliBlur! Theme always links to "/", even with reverse proxy prefix.

### ISSUE THREAD

**Issue by oh-ok** [janeczku/calibre-web#2756]
**Describe the bug/problem**
When using a reverse proxy that adds a url prefix to calibre-web's root, e.g. "http://example.com/calibre", the Home button in the caliBlur! theme will always link to the URL's absolute root i.e. "http://example.com/" instead of the calibre-web index page (as with the standard theme).

**To Reproduce**
1. Have a reverse proxy set-up as per the instructions in the Wiki. (I use nginx)
2. Go to Settings -> Edit UI Configuration -> View Configuration -> Theme -> (Select) caliBlur! Theme.
3. Click "Save".
4. Click the Home icon.
5. You'll find yourself at "/", which is not the calibre-web index.

**Expected behavior**
Be taken to the calibre-web index page.

**Environment (please complete the following information):**
 - OS: Windows 11
 - Python version: python3.10
 - Calibre-Web version: c2155b82
 - Docker container: None
 - Special Hardware: None
 - Browser: Chrome Version 112.0.5615.50; Firefox 112.0

**Additional context**
Access via a reverse proxy with a URL prefix.

**Comment by oh-ok** [comment]
Looking at the code I realised this is intended behaviour, as clicking on the server name brings you to the index. It just wasn't initially intuitive to me.

**Comment by OzzieIsaacs** [comment]
In the standard theme it behaves like you expect it. And I think this is as it should behave
