### ISSUE TITLE
building error - netifaces, Microsoft Visual C++ 14.0 or greater is required

### ISSUE THREAD

**Issue by lionhoho** [janeczku/calibre-web#2759]
Hello, I'm trying to fresh install the calibre-web via pip and a similar issue with Issue #2394  happened. I got Python 3.11.3 on Win2012.

screen shows
```
Collecting wrapt<2,>=1.10 (from deprecated>=1.2->limits>=2.8->Flask-Limiter<3.4.0,>=2.3.0->calibreweb)
  Using cached wrapt-1.15.0-cp311-cp311-win_amd64.whl (36 kB)
Collecting mdurl~=0.1 (from markdown-it-py<3.0.0,>=2.2.0->rich<14,>=12->Flask-Limiter<3.4.0,>=2.3.0->calibreweb)
  Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Collecting pycparser (from cffi>=1.12->cryptography<41,>=38.0.0->pyopenssl->advocate<1.1.0,>=1.0.0->calibreweb)
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Building wheels for collected packages: netifaces
  Building wheel for netifaces (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      D:\calibre-web\venv\Lib\site-packages\setuptools\config\setupcfg.py:516: SetuptoolsDeprecationWarning: The license_file parameter is deprecated,
 use license_files instead.
        warnings.warn(msg, warning_class)
      running bdist_wheel
      running build
      running build_ext
      building 'netifaces' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-
build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for netifaces
  Running setup.py clean for netifaces
Failed to build netifaces
ERROR: Could not build wheels for netifaces, which is required to install pyproject.toml-based projects
```

I tried to find the whl file from https://www.lfd.uci.edu/~gohlke/pythonlibs/#netifaces but there is no cp311 for netifaces
My question is do I have to install Microsoft C++ Build Tools 14.0 or above? I've run out of the space for the system disk and these are already installed

Microsoft Visual C+ + 2008 Redistributable - x64 9.0.21022
Microsoft Visual C++ 2015-2019 Redistributable (x86) - 14.29.30139
Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.32.31332
Microsoft Visual Studio Code

Thanks

**Comment by OzzieIsaacs** [comment]
I'm aware of this topic. There is no netiface prebuild for python3.11 available, as I know. Maybe it's possible to install it via python3.10 and then upgrade to python 3.11. There was a similar request regarding this topic for lxml, I try to find it and check if I can give additional hints. I try to do this this evening

**Comment by OzzieIsaacs** [comment]
I doublechecked it. I installed python 3.10. created a folder to install calibre-web (e.g. c:\cw), created a virtual enviroment in:
`cd c:\cw`
`c:\python310\python.exe -m venv venv`
Installed netifaces in the virtual enviroment:
`c:\cw\Scripts\python.exe -m pip install netifaces`
Installed python3.11, updated the virtual enviromnent:
`c:\python311\python.exe -m venv venv`
And installed calibre-web in the virtual enrionment:
`c:\cw\Scripts\python.exe -m pip install calibreweb`
Installation worked without problems and I could also start calibre-web without any issue:
![grafik](https://user-images.githubusercontent.com/6438895/233850971-e3578b4d-d572-481c-a186-aa5d8f2f15ee.png)

**Comment by lionhoho** [comment]
Thank you for the help. I tried different version but no luck

This is 3.10.11
![image](https://user-images.githubusercontent.com/2055025/233853090-180c3a19-4cfd-4c3e-a1be-ed092cbf22b9.png)

This is 3.10.0
![image](https://user-images.githubusercontent.com/2055025/233853544-80b7f34f-3e32-4bd1-9791-492a572c1c7a.png)

and finally I installed 3.9.13 and installed the whl file from https://www.lfd.uci.edu/~gohlke/pythonlibs/#netifaces
then it works great!
![image](https://user-images.githubusercontent.com/2055025/233857565-669c2ebb-cd10-4bd3-8ae6-ab11d3edd474.png)

Thanks for the idea of changing the python version.
