### ISSUE TITLE
reverse proxy

### ISSUE THREAD

**Issue by jiangjiangflies** [janeczku/calibre-web#276]
Hi, I'm planning to use a domain via reverse proxy to avoid visiting `http://ip:port` which is not good-looking.  I can visit my calibre-web via domain name but it seems css/js files can't be loaded. I'm new to nginx reverse proxy. How should I solve this problem?
Here is my vhost config file:
```
server
    {
        listen 80;
        #listen [::]:80;
        server_name www.ebook.itengli.com ebook.itengli.com;
        index index.html index.htm index.php default.html default.htm default.php;
        root  /home/wwwroot/www.ebook.itengli.com;

        location / {
        proxy_pass          http://128.xxx.xxx.xx:8083;
        proxy_redirect      off;
        proxy_set_header    X-Real-IP       $remote_addr;
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        include other.conf;
        #error_page   404   /404.html;

        # Deny access to PHP files in specific directory
        #location ~ /(wp-content|uploads|wp-includes|images)/.*\.php$ { deny all; }

        include enable-php.conf;

        location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
        {
            expires      30d;
        }

        location ~ .*\.(js|css)?$
        {
            expires      12h;
        }
               location ~ /.well-known {
            allow all;
        }

        location ~ /\.
        {
            deny all;
        }

        access_log off;
    }
```

**Comment by OzzieIsaacs** [comment]
Please try exampleconfiguration from readme. 
Are you using the Docker container, this generated problems in the past?

**Comment by jiangjiangflies** [comment]
Actually, I don't understand example config. I'm not using docker either. I just use `python cps.py ` command and keeping it running.

**Comment by jkrehm** [comment]
@jiangjiangflies, the `location ~ .*\.(js|css)?$` doesn't proxy the request to Calibre. Potentially the issue?

**Comment by jiangjiangflies** [comment]
Probably. But where is the css/js file located? I think the problem is the path.

**Comment by jkrehm** [comment]
They're located in `cps/static`, served up by cps.py. If you comment out that location block, they ought to "just work". Or add the proxy statements to the js|css location. But I'd start by commenting out the block to see if it works.

**Comment by jiangjiangflies** [comment]
Great! I commented out that few lines and it works now!

**Comment by jiangjiangflies** [comment]
I just found another problem, not related this one. When I updated calibre-web, I can't browse it anonymously. 
`AttributeError: 'Anonymous' object has no attribute 'mature_content'`

**Comment by jiangjiangflies** [comment]
When you select `Enable anonymous browsing` in DB configuration and then log out to browse anonymously, you will get an internal server error.

**Comment by jkrehm** [comment]
Usually better to open a separate issue when the issues aren't related. The anonymous browsing issue will be resolved when #278 is merged. If you want to fix it immediately, you can cherry-pick the commit into your copy of the repository.

**Comment by jiangjiangflies** [comment]
Thank you so much.  It works perfectly now. You have fully resolved these issues. Really great! And I will open a new thread if it's a different issue.

**Comment by OzzieIsaacs** [comment]
merged
