### ISSUE TITLE
Windows - python still required for setup?

### ISSUE THREAD

**Issue by jungle-boogie** [janeczku/calibre-web#2761]
Hello,

I've installed Calibre-Web-06-20-Setup.exe and copied my calibre metadata.db file into `C:\Calibre-Web`.

I'm able to login to `calibre-web` and see the titles of my books, but the cover art is missing and I cannot download any of the files.

Do I need to copy my calibre library into `C:\Calibre-Web`? Is there a configuration file to tell Calibre-Web where to look for the books?

Thanks!

**Comment by jungle-boogie** [comment]
So I don't believe python is required to run `calibre-web`, since you can run the binary `calibreweb.exe`.

I think this page can be updated, but I'll wait until I know more about this project:
https://github.com/janeczku/calibre-web/wiki/Windows-Installation

**Comment by OzzieIsaacs** [comment]
The wiki page is wrong. Some time again somebody added the download block linked a malware into it. I just removed the malware, but the link is wrong

**Comment by jungle-boogie** [comment]
Okay, so python isn't needed.

What about a better way to keep the directories organized in the `calibre-web` directory?

**Comment by OzzieIsaacs** [comment]
> .. copied my calibre metadata.db file into C:\Calibre-Web.

Don't do this as stated in the readme.

>  calibre-web and see the titles of my books, but the cover art is missing and I cannot download any of the files.

Yes, calibre-web is using the calibre database and also the calibre database structure, so all the files and folders. Calibre doesn't support splitting the database and the folder structure

> However, I'm wondering if there's a way to have a relative path to the books so that the calibre-web directory isn't filled will all the authors. Something like C:\Calibre-Web\books and inside books, would be all the directories.

Just enter `C:\Users\jungle\Calibre Library` as your Calibre databse path in the database config path.

**Comment by jungle-boogie** [comment]
Oh my goodness! I was an idiot!

I had assumed `calibre-web` was chrooted to `C:\Calibre-Web` and couldn't navigate out of that directory. Of course I can, and I can tell it where the database is.

thanks so much for your help!
