### ISSUE TITLE
Feature: Ability for admin to post "message of the day" type notifications

### ISSUE THREAD

**Issue by Andrew-H2O** [janeczku/calibre-web#2764]
**Is your feature request related to a problem? Please describe.**
I have a number of users with access to my ebook library.  As the admin, I would like the ability to post a message for them to see when logged in, for example to warn of upcoming downtime / changes, etc. 

**Describe the solution you'd like**
1. For more persistent messages, the option to place a one-line banner at the top of the page.  Something similar to the short-lived acknowledgement of certain tasks (like adding an ebook or sending it to e-reader).  These messages could have the option for the user to close them when read.
2. The possibility to set a 'display at next login' popup message that would be displayed to each user once, with the option to close.

**Describe alternatives you've considered**
I can use email, manually extracting each user's email address from the user list, but this is cumbersome and potentially prone to failure.

**Additional context**
Mock-up of banner display
![banner](https://user-images.githubusercontent.com/20803916/233641114-02d32811-a25d-443d-b296-fc41da7f295f.png)

Mock-up of admin options
![config](https://user-images.githubusercontent.com/20803916/233641142-2a10f830-da2d-4391-a1d5-275da266c16b.png)

**Comment by OzzieIsaacs** [comment]
Similar functions had been requested several times in the past: #992, #1587. 
I'd like to stick to my opinion to not implement it

**Comment by ste7enm** [comment]
![Arms_of_an_angel](https://github.com/user-attachments/assets/8faa9aae-ee74-4b39-9d5c-d389df26910e)
🥲
