### ISSUE TITLE
After the azw3 and mobi format e-books are uploaded to calibre-web, the metadata is lost

### ISSUE THREAD

**Issue by Nothend** [janeczku/calibre-web#2766]
**Describe the bug/problem**

First, in the PC version of caliber, the azw3 and mobi format e-books can display metadata normally, and the metadata can be displayed normally when saving to the hard disk or converting the format  , but once uploaded to calibre-web, the metadata is lost, including cover, publisher, label .  But when uploading an e-book in epub format, the metadata in the calibre-web is complete. I don't know if it is a problem with my settings, or is there a bug in the software itself? 

 The second problem : I converted the epub format to mobi or azw3 format through caliber-web's own converter, and downloaded these converted formats to the local PC, which can display normal metadata.  But if you download the converted e-book in mobi or azw3 format with the browser in kindle, the cover cannot be displayed in kindle.  Can someone help me?  very grateful, thank you very much，the related issue is #1271 

To Reproduce

1. Go to kindle browser
2. Click on the download button
3. can't display the correct cover 

 - OS: [docker in synology]
 - Python version: [3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]]
 - Calibre-Web version: [0.6.20 - 1451a67912a41a4811dcd425abc49bc49becb711 - 2023-03-27T19:49:57+02:00]:
 - Docker container: [docker in synology]:
 - Special Hardware: [x86]
 - Browser: [112.0.5615.121 (正式版本) （64 位）]

**Comment by OzzieIsaacs** [comment]
> [..] uploaded to calibre-web, the metadata is lost, including cover, publisher, label .

Calibre-web doesn't support metadata extraction from azw3 files. The metadata isn't lost, it's just not extracted.

**Comment by OzzieIsaacs** [comment]
For the 2nd half the question regarding the covers, this should be tracked in #1271

**Comment by Nothend** [comment]
> For the 2nd half the question regarding the covers, this should be tracked in #1271

Thanks a lot，Hope this issue will be resolved soon
