### ISSUE TITLE
Bind to specific IP address?

### ISSUE THREAD

**Issue by jungle-boogie** [janeczku/calibre-web#2771]
Hello,

With 0.6.20, I don't see a way to bind `calibre-web` to a specific IP address? Am I missing a setting for this?
I think it would be really helpful to bind to a specific IP address on a host.

Thanks!

**Comment by OzzieIsaacs** [comment]
Please use the -I commandline option: https://github.com/janeczku/calibre-web/wiki/Command-Line-Interface#command-line-options
