### ISSUE TITLE
X-CSRFToken is 'undefined' - user cannot send ebook to ereader

### ISSUE THREAD

**Issue by mpatton125** [janeczku/calibre-web#2774]
**Describe the bug/problem**
Some users (the one in question is a newly created user today) are unable to click the "Send Epub to eReader" button successfully.  The button clicks but there is no result (no change on screen).

Calibre-Web logs show:
INFO {flask_wtf.csrf:263} The CSRF token is invalid.

Checking developer console for the affected user, I can see the hidden 'csrf' field has a value, however the POST to 'send' shows:
"X-CSRFToken | undefined".

**To Reproduce**
1. Go to a book
2. Click on send ebook to ereader

However this doesn't appear to happen for all users.  My two users are working fine, but this newly created user has the problem.
Tried restarting Calibre-Web, logging in from private tab etc.  No change.

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

**Expected behavior**
Output on screen to show the send task was created and the book to be sent.

**Environment (please complete the following information):**
 - OS: Linux/Docker
 - Calibre-Web version: 0.6.21 Beta - fe4dc1bb8f63bb6e9fc0547fcee8e0bf5ee68cbc - 2023-04-22T09:25:54+02:00
 - Docker container: LinuxServer
 - Browser: Tried a few - Chrome, Firefox and Safari.

**Additional context**
Haven't encountered the problem prior to creating this new user today.  Haven't had any negative feedback from other users.

**Comment by JeepXJman** [comment]
I am having the same issue, however with all of my users.  Any update on a fix?

**Comment by OzzieIsaacs** [comment]
For me it's working. Do you use the Caliblur! theme?

**Comment by mpatton125** [comment]
No, I'm using the "Standard theme".

**Comment by mpatton125** [comment]
This is the access log for when an affected user clicks the "Send ePub to eReader" button.

`{
	"level": "error",
	"ts": 1685498076.6137397,
	"logger": "http.log.access.log5",
	"msg": "handled request",
	"request": {
		"remote_ip": "54.240.193.3",
		"remote_port": "8067",
		"proto": "HTTP/2.0",
		"method": "POST",
		"host": "calibre-web.nine-hells.net",
		"uri": "/send/571484/Epub/0",
		"headers": {
			"X-Requested-With": ["XMLHttpRequest"],
			"Origin": ["https://calibre-web.nine-hells.net"],
			"Referer": ["https://calibre-web.nine-hells.net/"],
			"Cookie": [],
			"Content-Length": ["0"],
			"User-Agent": ["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0"],
			"Sec-Fetch-Dest": ["empty"],
			"Sec-Fetch-Mode": ["cors"],
			"Sec-Fetch-Site": ["same-origin"],
			"Te": ["trailers"],
			"Accept": ["*/*"],
			"Accept-Encoding": ["gzip, deflate, br"],
			"Accept-Language": ["en-US,en;q=0.5"],
			"X-Csrftoken": ["undefined"]
		},
		"tls": {
			"resumed": false,
			"version": 772,
			"cipher_suite": 4865,
			"proto": "h2",
			"server_name": "calibre-web.nine-hells.net"
		}
	},
	"user_id": "",
	"duration": 0.022820497,
	"size": 1193,
	"status": 400,
	"resp_headers": {
		"X-Content-Type-Options": ["nosniff"],
		"Date": ["Wed, 31 May 2023 01:54:36 GMT"],
		"Server": ["Caddy"],
		"Alt-Svc": ["h3=\":443\"; ma=2592000"],
		"Content-Type": ["text/html; charset=utf-8"],
		"Strict-Transport-Security": ["max-age=31536000;"],
		"X-Frame-Options": ["SAMEORIGIN"],
		"X-Xss-Protection": ["1; mode=block"],
		"Vary": ["Cookie"],
		"Content-Length": ["1193"],
		"Content-Security-Policy": ["default-src 'self' calibre-web.nine-hells.net 'unsafe-inline' 'unsafe-eval'; font-src 'self' data:; img-src 'self' data:; object-src 'none';"]
	}
}`

**Comment by halorrr** [comment]
I'm experiencing the same thing for all my users as well, is there any data I can provide that would be helpful in tracking down this issue?

**Comment by halorrr** [comment]
Using the [linuxserver docker images](https://hub.docker.com/r/linuxserver/calibre-web) I can confirm the issue is not present in `0.6.19` or `0.6.20`, it is however present in the `nightly` build.

**Comment by OzzieIsaacs** [comment]
Could you please paste the raw html test of the page you press on the send to email button

**Comment by halorrr** [comment]
Here it is [page.txt](https://github.com/janeczku/calibre-web/files/11918896/page.txt)

**Comment by halorrr** [comment]
I stepped back through the nightly tags one at a time

The last working nightly build is https://github.com/janeczku/calibre-web/commit/13c0d30a8fb734c544b8de77b36527118ada880d

And the first broken nightly build is https://github.com/janeczku/calibre-web/commit/6c6841f8b0e04494b39f4a8e55d0fe2178ef9eb8

So we can narrow down that something in one of these four commits broke it:
- https://github.com/janeczku/calibre-web/commit/6c6841f8b0e04494b39f4a8e55d0fe2178ef9eb8
- https://github.com/janeczku/calibre-web/commit/592216588c4c2e02606e81d93e87579400ed6f2c
- https://github.com/janeczku/calibre-web/commit/f4db0f04d234857f723e6a1e55bcd7eaeb4dce51
- https://github.com/janeczku/calibre-web/commit/b16e3a6e2c271ad67d87ab470fd538ad0bb86a80

**Comment by OzzieIsaacs** [comment]
Please update to the newest nightly version  (same as #2847)

**Comment by halorrr** [comment]
> Please update to the newest nightly version (same as #2847)

Can confirm, updated to the latest nightly and the button is working now.
