### ISSUE TITLE
Way to click and fullscreen images in books?

### ISSUE THREAD

**Issue by Jorsher** [janeczku/calibre-web#2777]
It's possible there's already a way and I just don't know it.

I read a lot of educational books with embedded images/diagrams. On the Kindle I could click an image and it would zoom to fill the screen. Would be great if the web-reader did the same.

In the meantime, will just zoom the page in and out :) Thanks

**Comment by OzzieIsaacs** [comment]
The underlying JavaScript ePub reader isn‘t capable of doing this, and it seems it‘s development stalled, so there is no way of providong this function
