### ISSUE TITLE
Email as alternative of username for login

### ISSUE THREAD

**Issue by jeremitu** [janeczku/calibre-web#2780]
I see many of my users trying to log-in with an e-mail. For many web services username == mail address.

Is something along the lines of
```
username = form.get('username', "").strip().lower()
user = ub.session.query(ub.User).filter(func.lower(ub.User.name) == username or func.lower(ub.User.email) == username).first()
```
in web.py/login_post.py feasible? E-mails are unique in user DB.

**Comment by OzzieIsaacs** [comment]
If you name your users with thie email adress, they can use the email address a username. I prefer to have only one username for login. Your patch looks feasible, but I will not merge it
