### ISSUE TITLE
Hypothesis.js integration for Epub.js reader

### ISSUE THREAD

**Issue by intothebeans** [janeczku/calibre-web#2781]
**Is your feature request related to a problem? Please describe.**
Hypothes.is easily works with PDFs displayed from the server, which is great, but I haven't been able to get it to work with the epub viewer. I know it is possible to insert hypothesis into epub.js rendered pages, but I don't have the knowledge to do it. 

**Describe the solution you'd like**
Integrate hypothesis.js into the epub viewer to allow for annotations. 

**Describe alternatives you've considered**
I've attempted modifying the code myself on a test instance, but I was unable to get it to function properly. Someone with more expertise would be better at handling the integration.

**Comment by OzzieIsaacs** [comment]
The epub reader script is not developed any more by it's maintainer, so I will not spend any time in extending it's feature. There was a issue regarding this in the past: https://github.com/janeczku/calibre-web/issues/918, I don't know if this helps or not (haven't read it again today)

**Comment by minh-p** [comment]
Hello, for anybody interested: I managed to integrate it:

https://github.com/janeczku/calibre-web/commit/1fdc7cabc06222ad03551c4df4c9528ff4c1d2b4

As well, here's my fork if you're too lazy: https://github.com/minh-p/calibre-web.

I also disabled swiping for mobile (check my first few commits in the fork). It made it possible to highlight and annotate text without switching the page.

![image](https://github.com/user-attachments/assets/8dd0efbe-9509-4031-88d4-dfcda16e1326)
![image](https://github.com/user-attachments/assets/3f2c579b-8efd-4426-9771-2a0869e3538f)
