### ISSUE TITLE
No Thumbnail, logged out and Error 400 - Bad Request

### ISSUE THREAD

**Issue by Thomas1005** [janeczku/calibre-web#2782]
Hello,
have the newest update, but from time to time have no Thumbnail of the books and then will log me out, following with a "Bad Request". It works with Chrome without any problems, only at Safari this issue.
Any Help ?

**Comment by wireframed** [comment]
I am also experiencing issues with a 400 error when browsing books after updating to latest release. 

I run Calibre-Web in docker with an nginx reverse proxy in front. Things worked perfectly on previous version (6.19?)

**Comment by jvanderzande** [comment]
> Hello, have the newest update, but from time to time have no Thumbnail of the books and then will log me out, following with a "Bad Request". It works with Chrome without any problems, only at Safari this issue. Any Help ?

I see the same on my Ipad: Safari regularly opens a page with the thumbs being shown as broken links and after that I need to login again. Chrome works perfectly.

**Comment by scarpentier** [comment]
I had a similar issue that I was able to fix by disabling the "Strong session protection" introduced recently. This is set in the UI (admin -> basic configuration -> security settings) so I had to connect directly Calibre, bypassing the reverse proxy.

Hope this helps!

**Comment by OzzieIsaacs** [comment]
Please try to update to the newest nightly version, it should now work better (maybe)
