### ISSUE TITLE
Incorrect tag editing with non ASCII letters

### ISSUE THREAD

**Issue by KateGorina** [janeczku/calibre-web#2787]
**Describe the bug/problem**
When editing book metadata, I found a strange behavior of the tag editing field.
I tried to replace a lowercase letter with a uppercase letter but the tag does not change, it was duplicated. Then I tried to delete the extra tag that appeared, the changes were not saved. Clearing the field and saving an empty one helped. Аfter that I added and saved the necessary tags and it worked correctly.

**To Reproduce**
1. Go to the book metadata editing page.
2. Сhange the lowercase letter to the uppercase letter in the tag editing field.
3. Click on "Save".
4. On the book view page the text in the tags does not change, but is appended one more tag.
5. Go to the book metadata editing page again, clearing the field.
6. Click on "Save".
7. Go to the book metadata editing page again and insert tags in the tag editing field.
8. Click on "Save". Now the tags are displayed correctly.

**Expected behavior**
Tags are not duplicated during editing, the changes made in the field are saved.

**Environment:**
 - OS: [Ubuntu 22.04]
 - Python version: [e.g. python 3.10.6]
 - Calibre-Web version: [e.g. 0.6.20]:
 - Browser: [e.g. Chrome 109.0.5414.75]

**Comment by KateGorina** [comment]
I recorded a video too, the bug is playing on it.

https://github.com/janeczku/calibre-web/assets/50075821/7622dcb2-b278-47a0-8d1f-0b7433137b8c

**Comment by OzzieIsaacs** [comment]
So you replaced a russian uppercase letter with a russian lowercase letter, and this is not working, the "normal" ascii letters are working, I have look at it

**Comment by OzzieIsaacs** [comment]
Please update to the newest nightly version, it should now work as expected
