### ISSUE TITLE
log mode override (stdout)

### ISSUE THREAD

**Issue by cyberb** [janeczku/calibre-web#2792]
I am packaging calibre web for Syncloud project, which runs apps under systemd (https://github.com/syncloud/platform) and stdout is a preferred way of logging to not worry about cleaning logs and centralized way of looking at them.
Currently calibre automatically creates a log file and there is no way to to start the app with stdout mode.
There is one env variable (FLASK_DEBUG) which does this but it also enables debug level, it would be very useful to have something explicit (env variable or a command line arg).

**Comment by OzzieIsaacs** [comment]
You can enable logging to stdout by setting the logfile to stdout (this has to be done in the GUI), so it's not 100% what you asked for. I'll have a look at it

**Comment by cyberb** [comment]
yes, I think logging is one the things you want to be able to control before you start the app.
I could probably create a PR if you do not have enough time, if you tell me what would be the preferred way (CALIBRE_LOGGER or a cli arg)

Thanks

**Comment by OzzieIsaacs** [comment]
I have a small patch ready, I need to test it. I hope I can do it over the weekend (I used a command line argument "-o")

**Comment by cyberb** [comment]
So quick thank you very much!

**Comment by OzzieIsaacs** [comment]
The new option "-o" is included in the newest nightly version
