### ISSUE TITLE
Feature Request: Automatic (scheduled?) user import from LDAP

### ISSUE THREAD

**Issue by Hobbabobba** [janeczku/calibre-web#2794]
The manual import from LDAP users works flawless.

After i create a new LDAP user with the role `calibreweb` i need to manualy start the import from LDAP users in the GUI.

I would love to see the option to schedule the task `Import users from LDAP` so it will work automatically every day or every x hours.

**Comment by OzzieIsaacs** [comment]
There is a PR addressing this feature: https://github.com/janeczku/calibre-web/pull/2628
