### ISSUE TITLE
Book details not working under Internet Explorer 11 

### ISSUE THREAD

**Issue by p-rintz** [janeczku/calibre-web#280]
When using the latest Internet Explorer 11, book details will not work like so:

![Image Link](http://i.imgur.com/4ah80dU.png)

Opening in a new tab will work fine, as does most everything else. 

The only other smaller issue is that the main library view will have some layout problems in that whitespaces between books appear.

**Comment by jkrehm** [comment]
A couple things:

1. Could you use the F12 (developer) tools to check if there are JavaScript errors? A lot of the JavaScript currently uses ES6 syntax that is not supported by IE11. #255 will fix that.
2. While in the dev tools, try clearing cache to see if that fixes any issues. #279 will hopefully make that step unnecessary.

**Comment by jkrehm** [comment]
@p-rintz Now that #255 has been merged in, could you re-try in IE 11? I'm pretty sure it will work correctly for you. Do be sure to clear your cache first.

**Comment by p-rintz** [comment]
@jkrehm Hi, sorry for the late message. Both issues indeed seem to have been fixed now.
