### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement calibre-web (from versions: none)

### ISSUE THREAD

**Issue by lonelygoneby** [janeczku/calibre-web#2803]
![image](https://github.com/janeczku/calibre-web/assets/51850317/f46aa4b1-afb9-44bb-a940-c695e1c8961b)
![image](https://github.com/janeczku/calibre-web/assets/51850317/700afb65-0034-40c5-940d-79d2e3ab8967)

**Comment by OzzieIsaacs** [comment]
> Install Calibre-Web via pip: pip install calibreweb (or pip3 depending on your OS/distro)

calibreweb  != calibre-web
