### ISSUE TITLE
[BUG] Search on calibre-web differs in results drastically from Calibre

### ISSUE THREAD

**Issue by kanjieater** [janeczku/calibre-web#2805]
**Is your feature request related to a problem? Please describe.**

Books without covers are missing from calibre-web, only 16 results:
![image](https://github.com/janeczku/calibre-web/assets/32607317/96e9cec6-3ae9-4dff-90d2-fdfcf15d1a1e)

125 results for the same query
![image](https://github.com/janeczku/calibre-web/assets/32607317/715511fb-b97f-4a24-ada7-0f9bdb85f42c)

**Describe the solution you'd like**
Show same search results fro books as they are in Calibre

**Describe alternatives you've considered**
none currently

**Additional context**
none

**Comment by OzzieIsaacs** [comment]
For me it's working:
![image](https://github.com/janeczku/calibre-web/assets/6438895/d32fcc92-1c72-46e3-a745-415e36fe5ee0)
My screenshot looks a bit different, so I guess you are using some old version. In the 2nd screenshot you state that you get with another the same query 125 books, so everything it's working. Please keep in mind that I don't have your database and therefore I can only try to reproduce what you tell me, please generate a simple easy to reproduce scenario tell me all steps and provide also more information. 
With whta I have now I can't help you

**Comment by kanjieater** [comment]
The second screenshot is actually the original calibre. I will try updating though

**Comment by kanjieater** [comment]
I am on the latest version and search continues to only give back limited results. I'm not sure why or what settings to pair down, but if I search on calibre I get very different results than if I search calibre web:
![image](https://github.com/janeczku/calibre-web/assets/32607317/8c198197-1340-469c-a569-77aa6a7939b1)

![image](https://github.com/janeczku/calibre-web/assets/32607317/b206e83e-2834-4479-9d59-71e06c6cb8c2)

**Comment by kanjieater** [comment]
Can we relabel this from question to bug?
![image](https://github.com/janeczku/calibre-web/assets/32607317/58fc0ef0-13a7-4f9f-862a-52e962a34844)
![image](https://github.com/janeczku/calibre-web/assets/32607317/f9dca024-00f6-4afe-bb68-df27f7995ff6)

**Comment by OzzieIsaacs** [comment]
I still don‘t have a simple example showing the problem.

**Comment by kanjieater** [comment]
> I still don‘t have a simple example showing the problem.

Sorry, I missed your request - Yes it's quite easy to reproduce for me. 

Steps:
1. Go here https://www.gutenberg.org/ebooks/71908 
2. Grab the kindle copy. (*.mobi)
3. Load it into Calibre. It looks like this for me (I think it automatically converts from mobi to azw3 for me - not sure if that would have any impact)
![image](https://github.com/janeczku/calibre-web/assets/32607317/912bcac6-42ee-4fb5-b381-7e34b6a9f3a9)
4. Search the authors name in Calibre: "albert"
![image](https://github.com/janeczku/calibre-web/assets/32607317/f6c31b10-f7a7-4ca4-bec9-dde83462131b)
5. Search the same thing in Calibre-Web:
![image](https://github.com/janeczku/calibre-web/assets/32607317/dab14fa9-d477-4245-bb29-e2102c93b713)

**Comment by kanjieater** [comment]
There's no shortage of other easy to find examples.

Text files seem to have serious issues. I loaded in a text file named:
(一般小説) [宮部みゆき] 火車 《山本周五郎賞受賞作》 (青空文庫対応txt 表紙付)(校正20-06-16) 

searched for the title in that 火車, and calibre-web can't find it (and in fact finds something that calibre couldn't, guessing because it was in the description?). Even though 火車 is in the title

**Comment by OzzieIsaacs** [comment]
@kanjieater For me it's working:
Please check that you don't have applied a language visibility restriction or any other restriction based on tags or custom columns.
Additionally if you sort according to book date, the book should be the most recent one and should be visible:

![grafik](https://github.com/janeczku/calibre-web/assets/6438895/4a40694f-659e-41aa-ac6e-46393f71795a)

![grafik](https://github.com/janeczku/calibre-web/assets/6438895/2dc84148-4c32-4c6a-a66d-f6815378c977)

**Comment by OzzieIsaacs** [comment]
@kanjieater . I checked the 2nd example. Also performing the same steps from your post before (Generated a text file with random content, named it (一般小説) [宮部みゆき] 火車 《山本周五郎賞受賞作》 (青空文庫対応txt 表紙付)(校正20-06-16).txt, uploaded it via calibre and searched for 火車 in calibre-web)

![grafik](https://github.com/janeczku/calibre-web/assets/6438895/0d508e81-e2f9-4a77-be7c-aad0406d45b0)

So from my point of view no bug, still a question

**Comment by kanjieater** [comment]
Firstly, thank you for trying my examples - you were right. I had a filter for only Japanese book on & did not realize that Language of Books was actually a filter.

This now allows the 火車 example to show up & the Albert example.
In the 火車 example, I actually get back 2 results in calibre web and only one in calibre. I will track down how to reproduce and post back.

Here's some more weirdness though:
奈須 きのこ won't match 奈須きのこ. So in Calibre it gives back 125 results, but (now that I have the language filter removed) only gives back 117 results in Calibre web. You can test this by naming some books author 奈須 きのこ and some 奈須きのこ and searching. Ideally they'd be the same and normalized, but unfortunately with scrapers this is difficult, and it'd be nice to mirror the base calibre results.

**Comment by kanjieater** [comment]
Also, I am curious if you have any idea why my Calibre-web doesn't cleanly wrap like yours does 
![image](https://github.com/janeczku/calibre-web/assets/32607317/59e36d5f-3a9e-49fb-94ba-8dae7eb3dfdc)

**Comment by OzzieIsaacs** [comment]
You are using the caliblur theme, my examples using the standard theme. There are slightly differences in both tgemes

**Comment by kanjieater** [comment]
Yes, it seems Calibre matches on the comments metadata field too which is why some aren't showing up in my results in the 奈須きのこ example
![image](https://github.com/janeczku/calibre-web/assets/32607317/bc6495c0-70b6-43ca-86c1-71a235af639c)

**Comment by kanjieater** [comment]
Ah maybe Calibre-web does a loose match  on 火車 to get 赤い貨車 since they both end in the same character

**Comment by kanjieater** [comment]
Also, i did switch to the standard theme but have the same issue of text overflow
![image](https://github.com/janeczku/calibre-web/assets/32607317/18325289-a633-4d5d-9adf-fbe5229c4486)

**Comment by kanjieater** [comment]
Maybe this should be a separate issue, but it seems that 
searching by custom columns doesn't work either:

#audiobook:Yes
![image](https://github.com/janeczku/calibre-web/assets/32607317/3676f7a5-63b8-4b7f-9baa-5a367dd69323)
![image](https://github.com/janeczku/calibre-web/assets/32607317/de325f7d-f606-42d8-88e4-25122f22fa1e)

Potentially related to https://github.com/janeczku/calibre-web/issues/1338?
