### ISSUE TITLE
Calibre-web crashes docker

### ISSUE THREAD

**Issue by kevindherdt** [janeczku/calibre-web#2808]
What I use : docker or colima as replacement (tested both)

os : macos ventura

I am having a problem where docker/docker daemon will crash when I am scrolling down fast when browsing my series. It will crash the whole docker and I will have to restart it again. Everything else seems to work ok. 

I have tried checking logs and stuff but I don’t really see anything special. I might search and upload it later on when its weekend since I dont have time now during work.

It is a problem that I can easily reproduce and make a video of as well. 
it also seems to happen on my raspberry pi.

I wonder if it had to do with memory? But docker stats don’t show any abnormal usage.

if there is more things needed please tell me what and how to get it so I can help resolve this issue. 

edit : Seems like I have been able to pinpoint the problems more clearly and I think I solved some issues with calibre crashing docker-desktop/daemon.

I use cloudflare tunnel and on both systems it was when browsing series in calibre the cpu usage would jump 100% the whole time on that docker or  tunnel thru terminal.. it would eventually crash everything. That said calibre-web also would spike and crash. So what I did was limit the cpu usage.

My docker compose looks like this now in case anyone ever has the same problem.
It's running fairly fairly smooth now. I also enabled task schedule to generate book cover in hope it will cache faster next time.

That said, take my feedback with a grain of salt, I am a noob with this and only started using docker like a month ago.

version: "2.1"

services:
  calibre-web:

    image: lscr.io/linuxserver/calibre-web:latest

    container_name: calibre-web

    environment:

      - PUID=1000

      - PGID=1000

      - TZ=Europe/Brussels

      - 'DOCKER_MODS=linuxserver/mods:universal-calibre'

      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional

    hostname: docker-desktop

    deploy:

      resources:
  
        limits:

          cpus: "0.5"

          memory: 4g

    volumes:

      - /Volumes/data/docker/calibre-web/config:/config

      - /Volumes/data/media/library:/books

    ports:

      - 8083:8083

    restart: unless-stopped

**Comment by kevindherdt** [comment]
Tried fresh installation again on 2 devices, Problem keeps persisting. I think calibre-web might not be able to handle large libraries.

**Comment by OzzieIsaacs** [comment]
I don't support the docker containers, please ask for help from the provider of the docker container
