### ISSUE TITLE
Update nginx Documentation

### ISSUE THREAD

**Issue by sbelongie** [janeczku/calibre-web#281]
When trying to use the documentation to setup the reverse proxy I ran into an issue when using /calibre-web as the script name.
I looked at the issues and saw that a thread that showed to use /calibre.  That worked.  Here is what I used for my settings to work.  

Can you update your read me?

#Calibre
	location /calibre {
        proxy_pass http://127.0.0.1:8083;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $server_name;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Script-Name /calibre;
    }

**Comment by jkrehm** [comment]
I think the issue you're running into is you're trying to use `location /calibre {` with `proxy_set_header X-Script-Name /calibre-web;`. Those two need to match. So either go with

```
location /calibre {
    ...
    proxy_set_header X-Script-Name /calibre;
```
or
```
location /calibre-web {
    ...
    proxy_set_header X-Script-Name /calibre-web;
```
but don't mix the two.

The README shows the former and works correctly as-is.

**Comment by jkrehm** [comment]
Alternatively, if you want it to have its own subdomain (versus running as a sub-reference), just toss it all and use something like

```
server {
    listen       80;
    server_name  calibre.dev.local;

    location / {
        proxy_bind       $server_addr;
        proxy_pass       http://127.0.0.1:8083;
        proxy_set_header Host            $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Scheme        $scheme;
    }
}
```

**Comment by sbelongie** [comment]
strange I tried that but it did not work... if it works for you that is fine.  You can feel free and close.

**Comment by lmergner** [comment]
I'm not an nginx expert and haven't seen the X-Script-Name header before. It's not included in most proxy examples elsewhere. It might be helpful to explicitly highlight its importance.
