### ISSUE TITLE
Wiki information suggestion: nginx proxy manager configuration

### ISSUE THREAD

**Issue by BastionNtB** [janeczku/calibre-web#2814]
Just a heads up, the documentation makes mention to nginx proxy manager, and the headers to add to it, but doesn't mention that you will also want to add only 'proxy_set_header X-Scheme $scheme;' and none of the other ones that are listed for nginx. (NPM already adds them to the config by default)

If you don't add this, when generating a kobo sync key, the link is http instead of https, and you may be able to get it to sync with the following headers added in the advanced section on NPM,

```
client_max_body_size 50M;
proxy_busy_buffers_size   1024k;
proxy_buffers   4 512k;
proxy_buffer_size   1024k;
```

This will have all download requests be sent on the http scheme on whatever port is specified in the config section of calibre-web. This results in an error 400, specifcally `<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>\r\n` which I captured with a packet capture.

If you're using NPM, and you add the other requested headers as specified on the wiki, it will cause a conflict and what I noticed was, when viewing the kobo sync key link, the address would generate like so `api_endpoint=https://<hostname>,<hostname>/kobo/<key>` (notice the comma in the host address space)

On a side note; the only way to fix this, is to edit the host in NPM, and turn off all checkboxes, remove the conflicting headers that were added, and save the host. Then you can edit it again turning on the switches, but I wouldn't suggest adding the conflicting headers again.

So the fix...

In the location space of NPM for the proxy host of calibre-web, you must add this one header at least.
'proxy_set_header X-Scheme $scheme;'

Then in the advanced section you must add (as the wiki currently specifies correctly) the following:
```
client_max_body_size 50M;
proxy_busy_buffers_size   1024k;
proxy_buffers   4 512k;
proxy_buffer_size   1024k;
```

This was tested with all three checkboxes checked on the 'details' tab, and all four checkboxes checked on the 'ssl' tab. I can now sync, download, get images, etc. And the api_endpoint string is generating correctly with https, and only one hostname in the host address space.

Again, I'm just giving a heads up to others, but ultimately feel if this could be updated in the wiki, it would be awesome.

Thanks for the hard work, love this service!

**Comment by OzzieIsaacs** [comment]
The wiki is open to anyone, please do the change on your own, I'm not the expert in nginx, nginx proxy manager, npm
