### ISSUE TITLE
Kobo Sync Low resolution covers

### ISSUE THREAD

**Issue by Fosnine** [janeczku/calibre-web#2817]
**Describe the bug/problem**
Kobo seems to be unable to GET a high resolution cover image from the calibre-web server.

When adding a new book to my shelve and syncing on my Kobo, calibre-web receives a GET request in the following format:
[2023-06-26 16:35:06] "GET /kobo/{PRIVATE_KEY]/802d5ebf-399b-465d-8073-f0040cca8cc2/1264/1680/80/isGreyscale/image.jpg HTTP/1.1" 200 15368 0.010609
This is as configured in 'Kobo eReader.conf':
image_url_quality_template=http://[PRIVATE_ADDRESS].com:80/kobo/[PRIVATE_KEY/{ImageId}/{width}/{height}/{Quality}/isGreyscale/image.jpg

The issue is that this seems to just resolve to the thumbnail generated by calibre-web. This is a jpg with a max height of 225px.
Changing the requested {width}, {height} or {Quality} doesn't change anything.
The thumbnails use an address formatted as:
https://[PRIVATE_ADDRESS].com/cover/68/sm?c=1687722901
The full images are formatted as:
https://[PRIVATE_ADDRESS].com/cover/68/og?c=1687722901

This leads to a very blurry cover when using them as the sleep screen on a Kobo device although they are sufficient for the list view.

**To Reproduce**
1. Add new book to synced shelve
2. Sync on Kobo
3. Book and metadata shows up and gets downloaded
4. Cover is very blurry

**Logfile**
[2023-06-26 17:07:16,450] DEBUG {cps.kobo:945} Cover request received for book 802d5ebf-399b-465d-8073-f0040cca8cc2
-->
[2023-06-26 17:07:16] "GET //kobo/[PRIVATE_KEY]/802d5ebf-399b-465d-8073-f0040cca8cc2/1264/1680/80/isGreyscale/image.jpg HTTP/1.1" 200 15417 0.008981

**Expected behavior**
I would expect the GET to result in an image of the requested resolution.

**Environment (please complete the following information):**
 - Calibre-Web version: 25-06-2023 Nightly
 - Docker container: LinuxServer
 - Kobo: 4.37.21533

**Comment by Fosnine** [comment]
Some further information:
I've added another eBook to calibre-web after disabling 'Generate Thumbnails'.
Then I've added that book to a synced shelf and synced on my Kobo.
Calibre-web received two 'cover requests' :

[2023-06-27 10:25:31,466] DEBUG {cps.kobo:945} Cover request received for book 111a8411-a078-4e64-87fd-579100d60360
[2023-06-27 10:25:31,698] DEBUG {cps.kobo:945} Cover request received for book 111a8411-a078-4e64-87fd-579100d60360
-->
[2023-06-27 10:25:31] "GET /kobo/[PRIVATE_KEY]/111a8411-a078-4e64-87fd-579100d60360/1264/1680/80/isGreyscale/image.jpg HTTP/1.1" 200 379576 0.013534
[2023-06-27 10:25:31] "GET /kobo/[PRIVATE_KEY]/111a8411-a078-4e64-87fd-579100d60360/149/223/70/isGreyscale/image.jpg HTTP/1.1" 200 379576 0.012282

Both 'GET's result in the same full size cover being returned, 1400x2100px in this case.
I assume the first request is intended for full screen display and the second one for display in the grid or list.

**Comment by Fosnine** [comment]
For now I've deleted the '/app/calibre-web/cps/cache/thumbnails/' folder and restarted my container and disabled 'Generate Thumbnails'.
Kobo now receives the files at their original resolution.
This will probably lead to slower load times of calibre-web but just in case someone is looking for a temporary workaround.

**Comment by OzzieIsaacs** [comment]
One of the reasons for the thumbnails was to get smaller size cover images send to kobo. The thumbnail algorithm generates covers in the background, the sizes generated are of fixed size (I think it was something like 200x200). The thumbnail is returned independend of what kobo is asking for.
Sending the big covers to kobo was resulting in the kobo reader shrinking the files on it's own, which took a long time. I can change it to return the full size cover if the requested size is bigger than a certain size.

**Comment by OzzieIsaacs** [comment]
The covers aren't shrinked on depand, because this could take some time and kobo is requesting all covers during a sync

**Comment by ngdio** [comment]
My Clara 2e doesn't seem to struggle much with downscaling covers, so the fix in 7818c4a7b0f6ca133c04185bd3c520e6bca7d6ba should do just well for most readers.

I'd argue that shrinking on demand shouldn't be that much of an issue, as long as generated images are cached. As the request details should probably be the same at every sync anyway, the size could then also be saved and created during thumbnail generation ahead of time for future syncs? A lot of effort to code this for little benefit, though.

**Comment by Fosnine** [comment]
Just tested it with a couple of books and works perfectly after the fix. Calibre-web is smooth and quick because of the thumbnails and I still get to enjoy the art of the books on my Kobo. I haven't really noticed any performance issues but I'm the sort of person who keeps very few books on their Kobo and just syncs a couple at a time. Sorry for the late reply, I missed your responses. Thank you for the solution!

**Comment by Fosnine** [comment]
Just tested it with a couple of books and works perfectly after the fix. Calibre-web is smooth and quick because of the thumbnails and I still get to enjoy the art of the books on my Kobo. I haven't really noticed any performance issues but I'm the sort of person who keeps very few books on their Kobo and just syncs a couple at a time. Sorry for the late reply, I missed your responses. Thank you for the solution!
