### ISSUE TITLE
the website cant support ipv6

### ISSUE THREAD

**Issue by EnderAvaritia** [janeczku/calibre-web#2819]
**Describe the bug/problem**
the website cant support ipv6 

**To Reproduce**
i try to access the serve by ipv6 , but it shows `ERR_CONNECTION_REFUSED`

**Logfile**
none , it dont generate 

**Expected behavior**
i hope i can access the serve by ipv6

**Screenshots**
![image](https://github.com/janeczku/calibre-web/assets/84321282/e1896b47-cd21-4f20-baeb-977c26da2810)
![image](https://github.com/janeczku/calibre-web/assets/84321282/1cfc7687-3ea2-43ff-9d40-e7f13fae62f8)

**Environment (please complete the following information):**
 - OS:Windows Server 2022 Standard
 - Python version: 3.9.13
 - Calibre-Web version: 0.6.20
 - Browser:Microsoft Edge 版本 114.0.1823.67 (正式版本) (64 位)

**Comment by OzzieIsaacs** [comment]
The loopback equivalent for ipv4 in ipv6 is: [::1]:8083 an this is working in calibre-web:
![grafik](https://github.com/janeczku/calibre-web/assets/6438895/284ee9f4-ebff-4a3a-bad3-62bbd2d40d41)
In your first screenshot you access a https page with unknown ip-address (something else than loopback I guess), so the problem is outside of calibre-web. Please ask whoever is providing the "outside" stuff for help.

**Comment by EnderAvaritia** [comment]
![image](https://github.com/janeczku/calibre-web/assets/84321282/6381fff2-b1df-44b1-9acb-e8e5edbed069)
I use the full ipv6 address to attach the serve,so it looked too long.
I also try to attach it by VPN with ipv4. 
the under picture is arrached with VPN provided by zerotier
![image](https://github.com/janeczku/calibre-web/assets/84321282/d3400cf4-4a05-41b6-b1bb-c99bfdce5fba)
I try other serve in the port and change this serve to other port , these things are not effort
I want to know how to make it work with ipv6 , what should I check and what can I poroviding.
Thank you

**Comment by OzzieIsaacs** [comment]
Is your windows supporting ipv6?
Is there a firewall preventing ipv6 connections?

**Comment by EnderAvaritia** [comment]
> Is your windows supporting ipv6?
> Is there a firewall preventing ipv6 connections?
> 

Im sure it support ipv6. it has been worked for a long time.
firewall is allowed. will it block loopback?

**Comment by EnderAvaritia** [comment]
> The loopback equivalent for ipv4 in ipv6 is: [::1]:8083 an this is working in calibre-web: ![grafik](https://user-images.githubusercontent.com/6438895/250287079-284ee9f4-ebff-4a3a-bad3-62bbd2d40d41.png) In your first screenshot you access a https page with unknown ip-address (something else than loopback I guess), so the problem is outside of calibre-web. Please ask whoever is providing the "outside" stuff for help.

![image](https://github.com/janeczku/calibre-web/assets/84321282/e28945f7-270f-4840-8ba1-d23f3e003138)
I think the application must be some problem . I try it in a virutal mechine , another serve worked corrently.
whether the serve have a botom to allow ipv6 access?
I use the `exe` installer with MD5:`F166BE11FBEC4EE8687B069D6D1081C8`

**Comment by OzzieIsaacs** [comment]
The exe version is indeed listening only to ipv4, as visible in the logfile:
[2023-07-02 09:31:37,227]  INFO {cps.server:207} Starting Gevent server on 0.0.0.0:8083
starting it with the parameter `-i ::`, will make it listen to ipV6 (only!)

**Comment by EnderAvaritia** [comment]
> The exe version is indeed listening only to ipv4, as visible in the logfile: [2023-07-02 09:31:37,227] INFO {cps.server:207} Starting Gevent server on 0.0.0.0:8083 starting it with the parameter `-i ::`, will make it listen to ipV6 (only!)

thanks a lot , it works.
Will it support doublestack in the future?

**Comment by OzzieIsaacs** [comment]
The secure way is to limit the number of sockets to listen to and not to widen it. 
Windows does only support a single socket.
And I think only very less people need this feature, so I will not support it in the future
