### ISSUE TITLE
does the application can change configure by files

### ISSUE THREAD

**Issue by EnderAvaritia** [janeczku/calibre-web#2821]
**Is your feature request related to a problem? Please describe.**
I change the port to a invaild port. I enter a paradox between change port and enter the web.

**Describe the solution you'd like**
I want to change configure without enter the web.
may I change the configure by file or it can not accept invaild configures.

**Comment by OzzieIsaacs** [comment]
There are config options available via commandline and environment variables: https://github.com/janeczku/calibre-web/wiki/Command-Line-Interface

**Comment by EnderAvaritia** [comment]
> There are config options available via commandline and environment variables: https://github.com/janeczku/calibre-web/wiki/Command-Line-Interface

thank you
