### ISSUE TITLE
OPDS book search

### ISSUE THREAD

**Issue by kobemtl** [janeczku/calibre-web#283]
Thanks a lot for the application. Love it a lot since I started using it. If its possible, it would be great to have the search feature in OPDS. or perhaps shelf category?

**Comment by OzzieIsaacs** [comment]
Just checked it in Marvin3 OPDS-Reader (iOS), the search is working.
Which feed reader do you use, is there an error message (if search is not possible, is is implemented in the reader?)

**Comment by idalin** [comment]
try to restart your App.
I found there is no searching after first adding opds in some App. After a restarting, it shows up.

**Comment by kobemtl** [comment]
Thanks a lot for the reply. 

I am using Moon+ Reader Pro on Android. 
Below you can see the search icon shows on Calibre OPDS but not Calibre-Web OPDS. My Calibre server puts behind apache reverse proxy. 
Calibre OPDS: https://mydomain/calibre/opds
![calibre](https://user-images.githubusercontent.com/6043647/29380857-40fedc56-8295-11e7-881d-27a6851f1323.png)

Calibre-Web OPDS: https://mydomain/calibre-web/opds
![calibre-web](https://user-images.githubusercontent.com/6043647/29380859-436bcd64-8295-11e7-81d0-1d7ccc887464.png)

**Comment by jkrehm** [comment]
Might be more of an issue with Moon+ than Calibre-web. Perhaps it's looking for something specific? I use FBReader and it lets me search my library without issue.

**Comment by kobemtl** [comment]
Seems like it. I just found Moon+ not support search on Wikipedia. But how come the search works on Cablire-Server?

**Comment by jkrehm** [comment]
I just compared the output of Calibre's OPDS to Calibre-Web and I believe this makes the difference:

```xml
<link type="application/atom+xml" href="/opds/search/{searchTerms}?library_id=Books" title="Search" rel="search"/>
```

According to the [spec](http://opds-spec.org/specs/opds-catalog-1-1-20110627/#Search) we should be able to add that element to enable searching.

I suspect the apps us others are using just searches the XML directly.

**Comment by jkrehm** [comment]
D'oh, nevermind. My editor wasn't auto-wrapping the find and I failed to note Calibre-Web's

```xml
<link rel="search" title="Search" href="/opds/osd"
        type="application/opensearchdescription+xml"/>
```

at the top. So maybe that's not it.

**Comment by kobemtl** [comment]
maybe moon+ not supporting opensearch? Anyway this confirmed the problem is not from calibew-web. Thanks everyone.

**Comment by OzzieIsaacs** [comment]
There are several issues with moon reader:
- search is not working
- covers are not shown

**Comment by OzzieIsaacs** [comment]
Doublechecked, search should work now, please try with the newest commit. 
The covers are also not shown in calibre, it's a bug in moon reader (no login data is send in request for images). Nothing we can change easily.

**Comment by kobemtl** [comment]
Thank you so much!!! It's working now.

**Comment by 8bitgentleman** [comment]
I recently started using moon+ with calibre-web and this still seems to be happening. Moon+ can use Calibre's default content-server search but search is not available for calibre-web's opds feed

**Comment by OzzieIsaacs** [comment]
I fiddles about one month ago on the search code.
My readers work, I‘m having a look at it(takes some time, as I currently without my computer)
