### ISSUE TITLE
Docker container tries and fails to update itself

### ISSUE THREAD

**Issue by kaibagley** [janeczku/calibre-web#2830]
**Describe the bug/problem**
When using calibre-web docker container, when it starts it checks repositories, finds a bunch of lib* updates, downloads about 30MB of updates, unpacks etc etc until it fails

**To Reproduce**
1. docker compose up -d
2. docker logs calibre-web

**Logfile**

> ...
>         Symlinking /app/calibre/calibre-customize to /usr/bin/calibre-customize
> 	Symlinking /app/calibre/fetch-ebook-metadata to /usr/bin/fetch-ebook-metadata
> 	Symlinking /app/calibre/calibre-smtp to /usr/bin/calibre-smtp
> 	Symlinking /app/calibre/calibre to /usr/bin/calibre
> 	Symlinking /app/calibre/lrfviewer to /usr/bin/lrfviewer
> 	Symlinking /app/calibre/ebook-viewer to /usr/bin/ebook-viewer
> 	Symlinking /app/calibre/ebook-edit to /usr/bin/ebook-edit
> Setting up command-line completion...
> Installing zsh completion to: /usr/share/zsh/vendor-completions/_calibre
> Failed to find directory to install bash completions, using default.
> Installing bash completion to: /usr/share/bash-completion/completions/
> Setting up desktop integration...
> 
> ____________________ WARNING ____________________
> Setting up desktop integration failed with error:
> __________________________________________________
> 
> 
> 	Traceback (most recent call last):
> 	 File "calibre/linux.py", line 858, in setup_desktop_integration
> 	 File "calibre/linux.py", line 880, in do_setup_desktop_integration
> 	 File "calibre/linux.py", line 911, in install_xdg_junk
> 	 File "calibre/linux.py", line 896, in install_icons
> 	 File "calibre/linux.py", line 890, in install_single_icon
> 	 File "subprocess.py", line 364, in check_call
> 	 File "subprocess.py", line 345, in call
> 	 File "subprocess.py", line 966, in __init__
> 	 File "subprocess.py", line 1842, in _execute_child
> 	FileNotFoundError: [Errno 2] No such file or directory: 'xdg-icon-resource'
> 
> Creating un-installer: /usr/bin/calibre-uninstall
> 
> 
> There were 1 warnings
> 
> * Setting up desktop integration failed with error:
> 
> [custom-init] No custom files found, skipping...
> [ls.io-init] done.
> 

**Expected behavior**
Downloads to actually end up sucessfully installed. Or at least not have this happen whenever I start calibre-web. It seems to take a long time to  download

**Environment (please complete the following information):**

    OS: Ubuntu 22.04
    Python version: 3.10.6
    Calibre-Web version: linuxserver/calibre-web:latest
    Docker container: linuxserver

**Comment by OzzieIsaacs** [comment]
The errormessage looks to me it has something to do with calibre itself. 

I don't support the docker containers, please ask for help from the provider of the docker container
