### ISSUE TITLE
Option to replace cover in epub file (from metadata)

### ISSUE THREAD

**Issue by vampywiz17** [janeczku/calibre-web#2832]
**Is your feature request related to a problem? Please describe.**

I fetch metadata to my ebook, but not possible replace the cover inside the file.

**Describe the solution you'd like**

I would like a option the change from metadata cover to embedded one (convert?)

**Describe alternatives you've considered**

epub to epub convert maybe solve this?

**Additional context**

-

**Comment by vampywiz17** [comment]
I think it connect it, but not exact request...

https://github.com/janeczku/calibre-web/issues/1030

**Comment by OzzieIsaacs** [comment]
There are 2 PRs addressing the request: #2485 and #2497
