### ISSUE TITLE
dark mode in in-browser pdf reader

### ISSUE THREAD

**Issue by cmdpedro** [janeczku/calibre-web#2836]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
In the in-browser viewer/reader there should be an option to invert the colours of the pdf, aka dark/night mode.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by cmdpedro** [comment]
Can someone point me in the right direction? Perhaps I can try to do it myself and share the code.

**Comment by cmdpedro** [comment]
Solved this using a modified version of pdf.js.

**Comment by jrhedman** [comment]
Can you share this modification?

**Comment by cmdpedro** [comment]
> Can you share this modification?

Have a look at: https://github.com/janeczku/calibre-web/issues/2150
