### ISSUE TITLE
Export .csv of Library

### ISSUE THREAD

**Issue by crispybegs** [janeczku/calibre-web#2841]
Is there a way of exporting a .csv of my library from the UI? (I don't use calibre standalone) 
It would be really useful for importing into a spreadsheet and sorting through my whole collection, identifying things that need to be edited / binned

**Comment by austinwilcox** [comment]
@crispybegs  I like this idea, I could see myself using something like this as well. If we don't hear anything back shortly from the team I would be happy to take a look at this and see what I could do to get this in there, the code really shouldn't hard to add in.

**Comment by OzzieIsaacs** [comment]
Calibre supports the export using the calibredb command (https://manual.calibre-ebook.com/generated/en/calibredb.html#export). I'd like to encourage you to use this function. I's like to avoid reprogramming auxillary functions to focus on the core features of calibre-web.
