### ISSUE TITLE
Access NFS share from proxmox->LXC->Docker->calibre-web

### ISSUE THREAD

**Issue by zisco67** [janeczku/calibre-web#2851]
I know, this is not directly related to calibre-web, but probably somebody had the same issue...Finally I've successfully installed a (unprivileged) LXC on Proxmox where docker hosts calibre-web. It's up and running, but now I don't know how to access my library which is located outside of proxmox on a NAS in my LAN (it is already mounted to proxmox datacenter as NFS storage). Any ideas?

**Comment by jvoisin** [comment]
Don't use docker, and simply mount the NFS share on proxmox, and mount it inside the container?

**Comment by Eisfresser** [comment]
this thread might help: https://forum.proxmox.com/threads/how-to-mount-an-nfs-share-inside-an-lxc-container.89093/

**Comment by RobLW** [comment]
Can you setup docker inside LXC easily? Not tried that before!

Setup an NFS share on your proxmox host and drop your desired files on this share. Ensure you enable the correct ports on your firewall. You can then create unprivileged LXC to mount the NFS share(s). Stick it into your /etc/fstab and enjoy the simple life.

**Comment by zisco67** [comment]
I've now changed the LXC from unprivileged to privileged, and added this command to my docker-compose.yml:
>     volumes:
>       - /mnt/calibre/Daten/Calibre:/books
The mounted directory 
> /mnt/calibre/Daten/Calibre

 is accessible inside the LXC (and the metadata.db is located in this directory), the 

> books

 volume is selectable by calibre-web, but after saving it tells me:

> DB Location is not Valid, Please Enter Correct Path
Any ideas?

**Comment by zisco67** [comment]
It seems as if this is a user-permission problem; the calibre-web process in the docker container runs with user **abc**-credentials. But unfortunately this is a container-only user...so how can someone grant read-permission to that user on the mount on the host?

**Comment by zisco67** [comment]
Inside my container I tried
> chown -R 1000:1000 /books

but unfortunately unsuccessful.

**Comment by zisco67** [comment]
Installed Calibre-Web directly on LXC without using Docker.
