### ISSUE TITLE
Impossible to uninstall automatically

### ISSUE THREAD

**Issue by Leonatus** [janeczku/calibre-web#2852]
Windows 10, Edge browser, Python 3.10.10 (64 bit), Kobo Clara 2E, firmware 4.37.21586 (I didn't use Calibre at all).
I tried to uninstall Koblime by checking the "uninstall at sync" box. I ejected the reader and mounted it again. Then - the box still checked - I clicked on "Wired backup". The program began to backup the books, but finally ejecting the Kobo again, the Koblime files were still there. There was also no sign of rebooting. What did I wrong, please?

Edit: Sorry for acting precipitately: I didn't know that for uninstall it was necessary to check WLAN connection. Now, there remained only two empty Koblime folders that I deleted manually. I apologize!

**Comment by OzzieIsaacs** [comment]
?? 
Koblime 
??

If you want to uninstall calibre-web from windows and you installed the exe version just delete the whole folder. If you installed it using pip use: `pip uninstall calibreweb`

**Comment by Leonatus** [comment]
Yes, sorry, it was about Koblime, and thanks, seems to be alright now!
