### ISSUE TITLE
Admin login broken; Password reset doesn't have an effect.

### ISSUE THREAD

**Issue by thre3eye** [janeczku/calibre-web#2853]
Running on docker:
root@53263d0a42f5:/app/calibre-web# python3 ./cps.py -v
Calibre-Web version: 0.6.20 -2023-03-27T19:49:57+02:00

My admin login is suddenly broken.

Resetting the password:
root@53263d0a42f5:/app/calibre-web# python3 ./cps.py -s admin:password
Password for user 'admin' changed

But login with the new password still fails with 'Wrong username or password".

I don't see anything in the default log and don't see anything in the console log.

Any ideas? Thanks

**Comment by waldfee** [comment]
Just had the same issue. I had to secify the database file, in my case `python3 cps.py -p /config/app.db -s admin:password`.

**Comment by thre3eye** [comment]
Thanks @waldfee. Sounded promising but not working for me unfortunately.

It looks like without your switch the script uses /app/calibre-web/app.db (checked with timestamps after issuing the command) However, I am using a docker volume for config. (see below). I just tried downgrading to 0.6.20-ls219 but no luck either.

volumes:
  calibre-web:
    external: true

services:
  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
...
    volumes:
      - calibre-web:/config
      - "/mnt/books/_calibre:/books"

**Comment by OzzieIsaacs** [comment]
I doublechecked it, for me it's working (without docker)

**Comment by OzzieIsaacs** [comment]
Somebody in the discord chat had the same issue. The linuxserver readme is going to be updated, please check there for the solution

**Comment by OzzieIsaacs** [comment]
https://docs.linuxserver.io/images/docker-calibre-web#version-tags

**Comment by mabushey** [comment]
Where can I get a copy of cps.py ?
