### ISSUE TITLE
SMTP email

### ISSUE THREAD

**Issue by uschi1** [janeczku/calibre-web#2859]
Hallo
Ich habe ein Problem nach dem update des calibre-web images auf meinem Docker (synology), nachdem ich das update aufgespielt hatte, kann ich den SMTP email Account nicht mehr einstellen!
Ich habe nun 30 Minuten damit verbracht, unterschiedlichste Einstellungen einzugeben, aber ich bekomme immer eine Fehlermeldung unter Aufgaben!
Logdatei:
[2023-08-06 18:37:01,019] ERROR {cps.tasks.mail:199} [Errno 111] Connection refused
[2023-08-06 18:47:12,019] ERROR {cps.tasks.mail:199} [Errno 111] Connection refused
[2023-08-06 18:47:28,052] ERROR {cps.tasks.mail:199} [Errno 111] Connection refused

Ich habe den web.de Zugang eingegeben, also:
![smtp](https://github.com/janeczku/calibre-web/assets/38375902/6a8c0cd5-6795-4545-8cd6-3e8db6a50a9c)

**Comment by OzzieIsaacs** [comment]
Der server ist smtp.web.de, der imap.web.de ist zum empfangen von emails

**Comment by uschi1** [comment]
Bin ich blöd..... Vielen lieben Dank, ich sah den Wald vor lauter Bäumen nicht mehr 🙄

**Comment by uschi1** [comment]
Kann man eigentlich den Betreff beim versenden an den Reader verändern?

**Comment by OzzieIsaacs** [comment]
Nein das geht nicht, normalerweise sieht man die email ja auch nie

**Comment by uschi1** [comment]
Mein Kobo eben schon, da muss man einen Betreff wie z.B. [kobo] eingeben... damit der Kobo sich das eBook ziehen kann!
