### ISSUE TITLE
Slash in Title Metadata not being escaped

### ISSUE THREAD

**Issue by p-rintz** [janeczku/calibre-web#286]
If a book has a / slash in its title metadata the name will not be properly escaped while creating the directory to put the file into. 

A "TCP/IP" for example in the title metadata will lead to a directory "TCP" being created, as well as a subdirectory with whatever follows. Calibre-web will then not be able to find the file being uploaded.

**Comment by jkrehm** [comment]
In addition, colons should be escaped, too. I uploaded to my development environment on macOS and it didn't transform the colon, so when I copied the directory to Windows, I had an issue. I haven't looked at the code to see if it escapes differently per-OS, but it should probably follow the same rules if it is.

**Comment by p-rintz** [comment]
That fixed the issue. Thank you.

**Comment by p-rintz** [comment]
I have to reopen this issue. The fix by @jkrehm worked, but not the current master.

**Comment by OzzieIsaacs** [comment]
Copied @jkrehm patch to master.
