### ISSUE TITLE
Uninstall calibreweb

### ISSUE THREAD

**Issue by FeralFox** [janeczku/calibre-web#2869]
Hello,
I installed calibre-web using python.
Now I switched to the Docker version and wanted to uninstall calibre-web.

However, even after system reboot I get this process listed with `ps x`:
```
11584 ?        Ssl    0:03 python3 /app/calibre-web/cps.py
```

When I kill the process, it respawns. `pip list` does not show calibre-web, thus I cannot uninstall it that way.

Maybe I am missing something, but how do I at least remove that process from system startup?

Thank you in advance!

**Comment by OzzieIsaacs** [comment]
Please ask for help from the docker provider

**Comment by OzzieIsaacs** [comment]
How did you install calibre-web?
How do you start it?

**Comment by FeralFox** [comment]
I installed calibreweb using pip, I started it by running `cps &`.
I don't remember if I created a venv, I think I used system wide python.

**Comment by OzzieIsaacs** [comment]
To me it looks like you created a unit file for calibre-web?

**Comment by FeralFox** [comment]
Sorry, what is a unit file?

**Comment by OzzieIsaacs** [comment]
Something like this here: https://github.com/janeczku/calibre-web/wiki/Setup-Service-on-Linux#start-calibre-web-as-service-under-linux-with-systemd

**Comment by FeralFox** [comment]
Hmm...I will check, thanks!
I stopped the docker container running calibreweb and after that the cps.py-process vanished. It didn't appear again after restarting the container. I will close for now and may reopen when I face this issue again

**Comment by FeralFox** [comment]
Just in case someone is landing here with the same issue, [here](https://stackoverflow.com/questions/26659129/docker-processes-shown-on-host-process-list)  is explained why the process running in the container is visible on the host
