### ISSUE TITLE
Different behavior of Download and read books for registered and guest user

### ISSUE THREAD

**Issue by klaus3409** [janeczku/calibre-web#287]
Hello, i don't find in the menu a option to create a public shelve. I can create a Private shelves, this is ok.  The user should see anonymous documents in Public shelve. Thank yo for your answer, by.

**Comment by jkrehm** [comment]
Does the response from #265 help answer your question?

**Comment by klaus3409** [comment]
Hello, thank for your answer. Now i have created a new User with the public shelves entry, it works! Thanks.
A last question please:  I dont see the books in the new public Shelve without a  Registration, is this ok? 
I thought everyone can see the books without Registration?

**Comment by jkrehm** [comment]
Have you looked at the Admin > Configuration page? I believe you can do most of what you want from that screen. I would recommend against using "Public Shelf" for that. If you enable anonymous browsing, unregistered users will be able to browse. If you view the "Guest" user and grant it access to download, then anonymous users will be able to download.

That seems to be the use you're looking for.

**Comment by amoize** [comment]
Just as Klaus I would like to be able to offer ebooks (just browsing and reading in browser) on a intranet. I have configured so that 'Guest' user can browse the ebooks, but I also want the 'Guest' user to able to read the ebook in the browser. I could not find a setting for it.
It looked to me that the 'Guest' user doesn't have this right. I do not want to enable download for the 'Guest' user just only reading in the browser. 

Is it possible to configure this? or should I make changes somewhere?

**Comment by OzzieIsaacs** [comment]
There is currently no option to distinguish between reading in browser and downloading. If you are experienced user, you would be able to download the book. If you can see it, you can download it.

**Comment by amoize** [comment]
OzzieIsaacs, When I create a user (example: student) and I don't give the right to download. This user is still be able to read an ebook in the browser. See the attached screendumps below.

I would like to config the 'Guest' user as the same as the student user. But Guest user is created when Enable anonymous browsing is activated.
So to me it looks like Guest user with the same rights as a user created 'by hand' acts differently. 

How to get Guest user to act like the 'normal user' Student  and be able to Read ebooks in the browser, but not to have the right to download enabled.

![student-user-config](https://user-images.githubusercontent.com/10452828/29510945-dd96d61a-865d-11e7-93a0-51bdf50023b7.jpg)

![login as student - read in browser](https://user-images.githubusercontent.com/10452828/29510959-e6cf4b2c-865d-11e7-829c-1a1941212fbf.jpg)

**Comment by OzzieIsaacs** [comment]
Now it's the same behavior
