### ISSUE TITLE
TrueNAS Calibre-Web can't be accessed after restart

### ISSUE THREAD

**Issue by idefy** [janeczku/calibre-web#2872]
**Describe the bug/problem**
A clear and concise description of what the bug is. If you are asking for support, please check our [Wiki](https://github.com/janeczku/calibre-web/wiki) if your question is already answered there.

**To Reproduce**
1. Follow the steps described here: https://github.com/janeczku/calibre-web/wiki/How-To:-Install-on-True-NAS
2. Before step 9 the Calibre-web is accessible and I am able to login
3. after a stop and restart, it's not possible to access : "refused to connect" on chrome, it seems the server is not up.

After some digging it seems you have to manually start it with Jail Shell: /usr/local/app/calibre-web # nohup python3 cps.py

**Logfile**
Nothing was found in the logs

**Expected behavior**
Calibre-Web should start when starting the plugin in TrueNAS

**Environment (please complete the following information):**
 - OS: TrueNAS Core
 - Python version: Python 3.9.17
 - Calibre-Web version: 0.6.21 beta
 - Special Hardware: NAS
 - Browser: Chrome Version 115.0.5790.173 (Official Build) (64-bit)

**Additional context**
I haven't tried, but I am worried that after a restart of the NAS Calibre-Web won't come back up without manual intervention.

**Comment by OzzieIsaacs** [comment]
Sorry, I don‘t provide the truenas plugin, please ask for help from somebody from truenas

**Comment by idefy** [comment]
Thanks for looking into it. I've opened an issue at the proper place, adding it here if people have the same issue: https://github.com/ix-plugin-hub/iocage-plugin-index/issues/376
