### ISSUE TITLE
CW 0.6.20: User list is not visible in admin/users with > 8 Users created

### ISSUE THREAD

**Issue by orcofthedarkness** [janeczku/calibre-web#2873]
**Describe the bug/problem**
With up to 8 users created one can see the user list and its statistics in admin/users. Once you create a "nineth" user, the user list is gone.

Here is the admin page with 8 users:
![image](https://github.com/janeczku/calibre-web/assets/127893294/c3b92c4f-884b-4296-95b7-c03e4f0b3392)

once you create another user (here is the "Edit User" page with 9 users created):
![image](https://github.com/janeczku/calibre-web/assets/127893294/3f5bcf67-7f5d-4290-bb24-0f5f3774a5c3)

all 9 users are  working and able to login, but on the admin page the list is not visible anymore;
![image](https://github.com/janeczku/calibre-web/assets/127893294/6384d821-2c0e-4d1e-87ad-639f36fc1fa8)

Did I miss a setting/option/switch anywhere or is this on purpose?
thank you in advance,
Ron

**Comment by OzzieIsaacs** [comment]
This is correct. There is a limit, if the number of users is bigger than 8 users, the users are no longer shown on the "admin page", to  not flood the admin page with users. 
There is also no setting to change this, and I will not change it.
