### ISSUE TITLE
Always asks for library location after reboot (service)

### ISSUE THREAD

**Issue by MeisterLLD** [janeczku/calibre-web#2876]
**Describe the bug/problem**
When calibre-web is setup as a service (following https://github.com/janeczku/calibre-web/wiki/Setup-Service-on-Linux) at each reboot, accessing calibre-web for the first time asks for library location. The previous one is already setup in the field so I just have to click the button, nonetheless I don't know why it asks so.

**To Reproduce**
1. Setup calibre-web as a service
2. Reboot
3. Access calibre-web

**Expected behavior**
One should directly access to the library, as one would when launching cps, rebooting and relaunching cps.

**Environment (please complete the following information):**
 - OS: Raspberry Pi OS Bullseye
 - Python version: 3.9.2
 - Calibre-Web version: 0.6.20
 - Special Hardware:  Rasperry Pi 4
 - Browser: Firefox for Android
 - Library is on an exfat external SSD, mounted properly with fstab and all necessary permissions

**Comment by OzzieIsaacs** [comment]
The moment calibre-web starts the library isn‘t accessible, please add a delay fpr starting calibre-web

**Comment by MeisterLLD** [comment]
Thanks, I didn't think of that.
Solved by adding

RequestsMountsFor=

In the Unit section of the service file.

Le dim. 3 sept. 2023, 06:31, Ozzie Isaacs ***@***.***> a
écrit :
