### ISSUE TITLE
How to Enable hypothes.is Annotations for PDFs?

### ISSUE THREAD

**Issue by coderZoe** [janeczku/calibre-web#2882]
Hello,

I've been trying to use hypothes.is to annotate my books in Calibre-Web. It works well for EPUB format, but I can't get it to work for PDFs. How can I resolve this issue?

Here's what the EPUB annotation looks like:
![166a5a1c3d7776fa355b32a7aa3cdd1](https://github.com/janeczku/calibre-web/assets/55009317/dd09ec61-f0c9-4056-9ac3-ac5350df47f2)
![f7037dca5aa36619f719bff80c13ce6](https://github.com/janeczku/calibre-web/assets/55009317/e5ff6ddc-53f8-4468-9a62-c4b29aa50c6a)
And here's the PDF without the expected annotation:
![198eedaa09ca0edae192a1f3904b852](https://github.com/janeczku/calibre-web/assets/55009317/2154a4de-16eb-4553-bafb-f1144020a4f6)
![ba02d61b44734fe747f1486bf7ed066](https://github.com/janeczku/calibre-web/assets/55009317/7c67ef31-e183-40ed-89c7-43243f185b5d)

From the screenshots, it can be observed that when a book is in PDF format, selecting text and clicking on the hypothes.is Annotation button doesn't pop up a text box for annotations like it does with EPUB.

For additional context, I am using the Microsoft Edge browser and have installed the hypothes.is plugin from this link: https://chrome.google.com/webstore/detail/hypothesis-web-pdf-annota/bjfhmglciegochdpefhhlphglcehbmek.

Thank you for any guidance.

**Comment by coderZoe** [comment]
Sorry，I noticed that the size of the PDF seems to be a factor. Larger PDFs, such as those with several hundred pages, don't seem to work with hypothes.is. However, smaller PDFs, around ten or so pages, are annotatable without issues.

**Comment by huofu** [comment]
Hey, I got the same issue with you, and after explore and experiment a bit, I found it is actually relevant to if the web front end has completely download the pdf file, so here is the interim trick I do to enable hypothesis, on the pdf page of calibre-web, try to hit the search button and key in arbitrary text to search, the front-end will try to download the full pdf file, which will then enable the OTT layer hypothesis to start working. Enjoy it ~

**Comment by coderZoe** [comment]
> Hey, I got the same issue with you, and after explore and experiment a bit, I found it is actually relevant to if the web front end has completely download the pdf file, so here is the interim trick I do to enable hypothesis, on the pdf page of calibre-web, try to hit the search button and key in arbitrary text to search, the front-end will try to download the full pdf file, which will then enable the OTT layer hypothesis to start working. Enjoy it ~

Thank you for your suggestion. I tried the workaround you mentioned, which is triggering a full download of the PDF file by using the search function. Unfortunately, even after ensuring that the PDF is fully downloaded, I still couldn't get the hypothes.is annotation and highlighting to work.

**Comment by ares1977** [comment]
I suspect that, up to the changes implemented for #2654 , the behaviour was to download the full pdf.

A solution would be to set disableStream=false and disableAutoFetch=false (maybe it could be made configurable from the UI?)

Also note that if disableRange=false some pages will be loaded while the full pdf is downloading in the background, and no annotations will be shown until the whole pdf is downloaded.
