### ISSUE TITLE
Is it possible to support tornado 6.3 ?

### ISSUE THREAD

**Issue by luochen1990** [janeczku/calibre-web#2886]
**Is your feature request related to a problem? Please describe.**

I'm trying to run Calibre-Web on NixOS, but it seems [tornado 6.3 is not supported well](https://github.com/NixOS/nixpkgs/pull/253564),  and seems there is only a little work to do here.

**Describe the solution you'd like**

Apply this [patch](https://github.com/NixOS/nixpkgs/pull/253564/files)

**Additional context**

[tornado 6.3 release notes](https://www.tornadoweb.org/en/stable/releases/v6.3.0.html)

**Comment by OzzieIsaacs** [comment]
There is a patch applied in the development branch, I need some mor testing before merging into the master branch
