### ISSUE TITLE
Clean install Flask-Limiter version not satisfied.

### ISSUE THREAD

**Issue by jdrjones1975** [janeczku/calibre-web#2887]
Running a clean install on ubuntu linux of calibreweb 0.6.20 via the command:
`pip3 install calibreweb`

when the installer gets to 
`Collecting Flask-Limiter<3.4.0,>=2.3.0 (from calibreweb)`

It shows the following error:

```
Could not find a version that satisfies the requirement Flask-Limiter<3.4.0,>=2.3.0 (from calibreweb) (from versions: 0.0.1, 0.1.0, 0.1.1, 0.2, 0.2.1, 0.2.2, 0.3.0, 0.3.1, 0.3.2, 0.4, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.5, 0.6, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.7, 0.7.1, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.8, 0.7.9, 0.8, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.9, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.5.1, 1.0.0rc1, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.3, 1.3.1, 1.4, 1.5)
No matching distribution found for Flask-Limiter<3.4.0,>=2.3.0 (from calibreweb)
```
I  am able to manually install flask-limiter via pip3 but it doesn't look like the current versions fall within the window that calibreweb is looking for.

**Comment by OzzieIsaacs** [comment]
For me it's working. Flask-limiter definitely has versions in the range >2.3 and <3.4, as can be seen on the pypi website.
![grafik](https://github.com/janeczku/calibre-web/assets/6438895/4072d85d-fc0d-46c1-bb9d-5a3c38ed84fd)
