### ISSUE TITLE
Upload button missing

### ISSUE THREAD

**Issue by adorostkar** [janeczku/calibre-web#2888]
**Describe the bug/problem**
On Calibre-web 0.6.20 the upload button is missing from the interface. 

**To Reproduce**
Install Calibre-web on Raspberry pi 3. 

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

**Expected behavior**
The Upload button should be there.

**Screenshots**

<img width="862" alt="Screenshot 2023-09-14 at 20 34 30" src="https://github.com/janeczku/calibre-web/assets/3062660/430c5799-701e-43e2-9d3d-4296c2b07d80">
<img width="1723" alt="Screenshot 2023-09-14 at 20 33 37" src="https://github.com/janeczku/calibre-web/assets/3062660/6b40e707-6381-4184-99b9-380b0e47b779">

**Environment (please complete the following information):**
 - OS: Raspberry Pi OS
 - Python version: 3.9.2
 - Calibre-Web version: 0.6.20
 - Special Hardware: Rasperry Pi 3
 - Browser: Chrome 116.0.58, Firefox 117.0.1

**Comment by OzzieIsaacs** [comment]
Please enable uploads in admin section and check if the user has upload permissions and give the user the permissions.
