### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by JiangYeming** [janeczku/calibre-web#2893]
1. How to configure migration to an external MySQL database server
2. How to configure the use of storage server to store books

**Comment by OzzieIsaacs** [comment]
Sorry for the late answer:
1. It's not possible and not planned. I'd like to stay compatible to calibre itself
2. The only possible storage server back end is google drive. How to set it up is described her:  https://github.com/janeczku/calibre-web/wiki/G-Drive-Setup

You could mount other storage back ends to your links filesystem and point calibre-web towards it. My bet is you will get problems with corrupted libraries from time to time and maybe get problems during startup that the library and it will prompt you for the database location. This is somehow expectable and it is not recommended to do so.

**Comment by JiangYeming** [comment]
thank you
