### ISSUE TITLE
Are read only filesystems supported?

### ISSUE THREAD

**Issue by tonyjonespdx** [janeczku/calibre-web#2894]
https://github.com/linuxserver/docker-calibre-web/issues/133#issuecomment-838505629 mentions the following ticket as related to read-only databases.

https://github.com/janeczku/calibre-web/issues/1982 

It seemed to be marked fixed but the last two comments are asking for it to be re-opened (for read-only) so I'm a bit confused.

My /books directory (which contains 'metadata.db') is a **read-only** filesystem (NFS v3).  

After setup I can access the server on port 8083.  I can login as 'admin'

When I set the books directory to '/books' after a delay I get the following on the browser:  "DB is not Writeable {newline} Database Settings updated" and in the log " ERROR {cps.config_sql:384} (sqlite3.OperationalError) database is locked [SQL: attach database '/books/metadata.db' as calibre;]" "WARN {cps.config_sql:385} invalidating configuration".  

After which any attempt at access results in the error shown here:  https://github.com/janeczku/calibre-web/issues/2456

**Comment by OzzieIsaacs** [comment]
I can't imagine that this is coming out of nothing. I can imagine this is triggered if you do something, is there something you do right before this error occurs?

**Comment by tonyjonespdx** [comment]
I initialize the container containing calibre-web.  I try to access it for the FIRST TIME.   I get what is shown in the initial post.
