### ISSUE TITLE
add shebang to cps.py

### ISSUE THREAD

**Issue by perler** [janeczku/calibre-web#29]
could you add

#!/usr/bin/env python

on top of cps.py so that we can create an init.d/systemd startup script?

**Comment by hscissors** [comment]
@perler Did you ever get this working?

**Comment by perler** [comment]
what do you mean?

On Tue, 12 Jul 2016, 02:47 Harold Scissors, <notifications@github.com>
wrote:

> @perler <https://github.com/perler> Did you ever get this working?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/janeczku/calibre-web/issues/29#issuecomment-231907805>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAmB9M6_V2mTkLg4v2eTZV-8mPyYFMK9ks5qUuQ9gaJpZM4I46qG>
> .
>
--
