### ISSUE TITLE
[Request] Mass Edit/Delete option

### ISSUE THREAD

**Issue by simkin** [janeczku/calibre-web#290]
I find that I spend allot of time cleaning my library by deleting books 1-by-1 or by locating books without proper metadata. I hope that it might be a good idea to extend the search functionality with mass edit/delete functionality? e.g. to correct the Author, Series name, Language or to mass delete books. I guess it can work by showing one EDIT screen and overwrite the values for all books after submitting?

**Comment by OzzieIsaacs** [comment]
I recommend for tasks like this to use calibre, which has functions to rebuild the lib from scratch and ro do mass edit and mass delete

**Comment by simkin** [comment]
That makes sense, for me personal not ideal though as I only run the headless server :) Feel free to close/reject if this is not feasible!
