### ISSUE TITLE
Some of the JavaScript files within js/libs are minified, is it possible to provide a human-readable version?

### ISSUE THREAD

**Issue by Sysking1024** [janeczku/calibre-web#2905]
I am currently working on screen reader adaptation for the project, but when I attempt to modify reader.min.js, I find that the code in this file is a minified version. Could you provide an unminified version?

**Comment by OzzieIsaacs** [comment]
The minified versions are all library files provided by other people.  Should be this repository: https://github.com/futurepress/epubjs-reader
