### ISSUE TITLE
Caliblur: Home Button doesn't include subdirectory

### ISSUE THREAD

**Issue by CodeShakingSheep** [janeczku/calibre-web#2908]
**Describe the bug/problem**
My Calibre instance is running in a subdirectory `https://mydomain.tld/calibre`. When I change the Calibre theme to Caliblur there is a small bug with the home button. The home button doesn't link to `https://mydomain.tld/calibre` but to `https://mydomain.tld`. The interesting thing is that

**To Reproduce**
1. Install Calibre Web in a subdirectory
2. Change theme to Caliblur
3. Click on the home button in Caliblur
4. See that you are being redirected to the root domain without the subdirectory

**Expected behavior**
The home button should link to Calibre web's correct installation directory (including the subdirectory).

**Screenshots**
![image](https://github.com/janeczku/calibre-web/assets/19874562/57aa72af-cb7c-4358-a005-f5d356fdba32)

**Environment (please complete the following information):**
 - OS: Debian 11
 - Python version: Python 3
 - Calibre-Web version: 0.6.20
 - Docker container: None
 - Special Hardware: none
 - Browser: Chrome

**Additional context**
Interestingly, the Calibre Web Link just below the Home Button is pointing to the correct directory including the subdirectory. I briefly checked Caliblur JavaScript and thre the href property is set to `$(".navbar-brand")[0].href`, see https://github.com/janeczku/calibre-web/blob/master/cps/static/js/caliBlur.js#L506.

**Comment by OzzieIsaacs** [comment]
I'm not 100% sure but I think this is fixed in the newest nightly version:
https://github.com/janeczku/calibre-web/pull/2778
