### ISSUE TITLE
Is it possible to see some "Tags" only in Shelfs?

### ISSUE THREAD

**Issue by DarkUser089** [janeczku/calibre-web#2910]
I set up Calibre-Web yesterday and so far everything is going well. I own a lot of mangas and accordingly the mangas are now flooding my whole library. 

So my question would be: Is there somehow the possibility to hide the mangas so that this as an example is only visible in the shelves? Because otherwise the overview is just difficult, because this is as said totally flooded by the mangas.

**Comment by OzzieIsaacs** [comment]
It's (and will not be) not possible to see only tags in shelves. What you could do is add a tag to all mangas and create a second user with a restriction to only view books with tag "manga" and restrict the current user to have only books visible without tag "manga"
![grafik](https://github.com/janeczku/calibre-web/assets/6438895/f91ccdd0-080c-4908-b32c-3389bac49550)

**Comment by DarkUser089** [comment]
Hm ok thats not exactly what i wanted but at least i can then only show Mangas to people that actually are interested in it :)

Thanks for the fast reply
