### ISSUE TITLE
Update to 0.6.21 issues

### ISSUE THREAD

**Issue by gavdgavd** [janeczku/calibre-web#2917]
**Describe the bug/problem**
Two problems updating from 0.6.20 to 0.6.21
- (minor issue) The file that you get using the "Release V0.6.21" from https://github.com/janeczku/calibre-web/releases/download/0.6.21/Calibre-Web-06-21-Setup.exe is called "Calibre-Web-06-20-Setup.exe". When you compare the size of 0.6.20 (original) and 0.6.20 (for version 0.6.21), you see that they are different. Thus, I assume it is just a small renaming problem.
- (mayor issue) After installing release 0.6.21, the original database "disappears", thus all the original configurations are gone. Reviewing the installation folder, you see that there is a new "_internal" directory where the app.db file is. If you replace this db file with a backup of the old (0.6.21) version, everything starts working correctly. I am sure this directory was not in the original 0.6.20 version, and that the app.db file under the root of the Calibra-web directory was located.

**To Reproduce**
1. Install version 0.6.21 at the top of a working version 0.6.20
2. Run the Calibre-Web application
3. The data from the 0.6.20 version is not available anymore
4. The database used by the application is now in a new "_internal" directory
5.  Set a backup copy of the app.db file in the "_internal" directory, and all configurations are back

**Expected behavior**
To make an update from 0.6.20 to 0.6.21, everything should work correctly regarding data in the database

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python version: Python 3.10.5
 - Calibre-Web version: 0.6.20 to 0.6.21
 - Docker container: None
 - Special Hardware: None
 - Browser: Vivaldi, Edge

**Comment by OzzieIsaacs** [comment]
No1 is already solved. 
no2 I realized the folder during build process but I didn’t realize the consequences. I‘ll check why this happens

**Comment by OzzieIsaacs** [comment]
Starting an explanation. The changed file layout is due to an update of pyinstaller:
![image](https://github.com/janeczku/calibre-web/assets/6438895/dd9c6c8a-fe91-4ec7-8b4f-dc5985c59140)
So nothing I changed on my side

**Comment by OzzieIsaacs** [comment]
I fixed it for the next release. The files will show up in the root folder of calibre-web

**Comment by gavdgavd** [comment]
Thanks a lot Ozzie. Looking forward to the next release.
