### ISSUE TITLE
Link/Unlink button missing on user page

### ISSUE THREAD

**Issue by astrayel** [janeczku/calibre-web#2919]
**Describe the bug/problem**
I use OAuth authentication with both Google and Github using wiki for setup. All seems to be OK.
But, in userpage configuration (in admin mode), there is no LINK/UNLINK button to link the user to a OAuth account. The button(s) is simply not here. So users can't login with OAuth because user are not recognized. 
Message is : 
*INFO {cps.oauth_bb:156} Login failed, No User Linked With OAuth Account*

**To Reproduce**
1. Go to 'Edit Basic configuration'
2. Click on 'Feature Configuration'
3. Select Login type 'use OAuth'
4. Set github Oauth Client Id and and github OAuth Client Secret
5. Save
6. Go to 'Admin settings'
7. Edit one user.
8. No LINK button is present.

**Logfile**
```
[2023-10-31 08:30:39,322]  INFO {apscheduler.scheduler:181} Scheduler started
[2023-10-31 08:30:39,323]  INFO {apscheduler.scheduler:895} Added job "end scheduled task" to job store "default"
[2023-10-31 08:30:41,939]  INFO {cps.server:207} Starting Gevent server on [::]:8083
[2023-10-31 08:31:17,006] DEBUG {cps.updater:329} Stable version: {'version': '0.6.21'}
[2023-10-31 08:31:37,199]  INFO {cps.oauth_bb:156} Login failed, No User Linked With OAuth Account
```

**Expected behavior**
A LINK button should appear to link users to OAuth users

**Screenshots**
![image](https://github.com/janeczku/calibre-web/assets/55978388/84f7ee9e-9aaa-491d-b260-e88c3abbfadd)

**Environment (please complete the following information):**
 - OS: Unraid
 - Python version: [3.10.12]
 - Calibre-Web version: [0.6.21]:
 - Docker container: [lscr.io/linuxserver/calibre-web]:
 - Browser: [Version 118.0.5993.118 (Build officiel) (64 bits)]

**Additional context**
Maybe I'm missing something but I tried many times and I can't see any button.

Thank you for your time.

**Comment by OzzieIsaacs** [comment]
Could you please try the standard theme, maybe it‘s a theming error

**Comment by astrayel** [comment]
So fast...
But no, same thing. In html, no trace of link button somewhere.

**Comment by OzzieIsaacs** [comment]
One additional thing: every user has to link the GitHub account on his own, so the admin is only able to Link his GitHub account but he can‘t do it for others. The button might be only visible on the /me page

**Comment by astrayel** [comment]
OK. I did not understand that users must be logged in to link themselves on calibre-web. I thought it was an admin task.
So all is fine. Users can link their account from their profile. 
Thank you for your help.
I close the "issue".
