### ISSUE TITLE
SMTP fails to send, logs show random undecodable bytestring as error

### ISSUE THREAD

**Issue by ant-ds** [janeczku/calibre-web#2927]
**Describe the bug/problem**
When adding an SMTP configuration for mailing to work (save+send test email), the task fails after 30 seconds. The logs only give a random byte string as response

**To Reproduce**
1. Log in for the first time using default credentials
2. Add the calibre db
1. Go to 'admin'
3. Click on 'Edit Mail Server Settings'
4. Input the following information + correct account credentials: 
5. Click on 'Save and Send Test Email'
6. Go to 'Tasks'
7. Watch seconds go up to 30 before the task fails
8. Check logs

**Logfile**
`[2023-11-10 02:10:48,813] DEBUG {cps.updater:329} Stable version: {'version': '0.6.21'}
[2023-11-10 02:11:10,499] DEBUG {cps.config_sql:376} _ConfigSQL updating storage
[2023-11-10 02:11:10,511]  WARN {cps.config_sql:352} Log path  not valid, falling back to default
[2023-11-10 02:11:10,515] DEBUG {cps.services.worker:91} Add Task for user: admin - E-mail E-mail, Calibre-Web Test Email
[2023-11-10 02:11:11,227] DEBUG {cps.tasks.mail:194} Start sending e-mail
[2023-11-10 02:11:41,395] ERROR {cps.tasks.mail:199} (-1, b'\x02\x01Z\x15\x03\x03\x00\x02\x01\x00')
[2023-11-10 02:11:45,817] DEBUG {cps.updater:329} Stable version: {'version': '0.6.21'}`

**Expected behavior**
Mail succeeds, or error is at least indicating some clear issue.

**Screenshots**
![image](https://github.com/janeczku/calibre-web/assets/20105526/6651693b-a276-4c9d-9373-57ff83ea301a)

**Environment (please complete the following information):**
 - OS: Proxmox LXC Debian container / Docker container (I tried both with same result)
 - Python version: python 3.x
 - Calibre-Web version: [e.g. 0.6.8 or 087c4c59 (git rev-parse --short HEAD)]:
 - Docker container: both pip install and linuxserver
 - Browser: Firefox

**Comment by ant-ds** [comment]
I have also tried the same with an AOL email address (port 465, smtp.aol.com) and get the exact same bytestring error. I tried this on a machine connected straight to the router and also on a LinuxServer docker container.

**Comment by OzzieIsaacs** [comment]
https://www.solveforum.com/forums/threads/solved-smtpconnecterror-occurs-when-using-yahoo-but-my-login-and-port-are-correct.668312/

**Comment by ant-ds** [comment]
Thanks for the help! This advise indeed fixed it!
The solution: create an app-specific password in Yahoo / AOL and use that in combination with TLS/SSL setting.
NOTE: Yahoo seems to have disabled app-specific passwords so I'm using an AOL mail instead now.

**Comment by anadegraux** [comment]
Hi all,

I have the same error as you got... but link is not reachable anymore. could you please explain what you did?

> https://www.solveforum.com/forums/threads/solved-smtpconnecterror-occurs-when-using-yahoo-but-my-login-and-port-are-correct.668312/

thanks in advance!
