### ISSUE TITLE
Add option to chunk files on upload

### ISSUE THREAD

**Issue by BLACK4585** [janeczku/calibre-web#2928]
**Is your feature request related to a problem? Please describe.**
My Calibre-Web Server is sitting behind the Cloudflare Proxy. Since I don't have the enterprise plan, my request body size limit is only 100mb. Thus, I'm getting an error when uploading a stack of e-books bigger than 100mb.

**Describe the solution you'd like**
A way to solve this would be to chunk the uploaded files in pieces of like 95mb each, so they can be uploaded. Like done in [Zipline](https://github.com/diced/zipline). This option could be fine-tuned or enabled/disabled completely in the settings.

**Describe alternatives you've considered**
Using a VPN to connect to my server, then using the local IP and upload the files. But pretty inconvenient.

**Comment by qaqland** [comment]
Same on me, need this feature! Some PDFs are made by image and size lager than 100M

> To fix the “413 Request Entity Too Large” issue when uploading a 140MB file via Cloudflare API, you need to upgrade your plan. Free and Pro plans support a maximum file upload size of 100MB. Business plans support up to 200MB, and Enterprise plans support up to 500MB by default. For a higher limit, Enterprise customers can contact Cloudflare Customer Support.

**Comment by jasoncronje** [comment]
@OzzieIsaacs — Saw this was marked as completed. How do we use or setup the chunking feature?

**Comment by BLACK4585** [comment]
huh?

**Comment by BLACK4585** [comment]
So it won't get added to calibre web? Is there a reason for that?

**Comment by InnocentGecko698** [comment]
> So it won't get added to calibre web? Is there a reason for that?

Seems not... Did you ever find a workaround other than VPN? 

Was considering using Zipline as an upload middleware since it supports chunking.

**Comment by BLACK4585** [comment]
Just don't use the Cloudflare proxy and use it as DNS server. You can turn off the proxy for your (sub)domain using the checkbox right next to the entry in the CF dashboard.
