### ISSUE TITLE
Repopulate db based on the calibre folder

### ISSUE THREAD

**Issue by ashkan2200** [janeczku/calibre-web#293]
Hi,
This is more like a feature request. I use rsync to send books from my laptop to my server and sometimes I remove the books I don't want at the moment on my laptop.
This causes an update to metadata.db which makes calibre-web not show those books. 

Could you add a feature to repopulate the db on demand?

**Comment by OzzieIsaacs** [comment]
My personal experience is that the metadata in books are not always correct, so after adding a book into the db you have to edit some content manually. If we would add a repopulate db command than many people would complain about this, so I think it's not a good idea to implement this.
