### ISSUE TITLE
Can I sort by most recent added?

### ISSUE THREAD

**Issue by tknx** [janeczku/calibre-web#2930]
**Is your feature request related to a problem? Please describe.**
Often I will add several books to calibre through the monitored downloads folder and then want to start reading it soon thereafter. So it would be really great if I could see which ones I added most recently

**Describe the solution you'd like**
Add a sort by date added

**Describe alternatives you've considered**
I basically just have to track which ones I recently added manually and then search them

**Comment by jakesmorrison** [comment]
The default setting for me is to sort by book added date. 
![image](https://github.com/janeczku/calibre-web/assets/14865171/6f0314bb-5078-4dbd-9fa0-e940793137d8)
