### ISSUE TITLE
Can't Access anywhere but localhost

### ISSUE THREAD

**Issue by Tyoryn** [janeczku/calibre-web#2935]
So I'm running calibre-web on Debian 12, no docker, version 0.6.21.  The issue I'm having is when I go to localhost:8083 it comes up no problem.  Setup went fine, created the admin account and one for my wife, and enabled magiclink to eventually get everything to her kindle.  However, if I try to access via (IP address of host server):8083 instead of localhost I get an unable to connect page.  Port forwarding for 8083 on my router is configured.  Haven't tried accessing from outside my LAN via my DDNS address but I'd think if I cant from inside the network what chance do I have from outside

**Comment by DaneRainbird** [comment]
Howdy! If you have a firewall running on your machine (such as ufw), you may need to allow it through the firewall.

In the case of ufw, this would be something along the lines of `sudo ufw allow 8083`

**Comment by Tyoryn** [comment]
No firewall on router.  Never set anything up on computer either unless there's some low level one default to on in debian like windows has that defender junk.  All my other hosted services (Plex, sonarr, Radarr, etc..) work fine with localist,  LAN IP, and even from outside network via my DDNS.  That's what has me so confused, why only this one.

**Comment by ipcoder** [comment]
same here. no firewall

**Comment by OzzieIsaacs** [comment]
For me it‘s working. This is definitely not a problem of calibre-web
