### ISSUE TITLE
Shelves books order show blank bugs.

### ISSUE THREAD

**Issue by flashliao** [janeczku/calibre-web#294]
I don't knonw why this problem happen. The problem is show this picture.

![default](https://user-images.githubusercontent.com/28710685/29738694-11617290-8a5d-11e7-946a-5ee5ab4a7fe7.png)

**Comment by jkrehm** [comment]
What do your browser Dev tools say? Are there errors in the console and/or network tab?

**Comment by flashliao** [comment]
I don't konw how to find errors,but I find Shelves books order have blank title
![default](https://user-images.githubusercontent.com/28710685/29757839-8245fb9a-8be1-11e7-9d76-7067cce76e56.png)
When i change the order the error show like this :
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by flashliao** [comment]
I supply app.db and metadata.db.I found the app.db Shelves books not have metadata.db books.
Do you understand what am i talking about.
[11.tar.gz](https://github.com/janeczku/calibre-web/files/1255045/11.tar.gz)

**Comment by jkrehm** [comment]
I'm sorry, I do not understand. Could you provide your `calibre-web.log` file? Also, you can use your browser's developer tools to figure out why the images are not showing, e.g. 404 errors.

Internet Explorer 11: https://msdn.microsoft.com/en-us/library/gg589500(v=vs.85).aspx
Edge: https://docs.microsoft.com/en-us/microsoft-edge/f12-devtools-guide
Chrome: https://developer.chrome.com/devtools
Firefox: https://developer.mozilla.org/en-US/docs/Tools

**Comment by flashliao** [comment]
This problem is app.db database book_shelf_link table contain the deleted book.
The deleted books may not deleted the shelf information, I guess.
I can fix the problem this time  but I don't know next time if there can happen.
[calibre-web-master logs.tar.gz](https://github.com/janeczku/calibre-web/files/1255106/calibre-web-master.logs.tar.gz)
