### ISSUE TITLE
Text reader unusable - error invalid mulitbyte sequence

### ISSUE THREAD

**Issue by linonetwo** [janeczku/calibre-web#2945]
**Describe the bug/problem**

Text viewer online will be blank, and show HTML code after a while

**To Reproduce**
1. upload a txt
2. view it online

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

**Expected behavior**

Works like pdf online viewer

**Screenshots**
![图片](https://github.com/janeczku/calibre-web/assets/3746270/9dcdecae-ff55-4b23-971d-9569ef6c9e5f)

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10/Raspberry Pi OS] Windows 2022
 - Python version: [e.g. python2.7]
 - Calibre-Web version: Docker 0.6.21 - c45188beb22adc5416bb8fd73fa23bf5270f7759 - 2023-10-21T12:40:32+02:00
 - Docker container: [None/LinuxServer]: Windows
 - Special Hardware: [e.g. Rasperry Pi Zero]
 - Browser: [e.g. Chrome 83.0.4103.97, Safari 13.3.7, Firefox 68.0.1 ESR] Firefox 120.0.1 (64)

**Additional context**

it is deployed on an NAS, and view it using LAN IP http://192.168.xxx:10xx/read/62271/txt

**Comment by linonetwo** [comment]
![图片](https://github.com/janeczku/calibre-web/assets/3746270/26c7753b-71dc-4574-adf3-cdbbc7ea55e0)

some of book works...

here is the file that does not work
[无穷重阻 - 核动力战列舰.txt](https://github.com/janeczku/calibre-web/files/13627879/-.txt)

**Comment by linonetwo** [comment]
It works after changing encoding from GB2312 to UTF8 (By open with old encoding and save with new encoding.)

**Comment by OzzieIsaacs** [comment]
The problem is that the source book contains some invalid characters ("invalid mulitbyte sequence") this wasn't properly handled by calibre-web. I changed the code now, so an error is logged in the logbook and the wrong characters are ignored.
