### ISSUE TITLE
send azw3 to kindle email

### ISSUE THREAD

**Issue by jiangjiangflies** [janeczku/calibre-web#295]
Hi,
Why I can't send azw3 format ebook to  my kindle email?

**Comment by jkrehm** [comment]
Haven't tried it myself, but Googl'ing for "send azw3 to Kindle email" makes me think that it's an issue with the DRM that's part of AZW3 files.

**Comment by jiangjiangflies** [comment]
Can't kindlegen convert azw3 to mobi or epub before sending emails?

**Comment by jkrehm** [comment]
I don't have a file handy. Have you tried it with your copy of kindlegen? I don't believe it will because azw3/kf8 is designed to prevent viewing on non-Kindle devices. 

Personally I use a slightly older version of Kindle for Mac (1.17, I believe) so that I don't have to deal with KF8.

**Comment by jkrehm** [comment]
Ah nevermind, KFX/AZW6 is the problem, not KF8/AZW3. So at least the DRM shouldn't be an issue. Sorry for wandering into the weeds.

**Comment by jiangjiangflies** [comment]
I think it would be better if you can replace kindlegen in the vender with ebook-convert binary.

**Comment by jkrehm** [comment]
Can you provide some details on what error you get? Have you tried another ebook? Have you tried sending the file directly to your Kindle email (not via the calibre-web interface)?

**Comment by jiangjiangflies** [comment]
I tried to send the file directly to my kindle email, amazon refused......It  doesn't support azw3 file to mail. So  could you add a function to convert azw3 to mobi before sending?

**Comment by jkrehm** [comment]
`ebook-convert` does seem like a good way to go to support a wider variety of book formats. It requires installing Calibre, which may or may not make sense, e.g. I run calibre-web on a headless (no GUI) Linux server.

So if `ebook-convert` is made to be an option, I think `kindlegen` needs to remain.

For now, I recommend you use Calibre to convert your AZW3 books to ePub or MOBI format. calibre-web's code doesn't even support AZW3 files, so I don't know how it even mailed the file out.

```
    for entry in data:
        if entry.format == "MOBI":
            formats["mobi"] = os.path.join(calibrepath, book.path, entry.name + ".mobi")
        if entry.format == "EPUB":
            formats["epub"] = os.path.join(calibrepath, book.path, entry.name + ".epub")
        if entry.format == "PDF":
            formats["pdf"] = os.path.join(calibrepath, book.path, entry.name + ".pdf")

    if len(formats) == 0:
        return _("Could not find any formats suitable for sending by email")
```

**Comment by sbarut** [comment]
Amazon's servers don't  support azw3 or any other formats expect mobi

**Comment by jiangjiangflies** [comment]
I'm using a headless linux server and I have installed calibre which contains the `ebook-convert` binary. I don't think it a problem to install calibre. So I strongly suggest that adding an option to use ebook-convert to convert non-mobi format to mobi format so that Amazon can accept email.

**Comment by sbarut** [comment]
Why? For example, epub3 and azw3 almost same formats (both supports html5 and css3 elements). Why do you need convert them?

If you want to convert them to pdf, it is not stable, nevermind.

**Comment by jiangjiangflies** [comment]
I want to convert azw3 or epub to mobi because only mobi format is accepted by Amazon. Most of my ebooks are azw3 format, they can't be sent by email.

**Comment by sbarut** [comment]
Oh, I get it now. If you using gnu linux, I would help you about a bash script for convert all files.

**Comment by jiangjiangflies** [comment]
Thanks, but I still hope there is an option to use `ebook-convert` to convert non-mobi files to mobi format automatically before sending email. Anyway, I really appreciate your great work.

**Comment by simonporter007** [comment]
Muddying the water slightly perhaps, but I'd love to be able to email azw3 to the email address specified. I use my own email address and download books to the Kindle through IMAP plugin. So it doesn't go through amazon servers (and therefore is supported). Calibre has a format priority list, guess that would be the easiest way?

**Comment by jiangjiangflies** [comment]
How do you modify this program to use IMAP plugin to bypass amazon server? Could you paste your code here?

**Comment by simonporter007** [comment]
@jiangjiangflies Sorry, should have been more specific. The IMAP plugin is a KUAL plugin on the kindle. So I  email from calibre at the moment, to my own email address. Then open the plugin on the kindle which downloads the books and adds the covers. The code isn't great, I just knocked up something that worked for my case - but you could always use it as a base if you were still interested, i'll get it uploaded.

**Comment by bodybybuddha** [comment]
Yes - I’ll get started on it next.

John Taylor [ m. 908.672.0299 e. john@teamtaylor.net ]
bit.ly/JTsInfo <https://bit.ly/JTsInfo>
