### ISSUE TITLE
Space in folder name

### ISSUE THREAD

**Issue by rivaborn** [janeczku/calibre-web#2951]
**Describe the bug/problem**
I cannot add Calibre folders with paths that contain a space.
On Windows - Folder cannot be selected but folder path can be typed in and it works
On Synology NAS via Docker - Folder can be selected on setting up the Docker image. After logging into calibre-web and attempting to select the 'Location of Calibre Database' the folder contents are not seen and on saving it gives an error "DB Location is not Valid, Please Enter Correct Path". Works when folder path has no space in it.

**To Reproduce**
1. Select a Calibre folder with a a space in the path

**Expected behavior**
Calibre folder path can include space.

**Environment (please complete the following information):**
 - Windows 11
 - Docker container: Synology NAS

**Additional context**
The problem occurs on windows 11 and on Synology NAS via Docker

**Comment by OzzieIsaacs** [comment]
I don't have a windows 11 on my hand, so I checked it with Windows 10 and Firefox and also with my Linux Installations (I don't have a synology). Both work fine, for selecting the folder via the "filepicker" and also via entering a path with a space in it (at least if the space isn't the last character, this is not working and is intended (to make work on mobile devices convenient). I did the test with firefox and chrome browser. From the code I also see not reason why folders with spaces in them should not work
![2023-12-21_14-19](https://github.com/janeczku/calibre-web/assets/6438895/0c2a651b-64e4-41b6-af93-bb6fd8e05109)
![2023-12-21_14-21](https://github.com/janeczku/calibre-web/assets/6438895/17888fda-9353-45c4-887b-2311175459fa)

**Comment by OzzieIsaacs** [comment]
I used the newest nightly version and also the latest release 0.6.21

**Comment by rivaborn** [comment]
Thanks for looking into this! After more testing I think the problem is with the size of the library. My test library had only a few books while my smallest actual libraries has more than a thousand books. The space was a red herring, it just randomly happened that all my small libraries had no space in the title! 

I think the problem is the dialog box for selecting the location of the Calibre Database is trying to list all the folders in the directory, which can be thousands of folders. A workaround I've found that works on windows is to type the folder name and save. Sadly on Synology NAS using Docker, typing and saving the mapped volume name does not work.

Thanks again.

**Comment by OzzieIsaacs** [comment]
Because you do this only once, I will not implement a "chunked" directory listing and leave it as it is.
