### ISSUE TITLE
Barnes and Noble link tag

### ISSUE THREAD

**Issue by smax317** [janeczku/calibre-web#2956]
**Describe the bug/problem**
Metadata ids for barnesnoble:##### do not link to barnes and noble store page. Instead it links to [calibre-web-host]/#####

**To Reproduce**
1. Go to any book that has metadata id for barnes and noble
2. Click on link for barnesnoble
3. See error

**Expected behavior**
It should link to www.barnesandnoble.com/w/#####

**Environment**
 - OS: docker
 - Calibre-Web version: 0.6.21 
 - Docker container: LinuxServer/calibre-web
 - Browser: Brave

**Comment by OzzieIsaacs** [comment]
This is true, only a view id's are detected, Barnes & Noble don't belong to these, but I can add it
