### ISSUE TITLE
health check

### ISSUE THREAD

**Issue by joglekara** [janeczku/calibre-web#2957]
**Is your feature request related to a problem? Please describe.**
Deploying as a container on AWS requires a health check route. Calibre-web doesn't have one (I don't think?)

**Describe the solution you'd like**
Add a health check route

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by OzzieIsaacs** [comment]
Without reading to deep into the aws documentation, it looks to me you can do it on your own, by just configuring the healthcheck to point to a valid endpoint (like /login), which will return a http 200 code. This should fullfill the needs of the aws service (https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-healthchecks.html?)

**Comment by ramsnerm** [comment]
This is not the solution, unfortunately. Using wget this will return 403 which is leading then to the indication of an unhealthy container.

**Comment by ramsnerm** [comment]
This is not the solution, unfortunately. Using wget this will return 403 which is leading then to the indication of an unhealthy container. Is there any other (hidden) endpoint available beside the login?

**Comment by kusold** [comment]
Adding my use case here:

I have Calibre Web setup using Proxy Authentication. Currently every request is protected by this. It would be nice to have a `/healthcheck` endpoint that responds with a 200 that I could exclude from Proxy Auth.

**Comment by grumpyoldman-io** [comment]
> Adding my use case here:
> 
> I have Calibre Web setup using Proxy Authentication. Currently every request is protected by this. It would be nice to have a `/healthcheck` endpoint that responds with a 200 that I could exclude from Proxy Auth.

Expanding on this, it would be nice if that endpoint did not include the entire application interface, but merely a JSON endpoint with the health of the server and its dependencies. Simply calling the application is already possible, but a waste of resources.
