### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by grosejon** [janeczku/calibre-web#2958]
**Describe the bug/problem**
I will randomly receive a 500 Internal Server Error. It appears randomly and the only way to get rid of it is to either restart the container, or sometimes to recreate the container.

**To Reproduce**
1. I don't really know. It seems to happen randomly.

**Logfile**
Traceback (most recent call last):
File "/app/calibre-web/cps/db.py", line 770, in generate_linked_query
read_column = cc_classes[config_read_column]
KeyError: 1
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
response = self.full_dispatch_request()
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
rv = self.dispatch_request()
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
File "/app/calibre-web/cps/usermanagement.py", line 35, in decorated_view
return login_required(func)(*args, **kwargs)
File "/lsiopy/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
return current_app.ensure_sync(func)(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 790, in index
return render_books_list("newest", sort_param, 1, page)
File "/app/calibre-web/cps/web.py", line 408, in render_books_list
entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order[0],
File "/app/calibre-web/cps/db.py", line 803, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, database, pagesize, db_filter, order, False,
File "/app/calibre-web/cps/db.py", line 810, in fill_indexpage_with_archived_books
random_query = self.generate_linked_query(config_read_column, database)
File "/app/calibre-web/cps/db.py", line 777, in generate_linked_query
query = self.session.query(database, None, ub.ArchivedBook.is_archived)
AttributeError: 'NoneType' object has no attribute 'query'

**Environment (please complete the following information):**
 - OS: Docker on Synology
 - Python version: 
 - Calibre-Web version: 0.6.21-ls245
 - Docker container: LinuxServer
 - Special Hardware: 
 - Browser: Firefox

**Additional context**
Access is via NGINX Proxy Manager and Authelia. The NGINX advanced info was updated to bypass Authelia for Kobo sync. Authentication is via reverse proxy header from Authelia. Setup will work for a day or two, and then the error pops up again.

**Comment by grosejon** [comment]
I believe I _might_ have discovered the cause. I have a boolean set up in Calibre for read status, but I forgot to add "Read" to the regular expression to ignore field. Now that I've done that, it seems to be working again. Is that something that could cause this type of problem?

**Comment by OzzieIsaacs** [comment]
Many docker user have this problem (you can search for „ AttributeError: 'NoneType' object has no attribute 'query'“ in this repository). Usually this is related to permission or access problems to the metadata.db file. I don‘t think the read status has to do with it. Changing the setting  might cause a reboot of Calibre-web and therefore a reconnect to the database. You also could click on reconnect to database in the admin section.

**Comment by grosejon** [comment]
Thanks for the reply. I have looked through the previous issues and see this comes up sometimes. Would using chmod 766 or something like that on the /books folder typically resolve this issue? Other issues seem to state that the docker user doesn't have sufficient permissions to edit the db file. That's weird though because the LinuxServer images all have the PUID and GUID env variables and that user on my system is the owner of the folder. Sorry if I am misunderstanding.

**Comment by OzzieIsaacs** [comment]
I‘m not owner of the docker container, so I‘d like you to ask for further help at the linuxserver repository, they have also a discord chat
