### ISSUE TITLE
Feature Request: Allow a drop down, with options of which version of the book to send to e-reader

### ISSUE THREAD

**Issue by NascarUk** [janeczku/calibre-web#2959]
I am always frustrated when I try to send a book e.g. PDF, EPUB to my Kindle and chapters or pages are not recognised. I always make sure to convert to AZW3 but it seems like this isn't the one being sent.

An ideal solution would be to be able to have a drop down of the versions of the book you have before sending to Kindle so that you ensure the correct one goes across. Or just a way to select the version then click the send to Kindle button.

At the moment I have been converting to only AZW3 and deleting other versions then sending. Then re-converting to PDF or EPUB so users using the web can also read my books.

**Comment by OzzieIsaacs** [comment]
The azw3 version can't be send via email to kindle readers. Amazon currently accepts epub files via email.

**Comment by NascarUk** [comment]
Ah thanks! Looks like it automatically converts it back to an EPUB and that's what is being sent out. Might have been me getting a broken EPUB! Thanks for your quick response!
