### ISSUE TITLE
Allow manual https for kobo sync URLs

### ISSUE THREAD

**Issue by skeate** [janeczku/calibre-web#2960]
**Is your feature request related to a problem? Please describe.**

I've been trying to get Kobo Sync to work. My Calibre-Web installation sits behind a Traefik reverse proxy. Traefik handles the HTTPS, so as far as Calibre-Web is concerned it's running on HTTP.

I eventually got sync kind of working; it would sync the names of books on the shelves, but whenever I tried to open them they would fail. Checking access logs (both with Calibre-Web and Traefik itself), I didn't even see it attempting to access the download url given by the `/metadata` endpoint.

I noticed that download url was `http`, though. Traefik is configured to redirect http requests to https automatically, but maybe that doesn't work for book downloads? So I tried editing the return value in https://github.com/janeczku/calibre-web/blob/master/cps/kobo.py#L348 (adding `.replace('http', 'https')` as a quick hack on the `url_for` call) and... it worked!

This is fine for me, but probably not a good general solution :)

(Also: covers don't download. I _suspect_ this is a similar issue, though I haven't found the place to muck about yet)

**Describe the solution you'd like**

Maybe there's a better way, but one thing that came to mind is a manual override for (at least) the protocol part of the URLs this generates for metadata and other kobo sync things; toggle it on and it will always use HTTPS.

**Describe alternatives you've considered**

I'm not too familiar with Flask, not sure what the options are.

**Comment by OzzieIsaacs** [comment]
You need to add the x-scheme https header to your proxy config. I will not add another manual setting to the kobo sync, as there are many people who get confused with all these settings.
