### ISSUE TITLE
Ä Ö Ü do not count as uppercase letters for Passwords

### ISSUE THREAD

**Issue by KaeTuuN** [janeczku/calibre-web#2964]
**Describe the bug/problem**
If I create a new User, the Password must have an uppercase letter and  the letters Ä Ö Ü do not count.

**To Reproduce**
1. Create a new user
2. Set initial Password to Änder!M1ch (German for "Change me")
3. Error: "Use at least one uppercase character" is shown

**Logfile**
Nothing here

**Expected behavior**
The Password should be accepted.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10/Raspberry Pi OS]
 - Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
 - Calibre-Web version: 0.6.21 - c45188beb22adc5416bb8fd73fa23bf5270f7759 - 2023-10-21T12:40:32+02:00
 - Docker container: LinuxServer
 - Special Hardware: Standard x86_64 Hardware
 - Browser: Actual Firefox 

**Additional context**
Nothing here

**Comment by OzzieIsaacs** [comment]
Yep, that's true, I didn't think on this:
https://github.com/janeczku/calibre-web/blob/3aa75ef4a7ce240bf9c60ac885b682986fa93e11/cps/helper.py#L698

**Comment by KaeTuuN** [comment]
I'm not that good with writing RegEx, but they should include the following Characters for german users:
config.config_password_lower = a-z ä ö ü ß
config.config_password_upper = A-Z Ä Ö Ü

```
config.config_password_special:
            verify += "(?=.*?[^A-Za-z\s0-9])"
```
If I understand that right ä ö ü Ä Ö Ü ß are all counted as speacial Characters at the Moment?

From my point of view there are two valid Options:
1. Change the RegEx to catch the other Characters.
2. Add a warning, that these Characters are counted as Special Characters.

**Comment by OzzieIsaacs** [comment]
Solution (line 701) is: 
match = re.match(verify, unidecode.unidecode(check_password))

**Comment by OzzieIsaacs** [comment]
As usual easy implemetation, boring testing, takes some time to publish, I have 2 other things to finsih in the code

**Comment by OzzieIsaacs** [comment]
Finally...
Turned out to be a bigger issue, the newest commit solves the issue (needs additional installation of regex module)
