### ISSUE TITLE
Generic OIDC support

### ISSUE THREAD

**Issue by gianmarcomurru** [janeczku/calibre-web#2965]
It would be super nice to have a generic OIDC support along Google/GitHub oAuth! This could work with Authelia, Authentik and other SSO providers

**Comment by pto199** [comment]
oh man this is sad news.  I use Authentik, not google or Git Oauth

**Comment by danieljkemp** [comment]
Very disappointing. This isn't a entirely new login flow that would need a large amount of code to support it. It is a request to extend usage of https://oauthlib.readthedocs.io/en/latest/oauth2/endpoints/endpoints.html to a generic oidc beyond google/github. Selfhosting Authentik/Keycloak/Dex/Authy/etc is getting more and more common. There seems to be quite a few open issues relating to reverse-proxy auth config that likely only exist because of this feature gap.

**Comment by RChesterton** [comment]
This is a shame, as OIDC is a standard built on top of OAuth 2.0 and shouldn't need maintenance once implemented.

Not being able to integrate with industry-standard authentication, such as Microsoft Entra ID means I am having to put Calibre-Web behind a reverse proxy and Cloudflare Zero Trust, then authenticate with MS and THEN also log into Calibre-Web.

Is there at least a way to disable the login requirement on Calibre-Web when using it behind a reverse proxy and other authentication, so the double-login isn't needed?

**Comment by ttaeschn** [comment]
I extended the OAuth-Implementation with support for generic oauth providers.
@RChesterton, @pto199, @danieljkemp, @gianmarcomurru: If you are brave enough checkout https://github.com/ttaeschn/calibre-web. 

That version is tested with keycloak. 
Feedback is welcome.

**Comment by jdwill916** [comment]
It looks like there is a pull request to make the oauth implementation generic #3429. Hopefully this is merged so all of us can enjoy oauth.

**Comment by nprime496** [comment]
@OzzieIsaacs my G, people make mistakes, and you can still change your mind. Nothing wrong with that. You might have thought restricting this functionality was a good idea to stay aligned with the vision, but this one looks like a plain error in your decision process.

I use this at home and just want to have my own SSO. If the goal was to prevent other login methods, you wouldn’t have implemented the existing OAuth options. Keeping those but rejecting this feels inconsistent.

It’s a logical and rational extension of what already exists, so maybe it’s worth reconsidering.

For anyone interested, this fork by @gelbphoenix has the functionality: https://github.com/gelbphoenix/autocaliweb
