### ISSUE TITLE
Question - What is the technical limit for Calibre-Web to upload files?

### ISSUE THREAD

**Issue by refy02** [janeczku/calibre-web#2966]
**Describe the bug/problem**
I'd like to upload 20.000 eBooks at once, but this amount seems to be too much for Calibre-Web since it's giving me the error, that the upload size might be too big. Is there a way to upload masses of eBooks at once? What is the technical limit (in MBs or files) for Calibre-Web to upload books?

Thanks for any response
Fynn

**Comment by OzzieIsaacs** [comment]
With the default tornado Webserver it‘s 200mb, with the optional gevent it‘s unlimited. But currently there is a randomly occurring bug, which causes the upload to fail. My recommendation is to use the calibre desktop app to upload so many books at once

**Comment by refy02** [comment]
@OzzieIsaacs 
Thanks for your quick response! Can I use the Calibre Desktop app to upload books and use/see them in my calibre-web instance?  Can Calibre Desktop write into Calibre-Webs underlying Database?

**Comment by OzzieIsaacs** [comment]
Actually it‘s the calibre database which is used by calibre-web. So yes the database is compatible. Justdon‘t access the database by both programs at the same time
