### ISSUE TITLE
Can't even finish initial setup

### ISSUE THREAD

**Issue by teflontoni** [janeczku/calibre-web#297]
**Internal Server Error**
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

>  in execute
>    return self._execute_text(object, multiparams, params)
> File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 870, in _execute_text
>    statement, parameters
>  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
>    context)
>  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1159, in >_handle_dbapi_exception
>    exc_info
>  File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
>    reraise(type(exception), exception, tb=exc_tb)
>  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
>    context)
>  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
>    cursor.execute(statement, parameters)
>OperationalError: (OperationalError) no such table: custom_columns 'SELECT id, datatype FROM >custom_columns' ()
>ERROR:tornado.access:500 POST //config (::1) 115.78ms

app.db is created, but then the server crashes. and won't start till I delete app.db

Centos 7 with Python 2.7.5

I really want this to work, as it looks beautiful. If you need any further logs, etc. let me know.

Thanks for helping me out.

**Comment by OzzieIsaacs** [comment]
Looks like errors in the calibre db. Similar to #216. Could you please try to repair the database in calibre.

**Comment by teflontoni** [comment]
Calibre says all is well.

Just to be sure calibre-web searches for the "normal" library, I don't need to fire up the internal Calibre Server, right?

**Comment by teflontoni** [comment]
Ok, for reasons unknown my Library mirror had a 0kb metadata.db.
Now it seems to work. Sorry for the commotion.

**Comment by KunalGautam** [comment]
Pardon me for replying to a closed thread, but I was having same problem. I just deleted metadata.db from /books folder and it worked perfectly.
