### ISSUE TITLE
Unable to use alias on Synology Web Station

### ISSUE THREAD

**Issue by michiel-theelen** [janeczku/calibre-web#2974]
**Describe the bug/problem**
When setting up Calibre-Web using Synolog's container manager, it works fine when i use a port, but it doesn work when im using an alias instead. Two things happen:

1. No css is loaded so the page looks awful
2. Links ignore the alias, so clicking any link will return 404. For example instead of example.com/books/book it goes directly to example.com/book.

**To Reproduce**
1. Use Synology
2. Configure Calibre-Web with Container Manager
3. Setup an alias with Synology Web Station

**Logfile**
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

**Expected behavior**
It should be able to use aliases correctly.

**Screenshots**
If applicable

**Environment (please complete the following information):**
 - OS: MacOs
 - Python version: Python
 - Calibre-Web version: 0.6.21
 - Docker container: LinuxServer
 - Special Hardware: Synology
 - Browser: Chrome 120.0.6099.199

**Comment by OzzieIsaacs** [comment]
I have no idea what the alias means, but from the symptoms I can tell you, you need to set header values as described in the wiki section setup reverse proxy

**Comment by OzzieIsaacs** [comment]
If you ha a look at the generated links they point all to the root directory. You need to add a header value:
X-Script-Name   /books

as described in the wiki: https://github.com/janeczku/calibre-web/wiki/Setup-Reverse-Proxy#login-via-header-from-upstream-authentication-source

I have no idea how this is done on synology and or docker containers. What you are doing on the web-UI somehow for sure involves some sort of reverse proxy

**Comment by themichiel** [comment]
Thanks.

**Comment by OzzieIsaacs** [comment]
Maybe you need to set all header values which are described in the wiki. You also could search for synology in the issues, there are several question regarding it, maybe there is something useful among it

**Comment by pbernier99** [comment]
Have you found a solution?

I'm having similar issue regarding synonogy docker and http headers.
