### ISSUE TITLE
Cant import newly added ebooks

### ISSUE THREAD

**Issue by KeepCreatingOnline** [janeczku/calibre-web#2976]
How are new books added to the library? They are in the correct directory but there seems to be no way to refresh the database or schedule a task to look for new books...

**Comment by OzzieIsaacs** [comment]
Please activate upload in the admin section feature configuration. Please also make sure the current user has upload permissions.
A upload button should appear then. Upload the books. Alternatively use calibre itself to import the books (recommended for many books) 
Please do not have the books in folders below the database file during import/upload, this could cause problems
