### ISSUE TITLE
no books in Calibre-web

### ISSUE THREAD

**Issue by Geezus42** [janeczku/calibre-web#2979]
**Describe the bug/problem**
I ran the LS Calibre container and generated the DB, then shut it down. Then I setup the LS Calibre-web container and pointed it to the directory with the DB. It says it connects to the DB successfully, but it shows no books. I do not see relevant errors in the logs. I have done a tome of searching, including all of the Calibre-web issues here, but have not found a solution. 

**To Reproduce**
I followed the steps from the documentation. 

**Logfile**
[Calibre-Web log viewer.log](https://github.com/janeczku/calibre-web/files/13965972/Calibre-Web.log.viewer.log)
[Calibre-Web debug pack.zip](https://github.com/janeczku/calibre-web/files/13965974/Calibre-Web.debug.pack.zip)

**Expected behavior**
Books imported by Calibre should be shown in Calibre-web

**Environment (please complete the following information):**
 - OS: NixOs
 - Python version: python3.10
 - Calibre-Web version: Stable version: {'version': '0.6.21'}
 - Docker container: LinuxServer (lscr.io/linuxserver/calibre-web:latest)
 - Special Hardware: Skullcanyon Nuc
 - Browser: Arc Version 1.25.1 (45028) Chromium Engine Version 120.0.6099.216

**Additional context**
No reverse proxy. Database is on my ZFS array while the container runs on my root BTRFS disk. This is not a problem for other containers.

**Comment by OzzieIsaacs** [comment]
How did you import the books into the db?

**Comment by Geezus42** [comment]
Using the LS Calibre container.

**Comment by OzzieIsaacs** [comment]
The database you imported it to is not the database calibre-web sees

**Comment by Geezus42** [comment]
I thought Calibre wrote the Database into the same directory all the books are stored in?

**Comment by Geezus42** [comment]
Sounds like the metadata.db that somehow got created in /media/Books is not the real DB. I have no idea where it came from. I just found another under /opt/calibre/Calibre Library. So I will try pointing there. Not sure if I'm going to mount it as a volume, or symlink to /media/Books.

**Comment by OzzieIsaacs** [comment]
My experiences:
1.) If books are imported to calibre they are showing up in calibre-web
2.) Docker user reporting problems are always confused about files inside and outside of the container

**Comment by Geezus42** [comment]
I understand what is inside and outside of the container. Both /media/Books and /opt/calibre are external volume mounts.

**Comment by OzzieIsaacs** [comment]
If have no idea about this docker stuff, I only report my experiences

**Comment by Geezus42** [comment]
I think I just have a misunderstanding of how Calibre manages the library/db.

**Comment by Geezus42** [comment]
for other's reference

Calibre:
```
    volumes:
      - /opt/calibre:/config
      - /media/Books:/books
```

Calibre-web:
```
    volumes:
     - /opt/calibre-web:/config
     - /opt/calibre/Calibre Library:/books
```
     
     Sorry for bugging you with container stuff. Thank you for the help.
