### ISSUE TITLE
Feature Request: Enable admins to create download options based on custom URL scheme

### ISSUE THREAD

**Issue by ethanxrosen** [janeczku/calibre-web#2982]
I think this would open up a lot better usability for people using calibre-web in combination with client apps on their phones or other devices.

This came up for me specifically when attempting to download an audiobook I had stored in calibre-web to a popular iOS app BookPlayer. Currently I need to download the audiobook from calibre using a browser, open up BookPlayer, find the book among the folders on my phone, import the download, and after it is imported a duplicate file remains in my downloads folder, which I should remember to delete lest it takes up storage. This is not so bad but doesn't really pass the "easy for older family members" test.

If, say next to 'send to kindle' there was a custom option I could define named 'Send to BookPlayer' with a URL something like below

`bookplayer://download?url="https://direct-download-link-to-your-file-with-http-auth-or-access-token.m4b"`

in 1 click the book would load to the app I want. Sure there are other apps that could make use of a similar strategy too!

**Comment by OzzieIsaacs** [comment]
I thought on it and I came to the conclusion this generates a lot of effort for a single usecase (I have agreed to similar requests too many times in the past and now regret it). 
Only users with iOS devices would have a benefit of it, so I need to find a way to hide the button if the page is not accessed via iOS (parse the user agent string, this would generate constant work on it, as Apple changes the string from time to time). 
The button would be present if the user doesn't have the app installed, so I need a config option as you already suggested it. 
Furthermore as you already implied people will constantly ask for new send to xxx buttons
Currently downloads are protected by the calibre-web login system, as you already found out we need a new mechanism to bypass it by generating unique download links which expire after some time to make it still safe (needs new database, background cleanup routines, extensive testing...)
So, no
