### ISSUE TITLE
Would it be possible to choose which categories appear in the OPDS catalog?

### ISSUE THREAD

**Issue by onnyyonn** [janeczku/calibre-web#2983]
**Is your feature request related to a problem? Please describe.**
Currently, the OPDS catalog includes many categories that I have no use for. For example, Hot Books, Top Rated Books, Random Books, etc. Most of these categories appear at the beginning of the catalog, pushing the ones I need, down. It would be useful if we could customize what appears in the OPDS, the same way we can customize the web interface.

**Describe the solution you'd like**
I think the perfect solution for me would be to have some admin settings to choose what categories appear in the OPDS catalog.

**Additional context**
I understand that this is not a critical feature that needs immediate attention. But if you consider it for a future release, that would be great.

**Comment by aqxa1** [comment]
Even better would be if you could just specify a single shelf to expose. In KOReader for example, you have to move to the second page, then tap "Shelves", then the name of the shelf.  And if you have many shelves that would mean additional taps on top of that, which doesn't feel great on slow e-readers.

This could be reduced down to zero taps by just exposing the contents of the chosen shelf. Nevertheless, giving the option to hide categories would be a nice improvement on its own.

**Comment by Tronicgg** [comment]
This would be great. I’m in a similar position to you, except I manage a thousands library so shelves is not an option. Although tried this method and indeed works.

**Comment by OzzieIsaacs** [comment]
I've copied the settings from the web-UI to the opds catalog, so if something is hidden in the Web UI it's also hidden in the opds catalog (I will not make separate settings for OPDS catalog and I will not make the feature able to be switched on/off)

**Comment by OzzieIsaacs** [comment]
It's avaliable in the newest nightly build
