### ISSUE TITLE
Unable to reset Kobo sync for other users

### ISSUE THREAD

**Issue by deviantintegral** [janeczku/calibre-web#2993]
**Describe the bug/problem** 

When logged in as an administrator, you can view other user profiles and interact with them. The `Force full kobo sync` button has a check against the currently logged in user, not the user profile that is being viewed:

https://github.com/janeczku/calibre-web/blob/184ce23351d8c11fc42845f5559d57959cb9cf91/cps/admin.py#L920

**To Reproduce**

1. Create a second user and set up Kobo syncing
2. Browse their user profile as the first user, and click the `Force full kobo sync` button
3. Note that it returns with `0 sync entries deleted`

**Expected behaviour**

Admins should be able to reset sync for other users, _or_ the button should be disabled with a message that you have to be logged in as that user to reset sync.

**Environment (please complete the following information):**

 - OS: Alpine / Docker
 - Python version: 3.x
 - Calibre-Web version: 0.6.21
 - Docker container: [LinuxServer]:
 - Browser: Firefox 123.0b3 (this isn't a browser specific bug)

**Comment by OzzieIsaacs** [comment]
Thanks for the detailed reporting

The newest nightly version should fix the problem.

**Comment by deviantintegral** [comment]
Excellent, thank you!
