### ISSUE TITLE
Database Error: attempt to write a readonly database.

### ISSUE THREAD

**Issue by TheCyberWeaver** [janeczku/calibre-web#2996]
**Describe the bug/problem** 

When I was trying to upload files to the library, I get this error

> Database Error: attempt to write a readonly database.

I created a folder under /app, and stored the metadata.db under this folder

I have even given the metadata.db the permission of 777 but it is still not working

**Environment:**

 - OS: Ubuntu 
 - Python version: 3.10.12
 - Docker container: Linux Server
 - Special Hardware: cloud VPS

**Comment by OzzieIsaacs** [comment]
Like all the dozens of docker user having same/similar issues this is a permission problem
