### ISSUE TITLE
So after setup, again errors are thrown :/

### ISSUE THREAD

**Issue by teflontoni** [janeczku/calibre-web#300]
>    rv = self.handle_user_exception(e)
>  File "/opt/weblibrary/vendor/flask/app.py", line 1517, in handle_user_exception
>    reraise(exc_type, exc_value, tb)
>  File "/opt/weblibrary/vendor/flask/app.py", line 1612, in full_dispatch_request
>    rv = self.dispatch_request()
>  File "/opt/weblibrary/vendor/flask/app.py", line 1598, in dispatch_request
>   return self.view_functions[rule.endpoint](**req.view_args)
>  File "/opt/weblibrary/vendor/flask_login/utils.py", line 228, in decorated_view
>    return func(*args, **kwargs)
>  File "/opt/weblibrary/cps/web.py", line 1025, in index
>    entries, random, pagination = fill_indexpage(page, db.Books, True, db.Books.timestamp.desc())
>  File "/opt/weblibrary/cps/web.py", line 523, in fill_indexpage
>    random = db.session.query(db.Books).filter(common_filters())\
>  File "/opt/weblibrary/cps/web.py", line 517, in common_filters
>    return and_(lang_filter, ~content_rating_filter)
>  File "<string>", line 2, in and_
>  File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/elements.py", line 1835, in and_
>    return cls._construct(operators.and_, True_, False_, *clauses)
>  File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/elements.py", line 1783, in _construct
>    return clauses[0].self_group(against=operators._asbool)
>AttributeError: 'bool' object has no attribute 'self_group'
>ERROR:tornado.access:500 GET / (91.57.208.147) 14.49ms
>WARNING:tornado.access:404 GET /favicon.ico (91.57.208.147) 4.71ms

That's in the log file beforehand:

[2017-08-28 08:46:20,291] {/opt/weblibrary/vendor/flask/app.py:1560} ERROR - Exception on / [GET]

CentOS7 python 2.7.5

I'm more than bad with understanding python errors...

**Comment by jkrehm** [comment]
In the `common_filters` function in `web.py`, try changing
```
    else:
        lang_filter = True
```
to
```
    else:
        lang_filter = true()
```
See if that resolves the issue. It's not a problem in my environment, but I know I had a problem with the `content_rating_filter` filter when I first wrote it where I couldn't use `False` and had to use `sqlalchemy.false()` instead.

**Comment by teflontoni** [comment]
Ok,
another obstacle out of the way...
boy, I hope that's it for now.

Thanks for the help.
