### ISSUE TITLE
[Request] Sort by date added also for shelves

### ISSUE THREAD

**Issue by enaloha** [janeczku/calibre-web#3003]
**Is your feature request related to a problem? Please describe.**
I love how the books are sorted by Date added as default. However, this does not seem to apply to books added to a shelf and I wish it would behave just like the admin view. Right now, I have to go to the shelf, activate manual sort, then scroll all the way down to select the book and drag it all the way back up. And finally scroll all the way down to Save it.

**Describe the solution you'd like**
Simply mirror the behavior for the full book list also for the shelves. 

**Describe alternatives you've considered**
Alternatively, add a sort button to allow sorting by date added to all views/shelves

**Additional context**
not really needed.

Thank you for making this amazing utility!!!

**Comment by OzzieIsaacs** [comment]
So the request is to have a button for "date the book was added to shelf"
Because the button, book date and and added to calibre database are already present.
![grafik](https://github.com/user-attachments/assets/a8ae0a43-187e-45c9-a02f-d41876b30e3f)

**Comment by enaloha** [comment]
Thanks for the clarification. The problem is that the sorting when selecting either of the arrows you show never reflects the "date added". The first arrow theoretically should sort according to the "date added", but I don't think it does. If I add a book to the shelf, it ends up at the very bottom of the list and I have to manually drag it up all the way yo the top to get it to show up first. I have no idea what exactly the the second arrow's sorting does. It does not seem to sort according to "date added". Also, why does the Enable Change Order button not stay enabled once enabled?

**Comment by OzzieIsaacs** [comment]
The Date added button sorts according to date added to the database (I’ll additionally check if there wrong)

**Comment by enaloha** [comment]
And it actually works fine for the admin and the whole book database. It just does not work for the shelves. I will try to verify this again since I last tried it, but it always just ends up at the bottom of the list in every shelf I add a book to.

**Comment by enaloha** [comment]
thank you, you are amazing!!!

**Comment by OzzieIsaacs** [comment]
Please check the newest nightly version, the button status should now be saved

**Comment by enaloha** [comment]
> Please check the newest nightly version, the button status should now be saved

Just updated and this is even better as the change order buttons are enabled by default. This is excellent. 
Mahalo from Hawaii
