### ISSUE TITLE
Rebuild the Index/Database

### ISSUE THREAD

**Issue by Ziglar1** [janeczku/calibre-web#3006]
Hello,
i have installed Calibre-web into a docker on synology.
after i installed everything correctly i noticed that in my folder with books there were folders with only a cover.jpg and metafata.opf (this was my fault).
i ran a script to remove all folders that had only these files (Thousends of folders).
although they are gone now and i have only folders with books, Calibre-web is still showing those books.

how can i make Calibre-web check the existance of every folder or rebuild the entire index ?

(re-installing is not an option due to several kobo-readers syncing)

**Comment by OzzieIsaacs** [comment]
Please run a library check with calibre desktop program itself. Calibre-web is not capable to do a library scan
