### ISSUE TITLE
Read in Browser -- doesn't load the embed font in epub!!!

### ISSUE THREAD

**Issue by gwd0715** [janeczku/calibre-web#3009]
**Describe the bug/problem** 
Read in Browser doesn't load the embed font in epub!!!

**To Reproduce**
Here's a epub book:

CSS file defined 3 font-family with local embed font.
<img width="720" alt="image" src="https://github.com/janeczku/calibre-web/assets/17922721/9d951846-c951-4860-b32a-45a337656ef1">

Here are the 3 fonts embed in epub file.
<img width="342" alt="image" src="https://github.com/janeczku/calibre-web/assets/17922721/7367bf10-6d64-44de-95d6-1d6a1cf6babd">

But when you open this book in calibre-web and read in Browser:
![image](https://github.com/janeczku/calibre-web/assets/17922721/3609a12a-e4de-4241-a0ff-6a2ae2be5383)
the fonts are not loaded in 

Open the console, it says:
<img width="1294" alt="image" src="https://github.com/janeczku/calibre-web/assets/17922721/bb82a124-89f4-46b5-8005-322e0377f196">

**Environment (please complete the following information):**

 - OS: MacOS Sonoma 14.2.1
 - Python version: 3.11
 - Calibre-Web version: 0.6.21
 - Docker container: LinuxServer
 - Browser: Chrome and Edge

**Comment by OzzieIsaacs** [comment]
Please update to the newest nightly version

**Comment by OzzieIsaacs** [comment]
#3005

**Comment by gwd0715** [comment]
Thank you so much
