### ISSUE TITLE
Leading spaces are not being trimed on the Publisher & Identifiers field.

### ISSUE THREAD

**Issue by T-prog3** [janeczku/calibre-web#3015]
**Describe the bug/problem** 
I did just notice that space characters at the beginning of the `Publisher` field are not being trimmed when you save. This creates an issue where you can have `MyBookPublisher` and ` MyBookPublisher` if you don't notice the space yourself.

This issue affects both `Identifiers` fields as well but here you also have the additional problem of ending spaces not being removed. All other fields works as the should.

**Comment by OzzieIsaacs** [comment]
From reading the code I can't see the issue (and also not reproduce for publishers), for identifiers the problem is there

**Comment by T-prog3** [comment]
I got this issue by copy/paste the publisher data from amazon. 
![img1](https://github.com/janeczku/calibre-web/assets/74016497/97fee515-0a23-497a-84b8-d25ab880a9de)

In Calibre-Web it becomes this when i paste:
![img2](https://github.com/janeczku/calibre-web/assets/74016497/95193ce1-1fb4-48c9-8b26-d299525209e7)

When i save it turns into this:
![img3](https://github.com/janeczku/calibre-web/assets/74016497/bd454b2c-c4b3-40c5-a119-448a906903c2)

In this state with a space as first char it can't be found in the `Publishers list` in the side menu and it will be treated as a different publisher. I can thereby have 100 books of publisher `Ecco` and lets say 5 `"Space"Ecco` and they will have 2 separate lists when you click on the publisher name at the books page.

**Comment by T-prog3** [comment]
Update:
I did a character lookup of the content when i paste in Calibre-Web and it turns out that it's not just a space but another character as well.

This is the Unicode character content of it:

> U+0020 : SPACE [SP]
U+200E : LEFT-TO-RIGHT MARK [LRM]
U+0020 : SPACE [SP]
U+0045 : LATIN CAPITAL LETTER E
U+0063 : LATIN SMALL LETTER C
U+0063 : LATIN SMALL LETTER C
U+006F : LATIN SMALL LETTER O

**Comment by OzzieIsaacs** [comment]
I improved the removal of unicode spaces. In the newest nightly commit, these characters are removed
