### ISSUE TITLE
Incorrect tags on LubimyCzytac

### ISSUE THREAD

**Issue by Dinth** [janeczku/calibre-web#3016]
Hi. Firstly, many, many thanks for adding import from LC, this will save me hours and hours of manually copying data from LC to Calibre-Web.
I have noticed one tiny glitch - The category name is imported to Calibre-Web as a tag. This would be fine or even desired with most categories, but not with "fantasy, science fiction" category - a book is either fantasy or science fiction, very rarely both, but Calibre adds both genres as separate tags. Since not every category has this problem and in other categories adding the category as a name may be desired, i will leave it up to you if you want to fix it - just letting you know.
The "real" tags are actually underneath (but missing on many books):
![image](https://github.com/janeczku/calibre-web/assets/313674/9f7aef93-7563-4663-b380-1bfbf9f84bd2)

PS. I will use this opportunity for one tiny feature request - could Calibre Web also import translator's name to the description, similarly as it does with number of pages and date of publishing?

**Comment by OzzieIsaacs** [comment]
Please update to newest nighty version, it should work as suggested then (and please also check my translation of "translator", I'm digging in the dark regarding polish language)

**Comment by Dinth** [comment]
Hi. Both the tags and "Translator:" seem to work fine. But i have noticed that with the :nighly version the majority of my books cannot be found in LubimyCzytac database for fetching data ("Search error" message)
