### ISSUE TITLE
Using "count()" to determine the total number in `Pagination`

### ISSUE THREAD

**Issue by Yxa2111** [janeczku/calibre-web#3021]
at func `fill_indexpage_with_archived_books`, Pagination use `select *` instead of `selct count(*)` to determine the total number of books.

```
            pagination = Pagination(page, pagesize,
                                    len(query.all()))
```

use `query.count()` may be better?

```
                pagination = Pagination(page, pagesize,
                                        query.count())
```

I have approximately 25k books on calibre-web, the query cost decrease from about 500ms to 100ms.

**Comment by OzzieIsaacs** [comment]
Thanks for reporting.
It's fixed in the nightly build
