### ISSUE TITLE
FEAT: Add upload from url (instead of from disk) option

### ISSUE THREAD

**Issue by deafmute1** [janeczku/calibre-web#3029]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Most of the time I have a book that is available over a public http(s) url that I have to download to disk then immediately upload to calibre-web. Would be nice (and hopefully/probably not too much effort) to be able to pass a url that calibre itself downloads.

adding this issue to track interest/potential implementation but I may submit a PR for it myself when I get time. 

**Describe alternatives you've considered**
Currently works fine just extra step of downloading to disk.

**Additional context**
N/A

**Comment by OzzieIsaacs** [comment]
The software is now already very complex, I don't want to add more complexitiy
