### ISSUE TITLE
calibre-web app on asus nas

### ISSUE THREAD

**Issue by essegi62** [janeczku/calibre-web#3030]
Hi,
I installed calibre-web app on a asustor nas AT6207T. It is available on app central. It has automatically created a folder /Calibre and a sub-folder /books. I put there my books and the calibre library data. Calibre-Web interface is populated with the books, but there are no covers, and most of all I cannot open them in the epub reader. 
![calibre-web cover not available](https://github.com/janeczku/calibre-web/assets/86471491/35c7c680-4cc6-448c-bc1a-c1b99577118e)

It seems to be an issue related to permissions, according to this link https://github.com/janeczku/calibre-web/issues/1442.
I would be grateful for some indication about how to change permissions. 
Thanks a lot

**Comment by OzzieIsaacs** [comment]
Please ask for help from the provide of the app or form asustor, I can only support calibre-web itself
