### ISSUE TITLE
Multi volume series hard to distinguish

### ISSUE THREAD

**Issue by tknx** [janeczku/calibre-web#3041]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I have a series where the title is the same but the volume number at the end is cut off

**Describe the solution you'd like**

Calibre-web would preferentially display distinguishing parts of the title. 

**Describe alternatives you've considered**

None really. Not going to rename all my books to make it work. 

**Additional context**

Without looking at the covers tell me which book is next. 

![image](https://github.com/janeczku/calibre-web/assets/29260341/bfefea36-2213-4fd5-82f3-fcd232466563)

**Comment by eurotransient** [comment]
Using the the Series and Series ID metadata fields will solve this for you.

**Comment by OzzieIsaacs** [comment]
The solution from @eurotransient is also my preferred solution to this.
Another option would be to change nchars=xx in the following line to ab bigger number:
https://github.com/janeczku/calibre-web/blob/87b82424d54c8d08e125b42d541db1dcdfcefe7b/cps/jinjia.py#L52

On some places the title is shortened to a different umber of characters, then please search for the line in the templates folder and change |shortentitle to |shortentitle(xx)
