### ISSUE TITLE
Installation fail: "Legacy install failure on netifaces"

### ISSUE THREAD

**Issue by cgwers** [janeczku/calibre-web#3043]
Hi,

Yep, I can believe it's a heck of a lot of work. I added my log. 

Windows 10, Ryzen 5, 32GB
---------------------------
D:\>pip install calibreweb
Collecting calibreweb
  Downloading calibreweb-0.6.21-py3-none-any.whl (7.6 MB)
     ---------------------------------------- 7.6/7.6 MB 34.5 MB/s eta 0:00:00
Collecting flask-wtf<1.2.0,>=0.14.2
  Downloading flask_wtf-1.1.2-py3-none-any.whl (12 kB)
Collecting advocate<1.1.0,>=1.0.0
  Downloading advocate-1.0.0-py2.py3-none-any.whl (34 kB)
Collecting lxml<5.0.0,>=3.8.0
  Downloading lxml-4.9.4-cp310-cp310-win_amd64.whl (3.8 MB)
     ---------------------------------------- 3.8/3.8 MB 48.4 MB/s eta 0:00:00
Collecting SQLAlchemy<2.0.0,>=1.3.0
  Downloading SQLAlchemy-1.4.52-cp310-cp310-win_amd64.whl (1.6 MB)
     ---------------------------------------- 1.6/1.6 MB 51.0 MB/s eta 0:00:00
Collecting Flask<2.4.0,>=1.0.2
  Downloading flask-2.3.3-py3-none-any.whl (96 kB)
     ---------------------------------------- 96.1/96.1 KB ? eta 0:00:00
Collecting iso-639<0.5.0,>=0.4.5
  Using cached iso-639-0.4.5.tar.gz (167 kB)
  Preparing metadata (setup.py) ... done
Collecting Flask-Login<0.6.3,>=0.3.2
  Downloading Flask_Login-0.6.2-py3-none-any.whl (17 kB)
Collecting Werkzeug<3.0.0
  Downloading werkzeug-2.3.8-py3-none-any.whl (242 kB)
     ---------------------------------------- 242.3/242.3 KB ? eta 0:00:00
Collecting unidecode<1.4.0,>=0.04.19
  Downloading Unidecode-1.3.8-py3-none-any.whl (235 kB)
     ---------------------------------------- 235.5/235.5 KB ? eta 0:00:00
Requirement already satisfied: requests<2.32.0,>=2.28.0 in d:\python\python310\lib\site-packages (from calibreweb) (2.31.0)
Collecting tornado<6.4,>=6.3
  Downloading tornado-6.3.3-cp38-abi3-win_amd64.whl (429 kB)
     ---------------------------------------- 429.2/429.2 KB ? eta 0:00:00
Collecting PyPDF<3.16.0,>=3.0.0
  Downloading pypdf-3.15.5-py3-none-any.whl (272 kB)
     ---------------------------------------- 272.6/272.6 KB ? eta 0:00:00
Collecting APScheduler<3.11.0,>=3.6.3
  Downloading APScheduler-3.10.4-py3-none-any.whl (59 kB)
     ---------------------------------------- 59.3/59.3 KB ? eta 0:00:00
Collecting Wand<0.7.0,>=0.4.4
  Downloading Wand-0.6.13-py2.py3-none-any.whl (143 kB)
     ---------------------------------------- 143.8/143.8 KB ? eta 0:00:00
Collecting Flask-Babel<3.2.0,>=0.11.1
  Downloading flask_babel-3.1.0-py3-none-any.whl (9.6 kB)
Collecting Babel<3.0,>=1.3
  Downloading Babel-2.15.0-py3-none-any.whl (9.6 MB)
     ---------------------------------------- 9.6/9.6 MB 51.2 MB/s eta 0:00:00
Collecting pytz>=2016.10
  Downloading pytz-2024.1-py2.py3-none-any.whl (505 kB)
     ---------------------------------------- 505.5/505.5 KB 31.0 MB/s eta 0:00:00
Collecting Flask-Limiter<3.5.0,>=2.3.0
  Downloading Flask_Limiter-3.4.1-py3-none-any.whl (28 kB)
Collecting chardet<4.1.0,>=3.0.0
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
     ---------------------------------------- 178.7/178.7 KB ? eta 0:00:00
Collecting Flask-Principal<0.5.1,>=0.3.2
  Using cached Flask-Principal-0.4.0.tar.gz (5.5 kB)
  Preparing metadata (setup.py) ... done
Collecting ndg-httpsclient
  Downloading ndg_httpsclient-0.5.1-py3-none-any.whl (34 kB)
Collecting pyopenssl
  Downloading pyOpenSSL-24.1.0-py3-none-any.whl (56 kB)
     ---------------------------------------- 56.9/56.9 KB 2.9 MB/s eta 0:00:00
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting urllib3<2.0,>=1.22
  Downloading urllib3-1.26.18-py2.py3-none-any.whl (143 kB)
     ---------------------------------------- 143.8/143.8 KB ? eta 0:00:00
Collecting netifaces>=0.10.5
  Downloading netifaces-0.11.0.tar.gz (30 kB)
  Preparing metadata (setup.py) ... done
Collecting pyasn1
  Downloading pyasn1-0.6.0-py2.py3-none-any.whl (85 kB)
     ---------------------------------------- 85.3/85.3 KB ? eta 0:00:00
Collecting tzlocal!=3.*,>=2.0
  Downloading tzlocal-5.2-py3-none-any.whl (17 kB)
Collecting Jinja2>=3.1.2
  Downloading Jinja2-3.1.3-py3-none-any.whl (133 kB)
     ---------------------------------------- 133.2/133.2 KB ? eta 0:00:00
Collecting click>=8.1.3
  Downloading click-8.1.7-py3-none-any.whl (97 kB)
     ---------------------------------------- 97.9/97.9 KB ? eta 0:00:00
Collecting itsdangerous>=2.1.2
  Downloading itsdangerous-2.2.0-py3-none-any.whl (16 kB)
Collecting blinker>=1.6.2
  Downloading blinker-1.8.1-py3-none-any.whl (9.5 kB)
Collecting ordered-set<5,>4
  Downloading ordered_set-4.1.0-py3-none-any.whl (7.6 kB)
Requirement already satisfied: typing-extensions>=4 in d:\python\python310\lib\site-packages (from Flask-Limiter<3.5.0,>=2.3.0->calibreweb) (4.7.1)
Collecting limits>=2.8
  Downloading limits-3.11.0-py3-none-any.whl (45 kB)
     ---------------------------------------- 45.2/45.2 KB ? eta 0:00:00
Requirement already satisfied: rich<14,>=12 in d:\python\python310\lib\site-packages (from Flask-Limiter<3.5.0,>=2.3.0->calibreweb) (13.5.2)
Collecting wtforms
  Downloading wtforms-3.1.2-py3-none-any.whl (145 kB)
     ---------------------------------------- 146.0/146.0 KB ? eta 0:00:00
Requirement already satisfied: idna<4,>=2.5 in d:\python\python310\lib\site-packages (from requests<2.32.0,>=2.28.0->calibreweb) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in d:\python\python310\lib\site-packages (from requests<2.32.0,>=2.28.0->calibreweb) (2023.7.22)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\python\python310\lib\site-packages (from requests<2.32.0,>=2.28.0->calibreweb) (3.2.0)
Collecting greenlet!=0.4.17
  Downloading greenlet-3.0.3-cp310-cp310-win_amd64.whl (292 kB)
     ---------------------------------------- 292.3/292.3 KB ? eta 0:00:00
Collecting MarkupSafe>=2.1.1
  Downloading MarkupSafe-2.1.5-cp310-cp310-win_amd64.whl (17 kB)
Requirement already satisfied: colorama in d:\python\python310\lib\site-packages (from click>=8.1.3->Flask<2.4.0,>=1.0.2->calibreweb) (0.4.6)
Collecting packaging<25,>=21
  Downloading packaging-24.0-py3-none-any.whl (53 kB)
     ---------------------------------------- 53.5/53.5 KB 2.9 MB/s eta 0:00:00
Collecting deprecated>=1.2
  Downloading Deprecated-1.2.14-py2.py3-none-any.whl (9.6 kB)
Collecting importlib-resources>=1.3
  Downloading importlib_resources-6.4.0-py3-none-any.whl (38 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in d:\python\python310\lib\site-packages (from rich<14,>=12->Flask-Limiter<3.5.0,>=2.3.0->calibreweb) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in d:\python\python310\lib\site-packages (from rich<14,>=12->Flask-Limiter<3.5.0,>=2.3.0->calibreweb) (2.16.1)
Collecting tzdata
  Downloading tzdata-2024.1-py2.py3-none-any.whl (345 kB)
     ---------------------------------------- 345.4/345.4 KB ? eta 0:00:00
Collecting cryptography<43,>=41.0.5
  Downloading cryptography-42.0.6-cp39-abi3-win_amd64.whl (2.9 MB)
     ---------------------------------------- 2.9/2.9 MB 46.7 MB/s eta 0:00:00
Collecting cffi>=1.12
  Downloading cffi-1.16.0-cp310-cp310-win_amd64.whl (181 kB)
     ---------------------------------------- 181.6/181.6 KB ? eta 0:00:00
Collecting wrapt<2,>=1.10
  Downloading wrapt-1.16.0-cp310-cp310-win_amd64.whl (37 kB)
Requirement already satisfied: mdurl~=0.1 in d:\python\python310\lib\site-packages (from markdown-it-py>=2.2.0->rich<14,>=12->Flask-Limiter<3.5.0,>=2.3.0->calibreweb) (0.1.2)
Collecting pycparser
  Downloading pycparser-2.22-py3-none-any.whl (117 kB)
     ---------------------------------------- 117.6/117.6 KB 7.2 MB/s eta 0:00:00
Using legacy 'setup.py install' for Flask-Principal, since package 'wheel' is not installed.
Using legacy 'setup.py install' for iso-639, since package 'wheel' is not installed.
Using legacy 'setup.py install' for netifaces, since package 'wheel' is not installed.
Installing collected packages: Wand, pytz, netifaces, iso-639, wrapt, urllib3, unidecode, tzdata, tornado, six, PyPDF, pycparser, pyasn1, packaging, ordered-set, MarkupSafe, lxml, itsdangerous, importlib-resources, greenlet, click, chardet, blinker, Babel, wtforms, Werkzeug, tzlocal, SQLAlchemy, Jinja2, deprecated, cffi, limits, Flask, cryptography, APScheduler, pyopenssl, flask-wtf, Flask-Principal, Flask-Login, Flask-Limiter, Flask-Babel, ndg-httpsclient, advocate, calibreweb
  Running setup.py install for netifaces ... error
  error: subprocess-exited-with-error

  × Running setup.py install for netifaces did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      D:\Python\Python310\lib\site-packages\setuptools\config\setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!

              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.

              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      running install
      D:\Python\Python310\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!

              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.

              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************

      !!
        self.initialize_options()
      running build
      running build_ext
      building 'netifaces' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> netifaces

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
WARNING: You are using pip version 22.0.4; however, version 24.0 is available.
You should consider upgrading via the 'D:\Python\Python310\python.exe -m pip install --upgrade pip' command.

**Comment by OzzieIsaacs** [comment]
Please have a look here for potential solutions:
https://github.com/janeczku/calibre-web/issues/2875
