### ISSUE TITLE
Potential Issue regarding file upload

### ISSUE THREAD

**Issue by nevercodecorrect** [janeczku/calibre-web#3044]
**Describe the bug/problem** 

In the code [here](https://github.com/janeczku/calibre-web/blob/3a603cec22b8072f9c1991a48897484ec5a45004/cps/editbooks.py#L741), it uses the user provided file extension to determine the file type. However, it is possible to bypass it with a crafted a file name. This could be a potential security issue as described in [CWE-646](https://cwe.mitre.org/data/definitions/646.html)

**To Reproduce**

upload any file with a extension name like txt.

**Expected behavior**
A magic number based file type detection could be applied here.

I would be happy to make a PR for this. Please let me know your opinion.

**Comment by OzzieIsaacs** [comment]
Sorry I'm to stupid to understand the example: I tried "filetxt", "filetxt.", "file.pdf.txt", all of them lead to aborting the upload of the file. 
Could you please give me a example filename, preferably with a quoted filename so I know where the filename is starting and ending?
The CWE talkes about files with double endings getting handled as if they had the first file ending. Where is this happening in calibre-web, I don't see it?

**Comment by Jerk-Solutions** [comment]
I think the best way to resolve this would be to allow for an integration with an antimalware toolkit like ClamAV. Accept the upload, scan the files and if nothing gets flagged, add to the db.

An alternative would be to have such a toolkit running separately and scan the files on the local system.

**Comment by OzzieIsaacs** [comment]
I thought some time on this. If you upload an executable on Linux, the executable flag isn't set, so the file can't be executed (I currently can't check it in windows). I'm using ClamAV on my computer to scan files and there it's slow like hell (feels like over 30sec before a file scan is complete), if you have to do this on every upload, users will complain about it. So I think this would be nice to have, yes, but it's not practicable.
The file uploaded (even with executable flag set), can't create any damage on the firsthand, there is no function within calibre-web to execute it (if you view it using the viewer, it will be interpreted as pdf, txt or comic file so this means also no special harm. Something from outside of calibre-web needs to start the executable.
@nevercodecorrect: I'm curious, what was/is your solution for this topic? (You could also write me an email if this shouldn't discussed in the public)
