### ISSUE TITLE
通过打标签区分可以添加多标签么。

### ISSUE THREAD

**Issue by janewar** [janeczku/calibre-web#3048]
怎么管理未成年看书问题，通过打标签区分
怎么管理账号权限，不通的人可以看到不同种类的书籍，看到里面有标签过滤，但是那个怎么添加多标签。感觉不是很方便，权限管理。

**Comment by OzzieIsaacs** [comment]
In english please

**Comment by janewar** [comment]
> In english please

How to manage the issue of minors reading books, by tagging to distinguish

How to manage account permissions, different people can see different types of books, and there are tag filters inside, but how to add multiple tags seems inconvenient, permission management.

**Comment by janewar** [comment]
Can be separated by commas.

**Comment by janewar** [comment]
Can be separated by commas.
