### ISSUE TITLE
可以AI➕电子书变成有声读书么？

### ISSUE THREAD

**Issue by janewar** [janeczku/calibre-web#3049]
可以AI➕电子书变成有声读书么？
甚至于可以用AI总结电子书内容
直接读取精华。

**Comment by OzzieIsaacs** [comment]
In english please

**Comment by janewar** [comment]
> In english please

Can AI plus e-books be turned into audiobooks?

Or even use AI to summarize the content of e-books

Directly read the essence.

**Comment by OzzieIsaacs** [comment]
Sorry, this is way to complex for my hobby project.
