### ISSUE TITLE
Author browsing not limited to single author?

### ISSUE THREAD

**Issue by simkin** [janeczku/calibre-web#305]
When I click the author of a bunch of magazines and scroll downwards I noticed that also books from other authors were included. Is this a bug?

Screenshot below shows the page after clicking /author/**14861**
The books at the bottom belong to /author/**3201** and I did not expect these to be listed.

When checking the metadata I only see a single author listed

![image](https://user-images.githubusercontent.com/958263/29923311-5fd91c2a-8e59-11e7-9db4-65822b9b4bc7.png)

**Comment by jkrehm** [comment]
Likely the same regression that caused #302 (resolved with #303). Could you try merging the changes from #303 into your branch and check if that fixes it?

**Comment by simkin** [comment]
Confirmed. #303 fixes this issue as wel

**Comment by jkrehm** [comment]
Should be fixed now that #303 has been merged.

**Comment by OzzieIsaacs** [comment]
Merged
