### ISSUE TITLE
Cover not Available for books uploaded into Calibre-Web

### ISSUE THREAD

**Issue by kanjieater** [janeczku/calibre-web#3054]
**Describe the bug/problem** 

Books uploaded to Calibre-web don't add covers. Books added via classic Calibre do (Manually updated one that has an image here)
![image](https://github.com/janeczku/calibre-web/assets/32607317/d1417ce3-6115-4205-9257-80f81d8e35cd)

**To Reproduce**

1. Upload a few books
2. No cover is generated.

**Logfile**

[calibre-web.log](https://github.com/janeczku/calibre-web/files/15298782/calibre-web.log)

**Expected behavior**

Covers should be generated
![image](https://github.com/janeczku/calibre-web/assets/32607317/f6e138cf-48dc-43b3-a1a9-41dfb2d539ff)

**Environment (please complete the following information):**

 - OS: Windows
 - Python version: 3.10.10
 - Calibre-Web version: [e.g. 0.6.8 or 087c4c59 (git rev-parse --short HEAD)]:
 - Docker container: [None/LinuxServer]: (moving to LinuxServer soon, but currently none)
 - Special Hardware: Windows PC
 - Browser: Chrome 

**Additional context**
Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

**Comment by kanjieater** [comment]
Switched to docker and it works

**Comment by kanjieater** [comment]
![image](https://github.com/janeczku/calibre-web/assets/32607317/602e7f7c-4bc8-4d07-aeb4-bf215e7f9eb7)

Even after switching to the linuxserver docker image, a lot of books do add images, but some do not. They always do from calibre classic though

**Comment by kanjieater** [comment]
@OzzieIsaacs Is docker unsupported? Why the Invalid tag?

**Comment by OzzieIsaacs** [comment]
I asked you two questions and gave you a hint regarding your problem. I think it would have taken about 1minute to answer it. Instead you installed a docker container, which adds another level of complexity. The outcome was another problem (permission error for log file rotation. So my conclusion is: I can't help you.

And yes,I'm not supporting the docker container
