### ISSUE TITLE
about ssl certificate in docker

### ISSUE THREAD

**Issue by shawnzhou1120** [janeczku/calibre-web#306]
我用群晖的dock中装了calibre-web这个程序，按部就班的，目前也算基本安装成功了，但是有个比较麻烦的问题，那就是我的群晖默认开启了https。也申请安装了ssl证书。但是在访问docker中的calibre时，会提示不安全，每次都要跳转。甚至google还会禁止访问。请问使用这个calibre-web。需要怎么安装我的ssl证书进去呢？

**Comment by OzzieIsaacs** [comment]
Please write your comment in english, otherwise I will close this issue

**Comment by shawnzhou1120** [comment]
sorry
following is the english rev:
there are 2 questions:
1.technosoft2000/calibre-web and janeczku/calibre-web are same project or not in hub.docker? can the database be shared between the 2 project?i find the web is linked by the 2 project.I installed the 2 poject in docker,and use the same location,and technosoft2000/calibre-web can not find the database.
2.i install the janeczku/calibre-web in my DSM.i can open the web.but brower all shown me its not safe(https are using).The ssl certificate are installed in the DSM(Synology nas),and its work well(we can open the other site by the same domain name ). so i don't kown how i can take the my sll cer into janeczku/calibre-web?
thanks

**Comment by OzzieIsaacs** [comment]
Question 1: they are not the same. Janeczku/calibre-web is an old version, which is not developed any more. You should not use it.
Question 2: please use technosoft/calibre-web. You can use it behind a proxy like decribed in the readme:

> if you need SSL support similiar to the original Docker Container janeczku/calibre-web then use an additional NGINX or Apache HTTP Server as Reverse-Proxy, e.g see jwilder/nginx-proxy

SSL should work than, too

**Comment by shawnzhou1120** [comment]
thanks very much,i will try the technosoft/calibre-web
