### ISSUE TITLE
how to connect with Microsoft active Directory 

### ISSUE THREAD

**Issue by abidfakhrealam** [janeczku/calibre-web#3066]
we have implement in the university library system, how to authenticate users using Microsoft’s Active Directory (AD) with OAuth (Open Authorization) through university Azure Active Directory (Azure AD)

**Comment by OzzieIsaacs** [comment]
Only google and github are supported as outh providers (and this will not change). Some guy want to implement something for it https://github.com/janeczku/calibre-web/pull/2211. There seems to be a fork for it (in the issue). Maybe this helps you
