### ISSUE TITLE
downloaded files are renamed with numbers

### ISSUE THREAD

**Issue by dchao4852** [janeczku/calibre-web#3070]
In Moon Reader, when looking at the downloaded files on the device or the files synced to Dropbox, all of them are renamed with numbers. It would be nice to preserve the original titles in the filename.

I don't notice this problem on a pc, so it might be a Moon Reader problem.

**Comment by OzzieIsaacs** [comment]
Yes indeed it's a moonreader problem.  Calibre-web sends the proper file name with the file, the renaming is done by moon-reader. So nothing I can do from my side.
