### ISSUE TITLE
Clarification on Archiving part

### ISSUE THREAD

**Issue by juanbeniteza** [janeczku/calibre-web#3077]
Based on your [documentation ](https://github.com/janeczku/calibre-web/wiki/Kobo-Integration#book-management) for the Kobo Integration, you say that "n order to trigger deletions from their devices, users must archive books and then sync their devices." 

The action of archiving the books should be done on the devices or Calibre Web? because when I do it on Calibre Web and sync it the book is not removed

**Comment by OzzieIsaacs** [comment]
It is supposed to work both ways

**Comment by OzzieIsaacs** [comment]
The problem archiving a book in calibre-web and then syncing, is resolved in the newest nightly build
