### ISSUE TITLE
Forcing Bleach is causing problem displaying `<p>` tags

### ISSUE THREAD

**Issue by JeffersonQin** [janeczku/calibre-web#3080]
The newest commit https://github.com/janeczku/calibre-web/commit/f7d5480811c72c7e8104e79a39d08b9407ae3338

Causing the following problem when editing metadata:

![image](https://github.com/janeczku/calibre-web/assets/30655701/15e5f8f0-29f2-454b-83cb-f261275e540a)

**Comment by OzzieIsaacs** [comment]
Thanks for reporting and also for the fix. I have my own fix dveloped, I need one or 2 days to test (div, strong, pre and maybe more tags are also missing)

**Comment by JeffersonQin** [comment]
I see. Thank you for letting me know.

**Comment by OzzieIsaacs** [comment]
Should now fixed in the newest nightly version
