### ISSUE TITLE
 Calibre-Web 500 Internal Server Error The server encountered an internal error 

### ISSUE THREAD

**Issue by spindigits** [janeczku/calibre-web#3086]
## Short Notice from the maintainer 
This error occurs after /books/ and /config/:

Calibre-Web
500 Internal Server Error
The server encountered an internal error and was unable to complete your request. There is an error in the application.
Traceback (most recent call last):
File "/lsiopy/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
response = self.full_dispatch_request()

**Comment by OzzieIsaacs** [comment]
I need the full error message and the information from the for otherwise there is nothing I can do

**Comment by OzzieIsaacs** [comment]
And if you are using docker, it‘s a permission problem, read the manual more carefully

**Comment by Roomdead** [comment]
Not sure if it's your case but I got the same issue and after hours of tries I figured out that file metadata.db haven't been downloaded properly. Instead of file itself I've downloaded html page where I was trying to download file)))
