### ISSUE TITLE
Problem with downloading or viewing

### ISSUE THREAD

**Issue by ashkan2200** [janeczku/calibre-web#309]
Hi,
So I have this library in raspberry pi with raspian jessie.
The problem is that my browser fails to view or download the files from Calibre Web if the file is larger than a certain size. With the things I tried, I am unable to download files larger than 50 mb.

Here is the error message 

    Proxy Error
    
    The proxy server received an invalid response from an upstream server.
    The proxy server could not handle the request GET /download/259/pdf/259.PDF.
    
    Reason: Error reading from remote server

**Comment by jkrehm** [comment]
Is there anything in calibre-web.log that could help diagnose the issue?

**Comment by OzzieIsaacs** [comment]
Are you using gevent or tornado as server ( is there listed a tornado version in the about section)?
Is it possible to download the files without the proxy?
Is the download failing instantly, or after a certain timeout?

**Comment by OzzieIsaacs** [comment]
I just checked sucessfully a 100MB download on my ubuntu 16.04

**Comment by ashkan2200** [comment]
Hi. You can close this. I just checked and it works now. Apparently the second restart foxed it.
