### ISSUE TITLE
Specific packages that are now required

### ISSUE THREAD

**Issue by jasonxbergman** [janeczku/calibre-web#3093]
The latest release contains this warning:

**!Attention! For this update regex, beach and python-magic has to be installed !Attention!**

Can you link to the specific packages we need to install? Just want to make sure I'm grabbing the actual requirements before upgrading.

**Comment by sir-wilhelm** [comment]
They are listed in the [requirements.txt](https://github.com/janeczku/calibre-web/blob/0.6.22/requirements.txt).

Here is the diff where it was updated for the latest version: [b28a363#diff-4d7c51b](https://github.com/janeczku/calibre-web/commit/b28a3635f88b72f7cf6cd1e1304b796928d31b52#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552).

**Comment by jasonxbergman** [comment]
Well that explains my confusion - the requirements.txt shows you need bleach 6.2.0.

The release notes say _beach_ which was not something I was able to find!

**Comment by TheNomad11** [comment]
It might be obvious for more knowledgeable people than me but all these packages in question are python packages, so the solution is:

`sudo apt install python3-bleach python3-regex python3-magic`

but this was not enough in my case. I was greeted by an 503 error. In the logs I was told that PyPDF was required

so after

`pip3 install PyPDF`

and a reboot, I was able to use the new and shiny Calibre Web!

**Comment by jasonxbergman** [comment]
The easiest thing to do is re-run `./venv/bin/python3 -m pip install -r requirements.txt`. 

(Although I was confused, since the release notes had a typo)

**Comment by Trashwarez** [comment]
Following the "requirements.txt" it needs tornado>=6.3,<6.5.
At least on my system there are complaints that in order to fulfill this requirement it needs at least Python >= 3.8 installed and not "3.5+" as stated in the Readme on the top page.

**Comment by OzzieIsaacs** [comment]
The typo is fixed. 
Earlier tornado versions work, that’s correct
