### ISSUE TITLE
Missing convert options

### ISSUE THREAD

**Issue by designeramic** [janeczku/calibre-web#3094]
The option to convert from epub to azw3 has gone missing from the UI. It's been a while since I used this feature so I'm not sure when it happened. Kepub is the only option available to convert to in the dropdown menu. I've tried removing and reinstalling the docker image but I'm still having the same problem.

The filepicker icon right to the input field is missing so not sure if that's related to my issue.

I'm on v0.6.23 Beta using the latest linuxserver nightly container.

<img width="500" alt="external_binaries" src="https://github.com/janeczku/calibre-web/assets/65368842/09e653dd-bbb1-4b61-bd1d-acae8e822ada">
<img width="398" alt="convert-options" src="https://github.com/janeczku/calibre-web/assets/65368842/76d683af-7a42-4244-aa65-31f83bf97fec">

**Comment by OzzieIsaacs** [comment]
Please add the path to calibre binaries setting, afterwards the option should show up again

**Comment by designeramic** [comment]
Thanks. I got it to work by leaving the "Calibre E-Book Converter Settings" field empty. These instructions in the readme might need to be edited 

> Set "path to convertertool" to /usr/bin/ebook-convert

<img width="455" alt="Screenshot 2024-07-07 at 10 23 34 AM" src="https://github.com/janeczku/calibre-web/assets/65368842/dcb80463-1b4f-4a2f-b4b7-6aa44b01e0dc">

**Comment by OzzieIsaacs** [comment]
Thanks for the hint. I updated the readme and the other documentation
