### ISSUE TITLE
Add ability to configure logging

### ISSUE THREAD

**Issue by snesbittsea** [janeczku/calibre-web#310]
Currently default log level appears to be INFO and it is quite noisy and evidently not configurable. It would be useful if:

1.  A log handler was passed into the WSGIServer creation event as outlined here: http://www.gevent.org/gevent.pywsgi.html
2. Logging were a configuration item

**Comment by OzzieIsaacs** [comment]
Please go to admin section click on configure change the log level to whatever suits your needs. Enjoy
