### ISSUE TITLE
Some upload filetypes no longer work in latest (0.6.22) version

### ISSUE THREAD

**Issue by CarlesLlobet** [janeczku/calibre-web#3102]
**Describe the bug/problem** 

After updating to the latest version, where [Python-magic has been addedd to validate myme-types (PR 3061)](https://github.com/janeczku/calibre-web/pull/3061), some uploads fail.

My assumption is that some magicnumbers might be missing, since it only appears to happen with some specific files.
Here's an example where both files are M4B (which is accepted according to [EXTENSIONS_UPLOAD constant](https://github.com/yunimoo/calibre-web/blob/af52748acaa18a2b00585508222c7f884b1dc9f6/cps/constants.py#L155)), but one uploads and the other doesn't:
![telegram-cloud-photo-size-4-5798546939179025337-y](https://github.com/janeczku/calibre-web/assets/6575422/9df050c4-884f-44fc-ace2-eb3cefa65a49)

The first one doesn't work, and I haven't been able to find any reference to that Magic number, although it appears to be some sort of reference to M4A and M4A is also accepted according to [EXTENSIONS_UPLOAD constant](https://github.com/yunimoo/calibre-web/blob/af52748acaa18a2b00585508222c7f884b1dc9f6/cps/constants.py#L155):
- `0000 001c 6674 7970 4d34 4120 0000 0001 4d34 4120 6d70 3431 6d70 3432` -> Doesn't work

The second one does work and I've found it belongs to [MPEG4 Part 14](https://ca.wikipedia.org/wiki/MPEG-4_Part_14).
- `0000 0020 6674 7970 6973 6f6d 0000 0200 6973 6f32 6d70 3431 4d34 4120` -> Works

**To Reproduce**

1. Drag & Drop an M4B file with the first magic number, such as [the above M4B audiobook](https://easyupload.io/ekiysq) (upload expirates in 30days)
2. See error "`File type isn't allowed to be uploaded to this server`":
<img width="884" alt="image" src="https://github.com/janeczku/calibre-web/assets/6575422/2006b1c0-8bd2-4b63-9e73-d4b325c8dc5c">

**Logfile**

Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

**Expected behavior**

All valid files should be accepted. Either this (and any other missing) magic number is also allowlisted, or instead we opt for a denylist approach with only malicious files (executables and such) are denied, which would be much more maintainable and aligned with any future improvement (such as the adition of a ClamAV or similar upload scan).

**Environment (please complete the following information):**

 - OS: [Raspberry Pi OS]
 - Python version: [python3.12]
 - Calibre-Web version: [0.6.22]:
 - Docker container: [LinuxServer]:
 - Special Hardware: [Rasperry Pi 4B+]
 - Browser: [Chrome 126.0.6478.127]

**Additional context**
N/A

**Comment by OzzieIsaacs** [comment]
I‘ll Check, as workaround you can deactivate the upload check in admin -> basic config -> security settings -> …

**Comment by CarlesLlobet** [comment]
> as workaround you can deactivate the upload check in admin -> basic config -> security settings -> …
Oh didn't know about that option 😍   That will definitely be useful, thx! 💪

**Comment by OzzieIsaacs** [comment]
I knew this would happen

**Comment by OzzieIsaacs** [comment]
I added the correct file type check, please update to the newest nightly version, the upload should work now

**Comment by CarlesLlobet** [comment]
Wow, quickest fix I've ever seen 👀

I've seen where the error was, nice catch.
Confirmed its successfully fixed in nightly, thanks 💪 

Congrats on such amazing tool and support. 🙏 🎉

**Comment by OzzieIsaacs** [comment]
I‘d like to leave it open till the next release

**Comment by schmurtzm** [comment]
Doesn't seems to be fixed, I had to uncheck " Check if file extensions matches file content on upload" to upload my ebook successfully (V 0.6.23 Teofila, Windows)

**Comment by NathanIfinity** [comment]
Unable to upload anything since update to V 0.6.23 Teofila, Windows always get the message : File type isn't allowed to be uploaded to this server even though all file type are set in the settings 

![image](https://github.com/user-attachments/assets/4b8c4f3a-cac8-47c9-a83f-62b4a4a5f41e)
