### ISSUE TITLE
Scheduled Task Reconnect Calibre Database fails

### ISSUE THREAD

**Issue by cortomalese** [janeczku/calibre-web#3107]
Hi,
Thank you for your work!
I would like to draw your attention to this malfunction.

Regards,
Corto

**Describe the bug/problem** 

Scheduled Task Reconnect Calibre Database fails

**To Reproduce**

1. Go to 'Admin page'
2. Click on 'Edit schedule tasks settings'
3. Activate  Reconnect Calibre Database
4. Save
5. Go to 'Task page'
6. Look at Tasks table.

**Logfile**

[calibre-web.log](https://github.com/user-attachments/files/16313978/calibre-web.log)

**Expected behavior**

Calibre-web updating changes made to metadata.db by Calibre app.

**Screenshots**
[Calibre-Web _ Tasks.pdf](https://github.com/user-attachments/files/16313967/Calibre-Web._.Tasks.pdf)

**Environment (please complete the following information):**

 - OS: Debian 12
 - Python version: [e.g. python2.7]
 - Calibre-Web version: 0.6.22
 - Docker container: Linuxserver.io version:- 0.6.22-ls277 Build-date:- 2024-07-14T01:58:09+00:00
 - Special Hardware: Rasperry Pi 4
 - Browser: Firefox 128

**Additional context**
Database background sync via rsync

**Comment by OzzieIsaacs** [comment]
It's very clever programmed. Please start calibre-web with the command line parameter "-r". 
I'll check if I can change it

**Comment by cortomalese** [comment]
Thank you @OzzieIsaacs : how can I start calibre-web with the command line parameter "-r" with docker-commander, please?

**Comment by OzzieIsaacs** [comment]
I have no idea, you need to ask tge docker provider.
The other option is to switch to nightly build, then it works out of the box

**Comment by cortomalese** [comment]
Thanks, I'll take a look and let you know.

**Comment by cortomalese** [comment]
I switched to nightly and the database reconnection was successful.
Thanks!
