### ISSUE TITLE
A possibility to have a max and min for searches in a custom column

### ISSUE THREAD

**Issue by alva-seal** [janeczku/calibre-web#3109]
**Is your feature request related to a problem? Please describe.**
I have a custom column called pages and i would like to search for books in a range of pages. Eg. A book between 250 and 350 pages.
There is already a field for the custom column called pages in the search and it knows it needs to be a number, but searching for an exact number is not useful in this case. 

**Describe the solution you'd like**
Similar to the published date bi propose to have a from and to field in the search for numeric custom columns

**Describe alternatives you've considered**
The alternative i have to use calibre to search for this cases but that is not possible if I‘m not at home

**Comment by OzzieIsaacs** [comment]
Please check the newest nightly version

**Comment by alva-seal** [comment]
Thanks it is great now
