### ISSUE TITLE
Wrong Username or Password

### ISSUE THREAD

**Issue by bulletproof2k** [janeczku/calibre-web#3110]
Running on Windows after installation exe file.
I can't log in to my account after the last update.
![2024-07-28_16-45-47](https://github.com/user-attachments/assets/c94639de-d330-42aa-8493-683e5d8f6494)

**Comment by OzzieIsaacs** [comment]
The location of the app.db file was changed back to the root folder, I guess you try to install into a ‚new installation‘ try to move the app.db file or start from scratch with admin-admin123 as username password combination

**Comment by bulletproof2k** [comment]
Let's consider this issue resolved, which paths and which files should I specify here?
![2024-07-28_16-45-47](https://github.com/user-attachments/assets/c0271619-ae2a-4d73-9bfb-b4ea6bf6e95d)

**Comment by OzzieIsaacs** [comment]
The location of you calibre installation (if installed) usually c:\program files\calibre
2nd field empty
3rd one, path to your rar (e.g. winrar) installation
