### ISSUE TITLE
Error executing UnRar

### ISSUE THREAD

**Issue by bulletproof2k** [janeczku/calibre-web#3112]
This error appears when saving the settings.

![2024-07-29_10-27-25](https://github.com/user-attachments/assets/9cd3c950-4a0e-4f19-abc8-80f224a1627c)

**Comment by OzzieIsaacs** [comment]
Please enter the path including the unrar.exe

**Comment by bulletproof2k** [comment]
> Please enter the path including the unrar.exe

The settings cannot be saved. There is a long download, after which it closes, and after restarting the settings are not saved.

**Comment by OzzieIsaacs** [comment]
To answer your question with the same level of details:
![2024-07-31_19-33](https://github.com/user-attachments/assets/c8e3d321-4f7e-40fd-b218-54a1094a06b5)

**Comment by bulletproof2k** [comment]
I can't save the settings.
![2024-08-04_09-39-40](https://github.com/user-attachments/assets/504ccdfd-4ee2-4d52-8d8d-04008cfe1664)

**Comment by bulletproof2k** [comment]
@OzzieIsaacs The settings are still not saved. There is a long download (this can be seen on the server's download bar), and they are not saved after a reboot.

![2024-08-09_08-51-42](https://github.com/user-attachments/assets/a87d0dbd-69bf-4b60-837d-f998f6f113a3)
