### ISSUE TITLE
Prefix, URL is changing ( /cover/XX?c=1729999999 )

### ISSUE THREAD

**Issue by bonnebulle** [janeczku/calibre-web#3117]
Hello
I think it is not a bug, maybe a way to limit intrusion/content stealing
But, why, in covers URL there are 2 letters changing sometime?
After ```/cover/``` **XX** ```?c=1729999999``` change
So, we lost the cover permalink!
How to fix it /or/ find the cover_image_URL (from outside Calibre-web) ?
Maybe with the API ?
Thanks, great work here

**Comment by OzzieIsaacs** [comment]
The xx is the number of the book, it‘s not changing. The number behind the questionmark is changing to avoid browser caching issues after changing the cover. For a permalink you can remove this number

**Comment by bonnebulle** [comment]
Sorry I edit my question...
am asking about...
http : domaine.tld/cover/312/**sm**?c=1772777731
This 'sm' is not a number, it looks like it changing when installing into a new server
