### ISSUE TITLE
Safari 15.6.1 (macOS catalina) could not display pdf file properly.

### ISSUE THREAD

**Issue by drzchang** [janeczku/calibre-web#3118]
**Describe the bug/problem** 

I run a docker instance (linuxserver/calibre-web:0.6.23-ls281), and the pdf file content cannot display properly (nothing displayed) in Safari 15.6.1 (macOS catalina) while Chrome work well in the same MacBook pro.
This problem not only exist in this version, but also the previous versions (0.6.21 and 0.6.22).

I'm wondering it's related to calibre-web or linuxserver/calibre-web.

**To Reproduce**

1. read any pdf file in browser.

**Logfile**

no specified log output for this problem.

**Expected behavior**

show pdf content.

**Screenshots**

<img width="1536" alt="Screen Shot 2024-08-06 at 9 55 26 AM" src="https://github.com/user-attachments/assets/45dc5e0e-3142-40db-9ab4-44f88c6941db">

**Environment (please complete the following information):**

 - OS: QuTS Hero 5.1
 - Python version: 
 - Calibre-Web version: 0.6.23
 - Docker container: linuxserver/calibre-web:0.6.23-ls281
 - Special Hardware: QNAP NAS
 - Browser: Safari 15.6.1

**Additional context**
no

**Comment by OzzieIsaacs** [comment]
There have been reports that older Mobil OS versions aren’t working properly. Like here: https://github.com/mozilla/pdf.js/issues/18222
Could you please check if there is some error on the developers console in the browser visible?

**Comment by OzzieIsaacs** [comment]
And could you please check if both pdf files in the link are working/not working for you?

**Comment by drzchang** [comment]
> There have been reports that older Mobil OS versions aren’t working properly. Like here: [mozilla/pdf.js#18222](https://github.com/mozilla/pdf.js/issues/18222) Could you please check if there is some error on the developers console in the browser visible?

<img width="1535" alt="Screen Shot 2024-08-07 at 11 07 30 AM" src="https://github.com/user-attachments/assets/b4a3f41c-c1a0-4e41-93d4-9602e7217a17">

I'm not familiar with web development, so I'm not sure  if this is what you are looking for.

**Comment by drzchang** [comment]
> And could you please check if both pdf files in the link are working/not working for you?

> The PDF 1 link on the page https://test2.bannersky.com/bsk-pdf-manager/ use the old version 4.3.136, it CANNOT be open.

I don't find any pdf link in this link.

> The PDF 1 link on the page https://wangjingtang.com/bsk-pdf-manager/ use the old version 4.0.379, it CAN be open.

work.

**Comment by OzzieIsaacs** [comment]
You are right, I had a conversation a few weeks ago, there the first link also had a pdf file in it. Anyway, the first screenshot was what I was looking for, and google had a good idea what to do.

**Comment by OzzieIsaacs** [comment]
Please try to update to the newest nightly version. I changed the pdf reader, for me both version were working, so I'm not sure (but quit confident) that it will work afterwards

**Comment by drzchang** [comment]
> Please try to update to the newest nightly version. I changed the pdf reader, for me both version were working, so I'm not sure (but quit confident) that it will work afterwards

Great. It works in my machine. Thanks a lot.

**Comment by blog2020** [comment]
> Please try to update to the newest nightly version. I changed the pdf reader, for me both version were working, so I'm not sure (but quit confident) that it will work afterwards


I also encountered the same problem with version 0.6.23. I couldn’t open PDF in Chrome, Firefox, or Edge. Finally, I solved it by installing the nightly version. Thank you.

**Comment by machmalpause** [comment]
Fantastic ! Finally works well on an older iPad 5th gen 9.7 iOS 16.7.10.
Thank you for this great work, much appreciated ! Donation is on its way ;-)
BW
