### ISSUE TITLE
Hide Adult Content

### ISSUE THREAD

**Issue by teflontoni** [janeczku/calibre-web#312]
The function works as expected, but each user is free to show adult content by going to his/her profile page, thus the function lacks the intended purpose and is merely a small hinderance for tech-savy minors.

**Comment by jkrehm** [comment]
Huh, I thought I had surrounded that by an "if user is an admin, then show the checkbox" but apparently not. I'll do that and send a PR.

That's the only way I can think to make it work. Clearly someone has to decide if the user can see the content, and if the underage user is also an admin, there's absolutely nothing that could be done to prevent them from accessing the material.

**Comment by teflontoni** [comment]
Did a pull request already (my first ever for any project).

**Comment by jkrehm** [comment]
Congrats on your first PR. It's a good one to get your feet wet with.
