### ISSUE TITLE
(Docker) Ebook-convert in calilbre-web can not convert Chinese when converting epub to PDF

### ISSUE THREAD

**Issue by Hanzo-Huang** [janeczku/calibre-web#3121]
Ebook-convert in calilbre-web can not convert Chinese, but Linux/Windows  GUI can do it.

**Comment by Hanzo-Huang** [comment]
I tried ebook-convert command to convert equb to pdf in my PC, it works will. So I want to find if it works right as the same way in my server(calibre running in docker). 
```bash
ebook-convert book.equb book.pdf
```
Error
```
[1392:1392:0809/192103.286654:ERROR:zygote_host_impl_linux.cc(100)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
```

**Comment by OzzieIsaacs** [comment]
I don‘t provide th3 docker container, please ask there for help
