### ISSUE TITLE
Create e-book from RSS/Atom feeds

### ISSUE THREAD

**Issue by silverhook** [janeczku/calibre-web#3122]
> After 6 years of more or less intensive programming on Calibre-Web, I need a break. 
> The last few months, maintaining Calibre-Web has felt more like work than a hobby. I felt pressured and teased by people to solve "their" problems and merge PRs for "their" Calibre-Web. 
> I have turned off all notifications from Github/Discord and will now concentrate undisturbed on the development of “my” Calibre-Web over the next few weeks/months.  
> I will look into the issues and maybe also the PRs from time to time, but don't expect a quick response from me.

Very understandable, do take care and make sure it stays fun.

**Is your feature request related to a problem? Please describe.**

Not really, no.

**Describe the solution you'd like**

I would like to be able to subscribe to RSS/Atom feeds of websites (e.g. news sites, blogs etc.) like I can with Calibre (desktop app), so it then packages them into ePub and ships them to my eReader.

**Describe alternatives you've considered**

The alternative could be to use Calibre (desktop app) for it, but if it was happening on the server instead, that would be much more convenient.

**Comment by OzzieIsaacs** [comment]
I don't want to extend the calibre-web function towards a "web/feed scraper". This will create a lot of new functions and problems.

Sorry

**Comment by silverhook** [comment]
I’d love to see it, but fair enough.
