### ISSUE TITLE
no books list for guest users?

### ISSUE THREAD

**Issue by dmd** [janeczku/calibre-web#3126]
It looks like the books list is hardcoded to be disabled for Guest users. Why?

https://github.com/janeczku/calibre-web/blob/4d79c593f768be7d04ab5b1ebcfbe6b25d6e854d/cps/render_template.py#L99-L102

**Comment by OzzieIsaacs** [comment]
The book list was done as "admin-tool", you can edit books, but there is no button to view the books details page, download the book or do something else beside editing metadata. For normal users calibre-web stores the settings (which columns are visible) in the database on the server side, for guest users this is stored in the browser session (as many guest users can view the same page on the same time)

Editing metadata is not allowed for the guest user and I avoided programming the storage backend for the books list for the guest user.
Currently I'd like to stick to this decision.

**Comment by dmd** [comment]
That makes sense. I guess what I'm **really** looking for is simply a compact text list mode of any kind as opposed to viewing by cover.

**Comment by OzzieIsaacs** [comment]
Calibre-web doesn't have this and I'm not planing to implement it. The feedback I get is people love calibre-web because of the "pretty cover views", so I'd like to stick to this

**Comment by dmd** [comment]
Fair enough!
