### ISSUE TITLE
Limit display of authors when multiple authors are listed

### ISSUE THREAD

**Issue by aljovin** [janeczku/calibre-web#3134]
**Is your feature request related to a problem? Please describe.**
When displaying Comic books with ComicVine, sometimes the list of authors/artist is VERY long and ends up taking a lot of lines, taking a lot of real estate on the display

**Describe the solution you'd like**
I would like a way to reduce the number of authors displayed, but still keep the list of authors for searching purpose. What I'm suggesting is a parameter that would display up to X amount of authors on the list, and if there is more add a "(...)" at the end of the list. In this instance, setting 3 authors, would display them as : Stephen King, George Lucas, Steven Speilberg (...)

**Describe alternatives you've considered**
Alternatives, would be to udpate my database to remove the authors from the list, but this would also mean that I couldn't search with that criteria, and I don't feel like it's a good alternative

Example:
![LargeCalibre-weblist](https://github.com/user-attachments/assets/c864eb47-7ef4-48d8-867b-d05e0991d9e7)

**Comment by OzzieIsaacs** [comment]
Please go to Admin section -> Edit UI Configuration ->  View Configuration  -> No. of Authors to Display Before Hiding (0=Disable Hiding):
![grafik](https://github.com/user-attachments/assets/963c5f1d-8a96-4f88-8b3c-8bec62969e62)

**Comment by aljovin** [comment]
Thanks
