### ISSUE TITLE
Titlebar of Epub reader with dark theme have really low contrast

### ISSUE THREAD

**Issue by qrhfz** [janeczku/calibre-web#3145]
**Describe the bug/problem** 

A clear and concise description of what the bug is. If you are asking for support, please check our [Wiki](https://github.com/janeczku/calibre-web/wiki) if your question is already answered there.

**To Reproduce**

1. open epub reader for a book
2. set theme to dark
3.  see the toolbar

**Screenshots**
![Screenshot_20240908_105420](https://github.com/user-attachments/assets/00406356-d4a7-4e98-8fcc-b861897349a9)

**Expected behavior**
Titlebar should have sufficient contrast.
Like this, i use inspect element:
![Screenshot_20240908_105809](https://github.com/user-attachments/assets/cec5c06e-d1a5-41ae-81f8-7eb7fa6d0a48)

**Environment (please complete the following information):**

 - OS: Debian Bookworm
 - Python version: [e.g. python2.7]
 - Calibre-Web version: 0.6.23 - d3233b4b9cf4ec540ff31fba787865cb95810ae3
 - Docker container: LinuxServer
 - Special Hardware: -
 - Browser: LibreWolf 130.1

**Additional context**

**Comment by Xjocinx** [comment]
[](url)

**Comment by OzzieIsaacs** [comment]
![grafik](https://github.com/user-attachments/assets/c4d6ddfb-ed4c-4875-b932-fb81d276fe9c)
I think it looks better now (top row). Please update to the newest nightly version. If you are not satisfied please make suggestion what to change else (opacity, ...)

**Comment by qrhfz** [comment]
seems good. i'll close this now.
