### ISSUE TITLE
Configure metadata plugboard

### ISSUE THREAD

**Issue by GungHo63** [janeczku/calibre-web#3146]
Hi,
I think this functionality was implemented in PR
https://github.com/janeczku/calibre-web/pull/2497

But i would like a bit more information on how to implement the following in calibre-web

![image](https://github.com/user-attachments/assets/570e5180-3c03-4319-9b49-a7cd0974e93e)

For instance when i send the following book with email:
"Assassins Of Athens" By Jeffrey Siger, Series: Andreas Kaldis No. 2

This will result in the following attachment being sent 
"Assassins Of Athens - Jeffrey Siger.epub"

But i would like it to be named:
Andreas Kaldis [2] - Assassins Of Athens.epub

With the help of the following plugboard expression:
Any format:Any Device = ({series}{series_index:0>2s|[|] - }{title})

 - OS: unraid running docker
 - Calibre-Web version:  0.6.24 Beta - 481237dc778e812e9d0af0f30ebc4187c8a39ab9 - 2024-08-23T10:51:37+02:00
 - Docker container:  lscr.io/linuxserver/calibre-web:nightly
 - Special Hardware: Intel® Atom™ CPU C2750 @ 2.41GHz

**Comment by OzzieIsaacs** [comment]
No idea.
The implementation just uses the calibre binary to copy the metadata from the metadata.opf file to the ebook file itself, without any possible configuration
