### ISSUE TITLE
Missing calibre binaries: ebook-convert, calibredb

### ISSUE THREAD

**Issue by PepperDocker** [janeczku/calibre-web#3148]
First of all, wow calibre web is an amazing product.

I’m trying to get the convert-option to show up in calibre web. After reading through the notes on GitHub I made sure that:
a. In the environment settings, DOCKER_MODS=linuxserver/mods:universal-calibre was added.

![IMG_0004](https://github.com/user-attachments/assets/140feac3-8ade-45fe-8790-5d3d878e97de)

b. Under the Basic Config settings in Calibre,
‘path to calibre binaries —> /usr/bin/
‘path to kepubify binaries —> /usr/bin/kepubify

![IMG_0005](https://github.com/user-attachments/assets/40d06598-d3ac-4aa4-add7-8f2af312095e)

This gives the error ‘Missing calibre binaries: ebook-convert, calibredb, missing executable permissions: ebook-convert, calibredb.

a. seems to have worked, as  the log file shows:
2024/09/08 10:31:38 | stdout | [mod-init] linuxserver/mods:universal-calibre applied to container
2024/09/08 10:31:38 | stdout | [mod-init] Installing linuxserver/mods:universal-calibre
2024/09/08 10:31:37 | stdout | [mod-init] Downloading linuxserver/mods:universal-calibre from lscr.io
2024/09/08 10:31:36 | stdout | [mod-init] Adding linuxserver/mods:universal-calibre to container

And the conversion from epub to kepub now is available.
E-book convert seems to be missing? I tried setting it to  /usr/bin/ebook-convert, but this doesn’t give results either.
Any ideas?

**Comment by shooshpanov** [comment]
Same issue

**Comment by OzzieIsaacs** [comment]
Sorry guys, in a normal installation this is working, this is a docker permission rights problem, where I can't help you

**Comment by PepperDocker** [comment]
> Sorry guys, in a normal installation this is working, this is a docker permission rights problem, where I can't help you.

thanks for the reply. Good to know the setup is correct.. Will try to see if I can fix the permission rights.

**Comment by tge101** [comment]
Was anyone able to get this figured out?  I'm having the same issue.

**Comment by spcano01** [comment]
I just copied them over to /config after downloading from calibre 7.18 arm https://download.calibre-ebook.com/7.18.0/calibre-7.18.0-arm64.txz

**Comment by tge101** [comment]
> I just copied them over to /config after downloading from calibre 7.18 arm https://download.calibre-ebook.com/7.18.0/calibre-7.18.0-arm64.txz

Can you be more specific?  did you copy all of the contents or just the ebook-convert file?  did you change anything else?

**Comment by DrFr33ze** [comment]
But the files are missing in the docker container.

**Comment by mendhak** [comment]
Might be worth checking out some of the threads on the linuxserver github or posting an issue there.

https://github.com/linuxserver/docker-calibre-web/issues/306 
https://github.com/linuxserver/docker-calibre-web/issues/305  

I see some workarounds or troubleshooting steps posted, to look in the container and there's an alternative path you can try as well (assuming the binary did get downloaded)

**Comment by DrFr33ze** [comment]
I can confirm, that the procedure described here: https://github.com/linuxserver/docker-calibre-web/issues/306#issuecomment-2342923994
worked. I now have the conversion button. Thanks for pointing me to the right direction!

**Comment by jmarmstrong1207** [comment]
I can also confirm that this is an issue as well for me.

**Comment by timotheeandres** [comment]
[This](https://github.com/linuxserver/docker-calibre-web/issues/306#issuecomment-2344760371) is what did it for me, although I don't know exactly what it fixes:
> If you're getting issues with the mod on a 4.x kernel, use `DOCKER_MODS=lscr.io/linuxserver/mods:universal-calibre-v7.16.0`. You'll never be able to get newer versions of Calibre but you will have a functional mod for the time being.
