### ISSUE TITLE
Hot books: Internal Server Error

### ISSUE THREAD

**Issue by teflontoni** [janeczku/calibre-web#315]
When mature content is in the hot books section and the user hasn't the right to view them, the hot books link causes an internal server error.

> [2017-09-09 13:30:33,878] {/opt/weblibrary/vendor/flask/app.py:1560} ERROR - Exception on /hot [GET]
>Traceback (most recent call last):
>  File "/opt/weblibrary/vendor/flask/app.py", line 1982, in wsgi_app
>    response = self.full_dispatch_request()
>  File "/opt/weblibrary/vendor/flask/app.py", line 1614, in full_dispatch_request
>    rv = self.handle_user_exception(e)
>  File "/opt/weblibrary/vendor/flask/app.py", line 1517, in handle_user_exception
>    reraise(exc_type, exc_value, tb)
>  File "/opt/weblibrary/vendor/flask/app.py", line 1612, in full_dispatch_request
>    rv = self.dispatch_request()
>  File "/opt/weblibrary/vendor/flask/app.py", line 1598, in dispatch_request
>    return self.view_functions[rule.endpoint](**req.view_args)
>  File "/opt/weblibrary/vendor/flask_login/utils.py", line 228, in decorated_view
>    return func(*args, **kwargs)
>  File "/opt/weblibrary/cps/web.py", line 1099, in hot_books
>    title=_(u"Hot Books (most downloaded)"))
>  File "/opt/weblibrary/cps/web.py", line 611, in render_title_template
>    return render_template(instance=config.config_calibre_web_title, *args, **kwargs)
>  File "/opt/weblibrary/vendor/flask/templating.py", line 134, in render_template
>    context, ctx.app)
>  File "/opt/weblibrary/vendor/flask/templating.py", line 116, in _render
>    rv = template.render(context)
>  File "/opt/weblibrary/vendor/jinja2/environment.py", line 1008, in render
>    return self.environment.handle_exception(exc_info, True)
>  File "/opt/weblibrary/vendor/jinja2/environment.py", line 780, in handle_exception
>    reraise(exc_type, exc_value, tb)
>  File "/opt/weblibrary/cps/templates/index.html", line 1, in top-level template code
>    {% extends "layout.html" %}
>  File "/opt/weblibrary/cps/templates/layout.html", line 163, in top-level template code
>    {% block body %}{% endblock %}
>  File "/opt/weblibrary/cps/templates/index.html", line 47, in block "body"
>   <a href="{{ url_for('show_book', book_id=entry.id) }}" data-toggle="modal" data->target="#bookDetailsModal" data-remote="false">
>  File "/opt/weblibrary/vendor/flask/helpers.py", line 323, in url_for
>    force_external=external)
>  File "/opt/weblibrary/vendor/werkzeug/routing.py", line 1766, in build
>   rv = self._partial_build(endpoint, values, method, append_unknown)
>  File "/opt/weblibrary/vendor/werkzeug/routing.py", line 1681, in _partial_build
>    append_unknown)
>  File "/opt/weblibrary/vendor/werkzeug/routing.py", line 1689, in _partial_build
>    rv = rule.build(values, append_unknown)
>  File "/opt/weblibrary/vendor/werkzeug/routing.py", line 806, in build
>    add(self._converters[data].to_url(values[data]))
>  File "/opt/weblibrary/vendor/werkzeug/routing.py", line 1026, in to_url
>    value = self.num_convert(value)
>UndefinedError: 'None' has no attribute 'id'

**Comment by OzzieIsaacs** [comment]
Please try the newest commit, should work now

**Comment by teflontoni** [comment]
yup, it does, thank you.
