### ISSUE TITLE
Invalid amazon link

### ISSUE THREAD

**Issue by webysther** [janeczku/calibre-web#3151]
**Describe the bug/problem** 

With this ID on calibre `amazon_uk:0141439475` the link render:

![image](https://github.com/user-attachments/assets/a87f60fe-84e7-4739-9838-ded3bfaf63f9)

Send to: https://www.amazon.uk/dp/0141439475
Correct need include **.co**: https://www.amazon.co.uk/dp/0141439475

**Comment by OzzieIsaacs** [comment]
no rule without exception...

Please install a new package neamed "netifaces-plus" (has nothing to do with this fix) and update to the newest nightly version to enjoy the fix

**Comment by OzzieIsaacs** [comment]
Please leave it open till the next release

**Comment by webysther** [comment]
Oh boy... This happens also with amazon of brazil, amazon_br:8535282513 solve to https://amazon.br/dp/8535282513 but is https://amazon.com.br/dp/8535282513
