### ISSUE TITLE
Calibre-Web upgrade in RHEL 8

### ISSUE THREAD

**Issue by revog1410** [janeczku/calibre-web#3157]
Calibre-web was working and had an update to the newest version.  installed via the web console and calibre-web failed to restart and errors with python3.11 can't be found

![image](https://github.com/user-attachments/assets/d1bcacdb-9b8d-4d15-bd58-154a146ad840)

Running python 3.9 as default, python3.11 installed

Attempted to restart same error

Reinstalled python3.11 and later python3.12 with associated pip.  --- same issues

tried re-installing calibre-web via pip
pip3 install calibreweb

In all instances python3.11, 3.12 and attempting to revert to 3.9 it is unable to install with the following errors:

![image](https://github.com/user-attachments/assets/0de49ff0-a969-4a40-977a-44b87d8e292f)

Looked at forum and it recommended for windows with this error to revert to 3.9.. attempted that also and it still failed as the newer version wants 3.11 or higher.

**Comment by OzzieIsaacs** [comment]
Please install the python development tools: folowing the answer in this stackoverflow question:
https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory

`sudo yum install python3-devel `

and try again (please google the next error message by yourself)

**Comment by OzzieIsaacs** [comment]
And please also note this sentence :
![grafik](https://github.com/user-attachments/assets/bcdc6ace-8350-432d-bfa6-c3f0ddb0cfb4)
