### ISSUE TITLE
Removing a book from a shelf

### ISSUE THREAD

**Issue by teflontoni** [janeczku/calibre-web#316]
... is not working for me

if click on the x or shelf name and nothing happens, calibre-web.log stays silent about this.

Browser console comes up with this:

> Failed to load resource: the server responded with a status of 403 (FORBIDDEN)               
  remove/4/559 

Might be my setup. Any hints what to look for?

**Comment by OzzieIsaacs** [comment]
Just checked, works for me. So we need more details:

Are we talking on a public or private shelf?
Is the user admin, or guest account? 
Which access rights has the user?
In case of public shelf, is the user the creator of the shelf?
Which version of flask and flask-login is installed (stats page)?

**Comment by teflontoni** [comment]
OK, here is some more input:

User is Admin, it's a public shelf, created by this user.
User has any right toogable.

Accessing calibre web with an apache reverse proxy and https.

Flask  v0.12.2
Flask Login and Principal v0.4.0

**Comment by jkrehm** [comment]
What about your Apache logs? Anything useful in there to explain the 403?
What shows up in the response?

The code only returns a 403 for that request under these circumstances:
```
    if not shelf.is_public and not shelf.user_id == int(current_user.id) \
            or (shelf.is_public and current_user.role_edit_shelfs()):
```

If the calibre-web.log file doesn't have "Sorry you are not allowed to remove a book from this shelf:" in it, then it's most likely not an issue with calibre-web and is instead an error that's returned by Apache.

**Comment by teflontoni** [comment]
That's the only thing I've got:

> [Mon Sep 11 09:04:34.379161 2017] [core:warn] [pid 16221] (101)Network is unreachable: AH00056: connect to listener on [::]:80

**Comment by teflontoni** [comment]
as it's my setup that's faulty, I'll close this.
