### ISSUE TITLE
Could not locate runnable browser

### ISSUE THREAD

**Issue by pablominue** [janeczku/calibre-web#3165]
Describe the bug
Getting could not locate runnable browser error when setting up gmail account

To Reproduce

Go to admin/Edit Email Server Settings

Click on Setup Gmail Account

Expected behavior
Google Authentication

Configuration(please complete the following information):

OS Unraid

Hardware: Lincstation N1

Default instalation, gmail.json added successfully

**Comment by OzzieIsaacs** [comment]
This is a known problem with docker setups

https://github.com/janeczku/calibre-web/issues/2254
