### ISSUE TITLE
Change Amazon metadata

### ISSUE THREAD

**Issue by trigao** [janeczku/calibre-web#3166]
im using ina Asustor NAS and when i fetch metadata of my book, its search in amazon.com and dont find anything
i would like to change to amazon.com.br, is this possible??

a way to add metadata fetcher will be nice

**Comment by OzzieIsaacs** [comment]
Have a look here:
https://github.com/janeczku/calibre-web/wiki/Developer's-corner#add-metadata-provider

Please do it on your own:
You can take this file, copy it and modify the link (Change the __name__ attribute so your version will show up, or just change the file, please make sure to exclude the new file from updates):
https://github.com/janeczku/calibre-web/blob/master/cps/metadata_provider/amazon.py
