### ISSUE TITLE
Unable to designate Series ID with a trailing 0

### ISSUE THREAD

**Issue by Goonisto** [janeczku/calibre-web#3171]
If attempting to set Series ID to decimals ending in 0, it truncates the zero. Ex. 1.10 becomes 1.1. This prevents sorting by Series ID properly.

**Comment by OzzieIsaacs** [comment]
Duplicate of https://github.com/janeczku/calibre-web/issues/1213
There is a change in the newest nightly version to make the trailing zero visible:
![grafik](https://github.com/user-attachments/assets/458fbd91-dc42-4e1f-bf6b-a5a3cbb3cad6)
