### ISSUE TITLE
Sorting by Series ID does not allow for sorting in order with decimals above .9

### ISSUE THREAD

**Issue by Goonisto** [janeczku/calibre-web#3172]
If you set a Series ID to 1.12, it will show up after 1.1 rather than after 1.11.

**Comment by OzzieIsaacs** [comment]
No:

![grafik](https://github.com/user-attachments/assets/6afedd01-a905-42a4-abeb-69e2fe47de1d)

Anyhow, there is a change in the newest nightly version to avoid the confusion regarding missing trailing zero.
See #1213 and #3171
