### ISSUE TITLE
Endless login / Help with VirtualHost configuration

### ISSUE THREAD

**Issue by FeralFox** [janeczku/calibre-web#3175]
**Describe the bug/problem** 

I run calibre-web using docker and I guess I need some help with the Virtualhost configuration file.

Currently, everytime I click a link, I am redirected to the login page.
If i login again, I will get to the desired page, but when clicking the next link, I will be redirected to the login page again.
As far as I know, this happens as the authentication cookie is not forwarded correctly.

**To Reproduce**

1. Login
2. Click any link
3. Login again
4. Click any other link
5. Login again
...

**Environment (please complete the following information):**

 - Latest Calibreweb on Linux using docker.

**Additional context**

This is the VirtualHost file I use. It was working until some weeks ago. Then, the login-issue appeared (probably after some system updates)

```
<VirtualHost *:80>
DocumentRoot "/home/me/test"
ServerName calibreweb.myserver.net

ProxyRequests On
ProxyPreserveHost On

ProxyPass / http://0.0.0.0:8083/
ProxyPassReverse / http://0.0.0.0:8083/
ProxyPassReverseCookiePath / /
</VirtualHost>
```

Does somebody know what could be the issue?

Thank you very much in advance!

**Comment by robajr** [comment]
I have the same problem. If I log in directly (serverip:8083) I have no issues. If I login via an nginx proxy (prettyurl.com) I timeout to a 504 timeout. I tried CORS (via nginx, and via implementing flask-cors in the app python) and that didn't solve the issue. Calibre admin logfile shows no errors.

**Comment by robajr** [comment]
Attempted to update flask-login to v0.7, did not resolve proxy issues.

**Comment by FeralFox** [comment]
For me it worked again after the latest update (0.6.23). My current VirtualHost configuration is this:

```
<VirtualHost *:80>
DocumentRoot "/home/me/anyfolder"
ServerName my.server.net

ProxyRequests On
ProxyPreserveHost On

ProxyPass / http://0.0.0.0:8083/
ProxyPassReverse / http://0.0.0.0:8083/
ProxyPassReverseCookiePath / /
```
