### ISSUE TITLE
OPDS download epub error doctype

### ISSUE THREAD

**Issue by uschi1** [janeczku/calibre-web#3176]
Hello, unfortunately I hardly speak any English and have to use Google Translate, so please excuse the bad translation!  I think calibre-web does a great job of storing ebooks!!! I installed calibre-web on my Synology in a Docker, it works great, now I wanted to add the OPDS library via the Pocketbook Android app, that also worked, but downloading doesn't work, so I attached a screenshot! Is this an error in my configuration, or does it just not work?
I would look forward to an answer!
Ursula
![Screenshot_20241005_161525_PocketBook](https://github.com/user-attachments/assets/1025c37a-319f-40d5-baa6-57f4accd8d10)

**Comment by uschi1** [comment]
Zuerst mal vielen lieben Dank, dass du dich überhaupt meldest, dass ist für mich nicht selbstverständlich,  vor allem weil du das ja alles wahrscheinlich in deiner Freizeit machst und ich happy über calibre-web bin, denn alles andere funktioniert ja !!!

Also, das runterladen über den normalen Browser funktioniert einwandfrei ..... und ja 🥺 ich habe es auf meiner Synology in einem Docker installiert, ich wüsste auch gar nicht, wo ich es sonst installieren sollte??
Ich habe aber trotzdem die Debug Datei angehängt...

Gibt es eigentlich eine synch Methode für den Lesefortschritt mit Koreader?

Gruß Ursula
Ursula Bischofsberger
_______________
Schnaittacher Straße 14b
90562 Heroldsberg
***@***.***

15.10.2024 20:42:42 Ozzie Isaacs ***@***.***>:

**Comment by OzzieIsaacs** [comment]
Hallo Ursula,

die Datei ist leider nicht angekommen. Am Besten auf der Githubseite in dem "Issue" die Datei in das "Add a comment" Feld ziehen.
Wenn der Download im normalen Browser geht ist das schonmal gut und meine Vermutung stimmt wahrscheinlich nicht
Eine Sync Methode für den Koreader gibt es nicht

**Comment by uschi1** [comment]
[Calibre-Web-debug-pack.zip](https://github.com/user-attachments/files/17394048/Calibre-Web-debug-pack.zip)

**Comment by uschi1** [comment]
Hat es jetzt geklappt?

**Comment by OzzieIsaacs** [comment]
Ja hat geklappt, danke. Ich schaue es mir heute abend an

**Comment by OzzieIsaacs** [comment]
Also in den Logs findet man keinen Eintrag. Ich denke es passiert folgendes:
- Du hast "Anonymes Durchsuchen aktivieren", d.h. jeder kann Bücher ohne Anmeldung ansehen, der Gast Benutzer (Guest) hat keine Download Berechtigung
- Du hast Dich in der Pocketbook App mit deinem Benutzer angemeldet, dieser hat Download Berechtigungen
- Sobald Du in der Pocketbook App auf Download klickst  startet die App eine Anfrage allerdings ohne die Benutzerdaten (also als Gast Benutzer), dadurch wird der Download verweigert.

Lösungsmöglichkeiten:
"Anonymes Durchsuchen aktivieren" ausschalten

oder

Ich habe etwas geändert, es ist möglich das es jetzt geht, dazu müsstest Du die Software auf die "Nightly Version ändern" von LinuxServer gibt es einen entsprechenden Docker Container (falls Du das nutzt).
Ansonsten müsstest Du bis zum nächsten Release warten (ist noch nicht geplant)

**Comment by uschi1** [comment]
Jihuuu es funktioniert jetzt, ich habe tatsächlich gestern ein update vorgenommen und nachdem ich meine Daten nicht sichern kann, musste ich alles nochmal neu einstellen, danach ging alles einwandfrei! Ob das jetzt das update war, oder an den Einstellungen lag weiß ich nicht, aber Hauptsache es funktioniert jetzt!
Ganz lieben Dank für das durchschauen der Support Daten...
Noch eine kurze Frage, warum gibt es eigentlich keine Funktion Sichern/Wiederherstellen?
Mit dem Docker habe ich keine Möglichkeit auf die Daten zuzugreifen, zumindest bin ich so blond, dass ich nicht weiß wie, also muss ich bei jedem Update, die Konfiguration Neu machen!
Gruß Ursula

**Comment by OzzieIsaacs** [comment]
Die Daten sind in der Datei app.db gespeichert, sofern man diese sichert/nicht überschreibt und ggf. wieder zurückspeichert bleibt die Konfiguration erhalten

**Comment by uschi1** [comment]
Da liegt der Hund begraben 😢, auf die Dateien habe ich keinen Zugriff, zumindest habe ich es noch nicht rausgefunden  wo die auf der Synology hingeschrieben werden, deshalb dachte ich, wäre es toll, wenn das über die Oberfläche zum Speichern wäre....

Gruß Ursula

20.10.2024 06:44:59 Ozzie Isaacs ***@***.***>:

**Comment by uschi1** [comment]
Hallo, ich habe den Calibre-web Container nochmal neu installiert und nun das Problem, dass Calibre-web den ganzen tag funktioniert und plötzlich nicht mehr, dann sieht das ganze so aus:

![Screenshot_20241027_190614_Opera](https://github.com/user-attachments/assets/0ed20c39-b431-4bd9-a767-c38175556d9e)

Ich habe mir die Debug und Logdatei runtergladen, hilft das weiter? Ich weiß nicht mehr was ich machen soll....
[Calibre-Web-debug-pack.zip](https://github.com/user-attachments/files/17535024/Calibre-Web-debug-pack.zip)
[calibre-web.log](https://github.com/user-attachments/files/17535025/calibre-web.log)

**Comment by uschi1** [comment]
Nachtrag:
Wenn ich am PC Calibre starte und anschließend wieder calibre-web öffne, funktioniert alles wieder ohne Probleme.... 
Hast du eine Idee, was das sein kann?
