### ISSUE TITLE
Limit 'Read in browser' based on file size

### ISSUE THREAD

**Issue by webysther** [janeczku/calibre-web#3180]
**Is your feature request related to a problem? Please describe.**
Current reader download the entire file before render.

**Describe the solution you'd like**
Limit 'Read in browser' based on file size, CBZ, CBR or even PDF files with more than 100MB can be really slow to read because the current reader download the entire file before render it. Limit based on file size can allow save bandwidth and make clear the only option for such files is download it.

**Describe alternatives you've considered**
Maybe fix reader to work like kavita/komga for CBZ/CBR to read every image

**Comment by OzzieIsaacs** [comment]
This would just add up another level of complexity, in the books details page the file size is clearly visible. If I would add a setting I'm sure this would lead to many questions (why is it not possible to read my book)
