### ISSUE TITLE
Search error!! when fetching metadata

### ISSUE THREAD

**Issue by NathanIfinity** [janeczku/calibre-web#3188]
**Describe the bug/problem** 

Unable to search for any metadata

**To Reproduce**

1. Go to 'any book
2. Click on 'Fetch Metadata'
3.Click Search 
4.  See error

**Logfile**

[2024-10-20 00:36:42,473] ERROR {cps.metadata_provider.amazon:49} 503 Server Error: Service Unavailable for url: https://www.amazon.com/s?k=Heartless+-+Elsie+Silver&i=digital-text&sprefix=Heartless+-+Elsie+Silver%2Cdigital-text&ref=nb_sb_noss

[2024-10-20 00:36:42,519]  WARN {cps.metadata_provider.google:56} 429 Client Error: Too Many Requests for url: https://www.googleapis.com/books/v1/volumes?q=Heartless+Elsie+Silver
[2024-10-20 00:36:42,522] ERROR {cps:1414} Exception on /metadata/search [POST]

**Expected behavior**

Fetch the metadata for the selected book, tried with each one and none work they all give me an error message

**Screenshots**

![image](https://github.com/user-attachments/assets/f61e0278-c95f-4b0e-a7d8-1c0077c7cc44)

**Environment (please complete the following information):**

 - Calibre-Web version: [e.g. 0.6.23]:
 - Docker container: [LinuxServer]:
 - Browser: [e.g. Chrome 129.0.6668.103]

**Additional context**
N/A

**Comment by OzzieIsaacs** [comment]
Please update to the newest nightly version

**Comment by OzzieIsaacs** [comment]
The "429 Client Error: Too Many Requests" is because you searched to many times in a too short time, so waiting for a while should resolve this by it's own
On the newest nightly version it's working for me:
![grafik](https://github.com/user-attachments/assets/646c21ba-8590-4db0-968b-ae0baae2005f)

**Comment by NathanIfinity** [comment]
Where can I find the nightly version ?

**Comment by OzzieIsaacs** [comment]
Linuxserver is providing a nightly-docker container

**Comment by NathanIfinity** [comment]
I just switched the channel to nightly in the settings, trying this right now !

**Comment by NathanIfinity** [comment]
the nightly update fixed the issue
