### ISSUE TITLE
Calibre Web 500 Internal Server Error

### ISSUE THREAD

**Issue by herrerawilliamh** [janeczku/calibre-web#3197]
I have an installation in docker and portainer, I installed it and at first everything was fine. But once I put the database folder, the sign that you see in the image starts to appear.
![image](https://github.com/user-attachments/assets/c778b772-874c-4ce4-9a15-01a0b6893840)

**Comment by OzzieIsaacs** [comment]
The usual docker problem with wrong permissions/file locations, there are a lot of issues regarding this, please contact the docker container provider (or read the manual better). I don't know the solutions, but 500% sure I'm right and it's not a problem of calibre-web
