### ISSUE TITLE
upload?!

### ISSUE THREAD

**Issue by perler** [janeczku/calibre-web#32]
is the upload functionality not implemented yet or am I just to blind to find it?

**Comment by janeczku** [comment]
See https://github.com/janeczku/calibre-web#runtime-configuration-options

**Comment by perler** [comment]
PDF upload? so this is not an upload into the calibre library?

On Thu, Jul 14, 2016 at 1:41 AM Jan B <notifications@github.com> wrote:

> Closed #32 <https://github.com/janeczku/calibre-web/issues/32>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/janeczku/calibre-web/issues/32#event-722326826>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAmB9Knr1WuYezCOlT3sIMheDW3gRhcqks5qVXergaJpZM4I9_bD>
> .
>
--
