### ISSUE TITLE
Kobo sync does not respect series entry 0

### ISSUE THREAD

**Issue by nrbeaton** [janeczku/calibre-web#3204]
**Describe the bug/problem** 

I have a series which I've marked as having entry 0. This shows up in Calibre and Calibre-Web as entry 0 just fine. But when I sync to Kobo, on the device it shows as entry 1. (There is also an entry 1, so now on the device there are two entry 1s.)

Previously when I was transferring via USB, the book showed as entry 0. So this does seem specific to Calibre-Web.

**Environment (please complete the following information):**

 - OS: Arch Linux
 - Calibre-Web version: 0.6.23, installed from the AUR
 - Device: Kobo Libra 2

Not sure what other info is relevant, let me know and I'll post it.

**Comment by OzzieIsaacs** [comment]
Yeah, everything beside "0" is working

**Comment by OzzieIsaacs** [comment]
Please check the newest nightly version

**Comment by nrbeaton** [comment]
Yes that's resolved the issue.
