### ISSUE TITLE
Uploading of pdf slow and then 'Upload done, processing, please wait...' hangs forever

### ISSUE THREAD

**Issue by ikwyl6** [janeczku/calibre-web#3205]
**Describe the bug/problem** 

Uploading a pdf file (19MB) takes very long time (calibre-web is hosted on my LAN) and when the progress bar finishes to 100% the dialog box says:

```Upload done, processing, please wait...```

and hangs there for very long time. I can just reload the page by clicking Books but the book is not present. 

version: ```0.6.23```

I did have 0.6.22 installed and just installed 0.6.23 but the issue is still present. Here is my output from the install (no issues):
```
Downloading calibreweb-0.6.23-py3-none-any.whl (7.8 MB)
   ──────────────────────────────────────── 7.8/7.8 MB 25.5 kB/s eta 0:00:00
Downloading Flask_HTTPAuth-4.8.0-py3-none-any.whl (7.0 kB)
Installing collected packages: flask-httpAuth, calibreweb
  Attempting uninstall: calibreweb
    Found existing installation: calibreweb 0.6.22
    Uninstalling calibreweb-0.6.22:
      Successfully uninstalled calibreweb-0.6.22
Successfully installed calibreweb-0.6.23 flask-httpAuth-4.8.0
```
From my attached log, I started 0.6.23 on line ```2024-10-27 23:23:26,153``` of the attached log.

**To Reproduce**

1. Log into calibre-web
2. Click on Upload button
3. on the popup dialog box, select a pdf
4. Progress bar is displayed and eventually uploads PDF file (I think)
5. The progress bar just shows ```Upload done, processing, please wait...``` for very long time.

**Logfile**
[calibre-web-ikwyl6-2024-10-27.log](https://github.com/user-attachments/files/17536660/calibre-web-ikwyl6-2024-10-27.log)

**Expected behavior**

pdf should be uploaded (quickly) and then I can add the metadata for the pdf book.

**Screenshots**

If you need screenshots I can add them. 

**Environment (please complete the following information):**

 - OS: headless odroid running arch linus arm
 - Python version: From venv python 3.12.7
 - Calibre-Web version: 0.6.23
 - Docker container: LinuxServer
 - Special Hardware: Odroid
 - Browser: [Version 1.71.114 Chromium: 130.0.6723.58 (Official Build) (64-bit)](https://brave.com/latest/)

**Additional context**
N/A

**Comment by OzzieIsaacs** [comment]
I'm sure it hangs not forever, but parsing the pdf to extract the metadata takes a while especially on slow hardware like Raspberry/Odroid.
How long was "forever"?

**Comment by OzzieIsaacs** [comment]
You could uninstall pypdf via: `python -m pip uninstall pypdf` to bypass the metadata extraction.
Depending on when you tried this, the message:
`[2024-10-26 23:27:35,514]  INFO {tornado.general:294} Malformed HTTP message from 192.168.4.1: Content-Length too long`
could also be of relevance (try to increase the max content length of the proxy the docker container uses)

**Comment by ikwyl6** [comment]
Ok I'll try that. Metadata I can add in myself if I really need/want it. Thanks for heads up.

**Comment by ikwyl6** [comment]
> I'm sure it hangs not forever, but parsing the pdf to extract the metadata takes a while especially on slow hardware like Raspberry/Odroid. How long was "forever"?

Oh - 'forever' is atleast 10 minutes...
