### ISSUE TITLE
tts ?

### ISSUE THREAD

**Issue by NeverBeLazyG** [janeczku/calibre-web#3208]
where is tts? its missing. even the original simple server does have it.

**Comment by OzzieIsaacs** [comment]
no idea

**Comment by NeverBeLazyG** [comment]
calibre web is garbage. its just a blender, with much less functionality then the original web-app from the author of calibre. it just looks a bit better, but the functionality is garbage. totaly limited. i am back to the original web-app. its way better with much more possibilites.
