### ISSUE TITLE
calibre-web is garbage

### ISSUE THREAD

**Issue by NeverBeLazyG** [janeczku/calibre-web#3211]
calibre web is garbage. its just a blender, with way less functionality then the original web-app from the author of calibre. it just looks a bit better, but the functionality is garbage. totaly limited. i am back to the original web-app. its way better with much more possibilites.

**Comment by mohammed90** [comment]
What's your point of coming here spewing venom? Couldn't you just keep it to yourself? You had to show your real self, being a jerk in public, and hateful little being? The maintainer didn't force your hand into using. Go be an ass elsewhere. Try a mirror.

**Comment by OzzieIsaacs** [comment]
I'm not the owner, so i can't block the user. I reported him

**Comment by NeverBeLazyG** [comment]
> What's your point of coming here spewing venom? Couldn't you just keep it to yourself? You had to show your real self, being a jerk in public, and hateful little being? The maintainer didn't force your hand into using. Go be an ass elsewhere. Try a mirror.

no one asked you. or are you his advocate?

**Comment by NeverBeLazyG** [comment]
> I'm not the owner, so i can't block the user. I reported him

oh you reported me ? because i critisized your bad tool ?

**Comment by mohammed90** [comment]
> the maintainer is pushing a tool

Was the pushing at gun-point? You were commanded to either use it or die? Stop being ridiculous

**Comment by NeverBeLazyG** [comment]
> > the maintainer is pushing a tool
> 
> Was he pushing at gun-point? You were commanded to either use it or die? Stop being ridiculous

what is it up to you? abu mohammad mostafa abdal abu hanafai bin sarkawi ? 🤣. i will not stop doing somthing, because you told me. for me this tool is garbage ! So stop interfering and mind your own business.I will continue to criticize bad tools, and I will certainly not let you forbid me to do so. So go ahead.
