### ISSUE TITLE
I don't see a part of my books in calibre-web

### ISSUE THREAD

**Issue by zelig2004** [janeczku/calibre-web#3219]
Hi,
My calibre library on my HD Synology/pc contains more than 5000 books but when I consult it on calibre-web a lot of books are missing. There are only about 4,000 books left. I don't understand why some of them disappear, are not referenced?

Thank you for your help

**Comment by OzzieIsaacs** [comment]
There are settings to hide books per user:
- based on books language
- Based on tags
- Based on a custom column

please check the user settings as admin

**Comment by OzzieIsaacs** [comment]
https://github.com/janeczku/calibre-web/wiki/Configuration#visibility-restrictions-based-on-calibre-custom-column
