### ISSUE TITLE
How to add books to library?

### ISSUE THREAD

**Issue by lbls55** [janeczku/calibre-web#3227]
How to add books in calibre-web?

I've installed calibre-web as a docker container in a synology nas (DSM 7.1), it's working, I can access the webinterface, I've putted some ebooks in the /Media/books folder on my nas. 
But how to make them appear in the calibre-web webpage???

**Comment by OzzieIsaacs** [comment]
This is not how it's supposed to work.
Please enable upload in the webpage (admin -> Basi config -> feature config -> enable upload), the ensure the user has the right to uploasd books (admin -> user setup -> upload permission)
The you can upload the books via the upload button on top. 
Alternativly: Open the databse with calibre desktop programm and add the books there (calibre-web has problems with uploading many books at one time)

**Comment by lbls55** [comment]
Many thanks for your great work and for your help! You solve the problem...Everything is ok now!!!


________________________________
De : Ozzie Isaacs ***@***.***>
Envoyé : lundi 18 novembre 2024 17:15
À : janeczku/calibre-web ***@***.***>
Cc : lbls55 ***@***.***>; Author ***@***.***>
Objet : Re: [janeczku/calibre-web] How to add books to library? (Issue #3227)


This is not how it's supposed to work.
Please enable upload in the webpage (admin -> Basi config -> feature config -> enable upload), the ensure the user has the right to uploasd books (admin -> user setup -> upload permission)
The you can upload the books via the upload button on top.
Alternativly: Open the databse with calibre desktop programm and add the books there (calibre-web has problems with uploading many books at one time)
