### ISSUE TITLE
Windows exe produces ios-639 is missing and isn't starting

### ISSUE THREAD

**Issue by OzzieIsaacs** [janeczku/calibre-web#3228]
On Windows, **I am still getting the error**. Do you know what I can do? - 

C:\calibre\>calibreweb.exe
*** Cannot import iso-639 module, it is needed to run calibre-web, please install it using "pip install iso-639" ***

**I have requirements.txt installed** - C:\calibre\>python3.exe -m pip install -r _internal\requirements.txt
`Defaulting to user installation because normal site-packages is not writeable
Ignoring iso-639: markers 'python_version < "3.12"' don't match your environment
Requirement already satisfied: APScheduler<3.11.0,>=3.6.3 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from -r _internal\requirements.txt (line 1)) (3.10.4)
Requirement already satisfied: Babel<3.0,>=1.3 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from -r _internal\requirements.txt (line 2)) (2.16.0)
Requirement already satisfied: Flask-Babel<4.1.0,>=0.11.1 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from -r _internal\requirements.txt (line 3)) (4.0.0)
Requirement already satisfied: Flask-Principal<0.5.1,>=0.3.2 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from -r _internal\requirements.txt (line 4)) (0.4.0)
Requirement already satisfied: Flask<3.1.0,>=1.0.2 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from -r _internal\requirements.txt (line 5)) (3.0.3)
Requirement already satisfied: pycountry<25.0.0,>=20.0.0 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from -r _internal\requirements.txt (line 7)) (24.6.1)
Requirement already satisfied: PyPDF<5.1.0,>=3.15.6 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from -r _internal\requirements.txt (line 8)) (5.0.1)
Requirement already satisfied: pytz>=2016.10 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from -r _internal\requirements.txt (line 9)) (2024.2)
Requirement already satisfied: requests<2.33.0,>=2.32.0 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from -r _internal\requirements.txt (line 10)) (2.32.3)
Requirement already satisfied: SQLAlchemy<2.1.0,>=1.3.0 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from -r _internal\requirements.txt (line 11)) (2.0.36)
Requirement already satisfied: tornado<6.5,>=6.3 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from -r _internal\requirements.txt (line 12)) (6.4.1)
Requirement already satisfied: Wand<0.7.0,>=0.4.4 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from -r _internal\requirements.txt (line 13)) (0.6.13)
Requirement already satisfied: unidecode<1.4.0,>=0.04.19 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from -r _internal\requirements.txt (line 14)) (1.3.8)
Requirement already satisfied: lxml<5.3.0,>=4.9.1 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from -r _internal\requirements.txt (line 15)) (5.2.2)
Requirement already satisfied: flask-wtf<1.3.0,>=0.14.2 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from -r _internal\requirements.txt (line 16)) (1.2.2)
Requirement already satisfied: chardet<5.3.0,>=3.0.0 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from -r _internal\requirements.txt (line 17)) (5.2.0)
Requirement already satisfied: netifaces-plus<0.13.0,>=0.12.0 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from -r _internal\requirements.txt (line 18)) (0.12.3)
Requirement already satisfied: urllib3<3.0,>=1.22 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from -r _internal\requirements.txt (line 19)) (2.2.3)
Requirement already satisfied: Flask-Limiter<3.9.0,>=2.3.0 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from -r _internal\requirements.txt (line 20)) (3.8.0)
Requirement already satisfied: regex<2024.6.25,>=2022.3.2 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from -r _internal\requirements.txt (line 21)) (2024.5.15)
Requirement already satisfied: bleach<6.2.0,>=6.0.0 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from -r _internal\requirements.txt (line 22)) (6.1.0)
Requirement already satisfied: python-magic<0.5.0,>=0.4.27 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from -r _internal\requirements.txt (line 23)) (0.4.27)
Requirement already satisfied: python-magic-bin<0.5.0,>=0.4.0 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from -r _internal\requirements.txt (line 24)) (0.4.14)
Requirement already satisfied: flask-httpAuth<5.0.0,>=4.4.0 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from -r _internal\requirements.txt (line 25)) (4.8.0)
Requirement already satisfied: cryptography<44.0.0,>=30.0.0 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from -r _internal\requirements.txt (line 26)) (43.0.3)
Requirement already satisfied: six>=1.4.0 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from APScheduler<3.11.0,>=3.6.3->-r _internal\requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: tzlocal!=3.*,>=2.0 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from APScheduler<3.11.0,>=3.6.3->-r _internal\requirements.txt (line 1)) (5.2)
Requirement already satisfied: Jinja2>=3.1 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from Flask-Babel<4.1.0,>=0.11.1->-r _internal\requirements.txt (line 3)) (3.1.4)
Requirement already satisfied: blinker in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from Flask-Principal<0.5.1,>=0.3.2->-r _internal\requirements.txt (line 4)) (1.9.0)
Requirement already satisfied: Werkzeug>=3.0.0 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from Flask<3.1.0,>=1.0.2->-r _internal\requirements.txt (line 5)) (3.1.3)
Requirement already satisfied: itsdangerous>=2.1.2 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from Flask<3.1.0,>=1.0.2->-r _internal\requirements.txt (line 5)) (2.2.0)
Requirement already satisfied: click>=8.1.3 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from Flask<3.1.0,>=1.0.2->-r _internal\requirements.txt (line 5)) (8.1.7)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests<2.33.0,>=2.32.0->-r _internal\requirements.txt (line 10)) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests<2.33.0,>=2.32.0->-r _internal\requirements.txt (line 10)) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests<2.33.0,>=2.32.0->-r _internal\requirements.txt (line 10)) (2024.8.30)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from SQLAlchemy<2.1.0,>=1.3.0->-r _internal\requirements.txt (line 11)) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from SQLAlchemy<2.1.0,>=1.3.0->-r _internal\requirements.txt (line 11)) (3.1.1)
Requirement already satisfied: wtforms in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from flask-wtf<1.3.0,>=0.14.2->-r _internal\requirements.txt (line 16)) (3.2.1)
Requirement already satisfied: limits>=3.13 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from Flask-Limiter<3.9.0,>=2.3.0->-r _internal\requirements.txt (line 20)) (3.13.0)
Requirement already satisfied: ordered-set<5,>4 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from Flask-Limiter<3.9.0,>=2.3.0->-r _internal\requirements.txt (line 20)) (4.1.0)
Requirement already satisfied: rich<14,>=12 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from Flask-Limiter<3.9.0,>=2.3.0->-r _internal\requirements.txt (line 20)) (13.9.4)
Requirement already satisfied: webencodings in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from bleach<6.2.0,>=6.0.0->-r _internal\requirements.txt (line 22)) (0.5.1)
Requirement already satisfied: cffi>=1.12 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from cryptography<44.0.0,>=30.0.0->-r _internal\requirements.txt (line 26)) (1.17.1)
Requirement already satisfied: pycparser in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from cffi>=1.12->cryptography<44.0.0,>=30.0.0->-r _internal\requirements.txt (line 26)) (2.22)
Requirement already satisfied: colorama in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from click>=8.1.3->Flask<3.1.0,>=1.0.2->-r _internal\requirements.txt (line 5)) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from Jinja2>=3.1->Flask-Babel<4.1.0,>=0.11.1->-r _internal\requirements.txt (line 3)) (3.0.2)
Requirement already satisfied: deprecated>=1.2 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from limits>=3.13->Flask-Limiter<3.9.0,>=2.3.0->-r _internal\requirements.txt (line 20)) (1.2.15)
Requirement already satisfied: importlib-resources>=1.3 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from limits>=3.13->Flask-Limiter<3.9.0,>=2.3.0->-r _internal\requirements.txt (line 20)) (6.4.5)
Requirement already satisfied: packaging<25,>=21 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from limits>=3.13->Flask-Limiter<3.9.0,>=2.3.0->-r _internal\requirements.txt (line 20)) (24.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from rich<14,>=12->Flask-Limiter<3.9.0,>=2.3.0->-r _internal\requirements.txt (line 20)) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from rich<14,>=12->Flask-Limiter<3.9.0,>=2.3.0->-r _internal\requirements.txt (line 20)) (2.18.0)
Requirement already satisfied: tzdata in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from tzlocal!=3.*,>=2.0->APScheduler<3.11.0,>=3.6.3->-r _internal\requirements.txt (line 1)) (2024.2)
Requirement already satisfied: wrapt<2,>=1.10 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from deprecated>=1.2->limits>=3.13->Flask-Limiter<3.9.0,>=2.3.0->-r _internal\requirements.txt (line 20)) (1.16.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\ravi b\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from markdown-it-py>=2.2.0->rich<14,>=12->Flask-Limiter<3.9.0,>=2.3.0->-r _internal\requirements.txt (line 20)) (0.1.2)`

_Originally posted by @ravibaskaran in https://github.com/janeczku/calibre-web/issues/3140#issuecomment-2482982744_

**Comment by OzzieIsaacs** [comment]
Very stupid bug

**Comment by sir-wilhelm** [comment]
I had the same behavior using the install package from this morning, calibreweb.exe would crash and a log would have a line with:
```text
Cannot import iso-639 module, it is needed to run calibre-web, please install it using "pip install iso-639"
```

After using the new installer (`Calibre-Web-0624-Ext-Setup.exe`) it launches and keeps running in the background.

Thanks for the quick fix.

**Comment by OzzieIsaacs** [comment]
@ravibaskaran
