### ISSUE TITLE
"Check for Update" button is missing

### ISSUE THREAD

**Issue by trickinit** [janeczku/calibre-web#3234]
My Admin page does not have a "Check for Update" button

![image](https://github.com/user-attachments/assets/2e38a0ee-8ec4-4320-9307-f8f6fe18a890)

I manually updated my server to version 0.6.24 using the Windows .exe option. The update button was missing both before and after completing the update.

Here is my server info
![image](https://github.com/user-attachments/assets/d188a61b-0d77-4081-8fef-3127e868b2b1)

**Comment by OzzieIsaacs** [comment]
That's correct and intended. 

The updater is only capable of updating the source installations (the .py files), but not the exe files, therefore the button isn't available. And I will not program a version check or update function to the exe version

**Comment by trickinit** [comment]
Hey, thanks for clarifying. I appreciate the info and all the hard work you do. Cheers!
