### ISSUE TITLE
upgrade from 0.6.23 to 0.6.24 broke the installation

### ISSUE THREAD

**Issue by thncode** [janeczku/calibre-web#3241]
I am getting the error message on my RPI
*** Cannot import netifaces-plus module, it is needed to run calibre-web, please install it using "pip install netifaces-plus" ***

and installing netifaces-plus by
pip install netifaces-plus
just led to 
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement netifaces-plus
ERROR: No matching distribution found for netifaces-plus

any ideas anyone?

**Comment by OzzieIsaacs** [comment]
Have a look here: https://github.com/janeczku/calibre-web/issues/3236
