### ISSUE TITLE
Allow download tracking for anonymous users

### ISSUE THREAD

**Issue by Archinowsk** [janeczku/calibre-web#3244]
Could it be possible to add a setting to enable download tracking for anonymous users? 

Currently download tracking is only enabled for registered users: 

https://github.com/janeczku/calibre-web/blob/e6031844d5f10b825a5b412e452a3ac6bc210eb5/cps/helper.py#L1101-L1103

My use case is running a public library-kind page (https://roolipelikirjasto.fi) with only anonymous users and I would like to use the `Hot Books (Most Downloaded)` category and overall see download statistics.

**Comment by OzzieIsaacs** [comment]
You are aware, that the download statistic is on per user base, so a book once downloaded by a "guest" user counts same as 100 time the download of this book by guest user?

**Comment by Archinowsk** [comment]
Do you mean the fact that single anonymous user can download single book multiple times and every download is counted to statistic?

Our previous platform had similar statistics tracking and it didn't become a problem that each anonymous download was counted separately.

In practice simple "this book has been downloaded n times" would be enough, but I figured it's easier to modify the current implementation where download counts are per-user.

**Comment by Archinowsk** [comment]
You're right, I misunderstood how it works. Thanks for the clarification! Seems the current functionality doesn't work in my use-case. 

I wouldn't mind having per-book download tracking, but I understand it would be bigger undertaking than I anticipated at first.

I'll close this issue.
