### ISSUE TITLE
Remove authentication

### ISSUE THREAD

**Issue by Jocala** [janeczku/calibre-web#3246]
My installation of calibreweb is local to my network only. I'd like to remove password authentication.  Anyone know what portion of the code handles this?

**Comment by sir-wilhelm** [comment]
Any reason you can't just enable anonymous browsing? That might fit your use case an will be easier than trying to rip out the auth code.

https://github.com/janeczku/calibre-web/wiki/Configuration#enable-anonymous-browsing

Admin > Configuration > Edit Basic Configuration > Feature Configuration
* [x] Enable Anonymous Browsing

**Comment by Jocala** [comment]
Well, duh :)

Thank you!
