### ISSUE TITLE
There was a mistake when uploading this book

### ISSUE THREAD

**Issue by xxyyer** [janeczku/calibre-web#325]
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by teflontoni** [comment]
I'm pretty sure calibre-web can't handle the chinese symbols. Couldn't upload it either (even if I leave out the chinese text in the filename).

And on a side note: I know students have a tight budget, but your book looks like a pirated copy of an ebook and it isn't a good idea posting it to the public. Please refrain from doing so.

Here's the excerpt from the log:

>[2017-09-14 16:41:48,531] {/opt/weblibrary/vendor/flask/app.py:1560} ERROR - Exception on /upload 
> [POST]
>Traceback (most recent call last):
>  File "/opt/weblibrary/vendor/flask/app.py", line 1982, in wsgi_app
>    response = self.full_dispatch_request()
>  File "/opt/weblibrary/vendor/flask/app.py", line 1614, in full_dispatch_request
>    rv = self.handle_user_exception(e)
>  File "/opt/weblibrary/vendor/flask/app.py", line 1517, in handle_user_exception
>    reraise(exc_type, exc_value, tb)
>  File "/opt/weblibrary/vendor/flask/app.py", line 1612, in full_dispatch_request
>    rv = self.dispatch_request()
>  File "/opt/weblibrary/vendor/flask/app.py", line 1598, in dispatch_request
>    return self.view_functions[rule.endpoint](**req.view_args)
>  File "/opt/weblibrary/vendor/flask_login/utils.py", line 228, in decorated_view
>    return func(*args, **kwargs)
>  File "/opt/weblibrary/cps/web.py", line 499, in inner
>    return f(*args, **kwargs)
>  File "/opt/weblibrary/cps/web.py", line 2953, in upload
>    if not os.path.exists(filepath):
>  File "/usr/lib64/python2.7/genericpath.py", line 18, in exists
>    os.stat(path)
>TypeError: must be encoded string without NULL bytes, not unicode

**Comment by jkrehm** [comment]
For what it's worth, I was able to upload that file to my development environment (macOS) without issue. For unrelated reasons I can't upload (anything) to my Linux environment, so I can't test there.

Python 2.7.10

**Comment by OzzieIsaacs** [comment]
I don't think it's avoid idea to upload copyright protected books here.

**Comment by xxyyer** [comment]
Ok, thank you :)

**Comment by OzzieIsaacs** [comment]
The filename in the book ends with a string delimiter '\0' the new version will handle that correctly
