### ISSUE TITLE
Questions Regarding Importing New Books

### ISSUE THREAD

**Issue by IAmDarthMole** [janeczku/calibre-web#3255]
**Describe the bug/problem** 

After checking https://github.com/janeczku/calibre-web/wiki/Automatically-import-new-books-(Linux) I'm just a little confused about updating my Calibre database with new books.

I have Calibre and Calibre-Web installed on my ubuntu server. I can make changes to books through Calibre-Web and they show up in Calibre and I can make changes in Calibre and they show up in Calibre-Web.

1) If I use Calibre, on my server, to "Add Books" to the library like I normally would, which would then update the Calibre database, would Calibre-Web also reflect the changes next time I log in? 

2) If I use Calibre-Web's upload feature to upload a supported ebook file(s) (IE: epub) will it automatically update the Calibre database and subsequent folder structure like Calibre does when importing?

I would try the above questions but I don't want to risk corrupting my database as I've spent a lot of time getting everything converted. I also apologize if I'm misusing any terminology or am completely off base with my current understanding. Thank you very much!

**Environment (please complete the following information):**

 - OS: Ubuntu 22.04
 - Python version: 3.10.12
 - Calibre-Web version: 0.6.24, through PIP
 - Docker container: None, Ubuntu Server
 - Special Hardware: None
 - Browser: Firefox 133.0 Snap

**Comment by OzzieIsaacs** [comment]
1) yes. Calibre locks the database, so if  calibre is started before calibre is running, it will not work
2) yes, but calibre will only see the changes after a restart,as it requests exclusive access to the database

**Comment by IAmDarthMole** [comment]
> 1. yes. Calibre locks the database, so if  calibre is started before calibre is running, it will not work
> 2. yes, but calibre will only see the changes after a restart,as it requests exclusive access to the database

Thank you very much!
