### ISSUE TITLE
trouble reading directories with two middle periods (used for middle author initials)

### ISSUE THREAD

**Issue by JmzLo** [janeczku/calibre-web#3256]
I've recently noticed that Calibre-web has trouble reading from directories with two middle initials followed by two periods.  For example.  Books by the Author "Delana R. A. Dameron" store in a Delana R. A. Dameron directory cannot be found and report the following error:

File not found: /books/Delana R. A. Dameron/Redwood Court (26247)/Redwood Court - Delana R. A. Dameron.epub

These can be accessed correctly through the stand-alone Calibre application.

If I rename the author/directory by removing just one period -  /books/Delana R. A Dameron - it works correctly.

Environment:
 - OS: Linux 4.4.302+ #72806 SMP Thu Sep 5 13:44:44 CST 2024 x86_64 x86_64
 - Calibre-Web version: 0.6.24 - 0af52f205358b0147ee3430f9e6c8fe007c0ea77 - 2024-11-16T07:21:28+01:00
 - Docker container: LinuxServer

Screenshots attached:

![Before](https://github.com/user-attachments/assets/7ce60ca1-bb80-4fd8-bf50-a41629236761)
![After](https://github.com/user-attachments/assets/8dd84937-4f8f-47c9-9e7c-52f70467c41d)

**Comment by OzzieIsaacs** [comment]
For me it's working. I guess there is some problem with the information in database and on file system.
A) Please provide exact steps to produce the error from zero (e.g. upload book, rename book, upload book via calibre... with specific titles authors, (files?) and steps to reproduce), please also provide the debug_package file (from admin page) you could send it to me via private email, to limit the people having access to the information
 
B) Please try to perform a database maintenance from calibre program itself to fix the problems.

C) I guess renaming the file in calibre-web forth and back might solve the problem

**Comment by JmzLo** [comment]
The LinuxServer docker container that I use updated last night and I'm also not seeing the problem anymore.  I'm not sure what changed, but I tried a few things and seems to be working correctly.  Thanks for looking into it and Happy Holidays!

PS, happy to still provide a debug_package if you're curious.  Otherwise, I'll close this issue.

**Comment by OzzieIsaacs** [comment]
If you can‘t reproduce the issue anymore I will not find anything, so no need to send it
