### ISSUE TITLE
Anonymous cannot upload error

### ISSUE THREAD

**Issue by eightwt** [janeczku/calibre-web#3257]
I have installed calibre-web on my headless Debian server following all the instructions I could find. I can bring up the web interface on all of my devices in my LAN and download books with no issues. However I cannot upload any new books to the server through the web interface. I get the anonymous user error.

When I first ran calibre-web I did not get any configuration pages and I still can't even by trying a direct URL. Is there a py file that can be edited to allow me to upload? Or do I have to re-install, this time using a container?

Thnx, Geoff

**Comment by OzzieIsaacs** [comment]
Please refer to the readme for setting up calibre-web. You need to login first, then you can setup the database. Afterwards it's possible to enable uploads. 

[You need ](https://github.com/janeczku/calibre-web?tab=readme-ov-file#quick-start)

If this answer doesn't fit to your question, please be more precise what you did (step by step like explaining it to somebody totally stupid like me)

**Comment by eightwt** [comment]
Ozzie,

I uninstalled and reinstalled as per your manual installation instructions (https://github.com/janeczku/calibre-web/wiki/Manual-installation) . I think your instructions were pretty easy to follow and this was the first time I saw the login and configure pages once I figured out how to launch it on the server.  I had to hunt for the "enable uploads" switch, but once I found it I could add books to my library. I moved the local Calibre libray from my laptop to the server and I was good to go.

Next I wanted to set up a cps.service. That was another adventure. I kept getting what looked like permission errors each time I tried to start the daemon. Somewhere I read that changing the write permissions (chmod 664) on /opt/calibre-web/app.db may help. I did that and also got a write error re: calibre-web.log, so I changed that too. Now it works perfectly. I can reach the server on my Kindle and download and manage my books easily now. Look Ma, no wires!!

Originally I had tried to set up calibre-web from some youtube instructions. Some simple things were missing and that may be why it didn't work.

Thanks for your suggestions.

**Comment by haloboy777** [comment]
<img width="1213" height="872" alt="Image" src="https://github.com/user-attachments/assets/c17e92e5-cae0-4884-a924-e814bafd8627" />

For me I was unable to understand that I needed to enable the config for upload. The default upload disabling is fine, but would've been nice to have it spelled out.

No action needed. Just documenting here for future reference.
