### ISSUE TITLE
reverse proxy failed when login

### ISSUE THREAD

**Issue by jiangjiangflies** [janeczku/calibre-web#327]
Hi,
I use a reverse proxy (with a domain name) to replace serverip:8083. However, when I click guest to login, the URL in the browser is reverted to serverip:8083.  Below is my reverse proxy configuration, which is pretty simple. Is there anything wrong?
```
  1 server
  2 {
  3         listen          80;
  4         server_name     www.xxxxxx.com;
  5         location / {
  6         proxy_pass          http://188.xxx.xxx.xx:8083;
  7         proxy_redirect      off;
  8         proxy_set_header    X-Real-IP       $remote_addr;
  9         proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
 10         }
 11 }
```

**Comment by jkrehm** [comment]
Have you tried following the [example from the README](https://github.com/janeczku/calibre-web/#reverse-proxy) more closely?

**Comment by jiangjiangflies** [comment]
In the example, there is upstream field, which I don't know too much. But I have tried, and it was the same result.

**Comment by jkrehm** [comment]
Have you tried adding `proxy_bind $server_addr;` and `proxy_set_header Host $http_host;`? Those seem like likely culprits.

**Comment by jiangjiangflies** [comment]
Ahha, it works! Thank you so much!. Now this can be closed.

**Comment by MijacOnAir** [comment]
Hi everyone,
I am new to Calibre-web and all code related stuff so please bear with me chaps!

I have started doing my own research on how to set everything up but the challenge here is I am not code oriented so I am struggling to understand most of the instructions here and it is taking me forever to progress any single step. I am running Windows if this helps.

Having in mind the vast majority of you are far ahead from my baby steps so counting on your proven expertise, that would be great if you could guide me through a quick start, some tutorials, useful links somebody with zero idea of coding can understand or maybe even pointing me at the right community or link to find out how to do it.

My questions to get there are:

- How to set up "Remote login", which I have enabled from the admin panel but not sure how to access with another user in another device inside my home. Not sure if I need to extra tweak something to achieve that. Kind of lost at this point.

- Understand the differences between localhost and a hosted Calibre-web site. I have seen around a couple of libraries under custom domains so I would like to know pro's and con's of both methodologies (security issues included) and how to operate with them. Ideally, as I said before, I value the capacity of sharing my Calibre library with family and friends. (I have seen a post before with some piece of code to set a reverse proxy but I really don't know where to write it or what it is really for 😅)

If any of you could throw some light on this I would be everlasting thankful 😀

Many thanks in advance for all your input, feedback, comments and guidance.
Hope you all have a great day!
