### ISSUE TITLE
command line password management

### ISSUE THREAD

**Issue by jiangjiangflies** [janeczku/calibre-web#328]
Hi, is there a way to use command line to change user's password?

**Comment by jkrehm** [comment]
Unless you're looking to write a Python script of your own, I'm thinking probably no. The passwords are hashed using Werkzeug's [generate_password_hash](http://werkzeug.pocoo.org/docs/0.12/utils/#module-werkzeug.security) function. This is then stored in the SQLite database.

If all you need to do is reset a user's password, any administrator can do that via the GUI. If you need to reset a large number of users, then you'll probably be writing some Python to do it.

**Comment by jiangjiangflies** [comment]
What I want to do is to write a script to reset a user's password automatically every 6 hours and find a way to show the new password on a website page. Because I'm sharing my books with others, I don't want a fixed password for security reasons.

**Comment by jiangjiangflies** [comment]
Nerver mind, I have written a python script to do this. Thank you, buddy!
