### ISSUE TITLE
Read books with guest account not working

### ISSUE THREAD

**Issue by flashliao** [janeczku/calibre-web#332]
when I update the calibre-web application,the website  guest account can not the read books.
it's show 

Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

I just use admin accounts save one bookmarks.

**Comment by jkrehm** [comment]
Could you provide the logs that are generated when this error occurs? I haven't been able to recreate the issue in my local environment.

**Comment by flashliao** [comment]
logs show :AttributeError: 'Anonymous' object has no attribute 'id'

**Comment by flashliao** [comment]
@jkrehm

**Comment by flashliao** [comment]
@jkrehm [calibre-web-master.tar.gz](https://github.com/janeczku/calibre-web/files/1312697/calibre-web-master.tar.gz)

**Comment by OzzieIsaacs** [comment]
Please restart the server script and clear your browser cache.

**Comment by flashliao** [comment]
OzzieIsaacs it's not working.
![image](https://user-images.githubusercontent.com/28710685/30576810-f1d3ce12-9d3c-11e7-8484-e2ebf00cef0d.png)
![image](https://user-images.githubusercontent.com/28710685/30576822-07baad0e-9d3d-11e7-9f6f-8f0589a2c8c2.png)
![image](https://user-images.githubusercontent.com/28710685/30576854-41674468-9d3d-11e7-995e-4d29121f2514.png)


![image](https://user-images.githubusercontent.com/28710685/30576836-1e580778-9d3d-11e7-956e-e5e21451b639.png)

**Comment by flashliao** [comment]
@OzzieIsaacs @jkrehm 
If this problem only happens to me，tell me. I recreate the calibre-web website application.

**Comment by jkrehm** [comment]
I believe I know what the issue is but I have not had time to work on a fix. I believe the issue is that the Anonymous user class doesn't have an ID field. It extends UserBase and not User, so even though there's an actual user behind the anonymous user, it doesn't have ID.
