### ISSUE TITLE
Anonymous browsing not working?

### ISSUE THREAD

**Issue by dima-ser** [janeczku/calibre-web#336]
So I enabled anonymous browsing in configuration and it created a "guest" user, however when I log out I still can't browse books. It shows the navigation menu but still prompts me to log in. Am I missing something?

**Comment by OzzieIsaacs** [comment]
Please restart the server script and clear your browser cache (had this issue before, too)

**Comment by dima-ser** [comment]
Thanks, it worked! Awesome piece of software. I have another question/issue but I'll open it separately.
