### ISSUE TITLE
Library corrupted after managing with calibre-web

### ISSUE THREAD

**Issue by dima-ser** [janeczku/calibre-web#337]
So if I use calibre-web to add/edit books and then try to open the same library through calibre desktop application (Windows), I get the "corrupted database" error:

calibre, version 3.6.0
Corrupted database: The library database at E:\Books\CalibreLibrary appears to be corrupted. Do you want calibre to try and rebuild it automatically? The rebuild may not be completely successful. If you say No, a new empty calibre library will be created.

Traceback (most recent call last):
  File "site-packages\calibre\gui2\main.py", line 303, in initialize_db
  File "site-packages\calibre\db\legacy.py", line 81, in __init__
  File "site-packages\calibre\db\legacy.py", line 48, in create_backend
  File "site-packages\calibre\db\backend.py", line 384, in __init__
  File "site-packages\calibre\db\schema_upgrades.py", line 19, in __init__
  File "site-packages\calibre\db\backend.py", line 843, in execute
  File "c:\t\t\apsw-9hooel\apsw-3.13.0-r1\src\cursor.c", line 236, in resetcursor
ReadOnlyError: ReadOnlyError: attempt to write a readonly database

It forces me to rebuild it after which it works fine, but only until I edit the library though calibre-web, then it's corrupt again. Does this mean I can't manage my library through both your web application and calibre desktop program?

**Comment by teflontoni** [comment]
> ReadOnlyError: ReadOnlyError: attempt to write a readonly database

I think calibre-web and calibre can't work together at the same time on one database.

Try stopping calibre, then do your editing/uploading in calibre-web and try to start calibre again,
if my guess is right the db shouldn't be corrupted in that scenario, I might be wrong though.

**Comment by Kyosfonica** [comment]
Calibre's database is sqlite (a single file in the system) so only one program at a time can access it with write permissions.

**Comment by dima-ser** [comment]
I tried stopping calibre-web, then opening Calibre and it would still show
the error.

**Comment by teflontoni** [comment]
You need "clean" database for it to test. Let calibre repair the db, close calibre. 
Do some editing in Calibre-Web, open calibre again. That way it should work.

Can't test here because I keep calibre and calibre-web apart and only sync the whole directory including the db on demand.

**Comment by dima-ser** [comment]
Ok, after more investigation it appears to be related to file permissions. I run calibre-web on Linux box under "caluser" and on Windows I'm logged in as my own account. In order to be able to upload files via calibre-web, I have to set "caluser" as owner of metadata.db to give it write access. However, when I do that, the Windows app can no longer write to it and reports it as corrupt database. If I rebuild it, it resets the owner to my Windows username, so then calibre-web stops working. Basically, I either have to run both under the same account, or switch permissions on metadata.db every time I want to switch applications.

**Comment by dima-ser** [comment]
I solved it by setting the owner to my own username and the group to "caluser" and gave write permission on the group. Now it works on both.
