### ISSUE TITLE
Error on Win 10 with Python 2.7.13

### ISSUE THREAD

**Issue by bossanova808** [janeczku/calibre-web#338]
python cps.py on my Win 10 64 gives me:

```
C:\Utilities\calibre-web>python cps.py
Traceback (most recent call last):
  File "cps.py", line 13, in <module>
    from cps import web
  File "C:\Utilities\calibre-web\cps\web.py", line 36, in <module>
    import ub
  File "C:\Utilities\calibre-web\cps\ub.py", line 225, in <module>
    class Bookmark(Base):
  File "C:\Utilities\calibre-web\cps\ub.py", line 231, in Bookmark
    format = Column(String(collation='NOCASE'))
TypeError: __init__() got an unexpected keyword argument 'collation'
```

A pull at the same time works fine in a linux vm using the same python in a py-env scenario.

Any clues as to where to look for a problem?  I can't find anything that pertinent via a quick Google at least...

Thanks for your help - looks to be a *much* nicer interface than the content server (especially the latest version!)

**Comment by OzzieIsaacs** [comment]
Which version of sqlalchemy is installed (can be seen in the about section)
The documentation of this module states you should use at least 0.8, nonetheless it makes sense to upgrade to a newer version if possible.

**Comment by bossanova808** [comment]
Excellent catch - 0.7.9 apparently.  A `pip install -U sqlalchemy` has got me to the config page - many thanks!

(Kinda surprised the stated requirements.txt didn't get that to upgrade...)
