### ISSUE TITLE
Display error for comma in the author's name

### ISSUE THREAD

**Issue by os131** [janeczku/calibre-web#339]
In my library, author's name are formatted : "Lastname, Firstname".
In calibre-web, the comma is replaced by a pipe character : "Lastname| Firstname".
Same problem with either Chrome or Edge.
![sans titre](https://user-images.githubusercontent.com/32127126/30637324-4817a31e-9df8-11e7-949d-6f052aacf101.png)

**Comment by OzzieIsaacs** [comment]
Calibre replaces for author names with commas the commas with a pipe character. I'll fix it.
