### ISSUE TITLE
No Books Displaying

### ISSUE THREAD

**Issue by mccorkled** [janeczku/calibre-web#341]
I can only assume this is a database issue, and I have no idea how to fine out where the logs are, but I am using the Docker container on a Synology device. I am also using LazyLibrarian.

I have LL setup to place books into /Books/calibre
My Calibre-web database is in /Books/calibre as well. LL made the metadata.db and I pointed Calibre to it. 

When I open Calibre there is nothing on the screen but the regular menu items however I know the database is working because LL wouldn't be displaying books if it wasn't

![1](https://user-images.githubusercontent.com/13697804/30670849-108db264-9e32-11e7-8d36-ac3fd76249ce.png)

**Comment by Kyosfonica** [comment]
The logs are displayed in the docker container. Open docker in Synology and then double click de calibre-web container. There will be a Registry tab and there you will find the logs.

**Comment by mccorkled** [comment]
https://pastebin.com/YMPMXhEE

**Comment by OzzieIsaacs** [comment]
I don't know what lazylibarian does. What you need is a working calibre database, calibre should show the books, these books are shown on calibre-web. The log seems to show that in the calibre database columns (books) are missing

**Comment by mccorkled** [comment]
I do not have Calibre installed. LazyLibrarian is like CouchPotato for books. It downloads the books, post processes them, and then places them in /books/calibre. I thought that calibre web would then look at the shared database and list the books.

**Comment by Kyosfonica** [comment]
so it seems your metadata.db is empty. Calibre web doesn't autoload books for you. You should upload them via web or via Calibre desktop.

**Comment by mccorkled** [comment]
Could I suggest a feature request then for Calibre web to auto scan a directory every x hours to load new books?

**Comment by jkrehm** [comment]
I recommend checking out https://manual.calibre-ebook.com/generated/en/calibredb.html. It might have something that does what you want.

**Comment by mccorkled** [comment]
This all needs to run off of the server and not a local PC.

**Comment by jkrehm** [comment]
I don't know your particular set up, but Calibre should install into most Linux environments. From there it's a matter of figuring out how that CLI tool works and creating a cron job to run as often as you want it to.

**Comment by mccorkled** [comment]
Thanks. I will play around with it, but as I am extremely new to linux as well as Docker containers, I do not know how well that with fair. I will go ahead and open up a feature request in the meantime and see what happens. 

Thank you all for your help.

**Comment by OzzieIsaacs** [comment]
You could try this: create a bash file with the following content, and execute it frequently as from job.


#!/bin/bash

if [ "$(ls -A /folder/to/add/from )" ]; then
     calibredb add -r "/folder/to/add/from" --library-path="/path/to/metadata"
     rm /folder/to/add/from/*
fi

It checks if the /folder/to/add/from is no longer empty and than calls the calibreadd command to add all files in the folder to the database and afterwards deletes all files in the folder

**Comment by bodybybuddha** [comment]
Thanks for the script @OzzieIsaacs!  I needed that for a different issue!

@mccorkled - I did a little digging regarding LazyLibrarian and according to this [link](https://github.com/DobyTang/LazyLibrarian), the tool has the ability to autoload into calibre.  

> AutoAdd feature for book management tools like Calibre which must have books in flattened directory structure, or use calibre to import your books into an existing calibre library

Maybe a new feature?

**Comment by mccorkled** [comment]
Yeah I noticed that. The problem is that I cannot have Calibre running on a local machine. I needs to be running on my server which is why I went with Calibre-web
