### ISSUE TITLE
[Feature Request] Auto Add/Scan Books

### ISSUE THREAD

**Issue by mccorkled** [janeczku/calibre-web#344]
Could you please add a feature to scan a particular directory every x hours to auto add or remove books?

Thank you. :)

**Comment by OzzieIsaacs** [comment]
I entered a suggestion to solve this via bash script, this feature is beyond the scope of the project

**Comment by mccorkled** [comment]
Running a program frequently isn't a solution to something that should be automated.

**Comment by OzzieIsaacs** [comment]
What is LL? And how should Calibre-web detect that the download isn‘t finished?

**Comment by kianrafiee** [comment]
Actually I want to backtrack and point out that I was wrong. LL(LazyLibrarian) can move finished files to a different folder so no problems their. But the shell script is dependent on calibredb which calibre-web does not include. I, along with others, therefore cannot use it on a NAS such as Synology using docker.

But I feel this wouldn’t be hard to implement in caliber-web. You already have a bulk upload function. So having a call to that function on a “watch” folder would be pretty easy to implement imo. I wish I knew enough python to do it right now. Sorry I can’t be of much more help atm.

**Comment by kianrafiee** [comment]
Thanks I will hopefully try tomorrow and keep you all up to date. One thing: how would calibre-web play nicely with the calibre db when it has its own book db to worry about?

**Comment by kianrafiee** [comment]
I think this is user error. Will update you all tomorrow!

**Comment by kianrafiee** [comment]
Here is what I posted in LL repo:

> Yep! It was user error. I didn't realize I changed the book folder for LL. It wasn't the one with the metadata file used by calibre-web(and calibre for that matter). So far its slowly importing books and I am pleasantly surprised at the exceptional sorting/organizing of files.
> 
> Only thing to check last is whether calibre-web will see some books I never uploaded to it but that are in the books folder and being processed by LL shortly.
>  
> And on that note, I believe their should be some documentation added to LL and Calibre-web so other users are aware of the inherent cross-syncing of the two apps. I spent way too much time fixing a problem that never was. I blame myself but google searches made it seem like this was a problem. No bad on you or anyone else. Just my suggestion.

**Comment by kianrafiee** [comment]
So no need to configure anything. Just point both apps to same book dir.

**Comment by StudioEtrange** [comment]
BY the way a linuxserver mod, to use with docker-calibre-web which will create an empty calibre db for your LazyLibrarian + Calibre-Web install

https://github.com/StudioEtrange/docker-calibre-mod


`
CALIBRE_WEB_VERSION="24ae7350f5b749127b48e66758bc3f449296c65f"
export CALIBRE_WEB_DOCKER_VERSION="${CALIBRE_WEB_VERSION}"
export CALIBRE_RELEASE_DOCKERMOD_VERSION="4.6.0"

docker run --name calibre-web -d -v ${DATA}/data/calibre-web:/config -v /media/MEDIA/EBOOKS:/books  -p 8080:8083 -e PUID="$(id -u)" -e PGID="$(id -g)" -e TZ="Europe/Paris" -e DOCKER_MODS="studioetrange/calibre-mod:${CALIBRE_RELEASE_DOCKERMOD_VERSION}" linuxserver/calibre-web:${CALIBRE_WEB_DOCKER_VERSION}`

**Comment by jmarmstrong1207** [comment]
> I entered a suggestion in the first issue to solve this via bash script, this feature is beyond the scope of the project

I don't fully understand why this is beyond the scope of the project. Books can be converted to multiple formats, and imported individually with the uploads button. Why isn't an option to have auto importing in scope? Not sure if the project was different 7 years ago, but this feature would be loved by a ton of people. 

There are many workarounds to this online solely because this is the best program for a selfhosted calibre server, but the server itself can't natively import its own books.

**Comment by lifebarier** [comment]
I am trying to move couple hundred gigabytes of books into calibre-web and I was hoping I could just symlink folder with my books and click button to import all or set it as watch folder... But it seems I will have to do it all by hand.
