### ISSUE TITLE
Exception occurs when install 

### ISSUE THREAD

**Issue by XxZhang2017** [janeczku/calibre-web#345]
On windows 10
 Running setup.py install for MarkupSafe ... error
Exception:
Traceback (most recent call last):
  File "d:\python\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 2: invalid continuation byte

**Comment by OzzieIsaacs** [comment]
Please try the procedures described in:
https://github.com/pallets/markupsafe/issues/59
https://github.com/pallets/markupsafe/issues/67

**Comment by XxZhang2017** [comment]
Hi, I follow the solution on that change the code in line 75 in
__init__.py file: return s.decode('cp936'). I change parameter to 'cp936'.
It works. However, when I run cps.py, I encounter another decoding problem.

2017-09-23 21:44 GMT-07:00 Ozzie Isaacs <notifications@github.com>:

**Comment by XxZhang2017** [comment]
File "D:\east bay\software_engi\git_pro\cps\cache_buster.py", line 28, in
init_cache_busting
    file_hash = hashlib.md5(f.read()).hexdigest()[:7]
UnicodeDecodeError: 'gbk' codec can't decode byte 0xff in position 62:
illegal multibyte sequence
Does that mean you use gbk instead of unicode somewhere?

2017-09-24 10:19 GMT-07:00 张雪 <mynewvegaan@gmail.com>:
