### ISSUE TITLE
[Enhancement] Support mobi/azw3 view in browser (using epub conversion)

### ISSUE THREAD

**Issue by ghost** [janeczku/calibre-web#348]
Can do on-the-fly epub conversion to a temp file location then use epub viewer

I think would be widely appreciated, given mobi is becoming the dominant format for better or worse

**Comment by C0rn3j** [comment]
As a note, the native Calibre web server allows reading MOBI, AZW and AZW3 just fine.

I guess it does any format Calibre does.

**Comment by OzzieIsaacs** [comment]
Meanwhile amazon supports epubs for sending to the device. I have to focus on what is doable with my time, so I decided to not implement it.
