### ISSUE TITLE
Enhancement: Anon permissions

### ISSUE THREAD

**Issue by hscissors** [janeczku/calibre-web#35]
Is there any way that you could extend the permission model under the admin section to anon users? As far as I can tell, a lot of epub readers don't have interfaces for auth through the OPDS feed. Unless I'm missing something.

**Comment by janeczku** [comment]
I think most of them do support HTTP basic auth with OPDS. I know that Kobo doesn't. Are there more?

**Comment by hscissors** [comment]
I don't think Moon Reader (Android) does auth.

**Comment by janeczku** [comment]
So basically you want an option to give browse and download rights to anon user?

**Comment by hscissors** [comment]
Exactly.
