### ISSUE TITLE
restrict download quantity

### ISSUE THREAD

**Issue by jiangjiangflies** [janeczku/calibre-web#356]
Would you consider adding a function to restrict the quantity of downloads per user? I think it quite necessary to do this when you have hundreds of users.  If you can restrict  the number of downloadable files, say 1 book per day per user, it will protect your e-books as well as your server.

**Comment by OzzieIsaacs** [comment]
The project is not created as public books store. Its made for sharing books for a small group (like your family). In this szenario in my opinion it makes no sense to limit the no. of downloads per day.
