### ISSUE TITLE
Enhancement Request - Newsletter capability

### ISSUE THREAD

**Issue by bodybybuddha** [janeczku/calibre-web#357]
Anyone want to take a stab at this?

This was mentioned back in [2015](https://github.com/janeczku/calibre-web/issues/1), however, I don't think anything came of the request.

In any event, I've tried my hand at implementing this as its own script, [cps-WhatsNew](https://github.com/bodybybuddha/cps-WhatsNew) - mainly b/c I wanted to pick up more python coding.  In a nutshell, it parses the opds feed for new books, takes the contents of the feed and shoves it into a html formatted email.  

However, it would be great to see a feature like this baked into the system.

Thanks!
JT

**Comment by jkrehm** [comment]
Personally, I see that as beyond the scope of the project. While it could be useful, to me it doesn't seem like something that needs to be baked in. A separate (sister) project can do what you're doing – consume the feed – and do whatever formatting is necessary. But actually baking in a newsletter system to what's basically a library system seems like a reach to me.

**Comment by OzzieIsaacs** [comment]
I agree with @jkrehm. We should take care that not to much of the surrounding stuff like automated adding of books, newsletters and so on are included in the project and make it slow and hard to manage and maintain. 
Therfore I will close this issue.

**Comment by bodybybuddha** [comment]
In case anyone is interested, I did end up rolling this into a docker:  https://hub.docker.com/r/bodybybuddha/cpswhatsnew/
