### ISSUE TITLE
Enhancement: Can you add the priveledge management feature?

### ISSUE THREAD

**Issue by hysci** [janeczku/calibre-web#358]
In the current implementation, every user can access any book in the repository. Can you add a new feature to let the specific user access particular books? Thanks.

**Comment by OzzieIsaacs** [comment]
There is already a feature like this implemented. "- Ability to hide content based on categories for certain users"
You have to add the books which should be hidden for a group of users to a category. Than enter this categor(y/ies) in the config section in the "mature content" field of the admin area.
Finally you have to tick the show mature content in the users section for those user who should have access to all users.

I hope this is sufficient, its not 100% the feature you requested, but should be sufficient for most use cases.

**Comment by OzzieIsaacs** [comment]
no response for nearly one month
