### ISSUE TITLE
[Error] Failed to delete books

### ISSUE THREAD

**Issue by hysci** [janeczku/calibre-web#359]
Steps: 
1. Login admin account
2. Open Calibre, add another book and then quit (metadata.db will be changed)
3. Upload a pdf book in the calibre-web
4. Submit
5. Edit meta, then delete book
6. There will be errors
7. Flush, everything will be bad

[Error info shown in the web]
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

[Error info shown in the log]
calibre-web_1    | ::ffff:192.168.1.98 - - [2017-10-07 09:53:12] "POST /upload HTTP/1.1" 500 412 0.791692
calibre-web_1    | ::ffff:192.168.1.98 - - [2017-10-07 09:53:15] "GET /cover/E.%20M.%20Forster/Howards%20End%20%288336%29 HTTP/1.1" 200 43822 0.004812
calibre-web_1    | ::ffff:192.168.1.98 - - [2017-10-07 09:53:15] "GET /cover/Unknown/Chu%20Ying%20Wen%20Ku%20-Xue%20Sheng%20Cheng%20C%20%2817496%29 HTTP/1.1" 200 67740 0.004479
calibre-web_1    | ::ffff:192.168.1.98 - - [2017-10-07 09:53:30] "GET /logout HTTP/1.1" 302 767 0.010010
calibre-web_1    | ::ffff:192.168.1.98 - - [2017-10-07 09:53:30] "GET /login HTTP/1.1" 200 4645 0.017185
calibre-web_1    | ::ffff:192.168.1.98 - - [2017-10-07 09:53:37] "POST /login HTTP/1.1" 302 995 0.106519
calibre-web_1    | [2017-10-07 09:53:37,824] ERROR in app: Exception on / [GET]
calibre-web_1    | Traceback (most recent call last):
calibre-web_1    |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
calibre-web_1    |     response = self.full_dispatch_request()
calibre-web_1    |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
calibre-web_1    |     rv = self.handle_user_exception(e)
calibre-web_1    |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
calibre-web_1    |     reraise(exc_type, exc_value, tb)
calibre-web_1    |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
calibre-web_1    |     rv = self.dispatch_request()
calibre-web_1    |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
calibre-web_1    |     return self.view_functions[rule.endpoint](**req.view_args)
calibre-web_1    |   File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
calibre-web_1    |     return func(*args, **kwargs)
calibre-web_1    |   File "/calibre-web/app/cps/web.py", line 1037, in index
calibre-web_1    |     entries, random, pagination = fill_indexpage(page, db.Books, True, db.Books.timestamp.desc())
calibre-web_1    |   File "/calibre-web/app/cps/web.py", line 538, in fill_indexpage
calibre-web_1    |     .filter(db_filter).filter(common_filters()).all()))
calibre-web_1    |   File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2703, in all
calibre-web_1    |     return list(self)
calibre-web_1    |   File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
calibre-web_1    |     return self._execute_and_instances(context)
calibre-web_1    |   File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2876, in _execute_and_instances
calibre-web_1    |     close_with_result=True)
calibre-web_1    |   File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2885, in _get_bind_args
calibre-web_1    |     **kw
calibre-web_1    |   File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2867, in _connection_from_session
calibre-web_1    |     conn = self.session.connection(**kw)
calibre-web_1    |   File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 998, in connection
calibre-web_1    |     execution_options=execution_options)
calibre-web_1    |   File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1003, in _connection_for_bind
calibre-web_1    |     engine, execution_options)
calibre-web_1    |   File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 382, in _connection_for_bind
calibre-web_1    |     self._assert_active()
calibre-web_1    |   File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 276, in _assert_active
calibre-web_1    |     % self._rollback_exception
calibre-web_1    | InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.OperationalError) attempt to write a readonly database [SQL: u'INSERT INTO books (title, sort, author_sort, timestamp, pubdate, series_index, last_modified, path, has_cover, uuid) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: (u'C++\u6a21\u677f\u5168\u89c8', '', u'Unknown', datetime.datetime(2017, 10, 7, 9, 53, 12, 552923), datetime.datetime(101, 1, 1, 0, 0), '', datetime.datetime(2017, 10, 7, 9, 53, 12, 552928), u'Unknown/C_Mo Ban Quan Lan', 0, None)]
calibre-web_1    | ::ffff:192.168.1.98 - - [2017-10-07 09:53:37] "GET / HTTP/1.1" 500 412 0.005669
calibre-web_1    | [2017-10-07 09:53:40,474] ERROR in app: Exception on / [GET]
calibre-web_1    | Traceback (most recent call last):
calibre-web_1    |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
calibre-web_1    |     response = self.full_dispatch_request()
calibre-web_1    |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
calibre-web_1    |     rv = self.handle_user_exception(e)
calibre-web_1    |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
calibre-web_1    |     reraise(exc_type, exc_value, tb)
calibre-web_1    |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
calibre-web_1    |     rv = self.dispatch_request()
calibre-web_1    |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
calibre-web_1    |     return self.view_functions[rule.endpoint](**req.view_args)
calibre-web_1    |   File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
calibre-web_1    |     return func(*args, **kwargs)
calibre-web_1    |   File "/calibre-web/app/cps/web.py", line 1037, in index
calibre-web_1    |     entries, random, pagination = fill_indexpage(page, db.Books, True, db.Books.timestamp.desc())
calibre-web_1    |   File "/calibre-web/app/cps/web.py", line 538, in fill_indexpage
calibre-web_1    |     .filter(db_filter).filter(common_filters()).all()))
calibre-web_1    |   File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2703, in all
calibre-web_1    |     return list(self)
calibre-web_1    |   File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
calibre-web_1    |     return self._execute_and_instances(context)
calibre-web_1    |   File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2876, in _execute_and_instances
calibre-web_1    |     close_with_result=True)
calibre-web_1    |   File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2885, in _get_bind_args
calibre-web_1    |     **kw
calibre-web_1    |   File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2867, in _connection_from_session
calibre-web_1    |     conn = self.session.connection(**kw)
calibre-web_1    |   File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 998, in connection
calibre-web_1    |     execution_options=execution_options)
calibre-web_1    |   File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1003, in _connection_for_bind
calibre-web_1    |     engine, execution_options)
calibre-web_1    |   File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 382, in _connection_for_bind
calibre-web_1    |     self._assert_active()
calibre-web_1    |   File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 276, in _assert_active
calibre-web_1    |     % self._rollback_exception
calibre-web_1    | InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.OperationalError) attempt to write a readonly database [SQL: u'INSERT INTO books (title, sort, author_sort, timestamp, pubdate, series_index, last_modified, path, has_cover, uuid) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: (u'C++\u6a21\u677f\u5168\u89c8', '', u'Unknown', datetime.datetime(2017, 10, 7, 9, 53, 12, 552923), datetime.datetime(101, 1, 1, 0, 0), '', datetime.datetime(2017, 10, 7, 9, 53, 12, 552928), u'Unknown/C_Mo Ban Quan Lan', 0, None)]
calibre-web_1    | ::ffff:192.168.1.98 - - [2017-10-07 09:53:40] "GET / HTTP/1.1" 500 412 0.006103

**Comment by OzzieIsaacs** [comment]
I don't know what happed. The error maybe related to the filename, or the metainformations of the file. I did a change on this. Please restart the calibre-web server after updating to the newest commit. 
If the error still occours afterwards, could you please try a "english" pdf book without chinese characters in it and within the metadata.

**Comment by OzzieIsaacs** [comment]
Error is not reproducable
