### ISSUE TITLE
Reverse proxy subdirectory: Logout-Issue

### ISSUE THREAD

**Issue by bombcheck** [janeczku/calibre-web#36]
Hi there,

the Reverse proxy subdirectory-Support was exactly what I need and it works quiete well. But when I click on Logout, the page redirects to its base-url (without the prefix).

EDIT: Seems that is also true for login/register?

Regards

**Comment by janeczku** [comment]
Thanks! I'll look into that.

**Comment by janeczku** [comment]
@bombcheck Can you give it another try with current HEAD?

**Comment by bombcheck** [comment]
Thx for looking into it. Apparently, the problem still exists.

**Comment by janeczku** [comment]
@bombcheck Added another commit to fix the logout/login redirect. Tested successfully with the following configuration:

```
  # Serve static files 
  location ^~ /calibre/static/  {
      alias /opt/app/cps/static/;
  }

  # Proxy to gunicorn
  location /calibre {
    proxy_pass         http://127.0.0.1:8083;
    proxy_redirect     off;
    proxy_set_header   Host $http_host;
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Host $server_name;
    proxy_set_header   X-Scheme $scheme;
    proxy_set_header   X-Script-Name /calibre;
  }
```

**Comment by bombcheck** [comment]
Thx, that one did it. Great piece of software, by the way. Keep up the great work!
