### ISSUE TITLE
Disable Recently Added for unauthenticated users

### ISSUE THREAD

**Issue by grOGH** [janeczku/calibre-web#365]
As of the current version unauthenticated users can see a list of recently added books, exposing the entire library if they keep scrolling.

Previously, unauthenticated users could only log-in when anonymous browsing was disabled.

Can there be a setting to completely disable this feature and revert to only showing the login page for those who want to show the library contents only to authenticated users?

**Comment by teflontoni** [comment]
I am in favor of such a setting, too. My library is none other's concern.
