### ISSUE TITLE
[Enhancement] Implement calibre's native search query language

### ISSUE THREAD

**Issue by frogger72** [janeczku/calibre-web#369]
allow search syntax, like the following:

title:"harry potter" #customfield1:favorite

**Comment by OzzieIsaacs** [comment]
There is already a similar feature included, hidden behind the button advanced serach. Does this fullfill your needs. Implementing the search as you suggested is not very user friendly (you have to know the right syntax) and generates much programming effort (you have to parse the search string and combine the results to a huge database query.

**Comment by OzzieIsaacs** [comment]
yes that true, therefor its only similar. 
so what you are after is searching in custom columns. that could be easier to implement

**Comment by frogger72** [comment]
I guess it is 2 separate requests.  One is advanced search string parsing (allowing field specifiers, logic, and/or regex).  The other is custom columns support.  I personally am more interested in the parsing.

Here are some off the shelf libraries for parsing:
Seems more geared toward field specifiers: https://pypi.python.org/pypi/parse
More geared toward logic: https://github.com/hgomersall/python-boolean

**Comment by frogger72** [comment]
I changed the title of this after realizing Calibre has this built-in using their search query language, so no external implementation needed - just need to use their API

https://open-books.calibre-ebook.com/search

**Comment by OzzieIsaacs** [comment]
I don't see an external API for searching in the ebooks, its just describing how to use the commands for searching in the UI. Currently I'm not willing to reimplement the calibre searching commands, as it's too complicated, sorry.
