### ISSUE TITLE
 Reverse proxy subdirectory: Redirect-Issue again

### ISSUE THREAD

**Issue by bombcheck** [janeczku/calibre-web#37]
Hi there,

just tried the search function: The redirect is broken here, too.
It does work if I start searching from the advanced search.

**Comment by jgillman** [comment]
@bombcheck Are you having trouble logging out as well? Looks like that was your original title.

I'm also using a reverse proxy and can't search or logout!

**Comment by bombcheck** [comment]
@jgillman No that works fine. Make sure to set the "X-Script-Name"-Header in your webserver config.
If the subdir is for example http://stuff.domain.de/books then you have to set (example for apache vhost for stuff.domain.de): RequestHeader set X-Script-Name /books

**Comment by jgillman** [comment]
This is what the block looks like in my nginx.conf:

```nginx
location /books {
  proxy_bind $server_addr;
  proxy_pass http://127.0.0.1:26657;
  proxy_set_header Host $http_host;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Scheme $scheme;
  proxy_set_header X-Script-Name /books;
}
```

**Comment by jschuck** [comment]
Same search issue here. 
Proxy sits in /calibre/

Normal search goes to /search and fails. If i change it in the browsers addressbar so that it starts with /calibre/search it shows the result.

Advanced Search goes to /calibre/search as expected.

**Comment by OzzieIsaacs** [comment]
@jschuck could you please confirm that you can search now?
Do you still have logout/login problems? -> redirects to Hostname instead of hostname/calibre?
(got this too with apache server, where as search worked before)

**Comment by jschuck** [comment]
That was fast. Yes i can now search and i don't have logout problems.

I now noticed another slightly inconvenient bug with a re-login after a search. I will open another issue for it, since it's not directly related to this one.

**Comment by bombcheck** [comment]
Works great now, thank you!!

**Comment by jgillman** [comment]
Fixed for me too, thanks @OzzieIsaacs!
