### ISSUE TITLE
Can't remove book from Public Shelf

### ISSUE THREAD

**Issue by darth2499** [janeczku/calibre-web#376]
Currently logged in as admin and I can't remove a book from the public shelf. However, if I untick "should the shelf be public?" I can remove books from them. So right now that is what I am doing.

**Comment by OzzieIsaacs** [comment]
In the user condifuration (admin section) you can define for each user individually:
"Allow Editing Public Shelfs"
Is this box ticked?

**Comment by darth2499** [comment]
Yes, "Allow Editing Public Shelfs" is ticked

**Comment by OzzieIsaacs** [comment]
Should work now again

**Comment by bonnebulle** [comment]
Edit Shelfs is Public for me but I cant remove on clic...
was good working on previous version (am on 0.6.18 Caliweb version)
