### ISSUE TITLE
Possibility to add other meta data providers

### ISSUE THREAD

**Issue by ghost** [janeczku/calibre-web#380]
This may be a feature request.

Google books and Douban do not work well for my Dutch books, I use Amazon locally. Is it possible to add a meta data provider?

**Comment by OzzieIsaacs** [comment]
So what you are requesting is adding amazon as metadata provider?

**Comment by Thijxx** [comment]
Yes, or some directions so I can help make this possible.

**Comment by paulhybryant** [comment]
It'd be great if that is possible.

**Comment by OzzieIsaacs** [comment]
Would be okay for me

**Comment by ngodfriedt** [comment]
Amazon support would be most welcome!

**Comment by OzzieIsaacs** [comment]
Meanwhile Calibre-Web supports adding customized metadata providers: https://github.com/janeczku/calibre-web/wiki/Developer's-corner-#add-metadata-provider
I will not add anymore metadata providers, but anybody is free to add it's own provider.

**Comment by OzzieIsaacs** [comment]
https://github.com/janeczku/calibre-web/wiki/Developer's-corner#add-metadata-provider

**Comment by auspex** [comment]
I did eventually find it, but then couldn't manage to find where I'd commented on this issue to correct it myself!
