### ISSUE TITLE
Can Calibre-web execute malicious code in an ebook?

### ISSUE THREAD

**Issue by andyforceno** [janeczku/calibre-web#384]
I had some pirated ebooks that were suspicious due to their size, among other things. I deleted them, but I have read them in the past, and I have some concern they could harbor malware. I have only read them on my Android phone and Calibre-web (via Chrome browser running on Linux). I confirmed with the Android app developer that malicious Javascript embedded in ebooks will be ignored by the app. I figured Calibre-web would just ignore it too, but I wanted to confirm this. I'm not actually sure how it works anyway, that is, if Calibre-web plays any role, or if the browser itself would execute the code.

**Comment by OzzieIsaacs** [comment]
If you just organize your epubs with calibre-web, the content of the epub is not touched, and nothing gets to excecution. 
If you use the included epub-reader, it is a different story:
Calibre-web unpacks the epub (which are normal zip files) to a folder on the server which is accessable by the browser. Then calibre-web sends the reader page to the browser. The browser starts the epub-reader javascript file, which itself starts to build up the webpage you see. During that, the filecontents of the epub file is loaded into the browser. The content is just normal html pages, which can include stylesheet files and javascript files. So if there is malicious code included the epub, or links to javascript code the broser (if not prevented anyhow) will start to interpret it.

If you are not sure, you could rename the epub to zip open it and search for js-code and delete it, and afterwards rename t to epub again. Also tools like the [sigil epub editor](https://github.com/Sigil-Ebook/Sigil) could help to dig deeper into the suspicious books.
