### ISSUE TITLE
Help Accessing Library with 3rd party ereader apps

### ISSUE THREAD

**Issue by snesbittsea** [janeczku/calibre-web#387]
I could use some help in understanding how best to setup calibre-web so that I can search through my 2,000+ library of books and then transfer one or more of the search results to the book reader of choice (Bookari or MoonReader)

My initial thought was that I would use OPDS. Both MoonReader and Bookari support adding stores using OPDS. The problem I'm running into here is that both seem to fetch only a subset of books (I think about 60) and, I don't know if there is a way to force them to generate the entire list of books so I can then do a search.

So am I missing something regarding OPDS (such as specifying that the entire OPDS be generated before being transferred)

Or is another - not too onerous, process (GoogleDrive/DropBox) - to accomplish the same thing?

Much thanks in advance.

-steve

**Comment by ytilis** [comment]
You should be able to search the OPDS catalog. You don't need to download a list of every single book to do so. The OPDS browser should allow you to enter a search term and return relevant results from the server. I just tried it with Aldiko on Android and it worked fine for me. Haven't used MoonReader in years so not sure where the search button would be ion their UI.

**Comment by OzzieIsaacs** [comment]
The number of initally shown books correspond to the settings "books per page" in the web-ui. Normally you should be able to trigger a load of the next xx books by scrolling down or something else (just checked with Marvin3 on iOS that it is still working)

**Comment by snesbittsea** [comment]
Thanks all! I confirmed that it works as expected on Moon+. It doesn't appear to work correctly on Bookari.
