### ISSUE TITLE
[Enhancement] Request new books

### ISSUE THREAD

**Issue by ytilis** [janeczku/calibre-web#389]
Was wondering if there'd be interest in giving users the ability to request books and add them to a queue. 

This can leverage the existing get metadata functionality, except instead of populating the metadata for an existing book, it makes a virtual book that gets added to a queue (not sure if it should be publicly visible or only in admin). The request can be rejected or marked as done once the book is added.

**Comment by Code-Slave** [comment]
Yes if it is exportable to say Lazylibrarian..

**Comment by sudomonkey** [comment]
I would love to see something like this. At the moment I've been using a google form for people to make request from.

**Comment by Code-Slave** [comment]
lazylibrarian now has an API to talk to.

**Comment by OzzieIsaacs** [comment]
I thought meanwhile about what this project is for and what to implement and what not. I decided to not develop "social functions" like recommending/requesting books and so on. So, I'm sorry, I'm not implementing it.
