### ISSUE TITLE
[Enhancement] Flag broken files

### ISSUE THREAD

**Issue by ytilis** [janeczku/calibre-web#390]
Wondering if there's interest in marking books that may be corrupted, or which need fixing (if they have incorrect metadata, incorrect cover image, etc). Users would hit a button that prompts them to describe the problem, and books marked as such would appear in the admin for review, to be marked as fixed or rejected.

**Comment by OzzieIsaacs** [comment]
As calibre-web is made for sharing books among your family and friends, I think this should work in this usecases without a automated workflow. As it also seems that nobody else is requesting a feature like this, so I will not implement it.
