### ISSUE TITLE
Default config

### ISSUE THREAD

**Issue by plotti** [janeczku/calibre-web#396]
For new users I would really like to set the default config like this (see attachment). There is no way i can configure this, they all have to set it themselves, which takes away from the first aha moment. 
<img width="810" alt="bildschirmfoto 2017-11-27 um 12 37 44" src="https://user-images.githubusercontent.com/610885/33264949-f07ebd38-d36f-11e7-9752-527e357124ce.png">

**Comment by OzzieIsaacs** [comment]
Please update to the newest commit. By default now everything is visible and you an adjust the default in the config section

**Comment by plotti** [comment]
nice! thx a lot!

------
Thomas Ebermann
+49 179 9707188

**Comment by OzzieIsaacs** [comment]
Be careful with posting personal informations. I deleted the telephone no. In your post
