### ISSUE TITLE
public shelf

### ISSUE THREAD

**Issue by jiangjiangflies** [janeczku/calibre-web#399]
How can I modify public shelf? I want to modify the public shelf name and put some books in it so that everybody can see them. How should I do?

**Comment by OzzieIsaacs** [comment]
Changing Shelf names is only allowed for registered users with the right "edit public shelfs". 
You click on the shelf you want to edit. Click the button rename shelf and rename it.

**Comment by jiangjiangflies** [comment]
Thanks!
