### ISSUE TITLE
user DLS info 

### ISSUE THREAD

**Issue by jiangjiangflies** [janeczku/calibre-web#400]
Where is the DLS(recent downloads) info stored for users? I want to reset this value to 0 sometimes. Is there a database file that I can modify it directly？In addition, what about other info, like password of the admin? Sometimes I even lost my admin password so that I can't log in. It would be great if I can change my password through the db file.

**Comment by OzzieIsaacs** [comment]
Both infos are stored in the app.db, normally stored in Calibre-web‘s main folder. The structure of the db can be seen in the ub.py file in the User Class.

**Comment by jiangjiangflies** [comment]
I really hope that there will be a command line management tool.  Thanks!
