### ISSUE TITLE
Calibre-web & Calibre client desktop

### ISSUE THREAD

**Issue by hot22shot** [janeczku/calibre-web#402]
Hi,

I installed calibre-web on my Synology with a docker image and it works.
My calibre library is located on a shared directory on my NAS.
My question is can I use the full calibre client on my laptop to update my library without messing with calibre-web install ? 
Do I need to restart it or something ?

Regards

**Comment by OzzieIsaacs** [comment]
this should work, but as you may know calibre is not developed to have multiple access to the database, so be carefull with changing (writing) data from within calibre and calibre-web at the same time

**Comment by hot22shot** [comment]
OK, there should be no problem as I do not plan to change anything from calibre-web, it's just for online reading and access.

Thank you !
