### ISSUE TITLE
[Enhancement] Other Digital Media

### ISSUE THREAD

**Issue by ErroneousBosch** [janeczku/calibre-web#403]
Since Calibre has the ability to handle other digital media, could there be built in viewer support for other media types, like jpg/png (for things like posters/infographics) and Audiobooks/videos?

**Comment by ErroneousBosch** [comment]
I was thinking more of an ability to view/listen/watch within the webapp. A bit of a pie-in-the-sky idea, I know

**Comment by OzzieIsaacs** [comment]
Listening for audio books is now pissible, I will not implement a video viewer. I think a viewer for single picture files also not helpful, so I consider this issue as solved as far as I want to solve it.
