### ISSUE TITLE
[Enhancement] Ability to add multiple books to a shelf at one time

### ISSUE THREAD

**Issue by ajn142** [janeczku/calibre-web#404]
Howdy,

I've been playing with the calibre-web system for a few days now, and I love it. Way better than using the stock interface online, and the in browser reading is a game changer for me, since I don't have a dedicated e-Reader. However, I haven't yet found a way to add multiple books to a shelf at a time. Since I'm just starting out with setting up shelves, being able to add more than one book at a time would be really convenient. If this is already a feature that I've missed, feel free to close the issue, but otherwise I think this would be a pretty handy enhancement.

**Comment by MosabWadea** [comment]
any updates regarding this issue?

**Comment by OzzieIsaacs** [comment]
If you have at least one bookshelf you can now add all books of a search request (on the search result page) to a shelf at once.

**Comment by ramsnerm** [comment]
The button is only visible in case you select the standard theme - Using the dark theme will not present the button

**Comment by ajn142** [comment]
> The button is only visible in case you select the standard theme - Using the dark theme will not present the button

Hey, that sounds like it needs a separate issue raised. This one was just for adding the feature in the first place, and has been closed for almost a year and a half.

**Comment by cbartondock** [comment]
This should still be open

**Comment by srvoets** [comment]
> The button is only visible in case you select the standard theme - Using the dark theme will not present the button

this still happens
