### ISSUE TITLE
[Enhancement] Shelf Filter/Search/Sort

### ISSUE THREAD

**Issue by ErroneousBosch** [janeczku/calibre-web#405]
While I really wish shelves upstreamed into Calibre (or could be related to Virtual Libraries somehow), just as useful would be some way to sort within them, or filter/search them (perhaps by tags?). Large shelves become unwieldy, and and having many of them fills your left column up.

**Comment by paulhybryant** [comment]
+1 to sorting in shelf

**Comment by ErroneousBosch** [comment]
Subshelves would also make shelves WAY more useful. For instance being able to have 'Non-fiction->History' or something like that. Even just Category filtering within a shelf. 

Shelves are a neat Idea but in a large, multi-topic library, they are a bit useless for any practical organization. Then again, so are Categories the way they are presented now, but that's a different topic.

**Comment by ErroneousBosch** [comment]
After my last comment, I found [Issue 1193](https://github.com/janeczku/calibre-web/issues/1193), which would address some of these issues by making heirachical tags, allowing shelves to be relegated to each user.

**Comment by EolianPipes** [comment]
+1 for shelf sorting. It's really cool that you can manually choose the position (as if it were a real shelf), but it becomes a lot of work if you have a lot of items. For instance, I keep track of audiobooks with a checkbox and tried making a shelf for audiobooks. There were so many (100+) that it wasn't useful to look through as a separate view without being able to sort them by title, author, or dateAdded.

**Comment by OzzieIsaacs** [comment]
Shelfs are having now a paged view

**Comment by OzzieIsaacs** [comment]
Order of books in shelfs can now be changed by the same sorting options the other views. So I consider the original issue as solved. 
The heirachical shelfs or nested shelfs are requested in #370. Please let us track this there
