### ISSUE TITLE
How do i update?

### ISSUE THREAD

**Issue by sand3rk** [janeczku/calibre-web#407]
What files do I need to replace to update? If I replace all files, the program won't start.

**Comment by OzzieIsaacs** [comment]
I‘m using the update function for a while without problems. Just go as admin to the admin page, scroll down, press the search for update button, wait while update is performed, be happy.
If you want to do it manually, you should stop the program, afterwards just copy the new files over the old ones. If you delete everything before, you loose the app.db file, which is holding all the settings.

**Comment by sand3rk** [comment]
I don't see an update button on the admin page. 

When I replace all files the webpage does not load anymore.

**Comment by OzzieIsaacs** [comment]
It's there:
![grafik](https://user-images.githubusercontent.com/6438895/33808115-3a9e58bc-dde1-11e7-8452-a68b3d47ba12.png)
I suppose you are not using a docker image?
I suppose you are not using a reverse proxy?
Are you using python 2.7 or 3.x?

Both messages in the logbook are indicating normal startup. 

What does does not load anymore mean? Do you get ?error 500, or do you get a timeout, or ?
If you start calibre-web from the console, are there any outputs there?

**Comment by sand3rk** [comment]
![calibrewebhellp](https://user-images.githubusercontent.com/31222573/33808209-b7bd971c-dde2-11e7-851d-039903332fd3.png)

Not using docker or proxy. Probably using python 2.7 
Starting from console also does not work.
![calibrewebdirectory](https://user-images.githubusercontent.com/31222573/33808228-14cfd37a-dde3-11e7-8ea9-aeb14b3a55e8.png)
![calibrewebpagenotloading](https://user-images.githubusercontent.com/31222573/33808239-51873b5a-dde3-11e7-9bfe-80cd9d075ca8.png)

**Comment by OzzieIsaacs** [comment]
Okay, the version you are using is very old. In between many things changed.
The settings aren‘t loaded from the config file anymore, instead we have a grafical config. All settings are now stored in the app.db file (database). Everything should be migrated.

So you have to finish the setup on Hostnamen:8083. there you can change the port back to 8090.
We also removed the vendor path. So you should install the dependencies like described in the readme, chapter quick setup:
 Install dependencies by running pip install --target vendor -r requirements.txt. (First step)

**Comment by sand3rk** [comment]
Thanks for the help. I will try a clean install.

**Comment by sand3rk** [comment]
`/Documents/calibre-web-master # `pip install --target vendor -r requirements.txt`
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/certifi-2017.11.5.dist-info already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/wand already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/Jinja2-2.10.dist-info already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/Wand-0.4.4-py3.4.egg-info already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/tornado-4.5.2-py3.4.egg-info already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/backports_abc-0.5.dist-info already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/flask_principal.py already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/iso639 already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/blinker already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/pytz already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/Babel-2.5.1.dist-info already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/flask_babel already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/SQLAlchemy-1.1.15-py3.4.egg-info already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/idna-2.6.dist-info already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/Flask_Babel-0.11.1-py3.4.egg-info already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/Werkzeug-0.13.dist-info already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/backports_abc.py already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/urllib3 already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/chardet-3.0.4.dist-info already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/markupsafe already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/blinker-1.4-py3.4.egg-info already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/werkzeug already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/jinja2 already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/urllib3-1.22.dist-info already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/tornado already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/itsdangerous.py already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/sqlalchemy already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/chardet already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/Flask_Principal-0.4.0-py3.4.egg-info already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/__pycache__ already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/flask already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/pytz-2017.3.dist-info already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/babel already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/Flask-0.12.2.dist-info already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/iso_639-0.4.5-py3.4.egg-info already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/requests-2.18.4.dist-info already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/Flask_Login-0.4.1-py3.4.egg-info already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/PyPDF2 already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/PyPDF2-1.26.0-py3.4.egg-info already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/idna already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/unidecode already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/itsdangerous-0.24-py3.4.egg-info already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/flask_login already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/click already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/certifi already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/MarkupSafe-1.0-py3.4.egg-info already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/click-6.7.dist-info already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/requests already exists. Specify --upgrade to force replacement.
Target directory /home/sander/.local/share/Trash/files/calibre-web-master.2/vendor/Unidecode-0.04.21.dist-info already exists. Specify --upgrade to force replacement.
You are using pip version 7.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
If 'Collecting' is not a typo you can use command-not-found to lookup the package that contains it, like this:
    cnf Collecting
workstation:/home/sander/Documents/calibre-web-master # 
`
When i try to find these package using yast, it will not find all of them.

**Comment by OzzieIsaacs** [comment]
From what I read in the console output all requirements are installed. 
I'm a bit confused, because it looks like you started the command from: /home/sander/Documents/calibre-web-master
Calibre-web lies in: /home/sander/.local/share/Trash/files/calibre-web-master.2/ right? (This is where the dependencies are installed)

The last line confuses me: ... 'Collecting' ... 
in the whole output there is no line saying something about Collecting ???

**Comment by sand3rk** [comment]
I got it. It works now. Thanks. Only need to figure out why auto startup is not working.
