### ISSUE TITLE
Read status in Calibre

### ISSUE THREAD

**Issue by 8bitgentleman** [janeczku/calibre-web#409]
Is it possible to set the read status of a book in calibre-web and have that show up in calibre and vice-versa mark a book as read in calibre and have it marked as read in calibre-web?

**Comment by OzzieIsaacs** [comment]
You can add a boolean custom column in Calibre. In the edit book page you can them set it to true or false, this status will be shown on the books detail page.

But I was indeed thinking of a possibility to automatically link the Calibre-web read/unread status to a column in Calibre.

**Comment by 8bitgentleman** [comment]
Yea I've set up the column in Calibre and then noticed that calibre's read column was independent of calibre-web's read checkbox. I think automatically linking them like you said makes sense

**Comment by 8bitgentleman** [comment]
Thanks for implementing this! One small question. I have my read/unread column in calibre linked to calibre-web and that works perfectly. One strange thing is that now in calibre-web when you look at the book details page there is the normal Read checkbox as well as an un-editable Read checkmark. Is there a way to hide this? 

_This is what it looks like:_

---
<img width="338" alt="screen shot 2018-07-15 at 1 06 44 pm" src="https://user-images.githubusercontent.com/4028391/42736201-f2ced152-882f-11e8-97e6-6565c604be1a.png">

---
Thanks!

**Comment by OzzieIsaacs** [comment]
Yes please add the Column name to the ‚Regular expression for ignoring columns‘, on config page one line above the link read/unread config, than the checkmark disapears

**Comment by 8bitgentleman** [comment]
Perfect, you've thought of everything 👍
