### ISSUE TITLE
No Book-Cover with Kindlegen sending the Book via E-Mail

### ISSUE THREAD

**Issue by TheLux83** [janeczku/calibre-web#411]
Hey there,
I'm using the calibre-web Docker image from technosoft2000 but I think this is no error with the image.
When I'm sending a Book to my kindle via Calibre-Web, everything is going well.
It send the book and my kindle downloads the book. No problem with that. But unfortunately, it doesn't download or shows me the book cover. When I transfer the eBook via Calibre directly, it shows me the cover.

Is this a normal behavior? If not, do you need anything else to investigate my problem?
As I said, I'm running an Container via Docker. 
Here are the versions how they are displayed at the about page:

Program library | Installed Version
----------------|----------------------
Python | 2.7.13 (default, Apr 20 2017, 12:13:37)  [GCC 6.3.0]
Kindlegen | Amazon kindlegen(Linux) V2.9 build 1028-0897292
ImageMagick | ImageMagick 6.9.9-21 Q16 x86_64 2017-11-04 http://www.imagemagick.org
PyPDF2 | v1.26.0
Babel | v2.5.1
SqlAlchemy | v1.1.15
Flask | v0.12.2
Flask Login | v0.4.0
Flask Principal | v0.4.0
Tornado web server | v4.5.2
ISO639 Languages | v0.4.5
Requests | v2.18.4
SQlite | v3.20.1
Pysqlite | v2.6.0

**Comment by varunpatro** [comment]
Having the same issue here too. @janeczku can you provide any help here? I can help to submit a patch if you can point me in the right direction.

My guess for this is that its something about the metadata image url, but I'm only speculating here.

**Comment by Kyosfonica** [comment]
I use that container and do not experience the issue. Which kindle are you using? I have kindle keyboard and kindle app. Keyboard doesn't display covers but the app does after the book is downloaded.

**Comment by adocampo** [comment]
Kindle Voyage 2016.

**Comment by Kyosfonica** [comment]
Just received my Kindle Paperwhite.

I was able to reproduce the issue so I will take a look into it.

**Comment by Kyosfonica** [comment]
I checked the flow and what kindlegen does.
Unfortunately this is not an issue of calibre-web. The problem is with kindlegen that is unable to convert the epub cover into kindle mobi compatible. Kindlegen is Amazon.com property, it is free to use but it isn't open source.

I checked kindlegen alone and the same issue appears. The book is correctly converted and readable but you get this error message during conversion:
`Info(prcgen):I1052: Kindle support cover images but does not support cover HTML. Hence using the cover image specified and suppressing cover HTML in content.`

The quickest solution is to use another conversor and add the mobi files to the library, but it adds a layer of  complexity to the simple "Send to Kindle" feature that we all love.

Calibre has its own conversor but it is embedded in the code. A command line tool is provided but it is just an interface to use the conversor alone. The full project is required to make it work.

Maybe someone is willing to add support to another conversor?

**Comment by adocampo** [comment]
In fact, kindlegen does the job, but if not as effective, in terms of the size of the converted file, as calibre's one. If you take a EPUB and convert it to MOBI with both calibre and kindlegen, besides calibre can embed the book's cover, the total size of the MOBI file is far smaller than the file generated with Kindlegen.
I'm not a developer myself, so I'm not able to develop another conversion engine, but I wonder if it it would be very difficult to use calibre's converter (named ebook-converter) by installing calibre, perhaps we can use it in conjuntion with calibre-web.

**Comment by Kyosfonica** [comment]
It won't be difficult to add the option to use one or the other as the code just links the executable with the files before sending the book by email.

I can make the changes myself but I have no free time to do it right now.

If any other is willing to do it first, I can guide him. Otherwise I will take care of the changes once I have some free time.

**Comment by OzzieIsaacs** [comment]
Thanks a lot for digging into this (unfortunally I don't have a kindle.)

**Comment by adocampo** [comment]
@Kyosfonica to be fair, I didn't tested by myself ebook-convert from calibre's binaries. I guess that is the tool it uses when converting an ebook, but perhaps it does programmatically and not through this tool. So, please, before you invest time, let me test and make us sure it will work.
On the other hand, I was unable to install calibre inside the technosoft2000 docker container, so I need to dig also on this to add it to the container or fork it to include at least ebook-convert (and all its dependencies).
I'm pretty busy at the moment, and worst of all, I'm a "paper" reader, so I only read ebook ocassionally (when I just finished one and I'm on my way home in the subway) and the only kindle at my reach is the one from my woman, so please be a bit patient, I'll do the tests and report back here

**Comment by Kyosfonica** [comment]
Hi @adocampo,

I already tested both conversors. Kindle devices doesn't support html covers on books, although the cover is there for the kindle app (at least on Android) and for Kindle keyboard (that is only displayed on the book settings page, so a bit useless) on next gen kindles with cover support this image is not displayed at all.

On the other hand, calibre converter does the job as expected and the cover is visible on all kindle devices. The drawback of this conversor is that you need the full calibre project to make it work. There is a separate executable (ebook-convert) that is an interface to only use the converter via command line without the need of use the rest of calibre but it still requires the full project to work.

I didn't test yet to run calibre from the docker container though. I do not know if there are dependencies to meet before being able to run the conversor via command line.

**Comment by Kyosfonica** [comment]
@Technosoft2000 is it possible to run calibre on your calibre-web docker image?
I am having problems with "No such file or directory" when trying to execute it.

Could you guide me to have calibre up and running?

**Comment by Technosoft2000** [comment]
Hi @Kyosfonica 

I've seen that the user @jim3ma created a fork and added there the calibre support on the docker image - look at https://github.com/jim3ma/docker-calibre-web

Did you tried this fork already?

**Comment by Kyosfonica** [comment]
Hi @Technosoft2000,

Didn't know about that fork. Thanks for the information, I will take a look at it.

**Comment by adocampo** [comment]
I'd tried to follow the steps of several alpine calibre-web dockers to install calibre but none of them worked for me. Is that another cointainer from jim3ma working?

**Comment by TheLux83** [comment]
Hey there all,  
thanks for looking into my problem. It seems, that I was not the only one ^^  
Since a few month now, I switched from my kindle paperwhite to my kindle fire tablet. But now I wanted to switch back and remembered this issue.  
So, do I have to install jim3ma's Docker Image now? Or is it integrated in @Technosoft2000 Docker Image as well?

**Comment by Kyosfonica** [comment]
You should use jim3ma's one

**Comment by captainepoch** [comment]
If `calibre` is installed, they provide a command-line tool called `ebook-convert`. With this tool it is  possible to convert from epub to mobi and transfer the file to the kindle. Maybe it is useful instead using the `kindlegen` tool, which convert the file but is sent as a document, not as a book.

**Comment by OzzieIsaacs** [comment]
Converting books via calibre's ebook-convert is possible now. I consider this as solved.

**Comment by adocampo** [comment]
Just to be clear, now when you Send to Kindle an EPUB, it uses the ebook-convert tool instead kindlegen? Or is there some setting to check out?

**Comment by OzzieIsaacs** [comment]
You have to have calibre installed on your pc. Afterwards you can config calibre-web to use the calibre-converter to convert books (admin-> basic config -> converter)

**Comment by adocampo** [comment]
Perfect! I'm using the calibreweb docker cointainer with calibre preinstalled, so I only need to fetch the latest version and test it.

Thank you very much!!! :)

**Comment by adocampo** [comment]
Just hang around to say now, ebook-convert works perfectly and sends the cover to Kindle, besides the size of the MOBI file is quite smaller than the books converted with kindlegen.
Good job!! :+1:

**Comment by bodybybuddha** [comment]
FYI @Technosoft2000's docker image has the ebook-convert feature as well.
