### ISSUE TITLE
Google Drive Integration Missing

### ISSUE THREAD

**Issue by yabdali** [janeczku/calibre-web#414]
Installed optional packages one by one as it was talking forever due to running out of space on the /dev/root/. Installing lxml using PIP was causing issues so I kept till the end and got no issues installing it individually.

However, I cant seem to find GDrive integration in the config (admin) section for my already setup library.  I tried removing the app.db and starting from scratch but still its now showing me anywhere where I can tick for GDrive integration although I can activate now Goodreads api. 

Appreciate your help, thanks.

server detailts: Linux MyCloud 3.2.68 #7 SMP Wed Apr 1 18:37:42 UTC 2015 armv7l GNU/Linux

**_Below is the file structure after installing the optional packages._**
![imgnas](https://user-images.githubusercontent.com/30695308/34016080-00beb11c-e13a-11e7-8d8e-f8a19fb4470a.PNG)

Log file details:
[2017-12-14 01:49:14,251] {/media/ec1f22b7-89c5-4f90-94dd-801d215f393f/calibre-web/cps/web.py:230} INFO - Starting Calibre Web...
[2017-12-14 01:49:18,445] {cps.py:31} INFO - Falling back to Tornado
[2017-12-14 02:03:36,353] {/media/ec1f22b7-89c5-4f90-94dd-801d215f393f/calibre-web/cps/web.py:230} INFO - Starting Calibre Web...
[2017-12-14 02:03:39,122] {cps.py:31} INFO - Falling back to Tornado

**Comment by OzzieIsaacs** [comment]
For using the google drive integration, Calibre-web has to run with gevent, the logfile shows it’s running with tornado. But the filestructure indicates it’s installed, could you please check if it’s really installed and or try to reinstall this package?

**Comment by yabdali** [comment]
I had to reinstall the requirements and optional requirements using pip.  However, when I try to enter the Google Drive authorization details I keep getting an internal server error. I run my calibre-web on a local nas drive based on a private IP and Google console requires a top domain for the authorized redirect.  Not sure how people are configuring the CALIBRE_WEB_URL/gdrive/callback.  Can't seem to find a visual explanation for the integration anywhere.

**Comment by OzzieIsaacs** [comment]
Could you pleae paste the content of the calibre-web file and the traceback during the internal server error. Than I can have a look.

**Comment by OzzieIsaacs** [comment]
I mean the calibre-web.log file of course

**Comment by OzzieIsaacs** [comment]
No response for long time
