### ISSUE TITLE
Not able to remove books from private shelf

### ISSUE THREAD

**Issue by kobemtl** [janeczku/calibre-web#419]
Happy holiday.

I am having a problem to remove books from private shelf. Apache log shows the 403 error below. I have to set the shelf to public to remove it. The user I am using with all possible rights. Is it bug or anything wrong with my setting. 

` [26/Dec/2017:11:07:07 -0500] "GET /calibre-web/shelf/remove/3/13262 HTTP/1.1" 403 753 "https://xxx.xxx/calibre-web/shelf/6" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 `Safari/537.36"`

**Comment by OzzieIsaacs** [comment]
Please check newest commit
