### ISSUE TITLE
The 8083 port of my server is already used. How do I change the caliber-web port?

### ISSUE THREAD

**Issue by GBochicchio** [janeczku/calibre-web#421]
The 8083 port of my server is already used. How do I change the caliber-web port?  _Sorry for my english_

**Comment by OzzieIsaacs** [comment]
Stop the other program using the port. Start calibre-web, during the initial config you can define the port you want to use. After finishing the config of Calibre-Web restart the other program, and everything should work as desired

**Comment by GBochicchio** [comment]
Thanks for the answer! How can i show what is the program that used this port?

**Comment by OzzieIsaacs** [comment]
On Linux 
`netstat -tulpn | grep :8083`
should give the answer

**Comment by GBochicchio** [comment]
Perfect, and how i can shutdown the program?

**Comment by OzzieIsaacs** [comment]
there should be a number before the programname, which is the process id. kill and the number 
for further questions please use google

**Comment by GBochicchio** [comment]
**Thank for the answer!**

**Comment by GBochicchio** [comment]
@OzzieIsaacs I've an error when i convert an epub to mobi for send to kindle. 

> There was an error sending this book: Kindlegen failed with Error E24001. Message: The table of content could not be built.

**Comment by OzzieIsaacs** [comment]
As this one is has nothing to do with the first problem, you should open a new issue. But in this case it is not a calibre-web issue. The kindlegen program can't convert the book, because of some issues with the book itself. Sigil (https://github.com/Sigil-Ebook/Sigil) could help to repair the book.

**Comment by pktholia154** [comment]
I am a layman:
let me know how to make live my calibre library over internet
at present i can access only my own pc via http://localhost:8083/

**Comment by OzzieIsaacs** [comment]
what is your problem? You cannot access it from the internet, or the port is already in use?

**Comment by dongcd** [comment]
by changing default port 8083, you can try export CALIBRE_PORT=xxxx then restart your calibre-web server.

**Comment by Dirk71** [comment]
I can't change the port to 8084...using "Conatiner Manager" on Synology NAS....
[https://snipboard.io/hLcmM0.jpg](url)
No matter what I change it is always accessible via 8083 only.

On "orignial" Calibre-Web it worked well....but I also had to modify app.db settings and change 8083 to 8084.
