### ISSUE TITLE
[Suggestion] Make previews for authors/series/tags

### ISSUE THREAD

**Issue by gfriloux** [janeczku/calibre-web#422]
Actually, listing series will only print a text list of existing series.
This is not very friendly for everyone.

Being able to generate preview icons would help.
For example, being able to attach an image to a serie, or generate one automatically if none exists (by taking 4 covers from the series, for example).

A lot of people are used to previews, for example when using netflix, plex, emby...
I dont know the impact with OPDS support, and all those things, but the UI would really be enhanced by such a feature.

I know that calibre-web has its own DB for the UI part, and uses the DB from calibre for managing books, but i dont know what can be done (what would be best).

**Comment by gpapin** [comment]
Preview for series partially implemented in https://github.com/janeczku/calibre-web/pull/986
I say partially because you won't be able to chose the image of the serie, it's going to automatically pick the cover of the last book in the serie.

**Comment by gfriloux** [comment]
This is a long awaited feature :)
Nice to see someone working on it!
