### ISSUE TITLE
Web Layout

### ISSUE THREAD

**Issue by mccorkled** [janeczku/calibre-web#424]
I recently got this working on my NAS and am excited to begin using it on our iPads across the house. I was curious if there was a way to get a more responsive iPad layout. Everything on the main book page is squished to the right. It would be also nice to have a 140x140 favicon added to make it look more like an app rather than it caching the web page to use as the icon. I can add screenshots if necessary. 

Thanks :)

**Comment by OzzieIsaacs** [comment]
If created a new favicon with 140x140 resolution. Please check if it looks better, otherwise you are invited to create one. The logo is a big "C" in the GrandHotel-Regular font to be found in the font folder of calibre-web

**Comment by OzzieIsaacs** [comment]
I added a patch for the apple devices (didn't read it the first time)
Regarding ipad layout, you are talking about everything squished to the left (big empty area right), aren't you?
![grafik](https://user-images.githubusercontent.com/6438895/34916305-65d6bb9e-f936-11e7-95ba-2bdba7676933.png)

**Comment by mccorkled** [comment]
Yes, that is correct. Can I update via the webUI or do I have to redownload the Docker?

**Comment by OzzieIsaacs** [comment]
I'm not the maintainer of the docker container, and I don't know if the updater works within docker, sorry.

But for sure, the changes have to be included in the docker container, before redownloading the docker container makes sense.

**Comment by mccorkled** [comment]
Anyway you can add an update function/ auto update function to the program? The check for updates thing is cool, but if you can't update, what's the purpose?

Thanks

**Comment by OzzieIsaacs** [comment]
The updatefunction is working fine for the non docker version

**Comment by mccorkled** [comment]
The Docker build I am using is am automatic build. Maybe I am missing something, but I do not see update. Under Admin, there's a check for update but that's all I'm seeing.

**Comment by mccorkled** [comment]
I’m not seeing this as fixed. 

![0bb61ebe-672b-4040-8472-747b4e4ceb00](https://user-images.githubusercontent.com/13697804/34970569-0f084400-fa43-11e7-8362-a2d4b1b9c1c7.png)

**Comment by OzzieIsaacs** [comment]
I didn't change anything regarding the layout part. I'm aware of it, fiddled 3hours on it, but still don't understand what happens. It seems to be something in the bootstrap library.

**Comment by mccorkled** [comment]
Ok thanks. I'll wait it out.

**Comment by leram84** [comment]
yeah, theres a lot going on here. Hard coded absolute positions in the html does not mix well w all the percentage based sizing that bootstrap is packed with. A layout overhaul where everything is inline in the html so you have more freedom to build a dynamic layout in the css would be ideal, but a quick fix is to just pick a max-width for each item and stick with it so covers have room to be more or less wide as they're all different (this will also help w all the warping of covers that happens w these percentages). Personally, i think 225px is the sweet spot, so you could probably take care of this w 1 edit.

This is the offending code in bootstrap:
```
@media (min-width: 768px) {
    .col-sm-3 {
        width: 25%;
    }
}
```

Easiest fix imo is to just drop this in ur css:
```
@media (min-width: 768px) {
    #books, #books_rand {
        width: 225px;
    }
}
```
And you'll fix both this issue, and the warping issue (as long as the cover isn't over 225px wide... which i haven't come across yet.

**Comment by mccorkled** [comment]
Any more on this?
