### ISSUE TITLE
Broken bookshelf lay out 

### ISSUE THREAD

**Issue by abubaman** [janeczku/calibre-web#425]
As attached file below, bookshelf lay is broken.
Please let me know how to solve this problem

![cap 2018-01-03 17-05-31-368](https://user-images.githubusercontent.com/27588851/34512893-889bc0c0-f0a8-11e7-87c0-abe586b7a45f.jpg)

**Comment by OzzieIsaacs** [comment]
For me its working:
![grafik](https://user-images.githubusercontent.com/6438895/34639266-216cf43c-f2dd-11e7-8984-f93bdf994296.png)
which browser are you using? Is it always happening? If you are resize the browser is the problem disapearing?

**Comment by abubaman** [comment]
I found that this was happened when I use Explorer(V.11).
But, When I use Chrome, below happens.(at the very first, the number of column was 5, but for additional list this became 6 when I scrolled down.
![image](https://user-images.githubusercontent.com/27588851/34656321-492f7dee-f45b-11e7-8039-fb1d9644a080.png)

**Comment by OzzieIsaacs** [comment]
Related to #426
