### ISSUE TITLE
Having a trouble with searching which uses 2-bytes language(korean)

### ISSUE THREAD

**Issue by abubaman** [janeczku/calibre-web#426]
I opend issue a half-year ago like below(#217)
----------------------------
I am a user of calibre-web and it works fine.

but i have a trouble with searching functionality. when I have tried to search 'title in korean', sometimes they can find books, but sometimes they can not find books even though their titles have same word which i typed in search text area.

So how can I solve this problem?
------------------------
So You answered

OzzieIsaacs  commented on Jul 7 2017 

could you give me a working and a non working title example (I can than generate book entries in my library with these and check it)

**Comment by abubaman** [comment]
So I give you information about an working and a non-wokring title as below.
Working Title : 품격이
Non Working Title : 이윤기의

**Comment by OzzieIsaacs** [comment]
Both your working and your non working example worked for me:
![grafik](https://user-images.githubusercontent.com/6438895/34639504-92fa8aa2-f2e1-11e7-9fa1-5f26366b0f37.png)

Which browser are you using? 
Are you using the newest version, recently there was a change regarding non-ASCII search ( #368 )

**Comment by abubaman** [comment]
No I am not using latest version. 
I will try update version and let you know how it works. many thanks.

**Comment by abubaman** [comment]
after i updated to the latest version, same problem continued.
the exact problem is like below.
the original book title is "219 이윤기의 그리스 로마 신화" and when i search the title with only some part like"이윤기의" it didn't work.
when i search with full sentence like "219 이윤기의 그리스 로마 신화", it works.

**Comment by OzzieIsaacs** [comment]
I can reproduce the error now, with the informations you gave me.

**Comment by OzzieIsaacs** [comment]
Please try the newest commit, it should now work
