### ISSUE TITLE
What Happened ?

### ISSUE THREAD

**Issue by zerona2018** [janeczku/calibre-web#427]
![image](https://user-images.githubusercontent.com/35061787/34515090-8157a010-f0ab-11e7-9ce5-fee2e34165e0.png)

not suppot cbz ,cbr ?

**Comment by OzzieIsaacs** [comment]
Are you using the newest commit version from the master branch? 
For me its working.

**Comment by OzzieIsaacs** [comment]
No feedback for a long time
