### ISSUE TITLE
[Enhancement] "Want to Read" functionality

### ISSUE THREAD

**Issue by adilei** [janeczku/calibre-web#428]
It would be useful to have a "Want to Read" button/checkbox for books, and a matching section of "Books I Want to Read". Checking "Read" will remove books from that section, similarly to "Unread Books". 

"Unread Books" is not very useful in a multi user environment, as unread books are not necessarily interesting to all users, and so the view ends up being pretty cluttered. 

Thanks!

**Comment by 8bitgentleman** [comment]
Can't you create a custom "To Read" shelf for that?

**Comment by OzzieIsaacs** [comment]
I agree with @8bitgentleman, this is the way to do it.
