### ISSUE TITLE
Request: different authentication backends for LDAP support

### ISSUE THREAD

**Issue by cnf** [janeczku/calibre-web#43]
Hi,

any chance to get a modular authentication backend? I would like to get LDAP support.

From what I understand reading the source, and looking at `flask.ext.login`, it's pretty set to one way atm.

**Comment by mlg9000** [comment]
I'll second this, or at the very least the ability to disable authentication completely and instead handle that in with a reverse proxy web server.

**Comment by cnf** [comment]
Can we get a reasoning for this?

**Comment by OzzieIsaacs** [comment]
I'm not familiar with this topics. 
I don't want you to expect that it is implemented at any time, which isn't going to happen from my side. If anybody implements it, if it has no big influence on the code I'm willing to merge it.

**Comment by cnf** [comment]
Well, that is why i was asking if it could be made modular, so people could implement their own backends into it. I can check how it is now, but there are pluggable auth modules for flask, i think.
