### ISSUE TITLE
how to add apple-touch-icon

### ISSUE THREAD

**Issue by abubaman** [janeczku/calibre-web#437]
I use iPhone.
in order to see 'icon' in the frequently visited website in Safari, as I know, I need to register 'apple-touch-icon' to web server like below.
but I don't know how.
and can I substitute favicon to my personal image also?

please let me know if you have any ideas. thank you.
-------
```
<link href="http://www.yoursite.com/apple-touch-icon.png" rel="apple-touch-icon" />
<link href="http://www.yoursite.com/apple-touch-icon-152x152.png" rel="apple-touch-icon" sizes="152x152" />
<link href="http://www.yoursite.com/apple-touch-icon-167x167.png" rel="apple-touch-icon" sizes="167x167" />
<link href="http://www.yoursite.com/apple-touch-icon-180x180.png" rel="apple-touch-icon" sizes="180x180" />
<link href="http://www.yoursite.com/icon-hires.png" rel="icon" sizes="192x192" />
<link href="http://www.yoursite.com/icon-normal.png" rel="icon" sizes="128x128" />
```

**Comment by OzzieIsaacs** [comment]
The favicon section is located in the layout.html file. To replace the contents, you can exchange the favicon.ico in the static folder. 
url_for('static', filename='favicon.ico') -> means static folder link to favicon.ico, would get to
url_for('static', filename='apple-touch-icon.png') in your example above.
I think I will not make it changeable via the web-UI, but you can replace the file with whatever you want on your own.
