### ISSUE TITLE
support uploading multiple books at once

### ISSUE THREAD

**Issue by MosabWadea** [janeczku/calibre-web#438]
Hi
I like the tool a lot, it would be nice to support adding a directory with books to upload them all at once.

**Comment by MosabWadea** [comment]
@janeczku 
any plans to support this? it is very important, some members in our org has hundreds of books to upload, it would be very hard to upload them one-by-one.. 
they want to support the feature to upload many books in a shelf directly or into public without shelves

**Comment by OzzieIsaacs** [comment]
I think easiest way would be using Calibre to upload the files, it’s done within one minute. But this solves of course not the shelf problem. For this you can use my shelf mass adding tool: https://github.com/OzzieIsaacs/cps-shelf-adder

**Comment by MosabWadea** [comment]
I agree about using calibre itself to do the bulk addition..
however, I have launched this tool in our organization closed network, we have about 100 employee and some of them has tens of books, it wouldn't be easy for them to upload it by accessing the server and adding the books manually from there...

I hope I can use your tool as an internal social media for books sharing and knowledge center in our organization.. that is why I also opened issue #442 to add a field in the book info saying who uploaded the book..

**Comment by OzzieIsaacs** [comment]
Feature is implemented and merged. Special thanks to @falgh1

**Comment by crispybegs** [comment]
@OzzieIsaacs can you indicate how a bulk add / upload is executed? i can't find anything in the wiki that details it.

**Comment by OzzieIsaacs** [comment]
You select multiple books and drag’s drop them, or you select multiple books in the upload file dialog

**Comment by crispybegs** [comment]
> You select multiple books and drag’s drop them, or you select multiple books in the upload file dialog

ahhh as easy as that!? thanks!

sidenote: is there any way of searching my library for duplicates? i bulk uploaded several hundred books but there were some dupes in there. CW warned me on the import but imported them anyway. Is there an easy way of finding the dupes so i can delete them?
