### ISSUE TITLE
[HTTPS] Users are redirected to http://domain/login?next=%2

### ISSUE THREAD

**Issue by simkin** [janeczku/calibre-web#44]
I host this application behind an Apache reverse proxy that only listens on port 443. When I land on the website it redirects users to http://domain/login?next=%2, which cannot be resolved as port 80 is not active (so I can also not host a mod_rewrite/redirect to https on port 80.)

Is the login redirect to http hard coded or can it be fixed easily?

**Comment by OzzieIsaacs** [comment]
I found no other way than using header editing within apache config. Here is a working example:
(I didn't get it working on normal http port 80 without changing header)
`
<VirtualHost *:443>
    SSLEngine on
    SSLProxyEngine on
    SSLCipherSuite ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv2:+EXP:+eNULL
    SSLCertificateFile "C:\Apache24\conf\ssl\test.crt"
    SSLCertificateKeyFile "C:\Apache24\conf\ssl\test.key"
    
    <Location /calibre-web>       
           ProxyHTMLEnable On
           ProxyPass            http://127.0.0.1:8083/
           ProxyPassReverse     http://127.0.0.1:8083/  
           Header edit Location "^http://(.*?)/" "https://$1/calibre-web/"
           ProxyHTMLURLMap      /  /calibre-web/       
    </Location>
</VirtualHost>
`

**Comment by simkin** [comment]
Confirmed working for me as well, thanks!
