### ISSUE TITLE
Confusion about /books folder's property and PGID & PUID for docker

### ISSUE THREAD

**Issue by mpco** [janeczku/calibre-web#441]
No docker user in my linux system. 

I run the command: 
```
mkdir CalibreData
sudo docker run -d --restart=always \
    --name=calibre-web \
    -v /home/xx/CalibreData/books:/books \
    -v /home/xx/CalibreData/config:/calibre-web/config \
    -e USE_CONFIG_DIR=true \
    -p 8083:8083 \
    technosoft2000/calibre-web
```

then, the /books folder's own is root:root 755
the config folder's own is calibre:calibre 
I copy Calibre's metadata.db and so on files to /home/xx/CalibreData/books/
The Calibre-web works well at first launch.
But it occurs error( no permission ) when I want to upload pdf file.
Then I run `sudo docker exec calibre-web chmod -R 777 /books` and restart docker container.
Uploading works well.

I do not know whether this solution is correct.
what should I do?

Thank you.

**Comment by OzzieIsaacs** [comment]
Could you please post you issue/question in the docker repository. I'm not the owner of the docker repro, and I'm also no experienced docker user.
