### ISSUE TITLE
download/read in browser button when showing title physical book

### ISSUE THREAD

**Issue by amoize** [janeczku/calibre-web#443]
We have in Calibre also entered our physical books collection. When these physical book items are opened in Calibre-web the buttons for download and 'read in browser' are visible, but the buttons cannot do anything because there is no file to download or read. When the button 'read in browser' is pressed the list is empty. see picture. Would it be possible that the buttons are only visible when there are file(s) to read or download? So it is clear if the book is an ebook or a physical book item.
 
![calibre-web-readbutton](https://user-images.githubusercontent.com/10452828/35342405-e14cc322-011f-11e8-97a1-44e3a66d023f.png)

**Comment by OzzieIsaacs** [comment]
Please try the newest commit version

**Comment by amoize** [comment]
Tested it! It works very well. With the physical books there are no buttons. OzzieIsaacs@Thank you!

**Comment by ZhangYanTJU** [comment]
Hi
I used the latest version from GitHub.
But this problem remains.

**Comment by ZhangYanTJU** [comment]
![1](https://user-images.githubusercontent.com/23287501/38765645-8507baf0-3ff8-11e8-9328-d4ec6e3a3cc2.JPG)
![2](https://user-images.githubusercontent.com/23287501/38765646-8561ec28-3ff8-11e8-8442-d8361402ce9a.JPG)
