### ISSUE TITLE
"Calibre database directory (DB_ROOT) is not configured"

### ISSUE THREAD

**Issue by wtrdk** [janeczku/calibre-web#45]
Hi,

When I run ` /usr/bin/python /opt/calibre-web/cps.py` from my home dir I get this error:
`Calibre database directory (DB_ROOT) is not configured`

When I run `/usr/bin/python /opt/calibre-web/cps.py` from `/opt/calibre-web/` it runs perfectly!

I want to use the command to start the calibre-web instance at boot, but when I add it to crontab I get that same error message.

Can you help me?

**Comment by OzzieIsaacs** [comment]
As a quick workaround I recommend adding:
cd /opt/calibre-web/ && /usr/bin/python cps.py
In crontab, this should help

**Comment by wtrdk** [comment]
Thanks, that works for now!

**Comment by OzzieIsaacs** [comment]
I created a pull request #48 solving the issue.

**Comment by wtrdk** [comment]
Hi,

I dit a git pull, but no changes. Maybe it's not committed yet?

**Comment by OzzieIsaacs** [comment]
I have no write rights to the repro. So I created a pull request, but until it is merged by @janeczku you won't see it.

**Comment by wtrdk** [comment]
Ah, oke. Thanks a lot!

**Comment by cervinko** [comment]
#48 is merged. @wtrdk can this issue be closed?

**Comment by wtrdk** [comment]
Yes, it can be closed. Thanks!
