### ISSUE TITLE
Send the file without conversion

### ISSUE THREAD

**Issue by tomandocubatas** [janeczku/calibre-web#450]
Is possible to send the file (epub, etc) to a email? No only to send the epub after conversion to kindle

**Comment by modembug** [comment]
I was just thinking it would be cool to be able to share an item via email without any conversion.

**Comment by OzzieIsaacs** [comment]
Currently its only possible to send mobi files to a defined email adress. Sending it to a freely specified email adress would be in my eyes a bit beyond the project scope. So I'm not going to implement it.
Sorry for the late reply
