### ISSUE TITLE
Rating system

### ISSUE THREAD

**Issue by tomandocubatas** [janeczku/calibre-web#451]
Create a rating system on a book with comments sent by various selected users. Also have an average rating based on the ratings sent by the different users.

**Comment by OzzieIsaacs** [comment]
I don't want to create any new database coloums aside from the ones calibre has becauses this causes a lot of trouble. So I don't want to implement this one, sorry.

**Comment by chadfurman** [comment]
This is likely possible through a Calibre plugin / calibre-web-mod.
