### ISSUE TITLE
Setup.py

### ISSUE THREAD

**Issue by blade2005** [janeczku/calibre-web#456]
I was curious if there was a reason why a setup.py file isn't included?

Most projects I see do have a setup.py this aids in the install process and installs the script entry point in the correct ${PREFIX}/bin dir.

This would also allow the project to get onto pypi

**Comment by decentral1se** [comment]
I'd be willing to pick this up if someone is interested in reviewing the PR? With the latest modern setuptools situation, the `setup.py` is not the nasty monster it used to be. It would be really great to get #677 then moving along afterwards.

**Comment by OzzieIsaacs** [comment]
I'm interested in the feature, if you could implement it, this would be great

**Comment by decentral1se** [comment]
OK, I've opened up https://github.com/janeczku/calibre-web/pull/927 for it :+1:
