### ISSUE TITLE
Comics are "corrupted or not an image"

### ISSUE THREAD

**Issue by brandonmccarthy** [janeczku/calibre-web#459]
Looking at giving calibre-web a permanent home and running the docker image from technosoft2000 recommended in your readme but I'm getting issues with CBT, CBR, and CBZ files. When I open them I get "Page #1 ($filename).jpg Is corrupt or not an image" in both chrome and firefox.

This happens with three or four different cbr/cbt/cbz files that work with various other applications. I don't see any errors in the logs and don't see a way to enable debugging through the web admin or other means. If there is a good way to collect logs, let me know and I can provide those as well.

Happening on branch master commit ff2d53b. Also tried the comic_server branch and receive the same error message.

**Comment by brandonmccarthy** [comment]
Found debug, gives no more relevant information. Digging through the source code, I found the link to the static cbz, downloaded it and compared sha hashes to the one I uploaded and the hashes match so it's not being corrupted. Maybe this is an issue with kthoom or it's implementation?

**Comment by OzzieIsaacs** [comment]
The cbr cbz cbt files are just renamed rar zip and tar files. Could you please rename the files, open them with an archiver and check the file formats included (I think it’s maybe not jpg, but something different which isn‘t recognized well)

**Comment by brandonmccarthy** [comment]
I can extract the files from the archives no problem. They also open and work just fine in other applications.

$ file GITS.cbz 
GITS.cbz: Zip archive data, at least v2.0 to extract
$ extract GITS.cbz -d GITS
$ file GITS/002.jpg 
GITS/002.jpg: JPEG image data, JFIF standard 1.01, resolution (DPI), density 200x200, segment length 16, comment: "Handmade Software, Inc. Image Alchemy v1.9.1", baseline, precision 8, 1275x1999, frames 3

Also noticing a fun quirk where loading any cbz from calibre-web will completely fill my available ram and thrash for a bit, locking up my computer until the browser gets OOMed. Happens in both FF and Chrome. I'm assuming this issue is a byproduct of the cbz load/read failure.

**Comment by andy29485** [comment]
This is because the current implementation stores the image as base64 data in the html (read: load all of it at once uncompressed). I would like there to be an option to go back to locally extracting pages and having a url for each page. But i haven't had the time to think though the problems this will cause:
1. When do the extracted files get cleaned up?
2. Going to the next page will be slow (since the.browser will need to fetch the page each time - maybe cache just the next 1 or 2 pages? I'm not sure yet)

This might also fix the failing to extract problem you're (and I'm also) seeing.

**Comment by brandonmccarthy** [comment]
Is there any sort of temporary workaround that you have found? The cbz files that I'm testing with are only 30mb which is pretty small and should decompress fairly quickly even if it is client side in the browser.

**Comment by andy29485** [comment]
They don't decompress client side. What happens is it gets decompressed on the server, turned into text, and then sent to the browser.

As for a fix: refreshing the page and restarting calibre-web usually works for me. If that doesn't help try reverting back to an older commit (one of the first one in this branch).

**Comment by brandonmccarthy** [comment]
Restarting the server doesn't work for me. I also tried the commit mentioned but it still fails. I also tried spinning up the server in it's own virtualenv on my laptop to rule out the docker environment but I'm still getting the same errors. Everything else (epub mainly) continues to open as expected.

**Comment by ianc125** [comment]
I was having the same issue with all my CBR files. But noticed all my CBZ were working. I just converted them all to CBZ in the mean time and that has worked until this bug is fixed.

**Comment by OzzieIsaacs** [comment]
I‘m aware of the bug in the comic branch, it‘s still work in progress. The comic-branch is not ready for productive use. I‘m happy for any suggestions fixing the issue.

**Comment by brandonmccarthy** [comment]
> I was having the same issue with all my CBR files. But noticed all my CBZ were working. I just converted them all to CBZ in the mean time and that has worked until this bug is fixed.

I get the same error regardless of file type unfortunately. 

> I‘m aware of the bug in the comic branch, it‘s still work in progress. The comic-branch is not ready for productive use. I‘m happy for any suggestions fixing the issue.

These errors are occurring in the master branch. I only tried the comic branch for testing.

**Comment by OzzieIsaacs** [comment]
@ianc125 : the rar implementation of the used kthoom lib is not 100% complete for rar files, that could be the reason ( or if you are using the comic branch you need to install unrar and configure Calibre web to use it)

**Comment by brandonmccarthy** [comment]
As a jumping off point, I can't even get this to work with calibreweb master branch (Current commit timestamp: 3/10/18, 7:42 PM)

https://github.com/codedread/kthoom/blob/master/examples/codedread.cbz

I'm assuming that this should work since it's an example cbz file from the kthoom team. It works perfectly fine when I upload it from my computer to their github example page [here](https://codedread.github.io/kthoom/index.html). 

As always, to ensure this isn't a docker related issue, I've setup a testing version on my local machine using pip and virtualenv. The example cbz file from the kthoom team does not work in chrome or firefox. 

Seems to me that cbz/cbt/cbr support is completely broken.

**Comment by OzzieIsaacs** [comment]
Okay, I can reproduce the error with the codedread.cbz. I can take look at it. (My other files are working).

**Comment by OzzieIsaacs** [comment]
The kthoom link you posted is not from the main kthoom, but from a fork, which includes svg-Image support. That's why it wasn't working. SVG-Files are now working (but not in IE11). But this has nothing to do with the original problem. I doublechecked, my testcomics are working, I need a nonworking example to find the reason for your problem.
Could you send it to me via e-mail (the one one my profile page), thanks.

**Comment by OzzieIsaacs** [comment]
No response for long time
