### ISSUE TITLE
[Question] How add new book?

### ISSUE THREAD

**Issue by candidodmv** [janeczku/calibre-web#463]
Sorry, but I don't found instructions about how to add new books, someone could explain to me?

Thanks!

**Comment by OzzieIsaacs** [comment]
You have to enable uploading in the admin section (config) afterwards an uploading button appears.
Or you could add the books like before with calibre

**Comment by Gagalari** [comment]
Sorry, I can't see this button when I logged in as admin and I have the rights to upload.
Where should this button be?

**Comment by ajorians** [comment]
Hope this helps.

From the 'Admin' section click 'Edit Basic Configuration':
![image](https://user-images.githubusercontent.com/3475163/98455916-b39f8200-2144-11eb-8bd2-97cd06a473cd.png)

Then check 'Enable Uploads':
![image](https://user-images.githubusercontent.com/3475163/98455921-bef2ad80-2144-11eb-93a8-d28537265b37.png)

Save.  (Maybe reload too?)

But then the 'Upload' is in the upper right here:
![image](https://user-images.githubusercontent.com/3475163/98455926-d2057d80-2144-11eb-8449-5290008bb03e.png)

:smiley:

**Comment by Gagalari** [comment]
I had exactly tryed this, but the button wasn‘t shown. I will try it again maybe....

**Comment by timbroder** [comment]
This worked for me. The `admin` user doesn't have upload by default. I needed to give it that permission
