### ISSUE TITLE
Use cloud storage to store book files

### ISSUE THREAD

**Issue by a1023456** [janeczku/calibre-web#466]
可不可以单独配置metadata.db的存储路径？
单独配置图书的存储目录？
可否开发单独配置下载和图片等静态资源的访问域名。

因为我是用了云存储作为图书存储，所以将图书目录放到了云存储上面类似 aws s3 的腾讯云对象存储。

通过挂载后添加到服务器目录，但是频繁读写 metadata.db 会产生问题。 需要将 metadata.db 放到服务器本机。

使用python 访问图片会受限与服务器的出口带宽，我希望直接使用云储存的域名访问图片和下载图书文件。

Can I separately configure the storage path of metadata.db?
Separately configured book storage directory?
Can you develop an access domain that configures static resources such as downloads and images separately.

Because I used cloud storage as a book store, I put the book catalog on cloud storage like Tencent cloud object storage like aws s3.

It is added to the server directory after mounting, but frequent reading and writing of metadata.db can cause problems. You need to put metadata.db on the server itself.

Using python to access the image is limited to the server's export bandwidth. I hope to use the cloud-stored domain name to access pictures and download book files.

**Comment by OzzieIsaacs** [comment]
The only supported cloud storage by now is google drive. Currently I don't want to change this, because every new possible cloud storage creates new work, new issues, new things which have to be checked after a change.
