### ISSUE TITLE
[Question] : Hide content based on custom column

### ISSUE THREAD

**Issue by stefer09** [janeczku/calibre-web#467]
Hi,

Using Calibre content server, want to change to Calibre-web.  In Calibre, I have a custom column called NoNet for books that I don't want users to see.  It's a Yes or No. (Yes won't show on the net)  In calibre I just pick for the web user my usual library with this restriction : 
not #nonet:"Yes" 
It's not a tag, so I'd like to see if there's a way to get this working, if not, I'll have to add a tag to each of them.
(Edit : I tried to add the tag NoNet in some books and filter the mature content by the word NoNet  , it works with epubs, not with PDFs!)

**Comment by OzzieIsaacs** [comment]
It's not possible in calibre web to hide books based on a custom column, it's only pissible by the mature content setting. 
Regarding the not working pdf with mature content, I have to take alook, but I'm currently busy with another project.
