### ISSUE TITLE
[Question] How to add public shelf?

### ISSUE THREAD

**Issue by MaxLFarrell** [janeczku/calibre-web#469]
I'm on a new installation of Calibre-Web, logged in as admin and can only add to "Your Shelves". How am I supposed to add to Public Shelves?

**Comment by JRansomed** [comment]
If you go into the Admin setting and edit the user you are signing in as, check to see if "Allow Editing Public Shelfs" is checked.  I couldn't create public shelfs until I selected this, even though my user is an admin.  I also found that the built-in admin user didn't have this enabled by default.

When the option is enabled, it will give you a new option when you "Create a Shelf".  Under the prompt to name the new shelf, it should have a checkbox for "should the shelf be public?"

Hope this helps!
