### ISSUE TITLE
Suggestion: Integration of DJVU browser-reader

### ISSUE THREAD

**Issue by Johni81** [janeczku/calibre-web#475]
Hey,
would be great to have also a possibility to read DJVU files in the browser, maybe based on this viewer: [https://github.com/mateusz-matela/djvu-html5](https://github.com/mateusz-matela/djvu-html5)

**Comment by OzzieIsaacs** [comment]
I decided to focus on the more "modern" and common book formats: epub, cbx (for comics) and not implementing every different book format.
So I'm not going to implement it.

**Comment by verglor** [comment]
I have implemented it in PR #1713 by integration of proposed [djvu-html5](https://github.com/mateusz-matela/djvu-html5) viewer which is quite memory hungry (for thick scanned books) with modest UI, but for start it is good enough IMO.

As next step I would consider replacing it with [djvu.js](https://github.com/RussCoder/djvujs) which is much faster and does not eat up RAM. However it's UI is currently not suitable for reading books (mainly on mobile).
