### ISSUE TITLE
Downloads on Sony PRS-T1 do not work

### ISSUE THREAD

**Issue by guardiande** [janeczku/calibre-web#479]
When using the built-in browser on the Sony PRS-T1 browsing the library just works fine, but when I try to download an epub the downloads sort of starts but is describe as waiting for a connection.

Does anyone know how to get the downloading working on the rather ancient PRS-T1?

**Comment by gelsas** [comment]
After logging the network traffic with Wireshark it seems that the issue is the PRS-T1 it just cuts the connection to Calibre web

**Comment by OzzieIsaacs** [comment]
Seems not to be a problem of calibre-web
