### ISSUE TITLE
Audiobook support?

### ISSUE THREAD

**Issue by gelsas** [janeczku/calibre-web#480]
Hello,

I just wanted to ask if it is somehow possible to manage audiobooks with calibre/calibre web aswell.

If it is already possible to also manage audiobooks maybe this is also interesting:
Its basically Amazons Whispersync feature: https://github.com/readbeyond/aeneas/
(Someother developer already seems to have added this to his ebook manager: https://www.mobileread.com/forums/showthread.php?t=268702)

Thank you for your time. I really appreciate what you do!

**Comment by saitoh183** [comment]
I do it. I zip up the audiobook and then import the zip to Calibre. Everything else is like normal. You just can obviously read the audiobook online but you can download the zip via calibre-web

**Comment by gelsas** [comment]
There already is an app (https://www.readbeyond.it/menestrello/)  which could uses aeneas: 
And it is open source (https://www.readbeyond.it/minstrel/index.html)

Is it possible to somehow add a button so we can send epub3 files directly to the app ?

**Comment by gabriellluz** [comment]
Well, I use CalibreWeb with Voice (audiobook player for android). I encode all my m4b files to mka (opus audio) and then I open CalibreWeb with my android cellphone and play it directly with Voice audiobook player. It works great.

**Comment by bjhiggins** [comment]
@modembug has added the audiobook functionality in a pull request... Any chance this will become part of the master code branch?

Also - I have some changes to @modembug 's code (support for M4B as well as some usability changes) ... anyone know if I can commit the changes back to a pull request?

**Comment by saitoh183** [comment]
@modembug How do you add audiobooks to Calibre-web? Merge multiple mp3s and upload a single file?

**Comment by modembug** [comment]
You need to be running the code I submitted and then you would upload an audiobook in MP3 format. You could do multiple files if you wanted to, but they would show up as multiple books. I have been stripping the DRM from my Audible collection and uploading them to my caliber web installation. :)

**Comment by saitoh183** [comment]
@modembug im using google drive setup. Ozz said that it doesnt support reading books from web, so i dont know if your code will work with google drive. As i stated earlier i zip my Abooks so i can just download them because i couldnt add all mp3's to a single book. Maybe the next step would be to have all files under a single book. But progress has been made with your code and it is great!

**Comment by felixscheinost** [comment]
I think a cool platform-independent way to sync audiobooks would be to generate a RSS file. Calibre-Web could then provide a button "copy RSS link" which could simply be pasted into any podcast app.

This way Calibre-Web wouldn't need to manage syncing and most podcast apps would be great for listening to podcasts usability wise.

**Comment by bjhiggins** [comment]
Are we ever going to see this brought into the master code branch?

**Comment by bodybybuddha** [comment]
If we could get this brought into the code branch - I think @felixscheinost's idea would be a really awesome feature.  To keep it simple, the button would just need to create an RSS file on demand.

**Comment by bodybybuddha** [comment]
Hey folks - I've updated @modembug's initial PR with the latest changes to the main branch and re-submitted a new [PR](https://github.com/janeczku/calibre-web/pull/634).  Hopefully keeping this alive as, I'm sure, there is a lot of demand for the feature.

I'll keep the branch updated with code changes from the main branch until we have final confirmation if the PR will be accepted into the main branch.

I think that the more people that test this particular fork and report back on successes (or issues) would better the chances of the feature getting baked into the main branch.  So, folks - test away and get vocal!!

@bjhiggins - I added the ability to upload .m4b files.  However, I didn't see any details on usability improvements specifically.  If there are any other please let me know.  (ugh, now that I think of it, I forgot to add in the mime types for downloading!  Something to do tonight I guess...)

**Comment by OzzieIsaacs** [comment]
The feature is merged into the master branch

**Comment by janewar** [comment]
Audiobook?ok
