### ISSUE TITLE
Customizable positions for Navigation - Possible?

### ISSUE THREAD

**Issue by gelsas** [janeczku/calibre-web#481]
Hello! Its me again.

I wanted to ask if it is possible to customize the positions of the navigation.

For example I would like to have the Public shelf on top the browse section.
And maybe as well, if possible, to show the different bookshelfs  instead or above of the Recently added books in the dashboard overview.

**Comment by OzzieIsaacs** [comment]
The layout is fixed, I can not provide customization for everyone. Sorry
