### ISSUE TITLE
[Feature Request] Specific book deleting. 

### ISSUE THREAD

**Issue by mccorkled** [janeczku/calibre-web#485]
I recently noticed that several of my books have multiple copies. When I go into edit meta data and click delete book, it wants to delete all of them. Would there be a way to allow it to only delete the specific format I choose?

For instance, I have an epub and a mobi, and I just want to delete the mobi. Or I have an epub and a txt, and I just want to delete the txt. 

Thank you! :D

**Comment by OzzieIsaacs** [comment]
Function is merged
