### ISSUE TITLE
first time run and config calibre-web on windows, calibre-web gives error 

### ISSUE THREAD

**Issue by amoize** [janeczku/calibre-web#486]
When calibre-web runs for the first time on Windows (where python is installed in C:\program files\python and you save the first web config. Web-calibre crashes and the following error is shown at the command prompt window:  C:\Program: can't open file 'Files\Python\python.exe': [Errno 2] No such file or directory

Looks like the Space in Program Files directory name gives problem

After restarting calibre-web again. Calibre-web works fine. It is only when saving the first time config.

**Comment by OzzieIsaacs** [comment]
Works now on windows also (problem related to spaces in path of excecutable)
