### ISSUE TITLE
Update from admin view failing

### ISSUE THREAD

**Issue by simkin** [janeczku/calibre-web#488]
Stuck after "Files have been replaced" message
Debian: Linux 4.13.13-6-pve #1 SMP PVE 4.13.13-41 (Wed, 21 Feb 2018 10:07:54 +0100) x86_64 GNU/Linux
Python: 2.7.13

> Apr 10 16:25:26 vault13.eu python[22104]: Traceback (most recent call last):
> Apr 10 16:25:26 vault13.eu python[22104]:   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
> Apr 10 16:25:26 vault13.eu python[22104]:     self.run()
> Apr 10 16:25:26 vault13.eu python[22104]:   File "/opt/calibre-web4/cps/helper.py", line 394, in run
> Apr 10 16:25:26 vault13.eu python[22104]:     self.update_source(os.path.join(tmp_dir, os.path.splitext(fname)[0]), ub.config.get_main_dir)
> Apr 10 16:25:26 vault13.eu python[22104]:   File "/opt/calibre-web4/cps/helper.py", line 517, in update_source
> Apr 10 16:25:26 vault13.eu python[22104]:     self.moveallfiles(source, destination)
> Apr 10 16:25:26 vault13.eu python[22104]:   File "/opt/calibre-web4/cps/helper.py", line 489, in moveallfiles
> Apr 10 16:25:26 vault13.eu python[22104]:     + str(permission.st_uid) + ':' + str(permission.st_gid) + ' error: '+str(e))
> Apr 10 16:25:26 vault13.eu python[22104]: NameError: global name 'e' is not defined

**Comment by OzzieIsaacs** [comment]
It's indeed a bug. Please replace the file /cps/helper.py with current one:
https://github.com/janeczku/calibre-web/blob/master/cps/helper.py
and try update afterwards. 
Then the correct error message should appear (seems the user running calibre-web has no rights to change file permissions of the replaced files.)

**Comment by simkin** [comment]
Now I see this in my log. I needed to kill the pid and restart teh service before I could access the (upgraded) instance

> [2018-04-10 19:35:33,838] {/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py:696} ERROR - Exception during reset or similar
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 687, in _finalize_fairy
>     fairy._reset(pool)
>   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 827, in _reset
>     self._reset_agent.rollback()
>   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1621, in rollback
>     self._do_rollback()
>   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1659, in _do_rollback
>     self.connection._rollback_impl()
>   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 703, in _rollback_impl
>     self._handle_dbapi_exception(e, None, None, None, None)
>   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
>     exc_info
>   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
>     reraise(type(exception), exception, tb=exc_tb, cause=cause)
>   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 701, in _rollback_impl
>     self.engine.dialect.do_rollback(self.connection)
>   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 440, in do_rollback
>     dbapi_connection.rollback()
> ProgrammingError: (pysqlite2.dbapi2.ProgrammingError) SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 139707407021824 and this is thread id 139707213207296
> [2018-04-10 19:35:33,838] {/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py:591} INFO - Invalidate connection <pysqlite2.dbapi2.Connection object at 0x7f10265763b0> (reason: ProgrammingError:(pysqlite2.dbapi2.ProgrammingError) SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 139707407021824 and this is thread id 139707213207296)
> [2018-04-10 19:35:33,838] {/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py:297} DEBUG - Closing connection <pysqlite2.dbapi2.Connection object at 0x7f10265763b0>
> [2018-04-10 19:35:33,839] {/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py:303} ERROR - Exception closing connection <pysqlite2.dbapi2.Connection object at 0x7f10265763b0>
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 300, in _close_connection
>     self._dialect.do_close(connection)
>   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 446, in do_close
>     dbapi_connection.close()
> ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 139707407021824 and this is thread id 139707213207296
> [2018-04-10 19:35:33,839] {/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py:1232} INFO - Pool recreating

**Comment by OzzieIsaacs** [comment]
There is aproblem accessing the database (seems some dead thread is holding the database open). 
Could you please restart the whole device and try again.

**Comment by simkin** [comment]
Will retest as soon as a new version becomes available
