### ISSUE TITLE
French translation : replace check-box "Lire" by "Lu"

### ISSUE THREAD

**Issue by zoe12345** [janeczku/calibre-web#492]
All is in title, because in french, "Lire" (the book is NOT already read) and "Lu" (the book is already read) have opposite meanings, although the same word ("Read") is used in english.
To fix it :
please, replace check-box "Lire" by "Lu" in messages.po (line 1017)
I manually did it in my instance, but the check-box stayed as "Lire" (not replaced by "Lu").
Maybe, the replacement must be in another place…

**Comment by OzzieIsaacs** [comment]
It's the right place, but you have to "compile the file to get it used:
https://stackoverflow.com/questions/10863840/how-to-convert-gettext-mo-file-into-po-file
If updated the file, please try the latest commit

**Comment by zoe12345** [comment]
Thank you for your advice, it worked for me. How to tell the french translator about that ?
