### ISSUE TITLE
Book titles should be trimmed in UI

### ISSUE THREAD

**Issue by modembug** [janeczku/calibre-web#497]
![image](https://user-images.githubusercontent.com/1800289/38836259-578aa2b4-4182-11e8-8669-55afdb12ffa5.png)

![image](https://user-images.githubusercontent.com/1800289/38836280-64b68a5c-4182-11e8-9a19-86cbe18a003d.png)

**Comment by 0507spc** [comment]
This can be achieved by editing the calibre-web/cps/web.py

Line 412:

```
# custom jinja filters
@app.template_filter('shortentitle')
def shortentitle_filter(s):
    if len(s) > 60:
        s = s.split(':', 1)[0]
        if len(s) > 60:
            s = textwrap.wrap(s, 60, break_long_words=False)[0] + ' [...]'
    return s
```

if you change it to:

```
# custom jinja filters
@app.template_filter('shortentitle')
def shortentitle_filter(s):
    if len(s) > **20**:
        s = s.split(':', 1)[0]
        if len(s) > **20**:
            s = textwrap.wrap(s, **10**, break_long_words=**True**)[0] + ' [...]'
    return s
```

Alter the 20, 10 as appropriate. For your example, it looks like the meta data is wrong and a simple edit to put spaces in would resolve this, but, if the title is correct like that, then the above should help. There may be a config file to change this, I am new to this project and only just started using it.

**Comment by teflontoni** [comment]
All that is missing is some spaces. Calibre-Web handles long titles very well, but not if your title is as broken as in the screenshot.
