### ISSUE TITLE
Wont convert some special letters

### ISSUE THREAD

**Issue by Sblop** [janeczku/calibre-web#499]
First of all, great with a proper calibre that can run on my server. Thanks for this.

I read a lot of English books. When I send these to my kindly, no problem.
When I send a danish book it converts the danish special letters, (æÆ,øØ,åÅ) to gibberish when I use calibre web. When I send the same book from Calibre running on my computer it converts the file correctly.
I have tried with various language settings in the book metadata, but until now, to no avail.

Please assist, or guide me in right direction. Thanks in advance. 

Running Calibre-web on my qnap, via docker CLI.
Latest official version by: https://hub.docker.com/r/janeczku/calibre-web/
Commit:" Current commit timestamp: 4/13/18, 7:16 PM"

/Benjamin

**Comment by OzzieIsaacs** [comment]
So you have epub books and send them via calibre-web via email to your kindle, right?
calibre-web used kindlegan for conversion, so its a problem of kindlegen.  Changing the languages in the metadata has no effect on the conversion, as far as i know
Somebody created a fork to use calibre for conversion, but i think there is no docker of it

**Comment by OzzieIsaacs** [comment]
As this is not a problem of calibre-web I'll close the issue.
