### ISSUE TITLE
Possible to open field to chose where to open a ebook/pdf file when using iOS 

### ISSUE THREAD

**Issue by gelsas** [janeczku/calibre-web#503]
Is it Possible to open the dialog field of ios to chose where to open a ebook/pdf file when using iOS instead of opening pdfs directly in the browser?`

kind regards

**Comment by OzzieIsaacs** [comment]
Please push the download button, afterwards you can choose what to do (like in any other webapplication):
![img_1604](https://user-images.githubusercontent.com/6438895/39670817-117f426c-510d-11e8-9081-ccbc84d5dbdf.jpg)

**Comment by OzzieIsaacs** [comment]
No, this is how it is supposed to work
