### ISSUE TITLE
Syncing library with Nextcloud - possible? Best practices for syncing?

### ISSUE THREAD

**Issue by oakbrad** [janeczku/calibre-web#508]
I have my books and metadata.db shared between my server and home with Nextcloud. I would like to be able to edit my collection via the Calibre desktop app at home, and use calibre-web elsewhere, and have all these changes sync two ways.

When I make edits on either end I basically end up with the exact same problem as #337 - the permissions between the two get messed up and Nextcloud starts giving error/permission conflicts on the metadata.db file and it stops syncing.

Is it possible to sync this back and forth with Nextcloud? What is the easiest way to synchronize my local copy with a remote server two ways that isn't Google Drive?

**Comment by saitoh183** [comment]
Maybe use the same UID on both ends ? this way the permissions dont get messed up?

**Comment by bodybybuddha** [comment]
I used the same UID method for my workflow  - however, I use an NFS share that takes care of the remapping the UID.  

So I basically do an NFS share on my local machine to connect to my book collection, then I use calibre with its own version of metadata.db.  After doing whatever I need "locally", I would simply copy the metadata.db over the server one.  This works well as my users aren't updating the server version of the database (which calibre-web is using.)  

Which brings up a good point - I assume that you aren't making changes to the db at the same time?  I don't think sync'ing would work well there.

**Comment by OzzieIsaacs** [comment]
As nobody seems to have a better idea, I'll close this issue.
