### ISSUE TITLE
Add Language via UI

### ISSUE THREAD

**Issue by davydov-vyacheslav** [janeczku/calibre-web#509]
Is there a way to add new language via web ui? (to make it selectable in edit book / language select box) ?

If no, what are the possible ways to achieve that?

Thanks,
Slava

**Comment by OzzieIsaacs** [comment]
it‘s not possible. I remember I tried it during programming of the feature, and didn‘t succeed. Currently it’s only possible to add languages by attaching the languages to a book in Calibre itself. Afterwards the language is available in Calibre-web
