### ISSUE TITLE
ERROR installing: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by ltjdym** [janeczku/calibre-web#512]
Do I need to cd into a different directory? I'm installing in Linux Station in QNA.

**Comment by OzzieIsaacs** [comment]
Please double check:
- existence of requiremnts.txt file in the root folder of calibre-web
- that you are excecuting the pip command is this folder
- it's possible to read from requirements.txt with user which is excecuting the pip command

**Comment by ltjdym** [comment]
Ok so i have to download the zip file first?

**Comment by OzzieIsaacs** [comment]
Yes, please download the zip and extract it to the folder where you want to use calibre-web and than follow the instructions in the readme
