### ISSUE TITLE
OPDS updated date format invalid per Atom specification

### ISSUE THREAD

**Issue by elelay** [janeczku/calibre-web#513]
Date and time in the opds feed (e.g. `/books/opds/new`) is separated by a space instead of a `T`.
This is not valid according to the [Atom RFC](https://tools.ietf.org/html/rfc4287#section-3.3) :
> A Date construct is an element whose content MUST conform to the  "date-time" production in [RFC3339].  In addition, an uppercase "T"  character MUST be used to separate date and time, and an uppercase  "Z" character MUST be present in the absence of a numeric time zone offset.

**Comment by OzzieIsaacs** [comment]
Thanks

**Comment by elelay** [comment]
Cool, thanks!
