### ISSUE TITLE
Menu icon disappeared in Internet Explorer 11(in windows 7)

### ISSUE THREAD

**Issue by abubaman** [janeczku/calibre-web#515]
I use calibre-web in my synology nas and it works fine.
But when I access to my calibre-web with IE11(in windows 7) some menu icons are disappeared.
You can see this phenomenon like below. and I checked chrome is okay for that problem.(doesn't disappeared.)

I think this problem is because calibre-web use Ico, not jpg(or png) file to show icon in menu bar.
So i think it would be better that you change ico to picture format(like jpg, png), if it is available. 

![image](https://user-images.githubusercontent.com/27588851/40639195-979a8c36-634a-11e8-90b1-29dc25c04c91.png)

**Comment by abubaman** [comment]
Please see Hot books and Series.

**Comment by OzzieIsaacs** [comment]
I could reproduce the error, by redownloading the font files the error disappeared, please check newest commit.
