### ISSUE TITLE
发送这本书的时候出现错误: kindlegen失败，没有可执行权限

### ISSUE THREAD

**Issue by hongluoluo** [janeczku/calibre-web#516]
我是在群晖DSM6.1安装的，已经检查权限，kindlegen有这个运行权限， 每次想发送至亚马逊kindle账号，老是提示这个，不清楚是怎么回事， 之前用群晖dockcer安装可以使用，但是docker安装太不稳定了，关闭后，经常不能启动。所以直接git下载来安装的。

**Comment by OzzieIsaacs** [comment]
English please.
Please address problems regarding docker images to the provider of the docker image
