### ISSUE TITLE
Font is loaded via http, breaks (slightly) https only sites

### ISSUE THREAD

**Issue by perler** [janeczku/calibre-web#52]
Mixed Content: The page at 'https://site/book/1234' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Grand+Hotel'. This request has been blocked; the content must be served over HTTPS.

the font is available via https..

**Comment by OzzieIsaacs** [comment]
Should work now in my repro.

**Comment by perler** [comment]
thanks, looks good.

**Comment by cervinko** [comment]
#38 fixed this
