### ISSUE TITLE
Add option to convert with kindlegen without sending an email

### ISSUE THREAD

**Issue by xconverge** [janeczku/calibre-web#521]
There should be an option in a book if kindlegen is successfully linked AND only a non .mobi format is detected, to generate the mobi using kindlegen. I do not want to send an email and use the on-the-fly conversion, I would like to actively click something to generate the desired format (so that it can then be downloaded and manually copied to the device at a later time if desired)

Looks like a call to make_mobi() added as a button on the book would be perfect!

**Comment by xconverge** [comment]
Looking in the code, I have a workaround for now, kindlegen is run in send_to_kindle() as long as the SMTP server is NOT mail.example.com. The email will then fail but the conversion will have been done

I can change the server to some bogus value, then the send button acts as a "convert"

**Comment by OzzieIsaacs** [comment]
I will close the issue for now, as there is a workaround. I'm not sure about having every feature (or mass changes at most) implemented in calibre-web. From my point of view, this can be done better in calibre itself.
