### ISSUE TITLE
Feature Requests: Duplicate Detection

### ISSUE THREAD

**Issue by nickwinn** [janeczku/calibre-web#526]
Hi

Just wanted to throw this idea out there as a feature suggestion. Having Calibre Web detect duplicate uploads and blocking would be a nice feature. I've experienced this several times now, accidently upload a duplicated book, delete the duplicate which removes both the duplicate and the original. 

You could do duplicate checking via md5 or name collisions.

**Comment by OzzieIsaacs** [comment]
If books uploaded they are placed in the folder author/title. If nothing is changed additional books go to the same folder. Calibre stores books in the folder author/title(id).
