### ISSUE TITLE
Hide "send to kindle" button if no kindle address is set

### ISSUE THREAD

**Issue by perler** [janeczku/calibre-web#54]
if there is not kindle address set up for a user, the button should not be visible.

**Comment by cervinko** [comment]
for me this is how it works.
line 104-106 in detail.html
`           {% if g.user.kindle_mail %}
            <a href="{{url_for('send_to_kindle', book_id=entry.id)}}" id="sendbtn" class="btn btn-primary" role="button"><span class="glyphicon glyphicon-send"></span> Send to Kindle</a>
            {% endif %}`

**Comment by OzzieIsaacs** [comment]
But there is indeed one issue. If you have ever set a kindle password you can not delete it

**Comment by cervinko** [comment]
that's true

**Comment by cervinko** [comment]
should be fixed with 	commit 0f8c308.
can this issue be closed?
