### ISSUE TITLE
How to prevent guest page? 

### ISSUE THREAD

**Issue by n0valis** [janeczku/calibre-web#540]
If I visit calibre-web with a browser the first time without login it automatically shows the guest page with random books. How do I prevent that? Anonymous browsing is not activated.
It looks like that once you have logged in and out with an account the guest page won't show up again. But it shouldn't appear in the first place.

**Comment by OzzieIsaacs** [comment]
Please restart calibre-web (most important) and maybe clear your browser-cache. It should work afterwards. As I remember from investigating this in the past, it's some sort of caching issue, after disabeling anonymous browsing.

**Comment by n0valis** [comment]
I have had the problem again after clearing the cache. Without login the guest page shows up and gives access to the complete library although anonymous browsing is off.

**Comment by OzzieIsaacs** [comment]
For me its working. I assume you are on the newest commit and not using some docker container?

One issue I could think of would be some problems during settings database migration. 
Could you please try to enable anoymous browsing, save it, and than disable and save it again. After disabling in the admin overview section (where the users are listed bside other stuff) the user account "guest" should not be visible anymore. (You could try to delete the user Guest, which normally shouldn't be offered, but maybe for you, if it's still there).
If nothing helps, you could stop calibre-web, delete the app.db file (or better move/rename it) and start all over again with the configuration.

**Comment by n0valis** [comment]
right now there is no user guest in the users list.

**Comment by n0valis** [comment]
![snag00](https://user-images.githubusercontent.com/24315173/43023037-b4d27b54-8c69-11e8-9a95-1306ff0e1407.jpg)


but it appears when I call the front page

**Comment by OzzieIsaacs** [comment]
What happens if you press the logout button?

**Comment by n0valis** [comment]
then the login screen appears and the guest page won't show up again.
But I want to prevent the guest page showing up in the first place.

**Comment by OzzieIsaacs** [comment]
Could you please post the versions of the libs you are using (shown in the about section)?
So after you logged in as admin, and than log out everything works fine, it's just during the initial open of the website which cases problems?

**Comment by n0valis** [comment]
exactly.

![23-07-_2018_16-09-46](https://user-images.githubusercontent.com/24315173/43081884-f4757f10-8e92-11e8-85d3-26b80162ccd3.jpg)

**Comment by OzzieIsaacs** [comment]
I tried several configurations, and did some tests, I can‘t reproduce the issue

**Comment by n0valis** [comment]
ok, we leave it then. It's a minor thing anyway. Thanks for checking.

**Comment by greenapplepark** [comment]
Try this:
Settings -> Edit Basic Configuration -> Feature Configuration -> Uncheck "Enable Anonymous Browsing"
