### ISSUE TITLE
Timeout sending book to Kindle

### ISSUE THREAD

**Issue by captainepoch** [janeczku/calibre-web#546]
Hi, devs.

I got a timeout when I send a book to a Kindle. I got the kindlegen tool and it works, postfix sends mails (tested in the terminal), but Nginx got me a 499 code.

The errno I get from calibre-web is 10.

Should I post any config here?

**Comment by OzzieIsaacs** [comment]
Could you please try to send email from calibre without nginx in between to eliminate timeout issues of nginx. 
Are you using tornado, or gevent (on stats page 2nd option in dynamic link libraries)?
Could you please check the filesize of the file which is sent?
Could you please set calbre-web debug level to DEBUG and post the content on the moment of timeout?
One remark: Calibre-web is sending emails on its own to a server, and is not relying on some linux stuff for that. So if you are using postfix as targert server from calibre-web, everything is fine. 
If sending emails in general works from calibre-web can be check by pushing the "save and send test e-mail" button in the mail config section.

**Comment by captainepoch** [comment]
> Could you please try to send email from calibre without nginx in between to eliminate timeout issues of nginx.

It does not work.

> Are you using tornado, or gevent (on stats page 2nd option in dynamic link libraries)?

gevent, the one installed, I didn't choose it

> Could you please check the filesize of the file which is sent?

500KB or so

> Could you please set calbre-web debug level to DEBUG and post the content on the moment of timeout?

It does not generate any log :/

> One remark: Calibre-web is sending emails on its own to a server, and is not relying on some linux stuff for that. So if you are using postfix as targert server from calibre-web, everything is fine.
If sending emails in general works from calibre-web can be check by pushing the "save and send test e-mail" button in the mail config section.

Yeah, I know, but the whole point of using postfix is to not relay on any mail server.
