### ISSUE TITLE
[Enhancement]: Hide content based on categories for certain users

### ISSUE THREAD

**Issue by OzzieIsaacs** [janeczku/calibre-web#547]
Request from @ianc125 :
Ability to hide content based on categories for certain users
How is this done? I cant seem to find any options anywhere for this or info on how to do it.

**Comment by ramsnerm** [comment]
Do you have a plan when to implement this feature. I really seek for it because I am using the server to distribute my personal training materials and every user should only see their staff.

**Comment by OzzieIsaacs** [comment]
I‘m currently working on it

**Comment by jmriego** [comment]
I noticed that this is already possible by configuring it in the GUI and then opening the content server on the GUI itself. For some reason it doesn't work with `calibre-server`. Is there any current workaround for that?

**Comment by OzzieIsaacs** [comment]
The feature is now present, ypu can define custom columns content on user base for allowing and denying the access to books

**Comment by smitpau** [comment]
Similar to this would it be possible to have separate Calibre libraries per user. So in my case I'd like my Brother to use the server but would prefer it he has his own space in effect from mine so the books are not jumbled.

**Comment by smitpau** [comment]
Sorry just looked seems the best way is to create a separate Docker port for the DB, makes sense.
