### ISSUE TITLE
Download as PDF

### ISSUE THREAD

**Issue by dragonauta** [janeczku/calibre-web#55]
Hi, I have Calibre running on Debian Jessie (v.8.5).
Also installed calibre-web. I really enjoy it.

I was wondering how can I integrate "ebook-convert" tool (from Calibre) to allow downloading epub as PDF?
Thanks!

**Comment by cervinko** [comment]
you could look how calibre does it in the calibre source https://github.com/kovidgoyal/calibre
but for me this feature sounds like a lot of dependencies and i am not sure if we should implement every feature of calibre in calibre-web....

**Comment by dragonauta** [comment]
Thanks cervinko,
actually I was thinking in a wrapper instead a full implementation; to work as a vendor tool (like kindlegen).
If ebook-convert tool were available, this wrapper could just call that tool, make the conversion and return the PDF, allowing to download it.

I'll start looking how to add an option under "Download" button and make some testing.

**Comment by bodybybuddha** [comment]
Maybe the above can be expanded as an alternative or secondary (fall-back) method to convert Epubs when the kindlegen tool fails?   Kindelgen has been hit or miss with my pubs.

**Comment by OzzieIsaacs** [comment]
As there is no progress, I close this.
