### ISSUE TITLE
Download of book leads to login screen (Moonreader)

### ISSUE THREAD

**Issue by n0valis** [janeczku/calibre-web#553]
I have added calibre-web as netcatalog in Moonreader (Android). This works fine. After login all the books show up. But as soon as I try to download a book, it won't work. What I find is a file named 570.epub in the Moonreader dir which is actually the html file of the calibre-web login page.
I was, of course, logged in before, otherwise I wouldn't have seen the books in the first place.
'Reading in browser' works though.

I tried the calibre built-in webserver. That works fine. Books are downloaded correctly.

**Comment by OzzieIsaacs** [comment]
I've had time to set this szenario up with an android emulator.  I'm able to log in, covers are not shown (issue of moon reader known from the past. No login informations are send by moon reader). 
The unread and read section are not working (issue of moon reader, no login informations are send)
But I'm able to download the books (epub and pdf tested) as expected and the books are readable afterwards.
Which version of moon reader are you using.?

**Comment by n0valis** [comment]
I was on the latest version. 
But I have contacted the developer and he had a look on it and decided to fix it. I_ve already tested a beta where it works now. I think with the regular update in playstore that problem should be gone.
Thanks anyway for checking.

**Comment by OzzieIsaacs** [comment]
You‘re welcome. I close the issue, as there is nothing to do for me
