### ISSUE TITLE
Book Title Issue

### ISSUE THREAD

**Issue by mccorkled** [janeczku/calibre-web#556]
I have a book titled F*uck That's Delicious. It was imported into Calibre as F_ck That's Delicious. When I try to read the book via Calibre-Web the epub menu loads but the actual pages go not and I get an infinity loading loop. I imagine this is because of the special character. Can anyone confirm and is there a fix?

Thank you.

**Comment by OzzieIsaacs** [comment]
It's working for me. I think it's an issue with the book (the used library turned out to have a lots of unknown limitations). Could you please try renaming a different book to the title you named, doing the steps again?

**Comment by mccorkled** [comment]
The book opens fine outside of CW. I am using a build of Lazylibrarian with Calibre built in. I don’t actually have a stand alone Calibre that I can edit books with.

**Comment by OzzieIsaacs** [comment]
I was talking about renaming the file on the harddisk. It would be sufficient if you take a different epub file and replacing the book in question on the harddisk. But if it opens in other readers than it's pretty clear that it is a reader issue included in calibre-web. It's a free library we are using, so we can't do anything about it to make certain books work.

**Comment by mccorkled** [comment]
I replaced the book with another one and it is definitely an issue with the _ in the title. CW just keeps loading and loading the book.

**Comment by OzzieIsaacs** [comment]
Could you please check the javascript console, while it's loading, if/which error is showing on the console?
(e.g. Firefox: Extras -> Webdeveloper -> Web-console)

**Comment by OzzieIsaacs** [comment]
I doublechecked it's working for me, if I rename a book to the title you gave me. 
Could you please check if there are any relevant entries in the log file?

**Comment by mccorkled** [comment]
I do not see any errors here.
[Calibre-Web.html.zip](https://github.com/janeczku/calibre-web/files/2328499/Calibre-Web.html.zip)

**Comment by OzzieIsaacs** [comment]
To make progress in this issue, I need the book in question. Could you please send it to me via email (listed on my profile page)

**Comment by OzzieIsaacs** [comment]
Sorry for the late reply, I was busy with other projects. I could check the file. It's a valid epub file, viewable by Calibre. It's rather big with approx. 60MB, but this is not the problem. I could reproduce the issue, well sort of:
![bildschirmfoto vom 2018-10-30 20-02-37](https://user-images.githubusercontent.com/6438895/47743298-06552200-dc7f-11e8-99b0-d2868a7fd14a.png)
It's like I mentioned in this post (https://github.com/janeczku/calibre-web/issues/556#issuecomment-408613858), it's a issue with the contents of this special book. The epubjs library for displaying the book has approx. 185 issues, the reader another 15, we had at least 2 more issues related to the library. There was one other issue I could tear down to the book format, took me some time, I'm not going to do this again with this book. I'm sorry, as I mentioned above, I can not fix this

**Comment by mccorkled** [comment]
Thank you for trying.
