### ISSUE TITLE
How can i install calibre converter on Debian?

### ISSUE THREAD

**Issue by GBochicchio** [janeczku/calibre-web#557]

**Comment by OzzieIsaacs** [comment]
Calibre converter is a part of calibre itself. So just install calibre with:
`apt install calibre`
and the converter is installed. To get a more recent version of calibre, just follow the install guidelines on their webpage:
[https://calibre-ebook.com/download_linux](url)

**Comment by sirprancelot** [comment]
Once calibre is installed to find the location for ebook-converter (the part of calibre you are interested in) first type "ebook-convert" in terminal to make sure it is working, then type "whereis ebook-convert" to find where your converter is located.  Then use this for the basic configuration setup.  I simply needed to enter "/usr/bin/ebook-convert" on my raspberry pi for calibre e-book converter option.  Nothing else was needed.  Hope this helps. (Raspberry pi runs a version of Debian so it should be the same for you).

**Comment by rmzg** [comment]
Sorry to put this here, but where do you find the settings form to enter a value for ebook-convert? Is it it related to the kindlegen thing?

**Comment by OzzieIsaacs** [comment]
In admin section basic configuration: Fill out the form and hit the submit button:
![grafik](https://user-images.githubusercontent.com/6438895/43414909-6d2e5e76-9434-11e8-95cd-9282523412db.png)
