### ISSUE TITLE
Restart failed after recent update 

### ISSUE THREAD

**Issue by teflontoni** [janeczku/calibre-web#558]
Console output:
> [2018-07-28 15:31:32,557] ERROR in app: Exception on / [GET]
>Traceback (most recent call last):
>  File "/opt/weblibrary/vendor/flask/app.py", line 1982, in wsgi_app
>    response = self.full_dispatch_request()
>  File "/opt/weblibrary/vendor/flask/app.py", line 1614, in full_dispatch_request
>    rv = self.handle_user_exception(e)
>  File "/opt/weblibrary/vendor/flask/app.py", line 1517, in handle_user_exception
>    reraise(exc_type, exc_value, tb)
>  File "/opt/weblibrary/vendor/flask/app.py", line 1612, in full_dispatch_request
>    rv = self.dispatch_request()
>  File "/opt/weblibrary/vendor/flask/app.py", line 1598, in dispatch_request
>    return self.view_functions[rule.endpoint](**req.view_args)
>  File "/opt/weblibrary/cps/web.py", line 329, in decorated_view
>    return login_required(func)(*args, **kwargs)
>  File "/opt/weblibrary/vendor/flask_login/utils.py", line 228, in decorated_view
>    return func(*args, **kwargs)
>  File "/opt/weblibrary/cps/web.py", line 1049, in index
>    entries, random, pagination = fill_indexpage(page, db.Books, True, [db.Books.timestamp.desc()])
>  File "/opt/weblibrary/cps/web.py", line 496, in fill_indexpage
>    entries = db.session.query(database).join(*join,isouter=True).filter(db_filter)\
>  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 1721, in join
>    ','.join(kwargs.keys))
>TypeError
>ERROR:tornado.access:500 GET / (::1) 184.45ms

Web Output:

>Internal Server Error
>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Fully updated CentOS 7 changed nothing recently (I am aware off)

Any pointers?

**Comment by OzzieIsaacs** [comment]
Could you please check the SQLalchemy version you have installed. You need at least Version 1.1 (I forgot to update the requirements file

**Comment by teflontoni** [comment]
Ok, as I have no clue how to check version (it was probably still 0.84) I did
`pip install --upgrade --target vendor -r requirements.txt
`
It's still not working though:

>[2018-07-28 17:29:29,931] INFO in web: Starting Calibre Web...
>[2018-07-28 17:29:30,070] INFO in server: Starting Tornado server
>[2018-07-28 17:29:34,837] ERROR in app: Exception on / [GET]
>Traceback (most recent call last):
>  File "/opt/weblibrary/vendor/flask/app.py", line 2292, in wsgi_app
>    response = self.full_dispatch_request()
>  File "/opt/weblibrary/vendor/flask/app.py", line 1815, in full_dispatch_request
>    rv = self.handle_user_exception(e)
>  File "/opt/weblibrary/vendor/flask/app.py", line 1718, in handle_user_exception
>    reraise(exc_type, exc_value, tb)
>  File "/opt/weblibrary/vendor/flask/app.py", line 1813, in full_dispatch_request
>    rv = self.dispatch_request()
>  File "/opt/weblibrary/vendor/flask/app.py", line 1799, in dispatch_request
>    return self.view_functions[rule.endpoint](**req.view_args)
>  File "/opt/weblibrary/cps/web.py", line 329, in decorated_view
>    return login_required(func)(*args, **kwargs)
>  File "/opt/weblibrary/vendor/flask_login/utils.py", line 261, in decorated_view
>    return func(*args, **kwargs)
>  File "/opt/weblibrary/cps/web.py", line 1049, in index
>    entries, random, pagination = fill_indexpage(page, db.Books, True, [db.Books.timestamp.desc()])
>  File "/opt/weblibrary/cps/web.py", line 496, in fill_indexpage
>    entries = db.session.query(database).join(*join,isouter=True).filter(db_filter)\
>  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 1721, in join
>    ','.join(kwargs.keys))
>TypeError
>ERROR:flask.app:Exception on / [GET]
>Traceback (most recent call last):
>  File "/opt/weblibrary/vendor/flask/app.py", line 2292, in wsgi_app
>    response = self.full_dispatch_request()
>  File "/opt/weblibrary/vendor/flask/app.py", line 1815, in full_dispatch_request
>    rv = self.handle_user_exception(e)
>  File "/opt/weblibrary/vendor/flask/app.py", line 1718, in handle_user_exception
>    reraise(exc_type, exc_value, tb)
>  File "/opt/weblibrary/vendor/flask/app.py", line 1813, in full_dispatch_request
>    rv = self.dispatch_request()
>  File "/opt/weblibrary/vendor/flask/app.py", line 1799, in dispatch_request
>    return self.view_functions[rule.endpoint](**req.view_args)
>  File "/opt/weblibrary/cps/web.py", line 329, in decorated_view
>    return login_required(func)(*args, **kwargs)
>  File "/opt/weblibrary/vendor/flask_login/utils.py", line 261, in decorated_view
>    return func(*args, **kwargs)
>  File "/opt/weblibrary/cps/web.py", line 1049, in index
>    entries, random, pagination = fill_indexpage(page, db.Books, True, [db.Books.timestamp.desc()])
>  File "/opt/weblibrary/cps/web.py", line 496, in fill_indexpage
>    entries = db.session.query(database).join(*join,isouter=True).filter(db_filter)\
>  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 1721, in join
>    ','.join(kwargs.keys))
>TypeError
>ERROR:tornado.access:500 GET / (::1) 201.23ms

It seems the wrong path for sqlalchemy is choosen, or am i reading something wrong?

**Comment by OzzieIsaacs** [comment]
To make sure the version is really correct, could you please start a python console (by typing python)
and then enter:
`from sqlalchemy import __version__ as sqlalchemyVersion`
`print (sqlalchemyVersion)`
It should then print the version.
I changed the database request for fullfilling the request group the list by series. A databasetable join is needed, to me it looks like somehow the join is crashing (what it does not on my 3 computers)

**Comment by OzzieIsaacs** [comment]
And yes, it picks the sqlalchemy from the system.
In this case 
pip install sqlalchemy==1.1.0

should do the job

**Comment by teflontoni** [comment]
And the library is back in business :)

Thx for helping me out, I installed sqlalchemy with the command in your last comment. And now it's up and running.
