### ISSUE TITLE
[Suggestion]: Filter by star rating & Authors by Letter & List view

### ISSUE THREAD

**Issue by sirprancelot** [janeczku/calibre-web#559]
I know you guys are seriously busy and probably have more pressing matters but I wanted to flag this as an absolute future consideration.  I've only just started using calibre-web but this has the potential to become something very large.  It's absolutely great and potentially, when mixed with calibre tagging, the plex of books... no joke and I am sure others have already said.  Can't believe I stumbled over this project sort of inadvertantly... it should have been in my face on google in terms of finding a decent ebook server solution.  Running on a Pi 3 it's pretty much perfection (although a bit slow with conversion but that's a Pi issue).  The things that I miss most currently are filtering options.  The tag filtering is fantastic.  What I would love to see is a list view option to go with book cover option (if viewing on mobile devices this is a must), having the authors with option to view by alphabet (I like how it currently is but with lots of authors these lists run the risk of becoming v v long and unweildy), and finally filtering by star rating (I spent ages rating my ebooks and I would love to be able to filter for tag & star).  I hope you guys continue developing this.  If you do I wouldn't be surprised if this get's more mass traction.  Just needs in short term some better documentation (noddy proof ones) and ideally long-term, a simpler install system so larger numbers can get to experience this and it's not just techi minded + linux people who have the pleasure.  Just my 2 cents but no worries if you have more important things to do!!

**Comment by OzzieIsaacs** [comment]
See also #72

**Comment by OzzieIsaacs** [comment]
Filtering for starting letter and category ratings are implemented in newest commit
