### ISSUE TITLE
[Suggestion]: Linking with goodreads read/reading status

### ISSUE THREAD

**Issue by sirprancelot** [janeczku/calibre-web#560]
On iOS and Android Kindle versions you can currently mark a book as being read or having been finished which can then be fed back to goodreads... Having calibre-web read this information from goodreads would be super cool and closer to plex tracking.  Not sure if goodreads has an api or such to allow for tracking this but if it does it might be a good one for the wishlist featureset.  To be honest even if calibre-web only allows for manual entry of "reading" with potentially also a page number/chapter reached that would be kind of attractive as well. 
 Just my 2 cents.

**Comment by 8bitgentleman** [comment]
Similar to this it'd be awesome to have calibre-web look at your To-Read bookshelf on Goodreads, check calibre to see if you have any of the books on that book shelf, then automatically create a bookshelf in calibre web that has all of your to-read books on it in the same order as Goodreads

**Comment by GreenTeaBalls** [comment]
The only reason I still use the Calibre desktop application - alongside calibre-web - is this feature. The desktop application has a goodreads sync plugin. Having this in calibre-web would be totally awesome!

**Comment by jef** [comment]
Also fetching metadata would be nice.

**Comment by claym** [comment]
I'd love this functionality. It's the only reason I'm not using calibre-web, I really like the Goodreads integration :D

**Comment by armouredking** [comment]
With the Goodreads API being deprecated, I think you'd probably have to move to [OpenLibrary](https://openlibrary.org/) or [LibraryThing](https://www.librarything.com/)

**Comment by OzzieIsaacs** [comment]
@armouredking : I thought a while over your suggestion and came to the conclusion, that it would be easier for me and my hobby to stay on "my island" and not integrate a new api

**Comment by sanbroz** [comment]
I agree with you to not using any third party APIs. But I suggest to add author pic and bio in caliber-web

**Comment by Jerome2103** [comment]
> @armouredking : I thought a while over your suggestion and came to the conclusion, that it would be easier for me and my hobby to stay on "my island" and not integrate a new api

But it would be nice if you could at least maintain the data manually.
