### ISSUE TITLE
Series ID field in Edit Metadata should allow decimal values

### ISSUE THREAD

**Issue by rmzg** [janeczku/calibre-web#562]
e.g. 5.5 should be a valid entry for the "Series id" field.

**Comment by rmzg** [comment]
A) Because calibre itself supports it
B) How else do you mark novellas/short stories in between two full length novels?

**Comment by sirprancelot** [comment]
it's true.. I have quite a few series that have a decimals in the series.  Goodreads quite often marks series like this.  For e.g. https://www.goodreads.com/series/59393-jack-nightingale

**Comment by OzzieIsaacs** [comment]
Editor now allows entering decimal values
