### ISSUE TITLE
Is there an access log file ?

### ISSUE THREAD

**Issue by n0valis** [janeczku/calibre-web#564]
I can't find the access log file of Calibre Web. Only found calibre-web.log but that's  not an access logfile.
Can you please tell me where the actual access logfile is located?
Thanks.

**Comment by OzzieIsaacs** [comment]
Currently there is no access log (If you are using gevent it gives you the output on the console, I think stdout)
So the call would be:
python cps.py >>access.log

**Comment by n0valis** [comment]
thanks, that helps.
