### ISSUE TITLE
Send Mail Queue blocked after first task

### ISSUE THREAD

**Issue by Ribero** [janeczku/calibre-web#565]
The new send email in background feature seems to encounter some difficulties.
The first time a user select "send to kindle" the email is correctly sent and its status correctly displayed on the Task status screen.

If user tries to send another book, the task is blocked in the queue with "progress 0%". It will stay with this status for ever. No other book can be sent until a calibre-web restart.

Using version : 31/07/2018 18:19
Running on : Docker technosoft2000/calibre-web
Attachements : Docker Log + Screenshot

<img width="1173" alt="task_list_queue" src="https://user-images.githubusercontent.com/2266264/43505166-58b0c82a-9566-11e8-9f4a-1e161a96c901.png">

[Calibre-Web-log.log](https://github.com/janeczku/calibre-web/files/2248358/Calibre-Web-log.log)

**Comment by OzzieIsaacs** [comment]
Please try newest commit

**Comment by Ribero** [comment]
Yes, it works. 

Thanks
