### ISSUE TITLE
[Proposal] Swap Wand for Pillow for image handling

### ISSUE THREAD

**Issue by PPACI** [janeczku/calibre-web#567]
Hi everyone.
One of the biggest step in dockerfile for calibre-web is handling ImageMagick : https://hub.docker.com/r/technosoft2000/calibre-web/~/dockerfile/

And since ImageMagick is required only for 'Wand' (IM binding library) to work, I propose to remove Wand and use Pillow. It's a very mature and production ready Python Imaging Library.
I've worked for multiple years with Pillow and I could handle the refactoring.

So, would it be ok for you if I do a PR in future to implement this ticket ?

**Comment by PPACI** [comment]
Meanwhile, you can use my own fork [PPACI/calibre-web](https://github.com/PPACI/calibre-web)

It also include a Dockerfile which is initializing an empty Calibre library

**Comment by OzzieIsaacs** [comment]
Yes, it would be okay to drap wand. If you create a pull request I'll merge it. (I have to think on the incompability it causes)

**Comment by OzzieIsaacs** [comment]
I close the issue, if you have the PR ready I'll check it and merge it afterwards

**Comment by OzzieIsaacs** [comment]
Pillow can only write images to pdf format, but not read pdf. You still rely on ImageMagick, there is no benefit in using PIL or Pillow
