### ISSUE TITLE
Error reading books metadata

### ISSUE THREAD

**Issue by indeec05** [janeczku/calibre-web#568]
I have fresh installation of CW. And trying to upload few test books. And the error I recieving is:

`WARNING - cannot parse metadata, using default: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)`

Example of book: https://dropmefiles.com/kxw3u
The book is in a Russian language.

**Comment by OzzieIsaacs** [comment]
Please update, should work now

**Comment by indeec05** [comment]
Yes, that works! Thanks!
