### ISSUE TITLE
Feature : Mark as Read By User

### ISSUE THREAD

**Issue by wilsto** [janeczku/calibre-web#57]
Thanks for this development, it's awesome.
Is there a way or what is the best way to easely implement "mark read/not read" by user ?

**Comment by OzzieIsaacs** [comment]
If I understand you right you want to mark eg: User 1 has read book 1,2,3 and User 2 has read book 3,4,5.
You may could do this by creating a non public-bookshelf and add the corresponding books to it.

**Comment by wilsto** [comment]
Thanks for the answer, I'll try that way.
