### ISSUE TITLE
"SyntaxError: from __future__ imports must occur at the beginning of the file" in asyncmail.py

### ISSUE THREAD

**Issue by wolffstarr** [janeczku/calibre-web#571]
I'm getting this issue after trying to restart my install. I'm using @Technosoft2000's docker container, which is doing a git pull at the beginning, and it's failing to start. After attempting to launch, the following traceback comes up:

`[INFO] Launching Calibre-Web ...
Traceback (most recent call last):
  File "/calibre-web/app/cps.py", line 13, in <module>
    from cps.server import Server
  File "/calibre-web/app/cps/server.py", line 20, in <module>
    import web
  File "/calibre-web/app/cps/web.py", line 37, in <module>
    import helper
  File "/calibre-web/app/cps/helper.py", line 16, in <module>
    import asyncmail
  File "/calibre-web/app/cps/asyncmail.py", line 47
    from __future__ import print_function
SyntaxError: from __future__ imports must occur at the beginning of the file`

After that the container exits. 

For reference, the system that the container is running on is Debian Stretch; please let me know if there's anything else you need from me.

**Comment by mismamente** [comment]
Me too. I have this same problema after reinstall today

**Comment by YesThatRancourt** [comment]
Thirded. Having this exact problem, running on Ubuntu 18.04.

**Comment by gorgobacka** [comment]
Sorry, that was my fault. I never user _future_ imports before to ensure Python 2 and 3 compatibility and thought that they work like normal imports.

The line `from __future__ import print_function` should be the first import in the file.

**Comment by OzzieIsaacs** [comment]
It's now working again. I'm very sorry.
To make it run again you have to exchange the file asyncmail.py in the cps folder, or you have to force the container to make a new git pull.

**Comment by wolffstarr** [comment]
Thanks guys, no worries. Confirmed that the @Technosoft2000 container is now functioning again. It appears either it's designed to auto-update on run, or I managed to accidentally configure it that way, but either way works for me. I'm just glad to have it back, I was getting fidgety without the easy access to the books. :)

**Comment by Technosoft2000** [comment]
@wolffstarr 

>  It appears either it's designed to auto-update on run

Correct, at startup of the container a `git pull` is done and due this calibre-web gets updated.
The same happens of course when the container gets restarted.

@gorgobacka 

did you'r version run locally on your PC with the **from ... import ...** in the middle of the code?
I really wonder because at https://www.python.org/dev/peps/pep-0008/#imports they describe the following "Imports are always put at the top of the file".

**Comment by gorgobacka** [comment]
@Technosoft2000 
I thought that I tested it locally, before releasing the PR.
