### ISSUE TITLE
Unable to send ssl encrypted email 

### ISSUE THREAD

**Issue by ToasterFaerie** [janeczku/calibre-web#574]
I set my "send to kindle" email as my normal email for testing purposes and I tried setting up email with GMail SMTP server settings (i.e. smtp.gmail.com/465/SSL/GMail username and password). When I select save and send test, I get the notification that the test email was sent successfully. However I get this error in the console:

```
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
self.run()
File "/opt/calibre-web/cps/worker.py", line 167, in run
self.send_raw_email()
File "/opt/calibre-web/cps/worker.py", line 444, in send_raw_email
self.asyncSMTP = email_SSL(obj['settings']["mail_server"], obj['settings']["mail_port"], timeout)
File "/opt/calibre-web/cps/worker.py", line 142, in __init__
smtplib.SMTP_SSL.__init__(self, *args, **kwargs)
TypeError: unbound method __init__() must be called with SMTP_SSL instance as first argument (got email_SSL instance instead)
```

No email gets sent, and in the task list I can see that "Test E-Mail" task has started but never finishes. I tried sending a mobi file from the main library and get the same error.

Thanks for any help.

**Comment by OzzieIsaacs** [comment]
I could not reproduce your error message, but found some bug in sending email with SSL. Could you please update to the last commit and try again

**Comment by ToasterFaerie** [comment]
Thanks! I tried updating.

I don't see the exception error anymore. I still see the message that sending was successful, but in tasks I see the "Test Email" task failed. I'm also seeing this error now: "ERROR:flask.app:Connection unexpectedly closed".

It's possible at this point that there's something I haven't configured correctly for Google's smtp server, but it's difficult for me to troubleshoot because of the conflicting feedback from trying the test email.

Let me know if there is anything else I can test.

**Comment by OzzieIsaacs** [comment]
Could you please check the logfile for any relevant content?
Could you please set the loglevel to debug (admin -> basic config -> logfile), restart Calibre web, send the test email again and paste the output ( the sql rom stuff is irrelevant, there should be something like ‚200 elho‘...

**Comment by OzzieIsaacs** [comment]
I could reproduce the problem on linux

**Comment by ToasterFaerie** [comment]
Here's the log:

[calibre-web.log](https://github.com/janeczku/calibre-web/files/2284669/calibre-web.log)

**Comment by OzzieIsaacs** [comment]
It should work now (also on Linux), please update to the newest commit

**Comment by ToasterFaerie** [comment]
It works now! Thanks!
