### ISSUE TITLE
Invalid OPDS feed

### ISSUE THREAD

**Issue by lmorel3** [janeczku/calibre-web#579]
Hello, and thanks for this awesome app!

Perhaps, I'm facing an issue with _Koreader_ and the OPDS feed provided by _Calibre-Web_. My feed is accessible, and I'm also able to browse others OPDS feeds through Koreader. 

The issue is that the feed generated by Calibre-web is invalid regarding the OPDS specification. You [can have a try with this validator](http://opds-validator.appspot.com/). That's why - I think - Koreader gives me an error message, like: "can't get OPDS feed info".

As an example, [this feed](http://cops-demo.slucas.fr/feed.php) is valid and works. 

In my opinion, it doesn't require a lot of changes ;)

Best regards

**Comment by OzzieIsaacs** [comment]
I improved the compability, the last issue the validator is complaining about is a element the original Calibre server has also, so I think this should not cause a problem. Please try if your problem is solved

**Comment by lmorel3** [comment]
Thanks for the fix. Perhaps, I think the issue was related to the way Koreader handles SSL, because the whole traffic of my private server is served through https. Also, I was able to browse the feed without SSL.

But anyway, I think it's a good idea to respect the standard. I close the issue ;)
