### ISSUE TITLE
500 Internal Server Error - xxx.xxx.x.xxx:8083/admin/view

### ISSUE THREAD

**Issue by actiller** [janeczku/calibre-web#580]
After last update Aug 18 I have been unable to access the Admin home page (xxx.xxx.x.xxx:8083/admin/view, according to hover and webpage). I receive this error 

"Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."

I have done a clean install and this has not resolved the error.  all other hyperlinks appear to work.  Can you advise what I can do to resolve. I have attached the log files.

[calibre-web.log](https://github.com/janeczku/calibre-web/files/2300016/calibre-web.log)

OS: Ubuntu 18.04
No reverse proxy
Flask  v1.0.2
Babel v2.6.0
Flask Login v0.4.1
Flask Principal v0.4.0
Pyton 2.7

**Comment by OzzieIsaacs** [comment]
It looks like something went wrong during update, or coping files. The first error in the log is complaining about a non existing variable in web.py (line 599), but in the last version this line IOC code is a totally different one. after restart this error was gone, so I think the file was replaced with the current one.  The next error is complaint about a  lines in admin.html:
`File "/opt/calibre-web/cps/templates/admin.html", line 537, in template
    <td id="LC1" class="blob-code blob-code-inner js-file-line">{% extends &quot;layout.html&quot; %}</td>`
But admin.html has not 537 lines, and this text isn‘t existing in any template. Could you please check the contents of the file /opt/Calibre-web/cps/templates/admin.html and compare it with the content of the file online. If they are different, please exchange the file with the right one and restart. Maybe other files are also not the correct one, than you should please copy all the files again. Hope this helps

**Comment by actiller** [comment]
Thanks,  I did a complete delete and reinstall and that resolved the issue until I changed the Feature configurations Enable public registration check box to enabled.  I get the message that is it saved successfully. but after that if I attempt to access the admin/view page after that I get the Internal server error again.  if I remove the check box by navigating to http://XXX.XXX.X.XXX:8083/admin/config directly. I can again access the admin/view page.

**Comment by OzzieIsaacs** [comment]
Has nothing to do with the error before, I accidentially commited something, which should committed yet. Please update to the newest commit (decativate public registration, press search for update on admin/view page). It should work than

**Comment by actiller** [comment]
Works perfectly thank you.
