### ISSUE TITLE
Task List...What is it for and how do we use it?

### ISSUE THREAD

**Issue by saitoh183** [janeczku/calibre-web#581]
![image](https://user-images.githubusercontent.com/1534197/44431988-350f9780-a56e-11e8-9581-4d978fda6982.png)

**Comment by bodybybuddha** [comment]
When a person send a book to their Kindle, an entry will appear here.  The Admin roles can see all the tasks, while individual's can only see their own.  Also, if a book is being converted to Mobi, it will show up here.  The list will reset if you restart the service.

Pretty good feature to have in case there are further developments that require "long running" processes.

**Comment by saitoh183** [comment]
@bodybybuddha 

Thanks :)
