### ISSUE TITLE
Feature Request : RSS Feed for newly added eBooks

### ISSUE THREAD

**Issue by Ribero** [janeczku/calibre-web#582]
Hi,

It would be nice to have a RSS Feed implemented in Calibre Web that points to the content of newly added ebook (Recent Category). 
It should probably manage an authentication mechanism or another feature to allow RSS Feed to be read by the RSS client from a Calibre-Web instance that do not provide Anonymous access.

**Comment by bodybybuddha** [comment]
You could point your RSS reader to http(s)://<site>/opds/new.  This should get what you're looking for.
Security is already tied in.

Or were you looking for a specific route (/rss)?  In which case @OzzieIsaacs would need to chime in on.

**Comment by OzzieIsaacs** [comment]
I agree with @bodybybuddha, we have the opds feed for new books, a rss feed qould be beyond the scope of a online visualisation of a calibre database, so I'm not implementing it.
