### ISSUE TITLE
Clear login  cache?

### ISSUE THREAD

**Issue by jiangjiangflies** [janeczku/calibre-web#588]
I think there is a serious bug in users system.
If I change a user's password, he can still  browse the contents with browser's automatic login. 
If I delete this user and then add a new username and a password, he can even login automatically  with new username displayed on the page. That's terrible! 
How to resolve this issue? It's really a big loophole.

**Comment by OzzieIsaacs** [comment]
I can't reproduce the issue:
Log in on computer 1 as admin, create new user
Log in on tablet as new user, remember me ticked, close tab
On computer 1 as admin, delete new user
Open tab on tablet, user is logged out, try to log in as "new user" login rejected?

Could you please tell me step by step what you did? 
Are you using docker? 
Which operating systems and browsers are you using?

**Comment by jiangjiangflies** [comment]
After you **delete** the new user on your computer, **don't** refresh your browser on your tablet. 
Then create another new user (in the same row of the deleted user). After this new user is created,which has filled the position of the deleted user, refresh your tablet browser, you may find you are logged in automatically with new user name! 
Plus, the new user has the same data like the number of downloads as the deleted user. It seems that the new added user shares the same database with deleted user in the same row.

**Comment by OzzieIsaacs** [comment]
Problem is that the new user gets same id than the deleted user. 
Flask login suggests using alternative tokes for identification https://flask-login.readthedocs.io/en/latest/#alternative-tokens
Another option would be creating user ids based on creation time of user (no 2 users would get the same id)

**Comment by OzzieIsaacs** [comment]
Option 1 has the additional advance the user session automatically is ceased upon password change.

**Comment by OzzieIsaacs** [comment]
The latest fix should solve the issue.
