### ISSUE TITLE
Error: Calibre Database Directory <DB_ROOT> is not configured

### ISSUE THREAD

**Issue by saysongkham** [janeczku/calibre-web#59]
Hi
i try to use this calibre-web,
i download it and unzip it to C:\calibre-web-master
I  did rename and change the config file
[General]
DB_ROOT = C:\Users\S\Documents\Calibre Library
APP_DB_ROOT =
MAIN_DIR =
LOG_DIR =
PORT = 8083
NEWEST_BOOKS = 60
[Advanced]
TITLE_REGEX = ^(A|The|An|Der|Die|Das|Den|Ein|Eine|Einen|Dem|Des|Einem|Eines)\s+
DEVELOPMENT = 0
PUBLIC_REG = 0
UPLOADING = 0
ANON_BROWSE = 0

when i run cps.py 
C:\Python27>Python C:\calibre-web-master\cps.py
i got an error "Calibre Database Directory <DB_ROOT> is not configured"

what can it put DB_ROOT = C:\Users\S\Documents\Calibre Library
or i need to add any thing 
please help

**Comment by OzzieIsaacs** [comment]
Are you using the current version? A month ago we solved an issue with calling from diffrent paths.
Have you tried to change the directory to c:\calibre-Web-master and than call cps.py without the path?
Maybe there is a file permissions problem. Could you please try to move the Library ( or generate a new test Library with calibre) on a Location Outside the Users folder?

**Comment by saysongkham** [comment]
Thank you, it s working now. i just download the new version and try with both library within User folder and on C:\Test . it works well Thank you
