### ISSUE TITLE
Languages options are missing in upload form

### ISSUE THREAD

**Issue by arky** [janeczku/calibre-web#593]
## Expected behavior and actual behavior.
There must be a way for teachers to edit and/or save an e-book's language using Calibre-Web — but the UX is highly non-intuitive if so?

## Steps to reproduce the problem.
log into http://box/books using Admin/changeme
click "UPLOAD" on the top of the page; add a PDF book or similar
enter "English" or "EN" etc into the "Language" textfield
click Submit button
use Calibre-Web to browse to the newly uploaded book
click "Edit metadata"
sadly the "Language" field is completely blank...

## Downstream bug
https://github.com/iiab/iiab/issues/1040

**Comment by OzzieIsaacs** [comment]
There is a known limitiation (to me known). If you want to set the language you have to have at least one book in your calibre library with that language to make this work. So please open calibre with the database you want to use and add a language you want to use to one of the exisiting books. Afterwards you should be able to add further books in Calibre-Web with this language.
Background: Calibre stores the languages in a seperate table in the database with a 3-letter language code (like FRA for french). In calibre-web you can (only) enter the language in the UI-translated form (like francais for french). To find the corresponding 3 lettercode you have to translate the language name back to english and map it to the 3-letter code. I searched for a programming library, which could do that, but I failed, so we have this limitation now...
So if you want to enter a english book language in a e.g. french UI you have to enter Anglais, after typing one or 2 letters, Calibre-web helps you and offers (if the language is existing in the database) Anglais as possible language.

**Comment by arky** [comment]
Thanks @OzzieIsaacs for shedding light on this issue. Much appreciated.  

Perhaps a good UX experience would be to have a dropdown option of languages. This could be implemented using CSS or Jquery selector with list of languages. This could enhance the user experience?

Am no expert on these localization(l10n) issues, but if Calibre is using [standard CLDR language codes](http://www.unicode.org/cldr/charts/latest/supplemental/territory_language_information.html) then some library [babel](http://babel.pocoo.org/en/latest/locale.html) could work.

**Comment by holta** [comment]
Thanks @OzzieIsaacs and @arky for the explanation.

This is a very serious bug in developing countries where I help distribute Internet-in-a-Box, as new/indigenous language e-books & PDF's appear from teachers AFTER deployment, so it is not possible to "prime the pump" adding a book from each such language a priori.

I agree with @arky that a pull-down would be far better, even it just contained the 3-letter codes for each language, without further explanation.  _(For better than teachers assuming Calibre-Web is broken, which is their reaction today!)_

**Comment by holta** [comment]
Huge thanks @OzzieIsaacs for laying out this critical challenge!

Let's try for a partial solution in coming months, even if a teacher-friendly solution with all ~7000 languages might have to wait for 2019 _(and a child-friendly solution with all ~7000 languages might have to wait for 2020 ;)_

cc: @mapmeld who might also have ideas?

**Comment by OzzieIsaacs** [comment]
I could shrink the list of valid languages to roughly 400. Because a book an have more than one language a dropdownlist is not my first choise. Now you get typeahead hints for every valid language. For non translated lnaguage names you get the english name of the language:
![grafik](https://user-images.githubusercontent.com/6438895/45266582-4953ff80-b45d-11e8-94b8-a9aa7f4d23a5.png)
If the texts are translated you get hints in the UI language:
![grafik](https://user-images.githubusercontent.com/6438895/45266589-79030780-b45d-11e8-9680-078e03521723.png)
Hints starting with the character sequence are priorized. If there are less than 5 languages starting with the character sequence the list is filled with languages having the sequence somewhere in the name. Languages are seperated from each other with a ',' like tags.

**Comment by OzzieIsaacs** [comment]
And: If you are entering an invalid language name calibre-web will now tell you that it thinks the language is invalid
