### ISSUE TITLE
Change Password does not seem to work

### ISSUE THREAD

**Issue by sbelongie** [janeczku/calibre-web#6]
When changing a password for a user it does not seem to change.

**Comment by cervinko** [comment]
there is a typo in web.py in the edit_user function.
it should be `content.password = generate_password_hash(to_save["password"])` instead of `content.password == generate_password_hash(to_save["password"])`
fixed in latest commit for #5

**Comment by janeczku** [comment]
Thanks @sbelongie for reporting and @cervinko for fixing the issue!

**Comment by sbelongie** [comment]
Thank you.  I tested and this is resolved.
