### ISSUE TITLE
Multiple authors are treated as one

### ISSUE THREAD

**Issue by vigri** [janeczku/calibre-web#603]
Another problem I would like to report (sorry for that ;) )

When added multiple authors to a book calibre-web treats them as one author.
Input while editing the metadate of a book: Author1, Author2

This new author "Author1, Author2" even gets his own id which can later be browsed by `<URL>/author/<ID>.`

HTML code when viewing a book:
```
<p class="author">
  <a href="/author/7">Author1, Author2</a>
</p>
```

**Comment by OzzieIsaacs** [comment]
The separation character for authors is the &. Some users use „surname, firstname“ for there authors. Calibre is using also the & for splitting the names.

**Comment by vigri** [comment]
Thanks for clarification. This "issue" can be closed then.
