### ISSUE TITLE
"Add to shelf" should not be shown when no search result is found

### ISSUE THREAD

**Issue by vigri** [janeczku/calibre-web#604]
A little thing I discovered.

How to reproduce:

1. Create a shelf
2. Enter a search term which will return 0 books.

On the result page you'll see the "Add to shelf" button. Clicking on the button will obviously fail.

**Comment by vigri** [comment]
The button is now correctly shown. However there seems to still be a problem.
When you click the button it will always return "Could not add books to shelf: XYZ". There is no log entry.

It seems, that this condition fails 

`if current_user.id in ub.searched_ids and ub.searched_ids[current_user.id]`

which causes the error.

**Comment by OzzieIsaacs** [comment]
The results haven't been saved for a normal search, only for the advanced search. It's fixed now.

Thanks for the help
