### ISSUE TITLE
Which call is the "Check for updates" function making? (url:port)

### ISSUE THREAD

**Issue by simkin** [janeczku/calibre-web#608]
Reason I ask is that I have a very restrictive firewall that also blocks some outgoing traffic and I noticed that the UI hangs when I check for updates.

**Comment by OzzieIsaacs** [comment]
It's making a call to the github api:
https://api.github.com/repos/janeczku/calibre-web/git/refs/heads/master
https://api.github.com/repos/janeczku/calibre-web/git/commits/  +commithash of latest commit
an if your are updating it's requesting:
https://api.github.com/repos/janeczku/calibre-web/zipball/master
(If there are any errors in the logfile, I can take a look at it catch the errors and maybe "fail faster")
