### ISSUE TITLE
synchronization?

### ISSUE THREAD

**Issue by ak1n** [janeczku/calibre-web#612]
Does calibre-web allow any means to synchronize books' current page location between devices (by any method)? Apologies if I missed this from related informational pages. Thanks!

**Comment by OzzieIsaacs** [comment]
Are you refering to the internal reader? epub or comics?

Something related to Kindle features? -> No

**Comment by ak1n** [comment]
Re any method - including epub. Epub did not seem to sync... Apologies for response delay and thanks for your reply.
