### ISSUE TITLE
Current commit timestamp: Unknown in docker container

### ISSUE THREAD

**Issue by kianrafiee** [janeczku/calibre-web#613]
Did anyone else notice this? When checking for updates, it does confirm the latest version but it still doesn't reflect that on "Current commit".

Not sure of a way to get logs for this, nothing shows even with log level debug.

**Comment by kianrafiee** [comment]
This isn't that big of a deal... just something I thought should be known.

**Comment by OzzieIsaacs** [comment]
This is related to the update mechanism of the docker container. The container is doing a docker pull which leaves the commit-timestamp variable empty. Calibre-Web's update mechanisms does a download of the zip-file (like the file you get on the github website). In the zipfile the commit-timestamp variable is filled and calibre-web display the commit timestamp.

**Comment by kianrafiee** [comment]
Ah gotcha. Makes sense now.
