### ISSUE TITLE
Where are convert buttons? (Is Calibre-Web not finding /usr/bin/ebook-convert ?)

### ISSUE THREAD

**Issue by holta** [janeczku/calibre-web#624]
Two weeks ago @bodybybuddha [wrote](https://github.com/janeczku/calibre-web/issues/584#issuecomment-417008150): (as finalized in https://github.com/janeczku/calibre-web/issues/609)
> If a user has the ability to edit the metadata, and the system is configured for ebook-convert, the user should see a new option to convert books in the edit book page.

I'm trying but I cannot find any kind of convert buttons when clicking `Edit metadata` on any book.

Despite my having the very latest Calibre-Web (master branch) installed and also:
```
root@box:~# ebook-convert --version
ebook-convert (calibre 3.31.0)
Created by: Kovid Goyal <kovid@kovidgoyal.net>
```
Is it possible Calibre-Web cannot find `ebook-convert` that installed in /usr/bin, if Calibre-Web is perhaps expecting it in some other place ?
```
root@box:~# which ebook-convert
/usr/bin/ebook-convert
```
On Ubuntu 18.04, Calibre-Web's "About" page (suggests) it cannot find ebook-convert :-(
```
Linked libraries
Program library 	Installed Version
Sqlite 	v3.22.0
lxml 	v4.2.1.0
Image Magick 	ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
Flask 	v1.0.2
Babel 	v2.6.0
PyPdf 	v1.26.0
pySqlite 	v2.6.0
ebook_converter 	 	[ IS THIS A TYPO...SHOULDN'T IT BE "ebook-convert" ? ]
Tornado 	v5.1
Python 	2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
Sqlalchemy 	v1.2.11
Iso 639 	v0.4.5
Requests 	v2.19.1
Flask Login 	v0.4.1
Flask Principal 	v0.4.0
```
On Raspbian on Raspberry Pi, Calibre-Web's "About" page (suggests) it cannot find ebook-convert :-(
```
Linked libraries
Program library 	Installed Version
Sqlite 	v3.16.2
lxml 	v4.2.4.0
Image Magick 	ImageMagick 6.9.7-4 Q16 arm 20170114 http://www.imagemagick.org
Flask 	v1.0.2
Babel 	v2.6.0
PyPdf 	v1.26.0
pySqlite 	v2.6.0
ebook_converter 	[ IS THIS A TYPO...SHOULDN'T IT BE "ebook-convert" ? ]
Tornado 	v5.1
Python 	2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
Sqlalchemy 	v1.2.11
Iso 639 	v0.4.5
Requests 	v2.19.1
Flask Login 	v0.4.1
Flask Principal 	v0.4.0
```

**Comment by OzzieIsaacs** [comment]
Calibre-Web isn‘t searching for the converter, if you want to use it, you have to enter the path and name in ->admin-> basic settings -> external binaries (or similar), than please tick use Calibre ebook converter and add path and name in the field path to converter. Save settings, afterwards converting should be possible
About page also should list the version afterwards, the kindlegen binary is also a valid converter, so it’s ebook converter kindlegen version xxx or ebook-convert version yyy

**Comment by holta** [comment]
> enter the path and name in ->admin-> basic settings -> external binaries

Thanks!  Specifically, this is what worked for me under Calibre-Web -> Basic Configuration -> External binaries  -> Path to convertertool:
- I changed radio button `No converter` to `Use calibre's ebook converter`
- I entered: `/usr/bin/ebook-convert`

(Now we need to try to automate this for Internet-in-a-Box teachers everywhere...any quick hints as we set out to try to do both above programmatically?!)

**Comment by OzzieIsaacs** [comment]
Well, the settings-file app.db is a sqlite database. Maybe there is a sqlite editor where you could enter the 2 settings to the database directly via a commandline tool?

**Comment by bodybybuddha** [comment]
@holta - I was thinking about this path issue.  If ebook-convert is in the $PATH, you may only need to enter 'ebook-convert' -- without directory location in the configuration and it should find the tool.  Worth a quick test in your environment.

**Comment by holta** [comment]
> @holta - I was thinking about this path issue. If ebook-convert is in the $PATH, you may only need to enter 'ebook-convert' -- without directory location in the configuration and it should find the tool. Worth a quick test in your environment.

Great idea.

I'm also still hopeful Calibre-Web might in future run with this kind of idea &mdash; so conversion functionality works out-of-the-box as much as possible &mdash; perhaps even integrating https://manual.calibre-ebook.com/generated/en/ebook-convert.html into Calibre-Web itself, as appropriate.

**Comment by OzzieIsaacs** [comment]
If starting calibre-web the first time, the "usual" locations are searched for calibre's ebook converter
