### ISSUE TITLE
lxml version 3.7.2?

### ISSUE THREAD

**Issue by trasba** [janeczku/calibre-web#627]
Hi there,
I am currently working on a docker image for raspberry pi that includes calibre (ebook-convert).
My current environment works. However I noticed that I can not upload e.g. html, odt, rtf files.
So first I added those extensions, any reasons why those extensions should be avoided?
Further I can not convert e.g. html, odt files.
ebook-convert can handle those formats but it was not working in my environment. I found out that this was related to the version 3.7.2 of lxml. (This is fixed in the optional-requirements.txt "lxml==3.7.2") (ebook-convert told me that it needs at least version 3.8.0)
I switched to lxml version 4.2.1. Now the conversion works.
My question is, what is the reason for fixing the version of lxml to 3.7.2 ? Are there any known issues when using a higher version?

**Comment by OzzieIsaacs** [comment]
No, there have been no issues I've been aware of

**Comment by OzzieIsaacs** [comment]
Yes, I think I can merge/change it next week

**Comment by trasba** [comment]
Great,
I forked, branched it and created a pull request.
I hope it makes life easier for for you.
Cheers

**Comment by OzzieIsaacs** [comment]
Merged (also the added upload formats)

**Comment by trasba** [comment]
You are my hero.
Thanks :-)
