### ISSUE TITLE
Refactor web.py

### ISSUE THREAD

**Issue by Mohammed90** [janeczku/calibre-web#630]
The experience with the PR #629 and #495 show how the web.py 3000+ lines adds complexity and maintenance cost. The merge-conflict there was in functions unrelated to the added feature.

I believe this is a sign that web.py ought to be broken down into different files by feature.

**Comment by OzzieIsaacs** [comment]
I‘m aware of this problem. I already moved some functionality to other files and tried to reduce dublicate code. The problem is with flask (as far as I under stood it) all routes have to be in one file, or you have to add another dependency (flask-blueprint)

**Comment by bodybybuddha** [comment]
Being new to python, I did some research on blueprints and it seems like the next logical (big) step.  I also liked this person's [implementation](https://stackoverflow.com/a/17344725) - where the modules were contained in yaml file and then loaded.

The app is already pretty large, so restructuring it with blueprint will be a major decision/endeavor.  However, I think it will be beneficial moving forward.  I would gladly help here if the decision is to move forward.

(Just thinking out loud - but if we do move forward maybe we use github's release feature to designate pre- and post-blueprint structures?)

**Comment by bodybybuddha** [comment]
Did a quick [spreadsheet](https://drive.google.com/open?id=1dnqKML81MqSXoEce2bPwTWvKNJJT_clr6qX3qIkHLbk) on this.  Spreadsheet lists all the existing routes and proposed locations if we were to use blueprint. 

We go from 119 routes in one file to:
![image](https://user-images.githubusercontent.com/2854558/45792226-ecc1c300-bc5a-11e8-8270-ea3a9d4eb85f.png)

Of course, the proposed modules/pkgs are subject to change - just thought I'd do a quick analysis.

**Comment by bodybybuddha** [comment]
Another thing we could consider is to abstract the database functions to a controller.  Thus repetitive database queries can be replace with a controller function.  

For example, there are 79 **db.session.query** statements in web.py and of these, there are queries that are duplicated 5-8 times each.  For example: db.session.query(db.Books).filter(db.Books.id == book.book_id).first()

In addition to saving code maintenance in the future, by abstracting all database functions, we could think about allowing the use of multiple calibre db libraries with out having to run multiple instances of CW.  For instance, there could one db for audiobooks, another for comics, etc.  (Shooting for the moon here - but why not? :-) )

**Comment by wildthyme** [comment]
abstracting database functions would def make things easier
looking at it now and it seems writing book metadata is handled completely separately for new books uploaded vs existing books updated, and new books can't write a lot of metadata fields (even though the metadata extracted from the book file may include them)
