### ISSUE TITLE
Passwords for new users (public registration) not working

### ISSUE THREAD

**Issue by Cassock** [janeczku/calibre-web#636]
No issues logging in as admin, but when a new user is created from the public registration, the temp password that is emailed to them does not work. Same for when I try to reset that user's pw. 

Manually created users where I specify a username/pass work fine.

**Comment by Cassock** [comment]
Here's the response from the terminal:
```
[2018-09-18 17:28:34,054] INFO in web: Login failed for user "USERNAME" IP-adress: ::ffff:66.57.xx.xxx                                   
::ffff:66.57.xx.xxx - - [2018-09-18 17:28:34] "POST /login HTTP/1.1" 200 5652 0.126824   
```
The only useful thing I've been able to parse from this is that my time zone is off. Would that affect login?

**Comment by Cassock** [comment]
Additional notes about my environment: this is running on a Synology via docker using linuxserver/calibre-web.

**Comment by OzzieIsaacs** [comment]
I have no access to my programming computer this week, so I can‘t check it by myself. 
Timelzone Setting should not affect login.

**Comment by CHBMB** [comment]
Can't reproduce that behaviour here.  Just switched on public registration, created a new account, got the password emailed to me and logged straight in, also using our container. (My TZ is set correctly)

**Comment by Cassock** [comment]
CHBMB also verified this to be working on my machine. Will have to chalk this up to drinking, fat fingering, copy/pasting the wrong pw, or inadvertently fixing it (also while drinking).
