### ISSUE TITLE
Email test says successful no matter what's entered into fields

### ISSUE THREAD

**Issue by silentArtifact** [janeczku/calibre-web#657]
Hello,

Running into an odd issue; no matter what information I put into any of the SMTP fields, I can hit save and test, and it says that settings are saved, and email successfully sent. No emails are sending, obviously.

Edit: I noticed that under tasks it does show that the email tests fail, just not in the notifications that pop up on "save and test".

**Comment by bodybybuddha** [comment]
Sounds like we need to change the label to email was successfully queued.  Also I would like for the save action to take you immediately to the task screen - so one could see the result of the test.

**Comment by silentArtifact** [comment]
Ahh, that explains a lot. I'll have to open another one on why the email isn't actually sending, but it sounds like this one is mostly closed. Thanks!

**Comment by OzzieIsaacs** [comment]
I changed the text of the message to make it more clear what's going on. Bypassing the queue and sending it out directly make to much work for this problem
