### ISSUE TITLE
Unable to Send Email

### ISSUE THREAD

**Issue by silentArtifact** [janeczku/calibre-web#658]
This might be something extremely simple, so I apologize in advance if I'm being stupid. Calibre recently stopped sending emails (although other utilities using identical settings still do.) The logs show the following error, IP address removed

`ERROR - Error sending email: IP [172.X.X.X] is blocked.`

Has something changed on my end that I'm not aware of? I removed a few octets of the IP just in case.

**Comment by kesandal** [comment]
172.x seems to be a private IP range.
How did you configured the mail settings? Do you use a local mailserver?

**Comment by silentArtifact** [comment]
I am using a local mailserver, hosted on a synology NAS. I'm pointing Calibre at the internal IP (192.168.x.x), which has worked with other SMTP-using utilities. Perhaps the local mailserver is blocking it somehow?

**Comment by silentArtifact** [comment]
I'll have to look into the email server, thanks for the tips on where to go!

**Comment by silentArtifact** [comment]
So, I've been trying to get the log level to debug, and it actually shows _as_ debug, but it is still only putting out a single line when trying to send an email, same as before. I checked my SMTP settings, and they're identical to what I use in Ombi and Tautulli, both of which send correctly... is there a config file somewhere I might be looking into?

**Comment by bodybybuddha** [comment]
You may have to restart the application for the new level to kick in.

**Comment by OzzieIsaacs** [comment]
Are there any news, otherwise I will close the issue
