### ISSUE TITLE
Add configuration option to restrict http_server to only listen on localhost (127.0.0.1)

### ISSUE THREAD

**Issue by smallid** [janeczku/calibre-web#667]
When configuring calibre-web as a proxy for a local webserver, I would like to be able to prevent it from connecting to any external network interfaces and make it only be accessible from the local machine. Can you add a configuration option to allow this?

Note that adding 'address="127.0.0.1" to the http_server.listen call appears to restrict access in the manner desired.

server.py:
`http_server.listen(web.ub.config.config_port, address="127.0.0.1")
`

**Comment by OzzieIsaacs** [comment]
@hurui200320

**Comment by OzzieIsaacs** [comment]
Sorry, forgot to give feedback. It's meanwhile possible to limit the listening address by using the command line option: '-i', please see the [wiki](https://github.com/janeczku/calibre-web/wiki/Command-Line-Interface) for more details
