### ISSUE TITLE
Search works in web interface but not OPDS

### ISSUE THREAD

**Issue by benhoh** [janeczku/calibre-web#672]
Not sure if this is a bug, a problem with my install, my OPDS client (KyBook3 on iOS) or simply a feature request for something not yet on a the roadmap: OPDS search doesn't seem to exist. Meanwhile, the search functionality in the web interface is super-awesome!

**Comment by OzzieIsaacs** [comment]
The search is indeed no longer working. I'll check what's wrong

**Comment by OzzieIsaacs** [comment]
Should now work again
