### ISSUE TITLE
Calibre-Web Pip packaging 

### ISSUE THREAD

**Issue by arky** [janeczku/calibre-web#677]
Please kindly create pip packages for calibre-web. It will help wider distribution and adoption of the software.  Installing calibre-web would as simple as running:

`'pip install calibre-web' `

It would be helpful to have development version of the pip package to do pre-release testing.

`'pip install --pre calibre-web' `

**Comment by decentral1se** [comment]
I'm pretty interested in this and have left a comment over at https://github.com/janeczku/calibre-web/issues/456#issuecomment-491264590. Please let me know what you think. If we had a sufficient `setuptools` integration you would not be against uploading the package to PyPi @OzzieIsaacs?

**Comment by decentral1se** [comment]
Working towards this in https://github.com/janeczku/calibre-web/pull/927 :+1:

**Comment by decentral1se** [comment]
Btw, we can use https://test.pypi.org/ to test we're getting everything right before making an official PyPi release. More information about that over in https://packaging.python.org/tutorials/packaging-projects/#uploading-the-distribution-archives.

**Comment by decentral1se** [comment]
OK, #927 is merged. How to move forward on this? As per https://github.com/janeczku/calibre-web/pull/927#issuecomment-497734158, the release workflow is done somewhere else, so I am not sure how I can support it. I am https://pypi.org/user/decentral1se/ on PyPi if you need additional collaborators.

**Comment by epsilon-0** [comment]
@OzzieIsaacs necro bumpin.  
Is this still a thing that you are trying to get done?  
I'm packaging this for OpenBSD and it would be good to get this upstream instead of maintaining downstream patches.

**Comment by OzzieIsaacs** [comment]
It's still open: The problem so far is that via pypi you can not install dependencies via git, which is possible via the normal command line. Comicapi is causing the problem so far. Meanwhile I changed the code so much, that I'm thinking I'm having the right to publish it on pypi by myself, this would solve issue. But will still take some time

**Comment by epsilon-0** [comment]
I've created a pull request which kind of somewhat does the packaging. I've not implemented the dependency calculation and things of that form, please feel free to add those.
#1459

**Comment by OzzieIsaacs** [comment]
The project is now available on pyi under https://pypi.org/project/calibreweb/
