### ISSUE TITLE
how to set stmp

### ISSUE THREAD

**Issue by jxmlingyun** [janeczku/calibre-web#678]
Is there a sample for how to fit stmp setting?
My setting is finished,but there is a error
"ERROR - Error sending email: mail from address must be same as authorization user "

![image](https://user-images.githubusercontent.com/3866004/46916404-e3730e80-cfec-11e8-8da8-6d309b46951a.png)

**Comment by OzzieIsaacs** [comment]
I suggest putting the same e-Mail address in the from e

**Comment by jxmlingyun** [comment]
> I suggest putting the same e-Mail address in the ‚from e-mail‘ field as in the ‚SMTP Login‘ field

Thanks! It works.
