### ISSUE TITLE
New theme?

### ISSUE THREAD

**Issue by flashliao** [janeczku/calibre-web#682]
![image](https://user-images.githubusercontent.com/28710685/46941800-7f108780-d09e-11e8-90c5-dcea3aa958ca.png)

pleas change the page show ！

**Comment by OzzieIsaacs** [comment]
@leram84 is this fixed in the final version?

**Comment by leram84** [comment]
@OzzieIsaacs SORRY! i was meaning to get to this, but then got swamped, so im just gonna answer u now. the answer to this specific thing is yes thats not an issue at all on the finished version. BUT I dont have full support for all languages yet. I wasn't really planning on it, but now that iv gone this far, im gonna spend a few more hours getting the translations to work as well. I'll update here when thats done, but for english there are no bugs like this (or any that i know of) atm.

**Comment by OzzieIsaacs** [comment]
Is merged now
