### ISSUE TITLE
cover picture don't display when search metadata of  a book 

### ISSUE THREAD

**Issue by jxmlingyun** [janeczku/calibre-web#684]
A Bug!
When you search metadata of  a book ,cover picture don't display!
Fortunately, although it don't dispaly ,but it can download the cover normally。
![image](https://user-images.githubusercontent.com/3866004/47014856-0123ad80-d17e-11e8-9e26-b659410a5520.png)

**Comment by jxmlingyun** [comment]
ADD: google works well,douban can't show cover picture

**Comment by OzzieIsaacs** [comment]
Doubeln seems to have changed their websitelayout

**Comment by idalin** [comment]
Douban denies unknown referer source.
Three ways to solve it.
1. calibre-web scrapes it and then display.
2. view it by a proxy.
3. set Referrer-Policy to no-referrer(some browsers work, some not).

Solution 2: replace https://github.com/janeczku/calibre-web/blob/63bceeb9cd4b17593422b0993e4984a16eaaa420/cps/templates/book_edit.html#L252
with:
`         src="https://images.weserv.nl/?url=<%= cover %>"
`
"https://images.weserv.nl/?url=" is a images proxy. you can replace it with any others. 

Solution 3:  just add line undrer https://github.com/janeczku/calibre-web/blob/63bceeb9cd4b17593422b0993e4984a16eaaa420/cps/templates/book_edit.html#L253
content:
`referrerpolicy ="never"`


No PR:)

**Comment by jxmlingyun** [comment]
> Douban denies unknown referer source.
> Three ways to solve it.
> 
> 1. calibre-web scrapes it and then display.
> 2. view it by a proxy.
> 3. set Referrer-Policy to no-referrer(some browsers work, some not).
> 
> Solution 2: replace
> 
> [calibre-web/cps/templates/book_edit.html](https://github.com/janeczku/calibre-web/blob/63bceeb9cd4b17593422b0993e4984a16eaaa420/cps/templates/book_edit.html#L252)
> 
> Line 252 in [63bceeb](/janeczku/calibre-web/commit/63bceeb9cd4b17593422b0993e4984a16eaaa420)
> 
>  src="<%= cover %>" 
> 
> with:
> `src="https://images.weserv.nl/?url=<%= cover %>"`
> "https://images.weserv.nl/?url=" is a images proxy. you can replace it with any others.
> Solution 3: just add line undrer
> 
> [calibre-web/cps/templates/book_edit.html](https://github.com/janeczku/calibre-web/blob/63bceeb9cd4b17593422b0993e4984a16eaaa420/cps/templates/book_edit.html#L253)
> 
> Line 253 in [63bceeb](/janeczku/calibre-web/commit/63bceeb9cd4b17593422b0993e4984a16eaaa420)
> 
>  alt="Cover" 
> 
> content:
> `referrerpolicy ="never"`
> No PR:)

THANKS! You solve my problem!
Moreover，I am in China,so the image proxy is blocked.If someone come to the same problem ,remenber to let image proxy url go throng vpn.

**Comment by 275761919** [comment]
That add meta tag: `<meta name="referrer" content="never">`  also works.
