### ISSUE TITLE
Updater never ends, if connection is lost during update

### ISSUE THREAD

**Issue by flashliao** [janeczku/calibre-web#687]
If the calibre-web have not the internet network,just have local area （LAN）network。 
update the calibre-web ,The calibre-web can not longger enter the website。
I think if calibre-web have not the internet network,it shows some message，not system halted。

**Comment by OzzieIsaacs** [comment]
Update check fails if no internet connection is present
Updater runs endless if connection is lost during updater, or not present at start of update
