### ISSUE TITLE
Systemd

### ISSUE THREAD

**Issue by BelArvardan** [janeczku/calibre-web#69]
This is an excellent and much needed addition to calibre. Thanks for the hard work. 

I would like to run this as a service under systemd is there a way that could be integraded???

**Comment by OzzieIsaacs** [comment]
Create a file "cps.service" as root in the folder /etc/systemd/system with the following content:
```
[Unit]
Description=Calibre-web

[Service]
Type=simple
User=IFNOTROOT
ExecStart=python /PATH/TO/cps.py

[Install]
WantedBy=multi-user.target
```
Replace the user and ExecStart with your user and foldername. 
Afterwards
```sudo systemctl enable cps.service```
should enable the service. 
I can't test it myself, my system isn't using systemd as init system (this is in my opinion also the reason why we won't integrate it, it's not working for everybody). 
If you encounter any problems try to use your favorite web-search engine and search for something like: script systemd . Hope this helps. Feedback is welcome.

**Comment by BelArvardan** [comment]
Cool thanks. I will give it a try and get back to you. Your config looks different then the you I tried to write myself.

**Comment by BelArvardan** [comment]
It works!  I changed the config slightly from what was posted.

I have a virtualenv setup for calibre.

here is my systemd config. Just in case it is helpful to someone.

[Unit]
Description=Calibre-web

[Service]
Type=simple
User=calibre
ExecStart=/home/calibre/bin/python /home/calibre/calibre-web/cps.py

[Install]
WantedBy=multi-user.target

**Comment by esbeeb** [comment]
> Afterwards `sudo systemctl enable cps.service` should enable the service. ... Feedback is welcome.

You should do a "sudo systemctl daemon-reload", before your "sudo systemctl enable cps.service", _and_ "sudo systemctl start cps.service"
