### ISSUE TITLE
Error 500 on emailing to Kindle

### ISSUE THREAD

**Issue by ducatdusk** [janeczku/calibre-web#694]
On some books in my library, but not all, I receive an Internal Server Error when trying to email to kindle. The console outputs the following:

`[2018-11-03 16:44:46,719] ERROR in app: Exception on /send/23 [GET]
Traceback (most recent call last):`
  `File "/home/adamsj/bin/calibre-web/vendor/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()`
`  File "/home/adamsj/bin/calibre-web/vendor/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)`
 ` File "/home/adamsj/bin/calibre-web/vendor/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)`
`  File "/home/adamsj/bin/calibre-web/vendor/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()`
  `File "/home/adamsj/bin/calibre-web/vendor/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)`
`  File "/home/adamsj/bin/calibre-web/vendor/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)`
  `File "/home/adamsj/bin/calibre-web/cps/web.py", line 427, in inner
    return f(*args, **kwargs)`
 ` File "/home/adamsj/bin/calibre-web/cps/web.py", line 2457, in send_to_kindle
    result = helper.send_mail(book_id, current_user.kindle_mail, config.config_calibre_dir, current_user.nickname)`
 ` File "/home/adamsj/bin/calibre-web/cps/helper.py", line 148, in send_mail
    kindle_mail, user_id, _(u"E-mail: %(book)s", book=book.title))`
`TypeError: add_email() takes exactly 9 arguments (8 given)
`

It's not a big deal, I can download and email manually, but I guess that this isn't the expected behaviour. There does not appear to be any difference between these books and other in my library.

**Comment by OzzieIsaacs** [comment]
Mistake during programming this morning. The error occoured for all books having a mobi file and don't need a conversion. 
Please update to the newest commit, should work again with translated texts (if you need it)

**Comment by ducatdusk** [comment]
Confirmed working. Thanks!
