### ISSUE TITLE
[Enhancement]: Create category unassigned books

### ISSUE THREAD

**Issue by DoDoRonRon** [janeczku/calibre-web#695]
Hello. I have a suggestion for the developers of calibre-web docker. I use the linuxserver/calibre-web version on openmedivault 4. Everything works fine. Now to my suggestion.
Under the heading "Browsing" are different tabs, where I have a tab missing or at least deserved a change. These are "books sorted". Here could be an entry called "Unassigned Books". It makes sense if I put a book in my books collection, that it no longer appears in "Unassigned Books". Then I would have a perfect overview and know immediately which books I have not sorted yet. With several hundred books one easily loses the overview.

many Greetings

Ron

I would like to apologize for mistakes in the translation. I use Google translator.

**Comment by OzzieIsaacs** [comment]
You could use the read/unread feature for this. All new books added to calibre-web are unread, and showing in this category. After you have sorted, you could tick the read checkbox and than the books disappear from this section.
----------------------------------------------------------------------------------------------------------------------------------
Du könntest das Gelesen/Ungelesen Feature dazu benutzen. Alle neuen Bücher werden als ungelesen hinzugeführt. Nachdem diese sortiert wurde kann man einfach unter den Bücherdetails die Box "gelesen" anwählen, dadurch verschwindet das Buch aus der "Ungelesen"-Kategorie. 
Bitte antworte auf den Post bitte trotzdem in Englisch, damit andere von den Fragen ebenfalls profitieren können (der Google Übersetzer funktioniert fast tadellos zwischen Englisch und Deutsch, lediglich Eigennamen bringen Ihm zum Stolpern)

**Comment by DoDoRonRon** [comment]
This feature is known to us. Only then is the problem that you can no longer distinguish between read and unread books. Therefore the additional function would be sorted/unsorted a desirable function.

**Comment by joshuaherman** [comment]
Desired solution is a default shelf that contains all books. You can still add books to multiple shelves.

**Comment by OzzieIsaacs** [comment]
In tags there is a element to select named None, all books having no tags, series, language, publisher are visible there
