### ISSUE TITLE
OPDS Catalogs

### ISSUE THREAD

**Issue by xFilosofx** [janeczku/calibre-web#7]
Hello,
everything works fine, but have a question. Is it possible to expand the list of items in OPDS catalog? It is very difficult to find a book when there is only hot books, new books, and random books.

**Comment by janeczku** [comment]
TODO: add authors and category index to OPDS feed.

**Comment by OzzieIsaacs** [comment]
I've implemented it. 
After you've merged my other commits, I will create a pull request for this one (it depends on the changes I made in pull request #47
