### ISSUE TITLE
Send to Kindle error

### ISSUE THREAD

**Issue by simkin** [janeczku/calibre-web#70]
Results in an server error (I am using sendmail without authentication)

> [2016-11-07 14:05:26,697] {/opt/calibre-web/vendor/flask/app.py:1587} ERROR - Exception on /send/31239 [GET]
> Traceback (most recent call last):
>   File "/opt/calibre-web/vendor/flask/app.py", line 1988, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/opt/calibre-web/vendor/flask/app.py", line 1641, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/opt/calibre-web/vendor/flask/app.py", line 1544, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/opt/calibre-web/vendor/flask/app.py", line 1639, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/opt/calibre-web/vendor/flask/app.py", line 1625, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/opt/calibre-web/vendor/flask_login.py", line 792, in decorated_view
>     return func(*args, **kwargs)
>   File "/opt/calibre-web2/cps/web.py", line 262, in inner
>     return f(*args, **kwargs)
>   File "/opt/calibre-web2/cps/web.py", line 1003, in send_to_kindle
>     result = helper.send_mail(book_id, current_user.kindle_mail)
>   File "/opt/calibre-web2/cps/helper.py", line 75, in send_mail
>     msg['Subject'] = _('Send to Kindle')
> NameError: global name '_' is not defined

Any ideas what I configured wrong?
Calibre Web Version 0.10.1 2014-2016

**Comment by OzzieIsaacs** [comment]
Sorry, I broke it.

Please checkout the newest version, should now work again.

**Comment by simkin** [comment]
Confirmed fixed
