### ISSUE TITLE
Error when add/change language editing metadata.

### ISSUE THREAD

**Issue by JerryC75** [janeczku/calibre-web#701]
Hi! I'm having these error when trying to add or change the Language field editing metadata.
I'm using Spanish language.

![deepinscreenshot_select-area_20181115182100](https://user-images.githubusercontent.com/45083473/48590701-284cd680-e906-11e8-8552-86ac5a5b4286.png)

![deepinscreenshot_select-area_20181115182314](https://user-images.githubusercontent.com/45083473/48590706-300c7b00-e906-11e8-89c6-6e5932d71491.png)

This is the result when query the languages:
https://www.fakeweb.com/calibreweb/get_languages_json?q=
` [{"name": "Romansh"}, {"name": "Scots"}, {"name": "Sicilian"}, {"name": "Romany"}, {"name": "Romanian"}]
`

This is the result in the log file:
```
 [2018-11-15 17:29:18,048] {/var/www/calibre-web/cps/web.py:3770} ERROR - 'Languages' object has no attribute 'name'
 Traceback (most recent call last):
   File "/var/www/calibre-web/cps/web.py", line 3733, in edit_book
     modify_database_object(input_l, book.languages, db.Languages, db.session, 'languages')
   File "/var/www/calibre-web/cps/web.py", line 604, in modify_database_object
     elif db_element.name != add_element:
 AttributeError: 'Languages' object has no attribute 'name'

```

**Comment by OzzieIsaacs** [comment]
I couldn't reproduce it, but I found the problematic line and fixed it.
