### ISSUE TITLE
how to use 'Link read/unread status to Calibre column'

### ISSUE THREAD

**Issue by abubaman** [janeczku/calibre-web#704]
first of all, I always appreciate for you to make calibre-web.

recently, I made an update and I found some new features. one of them is 'Link read/unread status to Calibre column'.
As I understand, this function may make 'unread/read status in calibre-web' to Calibre's identical.
But, I can not find how to make it identical.

So, would you please let me know how to use this functionality?

**Comment by OzzieIsaacs** [comment]
You need to have a bool custom column in calibre to store the read/unread status. In the calibre-web config you now select the columns name. Calibre-web now takes the value in this column to display as read/unread. This is obviously only working for a one user system (gloabl read and unread status). I recommend to also add the name of the column in the field regular expression for ignoring columns in calibre-web. Advantage of the linked status is that you also can change the read/unread status in calibre.

**Comment by OzzieIsaacs** [comment]
From your issue #717 I think you found out how to use it, so I close this issue
