### ISSUE TITLE
Book extension lower is lower case when converting

### ISSUE THREAD

**Issue by bodybybuddha** [janeczku/calibre-web#705]
This may be a new bug.

If a user selects Send To Kindle on a book that requires conversion (in my case .epub) to .MOBI, the book will be converted and added to the database as expected.  However, if you view the formats of the book, the .MOBI extension is in lower case:
![image](https://user-images.githubusercontent.com/2854558/48681426-62211580-eb70-11e8-8b2b-558dc576a81e.png)

Whereas if you were to manually convert a book to .MOBI, the interface shows the expected uppercase .MOBI.

I'm sure this is just a formatting issue, but I thought I would bring it up.

**Comment by OzzieIsaacs** [comment]
I doublechecked it, I can not reproduce this, on my computer the file format is always uppercase. Could you please describe more detailed what to to to reproduce the issue?

**Comment by OzzieIsaacs** [comment]
Are there any new infos on this, otherwise I would close this issue
