### ISSUE TITLE
Possible to Sync Highlights, Notes and Reading Positions?

### ISSUE THREAD

**Issue by CyberLeopard** [janeczku/calibre-web#707]
Hello,

Is it possible to sync highlights, notes and reading positions between devices? Like Google Books does. This will be a great feature for an ultimate personal ebook library solution.

Thanks!

**Comment by OzzieIsaacs** [comment]
Currently there is now feature like this planned. I think each reader has it's own interface and so I don't know how to realize this

**Comment by TheNomad11** [comment]
Any news? Not even possible to sync with Calibre Desktop?

**Comment by benab** [comment]
> Is it possible to sync highlights, notes and reading positions between devices? Like Google Books does. This will be a great feature for an ultimate personal ebook library solution.
> 
> Thanks!
I would think this would be possible using the web version, but I don't think it is currently implemented.

**Comment by moomtaz** [comment]
I'm Using Obsidian to view my books via the web server. If I make highlights on the web server version I cannot sync those to the computer that is hosting the server. However if I look at the book in my browser it has the highlights. Is there a way to sync them back and forth?
