### ISSUE TITLE
[Suggestion] Support upload of .epub/.mobi (instead of only PDF)

### ISSUE THREAD

**Issue by simkin** [janeczku/calibre-web#71]
Not sure if already requested or designed on purpose but I would like to see it becomes possible to also upload ebooks in other formats as PDF.

**Comment by OzzieIsaacs** [comment]
This should work 
(There were errors on windows, I fixed it with latest commit)
Could you please check again. If it still fails, please explain detailed what happens, and please post the output of the logfile
