### ISSUE TITLE
Chinese path and book name issue

### ISSUE THREAD

**Issue by toseeme** [janeczku/calibre-web#710]
This is really good online ebook project. I love it very much! 
I got a problem recently with Chinese Path and book name issue. I would like have Chinese author name as path and Chinese books name, but system convert author and book name as Chinese spell, not character. but it worked as Chinese character when I using Docker version previously. Please check the picture as attached, the yellow highlight is the book which I've uploaded on Docker, and Red highlight was uploaded recentlly on new calibre-web installation with new Centos7(not docker version). 
**is it possible to let me know how to solve this problem?**
![2018-11-23 16_02_13-clipboard](https://user-images.githubusercontent.com/40018420/48932936-38ce0400-ef39-11e8-9b4a-9a9e77f3ed2e.png)
.
![2018-11-23 16_18_43-10 71 111 63 root](https://user-images.githubusercontent.com/40018420/48933626-f5c16000-ef3b-11e8-9dd0-3e5f7cd480ea.png)

**Comment by toseeme** [comment]
it's yours on docker hub. i will try your suggestion and will update you late. Thanks a lot.

**Comment by toseeme** [comment]
I did not find the way to remove undecode lib from my python environment. and I don't think that is the right way as you mentioned.

**Comment by paulhybryant** [comment]
I did the same. You can remove the unidecode lib from the requirements.
It works fine for me.

**Comment by toseeme** [comment]
> I did the same. You can remove the unidecode lib from the requirements.
> It works fine for me.

I've tried to pip uninstall unidecode. but it's same problem after remove. anything else I need to do?

**Comment by paulhybryant** [comment]
The dependencies are installed with: 
pip install --target vendor -r requirements.txt
Are you sure you are removing the one installed there?

**Comment by OzzieIsaacs** [comment]
The calibre-web janeczku container isn't maintained anymore, it's missing a lot of features and bugfixes, it shouldn't used anymore. I think the general issue is solved (it's not recommended to use the chinese character names), your problem now is a pure python problem.
Additionally you could change line 36 in file cps/helper.py to:
`    use_unidecode = False`
(The spaces at the beginning are essential)
