### ISSUE TITLE
Securely Set Admin Password Out-of-Band

### ISSUE THREAD

**Issue by Mohammed90** [janeczku/calibre-web#716]
Certificate transparency logs can be abused to beat admins to set up the admin password of a new installation before them, as explained [here](https://www.golem.de/news/certificate-transparency-hacking-web-applications-before-they-are-installed-1707-129172.html).

I propose introducing a config file that contains the path to Calibre's database and the rest of needed configuration. As for the admin username and password, introduce a command line script that can init Calibre-web's database, add/remove users, and modify users (e.g. set as admin, reset password).

**Comment by OzzieIsaacs** [comment]
I checked the paper, the big advantage over the programs described there is that calibre-web has some sort of "secret token" to finish the installation (you need to know the location of a server-local valid metadata.db), furthermore calibre-web allows no plugins and therefore you can't get shell access by uploading just ebooks. 
I think this attack is very complicated and you need to know more than just the host name. If the workaround would be implemented It rises the hurdles for users to do the setup. I think one of the advantages compared to the original .ini file setup(which was the first setup routine of calibre-web) is that it is fully graphically and in the browser and you don't have to do command-line work. 
From my point of view, also every admin of calibre-web should think very carefully if the wants to expose calibre-web into the internet (it's made for sharing books among your family and not a dark-web free ebook-store for the whole world).

**Comment by Mohammed90** [comment]
Good point on the requiring valid metadata.db path. I have not tried trying to pass through without entering a valid path. Calibre-Web will not allow it.

In this case, it's up to you whether you see this request valid. The only other argument I have is that the necessity of completing installation via GUI makes attempts to deploy Calibre-Web without manual intervention is not doable (not script-able).
