### ISSUE TITLE
Library Crash When I change something in calibre-web [Docker]

### ISSUE THREAD

**Issue by abubaman** [janeczku/calibre-web#717]
I am a Calibre-web user and almost function is running well.

But I have experiences Calibre-Library crushes when I change something(e.g., metadata) in calibre-web.
In this case, I added Custom 'Boolean column' to make 'read/unread status' match to Calibrew-Library(program).

But after I set up Custom coulum in Calbrew-web, It shows all books well, but it didn't show new-added books any more. And If I change author name(in calibre, author name is same as folder name) Calibre-web lose the information of books(I think Calibre-web might lose like address of books).

Because I am old user of Calibre-web, I know how to handle this. below is my solution.
---
1. Prepare new calibre library(program's library)
2. mount new calibre library in Calbre-web. and make calibre-web refer new calbre library.
3. if 2 doesn't work, delete app.db
4. after that, delete metadata.db in old Calibre library, and rebulid the database in calibre.
5. in calibre-web, make calibre-web refer old calibre web library which was rebuilt.
---
In this procedure, I think calibre-web stores its own library when it finds any differences between calibre-web and calibre-real-library(in program).

So please let me know how to solve this problem without above procedure.
for your information, I restared and reconnected to db sevral times before dogin above procedure.

**Comment by abubaman** [comment]
Please let me know there is another solution or not.
If you don't have that, I need to above procedure to revive Calibre Library.

**Comment by OzzieIsaacs** [comment]
Related to #620 (Issue with lib change)

**Comment by OzzieIsaacs** [comment]
I tried to reproduce the problem. For me everything is working fine. but I'm not sure if I 'm doing the right steps to reproduce the problem. What I did:
1) Started Calibre-web on computer 1 (linux) with calibre-lib on local hard drive logged in as admin
2) Started Calibre on computer 1 point to above calibre-lib added custom column of type "yes/no". Saved and restarted Calibre
3) in Calibre-web set the Link column to the added column (in the selector the column is shown).
4) tried to display book -> not working. Error in Log: 
`matching_have_read_book = getattr(entries,'custom_column_'+str(config.config_read_column))
AttributeError: 'Books' object has no attribute 'custom_column_1'`
5) in admin section click on reconnect to library-> Everything is working as expected, books can be displayed and edited

Could you please provide log of your problem?
Regarding your solution: 

> 2: mount new calibre library in Calbre-web. and make calibre-web refer new calibre library.

What do you mean with "mount"? The only think to do is set location of calibre database to the path of the new library (which sound to me like the second half of your sentence), what else do you do? Where is your database located, are you using google drive?

From my point of view there is no need to delete the lib and let calibre rebuild the lib (especially if you edit books in calibre-web, this isn't saved in the backup of calibre, so you will loose everything you did in calibre-web). I think a normal "repair library" in calibre should fix the database. If you are having such strange things. I recommend stopping calibre-web during all operations in Calibre.

**Comment by OzzieIsaacs** [comment]
Looks like an issue with the docker container, please report the issue there. I can't reproduce the problem
