### ISSUE TITLE
Allow editing of Ids

### ISSUE THREAD

**Issue by XenoPhage** [janeczku/calibre-web#719]
Editing metadata does not include the Ids field that exists in Calibre.  This prevent add/change/delete of data such as ISBNs.  What would it take to get editing of this field added?

**Comment by Dinth** [comment]
Im also desperate for this functionality.

**Comment by Dinth** [comment]
Sorry to bump this thread, but its very important for me.

**Comment by cwldev** [comment]
+1 for being able to do this. IDs are incredibly useful in Calibre-web for so many reasons. Allowing the ability to edit this stuff would be super useful.

**Comment by OzzieIsaacs** [comment]
This is meanwhile implemented

**Comment by XenoPhage** [comment]
YES!  Can't wait to try this out..  THANK YOU !!!

**Comment by XenoPhage** [comment]
Beautiful!  Works great.  Thanks @OzzieIsaacs !

**Comment by cwldev** [comment]
Awesome.. thanks @OzzieIsaacs - Looking forward to checking it out.
