### ISSUE TITLE
[Suggestion] Present Series List in filterable table

### ISSUE THREAD

**Issue by simkin** [janeczku/calibre-web#72]
Render "Series List" in paginated table format with columns: Serie Title, Author, Language, Genres, .. 

- Make sortable per column.
- Make none-author columns filterable (enable/disable languages/genres/..)
- Do not prefix random books at the top of the page when selecting a serie

**Comment by OzzieIsaacs** [comment]
Finally I made it. There is a new view option "Books List"
You can filter search books, select books and finally merge them. 
It's also possible to change title and author and any other field in the table by just clicking on the entry
![grafik](https://user-images.githubusercontent.com/6438895/95650639-1a4d6380-0ae5-11eb-9e8d-d38973ae2747.png)

(Available via nightly updates)
Tests aren't finished yet, but I think it's quite stable
