### ISSUE TITLE
Sent To Kindle

### ISSUE THREAD

**Issue by AndreasSchuette** [janeczku/calibre-web#724]
No real problem just cosmetic: in book-details view there is a button labeled "Send To Kindle". I'm using this button with a PocketBook without any problem. So please consider changing the button-label to something more "general" e.g. "send to device"

**Comment by OzzieIsaacs** [comment]
It looks like pocketbook is supporting a lot of formats, all the other readers (beside kindle) I know (kobo, tolino) support as as main format epub. The send to kindle button is converting epub to a kindle format like mobi of azw3 before sending it to the reader, so I think renaming the button will lead to confusion for users of these reader format.
I decided not to change the text in the GUi, I will add a short hint in the readme (or the planned wiki in the future) to cover this case. But anyway thanks for the hint.
