### ISSUE TITLE
Index in recently added books

### ISSUE THREAD

**Issue by paulhybryant** [janeczku/calibre-web#726]
Hi,

In the recently added books page, when mouse scroll down, it automatically loads the next x books when it reaches the bottom of the page.

Before the page loads, I see that there is an index of pages (which quickly goes away).

Is there an option to disable this auto-loading, and keep the index at the bottom of the page instead?

Thanks!

**Comment by OzzieIsaacs** [comment]
The autoloading happens on each page showing the books. The way to prevent it is to limit the number of books on each page (setting in view settings in the admin section) to fit on one page in the browser (e.g. 10 or 12 books on wide screen displays withhout random books showing). Then the page forward backward button is shown. 
A change of this behavior is not planned.

**Comment by paulhybryant** [comment]
That is good enough for me. Thanks or the reply!
