### ISSUE TITLE
[Suggestion] Allow editing of book shelfs

### ISSUE THREAD

**Issue by simkin** [janeczku/calibre-web#73]
Allow:
- Renaming shelf name
- Removal of books
- Reorder books (fix reading order)

**Comment by OzzieIsaacs** [comment]
Removing books from shelfs is already possible on the "show book" page.
Or, are you talking about deleting the book from the database?

**Comment by simkin** [comment]
I missed that, I guess I expected that a level higher, matter of taste. Ignore that point 😀

**Comment by n0valis** [comment]
Reorder books would be great though. I mean, that's what you do in your shelf right? Put the books together that belong together, and then rearrange if new ones come in. 
That would be a great feature. User defined order... love to see it!

**Comment by OzzieIsaacs** [comment]
Should work now

**Comment by n0valis** [comment]
Fantastic. Thank you.
