### ISSUE TITLE
download kindle format with conversion?

### ISSUE THREAD

**Issue by perler** [janeczku/calibre-web#734]
Is this a feature: download the .mobi version if only the .epub version exists by converting it on the fly?

if yes, how do I activate it?

**Comment by OzzieIsaacs** [comment]
Yes it's a feature. If you have installed kindlegen (not recommended anymore) or calibre you can enable these converters in admin -> basic setup -> external binaries. Afterwards the kindle button should show the option you mentioned above.

**Comment by perler** [comment]
Mh.. I don't really see it. (https://photos.app.goo.gl/uy5hxiPoCsEaqWJk9) In case I didn't make myself quite clear, I was expecting a mobi download button after enabling the conversion options..

**Comment by OzzieIsaacs** [comment]
Sorry, I misread your first post. 
There is only a send to kindle conversion on the fly button. If you want to convert the epub file to mobi, than you have to go to the edit page choose the conversion you want and download it afterwards.
Some people have already asked to move the conversion button to the view page, which I've denied (and still doing).

**Comment by perler** [comment]
Ok, which is a pity. 

Maybe it helps convincing you to do just that by explaining the reasoning behind this feature request: There are people who mistrust amazon so deeply, that they do not connect their kindle to amazon at all (pain in the ass it is to do this nonetheless). these people would like to download their epubs to the kindle directly from calibre-web and the on-the-fly conversion is very close to make this possible..

**Comment by astrodad** [comment]
I know this is beating a dead horse, but I concur with @perler on this. I use calibre-web for books for my kids and I don't want them going to Amazon for anything. I want to be able to download the mobi version of an epub and then just drag it over onto the kindle locally, no wi-fi required.

**Comment by rg9400** [comment]
Another use case is if you want to download azw3 files. These cannot be sent via the Send to Kindle option as they bounce back due to some restriction on Amazon Cloud. You have to download them and then place them on your kindle. Having the option to do it on the fly would be greatly appreciated.
