### ISSUE TITLE
127.0.0.1:8083 doesn't resolve, but localhost:8083 does

### ISSUE THREAD

**Issue by MReprogle1** [janeczku/calibre-web#735]
I know 127.0.0.1 works, as my Calibre Content server loads up perfectly fine, as well as my Plex server. I don't know if I am missing something, but when going to localhost:8083, it works flawlessly.

**Comment by MReprogle1** [comment]
Nevermind. I got it to work, but I am just unable to reach it it from outside, even though I have a port forward rule set up on my firewall..

**Comment by upsrokmj-creator** [comment]
localhost/127.0.0.1:8083
