### ISSUE TITLE
watch metadata.db without gdrive integration

### ISSUE THREAD

**Issue by perler** [janeczku/calibre-web#737]
can we have the option to watch the metadata.db even if we do not integrate with google drive? I sync the books folder by other means and right now need to manually reconnect the db to see changes made outside calibre-web

**Comment by a575606** [comment]
I second this.... just a toggle to auto reconnect to the database every so often would be all we needed.

**Comment by OzzieIsaacs** [comment]
I saw a lot of trouble with users trying to copy/replace metadata.db files in the background of calibre-web and wondering why it's not working, so I don't want to encourage them to do so. 
Calibre-web is not made for replacing metadata.db while running and it will not in the future

**Comment by perler** [comment]
Ok. But how do we update the metadata.db externally? Or do you see
calibre-web as the only tool to edit the metadata.db?

**Comment by OzzieIsaacs** [comment]
For me starting calibre after! starting calibre-web, editing whatever I wanted did always work. I never could reproduce any case where the metadata wasn't updated in Calibre-Web afterwards. There is a public reconnect route available "/reconnect". A simple script triggering this route can help in any other cases.
