### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by nicoroud** [janeczku/calibre-web#74]
Hi,
This project is absolutely awesome ! Thanks a lot for your work.
I made a translation in french this afternoon. If anybody is interested, I post the file here.

Anyway, it would be nice if we could launch the python script (python cps.py) like a service (I installed this in a debian server).

Regards

[messages.zip](https://github.com/janeczku/calibre-web/files/587918/messages.zip)

**Comment by OzzieIsaacs** [comment]
You can set it up as service as described in #69.

Thanks a lot for the translation, I try to merge it in the next days
