### ISSUE TITLE
CaliBlur: lib files not being loaded when Caliblur is selected

### ISSUE THREAD

**Issue by hexeth** [janeczku/calibre-web#745]
The newly added lib files:

readmore.min.js
compromise.min.js

Do not seem to be getting loaded when the new theme is selected:

Error as seen on all pages:
`Uncaught TypeError: $(...).readmore is not a function`

Error in particular book details pages where nlp function from compromise is called:
`Uncaught ReferenceError: nlp is not defined`

The above files are present in the directory structure of the technosoft docker:
![image](https://user-images.githubusercontent.com/7627137/50659488-a5351d80-0f51-11e9-9723-e4616c6325c3.png)

But do not appear in console source:
![image](https://user-images.githubusercontent.com/7627137/50659508-b8e08400-0f51-11e9-8953-c537b7f6d784.png)

Additionally,

A third library that is used in the Caliblur theme was not integrated. This library is used to ensure mouse-over hover elements stay on the screen:

https://github.com/customd/jquery-visible

**Comment by OzzieIsaacs** [comment]
Sorry my fault, in the files from the caliblur repro the libs have been merged to the js file, during merging I played a little bit with the libs to check if I got the right one and I forgot to comment the lines in. The last lib was integrated in the js file, because I wasn't sure which one it was, but now it's separate and should work.

**Comment by hexeth** [comment]
Thanks for the quick reply; I can confirm this has been fixed

**Comment by hexeth** [comment]
Hey @OzzieIsaacs I'm running into this again on a new install.

![image](https://user-images.githubusercontent.com/7627137/63045192-b4cff980-be84-11e9-9ea1-05d2de546574.png)

Any idea what's going on?

**Comment by OzzieIsaacs** [comment]
Nop, I'm feeling not guilty:
![grafik](https://user-images.githubusercontent.com/6438895/63045510-cb9c3d80-bed0-11e9-9d89-7ebdb9966ae5.png)
Could you please check if in your layout.html (cps/templates/layout.html) the lines are commented out, line 208ff)
You are using the current master branch commit?

**Comment by hexeth** [comment]
It looks like my docker volume was somehow stuck in the past. Wiped the volumes and configs and it's fixed. Thanks for the quick check.
