### ISSUE TITLE
[Enhancement] Visibility of read status in list of books 

### ISSUE THREAD

**Issue by Gronda74** [janeczku/calibre-web#748]
I've had a look through the previous entries but can't see this one. Is there scope to have the read status of a book displayed either as an overlay on the cover or as a marker next to the title (e.g. the tick box showing alongside the star rating)?

**Comment by OzzieIsaacs** [comment]
You should see the marker as long as you aren't anonymous user:
![grafik](https://user-images.githubusercontent.com/6438895/50707423-16172b00-1061-11e9-8551-f9917fc38cd2.png)
To make it show up in the sidebar you have to enable showing of read/unread status in the admin section of the corresponding user.

**Comment by Gronda74** [comment]
Yes, I can see the marker in the book info and have the read / unread options in the sidebar. What I mean is having it always listed along with the book title, such as:
![img_1107](https://user-images.githubusercontent.com/46248742/50709031-5a54fc00-105e-11e9-8654-a9fe316a536c.jpeg)

**Comment by celogeek** [comment]
Hi,

I have made this PR:

https://github.com/janeczku/calibre-web/pull/1214

It improves read status. We do not need to filter the custom header anymore (it is done automatically and only on book details (no on advanced search)).

**Comment by OzzieIsaacs** [comment]
The PR is meanwhile merged
