### ISSUE TITLE
How to reset password

### ISSUE THREAD

**Issue by wv1124** [janeczku/calibre-web#750]
How to reset password

**Comment by OzzieIsaacs** [comment]
Depending on the exact problem:
User forgot password: Admin section -> User -> change password
Admin forgot password: Same procedere procedure as above with other admin 
Only admin forgot password: You are in trouble. Currently no password reset function is implemented 
The only option would be editing the password in the App.db with a sqlite Databaseeditor, or starting from the beginning

**Comment by Mohammed90** [comment]
For the meantime, you can use this script:
```python3
import sys
import hashlib
import codecs
import hmac
from random import SystemRandom

_sys_rng = SystemRandom()
SALT_CHARS = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
DEFAULT_PBKDF2_ITERATIONS = 150000
PY2 = sys.version_info[0] == 2

if PY2:
    text_type = unicode
    from itertools import imap, izip, ifilter
    range_type = xrange
    def to_bytes(x, charset=sys.getdefaultencoding(), errors='strict'):
        if x is None:
            return None
        if isinstance(x, (bytes, bytearray, buffer)):
            return bytes(x)
        if isinstance(x, unicode):
            return x.encode(charset, errors)
        raise TypeError('Expected bytes')

    def to_native(x, charset=sys.getdefaultencoding(), errors='strict'):
        if x is None or isinstance(x, str):
            return x
        return x.encode(charset, errors)
else:
    text_type = str
    range_type = range
    def to_bytes(x, charset=sys.getdefaultencoding(), errors='strict'):
        if x is None:
            return None
        if isinstance(x, (bytes, bytearray, memoryview)):  # noqa
            return bytes(x)
        if isinstance(x, str):
            return x.encode(charset, errors)
        raise TypeError('Expected bytes')

    def to_native(x, charset=sys.getdefaultencoding(), errors='strict'):
        if x is None or isinstance(x, str):
            return x
        return x.decode(charset, errors)

def _hash_internal(method, salt, password):
    """Internal password hash helper.  Supports plaintext without salt,
    unsalted and salted passwords.  In case salted passwords are used
    hmac is used.
    """
    if method == 'plain':
        return password, method

    if isinstance(password, text_type):
        password = password.encode('utf-8')

    if method.startswith('pbkdf2:'):
        args = method[7:].split(':')
        if len(args) not in (1, 2):
            raise ValueError('Invalid number of arguments for PBKDF2')
        method = args.pop(0)
        iterations = args and int(args[0] or 0) or DEFAULT_PBKDF2_ITERATIONS
        is_pbkdf2 = True
        actual_method = 'pbkdf2:%s:%d' % (method, iterations)
    else:
        is_pbkdf2 = False
        actual_method = method

    if is_pbkdf2:
        if not salt:
            raise ValueError('Salt is required for PBKDF2')
        rv = pbkdf2_hex(password, salt, iterations, hashfunc=method)
    elif salt:
        if isinstance(salt, text_type):
            salt = salt.encode('utf-8')
        mac = _create_mac(salt, password, method)
        rv = mac.hexdigest()
    else:
        rv = hashlib.new(method, password).hexdigest()
    return rv, actual_method

def gen_salt(length):
    """Generate a random string of SALT_CHARS with specified ``length``."""
    if length <= 0:
        raise ValueError('Salt length must be positive')
    return ''.join(_sys_rng.choice(SALT_CHARS) for _ in range_type(length))

def _create_mac(key, msg, method):
    if callable(method):
        return hmac.HMAC(key, msg, method)
    hashfunc = lambda d=b'': hashlib.new(method, d)
    # Python 2.7 used ``hasattr(digestmod, '__call__')``
    # to detect if hashfunc is callable
    hashfunc.__call__ = hashfunc
    return hmac.HMAC(key, msg, hashfunc)

def pbkdf2_bin(data, salt, iterations=DEFAULT_PBKDF2_ITERATIONS,
               keylen=None, hashfunc=None):
    """Returns a binary digest for the PBKDF2 hash algorithm of `data`
    with the given `salt`. It iterates `iterations` times and produces a
    key of `keylen` bytes. By default, SHA-256 is used as hash function;
    a different hashlib `hashfunc` can be provided.
    .. versionadded:: 0.9
    :param data: the data to derive.
    :param salt: the salt for the derivation.
    :param iterations: the number of iterations.
    :param keylen: the length of the resulting key.  If not provided
                   the digest size will be used.
    :param hashfunc: the hash function to use.  This can either be the
                     string name of a known hash function or a function
                     from the hashlib module.  Defaults to sha256.
    """
    if not hashfunc:
        hashfunc = 'sha256'

    data = to_bytes(data)
    salt = to_bytes(salt)

    if callable(hashfunc):
        _test_hash = hashfunc()
        hash_name = getattr(_test_hash, 'name', None)
    else:
        hash_name = hashfunc
    return hashlib.pbkdf2_hmac(hash_name, data, salt, iterations, keylen)

def pbkdf2_hex(data, salt, iterations=DEFAULT_PBKDF2_ITERATIONS,
               keylen=None, hashfunc=None):
    """Like :func:`pbkdf2_bin`, but returns a hex-encoded string.
    .. versionadded:: 0.9
    :param data: the data to derive.
    :param salt: the salt for the derivation.
    :param iterations: the number of iterations.
    :param keylen: the length of the resulting key.  If not provided,
                   the digest size will be used.
    :param hashfunc: the hash function to use.  This can either be the
                     string name of a known hash function, or a function
                     from the hashlib module.  Defaults to sha256.
    """
    rv = pbkdf2_bin(data, salt, iterations, keylen, hashfunc)
    return to_native(codecs.encode(rv, 'hex_codec'))

def _hash_internal(method, salt, password):
    """Internal password hash helper.  Supports plaintext without salt,
    unsalted and salted passwords.  In case salted passwords are used
    hmac is used.
    """
    if method == 'plain':
        return password, method

    if isinstance(password, text_type):
        password = password.encode('utf-8')

    if method.startswith('pbkdf2:'):
        args = method[7:].split(':')
        if len(args) not in (1, 2):
            raise ValueError('Invalid number of arguments for PBKDF2')
        method = args.pop(0)
        iterations = args and int(args[0] or 0) or DEFAULT_PBKDF2_ITERATIONS
        is_pbkdf2 = True
        actual_method = 'pbkdf2:%s:%d' % (method, iterations)
    else:
        is_pbkdf2 = False
        actual_method = method

    if is_pbkdf2:
        if not salt:
            raise ValueError('Salt is required for PBKDF2')
        rv = pbkdf2_hex(password, salt, iterations, hashfunc=method)
    elif salt:
        if isinstance(salt, text_type):
            salt = salt.encode('utf-8')
        mac = _create_mac(salt, password, method)
        rv = mac.hexdigest()
    else:
        rv = hashlib.new(method, password).hexdigest()
    return rv, actual_method

def generate_password_hash(password, method='pbkdf2:sha256', salt_length=8):
    """Hash a password with the given method and salt with a string of
    the given length. The format of the string returned includes the method
    that was used so that :func:`check_password_hash` can check the hash.
    The format for the hashed string looks like this::
        method$salt$hash
    This method can **not** generate unsalted passwords but it is possible
    to set param method='plain' in order to enforce plaintext passwords.
    If a salt is used, hmac is used internally to salt the password.
    If PBKDF2 is wanted it can be enabled by setting the method to
    ``pbkdf2:method:iterations`` where iterations is optional::
        pbkdf2:sha256:80000$salt$hash
        pbkdf2:sha256$salt$hash
    :param password: the password to hash.
    :param method: the hash method to use (one that hashlib supports). Can
                   optionally be in the format ``pbkdf2:<method>[:iterations]``
                   to enable PBKDF2.
    :param salt_length: the length of the salt in letters.
    """
    salt = gen_salt(salt_length) if method != 'plain' else ''
    h, actual_method = _hash_internal(method, salt, password)
    return '%s$%s$%s' % (actual_method, salt, h)


if __name__ == '__main__':
    print(generate_password_hash("Mypassword"))
```

**Comment by D1skanime** [comment]
How to use this script? I have calibre -web in a docker container but i am not realy abroved in programming. I have change the admin PW but it looks that i had typed something false and now i can't login. Where i must upplaoding this and how i start the script?

**Comment by stiko** [comment]
Add the script to a file and give it some name e.g `hash_password.py`. 
From terminal run `python hash_password.py`
The output will be your hashed password for `Mypassword` if you want to change it, modify the last line of the script.

**Comment by OzzieIsaacs** [comment]
Passwords can be changed via command line now:
https://github.com/janeczku/calibre-web/wiki/Command-Line-Interface#command-line-options

**Comment by smvb64** [comment]
> 
> 
> Passwords can be changed via command line now:
> https://github.com/janeczku/calibre-web/wiki/Command-Line-Interface#command-line-options

How do you this? I tried entering the command on Calibre portainer console but im not sure what to put in fornt of -s.  Im still pretty new to all of this.

**Comment by OzzieIsaacs** [comment]
@smvb64 I guess you are referring to a docker container installation, please ask for help at their repository

**Comment by stiko** [comment]
> > Passwords can be changed via command line now:
> > https://github.com/janeczku/calibre-web/wiki/Command-Line-Interface#command-line-options
> 
> How do you this? I tried entering the command on Calibre portainer console but im not sure what to put in fornt of -s. Im still pretty new to all of this.

Try this [here](https://manual.calibre-ebook.com/server.html#managing-user-accounts-from-the-command-line-only) inside your container
```
docker exec -ti clibre-web bash
```

**Comment by triksmelb** [comment]
Required complex password error "Password doesn't comply with password validation rules" Admin123456! was accepted.

**Comment by crispybegs** [comment]
is it possible to disable the 'forgot password' button? I hit it with sausage fingers by accident yesterday and locked myself out of my admin account, as a pw reset email never arrived. Can do without having to fix that again, for no apparent reason!

**Comment by Niko-La** [comment]
> > > > Passwords can be changed via command line now:
> > > > https://github.com/janeczku/calibre-web/wiki/Command-Line-Interface#command-line-options
> > > 
> > > 
> > > How do you this? I tried entering the command on Calibre portainer console but im not sure what to put in fornt of -s. Im still pretty new to all of this.
> > 
> > 
> > Try this [here](https://manual.calibre-ebook.com/server.html#managing-user-accounts-from-the-command-line-only) inside your container
> > ```
> > docker exec -ti clibre-web bash
> > ```
> 
>     1. using putty.exe to connect to your NAS, login in with `sudo -i`
> 
>     2. run command
>        `docker exec -ti linuxserver-calibre-web1 bash`  , note that `linuxserver-calibre-web1` is the container's name and the container should be running.
> 
>     3. run `cd /app/calibre-web`
> 
>     4. run `python3 cps.py -s admin:admin123`
> 
>     5. What I got:  `Error starting server: [Errno 98] Address already in use: ('', 8083)`
>        Can you share how to fix this? Thanks.

```
nikola@nikola:~$ docker exec -it calibre-web bash
root@8f7224cd8fa9:/# cd /app/calibre-web
root@8f7224cd8fa9:/app/calibre-web# python3 cps.py -s admin:Book1234!
Password for user 'admin' changed
root@8f7224cd8fa9:/app/calibre-web# 

```

I have succesfully done the admin password change but still getting 


so i tried to change a password for a working user which i have login for 

```
root@8f7224cd8fa9:/app/calibre-web# python3 cps.py -s Monica:Book12345!
Username 'Monica' not valid, can't change password
root@8f7224cd8fa9:/app/calibre-web# python3 cps.py -s monica:Book12345!
Username 'monica' not valid, can't change password
root@8f7224cd8fa9:/app/calibre-web# 


```

not sure what is happening.

**Comment by crispybegs** [comment]
it really should be possible to disable the 'forgot password' button, since all it seems to achieve is admin agony if you accidentally touch it

**Comment by Niko-La** [comment]
if running the linuxserver docker stack for calibre-web

              With the linuxserver docker image, you need:
`python3 /app/calibre-web/cps.py -p /config/app.db -s admin:password`

_Originally posted by @mabushey in https://github.com/janeczku/calibre-web/issues/2853#issuecomment-1975389456_

**Comment by joshajh** [comment]
also run `set +H` to ensure bash doesn't treat the `:` as a special character, and remember that `&` is a control operator so as far as I can tell cannot be used in your password as everything after that character will be treated as a command.

> if running the linuxserver docker stack for calibre-web
> 
> ```
>           With the linuxserver docker image, you need:
> ```
> 
> `python3 /app/calibre-web/cps.py -p /config/app.db -s admin:password`

**Comment by Hernersi** [comment]
> if running the linuxserver docker stack for calibre-web
> 
> ```
>           With the linuxserver docker image, you need:
> ```
> 
> `python3 /app/calibre-web/cps.py -p /config/app.db -s admin:password`
> 
> _Originally posted by @mabushey in [#2853 (comment)](https://github.com/janeczku/calibre-web/issues/2853#issuecomment-1975389456)_

Thanks, saved me some headache

**Comment by sergioalegre** [comment]
i used the script, set an strong password (tried severals), but the output is allways something like this: `pbkdf2:sha256:150000$MS8uBOem$21d7b26a190c340bfff158284145795a994b695fc7bfd6dc0c7ae6d50e110580`

**Comment by pinheirodeabrantes** [comment]
Hi!
I'm having exactly the same problem with my YunoHost installation. Could you provide me with some info on how to solve the issue?
Thanks!

**Comment by keesfluitman** [comment]
I tried changing the password with the script, succesfully did so. But still says wrong username and password. Guess ill delete the database.

**Comment by EricMFink** [comment]
> I tried changing the password with the script, succesfully did so. But still says wrong username and password. Guess ill delete the database.

I had the same problem and it was driving me up the wall. Then I tried restarting the calibre web server (after doing the password change) and it worked.
