### ISSUE TITLE
Audiobook support

### ISSUE THREAD

**Issue by Genddos** [janeczku/calibre-web#753]
good afternoon. Offer to make audio books with reference to existing books. The user downloads several files at once in a format .mp3 and service archives mp3 files into one archive. Thank you for making such a convenient script. Already started using it for the corporate library.

**Comment by hexeth** [comment]
Audiobooks would be a huge undertaking. It's a completely different type of media. I would recommend you look at BookSonic for audiobooks

**Comment by jvimedia** [comment]
Seems to be in the pipe? PR #634

**Comment by Mohammed90** [comment]
Please check PR #634 . It's already in-process.

**Comment by OzzieIsaacs** [comment]
It‘s implemented now
