### ISSUE TITLE
I would like to use Google Drive functonality of calibre web but with encryption. Possible ?

### ISSUE THREAD

**Issue by gelsas** [janeczku/calibre-web#759]
Hello,

I would like to use Google Drive functonality of calibre web but with encryption.

Is that possible ? I don't want to upload my collection unencrypted.

Is it possible to include rclone (https://rclone.org/) somehow into calibre web? Or something like that ?

**Comment by OzzieIsaacs** [comment]
From what I unterstand reading the Information on the rclone tool it doing a Sync between you local Drive and some remote storage providers. 
So it has nothing to do with Calibre-Web: you use Calibre Web with the Data on you local drive, and the rclone is doing a Backup of you Data in the cloud. If you are accessing the Data from another Computer you have to do Sync the Data with rclone to the local Drive there. Both computers have to run an instance of Calibre-Web. The only problem you could have is some Users have reported Problems if the database file is changed outside Calibre-Web, which I could not reproduce up to now. And you have to take care that syncing is done continously if you access the database from different computers at the same time.
Is that what you want to do?

**Comment by gelsas** [comment]
I just solved it myself. I use rclone on my NAS and mount my Google Drive Folder via Rclone to it.

Then I give calibre web access to the mounted folder on my NAS.

Calibre Web can access it now. And when a book is requested to view/download it automatically gets decrypted.

But thank you for the quick answer.

I wrote on a question to you on gitter, are you still on that platform?

**Comment by OzzieIsaacs** [comment]
I can‘t remember that I ever created an account there, has to be somebody else.

**Comment by magicstone1412** [comment]
> 
> 
> I just solved it myself. I use rclone on my NAS and mount my Google Drive Folder via Rclone to it.
> 
> Then I give calibre web access to the mounted folder on my NAS.
> 
> Calibre Web can access it now. And when a book is requested to view/download it automatically gets decrypted.
> 
> But thank you for the quick answer.
> 
> I wrote on a question to you on gitter, are you still on that platform?

Could you please share your rclone mount settings? I could not make it works with calibre-web docker. Thank you

**Comment by dominus-imperium** [comment]
> > I just solved it myself. I use rclone on my NAS and mount my Google Drive Folder via Rclone to it.
> > Then I give calibre web access to the mounted folder on my NAS.
> > Calibre Web can access it now. And when a book is requested to view/download it automatically gets decrypted.
> > But thank you for the quick answer.
> > I wrote on a question to you on gitter, are you still on that platform?
> 
> Could you please share your rclone mount settings? I could not make it works with calibre-web docker. Thank you

This is how:

The command `rclone mount --vfs-cache-mode=full --file-perms=0777 cloud:Calibre_folder local:mountpoint`
is how you use calibre web with rclone. all the flags are necessary for the calibre-web to see and use the metadata.db file.
