### ISSUE TITLE
sorting of newest books is based on last change instead of date added

### ISSUE THREAD

**Issue by n0valis** [janeczku/calibre-web#76]
Well the headline says it already. I find it a bit unfortunate that every time I edit the metadata the book appears at the top of the newest books. 
I think the newest book list should be based on the date added to the library. Same as Calibre does...

**Comment by n0valis** [comment]
Is there a way to easily change that?
My whole order is now messed up with this setting.
I really need to have a sorting by 'last added' because I can't find them anymore in the sheer mass of all the books after have done a couple of editing/book conversions etc...

Is this something I  could change?

**Comment by n0valis** [comment]
I should say the name of the column in the db is 'timestamp' - and you used 'last_modified'

**Comment by n0valis** [comment]
yeah ok, found it myself. search and replace in web.py ;)

**Comment by OzzieIsaacs** [comment]
changed it with the newest commit.
