### ISSUE TITLE
Possible to automatically create book shelves from series ?

### ISSUE THREAD

**Issue by gelsas** [janeczku/calibre-web#760]
Could the functionality be added for an admin to toogle that Bookshelves get automatically created form a series?

It is quite time consuming to always add the new ebooks/animes of a series manually to a bookshelf.
This costs even more time when you have multiple frequently updated series.

**Comment by gelsas** [comment]
Or could someone point me in the right direction on  where I can learn to code such an automated thing?

**Comment by OzzieIsaacs** [comment]
You can now perform a advanced search, search for a specific series. Afterwards click on the add to shelf button in the search results, all books are added to the shelf (books already in the shelf are skipped)

**Comment by auspex** [comment]
This really doesn't answer the original request. It's not "automatic" when you have to search first.
