### ISSUE TITLE
CaliBlur! minified code is twice in file

### ISSUE THREAD

**Issue by OzzieIsaacs** [janeczku/calibre-web#762]
Looks like the minified code is twice in caliblur.min.css: 
![grafik](https://user-images.githubusercontent.com/6438895/50994858-a94ad780-151d-11e9-8651-3f79ba174451.png)
@hexeth, @leram84 could you please check and fix this.
Thanks.
And the debug console is complaining about an error:
![grafik](https://user-images.githubusercontent.com/6438895/50994985-06468d80-151e-11e9-9608-02f17dc3e6e8.png)
Saying color expected but only # found. A look in the source code looks like if its not correct:
`pointer-events:none;color:#}` (meaning the code is wrong)
Could you please also check this.
Thanks

**Comment by leram84** [comment]
ugghh... sorry, no idea how that happened. Ill fix it w the next pr for the internal class issue

**Comment by OzzieIsaacs** [comment]
No problem, I just wanted to document it (not in the old issue, it‘s getting otherwise to complicated)

**Comment by hexeth** [comment]
Fixed in latest PR
