### ISSUE TITLE
Feature Request: Make PWA Installable

### ISSUE THREAD

**Issue by unleashit** [janeczku/calibre-web#763]
Thank you very much for your work! For me the only thing I can think of that its currently lacking is the ability to install on the homescreen of my tablet. If you're interested, its very easy to add the feature. See: https://developer.mozilla.org/en-US/docs/Web/Apps/Progressive/Installable_PWAs

Basically you just need to add a webmanifest file referencing the right icon. That alone would make it work in iOS and Firefox mobile on Android. If you also want to support Chrome for Android, you'd need to also add basic a service worker.

A service like https://realfavicongenerator.net/ can take the current favicon and generate all the files needed (besides the service worker).

**Comment by vhfmag** [comment]
Whenever this issue is tackled and a service worker is implemented, it would be awesome to allow books to be downloaded and made available for reading offline :)

**Comment by OzzieIsaacs** [comment]
As many people having ideas on how to expand the project, and I have limited time, I have to priorize and also to limit the features which can be included in calibre-web, I decided not to implement it.

**Comment by joseph-cheung** [comment]
Just an installation of pwa app icon with no extra functions is of great help.
