### ISSUE TITLE
Allow users added by admin to choose their own passwords via email

### ISSUE THREAD

**Issue by donicrosby** [janeczku/calibre-web#768]
I have public registration open on my server. While it's nice that people I point it to can register themselves, I also have found a few people that signed up that I don't recognize and they have scraped my entire instance. 

I have SMTP setup and working on my instance, would it be possible for an admin to set the users email field and not their password field and send the password and username setup to that email?

**Comment by OzzieIsaacs** [comment]
Would be an option.
With public registration you can limit the servers from which people can register by filling out the for in the smtp server setup page:
![grafik](https://user-images.githubusercontent.com/6438895/51082481-e2df3680-1707-11e9-8833-d2f706bc6619.png)
So you could limit registrations only to users from "yahoo.com". You can use wildcards: ? for one random character and * for any number of characters. But indeed you can not limit the characters before the @sign, so this might not what you are needing.

**Comment by OzzieIsaacs** [comment]
Meanwhile a "forgot password" option is available, and admins can generate and e-mail passwords with the click of a button in the edit user section. So I consider this a implemented.
The registering e-mail domains can be white and blacklisted and you also can do something like allow/dissallow email addresses from: "*-myfamily@domin.com"
