### ISSUE TITLE
Disable the Discover (Random Books) section that inserts itself on the top of every page

### ISSUE THREAD

**Issue by mlg9000** [janeczku/calibre-web#77]
The Discover (Random Books) section is a super annoying UI distraction that takes valuable screen space from the stuff I really want to see.  The default page should be new books, sorted by when they were added (not modified) only.  The other pages should only show what I clicked on to view.  The discover page can remain on it's own.  At the very least there should be a toggle option to turn this on/off, as I'd suspect most people would want this off by default.

**Comment by OzzieIsaacs** [comment]
With the newest version you can disable enable the menus on the left side as you want. Just go (as admin) to the change user page and you can tick everything on and off

**Comment by mlg9000** [comment]
That works but it's not user configurable as you need an need an admin to do it for you.

**Comment by OzzieIsaacs** [comment]
Changed it, now normal user can configure the sidebar contents.

**Comment by mlg9000** [comment]
Works thanks!
