### ISSUE TITLE
Caliblur smtpserver setup page UI issues

### ISSUE THREAD

**Issue by OzzieIsaacs** [janeczku/calibre-web#773]
I found two small UI issues in the smtp server setup page:
There are two texts which are overlapping.
![double_text](https://user-images.githubusercontent.com/6438895/51197797-cd7a3000-18f2-11e9-84dd-dd8ebc0a174e.png)

And I think the margin from Allowed Domains for registering text to the button down the page should be increased:
![remote_register](https://user-images.githubusercontent.com/6438895/51197856-ea166800-18f2-11e9-9774-9d6a27f46971.png)

Both issues occurs if public registering is enabled. After this I'm sure I saw all pages and everything else is more than fine.
@hexeth and @leram84 could you please take a look?

**Comment by leram84** [comment]
yeah, i can see the issue, and i can fix everything in your ss, but we are having trouble creating the actual table because when i go to add a domain it just refreshes the page to a blank white page. Nothing to do with the theme as this happens in default theme too... Not sure what is causing that

**Comment by OzzieIsaacs** [comment]
Is fixed (a comma got somehow lost)

**Comment by OzzieIsaacs** [comment]
Thanks a lot @leram84
