### ISSUE TITLE
calibre-web Basic Konfiguration

### ISSUE THREAD

**Issue by marvfr** [janeczku/calibre-web#779]
Hey guys,

i just installed the the calibre web paket on my NAS.

After that I tried to connect over http://.... 

Now it tells me to enter the path of my databank 

I tried everything but it is always saying path is not correct .... 

I don´t know which format or what or how I should put in the path ...

Thanks for your help ...

**Comment by OzzieIsaacs** [comment]
Many NAS I know showing the user a path like /mydata/..... In reality the path isn't that but its in let's say /mnt/userdisk somewhat/freakynumbers/mydata.
You need to enter the path from "the reality". Could you give us more details, then helping would be easier. 
What did you install? docker or "plain python installation?" 
Do you  having access via ssh console? (could make things easier to find)  
Do you have a Calibre-libraryfile (metadata.db)? (It's a common mistake not to have one)
Which brand of NAS do you use (could help to find the normal used pathes)?

**Comment by marvfr** [comment]
First of all THANKS for helping!

I installed it via docker yes 

Do you having access via ssh console?
I guess no ...

Do you have a Calibre-libraryfile (metadata.db)?
Yes I copied it from my pc on the server 

Which brand of NAS do you use (could help to find the normal used pathes)?
Synology 

Sorry for being that stupid :-D

**Comment by OzzieIsaacs** [comment]
In the technosoft docker manual there is a hint for synology users:

> for Synology Users - don't map a top-level volume directory from the NAS as /books volume, e.g. /volume1/books because it results into problems with directory permissons. Create instead a subdirectory calibre at /volume1/books and map then /volume1/books/calibre as volume for /books

I think the example:

> docker create --name=calibre-web --restart=always \
> -v /volume1/books/calibre:/books \ ...
fits to these hint, so you have to enter the mapped path which means entering: `/books`
If this isn't working out, please open an issue at the relevant docker repro, because I don't use docker, and have no synology NAS. And if solved please close the issue, thanks a lot. 

Happy ebook browsing

**Comment by marvfr** [comment]
No sure if I understand it right.

Where do I put that ? 
"docker create --name=calibre-web --restart=always "

I already have a docker.

Lets say I have a folder project with subdirectory projektbooks

Does the path I have to put in like the following:

-v /volume1/books/calibre:/books\project\projektbooks ? 

It isn´t working unfortunatly... 

Sorry for beein that stupid xd

**Comment by OzzieIsaacs** [comment]
The docker stuff has to be done during creating the docker container. The docker container is creating it‘s own environment which does not know anything from the outside. To make the database accessible to the container contents it has to be mapped somehow, this is done with the docker create command. 
@Technosoft2000 could you please help out?

**Comment by marvfr** [comment]
So what I have done I loaded a paket in the docker on my NAS and than I started a container and that one is running now ... To start the container I put down a path for the folder(project/projektbook) and a Mount path(/opt/calibre/library). 

and I copied a file named metadata.db into that folder.

That´s what I have done so far. 

So now when I am on the website it is asking for the library configuration and where is databank is saved. 


I also could create a complete new one if that´s easier ... I would have no problem with that ... 


Thanks

**Comment by OzzieIsaacs** [comment]
I guess it's a problem to use command line arguments from one software for the other software. I tried to read a bit. On the technosoft2000 docker page, there is a whole section for Synology users (https://hub.docker.com/r/technosoft2000/calibre-web/) to me, it looks like you have to do something on the commandline (the ssh console question from the beginning). 
So I'm sorry, I have nothing to test it, nor do I have any experience in installing docker container on NAS. If I try helping you this will take a long time and with highly probability would lead to no solution as I'm a beginner in this topic too.
Ccould you please open a issue at the corresponding docker repro you want to use.

**Comment by marvfr** [comment]
Yeah it looks like I have to do quite a lot on my NAS ... 
I thought it would be just an quick install and it would run...
Anyways thanks for helping me! I really appriciate!

Have a great day mate!

**Comment by OzzieIsaacs** [comment]
I'm sorry I can't help you
