### ISSUE TITLE
[Feature request] prevent guest from reading books or downloading pdf

### ISSUE THREAD

**Issue by jvimedia** [janeczku/calibre-web#780]
prevent guest from reading books or downloading pdf

Please add button:
[allow viewing book content via webbrowser]

**Comment by OzzieIsaacs** [comment]
I'm not sure if I understand the request:
Currently it's possible to prevent guests from reading or downloading books by removing the setting 'Allow Downloads'.
What should be changed?

**Comment by OzzieIsaacs** [comment]
No response for long time, so I'll close the issue

**Comment by jvimedia** [comment]
Hi, sorry I missed your reply.
The user which is not allowed to download the book is still allowed to read the book. I want that a user can be also denied to read the book. Since a pdf could be still downloaded this way.

**Comment by jvimedia** [comment]
So a guest or any other user can only see the cover and information about the book.

**Comment by jvimedia** [comment]
Because I can simply circumvent the disable download option by choosing a pdf and clicking download in the PDF viewer

**Comment by OzzieIsaacs** [comment]
I had this discussion, during the change towards the current behavior. I knew that this would happen at some time

**Comment by OzzieIsaacs** [comment]
The Download Button is now removed for guests not having download rights.
