### ISSUE TITLE
[Feature request] magic login link QR code

### ISSUE THREAD

**Issue by jvimedia** [janeczku/calibre-web#781]
It would be great to not only have a link which we have to type down manually but also a QR code which could be scanned with a smartphone to log in. (opens the link then in browser)

**Comment by vigri** [comment]
This seems to be doable by using the python lib 'qrcode'.
I can take a look at that.
@OzzieIsaacs would you mind if we would add this dependency?

**Comment by OzzieIsaacs** [comment]
yes you could use this library, but please make it optional, so if someone hasn‘t installed qrcode can still use calibre-web

**Comment by OzzieIsaacs** [comment]
No feedback for one year, closing the issue
