### ISSUE TITLE
[Feature request] Incorporate calibredb for uploading epubs to enable DeDRM plugin

### ISSUE THREAD

**Issue by Metarded** [janeczku/calibre-web#782]
By using calibredb for uploading enables the DeDRM plugin. Currently, no drm-protected content is readable when uploaded.

**Comment by OzzieIsaacs** [comment]
You can use calibredb for your uploads if you want. Calibre-Web will not replicate all the features calibre has for editing and modifying books. 
I see this outside the scope of the project
