### ISSUE TITLE
[Feature Request] Personal notes/reviews

### ISSUE THREAD

**Issue by larabr** [janeczku/calibre-web#784]
I'd like to be able to write down some notes about a given book, something like a private review.
I guess the concept could then be extended to make the notes visible to other users as well, even though I'm not really interested in that.

Is this something you might consider for the future?

**Comment by OzzieIsaacs** [comment]
The project is using calibre database as base. You could use the comments of the book to store the information's you want to store, or you could use one of the custom columns, to do what you want. If you declare this column as mature-content you could hide it to all other users (if any). In this case there is only one field for all users of the database. 
I don't intend to extend the program in that way.
