### ISSUE TITLE
OPDS feeds aren't the same location/format as calibre

### ISSUE THREAD

**Issue by mlg9000** [janeczku/calibre-web#79]
It seems that several OPDS capable apps expect calibre format opds feeds to work, which calibre-web currently does not provide.   An example is Calibre Companion, a pretty widely used OPDS app on Android, obviously geared towards a calibre server.  It could be nice if calibre-web could offer a opds feed in the same format/location as calibre server so that these apps would work with it too.  The first issue is the feed uri, /opds (calibre) vs /feed (calibre-web).  I've used mod_rewrite to get past this which allows me to see the main feed categories, but these are not clickable links like calibre feeds so I'm unable to browse them any further. to get to any books.

**Comment by mlg9000** [comment]
In Calibre Companion I'm able to click on categories in the feed now to see books now, but not actually see covers or download them.  

Ebookdroid generally works except the series are split into multiple pages and I'm unable to browse beyond the first page.

I haven't tested other OPDS clients or IOS clients yet

**Comment by OzzieIsaacs** [comment]
I did a change which could hep to display the covers. I also changed the download link, so maybe this is working now, too (I have no Android phone to test it).
Ebookdroid: Do you have more than the configured no. of "NEWEST_BOOKS" (default 60) series? The expected behavior in this case is, that the data is loaded step by step (in other reader scroll to end, or similar)
I checked a longer time ago kybooks on ios and marvin is working fine. I see a problem with chunky reader I will check that later. I hope the last fix helps you a bit.  I try to do more testing in January.

**Comment by mlg9000** [comment]
Ok, I've tested this on multiple apps, still see issues:

Ebookdroid (android) and Mavin (IOS) the behavior is the same.  I'm able to see the first 60 items in any list.  So the Authors, categories list, and series list I have more than 60 items but can only see the first 60.  Trying to load more results in an error.  Otherwise these two work.

Calibre Companion still does not work at all. It's meant to talk with Calibre specifically and not just OPDS so I suspect it's very picky about how the feed is structured.  I'm able to see all the top level directories in the feed and I can see (the first 60) items under those main directories, but I see no covers and can't download books, and sub directories all show up as empty.

**Comment by OzzieIsaacs** [comment]
Calibre Companion seems to be a bit buggy. It can't deal with spaces in links (adds additional "%25") to the link. Covers aren't loaded, because Calibre companion seems to to care about the covers which are published (../cover/...) , instead asking for "/cover_90_90/" (I assume 90_90 is the image size it wants to have). 
I take a look what I can do programm around this

**Comment by OzzieIsaacs** [comment]
Metadatas are also not loaded via the opds published link. A request to 

`/ajax/book/bf87-4902-b1b0-a762c8359aa4?id_is_uuid=true` 

is transmitted

**Comment by OzzieIsaacs** [comment]
Finally it should work now, feel free to check and comment

**Comment by mlg9000** [comment]
It seems that I can see all my books now but I can't download anything in any client I've tested.  In ebookdroid all I see is mobi, when none of my books are that format.

**Comment by OzzieIsaacs** [comment]
Please try the newest version.
If you are using anonymous user, than you have to give the anonymous user download rights. This can be done as admin user, than go to the administration page and edit the guest user. Tick download "Allow Download", and it should hopefully work now without errors.

**Comment by mlg9000** [comment]
I'm on the latest version and using a user with full permissions. Since the last updates it seems to work with everything except Calibre Companion now.  In Calibre Companion with my reverse proxy I can see all my books fine /w covers, I just can't download anything.  There are no errors I can see.  Bypassing the proxy I can't even do that. It connects with no errors but doesn't list anything.  In the calibre-web.log I see the following errors:

[2017-01-15 22:35:14,663] {/opt/calibre-web/vendor/flask/app.py:1587} ERROR - Exception on /opds/osd [GET]
Traceback (most recent call last):
  File "/opt/calibre-web/vendor/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/calibre-web/vendor/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/calibre-web/vendor/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/calibre-web/vendor/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/calibre-web/vendor/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/calibre-web/cps/web.py", line 196, in decorated
    return f(*args, **kwargs)
  File "/opt/calibre-web/cps/web.py", line 423, in feed_osd
    xml = render_template('osd.xml')
  File "/opt/calibre-web/vendor/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/opt/calibre-web/vendor/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/opt/calibre-web/vendor/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/opt/calibre-web/vendor/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/calibre-web/cps/templates/osd.xml", line 11, in top-level template code
    template="{{url_for('feed_search')}}?query={searchTerms}"/>
  File "/opt/calibre-web/vendor/flask/helpers.py", line 332, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/opt/calibre-web/vendor/flask/app.py", line 1811, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/opt/calibre-web/vendor/flask/helpers.py", line 322, in url_for
    force_external=external)
  File "/opt/calibre-web/vendor/werkzeug/routing.py", line 1758, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'feed_search'. Did you mean 'feed_cc_search' instead?

**Comment by OzzieIsaacs** [comment]
We are getting closer....  I fixed that bug and found the problem with the reverse proxy (and fixed it also).

Now stupid question regarding "cc is not showning anything without proxy": I know this behavior, in case of disabled anonymous browsing. I found no option to activate user and password authentification. And it seems that there is no automatic password popup. Should this work, somehow?

**Comment by mlg9000** [comment]
With the latest change everything except connecting directly with Calibre Companion works now.  I tried seeing if there were any errors in any logs or the client but there were none.  I just don't see anything in the index, although if I search it does show me results but no covers or metadata and I can't download.  It doesn't prompt for a password either ( a pop up).  Other clients direct connections work. As far as I'm concerned none of that matters as I only plan on connecting via my (now fully working) proxy setup.  I'm perfectly happy to close this ticket out and write off the direct connection issues to a problem with the client.  It's a fairly confusing interface with inconsistent behavior.  I'm using it because originally it was the only game in town for OPDS on Android originally and later on didn't have performance and other issues.  That's not the case anymore, so I'm not sure if I'll even stick with using it much longer.  I'm perfectly willing to keep testing the direct connection stuff too though.

Thanks for all the work on this!  Now just need LDAP auth.. ;)

**Comment by OzzieIsaacs** [comment]
Working searching function was a bug (response even if not logged in). I found the reason why its not working directly. CC expects a "Digest access authentication" and calibre-web only provides a "basic access authentication". All (all!) other clients are fine with this, so I'm happy not having to implent it. Regarding LDAP auth: This is one of the last priorities of my own ToDo list, don't expect it soon.
