### ISSUE TITLE
Updating Calibre-web Removes Calibre-web

### ISSUE THREAD

**Issue by JeroenHoekstra91** [janeczku/calibre-web#790]
When updating Calibre-web today (30-01-2019) the auto updater was able to download and replace all files but after reloading the page, I was presented a 502 Bad Gateway error. This error was caused by the folder with all the calibre-web files being deleted.

I'm not sure if a previous version of the auto update is responsible for this and a newer version has already been created which fixes this problem.

**Comment by MephistoXoL** [comment]
to me too, the updater has deleted the whole directory

**Comment by OzzieIsaacs** [comment]
Oh, oh. I'll take a look

**Comment by OzzieIsaacs** [comment]
I broke (or github) broke the updater. After creating a tag or release the naming scheme of the master-zipball file changes (absolutely logically) and the old updater doesn't find the downloaded zipball for update anymore and updates to nothing -> I deleted the release and tag, now the name of the zipball is the old one, you can update to the new updater.
An everlasting problem....

**Comment by OzzieIsaacs** [comment]
No the files in that folder are the new one‘s. The app.db with all settings is not saved/backuped

**Comment by MephistoXoL** [comment]
Ok... so I have to do a scratch installation and configuration again.. right?

**Comment by OzzieIsaacs** [comment]
Yes, I‘m sorry. I didn‘t check it enough. If you have a backup, or an older version of the app.db file you can use it. They are all compatible.

**Comment by MephistoXoL** [comment]
Urbackup is my friend!!! :) thx for the hard work

**Comment by JeroenHoekstra91** [comment]
Unfortunately i had to reinstall and reconfigure calibre web entirely. Is it safe to auto update in the future? Aside from all arguments in support of backups in general, i will make a backup of the app.db file prior to updating the software from now on XD

Many thanks for keeping the code of calibre web updated!

**Comment by OzzieIsaacs** [comment]
Yes it‘s safe again to update. I also included some error handling to prevent issues like this in the future

**Comment by JeroenHoekstra91** [comment]
Amazing. Thank you very much.
