### ISSUE TITLE
Latest update breaks git link, won't grab latest dev commits

### ISSUE THREAD

**Issue by rg9400** [janeczku/calibre-web#793]
I cloned calibre-web using git. When I grabbed the latest update, it let me switch between Master and Nightly update channels. Master shows version 0.60, Nightly shows 1/27/19 1:32 AM (I am in the Central Timezone). 

It seems like my calibre-web grabbed the dev commit d81cb2927abcba3c4d198ecce9dca78550f676e1 (Update Test results), but is missing the 5 commits after that. Running the updater via the UI results in it saying there is no new version (both on Nightly and Master channels). 

Thinking I broke something, I shut down calibre-web and tried to pull the latest version using `git pull`. It gave an error `fatal: not a git repository  (or any of the parent directories): .git`

I tried reinstalling calibre-web multiple times, but it seems like git always breaks after running the updater from the UI, and the UI cannot grab the latest commits after `Update Test results` in the develop channel.

**Comment by OzzieIsaacs** [comment]
Update testresults is the newest commit you should get, the other commits are on a development branch and not published yet. 
I have to do some work before merging this commits to master. So everything is fine ( except the git pull part)

**Comment by OzzieIsaacs** [comment]
If you‘ve updated with the ui updater it deletes all folders it does not know except a possible vendor folder. So afterwards the hidden .git folder is deleted and git does not recognized the folder as a git repository.

**Comment by OzzieIsaacs** [comment]
I‘ll add the .git folder to the exceptions, which aren‘t deleted
