### ISSUE TITLE
GDrive Question

### ISSUE THREAD

**Issue by gelsas** [janeczku/calibre-web#796]
When I setup Calibre web with GDrive, will it pull everytime I visit the site all the preview images from GDrive (and cause longer loading times) or are the images pulled once and then cached locally in Calibre web ?

**Comment by OzzieIsaacs** [comment]
They are not cached locally

**Comment by OzzieIsaacs** [comment]
I decided not to implement this, because if you have the space to cache the covers locally, than you can have the database also locally.

**Comment by gelsas** [comment]
Oh okay. 

I have a lot.of cbz comic books that's why my library is 250 GB big. And I do not have that much space left locally. Thats why I am using GDrive.

So locally caching the covers would have been perfect, because that only would need a few (hundreds) MB.

**Comment by fabwu** [comment]
I would like to reopen this issue because I wait forever until all my covers are loaded.

Maybe we can create a small thumbnail for the overview and cache these. That should use only some kilobytes.
