### ISSUE TITLE
Help With Google Drive Calibre folder

### ISSUE THREAD

**Issue by truitt661** [janeczku/calibre-web#798]
Once again, Ubuntu 18.04+nginx+no docker

I am almost there and just need help to set this up. With the Google Drive Calibre folder I see the folder that have my books in and I have the Watch Channel ID connected also. The only thing is that the books are not uploading on calibre app. So, im assuming that i will need to somehow sync the google drive folder. to ubuntu to connect it to the app. 

What is a good solution for this. I tried rclone but i am not having much luck with it

**Comment by OzzieIsaacs** [comment]
You have to upload the books initially. If you add books later via the Calibre-Web UI they are uploaded automatically. 
I did the initial upload just with the web browser, thught this would be quicker than searching for years for a tool
