### ISSUE TITLE
Enhancement: Link to Amazon or Goodreads

### ISSUE THREAD

**Issue by JamieBarrows** [janeczku/calibre-web#80]
It would be nice to have a link to the books goodreads or amazon page if the book has the appropriate IDs.

**Comment by OzzieIsaacs** [comment]
Amazon Links should work with the latest version now. Goodreads links seem to my like they depend on some plugins, and I don't know what's happening exactly, so I didn't implement it.

**Comment by JamieBarrows** [comment]
Thanks. The amazon links work perfectly. Don't know any python myself, but I am a developer (c# for work at the moment). So I took a look at what you coded and was able to adapt it to the goodreads ids as well.
The goodreads stuff is a calibre plugin, but the url is pretty simple. 
>https://www.goodreads.com/book/show/29613215


I added the following goodreads sections to the if statements in my local copy and it worked perfectly.

    def formatType(self):
        if self.type == "amazon":
            return u"Amazon"
        elif self.type == "isbn":
            return u"ISBN"
        elif self.type == "doi":
            return u"DOI"
        elif self.type == "goodreads":
            return u"Goodreads"			
        else:
            return self.type

    def __repr__(self):
        if self.type == "amazon":
            return u"https://amzn.com/{0}".format(self.val)
        elif self.type == "isbn":
            return u"http://http://www.worldcat.org/isbn/{0}".format(self.val)
        elif self.type == "doi":
            return u"http://dx.doi.org/{0}".format(self.val)
        elif self.type == "goodreads":
            return u"http://www.goodreads.com/book/show/{0}".format(self.val)			
        else:
            return u""
