### ISSUE TITLE
Upload causing segfault [Docker]

### ISSUE THREAD

**Issue by brandonmccarthy** [janeczku/calibre-web#802]
Uploading a file of any type and size causes segfault using the linuxserver/calibre-web:latest image. Calibre-web version 0.6.0

root@c05721fc5328:/$ python /app/calibre-web/cps.py
[2019-02-05 20:59:16,795] INFO in web: Starting Calibre Web...
[2019-02-05 20:59:16,896] INFO in server: Starting Gevent server
::ffff:127.0.0.1 - - [2019-02-05 20:59:21] "GET / HTTP/1.1" 302 604 0.007768
::ffff:172.18.0.12 - - [2019-02-05 20:59:27] "GET / HTTP/1.1" 200 68167 0.295588
Segmentation fault (core dumped)

Note this is with debug logs. I can build a new image with strace and use it to take a look to see what it's doing when it segfaults. I've uploaded massive files before with no issue, this is a recent issue that's probably happened in the past few months.

**Comment by OzzieIsaacs** [comment]
Duplicate #789. Could you please open an issue at the linuxserver docker repro, seems to be a problem related to docker

**Comment by brandonmccarthy** [comment]
Closing as dup.
