### ISSUE TITLE
Use relative URLs instead of absolute

### ISSUE THREAD

**Issue by toddpalino** [janeczku/calibre-web#807]
It appears that all of the HTML content uses absolute paths for URLs (starting with a "/"). This makes it difficult to proxy calibre-web underneath another server. For example, I want to use a common Apache server to provide a SSL frontend for multiple services that are running. It can probably be worked around by using mod_proxy_html, but this is processing-intensive.

Opening the issue for any discussion before I try and spend time working on a fix.

**Comment by OzzieIsaacs** [comment]
There is a working example on how to use Apache for reverse proxying in the wiki, no need to change anything

**Comment by toddpalino** [comment]
Perfect. I somehow missed this
