### ISSUE TITLE
Auto-Assign Categories to Shelf

### ISSUE THREAD

**Issue by BuksheeTester** [janeczku/calibre-web#809]
Are there any plans or is it possible to auto-assign a category to a public shelf?

In my instance, I have ebooks imported into Calibre with certain tags that I can then use to identify those books in the Calibre-Web categories section to then manually add them to certain shelves. 
It would be really helpful if there was a way to automate this so that any ebook with a particular tag/category assigned is then dropped into a certain shelf, public or otherwise.

Hopefully, I explained that well enough, my apologies if not. Just let me know and I will try and explain this better.

Also on a second note, I was wondering if there are plans to add the ability to login using some Oauth options? Quite a few of my web apps are working with Plex Oauth that only allow friends/family on my shared list to access those sites.

**Comment by OzzieIsaacs** [comment]
It's a duplicate of #760. 
I'm currently planing to have the the filtering requests fulfilled as next topic.

There is an oauth login in the pull requests (for google and github) I'm currently merging it (having some trouble, because I want to have it optional and I refactored the whole code).

**Comment by BuksheeTester** [comment]
Perfect. Thank you for responding so quickly.
