### ISSUE TITLE
It would be nice if calibre-web could update itself from git

### ISSUE THREAD

**Issue by mlg9000** [janeczku/calibre-web#81]
Enhancement request to add the ability to self update from git

**Comment by OzzieIsaacs** [comment]
I'm now happy with the updater. In the admin section you can check if a new version is available, and afterwards update the files

**Comment by bodybybuddha** [comment]
@OzzieIsaacs - Great job on the update feature.  Worked like a champ.

**Comment by mlg9000** [comment]
The updater indeed works well.  Any chance it could be an automated option?  So check for an update say once a day and upgrade if one is available?

**Comment by OzzieIsaacs** [comment]
Currently there are changes planned (dependencies via pip), which require attention from the user, and I'm afraid that autoupdater will break the system. The docker image is also a issue regarding this feature. I'm willing to include it, when Calibre-web is more stabile. And I'm happy now that we don't have access rights problems

**Comment by OzzieIsaacs** [comment]
Currently autoupdater will not be implemented (code is to unstable, It's broken to often)
Maybe later
