### ISSUE TITLE
Recently added books show whether option checked or not.

### ISSUE THREAD

**Issue by MrMxyzptlk** [janeczku/calibre-web#810]
Recently added books show whether checked or not.

Windows 2016
Latest version of Calibre-Web
No additional users other than admin
Recent books unchecked for admin and new users
Calibre-Web restarted...Chrome reloaded.

Not sure what else to check?

**Comment by OzzieIsaacs** [comment]
For me it's working
Uncheck "show recent books" in users settings, press save. Option disappears (after reloading page)
Uncheck "show recent books" in admin section admin user, press save. Option disappears (after reloading page)
Uncheck "show recent books" in admin section UI configuration, Default configuration for new users press save. Create new user, save. Logout, login as new user option is invisible.
?

**Comment by OzzieIsaacs** [comment]
Not reproducable
