### ISSUE TITLE
Error when reading CBZ/CBT/CBR comics with subfolders and non-image files in browser

### ISSUE THREAD

**Issue by silentArtifact** [janeczku/calibre-web#812]
I've tried this with known-working comic files, each page displays `Page #1 (<file_name_within_archive>) Is corrupt or not an image.` I'd _love_ for this functionality to work, is there any known workaround for this?

**Comment by OzzieIsaacs** [comment]
This error indicates that the graphic file could not be read. Could you please open the cbz file with a normal zip file viewer and check the fileformat of the graphic files (jpg and svg should work). If this is okay please try to open the first from the archive with a normal graphics viewer. If this is also not the problem, the archive could use some "special" zip file feature (I'm not sure if the viewer suupports all zipfile features). In this case I would be great to get  a non working file via private email message.

**Comment by silentArtifact** [comment]
Alright, I tried with another, it's definitely just full of JPGs. I've sent you the file via a link in email. Thanks for the help!

**Comment by OzzieIsaacs** [comment]
Okay: The error message is `Page #1 (<non image filename or foldername>) Is corrupt or not an image.`
So workaround is put the image files within the cbz file in the root folder without any subfolders. And probable also delete thumbs files and and other non image files within the archive.
I'll improve the file handling

**Comment by silentArtifact** [comment]
Gotcha. I may have to wait for an alternative, then; I use Mylar to embed
metadata in my comics, and that's the format it structures them in.
Hopefully at some point it'll work with that as well! In any case, thanks
for looking into it!

**Comment by OzzieIsaacs** [comment]
There had been several issues: 
- .cbz files with "no compression", haven't been handled properly
- non image files are now handled properly
- for cover generation the first image file is now taken into account, and not the first file as before
Please check, with the newest commit, it should work now.

**Comment by silentArtifact** [comment]
This is exciting! Thanks for working on this, I'll check it out as soon as I can!
