### ISSUE TITLE
403 for EPUB but not PDF

### ISSUE THREAD

**Issue by kurankat** [janeczku/calibre-web#813]
I'm experiencing a problem where trying to read the EPUB version of a book just hangs after loading the epubjs reader. PDFs render just fine.
On looking through the logs, I notice that the server is responding with a 403 to the request for the book. I have copied part of the log below. 
```
::ffff:192.168.20.215 - - [2019-02-15 17:53:21] "GET /book/829 HTTP/1.1" 200 3867 0.029016
::ffff:192.168.20.215 - - [2019-02-15 17:53:21] "GET /static/js/details.js?q=4ece15d HTTP/1.1" 200 2893 0.003649
::ffff:192.168.20.215 - - [2019-02-15 17:53:23] "GET /read/829/epub HTTP/1.1" 200 4015 0.017296
::ffff:192.168.20.215 - - [2019-02-15 17:53:23] "GET /static/css/fonts/fontello.woff?60518104 HTTP/1.1" 200 6334 0.003751
::ffff:192.168.20.215 - - [2019-02-15 17:53:23] "GET /download/829/epub/file.epub HTTP/1.1" 403 1019 0.012699
```
I'm using Linuxserver's Docker image, so I can't tell for sure that it's not an issue of the Docker image instead.

**Comment by OzzieIsaacs** [comment]
Line 85 in read.html
`bookUrl: "{{ url_for('get_download_link_ext', book_id=bookid, book_format="epub", anyname='file.epub') }}",`
Anyname has no representation in the python route.

**Comment by OzzieIsaacs** [comment]
I checked it, for me (on "normal" installation) it's working. I get the file, if the file is not existing i get a 404 error as expected. Error 403 means forbidden. Could you please try to enable anonymous browsing and give download rights to the guest user and try again? This would help me to locate the problem.

**Comment by kurankat** [comment]
Yes, allowing downloads did the trick. I allow anonymous browsing already as this is a LAN-only installation, but the guest user did not have download rights.
Sorry to waste your time with a non-bug!
It surprised me that this was the issue, since PDFs load OK without it.
Thanks so much for your help!
