### ISSUE TITLE
Port error when deploying 

### ISSUE THREAD

**Issue by paulmorabito** [janeczku/calibre-web#814]
Hi,

I'm trying to deploy the linuxserver docker via a kubernetes cluster and I'm getting the following error:

Traceback (most recent call last):
File "/app/calibre-web/cps.py", line 13, in <module>
from cps.server import Server
File "/app/calibre-web/cps/server.py", line 25, in <module>
import web
File "/app/calibre-web/cps/web.py", line 36, in <module>
import ub
File "/app/calibre-web/cps/ub.py", line 64, in <module>
DEFAULT_PORT = int(os.environ.get("CALIBRE_PORT", 8083))
ValueError: invalid literal for int() with base 10: 'tcp://10.43.76.92:8080'
Traceback (most recent call last):
File "/app/calibre-web/cps.py", line 13, in <module>
from cps.server import Server
File "/app/calibre-web/cps/server.py", line 25, in <module>
import web
File "/app/calibre-web/cps/web.py", line 36, in <module>
import ub
File "/app/calibre-web/cps/ub.py", line 64, in <module>
DEFAULT_PORT = int(os.environ.get("CALIBRE_PORT", 8083))
ValueError: invalid literal for int() with base 10: 'tcp://10.43.76.92:8080'

I've tried port 8083, 8080, actually any port and it gives the same error. This is using the version pulled from the latest tag.

Any help would be very appreciated!

**Comment by OzzieIsaacs** [comment]
Looks like you entered 'tcp://10.43.76.92:8080' or somehow the value is changed to this value in DEFAULT_PORT env-value. The value should only be the port number -> '8083' in our case

**Comment by paulmorabito** [comment]
Something is very strange. It's definitely set to only 8083 and it gives
that error. Even when I don't specify a nodePort for accessing outside the
cluster, I get the same error. Something, somewhere is not reading the port
correctly. I've got the container running unber a Rancher cluster in
Kubernetes. If you have any idea how I can debug this then please let me
know.

Thanks

**Comment by OzzieIsaacs** [comment]
I have no clue about the whole dockerstuff, please ask at the linuxuser docker container for help

**Comment by paulmorabito** [comment]
OK thanks. I've raised a ticket there.

**Comment by OzzieIsaacs** [comment]
I improved the handling, if the environment variable is not a number the default value is taken

**Comment by paulmorabito** [comment]
Thanks! I've re-pulled the container but I guess it hasn't refreshed in the docker image yet. I'll keep trying and let you know if it's successful.

**Comment by OzzieIsaacs** [comment]
As far as I remember the linuxuser container is refreshed once a week ( on Sunday, I think)

**Comment by paulmorabito** [comment]
I just checked and it looks like the latest tag was updated 2 days ago so
it would update again in another 4-5 days. I'll re-check then and close
this if it is resolved.

**Comment by OzzieIsaacs** [comment]
Sorry I forgot to push the commit to github. It should show up next saturday/sunday.

**Comment by paulmorabito** [comment]
I can confirm this now works. Thanks.
