### ISSUE TITLE
"No release information" instead of update

### ISSUE THREAD

**Issue by Flo-63** [janeczku/calibre-web#815]
After lastest update, a couple of days ago, on admin page I see version 0.6.1. instead of a release date. Clicking the search for update button shows the message "No release information".
Any ideas how I can fix this and becoming able to update again?

Many thanks and best regards,

FLO

**Comment by OzzieIsaacs** [comment]
I changed the updater to "stable" versions and "nightly" version, but creating tag/release numbers  on github resulted in a name change of the file downloaded. The "old downloader could not handle this name, and deleted the whole installation (#790,  #795).  Therefore I removed the tag/release, I will reenable this after a while (after I think many people should have upgraded).
To get always the newest fix, you should change the the updater to "nightly" (admin section -> basic configuration -> server config). 
Currently I'm refactoring the whole code and therefore I created a development branch, I don't recommend to update to this one (only possible by manually download the correspondig zip file from github) (refer to  #793)

**Comment by OzzieIsaacs** [comment]
The releases are up on the website, you should now get an update
