### ISSUE TITLE
Question: Why does "send Azw3 to Kindle" show up when you can't send an Azw3 to Kindle?

### ISSUE THREAD

**Issue by EolianPipes** [janeczku/calibre-web#816]
I was curious as to why the "Send to Kindle" dropdown lists both "Send Azw3 to Kindle" as well as "Convert Epub to Mobi and send to Kindle."

I thought I read somewhere here that the Azw3 would get auto converted to .mobi, but it seems like it's still trying to send out the direct Azw3 file directly and failing due to Amazon's document limitations.

The convert to .mobi works great, but I can't wrap my head around having the "send Azw3" when it fails every time. Is it supposed to convert it? I just want to make sure I'm not missing something.

Context:
I've installed Calibre and have pointed the Calibre-Web conversion path. I have not set up Kindlegen as it's been mentioned to be deprecated. I haven't entered anything in the "E-Book Converter Settings."

**Comment by OzzieIsaacs** [comment]
I personally down own a kindle. One of the users requested to have a button send azw3 file to kindle, so during implementation of the conversion of everything to anything I implemented it. If it makes no sense I can remove it, but first let me doublecheck the old issue/request.

**Comment by EolianPipes** [comment]
That makes sense. I just wanted to make sure I wasn't missing a configuration step somewhere.

I just tested it on a book that didn't have an Azw3 file and it asked if I wanted to convert the EPUB to Azw3 and send to Kindle. After trying that, I got the same email back from Amazon saying it didn't send as that's not supported. Just wanted to send a heads up!

**Comment by OzzieIsaacs** [comment]
Related to #295

**Comment by EolianPipes** [comment]
Thanks for sending over the linked ticket. I remember reading through that one when I was researching the Azw3 issue.

Should I create an enhancement request to choose whether to see that option or not? It seems that sending the Azw3 to Kindle only works if you set up some additional plugin on the Kindle to go through IMAP instead of directly through Amazon's servers. It would be nice to toggle that option on for those that go through that route. Default "email to Kindle" functionality shouldn't show it if you can't actually use it as expected.
