### ISSUE TITLE
[Caliblur] Read-in-browser - Cannot read CBZ on browser 

### ISSUE THREAD

**Issue by floviolleau** [janeczku/calibre-web#820]
Hi,

I just installed calibre-web and it works well. I can access the library and download the CBZ but when I click on "Read in browser" the drop-down menu is not shown.

I seems that there is an issue with the dropdown that remains in display none.

The solution found to fix is to change at line 213 of file `cps/static/js/caliBlur.js` 

```
$( '#read-in-browser' ).click( function() {
    $(  '.readinbrowser-drop' ).toggle();
});
```
into
```
$( '#read-in-browser' ).click( function() {
    $(  'ul[aria-labelledby="read-in-browser"]' ).toggle();
});
```

Kind regards

**Comment by OzzieIsaacs** [comment]
Doublechecked it, for me it's working: With one format and also for 2 or more formats which are readable.
![grafik](https://user-images.githubusercontent.com/6438895/53286307-cefa0c00-376c-11e9-9678-a9f059974cf9.png)
Are you using the newest version?

**Comment by floviolleau** [comment]
The problem was with 1 format. I will update and check again soon.

**Comment by OzzieIsaacs** [comment]
There was an issue with .cbz files with "no compression", it should be fixed now
