### ISSUE TITLE
Upload failed - Upload done, processing, please wait...

### ISSUE THREAD

**Issue by raeisi** [janeczku/calibre-web#822]
I can not upload some PDF files and get below error on log file
============================. 
/init/launch.sh: line 5:    61 Segmentation fault      (core dumped) gosu $PUSER:$PGROUP bash -c "/usr/bin/python $APP_H OME/app/cps.py"
--
====================================

some PDF files are working OK.

I am using technosoft2000/calibre-web docker image

**Comment by OzzieIsaacs** [comment]
sound like duplicate of #789
