### ISSUE TITLE
[Development] How to handle new columns in app.db regarding updates?

### ISSUE THREAD

**Issue by vigri** [janeczku/calibre-web#824]
Hello,

I've made an improvement to calibre-web which adds a new configuration field in admin > UI configuration.
When I start from scratch (without app.db) the new column gets automatically added to app.db.

But what about when using an existing configuration?
Is there mechanism in calibre-web, which I can use to update an existing app.db?

Regards

**Comment by OzzieIsaacs** [comment]
Yes, I’m in.py there is the function migrate_Database() which does this, just add an 

    try:

        session.query(exists().where(Settings.config_default_role)).scalar()

    except exc.OperationalError:  # Database is not compatible, some rows are missing

        conn = engine.connect()

        conn.execute("ALTER TABLE Settings ADD column `config_default_role` SmallInteger DEFAULT 0")

        session.commit()
Block for your column and it should work.

**Comment by vigri** [comment]
Perfect. Thank you! 👍
