### ISSUE TITLE
[Enhancement] Browse by title in a "list" view 

### ISSUE THREAD

**Issue by midniteslice** [janeczku/calibre-web#825]
Hello! 
I have a huge amount of comics in my collection. Would it be possible to add a "browse by title". Browse by series works, but I have found that there are a lot of comics that don't have series in the metadata. 
Thank you so much for all the effort you've put into this, it's an awesome piece of software!

**Comment by OzzieIsaacs** [comment]
Have tried this awesome button on the left side? 
![grafik](https://user-images.githubusercontent.com/6438895/53354857-07921500-3928-11e9-878c-fe6e2bf7c237.png)

**Comment by midniteslice** [comment]
I have! Use it quite frequently actually, and it works great. My usual method is to either sort by title or search for a book/comic. 

When I browse by series I get an awesome series list in two columns with number of books beside each series name. A title list that works the same way would be pretty sweet, and save a lot of scrolling when dealing with a large collection. 

I apologize for not making my initial post clearer and more concise. I wasn't even thinking about the sort feature.

**Comment by OzzieIsaacs** [comment]
It's planned to have a list view for merging books and to have options for filtering and sorting in the normal views.

**Comment by midniteslice** [comment]
I just saw your reply, and that sounds pretty skippy actually. 
Thanks again for Calibre-web. It really is an awesome venture.

**Comment by OzzieIsaacs** [comment]
The list view is available in the newset commit version
