### ISSUE TITLE
[Enhancement] Requests (If this would be possible)

### ISSUE THREAD

**Issue by Emuarc** [janeczku/calibre-web#831]
Could the following features be included in future versions?

- robots.txt
- sitemap.xml
- RSS
- Google Analytics / Matomo
- Possibility of sending a download link for a document by email and not downloading it, even for a guest writing your email.

Thank you very much and congratulations for your work.

**Comment by OzzieIsaacs** [comment]
Calibre-Web is made for sharing books among a small group of users. I don‘t see the benefit in this usecase to have Google analytics. We have an opds feed, rss feeds are unusual for accessing books. Creating download links would create another level of complexity (having non guessable links which get invalid after some time,...).
I‘m sorry, I‘m not Honig to implement this feature.

**Comment by tdack** [comment]
To include Google Analytics or Matomo is relatively easy using the substitute/filter modules with either Apache or Nginx as reverse proxies.

Include this in the `location` block for nginx:
```
        sub_filter  </head> '\t<script type="text/javascript" src="/analytics.js"></script>\n</head>';
        sub_filter_last_modified on;
        sub_filter_once on;
````

Include this in the `VirtualHost` section for Apache:
```
	AddOutputFilterByType SUBSTITUTE text/html
	Substitute "s|</head>|<script type=\"text/javascript\" src=\"/analytics.js\"></script></head>|in"
```

Change `analytics.js` as appropriate for your analytics platform. You can also change the `</head>` tag to say `</body>` if you want your JS inserted at the end of the document.

If you proxy the app at the root of your domain (eg: www.example.com/) then you'll need a seperate `location` entry to handle serving the `analytics.js` file.

**Comment by Irv007** [comment]
Hi all,

"Include this in the location block for nginx"

Could somebody explain that in a little bit more words, how to do that?

I have attached my docker-compose.yml.
How do I add the given information in my location block for nginx?
Where is my configuration file for my nginx?
Is it /etc/nginx/nginx.conf in my nginx-proxy container?
/etc/nginx/nginx.conf says "include /etc/nginx/conf.d/*.conf"
Should I put this information into /etc/nginx/conf.d/default.conf? (attached)

with best regards,
Irvin

[docker-compose.yml.txt](https://github.com/janeczku/calibre-web/files/5014175/docker-compose.yml.txt)
[default.conf.part_of.txt](https://github.com/janeczku/calibre-web/files/5014176/default.conf.part_of.txt)

**Comment by OzzieIsaacs** [comment]
In the wiki there is an example config for nginx given https://github.com/janeczku/calibre-web/wiki/Setup-Reverse-Proxy#nginx
The default config file you pasted into it, you are the http and server Block, add the Location block there

**Comment by Irv007** [comment]
ok, thank you. I will check that.

**Comment by alfonsrv** [comment]
@OzzieIsaacs but isn't a `robots.txt` needed in order to prevent Google from indexing your site?

**Comment by OzzieIsaacs** [comment]
https://github.com/janeczku/calibre-web/wiki/Extend-Features#use-your-own-robotstxt-file

**Comment by alfonsrv** [comment]
Perfect; works as intended – Merry Christmas
