### ISSUE TITLE
Is there any way to open access of a given shelf to a certain user while hiding other books not belong to it?

### ISSUE THREAD

**Issue by waynesonia** [janeczku/calibre-web#832]
Hello, 
I'd like to share my e-books to my friends, while keeping some of my books private at the same time. This screening could only be achieved by setting 'adult content' tags up till now, but I felt it not convenient to set more than one filtering rules which could be applied to different users.

So if there is any way to make some permissions with shelves? For example, user A could only see books of shelf 1 and shelf 2 in my website, while user B for shelf 2 and shelf 3. 

Wish for your reply, thanks~

**Comment by tomjmul** [comment]
I agree, it would be a great feature to restrict certain users to certain shelves.

**Comment by tomjmul** [comment]
I've added a PR #851 which would allow configuring a set of tags against a user to restrict whe books they can view. It works for me.

**Comment by OzzieIsaacs** [comment]
The feature is merged

**Comment by bee-eater** [comment]
@OzzieIsaacs 
How can I allow a user to only see books on shelf "xy" and nothing else? I haven't found the solution yet :-)

**Comment by OzzieIsaacs** [comment]
@bee-eater This isn't possible, the restrictions are only based on tags, or a custom column
