### ISSUE TITLE
e-Mail set-up test e-mail gets sent to user's Kindle address rather than user address

### ISSUE THREAD

**Issue by Oak-Aged** [janeczku/calibre-web#834]
When you set up the e-mail settings for notifications (smtp server settings) and click the test button, it sends the test e-mail to the user's @kindle.com address instead of their regular e-mail address (both of which are in the user's account settings; it's just picking the wrong one).

In case it helps:
O/S: FreeNAS 11.2 (FreeBSD)
Calibre-Web is current version; installed via Git exactly per the instructions
If you need any other info just let me know.

Thanks

**Comment by OzzieIsaacs** [comment]
Yes, the behavior is known, and up to now it was absolutely plausible to me. The users email address is for public registering and not used for anything else. I was thinking on removing this email adress for users without public registration. I‘ll rethink the behavior.

**Comment by Oak-Aged** [comment]
OK, I thought maybe it was just an oversight. I just think it should use the Kindle address only for sending books, and the user address for notifications. The way it is now, the Kindle doesn't get anything, and the sending address gets a bounce message from Amazon saying there was no attachment (it expects a book). Anyway, it's not a big deal since it's only set up once.

Thanks for the quick response!

**Comment by OzzieIsaacs** [comment]
It's changed now, the test-email is send to the users email
