### ISSUE TITLE
Select by Categories, Series, or Authors: Internal Server Error. 

### ISSUE THREAD

**Issue by Oak-Aged** [janeczku/calibre-web#835]
Clicking on "Read" or "Unread" works as expected. Clicking on Categories, Series, or Authors goes to an "Internal Server Error" page. In each case the Traceback in the log starts with:

[2019-03-07 13:15:39,833] {/usr/local/lib/python2.7/site-packages/flask/app.py:1761} ERROR - Exception on /series [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()

The "Categories" traceback ends with:
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 4501, in _no_text_coercion
    "extra": "%s " % extra if extra else "",
CompileError: Can't resolve label reference for ORDER BY / GROUP BY. Textual SQL expression 'books_tags_link.tag' should be explicitly declared as text('books_tags_link.tag')

The "Series" traceback ends with:
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 772, in visit_textual_label_reference
    "Can't resolve label reference for ORDER BY / GROUP BY.",
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 4501, in _no_text_coercion
    "extra": "%s " % extra if extra else "",
CompileError: Can't resolve label reference for ORDER BY / GROUP BY. Textual SQL expression 'books_series_link.series' should be explicitly declared as text('books_series_link.series')

The "Authors" traceback ends with:
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 4501, in _no_text_coercion
    "extra": "%s " % extra if extra else "",
CompileError: Can't resolve label reference for ORDER BY / GROUP BY. Textual SQL expression 'books_authors_link.author' should be explicitly declared as text('books_authors_link.author')

OS: FreeNAS 11.2 (FreeBSD)
Calibre-Web: Current version
Python version: 2.7.15
Pip version: 19.0.3
SQLAlchemy version: 1.3.0

According to "pkg info" my sql versions are:
py27-sqlite3-2.7.15_7
sqlite3-3.26.0

But according to "pip list":
sqlite3 0.0.0

That seems weird to me. Wondering if I should uninstall pip's version and try the app, then if still the same errors, reinstall it and try again. Or is it an issue with the app code?

If you need any other details just let me know.

Thanks

**Comment by OzzieIsaacs** [comment]
I‘d bet more on the sqlalchemy Version than sqlite itself. Could you please Check which sqlalchemy Version you have installed. Just to make sure, your metadata.db was created by calibre?

**Comment by Oak-Aged** [comment]
SQLAlchemy version: 1.3.0
And just in case, I did a "pip install --upgrade SQLAlchemy" and it confirmed it's the latest.
...However I also just did "pkg search SQLAlchemy" and it found:
py27-Flask-SQLAlchemy-2.3.2_1  Adds SQLAlchemy support to Flask
py27-sqlalchemy-migrate-0.11.0 Database schema migrations for SQLAlchemy
py27-sqlalchemy10-1.0.14       Python SQL toolkit and Object Relational Mapper 1.0.x
py27-sqlalchemy11-1.1.18       Python SQL toolkit and Object Relational Mapper 1.1.x
py27-sqlalchemy12-1.2.14       Python SQL toolkit and Object Relational Mapper 1.2.x
(And a similar list for Python 3.6)

Do you think I should install one of those?

Metadata.db is initially created by calibre but updated by LazyLibrarian, but using calibredb, so essentially it's all calibre.

**Comment by OzzieIsaacs** [comment]
No need to install any of it, sqlalchemy and that‘s it.
Your version might be to new (
https://www.sqlalchemy.org/blog/#sqlalchemy-1.3.0-released). 

> Overall, most changes are fully backwards compatible with a SQLAlchemy 1.2 application, with the exception of the hard removal of the long-deprecated automatic coercion of SQL phrases into text (see Coercion of string SQL fragments to text() fully removed). 
Please downgrade sqlalchemy to 1.2.18 at most. 
I‘ll take look at it

**Comment by phampyk** [comment]
Thank you, I was having the same problem but downgrade to 1.2.18 works

**Comment by OzzieIsaacs** [comment]
I‘ll try to fix it this weekend

**Comment by Oak-Aged** [comment]
Awesome, thanks for the fast fix!
I tried to update via the "Check for update" button in admin, and it says "No release information available". There's nothing in the log about it. I can update manually via git, but shouldn't the update function work? Is there anything you'd like me to try, to help find the cause?

**Comment by OzzieIsaacs** [comment]
Please refer to #815 for the answer
