### ISSUE TITLE
http redirect to https if SSL used

### ISSUE THREAD

**Issue by seantrace** [janeczku/calibre-web#838]
Would it be possible to support an option to enable **http** redirection to **https** if **SSL** is being used?

**Comment by OzzieIsaacs** [comment]
I understand the wish for a redirect to https. For calibre-web this would mean opening a second port and redirecting everything to port one. In my opinion this could be better handled by a reverse proxy with a real webserver. 
I‘m willing to check how to redirect from a http request on port A to a https request von the same port A. 
Would this help you?

**Comment by seantrace** [comment]
A reverse proxy webserver is maybe the ideal solution. However since calibre-web does support SSL itself some form of http->https redirect would be a great help to avoid the overhead of reverse proxy setup and maintenance.  What I would like is http:80->https:443, but I could live with http:80->https:80 although somewhat unconventional.

**Comment by ikwyl6** [comment]
newb to project...
why not just have the webserver only serve ssl?

**Comment by OzzieIsaacs** [comment]
After a long time I had time to come back to this one. My opion hasn't changed, I don't want to add the complexity of adding another port for listening. Redirecting ports on linux is explained here with iptables: https://serverfault.com/questions/360236/how-can-i-redirect-a-port-number-on-linux/360373. The other option would be indeed using a reverse proxy
