### ISSUE TITLE
Automatic db reload

### ISSUE THREAD

**Issue by yannouchou** [janeczku/calibre-web#842]
Hello, first of all great work, I'm a very big fan!
I've noticed that I often find myself having to manually click "reconnect to calibre db" to refresh the latest updates after any update made with Calibre...
I don't know if there's already an auto-reload mechanism in place, but if there is, it doesn't seem to be working for me - possibly because my library is on a volume mounted in NFS, which might prevent inofitfy / watch notifications from the file system.
Is there any way to schedule or automate this reload in any way? 
Thanks!

**Comment by OzzieIsaacs** [comment]
currently there is no automated reload (I never could reproduce the problem myself). Each request (page load) opens a new database session and should get the current data. Docker container seem to have problems with this. There is already another issue requesting a reload mechanism.

**Comment by OzzieIsaacs** [comment]
possible duplicate of #727

**Comment by yannouchou** [comment]
Dupe indeed...
