### ISSUE TITLE
[Enhancement] Allow upload of png files via URL and local drive for covers

### ISSUE THREAD

**Issue by ariesdevil** [janeczku/calibre-web#843]
For now cover url just support jpg: https://github.com/janeczku/calibre-web/blob/a0a15b4598d372b05cb30c06ac5787dc229b7e9d/cps/helper.py#L446-L450

**Comment by Oreolek** [comment]
The calibre database uses JPEG for covers. calibre-web does have a backward compatibility to calibre. https://manual.calibre-ebook.com/_modules/calibre/db/cache.html#Cache.cover

**Comment by ariesdevil** [comment]
How about allowing to recevie png and convert to jpg?

**Comment by OzzieIsaacs** [comment]
Your last proposal sound reasonable. I changed the title accordingly.

**Comment by ariesdevil** [comment]
@OzzieIsaacs I create a PR for it.https://github.com/janeczku/calibre-web/pull/865

**Comment by cbartondock** [comment]
This was closed but not implemented correct?

**Comment by ariesdevil** [comment]
@cbartondock What problems are you having?
