### ISSUE TITLE
Upload Error: Empty reply from server

### ISSUE THREAD

**Issue by qokelate** [janeczku/calibre-web#845]
log level: DEBUG
pdf info: PDF document, version 1.5

command:
```
curl -b a.txt -c a.txt -L "http://127.0.0.1:60092/upload" -F "btn-upload=@/tmp/1.pdf;type=application/pdf" -v
* Expire in 0 ms for 6 (transfer 0x1451d50)
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x1451d50)
* Connected to 127.0.0.1 (127.0.0.1) port 60092 (#0)
> POST /upload HTTP/1.1
> Host: 127.0.0.1:60092
> User-Agent: curl/7.64.0
> Accept: */*
> Content-Length: 293513
> Content-Type: multipart/form-data; boundary=------------------------325e19906c2de9cf
> Expect: 100-continue
>
* Expire in 1000 ms for 0 (transfer 0x1451d50)
< HTTP/1.1 100 Continue
* Empty reply from server
* Connection #0 to host 127.0.0.1 left intact
curl: (52) Empty reply from server
```

log:
```
[2019-03-16 09:14:18,619] INFO in web: Starting Calibre Web...
[2019-03-16 09:14:18,762] INFO in server: Starting Gevent server
[2019-03-16 09:14:34,181] INFO in web: Starting Calibre Web...
[2019-03-16 09:14:34,323] INFO in server: Starting Gevent server
[2019-03-16 09:21:02,100] INFO in web: Starting Calibre Web...
[2019-03-16 09:21:02,410] INFO in server: Starting Gevent server
```

version:
```
Sqlite	v3.26.0
lxml	v4.3.2.0
Requests	v2.21.0
Image Magick	ImageMagick 6.9.9-51 Q16 x86_64 2018-12-25 https://www.imagemagick.org
Flask	v1.0.2
Babel	v2.6.0
pytz	v2018.9
PyPdf	v1.26.0
pySqlite	v2.6.0
ebook_converter	not set
Iso 639	v0.4.5
Python	2.7.15 (default, Jan 24 2019, 16:32:39) [GCC 8.2.0]
Sqlalchemy	v1.3.1
Jinja2	v2.10
Wand Version	0.5.1
Gevent	v1.2.1
Werkzeug	v0.14.1
Flask Login	v0.4.1
Flask Principal	v0.4.0
```

**Comment by OzzieIsaacs** [comment]
May I ask which version of calibre-web you are using (shown on bottom of admin page)?

**Comment by qokelate** [comment]
0.6.1

**Comment by OzzieIsaacs** [comment]
Perfect. The project is currently in transition from updating everybody with everything to a stable/nightly system. Unfortunately there was a bugin the updater, so I had to revert this system. It looks now you've updated from an older version right into this system and you now stuck in "buggy commit". Could you please change the updater to nightly (admin -> basic configuration -> server settings). Then you should have the option to update to a newer commit, where is issue is fixed. It's recommend afterwards to revert the updater setting to "stable"

**Comment by qokelate** [comment]
updated to `3/11/19, 2:26 AM`, upload works well! thanks!

**Comment by LoafingBunny** [comment]
Hi, not sure to open a new issue because the problem is very similar.

The log shows no error, but systemctl status prints:
`mar 26 16:21:07 Raspi python2.7[9131]: WARNING:tornado.access:422 POST /upload (::1) 9471.92ms
`

while in firefox I have this error in console:

![Screenshot_20190326_155403](https://user-images.githubusercontent.com/16180988/55010278-38776f80-4fe4-11e9-8e8a-eb2b65cfed56.png)

**Comment by OzzieIsaacs** [comment]
I could reproduce the problem in case of an upload error. Please update to the newest nightly version. The javascript error should disappear and you should see the "real error" (file permission error or something similar) in the upload dialogbox

**Comment by LoafingBunny** [comment]
thx now the error shows up

**Comment by OzzieIsaacs** [comment]
Hope you can fix the error.

**Comment by LoafingBunny** [comment]
uhm the problem is that calibre web creates new folders without executable permission so it cannot put the books into them. Any clue?

**Comment by OzzieIsaacs** [comment]
Hm, this always worked for me. What permissions do you get, and what you think we need? What is the exact error message, so I know where to insert the permission command.

**Comment by LoafingBunny** [comment]
might be only my file system configuration, thought.
All folders in library dir have permissions: 775, with my user and group.
The umask is u=rwx,g=rx,o=rx
But when I upload a book, the created directory has permissions: drw-rwxr-- while all the others have drwxrwxr--

And the error is:
`Impossibile creare il percorso /home/qwerty/library/Unknown/cassinari (autorizzazione negata)`

**Comment by LoafingBunny** [comment]
ok solved. I messed up with permissions.

**Comment by OzzieIsaacs** [comment]
Perfect
