### ISSUE TITLE
Allow guest to "send to kindle"

### ISSUE THREAD

**Issue by yannouchou** [janeczku/calibre-web#848]
It appears that the "send to kindle" button is disabled when browsing as guest, even if the "Guest" user has a valid kindle email set up.
In my setup all the authentication is handle upfront by proxy so I don't need any of the built-in user management (except for the admin features).
Is it possible to enable Kindle sending for guests?

**Comment by yannouchou** [comment]
Hello... Any comments on this? Any chance you might consider it?

**Comment by OzzieIsaacs** [comment]
I thought a while on this and I came to the conclusion not to do it. I Think There are much more use cases having different users accessing the guest User, as usecases having only one guest user.
So my Suggestion is:
Please cps/Templates/Detail.html and please change line 
{% if g.user.kindle_mail and g.user.is_authenticated and kindle_list %}

To 
{% if g.user.kindle_mail and kindle_list %}

The behavior should be than as you requested it

**Comment by yannouchou** [comment]
OK, fair enough, thanks for the guidance on this!

**Comment by yannouchou** [comment]
Actually @OzzieIsaacs, in case multiple users share the Guest account, all they'd have to do to hide the button is simply to not fill the Kindle email address for the Guest account... So removing the `is_authenticated` condition really wouldn't degrade any functionality and I'd argue that there's no harm doing it.

Anyway I'm facing some issues implementing the hack, since even after the edit, the UI still hides the button even after a Calibre-web restart and browser cache clearing... I suspect flask / jinja is caching the compiled template somewhere... Any suggestion? I really don't know much about python web frameworks...

**Comment by OzzieIsaacs** [comment]
Currently having no access to my computer, so it‘s hard for me to debug it remotely, please be patient (2-3weeks)

**Comment by yannouchou** [comment]
Sure no problem :)

**Comment by OzzieIsaacs** [comment]
Okay, convinced. I changed it, and documented in the wiki

**Comment by yannouchou** [comment]
Awesome, thanks a lot!
