### ISSUE TITLE
allow changing password also enables allow editing public shelfs

### ISSUE THREAD

**Issue by elfcan** [janeczku/calibre-web#853]
Hello,

I started Calibre Web with docker using this repo:
https://hub.docker.com/r/technosoft2000/calibre-web

When I click on Allow Changing Password and click on submit, it also enables Allow Editing Public Shelfs. It goes both ways, too, if i enable one of them it enables the other one and if i disable one of them it disables the other one. 

![Selection_253](https://user-images.githubusercontent.com/2270993/54675724-25f6c500-4b10-11e9-8cf2-4f43ddff7acd.png)

Could you kindly help?
Thanks.

**Comment by OzzieIsaacs** [comment]
I‘ll take a look at it

**Comment by OzzieIsaacs** [comment]
Thanks a lot, I merged your PR.

**Comment by elfcan** [comment]
Thank you for the quick response. Cheers.
