### ISSUE TITLE
Ebookdroid - Opds not allowing download

### ISSUE THREAD

**Issue by jnpeterson** [janeczku/calibre-web#856]
I installed calibre-web a few days ago and it works great over the web.  When I try to access it via OPDS from an android ereader though, I'm getting all sorts of strangeness.  I've tried several different readers and some work better than others.  The only way I can get things to work halfway correctly is to enable anonymous browsing.  Otherwise, depending on the reader, I get no book covers or can't download the book.  

Calibre-web is running the latest nightly build under Windows 10 using Python 3.7.2.  
Ebookdroid comes the closest to working correctly.  I can add the URL and my credentials to it and get all the book lists and covers, but downloading fails.  If I enable anonymous browsing and download for the guest user, downloading works.  If I don't enable mature content under the anonymous user at that point I can't see it, even though the user I'm logged in as has mature content enabled.  

Moon reader and FBreader can browse and download without anonymous browsing turned on, but shows no book covers.  Enabling anonymous browsing shows book covers, but again disables mature content unless I give the permission to the guest account.  What I'm getting is very similar to Issue #830.

**Comment by OzzieIsaacs** [comment]
I don't have access to Android, but I checked it with iOS and with windows firefox. Everything looks good.
So:
Do you use docker container? (which one)
Do you use reverse proxy for accessing the opds feed?
Did you change the standard port?
Does the username contan any non ASCII characters?
Is there any relevant entry in the logfile calibre-web.log?
Which server are you using tornado or gevent? (-> About section)
Has the user you are using enabled "allow download"?
The problems regarding mature content are also working perfectly for me? (Maybe it's a caching issue on android???) Do you also have the problems regarding mature content in the normal web-UI?

**Comment by jnpeterson** [comment]
> 
> 
> I don't have access to Android, but I checked it with iOS and with windows firefox. Everything looks good.
> So:
> Do you use docker container? (which one)
**I was originally running without a docker container, but I tried the linuxserver.io container today and get the same results.**

> Do you use reverse proxy for accessing the opds feed?
**No.**

> Did you change the standard port?
**No, it's on the standard 8083.**

> Does the username contain any non ASCII characters?
**No, I've tried both the default admin username and a simple username that I added.**

> Is there any relevant entry in the logfile calibre-web.log?
**No.  Just INFO entries on startup and shutdown.  I do get 401 unauthorized errors in the Powershell log display though.  "calibre-web    | ::ffff:172.18.0.1 - - [2019-03-24 19:09:37] "GET /opds/download/316/epub/ HTTP/1.1" 401 264 0.014589"**

> Which server are you using tornado or gevent? (-> About section)
**In the non-docker version I was using tornado, in the docker version it's gevent.**

> Has the user you are using enabled "allow download"?
**Yes.**

> The problems regarding mature content are also working perfectly for me? (Maybe it's a caching issue on android???) Do you also have the problems regarding mature content in the normal web-UI?
**Everything works as expected in the Web-UI including mature content.  I tried clearing the device cache and app cache on Android just to check.  It prompted me to log in again afterward, but still no solution.**

**Comment by OzzieIsaacs** [comment]
I had some time to debug the behavior. 
Ebookdroid: For I reason I don't understand Ebookdroid is not sending Authorization information on requesting the download file:
The first screenshot shows a request to the unread section, Authorization information is send:
![request](https://user-images.githubusercontent.com/6438895/56409816-fa840900-627a-11e9-824c-2dd55b25ff56.png)
Screenshot shows a request for downloading a file Authorization information is not send, the server responses with Unauthorized, afterwards the client (Ebookdroid) should repeat the request with Authorization informations. This is not happening, so the download fails.  
![download](https://user-images.githubusercontent.com/6438895/56409817-feb02680-627a-11e9-8e4c-4c7ef64696f2.png)
I tried Calibre with Ebookdroid, upon enabling the login, Ebookdroid responds with digest (the authorization method calibre uses) is not supported.
My conclusion: Ebookdroid is only working with anonymous browsing

**Comment by OzzieIsaacs** [comment]
MoonReader:
Same problem as with Ebookdroid, Moonreader is not sending authorization information for the cover requests. I also tried it with calibre, it's the same behavior

**Comment by OzzieIsaacs** [comment]
FB-Reader:
Same problem as with Ebookdroid, FB-Reader is not sending authorization information for the cover requests. I also tried it with calibre, it's server can not connect with authorization enabled.

**Comment by OzzieIsaacs** [comment]
I contacted the developers of ebookdroid, they confirmed it‘s a bug, they‘ll fix it.
