### ISSUE TITLE
DB location is not valid, please enter correct path

### ISSUE THREAD

**Issue by mouzzampk2014** [janeczku/calibre-web#857]
Hi, 

I am not sure what I am doing wrong could you please look into this for me. 

https://pastebin.com/8NwS1yaN

Thank you

**Comment by OzzieIsaacs** [comment]
As far as I unterstand the docker configuration you enter the path to the Calibre-db with the -v parameter while creating the container. This path is mapped to /books inside the container. I think therefore „/books“ is the auswer to your question. If this is not working, please ask for help from the docker provider.

**Comment by mouzzampk2014** [comment]
> As far as I unterstand the docker configuration you enter the path to the Calibre-db with the -v parameter while creating the container. This path is mapped to /books inside the container. I think therefore „/books“ is the auswer to your question. If this is not working, please ask for help from the docker provider.

Yes you are right this is exactly what I have 

`  calibreweb:
    container_name: calibreweb
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    image: linuxserver/calibre-web
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
    - ${CALIBREWEB_PORT_8083}:8083
    restart: unless-stopped
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${DOCKERCONFDIR}/calibreweb:/config
    - ${DOCKERSHAREDDIR}:/shared
    - ${MEDIADIR_BOOKS}:/books`

**Comment by mouzzampk2014** [comment]
All done. I just used metadata.db and then deleted the main app. Thank you

**Comment by mildfuzz** [comment]
@mouzzampk2014 I have having the same issue. By the look of your config, you're using dockstarter also, how did you resolve?
