### ISSUE TITLE
I can't download metadata from douban.

### ISSUE THREAD

**Issue by tanst** [janeczku/calibre-web#858]
I can't get it to download any metadata from douban, google is OK,only douban no metadata found.
It looks like for some reason it is not connecting to any of the metadata sources.

**Comment by OzzieIsaacs** [comment]
I can reproduce the problem. 
I tried to search for the douban api, to check if they made any change. It looks like the service is not accessible at all, so maybe they shut it down, or they are currently having problems

**Comment by paulhybryant** [comment]
Failed to load resource: the server responded with a status of 403 (Forbidden)
https://api.douban.com/v2/book/search?q=%E6%8A%95%E8%B5%84%E6%9C%80%E9%87%8D%E8%A6%81%E7%9A%84%E4%BA%8B&fields=all&count=10&callback=jQuery21409541467257626464_1554259597254&_=1554259597255 net::ERR_ABORTED 403 (Forbidden)

{"msg":"invalid_apikey","code":104,"request":"GET \/v2\/book\/search"}

I think it is because the API_KEY is not valid?

**Comment by idalin** [comment]
it seems that douban api has been shutdown. I can't get any info to fix it. so maybe amazon is another choice as mentioned at #380

**Comment by yunzhongci** [comment]
我也遇到这个问题，但是直接在calibre上是可以搜索到豆瓣的数据的，应该不是api关闭的原因？
另外能不能添加亚马逊中国的元数据？

**Comment by OzzieIsaacs** [comment]
@yunzhongci could you please change your post to english, so anybody can read it?

**Comment by idalin** [comment]
> @yunzhongci could you please change your post to english, so anybody can read it?

He said Douban Metadata Source works fine in Calibre, maybe the api has not been shutdown. and asked for Amazon China metadata source.

I check the source in calibre. it use another api with a apikey(like: https://api.douban.com/book/subjects?q=test&apikey=0bd1672394eb1ebf2374356abec15c3d ). maybe we can use this api too. the only problem is it returns xml result.

**Comment by OzzieIsaacs** [comment]
The lxml lib which is already a optional dependency, is able (should) to parse xml-files
From website of lxml
> lxml provides a very simple and powerful API for parsing XML and HTML.
So parsing xml should be no problem. Additional questions is, if we need to obtain an own apikey for calibre-web?

**Comment by idalin** [comment]
> The lxml lib which is already a optional dependency, is able (should) to parse xml-files
> From website of lxml
> 
> > lxml provides a very simple and powerful API for parsing XML and HTML.
> 
> So parsing xml should be no problem. Additional questions is, if we need to obtain an own apikey for calibre-web?

douban does not issue new apikey any more. I think the api server will be shutdown sooner or later. maybe Amazon or other source will be a better choice.

**Comment by OzzieIsaacs** [comment]
I removed the support for Douban, Amazon was requested in issue #380
