### ISSUE TITLE
Login and PDF viewing don't work with an Apache reverse proxy

### ISSUE THREAD

**Issue by mlg9000** [janeczku/calibre-web#86]
I have an Apache reverse proxy setup as follows:
```

<Location "/books" >
    RequestHeader set X-SCRIPT-NAME /books
    RequestHeader set X-SCHEME https
    ProxyPass http://localhost:8083/
    ProxyPassReverse http://localhost:8083/
</Location>
```

The documented method for Apache in readme.md using mod_proxy_html did not work at all.  Setting the X-SCRIPT-NAME header is the only method that seems to work.  There are two issue however:

1. The login redirects to / and not /books.  This can be worked around by simply going to /books, which works fine once I've already logged in.
2. Trying to view PDF's does not work.  I see 404's in the Apache logs: "GET /static/js/pdf.worker.js HTTP/1.1" 404 221".  

The rest of the reverse proxy works fine.  I can search, see covers, edit metadata, logout, etc without issue.

**Comment by OzzieIsaacs** [comment]
The newest commit should solver the pdf reader issue

**Comment by mlg9000** [comment]
The PDF reader now works.  The changes introduced two new issues though:  calibre-web would not start due to DB changes.  I had to remove app.db to fix and then re-add all my users/setup to fix.  The second issue is that user now default to Spanish.

The login redirection problem still isn't solved.

**Comment by OzzieIsaacs** [comment]
I fixed the database issue with the last commit. 
The default spanish language I can't reproduce (I indeed added a spanish translation)
With your configuration there is a login issue, indeed, and I don't get it, you are beeing redirected to hhtp instead of using https, even with rewrite rules?? I checked my configuration again and it worked (at least on windows 7) could you please describe the problem with my configuration, so I can have a deeper look into it?

**Comment by OzzieIsaacs** [comment]
I think I found. You have to remove all the _external=true statements from the url_for statements and remove the hardcoded '/' in the login function. But this actually reverts a commit from June to make reverse proxing work with ngnix. I have to do some more tests

**Comment by OzzieIsaacs** [comment]
I added a fix which should make your configuration work without problems. 
Please try the latest commit.

**Comment by mlg9000** [comment]
It all now works, thanks!
