### ISSUE TITLE
Deprecation of kindlegen?

### ISSUE THREAD

**Issue by wildthyme** [janeczku/calibre-web#860]
The configuration page on the wiki claims that kindlegen support is deprecated in favor of calibre's converter, and will be removed in a future release. However, I have been unable to find any other information or rationale about this. Is it actually true? If so, why? As far as I know, kindlegen is likely to be maintained indefinitely into the future, while (a) calibre proper is effectively moribund (because unlike calibre-web it's staying with python 2, which will hit EOL next year), and (b) depending on calibre directly to function seems contrary to this project's design.

**Comment by OzzieIsaacs** [comment]
Kindlegen is dreprecated for the usage inside calibre-web. Kindlegin is very picky regarding epub books. In my library only one out out 5 books could be converted by kindlegen. I will remove it from calibre-web, I think in Summer of this year
