### ISSUE TITLE
Disable app

### ISSUE THREAD

**Issue by truitt661** [janeczku/calibre-web#870]
I decided to start back over and did a new fork, but this once arise again and i am not sure which commit we did to fixed the issue.

![FireShot Capture 008 - Sign in - Google Accounts - accounts google com](https://user-images.githubusercontent.com/36707741/55280008-6232de00-52e5-11e9-95b1-761522315390.png)

**Comment by OzzieIsaacs** [comment]
I think this has nothing to do with calibre-web, you should do what the error message says. Please go to the google developer console and verify your server.
