### ISSUE TITLE
Error 500 on Series View

### ISSUE THREAD

**Issue by silentArtifact** [janeczku/calibre-web#874]
I'm having an issue where if I select the series view from the sidebar of the Web UI, it throws a 500 error. [I've attached the error from the logs.](https://pastebin.com/X3H9LVKB)

Any ideas? I'm running from the linux server docker container.

**Comment by OzzieIsaacs** [comment]
You are not on the newest commit version. Could you please try to change the updater to nightly, search for an update (which should be available), do the update and enjoy.
 (Or do a new git pull)
