### ISSUE TITLE
Getting this issue when trying to install calibre-web on Synology without docker. Any Ideas?

### ISSUE THREAD

**Issue by midnightmastermind** [janeczku/calibre-web#880]
Collecting Wand
  Using cached https://files.pythonhosted.org/packages/4f/1c/876afbc445a4537ffdb72b469e7594f3d822b7c3c1d75e89e9c3f4061cbf/Wand-0.5.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-FYo_co/Wand/setup.py", line 8, in <module>
        from wand.version import VERSION
      File "wand/version.py", line 45, in <module>
        from .api import libmagick, library
      File "wand/api.py", line 137, in <module>
        libraries = load_library()
      File "wand/api.py", line 112, in load_library
        for libwand_path, libmagick_path in library_paths():
      File "wand/api.py", line 100, in library_paths
        libwand = ctypes.util.find_library('MagickWand' + suffix)
      File "/usr/lib/python2.7/ctypes/util.py", line 242, in find_library
        raise RuntimeError("can not find library %s" % name)
    RuntimeError: can not find library MagickWand

**Comment by OzzieIsaacs** [comment]
Related to #398. We did not find a solution at that time. 
Maybe this post could help: https://forum.synology.com/enu/viewtopic.php?t=60190
The problem is that the imagemagick library isn‘t found. Could you please check if it‘s installed?

**Comment by OzzieIsaacs** [comment]
I googeld a bit. Looks like the imagemagick commandline tool is preinstalled to synology nas, but not the libraryfiles(?) I didn‘t find a recompiled package for installing on synology nas. For me the only solution now seems to be: comment out line 14 in requirements.txt (# wand >=...) finish the installation. Afterwards you can use Calibre-web, but it‘s not possible to extract images from pdf files upon upload.

**Comment by OzzieIsaacs** [comment]
Maybe this one helps:
https://synocommunity.com/package/imagemagick
How to install:
https://synocommunity.com/#easy-install

**Comment by OzzieIsaacs** [comment]
If you need more help, or this doesn't help, don't hesitate to contact me again.

**Comment by Alek-Zywot** [comment]
Just wanted to comment that its working in case anyone else ends up here. I installed the synocommunity package imagemagick first and then cloned and installed calibre-web. Im running this natively on a ds118 without any issues.
