### ISSUE TITLE
Sort by Author Name

### ISSUE THREAD

**Issue by wub-fur** [janeczku/calibre-web#882]
Calibre-Web is great, thanks for making it! But… 

Is it not possible to sort by the author-sort field? 

This seems like a pretty major oversight. 

(Sorry If I’m just being dense and missing something that’s already there, but if there's a way to do this I sure can't find it.)

**Comment by OzzieIsaacs** [comment]
If you go to the authors list, all entries are sorted according to authors sort field:
![grafik](https://user-images.githubusercontent.com/6438895/56077732-0afe3480-5de0-11e9-862a-ea940bce6dcc.png)
If you are changing authors names in calibre web, the authors sort field is automatically populated according to the rule: 2nd-name, space 1st-name
