### ISSUE TITLE
Can't log in to calibre web despite correct login

### ISSUE THREAD

**Issue by y2klol** [janeczku/calibre-web#883]
Calibre log file
```
OPDS feeds advertised via BonJour at: [correct IP] port: 25041
Failed login attempt from: [my ip]
Failed login attempt from: [my ip]
Failed login attempt from: [my ip]
Failed login attempt from: [my ip]
```
unit file
```
[Unit]
Description=Calibre Service
After=network.target

[Service]
Type=simple

ExecStart=/usr/bin/calibre-server\
--port 25041 \
--log=/opt/calibre/calibre.log \
--enable-auth \
/home/oneechan/calibre-library


[Install]
WantedBy=multi-user.targe
```
systemctl status

```
calibre-server.service - Calibre Service
   Loaded: loaded (/etc/systemd/system/calibre-server.service; enabled; vendor 
   Active: active (running) since Sat 2019-04-13 04:14:55 UTC; 7min ago
 Main PID: 2464 (BonJour)
    Tasks: 14 (limit: 4915)
   Memory: 52.1M
      CPU: 1.780s
   CGroup: /system.slice/calibre-server.service
           └─2464 /opt/calibre/bin/calibre-server --port 25041 --log=/opt/calib

Apr 13 04:14:55 debian-s-1vcpu-1gb-sgp1-01 systemd[1]: Started Calibre Service.
```

Without authetication enable (i.e. removing --enable-auth) calibre web works completely fine. I added users (Existing user names: oneechan, paddy, test) using `sudo calibre-server --userdb /home/myuser/.config/calibre/server-users.sqlite --manage-users`

all have basic passwords that are hard to mess up, so I'm 99.9% sure I am putting in correct username and password.

I consistently get failed login attempts despite putting in correct details. My website uses https but I'm getting only http for calibre-web, could that be the problem?

**Comment by OzzieIsaacs** [comment]
??
Please ask for help at the program‘s repro. Calibre-Web has nothing to do with Calibre.
The command line options you are mentioning are not relevant for Calibre-web.
