### ISSUE TITLE
Links to lubimyczytac.pl 

### ISSUE THREAD

**Issue by Dinth** [janeczku/calibre-web#884]
This is somewhat related to issue #80. 
Lubimyczytac matadata import tool adds ids with "lubimyczytac:" prefix. It would be great to have those translated to links by calibre-web.

**Comment by OzzieIsaacs** [comment]
What would be the spec?
The id field contains: lubimyczytac:[id-number]
This would be translated to a link:
http://lubimyczytac.pl/????????????????????????????? -> please provide example

**Comment by Dinth** [comment]
lubimyczytac:4806681 should point to http://lubimyczytac.pl//ksiazka/4806681

thanks for looking into this.
