### ISSUE TITLE
No Module named PIL

### ISSUE THREAD

**Issue by rg9400** [janeczku/calibre-web#885]
Trying to run the latest update (e1e79a73e87dc1e480ced63c2f0c04bd1173a4c9) with Python 3.7 is not working. 

```
c:\CalibreWeb>python37 cps.py
Traceback (most recent call last):
  File "cps.py", line 13, in <module>
    from cps.server import Server
  File "c:\CalibreWeb\cps\server.py", line 25, in <module>
    import web
  File "c:\CalibreWeb\cps\web.py", line 38, in <module>
    import helper
  File "c:\CalibreWeb\cps\helper.py", line 38, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
```

**Comment by OzzieIsaacs** [comment]
Please install PILwith 
pip install Pillow
(I did a mistake during commit, I wanted to do it optionally)

**Comment by rg9400** [comment]
Thanks, that solved it. But it still won't start, I get the below error now

```
c:\CalibreWeb>python37 cps.py
[2019-04-17 13:40:40,593] INFO in web: Starting Calibre Web...
Traceback (most recent call last):
  File "cps.py", line 13, in <module>
    from cps.server import Server
  File "c:\CalibreWeb\cps\server.py", line 25, in <module>
    import web
  File "c:\CalibreWeb\cps\web.py", line 205, in <module>
    language_table = cPickle.load(f)
_pickle.UnpicklingError: the STRING opcode argument must be quoted
```

**Comment by OzzieIsaacs** [comment]
You are having a line ending problem with the file translations/iso639.pickle. Could you please replace the file with the version from:
https://raw.githubusercontent.com/janeczku/calibre-web/master/cps/translations/iso639.pickle
or
open the file with a advanced editor like notepad++ and change the line endings to Unix -> only LF 
May I ask how you updated (via git pull?)

**Comment by rg9400** [comment]
That fixed it, thanks!

I had originally just been updating via the in-built updater. But after Calibre Web stopped starting, I tried using git pull, but it said it had lost the branch tracking info. So I cloned a fresh version from the repo and copied it over my existing folder.

**Comment by OzzieIsaacs** [comment]
So I think the git pull destroyed the line endings.
