### ISSUE TITLE
Enhancement:  Multiple kindle emails addresses per calibre-web account

### ISSUE THREAD

**Issue by thomasbra1** [janeczku/calibre-web#886]
Hi,

  Would it be possible to add the feature of having multiple email addresses per calibre-web account as I have more than one Kindle in the household.  It would be nice to send the same book to all kindles without having to switch to different calibre-web accounts. The kindle email field could be comma separated for the multiple email addresses.    Thanks for all the work on this software.

**Comment by OzzieIsaacs** [comment]
I think this is a very rare usecase. I decided not to implement it, you could use several accounts to manage the different kindle devices.
Sorry

**Comment by thomasbra1** [comment]
Sorry to waste your time. I'll just find something better to use.  A very poor response.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by noooz** [comment]
I dont think this is a rare usecase. A lot of us have More than one kindle.

**Comment by noooz** [comment]
As a workaround I set my email address for the kindle address. Than I made an email filter to forward all those emails to all of my kindle addresses.
This way I get the book on all kindles and I delete it on the devices where I dont need it.

**Comment by kukudemajia** [comment]
A lot of us have More than one kindle.It would be nice to send the book to selected kindles without having to switch to different calibre-web accounts.

**Comment by zerodayz1** [comment]
This is not a rare use-case. My grandparents and mother and father all have kindles, all want the same books, and my mother/gran are never going to log into CW, and a pain for my father to have to log into 4 accounts. All we need is a semi-colon list adding.

**Comment by hthighwaymonk** [comment]
Add my vote to the "this is not rare use-case" crowd
I'd love to see this implemented

**Comment by ericvoshall** [comment]
I would also like to see this.

**Comment by oznxzar** [comment]
4 kindles at home (my wife, children and me) and 2 at my parents home, it would be nice to be able to choose with kindle send to from one account, actually I need to login/logout account by account. For me is a good enhancement so please take in consideration

**Comment by blumarten** [comment]
adding my voice to this. i wanted to set up calibre-web so various members of my family in different locations with different devices can view my library and send a book to their respective kindles

**Comment by davidalben** [comment]
I prefer to read MOBI books in my Kindle and PDF magazines in my tablet using Kindle app. It should be great to select which device I want to send a book to without logging out/in.

**Comment by ryanmccool** [comment]
Adding my vote.

**Comment by crispybegs** [comment]
+1

**Comment by davidmtml** [comment]
Another vote.  I need to sometimes send books to my kindle, sometimes to my wife's, and sometimes to the kids'.  A lot easier if there could be an option to choose which email address to send it to, instead of having to login as each individual user before sending the book.

**Comment by RobbieG3** [comment]
Please reopen this request. I'm also adding a vote to support multiple Kindle email addresses in one account.

**Comment by mingw128** [comment]
+1, well really +4 since I often send the same book to four places. I would think in 2023 it's rare to not have more than one device that someone reads from (tablet, multiple kindles, phone, etc.). A distribution list would be another way to accomplish this.
