### ISSUE TITLE
Remove 'Discover (Random Books)' from New Books screen

### ISSUE THREAD

**Issue by brianbuquoi** [janeczku/calibre-web#89]
Since Discover has its own section, it would make sense for this discovery section to not exist on the New Books screen - it becomes redundant.

It would also be nice to see an alphabetical listing, maybe under a listing for 'All Books'.

It would also be nice if it is possible to pull series information from the calibre db and have a section titled 'Series'.

**Comment by OzzieIsaacs** [comment]
You can configure this. In the user settings screen there is a checkbox show random book, there you can also change the visibility of the discover section

**Comment by brianbuquoi** [comment]
Is this functionality not available in the docker container?

**Comment by OzzieIsaacs** [comment]
The docker container is from October, I merged this feature in early november. I'm not the owner of the repository, so I can't updatethe docker container.
This can only be done by @janeczku.

**Comment by brianbuquoi** [comment]
Ah - That makes sense then. Thanks for the clarification.

**Comment by janeczku** [comment]
@brianbuquoi hey there, I'll try to get a new image to docker hub asap!

**Comment by brianbuquoi** [comment]
Thanks @janeczku!

**Comment by DreamStatic** [comment]
One more idea on this front, would love to see an additional option to "Show Random Books" and "Show Discover Link". This way we could remove the random books from each page, but keep the Discover link. This would be the best of both worlds to me. As is, Show Random Books also hides the Discover link which loses all the random options.

**Comment by brianbuquoi** [comment]
bump for newer docker image?

**Comment by OzzieIsaacs** [comment]
@DreamStatic: The newest commit on github includes the ability to display the discover section independently from the books list view

**Comment by janeczku** [comment]
Triggered a new image build. Should appear shortly: https://hub.docker.com/r/janeczku/calibre-web/tags/
