### ISSUE TITLE
Send to Kindle error

### ISSUE THREAD

**Issue by toyqiu** [janeczku/calibre-web#892]
after got my SMTP settled , it shows that "test email successfully send to ..."
BUT I got nothing

![image](https://user-images.githubusercontent.com/479873/56603646-b30ecb80-6632-11e9-9779-c3aa4ff87e9e.png)

And then I send 2 books ,they just keep stay in the Tasks.
![image](https://user-images.githubusercontent.com/479873/56604086-c3737600-6633-11e9-8b04-68614a802448.png)

**Comment by OzzieIsaacs** [comment]
It looks like the first email sending doesn't come to an end (should have status finished, to get the other tasks started). The message "E-Mail send sucessfully" caused trouble in the past, I have to change it, it's just meaning that it is sucessfully queued for sending. 
Is there relevant output on the console or in the calibre-web logfile?
Maybe you are having a similar problem than #861? 
Which python version are you using? 
Are you using Linux or windows?
Are you using docker?

**Comment by toyqiu** [comment]
I'm using docker from linuxsever/calibre-web
and the python version is 2.7.15

**Comment by OzzieIsaacs** [comment]
One other user reported problems sending emails to kindle, you could kindly refer to this issue: https://github.com/janeczku/calibre-web/issues/643#issuecomment-449656280
For now the problem has a workaround, I still don't understand this, my inital guess was not right, otherwise you should have a ... user locale: none... output.

**Comment by OzzieIsaacs** [comment]
Are there any news?

**Comment by toyqiu** [comment]
> Are there any news?

sorry,forgot to update

turns out that my email permission key had been overdue
creatting a new key was the final solution.

**Comment by OzzieIsaacs** [comment]
Thanks for the feedback. I‘ll close the issue
