### ISSUE TITLE
About admin menu

### ISSUE THREAD

**Issue by arkandzaki** [janeczku/calibre-web#893]
Hello. Iam librarian and newbie ubuntu user...
after completing installing the web browser on ubuntu 1. then I open with the browser ipaddress address: 8083, then the menu appears to make admin access.  after I created an admin account, after logging in I was unable to find the web caliber configuration menu like the one on the github site. how do I resolve this problem?  and / or someone who can help provide instructions for installing caliber web in sequence.  thank you

**Comment by arkandzaki** [comment]
Correction.. ubuntu 14

**Comment by OzzieIsaacs** [comment]
The Admin menu is the 3.right button in the top right corner, the one which is labeled Admin.

What do you mean with ...instructions for installing Calibre Web in sequence?

**Comment by arkandzaki** [comment]
![download](https://user-images.githubusercontent.com/50050210/56850707-52cca200-6930-11e9-857d-abc35d571a36.jpeg)

I cant see that menu (see image)
I cant login with user admin password admin123

**Comment by OzzieIsaacs** [comment]
Sorry, the image is very blurry I can't read anything. The only think I can say that the layout is not looking familiar to me. Are you sure you have entered the right address to access Calibre-web? Is there maybe another service running on port 8083? 
What is the content of the calibre-web.log file? Is there any output on the console?

**Comment by arkandzaki** [comment]
![calibre thumb PNG 0b8d183d643403d54adc37bddd710caf](https://user-images.githubusercontent.com/50050210/56850853-5eb96380-6932-11e9-8346-5ad910bc4395.PNG)

I can access my ip: 8080.  I use a new computer, no other application uses that port.

**Comment by OzzieIsaacs** [comment]
You are trying to configure the docker image of calibre-web from linuxerver?!
Please ask for help at their reporistory (https://github.com/linuxserver/docker-calibre-web). 
I'm not the programmer of the docker image, and I can not provide support for it.
