### ISSUE TITLE
Download / Read only

### ISSUE THREAD

**Issue by dxcore35** [janeczku/calibre-web#894]
Hello, my suggestions are visible on attached picture.

1) Allow to download book only when book have copyright column with value: No.
If there is no such column this can be considered do be downloadable by default. Therefore you don't need to implement special settings. 

2) Move VIEW and DOWNLOAD buttons under cover
3) Change color for buttons

4) If book is downloadable (pass the point number one) then generate QR code for direct download from other device. The QR code can be generated for each format separately... or predefined format can be set. This QR generation is extremely useful when your software is running in library terminal PC, where user can just read or get details about book. If no copyright, user just scan the QR code with mobile and receive direct link for download / or he get list of file formats and then he can download selected book in format he likes.... Maybe in this case just QR code should be there no button to download the book to terminal PC....

![Screen Shot 2019-04-27 at 20 13 11](https://user-images.githubusercontent.com/7279156/56850655-793c0e80-692b-11e9-828d-961979a9dd88.jpg)

**Comment by arkandzaki** [comment]
I am interested.  how to make an appearance like that

**Comment by OzzieIsaacs** [comment]
I don't want to add any more specialties and options to calibre-web, there are already so many options which confuses many users
