### ISSUE TITLE
Feature Request: All metadata

### ISSUE THREAD

**Issue by dxcore35** [janeczku/calibre-web#895]
Show all metadata field in both themes. Allow to chose which:

1) Are visible
2) Allow to change order of metadata fields

**Comment by OzzieIsaacs** [comment]
This is way to complicated and will cause more trouble than benefit (from my point of view).
Sorry, but I will not implement this.

**Comment by dxcore35** [comment]
So why the 2 themes are handling this issue differently? 
The white is showing additional custom field but not all....
The dark is showing just default one...

So at least unification of the themes is needed....

**Comment by shayaknyc** [comment]
Hi, searched and landed on this issue. Is it possible to at least toggle on/off the display of custom metadata columns?

**Comment by OzzieIsaacs** [comment]
There is such feature (admin section -> UI config -> Regular expression for ignoring columns), but it's indeed currently not really working (you have to add all columns you want to see, but not the name calibre-web shows, you should use the label (?) of the column. I try to fix it.

**Comment by shayaknyc** [comment]
@OzzieIsaacs not sure I understand....mine is currently blank, as I don't want to ignore ANY columns. If I look at the HTML source code, it shows quite a number of `<div class="real_custom_columns"></div>` that are just empty, and different books will arbitrarily load different metadata columns to display, even though they all have the same entries in the same custom columns. Any insight here would be great as I'd love to see all my custom metadata. For example, I try to cross-reference my books to also include their DDC (Dewey Decimal Classification), as well as it's LOC (Library of Congress) number, which I then translate to Genre. I also include word-count, as well as the Flesch-Kinkade Grade, Flesch Reading Ease and the Gunning Fog quotient. While the interface allows me to search in the advanced search against these columns, they're not displaying in the book detail at all.
