### ISSUE TITLE
"MIME type ('text/plain') is not executable" error on latest Chrome

### ISSUE THREAD

**Issue by subdiox** [janeczku/calibre-web#896]
On `readcbr.html`, I always get the following error on the latest Chrome:
```
Refused to execute script from 'http://localhost:8083/static/js/io.js' because its MIME type ('text/plain') is not executable.
unzip.js:15 Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:8083/static/js/io.js' failed to load.
    at http://localhost:8083/static/js/unzip.js:15:1
```

On Microsoft Edge or Safari, the browsers execute 'text/plain' JavaScript files, but maybe Chrome does not.
How can I fix this issue?

Server Environment:
```
OS: Windows 10 Pro 64bit
Python: 3.7.3
```

**Comment by OzzieIsaacs** [comment]
For me it's working:
![grafik](https://user-images.githubusercontent.com/6438895/57027677-57999a80-6c3d-11e9-8031-7a96e2c71b0b.png)
I checked it with server running on Linux Mint and Windows 10, running Chrome 74.somewhat. I think decisive is which server-(version) calibre-web uses. I tred tornado 4.5.2 and 5.1.1 and gevent 1.3.7. Could you please check which version you are using (on the abouts section, either gevent or tornado should be listed).
You are using the version 0.6.2 and no docker or other stuff in between?

**Comment by subdiox** [comment]
I checked the about section and it's using tornado v6.0.2.
Maybe the version of tornado is too new?

**Comment by OzzieIsaacs** [comment]
Tried, with absolut fresh installation of python 3.73 on Windows10 Pro 64Bit it's still working:
![grafik](https://user-images.githubusercontent.com/6438895/57101560-cd773200-6d21-11e9-8896-1d8b5ab0a184.png)
![grafik](https://user-images.githubusercontent.com/6438895/57101729-1a5b0880-6d22-11e9-9a19-735ca7178936.png)

Do you have any addons, extensions,... activated in Chrome?

**Comment by subdiox** [comment]
Sorry, this issue was my fault.
I googled this error message and found a solution. My system registry setting of javascript files was changed somehow. I changed the value from 'text/plain' to 'application/javascript', the calibre-web started working on Chrome again. Thank you for your support.

- Reference
https://github.com/jupyterlab/jupyterlab/issues/6098#issuecomment-474098196

**Comment by rainsuns** [comment]
原谅我使用中文。
我在win10,python3.8出现了两样的问题。
解决方法如下：
打开cps\wep.py，按下图修改。
暂时能解决问题，在线升级后需要再次修改。
![鍥惧儚 066](https://user-images.githubusercontent.com/26184114/87519715-92f27e80-c6b4-11ea-8990-aa2f1dbde99d.png)
![鍥惧儚 067](https://user-images.githubusercontent.com/26184114/87519720-9554d880-c6b4-11ea-9244-d112afd7f0b6.png)
![鍥惧儚 068](https://user-images.githubusercontent.com/26184114/87519722-95ed6f00-c6b4-11ea-950a-6437ea7b4387.png)

cdn也可能导致此问题。

**Comment by candidodmv** [comment]
I faced the same problem on Windows 10 with python 3.7.8 and solved with the suggestion made of by @rainsuns but in more radically way comment the entire mentioned method (`add_security_headers`), and magically the issue has gone !
