### ISSUE TITLE
Read in browser does not work with PDF and ZIP

### ISSUE THREAD

**Issue by joshuaavalon** [janeczku/calibre-web#897]
Version: 0.6.2 & 0.6.3 Beta

PDF does not show any errors in web console or log.

ZIP return 500 by server.

Logs:
```
[2019-04-29 08:55:11,436] ERROR in app: Exception on /read/4/zip [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
```

The files can be downloaded and epub work fine.

**Comment by OzzieIsaacs** [comment]
> PDF does not show any errors in web console or log.

Is this a different problem than the problem in the next line, or does it belong to it?

Zipfiles in the latest commit should output an "not supported" message. It's also no longer possible to upload zip-files. I checked the behaviour in calibre, if you add zipfiles with jpgs inside, they are renamed to cbz, and pdf files are extracted.

**Comment by joshuaavalon** [comment]
> Is this a different problem than the problem in the next line, or does it belong to it?

I mean the PDF reader does not load the PDF. I checked the web console log and error log after I open PDF reader but there are not any error message shown. My guess is the PDF is not loaded.

> Zipfiles in the latest commit should output an "not supported" message. It's also no longer possible to upload zip-files. I checked the behaviour in calibre, if you add zipfiles with jpgs inside, they are renamed to cbz, and pdf files are extracted.

I can get CBZ working. If ZIP is not supported, may be it should be removed from `Read in browser`. I also has AWS3 format but it is not show in `Read in browser`. If it is shown in `Read in browser`, it suggested that it should support.

**Comment by OzzieIsaacs** [comment]
I‘m aware of the pdf not loading problem, a page reload helps. I try to fix it.
Regarding zip files you are right

**Comment by OzzieIsaacs** [comment]
The newest nightly version should now load the pdf files withut reload. I removed zip, tar and rar files from the readers list.
