### ISSUE TITLE
About Library aka cps and Calibre Web

### ISSUE THREAD

**Issue by arkandzaki** [janeczku/calibre-web#898]
I managed to install the CPS aka Library, at the link https://github.com/mutschler/calibreserver#library-aka-cps. the display as follows.
file:///home/ebookserver/Pictures/Screenshot%20from%202019-04-29%2015:10:01.png

is that different from Caliber-Web https://github.com/janeczku/calibre-web
  if it is different, how do I switch the Library aka cps to the web caliber?

**Comment by arkandzaki** [comment]
![library   Latest Books](https://user-images.githubusercontent.com/50050210/56884845-2d0cdd80-6a95-11e9-835d-90c1f455f471.png)

**Comment by OzzieIsaacs** [comment]
Calibre-web evolved much from library. There is no direct way of migrating. 

Please stop library delete the files and copy the new files from 
https://github.com/janeczku/calibre-web/archive/0.6.2.zip to the library folder. Then please follow the instructions in the readme ( It‘s a good idea to delete the app.db in the root folder before starting).

**Comment by arkandzaki** [comment]
after delete the files and copy the new files from
https://github.com/janeczku/calibre-web/archive/0.6.2.zip to the library folder. 
I run the command according to the readme file but when I run the command: python cps.py
there is an error as follows:

Traceback (most recent call last):
  File "cps.py", line 13, in <module>
    from cps.server import Server
  File "/opt/calibreweb/cps/server.py", line 25, in <module>
    import web
  File "/opt/calibreweb/cps/web.py", line 27, in <module>
    from flask import (Flask, render_template, request, Response, redirect,

how to overcome?

**Comment by arkandzaki** [comment]
![Screenshot from 2019-04-30 08_58_45](https://user-images.githubusercontent.com/50050210/56937459-fda6b100-6b26-11e9-868d-8d8f12aad6d8.jpg)

**Comment by OzzieIsaacs** [comment]
You are missing dependencys. From your screenshot I can see that the installation of pillow fails. Could you please delete the last line from requirements.txt (Pillow...) file Rerun:

> 1. Install dependencies by running pip install --target vendor -r requirements.txt.

And try again. If the errormessage Importerror... is still popping up, please try to follow the procedure in: https://github.com/janeczku/calibre-web/wiki/FAQ

**Comment by arkandzaki** [comment]
I gave up, I used Ubuntu 14 LTS. I followed all the guidelines, but it still didn't work. I have to learn more.
thank you for your attention...

**Comment by arkandzaki** [comment]
I was desperate. but after slowly I looked and I learned that I could finally install it.
as a note for installing web-caliber on Ubuntu 14:
1. Download Caliber Web "https://github.com/janeczku/calibre-web"
2. open the terminal then extract and move it in / usr (example: / opt or di / var)
3. Go to the folder where the web-Caliber file is located
4. Check the Python version with the command = "python --version"
make sure there is python version 2 (if not version 2 install python version 2)
5. install pip python with the command = "apt-get install python-pip"
6. install the tornado with the command = "apt-get install python-tornado"
7. Install pillow for Ubuntu 14 "sudo apt-get install libtiff5-dev libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python-tk" and "sudo pip install pillow "
8. edit the requirement.txt file (in the web-caliber folder), then discard the "tornado" and "pillow" text then save
9. run the command "sudo apt-get update" and continue with the command "pip install --target vendor -r requirements.txt" (make sure there are no errors)
10. run the "python cps.py" command
11. Open the browser, type "localhost: 8083" in the url

I attach the requirements.txt file
[requirements.txt](https://github.com/janeczku/calibre-web/files/3130551/requirements.txt)

tahnk you for
OzzieIsaacs

**Comment by OzzieIsaacs** [comment]
For No.4 python3 should also work, ubuntu14.04 is rather old, I'm not sure if was included in standard. For python3 (the future, as python2 end of life will be 1st january 2020). The pip command should be pip3.
No. 5: In Ubuntu14.04 the tornado version is 3.1, which is also very old. The support for ubuntu 14.4 ends today, so you should think about updating to a newer version, then you should have less problems.
I agree with you, the python stuff sometimes causes headaches, the more you are doing it, the more you are getting used to it.
I'm happy you got it to run
