### ISSUE TITLE
Request: Report of users downloading/sent what books

### ISSUE THREAD

**Issue by sbelongie** [janeczku/calibre-web#9]
I think this would be a nice feature to have so we can have some sort of history of who downloaded/sent what books.

**Comment by sbelongie** [comment]
I can do via sql queries if needed but it would be nice not to.

**Comment by cervinko** [comment]
on the admin page when you click on a nickname you get to admin/user/<userid>
at the bottom of this page the recent downloads (but actually i thin all download) of this user are listed.

is this the feature you where looking for??

**Comment by sbelongie** [comment]
Yes I am sorry I didn't realize that existed.  Cheers
