### ISSUE TITLE
Request: The ability to approve registration requests and/or send invitations for users to register

### ISSUE THREAD

**Issue by pjortiz** [janeczku/calibre-web#901]
I think the ability to approve registration requests and/or sending an invitation for users to register would be a better alternative to a public registration.

Perhaps by the User List in the admin view adding a button to approve or deny a new user registration. 

Or adding a invite new user button next to add new user. User would receive an email with a uniquely generated URL Link that brings them to the registration page.

**Comment by OzzieIsaacs** [comment]
I added the possibility of denying certain domain names, and also allowing only certain domain names. The admin can create a user, later on send a password to a user via reset user password in the edit users section.
I decided to focus more on enhancing the book organization and presenting features and doing less user management. 
So this is as far as I'm supporting your request.

**Comment by taxilian** [comment]
Just as a question of clarification -- because I don't have time to do it myself anyway =] -- would you be open to accepting a pull request to add this functionality if someone wanted it?

**Comment by OzzieIsaacs** [comment]
In general yes, but not if only the "initial work is done". The extended functionality should work and also handle error cases. 
Meanwhile I'm spending most of my time to create tests for the function already present in calibre-web and a feature change of only some minutes work creates testing effort for hours (and I hate writing tests). 
On the other hand I see that it is really helping to improve the software.
![grafik](https://user-images.githubusercontent.com/6438895/119219417-cb899280-bae5-11eb-82e3-db093071a057.png)

**Comment by minermartijn** [comment]
Dear Ozzielsaacs,

I know this request was closed 3 years ago.
But i was wondering if you now do have some extra time for this feature.

This feature would be really helpful, i think for multiple users.
If not, thats fine and ill have to make users for the people that want to use my server.
