### ISSUE TITLE
default login problem

### ISSUE THREAD

**Issue by arkandzaki** [janeczku/calibre-web#902]
yesterday I managed to install Caliber-web.
I can't login using
Default admin login:
Username: admin
Password: admin123
why?

**Comment by OzzieIsaacs** [comment]
Could you please send me the Calibre-web.log file? 
Could you please send me the app.db file via private message? ( E-mail on my profile page)

Thanks

**Comment by arkandzaki** [comment]
I have sent to your email: ozzie.fernandez.isaacs@googlemail.com
thank you

**Comment by OzzieIsaacs** [comment]
There is no admin user in the database:
![grafik](https://user-images.githubusercontent.com/6438895/57069996-6d0ed300-6cd6-11e9-9797-ef6bdc675c5e.png)
So either it's an migration problem from "library" program, or you acidently deleted it. Please stop calibre-web, delete the app.db file, start calibre-web again. You should then do the configuration again. afterwards the user admin is present, and login should work.

**Comment by arkandzaki** [comment]
I have re-installed the web-caliber, but still cannot log in with the default user and password.  even though I tried inputting the user manual from sqliteman, the result was the same I could not log in with the user and password I made.  can you help me create an admin user from sqliteman?

**Comment by arkandzaki** [comment]
the solution is quite easy, when I change OS from ubuntu 14 to ubuntu 18, everything runs smoothly,
the problem I face now is:
1. how to make a report on the use of books by users, such as user history, download reports by each user

**Comment by arkandzaki** [comment]
thank you

**Comment by OzzieIsaacs** [comment]
Open question is moved to nee issue #944
