### ISSUE TITLE
Feature Requests: Connect to OneDrive

### ISSUE THREAD

**Issue by idealclover** [janeczku/calibre-web#905]
I use OneDrive for sync my calibre folder. For calibre-web support gdrive, which I cannot use in China, I hope it can add support for OneDrive.

**Comment by askvittorio** [comment]
Please add support for MS Odrive, I use it as well for Calibre libraries.

**Comment by OzzieIsaacs** [comment]
I understand your request and see that it would be nice to have it. But after implementing the gdrive storage this caused a lot of trouble, caused many bugs. I don't want to do this again, I'd like to focus on the core feature of calibre-web (displaying calibre-db in a nice ways and offer options to search and filter books).
I decided not to implement it.

**Comment by Efreak** [comment]
Suggestion: instead of using PyDrive, use PyFilesystem, which has [plugins](https://www.pyfilesystem.org/page/index-of-filesystems/) for ftp, smb, sftp, webdav, google drive, dropbox, onedrive, s3.

**Comment by Borber** [comment]
Is it possible to restart the project? I also use onedrive

**Comment by OzzieIsaacs** [comment]
No, I regret the gdrive Integration every day. I Added a corresponding sentense to the contribution rules https://github.com/janeczku/calibre-web/blob/master/CONTRIBUTING.md#feature-request

**Comment by Borber** [comment]
> No, I regret the gdrive Integration every day. I Added a corresponding sentense to the contribution rules https://github.com/janeczku/calibre-web/blob/master/CONTRIBUTING.md#feature-request

Okay, I get it.
