### ISSUE TITLE
Run as Windows Service

### ISSUE THREAD

**Issue by centuryx476** [janeczku/calibre-web#907]
Hello,
Since this is a python coded application.
How can I have the calibre-web server running if I were to log off the server ?
Is there a way to run this as a service ?
This is a Windows server Core

Thank You

**Comment by OzzieIsaacs** [comment]
This one could help you:
https://www.sevenforums.com/tutorials/67503-task-create-run-program-startup-log.html

Googling for ‚create windows service from python script‘ could also provide some useful hints

**Comment by centuryx476** [comment]
Hello,
Yeah that is a weird way of doing it. 
If I were to install this on a Linux box and use "Screen" would the script stop running ?

**Comment by OzzieIsaacs** [comment]
A "linux box" would be what? 
For Linux there are installation instructions for creating a service in the wiki. If you want to start a script which continues to run after you close a remote session you could use 'nohup'. I personally have no experience with screen.
I would appreciate it, if you try to use your favourite web search engine to get your questions answered.

**Comment by centuryx476** [comment]
Hello,
I have been using google. Using windows for this particular application is basically zero, which is why I came here. I either end up with "AlwaysUP" application which costs an insane amount of money or using "Windows Scheduler" which I hate to use.

I'm just a user who is trying to find the most effective and efficient way of running this application on a windows box and I would "Appreciate" less sarcasm on your part as that is a prime way of pushing people away from using such an awesome application. This is the projects main source of information so I will naturally come here to ask a question on it. 

I have been able to hop together some sources on my "favorite web search engine" to make something work for our environment. 

Closing out

**Comment by OzzieIsaacs** [comment]
I'm sorry that I could not help you. 
I try to document how to install calibre-web as good as possible in the wiki. 
This evening I spend some time using google to answer your questions, because I don't know how to do it also. 
From my point it's not a question on how to use calibre-web as a service under windows, but the general question how to start a python script under windows as service. Your question was very general, so I could not figure out what your special needs are. 
To make it a positive end, if you are willing to share your solution with me, I'll include it into the wiki and everybody has a benefit of it.

**Comment by centuryx476** [comment]
Hello,
Let me do a test on my development box when I get home and I'll let you know. 
It is always good to share the knowledge for all to benefit  (100% agree) on that...

**Comment by centuryx476** [comment]
Hello,
So I got it to work. I had to use the Windows Scheduler

Rough Steps

- Install Python onto Windows (Core or GUI)

- Insure you add Python to the environmental variables

- Check if python is reachable via CMD
![image](https://user-images.githubusercontent.com/38863757/57266861-daf72980-704b-11e9-900a-dd245b969bdc.png)

- Create folder called "Calibre-Web)" name whatever you like and extract the "Calibre-web" files into the folder
![image](https://user-images.githubusercontent.com/38863757/57266980-5bb62580-704c-11e9-8c51-5ab73ceb3ee1.png)

- Change directory to "C:\Calibre-Web", run the below command to install the requirements
install --target vendor -r requirements.txt
![image](https://user-images.githubusercontent.com/38863757/57267031-8a340080-704c-11e9-85fd-3c970bc45ace.png)


Using Windows Scheduler to auto-run application

- Create batch script file (Run_Calibre_Web.bat) name it whatever you want
I put the batch file in "C:\Install_Folder", you can place it where ever you like
Insert the below code, change the directories to suit your needs
"C:\Users\UserName\AppData\Local\Programs\Python\Python37-32\python.exe" "C:\Calibre-Web\cps.py"
![image](https://user-images.githubusercontent.com/38863757/57267129-f878c300-704c-11e9-8689-382d5e237d54.png)


Create Schedule Task

![image](https://user-images.githubusercontent.com/38863757/57267169-25c57100-704d-11e9-8aed-39328f4c501f.png)

General Tab
Make sure you select the highlighted areas
![image](https://user-images.githubusercontent.com/38863757/57267285-7f2da000-704d-11e9-9fc3-76f6935483d6.png)

Triggers Tab
![image](https://user-images.githubusercontent.com/38863757/57267327-aedca800-704d-11e9-95af-eeb688529c30.png)

Actions Tab (I am using "C:\Install_Folder") to place the batch file
![image](https://user-images.githubusercontent.com/38863757/57267365-d92e6580-704d-11e9-9f7c-88566e5c9cc6.png)

Settings Tab
![image](https://user-images.githubusercontent.com/38863757/57267394-fd8a4200-704d-11e9-9eeb-65d3cdc44498.png)

With the schedule task, Calibre-Web will run on its own even with the user logged off

**Comment by centuryx476** [comment]
I'm sure you can take these steps and make them better presentable for the wiki

**Comment by OzzieIsaacs** [comment]
Thanks for the good pictures, I've included the informations into the wiki and consider this issues as solved now.

**Comment by Maddog0057** [comment]
https://nssm.cc/ - I've used this to run other python scripts as a service in the past, it's relatively easy to setup.

**Comment by Alacritous** [comment]
I've got it running as a service controlled by systemd. 

Copy the following and save as /etc/systemd/system/calibre-web.service

The comments say what all the bits do. If you don't want to use www-data as the user, then you can probably just change those lines to your username and group. 

```
# First off, this script must be installed in /etc/systemd/system
# it must be named 'calibre-web.service'
# To enable, use 'sudo systemctl enable calibre-web
# To start/stop use sudo systemctl start calibre-web   or sudo systemctl stop calibre-web

# To consult the log : journalctl -u calibre-web
[Unit]
Description=Calibre-web
After=syslog.target network.target
[Service]

#Full Path to where you've installed the cps.py python script.
# I've installed mine at /usr/bin/calibre-web/cps.py for example

ExecStart=/usr/bin/calibre-web/cps.py

# user and group that calibre-web will run as.  I am running apache2 
# so I put the www-data user as the owner of the /usr/bin/calibre-web directory
# You could probably put the executable files in your user directory, then you could just 
# run it as your username and group and everything would be fine. 
# this works for me. 

User=www-data
Group=www-data
Nice=10
SyslogIdentifier=calibre-web
StandardOutput=syslog
# Make calibre-web restart if it fails
Restart=on-failure
# calibre-web need a SIGINT to be notified to stop
KillSignal=SIGINT

[Install]
WantedBy=multi-user.target

```

**Comment by graphit0** [comment]
@Alacritous Thank you for the script, it saved a lot of time! 

> `ExecStart=/usr/bin/calibre-web/cps.py`

additionally if some folks have troubles with it, this line might needs to be changed to 
`ExecStart=/usr/bin/python3 /usr/bin/calibre-web/cps.py`
(the original line runs with python 2 on my setup for some reason by default and gets broken later on)

**Comment by Alacritous** [comment]
Check the shebang in the cps.py file.  That's the bit that should appear on the first line of the file that directs the system to use a particular interpreter to run the file.  

It will look something like this.  

#!/usr/bin/env python

**Comment by mattb112** [comment]
> Hello, So I got it to work. I had to use the Windows Scheduler
> 
> Rough Steps
> 
> * Install Python onto Windows (Core or GUI)
> * Insure you add Python to the environmental variables
> * Check if python is reachable via CMD
>   ![image](https://user-images.githubusercontent.com/38863757/57266861-daf72980-704b-11e9-900a-dd245b969bdc.png)
> * Create folder called "Calibre-Web)" name whatever you like and extract the "Calibre-web" files into the folder
>   ![image](https://user-images.githubusercontent.com/38863757/57266980-5bb62580-704c-11e9-8c51-5ab73ceb3ee1.png)
> * Change directory to "C:\Calibre-Web", run the below command to install the requirements
>   install --target vendor -r requirements.txt
>   ![image](https://user-images.githubusercontent.com/38863757/57267031-8a340080-704c-11e9-85fd-3c970bc45ace.png)
> 
> Using Windows Scheduler to auto-run application
> 
> * Create batch script file (Run_Calibre_Web.bat) name it whatever you want
>   I put the batch file in "C:\Install_Folder", you can place it where ever you like
>   Insert the below code into the batch file, change the directories to suit your needs
>   "C:\Users\UserName\AppData\Local\Programs\Python\Python37-32\python.exe" "C:\Calibre-Web\cps.py"
>   ![image](https://user-images.githubusercontent.com/38863757/57267129-f878c300-704c-11e9-8689-382d5e237d54.png)
> 
> Create Schedule Task
> 
> ![image](https://user-images.githubusercontent.com/38863757/57267169-25c57100-704d-11e9-8aed-39328f4c501f.png)
> 
> General Tab Make sure you select the highlighted areas ![image](https://user-images.githubusercontent.com/38863757/57295491-a6f62580-7098-11e9-94e9-3775f962d783.png)
> 
> Triggers Tab ![image](https://user-images.githubusercontent.com/38863757/57267327-aedca800-704d-11e9-95af-eeb688529c30.png)
> 
> Actions Tab (I am using "C:\Install_Folder") to place the batch file ![image](https://user-images.githubusercontent.com/38863757/57267365-d92e6580-704d-11e9-9f7c-88566e5c9cc6.png)
> 
> Settings Tab ![image](https://user-images.githubusercontent.com/38863757/57295427-78784a80-7098-11e9-9f27-a7789796b02f.png)
> 
> With the schedule task, Calibre-Web will run on its own even with the user logged off

I know this is really old but I dont know how to make a bat file and would love to use this

**Comment by OzzieIsaacs** [comment]
Just open an simple text editor like notepad, type the content into it and save it with the ending .bat

**Comment by mattb112** [comment]
@echo off
cd "C:\Users\PC\AppData\Local\Programs\Python\Python310\python.exe"
start python.exe
cd "C:\Calibre-Web\cps.py"
start cps.py 

not working for me cause again I dont know how to write a bat file correctly lol

**Comment by OzzieIsaacs** [comment]
```@echo off
cd "C:\Users\PC\AppData\Local\Programs\Python\Python310"
start python.exe "C:\Calibre-Web\cps.py"
```

**Comment by mattb112** [comment]
well that got it to work Thx!!
