### ISSUE TITLE
Feature Request: download as <book title>.<book format>

### ISSUE THREAD

**Issue by nothingbut** [janeczku/calibre-web#912]
Currently we can just download the book as <book id>.<book format>. Is it possible to provide a configuration to switch the download file name between <book title>.ext and <book id>.ext?

**Comment by OzzieIsaacs** [comment]
I'm not sure if I understand the question/request?
If you are having a book with different formats such as pdf, epub and so on, you can download each individual bookformat. The books are named according to the rule [authorname] [title].[fileformat]
What is your expected behaviour?

**Comment by OzzieIsaacs** [comment]
On response for Long time
