### ISSUE TITLE
Request: Add location picker for initial metadata.db /config form

### ISSUE THREAD

**Issue by decentral1se** [janeczku/calibre-web#914]
It is unclear to me whether to pass a relative or absolute path to this form field entry to point `calibre-web` to the `metadata.db` file. This lead me to think that it might be easier to simply add a file path picker (what users typically expect) when picking the path to this file. 

What do you think? I'll take a stab at implementation if we're agreed.

---

Some other thoughts on this form:
  * It forgets entries when it reloads, so you have to type it all in again
  * The error messaging is very general. It's not clear what the problem is

**Comment by OzzieIsaacs** [comment]
Very good idea, I was also thinking about this, as it's one of the most asked questions 
A few month ago I was pointed towards a security risk during installation (#716) and stated that typing in the location of the metadata.db acts as some sort of "second factor for authentication". 
But non the less I think having a "serverside" filebrowser for selecting the right location would help a lot.

**Comment by decentral1se** [comment]
I won't be getting time to pick this up unfortunately, so I will close this off (I use my issues as a TODO list). Glad you like the idea and hopefully someone can pick this up soon.

**Comment by decentral1se** [comment]
OK, I'm back to tackle this :)

**Comment by decentral1se** [comment]
Hey, I was giving this a shot with a simple diff:

```
diff --git a/cps/templates/config_edit.html b/cps/templates/config_edit.html
index cef969d..a7bda25 100644
--- a/cps/templates/config_edit.html
+++ b/cps/templates/config_edit.html
@@ -17,7 +17,7 @@
       <div class="panel-body">
     <div class="form-group required">
       <label for="config_calibre_dir">{{_('Location of Calibre database')}}</label>
-      <input type="text" class="form-control" name="config_calibre_dir" id="config_calibre_dir" value="{% if content.config_calibre_dir != None %}{{ content.config_calibre_dir }}{% endif %}" autocomplete="off">
+      <input type="file" class="form-control" name="config_calibre_dir" id="config_calibre_dir" value="{% if content.config_calibre_dir != None %}{{ content.config_calibre_dir }}{% endif %}" autocomplete="off">
     </div>
     <div class="form-group required">
       <input type="checkbox" id="config_use_google_drive" name="config_use_google_drive" data-control="gdrive_settings" {% if content.config_use_google_drive %}checked{% endif %} >
```

And realised something. This will work for "local" installations but not for remote ones, right? I mean, the file picker automatically looks at your own local file system. So, when I have calibre-web on a VPS and my calibre database is on that file system ...

Any hints?

**Comment by OzzieIsaacs** [comment]
I'm aware of this. We need something like a server side file browser. The most fitting plugin "jquery file tree" (https://github.com/jqueryfiletree/jqueryfiletree) is outdated, so something like jstree (https://www.jstree.com/) could do the job. As you already realized it's more than just changing the html page, that's why I didn't do it yet. 
We need to create a dialog box, get the data of the file structure via ajax calls and implement a backend in python for generating the tree information.

**Comment by hobbygirl** [comment]
I hope this happens soon. I have installed Calibre-web and my drive has a folder called ‘My Library’. I have created my database and it is in the root of that folder. I can’t figure out how to enter the path to the database on caliber-web. It says DB Location is not Valid, Please Enter Correct Path.

**Comment by OzzieIsaacs** [comment]
In the newest commit version there is a file picker for the metadata.db file. For security reasons it's deactivated on an unconfigured instance. To activate it start calibre-web with parameter -f, like:
python3 cps.py -f
