### ISSUE TITLE
[Mac] Homebrew for calibre-web

### ISSUE THREAD

**Issue by jef** [janeczku/calibre-web#917]
## Problem statement
calibre-web would be great ran as service and very easy to setup if it was in Homebrew.

### Additional information
It would be handy to have calibre-web run as brew service.

## Ways to fix
Create a formulae that would download the project, requirements, and enable the service

**Comment by hijxf** [comment]
I'd like to take a stab at this this weekend. Has this been tried in the past or is there any reason that it hasn't succeeded?

**Comment by OzzieIsaacs** [comment]
I‘m getting very less feedback regarding macOS, so I guess nobody tried. I think it should be possible.

**Comment by hijxf** [comment]
Sweet. I'll get to it this weekend and update the `README.md`

**Comment by decentral1se** [comment]
Could consider integrating with https://yunohost.org, for example.

**Comment by hijxf** [comment]
Cool idea. I'd have to counter and say that Docker is already good enough for that type of use case. Especially using linuxserver.io, which this project already provides. They [linuxserver.io] have many images that deploy to different types of architectures. Include some dashboarding for these types of services.

Seems like a cool project though...

**Comment by hijxf** [comment]
I wrote this up: https://github.com/hijxf/homebrew-calibre-web/blob/master/HomebrewFormula/calibre-web.rb

Doesn't seen to be working right now, trying to figure out why if anyone wants to see...

**Comment by jef** [comment]
Abandoned this idea... just using Docker.
