### ISSUE TITLE
Is there anyway to activate the Hypothesis annotation tool in epub reading page?

### ISSUE THREAD

**Issue by waynia** [janeczku/calibre-web#918]
Hello,

    I've installed calibre-web to build my own online library for a while, and felt it neccessary to add the annotation function for noting some important ideas. One of the ideal way to do annotation nowadays is to use the hypothesis.js. 

    As Calibre-web uses epub.js to render books with epub format in a generated <iframe> tab, and the only way to make the page annotable is to include a <script> tag  containg hypothesis.js into the <iframe> tag.  

    So, my question is: the <iframe> tag is generated by epub.js, how could I add the <script> tag in this generated <script> tag? For the <iframe> tag is generated actively, which means I could not archieve this goal by modifying the static template "read.html".

    Thanks~ (I hope that I have explained my question clearly...as the text above seems a little bit long)

**Comment by OzzieIsaacs** [comment]
I‘m not sure about the direction of your question. There is an example on the fututurepress Website for the feature you are requesting:
https://github.com/futurepress/epub.js/blob/master/examples/hypothesis.html
https://github.com/futurepress/hypothesis-reader
You should/could try to merge the Feature to Calibre-Web. The right Template file is:
https://github.com/janeczku/calibre-web/blob/master/cps/templates/read.html
Does this answer your question?

**Comment by waynia** [comment]
> I‘m not sure about the direction of your question. There is an example on the fututurepress Website for the feature you are requesting:
> https://github.com/futurepress/epub.js/blob/master/examples/hypothesis.html
> https://github.com/futurepress/hypothesis-reader
> You should/could try to merge the Feature to Calibre-Web. The Template file you are mentioning is the right one. (Sorry, for the first version, didn‘t read your post detailed enough)
> Does this answer your question?

Thanks very much for your reply~

I've read the examples in the two given links before I posted this issue. 

For the first link, I pasted the js codes in the <script> tag to the 'read.html' in calibre-web, but didn't work, and did not know why as well...

For the second one, the code even did not work correctly (the demo I downloaded did not render epub book correctly).

So I came here to see if there is some solution to this question. 

As the developer of hypothesis.js said, the solution is rather direct: just add a property to the <iframe> tag to activate the annotation function (https://h.readthedocs.io/projects/client/en/latest/publishers/embedding/) ,however, the <iframe> tag in calibre-web is not static, but a generated tag by epub.js, so I could not add the property as the link given said.

If there is any existing solution, it would be great, but if not, it's still ok... I would wait for someone to solve this, for I've spent a bit long time trying different ways but not succeeded...

**Comment by paulhybryant** [comment]
@waynia 
The example at https://github.com/futurepress/epub.js/blob/master/examples/hypothesis.html works with the following change:

Replace the two <script> tag on top with the following (it is just to point to the correct js path and prepare book url)

  <script type="text/javascript">
      window.calibre = {
          filePath: "{{ url_for('static', filename='js/libs/') }}",
          cssPath: "{{ url_for('static', filename='css/') }}",
          bookmarkUrl: "{{ url_for('bookmark', book_id=bookid, book_format='EPUB') }}",
          bookUrl: "{{ url_for('get_download_link_ext', book_id=bookid, book_format="epub", anyname='file.epub') }}",
          bookmark: "{{ bookmark.bookmark_key if bookmark != None }}",
          useBookmarks: {{ g.user.is_authenticated | tojson }}
      };
  </script>
  <script src="{{ url_for('static', filename='js/libs/jszip.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/libs/epub.min.js') }}"></script>

And update the part where the url of the book is set:
    var book = ePub(window.calibre.bookUrl);

But the look and feel is different from the original layout in calibre-web.

I am not sure what is required to integrate the hypothesis.js into calibre-web.
@OzzieIsaacs can comment on that.

**Comment by paulhybryant** [comment]
Or better yet, I just found out that you can simply install:
https://chrome.google.com/webstore/detail/hypothesis-web-pdf-annota/bjfhmglciegochdpefhhlphglcehbmek

And annotation just works.

**Comment by OzzieIsaacs** [comment]
After reading a few more minutes about hypothesis, my preferred solution would be using the chrome add on or the add on for the other browsers (https://web.hypothes.is/help/installing-the-bookmarklet/).
Otherwise I would spend weeks and month to implement it for pdf linking it to your online account and so on..

**Comment by paulhybryant** [comment]
yeah the chrome extension works fine. I don't see a strong need to integrate that for now.

**Comment by xcffl** [comment]
> After reading a few more minutes about hypothesis, my preferred solution would be using the chrome add on or the add on for the other browsers (https://web.hypothes.is/help/installing-the-bookmarklet/).
> Otherwise I would spend weeks and month to implement it for pdf linking it to your online account and so on..

I don't think we need to implement that much. Just adding the following lines into templates makes it:
````javascript
  <script type="text/javascript">
    window.hypothesisConfig = function () {
      return {
        openSidebar: false,
        enableMultiFrameSupport: true,
        onLayoutChange: function(state) {
          var main = document.querySelector('#main');
          if (state.expanded === true) {
            main.classList.add("open");
          } else {
            main.classList.remove("open");
          }
        }
      };
    };
  </script>
  <script src="https://cdn.hypothes.is/hypothesis"></script>
````

For pdf files, maybe we'll need to add another simple template in which the pdf file is integrated.

It's true that Single Sign On requires a lot of work. Plus, according to https://github.com/hypothesis/h/issues/1296 it's not possible to login the official public Hypothesis instance with calibre-web accounts (i.e. only if calibre-web also supports SSO can a administrator hosts a SSO identification provider to offer seamless login ability).

Perhaps it's not necessary to have SSO but the integration option, to inspire visitors to use Hypothesis (if it's a public instance).

**Comment by minh-p** [comment]
Hello! I managed to integrate it: https://github.com/janeczku/calibre-web/commit/1fdc7cabc06222ad03551c4df4c9528ff4c1d2b4
