### ISSUE TITLE
403 with anonymous browsing enable and Moon+

### ISSUE THREAD

**Issue by Alacard** [janeczku/calibre-web#919]
When trying to download a ebook (epub) im getting a 403 error message from moon+, when "Enable anonymous browsing" is enabled so moon+ can gets covers im not able to download a ebook i get a 403, but if i disable "Enable anonymous browsing" im able to download the ebooks just fine, it seem like for some reason if "Enable anonymous browsing" is enabled it trys to download the ebooks with anon and not with user/pass. im not sure if this would be on your side or moon+

**Comment by OzzieIsaacs** [comment]
I double checked it with the version 5.0.1. For me it's working, it shows cover files and downloading works with deactivated anonymous browsing. I can create 403 forbidden answers if I remove the "allow download" right for the user. Could you please double check the the user you are using has the appropriate rights?

**Comment by Alacard** [comment]
Yes I was using the admin account when i was doing my testing, would send you a log of the 403 error but for some reason changing the log level to debug, is not showing more log info. but all its showing is

`[2019-05-17 11:36:16,433] {/calibre-web/app/cps/web.py:188} INFO - Starting Calibre Web...
[2019-05-17 11:36:16,556] {/calibre-web/app/cps/server.py:84} INFO - Starting Gevent server`

in log. Forgot to say that i am using technosoft2000/calibre-web docker with Moon+ Android app. it maybe a bad install from something I did, ill back up config and do a reinstall and get back with you if im still getting the same problem
