### ISSUE TITLE
What is the purpose of cache_buster?

### ISSUE THREAD

**Issue by pwr** [janeczku/calibre-web#921]
From what I can tell, when sending static files, Flask correctly serves `Last-Modified` and `ETag` headers, with a decent default `Expires` of 12 hours. It also correctly replies with HTTP `304` if the request has `If-Modified-Since`/`If-None-Match` headers that apply.

The only use case that I can think of, is the expiration being too long after an application update; but this can be solved by doing a forced-refresh in the client, and/or mitigated server side by shortening the expiration time (or disabling the `Expires` header altogether).

If there something else I'm missing?

**Comment by OzzieIsaacs** [comment]
Without the cache-buster function there had always been problems with updating scripts during debugging and development. You never could be sure that the browser really updated the script, you had to doublecheck it, delete browser cache, I don‘t want to miss this function anymore
