### ISSUE TITLE
Unable to search for Metadata

### ISSUE THREAD

**Issue by Maddog0057** [janeczku/calibre-web#923]
I apologize if this has been posted before but I've been unable to find my exact issue. I am no longer able to search for metadata, when I hit "Get Metadata" I get the popup but no results no matter what I search for. I've attempted to restart both Calibre-Web, the server itself, and verified all my firewall rules.

>Calibre-Web 0.6.3 Beta
Image Magick	ImageMagick 6.7.8-9 2019-02-01 Q16 http://www.imagemagick.org
PyPdf	        v1.26.0
lxml	                v4.2.1.0
Wand	          0.5.3
Pillow	        v6.0.0
Babel	        v2.6.0
Sqlalchemy	v1.2.9
Werkzeug	v0.15.2
Jinja2	        v2.10.1
Flask	        v1.0.2
Flask Login	v0.4.1
Flask Principal	v0.4.0
Iso 639	        v0.4.5
pytz	                v2019.1
Requests	        v2.20.0
pySqlite	        v2.6.0
Sqlite	        v3.8.1
Calibre converter	ebook-convert (calibre 3.42.0)
Tornado	        v6.0.2
Python	        3.6.8 (default, May 2 2019, 20:40:44) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

**Comment by OzzieIsaacs** [comment]
I doublehecked it, for me it's working (Firefox, chromium, Safari on iOS). 
Which browser are you using?
Are there any relevant outputs in the developer's console on your browser (pressing str+shift+k in firefox) and afterwards pushing the get metadata button?
![grafik](https://user-images.githubusercontent.com/6438895/58621861-9701e800-82ca-11e9-966b-a826d531ee22.png)

**Comment by Maddog0057** [comment]
I am getting this error using both Chrome and Firefox
![image](https://user-images.githubusercontent.com/15681815/58830027-57fbcb80-8617-11e9-993b-caf90fa7921e.png)

**Comment by OzzieIsaacs** [comment]
I could not really reproduce your error, did some blind change (the code was indeed not correct). You should now get at least no errors anymore (but I guess you still don't get any results).
Please update to the newest nightly version.
