### ISSUE TITLE
Starting tornado server hang

### ISSUE THREAD

**Issue by syrac88** [janeczku/calibre-web#924]
Hello,

since yesterday the starting process hangs up while "Info in server: starting tornado server"
Waited for hours and tried a clean reinstall, but still the same problem.

Can anyone help me?

**Comment by OzzieIsaacs** [comment]
Could you give more details please? Which python version are you using, are you using docker, which one? How do you start Calibre-web? What do you expect to happen? What do you get if you access Calibre-web via your browser?

**Comment by syrac88** [comment]
Im using python v2.7.15 on windows 10
Im starting calibre web using powershell command "python cps.py".

I dont even get to the point where i might access the webserver. The log sais:

INFO in web: Starting Calibre Web...
INFO in server: Starting Tornado server

nothing more is happening.

**Comment by OzzieIsaacs** [comment]
That‘s right, after this message the Webserver should be available (http:127.0.0.1:8083), there is no more output

**Comment by syrac88** [comment]
Oh man :(

i was expecting someting on port 8087 and thought the webserver hangs up, im sorry.

Solved, thank you :)
