### ISSUE TITLE
[Reader] Request: Improve reader navigation for touchscreen devices.

### ISSUE THREAD

**Issue by ruifung** [janeczku/calibre-web#925]
It would be nice to have one or more of the following:

- Extend the next / back buttons to encompass the entire side its on.
- Swipe gestures.

These would enhance the reader experience on tablet devices like the surface go.

**Comment by OzzieIsaacs** [comment]
The next and back buttons are meanwhile bigger (they had been really small before indeed). For the swipe gestures I need to add jquery-mobile, shouldn't be that complicated, but I'm currently programming other topics, will take some time
