### ISSUE TITLE
[EBookreader] Kindle, can't tap covers

### ISSUE THREAD

**Issue by perler** [janeczku/calibre-web#926]
on kindle I cannot tap on book covers on the front page to to download. strangely, tapping on the author and tapping on the book cover on the author's page works..

**Comment by perler** [comment]
in the logs I see 

> "GET /cover/6116 HTTP/1.1" 304 220 0.006948

when tapping a cover on the front page.

**Comment by perler** [comment]
this is still an issue. is it that hard to fix?

**Comment by WROIATE** [comment]
I have the similar problem and my sidebar will display none. When i disabled the js it works, but if i do that, I can't click the download button.
![IMG_20200325_145205](https://user-images.githubusercontent.com/44677306/77511792-c8c4ea80-6eac-11ea-80d8-b66e427fc111.jpg)

**Comment by perler** [comment]
after upgrading to 0.6.9 - this is still an issue?!

**Comment by OzzieIsaacs** [comment]
I don't know. I have no kindle, and I did nothing intentionally to solve it, sorry.

**Comment by perler** [comment]
can I help in some way? 

it looks like a javascript problem as it goes away when disabling javascript. 

I think there is a chance that by solving this issue https://github.com/janeczku/calibre-web/issues/1020 we solve this problem as well, as I assume, that the mobile interface is a bit simpler and doesn't neccessary relies on javascript? is there a way to force the mobile interface to test the theory?

**Comment by gkovacsp** [comment]
On a Kindle PW with 5.12.2 OS version the modal book info view does not work (or hardly ever). The only way to download a book is the following:
- Open Calibre-web
- Disable javascript
- Navigate to the book
- Error: The download popup button does not work without javascript
- Enable javascript, the page reloads itself
- The popup starts to work and the book can be downloaded

**Comment by perler** [comment]
As another workaround you can tap the author and on this page suddenly
tapping on covers works again.

But a very ugly bug indeed. And an old one.

**Comment by OzzieIsaacs** [comment]
The problem occurs because the modal dialog which opened in this case needs some javascript. The javascript could not be executed by the kindle browser. Since some releases it's changed, so the kindle reader (and other readers) should open the book page in a new page
