### ISSUE TITLE
Request: calibre-web CLI interface

### ISSUE THREAD

**Issue by decentral1se** [janeczku/calibre-web#929]
Gven https://github.com/janeczku/calibre-web/pull/927 is coming and potentially, we will have a Python PyPi package, we can start to do `pip install calibre-web` and then have our installation ready.

It would be nice then to be able to `calibre-web serve|stop|etc.`.

If you're interested, I could write a small `argparse` based interface which supplies these basic commands.

**Comment by OzzieIsaacs** [comment]
I'm not sure if I understood how this would  work out:
You install Calibre-web via pip (clear).
You start the service by calibre-web start or whatever, which actually only starts the script.  (clear)

How is calibre-web started at the next computer start?
If you want to stop calibre-web, according to your proposal you would type: calibre-web stop. If you are having more than one instance running (the current suggestion for emulating virtual-libraries from calibre) how would the script know which instance to stop?

**Comment by decentral1se** [comment]
To be clear, this is just for the purpose of the following use case:

An end-user runs `pip install calibre-web` and then there is no `calibre-web` command to run! They do not know where Pip installed the package and it is not clear how to start the server. So, we should add a CLI entrypoint to solve this.

Your questions above are solved as end-users have done before, whether that is running two separate processes with `calibre-web start` or using systemd to automate service on boot. All that has changed in this regard is that they do not `git clone ... && python cps.py` anymore ...

Hope that is clear.

**Comment by decentral1se** [comment]
Looks like this is on the way in https://github.com/janeczku/calibre-web/commit/f5b335e8e9c9befb139a6a4e7e07762eb0b8894a#diff-380c6a8ebbbce17d55d50ef17d3cf906R36?

**Comment by OzzieIsaacs** [comment]
I played a little bit with it and I understood the need for a starter script. I will only create it for future versions from the development branch

**Comment by decentral1se** [comment]
OK, great, thanks a lot! Looking forward to it :)

**Comment by OzzieIsaacs** [comment]
The pypi package is finaly ready and the commandline entry point is named cps
