### ISSUE TITLE
Edit "Calibre Web"

### ISSUE THREAD

**Issue by DreamStatic** [janeczku/calibre-web#93]
Thank you for sharing this awesome Calibre web tool. I have used many others, but this one is shaping up to be the best. 

I utilize multiple libraries in Calibre. i.e. comics, ebooks, etc. So it would be super handy to be able to configure the site title ourselves to make it easy to distinguish across browser tabs. Or my **super wish** would be a dynamic menu (access controlled) that would allow you to jump from one library to the other. Without having to go to a different site. This would allow using only one port to access all of your Calibre libraries. 

In my mind the super wish idea would work something like this:

- Add DB_Root to Config.ini       i.e. /Volumes/HD/Calibre/ebooks/, /Volumes/HD/Calibre/comics/, etc.
- Admin panel would show all listed Libraries (from DB_Root comma separated entries) and allow you to edit their Page Titles and default access.
- User creation/edit panels would show all listed Libraries so you could control access.
- Dynamic Menu would build the libraries the user has access.

**Comment by tetrahydra** [comment]
I second this idea.

This is because, I separate my ebooks as well into different "library"

My calibre's libraries look like this
F:\eLibrary\Study [Computer]
F:\eLibrary\Study [Computer Programming]
F:\eLibrary\Magazine [Stamp]
F:\eLibrary\Magazine [Coin]

I would suggest, to allow multiple libraries, and auto-create shelf from the library's name, similar to the calibre's desktop format.

**Comment by OzzieIsaacs** [comment]
The latest commit fullfills the wish, not the superwish (Christmas is too far away for superwishes)
After configuration, you can change the title in the admin panel under configuration

**Comment by tetrahydra** [comment]
How can i add more library path?

http://192.168.1.20:8083/admin/view

I notice I can only have one path/folder at any one time.

**Comment by DreamStatic** [comment]
Thank you for the continued effort. This is a sweet front end and is only getting better and better.
