### ISSUE TITLE
calibre-web systemd integration documentation

### ISSUE THREAD

**Issue by decentral1se** [janeczku/calibre-web#930]
I've integrated calibre-web into a systemd service file and haven't seen any documentation around for that. I am wondering if I should add it to the wiki? I assume that would be useful :)

**Comment by OzzieIsaacs** [comment]
You mean something like this:
https://github.com/janeczku/calibre-web/wiki/Setup-Service-on-Linux
If you think it should be extended or better described, please feel free to do so.

**Comment by decentral1se** [comment]
Aha, apologies, I did not see. Cool!
