### ISSUE TITLE
Multiple libraries?

### ISSUE THREAD

**Issue by gerroon** [janeczku/calibre-web#931]
Hi

Is it possible to use multiple Calibre libraries with this?

**Comment by decentral1se** [comment]
Perhaps https://github.com/janeczku/calibre-web/wiki/FAQ#why-dont-you-support-calibres-virtual-libs is what you're looking for? Are the shelves feature not fitting your use case currently?

**Comment by gerroon** [comment]
Hi

I have many separate Calibre libraries (naturally with their own individual metadata.db), not sure how I can combine them in a shelf.

**Comment by OzzieIsaacs** [comment]
I extended the wiki (the headline already was there):
https://github.com/janeczku/calibre-web/wiki/FAQ#how-to-handle-multiple-calibre-libs
This should hopefully answer your question.

**Comment by gerroon** [comment]
Thanks, any recommendation for Docker use?

**Comment by OzzieIsaacs** [comment]
I'm sorry I have no clue about this docker stuff. 
The repros are maintained by other guys, please ask for help at the provider of the docker image.

**Comment by Shadowghost** [comment]
You just need to spawn different docker containers based on the same image. Each container will get it's own library by using environmental variables pointing to the correct library. Downside of this (and the mentioned approach above) is, that you'll have different calibre-web instances on different ports and not one webUI for all libraries.
But tbh I'm not sure if that's what the idea behind this request is. IMHO it would be nicer to be able to configure calibre-web to read multiple libraries and switch between them within the instance on the webinterface. But that has nothing to do with docker :)

**Comment by OzzieIsaacs** [comment]
I understand that it would be nice to have multiple libraries supported in calibre-web, but this would boost complexity of the project. 
All features which are outside calibre db like shelf-database, download-database and so on have to modified for this, so decided the first time when it came on the table not to implement it. It's a matter of time and more imported a matter of testing and supporting it after implementation.

**Comment by gerroon** [comment]
Thanks for the follow up guys, I will see how it goes with docker. I have like 20 libraries, so it is going to be a bit more complicated than anticipated I guess.

**Comment by ariznaf** [comment]
It would be great to be able to manage multiple calibre databases from the same

**Comment by Dirk71** [comment]
> I extended the wiki (the headline already was there):
> https://github.com/janeczku/calibre-web/wiki/FAQ#how-to-handle-multiple-calibre-libs
> This should hopefully answer your question.

I have installed Calibre-Web on Synology NAS using Docker. I do not know how to handle this tutorial. Is there somewhere an explanation for dummies?

**Comment by XargonWan** [comment]
> Sorry for asnwering in this close issue, but it would be great to be able to manage multiple calibre databases from the same calibre-web installation.
> 
> I have a private personal library and another library that share with other members of my family.
> 
> I have installed calibre-web in may qnap NAS. It works great. But having to have two separate docker installs is not an ideal solution. It consumes more memry and resources, and you have to remember two different ports (just enough to remember one) and get a more complex installation.
> 
> It would be great if you could configure more than one library path and just an initial interface that lets you select which library you wan to activate.
> 
> Calibre let you have more that one library database, but you work just on one database at a time. You have to switch selected database.
> 
> May be that approach is easier to implement in calibre-web too.
> 
> Anyway thanks for the effort and this great solution.

I second this.

**Comment by Dyredhead** [comment]
Yes just a simple toggle somewhere in the corner for which library you are currently viewing would work as a great solution! And then all that is needed is just to set permissions for what users can access what libraries and that should be most of what is needed for this functionality. 

I have two libraries, one for general books and one for comics, so being able to switch between the two without requiring a separate instance and url would be amazing!

**Comment by ChristopheRoyer21** [comment]
I second the need for this. I get the solution of setting many servers, one for each library, but if you have many users, it becomes a pain to setup their username for each of them. If we could manage them all in one server, but with Toggle to switch between libraries like the "official" Calibre Server, it would be awesome

**Comment by KumanduS** [comment]
yes, please add this, and also add the funcionality to share or not some library to a specific user.
