### ISSUE TITLE
[Docker] Allow "Reconnect to Calibre DB" REST call unauthenticated

### ISSUE THREAD

**Issue by yannouchou** [janeczku/calibre-web#933]
There are a few db sync issues that seem to be resolved by clicking "Reconnect to Calibre DB" (in my case, the updated books appear but not the covers after new books are added to Calibre - running Calibre-web in docker accessing the db over an NFS-mounted drive).

See #595 and #727 

While it would be nice to find out the root cause for this, in the meantime a simple workaround would be to simply automate the "Reconnect to DB" action after new books are added.

This could be easy to automate by sending a REST call to calibre-web. There is already an endpoint for this at `/shutdown?parameter=2` but it requires admin authentication, which means we need our automatic reload script to manage authentication and proper handling of the credentials.

Since making this call has a very limited impact on the applciation, I would suggest to open a separate anonymous endpoint for it (e.g. `/reconnect`).

I should be able to send a PR for this if you're ok with the idea.

**Comment by OzzieIsaacs** [comment]
The PR is merged and you can use it, as soon as the docker provider updated the calibre-web installation
