### ISSUE TITLE
Send to Kindle - issue?

### ISSUE THREAD

**Issue by bodybybuddha** [janeczku/calibre-web#94]
Hello - just downloaded and installed the repo today.  AMAZING!!

Having multiple issues - but that maybe b/c I haven't fully explored the site enough yet.  

However, I did setup a profile with a kindle email address, save the settings and sent email test.  Kindle sent back an email saying i didn't have a file attached (sorta expected.)  However, when sending a book via the email option, no book ever arrives on my Kindle.

I've verified allowed email addresses, I've sent a mobi file via an email client with no issue, etc.  

Notice that there was a change to the repo about 8 hours ago as of this writing, would that have caused the issue?

Thanks!

**Comment by OzzieIsaacs** [comment]
The change was related to encryption on login to send emails. I take a look.

**Comment by simkin** [comment]
Working correctly on:

> Program library	Installed Version
> Python	2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
> Kindlegen	Amazon kindlegen(Linux) V2.9 build 1028-0897292
> ImageMagick	ImageMagick 6.8.9-9 Q16 x86_64 2016-11-26 http://www.imagemagick.org
> PyPDF2	1.26.0

**Comment by bodybybuddha** [comment]
I'm slightly off on the versions:

Python	2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
Kindlegen	Amazon kindlegen(Linux) V2.9 build 1028-0897292
ImageMagick	ImageMagick 6.7.7-10 2016-11-29 Q16 http://www.imagemagick.org
PyPDF2	1.26.0

I'll update a little later today and see if it makes a difference!

Thanks!

**Comment by bodybybuddha** [comment]
I've set the Development flag and restarted.  I haven't upgraded any of the libraries yet (working on that next.)  

In any event attached is the entries from the log file (removed any private information and auth code, etc.) and i'm still experiencing the same issue.

[calibre-web-log.txt](https://github.com/janeczku/calibre-web/files/717900/calibre-web-log.txt)
 
The website gives me the green bar and states success - but the above is the entire log file.

I'll report back  after I get the latest and greatest software.

**Comment by bodybybuddha** [comment]
Almost there:

Python	2.7.12 (default, Jul 18 2016, 15:02:52) [GCC 4.8.4]
Kindlegen	Amazon kindlegen(Linux) V2.9 build 1028-0897292
ImageMagick	ImageMagick 6.7.7-10 2016-11-29 Q16 http://www.imagemagick.org
PyPDF2	1.26.0

Having issues upgrading ImageMagick.  I'll look at after dinner.

I did test with just the above upgraded and I still have the same issue.  Also, I'm selecting a book I know had a mobi version - so I'm not sure if ImageMagick would actually kick off.

**Comment by idalin** [comment]
I have the same problem.
If I use Send to Kindle to send a book  to my kindle email: nothing happend, no errors, no book sync to kindle.
If send to my own email: I can receive that mail, I can open book attached to that mail.
If I forward that mail to the kindle email, kindle can sync that book!
I am confused.
Nothing help from the debug log.

**Comment by bodybybuddha** [comment]
idalin - i just finishing that test too!  I sent the book to a standard email account and got the book.  Resent to kindle and got it there. I've verified the sender account as a valid account, etc.

Very strange considering that we're sending the email to the same "outbound" smtp server regardless where it's eventually heading.  The format of the email seems to be fine.

The log file seems only go back 1 file version - Not sure if it's b/c I have the more verbose setting or what, but the MIME portion of the smtp message forces the log to cycle so that all is contained in the log.1 file is the MIME information and the log file the lines that close the SMTP connection.  No log exist prior to the MIME information.  Is there a way of keeping more log data?

**Comment by bodybybuddha** [comment]
This may not be calibre-web issue.  According to a number of threads on the mobileread site, people are having the same issue with no rhyme or reason.  Some suspect Amazon is filtering off something in the email or metadata of the book. 

I've personally have tried a number of things - including editing the helper.py file to change the subject and body of the email.  Whenever I send a book to a personal email, it works.  If I take the same email and forward it to my kindle, the kindle sees it.  Nothing I've tried has gotten the calibre-web to send "directly" to the kindle.   -- oh I even setup a forwarding address on my domain for my kindle and sent from calibre-web to that address and had the same issue as before. 

I've tried a number of different books from my collection and public domain.  Some how Amazon may be blocking this feature for my account. (or am I paranoid??)

I'll do a little more research on this; however everything seems to be pointing an Amazon filter policy and not calibre-web.

**Comment by idalin** [comment]
I've tried many kind of 'send to kindle' python script. All failed.
I'll use msmtp+mutt to fixed this problem temporary.

**Comment by bodybybuddha** [comment]
@idalin - that's very interesting.  As a test I re-enabled my COPS instance (PHP OPDS server for calibre) and I was able to send to my kindle from there.

I also setup my wife's Kindle this morning to accept email from my account, created her a user acct on calibre-web and sent her Kindle a book.  Exactly the same result as I got with my Kindle.  

Did you change the helper.py function to use msmtp+mutt?

**Comment by OzzieIsaacs** [comment]
I don't think it depending on the library or program you use to sdend the email, it depends on the header fields and body format of the emails.

**Comment by bodybybuddha** [comment]
@OzzieIsaacs - you may be right.  

I looked at the raw source for messages sent via calibre-web and my COPS installation.  The headers all look "normal".  The only difference I could tell was that calibre-web encodes the entire message, including the text portion with base64.  COPS has the HTML portion and text portions all in 8bit.

Unfortunately, it's not a fair test as my COPS installation is using gmail as a relay, whereas calibre-web is using my hosting provider.  Let me see if it makes a difference if I change calibre-web to use gmail.  If it doesn't, maybe I should set up both to use my hosting provider so that the headers should be as close as possible. (gmail adds a lot..)

**Comment by bodybybuddha** [comment]
wow... everything worked once I switched over to using a gmail account.  The account has the "less secure" option already set, etc.  

I don't think it's really all that beneficial to troubleshoot this issue any more - as I think there really isn't anything wrong with the way calibre-web is working.  Any troubleshooting will basically boil down to figuring out how to convince Amazon's system to send a book.  If a gmail account works, great!  

As a matter of fact a number of threads on the mobileread site are recommending gmail accounts to be used.

I guess with that - I'll close out the bug.  

Thanks to @OzzieIsaacs and @idalin!

**Comment by idalin** [comment]
I captured packets both sending mail with mutt and smtplib/email. Tried to find the differences between them. There are some differences about headers.
And I found when I added headers 'Message-Id' and 'Date', it work!  So I fixed them and made a pull request

**Comment by bodybybuddha** [comment]
NICE!!  you rock!

**Comment by snakefeet** [comment]
Please could someone help me in setting up the email. I keep getting "SMTP AUTH extension not supported by server." 

Can someone please tell me where I'm going wrong or what I need to do. I have set up the SMTP settings for Gmail but I don't seem to be getting anywhere.

Many thanks Kate I'm advance
