### ISSUE TITLE
[Enhancement] Add option to discard on the fly Kindle conversions after sent

### ISSUE THREAD

**Issue by Phastor** [janeczku/calibre-web#940]
Add the option for the server to remove the resulting mobi file after it has been sent to a user. This would be useful for large libraries where an owner wants to have that functionality for their users, but don't want to have redundant copies stored.

**Comment by OzzieIsaacs** [comment]
Meanwhile a conversion to mobi isn't needed anymore, as amazon accepts epubs. It's possible to delete single formats in the edit a book screen
