### ISSUE TITLE
create History in calibre web

### ISSUE THREAD

**Issue by arkandzaki** [janeczku/calibre-web#944]
how to create a menu that records the activities of each user? for example X users have uploaded, changed metadata, downloaded or read ebooks. the user's activities are recorded and can be exported in the form of csv, xlsx or xls.

How do you make statistics on adding ebook collections that have been uploaded in a certain time period (years, months)?

Thank You

**Comment by OzzieIsaacs** [comment]
We are having the tasks view to see the last 20 actions. I decided not to implement a history function and export function.
Sorry
