### ISSUE TITLE
caliBlur! Register link not visible

### ISSUE THREAD

**Issue by xfouloux** [janeczku/calibre-web#946]
Hey,

thanks for this amazing theme ! But when you setup open registration, then the register link is not visible at all.

Is there any way to fix this please ?

Thanks !

**Comment by xfouloux** [comment]
caliblur theme redirect you to the login page directly when not logged in and public guest is not allowed, and on login page there is no register link.

Can the redirect be removed ?

also, If I allow public guest and register The navbar give this, and cliking on login icon is difficult.

![image](https://user-images.githubusercontent.com/9778409/59818863-54837680-9371-11e9-8298-b1798fb58cbd.png)

Thanks for the amazing theme ! Still need some fix

Plex oauth could be awesome too !

**Comment by OzzieIsaacs** [comment]
So problem 1:
In config disabled "anonymous browsing" and enabled registering -> Button to go to register page is not shown on login page
In config enabled "anonymous browsing" and enabled registering -> Button to go to register page not in overlap with Guest icon button
@leram84 and @hexeth could you please take a look at it?
