### ISSUE TITLE
Comic Reader not working in Google Chrome

### ISSUE THREAD

**Issue by myluki2000** [janeczku/calibre-web#948]
Hello,

I noticed that the comic .cbz reader is not working in Google Chrome (Version 75.0.3770.100, Windows). It just doesn't show the pages of the book:
![image](https://user-images.githubusercontent.com/3610788/59964499-e91cde80-9501-11e9-9395-ea5ed18ae5c5.png)

This happens in both the master and develop branch versions.

In Firefox and Edge it works just fine. Sadly I can't tell you since which version this is happening because I have been using a (very) old version of calibre-web up until now.

**Comment by myluki2000** [comment]
The chrome dev console puts out the followiing errors:
![image](https://user-images.githubusercontent.com/3610788/59966244-a6670080-9519-11e9-95b6-6d9b93c1d7f4.png)

**Comment by OzzieIsaacs** [comment]
Looks like duplicate of this one: https://github.com/janeczku/calibre-web/issues/896#issuecomment-488831045.
Could you please follow the instructions on the link above, and try again.

**Comment by myluki2000** [comment]
That worked, thank you very much! I'm just surprised that it would randomly change the registry key, because it worked before.
