### ISSUE TITLE
"guest" user can be created but it's a reserved username

### ISSUE THREAD

**Issue by paulhybryant** [janeczku/calibre-web#949]
I added a new user (guest), but using the username and password I set I was not able to login to the system.

**Comment by OzzieIsaacs** [comment]
The user guest is already present (it's the user which is used for anonymous browsing), you have to choose another name. I'll fix it, so it won't be possible to create a new user with that name

**Comment by OzzieIsaacs** [comment]
Should work now with the newest commit (existing, but maybe not visible guest account is denied as new user name)
