### ISSUE TITLE
Proposal: Allow configuration of optional columns / data fields

### ISSUE THREAD

**Issue by Flo-63** [janeczku/calibre-web#95]
It would be great if it was possible to configure additional data fields to be shown, i.e. "Publishing Date", "Language" etc. It might be globally configurable in ini-file or in a new admin tab.

**Comment by OzzieIsaacs** [comment]
Where do you want to see it? You can see these columns on the book detail page today

**Comment by Flo-63** [comment]
I'd like to see "Publishing Date" on the detail page - yes, I can see the language field (didn't recognize it for whatever reason before...).
