### ISSUE TITLE
Wrong images order in CBZ

### ISSUE THREAD

**Issue by floviolleau** [janeczku/calibre-web#950]
Hi,

Thanks for this gorgeous solution of having a calibre database view and be able to read in a browser.

I don't know if anybody is facing to the same solution but when the cbz/cbr contains files named like this:
0.png
1.png
2.png
...
9.png
10.png
11.png
...
19.png
20.png
21.png
...

- in a mobile application (like FBReader), comics are read in the correct order (0.png, 1.png, 2.png, 3.png, ..., 9.png, 10.png, 11.png, ..., 19.png, 20.png, 21.png...)
- in calibre web, comics are read in the **wrong** order (0.png, 1.png, 10.png, 11.png, 12.png, 13.png, ..., 19.png, 2.png, 20.png, 21.png, ..., 29.png, 3.png, 30.png, 31.png, ...

Any ideas on how to solve that?
Thanks

**Comment by OzzieIsaacs** [comment]
Yes it's indeed a bug which no one ever reported in 2 years.
Workaround would be renaming the files from 1 to 9->  -01 to -09 and renaming filesstarting from 10 with -10 and so on.
I'll try to find a real solution

**Comment by OzzieIsaacs** [comment]
I introduced a "natural sorting algorithm" should work now with the newest commit

**Comment by floviolleau** [comment]
Hi,

There is a regression, the bug is back.

**Comment by OzzieIsaacs** [comment]
I broke it indeed, should be okay again now.

**Comment by floviolleau** [comment]
Super!

Thanks a lot for your reactivity!

Everything is fixed
