### ISSUE TITLE
Cannot install calibre-web latest master with Python < 3.6

### ISSUE THREAD

**Issue by decentral1se** [janeczku/calibre-web#951]
Hmmm, I didn't get this issue before but now seeing it. What to do? We should still support Python 3.5, I assume? Is it possible to reduce this bound on the comicapi, I wonder ...

> https://github.com/wildthyme/comicapi/blob/master/setup.py#L12

```
...
    100% |████████████████████████████████| 122kB 269kB/s 
Collecting unidecode>=0.04.19 (from -r requirements.txt (line 15))
  Downloading https://files.pythonhosted.org/packages/d0/42/d9edfed04228bacea2d824904cae367ee9efd05e6cce7ceaaedd0b0ad964/Unidecode-1.1.1-py2.py3-none-any.whl (238kB)
    100% |████████████████████████████████| 245kB 11kB/s 
Collecting comicapi from git+https://github.com/wildthyme/comicapi.git@cb279168f9c5cec742b5a05ac8326b9c168a8a91#egg=comicapi (from -r requirements.txt (line 16))
  Cloning https://github.com/wildthyme/comicapi.git (to cb279168f9c5cec742b5a05ac8326b9c168a8a91) to /tmp/pip-build-pzc8ceba/comicapi
  Could not find a tag or branch 'cb279168f9c5cec742b5a05ac8326b9c168a8a91', assuming commit.
comicapi requires Python '>=3.6.0' but the running Python is 3.5.3
```

**Comment by decentral1se** [comment]
Opened up https://github.com/wildthyme/comicapi/issues/1. I'll submit a PR too.

**Comment by decentral1se** [comment]
As a temporary workaround, I've done this:

> https://github.com/decentral1se/calibre-web/commit/9d04f0d177eb6135a015673e0d9b948becf8ca1b

I can now install the package correctly.

**Comment by OzzieIsaacs** [comment]
I changed the repro where the dependency is downloaded from, and moved it to the optional requirements
