### ISSUE TITLE
Optional Requirements cannot install, missing remote branch comicapi

### ISSUE THREAD

**Issue by thelamer** [janeczku/calibre-web#962]
The packaging fix branch is no longer present on this fork: 

https://github.com/decentral1se/comicapi

I am not entirely sure but maybe just master here? 

https://github.com/janeczku/calibre-web/blob/master/optional-requirements.txt#L23

Please let me know if you need anymore information, this is preventing us from building downstream.

**Comment by OzzieIsaacs** [comment]
I forked the dependency by myself, changed the code in the fork, and updated the optional requirement file. It should work now

**Comment by thelamer** [comment]
You linked to the archive, pip needs a git repo.

This should work: 

```
git+https://github.com/OzzieIsaacs/comicapi.git@5346716578b2843f54d522f44d01bc8d25001d24#egg=comicapi
```

**Comment by OzzieIsaacs** [comment]
Sorry I didn't check it. Your proposal is included now.

**Comment by thelamer** [comment]
LGTM https://lsio-ci.ams3.digitaloceanspaces.com/linuxserver/calibre-web/V0.6.4-ls24/index.html :+1:
