### ISSUE TITLE
Question: Comics collection management

### ISSUE THREAD

**Issue by MijacOnAir** [janeczku/calibre-web#963]
Hi everyone, I have seen Tailchakra's [post](https://github.com/janeczku/calibre-web/issues/457) about comics but I am not quite sure how this works or what stage this is at the moment.

1. Can I manage comics in the same Calibre library as the rest of my book with a tag segmenting all of them from the rest of ebooks or should I get create a different library for Calibre on Windows?
2. Also, does comicapi has something to do with this functionality?

Thanks beforehand.

**Comment by MijacOnAir** [comment]
When installing the optional-requirements txt this keeps coming up for comicapi. Can anyone explain what is the issue here? 

Running command git clone -q https://github.com/OzzieIsaacs/comicapi.git 'C:\Users\myUser\AppData\Local\Temp\pip-install-bx_skd3v\comicapi'
  ERROR: Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/OzzieIsaacs/comicapi.git 'C:\Users\myUser\AppData\Local\Temp\pip-install-bx_skd3v\comicapi'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

**Comment by OzzieIsaacs** [comment]
Regarding the install problem: You need to install git (https://git-scm.com/downloads should work) and it should be in your path (means, independend of the folder you are currently in, all call to "Git" works). I'm almost sure the install program will take care of this.

**Comment by OzzieIsaacs** [comment]
Regarding the other questions:

1.) Yes it's no problem to have all books, comics in one library
2.) The comicapi is for extracting metadata (author name and so on) out of comic files (cbz, cbt) during upload
