### ISSUE TITLE
calibre-web "forgets" Path to Library

### ISSUE THREAD

**Issue by destynate** [janeczku/calibre-web#964]
Hey there :)

My Library is located on a NAS Storage and sometimes (after network reboot / nas reboot / i don't know) Calibre-Web seems to forget the path to my ebook Lib and shows Configuration Dialog on opening. Is there a way to "hardcode" the library destination to a config-file or within the cps.system service?

thanks in advance and cheers (:

**Comment by OzzieIsaacs** [comment]
If calibre-web presents the config page with empty path, the metadata is not accessable at this moment.
There is no posibility to hardcode the lib path. If we would do this, problems will arise. A hardcoded non accessible lib will lead to crashing the program, or extensive errorhandling for this case.

**Comment by zanhecht** [comment]
> If calibre-web presents the config page with empty path, the metadata is not accessable at this moment.
> There is no posibility to hardcode the lib path. If we would do this, problems will arise. A hardcoded non accessible lib will lead to crashing the program, or extensive errorhandling for this case.

Is there a way to store the metadata.db in a different location from the rest of the library (e.g. storing it on my server's internal memory while keeping the book files on a NAS)?

**Comment by zanhecht** [comment]
> If calibre-web presents the config page with empty path, the metadata is not accessable at this moment.
> There is no posibility to hardcode the lib path. If we would do this, problems will arise. A hardcoded non accessible lib will lead to crashing the program, or extensive errorhandling for this case.

@OzzieIsaacs Is there a way to store the metadata.db in a different location from the rest of the library (e.g. storing it on my server's internal memory while keeping the book files on a NAS)?
