### ISSUE TITLE
The upload button doesn't appear

### ISSUE THREAD

**Issue by erauzkin** [janeczku/calibre-web#965]
I have installed the docker several times, but I never get the upload button, and I have the necessary permissions.

[https://imgur.com/nit2KZl](url)

If I enter serverip:8083/upload I get error 404

**Comment by OzzieIsaacs** [comment]
Which docker do you Use?

**Comment by erauzkin** [comment]
https://hub.docker.com/r/technosoft2000/calibre-web/

**Comment by erauzkin** [comment]
Solved

**Comment by Patrice44** [comment]
Installation on a Synology NAS. same docker image: https://hub.docker.com/r/technosoft2000/calibre-web/
Working perfectly. But I got the same issue: The upload button doesn't appear.  serverip:8083/upload I get error 404 
Any info how erauzkin fixed this issue .
Regards,
Patrice

**Comment by erauzkin** [comment]
Basic Configuration ->  Feature Configuration -> Enable uploading
