### ISSUE TITLE
Additional Logging Request

### ISSUE THREAD

**Issue by bodybybuddha** [janeczku/calibre-web#97]
Hi!  For those of us that are not using a reverse proxy, is there a way to get more logging?  I'm looking specifically for user login attempts.  

Also, it appears that the log files only go back one version (.1)  -- can we increase this number or have it customizable per installation?

Sorry this may have been to enhancement requests and not one.

**Comment by OzzieIsaacs** [comment]
Please check the newest commit, every failed login attempt now creates a "Info" log entry (log level has to be set accordingly to see it). The number of log backups is increased to 2 now

**Comment by bodybybuddha** [comment]
@OzzieIsaacs Thanks for looking into this so quickly!

Unfortunately I had a problem installing the latest version with my existing app.db.  I renamed the app.db and a new one was created (smaller in size) after I started the application via the command line.  Although the site was running - i couldn't get a browser to access the site.

I've reverted back to a version you had submitted 13 days ago (fd9740f) and I removed the newly created app.db for my backup and everything came back up.  

I ran out of time to play with it just now, I'll look into it a bit later today.  If you see this message in the meantime - I had a couple of questions.  Are the usernames/passwords stored in the app.db (I had assumed so)?  When performing these upgrades - I'm simply copying the files over the existing installation (mindful of the config, and keeping a copy of kindlegen backed up of course) -- Is this the proper way of upgrading?

Thanks!

**Comment by OzzieIsaacs** [comment]
Usernames and passwords are stored in app.db, yes. Coping the file over the old ones is the way of doing update now. If you are on Linux, please check owner and file permissions on the new files, maybe this is a problem. Another issue could be, I moved all basic settings like port, calibre directory also in the app.db. What I didn't do is migrating the setup from the config file. So the port settings is reseted to 8083, could this cause the issue?

**Comment by bodybybuddha** [comment]
I didn't even think about trying the default port!! doh!  I do use a different port than the default.

I'll try to recreate and let you know later today.

**Comment by bodybybuddha** [comment]
@OzzieIsaacs confirmed - it was the set to the default port.  Moving forward with the latest version.  I can confirm I see failed logged in attempts.  Thanks again for looking into this!

Before I start re-adding the users manually, anyway advice on a quick way of doing that from a back up database?

**Comment by OzzieIsaacs** [comment]
Just stop caliber-web, replace the app.db with you backup. Start caliber-web again. Enter port and database location again, and everything else should be as before...

**Comment by bodybybuddha** [comment]
No Joy.   Ran the cps.py from the command line to get the below trace message.

I'll just revert back to the new app.db and manually retype the users -- unless you need/want to troubleshoot this issue?  If not, I can go ahead and close out the issue.

Traceback (most recent call last):
  File "./cps.py", line 12, in <module>
    from cps import web
  File "/opt/cps/cps/web.py", line 10, in <module>
    import ub
  File "/opt/cps/cps/ub.py", line 438, in <module>
    config = Config()
  File "/opt/cps/cps/ub.py", line 268, in __init__
    self.loadSettings()
  File "/opt/cps/cps/ub.py", line 271, in loadSettings
    data = session.query(Settings).first()
  File "/opt/cps/vendor/sqlalchemy/orm/query.py", line 2282, in first
    ret = list(self[0:1])
  File "/opt/cps/vendor/sqlalchemy/orm/query.py", line 2149, in __getitem__
    return list(res)
  File "/opt/cps/vendor/sqlalchemy/orm/query.py", line 2353, in __iter__
    return self._execute_and_instances(context)
  File "/opt/cps/vendor/sqlalchemy/orm/query.py", line 2368, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/opt/cps/vendor/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/opt/cps/vendor/sqlalchemy/engine/base.py", line 761, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/opt/cps/vendor/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/opt/cps/vendor/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "/opt/cps/vendor/sqlalchemy/util/compat.py", line 196, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/opt/cps/vendor/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/opt/cps/vendor/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (OperationalError) no such column: settings.config_log_level u'SELECT settings.id AS settings_id, settings.mail_server AS settings_mail_server, settings.mail_port AS settings_mail_port, settings.mail_use_ssl AS settings_mail_use_ssl, settings.mail_login AS settings_mail_login, settings.mail_password AS settings_mail_password, settings.mail_from AS settings_mail_from, settings.config_calibre_dir AS settings_config_calibre_dir, settings.config_port AS settings_config_port, settings.config_calibre_web_title AS settings_config_calibre_web_title, settings.config_books_per_page AS settings_config_books_per_page, settings.config_random_books AS settings_config_random_books, settings.config_title_regex AS settings_config_title_regex, settings.config_log_level AS settings_config_log_level, settings.config_uploading AS settings_config_uploading, settings.config_anonbrowse AS settings_config_anonbrowse, settings.config_public_reg AS settings_config_public_reg \nFROM settings\n LIMIT ? OFFSET ?' (1, 0)

**Comment by OzzieIsaacs** [comment]
Fixed it. But your DB is now broken, you can only try to migrate if you have a backup of an untouched database, sorry

**Comment by bodybybuddha** [comment]
No worries! - Thanks again for looking into this.  

Anything else you want me to break?? :-)

I'll go ahead and close this out.
