### ISSUE TITLE
Mature content exposed

### ISSUE THREAD

**Issue by privatechapter** [janeczku/calibre-web#975]
Hi, first big thanks for the project, very exiting to see a python web app replacing that ugly caliber ui...

So the issue if that even without the 'mature content' privilege it's trivial to access mature content present in the library.

Steps to reproduce:

1. Login as a user that doesn't have access to mature content if you don't have guest access enable
2. Go to advanced search
3. filter by your mature content tag, for example 'adult'
4. Hit submit 

At this point you are able to see the cover, title, author of all restricted content. If you try to open it though you won't be able which is a good thing. However there is a trivial way to open the content of those books. as describe bellow:

1. Hover the book cover to check the book ID in the link. For example `mycalibre-web/book/69`
2. Given the ID above navigate to `mycalibre-web/read/69/pdf` here is takes a bit of guesswork to find out the extension but there is not that many format out there, so it's pretty easy...

I'm a developper myself so I can try to help solve this, but any pointer would be appreciated.
Thanks again.

**Comment by OzzieIsaacs** [comment]
Found several lines where the mature filter is missing, your scenario (and some more) and now handled.

**Comment by privatechapter** [comment]
Wow that was quick, nice one 👏 I'm still trying to figure out how to build this lol

**Comment by OzzieIsaacs** [comment]
> how to build this ...

You mean using the setup.py? There are some secrets (you should run make_release script in the https://github.com/OzzieIsaacs/calibre-web-test repro)

**Comment by privatechapter** [comment]
Ok I'll give that a try, at the moment I'm using a docker image that pulls you release tar.gz.
So I'll check if I get that to run a local copy of the code. Even if you fixed that specific issue I have another feature in mind and I can't ask you to work too hard :)

**Comment by OzzieIsaacs** [comment]
Okay, than there is no need for the setup.py. 
Just copy the code to some folder, install the dependencys "globally" or like mentioned in the readme and start the cps.py file. 
Easy start for debugging (you can set the FLASK_DEBUG environment variable, than all log output goes to stderr)

**Comment by privatechapter** [comment]
Thanks for the pointers, much appreciated. Looking into the container I can see that all the files have their equivalent as `pyc` so I suppose that's what gets executed. Is the `cps.py` generating those ?

**Comment by OzzieIsaacs** [comment]
The pyc Files are generated by the python interpreter itself, without and code from the program itself. The Update of those files works Abwassers in the background

**Comment by privatechapter** [comment]
Right so in theory I could just edit the py files and restart the app and that should work.

**Comment by OzzieIsaacs** [comment]
Yes. But maybe you have to restart the container or similar, I don't have so much knowledge about docker container. In my opinion it's easier to debug without container, but it's up to you.

**Comment by privatechapter** [comment]
Yes I will have to restart the container as killing the main process will stop the container. I also going to need to mount the app folder as a volume so I can edit it with something else than vim. But that's going to be the easy part for me as I have more experience with docker than python app. The main benefit is to be able to keep my host as clean as possible. But that's technicalities, the main bit is I can change code, see the result and have some ruff debugging and the rest should be fine 👍

**Comment by OzzieIsaacs** [comment]
As the initial problem is solved, I'll close the issue.
