### ISSUE TITLE
First image not extracted from CBZ to be used as cover

### ISSUE THREAD

**Issue by floviolleau** [janeczku/calibre-web#985]
Hi,

Just posting an issue in case people are facing to the same issue like me.

I'm using 5f228fb checkout.
When I'm uploading a new CBZ to calibre-web by using the UI, the cover is not extracted like before.
Usually, it shoulds take the first image of the CBZ as a cover.

In the CBZ, images are ordered from 0.png, 1.png, 2.png, ....

Maybe the issue is the use of pngs?
I don't have any errors in logs.

Thanks for this amazing active project!

**Comment by OzzieIsaacs** [comment]
The first jpg file is extracted, if the book only includes non jpeg files than nothing is extracted. But I think it was always, like this.

**Comment by floviolleau** [comment]
Mmmh I understand but it's a shame because on UI we can upload .png files.

Can you tell me why we have this kind of restriction?

**Comment by OzzieIsaacs** [comment]
Yes, we don‘t have it, because I forgot to program it. I let the issue open as reminder that I habe to include it. It shouldn‘t be so difficult

**Comment by floviolleau** [comment]
Thanks! ♥️
