### ISSUE TITLE
[Raspi] Proxy Error 502 with apache proxy uploading many books

### ISSUE THREAD

**Issue by OzzieIsaacs** [janeczku/calibre-web#989]
Hi,

I installed calibre at the commit 5f228fb and I still have issues when I multiple upload.

I don't have any errors in logs but on UI, I have a 502 proxy error:
![image](https://user-images.githubusercontent.com/5442973/62080713-7fef6000-b251-11e9-81b9-123673037154.png)

Do you have an idea?

Thanks for your help here.

_Originally posted by @floviolleau in https://github.com/janeczku/calibre-web/issues/890#issuecomment-516152745_

**Comment by OzzieIsaacs** [comment]
This is a different error message than before, did you had the intial problem before? Otherwise I would create a new issue for this one.
Are the books added afterwards?
Do you use docker? reverse proxy? which one?

Info from @floviolleau:

I think I had this issue before that commit but I cannot be 100% sure.

Books are correctly added afterwards. I can see it in tasks page and if I do a md5sum check, all is OK.
I don't use Docker (I'm on a Rpi 3). I configured an Apache to do a reverse proxy to the calibre's port.

**Comment by OzzieIsaacs** [comment]
This is a diffrent problem from the original one. 
It's plausible that a "slow" raspi has communication problems with apache proxy (maybe timeout error). I'll try to reproduce it.
@floviolleau One additional question: Could you please check apache log if the 502 error is recorded there (in access-log or error-log?) and if there is more information

**Comment by floviolleau** [comment]
Hi,

Thanks for creating this new issue. I will try to catch the 502 proxy error in apache logs and I will get back to you.

**Comment by floviolleau** [comment]
The only output I have is this one that is repeating itself.

Nothing in JS console, neither in network tab of dev tools in Firefox.

```
[Tue Jul 30 16:31:58.345320 2019] [proxy_http:error] [pid 18659] (70007)The timeout specified has expired: [client <redacted>:<redacted>] AH01102: error reading status line from remote server localhost:8080, referer: https://<redacted>/tasks
[Tue Jul 30 16:31:59.343433 2019] [proxy:error] [pid 18659] [client <redacted>:<redacted>] AH00898: Error reading from remote server returned by /ajax/emailstat, referer: https://<redacted>/tasks
```

**Comment by OzzieIsaacs** [comment]
The error is caused by upload file size to big, so try to split your uploads into smaller portions. 
I agree that the error message isn't vary helpful, I try to change it.

**Comment by OzzieIsaacs** [comment]
It's changed
