### ISSUE TITLE
Not able to execute cps.py

### ISSUE THREAD

**Issue by bibhuashish** [janeczku/calibre-web#990]
Hi,

When I am executing the cps.py file, getting the below error.
**simpleldap: No module named 'flask_simpleldap'
Can't read file cps/translations/iso639.pickle: the STRING opcode argument must be quoted**

I have tried to install simpleldap but not able to install simpleldap. I have a windows10 laptop.
I have tried every possible thing like getting the latest VS build etc etc. but have not been able to proceed. Can someone please help me with how to proceed on this?
Else is there any other alternate to simpleldap which I can include in the simpleldap.py to proceed

Thanks

**Comment by OzzieIsaacs** [comment]
The first one should not be your problem, the second one "Can't read file cps/translations/iso639.pickle: the STRING opcode argument must be quoted" is your issue.
Luckily you are not the first one with this problem:
https://github.com/janeczku/calibre-web/wiki/FAQ#error-on-startup-the-string-opcode-argument-must-be-quoted

**Comment by OzzieIsaacs** [comment]
Looks like you solved it
