### ISSUE TITLE
issue with metadata

### ISSUE THREAD

**Issue by bibhuashish** [janeczku/calibre-web#995]
Not able to get the metatdata.db file. Where it is? and also would like to know the ways to create in case it has to be created.

Thanks!!

**Comment by OzzieIsaacs** [comment]
You need an ... "existing Calibre database." Please download, install and start Calibre (https://calibre-ebook.com/download). On the first startup you should be asked where to store your database. In this folder the inital calibre-database is located. (You can move the metadat.db and the folderstructure under it to a random location and use it there with calibre-web)
