### ISSUE TITLE
Theme not displaying on 0.6.5 beta

### ISSUE THREAD

**Issue by YesThatRancourt** [janeczku/calibre-web#999]
Since the 6/31 update on master, neither theme seems to be displaying (both appearing as the screenshot below illustrates), and the book covers are showing up at original file resolution (not resized for display). I've tested this with both Chrome, Firefox and Edge on Windows (in standard and incognito mode, to rule out plugins) as well as Chrome and Samsung's default browser on my phone, and have wiped and reinstalled calibre-web from both master and develop branches, into clean directories. The problem manifests both with a newly-generated app.db and my preexisting one, and manifests whether I access calibre-web directly from its default port or through the proxy on Apache which I usually use. 

Thank you for maintaining this project, and many apologies for being the bearer of news of a possible bug.

![cps_problem](https://user-images.githubusercontent.com/15682575/62429679-9aa55700-b6df-11e9-950e-64e41a7e06a9.jpg)

**Comment by OzzieIsaacs** [comment]
It's working for me, so not a general problem (maybe).
If the problem occurs on every browser, it looks like some problem on the server side.
Could you please check what the output of the developer console is: (on firefox extras -> developer -> web-consle, or similar): Are there any 404 errors?
![grafik](https://user-images.githubusercontent.com/6438895/62439545-8c415480-b74c-11e9-85c6-99e2c59df9d2.png)
Another possibility would be the tornado or gevent server component of calibre-web. Could you please post the content of the about section (dynamic library section). Is your server running on Linux/Windows on a PC or some sort of NAS (which one). From your description I assume your are not using docker, is this right?
Even if it is unlikely from your description, could you please check if in the calibre-web folder the path cps/static/css is existing and is accessible by the user running calibre-web?

**Comment by YesThatRancourt** [comment]
Thank you for your patience. I'm running calibre-web on Ubuntu 18.04 LTS, and not using docker. The web console appears to be reporting problems with uploadprogress; I've attached screen captures of both the console results and my About page. I've verified that cps/static/css and cps/static/js are both present and readable.

I'm sure this is something obvious I'm missing, and I thank you very much for your patience with me on this process.

![cps_problem2](https://user-images.githubusercontent.com/15682575/62440356-bd566080-b71d-11e9-9fb3-28215c65e081.jpg)
![cps_problem3](https://user-images.githubusercontent.com/15682575/62440357-bd566080-b71d-11e9-9fa1-42a32834793c.jpg)

**Comment by OzzieIsaacs** [comment]
your problem is „...was loaded even though its mime type is not a valid javascript mime type“

**Comment by OzzieIsaacs** [comment]
for chrome this could help: https://github.com/janeczku/calibre-web/issues/896#issuecomment-488831045

**Comment by OzzieIsaacs** [comment]
for more I have to be back at my computer

**Comment by YesThatRancourt** [comment]
Hmm. I've made the change you suggested, that error disappeared from the console, but the problem still persists. New console output (in Chrome this time) attached below. The "Unexpected token <" errors in main.js and uploadprogress.js strike me as possibilities here, but I'm not sure why they'd suddenly stop parsing after the 6/31 update.

![cps_problem4](https://user-images.githubusercontent.com/15682575/62478478-3040f500-b779-11e9-808b-dbc1b5b7747d.jpg)

**Comment by OzzieIsaacs** [comment]
Okay, I have an idea about the content of the main.js and uplloadprogress.js:
Please reload the page with open developer console, go to the line where upload progress.js is loaded:
![grafik](https://user-images.githubusercontent.com/6438895/62479319-7b74fb00-b7ad-11e9-877f-7475c7f87da9.png)
Click on the line, click to "answer/resonse?". It takes a short time, and then the content of uplodprogress.js is shown. 
My bet: You don't see the content i see, but you see some raw html like:

```
<!DOCTYPE html>
<html class="http-error" lang="en">
  <head>
    <title>Calibre-Web | HTTP Error (Error 404)</title>
    <meta charset="utf-8">
```
If so, please post the error message here.

**Comment by OzzieIsaacs** [comment]
This is where the "<" is from... (my guess)
If so, please check the content of ...calibre-web/cps/static/js/uploadprogress.js. It should start with the text you see above (or in the same file on the github repro.

**Comment by YesThatRancourt** [comment]
Yes indeed, I see HTML and not Javascript when I click on uploadprogress.js in the console, as you suspected! Opening the file itself in a text editor, I see the correct Javascript code as you've quoted above.

Many, many thanks again for working through this with me. I really appreciate it.

![cps_problem5](https://user-images.githubusercontent.com/15682575/62480320-7c8e3400-b77d-11e9-9782-bb43ae390120.jpg)

**Comment by OzzieIsaacs** [comment]
I doublechecked it, on June 30th i did notchange anything regarding server and serving js files. The big change was introduced on July 15th. The file you are seeing is the main calibre-web html page.
Could you please check if only the two files main.js and uploadprogress.js are affected and no other js file or css file?
One thing you could try (I give it only a 30% chance) is installing a newer version of tornado or gevent:
`pip install --upgrade tornado --target vendor` (if you did the installation as in the readme described, please execute the command in the calibre-web main folder, where vendor is the subfolder)
or 
`pip install gevent --target vendor`
If only the 2 files (or maybe 3) are affected and all other files are working, than there has to be something in between. 
Are you sure there is no proxy, firewall or similar in between which is maybe changing files or file roues?

**Comment by OzzieIsaacs** [comment]
What do you get as result if you are executing the following command from the servers  commandline (e.g. a terminal or via ssh) itself:
`wget http://127.0.0.1:8083/static/js/uploadprogress.js`
and open the downloaded file afterwards. Is it the html content or the javascript?

**Comment by YesThatRancourt** [comment]
I think I've found, and solved, the problem! Looks like an update to Flask and Flask_Login fixed it. My apologies for the runaround; the symptoms were bizarre, and I wasn't really sure what I was seeing. Hope this helps anyone else who encounters the problem!

**Comment by OzzieIsaacs** [comment]
Perfect.
Thanks for the quick response

**Comment by Flo-63** [comment]
I updated to python3-flask to 0.12.1-1 and  python3-flask-login 0.4.0-1 on Debian 4.9.144-3.1 - does not resolve the error.
